### ISSUE TITLE
Is email up ?

### ISSUE THREAD

**Issue by amammad** [centreon/centreon#10051]
Hey dear centreon team, how are you today?
can I ask following email still working or not ?
`security@centreon.com`

**Comment by sc979** [comment]
Dear @amammad ,

This mail is working indeed.
In the following link you will find more details about our security policy  :
https://github.com/centreon/centreon/security/policy

Best regards,
sc979

**Comment by sc979** [comment]
Dear @amammad ,

I'm closing this issue and will wait for your email on security@centreon.com

Best regards,
sc979

**Comment by amammad** [comment]
Yah thanks for your quick pong.
can I ask you to check emails from Huntr.dev?

**Comment by sc979** [comment]
Dear @amammad ,

We did not get any mail from the website you refer to.

Github issues is not intended to discuss security related matters.
Kindly, send us a mail on security@centreon.com.

Best regards
sc979

**Comment by sc979** [comment]
Dear @amammad ,

I contacted huntr.dev and I am waiting for their email.
If you want to be kept updated, kindly, send us your email address using: security@centreon.com

Best regards,

sc979
