### ISSUE TITLE
Resource Status -> monitoring server incorect list

### ISSUE THREAD

**Issue by cedrobert** [centreon/centreon#10064]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

centreon-21.04.4-2.el7.centos.noarch
centreon-auto-discovery-server-21.04.1-2.el7.centos.noarch
centreon-base-config-centreon-engine-21.04.4-2.el7.centos.noarch
centreon-broker-21.04.2-3.el7.centos.x86_64
centreon-broker-cbd-21.04.2-3.el7.centos.x86_64
centreon-broker-cbmod-21.04.2-3.el7.centos.x86_64
centreon-broker-core-21.04.2-3.el7.centos.x86_64
centreon-broker-storage-21.04.2-3.el7.centos.x86_64
centreon-clib-21.04.2-1.el7.centos.x86_64
centreon-common-21.04.4-2.el7.centos.noarch
centreon-connector-21.04.2-4.el7.centos.x86_64
centreon-connector-perl-21.04.2-4.el7.centos.x86_64
centreon-connector-ssh-21.04.2-4.el7.centos.x86_64
centreon-database-21.04.4-2.el7.centos.noarch
centreon-engine-21.04.3-5.el7.centos.x86_64
centreon-engine-daemon-21.04.3-5.el7.centos.x86_64
centreon-engine-extcommands-21.04.3-5.el7.centos.x86_64
centreon-gorgone-21.04.1-1.el7.centos.noarch
centreon-gorgone-centreon-config-21.04.1-1.el7.centos.noarch
centreon-license-manager-21.04.0-1.el7.centos.noarch
centreon-license-manager-common-21.04.0-1.el7.centos.noarch
centreon-nrpe-daemon-2.15-4.el7.centos.x86_64
centreon-perl-libs-21.04.4-2.el7.centos.noarch
centreon-poller-centreon-engine-21.04.4-2.el7.centos.noarch
centreon-pp-manager-21.04.0-1.el7.centos.noarch
centreon-release-21.04-4.el7.centos.noarch
centreon-trap-21.04.4-2.el7.centos.noarch
centreon-web-21.04.4-2.el7.centos.noarch
centreon-widget-engine-status-21.04.0-1.el7.centos.noarch
centreon-widget-global-health-21.04.0-1.el7.centos.noarch
centreon-widget-graph-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-grid-map-21.04.0-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-host-monitoring-21.04.0-2.el7.centos.noarch
centreon-widget-httploader-21.04.0-3.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-21.04.0-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-21.04.0-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-service-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-tactical-overview-21.04.0-1.el7.centos.noarch

***Operating System***

*CentOS*
CentOS Linux release 7.9.2009 (Core)
***Browser used***

- [x ] Google Chrome
- [x ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

### Description

-- Describe the encountered issue --
In ressource status, the filter for "monitoring server" display an incorect list somme poller apears twice.
![image](https://user-images.githubusercontent.com/43059901/129334040-01c2217b-2753-43d4-81c9-e8f543eea92b.png)
  

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. I reached the ressource status View
3. Add criteria Monitoring Server 
4. display server list

### Describe the received result
Some server apears twice
### Describe the expected result
Have a corect server list

**Comment by cedrobert** [comment]
Hello,
Can I have some news, about this issue?

**Comment by cedrobert** [comment]
UP

**Comment by GuerchetM** [comment]
I have the same issue, in my case I see old and desactivate poller in the list

**Comment by cedrobert** [comment]
Hello @nmagniezCentreon,
How can I provide you the log securely?
I dont wan't to put them in public on github.

**Comment by nmagniezCentreon** [comment]
Hello cedrobert,

If the file is not so big, you can send it to me via email (nmagniez@centreon.com) otherwise, I let you choose file transfert tool of your choice.

**Comment by cedrobert** [comment]
Logs send by email.

**Comment by cedrobert** [comment]
Hi, have you got the mail?

**Comment by nmagniezCentreon** [comment]
Hi Cedric,

Yes, I received them thanks. I'll let you know soon about investigation status.

Best,
Nils

**Comment by cedrobert** [comment]
Can I have some news?

**Comment by adr-mo** [comment]
Hi @cedrobert,

This issue has been fixed on next versions of the 21.04.x. I can see that you're running the 21.04.4. You might need to upgrade your platform to the latest version (https://docs.centreon.com/21.04/en/releases/centreon-core.html#210410)

Regards
