### ISSUE TITLE
action_url don't have target _blank 

### ISSUE THREAD

**Issue by alexlansovich** [centreon/centreon#10060]
Centreon 21.04.4
(commit  c8ff73c129)

Monitoring -> Resources Status
Notes and Action url on hosts and services dont have target "_blank".
Deprecated interface has it.

**Comment by ponchoh** [comment]
👍  00102071

**Comment by nmagniezCentreon** [comment]
hello,
We've decided not to do it on purpose, this is not good practice and we prefere to let the user decide the way he/she wants to open a link (thanks to right click, middle click ctrl click)
