### ISSUE TITLE
Centreon Graphs to Mbps/Kbps Instead MBps/KBps

### ISSUE THREAD

**Issue by VidushaZ** [centreon/centreon#10092]
Hi,

Is it possible to get my graphs with Mbps/Kbps instead of MBps/KBps? 
In Output the plugin returns with Mbps/Gbps but when it goes to Graphs it gets converted to MB and KB. 

Command : 

/usr/lib/centreon/plugins/plugins.pl   --plugin network::cisco::standard::snmp::plugin    --mode=interfaces   --hostname=xxx    --snmp-version='3'   --snmp-username xxx --authpassphrase 'xxx'   --authprotocol SHA   --privpassphrase 'xxx'   --privprotocol AES --snmp-timeout='60'   --interface '462'   --nagvis-perfdata  --add-traffic --add-errors --add-cast --no-skipped-counters  --warning-in-traffic '80'     --critical-in-traffic '90'    --warning-out-traffic '80'     --critical-out-traffic '90'         --add-status

Output : 
OK: Interface 'Te2/8/5' Status : up (admin: up), Traffic In : 1.11Gb/s (11.14%), Traffic Out : 51.52Mb/s (0.52%), Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0), In Ucast : 100.00 %, In Bcast : 0.00 %, In Mcast : 0.00 %, Out Ucast : 99.93 %, Out Bcast : 0.02 %, Out Mcast : 0.05 % | 'in'=139301932.27;0:1000000000;0:1125000000;0;1250000000 'out'=6439817.89;0:1000000000;0:1125000000;0;1250000000 'packets_discard_in'=0.00%;;;0;100 'packets_error_in'=0.00%;;;0;100 'packets_discard_out'=0.00%;;;0;100 'packets_error_out'=0.00%;;;0;100 'packets_crc_in'=0.00%;;;0;100 'in-ucast'=100.00%;;;0;100 'in-bcast'=0.00%;;;0;100 'in-mcast'=0.00%;;;0;100 'out-ucast'=99.93%;;;0;100 'out-bcast'=0.02%;;;0;100 'out-mcast'=0.05%;;;0;100

Thanx!

**Comment by lpinsivy** [comment]
Using "Monitoring > Performance > Curves" menu you can edit curves and change unit

**Comment by VidushaZ** [comment]
@lpinsivy I can't see any option there. Am I missing something?

![image](https://user-images.githubusercontent.com/34154568/132675294-88b53c7d-0476-480d-a52b-05733ade146f.png)

**Comment by lpinsivy** [comment]
Sorry it was in "Monitoring > Performances > Templates > Traffic", you can change "Base" method from 1000 to 1024.

**Comment by VidushaZ** [comment]
@lpinsivy Thanx it's working fine without the --nagvis-perfdata option in the command. When using --nagvis-perfdata in the command it's not working. Anything to fix that thing?

**Comment by VidushaZ** [comment]
Found a way here #909
