### ISSUE TITLE
WebUI bugs in ressource status and help icons

### ISSUE THREAD

**Issue by Kiolul** [centreon/centreon#10096]
Hello,

On a new fresh installation of CentreOn in version 21.04 we encountered 2 WebUI "bugs" : 

- When we sort resources status by colums, we can't check several lines to acknowledge for example,
- When we mouse over the "?" in configurations pages, no popup are displayed.
We have no errors on logs (Apache or CentreOn).
These issues are not present in a 20.10 installation.
Thx for your help.

Installation informations : 

# rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
centreon-21.04.4-2.el7.centos.noarch
centreon-auto-discovery-server-21.04.1-2.el7.centos.noarch
centreon-base-config-centreon-engine-21.04.4-2.el7.centos.noarch
centreon-broker-21.04.2-3.el7.centos.x86_64
centreon-broker-cbd-21.04.2-3.el7.centos.x86_64
centreon-broker-cbmod-21.04.2-3.el7.centos.x86_64
centreon-broker-core-21.04.2-3.el7.centos.x86_64
centreon-broker-storage-21.04.2-3.el7.centos.x86_64
centreon-clib-21.04.2-1.el7.centos.x86_64
centreon-common-21.04.4-2.el7.centos.noarch
centreon-connector-21.04.2-4.el7.centos.x86_64
centreon-connector-perl-21.04.2-4.el7.centos.x86_64
centreon-connector-ssh-21.04.2-4.el7.centos.x86_64
centreon-database-21.04.4-2.el7.centos.noarch
centreon-engine-21.04.3-5.el7.centos.x86_64
centreon-engine-daemon-21.04.3-5.el7.centos.x86_64
centreon-engine-extcommands-21.04.3-5.el7.centos.x86_64
centreon-gorgone-21.04.1-1.el7.centos.noarch
centreon-gorgone-centreon-config-21.04.1-1.el7.centos.noarch
centreon-license-manager-21.04.0-1.el7.centos.noarch
centreon-license-manager-common-21.04.0-1.el7.centos.noarch
centreon-perl-libs-21.04.4-2.el7.centos.noarch
centreon-poller-centreon-engine-21.04.4-2.el7.centos.noarch
centreon-pp-manager-21.04.0-1.el7.centos.noarch
centreon-release-21.04-4.el7.centos.noarch
centreon-trap-21.04.4-2.el7.centos.noarch
centreon-web-21.04.4-2.el7.centos.noarch
centreon-widget-engine-status-21.04.0-1.el7.centos.noarch
centreon-widget-global-health-21.04.0-1.el7.centos.noarch
centreon-widget-graph-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-grid-map-21.04.0-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-host-monitoring-21.04.0-2.el7.centos.noarch
centreon-widget-httploader-21.04.0-3.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-21.04.0-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-21.04.0-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-service-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-tactical-overview-21.04.0-1.el7.centos.noarch

***Operating System***

CentOS Linux release 7.9.2009 (Core)

***Browser used***

- [x] Google Chrome
- [x] Microsoft Edge

**Comment by nmagniezCentreon** [comment]
Bonjour,
ces 2 problèmes ont été corrigés.
Nils
