### ISSUE TITLE
[bug 21.04] Ressources status : graphics display problem

### ISSUE THREAD

**Issue by ArnoMdlt** [centreon/centreon#10120]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

centreon-auto-discovery-server-21.04.1-2.el7.centos.noarch
centreon-awie-21.04.0-1.el7.centos.noarch
centreon-bam-server-21.04.0-1.el7.centos.noarch
centreon-base-config-centreon-engine-21.04.4-2.el7.centos.noarch
centreon-broker-21.04.2-3.el7.centos.x86_64
centreon-broker-cbd-21.04.2-3.el7.centos.x86_64
centreon-broker-cbmod-21.04.2-3.el7.centos.x86_64
centreon-broker-core-21.04.2-3.el7.centos.x86_64
centreon-broker-storage-21.04.2-3.el7.centos.x86_64
centreon-business-release-21.04-4.el7.centos.noarch
centreon-clib-21.04.2-1.el7.centos.x86_64
centreon-common-21.04.4-2.el7.centos.noarch
centreon-connector-21.04.2-4.el7.centos.x86_64
centreon-connector-perl-21.04.2-4.el7.centos.x86_64
centreon-connector-ssh-21.04.2-4.el7.centos.x86_64
centreon-dsm-client-21.04.0-1.el7.centos.noarch
centreon-dsm-server-21.04.0-1.el7.centos.noarch
centreon-engine-21.04.3-5.el7.centos.x86_64
centreon-engine-daemon-21.04.3-5.el7.centos.x86_64
centreon-engine-extcommands-21.04.3-5.el7.centos.x86_64
centreon-gorgone-21.04.1-1.el7.centos.noarch
centreon-gorgone-centreon-config-21.04.1-1.el7.centos.noarch
centreon-license-manager-21.04.0-1.el7.centos.noarch
centreon-license-manager-common-21.04.0-1.el7.centos.noarch
centreon-nrpe3-daemon-3.2.1-9.el7.centos.x86_64
centreon-nrpe3-debuginfo-3.2.1-9.el7.centos.x86_64
centreon-nrpe-daemon-2.15-4.el7.centos.x86_64
centreon-open-tickets-21.04.1-1.el7.centos.noarch
centreon-perl-libs-21.04.4-2.el7.centos.noarch
centreon-poller-centreon-engine-21.04.4-2.el7.centos.noarch
centreon-pp-manager-21.04.0-1.el7.centos.noarch
centreon-release-21.04-4.el7.centos.noarch
centreon-trap-21.04.4-2.el7.centos.noarch
centreon-web-21.04.4-2.el7.centos.noarch
centreon-widget-engine-status-21.04.0-1.el7.centos.noarch
centreon-widget-global-health-21.04.0-1.el7.centos.noarch
centreon-widget-graph-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-grid-map-21.04.0-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-host-monitoring-21.04.0-2.el7.centos.noarch
centreon-widget-httploader-21.04.0-3.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-21.04.0-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-21.04.0-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-service-monitoring-21.04.0-1.el7.centos.noarch
centreon-widget-tactical-overview-21.04.0-1.el7.centos.noarch

***Operating System***

CentOS7

***Browser used***

- [x] Google Chrome (the problem is not present with this browser it looks like)
- [x] Firefox

Version: --

Chrome : 93.0.4577.63
Firefox : 92.0 and 78.6.1 (bug on this two versions)

### Description

this problem is random but very recurrent : 

![image](https://user-images.githubusercontent.com/73098333/133226154-6e35cc45-56f3-406f-8605-edf841227789.png)

When you select a graph in the resource view, very often it is not displayed.

### Steps to Reproduce

1. Go in services ressources status.
2. Select valid's graphs multiple times until you see a not displayed graph in the portlet "GRAPH".

Thanks !

**Comment by MajorFault** [comment]
I have the same issue. It only happens with Firefox, Chrome is working fine.
Workaround to see the graph: Click on "Timeline" and then on "Graph" again.

**Comment by ArnoMdlt** [comment]
> 
> 
> I have the same issue. It only happens with Firefox, Chrome is working fine.
> Workaround to see the graph: Click on "Timeline" and then on "Graph" again.

yes I use this "technique" too, thanks for the feedback!

**Comment by MajorFault** [comment]
With Centreon 21.04.10 and Firefox 95.0.2 I don't have this problem anymore.
@ArnoMdlt Can you confirm it is solved for you too?

**Comment by ArnoMdlt** [comment]
Yes @MajorFault, seem's ok for me too with 21.04.10.

**Comment by nmagniezCentreon** [comment]
Indeed, we fixed the issue in 21.04.10 version. Sorry for not updating.
