### ISSUE TITLE
Amélioration : disposer de la même fonction que nagios avec le network outages

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1013]
---

Author Name: **Maxime Peccoux** (Maxime Peccoux)
Original Redmine Issue: 301, https://forge.centreon.com/issues/301

---

Bonjour,

Il serait vraiment intéressant d'implémenter la fonction de Nagios -> Network outages. Celà permet de rapidement voir les problèmes réseaux lorsque l'on a mis en place des relations parent-child

Merci

**Comment by julienmathis** [comment]
version 2.9.0
