### ISSUE TITLE
Acknowledgment button too small

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1016]
---

Author Name: **Emylou Mavic** (Emylou Mavic)
Original Redmine Issue: 3961, https://forge.centreon.com/issues/3961
Original Date: 2012-11-29

---

Hi, 

In a service page the Option table displays : 

Acknowledged	     No     	 => 

But the => is too small, and need to be quite precise while clicking. 

Is it possible to add a bigger icon ? 
Or having the "Acknowledged" be a link to acknowledge ? 

This would improve the Web UI usability for users who need to ack many times a day. 

Best regards,

**Comment by julienmathis** [comment]
deprecated
