### ISSUE TITLE
New features in load monitoring engine configuration from files

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1021]
---

Author Name: **Maximilien Bersoult** (Maximilien Bersoult)
Original Redmine Issue: 3564, https://forge.centreon.com/issues/3564
Original Date: 2012-08-20

---

Add the new features for loading configuration from files.
* New options from Nagios 3.2.x
* Centreon Connector for Centreon Engine 1.3.0

**Comment by julienmathis** [comment]
deprecated
