### ISSUE TITLE
[Command] - os-linux-snmp-traffic-name - don't querry with custom port

### ISSUE THREAD

**Issue by watchix** [centreon/centreon#10279]
Hi,

I've added on my host template the relation : "OS-linux-Traffic-Generic-Name-SNMP-custom"
This template is ok with my hosts who SNMP port is 161

But for others hosts with a custom port (not 161), the executed check command don't comport the `--snmp-port='xxx'` argument ...

NOK command : `/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname='my-host-with-customport.com' --snmp-version='2c' --snmp-community='public'  --interface='^.*$' --name --add-status --add-traffic --warning-in-traffic='80' --critical-in-traffic='90' --warning-out-traffic='80' --critical-out-traffic='90' '
`
OK command on the same host : `/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::stormshield::snmp::plugin --mode=memory --hostname='my-host-with-customport.com' --snmp-port='10160' --snmp-community='public' --snmp-version='2c'  --warning='80' --critical='90''`

I can't edit the `os-linux-snmp-traffic-name` check command to add `--snmp-port='$_HOSTSNMPPORT$'`

Regards,

**Comment by lpinsivy** [comment]
Hi,

The best wy is to duplicate command, modify it, then select duplicated command in OS-linux-Traffic-Generic-Name-SNMP-custom tempalte.
