### ISSUE TITLE
centreonLDAP.class.php error

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon#10318]
BUG REPORT INFORMATION

Version:

20.10.12

We have configure LDAP authentication for centreon but we are facing issue on LDAP user refresh

Error in /var/log/centreon/centAcl.log

[2021-10-18 17:23:02] According to DB another instance of centAcl.php is already running and I found 0 process...
Correcting the state in the DB, by setting the `running` value to 0 for id =  3
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /usr/share/centreon/www/class/centreonLDAP.class.php on line 482

I have checked also into centreon database on table cron_operations and centAcl.php still always a 1 on running column

any idea?

Thanks

**Comment by lpinsivy** [comment]
Hi @R00T88 you have a loop in your template (host or service).
You need to fix this to stop loop
