### ISSUE TITLE
UI not fully translated 

### ISSUE THREAD

**Issue by pdergane** [centreon/centreon#10375]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***
21.04.3

For the RPM based systems
```
$ rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
centreon-21.04.3-1.el8.noarch
centreon-auto-discovery-server-21.04.1-2.el8.noarch
centreon-base-config-centreon-engine-21.04.3-1.el8.noarch
centreon-broker-21.04.3-1.el8.x86_64
centreon-broker-cbd-21.04.3-1.el8.x86_64
centreon-broker-cbmod-21.04.3-1.el8.x86_64
centreon-broker-core-21.04.3-1.el8.x86_64
centreon-broker-storage-21.04.3-1.el8.x86_64
centreon-clib-21.04.2-1.el8.x86_64
centreon-common-21.04.3-1.el8.noarch
centreon-connector-21.04.2-4.el8.x86_64
centreon-connector-perl-21.04.2-4.el8.x86_64
centreon-connector-ssh-21.04.2-4.el8.x86_64
centreon-database-21.04.3-1.el8.noarch
centreon-engine-21.04.3-5.el8.x86_64
centreon-engine-daemon-21.04.3-5.el8.x86_64
centreon-engine-extcommands-21.04.3-5.el8.x86_64
centreon-gorgone-21.04.2-1.el8.noarch
centreon-gorgone-centreon-config-21.04.2-1.el8.noarch
centreon-license-manager-21.04.0-1.el8.noarch
centreon-license-manager-common-21.04.0-1.el8.noarch
centreon-perl-libs-21.04.3-1.el8.noarch
centreon-poller-centreon-engine-21.04.3-1.el8.noarch
centreon-pp-manager-21.04.0-1.el8.noarch
centreon-trap-21.04.3-1.el8.noarch
centreon-web-21.04.3-1.el8.noarch
centreon-widget-engine-status-21.04.0-1.el8.noarch
centreon-widget-global-health-21.04.0-1.el8.noarch
centreon-widget-graph-monitoring-21.04.0-1.el8.noarch
centreon-widget-grid-map-21.04.0-1.el8.noarch
centreon-widget-hostgroup-monitoring-21.04.0-1.el8.noarch
centreon-widget-host-monitoring-21.04.0-2.el8.noarch
centreon-widget-httploader-21.04.0-3.el8.noarch
centreon-widget-live-top10-cpu-usage-21.04.0-1.el8.noarch
centreon-widget-live-top10-memory-usage-21.04.0-1.el8.noarch
centreon-widget-servicegroup-monitoring-21.04.0-1.el8.noarch
centreon-widget-service-monitoring-21.04.0-1.el8.noarch
centreon-widget-tactical-overview-21.04.0-1.el8.noarch
mph-mcpsup-centreon-2.37.4_-1.el8.x86_64

```

***Operating System***

*Red Hat Enterprise Linux 8.4 *

***Browser used***

- [x] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

### Description
When deploying Centreon on Linux Server where locale is set to en_US.UTF-8, the change of language in UI to French for example is not taken account fully. A part of Centreon GUI continue to be displayed in english like menu for example.

### Steps to Reproduce

I deployed centreon 21.04.3 on linux server where default locale is set to US.
Then Using my webbrowser (chrome or firefox):
1 - I logged in Centreon,
2 - then I defined the language to use for my account (menu administration>parameters>My Account) 
3 - then I logged off
4-  then I  logged in centreon again to check the changes. 

The menu labels are still in english (not in french).

### Describe the received result
Menu is still displayed in english

### Describe the expected result
all Centreon GUI shall be in French, even if server LANG is set to en_US.UTF-8.

### Logs

No error observed in logs file

### Additional relevant information (e.g. frequency, ...)
To workaround the issue, I have installed the package glibc-langpack-fr and set the locale to fr_FR
{code}
sudo yum install -y glibc-langpack-fr
localectl set-locale LANG=fr_FR.utf8
{code}

**Comment by lpinsivy** [comment]
Hi @pdergane can you apply fix describe here https://github.com/centreon/centreon-documentation/pull/1145
