### ISSUE TITLE
[Centreon] Session Expired via external call to generateImage.php

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1037]
---

Author Name: **Denis Garandel** (Denis Garandel)
Original Redmine Issue: 6105, https://forge.centreon.com/issues/6105
Original Date: 2015-01-26

---

Hello,

Since upgrade from Centreon 2.5.1 to 2.5.4 a lot of sessions expire when external http call the module "generateImage.php"

IE of external http call to Centreon:

http://centreon-master-host/centreon/include/views/graphs/generateGraphs/generateImage.php?username=external-user&akey=external-key&hostname=$name&service=$servicename

I find additional code on new /usr/local/centreon/www/include/views/graphs/generateGraphs/generateImage.php

$mySessionId = isset($_GET['session_id']) ? $_GET['session_id'] : '' ;
$pearDB->query("DELETE FROM session WHERE session_id = '".$pearDB->escape($mySessionId)."'");

But the mySessionId is not the "external-user" but MY user session.
It's not the "external-user" who are killed but my real session

PS: I don't know if there is same additional code on other external modules.
And not tested with Centreon 2.5.2 and 2.5.3
And I have my own script to kill the "external-user" on crontab

Regards.

**Comment by leoncx** [comment]
Duplicate #728
