### ISSUE TITLE
Widget service monitoring 21.10

### ISSUE THREAD

**Issue by jeremyit** [centreon/centreon#10397]
Widget service monitoring does not display icon in 21.10 version. Ok in 21.04. passive_check.png and chart.png not refer to /centreon/img/icons/
Error :"not allowed to display". I've compared with 21.04, path to png are false.

**Comment by lpinsivy** [comment]
Will be fixed by https://github.com/centreon/centreon-widget-service-monitoring/pull/181

**Comment by lpinsivy** [comment]
@jeremyit try to apply this patch: https://github.com/centreon/centreon-widget-service-monitoring/commit/03febcf5c5866b8a17fe68fbc5848877ab098061
