### ISSUE TITLE
No icons on 21.10

### ISSUE THREAD

**Issue by waaalex** [centreon/centreon#10398]
Hello,
Updated from 20.10 to 21.10.
Minor issue with GUI.
As you can see, there's no icons on first page Home  >  Custom Views
![image](https://user-images.githubusercontent.com/33757865/140728815-447ca78b-e84f-4bc8-8fc9-42b7bbbf5bdb.png)

Thanks for feedback ;)
Alex.

**Comment by jeremyit** [comment]
I think you have this problem only on service widget like me : https://github.com/centreon/centreon/issues/10397#issue-1046002908

Downgrade your service monitoring widget to 21.04 and icons come back

**Comment by waaalex** [comment]
Thank you @jeremyit 
I close this case.
