### ISSUE TITLE
Images dead links on custom views 

### ISSUE THREAD

**Issue by Midorip** [centreon/centreon#10429]
[root@CESWWW ~]# rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
centreon-auto-discovery-server-21.10.1-1.el7.centos.noarch
centreon-base-config-centreon-engine-21.10.0-2.el7.centos.noarch
centreon-broker-21.10.0-2.el7.x86_64
centreon-broker-cbd-21.10.0-2.el7.x86_64
centreon-broker-cbmod-21.10.0-2.el7.x86_64
centreon-broker-core-21.10.0-2.el7.x86_64
centreon-broker-storage-21.10.0-2.el7.x86_64
centreon-clib-21.10.0-2.el7.x86_64
centreon-common-21.10.0-2.el7.centos.noarch
centreon-connector-21.10.0-2.el7.x86_64
centreon-connector-perl-21.10.0-2.el7.x86_64
centreon-connector-ssh-21.10.0-2.el7.x86_64
centreon-engine-21.10.0-2.el7.x86_64
centreon-engine-daemon-21.10.0-2.el7.x86_64
centreon-engine-extcommands-21.10.0-2.el7.x86_64
centreon-gorgone-21.10.0-3.el7.centos.noarch
centreon-gorgone-centreon-config-21.10.0-3.el7.centos.noarch
centreon-license-manager-21.10.0-1.el7.centos.noarch
centreon-license-manager-common-21.10.0-1.el7.centos.noarch
centreon-perl-libs-21.10.0-2.el7.centos.noarch
centreon-poller-centreon-engine-21.10.0-2.el7.centos.noarch
centreon-pp-manager-21.10.0-2.el7.centos.noarch
centreon-release-21.10-4.el7.centos.noarch
centreon-trap-21.10.0-2.el7.centos.noarch
centreon-web-21.10.0-2.el7.centos.noarch
centreon-widget-engine-status-21.10.0-2.el7.centos.noarch
centreon-widget-global-health-21.10.0-2.el7.centos.noarch
centreon-widget-graph-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-grid-map-21.10.0-2.el7.centos.noarch
centreon-widget-host-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-hostgroup-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-httploader-21.10.0-2.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-21.10.0-2.el7.centos.noarch
centreon-widget-live-top10-memory-usage-21.10.0-2.el7.centos.noarch
centreon-widget-service-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-servicegroup-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-tactical-overview-21.10.0-2.el7.centos.noarch

***Operating System***

CentOS Linux release 7.9.2009 (Core)

***Browser used***

- [ x] Google Chrome
- [x ] Firefox

Version: --

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. I reached the Custom View
3. I see dead link images instead of notification images for exemple 

### Additional relevant information (e.g. frequency, ...)
It seems that the images path are wrong, a / is missing 
when i clicked on the dead link => /centreon/widgets/service-monitoring/centreonimg/icons/notifications_off.png
It seems that a / is missing between centreon & img 
![image](https://user-images.githubusercontent.com/7789954/143017766-b0a0cde5-6f67-4c27-84ce-728f81652685.png)

**Comment by Blubmann1337** [comment]
Could confirm the same problem. 

centreon-21.10.1-1.el7.centos.noarch
centreon-auto-discovery-server-21.10.1-1.el7.centos.noarch
centreon-base-config-centreon-engine-21.10.1-1.el7.centos.noarch
centreon-broker-21.10.0-6.el7.x86_64
centreon-broker-cbd-21.10.0-6.el7.x86_64
centreon-broker-cbmod-21.10.0-6.el7.x86_64
centreon-broker-core-21.10.0-6.el7.x86_64
centreon-broker-storage-21.10.0-6.el7.x86_64
centreon-clib-21.10.0-6.el7.x86_64
centreon-common-21.10.1-1.el7.centos.noarch
centreon-connector-21.10.0-6.el7.x86_64
centreon-connector-perl-21.10.0-6.el7.x86_64
centreon-connector-ssh-21.10.0-6.el7.x86_64
centreon-database-21.10.1-1.el7.centos.noarch
centreon-engine-21.10.0-6.el7.x86_64
centreon-engine-daemon-21.10.0-6.el7.x86_64
centreon-engine-extcommands-21.10.0-6.el7.x86_64
centreon-gorgone-21.10.0-3.el7.centos.noarch
centreon-gorgone-centreon-config-21.10.0-3.el7.centos.noarch
centreon-license-manager-21.10.0-1.el7.centos.noarch
centreon-license-manager-common-21.10.0-1.el7.centos.noarch
centreon-perl-libs-21.10.1-1.el7.centos.noarch
centreon-poller-centreon-engine-21.10.1-1.el7.centos.noarch
centreon-pp-manager-21.10.0-2.el7.centos.noarch
centreon-release-21.10-4.el7.centos.noarch
centreon-trap-21.10.1-1.el7.centos.noarch
centreon-web-21.10.1-1.el7.centos.noarch
centreon-widget-engine-status-21.10.0-2.el7.centos.noarch
centreon-widget-global-health-21.10.0-2.el7.centos.noarch
centreon-widget-graph-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-grid-map-21.10.0-2.el7.centos.noarch
centreon-widget-hostgroup-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-host-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-httploader-21.10.0-2.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-21.10.0-2.el7.centos.noarch
centreon-widget-live-top10-memory-usage-21.10.0-2.el7.centos.noarch
centreon-widget-servicegroup-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-service-monitoring-21.10.0-2.el7.centos.noarch
centreon-widget-tactical-overview-21.10.0-2.el7.centos.noarch

CentOS Linux release 7.6.1810 (Core)

**Comment by lpinsivy** [comment]
A new version of service-monitoring widget was released to fix this issue.
PR here: https://github.com/centreon/centreon-widget-service-monitoring/pull/181
