### ISSUE TITLE
[21.10] Open ID with Azure AD error unable get token Introspection : Page not found

### ISSUE THREAD

**Issue by prohand** [centreon/centreon#10433]
Hello,

I followed this documentation:
https://docs.centreon.com/current/fr/connect/openid.html
And I indicated the requested information as put in Azure AD:

![image](https://user-images.githubusercontent.com/20227162/143249239-b95e9a81-7d79-45d4-a228-04d28a6cd603.png)

But I end up with the following error message in debug mode:

`[OpenId] [Error] Unable to get Token Introspection Information: RestNotFoundException, message: Page not found`

In addition, it is indicated here that there is no "introspection" url:

https://stackoverflow.com/questions/43378748/does-azure-active-directory-have-an-oauth-openid-connect-token-introspection-end

Have you tested on your side?

Do you have a solution ?

Thank you

**Comment by lpinsivy** [comment]
Hi @prohand can you try to remove /introspection from your OIDC definition?

**Comment by prohand** [comment]
Hello,

Same problem.

Thank you

**Comment by prohand** [comment]
I use centreon 21.10.1

With debug mode:

If I don't put the / introspect, when I click on the button "Connect with openid" nothing happens and nothing in the logs

On the other hand, when I put the / introspect I am redirected to the Microsoft page which asks me for my credentials.
Once logged in, I am redirected to the centreon login page with the following message in login.log:

`[OpenId] [Error] Unable to get Token Introspection Information: RestNotFoundException, message: Page not found`

Thank you

**Comment by alexandre30290** [comment]
Hi !

Please help us to solve this problem.
This functionnality is really important for our company et we're blocked with this bug...

Someone have solution to solve it please ??

Thanks a lot ;)

**Comment by alexandre30290** [comment]
Hello everyone,

nobody have a solution to solve it ?

Thanks

**Comment by websylv** [comment]
Same issue for me

**Comment by joschi99** [comment]
Are there any news about this issue?

**Comment by alexandre30290** [comment]
Solved for me with upgrade to 21.10
Config with azure ad correct

**Comment by prohand** [comment]
> Solved for me with upgrade to 21.10 Config with azure ad correct

Can you post you're config please ?
My config not working :(
Thank you

**Comment by alexandre30290** [comment]
No problem
Please find my conf here.

![openid-connect-config-centreon](https://user-images.githubusercontent.com/68156048/166559973-d3ee7ed8-9e65-4c0d-98fa-446508b09a4c.JPG)

This is my configuration on centreon
- You can replace "id_annuaire" by your tenant id

Then, please find my conf in azure "register apps"
![config-azure-1](https://user-images.githubusercontent.com/68156048/166560226-6a4d03ff-84a5-4a17-b5d3-5b3c9c8c0f25.JPG)
![config-azure-2](https://user-images.githubusercontent.com/68156048/166560472-7d42f8b4-40d4-456d-b414-74a5b8cb3144.JPG)
![config-azure-3](https://user-images.githubusercontent.com/68156048/166560483-328e36d6-a833-489a-86a7-c03cc26e695f.JPG)


If you need more information, I can give you a short movie to show all details of configuration !
Good Luck, I spent so more time to config this system

**Comment by prohand** [comment]
Hello,
It's ok for me
I close the ticket

Thank you
