### ISSUE TITLE
Lissage des graphiques

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1043]
---

Author Name: **ROBIN matthieu** (ROBIN matthieu)
Original Redmine Issue: 4516, https://forge.centreon.com/issues/4516
Original Date: 2013-06-03

---

Bonjour,

Est possible de moins lisser les graphiques? Par exemple, les graphiques de PRTG sont lissés à partir d'un mois. Sur Centreon, cette période se réduit à 10/15 jours.
Je sais que cela implique de grand changement dans la mise en place des graphs, mais cela serait utile pour nos ingénieur réseau.

Merci :-)

**Comment by julienmathis** [comment]
Will be done in Centreon Web 2.8.
