### ISSUE TITLE
Monitoring Resources Status hostgroup filter not filtering

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#10450]
Hi there,

Since I have upgraded from 21.04.4 to 21.04.8 the resources status monitoring is not able to filter by hostgroup.
The frontend sends the correct filtered request but the backend answers by ignoring this filter

Also the check button responsable for forcing recheck resource does'nt seem to take effect

**Comment by zep-jonas** [comment]
We also have this problem in 21.04.8

**Comment by nmagniezCentreon** [comment]
Hello,
Indeed, there was a bug. It is now fixed and will be available in the next 21.04 version (21.04.10).
Best
