### ISSUE TITLE
Centreon 21.04.8, 21.04.9 - links from top counters are reffering to deprecated pages and not ressource page

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#10460]
Since 21.04.8 the links from TOP hosts/services are referring to the deprecated sites and not to resource status

![image](https://user-images.githubusercontent.com/6400595/144571277-2a08317b-9d72-44b3-9d93-ad7ccd636571.png)

**Comment by octvcdrc** [comment]
Hi,

Had the same issue, turns out "Use deprecated pages" setting was activated in user profile. You might want to check that.

![firefox_DOr4XOKHio](https://user-images.githubusercontent.com/9086425/145486935-36a3ee83-646f-452b-9161-26abd15acf09.png)

**Comment by joschi99** [comment]
Yes, can confirm that is depending on the settings in the user profile. Thanks
