### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by alvarofvr** [centreon/centreon#10479]
![image](https://user-images.githubusercontent.com/13423318/145605447-ec0dc83e-fe97-4e49-93a9-10bcca89089c.png)

![image](https://user-images.githubusercontent.com/13423318/145605652-a5f6da6b-b56c-4af6-af33-b6fac36cf17a.png)

This broke all composer update using packagist.org. 

![image](https://user-images.githubusercontent.com/13423318/145605757-040f54e5-81e8-4e60-9170-f2a46bb1a23e.png)

**Comment by lpinsivy** [comment]
Hi @alvarofvr why do you try to build "dev-optimize-browser-configuration" branch?

**Comment by alvarofvr** [comment]
The dependency centreon/centreon not exist in my whole project (not even as a sub dependency), and I think the errors comes from online repo: https://repo-eu-uk-1.packagist.org during a composer phase. Today I tried to update composer 1 and rerun composer update and magically it worked. I don't know at this point if the problem was related (as described above) to the packagist, your repository or my local composer.
