### ISSUE TITLE
Vérification contraintes sqls

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1065]
---

Author Name: **Sligs S.** (Sligs S.)
Original Redmine Issue: 4287, https://forge.centreon.com/issues/4287
Original Date: 2013-03-07

---

Bonjour,
dans le même genre de ce qui a été fait pour vérifier la présence des indexes. Est-il possible de fournir un équivalent mais pour vérifier la présence de toutes les contraintes du type :

--
ALTER TABLE `acl_actions_rules`
  ADD CONSTRAINT `acl_actions_rules_ibfk_1` FOREIGN KEY (`acl_action_rule_id`) REFERENCES `acl_actions` (`acl_action_id`) ON DELETE CASCADE;

--
-- Contraintes pour la table `acl_group_contactgroups_relations`
--
ALTER TABLE `acl_group_contactgroups_relations`
  ADD CONSTRAINT `acl_group_contactgroups_relations_ibfk_1` FOREIGN KEY (`cg_cg_id`) REFERENCES `contactgroup` (`cg_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `acl_group_contactgroups_relations_ibfk_2` FOREIGN KEY (`acl_group_id`) REFERENCES `acl_groups` (`acl_group_id`) ON DELETE CASCADE;

Merci

**Comment by julienmathis** [comment]
A vérifier.
