### ISSUE TITLE
Acknowledge impossible since update from 19.04.3 to 19.10.23

### ISSUE THREAD

**Issue by mullergg** [centreon/centreon#10726]
Hello,
I've updated my production server from 19.04.3 to 19.10.23 and we cannot acknowledge service from the status details with mass selection.
It works from the service overview individually.

The only log I found is in the centcore.log;
This is the error when I sent the ack from the scrolling menu:
```
2022-02-15 14:35:57 - ERROR - The IP address of the poller  is incorrect:
2022-02-15 14:35:57 - ERROR - Ip address not defined for poller 0
```
And when I made the ack from the service overview:

```
2022-02-15 14:38:24 - INFO - External command : 10.248.241.14 (19) : "[1644935903] ACKNOWLEDGE_SVC_PROBLEM;LORDEM1P:/swing/acquisitionv3/drive-france-test;Passerelles;2;0;1;admin;Acknowledged by GMU
[1644935903] SCHEDULE_FORCED_SVC_CHECK;LORDEM1P:/swing/acquisitionv3/drive-france-test;Passerelles;1644935903
```
I've checked all ip configuration and file, everything seems ok and was working before the update.

**Comment by mullergg** [comment]
Ok I found the problem.
The issue is my host name, centreon don't like the special characters ( / : - ) when I removed it I can acnowledge without any problem.
But it was working fine in 19.04.3.
I also test it on my development environment in version 21.04.7 it works fine with the special characters. 
So I think the issue is with the version 19.10.23.

**Comment by ponchoh** [comment]
Hello @mullergg happy to see that you have found a solution. Just as a friendly reminder about Centreon's [lifecycle](https://docs.centreon.com/docs/releases/lifecycle#maintenance-table-for-earlier-products):

Product | Release | End of life with | State
-- | -- | -- | --
Centreon 21.04 | 04/2021 | Centreon 22.10 | Supported
Centreon 20.10 | 10/2020 | Centreon 22.04 | Supported
Centreon 20.04 | 04/2020 | Centreon 21.10 | No longer supported
Centreon 19.10 | 10/2019 | Centreon 21.04 | No longer supported
Centreon 19.04 | 04/2019 | Centreon 20.10 | No longer supported
Centreon 18.10 | 10/2018 | Centreon 20.04 | No longer supported

- First phase: Bugs of all severity levels (minor, major, critical, blocker) and security issues are fixed according to their priority.
- Second phase: Major, critical bugs and blockers, or security issues are fixed according to their priority.
- Third phase: Blockers or security issues are fixed according to their priority.

**Comment by mullergg** [comment]
I found the cause **not** a solution.
I know that !
I'm working on a rebuild of our configuration so I have a little delay on the update.
For now I need to work with the 19.10.
