### ISSUE TITLE
[source upgrade] check_pear.php wrong prerequistes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1076]
---

Author Name: **Simon Bomm** (Simon Bomm)
Original Redmine Issue: 5959, https://forge.centreon.com/issues/5959
Original Date: 2014-11-13

---

Hi, 

Centreon 2.5.3
RHEL 5
pear 1.4.9 and HTML_QuickForm_advmultiselect 1.1.0

After an upgrade to 2.5.3 from sources, was unable to save some forms (in Centreon-BI module e.g). 

That's probably because the libinstall/check_pear.php needs an update. Couldn't really figure out how it is challenging version of installed pear package then let you find a way to force the upgrade of pear to 1.7.2 and HTML_QuickForm_advmultiselect to 1.5.1 .

Thanks !

**Comment by julienmathis** [comment]
Can you validate this Bomm's ticket ? :)

**Comment by Dacchi** [comment]
Hello,

Since Centreon 2.6.0, Quickform is package within Centreon so you no longer need PEAR for this package.
