### ISSUE TITLE
 ERROR - https://CENTRAL-IP:443: {"message":"No parent platform was found for : 'poller'@'poller-IP'"}

### ISSUE THREAD

**Issue by sako-cmr** [centreon/centreon#10920]

**Comment by Alexm974** [comment]
Hey Sako
Did you find the reason of that error?
I have the exact same one
Thanks

**Comment by sako-cmr** [comment]
hello Alex, sorry for the delay

the central and the poller are not in the same LAN, I had a problem with the gateway between the central and the poller. in the command : "/usr/share/centreon/bin/registerServerTopology.sh -u admin -t poller -h Central-IP -n poller "
I put the ip address of the gateway instead of Central-IP, which did not work, hence the error message.
So instead of executing the command in the poller, I executed it in the central server replacing Central-IP by its LAN address.

**Comment by XixisDev** [comment]
Hello, sorry for up, but i have the same problem.

My Centreon central is on a AWS server, and i try to install a poller on my local network and connect them.
When i send " /usr/share/centreon/bin/registerServerTopology.sh -u admin -t poller -h IP -n centreon-poller1" after entering password, i have the message "ERROR - http://IP:80: {"message":"No parent platform was found for: 'centreon-poller1'@'192.168.0.37'"}

So I tried to do what Sako said by entering in my central, the same command but replacing the public IP of the central by its private ip, but I got the following message: "ERROR - http://172.26.4.121:80: {"message":"Same address and parent_address for platform: 'centreon-poller1'@'172.26.4.121'"}"

Someone have a solution?

Thanks

**Comment by sakscams** [comment]
Hello,
you have to create a template file by specifying these elements in it :
              - API_USERNAME                      centreon-admin-user-name
              - API_TARGET_PASSWORD        password
              - CURRENT_NODE_TYPE           poller
              - TARGET_NODE_ADDRESS      (PARENT NODE ADDRESS)  -- > local IP of Central Server
              - CURRENT_NODE_NAME         poller-name
              - CURRENT_NODE_ADDRESS    (CURRENT NODE IP OR FQDN) --> public IP / IP of poller
then, you do : 
/usr/share/centreon/bin/registerServerTopology.sh --template "path to template file" 
you may need to add the --insecure option for self-signed certificates

**Comment by mqssi** [comment]
Hello, 
I'm having the exact same error message after following the Centos7 doc for Centreon 21.10.
sako-cmr suggestion did not work. Connectivity between Central and poller is operational.
