### ISSUE TITLE
detach causes servicegroups.cfg corruption

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1095]
---

Author Name: **Peeters Jan** (Peeters Jan)
Original Redmine Issue: 3485, https://forge.centreon.com/issues/3485
Original Date: 2012-07-31

---

If you detach a service check (let's say bound to say 100 servers; all in a certain hostgroup and other services linked to the host group) on 1 server , the check gets written x (in this case 99) times for all the servers that weren't detached (so 99 x 99) in servicegroups.cfg

Nagios load goes above 90% and checks will fail.

**Comment by julienmathis** [comment]
Sorry, I can't reproduice this problem.
