### ISSUE TITLE
Using Avaya IP Office MIB on centreon

### ISSUE THREAD

**Issue by uc33260** [centreon/centreon#10983]
Hi team,

I'm a voip engineer, and looking to understand how can i use MIB provided by a voip constructor (Avaya) for a specific product (IP office).

I can only monitor basic services (disk, memory, cpu, uptime, network bandwith usage, ping, swap).

My goal is to monitor the services running on the IPBX. many services are running under Apache-tomcat. 

Other things to monitor, is for example, licenses usage, alarms sip, etc.

It will be great to work together (voip skills in my side / monitoring skills in you side) and we can develop a new plugin "Avaya IP office" and share it with all the Centreon community.

I'm available to work on that, I have already a homelab running (Centreon + Avaya IP office).

PS: Find attached below on a comment, the Avaya IP office MIBs

Thank you

Issam BATTI

issam_batti@hotmail.fr

Best regards

**Comment by uc33260** [comment]
[avaya_ipoffice_snmp_mibs.zip](https://github.com/centreon/centreon/files/8495544/avaya_ipoffice_snmp_mibs.zip)

**Comment by Sims24** [comment]
Hello @uc33260 

Please open this here https://github.com/centreon/centreon-plugins 

We will see how we can mutually help.

**Comment by uc33260** [comment]
Hello @Sims24 

Done.

**Comment by uc33260** [comment]
Issue opened on: https://github.com/centreon/centreon-plugins/issues/3598
