### ISSUE TITLE
Changer type de colonne

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1106]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 6194, https://forge.centreon.com/issues/6194
Original Date: 2015-03-11

---

Les tables on_demand_macro_host et on_demand_macro_service ont comme type varchar(255) pour les colonnes svc_macro_value et host_macro_value.

Il serait bon de changer ce type en text car toutes les macros de plus de 255 caractères sont tronquées

**Comment by julienmathis** [comment]
Matthieu, 

Que fait on pour ce sujet ? Broker en engine gère bien cela ?

**Comment by ganoze** [comment]
Les tables on_demand_macro_* font partie de la base *centreon*. Elles ne sont donc pas utilisées par Broker ou Engine. Le changement peut donc être implémenté sans impact de mon côté.

**Comment by julienmathis** [comment]
Oui mais si nous autorisons cela, nous allons générer des macro de cette taille. Cela aura des impacts sur Broker et Engine :)
Donc ?

**Comment by ganoze** [comment]
Après une analyse rapide du code il ne semble pas y avoir de limite à la taille des macros gérées par Engine et Broker. On peut donc implémenter ce changement sans problèmes majeurs.
