### ISSUE TITLE
Per host/service check timeout

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#111]
---

Author Name: **Matthieu Kermagoret** (Matthieu Kermagoret)
Original Redmine Issue: 6192, https://forge.centreon.com/issues/6192
Original Date: 2015-03-10

---

In Centreon Engine 2 it is possible to configure a per host/service check timeout. The property is called *check_timeout* and is expressed in seconds.

**Comment by julienmathis** [comment]
implemented
