### ISSUE TITLE
Package not signed

### ISSUE THREAD

**Issue by andreluizpr** [centreon/centreon#11119]
Hello,

My environment:
CentOS Linux release 7.9.2009 (Core)
Centreon 21.04.14
commit  [1b93e8f660]

I'm getting this error when updating a package using yum update command:

Package perl-Libssh-Session-0.9-1.el7.x86_64.rpm is not signed

This package is in the centreon-stable repository

I'm not comfortable bypassing the signature verification to apply the above package and with that I can't update my environment.

Is it possible to release a properly signed package? Or can I fearlessly upgrade by disabling signature verification?

Thanks

André

**Comment by Nohzoh** [comment]
Hello,

The RPM has been signed.
Sorry for the inconvenience caused.
