### ISSUE TITLE
[PLUGIN PACKS] Some centreon-plugins don't plugin packaged

### ISSUE THREAD

**Issue by Gregesp** [centreon/centreon#11140]
Hello,

I could see, we have a little part of plugins who don't have their Plugin Packs and documentation associated.

Maybe it's normal (outdated or others), or not, just a forgot 🙂

The list :
**Apcupsd** https://github.com/centreon/centreon-plugins/tree/master/apps/apcupsd/local
**Checkmyws** https://github.com/centreon/centreon-plugins/tree/master/apps/checkmyws
**Arcserve UDP Job Status** https://github.com/centreon/centreon-plugins/tree/master/apps/backup/arcserve/udp/mssql/mode
**NetApp Snapcenter** https://github.com/centreon/centreon-plugins/tree/master/apps/backup/netapp/snapcenter/restapi
**Citrix** https://github.com/centreon/centreon-plugins/tree/master/apps/citrix/local
**Interactive Intelligence Interaction Gateway** https://github.com/centreon/centreon-plugins/tree/master/apps/inin/ig/snmp
**Interactive Intelligence Media Server** https://github.com/centreon/centreon-plugins/tree/master/apps/inin/mediaserver/snmp
**Jive ETL Jobs** https://github.com/centreon/centreon-plugins/tree/master/apps/jive/sql/mode
**Apache Jmeter** https://github.com/centreon/centreon-plugins/tree/master/apps/jmeter
**Kingdee EAS Application & DB Server Status** https://github.com/centreon/centreon-plugins/tree/master/apps/kingdee/eas
**IBM Lotus Mail Server** https://github.com/centreon/centreon-plugins/tree/master/apps/lotus/snmp
**ActiveDirectory WSMan** https://github.com/centreon/centreon-plugins/tree/master/apps/microsoft/activedirectory/
**IIS WSMan** https://github.com/centreon/centreon-plugins/tree/master/apps/microsoft/iis/wsman
**Loggly** https://github.com/centreon/centreon-plugins/tree/master/apps/monitoring/loggly/restapi
**Quanta.io application probes** https://github.com/centreon/centreon-plugins/tree/master/apps/monitoring/quanta/restapi
**PineApp SecureMail** https://github.com/centreon/centreon-plugins/tree/master/apps/pineapp/securemail/snmp
**RRDCached** https://github.com/centreon/centreon-plugins/tree/master/apps/rrdcached
**Sahi Pro scenario** https://github.com/centreon/centreon-plugins/tree/master/apps/sahipro/restapi
**Toshiba Storemate** https://github.com/centreon/centreon-plugins/tree/master/apps/toshiba/storemate/sql/mode
**oVirt** https://github.com/centreon/centreon-plugins/tree/master/apps/virtualization/ovirt
**Cisco Meeting place** https://github.com/centreon/centreon-plugins/tree/master/apps/voip/cisco/meetingplace
**Zoom** https://github.com/centreon/centreon-plugins/tree/master/apps/zoom/restapi
**Nginx Ingress Controller metrics through Prometheus server** https://github.com/centreon/centreon-plugins/tree/master/cloud/prometheus/direct/nginxingresscontroller
**Safenet HSM with ProtectToolkit** https://github.com/centreon/centreon-plugins/tree/master/hardware/devices/safenet/hsm/protecttoolkit
**AppeartTV** https://github.com/centreon/centreon-plugins/tree/master/hardware/devices/video/appeartv/snmp
**TemPerHum Sensors** https://github.com/centreon/centreon-plugins/tree/master/hardware/sensors/temperhum/local
**Avaya Communication Manager** https://github.com/centreon/centreon-plugins/tree/master/hardware/telephony/avaya/cm/snmp
**Alcatel DSL ISAM Family** https://github.com/centreon/centreon-plugins/tree/master/network/alcatel/isam/snmp
**Alcatel 1830 Photonic Service Switch** https://github.com/centreon/centreon-plugins/tree/master/network/alcatel/pss/1830/snmp
**Cambium ePMP equipments** https://github.com/centreon/centreon-plugins/tree/master/network/cambium/epmp/snmp
**Evertz Audio Embedder Card** https://github.com/centreon/centreon-plugins/tree/master/network/evertz/AEA47721/snmp
**Evertz Reclocking Distribution Amplifier Card** https://github.com/centreon/centreon-plugins/tree/master/network/evertz/DA6HDL7700/snmp
**HP Moonshot Switch Module for HP Moonshot chassis** https://github.com/centreon/centreon-plugins/tree/master/network/hp/moonshot/snmp
**Libraesva appliance** https://github.com/centreon/centreon-plugins/tree/master/network/libraesva/snmp
**Netgear Smart Switches** https://github.com/centreon/centreon-plugins/tree/master/network/netgear/sseries/snmp

Regards,

**Comment by garnier-quentin** [comment]
Please ask it here: https://github.com/centreon/centreon-plugins ;)

**Comment by Gregesp** [comment]
Hello,

No problem i close and move this issue.

Regards,
