### ISSUE TITLE
Gestion import des dépendances de services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1114]
---

Author Name: **Pascal Legrand** (Pascal Legrand)
Original Redmine Issue: 5489, https://forge.centreon.com/issues/5489
Original Date: 2014-04-23
Original Assignee: Julien Mathis

---

Bonjour,

Serait il possible d'avoir un champs permettant de définir le nom de la dépendance au moment de l'import via un fichier cfg, pour ne pas avoir a repasser sur toutes les dépendances pour les renommer et avoi quelque chose de plus parlant que "dependencies date minutes seconde" aprés l'import de masse.

Exemple de config qui pourrait être importé :
define servicedependency{
	dependency_name(description)    "Nom de ma dépendance"
        host_name			"Un serveur"
	service_description		"Un service  ou Une liste de services"
	dependent_host_name		"Un serveur"
	dependent_service_description	"Un service ou Une liste de services"
	inherits_parent			1
	execution_failure_criteria	w,u,c
	notification_failure_criteria	w,u,c
}

**Comment by julienmathis** [comment]
Désolé ce moteur va être déprécié sous peu.
