### ISSUE TITLE
Centreon 22.04 chmod(): Operation not permitted

### ISSUE THREAD

**Issue by prohand** [centreon/centreon#11155]
Hello,

I have upgrade my poller version 21.10.6 to 22.04 (Redhat) and i have this warning after regenerate configuration file : 

![image](https://user-images.githubusercontent.com/20227162/169984992-7389a320-8350-4bb7-b415-8a982663a372.png)

Do you have a solution ?

Thank you

**Comment by ERFPP** [comment]
I have the same problem after update 21.10.6 -> 22.04 Centos7

**Comment by ng-pe** [comment]
Same problem on fresh install... (AlmaLinux release 8.6 (Sky Tiger))

**Comment by barte91** [comment]
I resolve with grant this permission

` chown apache:centreon-engine /etc/centreon-engine/*.cfg`
`chown apache:centreon-broker /etc/centreon-broker/*.json`

**Comment by prohand** [comment]
> I resolve with grant this permission on Central Server
> 
> ` chown apache:centreon-engine /etc/centreon-engine/*.cfg` `chown apache:centreon-broker /etc/centreon-broker/*.json`

Hello,

Thank you, my problem is solved

**Comment by Raeanath-OC** [comment]
Hello,
It works for me too thank you @barte91 [barte91](https://github.com/barte91) !

**Comment by BlogofraisFR** [comment]
Hello,

it's ok for me too

thx @barte91

**Comment by ERFPP** [comment]
Good for me too, thanks !
