### ISSUE TITLE
How to work with base OID used for multiple Traps

### ISSUE THREAD

**Issue by uc33260** [centreon/centreon#11229]
Hello,

I configured traps on my Centreon server to receive alarms from an Avaya PBX (IP Office R11.1).

The constructor Avaya use base OID for multiple traps, for example all alarms related to licensing issue are defined on this  OID:

.1.3.6.1.4.1.6889.2.2.1.2.0.46 = when the alarm is active
.1.3.6.1.4.1.6889.2.2.1.2.0.47 = when the alarm is cleared

And the constructor use specific codes to identify which type of license is identified for the trap:

![OID_Avaya](https://user-images.githubusercontent.com/83720227/173381991-f1159639-12f7-427e-b931-8cb3ee10670c.png)

I used iReasoning MIB browser to receive traps from the PBX, here is the result for all licensing traps (with same OID)

![MIB_Browser](https://user-images.githubusercontent.com/83720227/173382025-9de85695-faf4-437e-8fa2-aab561b69e22.png)

Question: How can I do to be able to create all my licensing services to monitor ?

Because right now, I cannot create two services with the same OID:

![trap_centreon](https://user-images.githubusercontent.com/83720227/173382065-e11944c1-48fb-40b4-975a-595408abf2fb.png)

Thank you for help

Regards

Avaya MIB:

[IPO-MIB.mib.txt](https://github.com/centreon/centreon/files/8892147/IPO-MIB.mib.txt)

**Comment by ponchoh** [comment]
https://thewatch.centreon.com/platform-7/how-to-work-with-base-oid-used-for-multiple-traps-729
