### ISSUE TITLE
Missin icons after upgrade from 21.10 to 22.04

### ISSUE THREAD

**Issue by foxpluto** [centreon/centreon#1136]
***Get your module version***

```
$ rpm -qa | grep centreon-widget-graph-monitoring
```
```
centreon-widget-graph-monitoring-22.10.0-9.el8.noarch
```

***Operating System***

*CentOS 8*

***Browser used***

- [X ] Google Chrome

Version: Version 111.0.5563.64 (Official Build) (arm64)

### Description
After following the upgrade guide to upgrade Centreon from 21.10 to 22.04 I have some missing icons in a lot of pages, like for instance the page of the Hosts:

<img width="303" alt="Screenshot 2023-03-22 at 09 24 40" src="https://user-images.githubusercontent.com/26223813/226866648-a1044bc5-ff31-4dd9-bd17-55c37aa8e108.png">

### Steps to Reproduce

Just watch a page like any host page

**Comment by tkmeisterooo** [comment]
Hi
Try to move Your icons to another directory using GUI 
![image](https://user-images.githubusercontent.com/51006991/229069009-9ad34d3e-c89a-425a-a036-f118bb364e9e.png)

**Comment by foxpluto** [comment]
I think there is a misunderstood, those are not my icons but standard icons from the standard Centreon Installation. 
The screenshot I post is from the Host configuration page.

**Comment by DonKiShoot** [comment]
Same issue after upgrade from 21.10 to 22.10, basic centreon icons are in error.

Sample link :

[http://@ip/centreon/](http://ip/centreon/)<span style='fill:var(--help-tool-tip-icon-fill-color); vertical-align: middle'><?xml version='1.0' encoding='UTF-8'?><svg height='18' width='18' xmlns='http://www.w3.org/2000/svg' height='18px' viewBox='0 0 24 24' width='18px'>  <path d='M0 0h24v24H0V0z' fill='none'></path>  <path d='M11 18h2v-2h-2v2zm1-16C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm0-14c-2.21 0-4 1.79-4 4h2c0-1.1.9-2 2-2s2 .9 2 2c0 2-3 1.75-3 5h2c0-2.25 3-2.5 3-5 0-2.21-1.79-4-4-4z'></path></svg></span>

![image](https://user-images.githubusercontent.com/35999798/234638955-d5807a11-d509-42fa-aa9f-828413ff611a.png)

**Comment by DonKiShoot** [comment]
> Same issue after upgrading from 21.10 to 22.10, basic centreon icons are in error.
> 
> Sample link :
> 
> `<img class="helpTooltip" name="check_command" src="<span style='fill:var(--help-tool-tip-icon-fill-color); vertical-align: middle'><?xml version='1.0' encoding='UTF-8'?><svg height='18' width='18' xmlns='http://www.w3.org/2000/svg' height='18px' viewBox='0 0 24 24' width='18px'> <path d='M0 0h24v24H0V0z' fill='none'></path> <path d='M11 18h2v-2h-2v2zm1-16C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm0-14c-2.21 0-4 1.79-4 4h2c0-1.1.9-2 2-2s2 .9 2 2c0 2-3 1.75-3 5h2c0-2.25 3-2.5 3-5 0-2.21-1.79-4-4-4z'></path></svg></span>" style="cursor: pointer;">`
> 
> ![image](https://user-images.githubusercontent.com/35999798/234638955-d5807a11-d509-42fa-aa9f-828413ff611a.png)

Solved by clearing browser cache

**Comment by foxpluto** [comment]
it's true, clearing the cache solve the issue.
