### ISSUE TITLE
LDAP users not bind to LDAP groups

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#114]
---

Author Name: **Kevin Printz** (Kevin Printz)
Original Redmine Issue: 5947, https://forge.centreon.com/issues/5947
Original Date: 2014-11-07

---

Hi,

I recently set up a LDAP authentication (with Autoimport) in my Centreon server. Users are correctly imported with their informations (name, email, ...) in their first connection. I also see the LDAP groups in the ACL page.
But my LDAP users are not automatically bound to their ldap groups.

I have CES 3.0 and Centreon 2.5.0.

Here my LDAP centreon conf :
MariaDB [centreon]> select * from auth_ressource;
+-------+---------+----------------+---------+-----------+
| ar_id | ar_name | ar_description | ar_type | ar_enable |
+-------+---------+----------------+---------+-----------+
|     2 | LDAP    | LDAP           | ldap    | 1         |
+-------+---------+----------------+---------+-----------+
1 row in set (0.00 sec)

MariaDB [centreon]> select * from auth_ressource_host;
+--------------+-------------------+--------------+-----------+---------+---------+------------+
| ldap_host_id | auth_ressource_id | host_address | host_port | use_ssl | use_tls | host_order |
+--------------+-------------------+--------------+-----------+---------+---------+------------+
|           22 |                 2 | server       |       636 |       1 |       1 |          1 |
+--------------+-------------------+--------------+-----------+---------+---------+------------+
1 row in set (0.00 sec)

MariaDB [centreon]> select * from auth_ressource_info;
+-------+---------------------+---------------------------------------+
| ar_id | ari_name            | ari_value                             |
+-------+---------------------+---------------------------------------+
|     2 | alias               | uid                                   |
|     2 | bind_dn             |                                       |
|     2 | bind_pass           |                                       |
|     2 | group_base_search   | ou=Groups,dc=XXX                   |
|     2 | group_filter        | (&(objectClass=posixGroup))           |
|     2 | group_member        | memberUid                             |
|     2 | group_name          | cn                                    |
|     2 | ldap_auto_import    | 1                                     |
|     2 | ldap_contact_tmpl   | 20                                    |
|     2 | ldap_dns_use_domain |                                       |
|     2 | ldap_dns_use_ssl    | 0                                     |
|     2 | ldap_dns_use_tls    | 0                                     |
|     2 | ldap_search_limit   | 60                                    |
|     2 | ldap_search_timeout | 60                                    |
|     2 | ldap_srv_dns        | 0                                     |
|     2 | ldap_store_password | 0                                     |
|     2 | ldap_template       | 0                                     |
|     2 | protocol_version    | 3                                     |
|     2 | user_base_search    | ou=Users,dc=XXX                    |
|     2 | user_email          | mail                                  |
|     2 | user_filter         | (&(uid=%s)(objectClass=posixAccount)) |
|     2 | user_firstname      | sn                                    |
|     2 | user_group          |                                       |
|     2 | user_lastname       | sn                                    |
|     2 | user_name           | cn                                    |
|     2 | user_pager          |                                       |
+-------+---------------------+---------------------------------------+

And here the informations about my LDAP user dean :
MariaDB [centreon]> select contact_id, contact_name, contact_auth_type  from contact where contact_auth_type='ldap';
+------------+--------------+-------------------+
| contact_id | contact_name | contact_auth_type |
+------------+--------------+-------------------+
|         41 | dean         | ldap              |
+------------+--------------+-------------------+
1 row in set (0.00 sec)

MariaDB [centreon]> select * from contactgroup where cg_type='ldap';
+-------+---------------+---------------+------------+-------------+---------+--------------------------------------+-------+
| cg_id | cg_name       | cg_alias      | cg_comment | cg_activate | cg_type | cg_ldap_dn                           | ar_id |
+-------+---------------+---------------+------------+-------------+---------+--------------------------------------+-------+
|     9 | administrator | administrator | NULL       | 1           | ldap    | cn=administrator,ou=Groups,dc=XXX |     2 |
|    10 | FirstGroup    | FirstGroup    | NULL       | 1           | ldap    | cn=FirstGroup,ou=Groups,dc=XXX    |     2 |
|    11 | LDAPuser      | LDAPuser      | NULL       | 1           | ldap    | cn=LDAPuser,ou=Groups,dc=XXX      |     2 |
+-------+---------------+---------------+------------+-------------+---------+--------------------------------------+-------+
3 rows in set (0.00 sec)

MariaDB [centreon]> select * from contactgroup_contact_relation where contact_contact_id=41;
Empty set (0.00 sec)

**Comment by leoncx** [comment]
Hello,

The sync of contact/contactgroup relation from ldap is make by centAcl.php and they are a constant LDAP_UPDATE_PERIOD who define the interval for this sync. By default the interval is ! hour.
