### ISSUE TITLE
Notification Self Service

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1146]
---

Author Name: **Sligs S.** (Sligs S.)
Original Redmine Issue: 4304, https://forge.centreon.com/issues/4304
Original Date: 2013-03-13

---

Bonjour,
dans l'esprit des streams et alarmes de graylog2, est-il possible d'adopter un système de notification similaire sur l'interface.
Ce ne serait donc pas une notification gérée par le poller mais via un tool annexe ( ou pourquoi pas le broker )
le but étant de permettre à un utilisateur de s'inscrire lui même à une alarme, de lui permettre de choisir les notifications pertinentes pour lui, parmi tous les points de supervisions, et donc de se faire lui même et simplement sa supervision. 
Même si le service n'a pas de notification à la base.
Seul lui est notifié et il gère lui même tout ca. 

Le but étant de responsabiliser l'utilisateur et de lui permettre d'être acteur de la supervision de son périmètre

**Comment by lpinsivy** [comment]
duplication of #1292
