### ISSUE TITLE
Add fields "notes/notes url/image/map image" in more objects

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1172]
---

Author Name: **Romain Le Merlus** (Romain Le Merlus)
Original Redmine Issue: 1117, https://forge.centreon.com/issues/1117
Original Date: 2009-08-06

---

Those fields are only available for hosts by now.
It could be great if we can have them for services, host groups, services groups, meta.

Then, show the properties in the different page and not only in monitoring=>services

++

**Comment by julienmathis** [comment]
deprecated
