### ISSUE TITLE
Tactical Overview - choose if soft should be shown

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1181]
---

Author Name: **Vincent Varlet** (Vincent Varlet)
Original Redmine Issue: 4254, https://forge.centreon.com/issues/4254
Original Date: 2013-02-27

---

Hi,

since 2.3.9 (?), only hard states are shown in the tactical overview. Can we have an option to choose if soft should be shown and if so, add the state type and retry column ?

**Comment by julienmathis** [comment]
deprecated
