### ISSUE TITLE
Configure RRA storage

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1184]
---

Author Name: **tnttteam tntteam** (tnttteam tntteam)
Original Redmine Issue: 2261, https://forge.centreon.com/issues/2261
Original Date: 2011-04-08

---

Bonjour,

Points liés : http://forge.centreon.com/issues/2180 et http://forge.centreon.com/issues/2256

Dans l'idée ce serait de pouvoir configurer pour les graphs des services / hotes (dans un premier temps) puis aussi pour les graphs de nagios perfdata (dans un deuxième temps) différentes durées et précisions de rétention des données.

Par exemple, si je souhaite avoir des données exactes de mes services sur 1 mois, puis un archivage sur 1 an, et enfin des données historiques sur 10 ans. Je souhaite ne pas trop perdre de place donc je configure les intervales avec les précisions suivantes :
1 mois : 1 PDP pour 1 CDP = pas de consolidation
1 an : 10 PDP pour 1 CDP = average de 10 points pour 1 point.
10 ans : 100 PDP pour 1 CDP = average de 100 points pour 1 point.

Côté interface utilisateur ce serait genre (voir screenshot).

Côté code il faudrait se débrouiller pour faire correspondre les différents interva check des services (qui peuvent différer) avec les durées demandées par l'utilisateur.
Ex:
L'utilisateur demande les durées de rétention suivantes :
30 jours de rétention exacte
6 mois de rétention avec consolidation toutes les 2 heures
2 ans de rétention avec consolidation tous les 5 jours

Ca donne, pour un service qui a un check_interval de 5 min :
RRA:AVERAGE:0.5:1:8640 ( 30 j = 30 \* 24 \* 60 = 43200min, 43200 min / (5 min \* 1 point) = 8640 points
RRA:AVERAGE:0.5:24:2160 ( 2 h = 120 min, 120 min / 5 min = 24; 6 mois = 6 \* 30 \* 24 \* 60 = 259200 min, 259200 min / (5 min \* 24 points) = 2160 points )
RRA:AVERAGE:0.5:1440:146 ( 5 j = 5 \* 24 \* 60 = 7200 min, 7200 min / 5 min = 1440; 2 ans = 2 \* 365 \* 24 \* 60 = 1051200 min, 1051200 min / ( 5 min \* 1440 points) = 146 points )

Ca donne, pour un service qui a un check_interval de 10 min :
RRA:AVERAGE:0.5:1:4320 ( 30 j = 30 \* 24 \* 60 = 43200min, 43200 min / (10 min \* 1 point) = 4320 points
RRA:AVERAGE:0.5:24:1080 ( 2 h = 120 min, 120 min / 5 min = 24; 6 mois = 6 \* 30 \* 24 \* 60 = 259200 min, 259200 min / (10 min \* 24 points) = 1080 points )
RRA:AVERAGE:0.5:1440:73 ( 5 j = 5 \* 24 \* 60 = 7200 min, 7200 min / 5 min = 1440; 2 ans = 2 \* 365 \* 24 \* 60 = 1051200 min, 1051200 min / ( 10 min \* 1440 points) = 73 points )

**Comment by lpinsivy** [comment]
linked to #2125

**Comment by Moujimouja** [comment]
Let's admit that the default configuration that comes with Centreon is the good one.
