### ISSUE TITLE
ACL : host avec aucuns services non visible par des users non admin

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1229]
---

Author Name: **Mathieu GUMEZ** (Mathieu GUMEZ)
Original Redmine Issue: 4949, https://forge.centreon.com/issues/4949
Original Date: 2013-10-22

---

Bonjour,

Un problème rencontré qui je pense n'est pas un fonctionnement normal.
Lorsque je créé des ACL pour mes collaborateurs juste opérateurs ils n'ont pas la visualisation sur les hosts ne possédant pas de services associés (principalement du check host alive sur des routeurs clients).
Le log me remonte effectivement des warnings m'informant que 27 de mes hôtes n'ont pas de services associés mais c'est un fonctionnement normal.

Merci de résoudre ce problème qui me gêne énormément dans la mise en place de l'outil car mes clients finaux doivent voir ses informations qui leurs sont donc invisible.

Mathieu

**Comment by julienmathis** [comment]
implemented
