### ISSUE TITLE
massive change can not delete fields

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1231]
---

Author Name: **Thomas - aka Jogarem -** (Thomas - aka Jogarem -)
Original Redmine Issue: 1972, https://forge.centreon.com/issues/1972
Original Date: 2010-09-28

---

There should be an option (like a radio button) for deleting the content of a setting within hosts/services by using the massive change option.

Example:
- I have multiple services or hosts which have the same check interval.
- Now I decide to use a template for all these services where the check interval is set.
- Now I want to delete the check interval setting in all my services but this cannot be done by "Massive change"
- this is not needed for check interval only, the same is for all other settings like arguments etc etc.

Solution:
- Add radio button selection "Update options" ("replace this setting or not") to all other fields, too (you can replace and so delete 'Notification contacts' for example but not check interval, arguments, notification interval etc etc)

Regards
Thomas

**Comment by lpinsivy** [comment]
duplicate of #2285
