### ISSUE TITLE
Default installation files

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1254]
---

Author Name: **Louis Ferret** (Louis Ferret)
Original Redmine Issue: 6451, https://forge.centreon.com/issues/6451
Original Date: 2015-06-30

---

*It might be a fault of our own*, but it seems that the installation files are not deleted after the software installation. If i go to https://[Centreon_Server]/centreon/tpcmXD/setup.php, *then anyone can install Centreon all over again*.

**Comment by julienmathis** [comment]
This has been fixed in Centreon 2.7.0. Now update and install data are moved after the setup or update into installDir directory in root dir of Centreon. Directory are named by the version installad and the timestamp of the action.
