### ISSUE TITLE
Updating command fails if no graph template is selected

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1255]
---

Author Name: **Moritz Bunkus** (Moritz Bunkus)
Original Redmine Issue: 5992, https://forge.centreon.com/issues/5992
Original Date: 2014-11-27

---

openSUSE 13.1, MySQL 5.6.12
Centreon 2.5.3
Centreon Broker 2.6.3

This is a fresh installation of the aforementioned versions mostly
with default settings. The databases have just been set up via the
web-based setup wizard.

If I try to update an existing command and select NO graph template
then the command isn't updated. sql-error.log shows:

2014-11-14 16:34|0|0|DB Error: unknown error QUERY : UPDATE command SET command_name = 'check_centreon_cpu', command_line = '$/check_centreon_snmp_cpu -H $ -v $ -C $ -c $ -w $', enable_shell = '0', command_example = '!80!90', command_type = '2', command_comment = '', graph_id = '', connector_id = NULL WHERE command_id = '96'

If I connect to the »centreon« database and execute that command
manually then MySQL reports the following error:

ERROR 1366 (HY000): Incorrect integer value: '' for column 'graph_id' at row 1

In order to reproduce:

1. Install Centreon Broker 2.6.3 and Centreon 2.5.3 on a fresh system
   using mostly defaults for the answers

2. Run the web-based setup procedure and let it create the databases

3. Login, go to »configuration« ? »commands«, edit one of them

4. Select NO graph template in the drop-down box, hit save

5. Look into sql-error.log

**Comment by julienmathis** [comment]
I think that it's due to the strict mode of MySQL
