### ISSUE TITLE
View values of check command arguments inherited from service template

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1285]
---

Author Name: **Hugo Nieva** (Hugo Nieva)
Original Redmine Issue: 3647, https://forge.centreon.com/issues/3647
Original Date: 2012-09-07

---

Hi guys, in Centreon 2.3.8 I have a situation with values of service arguments , inherited from a template, that are not shown in Configuration menu. I'm following this steps:

1) Go to Configuration -> Commands -> Add -> I have been created the check command COM_iNET900_Remote-RSSI with 4 arguments (See command_definition.png)

2) Go to Configuration -> Services -> Templates -> Add -> I have been created the service template iNET900_REMOTE_RSSI configuring the command check to COM_iNET900_Remote-RSSI, made on setp 1, putting values on arguments and setting all parameters (See service_template.png)

3) Go to Configuration -> Services -> Add -> I have been created a new service using the service template iNET900_REMOTE_RSSI, made on step 2. In Relations I select a host, for example TEST_HOST, then Save.

4) Go to Monitoring -> Host -> click on TEST_HOST -> click on shortcut button "view status of all services on host" -> click on the service iNET900_REMOTE_RSSI -> click on shortcut button "configure service" -> and.... here is the problem: the values of the arguments are not shown, then the NOC operator don't know what are the values configured (See service.png)

It would be nice to see the inherited values ??of the check command arguments.

Best regards,
Hugo

**Comment by julienmathis** [comment]
implemented in 2.7.0 version
