### ISSUE TITLE
Pagination and search filter

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1314]
---

Author Name: **Quentin Garnier** (Quentin Garnier)
Original Redmine Issue: 4020, https://forge.centreon.com/issues/4020
Original Date: 2012-12-18
Original Assignee: Quentin Garnier

---

Hi,

We have the following problem on page 'Services by host group (configuration)', 'Host (Configuration)', 'Manage (Administration centstorage)':
- You go to page 10
- You search a service like 'ping' (you don't have enough 'ping' services to go to page 10)
- The result: nothing and you have or not pagination (it depends)

To patch, we have to clean pages and have less SQL requests. (and there is 'checkPagination.php' to use)

**Comment by adr-mo** [comment]
Hi,

Thanks for the feedback 💯 

This issue will be fixed in the **18.10.5 release**

Regards,
