### ISSUE TITLE
Services reported as disabled on the Tactical Overview page

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1328]
---

Author Name: **Sergiu Badan** (Sergiu Badan)
Original Redmine Issue: 3157, https://forge.centreon.com/issues/3157
Original Date: 2012-03-12
Original Assignee: Sylvestre Ho

---

Hi,
I have installed centreon on a CentOS 6 server, using this guide: http://en.doc.centreon.com/Setup:Centos/Fedora/RHEL
Software versions:
Centreon: 2.3.4
Nagios: 3.2.3
ndoutils: 1.4b9
Nagios-plugins: 1.4.15

The problem is that Centreon doesn't display all the services configured. The services that it doesn't display are marked as "Disabled" in the tactical overview page. When any of the "Disabled" services are in Warning or Critical state, they are shown as disabled under the Warning or Critical box respectively.

The setup is simple:
14 hosts in Windows-Servers host group. This host group has configured by 3 services-by-hostgroup services. All hosts configurations are the same except for the server name, alias and ip.
Processes related to nagios:
[root@nagios-01 ~]# ps aux | grep nagios | grep -v grep
nagios    1274  0.0  0.3  14888  5864 ?        SN   Mar08   0:06 /usr/bin/perl -w /usr/local/centreon/bin/centcore
nagios    1394  0.0  0.0   8164   592 ?        Ss   Mar08   0:00 /usr/local/nagios//bin/ndo2db -c /etc/ndo2db.cfg
nagios    3351  0.0  0.0   8164  1312 ?        S    09:00   0:00 /usr/local/nagios//bin/ndo2db -c /etc/ndo2db.cfg
nagios    3352  0.0  0.0   8296  1476 ?        S    09:00   0:01 /usr/local/nagios//bin/ndo2db -c /etc/ndo2db.cfg
nagios    3354  0.0  0.0  13448  1244 ?        Ssl  09:00   0:01 /usr/local/nagios/bin/nagios -d /usr/local/nagios/etc/nagios.cfg
nagios   14191  0.0  0.2  21688  4144 ?        S    02:00   0:10 /usr/bin/perl -w /usr/local/centreon/bin/centstorage

Please advice.
--
Sergiu BADAN.

**Comment by julienmathis** [comment]
deprecated
