### ISSUE TITLE
CES - check_nrpe

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#135]
---

Author Name: **Mathieu Chateau** (Mathieu Chateau)
Original Redmine Issue: 6122, https://forge.centreon.com/issues/6122
Original Date: 2015-02-01

---

Hello,

after installing CES standard, last version, check_nrpe is the only one in /usr/lib*64*/nagios/plugins
All others plugin are in /usr/lib/nagios/plugins

**Comment by julienmathis** [comment]
Please install Centreon plugins and Nagios plugins :)

yum install centreon-plugins nagios-plugins*
