### ISSUE TITLE
Data retention policy

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1351]
---

Author Name: **Olivier Ragain** (Olivier Ragain)
Original Redmine Issue: 3871, https://forge.centreon.com/issues/3871
Original Date: 2012-11-06

---

Hi,

I have been using centreon for a while now. In order to do some reporting I started monitoring lots of services and hosts. Some of these hosts are servers with CPU / Memory / Disk checks... and so on. Others are printers with Toner capacity, Page counters and the likes.

Now, since I had the printers statistics, I decided to do a little reporting and evolution over the time. And thus I want to see like the 3 last years of data. Which means keeping like 1000 days of data for all services and hosts. Which in turns means a huge number of lines in the data_bin table in centstorage. But I actually don't care to keep that many data sets for the servers. Having those over like 6 months is really enough.

What I would like to see, if possible is either of the following:
* A way to specify the data retention policy at host and service levels
* A way to specify a number of datasets to keep instead of a number of days. For example, keep 10 000 datasets for each services and hosts

Also, I monitor the state of the WiFi infrastructure through some pinging of a subset of devices. I don't really care about the ping information but really care about the status of the device (OK / Warning / Critical) which is lighter to store... So if possible, a way to not store the services / hosts raw information but only it's status updates.

Those modifications would be nice to have.

Regards

**Comment by julienmathis** [comment]
implemented cf https://www.centreon.com/en/products/centreon-business-intelligence/
