### ISSUE TITLE
[centreon] Expired downtime never purged

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#136]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 3229, https://forge.centreon.com/issues/3229
Original Date: 2012-04-10

---

Hello,

It seems nothing is configured to regularly purge the expired downtime.
We need to remove them by hand when we think about it. :)

Regards.

**Comment by ganoze** [comment]
This was implemented in an already released version of Centreon (likely Centreon 2.7).
