### ISSUE TITLE
the macro expression field only allows 256 characters

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1369]
---

Author Name: **Max Mongardini** (Max Mongardini)
Original Redmine Issue: 6354, https://forge.centreon.com/issues/6354
Original Date: 2015-04-21

---

When adding a new resource, the macro expression field only allows 256 characters.

Although 256 chars sounds like a lot, I found myself in a situation where I had to create a resource with plenty of key=values cookies to pass to a command and the string was truncated.

**Comment by ganoze** [comment]
There is no limit on resource size in Centreon Engine. Limitation comes from Centreon Web where the resource_line column of the cfg_resource table is a varchar(255).
