### ISSUE TITLE
Filter in services in not kept for pages

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1371]
---

Author Name: **Andres Gomez** (Andres Gomez)
Original Redmine Issue: 5912, https://forge.centreon.com/issues/5912
Original Date: 2014-10-27
Original Assignee: Maximilien Bersoult

---

The configuration > services has a filter option including the status (Enabled) services.
This option works fine once it is selected, but when using the pages (1 2 3 4) the status option is removed.

Let's suppose a configuration with enabled and disabled services:

1. Configuration
1. Services
1. Change Status to enable
1. Change page
1. The new page does show the disabled services. The status option was lost.

This problem appears on Centreon 2.3.3

**Comment by julienmathis** [comment]
Sorry, you have to click "search" in order to keep the search values in your session. It works for me :)
