### ISSUE TITLE
rework external commands handling

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1373]
---

Author Name: **Nikolaus Filus** (Nikolaus Filus)
Original Redmine Issue: 1242, https://forge.centreon.com/issues/1242
Original Date: 2009-09-30

---

External commands are defined in multiple places, so using and debugging them is not "optimal".
1. Merge, where possible:
** www/include/monitoring/external_cmd
** centreonExternalCommand.class.php
1. use merged version for consistency
1. optimize security by checking $_GET before passing to passthrough

**Comment by julienmathis** [comment]
will not be implemented
