### ISSUE TITLE
Graphing data on two axises

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1395]
---

Author Name: **Nicolas PONS** (Nicolas PONS)
Original Redmine Issue: 5615, https://forge.centreon.com/issues/5615
Original Date: 2014-06-13

---

Good morning, 

I have quickly checked and it seems this question may have not been raised already, if it was, please redirect me to the answer. 

For a running project I am graphing data which have two different scales (Wh / Amps)
I have a few hundred of Watt/Hours but a few Amps, 
therefore while graphing, I'd like both to appear on two separated axis. 
Would it be possible to bring up such functionality ? 

From my knowledge, RRD tool at least supports it ([--right-axis scale:shift] [--right-axis-label label]) 

Thanks

**Comment by Hellnino18** [comment]
Hello,

News about this feature plz ?
