### ISSUE TITLE
Copy Default Argument Example

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1405]
---

Author Name: **Anthony Cano** (Anthony Cano)
Original Redmine Issue: 2657, https://forge.centreon.com/issues/2657
Original Date: 2011-09-27
Original Assignee: Sylvestre Ho

---

In previous versions of Centreon we were able to copy the example arguments over to the actual arguments field in the "Add a Service" page.  Now you must re-type all the arguments in the respective fields.  Request is to re-add the ability to copy the example arguments over which is beneficial if your default examples are used and there are many arguments that need to be specified.

**Comment by julienmathis** [comment]
This features will be implemented with the new version of macro management.

**Comment by leoncx** [comment]
This feature has applied on macros, and we advise to use macros instead arguments in command configuration.
