### ISSUE TITLE
Manque des lignes dans le fichier /etc/sudoers.d/centreon pour reload le module CentreonTrapd

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1417]
---

Author Name: **Sébastien Boulianne** (Sébastien Boulianne)
Original Redmine Issue: 5734, https://forge.centreon.com/issues/5734
Original Date: 2014-08-11

---

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified

----

centpoller sudo: centreon : command not allowed ; TTY=unknown ; PWD=/var/spool/centreon ; USER=root ; COMMAND=/etc/init.d/centreontrapd reload

Je joins le .diff qui modifie le fichier.

**Comment by julienmathis** [comment]
Je crois que cela a été corrigé pour la 2.6.0
