### ISSUE TITLE
[Idea Box] - In hosts templates add groups

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1422]
---

Author Name: **Tonio Allamellou** (Tonio Allamellou)
Original Redmine Issue: 2961, https://forge.centreon.com/issues/2961
Original Date: 2012-01-11

---

Hi,
In host template setting up, add the possibility to put a hostgroup and/or host category. It will allow the users to have automaticaly, a host inheriting the template, added to a group and / or category. Same idea for the services template with service group. 
Regards,

**Comment by julienmathis** [comment]
already implemented
