### ISSUE TITLE
Limited Administrator

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1426]
---

Author Name: **jon rhodes** (jon rhodes)
Original Redmine Issue: 3079, https://forge.centreon.com/issues/3079
Original Date: 2012-02-14
Original Assignee: Sylvestre Ho

---

I would like to request a few new options for the ACLs in Centreon. 

We are currently testing deployment of Centreon across our sister companies (using a distributed architecture) and will have the Central poller located in our corporate office. 

Our CIO requests that the Administrators from each site manage only objects from their location. I'm assuming this would be possible with the creation of a "limited administrator" account in Centreon that could only be given access to a specific poller. 

*When I create a user account that only has "resource access" to their sites servers (but has access to all pages), they see only their servers under "Monitoring/Hosts" but can manage all servers under "Configuration-Hosts".

In addition, some of the managers want Read-Only access to all the configuration pages. Is there a way we can allow them to view the Configuration/Administration tabs but not be able to save anything?

**Comment by julienmathis** [comment]
cf organisation in the next 3.0 version
