### ISSUE TITLE
Event2vrule - Commentaire event calendaire sur graph rrdtool

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1442]
---

Author Name: **Thomas GUILLEMOT** (Thomas GUILLEMOT)
Original Redmine Issue: 5765, https://forge.centreon.com/issues/5765
Original Date: 2014-08-25

---

Bonjour,

event2vrule est un petit script permettant de rajouter un évènement calendaire avec commentaire sur un graph rrd.
Ces solutions sont très intéressantes afin d'améliorer la compréhension et la lecture des graphiques.
Par exemple lors d'évènements intentionnellement déclenchés ou même pour identifier plus facilement des changement en matchant des dates avec des fluctuations.
Lors de test de performance cela permet aussi de garder un historique et mesurer rapidement les améliorations.

Lorsque Centreon est ouvert en lecture pour d'autres équipes ou par des prestataires externe cela permet un transfert d'information plus aisé et éviter des questionnements/pertes de temps inutiles.

Voilà un exemple de ce que cela donne (fichier en PJ) : http://hpics.li/479c8ec

Afin de ne pas inonder tout les graphiques avec des informations inutiles il faudrait choisir sur lesquels ajouter les events.
Pourquoi pas retrouver ces mêmes évènements dans la dashbord sur laquelle il serait possible de les faire apparaitre sur l'échelle de temps déjà existante.

**Comment by julienmathis** [comment]
Won't be implemented. RRD is not the futur.
