### ISSUE TITLE
Mode debug pour Poller Status

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1443]
---

Author Name: **Nicolas COULIN** (Nicolas COULIN)
Original Redmine Issue: 2205, https://forge.centreon.com/issues/2205
Original Date: 2011-03-03

---

Bonjour,

Depuis la 2.1.11, le Poller Status me renvoi 2 pollers is not running. La page statusCounter.php qui gère cette afichage n'est pas simple à comprendre du fait qu'il y ait pas mal de calcul de fait.

Pouvez vous rajouter un mode debug afin de comprendre l'erreur retournée

SELECT UNIX_TIMESTAMP(status_update_time) AS last_update, is_currently_running , instance_name, nagios_instances.instance_id
FROM nagios_programstatus, nagios_instances
WHERE nagios_programstatus.instance_id = nagios_instances.instance_id AND nagios_instances.instance_name IN ($pollerList) ;

et surtout pour les 2 tests suivants :

if ($status != 2 && $ndo["is_currently_running"] == 0 && (time() - $ndo["last_update"] >= $timeUnit / 5)) {
if ($ndo["is_currently_running"] == 0 || (time() - $ndo["last_update"] >= $timeUnit / 2)) {

Merci !

**Comment by julienmathis** [comment]
Il n'y a plus de problème sur cet indicateur à présent. Je ferme la demande.
