### ISSUE TITLE
Incohérence entre la table host_service_relation du database Centreon2 et la console

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1472]
---

Author Name: **Pascal Legrand** (Pascal Legrand)
Original Redmine Issue: 5447, https://forge.centreon.com/issues/5447
Original Date: 2014-04-06
Original Assignee: Julien Mathis

---

Bonjour,
Les champs hostgroup_hg_id et servicegroup_sg_id ne sont pas utilisés par les vues hostgroup et servicegroup

Objet de la demande :
Permettre de rattacher les TS aux hôtes depuis les hostgroups ou les servicegroups

**Comment by julienmathis** [comment]
duplicate & deprecated
