### ISSUE TITLE
22.04.x - OpenID overrides groups and ACL configuration on user

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#1500]
- Centreon version 22.04.12 
- OpenID configured in mixed mode and "Auto import users" disabled
- Users assigned to a user group
- Users "not admin", but with ACL configured through assigned user group

If user login using OpenID the assigned user group will be removed and assigned the user group from OpenID configuration:
![image](https://github.com/centreon/centreon/assets/6400595/3d6752a0-f426-4eb5-a534-ee8fc409e313)

Also if the user have assigned a dedicated ACL this will be removed when user logs in using OpenID.

Problem:
- all assigend user groups will be substituted be the default user group configured on OpenID
- all assigned ACL rules are removed
- user can login using OpenID, but all rights ecc. are missing and user are not able to see objects or pages

**Comment by lpinsivy** [comment]
Fixed in Centreon Web 23.04.7:
https://docs.centreon.com/docs/releases/centreon-os/#23047
