### ISSUE TITLE
Blank Page after open check command

### ISSUE THREAD

**Issue by ptitpopey** [centreon/centreon#1501]
Hello,

I have recently upgrade centreon to 23.04 on Debian 11.

When I open Commands -> Check, all check command are listed, but when I want to edit check command, a blank page appear.

Do you know why ?

How I can debug it ?

List package installed :
ii  centreon                                                  23.04.0-bullseye                                                           all          Centreon is a network, system, applicative supervision and monitoring tool,
ii  centreon-auto-discovery-server                            23.04.0-1                                                                  amd64        This extension offers auto discovery on Centreon
ii  centreon-broker                                           23.04.0-1                                                                  amd64        Centreon Broker is a Centreon Engine/Nagios module that report events in
ii  centreon-broker-cbmod                                     23.04.0-1                                                                  amd64        This module can be loaded by Centreon Engine.
ii  centreon-broker-core                                      23.04.0-1                                                                  amd64        core holds Centreon Broker's default modules.
ii  centreon-broker-storage                                   23.04.0-1                                                                  amd64        Storage holds Centreon Broker's perfdata storage.
ii  centreon-central                                          23.04.0-bullseye                                                           all          The package contains base configuration for Centreon Engine and Centreon Broker.
ii  centreon-clib                                             23.04.0-1                                                                  amd64        Centreon Clib is a common library for all Centreon products
ii  centreon-common                                           23.04.0-bullseye                                                           all          Base package for all Centreon installations.
ii  centreon-connector                                        23.04.0-1                                                                  amd64        Centreon Connector provide a monitoring tools, compatible with
ii  centreon-connector-perl                                   23.04.0-1                                                                  amd64        Centreon Connector Perl provide embedded perl for Centreon Engine
ii  centreon-connector-ssh                                    23.04.0-1                                                                  amd64        Centreon Connector SSH provide persistent connection between checks.
ii  centreon-database                                         23.04.0-bullseye                                                           all          Install a database server optimized for use with Centreon.
ii  centreon-engine                                           23.04.0-1                                                                  amd64        Centreon Engine is a monitoring engine, compatible with Nagios
ii  centreon-engine-extcommands                               23.04.0-1                                                                  amd64        Centreon Engine External Commands allow to other applications to send
ii  centreon-gorgone                                          23.04.0-bullseye                                                           amd64        Centreon Gorgone.
ii  centreon-license-manager                                  23.04.0-bullseye                                                           amd64        This extension manage licenses of proprietary Centreon products.
ii  centreon-perl-libs                                        23.04.0-bullseye                                                           all          This packages contains Centreon Perl libraries.
ii  centreon-plugin-applications-databases-mysql              20230511-111529-bullseye                                                   all          centreon-plugin-Applications-Databases-Mysql
ii  centreon-plugin-applications-jvm-actuator                 20230511-111529-bullseye                                                   all          centreon-plugin-Applications-Jvm-Actuator
ii  centreon-plugin-applications-monitoring-centreon-central  20230511-111529-bullseye                                                   all          centreon-plugin-Applications-Monitoring-Centreon-Central
ii  centreon-plugin-applications-monitoring-centreon-database 20230511-111529-bullseye                                                   all          centreon-plugin-Applications-Monitoring-Centreon-Database
ii  centreon-plugin-applications-monitoring-centreon-poller   20230511-111529-bullseye                                                   all          centreon-plugin-Applications-Monitoring-Centreon-Poller
ii  centreon-plugin-applications-protocol-dns                 20230511-111529-bullseye                                                   all          centreon-plugin-Applications-Protocol-Dns
ii  centreon-plugin-applications-protocol-ftp                 20230511-111529-bullseye                                                   all          centreon-plugin-Applications-Protocol-Ftp
ii  centreon-plugin-applications-protocol-ldap                20230511-111529-bullseye                                                   all          centreon-plugin-Applications-Protocol-Ldap
ii  centreon-plugin-hardware-printers-generic-snmp            20230511-111529-bullseye                                                   all          centreon-plugin-Hardware-Printers-Generic-Snmp
ii  centreon-plugin-hardware-ups-standard-rfc1628-snmp        20230511-111529-bullseye                                                   all          centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp
ii  centreon-plugin-network-cisco-standard-snmp               20230511-111529-bullseye                                                   all          centreon-plugin-Network-Cisco-Standard-Snmp
ii  centreon-plugin-operatingsystems-linux-snmp               20230511-111529-bullseye                                                   all          centreon-plugin-Operatingsystems-Linux-Snmp
ii  centreon-plugin-operatingsystems-windows-snmp             20230511-111529-bullseye                                                   all          centreon-plugin-Operatingsystems-Windows-Snmp
ii  centreon-poller-centreon-engine                           23.04.0-bullseye                                                           amd64        This package add rights and default directories for a poller
ii  centreon-pp-manager                                       23.04.0-1                                                                  amd64        Install, update and manager your Plugin Packs with this Centreon extension.
ii  centreon-trap                                             23.04.0-bullseye                                                           all          This package contains Centreon Trap engine
ii  centreon-web                                              23.04.0-bullseye                                                           all          This package contains WebUI files.
ii  centreon-web-apache                                       23.04.0-bullseye                                                           all          Centreon is a network, system, applicative supervision and monitoring tool,
ii  centreon-web-common                                       23.04.0-bullseye                                                           all          Centreon installation entry point.
ii  centreon-widget-engine-status                             23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-global-health                             23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-graph-monitoring                          23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-grid-map                                  23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-host-monitoring                           23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-hostgroup-monitoring                      23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-httploader                                23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-live-top10-cpu-usage                      23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-live-top10-memory-usage                   23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-service-monitoring                        23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-servicegroup-monitoring                   23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-single-metric                             23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets
ii  centreon-widget-tactical-overview                         23.04.0-bullseye                                                           all          Add homepage with Centreon Widgets

**Comment by jeremyjaouen** [comment]
Hello, could you provide the content of the following files:
/var/log/php-fpm/centreon-error.log
/var/log/centreon/sql-error.log

the blank page are oftenly related to a PHP error so you should have some information into the centreon-error.log file

**Comment by ptitpopey** [comment]
No file /var/log/php-fpm/centreon-error.log

/var/log/centreon/sql-error.log
2023-05-17 11:13|0|0|SQLSTATE[42S02]: Base table or view not found: 1146 Table 'centreon.cron_operation' doesn't exist QUERY : SELECT id, running FROM cron_operation WHERE name LIKE 'centAcl.php'
2023-05-17 11:13|0|0|SQLSTATE[42S02]: Base table or view not found: 1146 Table 'centreon.options' doesn't exist QUERY : SELECT \\* FROM options WHERE key = 'debug_path'
2023-05-17 11:14|0|0|SQLSTATE[42S02]: Base table or view not found: 1146 Table 'centreon.cron_operation' doesn't exist QUERY : SELECT id, running FROM cron_operation WHERE name LIKE 'centAcl.php'
2023-05-17 11:14|0|0|SQLSTATE[42S02]: Base table or view not found: 1146 Table 'centreon.options' doesn't exist QUERY : SELECT \\* FROM options WHERE key = 'debug_path'

No file centreon-error.log found

**Comment by ptitpopey** [comment]
There is an another log file who can help me ?

**Comment by ptitpopey** [comment]
I find the problem on /var/log/apache2/error.log

[Mon May 22 17:18:52.976180 2023] [proxy_fcgi:error] [pid 5667] [client 192.168.14.135:57442] AH01071: Got error 'PHP message: PHP Warning:  opendir(/usr/lib64/nagios/plugins/): Failed to open directory: No such file or directory in /usr/share/centreon/www/include/configuration/configObject/command/DB-Func.php on line 304PHP message: PHP Fatal error:  Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/centreon/www/include/configuration/configObject/command/DB-Func.php:305\nStack trace:\n#0 /usr/share/centreon/www/include/configuration/configObject/command/DB-Func.php(305): readdir()\n#1 /usr/share/centreon/www/include/configuration/configObject/command/formCommand.php(59): return_plugin()\n#2 /usr/share/centreon/www/include/configuration/configObject/command/command.php(101): require_once('...')\n#3 /usr/share/centreon/www/main.get.php(271): include_once('...')\n#4 {main}\n  thrown in /usr/share/centreon/www/include/configuration/configObject/command/DB-Func.php on line 305', referer: http://172.20.100.60/centreon/main.get.php?p=60801&type=2

**Comment by ptitpopey** [comment]
Problem solved. Thank for your help
