### ISSUE TITLE
Disparition des hostgroups

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1502]
---

Author Name: **Nolwenn DUMONT** (Nolwenn DUMONT)
Original Redmine Issue: 3401, https://forge.centreon.com/issues/3401
Original Date: 2012-06-26

---

Bonjour,

Si je charge dans nagios->load un fichier de configuration contenant des hosts déjà existants dans Centreon, alors toutes leurs assignations de hostgroups disparaissent et aucunes ne leur est rajoutée. Et ce que le mode d'écriture soit en remplacement ou en incrément.

Exemple : 

Dans Centreon, il y a un host "serveur01 | description01 | 10.145.90.78 | parent01 | hostgroup01, hostgroup02, hostgroup03".

Je charge dans "Configuration->Nagios->Load : Manual Filling" une configuration qui contient :

define host {
	host_name serveur01
 address 10.145.90.78
 alias description01
 use generic-host
 parents parent01
 hostgroups hostgroup01, hostgroup04, hostgroup06
}

Je récupère le host sans aucun hostgroup : 
"serveur01 | description01 | 10.145.90.78 | parent01"

Version de Centreon : 2.3.4 et 2.3.5

Merci de votre aide.

**Comment by julienmathis** [comment]
cf https://github.com/centreon/nagiosToCentreon
