### ISSUE TITLE
Macros in notes url and action url in monitoring and service details page

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1509]
---

Author Name: **Tensibai - Bastien Jove** (Tensibai - Bastien Jove)
Original Redmine Issue: 2307, https://forge.centreon.com/issues/2307
Original Date: 2011-04-22
Original Assignee: Tensibai - Bastien Jove

---

Macros are not replaced except HOSTNAME and SERVICEDESC ones.

Patch done for 2.1, work in progress for 2.2

**Comment by lpinsivy** [comment]
linked to linked to #4277
