### ISSUE TITLE
/usr/lib/nagios/plugins/check_meta_service - metrics recovery by regexp is not working for Centreon Broker in check_meta_service.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1534]
---

Author Name: **vincent palluel** (vincent palluel)
Original Redmine Issue: 6078, https://forge.centreon.com/issues/6078
Original Date: 2015-01-09

---

metrics recovery by regexp is not working for Centreon Broker in check_meta_service.
Escaped simple quotes missing around the $metric_select var.

**Comment by julienmathis** [comment]
I don't understand... Sorry
