### ISSUE TITLE
Add substract operation to meta-service

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1543]
---

Author Name: **m m** (m m)
Original Redmine Issue: 3783, https://forge.centreon.com/issues/3783
Original Date: 2012-10-16

---

Hi, the operation of metaservices are interesting for sum, or average.
but the substract could be also interesting for exemple to In-Out check
Count number of files In, and Substract it to Number of Files Out.

Thanks

**Comment by julienmathis** [comment]
deprecated
