### ISSUE TITLE
Possibility to define period of chart in monitoring pop-in

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1550]
---

Author Name: **Romain Le Merlus** (Romain Le Merlus)
Original Redmine Issue: 444, https://forge.centreon.com/issues/444

---

Might it be possible to put a duration in RRD graph template ?

We can show for a kind of service/BA a pre defined duration (in monitoring overlay for example).

**Comment by Moujimouja** [comment]
Let's admit the default behavior is the good one.
