### ISSUE TITLE
formatage des dates

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1553]
---

Author Name: **Pascal Legrand** (Pascal Legrand)
Original Redmine Issue: 5450, https://forge.centreon.com/issues/5450
Original Date: 2014-04-06
Original Assignee: Julien Mathis

---

Objet de la demande :
Formater la date dans les vues "views" et "dashboard" en fonction de la langue sélectionnée pour l'utilisateur dans l'affichage des dates du filtre.

exemple une fois la date sélectionnée sur le calendrier :
en : 04/05/2014
fr : 05/04/2014

Typiquement de devrais pouvoir filtrer sur le 31/12/2014 si je suis en francais et le 12/31/2014 si je suis en anglais

**Comment by julienmathis** [comment]
Fixed in 2.8.0
