### ISSUE TITLE
Services - Inherit contacts from host not working for contacts

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1591]
---

Author Name: **vincent palluel** (vincent palluel)
Original Redmine Issue: 5976, https://forge.centreon.com/issues/5976
Original Date: 2014-11-19

---

Hi,

When i link a contact to a host in Host configuration and add some services (from templates) to this host with The option "Inherit contacts from host" checked it does not work.
When Generating Configuration Files and running monitoring engine debug from centreon it says :
Service 'xxxxx' on host 'xxxxx' has no default contacts or contactgroups defined!

No problem if i link a contact group to the host.

**Comment by ganoze** [comment]
The "Inherit contacts from host" issue comes from Centreon Engine's behavior that do not inherit host's contacts in services. This will be fixed in the next Centreon Engine release.
