### ISSUE TITLE
Graphs period vs. date picker

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1598]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 3566, https://forge.centreon.com/issues/3566
Original Date: 2012-08-20

---

Hi, 

There is a behaviour a little bit irritating in view > graphs. 

When you select a predefined Graph Period via the drop-down-list, and next want to define a more precise interval with the date pickers it doesn't work because you've to unselect the Graph period. 
And unselecting the Graph period flush dates and times previously selected !

Screenshots attached with steps, should be more comprehensive

pch

**Comment by julienmathis** [comment]
deprecated
