### ISSUE TITLE
Column not found: 1054 Unknown column 'topology_url_substitute'

### ISSUE THREAD

**Issue by philipraets** [centreon/centreon#1603]
# BUG REPORT INFORMATION

### Prerequisites

***Get your module version***
Centreon 23.04.2

***Operating System***
Debian 11

***Browser used***

- [ ] Google Chrome
- [X] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: latest

### Description
When trying to configure hosts, services, commands, users, ..., there is an PHP fatal error:

`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'topology_url_substitute' in 'field list' in /usr/share/centreon/www/class/centreonDBStatement.class.php:132\nStack trace:\n#0 /usr/share/centreon/www/class/centreonDBStatement.class.php(132): PDOStatement->execute()\n#1 /usr/share/centreon/www/main.get.php(130): CentreonDBStatement->execute()\n#2 /usr/share/centreon/www/main.get.php(142): {closure}()\n#3 {main}\n  thrown in /usr/share/centreon/www/class/centreonDBStatement.class.php on line 132'`

### Steps to Reproduce
1. Upgraded centreon 23.04.1 to 23.04.2
2. Log in into centreon
3. Navigate to settings, configuration pages

### Describe the received result

I get white pages instead of the correct pages

### Describe the expected result
See all the hosts, services, users, commands, settings, ...

### Logs
apache_error_log:

`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'topology_url_substitute' in 'field list' in /usr/share/centreon/www/class/centreonDBStatement.class.php:132\nStack trace:\n#0 /usr/share/centreon/www/class/centreonDBStatement.class.php(132): PDOStatement->execute()\n#1 /usr/share/centreon/www/main.get.php(130): CentreonDBStatement->execute()\n#2 /usr/share/centreon/www/main.get.php(142): {closure}()\n#3 {main}\n  thrown in /usr/share/centreon/www/class/centreonDBStatement.class.php on line 132'`

sql-error.log:
`2023-06-08 08:52|0|0|SQLSTATE[42S22]: Column not found: 1054 Unknown column 'topology_url_substitute' in 'field list' QUERY : SELECT topology_parent, topology_name, topology_id, topology_url, topology_page, topology_url_substitute
FROM topology
WHERE topology_page = :page, null`

I've encountered this on 2 separate centreon installations, after upgrading to 23.04.2 on debian 11.

How can we fix this?

**Comment by philipraets** [comment]
Found it,

I had to apply the following directly in mysql in the centreon database:

```
ALTER TABLE `topology` ADD COLUMN `topology_feature_flag` varchar(255) DEFAULT NULL AFTER `topology_OnClick`;
ALTER TABLE topology ADD topology_url_substitute VARCHAR(255) NULL AFTER topology_url_opt;
```

**Comment by ChenrySecmon** [comment]
Hello @philipraets 
Do you mind sharing how you got to that solution ?
It turns out I have the same error in sql-error.log

This is on centreon 23.04.1 and when upgading i get the same white page. Should I upgrade and reproduce your steps ?
It would be great if i could solve this issue.. thank you for your post !

**Comment by philipraets** [comment]
Hi,

I've searched the source code here for topology_url_substitute, and I've found the file centreon/www/install/sql/centreon/Update-DB-23.04.1.sql with the 2 statements.

I'm guessing that it didn't make it in the deb packages, and doesn't get applied when upgrading with apt.

I've applied them manually in mysql.

```
mysql -u root -p
use centreon;
ALTER TABLE `topology` ADD COLUMN `topology_feature_flag` varchar(255) DEFAULT NULL AFTER `topology_OnClick`;
ALTER TABLE topology ADD topology_url_substitute VARCHAR(255) NULL AFTER topology_url_opt;
```

**Comment by ptitpopey** [comment]
Same problem on Debian 11. I have apply the correction and everything works again

Correction : 
<code>
mysql -u root -p
use centreon;
ALTER TABLE `topology` ADD COLUMN `topology_feature_flag` varchar(255) DEFAULT NULL AFTER `topology_OnClick`;
ALTER TABLE topology ADD topology_url_substitute VARCHAR(255) NULL AFTER topology_url_opt;
</code>

Many thanks [philipraets](https://github.com/philipraets)
