### ISSUE TITLE
Graphs stuck at 6 month of history

### ISSUE THREAD

**Issue by SpecialOOps** [centreon/centreon#1605]
Hello !

I've been encountering a problem with datas in graphs.

I want to see on all my checks, 1 year of graph history.
My configuration is like this :
![image](https://github.com/centreon/centreon/assets/20866916/21042e6f-5560-41c7-bb84-2e6792b3ba33)

But my graphs look like this :
![image](https://github.com/centreon/centreon/assets/20866916/698d0a8c-2088-444a-9050-21ac420e3b9c)

It stops at 6 months...

Any idea on what could i change to make it work ?

Centreon Info : 
Version : Centreon 22.10.7
OS : CentOs 7

If any more info are needed, don't hesitate to ask.

**Comment by cgagnaire** [comment]
Hi,
RRDs are created with a fixed size based on the retention define at that time.
If you change the retention afterwards you'll need to recreate them.
You can use the rebuild feature brought by Broker for that, but you will want to do it gradually as it will load you database and your Central.
For that, you can go to the 'Administration  >  Parameters  >  Data' page, select the services and select the 'Rebuild RRD Database' action.

**Comment by SpecialOOps** [comment]
Hello !

Thanks for the reply, i'm seeing changes in the one's that i have rebuild.

But a quick question, i keep all my datas for a Year, so why doesn't it rebuild with the ''old'' data ?

Thanks anyways for the answer :)

**Comment by cgagnaire** [comment]
Hi,
Well if you have 1 year of data for a metric in the SQL database then you should see 1 year of data on the graph.
If not It may be because the metric has been created less than 1 year ago.
Also version 22.10.2 of Broker fixes things around rebuild so you may try it https://docs.centreon.com/docs/22.10/releases/centreon-os/#bug-fixes-10

**Comment by SpecialOOps** [comment]
Hello !

Just an update on this, the first rebuild wasn't really working and a second one made everything look goods !

Thanks again !
