### ISSUE TITLE
Remove the daemon_dumps_core option

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1627]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 6067, https://forge.centreon.com/issues/6067
Original Date: 2015-01-08

---

Hello,

I'm using Centreon 2.5.4 and Centreon ENGINE.

The debug process of generated files shows a message like this :
Warning daemon_dumps_core variable ignored

The daemon_dumps_core option is useless with Centreon ENGINE and this is why the message is shown.
Daemon dumps core option must be set in init script, and for this reason the daemon_core_option should be removed from centreon.

Best regards.

**Comment by julienmathis** [comment]
fixed in 2.6.x.

Thanks
