### ISSUE TITLE
check_load_average check incorrect

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1637]
---

Author Name: **Mathieu Chateau** (Mathieu Chateau)
Original Redmine Issue: 6121, https://forge.centreon.com/issues/6121
Original Date: 2015-02-01

---

When installing Centreon, for example CES in last version, some checks are predefined.

one of them is check_load_average.
The command is incorrect:
$USER1$/check_load $HOSTADDRESS$ -w $ARG1$ -c $ARG2$

this command doesn't accept host address, as it's not using a remote protocol.

Usage:
check_load [-r] -w WLOAD1,WLOAD5,WLOAD15 -c CLOAD1,CLOAD5,CLOAD15

fix proposal:
remove $HOSTADDRESS$ argument and rename it explaining its local only

**Comment by julienmathis** [comment]
Please open the ticket in the dedicated forge : https://github.com/centreon/centreon-plugins/issues/
