### ISSUE TITLE
Remove BA and meta-services virtual services generation

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1639]
---

Author Name: **Matthieu Kermagoret** (Matthieu Kermagoret)
Original Redmine Issue: 6214, https://forge.centreon.com/issues/6214
Original Date: 2015-03-23

---

Starting with Centreon Broker 3, BAs and meta-services will be directly computed and handled by the _bam_ module of Centreon Broker. It is therefore unnecessary to generate virtual services for Centreon Engine.

**Comment by lpinsivy** [comment]
I suppose it solved
