### ISSUE TITLE
Centreon 23.04.2 :  blank screen

### ISSUE THREAD

**Issue by doudz** [centreon/centreon#1644]
I'm running Centreon on Debian, after upgrading from 23.04.1 to 23.04.2 I get blank blank page on many screens

![image](https://github.com/centreon/centreon/assets/1262548/d39855f4-57fa-4d9a-85cd-144984688790)

![image](https://github.com/centreon/centreon/assets/1262548/f439c61a-de98-417a-8e49-86182625d0c0)

![image](https://github.com/centreon/centreon/assets/1262548/09a8a280-9edd-41eb-9f59-b5262877c5db)

I see a lot of error in javascript console

![image](https://github.com/centreon/centreon/assets/1262548/0b23067a-7fa8-4b5b-be2c-723443797cb8)

![image](https://github.com/centreon/centreon/assets/1262548/f774d57e-12b7-4469-9919-4ad739cc365a)

**Comment by ptitpopey** [comment]
Hi,

see logs file /var/log/apache2/error.log

**Comment by jasafel** [comment]
https://github.com/centreon/centreon/issues/1603

**Comment by doudz** [comment]
I confirm the following fix the problem https://github.com/centreon/centreon/issues/1603

Correction :

mysql -u root -p
use centreon;
ALTER TABLE topology ADD COLUMN topology_feature_flag varchar(255) DEFAULT NULL AFTER topology_OnClick;
ALTER TABLE topology ADD topology_url_substitute VARCHAR(255) NULL AFTER topology_url_opt;

Many thanks
