### ISSUE TITLE
Grouper des hôtes / services par regex (Group hosts/services with a regex)

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1655]
---

Author Name: **Bruno Legros** (Bruno Legros)
Original Redmine Issue: 2633, https://forge.centreon.com/issues/2633
Original Date: 2011-09-15
Original Assignee: Sylvestre Ho

---

Il serait utile dans beaucoup de cas de grouper automatiquement un hôte ou un service suivant son nom.

Par exemple, je créée un groupe d'hôtes "Backstores" avec la regex "srv???bkstore??"
Les serveurs "srv010bkstore01" et "srv010bkstore02" ferait alors automatiquement partie de ce groupe.

**Comment by lpinsivy** [comment]
linked to #2210
