### ISSUE TITLE
Error "About" page - Access not allowed

### ISSUE THREAD

**Issue by barte91** [centreon/centreon#1671]
***Get your module version***
Centreon 23.04.2

***Operating System***
AlmaLinux 9.2

***Browser used***
- [ ] Google Chrome
- [X ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

### Description
On the about page I see this error "You are not allowed to reach this page"

On javascript console I see this log:
Il foglio di stile https://192.168.102.110/centreon/include/common/javascript/jquery/plugins/select2/css/www/Themes/Generic-theme/Variables-css/variables.css non è stato caricato in quanto il suo tipo MIME, “text/html”, non corrisponde a “text/css”. [select2.css](https://192.168.102.110/centreon/include/common/javascript/jquery/plugins/select2/css/select2.css)
Il foglio di stile https://192.168.102.110/centreon/include/common/javascript/charts/www/Themes/Generic-theme/Variables-css/variables.css non è stato caricato in quanto il suo tipo MIME, “text/html”, non corrisponde a “text/css”.

Can anyone help me, please?

Kind Regards

Stefano

**Comment by Athar42** [comment]
I would just guess... this ?
https://github.com/centreon/centreon/issues/1517

**Comment by Athar42** [comment]
Update : seems to finally be fixed in 23.04.5
