### ISSUE TITLE
Add new filters for search box

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1679]
---

Author Name: **sygoletto -** (sygoletto -)
Original Redmine Issue: 1278, https://forge.centreon.com/issues/1278
Original Date: 2009-10-20

---

Search Box only filters for hosts or services. For full integration with some plugins (NagVis for exemple) it could be nice to add filters for hostgroups and servicegroups so they could be displayed directly from a search url
I already added this feature in 2.0.1 and will try to do it for 2.1.2 if needed

**Comment by lpinsivy** [comment]
Servicegroup filter is now available in "Status detials" page

Possibility tu add '&sg=<servicegroup_id>' in URL
