### ISSUE TITLE
Ability to Display Host Check PerfData

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1681]
---

Author Name: **Gavin Williams** (Gavin Williams)
Original Redmine Issue: 1465, https://forge.centreon.com/issues/1465
Original Date: 2010-01-14

---

It would be useful if Centreon could support the processing and display of 'Host check' performance data gathered.

**Comment by julienmathis** [comment]
No, it's not a good ideas. Use a ping service to do that.
