### ISSUE TITLE
trie par colonne dans la partie "Configuration"

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1684]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 1352, https://forge.centreon.com/issues/1352
Original Date: 2009-12-02

---

Serait il possible d'ajouter le tri par colonne dans la partie "Configuration" ?

C'est déjà le cas dans la partie "Monitoring" ou l'on peut trier par n'importe quelle colonne, mais pas dans la partie "Configuration"

Cordialement.

**Comment by lpinsivy** [comment]
The filters allows to select objects
