### ISSUE TITLE
Add downtimes time in reporting timeline

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1691]
---

Author Name: **nathanael bonin** (nathanael bonin)
Original Redmine Issue: 2990, https://forge.centreon.com/issues/2990
Original Date: 2012-01-23
Original Assignee: Sylvestre Ho

---

Bonjour,

Serait-il possible d'ajouter dans la popup dans le tableau de bord donnant un résumé des différentes temps OK, Warning, Critical, les temps des DOWNTIME. (cf mon fichier joint). On remarque que les 4min49s du downtime n'est pas répercuté sur la popup.

Je pense qu'il faudrait la rajouter.

Merci par avance.

**Comment by cgagnaire** [comment]
Done.
