### ISSUE TITLE
tp_id not defined when inserting initial timeperiods

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#17]
---

Author Name: **geert de pooter** (geert de pooter)
Original Redmine Issue: 6468, https://forge.centreon.com/issues/6468
Original Date: 2015-07-17

---

Dear,

I've just installed the latest CES version and found that I was unable to logon to the website.
During my search I noticed that the centreon.contacts table is empty.
When trying to insert the contact,host,service portion of insertBaseConf.sql I received this error:

Error Code: 1452. Cannot add or update a child row: a foreign key constraint fails (`centreon`.`contact`, CONSTRAINT `contact_ibfk_1` FOREIGN KEY (`timeperiod_tp_id`) REFERENCES `timeperiod` (`tp_id`) ON DELETE SET NULL)

Then I looked up the timeperiod table I saw that the tp_id was not 1,2,3,4 but 2,12,22,32
This is native to our Mysql-clusterconfiguration and can not be changed.

Therefor I think it should be best to define the tp_id.
insertCmd-Tps.sql:
INSERT INTO `timeperiod` VALUES (1, '24x7', '24_Hours_A_Day,_7_Days_A_Week', '00:00-24:00', '00:00-24:00', '00:00-24:00', '00:00-24:00', '00:00-24:00', '00:00-24:00', '00:00-24:00');
INSERT INTO `timeperiod` VALUES (2, 'none', 'No Time Is A Good Time', '', '', '', '', '', '', '');
INSERT INTO `timeperiod` VALUES (3, 'nonworkhours', 'Non-Work Hours', '00:00-24:00', '00:00-09:00,17:00-24:00', '00:00-09:00,17:00-24:00', '00:00-09:00,17:00-24:00', '00:00-09:00,17:00-24:00', '00:00-09:00,17:00-24:00', '00:00-24:00');
INSERT INTO `timeperiod` VALUES (4, 'workhours', 'Work hours', '', '09:00-17:00', '09:00-17:00', '09:00-17:00', '09:00-17:00', '09:00-17:00', '');

Kind Regards,
Geert

**Comment by ganoze** [comment]
This architecture is not described in the official documentation and we will not support it any time soon. The list of available architectures is available [here](https://documentation.centreon.com/docs/centreon/en/2.7.x/installation/architecture/index.html).
