### ISSUE TITLE
[Commands] Argument Example // Argument Descriptions

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1703]
---

Author Name: **Florian Asche** (Florian Asche)
Original Redmine Issue: 5369, https://forge.centreon.com/issues/5369
Original Date: 2014-03-15

---

Hello,

the "Argument Descriptions" has already a nice mapping function.
It would be cool if it you could also introduce this "Argument Example".
You could also combine both useful.

**Comment by julienmathis** [comment]
Already implemented
