### ISSUE TITLE
Graph Item Type: Stacked in addition to LINE1 or AREA

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1709]
---

Author Name: **michael joyner** (michael joyner)
Original Redmine Issue: 1233, https://forge.centreon.com/issues/1233
Original Date: 2009-09-27

---

We can easily extend the functionality of STACKED graphing
1) Have a drop box in Curve UI "LINE/AREA/STACKED" that will determine the curve type.
2) Have a "Ordinal" field in CURVES that will determine the order of the DS's.
3) In the genereateODSview just have graph based on the field type.

I made this modification in 2.0.1 and it was really quick and easy. It allowed me to make utilization graphs for various metrics. 

"BUSY:14%"....... AREA
"IDLE:86%"....... STACKED
"TOTAL:100%"..... LINE

**Comment by julienmathis** [comment]
will be integrated in another formula in Centreon Web 2.8.
