### ISSUE TITLE
Message d'information déroulant

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1742]
---

Author Name: **julien breton** (julien breton)
Original Redmine Issue: 3356, https://forge.centreon.com/issues/3356
Original Date: 2012-06-09

---

Bonjour,

Une demande d'amélioration : l'affichage d'un bandeau déroulant à coté du logo Centreon

Ça peut être pratique pour diffuser une information à tout les agents connecté au dashboard. Il faudrait que le message s'affiche sans que l'utilisateur ait besoin de se délogger / relogger

Merci

**Comment by julienmathis** [comment]
deprecated
