### ISSUE TITLE
password begin with '$'

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1753]
---

Author Name: **Actarus GoldoraQ** (Actarus GoldoraQ)
Original Redmine Issue: 6184, https://forge.centreon.com/issues/6184
Original Date: 2015-03-06

---

Hello,
If password begin with '$', it doesn't work because '"' is used in config file to enclose variable and the password is interpreted and try to substitute to a variable.
I must change '"' to simple quote to avoid interpretation and all works fine.

**Comment by leoncx** [comment]
Duplicate #3460

**Comment by leoncx** [comment]
This problem is fix on fresh install
