### ISSUE TITLE
Enable to link contact groups to access groups with DN provided by LDAP

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1780]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 6470, https://forge.centreon.com/issues/6470
Original Date: 2015-07-23

---

Hello,

I'm using Centreon 2.6.1 and I have a strange problem regarding ACL configuration and LDAP.

I want to link contacts groups and access groups with DN imported with LDAP imported users.

To reproduce the case, please follow these steps :
-Create a contact group named like a DN that will be imported ;
-Import users for DN needed ;
-In ACL, create an Access Group named like the DN concerned ;
-On this Access Group, add the standard contact group and the virtual contact group provided by LDAP (this contact group is name like LDAP-%CG%). Save the configuration.
At this step, the AG will show 2 relationships with contacts groups, but when I click on it, there is only one group linked. I'm not able to change this relationship, the change is not acknowledged.

To workaround this problem, I must rename the contact group name.

Best regards.

**Comment by julienmathis** [comment]
@leoncx : so ?

**Comment by julienmathis** [comment]
Documentation will be updated in order to help users to prevent bad behavior in this case. We cannot automaticaly manage this kind of case without problem. The best way to avoid problem when we have groups with the same name in LDAP and not in LDAP is to rename manually.
