### ISSUE TITLE
Accenting caractere in search

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1784]
---

Author Name: **Bastien MAREAU** (Bastien MAREAU)
Original Redmine Issue: 6133, https://forge.centreon.com/issues/6133
Original Date: 2015-02-09

---

Hi,

In "Monitoring - Services - All services" and "Monitoring - Hosts" research with accent does not work.

Exemple :
For a host "testé", if you search "testé" in the search bar, no host is found.
However, typing "teste", we find host "testé".

Regards

**Comment by julienmathis** [comment]
Which version of Centreon ?

**Comment by bsauveton** [comment]
Problem is due to encoding on centreon_storage.
If we use : SET NAMES 'utf8' on centreon_storage connector before the request, it works.
