### ISSUE TITLE
XML Files and CDATA

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#180]
---

Author Name: **Quentin Garnier** (Quentin Garnier)
Original Redmine Issue: 3967, https://forge.centreon.com/issues/3967
Original Date: 2012-11-30

---

Hi,

We shouldn't put CDATA everywhere. We should only put it on free text field. (example: broker XML Files)

**Comment by ganoze** [comment]
Many fields are dynamically generated. Therefore we do not want to avoid using CDATA.
