### ISSUE TITLE
Plage de maintenance sur groupe de service KO

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1818]
---

Author Name: **Mathieu HERRERO** (Mathieu HERRERO)
Original Redmine Issue: 6048, https://forge.centreon.com/issues/6048
Original Date: 2014-12-18

---

Bonjour,

Lorsque je mets en place une plage de maintenance récurrente associée à un groupe de service, elle n'est pas prise en compte.

La maintenance ne démarre jamais.

par contre si je mets cette plage de maintenance service par service c'et bon

Voici les versions utilisées :
Centreon 2.5.2
Centreon Engine 1.4.6

**Comment by julienmathis** [comment]
Je crois que cela a été corrigé pour la 2.6.0
