### ISSUE TITLE
Détail d'un service

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1829]
---

Author Name: **Nicolas VERNHES** (Nicolas VERNHES)
Original Redmine Issue: 5905, https://forge.centreon.com/issues/5905
Original Date: 2014-10-23

---

Bonjour,

J'ai un soucis quand je veux afficher les détails d'un de mes services monitorés, cela m'affiche une page blanche...
Je ne rencontre pas ce soucis avec le détail des hosts.

Version :
 Debian 7.7
 Centreon 2.5.2
 PHP 5.3.29
 Centreon-Broker 2.6.3
 Centreon-Engine 1.4.7

Cordialement,

**Comment by julienmathis** [comment]
Thanks
