### ISSUE TITLE
[Downtime] Downtimes toujours présent sur quelques serveurs

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#183]
---

Author Name: **nathanael bonin** (nathanael bonin)
Original Redmine Issue: 6403, https://forge.centreon.com/issues/6403
Original Date: 2015-05-20

---

Bonjour,

Sur quelques serveurs j'ai des downtimes qui sont encore positionnés sur la machine alors qu'aucun n'est en cours. Lorsque l'on passe la souris sur le panneau attention, il n'indique aucune donnée. Comment faire pour les faire disparaitre svp? (cf les captures jointes).

Merci par avance.

**Comment by ganoze** [comment]
This issue was fixed in an already released version of Centreon.
