### ISSUE TITLE
New filter for service group  under monitoring/services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1838]
---

Author Name: **Christophe Absalon** (Christophe Absalon)
Original Redmine Issue: 4110, https://forge.centreon.com/issues/4110
Original Date: 2013-01-18

---

Hello it should be good to add a new filter for a service group in the service moniroting part.
so we can create a group with a list of critical service and have a direct view on all the status with clear detail.
useful for daily morning control or else

**Comment by lpinsivy** [comment]
Linked to #2218 and # 1679

**Comment by lpinsivy** [comment]
Servicegroup filter is now available in "Status detials" page

Possibility tu add '&sg=<servicegroup_id>' in URL

**Comment by Tpo76** [comment]
OK
