### ISSUE TITLE
Connexion SSO impossible avec utilisateur LDAP

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1841]
---

Author Name: **aurelie au** (aurelie au)
Original Redmine Issue: 6331, https://forge.centreon.com/issues/6331
Original Date: 2015-04-10

---

La connexion SSO n'est pas possible pour un utilsateur LDAP.
Le test qui vérifie le username est forcément FAUX car il compare <user_name> avec <user_name@FQDN>.

Voila la correction effectuée dans le fichier centreonAuth.SSO.class :
ligne 30 : Fichier d'origine : 
 if ($this->check_sso_client()) {
                                $this->sso_mandatory = 1;
                                $username = $this->sso_username;
                        }

Correction :
if ($this->check_sso_client()== 1) {
			$this->sso_mandatory = 1;
                       $posat=strrpos($this->sso_username,'@');
			global $orig_name;
			$orig_name=$username;
	 		$username = substr($this->sso_username,0,$posat);

}

**Comment by golgoth31** [comment]
Hi,
This bug has been closed but not resolved ! Can you resolv it, please.
