### ISSUE TITLE
Possibilité de voir que les services dont la notification est disable.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1845]
---

Author Name: **Nicolas COULIN** (Nicolas COULIN)
Original Redmine Issue: 985, https://forge.centreon.com/issues/985
Original Date: 2009-06-16

---

Bonjour,

Vous est il possible de rajouter une option afin de ne voir que les services dont la notification est désactivée ??

Il arrive tres souvent que l'on desactive les notifications lors de la réparation du probleme afin de ne pas etre spammer mail ou sms.
Et il arrive aussi de ne pas remettre les notifications !

Je pense que cette option serait vraiment interressante.

Merci,
Et vraiment bravo pour ce produit :)

**Comment by lpinsivy** [comment]
You need to use downtimes or acknowledge instead of disable notification
