### ISSUE TITLE
Problèmes avec la visualisation des méta-services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1853]
---

Author Name: **nathanael bonin** (nathanael bonin)
Original Redmine Issue: 2889, https://forge.centreon.com/issues/2889
Original Date: 2011-12-15
Original Assignee: Sylvestre Ho

---

Bonjour,

J'ai remarqué que lorsque l'on va dans la vue Supervision -> Services -> Méta services et que l'on en sélectionne un, il ne se passe rien. On arrive pas sur le détail du méta service. Je viens de remarquer que cela rajouté un # dans l'URL mais qu'il ne se passait rien d'autre...

Merci.

**Comment by julienmathis** [comment]
Done in 2.8 with the merge of meta service with regular services

**Comment by querwin** [comment]
Some informations are missing : 
Current Attempt

For all services on 2.8.0 this informatiosn are missing too : 
Current State Duration
Last Service Notification
