### ISSUE TITLE
Centreon 22.10 : Reach API Configuration not working

### ISSUE THREAD

**Issue by fabien493** [centreon/centreon#1872]
# BUG REPORT INFORMATION

### Tested on:

Version : Centreon 22.10.7
OS : Red Hat Entreprise Linux release 8.8 (Ootpa)

### Description

unable to use a non-admin account with « Reach API Configuration » enabled.

### Steps to Reproduce

1. Create user
2. Position an access group with all access (All resources and All action access)
3. Enable "Reach API Configuration" for the user
4. Use Api V1 (exemple for activate host)

### Result 
Unauthorized

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Can you provide the cURL used to activate host ?
Thanks

**Comment by fabien493** [comment]
Hello,

after generating the token, i run the following command:

curl -X POST 'https://mysupervision.com/centreon/api/index.php?action=action&object=centreon_clapi' -H "centreon-auth-token: Ye56aUNgNW0IUEP8EtiD2c17ddAz2B90xrHWXoMOnfeahEDytPhMHTFdXkNJZQUs" -H "Content-Type: application/json" --data '{ "action": "setparam", "object": "host", "values": "MYHOST;activate;1"}'

if the user associated with the token is an administrator, the command works but if the user is not an administrator, it returns "forbidden", although the Reach API Configuration box is enabled and the user has full rights in the ACLs

Can the Reach API Configuration option work without being an administrator ?

**Comment by fmattesct** [comment]
Hi @fabien493 ,
Thanks for your answer.
Since 22.04.5 (September 2022), admin rights are mandatory to use CLAPI/API V1.
https://docs.centreon.com/docs/22.04/releases/centreon-core/#security-fixes-3

We planned to update the documentation about that.
