### ISSUE TITLE
Global health graph display error

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1878]
---

Author Name: **Peeters Jan** (Peeters Jan)
Original Redmine Issue: 4273, https://forge.centreon.com/issues/4273
Original Date: 2013-03-04

---

In Home -> Global -> Services Graph
The labels warning and critical are displayed on top of each other (version 2.4.1).

Tested it with FF19, IE10, Safari6
Screenshot attached.

**Comment by julienmathis** [comment]
deprecated
