### ISSUE TITLE
Reporting page: customizable view(s)

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1879]
---

Author Name: **Peeters Jan** (Peeters Jan)
Original Redmine Issue: 1003, https://forge.centreon.com/issues/1003
Original Date: 2009-06-26

---

Can the drop down menu on the Reporting page be replaced by something like the tree on the Views page?
That way, you can select different hosts/hostgroups/servicegroups to be shown on the same page.
It would also be nice to be able to choose what to display (graph, period, service state, ...) for that selection.

This would be ideal to give the management a customized report page ...

**Comment by julienmathis** [comment]
depreacted
