### ISSUE TITLE
Restart centreontrapd from Centreon Web interface

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#189]
---

Author Name: **Francis FACHINAN** (Francis FACHINAN)
Original Redmine Issue: 5774, https://forge.centreon.com/issues/5774
Original Date: 2014-08-28

---

Hello,

When generating SQlite database for a poller, we also restart centreontrapd from web interface to reload configuration.
This restart does not work if the sudoers are not correctly configured.

We have added the following directive in /etc/sudoers to solve this problem:
CENTREON ALL = NOPASSWD: /etc/init.d/centreontrapd *

Can we include this directive in /etc/sudoers (CES 2.2) or /etc/sudoers.d/centreon (CES 3) with next updates?

Thanks in advance,

Regards,

**Comment by julienmathis** [comment]
I think it's ok in 2.6.2 no ?
