### ISSUE TITLE
Assing users to specific pollers

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1905]
---

Author Name: **julien gormotte** (julien gormotte)
Original Redmine Issue: 1739, https://forge.centreon.com/issues/1739
Original Date: 2010-05-06
Original Assignee: Julien Mathis

---

It could be a good idea to add a "poller" field to users, so that all users defined are not written to all nagios configurations.
For example, in my case, I have remote pollers on servers owned by clients. I do not want the contacts from other clients included in all the pollers.

I think this issue can be priorized as "high" because for some companies it could be a blocker (privacy reasons).

**Comment by garnier-quentin** [comment]
In centreon 2.7.x, it's by design. You only have contact needed. Not all.
