### ISSUE TITLE
Problème d'accent dans les custom view

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1908]
---

Author Name: **Roms Ain** (Roms Ain)
Original Redmine Issue: 6422, https://forge.centreon.com/issues/6422
Original Date: 2015-06-05

---

Bonjour,

Je remarque un problème d'accent, mais uniquement dans les custom view.
Dans le monitoring pas de soucis.

Merci.

**Comment by julienmathis** [comment]
Deprecated
