### ISSUE TITLE
Log de Nagios

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1914]
---

Author Name: **coolchamber -** (coolchamber -)
Original Redmine Issue: 1566, https://forge.centreon.com/issues/1566
Original Date: 2010-02-17

---

Bonjour,

je cherche mais ne trouve pas les messages de Nagios dans les logs.
Je parle pas des retours de plugins ni des alertes dans les logs.
Je parle des messages d informations quand on redémarre le service Nagios par exemple...(qui sont par contre visible sur Nagios)

Est ce que je rate un truc ?
CoOlChI

**Comment by julienmathis** [comment]
Available in Centreon Web 2.7 : Monitoring > Eventlogs > System logs
