### ISSUE TITLE
Ajout d'un champ dans commentaire d'acquitement

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1932]
---

Author Name: **Germe Charles** (Germe Charles)
Original Redmine Issue: 3449, https://forge.centreon.com/issues/3449
Original Date: 2012-07-20

---

Bonjour,

Est-il possible d'ajouter une champ "ticket" en plus du champ "commentaire" déjà présent dans les acquittements d'alertes.

Cela permettra d'identifier plus rapidement des les tickets ouvert dans les outils ITSM.

Cordialement

Charles Germe

**Comment by julienmathis** [comment]
now : https://github.com/centreon/centreon-open-tickets
