### ISSUE TITLE
Qualification of incidents

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1952]
---

Author Name: **Florence Pagani** (Florence Pagani)
Original Redmine Issue: 4335, https://forge.centreon.com/issues/4335
Original Date: 2013-03-25

---

It would be great if we could qualify incidents (as an attribute for example), in particular when Centreon BI is used, to generate an accurate report.

For example, it could be used to know who must be charged (for a service provider, it is not the same if incident is due to provided ressources as a service or if the failure comes from the network provider).

**Comment by julienmathis** [comment]
No informations
