### ISSUE TITLE
Add possibility for Admin to disable Service or Host from Monitoring

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1966]
---

Author Name: **Julien Mathis** (Julien Mathis)
Original Redmine Issue: 1342, https://forge.centreon.com/issues/1342
Original Date: 2009-11-24
Original Assignee: Sylvestre Ho

---

None

**Comment by lpinsivy** [comment]
No because after you need to export configuration and restart poller -> so it's configuration
