### ISSUE TITLE
Option manquante pour Méta-services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1974]
---

Author Name: **nathanael bonin** (nathanael bonin)
Original Redmine Issue: 3655, https://forge.centreon.com/issues/3655
Original Date: 2012-09-10

---

Bonjour,

Contrairement aux menus Hôtes et Services, le Menu Méta-services ne dispose pas des options "Activer", "Désactiver" dans le menu déroulant des actions complémentaires (au même titre que Dupliquer et Supprimer).

Serait-il possible de rajouter ces options svp?

Merci par avance.

**Comment by lpinsivy** [comment]
present in Centreon web 2.8.x
