### ISSUE TITLE
Fra translation broke «Monitoring» view

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#1991]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 3087, https://forge.centreon.com/issues/3087
Original Date: 2012-02-16

---

Hello,

tested on two centreon 2.2.2 server, Debian 6.0

I installed the French tranlation found on the http://translate.centreon.com/ website.

the exact download link : http://translate.centreon.com/fr/centreon-2.2/LC_MESSAGES/

I followed this doc to install it : http://en.doc.centreon.com/Setup:Language

Now with a user with the french language enabled, the menus «Supervision > Hôtes» & «Supervision > Services > Tous les services» remains empty.

Regards.

**Comment by julienmathis** [comment]
deprecated
