### ISSUE TITLE
Pouvoir exporter les alarmes en cours en CSV

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2023]
---

Author Name: **Samuel Mutel** (Samuel Mutel)
Original Redmine Issue: 4582, https://forge.centreon.com/issues/4582
Original Date: 2013-06-28

---

Bonjour,

Serais-il possible d'avoir un lien dans l'interface pour exporter en CSV les alarmes en cours ?

Cordialement,
Samuel Mutel.

**Comment by julienmathis** [comment]
Demande en cours côté widgets.
