### ISSUE TITLE
Adding Multiple Hosts/Items - from txt, csv, ldap 

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2029]
---

Author Name: **Constantin Lotz** (Constantin Lotz)
Original Redmine Issue: 2864, https://forge.centreon.com/issues/2864
Original Date: 2011-12-08

---

Would also be a nice feature if it's possible to add devices from ldap, or a csv file.
The Multiple edit feature is amazing, and i often use it.
But for adding for example 40 Camera devices it would be nice to get an automatic help :-)
Or by ip-range:
Starting device: 10.0.100.1
End device: 10.0.100.50
Name Start: Camera-{number}

The Ldap part will be easier, cause it already exists for the user import. for computers its not really different.
Thanks,
Burnout

**Comment by julienmathis** [comment]
This feature is now available via CLAPI
