### ISSUE TITLE
Swapped contact_name and contact_alias!

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2043]
---

Author Name: **Thomas - aka Jogarem -** (Thomas - aka Jogarem -)
Original Redmine Issue: 2378, https://forge.centreon.com/issues/2378
Original Date: 2011-05-05
Original Assignee: Sylvestre Ho

---

In nagios the contact_name is a short description used to name the object (what the contactgroup uses in the members item) and alias is the long description. For some reason Centreon has these reversed, using the nagios alias as the login name and contact_name is called "Full Name". After replacing spaces with underscores, "Full Name" is then totally ignored within Centreon itself.

taken from #132:

```
My suggestion is to reverse these (again?) in Centreon, to be more in line with nagios. Of course potentially breaking all logins to centreon where contact_name and alias are different, without some careful SQL trickery.
Thus:
- using contact_name as the short name used for logins.
- alias would be the "Full Name" description (with spaces allowed) used in "Online Users" box.

This would create a much cleaner looking contactgroups.cfg.

I did submit a suggested patch against a 1.4.2.7 install at http://bugs.centreon.com/?do=details&id=511 . Sorry it's not against svn and I haven't looked at centreon 2's code.
prud'homme sebastien wrote:
> I reopen this bug as this is really annoying : all others Nagios based tools (and Nagios CGI) uses "contact_name" for authentification. Centreon is the only one that uses "alias". Here is the Nagios documentation:
> 
> [...]
> 
> Example that is correct with Nagios:
> 
> contact_name = sebastien.prudhomme
> alias = Sébastien PRUD'HOMME
> 
> But in Centreon:
> contact_name = Sebastien_PRUDHOMME (no spaces an other specials chars...)
> alias = sebastien.prudhomme
> 
> If i want to use the same authentification login in Centreon and other Nagios addons, i need to put "sebastien.prudhomme" in both fields. As i said in the beginning, annoying.



```

please reopen #132 ! this is also a problem when using the eventbroker in nagios it expects the contact_name as the short name and the alias as the long name. This results in several problems e.g. within livestatus another broker module but also with other tools which rely on those directives!

**Comment by julienmathis** [comment]
deprecated
