### ISSUE TITLE
complete template and object inheritance support

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2057]
---

Author Name: **Nikolaus Filus** (Nikolaus Filus)
Original Redmine Issue: 982, https://forge.centreon.com/issues/982
Original Date: 2009-06-15

---

While reading through the nagios documentation, I found object inheritance options not avaiable in centreon.
This bug report shall list and track/document the level of support for them. Source of truth is
http://nagios.sourceforge.net/docs/3_0/objectinheritance.html
Each item must be checked for import and for export support plus presentation in the interface.

* Cancelling Inheritance of String Values (event_handler null)
* Additive Inheritance of String Values (host_groups +mygroup)
* Implied Inheritance
* Implied/Additive Inheritance in Escalations
* multiple inheritance for services (and unify with host template dialog)

**Comment by julienmathis** [comment]
ok implemented in the major part of case
