### ISSUE TITLE
Multiple search in Monitoring > Status Details filters

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#210]
---

Author Name: **julien homer** (julien homer)
Original Redmine Issue: 3846, https://forge.centreon.com/issues/3846
Original Date: 2012-10-30

---

Is it possible to add the possibility to search multiple services/hosts in the Monitoring menu

Example :
- in the "Service" textbox, if we write cpu||mem => list all the services named _cpu_ or _mem_
- in the "Host" textbox, if we write WORD1||WORD2 => list all the hosts named _WORD1_ or _WORD2_

**Comment by Moujimouja** [comment]
Implemented for a while and efficient in 20.04.

I close the ticket
