### ISSUE TITLE
Security enhancement : session token in URL

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2112]
---

Author Name: **Louis Ferret** (Louis Ferret)
Original Redmine Issue: 6456, https://forge.centreon.com/issues/6456
Original Date: 2015-06-30

---

Some URL seem to contain session ids in them. There problem here is that it increases the risk that these data will be captured by attackers.

For instance : 
/centreon/include/Administration/corePerformance/getStats.php?ns_id=1&key=host_states&start=today&*session_id*=[Number]
/centreon/include/reporting/dashboard/xmlInformations/GetXmlHost.php?id=14&*session*=[Number]&[Other Parameters]
/centreon/include/Administration/corePerformance/getStats.php?ns_id=1&key=active_host_check&start=today&*session_id*=[Number]

To transmit session tokens, it is recommended to use HTTP cookies or hidden fields in forms that are submitted using the POST method.

**Comment by Tpo76** [comment]
OK
