### ISSUE TITLE
'sudo sorry you must have a tty to run sudo' error

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2114]
---

Author Name: **Eins Chung** (Eins Chung)
Original Redmine Issue: 5848, https://forge.centreon.com/issues/5848
Original Date: 2014-09-29

---

After Install Centreon and Centreon Poller in same machine. 
I got error message 'sudo sorry you must have a tty to run sudo' when execute Export(Configuration>Monitoring Engine>Generate>Export).
I think web user has not proper permission. so add 'apache' (in the CentOS) user to /etc/sudoers. 
 And Next time Export command succeeds.

**Comment by pvillard31** [comment]
Hi.

Just to let you know I faced the same issue with last versions (see below).
I added apache user in the /etc/sudoers.d/centreon to solve the issue.

centreon-clib-1.4.2
centreon-base-config-centreon-engine-2.7.1
centreon-engine-1.5.0
centreon-2.7.1
centreon-connector-1.1.2
centreon-common-2.7.1
centreon-connector-perl-1.1.2
centreon-broker-storage-2.11.1
centreon-engine-daemon-1.5.0
centreon-trap-2.7.1
centreon-plugins-2.7.1
centreon-broker-cbmod-2.11.1
centreon-web-2.7.1
centreon-poller-centreon-engine-2.7.1
centreon-broker-2.11.1
centreon-connector-ssh-1.1.2
centreon-broker-core-2.11.1
centreon-engine-extcommands-1.5.0
centreon-perl-libs-2.7.1
centreon-broker-cbd-2.11.1
centreon-plugin-meta-2.7.1
