### ISSUE TITLE
Nagios start/stop/die history

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2117]
---

Author Name: **Jean-Baptiste Lamotte** (Jean-Baptiste Lamotte)
Original Redmine Issue: 2032, https://forge.centreon.com/issues/2032
Original Date: 2010-11-05
Original Assignee: Julien Mathis

---

It could be interesting to have a very simple page with history for each poller.
Start event, stop event, and why not, an event when a poller has not given response for a laps of time.

**Comment by garnier-quentin** [comment]
There is a system log page in centreon 2.7.x.
