### ISSUE TITLE
Bug for informations in Configuration - Centreon

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2146]
---

Author Name: **Stephane Duret** (Stephane Duret)
Original Redmine Issue: 6031, https://forge.centreon.com/issues/6031
Original Date: 2014-12-15

---

Hello,

If I have old poller in the table "intances", the version of monitoring engine will be wring in the page "Conguration --> Centreon".

This is the query in ./include/configuration/configServers/listServers.php
@SELECT DISTINCT instance_id, version AS program_version, engine AS program_name, name AS instance_name FROM instances LIMIT $pollerNumber@

Two solutions:
* delete old pollers from table "instances"
* do not use "limit" in query

Regards

**Comment by bsauveton** [comment]
Duplicate #1195
