### ISSUE TITLE
Renaming a service messes up Service Group

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2155]
---

Author Name: **Pedro Walter** (Pedro Walter)
Original Redmine Issue: 4903, https://forge.centreon.com/issues/4903
Original Date: 2013-09-26

---

Hi,

Opened this as a thread at the forums first, didn't know you had an open bug tracker...

The bug we found is on the last version of Centreon (2.4.4). Here are the steps to reproduce it:

First, we create a Service, say, "Test Service";
Second, we add this service to many hosts (example: "host1","host2","host3");
Third, we create a Service Group, say, "Test Service Group", adding only one host to it (say, "host1");
Fourth, we go the Service Description Page and just click "Save", no modifications needed.

What happens is that now the "Test Service Group" will have ALL hosts that had this service added inside it ("host1","host2","host3").

Trying to debug it, something was messing things up in the "updateServiceServiceGroup" function, at file "/opt/centreon/www/include/configuration/configObject/service/DB-Func.php". It deletes all the hosts related with the Service Group, then recreates them with the hosts from function "getMyServiceHosts" (line 1824).

Hope all this info helps, just reply if you need any more details.

Thanks!

**Comment by lpinsivy** [comment]
should be solved
