### ISSUE TITLE
Backup durant l'export

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2157]
---

Author Name: **Raphael Troiano** (Raphael Troiano)
Original Redmine Issue: 3190, https://forge.centreon.com/issues/3190
Original Date: 2012-03-29

---

Bonjour,

Il serait pratique d'avoir dans la page "Nagios Configuration Files Export" une ligne optionnel pour faire un backup automatique de la base "Centreon" et des fichiers présents dans "./centreon/filesGeneration"
Le tout se mettant dans ./centreon/backup/%user%-%date%-%time%.tar.gz

Cdlt,

**Comment by julienmathis** [comment]
possible depuis centreon 2.7.x
