### ISSUE TITLE
problem with cron_operation table and running values after reboot

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2161]
---

Author Name: **victor hugo dos santos** (victor hugo dos santos)
Original Redmine Issue: 5202, https://forge.centreon.com/issues/5202
Original Date: 2014-02-13
Original Assignee: remi werquin

---

Hi,

the other day, I reboot my server normaly and all services were stopped and started correctly.
but, after 3 days... I look in the dashboard page and the values of services status is not correct (all they are showing "undertemined" values).

so... I log in the mysql and that is the output of cron_operation table:

*************************
 mysql> select * from cron_operation;
 +----+-----------------+---------+-------------+-------------------+--------+--------+---------+---------------------+----------+
 | id | name            | command | time_launch | last_modification | system | module | running | last_execution_time | activate |
 +----+-----------------+---------+-------------+-------------------+--------+--------+---------+---------------------+----------+
 |  2 | centAcl.php     | NULL    |  1392317041 |                 0 | 1      | NULL   | 0       |                   0 | 1        |
 |  3 | nagiosPerfTrace | NULL    |  1391897402 |                 0 | 1      | NULL   | 1       |                  62 | 1        |
 |  4 | logAnalyser     | NULL    |  1392317041 |                 0 | 1      | NULL   | 1       |                   2 | 1        |
 +----+-----------------+---------+-------------+-------------------+--------+--------+---------+---------------------+----------+
 3 rows in set (0.00 sec)
*************************

So... the problem is that in the shutdown process, centreon "dont" update this table.. and the "running" still in "1"
and after the reboot, the cron process dont process the logs, because this value is set in 1 and "never" change to "0" again.

solutions (??):
- when the centreon is stopped, update this values to 0 
- when the system boot, make this values to 0 (maybe in the cron at @reboot option)

thanks and attentive.

**Comment by julienmathis** [comment]
deprecated
