### ISSUE TITLE
Filtre par Groupe de service

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2218]
---

Author Name: **cedric meschin** (cedric meschin)
Original Redmine Issue: 3086, https://forge.centreon.com/issues/3086
Original Date: 2012-02-15

---

Bonjour,
J'ai cherché mais n'ai pas trouvé de demande correspondante.

Est-il possible d'ajouter dans les critères de filtre sur la page de supervision le "Groupe de Service" comme c'est déjà le cas pour le "Groupe d'hôtes"?
Le groupe de service nous sers pour identifier les clients, certains hôtes étant mutualisés, la distinction se fait donc par le groupe de service. Cette fonction permettrai de ne pas nommer les service avec le nom du client et ainsi gagner en lisibilité.
cf PJ pour exemple

cordialement
Cedric Meschin

**Comment by lpinsivy** [comment]
Servicegroup filter is now available in "Status detials" page

Possibility tu add '&sg=<servicegroup_id>' in URL
