### ISSUE TITLE
[Mysql Error] Cannot connect to database

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2240]
---

Author Name: **Antoine Faisandier** (Antoine Faisandier)
Original Redmine Issue: 6464, https://forge.centreon.com/issues/6464
Original Date: 2015-07-13

---

centreon version ces-standard : centreon 2.6.1

Same error in multiple log 
For example :
/var/log/centreon/centcore.log or in /var/log/centreon/logAnalyser.log
```
2015-07-13 11:37:29 - MySQL error : cannot connect to database centreon: Access denied for user 'XXXXXX'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)

```

I set up the password in log /usr/share/perl5/vendor_perl/centreon/common/db.pm line 210 
```
logger->writeLogError("MySQL error : cannot connect to database " . $self->{db} . ": ".$self->{password}. ":" . $DBI::errstr . " (caller: $package:$filename:$line)");

```

My password contains an '@' : test@password
result password in log : test

I set up hard coded password in file  /usr/share/perl5/vendor_perl/centreon/common/db.pm line 201 for the connection to mysql
```
$self->{instance} = DBI->connect(
196                 "DBI:".$self->{type}
197                     .":".$self->{db}
198                     .":".$self->{host}
199                     .":".$self->{port},
200                 $self->{user},
201                 'test@password',


```

Now it's working.

This bug affect acknowledgments, perf data ...

Regards

**Comment by julienmathis** [comment]
link to #1752 and #1200
