### ISSUE TITLE
[Graph Curves] Ability to setup the Area Color with a random color

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2243]
---

Author Name: **sebastien maury** (sebastien maury)
Original Redmine Issue: 5055, https://forge.centreon.com/issues/5055
Original Date: 2013-12-13

---

Hi,

Today, we can define a line color with a random color.

But we have to define a specific color for the Area Color.

It would be great if we can define the Area color this way :
1/ Defining a specific color
2/ Defining a randome color
3/ Telling to use the same color as the line color

Thanks in advance.
Regards,
Sébastien

**Comment by querwin** [comment]
I think, there is a problem with the filling option.

Curves always are filled. No matter we use box filling or not.
