### ISSUE TITLE
filter field for escalations

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2247]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 2232, https://forge.centreon.com/issues/2232
Original Date: 2011-03-25
Original Assignee: Lionel Assepo

---

Hello,

When Centreon got a lot of hosts and services to manage, it become very hard to use escalation. (> Configuration > Notifications > Escalations)

Indeed, there is no way to sort or search in the list of hosts and services, so when the list is very big it's a real pain to find something.

Is it possible to add at least a search field ? (i added a mockup to illustrate what i mean)

One more thing : the "Selected" columrs is not sorted, but the "Available" is sorted.

Regards.

**Comment by julienmathis** [comment]
Passage à select2 ?
