### ISSUE TITLE
Centreon Purge should execute an optimize of tables

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2263]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 6038, https://forge.centreon.com/issues/6038
Original Date: 2014-12-16

---

Hello,

I'm working with Centreon since few years. My database size is very heavy and the centreon purge has no effect on used disk space, the script is not able to recover space disk.

To recover it, the script should execute at the end an optimize query on tables like data_bin or logs.

The query is heavy, tables are locked during the process, but this job allows to recover a large amount of disk space.

Best regards.

Best regards.

**Comment by julienmathis** [comment]
Yes, It's too much dangerous to integrate this kind of script. User is responsible of this kind of tasks.
