### ISSUE TITLE
Move all MyISAM tables to InnoDB

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2276]
---

Author Name: **Matthieu Kermagoret** (Matthieu Kermagoret)
Original Redmine Issue: 3676, https://forge.centreon.com/issues/3676
Original Date: 2012-09-17

---

According to this article (http://www.oracle.com/partners/en/knowledge-zone/mysql-5-5-innodb-myisam-522945.pdf), InnoDB is now more performant and scalable than MyISAM. Would it be possible to move all tables that are still in MyISAM (logs, index_data, metrics, data_bin and others) to InnoDB ?

**Comment by julienmathis** [comment]
@garnier-quentin Do you think it could be ok for the installation ? We can't manage upgrade action but now InnoDB is very faster that MyISAM...

**Comment by garnier-quentin** [comment]
On new install, yes.
