### ISSUE TITLE
TOKEN Rest API

### ISSUE THREAD

**Issue by Steph6Steph** [centreon/centreon#228]

**Comment by ponchoh** [comment]
# 😎🦝

anything else?

**Comment by ponchoh** [comment]
# 🏁 

V1 | https://docs.centreon.com/docs/api/rest-api-v1/#authentication
V2 | https://docs-api.centreon.com/api/centreon-web/#tag/Authentication/paths/~1login/post

## V1

https://docs.centreon.com/docs/api/rest-api-v1/#authentication

<html>
<body>
<p style="box-sizing: border-box; margin-top: ; margin-right: ; margin-bottom: var(--ifm-leading); margin-left: ; color: rgb(28, 30, 33); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Using POST method and the URL below:</p><div class="language-shell codeBlockContainer_Ckt0 theme-code-block" style="box-sizing: border-box; background: var(--prism-background-color); color: var(--prism-color); border-radius: var(--ifm-code-border-radius); box-shadow: var(--ifm-global-shadow-lw); margin-bottom: var(--ifm-leading); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; --prism-color:#393A34; --prism-background-color:#f6f8fa;"><div class="codeBlockContent_biex" style="box-sizing: border-box; border-radius: inherit; direction: ltr; position: relative;"><pre tabindex="0" class="prism-code language-shell codeBlock_bY9V thin-scrollbar" style="box-sizing: border-box; overflow: auto; margin: 0px; background-color: var(--ifm-pre-background); border-radius: var(--ifm-pre-border-radius); color: var(--ifm-pre-color); font: var(--ifm-code-font-size)/var(--ifm-pre-line-height) var(--ifm-font-family-monospace); padding: 0px; --ifm-pre-background:var(--prism-background-color);"><code class="codeBlockLines_e6Vv" style="box-sizing: border-box; vertical-align: middle; background-color: initial; border: none; border-radius: var(--ifm-code-border-radius); font: inherit; padding: var(--ifm-pre-padding); float: left; min-width: 100%;"><span class="token-line" style="box-sizing: border-box; color: rgb(57, 58, 52);"><span class="token plain" style="box-sizing: border-box;">api.domain.tld/centreon/api/index.php?action</span><span class="token operator" style="box-sizing: border-box; color: rgb(57, 58, 52);">=</span><span class="token plain" style="box-sizing: border-box;">authenticate</span><br style="box-sizing: border-box;"></span></code></pre><div class="buttonGroup__atx" style="box-sizing: border-box; column-gap: 0.2rem; display: flex; position: absolute; right: calc(var(--ifm-pre-padding)/2); top: calc(var(--ifm-pre-padding)/2);"><button type="button" aria-label="Copy code to clipboard" title="Copy" class="clean-btn" style="box-sizing: border-box; background: var(--prism-background-color); border: 1px solid var(--ifm-color-emphasis-300); color: var(--prism-color); cursor: pointer; font-family: inherit; padding: 0.4rem; align-items: center; border-radius: var(--ifm-global-radius); display: flex; line-height: 0; opacity: 0; transition: opacity 0.2s ease-in-out 0s;"><span class="copyButtonIcons_eSgA" aria-hidden="true" style="box-sizing: border-box; height: 1.125rem; position: relative; width: 1.125rem;"><svg class="copyButtonIcon_y97N" viewBox="0 0 24 24"><path d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z"></path></svg><svg class="copyButtonSuccessIcon_LjdS" viewBox="0 0 24 24"><path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg></span></button></div></div></div><p style="box-sizing: border-box; margin-top: ; margin-right: ; margin-bottom: var(--ifm-leading); margin-left: ; color: rgb(28, 30, 33); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Body form-data:</p>

Parameter | Type | Value
-- | -- | --
username | Text | The user name you use to login on Centreon
password | Text | Your Centreon password

<p style="box-sizing: border-box; margin-top: ; margin-right: ; margin-bottom: var(--ifm-leading); margin-left: ; color: rgb(28, 30, 33); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The response is a json flow getting back the authentication token :</p><div class="language-json codeBlockContainer_Ckt0 theme-code-block" style="box-sizing: border-box; background: var(--prism-background-color); color: var(--prism-color); border-radius: var(--ifm-code-border-radius); box-shadow: var(--ifm-global-shadow-lw); margin-bottom: var(--ifm-leading); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; --prism-color:#393A34; --prism-background-color:#f6f8fa;"><div class="codeBlockContent_biex" style="box-sizing: border-box; border-radius: inherit; direction: ltr; position: relative;"><pre tabindex="0" class="prism-code language-json codeBlock_bY9V thin-scrollbar" style="box-sizing: border-box; overflow: auto; margin: 0px; background-color: var(--ifm-pre-background); border-radius: var(--ifm-pre-border-radius); color: var(--ifm-pre-color); font: var(--ifm-code-font-size)/var(--ifm-pre-line-height) var(--ifm-font-family-monospace); padding: 0px; --ifm-pre-background:var(--prism-background-color);"><code class="codeBlockLines_e6Vv" style="box-sizing: border-box; vertical-align: middle; background-color: initial; border: none; border-radius: var(--ifm-code-border-radius); font: inherit; padding: var(--ifm-pre-padding); float: left; min-width: 100%;"><span class="token-line" style="box-sizing: border-box; color: rgb(57, 58, 52);"><span class="token punctuation" style="box-sizing: border-box; color: rgb(57, 58, 52);">{</span><span class="token plain" style="box-sizing: border-box;"></span><br style="box-sizing: border-box;"></span><span class="token-line" style="box-sizing: border-box; color: rgb(57, 58, 52);"><span class="token plain" style="box-sizing: border-box;">    </span><span class="token property" style="box-sizing: border-box; color: rgb(54, 172, 170);">"authToken"</span><span class="token operator" style="box-sizing: border-box; color: rgb(57, 58, 52);">:</span><span class="token plain" style="box-sizing: border-box;"> </span><span class="token string" style="box-sizing: border-box; color: rgb(227, 17, 108);">"NTc1MDU3MGE3M2JiODIuMjA4OTA2OTc="</span><span class="token plain" style="box-sizing: border-box;"></span><br style="box-sizing: border-box;"></span><span class="token-line" style="box-sizing: border-box; color: rgb(57, 58, 52);"><span class="token plain" style="box-sizing: border-box;"></span><span class="token punctuation" style="box-sizing: border-box; color: rgb(57, 58, 52);">}</span><br style="box-sizing: border-box;"></span></code></pre><div class="buttonGroup__atx" style="box-sizing: border-box; column-gap: 0.2rem; display: flex; position: absolute; right: calc(var(--ifm-pre-padding)/2); top: calc(var(--ifm-pre-padding)/2);"><button type="button" aria-label="Copy code to clipboard" title="Copy" class="clean-btn" style="box-sizing: border-box; background: var(--prism-background-color); border: 1px solid var(--ifm-color-emphasis-300); color: var(--prism-color); cursor: pointer; font-family: inherit; padding: 0.4rem; align-items: center; border-radius: var(--ifm-global-radius); display: flex; line-height: 0; opacity: 0; transition: opacity 0.2s ease-in-out 0s;"><span class="copyButtonIcons_eSgA" aria-hidden="true" style="box-sizing: border-box; height: 1.125rem; position: relative; width: 1.125rem;"><svg class="copyButtonIcon_y97N" viewBox="0 0 24 24"><path d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z"></path></svg><svg class="copyButtonSuccessIcon_LjdS" viewBox="0 0 24 24"><path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg></span></button></div></div></div><p style="box-sizing: border-box; margin-top: ; margin-right: ; margin-bottom: var(--ifm-leading); margin-left: ; color: rgb(28, 30, 33); font-family: system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This token will be used later on the other API actions.</p>
</body>
</html>

## V2

https://docs-api.centreon.com/api/centreon-web/#tag/Authentication/paths/~1login/post

```
POST | {protocol}://{server}:{port}/centreon/api/{version}/login
```

```json
{
  "security": {
    "credentials": {
      "login": "admin",
      "password": "centreon"
    }
  }
}
```

Response 200

```json
{
  "contact": {
    "id": 3,
    "name": "Admin",
    "alias": "admin",
    "email": "admin@localhost",
    "is_admin": true
  },
  "security": {
    "token": "9ed937d3911d212eae59300ac6977352"
  }
}
```

# 🤞
