### ISSUE TITLE
Ajouter la vue "Configuration -> Centreon -> Collecteurs" en lecture seule pour les utilisateurs avec ACL

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2290]
---

Author Name: **nathanael bonin** (nathanael bonin)
Original Redmine Issue: 6156, https://forge.centreon.com/issues/6156
Original Date: 2015-02-20

---

Bonjour,

Vous avez amélioré la liste des fonctionnalités possible avec les ACL. Serait-il possible de donner en lecture seule UNIQUEMENT la page de configuration "Configuration -> Centreon -> Collecteurs" svp?

En effet, cela permettrait montrer aux utilisateurs sur quels serveurs des modifications ont été apportées et ils sauraient sur quel(s) poller(s) il est nécessaire de recharger la configuration.

Je vous en remercie par avance.

Nathanael.

**Comment by lpinsivy** [comment]
Bonjour nathanael,

Depuis Centreon 2.7, la génération des collecteurs passe forcement par cette page. Ainsi si l'utilisateur a accès en lecture seule, alors il ne pourra pas régénérer la configuration.

Je pense que cette demande devient désuète non ?

Cdt,

**Comment by Hellnino18** [comment]
Bonjour Laurent,

Si l'utilisateur a accès en écriture il peut modifier aussi la configuration des satellites ? Si oui, ce n'est pas terrible comme gestion. Les ACL devraient dans ce cas être beaucoup plus fines.

**Comment by julienmathis** [comment]
Should be ok now with fixed #4122
