### ISSUE TITLE
/bin/sh: /var/log/centreon/downtimeManager.log: Permission denied

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2298]
---

Author Name: **Sébastien Boulianne** (Sébastien Boulianne)
Original Redmine Issue: 6181, https://forge.centreon.com/issues/6181
Original Date: 2015-03-05
Original Assignee: Maximilien Bersoult

---

Message 20:
From root@centreonpoller.qc.ca  Mon Feb 23 16:10:01 2015
Return-Path: <root@centreonpoller.qc.ca>
X-Original-To: apache
Delivered-To: apache@centreonpoller.qc.ca
From: root@centreonpoller.qc.ca (Cron Daemon)
To: apache@centreonpoller.qc.ca
Subject: Cron <apache@lsneufchatel_poller> /usr/bin/php -q /usr/share/centreon/cron/downtimeManager.php >> /var/log/centreon/downtimeManager.log 2>&1
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <PATH=/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <CRONTAB_EXEC_USER=>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/var/www>
X-Cron-Env: <LOGNAME=apache>
X-Cron-Env: <USER=apache>
Date: Mon, 23 Feb 2015 16:10:01 -0500 (EST)
Status: R

/bin/sh: /var/log/centreon/downtimeManager.log: Permission denied

**Comment by julienmathis** [comment]
You should have changed yourself this rights because we don't have this kind of feedbacks...
