### ISSUE TITLE
Inherit macro from model

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#230]
---

Author Name: **Etienne Chauve** (Etienne Chauve)
Original Redmine Issue: 6448, https://forge.centreon.com/issues/6448
Original Date: 2015-06-30

---

When configuring an object model(service or host)or an object inheriting from a model, it would be nice to have a way to see the macros it is inheriting and their values.

**Comment by ganoze** [comment]
This feature was implemented in Centreon 2.7.
