### ISSUE TITLE
CentreonConfigurationModule

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2319]
---

Author Name: **Florian Asche** (Florian Asche)
Original Redmine Issue: 5595, https://forge.centreon.com/issues/5595
Original Date: 2014-06-04

---

Hi,

i have some enhancement for this commit:

```
https://forge.centreon.com/projects/centreon/repository/revisions/e373c3052d8c3e0902afb580bc2bc91c10badb1a/entry/modules/CentreonConfigurationModule/repositories/ConfigApplyRepository.php

```

```
        $command = "sudo /etc/init.d/centengine $method";

```

in Old Versions the path comes from database. It would be nice if we could make this here configureable too. 

In our company we use centreon, but we cant install in /var/ /usr/ or /etc/ so we build our own package where all files installed in /CENTREON/...

**Comment by julienmathis** [comment]
deprecated
