### ISSUE TITLE
Customziable Table listing under Monitoring->Hosts/Services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2323]
---

Author Name: **Constantin Lotz** (Constantin Lotz)
Original Redmine Issue: 4891, https://forge.centreon.com/issues/4891
Original Date: 2013-09-18

---

Hi there,

it would be nice if it is possible to customize information showed up under Monitoring->Hosts (or Services).
For example that also the host description can be shown. Or maybe some users want to hide the IP Address.

Is that already planned for centreon < 2.5 - or not yet thought about ?

kind regards,
Constantin

At the moment the Table looks like

| Hosts | Status | IP Address | Last Check | Duration | Tries | Status information |
customized:
| Hosts | Host description | Status  | Duration | Tries | Status information | Last Check

**Comment by julienmathis** [comment]
deprecated
