### ISSUE TITLE
use INNODB for centstorage Tables data_bin and logs

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2325]
---

Author Name: **Ira Maus** (Ira Maus)
Original Redmine Issue: 6431, https://forge.centreon.com/issues/6431
Original Date: 2015-06-12

---

If you have a huge data_bin and want to rebuild an RRD, the executed SELECT will then freeze GUI and centreon-broker. The SELECT for rebuild a RRD performs a full table scan and this creates a LOCK on the table as data_bin is a MYISAM.
Same for SELECTS for table logs.

AS INNODB can handle those SELECTs without a lock, it might be better to switch those tables to INNODB. Of course I know that these tables have a huge UPDATE/INSERT rate, but if you know how to tune your INNODB engine/MYSQL Server, it could be better to use INNODB than MYISAM.

**Comment by garnier-quentin** [comment]
innodb is now used in centreon 2.7.x. From previous version, we don't do the engine change.

**Comment by george-vieira** [comment]
sorry top jump in, you don't change the engine type but is centreon happy for me to simply take it down, convert it over and start it or are there changes needed for this to be running with innodb?
