### ISSUE TITLE
Unable to submit passive result to several services in one action

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2340]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 2322, https://forge.centreon.com/issues/2322
Original Date: 2011-05-03

---

Hello.

In «Monitoring > Services», via the drop down menu «More actions», there is no choice to submit passive result to several services.

If need to do that, you need to open every service, one by one, and follow the procedure. Very painfull if you need to reset a lot of passive service.

Is it possible to add something like «Services : Submit result» to this drop down menu ?

Regards.

**Comment by julienmathis** [comment]
An API will be available for that with web 2.8.x
