### ISSUE TITLE
host/service configuration with template presentation

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2356]
---

Author Name: **gae -** (gae -)
Original Redmine Issue: 407, https://forge.centreon.com/issues/407

---

It would be very usefull if the host/service configuration page presents directly parameters heritated from selected templates in the configuration fields with a different color.

this feature could allow the administrator to see :
- the exact configuation of the host/service without having to compare with the template above,
- if all requested fields are specified before saving the configuration.

color could be set with a specific css class for parameters heritated from a template

parameters field from templates can still be overwriten by user specific values.

**Comment by lpinsivy** [comment]
implemented
