### ISSUE TITLE
Sommaire des configurations suite à la concaténation de template associé à un host 

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2357]
---

Author Name: **yan bisson** (yan bisson)
Original Redmine Issue: 1164, https://forge.centreon.com/issues/1164
Original Date: 2009-08-26

---

Bonjour,

Je voudrais suggérer d'avoir un un écran depuis la page des hosts qui pourrait nous donner le sommaire des configurations suite à la concaténation des différents template associé à un host... lorsqu'un host est associé à plusieurs template il peut devenir difficile de comprendre la résultante.

Évidement cette fonctionnalité ne permettrait que de voir la résultante pour les template associé au host et n'aurait pas à prendre en compte tout les autres éléments qui peuvent influencer la configuration final.

Qu'en pensez-vous?

Merci

**Comment by julienmathis** [comment]
present in 3.0
