### ISSUE TITLE
Insert in index_data doesn't work as expected

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2362]
---

Author Name: **Simon Bomm** (Simon Bomm)
Original Redmine Issue: 6421, https://forge.centreon.com/issues/6421
Original Date: 2015-06-05

---

Hi guys, 

Find on :
Centreon 2.5.4
Centreon 2.6.1

Faced a funny issue with my poller-display setup, when enabling "insert in index_data" option box in Administration > Options, and creating a storage/perfdata output in broker configuration, value is set to 0. 

If disabling it, then the value is set to 1. 

So there is probably some reversed condition concerning update of the centreon.options table for the key index_data. 

Thanks a lots !

**Comment by Tpo76** [comment]
OK
