### ISSUE TITLE
Classer les hosttemplates par ordre alphabétique dans les Services Groups

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2384]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 6429, https://forge.centreon.com/issues/6429
Original Date: 2015-06-11

---

Afin de pouvoir conserver la hiérarchie des modèles d'hôtes pour les services groups, il serait bon de classer les hosts templates par ordre alphabétique dans la configuration  des services groups. Pour cela :

- Editer : www/include/configuration/configObject/servicegroup/formServiceGroup.php
- Ligne 144 : Modifier "ORDER BY service_service_id" par "ORDER BY host_name"
- Ligne 170 : Remplacer / AND host_register = '0'"; / par / AND host_register = '0' ORDER BY host_name"; /

**Comment by Tpo76** [comment]
OK
