### ISSUE TITLE
Search tool when configuring relations

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2396]
---

Author Name: **Vincent Varlet** (Vincent Varlet)
Original Redmine Issue: 4841, https://forge.centreon.com/issues/4841
Original Date: 2013-08-23

---

Hi,

when configurating relations (groups, dependecies ...), it could be usefull to have a dynamic search filter instead of scrolling dozens of hosts/services.

++

**Comment by lpinsivy** [comment]
implented
