### ISSUE TITLE
Macros with exclamation marks

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2405]
---

Author Name: **Chris Costa** (Chris Costa)
Original Redmine Issue: 4993, https://forge.centreon.com/issues/4993
Original Date: 2013-11-13

---

hi,
I am trying to use macros to connect to my redis servers but i find it impossible to use exclamation marks when defining macros.

Macro: REDISPASS | value: 'password!' (since i have to escape the "!" i use "!") Everything is saved and exclamation mark is still showing even after i save.

when i use it in my command:

$User1$/check_nrpe -H $HOSTADDRESS$ -p 5666 -c check_redis -a $_SERVICEREDISIP$ $_SERVICEREDISPORT$ '$_SERVICEREDISPASS$'

i get error:

'The command (c:/perl.exe check_redis.pl -H 123.123.123 -p 1234 -x password) returned an invalid return code 255 [auth] ERR invalid password.'     

As you can see the "password" here has no exclamation mark which tells me that the "!" is not passed.

When i hard-code the password in my nsclient.ini file it accepts it normally, so there is nothing wrong with that.

Please try and replicate this to see if there is something wrong. thank you

**Comment by julienmathis** [comment]
deprecated
