### ISSUE TITLE
Les services restent sur l'hosts apres suppression du template lié 

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2424]
---

Author Name: **Nicolas COULIN** (Nicolas COULIN)
Original Redmine Issue: 6227, https://forge.centreon.com/issues/6227
Original Date: 2015-03-27

---

Bonjour,

Lorsque je suis sur mon host, et que je lui enleve le template Dick E par exemple, cela avait pour effet de supprimer le service qui lui etait lié.
Hors depuis quelque temps, surement le passage en 2.5.4, la suppression du template n'entraine pas la suppression du service.

Est ce normal, avez vous revu ce fonctionnement ? ou est ce un pb de mon cote ?

Merci

**Comment by julienmathis** [comment]
A valider
