### ISSUE TITLE
LDAP imported user are not associated with user template

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#244]
---

Author Name: **Romain Couturat** (Romain Couturat)
Original Redmine Issue: 3001, https://forge.centreon.com/issues/3001
Original Date: 2012-01-26
Original Assignee: Maximilien Bersoult

---

In Administration > Options, LDAP
we can configure a "Contact template" to be associated with newly LDAP imported users.
But imported users do not use the template !

To correct the problem, simply add the folowing line
```
$tmpConf["contact_template_id"] = $tmpContacts["contact_template_id"][$select_key];

```
in file www/include/configuration/configObject/contact/DB-Func.php
in the foreach of the insertLdapContactInDB function (around line 870).

**Comment by julienmathis** [comment]
deprecated
