### ISSUE TITLE
Ajout automatique des macros personnalisés

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2459]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 4979, https://forge.centreon.com/issues/4979
Original Date: 2013-11-07

---

La bonne pratique voulant que nous utilisions des macros personnalisés à la place des arguments, il serait judicieux de créer automatiquement les macros lors qu'une check command est choisie lors de la création d'un service.

**Comment by julienmathis** [comment]
Implemented
