### ISSUE TITLE
enhancement of monitoring interface

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2460]
---

Author Name: **carrillo manuel** (carrillo manuel)
Original Redmine Issue: 2057, https://forge.centreon.com/issues/2057
Original Date: 2010-11-29
Original Assignee: Julien Mathis

---

Bonjour,

Je souhaiterais savoir si il est possible d'intégrer des colonnes supplémentaires dans la vue monitoring dans une rochaine version :

Je m'explique :

1 - depuis GLPI (on se sert de celui-ci pour la gestion de parc avec notion de criticité) j'arrive à extraire la valeur de la criticité d'un serveur 3 niveaux standart haute Critique.

2 - je souhaiterais avoir une colonne dans la vue monitoring qui m'indique la criticité d'un check selon son serveur (info remontés par GLPI).

3 - dans une deuxième colonne je calculerai avec la valeur de la première colonne (la criticité valeur remonté par GLPI ou autre chose) et le statut du check (Critical, Warning, etc...) (l'impact) la valeur de la priorité d'incident définit en P1 P2 et P3 (ou plus selon les cas).

Ceci permettrait aux equipes de pilotes de pouvoir gérer les évènements en fonction de leur priorité, afin qu'il soient plus réactifs (ne se trompent pas dans leur analyse criticité +impact) ceci pour les aider à créer des incidents dans un outils de ticketing commercial dont je ne citerais pas le nom.

Tout d'abord est-ce possible à mettre en oeuvre (s'en trop de mal ou developpement spécifique) et si c'est possible ,y aurait 'il un impact si on upgrade centreon.

Je vous remercie d'avance pour vos réponses, ceci serait encore un plus à centreon étant donné qu'on se rapproche de plus en plus d'ITIL (impact criticité qui implicitement impacte les processus).

Cordialement

Latin_warrior

**Comment by julienmathis** [comment]
mise en place depuis la version 2.5. Mais pas aussi poussée. Nous allons retravailler le sujet.
