### ISSUE TITLE
Assign a Centreon Broker configuration to an host who are not a poller

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2486]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 5885, https://forge.centreon.com/issues/5885
Original Date: 2014-10-16

---

Hello,

Currently we can't assign a Centreon Broker configuration to an host who are not a poller.

Example : a database dedicated host with Centreon Broker Daemon on it. Or a dedicated host to buid the RRDs.

It would be greate to be able to build this kind of setup (and to be able to look at theses modules stats on the «Broker Statistics» pages.)

Regards.

**Comment by julienmathis** [comment]
Will not be implemented for the moment. Too few asks.
