### ISSUE TITLE
Dependancy: display desactivated services from form

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#25]
---

Author Name: **Laurent Pinsivy** (Laurent Pinsivy)
Original Redmine Issue: 3417, https://forge.centreon.com/issues/3417
Original Date: 2012-07-05
Original Assignee: Sylvestre Ho

---

In "Configuration -> Notifications -> Services" the select list for "Dependant Services" includes desactivated services

**Comment by ganoze** [comment]
This was fixed in an already released version of Centreon.
