### ISSUE TITLE
Collecteur toujours présent dans centreon_storage.instances après suppression de celui-ci

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2519]
---

Author Name: **Serge MARIE** (Serge MARIE)
Original Redmine Issue: 5958, https://forge.centreon.com/issues/5958
Original Date: 2014-11-13

---

Bonjour,

Après suppression d'un poller depuis "Configuration -> Centreon -> Collecteurs", le collecteur est toujours visible dans la liste déroulante "Monitoring -> Services -> 'Filtrer par Collecteur'".

Est-ce voulu ?

Sinon cela est dû à la présence de celui-ci dans la table "centreon_storage.instances".

**Comment by cmeschin** [comment]
Bonjour,
je confirme la persistance d'un poller supprimé dans la liste déroulante côté supervision.
le champ est bien présent dans la table centreon_storage.instances et positionné à 1 (cf PJ)
![centreon_cessat_deleted](https://cloud.githubusercontent.com/assets/8720203/11659444/908791f4-9dc8-11e5-94b9-5291bdf3e6ef.png)
versions:
Centreon 2.6.6
centreon-broker 2.10.1

cordialement,

**Comment by cmeschin** [comment]
Bonjour,
Les collecteurs supprimés sont toujours visibles en 2.7.4 dans le filtre par collecteur des pages de supervision.

est-ce normal que le ticket ait été fermé (géré dans un autre ticket peut-être...) ?
cdlt,
