### ISSUE TITLE
Rattachement des hostgroups aux Templates d'hôtes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2532]
---

Author Name: **Pascal Legrand** (Pascal Legrand)
Original Redmine Issue: 5096, https://forge.centreon.com/issues/5096
Original Date: 2014-01-08
Original Assignee: Julien Mathis

---

Bonjour,

serait-il possible de pouvoir rattacher directement les hostgroups au Templates d'hôtes afin qu'ils soient rattachés directement à un hôte quand on le rattache à un Template d'hôte

Merci

**Comment by lpinsivy** [comment]
duplicate #4655
