### ISSUE TITLE
Users - Expiration date on users accounts

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2554]
---

Author Name: **sebastien maury** (sebastien maury)
Original Redmine Issue: 5073, https://forge.centreon.com/issues/5073
Original Date: 2013-12-19

---

Hi,

It would be great to be able to set up an expiration for accounts we are creating in Centreon.

When the expiration date is reached, the user is automatically disabled.

It would be really useful specially for cases when you create a temporary user (for an expertise for example), or when you have a contract with a services company for a limited time.

Thanks in advance,
Regards,
Sébastien

**Comment by lpinsivy** [comment]
We won't implement this request in Centreon
