### ISSUE TITLE
Add the possibility to send message on Centreon web interface

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2611]
---

Author Name: **Laurent Pinsivy** (Laurent Pinsivy)
Original Redmine Issue: 2802, https://forge.centreon.com/issues/2802
Original Date: 2011-11-17
Original Assignee: Sylvestre Ho

---

Add the possibility for user/admin to send message to another user. When a user access to Centreon web interface a popup display the message.

Ajouter la possibilité dans l'interface Centreon qu'un utilisateur/administrateur puisse laisser un message(s) pour un utilisateur(s). Grâce à cela, l'utilisateur lors de sa prochaine connexion verra une popup contenant le message à son attention.

**Comment by julienmathis** [comment]
deprecated
