### ISSUE TITLE
Schedule host check

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2613]
---

Author Name: **Nicolas Cordier** (Nicolas Cordier)
Original Redmine Issue: 905, https://forge.centreon.com/issues/905

Original Assignee: Sylvestre Ho

---

Hi,

In service you can schedule a service check, in host you can schedule check of all services on the host but you can't schedule a check of this host, it would be awesome to add this feature :)

**Comment by julienmathis** [comment]
already implementee
