### ISSUE TITLE
Memory leak when displaying list of status

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2614]
---

Author Name: **Pierre Villard** (Pierre Villard)
Original Redmine Issue: 4905, https://forge.centreon.com/issues/4905
Original Date: 2013-09-30
Original Assignee: Julien Mathis

---

Hi guys !

I'm using Firefox and when I'm displaying a list of status there is a memory leak after a long period of time. Unfortunately, I need to be able to let run Firefox permanently. However when I let Firefox on a Centreon page displaying list of services refreshed frequently, I observe a memory leak as shown in the enclosed graph. As soon as I shut down Firefox, I get back all the memory. I guess there is something wrong when you are refreshing statuses for displayed services. You should have a look on jQuery usage I think.

**Comment by julienmathis** [comment]
We have checked, the problem can't be reproduced
