### ISSUE TITLE
rattachement des Templates de Services aux servicegroups

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2629]
---

Author Name: **Pascal Legrand** (Pascal Legrand)
Original Redmine Issue: 5449, https://forge.centreon.com/issues/5449
Original Date: 2014-04-06
Original Assignee: Julien Mathis

---

Objet de la demande :

Permettre de rattacher les TS aux servicegroups

**Comment by lpinsivy** [comment]
duplicate of #4656
