### ISSUE TITLE
Load configuration, missing connector.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#266]
---

Author Name: **Dorian Guillois** (Dorian Guillois)
Original Redmine Issue: 3990, https://forge.centreon.com/issues/3990
Original Date: 2012-12-05

---

Into Configuration/Monitoring Engines/Load, when we load main.cfg with connector, connector was ignore.

**Comment by ganoze** [comment]
Configuration load is only made to import Nagios configuration files. We will not implement this feature.
