### ISSUE TITLE
Checkbox et refresh

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2712]
---

Author Name: **Guillaume Watteeux** (Guillaume Watteeux)
Original Redmine Issue: 1070, https://forge.centreon.com/issues/1070
Original Date: 2009-07-24

---

Lorsque l'on sélectionne des services/hosts sur la page de monitoring (pour par exemple suspendre la notification de X services), l'ensemble des checkbox repasse à false dès qu'un rafraichissement de la page est effectuée.

Le problème ne se pose pas forcement lorsque l'on a uniquement 2 services, mais beaucoup plus lorsque cela concerne 70% de la page visualisée.

Vu sur Centreon2.1-RC6

**Comment by julienmathis** [comment]
deprecated
