### ISSUE TITLE
Donner la possibilité de voir le zendid depuis l'interface web

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2750]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 4967, https://forge.centreon.com/issues/4967
Original Date: 2013-11-05

---

Il serait pratique de pouvoir avoir le zend id sans taper de commandes type "zendid".
On pourrait afficher ça dans "Administration" ==> "Server status"

**Comment by lpinsivy** [comment]
Now available for all modules needed license in "Administration > Extensions" by clicking on "?" icon.
