### ISSUE TITLE
Show the exact number of hosts/services in the banner

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon#277]
Hi,

This is a feature request.

Currently, in the banner, only a coarse estimation of the number of hosts or services is shown for every statuses (example: 4k, 99+).

Could it be possible to have an option to show the exact numbers here instead?

**Comment by ponchoh** [comment]
# 👋 

@StefThomas

I understand your argument. We are currently having an internal discussion about this. ⚖ What I can recommend for now is to open a conversation and introduce it to the rest of the community via 💡 https://thewatch.centreon.com/ideas as that is the main way to discuss these requests. This is also good in case you have other features you want to discuss or get involved with.

![image](https://user-images.githubusercontent.com/85764737/203838087-29c36a27-790e-483f-97fa-51af7cad37f4.png)

Thank you.

**Comment by StefThomas** [comment]
I opened an Idea on TheWatch. From now on I’ll prefer TheWatch for feature request and reserve GitHub for bugs.

I think Github is better for bugs because it’s publicly available without the need for an inscription. It’s better for links, for search engines, and it has a way greater audience. The GitHub UI also is far better than the one in TheWatch, for editing messages for example.

TheWatch “idea”: https://thewatch.centreon.com/ideas/show-the-exact-number-of-hosts-services-in-the-banner-1216 (inscription needed).

**Comment by StefThomas** [comment]
The subject may now be tracked on TheWatch but I still don’t understand why you stopped using Github for issues and feature requests. The Github issues may be seen anonymously. Many people have a Github account and many won’t make the effort to create an account to TheWatch just to  participate in the Centreon project. This is about transparency, which is a basic pillar for opensource software.
