### ISSUE TITLE
Action & notes URL doesn't evaluate custom macros

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2800]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 3863, https://forge.centreon.com/issues/3863
Original Date: 2012-10-31

---

Hi, 

Specifying notes or action URLs using custom macros like $_HOST<macroname>$ doesn't work, because these macros aren't evaluated in centreon-web. 

pch

**Comment by lpinsivy** [comment]
linked to #4277
