### ISSUE TITLE
Possibility to choose multiple poller to send / reload configuration

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2802]
---

Author Name: **Nicolas COULIN** (Nicolas COULIN)
Original Redmine Issue: 6343, https://forge.centreon.com/issues/6343
Original Date: 2015-04-16

---

Hi,

Actually, we have the choice between All poller, or one poller. Why not use box to select only poller concerned ?

Moreover, you could add an option to auto select poller whose configuration has changed.

Thanks,

**Comment by julienmathis** [comment]
Ok since 2.7.x.
