### ISSUE TITLE
Date of update for a Centreon module

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2813]
---

Author Name: **Tonio Allamellou** (Tonio Allamellou)
Original Redmine Issue: 2941, https://forge.centreon.com/issues/2941
Original Date: 2012-01-05
Original Assignee: Sylvestre Ho

---

Hi,
Is it possible to have the date of update for the Centreon modules in the tab [Administration > Modules. I mean when you update a Centreon module you can see the information written in the module table. 
Regards,

**Comment by julienmathis** [comment]
useless
