### ISSUE TITLE
Usage problem when no pooler is selected at SNMP traps configuration generation

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2815]
---

Author Name: **Alexandru Vilau** (Alexandru Vilau)
Original Redmine Issue: 3732, https://forge.centreon.com/issues/3732
Original Date: 2012-09-28

---

When traps are generated no poller is selected and no error message if we click generate button

I propose one of the two following fixes:
* Select by default the main pooler and don't allow empty selection
* Display an error message if no pooler is selected

**Comment by julienmathis** [comment]
already fixed.
