### ISSUE TITLE
Superposition de graph

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2816]
---

Author Name: **julien breton** (julien breton)
Original Redmine Issue: 2765, https://forge.centreon.com/issues/2765
Original Date: 2011-11-03
Original Assignee: david porte

---

Serait-il possible d'ajouter une fonction de superposition de graphique ?

Lorsque l'on coche 1 ou plusieurs services, l'idée serait d'avoir un bouton permettant de superposer les graphs. Dans notre cas ce serait très pratique par exemple pour superposer un graph de rapport signal/bruit (RF) et de puissance de transmission.

Il faudrait cependant que l'un des graphs ait une valeur de transparence plus forte que le premier.

Merci

**Comment by lpinsivy** [comment]
linked to #3714
