### ISSUE TITLE
Centreon-Engine ne redémarre plus après la migration vers 2.6.0

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2847]
---

Author Name: **David DU SERRE-TELMON** (David DU SERRE-TELMON)
Original Redmine Issue: 6401, https://forge.centreon.com/issues/6401
Original Date: 2015-05-19

---

Bonjour,

La configuration de sudo est incorrecte suite à la mise à jour de Centreon 2.5.4 vers 2.6.0 (via RPM). 

Fichier de configuration après la mise à jour :

```## BEGIN: CENTREON SUDO
#Add by CENTREON installation script
User_Alias      CENTREON=apache,nagios,centreon
Defaults:CENTREON !requiretty
## Snmptrapd Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/snmptrapd restart
## CentStorage
CENTREON   ALL = NOPASSWD: /etc/init.d/centstorage *
1. Nagios Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/nagios restart
1. Nagios stop
CENTREON   ALL = NOPASSWD: /etc/init.d/nagios start
1. Nagios stop
CENTREON   ALL = NOPASSWD: /etc/init.d/nagios stop
1. Nagios reload
CENTREON   ALL = NOPASSWD: /etc/init.d/nagios reload
1. Nagios test config
CENTREON   ALL = NOPASSWD: /usr/sbin/nagios -v *
1. Nagios test for optim config
CENTREON   ALL = NOPASSWD: /usr/sbin/nagios -s *
1. ndo2db restart
CENTREON   ALL = NOPASSWD: /etc/init.d/ndo2db restart
1. ndo2db start
CENTREON   ALL = NOPASSWD: /etc/init.d/ndo2db start
1. ndo2db stop
CENTREON   ALL = NOPASSWD: /etc/init.d/ndo2db stop
## END: CENTREON SUDO
```

Il manque les services pour Centreon Broker et Centreon Engine.

Exemple de fichier fonctionnel (utilisé avant la MAJ, sans Nagios ni NDO) :```
## BEGIN: CENTREON SUDO
#Add by CENTREON installation script
User_Alias      CENTREON=apache,nagios,centreon
Defaults:CENTREON !requiretty

1. Monitoring engine Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine* restart
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine restart
1. Monitoring engine reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine* reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine reload
1. Monitoring engine force-reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine* force-reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine force-reload
1. Monitoring engine test config
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine* -v *
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -v *
1. Monitoring engine test for optim config
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine* -s *
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -s *
1. Snmptrapd Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/snmptrapd restart
1. Centreontrapd restart
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd restart
1. Centreontrapd reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd reload
1. CentStorage Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/centstorage restart
1. CentStorage stop
CENTREON   ALL = NOPASSWD: /etc/init.d/centstorage stop
1. CentStorage start
CENTREON   ALL = NOPASSWD: /etc/init.d/centstorage start
1. Broker engine Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd* restart
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd restart
1. Broker engine reload
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd* reload
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd reload
## END: CENTREON SUDO

```

Cordialement,

**Comment by kduret** [comment]
Duplicate #357
