### ISSUE TITLE
Problème suppression d'un commentaire sur un service supprimé

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2857]
---

Author Name: **Mathieu Cinquin** (Mathieu Cinquin)
Original Redmine Issue: 6016, https://forge.centreon.com/issues/6016
Original Date: 2014-12-04

---

Bonjour,

Il n'est pas possible de supprimer le commentaire d'un service qui a été acquitté après qu'il ait été supprimé de la configuration de Centreon.

Cordialement.

**Comment by julienmathis** [comment]
J'ai donc désactivé de l'affichage les services supprimés. C'est beaucoup plus simple.

Merci
