### ISSUE TITLE
UI-Notification / ACL

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2879]
---

Author Name: **jeremy rouanne** (jeremy rouanne)
Original Redmine Issue: 6418, https://forge.centreon.com/issues/6418
Original Date: 2015-06-03

---

Bonjour,

Les UI-Notifications ne tiennent pas compte des ACL de l'utilisateur et affiche des pop-up pour les alertes des hôtes/services ne faisant pas parti de son périmètres.
Le problème est le même pour les alertes sonores.

**Comment by lpinsivy** [comment]
already done
