### ISSUE TITLE
Warning Service 'CPU' on host '------------------' has no default contacts or contactgroups defined et les contacts ne semblent pas importés!

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2908]
---

Author Name: **Sébastien Boulianne** (Sébastien Boulianne)
Original Redmine Issue: 6167, https://forge.centreon.com/issues/6167
Original Date: 2015-03-02
Original Assignee: Maximilien Bersoult

---

Bonjour,

Admettons que je configure mon service comme ceci:
http://imgur.com/Yq5Vfx5,CsDCvGZ,yLAWn7m#1

Que je sélectionne "Inherit Contacts from hosts" et que je n'ajoute pas de contacts ni de contacts groups... Tel que c'est décrit: http://imgur.com/Yq5Vfx5,CsDCvGZ,yLAWn7m#0

Quand je vais dans Configuration > Monitoring Engines et que j'exporte la configuration, j'obtiens ces warnings.

Warning Service 'CPU' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Disk-C' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Disk-E' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Memory' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Ping' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Swap' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'CPU' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Disk-C' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Disk-D' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Memory' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Ping' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Swap' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'Ping' on host 'HOSTNAME1' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-cpu-usage' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-io-aborted' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-io-device' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-io-kernel' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-io-queue' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-io-read' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-io-resets' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-io-write' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-mem-usage' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-net-receive' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-net-send' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-net-usage' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-runtime-issues' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'vmware-dc-runtime-status' on host 'HOSTNAME2' has no default contacts or contactgroups defined!
Warning Service 'CPU' on host 'HOSTNAME3' has no default contacts or contactgroups defined!
Warning Service 'Disk-C' on host 'HOSTNAME3' has no default contacts or contactgroups defined!
Warning Service 'Memory' on host 'HOSTNAME3' has no default contacts or contactgroups defined!
Warning Service 'Ping' on host 'HOSTNAME3' has no default contacts or contactgroups defined!
Warning Service 'Swap' on host 'HOSTNAME3' has no default contacts or contactgroups defined!
Warning Service 'CPU' on host 'HOSTNAME4' has no default contacts or contactgroups defined!
Warning Service 'Disk-C' on host 'HOSTNAME4' has no default contacts or contactgroups defined!
Warning Service 'Memory' on host 'HOSTNAME4' has no default contacts or contactgroups defined!
Warning Service 'Ping' on host 'HOSTNAME4' has no default contacts or contactgroups defined!
Warning Service 'Swap' on host 'HOSTNAME4' has no default contacts or contactgroups defined!

Les contacts ne semblent pas importés: http://imgur.com/Yq5Vfx5,CsDCvGZ,yLAWn7m#2

Merci de régler ce problème­.

Sébastien

**Comment by julienmathis** [comment]
Hello Ganoze, 

Je pense que c'est le problème que tu es en train de corriger ?

++

**Comment by ganoze** [comment]
Oui ca semble être un duplica du ticket centreon/centreon-engine#19
