### ISSUE TITLE
Problème menu d'action déroulant pour certains services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#291]
---

Author Name: **Jérôme V.** (Jérôme V.)
Original Redmine Issue: 2929, https://forge.centreon.com/issues/2929
Original Date: 2011-12-30
Original Assignee: Sylvestre Ho

---

J'utilise Centreon 2.3.3 avec Nagios 3.3.1.

Pour certains services les utilisateurs avec des droits non admin ne peuvent pas lancer de "Schedule immediate check (forced)" (ou toutes autres commandes d'ailleurs) via le menu déroulant dans Monitoring >> Services.
Par contre avec un utilisateur qui a des droits d'admin aucun problème.
Cependant si ces mêmes utilisateurs utilisent le bouton "Schedule immediate check (forced)" directement dans la page du service cela fonctionne sans problème.

A noter qu'aucun message d'erreur ne semble être renvoyé dans Centreon.

Cela se produit, entre autre, avec le service:
G0/22 - Interco HSR vers Auber

Pour tester j'ai lancé un tail -f sur le fichier de log nagios et quand le problème se produit il n'y a aucun log dans nagios ce qui laisse fait penser que c'est centreon qui ne transmet pas la demande de check.

**Comment by julienmathis** [comment]
deprecated
