### ISSUE TITLE
Error when doing a "Run Nagios debug (-v)" on configuration export if local poller is deactivated

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2921]
---

Author Name: **Frank Enser** (Frank Enser)
Original Redmine Issue: 2671, https://forge.centreon.com/issues/2671
Original Date: 2011-10-05

---

Hi,

if you deactivate your local poller and issue a "Run Nagios debug (-v)" for your nagios configuration, you get an sudo syntax error. Perhaps because centreon cannot find the path to the nagios binary and submits an emptry string to sudo.

Error is: "{-e file [...] | -i | -s | <command>}"

Thanks
Frank

**Comment by julienmathis** [comment]
Central polling system is mandatory
