### ISSUE TITLE
Unable to load Status Map Image on host template

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2946]
---

Author Name: **Nicolas COULIN** (Nicolas COULIN)
Original Redmine Issue: 6338, https://forge.centreon.com/issues/6338
Original Date: 2015-04-13

---

Hi,

When I want to load image for my template, it does not work

[error] [client ] PHP Notice:  Undefined variable: pos in /usr/share/centreon/www/include/configuration/configObject/host_template_model/listHostTemplateModel.php on line 191, referer: http://centweb.lan.net/centreon/main.php?p=60103&o=c&host_id=1891

Centreon 2.5.3

Thanks,

**Comment by julienmathis** [comment]
Hello, 

Can we have more information about this problem. The log error is not linked to your problem.
