### ISSUE TITLE
Catégories d'hôtes et Modèles D'hôtes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2950]
---

Author Name: **Julien Flamand** (Julien Flamand)
Original Redmine Issue: 5510, https://forge.centreon.com/issues/5510
Original Date: 2014-04-30

---

Bonjour, 

J'ai remarqué que lorsqu'on affecte une catégorie d'hôte à un modèle d'hote, celle ci ne se répercute pas sur les hôtes héritant du modèle, c'est pourtant le cas pour les catégories de services. Cela implique une lourdeur d'administration des catégories d'hôtes car il faut manuellement spécifier chaque hôte.

Est-il possible d'intégrer cette fonctionnalité ? 

Merci par avance, 

Cordialement,

Julien Flamand.

**Comment by julienmathis** [comment]
deprecated
