### ISSUE TITLE
Adapt form infput size to the intended content

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#296]
---

Author Name: **Lionel Assepo** (Lionel Assepo)
Original Redmine Issue: 4520, https://forge.centreon.com/issues/4520
Original Date: 2013-06-05

---

It should be useful in Centreon to adapt the size of input field to the intended contnent.
For example, some path field are too small and some numeric field are too big.

**Comment by ganoze** [comment]
This was fixed in an already released version of Centreon.
