### ISSUE TITLE
Possibility to choose between Hostname or Alias in Views Graph Tab.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#2968]
---

Author Name: **Nicolas COULIN** (Nicolas COULIN)
Original Redmine Issue: 1261, https://forge.centreon.com/issues/1261
Original Date: 2009-10-09

---

Hi,

Is it possible to have the possibility to choose between Hostname or Alias in Views Graph Tab because Hostname are not really explicit when you use nommenclature name as PC-01-01-01.

Clients prefered to see APP01 or SQL01

Thanks.

**Comment by julienmathis** [comment]
No, it's not possible !
