### ISSUE TITLE
Centstorage ne dépile pas service-perfdata, les metrics sont toutes à "nan"

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3017]
---

Author Name: **Romain Aubry** (Romain Aubry)
Original Redmine Issue: 2599, https://forge.centreon.com/issues/2599
Original Date: 2011-08-29
Original Assignee: Julien Mathis

---

Bonjour,

Je suis sous centreon 2.2.0 sous suse 10

J'ai un problème avec mes graphs centreon et donc avec le module centstorage.
Cela fait une semaine que les graphs ne se font plus les symptômes sont les suivants :
- Au départ la base data_bin a été corrompue, je l'ai donc réparée puis j'ai redémarré centstorage mais les graphs n'ont pas recommencé à se tracer.
- J'ai testé de régénéré une base rrd via l'interface web administration->options->centstorage->gérer mais rien
- J'ai testé les deux commandes suivantes :
perl -w /usr/local/centreon-2/cron/archiveDayLog -r
perl -w /usr/local/centreon-2/bin/logAnalyser -a
Mais ça n'a rien donné
- je n'ai rien d'anormal dans les logs de centstorage
- le fichier services-perfdata ne fait que se remplir. J'ai lu dans pas mal d'endroit que le process centstorage était censé le "manger". Donc le miens ne le fait apparemment pas.
- les fichiers de metrics (/var/lib/centreon/metrics) sont bien créés mais ne se remplissent plus.

Je reste à votre disposition pour tout élément complémentaire qu'il vous faudrait pour m'aider à faire "réapparaitre" mes graphiques.

**Comment by julienmathis** [comment]
deprecated
