### ISSUE TITLE
Problème lors de l'ajout nouveau d'un nouveau monitoring engine

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3023]
---

Author Name: **Alexandre Allard** (Alexandre Allard)
Original Redmine Issue: 6300, https://forge.centreon.com/issues/6300
Original Date: 2015-03-31

---

Lors de l'ajout d'un nouveau monitoring engine *Configuration > Monitoring Engines > main.cfg*, le monitoring engine ne se crée pas et je me retrouve avec une erreur SQL dans */var/log/centreon/sql-error.log*

<code>
DB Error: unknown error QUERY : INSERT INTO cfg_nagios...
</code>

En rejouant la requête à la main dans MySQL, cela me retourne l'erreur suivante :

<code>
ERROR 1366 (22007): Incorrect integer value: '.-1.' for column 'debug_level' at row 1
</code>

J'ai donc regardé dans le code de Centreon et dans le fichier */usr/share/centreon/www/include/configuration/configNagios/DB-Func.php* à la ligne *312* j'ai :

<code class="php">
$rq .= "'.$level.', ";
</code>

Il suffit juste de retirer les "." comme suit : 

<code class="php">
$rq .= "'$level', ";
</code>

Pour information, j'utilise la dernière version stable de Centreon présente sur les dépots CES.

**Comment by julienmathis** [comment]
Do you use MySQL 5.6 with strict mode ?
