### ISSUE TITLE
Clapi - PHP Fatal erro POLLERGENERATE

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3036]
---

Author Name: **Denis Garandel** (Denis Garandel)
Original Redmine Issue: 6157, https://forge.centreon.com/issues/6157
Original Date: 2015-02-20

---

Bonjour,

Depuis Centreon 2.5.4 (fonctionnait en 2.5.1) j'ai l'erreur suivante avec Clapi :

1. clapi -u user -p password -a POLLERGENERATE -v 4
PHP Fatal error:  Call to a member function getData() on a non-object in /usr/local/centreon/www/include/configuration/configGenerate/genHosts.php on line 243

Cela se produit sur tous les hosts ayant le champ "Severity Level" de renseigné.

Clapi v1.5.2 et v1.7.0

**Comment by julienmathis** [comment]
Kevin,

You are currently working on Centreon CLAPI. Can you fix this problem ?

Thanks

**Comment by kduret** [comment]
This has been fixed on Centreon 2.6. Here is the commit : 
https://github.com/centreon/centreon/commit/d3f9bede850ab54a2ad40dca04338e1ac0225764

**Comment by Tpo76** [comment]
OK
