### ISSUE TITLE
persistance du flag "create services linked to the template too"

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3039]
---

Author Name: **Pascal Legrand** (Pascal Legrand)
Original Redmine Issue: 3747, https://forge.centreon.com/issues/3747
Original Date: 2012-10-04
Original Assignee: Pascal Legrand

---

Permettre le choix de créer ou non a la volée des services sur des hôtes existant via les templates.

**Comment by julienmathis** [comment]
Planned in Centreon Web 3.
