### ISSUE TITLE
Bug dans les graphiques

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3047]
---

Author Name: **Maxime Peccoux** (Maxime Peccoux)
Original Redmine Issue: 238, https://forge.centreon.com/issues/238

---

Bonjour,

Lorsque l'on affiche les graphiques avec la vue Jour, Semaine, Mois, Année. Les courbes sont écrasées pour les vues par année et par mois et les valeurs deviennent incorrectes: Flagrant sur le champ "Max"

Merci

**Comment by julienmathis** [comment]
Will be integrated into Centreon Web 2.8.
