### ISSUE TITLE
Creation de servicegroup incomplète

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3054]
---

Author Name: **Tiago  Pires Gomes** (Tiago  Pires Gomes)
Original Redmine Issue: 4593, https://forge.centreon.com/issues/4593
Original Date: 2013-07-05

---

Versions testées :
Centreon 2.3.9 et Centreon 2.4.1

Soit le cas suivant :
Un host unitaire H1 avec un service unitaire check_Tomcat.
Un hostgroup HG composé de 2 machines H2 et H3.
Un service check_Tomcat rattaché au hostgroup HG contenant donc H2 et H3.

-> Donc toutes les machines d'une manière ou d'une autre sont gérées en check_Tomcat

Maintenant je souhaite créer un servicegroup Tomcat, (dans la page de création de servicegroup) j'inclus le host unitiare dans la case supérieure H1 - Tomcat. Mais il m'est impossible de choisir aussi H2-Tomcat (non présent dans la case du haut). Je peux uniquement rajouter le service attaché au hostgroup soit H2 et H3 or je souhaite exclure H3.

**Comment by julienmathis** [comment]
Service par hostgroup n'est pas une bonne pratique. Ne plus l'utiliser mais utiliser des templates.
