### ISSUE TITLE
Comportement en cas de conflicts de Nagios Configuration Load 

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3074]
---

Author Name: **romain vrignaud** (romain vrignaud)
Original Redmine Issue: 1557, https://forge.centreon.com/issues/1557
Original Date: 2010-02-16

---

Lors de l'import d'une configuration Nagios dans Centreon,
le comportement, en cas d'existence de l'objet dans la base, n'est pas le même entre les différents objets.
ex: si j'importe la configuration d'un host ou d'un contact alors qu'ils sont déjà définis en BD.
Si l'objet est un host, la configuration de la BD sera changée afin de respecter la configuration importée.
Si l'objet n'est pas un host, la configuration importée est ignorée.

Version Centreon 2.1.4
Nouvelle installation.

**Comment by julienmathis** [comment]
Cette fonctionnalité va etre abandonnée dans les prochaines versions. Nous ne pouvons investir de temps sur cette correction
