### ISSUE TITLE
ACL - pb affichage catégorie d'hôte dans les pages de configuration

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#308]
---

Author Name: **cedric meschin** (cedric meschin)
Original Redmine Issue: 6353, https://forge.centreon.com/issues/6353
Original Date: 2015-04-21

---

Bonjour,
Un utilisateur soumis à ACL avec accès à la configuration des hôtes (que ce soit lecture seule ou lecture/écriture), ne voit pas les catégories d'hôtes associées à celui-ci via le manu Configuration -> Hôtes -> onglet "Relation". Les groupes d'hôtes quant à eux sont bien visibles (cf CENTREON_ACL_RO_host_categorie.png et CENTREON_ACL_RW_host_categorie.png).
Via le menu Configuration -> Hôtes-> catégories, on retrouve bien l'hôte dans la catégorie souhaitée (cf CENTREON_ACL_categorie.png).

**Comment by cmeschin** [comment]
Bonjour,
Il s'agit du même ticket que celui-ci #4315 mais le problème est toujours présent dans le version 2.7.4

cordialement,
