### ISSUE TITLE
metrology / rrdtool / graphing library

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3082]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 3316, https://forge.centreon.com/issues/3316
Original Date: 2012-05-12

---

Hi, 
I'm interesting in graphic representations of metrics/virtual/meta-services in Centreon (#1979, #2012, ...);

It seems that some metrology/frontend solutions are progressing well : 
- canopsis.org
- graphene / graphite
...
Also, graph library seems to be able to replace RRDTool well : 
- highcharts.com
- pchart.net (2.0)
- javascript-rrd

What are the positions of Centreon about that : integration of libraries to provide graphing features quickly ? future of RRDTool ? studying performance aspects ("NoSQL" / full-RAM storage seems to be a solution choosed to replace RRD DB) ? 

Thanks,

**Comment by julienmathis** [comment]
Integrated in Centreon Web 2.8.
