### ISSUE TITLE
Invisible HostGroups

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3092]
---

Author Name: **Pierre Marconnier** (Pierre Marconnier)
Original Redmine Issue: 6466, https://forge.centreon.com/issues/6466
Original Date: 2015-07-15

---

Hi,

Creating hostgroups via CLAPI is a real pleasure, and it allows us to create a hostgroup without assigning any host to it (which is not possible through the web interface).
The problem is this hostgroup doesn't appear anywhere for the non-admin users. Even if you put "no restriction" ACLs (without checking the Admin box), the user won't see the HG anywhere in the web interface.
My solution to "solve" the problem temporarily is to assigned a disabled host to any HG I create via CLAPI. This makes the HG visible for my "Hosts Creators" Access Groups.

Regards,

**Comment by lpinsivy** [comment]
Possibility to manage ACL resources via Centreon API
