### ISSUE TITLE
MySQL socket cannot be customized with Centreon's PERL scripts

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3102]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 5872, https://forge.centreon.com/issues/5872
Original Date: 2014-10-10

---

Hello,

I'm working with a specific environnement. My MySQL server is using a specific directory to defined the MySQL socket path.
I found that Centreon's PERL scripts are not able to use a specific MySQL Socket path. Centcore or centstorage must bring this possibility.

Also, I found a workaround by hard coding the database connection class in /usr/lib/perl5/vendor_perl/5.8.8/centreon/common/db.pm.

In the connect() function, add the "mysql_socket" directive after the port definition.
The modification is looking like this.

```
} else {
            $self->{instance} = DBI->connect(
                "DBI:".$self->{type}
                    .":".$self->{db}
                    .":".$self->{host}
                    .":".$self->{port}
                    .":mysql_socket=/opt/mysql-server/mysql.sock",
                $self->{user},
                $self->{password},
                { "RaiseError" => 0, "PrintError" => 0, "AutoCommit" => 1 }
            );
        }


```

Best regards.

**Comment by julienmathis** [comment]
deprecated
