### ISSUE TITLE
Date display format not consistent (dd/mm/yyyy instead of yyyy/mm/dd)

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#312]
---

Author Name: **ben bomgardner** (ben bomgardner)
Original Redmine Issue: 1311, https://forge.centreon.com/issues/1311
Original Date: 2009-11-05

---

The date format in the main display table for services/hosts shows dd/mm/yyyy (under Last Check). This format is also shown in the mouse over popup under services for the Last Check, Next Check, etc. When entering the host or service page, these stats are shown in the normal date format yyyy/mm/dd.

This formatting should be consistent, and I am unaware of a user option to configure this.
The official demo has the same behavior as my installation.  (I have not looked at any current development builds, so I don't know if this is fixed there or not.)

**Comment by ganoze** [comment]
This is a duplicate of #102 .
