### ISSUE TITLE
Ability to Configure Report SLA times

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3132]
---

Author Name: **Gavin Williams** (Gavin Williams)
Original Redmine Issue: 1120, https://forge.centreon.com/issues/1120
Original Date: 2009-08-07

---

Hi there, 

Can I request the ability to define a SLA Style report within the CentWeb. 
We need to be able to report on the Availability of Service/Host Groups for a specific time/range - E.g. 09:00-17:30 only, Monday to Friday... 

Currently I can only select Monday 9:00 to Friday 17:30, but that includes all the out-of-hours time aswell. 

Regards
Gavin

**Comment by julienmathis** [comment]
deprecated
