### ISSUE TITLE
migration 2.1.13 to 2.2.1 second poller configuration field erased (broker conf)  and problem with status_file in nagios_cfg

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3145]
---

Author Name: **BAROTIN stephane** (BAROTIN stephane)
Original Redmine Issue: 2487, https://forge.centreon.com/issues/2487
Original Date: 2011-06-09

---

i migrate to 2.2.1.

i have two pollers a principal and a secondary.
after migration my remote poller becomes red in the interface(and no mysql update in censtatus base for the secondary poller).

to be sure, all is ok, i push all nagios configuration from centreon.

I discovered a problem : 
for the secondary poller (nagios_cfg_2 the remote poller) some field were erased : the line for broker configuration  for ndomod.o diseapeared

workaround : 
 --> i destruct the nagios_cfg_2 for this poller, and duplicate the nagios_cfg_1 (rename it to nagios_cfg_2, and make little change for name, poller)  and push configuration --> this correct the problem

just after another problems comes !... 
the statusfile for nagios becomes, on my remote poller,  /var/lib/nagios/status.dat and my principal poller have a /var/lib/nagios/status.log (i discover that because i have a local script to check nagios state so it becomes totaly red).
With 2.2.1 in nagios_cfg the field statusfile in phpinterface desapeared.
so i can renew it. 

workaround :
i take the way, if we don't have a field to initialize it, i put on the mysql field the standard configuration (NULL instead of /var/lib/nagios/status.log) .

becarefull i write this from memory (random syntax) :
mysql > use centreon ; 
mysql > update status_file to  NULL from nagios_cfg where id_nagios = 1 ; 
    
and i correct my commands check_local_nagios and use nagios.dat file.

i push this like a bug to you in order to help someone with the same problems,
and if problems come from migration scripts in order to help to correct them.

bye
Stef

**Comment by julienmathis** [comment]
deprecated
