### ISSUE TITLE
Enable/Disable status disappear during Create Services linked to the Template too

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3180]
---

Author Name: **Raphael Troiano** (Raphael Troiano)
Original Redmine Issue: 3777, https://forge.centreon.com/issues/3777
Original Date: 2012-10-12

---

Hi,

I massively use hosttemplate to add new host.
I have hosttemplate with service template which are linked to.
Sometime, i have a service template disabled but when i use it during "Create Services linked to the Template too", the disable status disappear.

Could you fix it?
Thx,

(centreon 2.3.9 & 2.4-RC)

**Comment by julienmathis** [comment]
deprecated
