### ISSUE TITLE
Custom Views : views library instead of sharing system ?

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3183]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 3866, https://forge.centreon.com/issues/3866
Original Date: 2012-11-02

---

Hi, 

For >2.4 releases you can replace the sharing system with a "views library". 

A user can select custom views created by others, based on the description (showing the creators accounts names it's not illogical in this situation, but the locked concept is not relevant).
E.g. pick a view in the global shared library, or create your own. 

Many "2.0 oriented websites" allow this (bank & trading dashboards, CMS, medias & social platforms, etc.). 

pch

originally related to #3851

**Comment by julienmathis** [comment]
ok since 2.7.x
