### ISSUE TITLE
Filter on service doesn't work in "Views --> Graphs"

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#322]
---

Author Name: **Stephane Duret** (Stephane Duret)
Original Redmine Issue: 5914, https://forge.centreon.com/issues/5914
Original Date: 2014-10-28

---

Hello,

If I want to filter on host (field at the top on the right) in page "Views --> Graphs", it works fine (right.jpg).
But if I want to filter on a service (field at the top on the right), it doesn't work (wrong.jpg).

Regards

**Comment by leoncx** [comment]
Work fine for me in 2.6.1
