### ISSUE TITLE
Caractère speciaux contact

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3226]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 6438, https://forge.centreon.com/issues/6438
Original Date: 2015-06-18

---

Lorsque le nom d'un contact contient un accent, il y a une erreur au niveau de la génération de la configuration.
Pour éviter cette erreur :

- Editer /usr/share/centreon/www/include/configuration/configGenerate/genContacts.php

Ligne 50 
Remplacer :  $queryGetUserAlias = 'SELECT contact_name FROM contact WHERE contact_id = %d';
Par : $queryGetUserAlias = 'SELECT REPLACE(contact_name,"\'","") as contact_name FROM contact WHERE contact_id = %d';

**Comment by julienmathis** [comment]
Sorry But I can't reproduce the problem. Can you test on the last 2.6.1 ?

Thanks
