### ISSUE TITLE
Add the possibility to customize popup in UI Notifications

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3243]
---

Author Name: **charles judith** (charles judith)
Original Redmine Issue: 5223, https://forge.centreon.com/issues/5223
Original Date: 2014-02-18

---

Hi,

Is it possible to add the possibility to customize popup in UI Notifications ?

For example if I want popups display on the left side of my screen and not on the right side.
## Thanks,

Charles

**Comment by julienmathis** [comment]
won't be implemented
