### ISSUE TITLE
Upgrade block poller config push

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3248]
---

Author Name: **donkishoot -** (donkishoot -)
Original Redmine Issue: 2601, https://forge.centreon.com/issues/2601
Original Date: 2011-08-31
Original Assignee: Guillaume Watteeux

---

Hi,

Since a lot of upgrade, i think i found a recurrent bug.
It seems that after every upgrade on my pollers i had to delete the nagios etc files.
If i do not that, the permissions on files prevent centcore from updating nagios conf files.

[root@srv78supervision etc]# ls -ail
total 224
3242661 drwxrwxr-x  2 nagios apache  4096 mai  3 13:33 .
3242261 drwxr-x--x 11 nagios nagios  4096 avr 28  2010 ..
3240882 -rwxrwxr-x  1 apache apache  1851 mai 31 09:26 cgi.cfg
3240891 -rwxrwxr-x  1 apache apache 18882 mai 31 09:26 checkcommands.cfg
3240904 -rwxrwxr-x  1 apache apache  2714 mai 31 09:26 contactgroups.cfg
3240905 -rwxrwxr-x  1 apache apache  7252 mai 31 09:26 contacts.cfg
3240906 -rwxrwxr-x  1 apache apache  1089 mai 31 09:26 dependencies.cfg
3240907 -rwxrwxr-x  1 apache apache  1089 mai 31 09:26 escalations.cfg
3240909 -rwxrwxr-x  1 apache apache  5287 mai 31 09:26 hostgroups.cfg
3240910 -rwxrwxr-x  1 apache apache 16969 mai 31 09:26 hosts.cfg
3240912 -rwxrwxr-x  1 apache apache  1949 mai 31 09:26 hostTemplates.cfg
3240913 -rwxrwxr-x  1 apache apache  4390 mai 31 09:26 misccommands.cfg
3240914 -rwxrwxr-x  1 apache apache  4318 mai 31 09:26 nagios.cfg
3240918 -rwxrwxr-x  1 apache apache  3593 mai 31 09:26 nagiosCFG.DEBUG
3240919 -rwxrwxr-x  1 apache apache  1445 mai 31 09:26 ndo2db.cfg
3240920 -rwxrwxr-x  1 apache apache  1357 mai 31 09:26 ndomod.cfg
3241173 -rwxrwxr-x  1 apache apache  1279 mai 31 09:26 resource.cfg
3241381 -rwxrwxr-x  1 apache apache  6066 mai 31 09:26 servicegroups.cfg
3241416 -rwxrwxr-x  1 apache apache 16541 mai 31 09:26 services.cfg
3241897 -rwxrwxr-x  1 apache apache 68166 mai 31 09:26 serviceTemplates.cfg
3242412 -rwxrwxr-x  1 apache apache  4891 mai 31 09:26 timeperiods.cfg
[root@srv78supervision etc]# rm -rf *
[root@srv78supervision etc]# ls -ail
total 8
3242661 drwxrwxr-x  2 nagios apache 4096 aoû 31 10:25 .
3242261 drwxr-x--x 11 nagios nagios 4096 avr 28  2010 ..
## push conf ##
[root@srv78supervision etc]# ls -ail
total 228
3242661 drwxrwxr-x  2 nagios apache  4096 aoû 31 10:26 .
3242261 drwxr-x--x 11 nagios nagios  4096 avr 28  2010 ..
3240866 -rw-r--r--  1 nagios nagios  1851 aoû 31 10:26 cgi.cfg
3240891 -rw-r--r--  1 nagios nagios 18882 aoû 31 10:26 checkcommands.cfg
3240904 -rw-r--r--  1 nagios nagios  2714 aoû 31 10:26 contactgroups.cfg
3240905 -rw-r--r--  1 nagios nagios  7252 aoû 31 10:26 contacts.cfg
3240906 -rw-r--r--  1 nagios nagios  1089 aoû 31 10:26 dependencies.cfg
3240907 -rw-r--r--  1 nagios nagios  1089 aoû 31 10:26 escalations.cfg
3240909 -rw-r--r--  1 nagios nagios  5287 aoû 31 10:26 hostgroups.cfg
3240910 -rw-r--r--  1 nagios nagios 16970 aoû 31 10:26 hosts.cfg
3240912 -rw-r--r--  1 nagios nagios  1949 aoû 31 10:26 hostTemplates.cfg
3240913 -rw-r--r--  1 nagios nagios  4390 aoû 31 10:26 misccommands.cfg
3240914 -rw-r--r--  1 nagios nagios  4298 aoû 31 10:26 nagios.cfg
3240918 -rw-r--r--  1 nagios nagios  3573 aoû 31 10:26 nagiosCFG.DEBUG
3240919 -rw-r--r--  1 nagios nagios  1445 aoû 31 10:26 ndo2db.cfg
3240920 -rw-r--r--  1 nagios nagios  1357 aoû 31 10:26 ndomod.cfg
3240963 -rw-r--r--  1 nagios nagios  1279 aoû 31 10:26 resource.cfg
3240964 -rw-r--r--  1 nagios nagios  8515 aoû 31 10:26 servicegroups.cfg
3240965 -rw-r--r--  1 nagios nagios 16541 aoû 31 10:26 services.cfg
3240966 -rw-r--r--  1 nagios nagios 68159 aoû 31 10:26 serviceTemplates.cfg
3240967 -rw-r--r--  1 nagios nagios  4891 aoû 31 10:26 timeperiods.cfg

**Comment by julienmathis** [comment]
deprecated
