### ISSUE TITLE
Classement des polars

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3262]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 6397, https://forge.centreon.com/issues/6397
Original Date: 2015-05-15

---

Dans "Configuration" --> "Monitoring Engine", il serait bon de classer les pollers par ordre alphabétique (comme avec Centreon 2.4).

Pour ça : 

Editez : /usr/share/centreon/www/include/configuration/configGenerate/formGenerateFiles.php

Remplacez : $form->addElement('select', 'host', _("Poller"), $newTabNagiosServer, array("id" => "nhost", "style" => "width: 220px;"));

par : 

$form->addElement('select', 'host', _("Poller"), $newTabNagiosServer, array("name" => "nhost", "style" => "width: 220px;"));

**Comment by julienmathis** [comment]
Bonjour Loïc, 

Les pollers sont déjà organisé par ordre alpha.  Pas de souci à ce sujet sur une 2.6.x

++
