### ISSUE TITLE
Acknowledgement filter in Monitoring > Event logs

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3267]
---

Author Name: **Mat Sugumaran** (Mat Sugumaran)
Original Redmine Issue: 1653, https://forge.centreon.com/issues/1653
Original Date: 2010-03-19
Original Assignee: Julien Mathis

---

Hi!

An we have a filter acknowledgement in the eventLog search filters?
We can filter log entries with the following types :
- Alerts
- Hard Only
- Errors
- Notifications
But if we need to see the acknowledgment, we need to unselect all these filters. So we can't see only the alerts with their ack.

Thanks!

**Comment by julienmathis** [comment]
deprecated
