### ISSUE TITLE
Push Plugins to Pollers

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3273]
---

Author Name: **Thomas - aka Jogarem -** (Thomas - aka Jogarem -)
Original Redmine Issue: 426, https://forge.centreon.com/issues/426

---

It would be really great when there would be the possibilty
to push local plugins (local on the Principal) to Pollers so that the plugins there stay up to date.

It should be an extra option that can be enabled to push all plugins that are on the Master server to all or selected Pollers.

If you have questions regarding this feature request don't hesitate to ask ;o)

Regards
Thomas

**Comment by julienmathis** [comment]
I think this job is dedicated to config management product. Please report your need to Puppet or Chef
