### ISSUE TITLE
Possibility of configuring the databases separately

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3286]
---

Author Name: **Laurent Pinsivy** (Laurent Pinsivy)
Original Redmine Issue: 1569, https://forge.centreon.com/issues/1569
Original Date: 2010-02-18
Original Assignee: Maximilien Bersoult

---

Add possibility of configuring the databases separately.

May be in menu "Administration -> Databases" with field:
- DB Address
- DB Name
- DB port
- DB user
- DB user pwd

This for each databases. And add button to export informations in file centreon.conf.php.

That could be to use in the long term for the redundancy of databases with failover configuration by database.

**Comment by julienmathis** [comment]
deprecated
