### ISSUE TITLE
Split graph metrics in overlay popup

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3306]
---

Author Name: **Romain Le Merlus** (Romain Le Merlus)
Original Redmine Issue: 1153, https://forge.centreon.com/issues/1153
Original Date: 2009-08-20

---

Graphs template should have a "split" property.
Then, the graph popup on mouse overlay have to show the different metrics splited.

Now, we have to go in view menu, select the service, then the split the metrics. 

Thank you.

**Comment by julienmathis** [comment]
Impossible because we cannot display all graphs when they are more than 3 graphs...
