### ISSUE TITLE
Upper limit dans un modele de graph ne fonctionne pas

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3317]
---

Author Name: **nathanael bonin** (nathanael bonin)
Original Redmine Issue: 6154, https://forge.centreon.com/issues/6154
Original Date: 2015-02-19

---

Bonjour,

J'ai remarqué que mon modèle de graphique ne fonctionnait plus comme il le devait. Je suis en Centreon 2.4.5. En effet, dans mon modèle de graphique pour les disques, j'ai déclaré que mon axe avait comme valeur max, la valeur maximale renvoyée par ma sonde.

Comme vous pourrez le voir sur les différentes captures jointes à ce ticket, tout est bien déclaré normalement. Seul chose que nous ne voyons pas sur les captures c'est que le modèle de graphique est rattaché directement à un modèle de service et non au service lui même.

Je vous remercie par avance de la prise en compte de ce bug.

Nathanaël.

**Comment by julienmathis** [comment]
I works on 2.6.1. Please update now
