### ISSUE TITLE
Service Downtime Not Working

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3331]
---

Author Name: **Eduardo Bayon Perales** (Eduardo Bayon Perales)
Original Redmine Issue: 5540, https://forge.centreon.com/issues/5540
Original Date: 2014-05-13

---

I've just updated to centreon 2.5.1 with "Program Version" 1.3.7

Service downtime are not working. I've set a downtime for some services from monday to sunday and from 0:01 to 23:59 (i.e. all time all days) and services are displaying "In Scheduled Downtime? -> NO "

So notifications when those services go down still are being sent.

**Comment by julienmathis** [comment]
Fixed in Centreon 2.7.
