### ISSUE TITLE
Cannot execute two immediat checks on monitoring

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3338]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 6303, https://forge.centreon.com/issues/6303
Original Date: 2015-04-01

---

Hello,

I'm using Centreon 2.5.4 (with chrome), I found a bug around the immediat check action on the monitoring.

I'm able to schedule a check once, but it does not work when I retry.
To workaround, I have to refresh manualy the page.

Best regards.

**Comment by leoncx** [comment]
Follow github issue #95

**Comment by bsauveton** [comment]
Cannot reproduce this bug, maybe already solved. A test is needed.
