### ISSUE TITLE
Needed for plugins packs - Ability to add macros description/documentation

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3339]
---

Author Name: **Quentin Delance** (Quentin Delance)
Original Redmine Issue: 5559, https://forge.centreon.com/issues/5559
Original Date: 2014-05-20
Original Assignee: Julien Mathis

---

We are shipping a bunch of macros in our templates (hosts or services) provided by plugins packs.
Our goal is that the templates are the most "self contained" as possible which means that the template should hold as much information as possible.
This should prevent the end user from switching to an additional document (which does not exist by the way) when overloading templates and filling in macros.

Requirements : 
* a textarea like that allows us to define a long description text for each macro
* the ability to read this text when filling in macros (like for instance through an icon close to the macro displaying the text when clicked ? )

**Comment by leoncx** [comment]
Duplicate #2292
