### ISSUE TITLE
[Meta Services] Add several curves on one Meta service

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3355]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 4575, https://forge.centreon.com/issues/4575
Original Date: 2013-06-26

---

Hello,

It would be nice to be able to see on a meta service's graph the services involved in the meta service's calculation.
The idea is to see on the meta service's graph, the components of the meta service.

I added an example to illustrate :
I have several network interfaces, and i want to get an alert if the sum of all their traffic is higher than a threshold.

But i would like to see on the graph, not only the calculated sum, but each network interface's traffic. In order to get an overview on what happens.

Please look at the sceenshot added.

Regards.

**Comment by lpinsivy** [comment]
linked to #3714
