### ISSUE TITLE
Create a default status graph for all services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3379]
---

Author Name: **Bruno Legros** (Bruno Legros)
Original Redmine Issue: 3270, https://forge.centreon.com/issues/3270
Original Date: 2012-04-26

---

A status graph is automatically created for all services which return performance datas.

Why not generate a status graph for all services, even those not returning perf datas ? ...and for passive ones too.

With this functionnality, we will have all services in the "Graphs" view of Centreon, which is much more coherent.

Thanks in advance.

**Comment by julienmathis** [comment]
implemented
