### ISSUE TITLE
Gestion de l'ordre des héritages de template d'hôtes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3383]
---

Author Name: **Guillaume Watteeux** (Guillaume Watteeux)
Original Redmine Issue: 3679, https://forge.centreon.com/issues/3679
Original Date: 2012-09-17

---

Bonjour,

est-il possible d'ajouter une interface qui permettrai de pouvoir modifier facilement l'ordre des templates d'hôte une fois que celui-ci est créer sans avoir à tout supprimer puis refaire. Cela nous permettra d'avoir une vue plus claire de l'ordre des héritages.

Cordialement
WAtt

**Comment by julienmathis** [comment]
Already fixed since a long time
