### ISSUE TITLE
Custom view : add more columns

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3390]
---

Author Name: **ROBIN matthieu** (ROBIN matthieu)
Original Redmine Issue: 4681, https://forge.centreon.com/issues/4681
Original Date: 2013-08-02
Original Assignee: Sylvestre Ho

---

Morning,

Is there a way to add an option to have 4 or maybe 5 columns?
It cool be very interesting for the widescreen monitor and TV.

Thanks a lot

**Comment by Moujimouja** [comment]
Hi,

We won't implement more columns, we'll better integrate progressively a new flexible & efficient dashboard engine.
