### ISSUE TITLE
Add thresholds in the graphs

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3394]
---

Author Name: **Thomas - aka Jogarem -** (Thomas - aka Jogarem -)
Original Redmine Issue: 1171, https://forge.centreon.com/issues/1171
Original Date: 2009-08-26

---

a great improvement would be to display the thresholds of the defined warning and critical values within each graph.

example:

```
megabyte   = mmmmmmmm
time       = ttttttttt
warning    = ----------
critical   = ~~~~~~~~~~~



  m
  m~~~~~~~~~~~~~~~~~~~~~~~~
  m        ______
  m-------/------\---------
  m______/        \
  m                \_______
  m
  ttttttttttttttttttttttttt


```

**Comment by julienmathis** [comment]
Done
