### ISSUE TITLE
Print downtimes in graphs

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3413]
---

Author Name: **Matthieu Kermagoret** (Matthieu Kermagoret)
Original Redmine Issue: 6371, https://forge.centreon.com/issues/6371
Original Date: 2015-04-30

---

Graphs show information about a status or a metric. During downtimes, these information can be move far off their normal values. Users should be made aware that this is normal situation as a downtime was planned.

Could it be possible to flag scheduled downtimes periods somehow in graphs ? It could be for example a different background color in this time period, or something else.

**Comment by lpinsivy** [comment]
done!
