### ISSUE TITLE
Génération des time period

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3441]
---

Author Name: **GIBERT Florian** (GIBERT Florian)
Original Redmine Issue: 5743, https://forge.centreon.com/issues/5743
Original Date: 2014-08-14

---

La génération des timeperiod sur la version centreon 2.5.2 amène une contrainte supplémentaire : 

define timeperiod{
        name                            0-000
        timeperiod_name                 0-000
        alias                           0000
        use                             00-24x7
}

define timeperiod{
        name                            00-24x7
        timeperiod_name                 00-24x7
        alias                           24/24h 7/7j
        sunday                          00:00-24:00
        monday                          00:00-24:00
        tuesday                         00:00-24:00
        wednesday                               00:00-24:00
        thursday                                00:00-24:00
        friday                          00:00-24:00
        saturday                                00:00-24:00
}

==> Cela ne fonctionne plus car la timeperiod 0-000 utilise la timeperiod 00-24x7 qui n'est pas encore lut par le process ==> blocage de la génération des fichiers

**Comment by julienmathis** [comment]
deprecated
