### ISSUE TITLE
Downtime not working

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3446]
---

Author Name: **Bastien MAREAU** (Bastien MAREAU)
Original Redmine Issue: 6411, https://forge.centreon.com/issues/6411
Original Date: 2015-05-28

---

Centreon : 2.6.0
Engine : 1.4.13
Broker : 2.8.2
---

Hi,

In Centreon I have set a service downtime.
-> All Days from 00:00 to 23:59
-> Linked with Service Groups

But the downtime doesn't work.
I have reproduced the bug on two test platforms.

Regards

**Comment by leoncx** [comment]
Duplicate #1818
