### ISSUE TITLE
Poller script check timeout

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3448]
---

Author Name: **Jürgen Ecker** (Jürgen Ecker)
Original Redmine Issue: 6348, https://forge.centreon.com/issues/6348
Original Date: 2015-04-17

---

Hello Centreon Team,

we searched about a option where we can define scripts which should excluded by the poller timeout and should have there own timeout. The poller timeout of 60 seconds is OK. The most scripts should have the timeout of 60 seconds but some scripts takes longer and we want set the timeout only for some Scripts. It would be appreciated if you can implement this issue in the next Centreon version.

Best Regards
Jürgen Ecker

**Comment by julienmathis** [comment]
In the next version of Centreon Engine, Timeout will be configurable on host and service.
