### ISSUE TITLE
New log_pid feature from 2.6.1 block nagios config file generation.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3464]
---

Author Name: **Baptiste Boilet** (Baptiste Boilet)
Original Redmine Issue: 6412, https://forge.centreon.com/issues/6412
Original Date: 2015-05-28

---

Since I upgrade to 2.6.1, i cannot update nagios.cfg anymore:
Error in configuration file '/usr/share/centreon/filesGeneration/nagiosCFG/1/nagiosCFG.DEBUG' - Line 89 (UNKNOWN VARIABLE)

Looking at line 89, gives: 
log_pid=1

Nagios verify config is not able to verify due to this line.

**Comment by julienmathis** [comment]
To be checked !

**Comment by Tpo76** [comment]
OK

**Comment by asalmoran** [comment]
Hello, 

I have a issue with Centreon 2.7 when I try to run "Run monitoring engine debug (-v)", the progress is (0%) but the enviroment is OK. 

Is it right that result?

Centreon v. 2.7.1
SO: CentOs 7 

Regards.
