### ISSUE TITLE
Show Centreon Broker state in top counter

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#348]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 4146, https://forge.centreon.com/issues/4146
Original Date: 2013-01-28

---

Hello,

In the case where Centreon BROKER is going down, never information is showed in Centreon in order to alert end user.

I think, we must add another indicator in Centreon in order to show broker state like we have with poller state.

Regards.

**Comment by lpinsivy** [comment]
Need information stored by Centreon Broker in DB.
