### ISSUE TITLE
Revert changes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3484]
---

Author Name: **Stefan Billeb** (Stefan Billeb)
Original Redmine Issue: 4848, https://forge.centreon.com/issues/4848
Original Date: 2013-08-27

---

Hi,

I noticed today and discussed in IRC that there is no possibility to revert some changes that were done *before* generating and exporting the new configuration.

I accidentally  deleted a service check and did not find any reload steps that could give me the check back.
Reloading centreon without new configuration made the check be still visible in the GUI, but not able to look into check definitions or anything more.

This would be a necessary feature in my opinion.

**Comment by ermurenz** [comment]
any news about this?
