### ISSUE TITLE
Patch to add a description field in Pollers menu

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3485]
---

Author Name: **charles judith** (charles judith)
Original Redmine Issue: 4608, https://forge.centreon.com/issues/4608
Original Date: 2013-07-08

---

Hi,

You will find in attachment a patch to add a description field in pollers menu (Configuration>Centreon). This field can be empty.

I've applied this patch on my platform, I share it here and hope this will be useful for other people.

Thanks,

**Comment by julienmathis** [comment]
deprecated
