### ISSUE TITLE
Remove data from deleted hosts/services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3486]
---

Author Name: **Matthieu Kermagoret** (Matthieu Kermagoret)
Original Redmine Issue: 3535, https://forge.centreon.com/issues/3535
Original Date: 2012-08-09
Original Assignee: Sylvestre Ho

---

Upon removal of hosts/services in Centreon, a database cleanup should be performed. Among other things, entries in these tables should be dropped :

- hosts (have ON DELETE CASCADE with other tables)
- services (have ON DELETE CASCADE with other tables)
- logs (removal based on both IDs and names)
- index_data
- metrics (corresponding RRD graphs should be dropped too)
- data_bin

**Comment by julienmathis** [comment]
no way !
