### ISSUE TITLE
newline chars in commands comments give bad nagios.cfg

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#349]
---

Author Name: **Bruno Legros** (Bruno Legros)
Original Redmine Issue: 3313, https://forge.centreon.com/issues/3313
Original Date: 2012-05-11

---

When writing a comment with newline characters in a command configuration, the nagios.cfg generated is bad.

Exemple :
--------
This is a comment on
two lines in a command
--------

is generated like :
--------
### This is a comment on
two lines in a command ###
--------

nagios -v gives a fatal error.

**Comment by julienmathis** [comment]
Should be tested by the new engine
