### ISSUE TITLE
Groupe de notification - Affichage des contacts du groupe

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3494]
---

Author Name: **cedric meschin** (cedric meschin)
Original Redmine Issue: 6381, https://forge.centreon.com/issues/6381
Original Date: 2015-05-05

---

Bonjour,
est-il possible d'afficher dans le détail d'un service ou d'un hôte le détail des groupes de notification par un popup au survol du groupe concerné (cf PJ)?
Cela permettrait à un utilisateur n'ayant pas accès à la configuration de connaitre les personnes notifiées.

cordialement,

**Comment by lpinsivy** [comment]
linked to #3780
