### ISSUE TITLE
Groupe de serveurs dans CustomViews

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#352]
---

Author Name: **Sligs S.** (Sligs S.)
Original Redmine Issue: 4303, https://forge.centreon.com/issues/4303
Original Date: 2013-03-13

---

bonjour,
est-il possible de permettre à un utilisateur de se créer ses propres hostgroups ?
Le but est qu'il puisse se faire lui même un groupe de serveurs correspondant à un expression sur le nom de machine ( type web%-france ), ou une sélection directe de serveurs.
Grâce à cela il va pouvoir avoir de meilleur filtre sur l'interface et jouer plus finement avec les différents widgets

Pas un groupe au sens hostgroup nécessitant un reload du poller etc. un groupe purement logique et propre à l'interface
Merci

**Comment by julienmathis** [comment]
Géré avec les tags dans Centreon 3.
