### ISSUE TITLE
Change Tree view tool to a jquery Plugin

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3533]
---

Author Name: **Lionel Assepo** (Lionel Assepo)
Original Redmine Issue: 3681, https://forge.centreon.com/issues/3681
Original Date: 2012-09-17

---

Currently Tree view loading is very slow when many elements are presents in the tree view (for example whan you have over 1000 hosts in "Views -> Graphs" with ACL activated).

Swicthing Tree view tool (that uses XML for tree's data population) to a jquery plugin (that uses JSON could be more efficient)

**Comment by julienmathis** [comment]
deprecated
