### ISSUE TITLE
Change default option from restart to reload when exporting

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3539]
---

Author Name: **Thomas - aka Jogarem -** (Thomas - aka Jogarem -)
Original Redmine Issue: 427, https://forge.centreon.com/issues/427

Original Assignee: Julien Mathis

---

When you choose in centreon web frontend
Configuration - Nagios  
then the default option of 'Nagios Restart' is 'Restart'.

In my opinion this is not a good choice because a reLOAD will do
it most the time and is much faster then a complete restart of
Nagios..

I will attach a screenshot.

Regards
Thomas

**Comment by hugleo** [comment]
Could we also have a general option?

I would need it for example for livestatus:
https://github.com/centreon/centreon-engine/issues/81#issuecomment-321988770
