### ISSUE TITLE
Ajout d'une colonne "Comments" 

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3540]
---

Author Name: **julien breton** (julien breton)
Original Redmine Issue: 2770, https://forge.centreon.com/issues/2770
Original Date: 2011-11-04
Original Assignee: Sylvestre Ho

---

Bonjour,

Est-il possible d'ajouter une colonne "Comments" dans la vue Monitoring / Hosts et Monitoring / Services. Cette colonne montrerait le texte ajouté lors d'un acquittement.

Dans notre cas, c'est le n° de ticket d'incident que l'on inscrit et ce serait plus pratique d'avoir une vue globale plutôt que de passer la souris sur l'icône d'acquittmeent pour voir le contenu des commentaires.

En vous remerciant.

**Comment by julienmathis** [comment]
Done in host monitoring and service monitoring widget.
