### ISSUE TITLE
Calcul sur l'évolution d'un métrique entre 2 périodes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3553]
---

Author Name: **nicolas moreau** (nicolas moreau)
Original Redmine Issue: 4403, https://forge.centreon.com/issues/4403
Original Date: 2013-04-17

---

Bonjour,

Serait-il possible d'introduire la possibilité de comparer 2 valeurs d'un même métrique sur une période temporelle donnée?
Je m'explique, par exemple, pour créer un service (une sorte de méta-service) qui nous dit: lors des dernières 24h, ou entre 2 dates données, l'occupation du disque C du serveur A a augmenté de x Gb avec des valeurs en warning et critical

A moins que ce soit déjà possible et que je ne sache pas le faire

**Comment by julienmathis** [comment]
Present dans Centreon MBI. Impossible de faire cela sans DWH
