### ISSUE TITLE
Commentaires multilignes - acquittements

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3554]
---

Author Name: **Bastien MAREAU** (Bastien MAREAU)
Original Redmine Issue: 5816, https://forge.centreon.com/issues/5816
Original Date: 2014-09-15

---

Bonjour,
Lorsque qu'un service est acquitté depuis l'interface centreon (et même depuis l'interface centreon map) seul la première ligne du commentaire est conservée. 

Cordialement

== 

Hi,
When a service is acquitted from the centreon interface (and even from the centreon interface map) only the first line of the comment is retained.

Best Regards

**Comment by leoncx** [comment]
Duplicate #451
