### ISSUE TITLE
Add configuration directives for Icinga

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3562]
---

Author Name: **Martin Soltis** (Martin Soltis)
Original Redmine Issue: 2583, https://forge.centreon.com/issues/2583
Original Date: 2011-08-11
Original Assignee: Sylvestre Ho

---

Hi, could you please add directives that are in Icinga ? 
There are many new options, that are not in Nagios.

For example i need these

first_warning_notification #
last_warning_notification #
first_critical_notification #
last_critical_notification #
first_down_notification #
last_down_notification #
first_unreachable_notification #
last_unreachable_notification #
first_unknown_notification #
last_unknown_notification #

because escalations in Nagios are strange, like in this thread

http://www.mail-archive.com/nagios-users@lists.sourceforge.net/msg29851.html

so i need to switch to Icinga.

Thank you

Martin

**Comment by julienmathis** [comment]
@ganoze Do we integrate this feature ? I don't remember :)

**Comment by ganoze** [comment]
This is a duplicate of centreon/centreon-broker#22 . We've discussed about it offline but no final decision was made. In my opinion implementing this feature would be useless and against what we're trying to do with the in-dev correlated notification system.
