### ISSUE TITLE
Manage cancellation to rebuild RRD databases

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3572]
---

Author Name: **nathanael bonin** (nathanael bonin)
Original Redmine Issue: 4959, https://forge.centreon.com/issues/4959
Original Date: 2013-10-29

---

Bonjour,

Suite à la migration vers la version 2.4.5, j'ai remarqué que si l'on modifiait la valeur de la colonne "must_be_rebuild" à 1, il donnait bien l'ordre à Centstorage de reconstruire les graphiques. Si on lance cette demande sur 20 services en parallèle, il n'en fait qu'un en simultané voire 2. Du coup si on décide de remettre la colonne "must_be_rebuild" à 0, pour annuler cette demande, et que l'on regarde de temps à autre, avec la commande suivante :

```
SELECT * FROM index_data where must_be_rebuild="2";

```

On se rend compte qu'il reconstruit tout de même les graphiques en question. J'ai vérifié depuis l'interface web dans Administration -> Centstorage -> Gérer que les services étaient bien marqués "Non" pour le besoin de reconstruction.

Merci par avance pour la prise en charge de cette demande.

**Comment by julienmathis** [comment]
@ganoze : est ce que Broker est capable de faire cette annulation ? 10 par 10 et non pas prendre tout d'un coup

**Comment by ganoze** [comment]
Dans l'implémentation actuelle, Centreon Broker récupère la liste des index et des metric à rebuilder en une fois.

**Comment by Moujimouja** [comment]
Deprecated issue
