### ISSUE TITLE
Possibilité d'escaper un caractère "<" ou ">" ?

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3582]
---

Author Name: **Jérémy DS** (Jérémy DS)
Original Redmine Issue: 6379, https://forge.centreon.com/issues/6379

Original Assignee: Julien Mathis

---

Voici ma commande :

$USER1$/pmp-check-mysql-status -H $HOSTADDRESS$ -l $_SERIVCEBDD_USER$ -p $_SERVICEBDD_PWD$ -x $ARG1$ -C $ARG2$ -w $ARG3$ -c $ARG4$

$ARG1$ = wsrep_cluster_size
$ARG2$ = <=
$ARG3$ = 2
$ARG4$ = 1

L'argument 2 pose problème et je n'arrive pas a gérer le '<', j'ai essayé !<= et pas moyen...

Avec un autre service basé sur la même commande il a fallu que je gère en $ARG2$ != et j'ai juste eu a faire un \!= et c'est passé sans aucun problème.

Une possibilité ?

**Comment by julienmathis** [comment]
Max, 

Can you help me on this issue ?

Thanks

**Comment by julienmathis** [comment]
bonjour, 

< et > sont des caractères interdits car dangereux et interprétés par le shell. Nous ne connaissons pas vraiment le plugin mais je pense qu'il faudrait construire la commande directement...

Nous ne pouvons rien faire dans l'immédiat.
