### ISSUE TITLE
LDAP Import

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3590]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 5532, https://forge.centreon.com/issues/5532
Original Date: 2014-05-10

---

Après la configuration de l'importation des utilisateurs LDAP, en entrant manuellement le serveur LDAP à choisir.
J'ai l'erreur suivante dans /var/log/httpd/error :

[Sat May 10 19:47:36 2014] [error] [client ] PHP Warning:  ldap_search(): Search: No such object in /usr/share/centreon/www/class/centreonLDAP.class.php on line 481, referer: http://192.168.15.7/centreon/main.php?p=60301&o=li
[Sat May 10 19:47:36 2014] [error] [client ] PHP Warning:  ldap_sort() expects parameter 2 to be resource, boolean given in /usr/share/centreon/www/class/centreonLDAP.class.php on line 484, referer: http://192.168.15.7/centreon/main.php?p=60301&o=li
[Sat May 10 19:47:36 2014] [error] [client ] PHP Warning:  ldap_count_entries() expects parameter 2 to be resource, boolean given in /usr/share/centreon/www/class/centreonLDAP.class.php on line 485, referer: http://192.168.15.7/centreon/main.php?p=60301&o=li
[Sat May 10 19:47:36 2014] [error] [client ] PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /usr/share/centreon/www/class/centreonLDAP.class.php on line 488, referer: http://192.168.15.7/centreon/main.php?p=60301&o=li
[Sat May 10 19:47:36 2014] [error] [client ] PHP Warning:  ldap_free_result() expects parameter 1 to be resource, boolean given in /usr/share/centreon/www/class/centreonLDAP.class.php on line 490, referer: http://192.168.15.7/centreon/main.php?p=60301&o=li
[Sat May 10 19:47:36 2014] [error] [client ] PHP Warning:  ldap_err2str() expects parameter 1 to be long, resource given in /usr/share/centreon/www/include/configuration/configObject/contact/ldapsearch.php on line 215, referer: http://192.168.15.7/centreon/main.php?p=60301&o=li

**Comment by leoncx** [comment]
Bonjour,

Pouvez-vous nous donner plus d'information pour reproduire le problème et la version de Centreon sur laquelle vous avez eu le problème ?

Merci
