### ISSUE TITLE
Ajout d'une possibilité dans le champ de recherche

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3602]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 4437, https://forge.centreon.com/issues/4437
Original Date: 2013-04-30

---

Dans "Monitoring" ==> "Services" il serait pratique de pouvoir voir les hôtes et les services pour lesquels aucune notification n'est envoyée.

**Comment by dgarandel** [comment]
Oui ce serait vraiment très pratique surtout lorsque les services sont en status 'OK'. Ces notifications peuvent rester en l'état durant un fort long moment sans s'en apercevoir . Et serait plus facile à "énabler" en masse.

**Comment by julienmathis** [comment]
I prefer doing that in the configuration view
