### ISSUE TITLE
Modification de la configuration à chaud

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3608]
---

Author Name: **Florence Pagani** (Florence Pagani)
Original Redmine Issue: 3996, https://forge.centreon.com/issues/3996
Original Date: 2012-12-07

---

Avec la configuration actuelle de Centreon, les modifications doivent être faites « à froid » ce qui oblige à redémarrer toute la supervision pour toute nouvelle configuration d'un host ou d'un service. 

La fonctionnalité de configuration à chaud permet:
- l'ajout de nouveaux hosts ou de nouveaux services 
- la modification des hosts et des services
sans nécessiter de redémarrage. 

(Nécessite Centreon Engine) 
Les fichiers de configuration générés dans Centreon sont pris en compte immédiatement par Centreon Engine et les processus de debug et de redémarrage fonctionnent désormais en tâche de fond sans ralentir la supervision.

**Comment by julienmathis** [comment]
done
