### ISSUE TITLE
Access to action/url links from chart

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3609]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 4258, https://forge.centreon.com/issues/4258
Original Date: 2013-02-27

---

Hi, 

Action-link and link properties integration in monitoring or home views are useful. 

But, when a user display a graph and see a problem, it could be interesting to gives him a direct access to theses properties. 
This avoid to navigate to monitoring, find the service again and click the link. 

A visual idea is attached. 

Thanks, 

pch

**Comment by Moujimouja** [comment]
Graph is display in the resource context so the links are often next to the graph. 
There are already enough information on graphs. 

Won't do

**Comment by warden** [comment]
FWIW I don't see the comment addressing the original report. As I understand the OP wanted to have a *direct link* to the graph which is crucial if you want to share this with another person. Resource context can have many graphs and this does not directly get the user to the mentioned graph *and* selected time period.

**Comment by Moujimouja** [comment]
> FWIW I don't see the comment addressing the original report. As I understand the OP wanted to have a _direct link_ to the graph which is crucial if you want to share this with another person. Resource context can have many graphs and this does not directly get the user to the mentioned graph _and_ selected time period.

I think you're misunderstanding, the user is talking about Action URL & URL properties that you can access in the listing & detail page of Centreon 

![image](https://user-images.githubusercontent.com/6620287/90409695-c8bac680-e0a9-11ea-9cd7-ca7249810da6.png)

Having a direct link to the graph is a good idea and will be considered in the new event view page (in beta)
