### ISSUE TITLE
Poller States

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3626]
---

Author Name: **Oxidnation Jonathan** (Oxidnation Jonathan)
Original Redmine Issue: 4493, https://forge.centreon.com/issues/4493
Original Date: 2013-05-27

---

Hello,

I've just see a problem with "Poller States" on the top of the page. the check sends a wrong status from an old configuration.

In my case, my first attempt to create a poller was named "Poller1". After some edition, I've delete them and finaly reacreated with the new name "poller1". (no capital letter)

After completly configure this new poller, the state stayed in error only from this "Poller States".

When I putted my mouse on the red case, he was talking about "Poller1". This object wasn't exist anymore.

I think there are a problem somewhere about case sensitive check and/or some non deleted informations.

Where can I check the old entries?

**Comment by julienmathis** [comment]
no info, sorry...
