### ISSUE TITLE
ExternalCommands not sent to Nagios after Upgrade to 2.5

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#365]
---

Author Name: **Constantin Lotz** (Constantin Lotz)
Original Redmine Issue: 5486, https://forge.centreon.com/issues/5486
Original Date: 2014-04-23

---

I have on an system the issue that external commands from centreon where not sent to nagios. Upgraded to Centreon 2.5.0 (from 2.4.5)
I have enabled debug logging, but centcore.log and centstorage.log are only 0 byte.

The processes are up and running:
root@SERVER:/usr/local/centreon/log# ps aux | grep cent
root      1521  0.0  0.0  63236   692 ?        Ss   Apr22   0:01 /usr/bin/perl /usr/local/centreon/bin/snmptt --daemon --ini=/etc/snmp/centreon_traps/snmptt.ini
root      1522  0.0  0.1  71792  4860 ?        Ss   Apr22   0:04 /usr/bin/perl /usr/local/centreon/bin/snmptt --daemon --ini=/etc/snmp/centreon_traps/snmptt.ini
root     22860  0.0  0.0  10920   932 pts/0    S+   09:58   0:00 grep --color=auto cent
centreon 25274  0.0  0.6 211440 16704 ?        S    09:38   0:00 /usr/bin/perl /usr/local/centreon/bin/centstorage
centreon 25279  0.1  0.5 201516 14664 ?        S    09:38   0:01 /usr/bin/perl /usr/local/centreon/bin/centstorage
centreon 25280  0.1  0.5 201536 14644 ?        S    09:38   0:01 /usr/bin/perl /usr/local/centreon/bin/centstorage
centreon 25281  0.1  0.5 201536 14624 ?        S    09:38   0:01 /usr/bin/perl /usr/local/centreon/bin/centstorage
centreon 25282  0.1  0.5 201632 14692 ?        S    09:38   0:01 /usr/bin/perl /usr/local/centreon/bin/centstorage
centreon 25283  0.0  0.5 201736 14208 ?        S    09:38   0:00 /usr/bin/perl /usr/local/centreon/bin/centstorage
centreon 25392  0.0  0.5 138692 13984 ?        S    09:38   0:00 /usr/bin/perl /usr/local/centreon/bin/centcore

It seems that the centcore.cmd is not created:
root@SERVER:/var/lib/centreon# ls -lha
insgesamt 84K
drwxrwxr-x 10 centreon centreon 4,0K Apr 23 10:06 .
drwxr-xr-x 51 root     root     4,0K Mär 16 12:00 ..
-rw-rw-r--  1 centreon centreon    7 Nov  9  2011 archiveDayLog.last
drwxrwxr-x  2 centreon centreon 4,0K Jun 11  2013 broker-stats
drwxrwxr-x  2 centreon centreon 4,0K Feb 18  2011 centplugins
drwxrwxr-x  7 centreon centreon 4,0K Jun 18  2013 log
-rw-rw-r--  1 centreon centreon    6 Feb  4  2012 logAnalyser.lock
drwxrwxr-x  2 centreon centreon  20K Mär 14 12:28 metrics
drwxrwxr-x  7 centreon centreon 4,0K Jun 18  2013 nagios-perf
drwxrwxr-x  6 centreon centreon 4,0K Jun 18  2013 perfdata
drwx-w----  2 centreon centreon 4,0K Mär 14 15:23 .ssh
drwxrwxr-x  2 centreon centreon  20K Apr  3 12:50 status
-rw--w----  1 centreon centreon  945 Jun 13  2013 .viminfo

I can run the centcore process as centreon user - but it shows on commandline only that it's starting..

What can I check next ?

**Comment by julienmathis** [comment]
deprecated
