### ISSUE TITLE
Downtime et changement d'heure

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3657]
---

Author Name: **jonathan cousin** (jonathan cousin)
Original Redmine Issue: 5916, https://forge.centreon.com/issues/5916
Original Date: 2014-10-26

---

Bonjour,
J'ai 2 plates-formes centreon.
Une en 2.4.3 autonome.
Une en distribuée en 2.4.5 avec une dizaine de poller.
Ces 2 plates-formes sont séparées et ne dialoguent pas ensemble.

Tous les week end, certains de mes checks sont en downtimes pour des maintenances particulières en fonction de la plate-forme.
Ca fait 1 an que ça tourne sans aucun problème.

Hier matin (le 27/10/2014), on m'a remonté que plusieurs jobs étaient encore en downtime sur la plage 26/10/2014 23h00 à 27/10/2014 23h00.
Or je n'ai aucun downtime récurrent sur cette plage et le problème est strictement identique sur les 2 plates-formes.
Constat : Tous les jobs qui étaient en downtime lors du changement d'heure ont un nouveau downtime du 26/10 23h00 au 27/10 23h00...

Dans les logs, je vois bien les external command de downtime à 22h50 le 26/10 :
[1414360219] EXTERNAL COMMAND: SCHEDULE_HOST_DOWNTIME;xxxxxx;1414360800;1414447200;1;0;0;Downtime cycle;[Downtime cycle #125]
[1414360219] EXTERNAL COMMAND: SCHEDULE_HOST_SVC_DOWNTIME;xxxxxx;1414360800;1414447200;1;0;0;Downtime cycle;[Downtime cycle #125]
[1414360219] EXTERNAL COMMAND: SCHEDULE_HOST_DOWNTIME;xxxxxx;1414360800;1414447200;1;0;0;Downtime cycle;[Downtime cycle #125]
...
D'où viennent-elles ??? Les demandes de downtime sont effectuées exactement à la même heure sur les 2 plates-formes, à 22h50 le 26/10.
Rien dans les cron, rien dans les downtime récurrents...

Ce problème est très gênant et a un impact non négligeable sur notre production.

Merci d'avance.

**Comment by leoncx** [comment]
It will be fix with the new feature of Centreon Engine. Now you can configure timezone with dst in Centreon Web and Centreon Engine.
