### ISSUE TITLE
[ACL] Crontab use the wrong user

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3670]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 3582, https://forge.centreon.com/issues/3582
Original Date: 2012-08-24

---

Hello,
 
I got this error in my log file /usr/local/centreon/log/sql-error.log for months :

2012-08-24 15:06|0|0|DB Error: insufficient permissions QUERY : DELETE FROM centreon_acl WHERE group_id NOT IN (SELECT DISTINCT acl_group_id FROM centreon.acl_res_group_relations)

I find the crontab who wrote this error : /usr/local/centreon/cron/centAcl.php

But this crontab in trying to modify the «centreon» database, with the NDO user (who is restricted to the «centstatus» database).

That's not a good behaviour. To modify the centreon database , you must use the the user for this base, note the one created for NDO2DB.

Regards.

**Comment by julienmathis** [comment]
deprecated
