### ISSUE TITLE
ndo2db lock_file attribute

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3674]
---

Author Name: **centreon admin** (centreon admin)
Original Redmine Issue: 4244, https://forge.centreon.com/issues/4244
Original Date: 2013-02-21

---

Hello all,

I added the lock_file attribute to the Configuration pages of ndo2db.

Attached you'll find the edited files and also the SQL alter command to edit the database.

ALTER TABLE `centreon`.`cfg_ndo2db` ADD `lock_file` VARCHAR( 255 ) CHARACTER SET latin1 COLLATE latin1_general_ci NULL AFTER `description` 

Can you please add them to this version?

Thanks

**Comment by julienmathis** [comment]
Sorry, no evolution for ndo in the futur. Please use centreon broker.
