### ISSUE TITLE
Massive change only applies to 1000 elements

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3692]
---

Author Name: **Pierre Marconnier** (Pierre Marconnier)
Original Redmine Issue: 6222, https://forge.centreon.com/issues/6222
Original Date: 2015-03-25

---

Hello,

I've discovered that if you select more thant 1000 elements and do a massive change with them, the change only applies to the first 1000 (or 1001?) elements.
I've tested it with hosts so I am not 100% sure that it will do the same with other elements as services for instance.

Regars,

**Comment by julienmathis** [comment]
deprecated
