### ISSUE TITLE
WARNINGS in /var/log/centreon/centAcl.log.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3693]
---

Author Name: **Sébastien Boulianne** (Sébastien Boulianne)
Original Redmine Issue: 6178, https://forge.centreon.com/issues/6178
Original Date: 2015-03-05
Original Assignee: Julien Mathis

---

Poller Centreon... up to date...

PHP Notice:  Undefined variable: centreon_path in /usr/share/centreon/cron/centAcl.php on line 51
PHP Warning:  include_once(/www/class/centreonMeta.class.php): failed to open stream: No such file or directory in /usr/share/centreon/cron/centAcl.php on line 51

**Comment by julienmathis** [comment]
Sorry, it works for me. I think you have a wired setup.
