### ISSUE TITLE
Sudoers isn't good

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3698]
---

Author Name: **Stephane Duret** (Stephane Duret)
Original Redmine Issue: 5945, https://forge.centreon.com/issues/5945
Original Date: 2014-11-06

---

Hello,

In my /etc/sudoers, we still have "centstorage" with centreon-engine and centreon-broker.
But we haven't centreontrapd.

Can you delete centstorage and add centreontrapd?

Regards,

**Comment by Tpo76** [comment]
OK
