### ISSUE TITLE
AJAX-ifying Centreon [RFC]

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3700]
---

Author Name: **Nikolaus Filus** (Nikolaus Filus)
Original Redmine Issue: 1205, https://forge.centreon.com/issues/1205
Original Date: 2009-09-16

---

On Roadmap to 2.2 is renaming some classes (#1071), enhancing code documentation (#1072) and
applying more OO Patterns. On the way to better code I propose using less manual javascript
and HTML code, but more available tools. Here is a collection of some interesting resources:

* http://www.extjs.com/ (choosen by icinga)
** http://nexus.zteo.com/2008/03/04/extphp-an-extjs-converterwrapper-for-php-developers/
** http://php-ext.quimera-solutions.com/
* http://jquery.com/
* http://www.mootools.net/
** http://jqueryvsmootools.com/ and
** http://mootools.net/slickspeed/

A first milestone may be to use some more intelligent widgets (smart forms, combo boxes, ...).

**Comment by julienmathis** [comment]
deprecated
