### ISSUE TITLE
Users are able to login without password

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3708]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 6443, https://forge.centreon.com/issues/6443
Original Date: 2015-06-25
Original Assignee: Julien Mathis

---

Hello,

I found this issue on Centreon 2.5.2 and 2.6.1.

Users are able to login to Centreon without password.

After some tests, I found that the problem is related to the SSO authentication.
The problem occurs when the SSO authentication is enabled  (Administration > Centreon > Enable SSO authentication > No).

To workaround the problem, we have to disable the SSO authentication.

Best regards

**Comment by Tpo76** [comment]
OK

**Comment by samuel4x4** [comment]
Hi @centreon, you said that you will documents all SSO pre-requisits in the documentation. Can you please give me the link for this documenattion section? Thanks.
