### ISSUE TITLE
Ajout du "name" d'un widget

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3720]
---

Author Name: **Pateretou -** (Pateretou -)
Original Redmine Issue: 6140, https://forge.centreon.com/issues/6140
Original Date: 2015-02-12

---

Hello

il serait interessant de pouvoir "nommer" ses widgets comme on peut nommer ses "views".

Par exemple sur une view je mets un widget service "prod" et un widget "service non prod".
Je differencie les deux en utilisant le filtre de servicegroup.

Pour avoir une view plus "lisible" ça serait top (et je pense pas un gros dev) de pouvoir mettre un nom sur le widget (la partie grise qu'on fait glisser/deposer pour deplacer sa widget)

Merci!

**Comment by julienmathis** [comment]
Bonjour, 

C'est déjà le cas, sur la version 2.x de Centreon.

Merci du retour.
