### ISSUE TITLE
LDAP Configuration : Contact template

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3731]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 6193, https://forge.centreon.com/issues/6193
Original Date: 2015-03-11

---

Lors de la création d'un nouveau serveur LDAP, dans le champ "Contact Template" si on clique sur la roue dentée pour configurer le contact template on est redirigé vers la fiche d'un contact et non d'un contact template

**Comment by Tpo76** [comment]
OK
