### ISSUE TITLE
Time period management

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#3741]
---

Author Name: **Emylou Mavic** (Emylou Mavic)
Original Redmine Issue: 4360, https://forge.centreon.com/issues/4360
Original Date: 2013-04-03

---

Hi,

It would be helpful to add a quick time period management, like when time changes for certain user / host but not for others located in an other timezone. 

Today, the only way is to edit every single time period, notifications, checks one by one. 

Can it be imagined a way in the interface to make a +1 or -1 button for the line, or the whole time period ?

Best regards,

**Comment by julienmathis** [comment]
deprecated. timezone added in Web 2.7.
