### ISSUE TITLE
Link between Monitoring - Hostrgroups and services

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#3758]
Hello,

When I go to Monitoring --> Hosts --> Hostgroups, I can see all my hostgroups and states of hosts and services.
If I click on a hostgroup, I go in Monitoring --> Services --> All Services but it doesn't display all hosts and services.
I should display all hosts/services of my hostgroup.

As you can see on captures, I only see 3 hosts (services.jpg) but I should see 5 hosts (hostgroups.jpg)

![hostgroups](https://cloud.githubusercontent.com/assets/11076322/9061557/d7484670-3abc-11e5-87bf-63c0d5d95d89.JPG)

![services](https://cloud.githubusercontent.com/assets/11076322/9061558/d74e0a92-3abc-11e5-84f0-2b3cb282e0f7.JPG)

Regards,

**Comment by bigla** [comment]
To get rid of the saved Hostgroup this line can be included in any php-script you want to use.

$_SESSION['monitoring_default_hostgroups'] = 0; # reset default_hostgroup value (for filter form)

**Comment by julienmathis** [comment]
I'm sorry but it works for me. Can you give more information regarding the version, environement (user type, acl, etc...) ?

Thanks

**Comment by s-duret** [comment]
Doesn't work in Centreon 2.6.0 and 2.6.1
It's a CES 3
I'm an admin user
