### ISSUE TITLE
User edit not working if you don't (re) Confirm password everytime

### ISSUE THREAD

**Issue by anthony-sticky** [centreon/centreon#3760]
Hello,

I use Centreon 2.6.1.

When i edit an existing user (to add a *Host Notification Option* for instance) and then press *save* nothing happens (changes aren't effective).

We've to go on *Centreon Authentication* and fill *Confirm password* with our password on every edit for changes to be validated.

Regards.
Anthony.

**Comment by Sims24** [comment]
Hello, 

I can't reproduce on my platform, can you give further informations on how to repoduce it ? It works for me on 2.6.1. 

Regards,

**Comment by anthony-sticky** [comment]
I know what's happening.

I saved my admin password with Firefox.

Everytime i try to edit a user, my browser fill my password on *Centreon Authentication* tab (password field).
However *Confirm Password* field is empty and Centreon is waiting for this field (like if i was really changing my password).
