### ISSUE TITLE
Downtime of a renamed or disabled object can not be deleted/cancelled

### ISSUE THREAD

**Issue by Iralein** [centreon/centreon#3763]
Hello,

If you rename or disable Services, which are in a downtime, you are not able to delete or cancel the downtime via GUI after monitoring restart. The services are actually not in downtime, which is correct, but you can see the old downtimes in the downtimelist.

Centreon 2.6.1 and CBD 2.8.2-5

To reproduce:
Set a downtime for two objects. Rename one object, disable the other. Restart Engine. 
Result: The renamed service is not in a downtime anymore. Both downtimes are still listed in Services->Downtimes and can not be deleted or cancelled. 

Regards,

Ira

**Comment by julienmathis** [comment]
This problem is due to Centreon Broker. We are currently working on this issue ans hope providing a fix very soon

**Comment by Iralein** [comment]
I've installed Centreon 2.6.6 and the issue is still present. The names (hostname or service_description) is now correct, if you've renamed it and restarted, but you still can't cancel the downtime.
More problematic right now is the fact, that the GUI presents the downtime-icon, but the system isn't in downtime because of the renaming.
