### ISSUE TITLE
Safari back-button causes problems after entering terms in host-search field in filter form

### ISSUE THREAD

**Issue by bigla** [centreon/centreon#3767]
Bug appearance:

Monitoring -> Services -> By Status (for all Sub-Pages: Unhandled Problems, Service Problems, All Services)

Type anything in "Host:" input field in filter-form.

After list was filtered (e.g. host_name / host_search was defined) click on a Service.

After being redirected to the service description, press the back button in Safari-Browser. It either hangs or loads parts of the previous page, but no hosts or services are shown. Sometimes even closing the tab is necessary.

I think there might be a problem with $_SESSION - where all the information is stored - resetting the search form variables on load/redirect might solve the problem.

**Comment by julienmathis** [comment]
Hello, 

No able to fix it since a moment.
