### ISSUE TITLE
one notification for a list of services with the detail of the mistakes services

### ISSUE THREAD

**Issue by AllonnesWebDesign** [centreon/centreon#3772]
Hi,

The objective of this request is to group a list of services (for a unique host or multiple hosts) into a unique notification definition (or service of service, more than meta-services) to reduce the number of notification in our mailbox and receive a unique notification when it represent a similarity (for exemple a notification for not enough space in a linux server or not, like actualy, a notification for each file system that achieve the warning or critical value).
It can also be used to monitoring a group of Citrix servers having the same configuration and receive a unique notification for ressources problems (like memory or CPU or disk space...). We need to know furthermore which server have this problem, not only the number (like the script "check_cluster").

Thanks and best regards
Philippe.

**Comment by julienmathis** [comment]
So you need correlation ? You want only one notif for multiple notif on the same host ?
