### ISSUE TITLE
Importing / Load from file leaves host_register field empty

### ISSUE THREAD

**Issue by TheRealEgor** [centreon/centreon#3777]
Running 2.6.1

Configuration -> Monitoring Engines -> Load

Type : Template based method file
Command Type : check command
file : myfile.cfg
behavior on dupe : Create new
Prefix : new_
Group member update : Increment

myfile.cfg contains 100+ hosts in this format:

define host{
        host_name       myhostname1
        use     template-name
        alias   myhostname1
        address myhostname.myorg.org
        hostgroups      host-group-1,host-group-2,host-group-3
}

"Load" shows that 100+ hosts were imported correctly, but they do not show in Configuration -> Hosts view.  Not searchable.

Checking the DB shows that hosts.host_register is empty.  

mysql> update hosts set host_register=1 where host_reigster="" and where host_id > xxxxx  

Hosts are now visible in Centreon and export.  I did have to remove multiple new_, new_new_, etc.. because of multiple imports, but that is my fault/problem.

**Comment by leoncx** [comment]
The Load form configuration file is removed from Centreon Web, but a script will be created for replace.
