### ISSUE TITLE
insert_data switch in option form

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3783]
Hello,
there is a functional problem on the centstorage option form, with the index_data switch; tested on 2.6.2 ...
It can be reproduced on a fresh install:
* switch off index_data
* save
* reload the page -> index_data is back to on

other test:
* switch on or off any other option
* save
* reload the page -> index_data is switched off
* revert the switch you choose and index_data is back to on ...

regards

David Sabatie

**Comment by Shini31** [comment]
This bug is also present after an upgrade from 2.6.1 to 2.6.2
