### ISSUE TITLE
Importing / Load from file leaves service_register field empty 

### ISSUE THREAD

**Issue by TheRealEgor** [centreon/centreon#3784]
This is a similar / same bug as : https://github.com/centreon/centreon/issues/3777

I must go into the DB and execute ; update service set service_register = '1' where service_register = ''  when importing from a config file.

I added 'register 1 ' to each service definition in the nagios.cfg file I was importing and still same behavior.

**Comment by leoncx** [comment]
The Load form configuration file is removed from Centreon Web, but a script will be created for replace.
