### ISSUE TITLE
Documentation for labels and so on

### ISSUE THREAD

**Issue by CharlesJUDITH** [centreon/centreon#3785]
I guess it should be interesting to have a documentation on labels and so on. Indeed sometimes you have the label solved, the issue is open. 

It could bit a little bit difficult to understand the real state of the issue. Well this is just an idea.

You could find an example there : https://github.com/docker/docker/blob/master/project/ISSUE-TRIAGE.md

Note: Thank you to Mathieu Cinquin for the previous link.

**Comment by julienmathis** [comment]
Good Ideas. We just move to github. We are currently working on this new workflow. I will work on this.

**Comment by CharlesJUDITH** [comment]
Thanks for you feedback @julienmathis ;-)

**Comment by julienmathis** [comment]
Hi Charles, 

What do you think about that : 
https://github.com/centreon/centreon/blob/2.7.x/project/issue-workflow.md

++

**Comment by CharlesJUDITH** [comment]
Hi Julien,

I think it's a good start.
