### ISSUE TITLE
Remove global options for generate index_data by Centreon

### ISSUE THREAD

**Issue by leoncx** [centreon/centreon#3786]
Remove global options for generate index_data by Centreon, and force the option for Centreon Broker generate index_data (insert_in_index_data set to 1).

**Comment by julienmathis** [comment]
90% done. We have just some code to remove. It can wait

**Comment by lpinsivy** [comment]
Done? What is left to be done.?

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
