### ISSUE TITLE
Timeperiod field limitation

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon#3789]
Hello,

I'm using Centreon 2.6.2 and I want to schedule a check every 30 minutes in a time range between some minutes.

To do ti, I must to configure my time period for each day, like this : 08:10-08:15,08:40-08:45,09:10-09:15,09:40-09:45 ...

Like this, I'm able to define my period until "19:40-19:45" due to a field limitation.

Is there a way to increase the field limitation in a future version?

Best regards,

**Comment by julienmathis** [comment]
Yes I think it will be possible in the next minor version.
