### ISSUE TITLE
Problèmes avec la création des host group

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#3793]
Centreon 2.6.2
Engine 1.4.14
Broker 2.10.0

Bonjour,
- Lors de la création d'un host group vide (sans hôte associé) avec un user admin, il n'y a pas de problème. La conf est bien sauvegardée.
- Lors de la création d'un host group vide (sans hôte associé) avec un user non-admin, il y a un message d'erreur nous empêchant de sauvegarder la conf. J'ai réalisé le test avec un user soumis aux ACL mais qui a le droit à TOUT.

Le message d'erreur est le suivant : 
- Compulsory hosts (due to ACL restrictions that could prevent you from seeing this host group)
- Hôtes obligatoires (en raison des restrictions d'accès ACL qui pourraient vous empêcher de voir ce groupe d'hôte)

Le problème n'apparaît pas pour les services groups.
En revanche, pour les services groups créés vides, l'utilisateur soumis aux ACL ne peut pas les voir dans son interface. 

Cordialement

**Comment by querwin** [comment]
I just apply patch, I can't see any differences than before.

**Comment by querwin** [comment]
Hello,

Le problème sur les hostgroups a été corrigé dans une version précédente de Centreon.

Pour les services groups, le problème n'est pas évident à corriger, il restera donc comme étant un Bug connu.
