### ISSUE TITLE
Password in macro

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#3797]
Hello,

Passwords are displayed in macros.
The bug comes from Centreon 2.6.2, passwords were not displayed in 2.6.1.

Regards,

**Comment by bsauveton** [comment]
To fix this issue, change the following line in this file www/include/common/javascript/centreon/macroPasswordField.js

delete line 15 : - "input[0].removeAttr("type");"

replace line 17 : - "input.prop('type', 'password');" with 
                          - "input[0].type = 'password'; "

replace line 20 : - "input.prop('type', 'text');" with 
                          - "input[0].type = 'text';"
