### ISSUE TITLE
Home, icon missing if criticality

### ISSUE THREAD

**Issue by benoiteolas** [centreon/centreon#3798]
Hello,

There is a little bug in the home in the «:: Unhandled Service problems» bloc.

When at least one service has a Severity set, a column named «C» is shown. (C for Severity (>.< ) )
But for the services who don't have a Severity set, an missing icon is shown.
Please look the screen shot.

Regards.

![capture](https://cloud.githubusercontent.com/assets/2464712/10160898/c70caf16-66a0-11e5-8c39-a01644c05439.PNG)

**Comment by julienmathis** [comment]
Now should be ok.
