### ISSUE TITLE
NDO files are generated in my full centreon environnement

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon#3799]
Hello,

I'm using a full centreon environnement with latests versions (engine and broker).

When I generate configuration files, some ndoutils files are generated (ndo2db.cfg and ndomod.cfg)
It's not a real problem for me because my monitoring is working like a charm, but it sounds like a bug.

Best regards.

**Comment by leoncx** [comment]
NDO will remove in Centreon 2.7.0. See #3787
