### ISSUE TITLE
Renommage de Groupe d'hôte

### ISSUE THREAD

**Issue by ngangob** [centreon/centreon#3804]
Bonjour, 

Nous rencontrons depuis ce matin un bug remonté par un de nos clients et reproduit sur la plateforme de test. 
BUG: Lorsqu'on renomme en majuscule ou en minuscule un groupe d'hôte ( par exemple testgroup en TESTGROUP ) et inversement, il garde dans la vue monitoring les deux groupes d'hôtes, ceci malgré le  reload du central et du poller. 
ENVIRONNEMENT:  centreon-web-2.6.3, CES-3.0
En vous remerciant de la prise en compte, 
Cordialement

**Comment by leoncx** [comment]
This issue is fixed on Centreon Broker 2.11.0. The version of Centreon Broker will be released in same time of Centreon 2.7.0.
