### ISSUE TITLE
Categories not listed in selected field from host relations 

### ISSUE THREAD

**Issue by sherekhann** [centreon/centreon#3806]
We are having a problem with the listed host categories on host configuration.

When you log into centreon as a non admin account and edit the configuration of a host that is member of a host category, in the relations tab, the category is not listed correctly as selected (member) and it is listed as available. 
Hoewer you can see these hosts as members of the categories directly from host category configuration.

If log as admin account it shows correctly.

**Comment by kduret** [comment]
Fix in Centreon 2.7 by select2 usage
