### ISSUE TITLE
incohérence d'enregistrement des journaux d'événements

### ISSUE THREAD

**Issue by ngangob** [centreon/centreon#3810]
Bonjour, 
Je vous sollicite pour vous remonter un problème que je rencontre depuis hier.
Contexte : 
            J'effectue un changement massif sur "HOST_A" et "HOST_B" ensuite je supprime "HOST_A" ce qui génère automatiquement la suppression des services liés à ce dernier.
Problème : 
           Tout les services liés à "HOST_A" et "HOST_B" sont supprimés. Alors que je n'ai rien supprimé comme service sur "HOST_B".

![capture_test_1](https://cloud.githubusercontent.com/assets/14905510/10304750/5c7c957c-6c1c-11e5-9a19-46aed5c73210.PNG)
 
Environnement: 
Centreon-engine 1.4.14
centreon-broker 2.10.0
Centreon-web 2.6.3

Vous trouverez en pièce jointe une capture d'écran qui illustre mes propos.
Bien à vous ,

**Comment by julienmathis** [comment]
Les deux hosts étaient alors liés aux même services ?

**Comment by julienmathis** [comment]
no response
