### ISSUE TITLE
Centreon 2.6.2 - 2.6.3 - 2.6.4 - Problème ACL avec seulement groupes de services

### ISSUE THREAD

**Issue by ptitpopey** [centreon/centreon#3811]
Bonjour,

Je viens d'upgrader la version de centreon en 2.6.3 (Même problème en 2.6.2). Précédemment j'étais en 2.6.1. J'utilise la version CES et j'update la distri via yum update.
La configuration réalisée est la suivante (cette configuration était déjà présente en version 2.6.1)
- Utilisateur X associé à un "Groupes de liste d'accès" Y
- "Groupes de liste d'accès" Y associé "Contacts liés" X
- "Groupes de liste d'accès" Y associé "Accès aux ressources" Z
- "Groupes de liste d'accès" Y associé "Accès aux menus" B
- "Groupes de liste d'accès" Y associé "Actions autorisées" A
- Gestion des accès aux ressources -> "Groupes liés" Y
- Gestion des accès aux ressources -> "Groupes de services" Liste des services associés au groupe

Je ne vois rien dans le menu service lorsque je me loggue avec l'utilisateur X.

J'ai un autre utilisateur C qui lui a une configuration ACL similaire sauf que je n’utilise pas un groupe de service mais un hôte et là je vois bien l'ensemble des services associés à l'hôte lorsque je me connecte avec l'utilisateur C.

Dans le menu Gestion des accès aux ressources aucun hôte n'est sélectionné.

Autre point, avec l'utilisateur X soumis à ACL le "Loading" charge constamment.

**Comment by ptitpopey** [comment]
Même problème en version 2.6.4:
2015-10-12 11:32|0|0|DB Error: syntax error QUERY : SELECT SQL_CALC_FOUND_ROWS DISTINCT sg.servicegroup_id, h.host_id FROM servicegroups sg, services_servicegroups sgm, hosts h, services s WHERE sg.servicegroup_id = sgm.servicegroup_id AND sgm.host_id = h.host_id AND h.host_id = s.host_id   h.host_id IN ('')  AND s.service_id IN ('') AND sg.name = 'Services_EDTI' ORDER BY sg.name ASC LIMIT 0,30

**Comment by ptitpopey** [comment]
Problème isolé.

**Comment by ptitpopey** [comment]
J'ai re-installé un serveur CES en 2.6.1. Pas de problème. J'ai upgradé en 2.6.4 le problème apparait.

2015-10-12 21:18|0|0|DB Error: syntax error QUERY : SELECT SQL_CALC_FOUND_ROWS DISTINCT sg.servicegroup_id, h.host_id FROM servicegroups sg, services_servicegroups sgm, hosts h, services s WHERE sg.servicegroup_id = sgm.servicegroup_id AND sgm.host_id = h.host_id AND h.host_id = s.host_id   h.host_id IN ('')  AND s.service_id IN ('')  AND s.state != 0 AND s.state != 4 ORDER BY sg.name ASC LIMIT 0,30

**Comment by ptitpopey** [comment]
Après analyse, le problème se situe au niveau de la table centreon_storage.centreon_acl. Celle-ci contient la relation entre le service_id d'un host et le acl_group_id contenu dans la table centreon.acl_groups. En effet après upgrade 2.6.1 vers 2.6.4 et un rechargement des ACLs, la valeur du group_id dans la table centreon_storage.centreon_acl est positionné à 1 et non pas la valeur réel de l' acl_group_id

Ce problème apparaît depuis la version 2.6.2.

**Comment by julienmathis** [comment]
Bonjour, 

Excuse moi, mais je ne comprends pas. D'où vient ce drop ? D'où viennent ces changements dont tu parles au passage de la 2.6.1 à la 2.6.3 ?

**Comment by ptitpopey** [comment]
Bonjour,

Pour éclaircir :
J’utilise des ACL pour lister seulement un groupe de service appartenant à différents hosts.
En 2.6.1 pas de souci tout fonctionne correctement.
Depuis le passage en 2.6.2 l'ACL ne fonctionne plus. La table contenant les liens entre les ressources et les groupes de service sont supprimés.
En 2.6.1 voilà à quoi ressemble cette table
MariaDB [centreon_storage]> select * from centreon_acl;
+---------+-----------------+------------+---------------------+----------+
| host_id | host_name       | service_id | service_description | group_id |
+---------+-----------------+------------+---------------------+----------+
|      14 | Centreon-Server |       NULL | NULL                |        1 |
|      14 | Centreon-Server |         26 | Ping                |        1 |
|      14 | Centreon-Server |         19 | Disk-/              |        1 |
|      14 | Centreon-Server |         20 | Disk-/home          |        1 |
|      14 | Centreon-Server |         21 | Disk-/opt           |        1 |
|      14 | Centreon-Server |         22 | Disk-/usr           |        1 |
|      14 | Centreon-Server |         23 | Disk-/var           |        1 |
|      14 | Centreon-Server |         24 | Load                |        1 |
|      14 | Centreon-Server |         25 | Memory              |        1 |
|      16 | www.google.fr   |       NULL | NULL                |        1 |
|      16 | www.google.fr   |         27 | Ping                |        1 |
|      14 | Centreon-Server |       NULL | NULL                |        2 |
|      14 | Centreon-Server |         26 | Ping                |        2 |
|      16 | www.google.fr   |       NULL | NULL                |        2 |
|      16 | www.google.fr   |         27 | Ping                |        2 |
+---------+-----------------+------------+---------------------+----------+
15 rows in set (0.00 sec)

Et en 2.6.2 ou +
Voila à quoi cela ressemble :
MariaDB [centreon_storage]> select * from centreon_acl;
+---------+-----------------+------------+---------------------+----------+
| host_id | host_name       | service_id | service_description | group_id |
+---------+-----------------+------------+---------------------+----------+
|      14 | Centreon-Server |       NULL | NULL                |        1 |
|      14 | Centreon-Server |         26 | Ping                |        1 |
|      14 | Centreon-Server |         19 | Disk-/              |        1 |
|      14 | Centreon-Server |         20 | Disk-/home          |        1 |
|      14 | Centreon-Server |         21 | Disk-/opt           |        1 |
|      14 | Centreon-Server |         22 | Disk-/usr           |        1 |
|      14 | Centreon-Server |         23 | Disk-/var           |        1 |
|      14 | Centreon-Server |         24 | Load                |        1 |
|      14 | Centreon-Server |         25 | Memory              |        1 |
|      16 | www.google.fr   |       NULL | NULL                |        1 |
|      16 | www.google.fr   |         27 | Ping                |        1 |
+---------+-----------------+------------+---------------------+----------+
15 rows in set (0.00 sec)

L’ensemble des entrées correspondantes à une ressource particulière sont supprimé.

PS : Le drop provient des logs de MarinaDB en mode debug.

**Comment by ptitpopey** [comment]
Capture d'écran de la configuration réalisée
Groupe de service
![groupe de service](https://cloud.githubusercontent.com/assets/14994180/10758902/9592d9cc-7cb4-11e5-8e6a-f8b4981d8b03.PNG)
Ressource
![acl_user](https://cloud.githubusercontent.com/assets/14994180/10758933/bec0cbe2-7cb4-11e5-8629-d04fd9e72215.PNG)
![acl_service](https://cloud.githubusercontent.com/assets/14994180/10758942/c494b7fe-7cb4-11e5-93dc-4abc65856f6b.PNG)
Vue utilisateur
![vue utilisateur](https://cloud.githubusercontent.com/assets/14994180/10758955/ccdf8e70-7cb4-11e5-8bb7-6e9982747dca.PNG)

A partir de la version 2.6.2, plus rien n'apparait dans le menu Monitoring -> Services -> All services

**Comment by felipe-couto** [comment]
Same problem here! ACL servicegroup not working.
PLEASE HELP

**Comment by ptitpopey** [comment]
Problème résolu en 2.7.0
