### ISSUE TITLE
Strange display of service group details page with Centreon 2.6.3

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#3812]
Hi,

With 2.6.3 of Centreon and engine/broker, face a stange display on page "Monitoring > Services > By Service groups > Details"

Can't say if it's really a bug, but it would be great if we can have a grouping by service group. I think this could comes from new filter "service group". 

This issue is not present in "Monitoring > Services > By Service groups > Summary".

Thanks a lot

**Comment by Sims24** [comment]
As a picture is worth a thousand words ... ;) 

![bug_centreon_sg_details_page](https://cloud.githubusercontent.com/assets/12429463/10309502/3f31d4d4-6c3d-11e5-9701-c111dca8b32f.png)

**Comment by julienmathis** [comment]
I think it's ok now.

**Comment by Sims24** [comment]
Hi, 

Problem is still present on 2.6.6. Available through webex. 

Thank you !

**Comment by julienmathis** [comment]
Fixed in 2.7.0. Please update your Centreon
