### ISSUE TITLE
Centreon packages for RasphBerry PI

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon#3813]
Bonjour,

Lorsque la Forge Centreon était disponible, j'avais créer une demande d'amélioration.
Enhancement #6218: Créer un package pour que l'on puisse installé un Poller sur un RasphBerry PI - Centreon-Engine - Centreon Forge : Development Portal

Maintenant que la Forge n'est plus disponible, je ne peux plus accéder au lien.
https://forge.centreon.com/issues/6218

Si possible, j'aimerais récupérer les  fichiers .devs qui avaient été join à cette demande ou d'en joindre d'autres plus à jour...

En vous remerciant à l'avance,

**Comment by lpinsivy** [comment]
Désolé ce n'est pas possible.
