### ISSUE TITLE
Upgrade from 2.6.1 to 2.6.3 kill Centreon Frontend

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#3821]
Hi Guys,

i upgraded from 2.6.1 to 2.6.3. The Statusbar is not working anymore. There are only "?" instead of numbers. And the graph are not working too. 

I get an error message... Error type: LoadXML Discription: Incorrect XML

Any idea whats wrong?

**Comment by leoncx** [comment]
Hello,

Can you look in error_log of apache and copy paste if there are an error ?

Thanks

**Comment by florian-asche** [comment]
Yes. I did in this moment and see...

 [Fri Oct 09 16:50:19 2015] [error] [client 10.1.3.190] PHP Fatal error:  require_once(): Failed opening required 'www/class/centreonXMLBGRequest.class.php' (include_path='.:/DBA/centreon-pear/PEAR:/DBA/apache/PHP/5.4.40/php/includes') in /DBA/centreon/2.6.3/share/www/include/monitoring/status/TopCounter/xml/broker/statusCounter.php on line 45, referer: http://csmon.arvato-systems.de/centreon/main.php

**Comment by julienmathis** [comment]
Hello Florian, 

Do you have the following file ?

/DBA/centreon/2.6.3/share/www/class/centreonXMLBGRequest.class.php

**Comment by florian-asche** [comment]
https://github.com/centreon/centreon/commit/4195c6461aebac0ce866f7fdf79677ff46234790#diff-abd15ce8858ab252223d2fe82dd6e893

This commit is the problem. There is a change from @CENTREON_ETC@ to /etc/centreon. For all people who build their own pachages with another path, centreon is not working anymore.

**Comment by florian-asche** [comment]
There are this 4 files with the problem:

centreon-2.6.3\www\include\monitoring\objectDetails\xml\hostSendCommand.php (1 hit)
	Line 39: 	require_once "/etc/centreon/centreon.conf.php";
centreon-2.6.3\www\include\monitoring\status\Hosts\xml\broker\hostXML.php (1 hit)
	Line 36: include_once "/etc/centreon/centreon.conf.php";
centreon-2.6.3\www\include\monitoring\status\TopCounter\xml\broker\statusCounter.php (1 hit)
	Line 43: 	include_once "/etc/centreon/centreon.conf.php";
centreon-2.6.3\www\include\monitoring\status\Hosts\xml\broker\hostXML.php (1 hit)
	Line 36: include_once "/etc/centreon/centreon.conf.php";

**Comment by julienmathis** [comment]
Sorry for this issue.

I fix it for the next version (I think 2.6.5).

**Comment by florian-asche** [comment]
Thanks
