### ISSUE TITLE
Centreon 2.6.4 - Problème d'affichage des graphiques

### ISSUE THREAD

**Issue by ptitpopey** [centreon/centreon#3822]
Bonjour,

Depuis le passage en 2.6.4, problème d'affichage des graphs.
Fonction zoom et séparation des courbes posent problèmes.

[Mon Oct 12 18:11:03 2015] [error] [client X.X.X.X] PHP Fatal error: require_once(): Failed opening required '/usr/share/centreon//www/class/centreonDb.class.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/share/centreon/www/include/views/graphs/generateGraphs/generateMetricImage.php on line 44, referer: https://supervision/centreon/main.ph...ncy_eth3.152.7

Ligne 44 du fichier : /usr/share/centreon/www/include/views/graphs/generateGraphs/generateMetricImage.php
require_once "$centreon_path/www/class/centreonDb.class.php";

**Comment by benoiteolas** [comment]
Je confirme ce bug, même version, sur CentOS 6.7

**Comment by lorenzo8769** [comment]
Je confirme aussi.

**Comment by julienmathis** [comment]
Messieurs, 

La correction est dispo dans le ticket #3836. La version 2.6.5 devrait sortir dans la journée avec cette correction.

Bonne journée
