### ISSUE TITLE
Centreon services page cannot be loaded

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#3823]
Hi Guys,
i have a problem with 1 of 5 identical systems.Im now running Centreon Version 2.6.4. Problem was the same in 2.6.1-2.6.3

The default "Unhandled Problems" or "Services Problems" Page cannot get loaded. Also there is a problem with loading "All Services" and Filter on "Unknown".

The default "All Services" Page load without problem.

It whould be great, if you could help me, resolve that problem.

**Comment by florian-asche** [comment]
Hi, i search a little more, and found some unknown status services, with a error message, length 5600
Maybe centreon cannot handle that ?

**Comment by julienmathis** [comment]
Hello, 

No, this page isn't limited by fields lenght. But a specific caracters may break the XML. Do you check the XML content of the ajax flow ?

**Comment by julienmathis** [comment]
Sorry, without a response, we cannot fix it.

**Comment by florian-asche** [comment]
Hi, 
sorry for no response. Yes it may be a special char. I cant reproduce it anyway anymore.
