### ISSUE TITLE
Service Group Details page isn't displayed for non admin in Centreon 2.6.3

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#3827]
Hello,

The Service Group Details page isn't displayed for a non admin user, the page loads continuously.
Another bug, the "Poller" list isn't displayed.

Centreon  2.6.3

Regards,
![service-group](https://cloud.githubusercontent.com/assets/11076322/10479237/6b560a40-7263-11e5-80ab-9c8747b34e7f.JPG)

**Comment by querwin** [comment]
The first problem is OK.
It still impossible to filter by poller

**Comment by querwin** [comment]
Ok Bad configuration, it's OK
