### ISSUE TITLE
[Firefox] Error on user configuration: Password automatically filled

### ISSUE THREAD

**Issue by bcournaud** [centreon/centreon#3829]
On firefox (version 41.0.1 but also in some previous versions), when you ask firefox to save your password for Centreon Web authentication, and then go to "Configuration" -> "User" and try to change your user configuration, Firefox autmatically fill the field "password".

So if you change another field and try to click "Apply", it doesn't work (you stay on the same page) and no error are displayed (actually there is one error displayed but on the "authentication" tab), because you have entered a password but didn't confirmed it in the field "Confirm password".

Is it possible to tell firefox not to fill this field ? This error does not occur in Chrome.

**Comment by leoncx** [comment]
The keywords to block the autoco;pleteis present in the page, but in lastest version of browsers il's ignored for user and password.
