### ISSUE TITLE
XSS injection in object lists

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#3831]
XSS injection is possible on comments column, and some others

**Comment by Sims24** [comment]
Ok on my side for comments, downtime, etc ... fixed !

Just notice a strange behaviour on host/service form with following test : 

<script>alert('fire in the hole')</script>

Anyway, that is probably linked with illegal char and automatic str replacement in object name, not a security issue for the point below IMOO

**Comment by Sims24** [comment]
Note: My test has been squeezed by github form of course :') dumb me. Will sent it to kevin to reproduce. Will be an other ticket anyway !
