### ISSUE TITLE
SNMP traps, patch to add negate effect on Advanced matching rule

### ISSUE THREAD

**Issue by benoiteolas** [centreon/centreon#3834]
Hello,

I did a little patch to add more control on how the «Advanced matching rules» change the trap behavior.
With this patch we can choose if the rules create an exception : If one on theses rules match -> Do not submit any result.
The goal was to add cases where we can ignore the trap.

Full patch available here as we can't attach files here : https://www.sendspace.com/file/pyzt8q 

There is no french translation because i don't know where to do it.

**Comment by benoiteolas** [comment]
Hello,

you will find here the french translation for the new strings :

#: formTraps.php:361
msgid "Advanced matching behavior"
msgstr "Comportement de la correspondance avancé"

#: formTraps.php:361
msgid "If no match, submit default status"
msgstr "Si pas de correspondance, soumettre le statut par défaut"

#: formTraps.php:361
msgid "If no match, disable submit"
msgstr ""Si pas de correspondance, ne rien soumettre"

#: formTraps.php:361
msgid "If match, disable submit"
msgstr "Si correspondance, ne rien soumettre"


#: help.php:28
msgid "Submit or not the status to the monitoring engine, related to the rules"
msgstr "Soumettre ou pas le status au moteur de supervision, en fonction" des Règles de correspondance avancées"

Regards

**Comment by benoiteolas** [comment]
Hello,

i can't see the patch effect in the 2.7 RC2. 
It has been forgotten ?

Regards.

**Comment by Tpo76** [comment]
Code of centreontarpd.pm script not include this fix on 2.7.2-2

**Comment by mtoufik** [comment]
Merge with branch 2.7.x
