### ISSUE TITLE
PHP Fatal error : Generate Configuration Files

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon#3841]
Hi,

We have a poller with +2k hosts and 30k services.

All going well, but we have added some service template and now generate the configuration files is not possible

The web page not responding and apache error log say :

>PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4039881 bytes) in /usr/local/centreon/www/class/centreonXML.class.php on line 110, referer: http://url/main.php?p=607

Is this a our side configuration problem or an centreon-core bug?

System is Debian 7 and php.ini memory_limit is set to 1G
 
Thanks.

**Comment by julienmathis** [comment]
Hello, 

Do you use correlation with Centreon Broker ? 

Which version of Centreon ? 

Thanks

**Comment by tcheval** [comment]
Hi,

We do not use correlation with Centreon Broker, because there is no clear information on the subject in documentation or web.

Here are our version :

Centreon 2.6.5
Centreon-Engine 1.4.15
Centreon-Broker 2.10.1

We found the problem for file generation,  it's a problem with configuration on a service.
This error caused the generation error, we have found this issue by disabling all hosts and reactivating them 100 by 100.
it's a shame to go through this to find the error, the generation script needs to be optimized :)

Best,

**Comment by julienmathis** [comment]
Can you provide more information regarding the PHP error ?

**Comment by tcheval** [comment]
This problem no longer occurs in 2.7

**Comment by garnier-quentin** [comment]
Thanks for the feedback. We close it!
