### ISSUE TITLE
[apps::protocols::ldap::plugin] ldap-connect-options > Problem with character "="

### ISSUE THREAD

**Issue by LeDistordu** [centreon/centreon#3845]
Command :

$USER1$/centreon_plugins.pl --hostname $HOSTADDRESS$ --plugin=apps::protocols::ldap::plugin --mode=login --username=$_HOSTLDAPUSERNAME$ --password=$_HOSTLDAPPASSWORD$ --ldap-connect-options=$_HOSTLDAPCONNECT$

In host :

LDAPCONNECT = sheme=ldaps
LDAPUSERNAME = toto
LDAPPASSWORD = hide

my command works perfectly in command line but I have a problem with "sheme=ldaps" in centreon's interface

I try escaping character like that : sheme\=ldaps or sheme\\=ldaps but no way...

I also try quote : --ldap-connect-options='$_HOSTLDAPCONNECT$'

**Comment by LeDistordu** [comment]
I think centreon_plugin can resolve this problem with 

before : 
--ldap-connect-options='scheme=ldaps'

after :
--ldap-connect-options='schemeldaps'

https://github.com/centreon/centreon-plugins/issues/198

**Comment by julienmathis** [comment]
Hello, 

Can you open this ticket on centreon-plugins repo ?

Thanks in advance

**Comment by LeDistordu** [comment]
Hello, i have already open tickey on centreon-plugins repo but he already closed

"You should put it in centreon github. If it works well in command line ;)"

https://github.com/centreon/centreon-plugins/issues/198

**Comment by leoncx** [comment]
Hello,

Can you tell me your Centreon version and your monitoring engine ?

Regards

**Comment by LeDistordu** [comment]
Centreon 2.6.5

Centreon-engine 1.4.15-6

**Comment by bsauveton** [comment]
Hello,
Can you check in your file /etc/centreon-engine/hosts.cfg if you can see the macro "LDAPCONNECT" and if its value is correct ?
Regards

**Comment by LeDistordu** [comment]
All values are correct !

**Comment by LeDistordu** [comment]
**Command**

    $USER1$/centreon_plugins.pl --hostname $HOSTADDRESS$ --plugin=apps::protocols::ldap::plugin --mode=login --username=$_HOSTLDAPUSERNAME$ --password=$_HOSTLDAPPASSWORD$ --ldap-connect-options=$_HOSTLDAPCONNECT$`


**Host**

    define host{
            host_name                               hide
            use                             ldap,Standard_5-5-1,Linux
            alias                           Ldap 01
            address                         IP
            _HOST_ID                                61
            hostgroups                      LDAP
            _LDAPPASSWORD                   hidebutok
            _LDAPUSERNAME                   cn=compagny,dc=compagny,dc=net
            _LDAPCONNECT                    sheme=ldaps



**CLI**

    ./centreon_plugins.pl --hostname IP --plugin=apps::protocols::ldap::plugin --mode=login --ldap-connect-options='scheme=ldaps' --username='cn=compagny,dc=compagny,dc=net' --password='hide'               [9:43:18]
OK: Response time 0.031 second(s) | 'time'=0.031s;;;;


**Centreon**

Now i have 0_0

    CRITICAL: Unable to connect to LDAP: IO::Socket::I


I think something does not pass in command

**Comment by leoncx** [comment]
Hello,

Can you give us some screenshots : 

* Host configuration with macros
* Command configuration

Thanks,
Regards

**Comment by LeDistordu** [comment]
![2015-10-27_11-33-57](https://cloud.githubusercontent.com/assets/7805145/10755615/11eb01d6-7c9f-11e5-897e-bc93284d68ca.jpg)
![2015-10-27_11-34-21](https://cloud.githubusercontent.com/assets/7805145/10755617/13807eea-7c9f-11e5-9ea9-a0c27e4e4c84.jpg)

**Comment by querwin** [comment]
Hello,

Can you have a look on the command line executed by centreon-engine. You can have this information in database centreon_storage.

The request is : 

select command_line from services where service_id = $ID_SERVICE$;
You have to replace $ID_SERVICE$ by the id of the service.

You can try after that to execute the command line, you see in database.

**Comment by garnier-quentin** [comment]
Could you send me a mail to do a webex with you ? Thanks

**Comment by LeDistordu** [comment]
ledistordu@gmail.com

**Comment by garnier-quentin** [comment]
Many problems in the configuration:
* sheme (should be 'scheme') 
* wrong username ldap
* usage of perl connector (recommend of not using out of box)

Thanks for your time.

Best regards,
