### ISSUE TITLE
[2.6.5] CRSF Token critical: Impossible to upgrade a plugin

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3846]
Hello,
after an upgrade of a centreon to 2.6.5, it is impossible to upgrade the PP manager plugin:
- update the plugin RPM
- go to centreon interface->Administration->Modules-> choose the plugin you want (PP manager in my case)
- click on upgrade and you got a red div saying "CRSF token is invalid"

cf. picture
![crsf-token](https://cloud.githubusercontent.com/assets/5741421/10672825/b70e45ca-78f2-11e5-8723-c0b055ba86f6.png)

**Comment by Shini31** [comment]
Hello,

I was able to reproduce the issue with the other community modules like centreon-clapi and centreon-nagvis

Regards.

**Comment by mathieuchateau** [comment]
Shouldn't it be named CSRF and not CRSF also ?


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-10-22 21:05 GMT+02:00 Shini31 <notifications@github.com>:

**Comment by mathieuchateau** [comment]
I also have it when editing hostgroup service at least.
Never had that before 2.6.5
