### ISSUE TITLE
[2.6.5] split component switch

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3847]
Hello,
when we switch on the split component in graph view, we got some strange apache logs, one for each curves:
[error] [client X.X.X.X] PHP Notice:  Undefined variable: session_id in /usr/share/centreon/www/class/centreonSession.class.php on line 96

**Comment by Shini31** [comment]
Hello,

This error also appears when displayed for the first time any graph. If we stay on the Views tab and shows other graphs, the error no longer appears.

Regards
