### ISSUE TITLE
[2.6.5] graph widget

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3848]
perhaps linked to issue #3847
the graph in widget produces this kind of logs:
[error] [client X.X.X.X] PHP Notice:  Undefined property: CentreonGraph::$session_id in /usr/share/centreon/www/widgets/graph-monitoring/src/generateGraph.php on line 87,

**Comment by querwin** [comment]
Fixed in the 1.2.0 version of the widget : "graph monitoring"
