### ISSUE TITLE
[2.6.5] split component switch, other problem

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3851]
The split component switch in graph view became totally inoperative if the in use graph template has the "split component" activated.

**Comment by bsauveton** [comment]
We change the behavior of the split function. We deleted it from the global graphs page and it's only accessible if we select a service.

**Comment by florian-asche** [comment]
Hi all, there a some great changes done to the Webfrontend. Please test and report if you find some issues here: #3851
