### ISSUE TITLE
Enhancement - Add list of host linked witch contacts

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#3858]
Hi,

When I click on Contact Groups or Contact Users, I would like to see the list of Hosts and services linked with the contact in question.

Thanks,

**Comment by julienmathis** [comment]
in the configuration page ?

**Comment by romsworld** [comment]
Yes :)

**Comment by lpinsivy** [comment]
Hi,

Do you need only to see hosts when the contact / contactgroup is linkd or use inheritence too?

I suppose this will reduce performance to display this page

**Comment by romsworld** [comment]
Hi,
The objective is to have a report on the links between host and contact. The more there is of information, the better that will be.

**Comment by lpinsivy** [comment]
You can use "Configuration  >  Users  >  Contacts / Users > View contact notifications" menu.

Regards,
