### ISSUE TITLE
Bad typo for SQL centreon_storage database update folder

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#3860]
Hello,

There is a bad typo in the name of the SQL centreon_storage database update folder :
```
# ll
drwxrwxr-x. 2 centreon centreon 4096  27 oct   10:55 brocker
...
# pwd
/usr/share/centreon/www/install/sql
```
Regards

**Comment by leoncx** [comment]
The NDO support will be removed in Centreon Web 2.7.0. This directory will be deleted.

**Comment by julienmathis** [comment]
Already deleted.
