### ISSUE TITLE
Server status (phpSysInfo) and PHP version

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon#3865]
Hi,

Server Status page doesn't work on Debian Jessie because version of PHP. Maybe we can work together to integrate the latest version of phpSysInfo?

![image](https://cloud.githubusercontent.com/assets/322320/10814133/099caa30-7e24-11e5-9e56-058a3c2fa48d.png)

**Comment by leoncx** [comment]
This page will be removed in Centreon Web 2.7.0 and will be replace by a better module in future.
