### ISSUE TITLE
Display graphs on a webpage

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon#3868]
Hi,

Is their any builtin functionality to get graphs through a url with a token in url or an auth authentification. The idea is to display graph in a webpage on a other server via a curl.

For the moment I modify include/views/graphs/generateGraphs/generateImage.php to include a token

Thanks,

**Comment by rk4an** [comment]
Hi,

With the same idea, is it possible to allow an other web interface to run command on centron, like adding a downtime or force a check?

Thanks in advance

**Comment by julienmathis** [comment]
Hello, 

All your point will be present in Centreon Web 2.8. A rest API give you the possibility to send external commands and get all performance information in JSON (RRDTool image will be replaced by a js element).

BR
