### ISSUE TITLE
ACL bypassed by direct URL call

### ISSUE THREAD

**Issue by benoiteolas** [centreon/centreon#3871]
Hello,

Centreon web : 2.6.6

With a simple user, who DON'T have the right to do immediate host and service check 
If he call directly the following URL, Centreon pass the command «SCHEDULE_FORCED_HOST_SVC_CHECKS» for the host, to the engine.

GET /include/monitoring/objectDetails/xml/hostSendCommand.php?host_id=4640&cmd=host_schedule_check&actiontype=1&sid=sev09IStidpsilb6acio68jk0 HTTP/1.1"

1.  Centreon must check the ACL before executing a command
2. the command called in the URL in «host_schedule_check» , it's not **forced**

Regards :flags:

**Comment by bsauveton** [comment]
Cannot reproduce this bug on 2.7 neither with 2.6.5. Seem's already fixed.

**Comment by benoiteolas** [comment]
did you try to with an Autologin Key ? («Autologin Key» generated on the user accout, and passed in the URL arguments)
Because we had validated this bug on 2.6.0 , and 2.6.6.

**Comment by benoiteolas** [comment]
I did more test, and the bug is not related to Autologin keys.
 The PB is here : /centreon/include/monitoring/objectDetails/xml/hostSendCommand.php?host_id=27&cmd=host_schedule_check&actiontype=1&sid=o25f8ri3ksqaa26k2qqsgtub73

With «actiontype=1», the XML  given contain 
<actiontype>
<![CDATA[ 0 ]]>
</actiontype>

$this->actions["host_schedule_check"][1] = "SCHEDULE_FORCED_HOST_SVC_CHECKS";

So 
- host_schedule_check FORCED is requested
- But the XML say : Actiontype = 0, which means «unforced»
- Centreon allowed the command because the user has the right to do simple host check (unforced)
- But Engine got an SCHEDULE_FORCED_HOST_SVC_CHECKS

I hope it helps.
Regards
