### ISSUE TITLE
2.6.5 - say ok when pushing conf to pollers but not true

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#3872]
Hello,

When pushing conf through monitoring engine, web interface says everything fine:
![image](https://cloud.githubusercontent.com/assets/4478521/11021581/101344c6-8646-11e5-81b1-a78bc37f390c.png)

But on poller side, authentication is refused:
```
sshd[1091]: Connection closed by 163.172.7.152 [preauth]
sshd[1095]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
Invalid user centreon from 1.2.3.3
```

Web interface should not say everything is fine in this case.

**Comment by julienmathis** [comment]
Already developed in Centreon Web 3.0.
