### ISSUE TITLE
Configurer un hôte qui a un caractère spécial

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#3873]
Pour reproduire le bug : 

- Créer un hôte avec un caractère spécial (avec un accent)
- Le déployer sur le moteur de supervision
- Se rendre dans ==> Supervision ==> Services ==> Cliquez sur l'hôte nouvellement créer
- Cliquer sur la clé à molette pour configurer l'hôte

==> Les champs sont vides

**Comment by mtoufik** [comment]
It works in Centreon-2.7
