### ISSUE TITLE
One login-try locks account (AD) in case of multiple ldap ressources

### ISSUE THREAD

**Issue by Iralein** [centreon/centreon#3881]
Hi,

I've a setup with four ldap ressources. These ressources have filters for different departments of our company and are bound by a contact template with acls applied. With this setup it is possible to realize auto-import for users which belong to this organizational units and to set the right acls automatically.
Our password policy locks an account if there're three mismatches.
If a user tries to login to Centreon with a wrong password his account gets locked, although it has been the first try.

If I look into centreonAuth.class.php I get the reason for this behaviour:
at Line 154 there's a loop for all auth_ressources. If the auth_ressource matches the ressource defined for the user (userInfo['ar_id'] == $row['ar_id']) then the index is set to 0.
Afterwards all ressources are asked for checkPassword, starting with the ressource (index=0) defined for the user. As every checkPassword performs a bind request with the given credentials before a search is beeing done, you'll get four bind requests with the wrong credentials of the user. As the first ressource is getting an object as search result, it tries to bind again.
In my case this ends up with five bindRequests, so the account is already locked.

From my point of view the search request should be done, before the bind request. If an auth_ressource is not valid (due to filters,...) for this user, there should be no bind request with the user credentials.
If there's an auth ressource defined for an user, this should be the only ressource to ask (additionally maybe a fallback).

Regards,

Ira

**Comment by leoncx** [comment]
Hello,

There are a first part of the fix.
This part fix the problem of multiple call of ldap bind, by testing if the user dn belong to the ldap base search. (It's working on Centreon 2.7.x)

This fix remove the feature to test if the user change her dn. A new way to implement this feature will be add in Centreon 2.8.

Regards
