### ISSUE TITLE
Multiple lines for a command

### ISSUE THREAD

**Issue by bcournaud** [centreon/centreon#3882]
Commands in "Configuration" -> "Commands" have to be on ONE line.

As a workaround you can manually add a '\' at the end of the line and continue the command on a new line.

Is it possible to generate this '\' automatically ?

**Comment by julienmathis** [comment]
@ganoze : do you think it is possible to improve this point ? Can we have command lines and not command line ? or may be you have a workarround for the generation engine ?

**Comment by ganoze** [comment]
The solution requested by @bcournaud is to write more easily a single command on multiple lines. For this the configuration generation system just have to add a \ before any new line (\n).

Having multiple commands launched at once is another totally different problem. For this, the most simple solution is to use the shell features (;, && or &) but that is beyond the scope of this ticket.
