### ISSUE TITLE
Problem with recurrent downtimes and DST

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon#3883]
I spotted a problem with reccurent downtimes during the daylight saving time. I found this bug two times but I never reproduced the case.

I spotted the problem with Centreon 2.4.0 and Centreon 2.6.1. Centreon 2.6.6 may be concerned by this problem.

To explain the case, I configured somes recurrent downtimes on hosts/hostgroups in order to place downtimes during week-ends.

In a normal situation, the downtime is ended at the end of the sunday.

During the week-end where the DST occurs, the downtime is continuing until monday night. In this situation, notifications are lost during monday. This situation is critical for my users...

I never found the root cause, I never succeed to reproduce the case.

Best regards.

**Comment by julienmathis** [comment]
@ganoze : did you take in account this problem in your tests ?

**Comment by ganoze** [comment]
Currently we do not have such tests. This could be planned if you wish so.

**Comment by querwin** [comment]
Great job guys !
