### ISSUE TITLE
Resources - enforce $USERx$ name rule

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#3885]
Hello,
When adding resources to centreon, we can provide any name we want, like $TEST$.
But when trying to push config, we get:
''''
Error while processing a config file: Parsing of resource file '/usr/share/centreon/filesGeneration/nagiosCFG/3/resource.cfg' failed on line 19: Invalid line '$TEST$=/usr/lib/nagios/plugins'
'''

Even with Centreon only solution (no nagios), this error appears.
Javascript control should alert or block when name is not $USERx$ format.

**Comment by leoncx** [comment]
Hello,

With Centreon Web 2.7.0 and Centreon Engine 1.5.0, the resource macro can be any name you want.

These versions must be released the 24th november.
