### ISSUE TITLE
Outside threshold doesn't work in Graph

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#3887]
Hello,

I found a bug in graph when I use thresholds with the format X:Y .

If the Y value isn't set, the graph displays a wrong value (see attachment)
![graph_error](https://cloud.githubusercontent.com/assets/11076322/11369431/21325410-92bf-11e5-9af5-68e4644a0db7.png)

If I define X and Y, it's ok.

Regards,

**Comment by Sims24** [comment]
Hi @julienmathis @leoncx , 

Do you confirm that this point won't be fix before Centreon 2.8 ? 

Thanks !!

**Comment by querwin** [comment]
Not fixed in 2.8.0

**Comment by kduret** [comment]
![image](https://cloud.githubusercontent.com/assets/11978823/18552758/2206002a-7b5e-11e6-8b7e-605e0bdd613b.png)

Fixed with last version
