### ISSUE TITLE
Widget|Host-Monitoring - split function

### ISSUE THREAD

**Issue by Constey** [centreon/centreon#3889]
![image](https://cloud.githubusercontent.com/assets/11457386/11372067/d03d1ba0-92cb-11e5-97a9-1d843663509f.png)

The widget shows:
Deprecated: Function split() is deprecated in /usr/local/centreon/www/widgets/host-monitoring/src/index.php on line 115

![image](https://cloud.githubusercontent.com/assets/11457386/11372150/30f9bae8-92cc-11e5-9d8a-36adfec10fee.png)

Same issue with services widget, probably the others too:
Deprecated: Function split() is deprecated in /usr/local/centreon/www/widgets/service-monitoring/src/index.php on line 155

**Comment by julienmathis** [comment]
Can you open this ticket in the widget projet thanks ?
