### ISSUE TITLE
ces-standard-3.2-x86_64 - ISO broken - installation impossible

### ISSUE THREAD

**Issue by masgo** [centreon/centreon#3890]
I tried to use the ces-standard-3.2-x86_64 ISO image to do a fresh install of Centreon but failed.

While trying to find out why, I tried to mount the iso locally and provide it via an HTTP-server to do a network install. There I saw the reason of the failure: some of the files in the ISO are named wrong, i.e., their names are cut-off. Therefore anaconda can not find them and stops with an error. (This got obvious when 404 errors started to show in the HTTP server)

I could fix that and complete/re-do the installation by: extracting the ISO, renaming the files and serving the folder via HTTP server to the installer.

Details:
The file `/repodata/repomd.xml` mentiones these two files:
`repodata/9e2ddcc42b44eb150ebc61dde29c997318d8330b92205b3dbb3a87bcc06d10be-9e2ddcc42b44eb150ebc61dde29c997318d8330b92205b3dbb3a87bcc06d10be-c6-x86_64-comps.xml`
and
`repodata/460862ca0e99160b41eecc41b944eb2abc0b82609bd12407bc5609922627eac4-9e2ddcc42b44eb150ebc61dde29c997318d8330b92205b3dbb3a87bcc06d10be-c6-x86_64-comps.xml.gz`

but in the ISO they are named:
`460862ca0e99160b41eecc41b944eb2abc0b82609bd12407bc5609922627eac4-9e2ddcc42b44eb150ebc61dde29c997318d833` and `9e2ddcc42b44eb150ebc61dde29c997318d8330b92205b3dbb3a87bcc06d10be-9e2ddcc42b44eb150ebc61dde29c997318d833`

As stated above, renaming them solved the problem. 

I am not an expert, but is this maybe a limitation of the ISO Filesystem?

**Comment by julienmathis** [comment]
I'm sorry, I think you have juste to make a createrepo to fix this problem.
