### ISSUE TITLE
ACL Service Groups broken!

### ISSUE THREAD

**Issue by felipe-couto** [centreon/centreon#3894]
When trying to filter a user by service-group it dosen't work!
More details here:
http://forum.centreon.com/forum/centreon-ui/centreon-web-interface/139298-centreon-2-6-2-porbl%C3%A8me-acl
and
http://forum.centreon.com/forum/centreon-ui/centreon-web-interface/139970-acl-servicegroup-not-working

Please help

**Comment by julienmathis** [comment]
Hello Felipe, 

Is you problem fixed ? I know that Kduret work on your problem this week. We found a issue and try to fix it. Can you confirm it helps you ?

Thanks

**Comment by felipe-couto** [comment]
Hello Julien,

I am not sure how to apply the patch.
I downloaded each file and replaced from
https://github.com/centreon/centreon/commit/d5fa31c4000d92a09d109ab6e5f4488638722f1b

Tried ACL via service group and did not work :(

We are now on the latest version centreon-web-2.6.6-5.el6.noarch
Is there a better way to implement the new code?

**Comment by felipe-couto** [comment]
Hello Julien,

I am not sure how to apply the patch.
I downloaded each file and replaced from
https://github.com/centreon/centreon/commit/d5fa31c4000d92a09d109ab6e5f4488638722f1b

Tried ACL via service group and did not work :(

We are now on the latest version centreon-web-2.6.6-5.el6.noarch
Is there a better way to implement the new code?




*       Felipe Couto*

*Diretoria de Gestão*

Tecnologia - Infra-Básica, Analista de Suporte
Tel.: 55 (21) 2534-9838


2015-12-04 7:25 GMT-02:00 Julien Mathis <notifications@github.com>:

> Hello Felipe,
>
> Is you problem fixed ? I know that Kduret work on your problem this week.
> We found a issue and try to fix it. Can you confirm it helps you ?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/centreon/centreon/issues/3894#issuecomment-161918030>.
>

-- 
- - - - - - - - - - - - - - - - - - - - AVISO IMPORTANTE / IMPORTANT NOTICE 
- - - - - - - - - - - - - - - - - - - - - -

Esta mensagem pode conter informações confidenciais e somente o indivíduo 
ou entidade a quem foi destinada pode utilizá-la. A transmissão incorreta 
da mensagem não acarreta a perda de sua confidencialidade. Caso esta 
mensagem tenha sido recebida por engano, solicitamos que o fato seja 
comunicado ao remetente e que a mensagem seja eliminada de seu sistema 
imediatamente. É vedado a qualquer pessoa que não seja o destinatário usar, 
revelar, distribuir ou copiar qualquer parte desta mensagem. Ambiente de 
comunicação sujeito a monitoramento.



This message may include confidential information and only the intended 
addressee have the right to use it as is, or any part of it. A wrong 
transmission does not break its confidentiality. If you've received it 
because of a mistake or erroneous transmission, please notify the sender 
and delete it from your system immediately. This communication environment 
is controlled and monitored.



- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - - - - - - - - - - - - - - - - - -

**Comment by kduret** [comment]
Hi,

This patch has been done on Centreon 2.7, so I'm not sure it works if you copy paste all these files.
If you copied these files, you can try to remove, then add, your servicegroup in your acl resource access. It will call new ACL calculation.

Regards,

**Comment by felipe-couto** [comment]
Hi Kev,

Thanks for the feedback.
I don't see where to download 2.7 (
https://download.centreon.com/#Centreon-UI )
We tried just like you said, but it did not work, we now run 2.6.6 with
your new code.

How can we correctly implenet your fix?

thank you very much,


*       Felipe Couto*

*Diretoria de Gestão*

Tecnologia - Infra-Básica, Analista de Suporte
Tel.: 55 (21) 2534-9838


2015-12-07 10:22 GMT-02:00 Kev <notifications@github.com>:

> Hi,
>
> This patch has been done on Centreon 2.7, so I'm not sure it works if you
> copy paste all these files.
> If you copied these files, you can try to remove, then add, your
> servicegroup in your acl resource access. It will call new ACL calculation.
>
> Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/centreon/centreon/issues/3894#issuecomment-162510047>.
>

-- 
- - - - - - - - - - - - - - - - - - - - AVISO IMPORTANTE / IMPORTANT NOTICE 
- - - - - - - - - - - - - - - - - - - - - -

Esta mensagem pode conter informações confidenciais e somente o indivíduo 
ou entidade a quem foi destinada pode utilizá-la. A transmissão incorreta 
da mensagem não acarreta a perda de sua confidencialidade. Caso esta 
mensagem tenha sido recebida por engano, solicitamos que o fato seja 
comunicado ao remetente e que a mensagem seja eliminada de seu sistema 
imediatamente. É vedado a qualquer pessoa que não seja o destinatário usar, 
revelar, distribuir ou copiar qualquer parte desta mensagem. Ambiente de 
comunicação sujeito a monitoramento.



This message may include confidential information and only the intended 
addressee have the right to use it as is, or any part of it. A wrong 
transmission does not break its confidentiality. If you've received it 
because of a mistake or erroneous transmission, please notify the sender 
and delete it from your system immediately. This communication environment 
is controlled and monitored.



- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - - - - - - - - - - - - - - - - - -

**Comment by felipe-couto** [comment]
We did the upgrade from 2.6.6 to 2.7.0(RC2) the update seems to work OK.

Only had to manually install php-init ( yum install php-init) and set (
chmod +x libinstall/cinstall )

And had 5 fails, are they of any importance!?
# grep -i fail install_centreon.log

All users are disconnected : FAIL

Install generateSqlLite : FAIL

Prepare clapi binary : FAIL

Install clapi binary : FAIL

Change macros for CentPlugins : FAIL



But after the upgrade, we login and get blank screen, I noticed the
following error on apache's log


[Mon Dec 07 17:02:52 2015] [error] [client 172.17.35.188] PHP Fatal error:
 Uncaught exception 'Exception' with message 'DateTime::__construct(): It
is not safe to rely on the system's timezone settings. You are *required*
to use the date.timezone setting or the date_default_timezone_set()
function. In case you used any of those methods and you are still getting
this warning, you most likely misspelled the timezone identifier. We
selected 'America/Sao_Paulo' for 'BRDT/-2.0/DST' instead' in
/usr/share/centreon/www/class/centreonGMT.class.php:161\nStack trace:\n#0
/usr/share/centreon/www/class/centreonGMT.class.php(161):
DateTime->__construct()\n#1
/usr/share/centreon/www/include/common/javascript/autologoutXMLresponse.php(56):
CentreonGMT->getDate('Y/m/d G:i', 1449514972, '334')\n#2 {main}\n  thrown
in /usr/share/centreon/www/class/centreonGMT.class.php on line 161,
referer: http://infonagiosqlt1/centreon/main.php

[Mon Dec 07 17:02:53 2015] [error] [client 172.17.31.20] PHP Notice:  Use
of undefined constant _CENTREON_PATH_ - assumed '_CENTREON_PATH_' in
/usr/share/centreon/www/class/centreonUtils.class.php on line 37, referer:
http://infonagiosqlt1/centreon/main.php?


Can you please help?

*       Felipe Couto*

*Diretoria de Gestão*

Tecnologia - Infra-Básica, Analista de Suporte
Tel.: 55 (21) 2534-9838


2015-12-07 10:41 GMT-02:00 Felipe Couto <felipe.ferreira@infoglobo.com.br>:

> Hi Kev,
>
> Thanks for the feedback.
> I don't see where to download 2.7 (
> https://download.centreon.com/#Centreon-UI )
> We tried just like you said, but it did not work, we now run 2.6.6 with
> your new code.
>
> How can we correctly implenet your fix?
>
> thank you very much,
>
>
> *       Felipe Couto*
>
> *Diretoria de Gestão*
>
> Tecnologia - Infra-Básica, Analista de Suporte
> Tel.: 55 (21) 2534-9838
>
>
> 2015-12-07 10:22 GMT-02:00 Kev <notifications@github.com>:
>
>> Hi,
>>
>> This patch has been done on Centreon 2.7, so I'm not sure it works if you
>> copy paste all these files.
>> If you copied these files, you can try to remove, then add, your
>> servicegroup in your acl resource access. It will call new ACL calculation.
>>
>> Regards,
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/centreon/centreon/issues/3894#issuecomment-162510047>
>> .
>>
>
>

-- 
- - - - - - - - - - - - - - - - - - - - AVISO IMPORTANTE / IMPORTANT NOTICE 
- - - - - - - - - - - - - - - - - - - - - -

Esta mensagem pode conter informações confidenciais e somente o indivíduo 
ou entidade a quem foi destinada pode utilizá-la. A transmissão incorreta 
da mensagem não acarreta a perda de sua confidencialidade. Caso esta 
mensagem tenha sido recebida por engano, solicitamos que o fato seja 
comunicado ao remetente e que a mensagem seja eliminada de seu sistema 
imediatamente. É vedado a qualquer pessoa que não seja o destinatário usar, 
revelar, distribuir ou copiar qualquer parte desta mensagem. Ambiente de 
comunicação sujeito a monitoramento.



This message may include confidential information and only the intended 
addressee have the right to use it as is, or any part of it. A wrong 
transmission does not break its confidentiality. If you've received it 
because of a mistake or erroneous transmission, please notify the sender 
and delete it from your system immediately. This communication environment 
is controlled and monitored.



- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - - - - - - - - - - - - - - - - - -

**Comment by felipe-couto** [comment]
After configuring my /etc/php.ini 
date.timezone

It is OK, ACL and Service Groups works fine in Centreon Web 7.0 (RC2)
https://github.com/centreon/centreon/archive/2.7.x.zip
