### ISSUE TITLE
[beta-test] No release note 

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#3896]
Hi,

During an update from 2.6.6 to 2.7 there is no release note on the web interface update.
<img width="772" alt="cap 2015-11-27 a 21 15 41" src="https://cloud.githubusercontent.com/assets/10330979/11447842/99b34d0a-954d-11e5-97b6-3a0903674656.png">

Thanks

**Comment by querwin** [comment]
Release note will be OK for 2.7.0
