### ISSUE TITLE
[beta-test] Problem with the quotes in the Argument with migration

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3899]
after migration in 2.7, the service template SNMP-Linux-Swap does not work with quotes in disk number argument.
![install-centreon-nagvis2015-11-28_02-47-54_pm](https://cloud.githubusercontent.com/assets/12350746/11452238/4a024402-95e1-11e5-805c-ed0db316f5b8.png)
log broker
info:    SQL: processing service check event (host: 14, service: 29, command: /usr/lib/nagios/plugins/check_centreon_snmp_remote_storage -H 127.0.0.1 -n -d &quot -w  -c  -v 2c -C public, from instance: 1)
the problem disappears when saving new template SNMP-Linux-Swap

**Comment by julienmathis** [comment]
id de commit ? Y en a pas ?

**Comment by kermith72** [comment]
je vais refaire un test ce soir avec une nouvelle configuration basé sur un eemple de mon site avec authentification ldap et gestion acl. Je vous dirais si j'arrive à reproduire ou non ce problème ;-)

**Comment by kermith72** [comment]
Je confirme que le problème se produit après une migration d'une CES en respectant la procédure qui nous a été fournie. Il faut sauvegarder le template comportant l'argument avec double-quote et appliquer la configuration, le service fonctionne de nouveau.
![install-centreon-nagvis2015-12-04_11-14-06_am](https://cloud.githubusercontent.com/assets/12350746/11587240/56623946-9a78-11e5-9821-6f13a0a6b90b.png)
