### ISSUE TITLE
[beta-test] centreon-clapi not working with migration 2.6 -> 2.7rc1

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3900]
the following command does not work

> centreon-clapi -u admin -p password -a POLLERLIST

> PHP Warning:  require_once(/root): failed to open stream: No such file or directory in /usr/bin/centreon-clapi on line 41
PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/bin/centreon-clapi on line 41

**Comment by kermith72** [comment]
The symbolic link and executable are in the wrong place
there is :
> ls -l /usr/bin/centreon-clapi
-rwxr-xr-x 1 centreon centreon 6543 26 nov.  14:12 /usr/bin/centreon-clapi

and
>ls -l /usr/share/centreon/bin/centreon-clapi
lrwxrwxrwx 1 centreon centreon 23 27 nov.  20:50 /usr/share/centreon/bin/centreon-clapi -> /usr/bin/centreon-clapi

it should
>ls -l /usr/bin/centreon-clapi
lrwxrwxrwx 1 root root 38 28 nov.  00:08 /usr/bin/centreon-clapi -> /usr/share/centreon/bin/centreon-clapi

and
>ls -l /usr/share/centreon/bin/centreon-clapi
-rwxr-xr-x 1 centreon centreon 6543 28 nov.  00:09 /usr/share/centreon/bin/centreon-clapi

**Comment by querwin** [comment]
It will be OK in the RC2. I've fixed it in the spec
