### ISSUE TITLE
[beta-test] integration widgets

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3901]
Graph widget does not work
![install-centreon-nagvis2015-11-27_08-35-53_pm](https://cloud.githubusercontent.com/assets/12350746/11452352/00e07ace-95e5-11e5-92db-4322a5bfa0f7.png)

**Comment by querwin** [comment]
Hello,

The package centreon-widget-graph-monitoring-1.3.0-2.el6.noarch.rpm should fix this problem.

**Comment by kermith72** [comment]
cool :+1: after a
