### ISSUE TITLE
[beta-test] link does not work

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3902]
Monitoring  >  Status Details  >  Services
the link host does not work
![install-centreon-nagvis2015-11-28_03-46-56_pm](https://cloud.githubusercontent.com/assets/12350746/11452473/b2435c48-95e8-11e5-8c1c-4261aa419f00.png)

**Comment by matthieu-robin** [comment]
Hi Eric,

It works for me. Did you restart httpd? with the good php.ini?

**Comment by kermith72** [comment]
Hi Matthieu,

Exact, restarting httpd, the link works

Thanks
