### ISSUE TITLE
[beta-test] Fresh Install widgets does not work

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3907]
The properties of the widget does not work
![install-centreon-nagvis2015-11-29_10-24-07_pm](https://cloud.githubusercontent.com/assets/12350746/11460170/4f0144dc-96e8-11e5-9eec-23566764e585.png)
ditto for the service and host

**Comment by Dacchi** [comment]
Hello,

Did you use a specific widget?

**Comment by kermith72** [comment]
Hello,

No, These are the standard widget
![install-centreon-nagvis2015-12-02_03-03-07_pm](https://cloud.githubusercontent.com/assets/12350746/11532733/1e4de5a0-9906-11e5-8d19-b0d147a14aac.png)

**Comment by Shini31** [comment]
Hello,

I encountered the same problem as @kermith72 with a fresh install of Centreon 2.7 RC1.

Regards.

**Comment by mtoufik** [comment]
commit 8097066def7dce2178c570f078eb49c1b59916a6
