### ISSUE TITLE
Centreon 2.6.6 bug : Espace dans métrique

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#3914]
Si un espace existe dans une métrique alors lors de la création d'un méta-service associé à cette métrique le graphique de performances ne se génère pas.

**Comment by Sims24** [comment]
Hello, 

Pour enrichir les informations fournies par Loïc, il semblerait que cela soit également le cas pour un service simple. Constaté avec Temps de reponse=31ms par exemple

Selon les guidelines des plugins : 

label can contain any characters except the equals sign or single quote (')
the single quotes for the label are optional. **Required if spaces are in the label**

Une fois remplacé par rtt cela graph correctement. 

Maybe a "won't fix" ..

++

**Comment by julienmathis** [comment]
Ha mais vous ne mettez pas un simple quote autour de la métrique ?

Normal si c'est le cas...
