### ISSUE TITLE
Service template name with space converted to underscore

### ISSUE THREAD

**Issue by trunet** [centreon/centreon#3915]
Hello,

As per:
http://forum.centreon.com/forum/centreon-ui/centreon-web-interface/140023-service-template-name-with-space-converted-to-underscore

I have a service template that should have a space on the name so I can have the service on my hosts with a space as well.

However, on both "alias" and "Service Template Name" if I put a space on the name, it automatically converts to underscore _ . If I go on the service created after the template being applied, and edit it, than I can set the name with a space. However this is not doable on 1.6k hosts and 22k services.

I think this is a bug that needs to be fixed.

Best regards,
Wagner Sartori Junior

**Comment by rk4an** [comment]
Hi, the bug is still present on 2.7.5, any idea?

Thanks

**Comment by trunet** [comment]
This was fixed in 2.8. For 2.7, you'll need to do it yourself.

This is the commit that fixes on 2.8:
https://github.com/centreon/centreon/commit/d6fd21ba5c98580a6211812addd76d5925c40c12

**Comment by rk4an** [comment]
Thanks for the link! :)
