### ISSUE TITLE
[beta-test] ACL with filter categories does not work

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3917]
I use I used the following model http://sugarbug.web4me.fr/atelier/maquettes/maquette_duchmol/ 
After migration CES with centreon 2.7,  Monitoring Status details view no longer works with the user Alain Durand
before with centreon 2.6.6
![install-centreon-nagvis2015-12-03_07-11-45_am](https://cloud.githubusercontent.com/assets/12350746/11553249/277eb4c4-998d-11e5-8d25-e365e4853971.png)

after with centreon 2.7
![install-centreon-nagvis2015-12-03_07-06-26_am](https://cloud.githubusercontent.com/assets/12350746/11553222/d1eb332a-998c-11e5-8f45-ce3225ad00ad.png)

the view of ressouce acl
![install-centreon-nagvis2015-12-03_07-15-05_am](https://cloud.githubusercontent.com/assets/12350746/11553305/b6f17dc6-998d-11e5-9ec8-8edfa661842a.png)

the user has the rights on the objects
![install-centreon-nagvis2015-12-03_07-15-31_am](https://cloud.githubusercontent.com/assets/12350746/11553312/d5fa9d92-998d-11e5-8880-c2493027ba3d.png)

other views work
![install-centreon-nagvis2015-12-03_07-18-46_am](https://cloud.githubusercontent.com/assets/12350746/11553359/33c52bf4-998e-11e5-97a6-e50e8fa743ca.png)
![install-centreon-nagvis2015-12-03_07-19-04_am](https://cloud.githubusercontent.com/assets/12350746/11553386/8404415e-998e-11e5-8810-8044ade816c3.png)

**Comment by bsauveton** [comment]
I think this commit solve the issue.
https://github.com/centreon/centreon/commit/88366299159fce285319ff28cee4d1ba4fb3e92c

**Comment by bsauveton** [comment]
And the next one :
https://github.com/centreon/centreon/commit/0a023addf1c697f3b3099fb6fa20a91a29c11739
