### ISSUE TITLE
[2.7.0-rc1] Error with graph widgets

### ISSUE THREAD

**Issue by qdelance** [centreon/centreon#3918]
Image is not generated with graph widget (centreon-widget-graph-monitoring-1.3.0-1.el6.noarch), this error in logs : 

[Thu Dec 03 11:02:16 2015] [error] [client 192.168.56.1] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/class/centreonGMT.class.php on line 220, referer: http://192.168.56.252/centreon/widgets/graph-monitoring/index.php?widgetId=3

This seems to fix it (no time to diff against Git): 

    function getMyGTMFromUser($userId, $DB = null)
    {
        global $pearDB;

        if (!isset($pearDB) && isset($DB)) {
            $pearDB = $DB;
        }

        $DBRESULT = $pearDB->query("SELECT `contact_location` FROM `contact` " .
                "WHERE `contact`.`contact_id` = " . $userId .
                " LIMIT 1");
        if (PEAR::isError($DBRESULT)) {
            $this->myGMT = 0;
        } else {
        $info = $DBRESULT->fetchRow();
        $DBRESULT->free();
        $this->myGMT = $info["contact_location"];
}
    }

With this, graphs images are generated.

**Comment by julienmathis** [comment]
Hello, 

Did you use the last version of the widget graph ?

Thanks

**Comment by qdelance** [comment]
The name of the RPM with the version is provided in my ticket description.
I used all RPM published in YUM repo yesterday moring. I thought they were supposed to work toguether at one time.
Cannot say at this time if this is a bug in Centreon or a misuse of Centreon API by the widget. It seems the bug is in Centreon given my fix.

**Comment by julienmathis** [comment]
Thanks !

**Comment by querwin** [comment]
Hello,

The package centreon-widget-graph-monitoring-1.3.0-2.el6.noarch.rpm should fix this problem.
