### ISSUE TITLE
[2.7.0-RC1] Missing Default_Graph Template

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#3920]
Hello,

With a fresh install of Centreon 2.7.0-RC1, the Default_Graph Template is missing.

The consequence is that when you have a service with performance data with the warning or critical thresholds, the graph is not generated and has that kind of error in the PNG file : 
```ERROR: Legend set but no color: Critical \: 1.00```

Regards.

**Comment by julienmathis** [comment]
Should be fixed since @Dacchi fixed the DB init problem. Must be validated with a fresh install.

**Comment by querwin** [comment]
Not sure if it's the same problem but I built a new packet today and the graphs are still not good.

I've got this error in Apache logs : 
http://10.30.2.33/centreon/main.php?p=204&mode=0&svc_id=Centreon-Server-Central;proc-ntpd#

**Comment by Dacchi** [comment]
@querwin It's related but not exactly the same problem.
Some options have been removed on fresh install but they're still needed to geenrate the graph.
I restored those options.
