### ISSUE TITLE
issue with /etc/centreon/conf.pm on poller

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#3926]
On a poller the /etc/centreon/conf.pm file is rewritten by centreontrapd SQLite configuration

centreontrapd must have it configuration information into /etc/centreon/centreontrapd.pm
this file have to be created by the RPM
centreontrapd have to select info into this own configuration file

**Comment by garnier-quentin** [comment]
I think it's wrong idea. Because it will break some upgrade. 
We need to keep the same system. But if there is configuration on centreontrapd.pm, it overrides '/etc/centreon/conf.pm'.
