### ISSUE TITLE
[beta-test] Arguments description

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#3930]
- Step 1 : Create a command with arguments like $ARG1$...
- Step 2 : Describes your arguments and save
- Step 3 : Create a service template and use the command created previously
- Step 4 : Create a service that use the service template created previously

The service doesn't show any arguments in the "Args" field.

**Comment by Dacchi** [comment]
It works for me

**Comment by Dacchi** [comment]
I saw the issue, there's a regression (compare to 26.x), arguments is not dynamically updated
