### ISSUE TITLE
[2.7.0-RC1] All Timezone's fields are empty

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#3932]
Hello,

With a fresh install of Centreon 2.7.0-RC1, all Timezone's fileds are empty.
![timezone_empty1](https://cloud.githubusercontent.com/assets/333820/11628788/43b7c562-9cf4-11e5-9981-b3be03fe22a9.png)
![timezone_empty2](https://cloud.githubusercontent.com/assets/333820/11628787/43b1b654-9cf4-11e5-8487-63a102db3aa6.png)

Regards

**Comment by mtoufik** [comment]
commit 8097066def7dce2178c570f078eb49c1b59916a6
