### ISSUE TITLE
[2.7.0RC1] Missing command disco topology

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#3938]
I can create a command with type=4 (Discovery) but I can see it because commands menu doesn't allows to see it

INSERT INTO topology VALUES(NULL, 'Discovery', NULL, '608', '60804', '35', '1', './include/configuration/configObject/command/command.php', '&type=4', '0', '0', '1', NULL, NULL, NULL, '0');

**Comment by querwin** [comment]
it seems to be present only for migration since 2.6.x
