### ISSUE TITLE
[2.7.0RC1] Create a poller is incomplete

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#3939]
When I create a new poller using Centreon web interface, the process create a Centreon engine configuration assicoated to the new poller but the process forgot to create a broker module entry !

To complete the process the Centreon web interface could create a Centreon Broker entry associated to the poller.

Linked to #3910

**Comment by querwin** [comment]
In a ideal world, the broker configuration can be create too when create a new centreon engine entry.

Maybe in a future version
