### ISSUE TITLE
ServiveGroup Details (p=20212) page is empty if you have previously set a search on a service 

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#394]
---

Author Name: **Ira Maus** (Ira Maus)
Original Redmine Issue: 6436, https://forge.centreon.com/issues/6436
Original Date: 2015-06-17

---

If you search after a service at the all services page (p=20201) and then switch to page ServiceGroup Details (p=20212) you'll get an empty site (depends on your search before and your monitoring items).

Reason: at 20212 there's only a host search field, but the query get the search field as input which is for service search.

Solution: change one line
centreon/www/include/monitoring/status/ServicesServiceGroups/serviceSummaryBySGJS.php at Line 150

OLD:
proc.setXml(_addrXML+"?"+'sid='+_sid+'&search='+_search+'&num='+_num+'&limit='+_limit+'&sort_type='+_sort_type+'&order='+_order+'&date_time_format_status='+_date_time_format_status+'&o='+_o+'&p='+_p+'&time=<?php print time(); ?>');

NEW:
proc.setXml(_addrXML+"?"+'sid='+_sid+'&search='+_host_search+'&num='+_num+'&limit='+_limit+'&sort_type='+_sort_type+'&order='+_order+'&date_time_format_status='+_date_time_format_status+'&o='+_o+'&p='+_p+'&time=<?php print time(); ?>');

**Comment by julienmathis** [comment]
Thanks ! Already fixed
