### ISSUE TITLE
[2.6.6] Monitoring by service group very long

### ISSUE THREAD

**Issue by NicolasLarrouy** [centreon/centreon#3940]
Hi,
Centreon 2.6.6
1700 Hosts / 11200 Services.
On Monitoring > Services > (Details | Summary) >> By Service Group.
User with ACL ALL Ressources 
For users who have an ACL ressources (ALL), access to the service group page is very long. No problem with users who do not have ACL. No problem with users who have 40/50 servers on ACL ressources. No problem for against Host Group page.
On the SQL server, I actually found that a SQL query takes more than 1 minute:

SELECT SQL_CALC_FOUND_ROWS DISTINCT sg.servicegroup_id, h.host_id FROM servicegroups sg, services_servicegroups sgm, hosts h, services s WHERE sg.servicegroup_id = sgm.servicegroup_id AND sgm.host_id = h.host_id AND h.host_id = s.host_id AND s.service_id = sgm.service_id AND h.host_id IN ('383', '385', '386', '387', '388', '390', '391', '392', '393', '831', '832', '395', '396', '397', '1281', '42', '398', '399', '400', '401', '402', '403', '404', '405', '406', '407', '384', '408', '409', '410', '411', '412', '413', '414', '415', '416', '417', '418', '419', '420', '421', '1868', '422', '423', '424', '425', '426', '1869', '427', '428', '1870', '394', '436', '430', '431', '2087', '389', '432', '1753', '433', '1504', '828', '66', '43', '67', '68', '69', '70', '71', '1676', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '1505', '1482', '1265', '1299', '1218',
[...]
AND sg.name = 'APP-Surveillance-XXXXXXXXX' ORDER BY sg.name ASC LIMIT 0,30

Regards

**Comment by julienmathis** [comment]
@bsauveton : it's ok now ?
