### ISSUE TITLE
[2.7.0-RC2] Calendar isn't in flat design

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#3945]
The date is ok, but not the time :-)
![cap 2015-12-09 a 18 58 22](https://cloud.githubusercontent.com/assets/10330979/11693736/d80368e4-9ea6-11e5-8f51-06679e5aefeb.png)

**Comment by benoiteolas** [comment]
It would be great to have a different color for Minutes and Hour.
It difficult to read with all in green.
