### ISSUE TITLE
[2.7.0-RC2]Espaces inutiles dans le fichier /etc/sudoers.d/centreon

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon#3948]
![sans titre](https://cloud.githubusercontent.com/assets/10491809/11695083/55cf1344-9e7b-11e5-8fe8-c13903f54c53.jpg)
Comme vous pouvez le voir dans la capture d'écran ci-dessous, des espaces inutiles sont présents dans le fichier /etc/sudoers.d/centreon.
Est-ce possible de faire en sorte que ces espaces inutiles ne soient pas ajoutées ?

**Comment by querwin** [comment]
Fixed in RPM spec

**Comment by julienmathis** [comment]
Still not working.

**Comment by Tpo76** [comment]
Stay spaces on line 8 :
CENTREON   ALL = NOPASSWD: /etc/init.d/snmptrapd restart

**Comment by querwin** [comment]
Will be ok in the next release, it's a packaging problem
