### ISSUE TITLE
[2.7.0-RC2] not example configuration ?

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3951]
is it normal that there are no example configuration ?
![install-centreon-nagvis2015-12-09_09-43-23_pm](https://cloud.githubusercontent.com/assets/12350746/11698361/7d330a38-9ebe-11e5-9e54-f295ed6608d9.png)

**Comment by Dacchi** [comment]
Hello,

Is it a fresh install from the RC2 or RC1?

**Comment by kermith72** [comment]
Hello,
No, it is a fresh install with iso ces-standard-3.3-x86_64.iso (RC2)

**Comment by querwin** [comment]
I try this morning with a new installation

**Comment by querwin** [comment]
Same thing as #3955, I think
