### ISSUE TITLE
[2.7.0-RC2] the module centreon-nagvis does not work after migration

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3954]
After migration centreon 2.6.6 to 2.7.0 RC2, the module centreon-nagvis does not work.
![install-centreon-nagvis2015-12-10_07-13-12_am](https://cloud.githubusercontent.com/assets/12350746/11708256/846f751c-9f0d-11e5-8155-f6473ad0650a.png)
there is no menu for this module

**Comment by mathieuchateau** [comment]
Hello,

do you know if backend module still works ? could you test from nagvis
directly if still able to see resources?

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-12-10 7:15 GMT+01:00 kermith72 <notifications@github.com>:

**Comment by kermith72** [comment]
the centreon-backend works ;-)
![install-centreon-nagvis2015-12-10_07-27-38_am](https://cloud.githubusercontent.com/assets/12350746/11708456/b445bc40-9f0f-11e5-8af4-46c680f2ffdf.png)
![install-centreon-nagvis2015-12-10_07-31-04_am](https://cloud.githubusercontent.com/assets/12350746/11708489/0eea3022-9f10-11e5-9909-5ad45610ba45.png)
it's just the web interface is not working
regards

**Comment by mathieuchateau** [comment]
Thanks, I am feeling better :)

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-12-10 7:32 GMT+01:00 kermith72 <notifications@github.com>:

**Comment by qdelance** [comment]
This is likely due to a "topology" change in 2.7.
We no longer have a View menu item (graphs have moved in monitoring menu item).
So this is probably just a matter of changing the correct parent ID (Views => Monitoring) in DB

**Comment by jdufrene** [comment]
Hello!
Do someone know what I have to change in the DB to make nagvis works with the new UI?

**Comment by querwin** [comment]
Hello,

I close here. The problem is open in the nagvis project : https://github.com/centreon/centreon-nagvis/issues/7

**Comment by DaStivi** [comment]
i've tried to change the topology ...

INSERT INTO `topology` (`topology_id`, `topology_name`, `topology_icone`, `topology_parent`, `topology_page`, `topology_order`, `topology_group`, `topology_url`, `topology_url_opt`, `topology_popup`, `topology_modules`, `topology_show`) VALUES ('', 'Nagvis', NULL, 2, 243, 20, 1, './modules/centreon-nagvis/index.php', NULL, '0', '1', '1');

i see the nagvis link in the monitoring tab... but the page does not load anymore... same for my centreon-nagmap plugin.... the link is in the monitoring tab but the pages does not load anymore...

**Comment by DaStivi** [comment]
i "found" the cause why the iframe is not displaying correctly.... there is some issue in the resize function... i can't track it down as i'm not aware of the jquery commands... butmay this information help someone to fix it :)
