### ISSUE TITLE
[2.7.0-RC2] problem centreon-clapi with CES 3.3

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#3955]
after migration 2.6.6 to 2.7 rc2 on CES 3.2, centreon-clapi works with command centreon :
>[root@ces media]# type centreon
centreon est haché (/usr/bin/centreon)
[root@ces media]# ls -l /usr/bin/centreon
lrwxrwxrwx 1 centreon centreon 32  9 déc.  21:11 /usr/bin/centreon -> /usr/share/centreon/bin/centreon
[root@ces media]# centreon -u admin -p password -a pollerlist
1	Central
Return code end : 0
[root@ces media]# centreon
Centreon version 2.7.0-RC2 - Copyright Merethis - www.centreon.com
This software comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to modify and redistribute it under the GPL license

after fresh install CES 3.3, centreon-clapi does not work with command centreon-clapi :
>centreon-clapi
PHP Warning:  require_once(/root): failed to open stream: No such file or directory in /usr/bin/centreon-clapi on line 41
PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/bin/centreon-clapi on line 41
[root@ces33 ~]# centreon
-bash: centreon : commande introuvable
[root@ces33 ~]# type centreon-clapi
centreon-clapi est haché (/usr/bin/centreon-clapi)
[root@ces33 ~]# ls -l /usr/bin/centreon-clapi
-rwxr-xr-x. 1 centreon centreon 6543 26 nov.  14:12 /usr/bin/centreon-clapi

**Comment by querwin** [comment]
Eric,

With a fresh install of CES 3.3 the command is still centreon.

It works for me

[root@CES33 ~]# centreon
Centreon version 2.7.0-RC2 - Copyright Merethis - www.centreon.com
This software comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to modify and redistribute it under the GPL license

....

By the way, it lets me see that we have to change the copyright :)

**Comment by kermith72** [comment]
Remi,
I just downloaded the iso again and I confirm that I still have the problem
![install-centreon-nagvis2015-12-10_05-28-40_pm](https://cloud.githubusercontent.com/assets/12350746/11724143/967db236-9f72-11e5-927f-820867c201e7.png)

>[root@ces33 ~]# centreon
-bash: centreon : commande introuvable
[root@ces33 ~]# centreon-clapi
PHP Warning:  require_once(/root): failed to open stream: No such file or directory in /usr/bin/centreon-clapi on line 41
PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/bin/centreon-clapi on line 41

**Comment by querwin** [comment]
OK

I try this morning a new installation

**Comment by querwin** [comment]
Eric,

The ISO we upload is not the good one :(. If you try to add testing repo and update after the installation it will be OK

I can give you alink to the good one by mail if you want

**Comment by kermith72** [comment]
yes I want :-)
eric.coquard@gmail.com

**Comment by kermith72** [comment]
It's OK :+1: 
>[root@ces33 ~]# centreon
Centreon version 2.7.0-RC2 - Copyright Merethis - www.centreon.com
This software comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to modify and redistribute it under the GPL license
