### ISSUE TITLE
problem with timezone

### ISSUE THREAD

**Issue by felipe-couto** [centreon/centreon#3956]
I just updated from 2.6.6 to 2.70 (RC2) https://github.com/centreon/centreon/tree/2.7.x
I get a problem with timezone:
Error while processing a config file: Parsing of object definition failed in file '/usr/share/centreon//filesGeneration/nagiosCFG/1/hosts.cfg' on line 23: Invalid line 'timezone :America/Sao_Paulo'
One or more problems occurred while processing the config files.

Even creating the /etc/php.d/php-timezone.ini file did not help, and restarting apache, and all centreon services, nothing...

Anyone knows how to fix this?

**Comment by Dacchi** [comment]
Hello,

Centreon 2.7 requires Centreon Engine (1.5.0).

If you're using Red Hat like OS, you can use this procedure to get the last unstable version
    # cd /etc/yum.repos.d
    # wget http://yum.centreon.com/standard/3.0/testing/ces-standard-testing.repo -O /etc/yum.repos.d/ces-standard-testing.repo
    # /etc/init.d/centengine stop
    # /etc/init.d/cbd stop
    # yum update centreon

**Comment by Dacchi** [comment]
Here the link to Centreon documentation => https://documentation.centreon.com/docs/centreon/en/2.7.x/installation/betaTest2.7.0.html#betatest2-7-0
