### ISSUE TITLE
Views - Graphs - not using custom icon

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#3965]
We can define custom icon on Host, service, host group & co.

Once defined, they do appear in Monitoring views.
But they are not used in Views\graphs menu, where default standard icon appears.

Any way to get custom icons displayed there too ?

Thanks

**Comment by querwin** [comment]
No more icons on this page since Centreon Web 2.7.0.

Maybe possible to add it ?

**Comment by julienmathis** [comment]
Hello Mathieu, 

I'm sorry because we have remove the treeview in Centreon Web 2.7. So I think we will never implement that point.

Regards
