### ISSUE TITLE
centreon web - non admin cannot change their own password

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#3966]
Hello,

When a user have access to Centreon frontend, but is not Centreon admin (Admin set to yes), preference menu is not accessible (no hyperlink) and so user can't change passsword.

If user try direct access to page, error message is displayed:
'''''
You are not allowed to reach this page
'''

User should also be able to change other preferences, like language and UI notifications.

Regards,
Mathieu

**Comment by lpinsivy** [comment]
Hi

To change your passowrd if you are a non admin user you have to click on your login on the header of Centreon: "Welcome <my login> | Logout".

Regards,
