### ISSUE TITLE
Dashboard - Hostgroup non visible depuis centreon 2.6.4

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#3968]
Bonjour,
la visualisation du dashboard sur les groupes d'hôtes est vide depuis la version 2.6.4 (plateforme actuellement en version 2.6.6) => cf PJ
J'ai pu vérifier sur les versions précédentes à partir de la 2.6.1 sur une plateforme de recette en passant chaque version à la main. Les groupes d'hôtes sont bien visibles jusqu'à la version 2.6.3 inclue.
centreon 2.6.3
![centreon-2 6 3](https://cloud.githubusercontent.com/assets/8720203/11779670/0b13e074-a25d-11e5-96b2-475c55922e56.png)
centreon 2.6.4
![centreon-2 6 4](https://cloud.githubusercontent.com/assets/8720203/11779679/16df4d44-a25d-11e5-81bb-1fd06a78a0fb.png)

cordialement,

**Comment by julienmathis** [comment]
fixed #4129
