### ISSUE TITLE
[2.7.0-RC2] php fatal error in curves view

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3972]
Hi,
after a fresh install from 3.3 iso, when going to "Monitoring->Performances->Curves", click on one curve (CPU for exemple) and there is a fatal error in httpd logs:
PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/class/centreonService.class.php on line 1076, referer: http://192.168.122.121/centreon/main.php?p=20405&o=c&compo_id=3

thanks
David

**Comment by Dacchi** [comment]
commit 9860a96376d1d65bba93f4beb60493cab413a9c8
