### ISSUE TITLE
[2.7.0-RC2] use system timezone into php.ini

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3973]
Hi,
has timezone definition is now mandatory in php.ini. Why not getting it during installation and write it into php.ini (form a post install script into an RPM for exemple).

thanks
David

**Comment by julienmathis** [comment]
@mtoufik : that is ok now ? doesn't it ?

**Comment by querwin** [comment]
Don't think so

**Comment by leoncx** [comment]
The RPM policies does not authorize to modify a file from another RPM.
