### ISSUE TITLE
[2.7.0-RC2] first level menu not colored

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#3977]
Hi,
after an update from a working 2.6.6, the first level menu background is not coloring when clicking. It's ok when a level 2 menu entry is selected:
![menu-color](https://cloud.githubusercontent.com/assets/5741421/11785574/bb81f0ca-a282-11e5-84fb-e680ebf91d0e.png)
 
thanks
David

**Comment by julienmathis** [comment]
It is persistent ?

**Comment by golgoth31** [comment]
yes, it's still there today

**Comment by julienmathis** [comment]
Can you send me the ip address ? Thanks :)

**Comment by julienmathis** [comment]
Can you send me in mail all informations ?

Thanks
