### ISSUE TITLE
[2.7.0-RC2]Bug dans la définition des commandes

### ISSUE THREAD

**Issue by nutzmdm** [centreon/centreon#3980]
Version 2.7 RC2

En modifiant la définition d'une commande j'ai supprimé les $ARG1$ $ARG2$ et $ARG3$, tout en laissant les 4, 5 et 6.
Lorsque j'ai voulu créer un service utilisant cette commande, les valeurs d'arguments semblent ne pas être prises en compte à l'enregistrement (si on retourne dans le service, les champs sont vides). En fait, elles le sont puisque si je modifie à nouveau la définition de commande pour remplacer les arg 4, 5 et 6 par 1, 2, 3, les valeurs que j'avais mises apparaissent dans je vais dans la page de modification du service.

**Comment by julienmathis** [comment]
Mais si tu supprime  $ARG1$ $ARG2$ et $ARG3$ alors  $ARG4$ $ARG5$ et $ARG6$ deviennent  $ARG1$ $ARG2$ et $ARG3$.

Ce n'est donc pas un bug a mon avis... Non ?

**Comment by nutzmdm** [comment]
En fait, si je fais ça:
$USER2$/check_snmp -H $HOSTADDRESS$ -C $_HOSTSNMPCOMMUNITY$ -P $_HOSTSNMPVERSION$ -o $ARG4$ -w $ARG5$ -c $ARG6$ 

et que je créé un service associé:
![image](https://cloud.githubusercontent.com/assets/6714873/11875311/5f4a88bc-a4e4-11e5-98db-056cec4307fa.png)

je peux sauvegarder sans erreur et si je reviens dessus les valeurs des arguments sont vides: 
![image](https://cloud.githubusercontent.com/assets/6714873/11875379/9c06f204-a4e4-11e5-8920-df4560469110.png)

Et si après ça, je modifie ma commande en remplaçant ARG4, 5, 6 en 1, 2, 3
et que j'affiche le service sans le modifier j'ai bien 
![image](https://cloud.githubusercontent.com/assets/6714873/11875480/1871f474-a4e5-11e5-9e59-9c892e60ee6a.png)

Bon, par contre, on est bien d'accord, ça ne doit pas arriver quand on définit ses commandes correctement.

**Comment by julienmathis** [comment]
Oui donc je pense que le premier problème ne vient pas de l'interface mais de la façon dont on définit les commandes. Non ?
