### ISSUE TITLE
[2.7.0-RC2]  Incomplete redirection in error_log

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#3983]
Hello,

Every 5 minutes, this error message appears in error log : 
```
[Tue Dec 15 09:01:01 2015] [warn] [client X.X.X.X] incomplete redirection target of '/centreon/index.php' for URI '/' modified to 'http://Y.Y.Y.Y/centreon/index.php'
[Tue Dec 15 09:05:58 2015] [warn] [client X.X.X.X] incomplete redirection target of '/centreon/index.php' for URI '/' modified to 'http://Y.Y.Y.Y/centreon/index.php'
[Tue Dec 15 09:10:56 2015] [warn] [client X.X.X.X] incomplete redirection target of '/centreon/index.php' for URI '/' modified to 'http://Y.Y.Y.Y/centreon/index.php'
```

I think it's linked to downtimeManager's cron.

Regards.

**Comment by querwin** [comment]
Seems to be linked to the apache configuration

**Comment by julienmathis** [comment]
Hello, 

I'm sorry, I can't reproduce this behavior... Can you communicate by email the machine ip that produce this problem ?

Thanks

**Comment by Shini31** [comment]
Hello,

Sorry but it was a machine specifically created to test the 2.7.0 version and it was deleted.

Regards.

**Comment by edshot45** [comment]
Hello,

I have the same problem since my update with centreon 3.3 and Centreon Web 2.7.1. 

Regards

**Comment by julienmathis** [comment]
I think it's a apache bug.... 

http://stackoverflow.com/questions/15928398/apache-mod-rewrite-error-incomplete-redirection-target-of-for-uri-m

We haven't changed anythings since Centreon 2.6. May be an apache update.
