### ISSUE TITLE
The centreon 2.7.0 using plugin pack does not work with perl connector

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#3998]
I upgraded to version Centreon 2.7.0 this morning and I get lot of errors like that:
[1450354985] [12580] Error: Service check command execution failed: Connector 'Perl Connector' failed to restart
On command line plugin package commands are working but in the frontend I see only: (Execute command failed).
If I remove perl_connector from the command. it starts to work in Frontend also.

**Comment by querwin** [comment]
Is the box "Enable shell" check for the commands ?
It could be part of the problem.

@ganoze : what do you think about it ?

**Comment by kadrika** [comment]
No, it is not checked. It is empty.

**Comment by ganoze** [comment]
What are the command names (and associated command lines) which do not work ? 5 non-working commands will be enough.

**Comment by ganoze** [comment]
After testing, it might come from Centreon Connector Perl configuration. You should have something like that in the Connector command line 

```shell
centreon_connector_perl --code "use '/usr/lib/nagios/plugins/'\;"
```

Try to replace it with (add lib keyword).

```perl
centreon_connector_perl --code "use lib '/usr/lib/nagios/plugins/'\;"
```

This should fix the plugin execution error.

**Comment by maksimatveev** [comment]
@ganoze: With both options proposed - (Execute command failed)

**Comment by ganoze** [comment]
@maksimatveev : which command (command name, command line, macros) are you using ?

**Comment by maksimatveev** [comment]
@ganoze: $USER1$/centreon-plugins/centreon_plugins.pl --hostname=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --plugin=$_SERVICEPLUGIN$ --mode=$_SERVICEMODE$ --warning=$_SERVICEWARNING$ --critical=$_SERVICECRITICAL$ $_SERVICEOPTIONS$

**Comment by ganoze** [comment]
It seems that your Centreon Plugins are installed under /usr/lib/nagios/plugins/centreon-plugins. Can you confirm ?

In such case the Centreon Connector Perl command line should look like the following.

```shell
centreon_connector_perl --code "use lib '/usr/lib/nagios/plugins/centreon-plugins/'\;"
```

**Comment by maksimatveev** [comment]
Excellent! Everything is working! =)
I think it is necessary to specify the documentation.

**Comment by kadrika** [comment]
I can test it also, but after Christmas holiday.

**Comment by Hellnino18** [comment]
Hi @ganoze, I'm trying to test centreon connector, and I have the same problem with Centreon broker 2.10.3, Centreon Engine 1.4.15, Centreon Connector 1.1.2 and Centreon 2.6.6.

I tried in the command line : 
$USER3$/centreon_connector_perl --code "use lib '/usr/lib/nagios/plugins/'\;"

but I always have the same behavior in the centengine.log : 

[1453909238] [35594] Error: Service check command execution failed: Connector 'Perl Connector' failed to restart
[1453909238] [35594] Error: Service check command execution failed: Connector 'Perl Connector' failed to restart
[1453909238] [35594] Error: Service check command execution failed: Connector 'Perl Connector' failed to restart
[1453909238] [35594] Error: Service check command execution failed: Connector 'Perl Connector' failed to restart
[1453909238] [35594] Error: Service check command execution failed: Connector 'Perl Connector' failed to restart
[1453909238] [35594] Error: Service check command execution failed: Connector 'Perl Connector' failed to restart

Execute command failed

Do you have an explanation plz ?

Thanks in advance!
