### ISSUE TITLE
Timezone Error with :

### ISSUE THREAD

**Issue by dennis0212** [centreon/centreon#3999]
Centreon 2.7.0

When I generate FIles I have this error!

Reading configuration data...
Read main config file okay...
Error Invalid host object directive 'timezone'.
Error Could not add object property in file '/usr/share/centreon//filesGeneration/nagiosCFG/1/hosts.cfg' on line 26.
Error processing object config files!

In the FIle is

timezone                       :Europe/Paris
    use                            generic-host
    _HOST_ID                       14

The Error is the (:)  

what I can do here to fix it

**Comment by Dacchi** [comment]
Starting with Centreon 2.7, Centreon Engine 1.5.0 is mandatory

**Comment by dennis0212** [comment]
I have Centreon 2.7.0
