### ISSUE TITLE
Displaying Graphs and some other enhancement interface

### ISSUE THREAD

**Issue by dgarandel** [centreon/centreon#4005]
1° The "Split" select function not appear correctly on page (Showing on right page)
And an unhancement to select graph needed. And if possible show this split selet field like version < 2.6.4. Split function in first page and not after clic and browse Weekly/Monthly/Yearly

2° Now in 2.7 we needed for services, select services by host. Is ti possible to display only service name and not Host+Service ?

3° I understand that color configuration menu disappear but the monitoring view for Critical is really unreadable with a back text on red background (This is the color I had changed). and with this red background some icons like Note, Url,Actions are not easyly visable. And why background color only for Critical?

4° Module page id can be wrong. I understand thaht personal modules need to be rewrutten but at the first time Centreon-Syslog has same topology-page ID than "Performance" page.

5° Is it possible to improve test on SQL updating where upgrade Centreon. IE. I upgrae Centreon from 2.6. to 2.7 with empty DB and all work well. I restor my production DB to this server, So i must to upgrade DB restor to 2.7 format. Th emore easy I find is to send an "yum reinstall" but uograde failed because new tables already exist or with contraints violation because records already exist.
It's just a test if table exist and records or contraints already exist. This to do not edit the .sql file and comment some records.

This for the last 2.7.0 stable version. Some othe bug corrected from RC2.

But nice interface and great job ;-) Thanks for your work

**Comment by dgarandel** [comment]
Sorry is for tag : Beta-Test and Enhancement. I don't understand your GitHub

**Comment by julienmathis** [comment]
Hello, 

We will not be able to fix all items of this big ticket. 

For syslog, a version is now compatible with Centreon 2.7.

The split will be fixed.

Can you give more information regarding the last point ?

Thanks

**Comment by dgarandel** [comment]
Hello Mr Mathis.

For the last point it's not a bug but a enhancement. 
We cannot send and sometimes need it an "yum reinstall centreon". Just because some ../install/sql/centstorage/Update-CSTG*.sql files stop with error if action canniot be made. Ie: stop on "create tables", "insert record", ... It's logical because thes was previously created by the "yum install/update centreon". Can you test the function before executing on these files like "do not create table if the tables already exist"

Great job on the new interface. But for me the <Monitoring> <Performance> page is very strange. "Split" button not correctly positioned and not functional, Cannot display correct services selected for a host or somes hosts, ....

Other problem comes from not v2.7 but v2.6;X with last securityTokenCheck function (CSRF patch return false for some extension on token validated) on QuickForm.php and positional menu from 2.7

Thanks.

**Comment by lpinsivy** [comment]
Hi,

split was fixed on Centreon 2.7.3.

They are other point still open in this ticket ?

Regards,

**Comment by dgarandel** [comment]
Bonjour,

J'ai vu ceci et testé ce matin après l'update (en DEV) en 2.7.3
La vue graphes est maintenant tout à fait opérationnelle. Ceci bloquait la mise à jour en prod.

Je trouve juste dommage qu'il n'y ai pas/plus de sélection multiple sur les services. Pour afficher 300 graphes de ping par exemple ce n'est plus trop facile et leger.

Je cloture ce dossier.
Merci encore.

**Comment by lpinsivy** [comment]
Tu peux depuis Centreon 2.7.3 chercher PING et faire "select all"

**Comment by dgarandel** [comment]
Ah effectivement j'avais pas vu ce nouveau bouton. Sympa. Merci encore
