### ISSUE TITLE
Events log page is slow for user with ACL

### ISSUE THREAD

**Issue by bsauveton** [centreon/centreon#4006]
Especialy for the first request when there is no filters.

**Comment by bmareau** [comment]
Hi,
After application of the patch at a client, logs are displayed six times in the interface.

**Comment by bsauveton** [comment]
This commit solve the issue.
https://github.com/centreon/centreon/commit/8050a0e6cf448a265d837e6598a6a44c2e8f8968#diff-cb05267027d3cb4e7052ba9ae1fb047c

**Comment by bmareau** [comment]
Hi,
It's okay now =)
