### ISSUE TITLE
meta-service: Could not find broker connection info!

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#4008]
After upgrading from Cenreon 2.6.6 to 2.7.0 the meta-service are not working.

* Status: unknow
* Status information: Could not find broker connection info!
* Calculation Type: Sum
* Selection Mode: Service List
![2015-12-17 13_41_29-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/6400595/11875301/562c7240-a4e4-11e5-8980-8ea7976144cf.png)

**Comment by julienmathis** [comment]
Hello, 

in your centreon database, is cfg_ndo2d still present ?

Thanks

**Comment by joschi99** [comment]
Hello,

I confirm that the table cfg_ndo2db is present, but is empty.

merry christmas

**Comment by julienmathis** [comment]
I have fixed you problem.

https://github.com/centreon/centreon-plugins/commit/d0142cdfc7939306f7e4a6086713ce481ab1a87b

Can you check that it works ?

You should get the raw file et after that replace @CENTREON_ETC@ by /etc/centreon.

**Comment by joschi99** [comment]
I tried with the new file check_meta_service replacing the line @CENTREON_ETC@ with
``` php
require "/etc/centreon/conf.pm";
```

Executing the plugin I got the error:
```ssh
./check_meta_service
"use" not allowed in expression at ./check_meta_service line 392, at end of line
syntax error at ./check_meta_service line 392, near "use strict"
BEGIN not safe after errors--compilation aborted at ./check_meta_service line 393.
```

**Comment by joschi99** [comment]
Hi Julien,

it works correctly now.

Thanks
