### ISSUE TITLE
[Centreon 2.7.0] Centreon Web - You are not allowed to reach this page

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon#4009]
Centreon 2.7
After upgrading to 2.6.6 to 2.7 I try to open any host on the page "Monitoring - Status etails - By Status - Services" leads to the result:
You are not allowed to reach this page

This page "Monitoring - Status etails - By Status - Hosts" is host to the page opens.

I apologize if such a problem already mentioned here.

**Comment by querwin** [comment]
It seems to work for me.

You test with an admin user ?

**Comment by maksimatveev** [comment]
Yes

**Comment by maksimatveev** [comment]
Perhaps this is due to different addresses into links:
"Monitoring - Status etails - By Status - Services"
../centreon/main.php?p=201&o=hd&host_name=host-test1

"Monitoring - Status etails - By Status - Hosts"
../centreon/main.php?p=20202&o=hd&host_name=host-test1

**Comment by maksimatveev** [comment]
Do you need any further information or?

**Comment by maksimatveev** [comment]
The same result can be achieved by trying to open the schedule of service at the host from the same page "Monitoring - Status details - By Status - Services"
../centreon/main.php?p=4&mode=0&svc_id=host-test1;test-status-service

**Comment by maksimatveev** [comment]
Updates:
I decided to check another browser in Mozilla there Host page opens normally. Same in Google. In Opera not, links turn out different.

**Comment by maksimatveev** [comment]
Adguard Antibanner - that's the problem =)

**Comment by dmagniez** [comment]
same problem here with chrome = HS | firefox = OK

the difference is the URL :

chrome : http://supervision.int.solidd.fr/main.php?p=4&mode=0&svc_id=MAX-VCENTER;VM-snapshot
firefox : http://supervision.int.solidd.fr/main.php?p=204&mode=0&svc_id=MAX-VCENTER;VM-snapshot

**Comment by dmagniez** [comment]
same problem here : 
chrome : HS : http://supervision.int.xxxx.fr/main.php?p=4&mode=0&svc_id=MAX-VCENTER;VM-snapshot
firefox : OK  : http://supervision.int.xxxx.fr/main.php?p=204&mode=0&svc_id=MAX-VCENTER;VM-snapshot

**Comment by maksimatveev** [comment]
dmagniez, In Chrome not working yet "+ Add a new entry" on Configuration  >  Services  >  Services by host > Custom macros. In Mozilla everything works as it should!

**Comment by julienmathis** [comment]
@dmagniez do you clean the browser cache ?

**Comment by gslongo** [comment]
I confirm this issue on 2.7.1 when trying to open host status page (eg: http://XXXX/centreon/main.php?p=20102&o=hd&host_name=YYYY)
Even on Chrome or Firefox (last ESR). Cleaning cache do not help

Regards,

![capture-centreon - it network monitoring - google chrome](https://cloud.githubusercontent.com/assets/5636906/12288317/6cb515c2-b9d3-11e5-870c-f04a4e74c677.png)

**Comment by maksimatveev** [comment]
@gslongo This occurs even when you open the host of a widget "Service Monitoring", you also?

**Comment by gslongo** [comment]
@maksimatveev This do not seems to happen on service status host page

Thanks

**Comment by ccharnay** [comment]
Hi all, I solved a same issue on my centreon website, After update 2.7.0 CentreonEngine and Nagvis 1.8.5 . 
I had this following sentence : You're not allowed ... into nagvis URL p?p=20102&o=hd&ho ... 
But new page on Centreon are p=20201 for services and p=2202 for host's page. 

If you want solves this problem go into your nagvis  ini.php ( for me /usr/local/nagvis/etc/nagvis.ini.php
 and modify value URL template for host object link to

hosturl="[htmlcgi]/main.php?p=20202 .... and restart httpd

Running for me, 
Enjoy your Centreon

**Comment by maksimatveev** [comment]
@ccharnay problem mentioned at the beginning, does not refer to nagvis, and generally to the links in centreon. but I think your decision is also true.

**Comment by eglis** [comment]
I did a quick and dirty fix on one of my installations just to get it working it seams ok but i'm far from a programmer!

I have rpm based centreon installed on a centos/redhat 6.7 and php 5.3

cd /usr/share/centreon/www
diff -uN widgets/service-monitoring/src/table.ihtml.orig widgets/service-monitoring/src/table.ihtml
--- widgets/service-monitoring/src/table.ihtml.orig     2016-02-04 15:35:39.495464918 -0500
+++ widgets/service-monitoring/src/table.ihtml  2016-02-04 15:35:46.834132417 -0500
@@ -40,7 +40,7 @@
                             <img src ='{$centreon_web_path}img/media/{$elem.icon_image}' width='16' height='16' style ='padding-right:5px;' />
                         {/if}
                         <span class="state_badge" style='background-color: {$elem.hcolor};'></span>
-                        <a href='{$centreon_web_path}main.php?p=20102&o=hd&host_name={$elem.encoded_hostname}' target=_blank>{$elem.hostname}</a>
+                        <a href='{$centreon_web_path}main.php?p=20202&o=hd&host_name={$elem.encoded_hostname}' target=_blank>{$elem.hostname}</a>
                     </td>
                     <td class='ListColRight'>
                         <div style='float: right;'>

**Comment by mtoufik** [comment]
https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/issues/31

**Comment by amtz83** [comment]
@ccharnay Thanks !! That's work for me.
