### ISSUE TITLE
[2.7.0] Design is not perfect

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4010]
Hi,
there is some space above the page header. Please see attachment.
![design](https://cloud.githubusercontent.com/assets/2785700/11896545/b00c89dc-a587-11e5-8e6c-4a22b6762eb4.PNG)

**Comment by julienmathis** [comment]
Hello, 

The space is present only when the page is a form without tabs. We will fix it :) thanks.

**Comment by julienmathis** [comment]
This is the only one page who don't have tabs. The design is the good one.
