### ISSUE TITLE
[2.7.0] Configuration  >  Hosts  >  Templates - small bug

### ISSUE THREAD

**Issue by vurmil** [centreon/centreon#4012]
![1](https://cloud.githubusercontent.com/assets/15263415/11914161/78784c9e-a678-11e5-8942-a1250feb44d2.jpg)

**Comment by julienmathis** [comment]
Hello 

Does you host template description very long ?

Thanks

**Comment by vurmil** [comment]
Im sorry. Im rollback centreon to old version.
In template i have 90 templates.
Witch longest tempplate name - 20 chars and description - 27 chars

**Comment by Tpo76** [comment]
fonctionne sur la description mais pas sur le host template name

**Comment by querwin** [comment]
Thanks Fabien
