### ISSUE TITLE
[2.7.0] Services assigned via Host Groups are not correctly exported if Host has more than one Host Group

### ISSUE THREAD

**Issue by CsMAr51** [centreon/centreon#4013]
Centreon 2.7.0 on a fresh CES 3.3 install.

If a host has more than one host group and has services assigned through them, configuration for these services is not properly generated. Only services from the first host group (as returned from database) get exported in the configuration file.

I have tracked the issue as coming from method *getServicesByHg* in class *Host* (https://github.com/centreon/centreon/blob/edcf4f9d3dcd7e0e276bb0c4d98641017cf15b82/www/class/config-generate/host.class.php#L119) where a PDO prepared statement is used to bind a value to an "IN" clause in the SQL query.

This in not supported in PHP with PDO as numerous tickets in their bug tracker can attest. The value gets surrounded by quotes when the query is executed, so instead of getting what we might have expected:
```SQL
SELECT service_service_id
FROM host_service_relation
WHERE hostgroup_hg_id IN (62,113,112,135,86)
```
We get:
```SQL
SELECT service_service_id
FROM host_service_relation
WHERE hostgroup_hg_id IN ('62,113,112,135,86')
```
In this example, the database still manages to retrieve services linked to host group id 62, but not the others.

I have temporarily fixed the issue with the [following patch](https://github.com/centreon/centreon/files/67957/hg_svc_cfggen_temp_fix.txt), but this might not be how you want to address this.

**Comment by garnier-quentin** [comment]
The patch is good!

**Comment by kduret** [comment]
Thanks for patch @CsMAr51 ;)
It has been applied
