### ISSUE TITLE
Linked Service Templates in Host template aren't easy to read

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4014]
![cap 2015-12-21 a 08 09 25](https://cloud.githubusercontent.com/assets/10330979/11925282/475046ec-a7ba-11e5-8884-8ec408a302f7.png)

**Comment by julienmathis** [comment]
Rabaa, 

Can you improve the size of select2 elements ?

Thanks

**Comment by garnier-quentin** [comment]
Adding something like that: https://jqueryui.com/resizable/

**Comment by bsauveton** [comment]
same as https://github.com/centreon/centreon/issues/4026

**Comment by querwin** [comment]
I mark as Validated, it's the same issue as 4026
