### ISSUE TITLE
Hostgroup selected disappear after service modification

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4015]
Hello,

When we select a hostgroup in the menu "Service by host", we modify a service, click Save, and them we go back to the list of Service by host without the hostgroup selected before. All services by host appear :-(

Thanks

**Comment by bsauveton** [comment]
Does this bug appears when you make a fresh install or a migration to centreon web 2.7 ?

**Comment by matthieu-robin** [comment]
it's a migration from CES 3.2 updated until 2.6.6.

Thanks

**Comment by bsauveton** [comment]
Thanks for the info.
