### ISSUE TITLE
Cannot select by hostgroup in Monitoring view

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4017]
![cap 2015-12-21 a 09 06 28](https://cloud.githubusercontent.com/assets/10330979/11926132/93d80c18-a7c2-11e5-88f1-44369f80c4a1.png)
![cap 2015-12-21 a 09 06 06](https://cloud.githubusercontent.com/assets/10330979/11926136/95fe98e0-a7c2-11e5-9a02-0aa6769fd03e.png)

And I have hostgroups, it works in other menu.

Thanks

**Comment by bsauveton** [comment]
This issue appear when you migrate to centreon 2.7 and you don't regenerate the configuration of your pollers before restarting engine/broker. 
To solve this issues, regenerate your conf with a "restart" instead of a "reload" of engine.
Regards.
