### ISSUE TITLE
[2.7.0] Widget graph no auto refresh

### ISSUE THREAD

**Issue by nicomin73** [centreon/centreon#4018]
Hi,

Since my centreon upgrade 2.6.6 to 2.7.0, my widget graph monitoring doesn't auto refresh anymore.
I am using the last version version 1.3.0-3, the data are correct, but into my widget no auto refesh of the view after x sec.

Did you have the same issue ?

Thank for your feedback.

**Comment by nicomin73** [comment]
Do you know if I need to modify some code into this widget or I need to wait the next release of this widget (1.3.0.4 ?).
Thanks for the update ;-)

**Comment by nicomin73** [comment]
Hi,
Only me have this error or not ? 
I only proceed to a standard upgrade and upgrade the widget too .. so I don't understand exactly where the problem is.
Thank you for your feedback and a big thank you for this very good tool !!!!

**Comment by nicomin73** [comment]
Also I am using php 5.3.3-46 on my centreon VM, is it a problem about centreon widget requierements ?

**Comment by julienmathis** [comment]
If you still have this problem, please open a ticket in the widget github repo
