### ISSUE TITLE
[2.7.0] Immediate check (Forced) - External command doesn't work

### ISSUE THREAD

**Issue by vurmil** [centreon/centreon#4019]
Immediate check (Forced) - External command doesn't work

**Comment by vurmil** [comment]
System commands - working
My command - doesn't working

**Comment by julienmathis** [comment]
Hello, 

Do you have error in apache log file ?

Thanks

**Comment by vurmil** [comment]
Sorry. I'm rolback to old version.
Because It was very important for me

**Comment by julienmathis** [comment]
It works for me...

**Comment by romnvll** [comment]
Bonjour,
je me permet de relancer le sujet, car depuis ma migration de la version 2.4 à la 2.7, j'observe le même phénomène, impossible de faire un force check, il ne se passe rien.

les logs que j'ai sur apache :
[Mon Jan 11 08:46:25 2016] [error] [client 192.168.15.24] PHP Warning:  strlen() expects parameter 1 to be string, array given in /usr/share/centreon/www/lib/HTML/QuickForm/checkbox.php on line 126, referer: http://192.168.14.149/centreon/

je ne sais pas si ça a un rapport avec mon erreur ...
