### ISSUE TITLE
Password in macro

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4020]
Hello, Is it not any more possible to set a macro as a password?

![cap 2015-12-21 a 13 07 36](https://cloud.githubusercontent.com/assets/10330979/11930477/fd7bd750-a7e3-11e5-9e45-2e520a04a501.png)

Thanks guys

**Comment by albundy83** [comment]
Hello,
I have also this issue under debian 7 (with php 5.6 from dotdeb) but not with debian 8 (php 5.6 from official repository).
Not sure if it could be related...

**Comment by bsauveton** [comment]
"Oranges" macros comes from templates setted on the current object. 
You can set the macro as a password on the template wich the macro belong.

**Comment by querwin** [comment]
You're right Benoit but I think that the password checkbox of all macros could be updated. Even if there are inherited macro

**Comment by matthieu-robin** [comment]
Hi guys,
I have created a new service template, and I cannot setup a macro with a password (not in clear). Do you have any idea?
<img width="877" alt="cap 2015-12-22 a 17 21 34" src="https://cloud.githubusercontent.com/assets/10330979/11959975/970c1b5e-a8d0-11e5-93b3-e01d901941f8.png">
