### ISSUE TITLE
[2.7.0] Specific characters in Users --> Full Name filed not allowed

### ISSUE THREAD

**Issue by albundy83** [centreon/centreon#4021]
Hello,
in my name, I have a e acute accent (Grégoire).
So, I have set this in Full Name field from Users.
It's not allowed anymore with Centreon 2.7.
I have an error when I restart Poller, here the error message :
`Error The name of contact 'Gr&eacute' contains one or more illegal characters.`

**Comment by querwin** [comment]
I add that when I want to add my contact on a host, I have an error in my Apache logs : 

[error] [client 10.40.1.137] PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /usr/share/centreon/www/lib/HTML/Common.php on line 144

It's impossible to save the modification

**Comment by Tpo76** [comment]
OK

**Comment by Tpo76** [comment]
works from 2.7.0 freshinstall but not with an update from 2.6.X

**Comment by bsauveton** [comment]
https://github.com/centreon/centreon/commit/de63c42ce553cdd981b6021a92cd88c0ab6c7977#diff-b8156372c789019288182fa921a814ad

**Comment by bsauveton** [comment]
https://github.com/centreon/centreon/commit/a21359eed596c2b038605bf40f473ddf3787966f
