### ISSUE TITLE
[2.7.0] Graph monitoring widget error

### ISSUE THREAD

**Issue by albundy83** [centreon/centreon#4022]
Hello,

this is a post I have made on centreon forum, but maybe it has his place here : 
http://forum.centreon.com/forum/centreon-ui/centreon-web-interface/140149-centreon-web-2-7-0-and-graph-monitoring-widget
When I have upgraded to Centreon 2.7, graph monitoring widgets are not working any more.
I had to modify a php file (/$CENTREON/www/class/centreonGMT.class.php) to make it work again by adding this : 
```php
    if (!isset($sid)) {
        return 0;
    }
```

Here the function before and after : 
```php
function getMyGTMFromUser($userId, $DB = null)
{
    global $pearDB;

    if (!isset($pearDB) && isset($DB)) {
        $pearDB = $DB;
    }

    $DBRESULT = $pearDB->query("SELECT `contact_location` FROM `contact` " .
            "WHERE `contact`.`contact_id` = " . $userId .
            " LIMIT 1");
    if (PEAR::isError($DBRESULT)) {
        $this->myGMT = 0;
    }
    $info = $DBRESULT->fetchRow();
    $DBRESULT->free();
    $this->myGMT = $info["contact_location"];
}
```
And the fixed one :
```php
function getMyGTMFromUser($userId, $DB = null)
{
    global $pearDB;

    if (!isset($pearDB) && isset($DB)) {
        $pearDB = $DB;
    }

    if (!isset($sid)) {
        return 0;
    }

    $DBRESULT = $pearDB->query("SELECT `contact_location` FROM `contact` " .
            "WHERE `contact`.`contact_id` = " . $userId .
            " LIMIT 1");
    if (PEAR::isError($DBRESULT)) {
        $this->myGMT = 0;
    }
    $info = $DBRESULT->fetchRow();
    $DBRESULT->free();
    $this->myGMT = $info["contact_location"];
}
```

**Comment by querwin** [comment]
Have you updated the widget after the centreon update ?

All widgets have to be updated to be compatible with the new version 2.7.0

**Comment by albundy83** [comment]
Not sure to understand what do you mean by updated ?
We were already using the latest Widgets Graph Monitoring version available, the 1.2.0.
Is there a step that I missed ?

**Comment by julienmathis** [comment]
Hello, 

We put online the new version in tgz. Can you test with the version 1.3.0 ? 

Thanks

**Comment by albundy83** [comment]
Hello,
that's just perfect, with this release of graph monitoring widget, I don't need anymore to modify the file : 
`$CENTREON/www/class/centreonGMT.class.php`
It works as expected.
Thanks a lot.

**Comment by albundy83** [comment]
By the way, I have also the issue described here : 
http://forum.centreon.com/forum/centreon-ui/centreon-web-interface/140170-centreon-2-7-0-hostgroups
In apache error log, I have this error : 
`PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/local/centreon/www/widgets/hostgroup-monitoring/src/index.php on line 149`

I have tried your update 1.3 for Widgets Host Group Monitoring and it fix also this issue :) 
Good job !!

**Comment by querwin** [comment]
Perfect I close the ticket.

Thanks for the feedback :)

**Comment by albundy83** [comment]
Just a small issue .. the url for widget Service Group Monitoring is not allowed : 

https://s3-eu-west-1.amazonaws.com/centreon-download/public/centreon-widgets/centreon-widget-servicegroup-monitoring/centreon-widget-servicegroup-monitoring-1.3.0.tar.gz
I have an AccessDenied from amazon ...
