### ISSUE TITLE
[2.7.0] Cannot search event logs filtering by hostgroup - query is wrong

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4023]
Hi, 

On 2.7.0 updated this morning, if I want to select a hostgroup in the eventlog page, select2 display "searching" but nothing happen. 

In sql-error.log I can see that the query is passing (unquoted) host group name in WHERE condition, it's probably some ids that we want pass as the filed is hg.hg_id. Please find detail below :

Error: no such field QUERY : SELECT SQL_CALC_FOUND_ROWS DISTINCT hg.hg.name, hg.hg_id FROM hostgroup hg WHERE hg.hg_name LIKE '%%' AND hg.hg_id IN (Linux,Mon,WIN) ORDER BY hg.hg_name LIMIT 0,30. 

Thanks

**Comment by querwin** [comment]
Fixed with this commit : 
https://github.com/centreon/centreon/commit/05d8e5e5646eebc9b3e3f91cb9b7a32890805e7b
