### ISSUE TITLE
[2.7.0] Syslog GUI not working  

### ISSUE THREAD

**Issue by unbreakabl3** [centreon/centreon#4024]
When clicking on "monitoring>syslog" - its forwarded to "monitoring>performance".
Both links (performance and syslog) are: hostname/centreon/main.php?p=204

**Comment by querwin** [comment]
A new version of syslog will be released soon to fix this problem

**Comment by querwin** [comment]
The new version is online.

If you have any future problem with this module can you open case on the specific git ?

https://github.com/centreon/centreon-syslog-frontend/issues

**Comment by unbreakabl3** [comment]
Hi,
During the upgrade to 1.5.3, all upgrade stages was ok, but the last one is:
"Unable to load all parameters in "instCentWeb.conf" - failed".
