### ISSUE TITLE
[2.7.0] Problem when names are long in Relations tab

### ISSUE THREAD

**Issue by albundy83** [centreon/centreon#4026]
A screen capture will be better in this case, than long explanation ... :)

![screen](https://cloud.githubusercontent.com/assets/1215213/11941738/1098a770-a832-11e5-8582-725db9ace8fc.png)
As you can see in the screen capture above, when the name of the linked resource is long (around / more than 30 characters), the deleting mark is not display and as the zone is not resilzable, you can't remove the resource.
It happens in the : 
- Configurations --> Hosts --> Templates --> Relations
- Configurations --> Services --> Templates --> Relations

Well and maybe in some others places, but that's only place where we use long names ...

**Comment by garnier-quentin** [comment]
You're right. Need a system to manually resize the size.
But you can hold control+shift and click to select/unselect.

**Comment by querwin** [comment]
We can now resize the box and it's a good thing but it's not ompletely ok for me.

If you look at the attach screenshot, you will see the problem
![resize](https://cloud.githubusercontent.com/assets/7510531/12144579/0014f79c-b489-11e5-81a4-e03c1500f163.png)
