### ISSUE TITLE
Possibility to filter servicegroup name in URL

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#4028]
In servicegroup widget, if I click on an servicegroup, it doesn't filter by servicegroup name.
Centreon servicegroup page needs to allow servicegroup name filter in url.
Currently, the servicegroup name filter works only with javascript.

**Comment by kduret** [comment]
linked to this centreon-widget ticket : 
https://github.com/Centreon-Widgets/centreon-widget-servicegroup-monitoring/issues/6

**Comment by Tpo76** [comment]
OK
