### ISSUE TITLE
not really useful (multi-selection)

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4029]
Hello team,
When we have to select multi hosts or services, it's really difficult with the new interface :-(
Is there a way to make multi-selection?
<img width="557" alt="cap 2015-12-22 a 15 24 18" src="https://cloud.githubusercontent.com/assets/10330979/11957169/4f5b4c2c-a8c0-11e5-98f5-db264a11eda5.png">

Thanks a lot

**Comment by Sims24** [comment]
Hi Matthieu,

Ctrl-Shift and click on objects should do what you want I think,

Thanks

**Comment by matthieu-robin** [comment]
Ok, it works. Thanks. 
Another question, if i can? :-)
How can you see all select objects (hosts/services)?

**Comment by Sims24** [comment]
Don't really understand what you mean here, but if this turns around ability to resize boxes, some tickets have already been opened like yours : 

https://github.com/centreon/centreon/issues/4014 
and some others also https://github.com/centreon/centreon/issues/4026  :) 

But maybe you imagine an other listing specific thing ? 

Thanks

**Comment by matthieu-robin** [comment]
Yes, following tickets are ok.
All boxes should be resized, if possible.

Thanks

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by Sims24** [comment]
Cool, think that somebody in on already on it ;) 

++

**Comment by julienmathis** [comment]
Boxes will be resizable in the next version 2.7.2.

Regards
