### ISSUE TITLE
fix upgrade doc 2.7 about myisam -> innodb

### ISSUE THREAD

**Issue by dmagniez** [centreon/centreon#4030]
Reading upgrade doc, a sentence is not understandable

"Database engine update from MyISAM to InnoDB (expected logs and data_bin tables)"
should be "except" in place of "expected"

https://documentation.centreon.com/docs/centreon/en/latest/upgrade/from_packages.html

by the way, is a manual couversion for these 2 tables are allowed ?
should it be precised ?

**Comment by julienmathis** [comment]
Thanks ! 

https://github.com/centreon/centreon/commit/601752baf186e28044b4fba6246c518f5b8b37ef
