### ISSUE TITLE
Cannot remove "public" access to my widget view

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4033]
I would like to remove the "public" access to my view, and I can't. When I remove the tick, it stays here.
<img width="377" alt="cap 2015-12-22 a 17 47 25" src="https://cloud.githubusercontent.com/assets/10330979/11960706/3698d47a-a8d4-11e5-9519-de92508adec7.png">
<img width="382" alt="cap 2015-12-22 a 17 47 20" src="https://cloud.githubusercontent.com/assets/10330979/11960707/36bab5c2-a8d4-11e5-8c3a-3d5e21600900.png">

**Comment by querwin** [comment]
Fix seems not to be OK
