### ISSUE TITLE
see '0' instead of name of graph template

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4035]
On a Service template, when we select a graph template, we got a 0:

<img width="595" alt="cap 2015-12-23 a 10 22 11" src="https://cloud.githubusercontent.com/assets/10330979/11973861/26caece6-a95f-11e5-9e86-4f9665117ee9.png">

**Comment by maksimatveev** [comment]
@querwin Sorry, but the correction is already available for download via the update?

**Comment by mathieuchateau** [comment]
Even after manual fix, it comes back when editing again service

**Comment by maksimatveev** [comment]
@mathieuchateau those. the problem is not solved by manual files?
@bsauveton Your fix should be installed otherwise?
