### ISSUE TITLE
[2.7.0] Several observations on LDAP groups

### ISSUE THREAD

**Issue by dooko** [centreon/centreon#4036]
- Groups are duplicated in 'Linked Contact Groups' when editing an access group. Just one of each can be selected though. One of each also appearing in centreon.contactgroup.
- On a LDAP user belonging to a LDAP group, is that normal to see a 'contact group' object, in addition to the 'Group Ldap' ?
  ![image](https://cloud.githubusercontent.com/assets/15345999/11974798/f159f92c-a967-11e5-9359-1fa6273fe17d.png)

**Comment by lpinsivy** [comment]
should be solved
