### ISSUE TITLE
[2.7.0] Empty pollers list despite ACLs permission

### ISSUE THREAD

**Issue by dooko** [centreon/centreon#4037]
Non admin users cannot see poller list in 'Configuration > Pollers' despite the fact that we give them the right :
 - to see 'Configuration > Poller' in 'Menu Access' in ACL configuration,
 - to do 'Restart Monitoring Engine' in 'Actions Access' in ACL configuration.

The rights are then given to a LDAP 'contact group' through an 'Access group'

**Comment by bsauveton** [comment]
You must add the pollers in the resources access menu.

Administration  >  ACL  >  Resources Access

Click on the resource group and go into "filter" tab, there you can see the list of poller you want to give the access to the resource group.
(only activated pollers will appears for the user.)

Regards.

**Comment by dooko** [comment]
It works for me too, thanks !
