### ISSUE TITLE
[2.7.0] Widget "service monitoring" shows alert but host is deleted

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#4038]
The service widget "service monitoring" reports a CRITICAL alert, but the host is deleted from the system.
![2015-12-23 11_49_50-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/6400595/11975184/6701e542-a96b-11e5-93a4-5f5c6d0171d7.png)

**Comment by joschi99** [comment]
After some hour the false alert are not more visible. No idea why.

**Comment by maksimatveev** [comment]
confirm the remote hosts in the widget are.

**Comment by mtoufik** [comment]
Did you export the configuration after removing the host ?

**Comment by joschi99** [comment]
After removing the host the configuration was exportet and the engine reloaded.

If you look the screenshot you can see that:
* the service is critical
* last check of the service was on 10:35
* system time was 11:49
* on global service indicators there are no critical services
* I checked manually on host and configuration monitoring site, but host and service was removed

**Comment by julienmathis** [comment]
this commit should fix your problem.

https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/commit/0a65fb561f1cd553821220165c9b944d5759e61f

Can you open widget ticket on the good projet ? :) Thanks in advance

**Comment by joschi99** [comment]
Please refer to https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/issues/32
