### ISSUE TITLE
[2.7.0] UI notifications can't be removed

### ISSUE THREAD

**Issue by albundy83** [centreon/centreon#4040]
Hello,

I have activated the UI notifications from Administration  >  Parameters  >  My Account
(All of them).
But some OK notifications remains and continue to popup all the time even when I click on them...
No idea, how I can send you some errors about this ... :(

**Comment by albundy83** [comment]
To be more specific, when I click on a page that refresh the UI, notifications come back.
I have tried on Chrome and Firefox (both latest version) on Ubuntu.

**Comment by bsauveton** [comment]
Can you contact me by mail ? 
bsauveton@centreon.com

**Comment by albundy83** [comment]
Mail sent.

**Comment by querwin** [comment]
Hello,

No news since Benoit contacts you. Is the problem solved ?

**Comment by albundy83** [comment]
No, no more news.
But with my latest tests and centreon 2.7.1, no more problem :) 
Thanks a lot.

**Comment by querwin** [comment]
Ok good news :)

Thanks for your answer
