### ISSUE TITLE
[2.7.0] Problem with recurring downtime timestamp

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4041]
Hi, 

With following setup :

Centreon 2.7.0 
Timezone server = "Europe/Paris"
Timezone centreon_user = "Europe/Paris"
Timezone centreon_host = "Europe/Paris"
Timezone php.ini = "Europe/Paris"

When using recurring downtime, my time value are OK in the DB but when downtimeManager.php schedule the downtime, it adds an offset (see centreonGMT.class.php), and then for me my downtime is one hour late ... 

Could you check this point please ? 

Thanks !

**Comment by Sims24** [comment]
After digging around a little juste think that the problem is line 201/202 from centreonGMT.class.php, because when we use the getOffset method we compare with UTC time even if the server is not configured with this timezone.

My dirty workaround is to comment the line where we add the offset and let the $iTimestamp unchanged and it's ok. 

Regards

**Comment by querwin** [comment]
Sorry wrong ticket :)
