### ISSUE TITLE
[2.7.0] Perl Connector will not be exported on central poller

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#4045]
If I generate the configuration on the central poller the export will not find any connector and show's me this output:
```
Reading main configuration file '/usr/share/centreon/filesGeneration/nagiosCFG/1/nagiosCFG.DEBUG'.
Reading resource file '/usr/share/centreon//filesGeneration/nagiosCFG/1/resource.cfg'
Checking global event handlers...
Checking obsessive compulsive processor commands...

Checked 16 commands.
Checked 0 connectors.
Checked 1 contacts.
Checked 0 host dependencies.
Checked 0 host escalations.
Checked 1 host groups.
Checked 1 hosts.
Checked 0 service dependencies.
Checked 0 service escalations.
Checked 1 service groups.
Checked 29 services.
Checked 1 time periods.
```

If I export the configuration on the same system for the poller 1 then the connector will be found and exported:
```
Reading main configuration file '/usr/share/centreon/filesGeneration/nagiosCFG/2/nagiosCFG.DEBUG'.
Reading resource file '/usr/share/centreon//filesGeneration/nagiosCFG/2/resource.cfg'
Checking global event handlers...
Checking obsessive compulsive processor commands...

Checked 10 commands.
Checked 2 connectors.
Checked 1 contacts.
Checked 0 host dependencies.
Checked 0 host escalations.
Checked 1 host groups.
Checked 1 hosts.
Checked 0 service dependencies.
Checked 0 service escalations.
Checked 0 service groups.
Checked 8 services.
Checked 1 time periods.

Total Warnings: 0
Total Errors: 0
```

**Comment by Laexar** [comment]
Bonjour,

Même problème ici, pour corriger le souci c'est assez simple.

Première solution, modifier le code dans le fichier centreon/www/class/config-generate/engine.class.php, ligne 405:

    if (!is_null($poller['monitoring_engine']) && $poller['monitoring_engine'] == 'CENGINE') {
 par : 

    if (!is_null($poller['monitoring_engine']) && ($poller['monitoring_engine'] == 'CENGINE' || $poller['monitoring_engine'] == 'Centreon Engine')) {

Sinon, autre méthode, sur la base centreon directement : 

    UPDATE nagios_server SET monitoring_engine = 'CENGINE' WHERE monitoring_engine = 'Centreon Engine';

La première solution est plus perreine car il semblerait que, lors de la création de poller Centreon Engine depuis l'interface, la colonne monitoring_engine soit mis à la valeur "Centreon Engine".
Cependant cela implique la modification du code source de l'application.

**Comment by Tpo76** [comment]
OK

**Comment by kadrika** [comment]
We had similar problem in 2.7.1 also. But we have frontend with 4 pollers, and only 1 poller had that problem and modifying the engine.class.php file fixed the issue.

**Comment by lolokai** [comment]
This problem has not been corrected in 2.7.2...

**Comment by kadrika** [comment]
I can also confirm, that the problem still exists in 2.7.2.

**Comment by joschi99** [comment]
For me know in 2.7.2 works. Maybe another issue?

**Comment by lolokai** [comment]
I 've corrected this problem by editing this file : centreon/www/class/config-generate/engine.class.php
So I suppose Centreon 2.7.2 release doesn't include the modification in this file.
