### ISSUE TITLE
[2.7.0] Duplicated services on hosts

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon#4046]
Hello!
Some hosts other than the main service (example 	fping-lan) has not yet active doubles:
![2015-12-24_185606](https://cloud.githubusercontent.com/assets/15804154/11996253/36c36dc8-aa70-11e5-9dff-e38a05849512.png)
How can I remove them? This is a bug or my configuration error?

At the same time such services are suppressed from the destination (Configuration  >  Services  >  Services by host):
![2015-12-24_190154](https://cloud.githubusercontent.com/assets/15804154/11996285/a4fb51ca-aa70-11e5-9884-8283836bd880.png)

The only place where the service is mentioned "Configuration  >  Services  >  Services by host group":
![2015-12-24_190238](https://cloud.githubusercontent.com/assets/15804154/11996299/e3ef38a6-aa70-11e5-8106-b5e5a6c46de9.png)

There is a way to clear inactive duplicates?

**Comment by cmeschin** [comment]
Hello,
I have similar issue on centreon 2.6.6 and centreon-engine 1.4.15
Visibly, it's the reload process of centreon-engine who make this duplicates but it's not at every times.
I can't identify, at this time, the process who generate this doubles.
A restart (not reload) of centreon-engine resolve this for me.

regards.

**Comment by maksimatveev** [comment]
@cmeschin Thanks, really helped!

**Comment by maksimatveev** [comment]
Closed
