### ISSUE TITLE
[2.7.0] Centreon API 2.7 (old CLAPI) breaks Web Configuration Gen/Export

### ISSUE THREAD

**Issue by DaStivi** [centreon/centreon#4047]
Hi, i've posted this in the centreon forum too... but i guess it would be good to post here too, as i expect this is a bug!

i've updated Centreon to 2.7 (Centreon-Broker 1.5) and i have some automation Scripts inplace that adds Checks automatically.... after the upgrade the scripts didn't worked anylonger ... i found that the centreon-clapi directory didn't exist anylonger.... i tried manually adding the centreon-clapi back to the extensions... that did worked, but configuration generation (applycfg) didn't worked.... as there are couple of files missing... then i found that the centreon-web 2.7 replaced the clapi with the new "centreon api"...

calling the same poller applycfg comand with the api works, the files get generated and the poller is restarted... the issue is that this command works with root credentials, but as soon as running it with centreon user i got "please check that you parameters are valid"

the issue after running it as root is that i can't generate the poller configs from the web interface anylonger!

Preparing environment... OK
Generating files... NOK (Exception received : Not writeable directory '/usr/share/centreon//filesGeneration/nagiosCFG/1' [file: /usr/share/centreon/www/class/config-generate/backend.class.php] [line: 114] )
Aborted.

workaround to fix the generation via webinterface is to chown back the folder/files of fileGeneration/nagioscfg and broker to centreon user/group:

 ll /usr/share/centreon/filesGeneration/nagiosCFG/1/
insgesamt 124
-rw-r--r-- 1 root centreon  3628 28. Dez 09:33 centengine.cfg
-rw-r--r-- 1 root centreon  8018 28. Dez 09:33 commands.cfg
-rw-r--r-- 1 root centreon  1424 28. Dez 09:33 connectors.cfg
-rw-r--r-- 1 root centreon  1724 28. Dez 09:33 contactgroups.cfg
-rw-r--r-- 1 root centreon  6684 28. Dez 09:33 contacts.cfg
-rw-r--r-- 1 root centreon  1088 28. Dez 09:33 dependencies.cfg
-rw-r--r-- 1 root centreon  1088 28. Dez 09:33 escalations.cfg
-rw-r--r-- 1 root centreon  2030 28. Dez 09:33 hostgroups.cfg
-rw-r--r-- 1 root centreon  4356 28. Dez 09:33 hosts.cfg
-rw-r--r-- 1 root centreon  2646 28. Dez 09:33 hostTemplates.cfg
-rw-r--r-- 1 root centreon  1088 28. Dez 09:33 meta_commands.cfg
-rw-r--r-- 1 root centreon  1088 28. Dez 09:33 meta_host.cfg
-rw-r--r-- 1 root centreon  1088 28. Dez 09:33 meta_services.cfg
-rw-r--r-- 1 root centreon  1088 28. Dez 09:33 meta_timeperiod.cfg
-rw-r--r-- 1 root centreon  4132 28. Dez 09:33 nagiosCFG.DEBUG
-rw-r--r-- 1 root centreon  1253 28. Dez 09:33 resource.cfg
-rw-r--r-- 1 root centreon  1088 28. Dez 09:33 servicegroups.cfg
-rw-r--r-- 1 root centreon 23895 28. Dez 09:33 services.cfg
-rw-r--r-- 1 root centreon 10377 28. Dez 09:33 serviceTemplates.cfg
-rw-r--r-- 1 root centreon  1746 28. Dez 09:33 timeperiods.cfg
[root@host modules]# chown apache:centreon /usr/share/centreon/filesGeneration/nagiosCFG/1/*
[root@host modules]# ll /usr/share/centreon/filesGeneration/nagiosCFG/1/
insgesamt 124
-rw-r--r-- 1 apache centreon  3628 28. Dez 09:33 centengine.cfg
-rw-r--r-- 1 apache centreon  8018 28. Dez 09:33 commands.cfg
-rw-r--r-- 1 apache centreon  1424 28. Dez 09:33 connectors.cfg
-rw-r--r-- 1 apache centreon  1724 28. Dez 09:33 contactgroups.cfg
-rw-r--r-- 1 apache centreon  6684 28. Dez 09:33 contacts.cfg
-rw-r--r-- 1 apache centreon  1088 28. Dez 09:33 dependencies.cfg
-rw-r--r-- 1 apache centreon  1088 28. Dez 09:33 escalations.cfg
-rw-r--r-- 1 apache centreon  2030 28. Dez 09:33 hostgroups.cfg
-rw-r--r-- 1 apache centreon  4356 28. Dez 09:33 hosts.cfg
-rw-r--r-- 1 apache centreon  2646 28. Dez 09:33 hostTemplates.cfg
-rw-r--r-- 1 apache centreon  1088 28. Dez 09:33 meta_commands.cfg
-rw-r--r-- 1 apache centreon  1088 28. Dez 09:33 meta_host.cfg
-rw-r--r-- 1 apache centreon  1088 28. Dez 09:33 meta_services.cfg
-rw-r--r-- 1 apache centreon  1088 28. Dez 09:33 meta_timeperiod.cfg
-rw-r--r-- 1 apache centreon  4132 28. Dez 09:33 nagiosCFG.DEBUG
-rw-r--r-- 1 apache centreon  1253 28. Dez 09:33 resource.cfg
-rw-r--r-- 1 apache centreon  1088 28. Dez 09:33 servicegroups.cfg
-rw-r--r-- 1 apache centreon 23895 28. Dez 09:33 services.cfg
-rw-r--r-- 1 apache centreon 10377 28. Dez 09:33 serviceTemplates.cfg
-rw-r--r-- 1 apache centreon  1746 28. Dez 09:33 timeperiods.cfg

centreon api isn't working either after this:
centreon -u admin -p ***** -a POLLERGENERATE -v 1
Please check that your parameters are valid

only pollergenerate isn't working.... movecfg, pollerrestart, list pollers etc everything is working... only pollergenerate isn't!

**Comment by DaStivi** [comment]
i found a "solution"  you have to run the centreon "clapi" command as apache user

**Comment by hecko** [comment]
We are experiencing slightly different issue - the configuration for poller is generated just fine with clapi

centreon -u clapi -p zxczxc -a APPLYCFG -v 12
they are generated with apache:apache owner flags
but the files are never moved to the poller

when generated via web page the files are generated and instantly moved to poller
in this case files are created as apache:centreon

groups:
centreon:x:498:centreon-engine,centreon-broker,apache

thats the only difference I see here that I can actually debug as I cant find ANY debug/log information about the process of generating files , copying to the pollers or restarting pollers in main centreon server
