### ISSUE TITLE
[2.7.0] View log page with vhost

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon#4048]
With apache configured in vhost, for displaying Centreon with a url http://mysite.mydomain/ instead of http://mysite.mydomain/centreon/

We have a problem with eventlog page. When we are displaying the event log page, we are redirected on this url http://mysite.mydomain/centreon/

In the viewlog.php, we have removed "/centreon/" on the line 495 and 779, and it's ok now.

**Comment by Tpo76** [comment]
ok
