### ISSUE TITLE
[2.7.0] PHP 5.4.45: PHP Warning strlen() expects parameter 1 to be string /usr/share/centreon/www/lib/HTML/QuickForm/checkbox.php

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#4050]
Upgrading on CentOS 6.7 to PHP 5.4 there is a warning on Centreon Web on Custom Views:

```
[Tue Dec 29 21:41:12 2015] [error] [client 192.168.193.1] PHP Warning:  strlen() expects parameter 1 to be string, array given in /usr/share/centreon/www/lib/HTML/QuickForm/checkbox.php on line 126, referer: http://192.168.193.129/centreon/main.php?p=504
```

**Comment by Laexar** [comment]
Same issue here.
This is due to PHP5.3.0+ (http://php.net/manual/en/function.strlen.php) which is not automatically casting argument to string anymore.

You can quickly fix it by replacing line126:
if (0 == strlen($this->_text)) {

by:
if (0 == strlen((string)$this->_text)) {

**Comment by joschi99** [comment]
This resolve the issue.

Thx,
Jochen
