### ISSUE TITLE
display issue on Graph

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4051]
We don't see the end of the graph :-(
![cap 2015-12-30 a 10 48 13](https://cloud.githubusercontent.com/assets/10330979/12049065/09d87ac0-aee3-11e5-8655-49c442d30fb1.png)

**Comment by julienmathis** [comment]
Sorry, but with Centreon 2.7.1 it doesn't work for me.

**Comment by julienmathis** [comment]
Works for me now.
