### ISSUE TITLE
[2.6.6] ACL - Servicegroup non visible dans la configuration

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4052]
Bonjour,
Ce problème a peut-être déjà été signalé mais je ne l'ai pas retrouvé.
Un utilisateur soumis à ACL et ayant accès à la configuration ne peut pas affecter de servicegroup (liste grisée) que ce soit de manière unitaire ou par changement massif.
![centreon_acl_servicegroup](https://cloud.githubusercontent.com/assets/8720203/12051964/7f89cce8-af0a-11e5-9b4a-eaeac2aa6648.png)

Dans la configuration des ACL, l'accès est total (tous menus, groupes et ressources) et en lecture/écriture.
![centreon_acl_manager_plus](https://cloud.githubusercontent.com/assets/8720203/12051931/15e0fca8-af0a-11e5-983c-7f4aa150d17a.png)

Ce problème ressemble fortement à un ticket précédent sur les catégories d'hôte (#308).

**Comment by lpinsivy** [comment]
Works with Centreon 2.7.2

**Comment by julienmathis** [comment]
So already fixed !
