### ISSUE TITLE
[2.7.0] Services and TopCounter XML directory structures differs from others

### ISSUE THREAD

**Issue by fffialho** [centreon/centreon#4053]
The supression of subdirectory broker on directory structure of monitoring/status/Services and TopCounter breaks compatibility with some monitoring clients, e.g nagstamon.

I know that ndo support was dropped at last centreon release, but all others dirs under monitoring/status have kept the broker subdirectory.

**Comment by julienmathis** [comment]
Sorry, we will not fix that. May be a apache configuration can solve that ?

**Comment by fffialho** [comment]
Hummm.. Yes, apache rewrite can solve it.

Indeed, I'm using rewrite module to solve this and others strange changes
like "o" parameter to statusHost/statusService for service and host XML
files.


2016-01-07 10:28 GMT-02:00 Julien Mathis <notifications@github.com>:

> Sorry, we will not fix that. May be a apache configuration can solve that ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/centreon/centreon/issues/4053#issuecomment-169648240>.
>



-- 
Francisco Fialho
fffialho@gmail.com

**Comment by flooll** [comment]
Hi, can you explain how do you configure the apache rewrite module ?

**Comment by fffialho** [comment]
Hi @flooll,

The workaround I'm using is something like that:
```
        RewriteCond %{REQUEST_URI}      ^(.*/Services/xml)/broker/(.*)$ [NC]
        RewriteRule ^.*$                %1/%2 [QSA]

        RewriteEngine On
        RewriteCond %{REQUEST_URI}      /serviceXML.php [NC]
        RewriteCond %{QUERY_STRING}     (.*(?:^|&))o=svcpb((?:&|$).*)
        RewriteRule ^(.*)$              $1?%1statusService=svcpb%2 [L]

        RewriteCond %{REQUEST_URI}      /hostXML.php [NC]
        RewriteCond %{QUERY_STRING}     (.*(?:^|&))o=hpb((?:&|$).*)
        RewriteRule ^(.*)$              $1?%1statusHost=hpb%2 [L]
```

It fixes the problem that I described before and the issues with changes on querystring for service and host problem that affects nagstamon.
