### ISSUE TITLE
[2.7.0] Groupes d'hôtes parents erreur pour les utilisateurs

### ISSUE THREAD

**Issue by Wouaf** [centreon/centreon#4057]
Bonjour,

Nous rencontrons actuellement un problème lors de la création d'un nouvel hôte.
En effet, dans l'onglet <code>Relations</code>, lorsque l'utilisateur clique dans <code>Groupes d'hôtes parents</code> la liste n'apparait pas (searching en boucle), une erreur apparait dans les fichiers de log de httpd et de centreon/sql-error.log. Pour httpd, il s'agit simplement de PHP qui signale un problème de fetch row sur une requête échoué, mais pour centreon/sql, l'erreur est plus parlante :
<pre><code>2016-01-04 11:37|0|0|DB Error: no such field QUERY : SELECT SQL_CALC_FOUND_ROWS DISTINCT hg.hg_name, hg.hg_id FROM hostgroup hg WHERE hg.hg_name LIKE '%%' AND hg.hg_id IN (Firewall,Linux-Servers,Networks,Printers,Routers,Switchs,Unix-Servers,Windows-Servers) ORDER BY hg.hg_name LIMIT 0,30</code></pre>
Comparer des IDs et des noms est assez compliqué XD.
Du coup, j'ai tracé l'erreur pour arriver à la classe suivante : www/class/centreonACL.class.php.
La fonction <em>getHostGroupsString</em> possède une bonne coquille : 
<pre><code>    /*
     *  Hostgroups string Getter
     *  Possible flags :
     *  - ID => will return the id's of the element
     *  - NAME => will return the names of the element
     */

    public function getHostGroupsString($flag = null) {
        $flag = strtoupper($flag);

        $hostgroups = "";
        foreach ($this->hostGroups as $key => $value) {
            switch ($flag) {
                case "NAME" :
                    $hostgroups .= "'" . $value . "',";
                    break;
                case "ALIAS" :
                    $hostgroups .= "'" . addslashes($this->hostGroupsAlias[$key]) . "',";
                    break;
                case "ID" :
                    $hostgroups .= $value . ",";
                    break;
                default :
                    $hostgroups .= "'" . $key . "',";
                    break;
            }
        }</code></pre>
Il faut remplacer <pre><code>case "ID" :
    $hostgroups .= $value . ",";
    break;</code></pre>
Par <pre><code>case "ID" :
    $hostgroups .= $key . ",";
    break;</code></pre>

Ayant rencontré ce bug sur nos deux serveurs de supervision, je suppose qu'il s'agit d'un problème généralisé.

Cordialement.

**Comment by querwin** [comment]
Fixed by this commit : 05d8e5e5646eebc9b3e3f91cb9b7a32890805e7b
