### ISSUE TITLE
Quicksearch not working on service_dependency page (p=60409) - SQL Query

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#406]
---

Author Name: **Ira Maus** (Ira Maus)
Original Redmine Issue: 6425, https://forge.centreon.com/issues/6425
Original Date: 2015-06-09

---

Quicksearch is not working, because there are some "()" missing at the SQL Queries.

File:centreon/www/include/configuration/configObject/service_dependency/listServiceDependency.php

Line62 - add (:
 $rq .= " WHERE ((SELECT DISTINCT COUNT(*)
Line68 - add ):
  WHERE dscr.dependency_dep_id = dep.dep_id $aclCond) > 0) ";
Line101 - add (:
  $rq .= " WHERE ((SELECT DISTINCT COUNT(*)
Line107 - add ):
  WHERE dscr.dependency_dep_id = dep.dep_id $aclCond) > 0 )";

Reason: The query contains ...where xxx OR xxx AND search -> interpreted as "(xxx) OR (xxx AND seach)" by SQL-Server.

**Comment by julienmathis** [comment]
Thanks for the feedback
