### ISSUE TITLE
List not more 100 items

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4060]
Since the version 2.7, we cannot select the full list of items. We are blocked at 100...

Can we have the possibility to have the full list?

<img width="1177" alt="cap 2016-01-05 a 09 00 05" src="https://cloud.githubusercontent.com/assets/10330979/12110297/230ba894-b38b-11e5-972f-a71c0c6129a1.png">

**Comment by julienmathis** [comment]
Oh no :) We haven't changed anything on this point. It is like that since a long time. We don't want  performance issues...

**Comment by matthieu-robin** [comment]
Roh…
My client is crying….! :-)
A small tips to remove this limitation?

:-)

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by julienmathis** [comment]
Send me an email on private :)
