### ISSUE TITLE
Service Monitoring Widget issue 

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4062]
When I (as admin) click on a host, I got a "You are not allowed to reach this page":
<img width="664" alt="cap 2016-01-05 a 17 08 38" src="https://cloud.githubusercontent.com/assets/10330979/12119985/0d3c1e4c-b3cf-11e5-9be9-05fd9e5e72dc.png">

<img width="920" alt="cap 2016-01-05 a 17 08 51" src="https://cloud.githubusercontent.com/assets/10330979/12119982/08bd0afc-b3cf-11e5-883d-eef5dca210bf.png">

Merci

**Comment by querwin** [comment]
Issue concerning widget have to be open on centreon widget github.

This issue is the same as this : https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/issues/31

It will be ok in the next release of this widget
