### ISSUE TITLE
Display issue on user view

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4063]
Hello team,

Tested with Chrome and Firefox:
<img width="413" alt="cap 2016-01-06 a 09 15 00" src="https://cloud.githubusercontent.com/assets/10330979/12138094/5dfd0184-b456-11e5-9db8-131ab62a44ca.png">

Merci bien

**Comment by querwin** [comment]
Same as this issue : https://github.com/centreon/centreon/issues/4039
