### ISSUE TITLE
Dashboard by hostgroup doesn't work with ACL

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4065]
I got a user with All ressources access, and lot of access. When he goes to Reporting, Dashboard:
By host, it works fine
By hostgroup, doesn't work at all. Empty.

Any idea?

**Comment by julienmathis** [comment]
linked to #4129

**Comment by aelkerouani** [comment]
fix the dashboard hostgroup display problème bath not the servicegroup with ACL.
