### ISSUE TITLE
Widget issue with Firefox ESR (version 38.5.2)

### ISSUE THREAD

**Issue by boupjof** [centreon/centreon#4066]
Centreon 2.7.0
Host Monitoring Widget for displaying host monitoring information 1.4.1 
Service Monitoring Widget for displaying service monitoring information 1.4.1 

![capture](https://cloud.githubusercontent.com/assets/16577504/12145043/210029ec-b48c-11e5-92b4-364cac45c470.JPG)

**Comment by masgo** [comment]
I can support this problem. I am using the latest Firefox (43.0.4) and the Two widgets are also very small for me. They only show 6 hosts and a scroll bar, althou I have ~30 hosts and plenty of blank screen below them. 
The error does not happen in Chrome.
![screenshot-localhost 50080 2016-01-07 09-19-57](https://cloud.githubusercontent.com/assets/1336992/12165676/2d0405bc-b520-11e5-9217-6b976c2ca300.png)

**Comment by gslongo** [comment]
Dear Team and Community,

Same issue for us with Firefox ESR. I confirm the issue do not appears on Google-Chrome.

This is a non-critical bu annoying bug :-(

![capture-centreon - it network monitoring - mozilla firefox](https://cloud.githubusercontent.com/assets/5636906/12288148/e1b201e8-b9d1-11e5-9950-808e10fa261d.png)

**Comment by julienmathis** [comment]
Hello, 

Can you checkout the last version of the widget "host-monitoring" and validate that all is ok for you ? 

commit : 038554c

Thanks in advance.

**Comment by boupjof** [comment]
With the last version of centreon (2.7.4) and "host-monitoring" (1.4.2) the issue dont appear.
Thanks

**Comment by masgo** [comment]
The issue is still present in the latest Firefox (46.0.1)
(I also use centreon 2.7.4 and host-monitoring 1.4.2)

It works _sometimes_ if I press the small refresh button of the widget, but not every time.
