### ISSUE TITLE
2.7.0 - no performance graph for host group service

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#4068]
Hello,

since version 2.7.0, when I go to Performance page, services drill down only display service host, no hostgroup service.

Whether or not I choose a host first, Services field only shows up a host service I created to test:

Page called: /centreon/main.php?p=204

![image](https://cloud.githubusercontent.com/assets/4478521/12148990/b07e26f4-b4a1-11e5-82f1-eb070b0a66b6.png)

All my services are hostgroup based, so it only display this test one.

From Status details, I can see graph. If I click on a graph, then page is working:
![image](https://cloud.githubusercontent.com/assets/4478521/12149039/eea7ea50-b4a1-11e5-9d56-75894e82c896.png)

**Comment by julienmathis** [comment]
Thanks !
