### ISSUE TITLE
[2.7.0] Rights change on generated files

### ISSUE THREAD

**Issue by dooko** [centreon/centreon#4069]
We are out of solutions...
Since the update to Centreon Web 2.7.0, the following directories rights are always modified to root.root :
/usr/share/centreon/filesGeneration/nagiosCFG/10
/usr/share/centreon/filesGeneration/broker/10
This prevent us to reload the corresponding poller.
Can this come from Centreon ?

**Comment by querwin** [comment]
Maybe the same of this issue : https://github.com/centreon/centreon/issues/4047

We are on it
