### ISSUE TITLE
[2.7.0] Downtime recurrent

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4071]
Les downtimes recurrent se basent sur l'heure UTC et non sur l'heure définit dans le champ Timezone (définit sur Administration ==> Parameters) ce qui fait qu'on se retrouve avec des downtimes récurrents qui sont décalés par rapport aux horaires définits

**Comment by Gilum** [comment]
+1

**Comment by querwin** [comment]
Can you try and say me if the 2.7.1 version fix the problem ?

**Comment by Gilum** [comment]
Thank you querwin,  i'm testing update tomoro

**Comment by querwin** [comment]
I think timezone are not apply and now timezone are created every time the cron is scheduled

**Comment by julienmathis** [comment]
@ganoze : can you give us a status about this ticket ?

Thanks

**Comment by Gilum** [comment]
Merci pour le fix, il corrige pas mal de bug.
Cependant il reste un gros bug pour certain downtime a cheval entre deux jours

Exemple, j'ai un downtime de 19h à 7h avec deux plage 19:00 - 24:00 et 00:00 - 07:00
Le 12/02 à 18h50 le cron crée un downtime qui commence le 12/02 à 19:00 et ce termine le 14/02 à 00:00 soit plus de 24heure de downtime.


Pour contourner le problème je crée une première plage de 19:00 à 23:59 et une autre de 00:01 à 07:00

**Comment by Gilum** [comment]
#4191

**Comment by Gilum** [comment]
#4191 not merged ?
