### ISSUE TITLE
2.7.0 - status detail - hostgroup filter is empty

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#4075]
Hello,

With admin account and version 2.7.0, on status detail page, Hostgroup filter is empty while i do have 50 hostgroups:

![image](https://cloud.githubusercontent.com/assets/4478521/12192162/a62d92f2-b5dc-11e5-917b-a3ae100d0a6b.png)

**Comment by mathieuchateau** [comment]
resolved after restarting all centreon daemon.

Maybe add to procedure that all services need restart after upgrade?

**Comment by bsauveton** [comment]
https://documentation.centreon.com/docs/centreon/en/2.7.x/upgrade/from_packages.html
