### ISSUE TITLE
centreon-widget-live-top10-memory-usage does not work

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon#4076]
Hello,

I'm using Centreon 2.7.0 and the top10 widget to monitor usage memory.
---> Package centreon-widget-live-top10-memory-usage.noarch 0:1.0.0-5.el6 

I have some memory services with the "used" metric, but my widget is empty, the widget does not show anything.

Best regards.

**Comment by florian-asche** [comment]
Hi, my Top10 Memory is working great. I'm working with the centreon-plugins from Github. Here is a example output from perf-data: 'cached'=94826496B;;;0; 'buffer'=0B;;;0; 'used'=1675612160B;0:3006477107;0:3435973836;0;4294967296

**Comment by julienmathis** [comment]
Is the problem still there ? I don't have problem with this widget.

If yes, can you open it in the right github repo : Centreon-Widgets/centreon-widget-live-top10-memory-usage
