### ISSUE TITLE
[2.7.0] generateSqlLite not install with source

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#4077]
Hello

generate SNMP trap generation does not work. 
![install-centreon-nagvis2016-01-08_10-48-41_pm](https://cloud.githubusercontent.com/assets/12350746/12210439/4494a69c-b65a-11e5-864d-588fad94d22f.png)
Install with source with Debian. 
Logs install

>[./install.sh]:INFO: Install generateSqlLite
Install generateSqlLite : FAIL

the file generateSqlLite was not copied to the folder /usr/share/centreon/bin

**Comment by albundy83** [comment]
I confirm that this problem is still present in 2.7.1.

**Comment by euidzero** [comment]
My fix :
[CentWeb.patch.txt](https://github.com/centreon/centreon/files/103022/CentWeb.patch.txt)

**Comment by albundy83** [comment]
Yes it works perfectly.

**Comment by julienmathis** [comment]
Thanks we will fix that.
