### ISSUE TITLE
Cannot add directly filters to new outputs

### ISSUE THREAD

**Issue by bcournaud** [centreon/centreon#4078]
When a create a new TCP/IP V4 output, I cannot set the filters.
When I try to do so, nothing happens and I got the following error in the console :

Uncaught TypeError: Cannot read property 'length' of undefined
QFAMS.moveSelection @ qfamsHandler-min.js:1
ondblclick @ main.php?p=60909&o=c&id=1:1

However, if I create the output without filters, save, and then edit it again, I can add filters.

I had this issue on several platforms.
However, some times I'm not able to reproduce it.

**Comment by Tpo76** [comment]
OK
