### ISSUE TITLE
[2.7.0] bad service name encoding after upgrade

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#4079]
Hello,

after upgrading from 2.6.x to 2.7.0, service name with french accent are badly encoded:
![image](https://cloud.githubusercontent.com/assets/4478521/12215559/ff7a2542-b6c1-11e5-8c39-a56be950d9ee.png)

**Comment by Sims24** [comment]
Hi, 

I confirm this behaviour on 2.7.0, upgrading from 2.6.3.

If I save the form manually replacing char it's OK then, but can take a long time for unique objects like contacts.

For services, I just used a SQL Query creating some pending state at restart but it did the trick as a workaround.

Thanks
