### ISSUE TITLE
Issue with quick "Export configuration" after update 24.04.0

### ISSUE THREAD

**Issue by Nyxtorm** [centreon/centreon#4079]
```
# dpkg -l | grep centreon-widget-graph-monitoring
X [2024-05-15 05:50:37 +0200] root@kepler [ ~ ]
```
### Operating System

Debian 12 w/ Centreon from APT packages

### Browser used

Microsoft Edge 124.0.2478.97

### Description / Received result

Since updating to 24.04.0 from the latest 23.10, when I use the quick "Export configuration" button, I get the message `There was an inconsistency error in the exported files - please use the legacy export menu to troubleshoot`.

The URL `/centreon/api/latest/configuration/monitoring-servers/generate-and-reload` displays this:

```
{
    "code": 500,
    "message": "There was an consistency error in the exported files  - please use the legacy export menu to troubleshoot"
}
```

- No change in Apache configuration
- No error with legacy method

### Steps to Reproduce

1. I logged in Centreon
2. Pollers => Export Configuration

### Describe the expected result

Success message reloading as it was with 23.10.

### Logs

**Centreon Web Log**

```
[2024-05-15T05:48:06+0200] [ERROR] [Centreon\Application\Controller\Configuration\MonitoringServerController:229]: Generation error on monitoring server #1: Authentication token expired
```

**PHP error logs**

```
[Wed May 15 05:59:59.411765 2024] [proxy_fcgi:error] [pid 960:tid 140715459860160] [client 10.15.48.10:0] AH01071: Got error 'PHP message: [2024-05-15T05:59:59+0200] [CRITICAL] There was an consistency error in the exported files  - please use the legacy export menu to troubleshoot {"context":"[object] (Centreon\\\\Domain\\\\MonitoringServer\\\\Exception\\\\MonitoringServerException(code: 0): There was an consistency error in the exported files  - please use the legacy export menu to troubleshoot at /usr/share/centreon/src/Centreon/Application/Controller/Configuration/MonitoringServerController.php:230)"}\n'
```

Sorry for my English.

**Comment by Nyxtorm** [comment]
So, I haven't touched anything since I opened my issue... and now it works. I can't explain what fixed my problem.

**Comment by Robson-DB** [comment]
Good afternoon
I find myself with the same problem.
Before I resumed all the services (Cenngine, CBD, Gorgoned, Apache2, PHP8.1-FPM, Centeon, Mariadb and Centers) and work again, but right now restarting it does not work again.
The error is identical to that reported by our colleague.
My server is running:
Pretty_Name = "Debian Gnu/Linux 12 (Bookworm)"
Name = "Debian Gnu/Linux"
Version_id = "12"
Version = "12 (Bookworm)"
Version_codename = Bookworm
ID = Debian

Follows data:

![image](https://github.com/user-attachments/assets/c3dd6f75-b55a-409e-9698-ceaeadffeeda)
