### ISSUE TITLE
[2.7.0] - only services in 1st host group are generated

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#4081]
Hello,

After upgrading from 2.6.x to 2.7.0, services by host group were still there.
Since I pushed a new configuration, most of them are missing.
I can see them in config, edit them, but when pushing configuration to poller, only a few are generated.

I tried to disable some of them hoping one was blocking, without clue.

Also tried:
-Add a working service host group to another host group : not in generated config
-Add a non working service host group to an existing host group that have services: not in generated config

How to debug config file generation ? I found Generate() method in code, but didn't find anything to get more debug info.

**Comment by Eldertoon** [comment]
Hi,

I confirm this problem and this is a major issue ! This can't wait Centreon-2.8, right now my system is out because of the disappearance of a lot of my services. Furthermore : it is totally stealth, no error anywhere.

Regards,

**Comment by Eldertoon** [comment]
I have no clue how / why, but I solved this issue by clearing in each host the Parent & Child informations (it seems clearing only one of them also solve this).

I confirm this is a major bug for me, but this workaround is acceptable as I don't use anymore a mapping tool

**Comment by mathieuchateau** [comment]
@eldertoon: I tried as I have relation too, but didn't solve yet this issue.

I confirm it's also a major pain for me, as I only use service by host group

**Comment by Eldertoon** [comment]
@mathieuchateau : I need to clarify, I solved my issue now on my hosts by editing them one by one. In order to verify my work, I first massively assigned one host as parent for every other host and deleted every child. Then I modified by hand one by hand my hosts since massively editing doesn't solve the issue. To conclude I applied my action on every host, I verified that table host_hostparent_relation is empty.

My conclusion : it is maybe not editing child / parent relation that solve the issue but maybe editing something and then saving each host config.

**Comment by mathieuchateau** [comment]
Now it's better.
After removing parent relation for one host, this host blocked configuration because template (generic) was lost.

Thanks a lot @Eldertoon  :)

**Comment by mathieuchateau** [comment]
I removed all host/parent relation on my side + 1 host that lost template
in this action.



Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2016-01-11 15:33 GMT+01:00 Eldertoon <notifications@github.com>:

**Comment by mathieuchateau** [comment]
@Eldertoon  I do have more services generated in config, but not all of them. Did you get 100% back ?

**Comment by Eldertoon** [comment]
@mathieuchateau : I hope so, but I have no way to verify. The one services I noticed missing are back, but I have +280 hosts configured, so only time will tell me if it's OK

**Comment by Eldertoon** [comment]
@mathieuchateau : OK, I found some others missing ...

**Comment by Eldertoon** [comment]
Correction : some that were working now are missing

**Comment by Eldertoon** [comment]
@mathieuchateau : Of all I looked for, it seems that only the checks of one hostgroup assigned to a host is active. If the host have more than one hostgroup, it is random : only one of them will be active. Can you confirm ?

**Comment by mathieuchateau** [comment]
@Eldertoon yes I confirm it only deploy service from 1st hostgroup. Service for others host group are skipped for each host. Incredible!

**Comment by mathieuchateau** [comment]
To reproduce :

- Create host which is member of 2 host group
- Create 1 service for each host group (in services by hostgroup)
- Deploy config to poller

Only service for 1st host group is checked. Other one is not in config.

**Comment by garnier-quentin** [comment]
Have you tested it with centreon 2.7.1 ?

**Comment by mathieuchateau** [comment]
just right now, and it works again :)
I just doubled my monitored services count.

Checking deeper but looks promising!

**Comment by garnier-quentin** [comment]
Great! We wait for your complete feedback.

**Comment by mathieuchateau** [comment]
I do confirm this issue is closed after updating to centreon 2.7.1 and pushing configuration to poller.
Even adding back parent/host relation keep everything working.

Great news after a nightmare :)
