### ISSUE TITLE
Reload/restart command must work with System V and Systemd

### ISSUE THREAD

**Issue by leoncx** [centreon/centreon#4082]
The relaod and restart command for Centreon Broker and Centreon Engine must work both init system, System V and Systemd.

The command for SystemV are like

```
service cbd restart
```

The command for Systemd are like 

```
systemctl restart cbd
```

You can detect if the linux system is a systemd, you can check if the directory /run/systemd/system exists.

This test must be used in installation for detect the init service.

**Comment by lpinsivy** [comment]
@leoncx apply in Centreon 2.7.3 ?

Can you close this ticket ?
