### ISSUE TITLE
Useless texte field in host extended information with centreon 2.7 

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4086]
Hello,

Is the texte field "Comments" in the tab "Host extended infos" of the host configuration still used in centreon 2.7 ?

When i add a comment in this page, the comment is not visible in the monitoring page.
![selection_032](https://cloud.githubusercontent.com/assets/13485588/12267830/44d5bd88-b94a-11e5-89cc-c152a24a2eb0.png)

But when i add a comment through the page monitoring page it seems to work:
![selection_033](https://cloud.githubusercontent.com/assets/13485588/12267910/b2abea58-b94a-11e5-9dc1-85d534812f75.png)

**Comment by querwin** [comment]
Hello,

Comment in host configuration is not the same thing as in host monitoring. If you add an host comment in the monitoring, you'll see it in the comment tab of the host status detail.

Comment in configuration will not be seen here

**Comment by querwin** [comment]
ok for you ?

**Comment by tseegers** [comment]
Ok i understand so there is two different comments, thank you for this respond !
