### ISSUE TITLE
CES - old nagios plugin

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#4087]
Hello,

On a 3.2 CES, I found that nagios-plugins package is not from epel source, and are quite older than normal centos 6.7.

From CES:

``` shell
# yum list installed | grep nagios
nagios-plugins.x86_64   1.4.16-7.el6       @anaconda-CES-201309230102.x86_64/6.6

```

From a standard centos 6.7:

``` shell
# yum list installed | grep nagios
nagios-common.x86_64            3.5.1-1.el6            @epel
```

Do you know where this @anaconda-CES-201309230102.x86_64/6.6 is coming from ?

That create discrepancies, like for check_procs that is missing -T argument in old version.

**Comment by julienmathis** [comment]
@leoncx : do you have information ?

**Comment by directict** [comment]
Hello, @julienmathis @leoncx @mathieuchateau we have exact the same issue, we have everything updated, our YUM wants to update nagios nagios-plugins.x86_64   1.4.16-7.el6       @anaconda-CES-201309230102.x86_64/6.6 and it fails with:
rror: Package: nagios-plugins-nsc-1.4.16-7.el6.x86_64 (@anaconda-CES-201309230102.x86_64/6.6)
           Requires: nagios-plugins = 1.4.16-7.el6
           Removing: nagios-plugins-1.4.16-7.el6.x86_64 (@anaconda-CES-201309230102.x86_64/6.6)
               nagios-plugins = 1.4.16-7.el6
           Updated By: nagios-plugins-2.0.3-3.el6.x86_64 (epel)
               nagios-plugins = 2.0.3-3.el6
           Available: nagios-plugins-1.4.15-3.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.15-3.el6
           Available: nagios-plugins-1.4.16-4.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.16-4.el6
           Available: nagios-plugins-1.4.16-6.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.16-6.el6
Error: Package: nagios-plugins-udp-1.4.16-7.el6.x86_64 (@anaconda-CES-201309230102.x86_64/6.6)
           Requires: nagios-plugins = 1.4.16-7.el6
           Removing: nagios-plugins-1.4.16-7.el6.x86_64 (@anaconda-CES-201309230102.x86_64/6.6)
               nagios-plugins = 1.4.16-7.el6
           Updated By: nagios-plugins-2.0.3-3.el6.x86_64 (epel)
               nagios-plugins = 2.0.3-3.el6
           Available: nagios-plugins-1.4.15-3.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.15-3.el6
           Available: nagios-plugins-1.4.16-4.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.16-4.el6
           Available: nagios-plugins-1.4.16-6.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.16-6.el6

**Comment by directict** [comment]
Hello, @julienmathis @leoncx @mathieuchateau we have exact the same issue, we have everything updated, our YUM wants to update nagios nagios-plugins.x86_64   1.4.16-7.el6       @anaconda-CES-201309230102.x86_64/6.6 and it fails with:
rror: Package: nagios-plugins-nsc-1.4.16-7.el6.x86_64 (@anaconda-CES-201309230102.x86_64/6.6)
           Requires: nagios-plugins = 1.4.16-7.el6
           Removing: nagios-plugins-1.4.16-7.el6.x86_64 (@anaconda-CES-201309230102.x86_64/6.6)
               nagios-plugins = 1.4.16-7.el6
           Updated By: nagios-plugins-2.0.3-3.el6.x86_64 (epel)
               nagios-plugins = 2.0.3-3.el6
           Available: nagios-plugins-1.4.15-3.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.15-3.el6
           Available: nagios-plugins-1.4.16-4.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.16-4.el6
           Available: nagios-plugins-1.4.16-6.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.16-6.el6
Error: Package: nagios-plugins-udp-1.4.16-7.el6.x86_64 (@anaconda-CES-201309230102.x86_64/6.6)
           Requires: nagios-plugins = 1.4.16-7.el6
           Removing: nagios-plugins-1.4.16-7.el6.x86_64 (@anaconda-CES-201309230102.x86_64/6.6)
               nagios-plugins = 1.4.16-7.el6
           Updated By: nagios-plugins-2.0.3-3.el6.x86_64 (epel)
               nagios-plugins = 2.0.3-3.el6
           Available: nagios-plugins-1.4.15-3.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.15-3.el6
           Available: nagios-plugins-1.4.16-4.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.16-4.el6
           Available: nagios-plugins-1.4.16-6.el6.x86_64 (ces-standard-stable-deps)
               nagios-plugins = 1.4.16-6.el6

**Comment by nogomes** [comment]
Hi

The same here. We need the epel-release repo to install open-vm-tools, but when the repo is enabled, there's a conflict with nagios-plugins when doing a 'yum update'

Regards

Norbert

**Comment by julienmathis** [comment]
Yes Centreon Repo is not compatible with EPEL.
