### ISSUE TITLE
[2.7.1] Decentralized Poller Statistics

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4089]
Dear Team,

In the last version we notice a bug in the display statistics page. (Home  >  Poller Statistics)

Statistics are OK for our central poller but not for our remote poller : empty screen (please see attached)

Thanks
![capture-centreon - it network monitoring - google chrome-1](https://cloud.githubusercontent.com/assets/5636906/12291756/6bf915be-b9e9-11e5-9bc0-724e0ebc2424.png)

**Comment by lpinsivy** [comment]
@gslongo can you confirm that this issue is fixed by  #4104 ?

Regards,

**Comment by gslongo** [comment]
Dear Laurent, 

Seems to be OK with the updated 2.7.3 version.

Thanks for the work

**Comment by julienmathis** [comment]
Thanks !

**Comment by kikoololstyle** [comment]
Hi, i got the same problem, but with Centreon Web 2.7.5 : 
- Central : OK
- Other poller :  empty content
