### ISSUE TITLE
[2.7] Export des pollers 1 par 1 

### ISSUE THREAD

**Issue by pateretou** [centreon/centreon#4091]
Hello,

j'ai l'impression qu'on ne peut plus faire un export de tous les pollers mais qu'on doit se les faire un par un avec la version 2.7.x

j'ai loupé une étape?

merci les gars :)

**Comment by Sims24** [comment]
Hi, 

@leoncx don't you think that something could happen before Centreon 2.8 ? I think this is really important for large setup...

Thanks

**Comment by pateretou** [comment]
(ca ressemble plus a une regression qu'un enhancement quand meme :) )

**Comment by lpinsivy** [comment]
Réintroduit en Centreon 2.7.3
