### ISSUE TITLE
Problème centcore.cmd

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4095]
Bonjour,

Il y a un petit oublie dans le fichier moveFiles.php :

    $centcore_pipe = "/var/lib/centreon/centcore.cmd";
	if ($centcore_pipe == "/centcore.cmd") {
		$centcore_pipe = "/var/lib/centreon/centcore.cmd";
	}

-- > Normalement :

    /*
     * Centcore pipe path
     */
    if (defined("_CENTREON_VARLIB_")) {
        $centcore_pipe = _CENTREON_VARLIB_."/centcore.cmd";
    } else {
        $centcore_pipe = "/var/lib/centreon/centcore.cmd";
    }

**Comment by Tpo76** [comment]
OK
