### ISSUE TITLE
Admins get deleted from ACL-groups (2.7)

### ISSUE THREAD

**Issue by oyvjel** [centreon/centreon#4097]
When editing Access Groups admin accounts are not included in the "Availabe" and "Selected" lists for Linked Contacts. Thus saving a change will delete admin users from the group.

Temporarily removing admin rights on users the risk leaving the users without any access.

**Comment by querwin** [comment]
Hello,

Centreon administrators are not subject to ACLs (property of the contact).

So I think this a normal behavior.

Uf you want to apply ACL to an user, this user can't have admin right.
