### ISSUE TITLE
Elévation de privilèges pour un utilisateur soumis à des ACL

### ISSUE THREAD

**Issue by florentfillion** [centreon/centreon#4098]
J'ai configuré des ACL de manières à ce que des utilisateurs ne possèdent qu'un accès en lecture seule à la rubrique Configuration --> Hôtes (via les ACL concernant l'accès aux menus).

Lorsqu'un utilisateur accède à cette rubrique normalement en cliquant sur "Configuration" puis sur "Hôtes", les options pour ajouter des hôtes, les supprimer, les dupliquer, etc...   n'apparaissent pas (ce qui est normal car l'utilisateur est en lecture seule).

En revanche si on clic deux fois de suite (double clic ou non) sur "Configuration" (depuis n'importe quel menu), on arrive également sur la page "Hôtes" mais cette fois les options apparaissent ce qui peut donc permettre à l'utilisateur de modifier à volonté les hôtes (ajout, suppression, etc...).
Pour les deux situations ci-dessus, la page correspondant à la rubrique "Hôtes" n'a pas le même id dans l'URL.

Cela fonctionne sur centreon 2.6.* et 2.7.*

**Comment by Shini31** [comment]
Egalement présent en 2.7.1

**Comment by Tpo76** [comment]
OK
