### ISSUE TITLE
ACL non prise en compte

### ISSUE THREAD

**Issue by florentfillion** [centreon/centreon#4100]
J'ai configuré une ACL qui autorise uniquement un accès en lecture seule à la rubrique : 
Configuration --> Commandes --> Connecteurs

Lorsqu'un utilisateur soumis à cette ACL se rend à cet endroit, les options permettant d'ajouter, de supprimer et de dupliquer sont toujours présentes en dessous de la listes des connecteurs.

Fonctionne sur centreon 2.6.* et 2.7.*

**Comment by florentfillion** [comment]
Fonctionne sur centreon 2.6.* et 2.7.*

**Comment by julienmathis** [comment]
refs 68129c8 & a81c2bd
