### ISSUE TITLE
Problème de Path

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4101]
Bonjour,

Dans le fichier brokerPerformance.php, il serait mieux que le chemin de la variable $statsfile soit plus dynamique. par exemple en ajoutant : 

require_once realpath(dirname(__FILE__) . "/../../../../config/centreon.config.php");

if (defined("_CENTREON_VARLIB_")) {
 $statsfile = _CENTREON_VARLIB_.'/centreon/broker-stats/broker-stats-' . $selectedPoller . '.dat';
} else {
 $statsfile = '/var/lib/centreon/broker-stats/broker-stats-' . $selectedPoller . '.dat';
}

**Comment by Tpo76** [comment]
Link with #4104 
OK
