### ISSUE TITLE
Can not acknowledge or disable checks on remote pollers. (2.7.1)

### ISSUE THREAD

**Issue by oyvjel** [centreon/centreon#4102]
In a setup with several remote pollers and a local poller running on the CES-server I can only acknowledge problems or enable/disable checks on the local poller. I get no feedback in the remote poller case. Where to look for error-log?

Pushing configs and monitoring state and performance i OK.

**Comment by jben94** [comment]
Bonjour,

J'ai le même problème, il y a un problème dans le fichier centcore.pm lié au changement de configuration du broker. Partie du code source qui pose problème : 


###########################################
## Get a instant copy of the broker stat
## fifo
#
sub getBrokerStats($) {
    my $self = shift;
    my ($poller_id) = @_;
    my $port = "";
    my $statPipe = "/tmp/.centreon-broker-stats.dat";
    my $destFile = $self->{centreon_config}->{VarLib} . "/broker-stats";
    my $server_info;
    my ($lerror, $stdout, $cmd);

    # Check Cache directory
    if (!-d $destFile) {
        $self->{logger}->writeLogInfo("Create data directory for broker-stats: $destFile");
        mkpath($destFile);
    }

    my ($status, $sth) = $self->{centreon_dbc}->query("SELECT cbi.config_value FROM cfg_centreonbroker_info as cbi, cfg_centreonbroker as cb WHERE cb.config_id = cbi.config_id AND cbi.config_group = 'stats' AND cbi.config_key = 'fifo' AND cb.ns_nagios_server = '".$poller_id."'");
    if ($status == -1) {
        $self->{logger}->writeLogError("Error poller broker pipe");
        return -1;
    }
    while (my $data = $sth->fetchrow_hashref()) {

        # Get poller Configuration
        $server_info = $self->getServerConfig($poller_id);
        $port = checkSSHPort($server_info->{ssh_port});

        # Copy the stat file into a buffer

        $cmd = "$self->{ssh} -q $server_info->{ns_ip_address} -p $port 'cat \"$data->{config_value}\" > $statPipe'";
        ($lerror, $stdout) = centreon::common::misc::backtick(command => $cmd,
                                                              logger => $self->{logger},
                                                              timeout => $self->{cmd_timeout}
                                                              );

La requête SQL ne retourne rien !

**Comment by oyvjel** [comment]
Found http://forum.centreon.com/forum/centreon-use/distributed-monitoring/14433-acknowledge-external-command-to-poller-is-not-working

/var/lib/centreon-engine/rw/centengine.cmd is a named pipe on central but an ordinary file on the remote pollers.

Tried the following on a poller:
<pre>
rm centengine.cmd 
mkfifo  centengine.cmd
chown centreon-engine.centreon-engine centengine.cmd
/etc/init.d/centengine restart
</pre>

Can still not acknowledge.

Rebooted the poller.

The named pipe goes away.

Tried another ack at the CES. A new ordinary file is created on the remote poller with content:
<pre>
[1452863653] ACKNOWLEDGE_HOST_PROBLEM;NetAppBraveTern1;2;0;1;oyvjel;Acknowledged by oyvjel
[1452863653] SCHEDULE_FORCED_HOST_CHECK;NetAppBraveTern1;1452863653
[1452863653] ACKNOWLEDGE_SVC_PROBLEM;NetAppBraveTern1;Check_Ping_boat;2;0;1;oyvjel;Acknowledged by oyvjel
[1452863653] SCHEDULE_FORCED_SVC_CHECK;NetAppBraveTern1;Check_Ping_boat;1452863653
</pre>

**Comment by oyvjel** [comment]
The poller was installed from ISO v 2.6.6 and later upgraded to 2.7.1 ( yum)

**Comment by oyvjel** [comment]
Config:

In:
Configuration  >  Pollers  >  Engine configuration
For remotePoller,Files tab
...
External Commands
 External Command Check Option:	Yes
 External Command Check Interval	: 1s
 External Command File: 	/var/lib/centreon-engine/rw/centengine.cmd
 External Command Buffer Slots:	4

The working local poller has Buffer Slots <blank>
Tried to unset Buffer Slots on remote. 

No success.

**Comment by oyvjel** [comment]
Rebooting. 
Pipe is deleted again.
Ack creates a file but with different owner:
# ls -la
total 12
drwxrwxr-x. 2 centreon-engine centreon-engine 4096 2016-01-15 16:04 .
drwxr-xr-x. 4 centreon-engine centreon-engine 4096 2015-11-25 16:02 ..
-rw-rw-r--  1 centreon        centreon         349 2016-01-15 16:04 centengine.cmd

centreon or centreon-engine makes no difference.

**Comment by oyvjel** [comment]
Solved!
Added Event broker directive = /usr/lib64/centreon-engine/externalcmd.so
in Configuration  >  Pollers  >  Engine configuration, Data tab, syncked config files and  manually stopped and started centengine on remote poller.
