### ISSUE TITLE
Problème statistique Poller

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4104]
Bonjour,

J'ai un problème sur la remonté des statistiques de mes pollers, il y a un problème dans le fichier centcore.pm lié au changement de configuration du broker. 

Partie du code source qui pose problème : 

 ###########################################
 ## Get a instant copy of the broker stat
 ## fifo
 #
sub getBrokerStats($) {
    my $self = shift;
    my ($poller_id) = @_;
    my $port = "";
    my $statPipe = "/tmp/.centreon-broker-stats.dat";
    my $destFile = $self->{centreon_config}->{VarLib} . "/broker-stats";
    my $server_info;
    my ($lerror, $stdout, $cmd);

    # Check Cache directory
    if (!-d $destFile) {
        $self->{logger}->writeLogInfo("Create data directory for broker-stats: $destFile");
        mkpath($destFile);
    }

    my ($status, $sth) = $self->{centreon_dbc}->query("SELECT cbi.config_value FROM cfg_centreonbroker_info as cbi, cfg_centreonbroker as cb WHERE cb.config_id = cbi.config_id AND cbi.config_group = 'stats' AND cbi.config_key = 'fifo' AND cb.ns_nagios_server = '".$poller_id."'");
    if ($status == -1) {
        $self->{logger}->writeLogError("Error poller broker pipe");
        return -1;
    }
    while (my $data = $sth->fetchrow_hashref()) {

        # Get poller Configuration
        $server_info = $self->getServerConfig($poller_id);
        $port = checkSSHPort($server_info->{ssh_port});

        # Copy the stat file into a buffer

        $cmd = "$self->{ssh} -q $server_info->{ns_ip_address} -p $port 'cat \"$data->{config_value}\" > $statPipe'";
        ($lerror, $stdout) = centreon::common::misc::backtick(command => $cmd,
                                                              logger => $self->{logger},
                                                              timeout => $self->{cmd_timeout}
                                                              );

La requête SQL ne retourne plus rien ! Car la partie de configuration du broker depuis l'interface web a été retirée.

**Comment by gslongo** [comment]
@jben94 This is same issue as https://github.com/centreon/centreon/issues/4089 ?

**Comment by jben94** [comment]
Bonjour,

Proposition de contournement en attente du fixe.

 #    my ($status, $sth) = $self->{centreon_dbc}->query("SELECT cbi.config_value FROM cfg_centreonbroker_info as cbi, cfg_centreonbroker as cb WHERE cb.config_id = cbi.config_id AND cbi.config_group = 'stats' AND cbi.config_key = 'fifo' AND cb.ns_nagios_server = '".$poller_id."'");
    my ($status, $sth) = $self->{centreon_dbc}->query("SELECT DISTINCT config_name  FROM cfg_centreonbroker_info as cbi, cfg_centreonbroker as cb WHERE cb.config_id = cbi.config_id AND cb.ns_nagios_server = '".$poller_id."' LIMIT 1");


 #       $cmd = "$self->{ssh} -q $server_info->{ns_ip_address} -p $port 'cat \"$data->{config_value}\" > $statPipe'";
        $cmd = "$self->{ssh} -q $server_info->{ns_ip_address} -p $port 'cat \"".$self->{centreon_config}->{VarLib}."/retention/".$data->{config_name}.".stats\" > $statPipe'";

 #           $self->{logger}->writeLogError("Could not read pipe ".$data->{config_value}." on poller ".$server_info->{ns_ip_address});
            $self->{logger}->writeLogError("Could not read pipe ".$data->{config_name}." on poller ".$server_info->{ns_ip_address});

**Comment by jben94** [comment]
Bonjour,

Depuis ma petite modification, je récupère bien les statistiques par contre je remarque qu'il manque des statistiques sur le central. 
Je n'ai que les statistiques du broker "central-module", donc il me manque " central-broker" et "central-rdd".

**Comment by kduret** [comment]
Fixed here : d548e75d22f8d2dbfbb00b8458f00057119ae31d

**Comment by Tpo76** [comment]
Already works on Centreon-2.7.1 you need to enable collection of your poller in menu Administration -> Parameters -> CentCore and activate "Enable Broker Statistics Collection".

**Comment by Tpo76** [comment]
OK
