### ISSUE TITLE
inheritance service macro

### ISSUE THREAD

**Issue by dutangp** [centreon/centreon#4108]
Hi,

I got a problem when I upgrade tocentreon 2.7. When I need to modify an existing (IP address for example), the change is not submit. I notice that when I remove my inheritance service macro, the submit works fine.

Best

PS: too bad that the Tactical Overview widget is not complete as before, Unhandled Service/Host problems (last 100) (it's a big problem for our monitoring without all information)

**Comment by lpinsivy** [comment]
Hi,

Can you confirm that this issue is still present with Centreon web 2.7.3 ?

Regards,

ps: you can complete tactical overview widget with hosts and services widgets using filters by items non OK

**Comment by dutangp** [comment]
Hi,

I just update my centreon to 2.7.3 and this issue is still present.

Best,

On Fri, Mar 25, 2016 at 4:40 PM, Laurent Pinsivy <notifications@github.com>
wrote:

> Hi,
>
> Can you confirm that this issue is still present with Centreon web 2.7.3 ?
>
> Regards,
>
> ps: you can complete tactical overview widget with hosts and services
> widgets using filters by items non OK
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/centreon/centreon/issues/4108#issuecomment-201337429>
>



-- 
Pierre
06 52 08 00 52

<http://www.linkedin.com/in/pedutang>

**Comment by querwin** [comment]
Hello,

Do you have some apache logs when trying to save a form ?

Regards,

**Comment by julienmathis** [comment]
no log received.
