### ISSUE TITLE
Add warning when deactivate or delete a object used in configuration

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#411]
---

Author Name: **Maximilien Bersoult** (Maximilien Bersoult)
Original Redmine Issue: 4180, https://forge.centreon.com/issues/4180
Original Date: 2013-02-05

---

In configuration, we cannot deactivate or delete an object used by another object.

The list of objects is :
* Service template
* Host template
* Command
* Host (related to Meta Service)
* Service (related to Meta Service)
* Timeperiod
* Connector

**Comment by julienmathis** [comment]
Can't understand
