### ISSUE TITLE
UI doesn't display the good limit of pagination

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4110]
Hello,

The pagination works in Centreon 2.7.1 but the limit of page isn't really displayed.
In UI parameters (Adminisration --> Parameters), I set 500 for "Limit per page for Monitoring", so in the monitoring page I see 500 services but we can only choose 10 to 100 objects in the list.
See attachements.

Regards,
![monitoring](https://cloud.githubusercontent.com/assets/11076322/12386775/14427792-bdc8-11e5-81ad-225f49e7e128.JPG)
![parameters](https://cloud.githubusercontent.com/assets/11076322/12386774/143e51bc-bdc8-11e5-941e-dea087a83964.JPG)

**Comment by julienmathis** [comment]
Ohhh Yeah ! Strange.

Thanks
