### ISSUE TITLE
LDAP authentication failed when password contains accent

### ISSUE THREAD

**Issue by smutel** [centreon/centreon#4112]
Hello,

Most of the issue is describe in title. When the user set his password with some letters with accent, for example "é" or "è", the authentication does not work correctly.
Centreon consider the password as **wrong**:

`2016-01-18 15:52|-1|0|0|Connexion = CN=XXXX :: Invalid credentials`
`2016-01-18 15:52|-1|0|0|LDAP AUTH : LDAP don't like you, sorry`
`2016-01-18 15:52|-1|0|0|LDAP AUTH : Update user DN for user XXXX`

Perhaps it is due to encoding (UTF-8/Windows charset) ...

Regards.

**Comment by kadrika** [comment]
Hi,

Do you have ETA when this bug will be fixed or the version in what it will be fixed?

**Comment by julienmathis** [comment]
Which version of Centreon do you use ?

**Comment by leoncx** [comment]
Hello,

Can you tell us your client OS, client browser and client keyboard layout ?

Thanks.

**Comment by lpinsivy** [comment]
@smutel still present in Centreon web 2.8.5 ?
