### ISSUE TITLE
Duplicate Centreon Engine Configuration

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#4113]
When you duplicate an existing engine configuration the parameter are not the same as the original configuration, like "Temp directory" in files part

In default engine configuration this field is empty, but when you duplicate this configuration this field is fill by "/tmp".

Furthermore, some of this parameter create warning when you generate the configuration, like tmp_dir was ignored or p1_file was ignored.

Centreon 2.7.1
Engine 1.5.0
Broker 2.11.0

**Comment by julienmathis** [comment]
Fixed in 2.7.3
