### ISSUE TITLE
 Error when generate config file with CLAPI

### ISSUE THREAD

**Issue by Malikcg** [centreon/centreon#4114]
Bonjour à tous,

Je suis sûr :
Centreon 2.7, Centos 6.7 et centengine 1.5

J'ai écrit un script permettant de vérifier dans la base Oracle de mon Vcenter si les hotes présent sur mon Centreon correspondent.
Si un hôte est sur le vcenter mais pas dans Centreon il est ajouté via CLAPI
Si l'hote est présent sur Centreon mais pas sur le Vcenter il est supprimé ( Vcenter est la référence en gros)
Tout marche bien mis à part que je doit regénérer les fichiers de config a la main via l'interface web et redémarrer le poller moi meme.

J'ai absolument besoin que cela soit automatisé.
C'est pourquoi j'ai voulu utiliser la commande CLAPI APPLYCFG à la fin de mon script. Voici l'erreur que mon script retourne quand je le lance :

PHP Warning: require(../../../include/configuration/configGenerate/genCGICFG.php): failed to open stream: No such file or directory in /usr/share/centreon/www/modules/centreon-clapi/core/class/centreon.Config.Poller.class.php on line 485
PHP Fatal error: require(): Failed opening required '../../../include/configuration/configGenerate/genCGICFG.php' (include_path='/usr/share/centreon/www/modules/centreon-clapi/core/lib:/usr/share/centreon/www/modules/centreon-clapi/core/class:.:/usr/share/pear:/usr/share/php') in /usr/share/centreon/www/modules/centreon-clapi/core/class/centreon.Config.Poller.class.php on line 485

Avez vous une idée d'où cela vient ?

Hello everybody,

In my organisation we have :
Centreon 2.7, Centos 6.7 et centengine 1.5

I made a synchro-script between my Vcenter and my Centreon.
My script work but i have to generate config file and restart the poller with my bear hands. That's not what i want.

That's why i wanted to use CLAPI APPLYCFG command at the end of the script. But when i run this command this error occure :

PHP Warning: require(../../../include/configuration/configGenerate/genCGICFG.php): failed to open stream: No such file or directory in /usr/share/centreon/www/modules/centreon-clapi/core/class/centreon.Config.Poller.class.php on line 485
PHP Fatal error: require(): Failed opening required '../../../include/configuration/configGenerate/genCGICFG.php' (include_path='/usr/share/centreon/www/modules/centreon-clapi/core/lib:/usr/share/centreon/www/modules/centreon-clapi/core/class:.:/usr/share/pear:/usr/share/php') in /usr/share/centreon/www/modules/centreon-clapi/core/class/centreon.Config.Poller.class.php on line 485

Did you have any idea on how fix it ?

**Comment by querwin** [comment]
Bonjour,

Il s'agit d'une CES ou d'une installation par les sources ?
Est ce une mise à jour depuis 2.6.x ou une fresh install ?

**Comment by Malikcg** [comment]
Bonjour,

il s'agit d'une fresh install de CES 3.3

2016-01-19 15:50 GMT+01:00 querwin <notifications@github.com>:

**Comment by kduret** [comment]
Bonjour,

CLAPI est maintenant intégré à Centreon. Il ne faut donc plus passer par le module pour l'utiliser (vous pouvez le désinstaller).

Le binaire est maintenant accessible par le chemin suivant : 
/usr/share/centreon/bin/centreon
