### ISSUE TITLE
[2.7.1] Depency page select2 display

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4116]
Hi, 

As some other pages before (see https://github.com/centreon/centreon/issues/4042 for similar issue), if I create a dependency and fill my "service" and "dependent service" boxes, I save and come back in the page and can't see my previous selection. 

EDIT 
In other words, if I defined 1000 services dependent on one other service. If I want to add another relation I need to select again my 1000 services and add the new one =) 

Thanks

**Comment by kduret** [comment]
Same thing for services relation in escalation

**Comment by Sims24** [comment]
Thanks dude ;)

**Comment by Tpo76** [comment]
OK
