### ISSUE TITLE
Generation du poller non visible via ACL

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon#4118]
Bonjour,

J'essaye de reproduire les ACL que j'avais sur un Centreon 2.6.6 vers un 2.7 mais certaines choses ne fonctionnent pas comme je voudrais.

Actuellement je voudrais donner la possibilité à un groupe de générer le poller.
Pour ça, dans les ACL, j'ai ajouté :

* Configuration > Pollers > Generate (coché) et Pollers (coché)

L'utilisateur voit bien le menu Configuration > Pollers mais le poller Central n'est pas affiché. Donc impossible de sélectionner l'icone pour régénérer la configuration.

Une idée ?

Merci.

**Comment by dooko** [comment]
https://github.com/centreon/centreon/issues/4037
