### ISSUE TITLE
ACL 2.7.2: Cannot use tab on Centengine configuration

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4121]
hi,
I have configured the ACL like this:
![cap 2016-01-19 a 23 17 28](https://cloud.githubusercontent.com/assets/10330979/12433707/ef52e962-bf02-11e5-830f-91d7af4ed297.png)

And the user cannot read the tabs on the following page:
![cap 2016-01-19 a 23 17 36](https://cloud.githubusercontent.com/assets/10330979/12433715/fa965a34-bf02-11e5-9998-dc77d59ed2e8.png)

Thanks for your help

**Comment by lpinsivy** [comment]
Hi Matthieu,

Can you try to execute this SQL request in "centreon" database ?

INSERT INTO topology_JS(id_t_js, id_page, o, PathName_js, Init) VALUES(NULL, 60903, 'w', './include/common/javascript/changetab.js', 'initChangeTab');

Regards

**Comment by matthieu-robin** [comment]
Perfect Laurent! It works!
Thanks a lot

**Comment by lpinsivy** [comment]
Matthieu,

It's strange because this insert is present in full installation.

I added in upgrade from 2.7.2 to 2.7.3

Regards,
