### ISSUE TITLE
ACL 2.7.2: Configuration can be generated and poller configuration modified

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4122]
Hi,

Is it possible to ACLiser the capacity to generate the config and not change data on Poller config.
With this ACL, the user can reload/restart the poller, and he can modify the poller configuration.
Can we remove the possibility to change the poller configuration=

Thanks in advance.

**Comment by matthieu-robin** [comment]
2 printscreens to explain the issue.

Thanks

![cap 2016-03-02 a 09 32 21](https://cloud.githubusercontent.com/assets/10330979/13454808/c99309b4-e059-11e5-8f00-e032dd9bff01.png)
![cap 2016-03-02 a 09 32 29](https://cloud.githubusercontent.com/assets/10330979/13454809/ca685178-e059-11e5-846d-d08ccd286de3.png)

**Comment by julienmathis** [comment]
Fixed now

**Comment by julienmathis** [comment]
Les commits précédents ne sont pas bons. A corriger.
