### ISSUE TITLE
Usability bug - adding hosts to hostgroups

### ISSUE THREAD

**Issue by hecko** [centreon/centreon#4124]
In the 2.6 series there were two tables side-by-side where we could select and mass-add hosts to the hostgroup - we knew exactly which hosts are available to be added and which are already added. This is not possible to do in 2.7 - this is a complete disaster for our ops team. We have more than 4000 hosts in the config and the interface is simply not good enough here. This needs to change. The same goes to other parts of the configuration which have had the same configuration intrerface as described. Please fix this.

2.6 was really good in this specific case, 2.7 is much nicer, but a downgrade when we talk about usability :(

**Comment by maksimatveev** [comment]
@hecko agrees interface changes went friendliness is not good in this case.

**Comment by gslongo** [comment]
@hecko I agree to your request. But this is not only related to hostgroup, but to EVERY list

**Comment by julienmathis** [comment]
The next 2.7.3 will fix that very soon. This version is planned very shortly.
