### ISSUE TITLE
[2.7.0] Nothing to show on Reporting > Dashboard for non-admin users

### ISSUE THREAD

**Issue by dooko** [centreon/centreon#4125]
Non-admin users cannot see anything on the Dashboard of the Reporting menu.
Althought they have access to all hosts, hostgroups et servicegroups.

What do we miss ?

**Comment by dooko** [comment]
Hostgroups :
2016-01-20 17:11|0|0|DB Error: no such field QUERY : SELECT host_id, host_name FROM hostgroup, acl_res_group_relations, acl_resources_hg_relations WHERE hg_id = '420' AND acl_res_group_relations.acl_group_id  IN (32,22) AND acl_res_group_relations.acl_res_id = acl_resources_hg_relations.acl_res_id AND acl_resources_hg_relations.hg_hg_id = hostgroup.hg_id  ORDER BY LOWER(host_name)

**Comment by Laexar** [comment]
Hi,

It's a bug in the ACL, some SQL queries are not syntaxically correct and you can see it in /var/log/centreon/sql-error.log

You have some errors like : 
DB Error: syntax error QUERY : (SELECT service_id, service_description FROM ( SELECT s.service_id, s.service_description FROM host_service_relation hsr, host h, service s, centreon_storage.centreon_acl WHERE h.host_id = '6033' AND h.host_activate = '1' AND h.host_register = '1' AND h.host_id = hsr.host_host_id AND hsr.service_service_id = s.service_id AND s.service_activate = '1' AND centreon_storage.centreon_acl.host_id = h.host_id AND centreon_storage.centreon_acl.host_id = '6033' AND centreon_storage.centreon_acl.group_id IN ('32','22') UNION SELECT s.service_id, s.service_description FROM host h, hostgroup_relation hgr, service s, host_service_relation hsr, centreon_storage.centreon_acl WHERE h.host_id = '6033' AND h.host_activate = '1' AND h.host_register = '1' AND h.host_id = hgr.host_host_id AND hgr.hostgroup_hg_id = hsr.hostgroup_hg_idAND hsr.service_service_id = s.service_idAND centreon_storage.centreon_acl.host_id = h.host_id AND centreon_storage.centreon_acl.host_id = '6033' AND centreon_storage.centreon_acl.group_id IN ('32','22') ) as t  ORDER BY LOWER(service_description)

This one is for host reporting, and you'll have this other one for hostgroup : 
DB Error: no such field QUERY : SELECT host_id, host_name FROM hostgroup, acl_res_group_relations, acl_resources_hg_relations WHERE hg_id = '350' AND acl_res_group_relations.acl_group_id  IN (32,23) AND acl_res_group_relations.acl_res_id = acl_resources_hg_relations.acl_res_id AND acl_resources_hg_relations.hg_hg_id = hostgroup.hg_id  ORDER BY LOWER(host_name)

To fix these errors, it's quite easy, you'll just have to correct queries.
Open the file ~centreon/www/class/centreonACL.class.php, then edit the query line 2022 by removing the leading opening parenthesis and adding one space at the end of strings line 2042 and 2043, this will fix the first error.

For the second one, still in the same file, line 2140, add this : 
                . "AND hg_activate = '1' "
                . "AND host_activate = '1' "
                . "AND hostgroup_relation.hostgroup_hg_id = hostgroup.hg_id "
                . "AND hostgroup_relation.host_host_id = host.host_id "

Your $query should look like this now : 
    $query = $request['select'] . $request['fields'] . " "
    . "FROM hostgroup, hostgroup_relation, host, acl_res_group_relations, acl_resources_hg_relations "
                . "WHERE hg_id = '" . CentreonDB::escape($hg_id) . "' "
                . "AND hg_activate = '1' "
                . "AND host_activate = '1' "
                . "AND hostgroup_relation.hostgroup_hg_id = hostgroup.hg_id "
                . "AND hostgroup_relation.host_host_id = host.host_id "
                . "AND acl_res_group_relations.acl_group_id  IN (" . implode(',', $groupIds) . ") "
                . "AND acl_res_group_relations.acl_res_id = acl_resources_hg_relations.acl_res_id "
                . "AND acl_resources_hg_relations.hg_hg_id = hostgroup.hg_id ";

After that, things must be ok !
