### ISSUE TITLE
Mysql error when normal users try to access reporting->hostgroups.

### ISSUE THREAD

**Issue by postmannen** [centreon/centreon#4126]
Hi.

When a normal user tries to access Reporting->hosts information is displayed fine.
When a normal user tries to access Reporting->hostgroups no information is displayed for that hostgroup.
When an Administrator tries, both host and HG reports is displayed

The error below is shown in the sql log:
==> /usr/local/centreon/log/sql-error.log <==
2015-11-03 13:16|0|0|DB Error: no such field QUERY : SELECT host_id, host_name FROM hostgroup, acl_res_group_relations, acl_resources_hg_relations WHERE hg_id = '129' AND acl_res_group_relations.acl_group_id IN (2) AND acl_res_group_relations.acl_res_id = acl_resources_hg_relations.acl_res_id AND acl_resources_hg_relations.hg_hg_id = hostgroup.hg_id ORDER BY LOWER(host_name)

I've checked hostgroup, acl_res_group_relations, acl_resources_hg_relations, and none of those tables got a field called host_id.

If i log in with an account with administrator privileges set to 'yes' for Centreon Gui it works fine. The hostgroups reports data are shown as it should.

I've verified that the normal user have privileges to see all hostgroups within my acl's,

This used to work earlier, and I'm not sure when this happened, but to me it seems like it look for a field called host_id within those tables, but can't find it.
And since it works with an administrator account I don't think it's anything wrong with the mysql db.
Seems to me there is something wrong with the query when accessed by a normal user.

Any ideas what this might be ?

Currently running Centreon 2.6.6. Also had the problem running Centreon 2.6.5.

Regards
Bjorn Tore.

**Comment by postmannen** [comment]
Seems like same problem as
Dashboard by hostgroup doesn't work with ACL #4065

**Comment by julienmathis** [comment]
Fixed by #4129

**Comment by postmannen** [comment]
Thank you :)
