### ISSUE TITLE
Please add max_externalcommands_age ndo2db.cfg config option to centreon

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#413]
---

Author Name: **Adrian Fita** (Adrian Fita)
Original Redmine Issue: 2009, https://forge.centreon.com/issues/2009
Original Date: 2010-10-20

---

Hi.

I've noticed that Centreon doesn't allow to configure max_externalcommands_age for ndo2db.cfg. I configured this by hand in ndo2db.cfg, but it was overwritten when I regenerated the configs.

**Comment by julienmathis** [comment]
ndo is the past
