### ISSUE TITLE
[CLAPI] PHP warning with APPLYCFG command

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#4130]
These php warning appear when I can to apply configuration with centreon-calpi : 
PHP Warning: chown(): No such file or directory in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 430
PHP Warning: chgrp(): No such file or directory in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 431
PHP Warning: chown(): No such file or directory in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 444
PHP Warning: chgrp(): No such file or directory in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 445

**Comment by Tpo76** [comment]
OK
