### ISSUE TITLE
[2.7] ServiceGroups relation configuration seems to be broken

### ISSUE THREAD

**Issue by pateretou** [centreon/centreon#4132]
Hello,

on my centreon 2.7.1 it's appear the "service groups" configuration part is broken.
Not relation appear.

But I'm pretty sure theses relations exists because I can see it with clapi and in the monitoring/status details/services by servicegroup

Here a screenshot:

![image](https://cloud.githubusercontent.com/assets/5527345/12483913/d74a361c-c057-11e5-9c49-3110ce8f4744.png)

and the result with clapi :

> $ /usr/local/centreon/www/modules/centreon-clapi/core/centreon -u xxxx -p  xxxxx -o SG -a getservice -v "Processes-RT"
host id;host name;service id;service description
1466;QH_FBS;11801;QH-Process-FBS-CPU
1466;QH_FBS;11802;QH-Process-FBS-RUNNING
1466;QH_FBS;11803;QH-Process-FBS-TCPPORT
1703;QH_FH2;12994;QH-Process-FH2-CPU
1703;QH_FH2;13001;QH-Process-FH2-DBSNAPSHOT
1703;QH_FH2;12995;QH-Process-FH2-DB_REF
1703;QH_FH2;12996;QH-Process-FH2-DECODERSTATUS
1703;QH_FH2;38692;QH-Process-FH2-MCAST_SENDER

and the monitoring view

![image](https://cloud.githubusercontent.com/assets/5527345/12483855/8ef716be-c057-11e5-96c8-fc956f8447ed.png)

**Comment by pateretou** [comment]
Fix didn't solve the issue ...

**Comment by pateretou** [comment]
ok, work with 275fe857fe0e1586fc3267331804c72d5f8b8276

**Comment by pateretou** [comment]
Ok pardon c'estu n peu brouillon mais je viens de me rendre compte qu'en fait il y a le meme probleme sur le "linked service templates".
I lfaut faire le meme fix que el 4132 mais sur la partie "sg_tServices" dans le case

**Comment by Tpo76** [comment]
Same trouble works with "Host Group Services" and "Host Services" but not with "Service Templates".
