### ISSUE TITLE
[2.7.1] Missing GMT and UTC timezone

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4137]
Hello,

GMT and UTC timezone are missing in Administration, Host and Services parameters.

Regards.

**Comment by Dacchi** [comment]
It's normal as GMT and UTC are not timezones as timezones are geographic location.

If you want timezones close to GMT or UTC youu should use for example Africa/Abidjan as no DST is applied to this timezone.
Full list of UTC "compliant" timezones are listed here => https://en.wikipedia.org/wiki/UTC%C2%B100:00

Regards

**Comment by Shini31** [comment]
FYI.
https://secure.php.net/manual/en/timezones.others.php

**Comment by julienmathis** [comment]
@afouille : Alex can you validate that UTC and GMT are Posix ? 

Thanks in advance

**Comment by afouille** [comment]
Hi,

UTC and GMT are both valid zoneinfo from tzdatabase. Therefore, they are standard.

Regards,

**Comment by julienmathis** [comment]
Ok thanks
