### ISSUE TITLE
Delaying problem in Centreon

### ISSUE THREAD

**Issue by ectorr** [centreon/centreon#4138]
Hi all,

I have a Centreon with passive monitoring configured with 60 host and 150 services more or less. I have a problem because i have delay in the checks. At this moment, the check are of yesterdey (12 hours of delay). I have not latency in my Centreon. I have not problems of CPU, RAM or i/o. I check the mysql configuration and i tunning it, and i still have the problem.. I dont know what more can i do..
Any idea?

**Comment by julienmathis** [comment]
Do you use nsca ?

**Comment by ectorr** [comment]
Yes.

**Comment by julienmathis** [comment]
Do you still have the problem ?

**Comment by ectorr** [comment]
yes..

**Comment by Moujimouja** [comment]
Hi,

I think this issue can be closed due to its opened date.

Don't hesitate to contact us on Slack or re-open the issue if the problem is still here.

Have a nice day
