### ISSUE TITLE
Popup non mise à jour après changement description Host

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#4139]
Bonjour,

Je viens de me rendre compte d'un bug lorsque l'on change la description d'une machine. Celle-ci est bien appliquée PARTOUT, exceptée dans l'info bulle lorsque l'on survole le nom de la machine. L'info-bulle contient toujours l'ancienne description.

En cherchant dans la BDD, il s'agit de la table host de la base centreon_storage qui ne se met pas à jour. En changeant la valeur à la main, la modification est prise en compte immédiatement.

Je suis en version de Centreon 2.6.6.

Merci par avance.

**Comment by Hellnino18** [comment]
Hi,

Do you have an explanation for this bug plz?

**Comment by julienmathis** [comment]
As tu bien re-généré la configuration ? Seul broker fait cela et surtout pas toi, a la main... 

Je ne peux reproduire ton problème.
