### ISSUE TITLE
[2.7.1] php7 under debian 8

### ISSUE THREAD

**Issue by albundy83** [centreon/centreon#4140]
Hello,

as php 7 start to be available on debian 8 environment, I want to try to install it and test it against Centreon.
Unfortunately, my tests run out.
All what I have is a Database Error: Could not connect to database. on the web page.
In the log files, I don't see lots of error ...
Just a warning in apache error log : 

```
[Tue Jan 26 12:53:22.979767 2016] [:error] [pid 628] [client 10.0.0.1:43348] PHP Warning:  Declaration of CentreonAuthSSO::checkPassword($password, $token, $autoimport = false) should be compatible with CentreonAuth::checkPassword($password, $token = '', $autoimport = false) in /usr/local/centreon/www/class/centreonAuth.SSO.class.php on line 5
```

And another error in /var/log/centreon/centAcl.log : 

```
[2016-01-26 11:56:01] Database Error: Could not connect to database. <br />Please contact your administrator.
[2016-01-26 11:57:02] Database Error: Could not connect to database. <br />Please contact your administrator.
```

Is there a way to get more errors or trace ?

**Comment by george-vieira** [comment]
hey albundy, you got a build I can replicate it? I'll give a crack at it. centreon 2.7.1 is buggy as all.

**Comment by albundy83** [comment]
Hello,
it's not centreon 2.7.1 the problem (nor 2.7.0), it's php 7 that seems to be not compatible for moment.
But as I explain, I have no idea, where the problem comes from.
I have setup php 7.0 on my debian 8 using : 
https://www.dotdeb.org/2016/01/08/php-7-0-2-for-jessie/
For pear packages, I have installed them manually.

**Comment by albundy83** [comment]
Here how I have done to setup pear, it's just the commands / notes I have taken : 
Pear installation : 
```
wget http://pear.php.net/go-pear.phar
php go-pear.phar
```
Parameters I have set : 
```
 1. Installation base ($prefix)                   : /usr
 2. Temporary directory for processing            : /tmp/pear/temp
 3. Temporary directory for downloads             : /tmp/pear/install
 4. Binaries directory                            : /usr/bin
 5. PHP code directory ($php_dir)                 : /usr/share/php
 6. Documentation directory                       : /usr/share/php/doc
 7. Data directory                                : /usr/share/php/data
 8. User-modifiable configuration files directory : /usr/share/php/cfg
 9. Public Web Files directory                    : /usr/share/php/htdocs
10. System manual pages directory                 : /usr/man
11. Tests directory                               : /usr/share/php/test
12. Name of configuration file                    : /etc/pear/pear.conf
```

Packages installation : 
```
pear list
pear 
pear update-channels
pear upgrade-all
pear install Archive_Tar Archive_Zip-beta Auth_SASL Console_Getopt DB DB_DataObject DB_DataObject_FormBuilder Date HTML_Common HTML_QuickForm HTTP_Request Log MDB2 Net_Ping Net_SMTP Net_Socket Net_Traceroute-alpha Net_URL SOAP-beta Structures_Graph Validate-beta

wget --no-check-certificate https://de.pear.php.net/get/XML_RPC-1.5.5.tgz
pear install XML_RPC-1.5.5.tgz
```

Full list of necessary pear packages : 

PEAR                            1.4.9       1.9.4          OK
DB                              1.7.6       1.7.14         OK
DB_DataObject                   1.8.4       1.10.0         OK
DB_DataObject_FormBuilder       1.0.0RC4    1.0.2          OK
MDB2                            2.0.0       2.4.1          OK
Date                            1.4.6       1.4.7          OK
HTML_Common                     1.2.2       1.2.5          OK
HTML_QuickForm                  3.2.5       3.2.13         OK
HTML_QuickForm_advmultiselect   1.1.0       1.5.1          OK
HTML_Table                      1.6.1       1.8.3          OK
Archive_Tar                     1.1         1.3.1          OK
Auth_SASL                       1.0.1       1.0.6          OK
Console_Getopt                  1.2         1.2            OK
Validate                        0.6.2       0.8.5          OK
Log                             1.9.11      1.12.7         OK
Archive_Zip                     0.1.2       0.1.2          OK

**Comment by george-vieira** [comment]
What about PHP, did you use dotdeb install or source or what?


deb http://packages.dotdeb.org jessie all

deb-src http://packages.dotdeb.org jessie all

 
sorry, been busy haven’t had a chance yet. Stupid question but did you check php for mysql support too?

**Comment by albundy83** [comment]
Yes, here the php7.0 installation method I have used : 
```
echo 'deb http://packages.dotdeb.org jessie all
deb-src http://packages.dotdeb.org jessie all' > /etc/apt/sources.list.d/dotdeb-php70.list

wget -qO - https://www.dotdeb.org/dotdeb.gpg | apt-key add -
apt-get update
apt-get install libapache2-mod-php7.0 php7.0 php7.0-cli php7.0-common php7.0-gd php7.0-intl php7.0-json php7.0-ldap php7.0-mysql php7.0-readline php7.0-snmp php7.0-sqlite3
```

**Comment by albundy83** [comment]
Ok, I have found an issue in my pear setup.
I will give another try :)

**Comment by albundy83** [comment]
Ok, problem is "solved", the problem comes from variable 12 in pear setup.
If path is not /etc/pear.conf, all those environment variables are ignored and pear packages are installed in a not common path (/usr/lib/pear something like this...).

Anyway, now I have real php 7.0 working version with pear packages correctly installed.
So here the first real php 7.0 issue : (deprecated stuff :) 
```
PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /usr/local/centreon/GPL_LIB/Smarty/libs/Smarty_Compiler.class.php on line 269, referer: http://X.X.X./centreon/install/setup.php
```
And the affected function : 
```
$source_content = preg_replace($search.'e', "'"
                                       . $this->_quote_replace($this->left_delimiter) . 'php'
                                       . "' . str_repeat(\"\n\", substr_count('\\0', \"\n\")) .'"
                                       . $this->_quote_replace($this->right_delimiter)
                                       . "'"
                                       , $source_content);
```
Maybe there will some others  ...
If someone know php over here and can help me...

**Comment by albundy83** [comment]
Ok here the fix I have found : 
```php
$source_content = preg_replace_callback($search, create_function ('$matches', "return '"
                                       . $this->_quote_replace($this->left_delimiter) . 'php'
                                       . "' . str_repeat(\"\n\", substr_count('\$matches[1]', \"\n\")) .'"
                                       . $this->_quote_replace($this->right_delimiter)
                                       . "';")
                                       , $source_content);
```
And it works, but some others errors appear :(

**Comment by george-vieira** [comment]
initially I had a blank page on setup screen. this turns out to be preg_replace not accepting /e anymore and suggests callback function in file /usr/local/centreon/GPL_LIB/Smarty/libs/Smarty_Compiler.class.php in line 266.

Getting past that, it complained of not finding mysql.so . looks like php modules for mysql were only:
root@test:~ $ php -m|grep mysql -i
mysqli
mysqlnd
pdo_mysql

trying to enable mysql.so is a fail for the moment. regardless, looks like we're heading for yet another php compatibility like we had with php 5.6
maybe centreon should move away from using mysql and switch to PDO or mysqli etc.

**Comment by albundy83** [comment]
Hello,
sorry, I did not add my latest updates, here the futur errors you will found : 
- php_mysql has been deprecated in php7, all mysql_xxx functions have been deprecated, you have to change manually each mysql_xxx by mysqli_xxx, 
- for mysql_pconnect, you have to change it to mysqli_connect with speciale p character : 
```php
@mysql_pconnect($pServeur, $pNom, $pMotPasse) or ($msg = mysql_error());
```
Will become : 
```php
@mysqli_connect("p:".$pServeur, $pNom, $pMotPasse) or ($msg = mysqli_error());
```
You have also to update xxx/www/install/var/phplib file : 
```
MySQL:mysql
GD:gd
LDAP:ldap
XML Writer:xmlwriter
MB String:mbstring
SQLite:pdo_sqlite
INTL:intl
```
to 
```
MySQL:mysqli
GD:gd
LDAP:ldap
XML Writer:xmlwriter
MB String:mbstring
SQLite:pdo_sqlite
INTL:intl
```
To allow web installer to recognize mysqli module.

That's where I am whith my tests.

**Comment by albundy83** [comment]
It seems that even with my big ugly hack, data base is not created correctly.
Maybe on a running system it could work better as it seems that mysql_xxx are used only during initial installation process.
Then it pdo functions.
If a centreon team member read our post (and between 2 laughs...) he can confirm this :)

Thanks a lot.

**Comment by albundy83** [comment]
The problem comes from mysqli_query() that need to have the connection link in parameters...

**Comment by zskarman** [comment]
Hi,

is that possible to fix the support for PHP 7 ?

because if i check this one

![image](https://user-images.githubusercontent.com/24320218/34216116-a8e5e966-e5a7-11e7-9592-6631d552f4cc.png)


Looks not right the 5.4

**Comment by lpinsivy** [comment]
We are looking on this but not yet planned.

**Comment by olivier-monaco** [comment]
I'm using the latest Centreon on Debian Stretch with PHP 7. I had to changes some files to get it working and it run fine for some days now. Here are my changes (including the one of @albundy83).

Caution: it's not a fix, just a workaround. The way the PHP part is coded need to be fully reviewed. Don't use it as a "now all will be good". It may be some parts broken that we didn't notify for now.

For the install part, I choose to write some compatibility layer. Open www/install/steps/functions.php and add at the beginning:
```php
$_my_link = null;
 
function mysql_close($link = null)
{
    global $_my_link;
    if (is_null($link)) {
        $link = $_my_link;
    }
    return mysqli_close($_my_link);
}
 
function mysql_connect($dsn, $user, $password)
{
    global $_my_link;
    $_my_link =  mysqli_connect($dsn, $user, $password);
    return $_my_link;
}
 
function mysql_error()
{
    global $_my_link;
    return mysqli_error($_my_link);
}
 
function mysql_fetch_assoc($res)
{
    return mysqli_fetch_assoc($res);
}
 
function mysql_free_result($res)
{
    return mysqli_free_result($res);
}
 
function mysql_query($sql)
{
    global $_my_link;
    return mysqli_query($_my_link, $sql);
}
 
function mysql_select_db($name)
{
    global $_my_link;
    return mysqli_select_db($_my_link, $name);
}
```

Next open www/install/var/phplib and replace:
```
MySQL:mysql
```
by
```
MySQL:mysqli
```

Centreon use the Pear DB package for database related access. It is outdated now but it can use mysqli directly. So there a less change to do. The only issue is the direct use of mysql_real_escape_string. I replaced it be a home made version. Here is a Git diff for www/class/centreonDB.class.php:
```
diff --git a/www/class/centreonDB.class.php b/www/class/centreonDB.class.php
index 9c90666..adc1028 100644
--- a/www/class/centreonDB.class.php
+++ b/www/class/centreonDB.class.php
@@ -35,11 +35,19 @@
 include_once(realpath(dirname(__FILE__) . "/../../config/centreon.config.php"));
 require_once("DB.php");

+function mysql_real_escape_string($str)
+{
+    $search = array("\\", "\0", "\n", "\r", "\b", "\t", "\x1a", "'", '"');
+    $replace = array("\\\\", "\\0", "\\n", "\\r", "\\b", "\\t", "\\Z", "\\'", '\\"');
+    $escapedStr = str_replace($search, $replace, $str);
+    return $escapedStr;
+}
+
 class CentreonDB
 {

     private static $instance = array();
-    protected $db_type = "mysql";
+    protected $db_type = "mysqli";
     protected $db_port = "3306";
     protected $retry;
     protected $db;
@@ -366,9 +374,9 @@ class CentreonDB
         if ($htmlSpecialChars) {
             $str = htmlspecialchars($str);
         }
-        
+
         $escapedStr = mysql_real_escape_string($str);
-        
+
         return $escapedStr;
     }

@@ -547,7 +555,7 @@ class CentreonDB
                     $info[$key] = round($value / $unitMultiple, 2);
                 }
                 if ($key == "version") {
-                    $tab = split('-', $value);
+                    $tab = explode('-', $value);
                     $info["version"] = $tab[0];
                     $info["engine"] = $tab[1];
                 }
```

Then we need to fix Smarty lib:
```
diff --git a/GPL_LIB/Smarty/libs/Smarty_Compiler.class.php b/GPL_LIB/Smarty/libs/Smarty_Compiler.class.php
index 1898c5d..232c2b2 100644
--- a/GPL_LIB/Smarty/libs/Smarty_Compiler.class.php
+++ b/GPL_LIB/Smarty/libs/Smarty_Compiler.class.php
@@ -262,12 +262,12 @@ class Smarty_Compiler extends Smarty {
         reset($this->_folded_blocks);

         /* replace special blocks by "{php}" */
-        $source_content = preg_replace($search.'e', "'"
-                                       . $this->_quote_replace($this->left_delimiter) . 'php'
-                                       . "' . str_repeat(\"\n\", substr_count('\\0', \"\n\")) .'"
-                                       . $this->_quote_replace($this->right_delimiter)
-                                       . "'"
-                                       , $source_content);
+               $repl_func = function ($matches) {
+            return $this->_quote_replace($this->left_delimiter) . 'php'
+                . str_repeat("\n", substr_count($matches[1], "\n"))
+                . $this->_quote_replace($this->right_delimiter);
+               };
+        $source_content = preg_replace_callback($search, $repl_func, $source_content);

         /* Gather all template tags. */
         preg_match_all("~{$ldq}\s*(.*?)\s*{$rdq}~s", $source_content, $_match);
```

Another issue in a Centreon authentication class:
```
diff --git a/www/class/centreonAuth.SSO.class.php b/www/class/centreonAuth.SSO.class.php
index cee1412..0661afb 100644
--- a/www/class/centreonAuth.SSO.class.php
+++ b/www/class/centreonAuth.SSO.class.php
@@ -108,7 +108,7 @@ class CentreonAuthSSO extends CentreonAuth
         }
     }

-    protected function checkPassword($password, $token, $autoimport = false)
+    protected function checkPassword($password, $token = '', $autoimport = false)
     {
         if ($this->sso_mandatory == 1) {
            # Mode LDAP autoimport. Need to call it
```

and in configuration forms:
```
diff --git a/www/include/configuration/configObject/command/listCommand.php b/www/include/configuration/configObject/command/listCommand.php
index 0ad5789..1aea893 100644
--- a/www/include/configuration/configObject/command/listCommand.php
+++ b/www/include/configuration/configObject/command/listCommand.php
@@ -82,7 +82,7 @@ include_once "./include/common/checkPagination.php";
  * Smarty template Init
  */

-set_magic_quotes_runtime(0);
+//set_magic_quotes_runtime(0);

 $tpl = new Smarty();
 $tpl = initSmartyTpl($path, $tpl);
```

followed by:
```
diff --git a/www/lib/HTML/QuickForm.php b/www/lib/HTML/QuickForm.php
index af4cce5..10d82ca 100644
--- a/www/lib/HTML/QuickForm.php
+++ b/www/lib/HTML/QuickForm.php
@@ -1873,7 +1873,8 @@ class HTML_QuickForm extends HTML_Common
     function toArray($collectHidden = false)
     {
         include_once 'HTML/QuickForm/Renderer/Array.php';
-        $renderer =& new HTML_QuickForm_Renderer_Array($collectHidden);
+        $a = new HTML_QuickForm_Renderer_Array($collectHidden);
+        $renderer = &$a;
         $this->accept($renderer);
         return $renderer->toArray();
      } // end func toArray
```

Once running, I found that Centreon sometimes use www/lib/HTML/QuickForm.php, sometimes the globally-installed Pear version /usr/share/php/HTML/QuickForm.php. So we have to fix it too. Here is a diff:
```
597c597,598
<         $elementObject =& new $className();
---
>         $a = new $className();
>         $elementObject =& $a;
1707c1708,1709
<             $GLOBALS['_HTML_QuickForm_default_renderer'] =& new HTML_QuickForm_Renderer_Default();
---
>             $a = new HTML_QuickForm_Renderer_Default();
>             $GLOBALS['_HTML_QuickForm_default_renderer'] =& $a;
1864c1866,1867
<         $renderer =& new HTML_QuickForm_Renderer_Array($collectHidden);
---
>         $a = new HTML_QuickForm_Renderer_Array($collectHidden);
>         $renderer =& $a;
```

And to compile the Broker, you need to add the following line in build/CMakeLists.txt, just after `project("CentreonBroker" C CXX)` (source https://github.com/centreon/centreon-broker/issues/139):
```
 set(CMAKE_CXX_FLAGS “${CMAKE_CXX_FLAGS} -std=c++98 -fpermissive")
```

There are some warnings to fix but it's working.

**Comment by olivier-monaco** [comment]
Debian Stretch comes with RRDTool 1.6 but Centreon does not support this version. See.  #5370.

To get it working, I had to copie librrd.so.4 from Jessie as librrd.so.8 under Stretch, to replace the rrdtool with the one from Jessie. Next, I had to copy the libpng12 library from Jessie...

Reading what @lpinsivy says here and @julienmathis in #5370, I think you need an 5 year old system to use Centreon. I try to go deeper in code to rewrite obsolete code but there are all components of Centreon that are outdated...

**Comment by lgcosta** [comment]
Would not it be interesting to work with an ORM in these codes? this could help maintain compatibility with future versions of PHP and we would still have greater compatibility with other databases (eg: Postgresql). Thus, we would have an abstract DB access layer in the code. Has this already been discussed?

**Comment by olivier-monaco** [comment]
MariaDB 10.2 has changed defaut sql_mode setting. Centreon Web can't work with MariaDB 10.2 "out-of-box". Some updates fail silently with warning like:

```
ERROR 1366 (22007): Incorrect integer value: '' for column 'graph_id' at row 1                                                        
```

You need to set "sql_mode" to an empty string in MariaDB settings.
