### ISSUE TITLE
ACL - Simple user cans create widgets but I don't authorize it in acl rules

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4147]
Hello,

In my acl rules for "menus", I define this:
 - Home :	Yes
  - Custom Views :Yes
     - Edit : No
    -  Share : No
    -  Parameters : No
    -  Add Widget : No
    -  Rotation : Yes

Problem is my simple user cans create its own view and add widgets on this view.
It can't add widgets on shared views but it's normal.

Regards,

**Comment by kduret** [comment]
Works fine.
Probably fixed here : 16747a5ec7ba7099fb6cdb73b2ec362350509586
