### ISSUE TITLE
[Custom_Views] Can't remove relations between usergroup and my view

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4148]
Hi, 

When trying to remove authorizations on my custom view (delete a contact group e.g), I get some SQL error because of unitialized userId var. 

See sql error below : 

DELETE FROM custom_view_user_relation
                          WHERE usergroup_id = 3
                          AND custom_view_id =

and 

 REPLACE INTO custom_view_user_relation (custom_view_id, user_id, locked, is_consumed) VALUES (8, , 1, 0)

Thanks, 

++

**Comment by Sims24** [comment]
Thanks, confirm that the issue is fixed !

**Comment by Sims24** [comment]
Sorry spoke too fast... but it's not fixed on my side. 

Contact me to get IP, 

Thanks

**Comment by lpinsivy** [comment]
Should be corrected by : https://github.com/centreon/centreon/issues/4148
