### ISSUE TITLE
Timeout centcore

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4153]
Bonjour,

A la suite d'un problème d'un nombre important de Pipe ouvert sur un de mes Pollers. Je vous propose d'ajouter un timeout sur les commandes envoyées par centcore, en ajoutant la commande "timeout" devant la commande "cat" (par exemple) au moment de la récupération des statistiques des pollers.

Le timeout existant n'a aucun effet sur les pollers, il agit juste sur le centcore placé sur le central.

**Comment by julienmathis** [comment]
Bonjour, 

Je ne suis pas sur que cela ferme les pipe. Le problème est ailleurs. Pourquoi y avait il blocage ?

**Comment by jben94** [comment]
Bonjour,

Après 6 mois j'ai du mal à m'en souvenir. Ce que je me souviens, c'est que nous avions eu un problème sur le nombre de processus ouvert car le central avait essayé de récupérer les statistiques du poller. N'ayant pas de retour il tombait en Timeout ( configuré depuis l'interface Web ). Par contre la commande distante restait bloquée et n'avait pas de Timeout programmé. 

Si je ne met pas de Timeout via l'interface web. Centcore restait bloquée et j'étais obligé de le redémarrer.

**Comment by lpinsivy** [comment]
Le mécanisme à changé c'est des fichiers json maintenant
