### ISSUE TITLE
Possibility to disable ajax search in monitoring views

### ISSUE THREAD

**Issue by rbw** [centreon/centreon#4154]
Hello!

We have a pretty large number of hosts and the typeahead search in the monitoring view tends to get a bit laggy, especially when there's considerable load on the system. This is probably due to the fact that 95% of our servers starts with the same 4 characters.

It would be nice if the typeahead search could be disabled and replaced by a manual search (similar to the Configuration view one), alternatively the possibility to add a delay to the search.

Perhaps this is configurable, and I've missed the setting. If so, please point me in the right direction here :)

We're using Centreon 2.6.6.

Thanks!

**Comment by lpinsivy** [comment]
linked to #5464

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Furthermore version is 2.6.6 which is **no longer supported**

Closing this issue.

Regards,
