### ISSUE TITLE
[2.7.1] Services generation using host templates

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4155]
When we add an host (using Host templates) with Centreon CLAPI services are not automatically generated after the adding.
We must use the web interface : "More action menus" ==> "Deploy services"

**Comment by querwin** [comment]
I think it's a normal behaviour, as I can see in the doc : 

https://documentation-fr.centreon.com/docs/centreon/en/2.7.x/api/clapi/objects/hosts.html#addtemplate-and-settemplate
