### ISSUE TITLE
Display charts of selected resources from monitoring views

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4159]
Hello Centreon Team,
the new Design / Layout is great, but some important functions are missing now. 

1)
Search in services and graph is different since update. Search with text is better than search and select. For example if you want to show all server with name "sometest-" i dont want to add each server for themselves. But i think i can live with that. Maybe with time it gets a good change.

2) 
Before the update it was possible with the symbol top right to jump from services or hosts (with selection in list) to the graphs. Can we add some similar function?
That whould solve also 1) a little bit. The best whould be, if we could change the type of search in settings, but i think that is a big change and not possible to 2.7.3.

**Comment by florian-asche** [comment]
Why two different search approches (Status and Performances)? In 2.7.2 still not fixed. Im stocked at 2.6.5 for 5 customers. Cause of this missing functions.

**Comment by florian-asche** [comment]
Hi, Quentin told me about the usage "Crtl" and the "select all" comming in Version 2.7.3. See https://github.com/centreon/centreon/commit/1f648f4522d7bed22b85bc9400aaf6c03f685141

That is great news. So i think we can close 1).

**Comment by florian-asche** [comment]
I think 2) is still a good idea for implementing the old function as new one. To change the Page from Monitoring  >  Status Details  >  Hosts to Monitoring  >  Performances  >  Graphs, and the selected hosts- or services are automatically added to the selection form.

Like in the old version with that graph icon:
![unbenannt](https://cloud.githubusercontent.com/assets/2785700/13618513/d61bb1e2-e584-11e5-832e-09485eb5223d.png)

**Comment by lpinsivy** [comment]
Hi @florian-asche 

Yes 1) is closed by new options in Select2 (select all box)

Point 2) will be implemented in other version thant 2.7.3

**Comment by Moujimouja** [comment]
Hi,

The performance > graph page can handle that kind of request.

I close the ticket
