### ISSUE TITLE
Help tooltips still visible when change tab

### ISSUE THREAD

**Issue by vurmil** [centreon/centreon#4160]
Hi

When you click help icon

![capture20160203071715784](https://cloud.githubusercontent.com/assets/15263415/12774554/508696f4-ca46-11e5-869b-fefc0cb9bde7.png)

When you change the page

![capture20160203071858421](https://cloud.githubusercontent.com/assets/15263415/12774564/6b779620-ca46-11e5-86d0-54837d102c42.png)

**Comment by cgagnaire** [comment]
Fixed by https://github.com/centreon/centreon/pull/7729
