### ISSUE TITLE
[2.7.1] Usability regression - Dual lists / selection component

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4161]
Dear team,

Thank you for the hard work on the new interface.
However in order to help you to improve the tool I would like to talk about dual lists (see attachement, old version 2.6). The new selection component (in 2.7+) is not friendly to use, especially when you have to select a long list of items at one time (Hostgroups for example). It seems I'm not the only one complaining about this.

If you don't plan to revert to the old selection component please make it configurable

Thank you for understanding

![listes doubles-ann](https://cloud.githubusercontent.com/assets/5636906/12776761/e3ce57dc-ca58-11e5-9bc4-3db137565501.png)

**Comment by gslongo** [comment]
Any follow up to this request ?

Thanks

**Comment by julienmathis** [comment]
Hello, 

We have done on the last versions many enhancements. New ones will be introduce in the next version. Are you still disapointed by this component ?
