### ISSUE TITLE
Delete Hosts and Relations via Script

### ISSUE THREAD

**Issue by Meistercoach83** [centreon/centreon#4166]
Hi! I started an import-script for centreon Hosts from our Switch-database (mysql, too). I think I need 5 Tasks to add a new host:
1. add host to host
2. add host to ns_host_relation (defined as a global val)
3. add host to hostgroups (defined as a global Array)
4. create Services from linked host-templates (defined as a global Array)
5. reload the Server via exec()

Is that correct? Or is there an easier method to load new Hosts from a given database (and delete Hosts if they don´t exists in source-db any longer?

**Comment by cemir** [comment]
Hi,

IMO it's better to use CLAPI for this kind of actions, and in a more general way, it's not a good idea to insert things manually into centreon's DB.

Basicaly, what you want to do here is 
1) create your template and hostgroups via web interface
2) extract all your hostnames from your old DB
3) make a shell script to loop throught your extract and add them to centreon via clapi with correct template and hostgroup
4) generate config files and restart poller via web interface.

**Comment by Meistercoach83** [comment]
Hi! The clapi is really cool. All I did in x lines of code are now in 3 lines :+1: 
Last question: Is there a possibility to auto-generate the services assigned to a host template?

**Comment by cemir** [comment]
Hi,

there is an action on host object for that : Applytpl

see [https://documentation.centreon.com/docs/centreon-clapi/en/latest/objects/hosts.html?highlight=applytpl](url)

regards

**Comment by Meistercoach83** [comment]
Thanks for help!
