### ISSUE TITLE
Comments overlapping

### ISSUE THREAD

**Issue by tanguyvda** [centreon/centreon#4169]
When service is acknowledged with a comment and then put under downtime with another comment from the  Status Details menu it shows the ackowledged comment twice but not the downtime one. 

Temporary fix : put acknowledge comment via Status Details then go under the monitoring>Downtimes menu to add your downtime with the comment.

centreon : 2.7.1
broker : 2.11.0
engine : 1.5.0

Tanguy Charles

**Comment by kduret** [comment]
Linked to #4170
