### ISSUE TITLE
[2.7.1] eventReportBuilder -> Can't call method "query"

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#4172]
The cron eventReportBuilder runs every day on error:
```
2016-02-07 03:00:02 - Starting program...
2016-02-07 03:00:02 - Processing period: Sat Feb  6 00:00:00 2016 => Sun Feb  7 00:00:00 2016
Error: Can't call method "query" on an undefined value at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 96.
```

Probabily for this reason the dashboard shows 100% undetermined for all periods since the upgrade to centreon 2.7.0

**Comment by aurelazy** [comment]
I have the same issue with centreon 2.7.1.
Thanks in advance.

**Comment by Sims24** [comment]
Hi, 

Could you give the result of the following sql query please :

**Comment by Sims24** [comment]
SELECT `value` FROM `options` WHERE `key` = 'broker'

**Comment by joschi99** [comment]
the value is `ndo`

**Comment by Sims24** [comment]
Please do : 
 
 UPDATE centreon.options SET value='broker' WHERE value='ndo';

I have the same issue here and fix the problem. We will dig around to understand why ndo is set as it is unsupported now.

Thanks

**Comment by joschi99** [comment]
Hi,

this solves the problem. Now the job is working fine. Rebuilding the data with eventReportBuilder and dashboardBuilder also the dashboard is correct.

Thanks for the help

**Comment by aurelazy** [comment]
Super Thanks so much !! it's working now

**Comment by maksimatveev** [comment]
Thx!!
