### ISSUE TITLE
Multiselect Improvement

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#4173]
The new multiselect that has been included in Centreon 2.7 is great and could be improve to ease the massive multiple item selection. 

Something like Shift+Click then Scroll then Click that will select all the item between the first and the last click.

For now, if you have 200 datastores called DS_xxxxx , if you want to select all these metrics, it's just impossible.

**Comment by gslongo** [comment]
+1 https://github.com/centreon/centreon/issues/4161

**Comment by julienmathis** [comment]
With all improvements done done for version 2.7.3, I think this one can be delayed.

**Comment by gslongo** [comment]
Dear Team,

This functionnality is really missing (Shift+Click to select a couple of items). This is very useful for large setups. 2.7.3 allows to select all items only.

Do is it possible to configure the choice of select component ? (integrate the old and the new components and make it configurable)

Thank you for advance,
