### ISSUE TITLE
Trouble with Inherit contacts from host on Service

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#4177]
When you configure the option "Inherit contacts from host" in notification tab on a service, if this variable as set as "no" and you have a contact group set on host template some notification are send any way for service heritate of this host template.

I saw with Matthieu Kermagoret that they have some implicite dependence in centreon engine.
We need to put the field service_inherit_contacts_from_host of table centreon.servicice as NULL to fix it, but this way is really dirty.
We can also set a empty contact group on the generic-active-service to overwrite this implicite dependence.

**Comment by lpinsivy** [comment]
The Inherit contacts has beed rewritten. Should be corrected
