### ISSUE TITLE
Notification escalation - contact groups cannot have space in name / alias

### ISSUE THREAD

**Issue by oragain** [centreon/centreon#4178]
When using a contact group in a notification escalation, if the contact group name or alias (unsure which one exactly) has spaces the generation of files will fail saying that the contact group cannot be found.
Also if you just configured escalation and applied it to hundreds / thousands of services, the generation of the files might seem to stall without letting you know why because of the above error.

**Comment by julienmathis** [comment]
Hello, 

It seem that the problem has been fixed in the version 2.7.2. What is your version of Centreon Web ?

Thanks

**Comment by oragain** [comment]
2.5.4. So normal i guess ;)
Thanks
