### ISSUE TITLE
Erreur variable

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4181]
Bonjour,

Dans le fichier de configuration de centengine.cfg, il y a une erreur lors de la construction du fichier.

Fichier : engine.class.php
Ligne : 386

$object['service_perfdata_command'] = $command_instance->generateFromCommandId($object['**global_host_event_handler_id**']);

$object['service_perfdata_command'] = $command_instance->generateFromCommandId($object['service_perfdata_command'])

**Comment by julienmathis** [comment]
Thanks !
