### ISSUE TITLE
p1 file not in  packages?

### ISSUE THREAD

**Issue by hecko** [centreon/centreon#4182]
The documentation states

Location of the Perl program to provide Perl code persistence for the Monitoring Engine project. This program provides an API for calling Monitoring Engine Perl plugins from Monitoring Engine when it is built with embedded Perl support. The intent is to tradeoff memory usage against repeated context switches to recompile Perl plugins. **The file p1.pl is provided by default with the Monitoring Engine package.**

But could not find the p1.pl file anywhere in any packages:

[root@SDCTLP0009 ~]# yum provides "*/p1.pl"

This is probably just a cosmetic thing, but Im getting (2.7.1) this when generating config for a poller:
Warning p1_file variable ignored
Warning enable_embedded_perl variable ignored
Warning use_embedded_perl_implicitly variable ignored

This is partly discussed in #3032

**Comment by julienmathis** [comment]
@ganoze : can you confirm that p1.pl is deprecated or useless ?

Thanks

**Comment by ganoze** [comment]
Yes I confirm, p1 file is deprecated.

Also I cannot find any reference to p1.pl in the official online documentation.
