### ISSUE TITLE
Usability enhancement - graph lines not visible if they are in yellow

### ISSUE THREAD

**Issue by hecko** [centreon/centreon#4184]
Some graphs use yellow color to draw lines - I assume this color is randomly generated - once the line is yellow (or light orange) it is hardly visible. Please remove the yellow and very light colors from the poll of colors to be selected for the lines - especially when the background is (by default) white.
![graph](https://cloud.githubusercontent.com/assets/855807/13005221/ac33f0b4-d180-11e5-887b-aa28b3c75fdd.jpg)

**Comment by gslongo** [comment]
I think the color is generated randomly. As a workarround you can force colors : Views > Graphs > Curves
