### ISSUE TITLE
Unexpected scheduling 

### ISSUE THREAD

**Issue by tanguyvda** [centreon/centreon#4185]
Scheduling interval doesn't match the configured one in Centreon. 

Vm-tools are up to date

centreon-broker-core-2.10.2-2.el6.x86_64
centreon-engine-1.4.15-6.el6.x86_64
centreon-trap-2.6.6-5.el6.noarch
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-common-2.6.6-5.el6.noarch
centreon-broker-cbd-2.10.2-2.el6.x86_64
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-connector-1.1.2-1.el6.x86_64
centreon-plugins-2.6.6-5.el6.noarch
centreon-broker-2.10.2-2.el6.x86_64
centreon-engine-daemon-1.4.15-6.el6.x86_64
centreon-broker-cbmod-2.10.2-2.el6.x86_64
centreon-poller-centreon-engine-2.6.6-5.el6.noarch
centreon-broker-storage-2.10.2-2.el6.x86_64
centreon-engine-extcommands-1.4.15-6.el6.x86_64
centreon-perl-libs-2.6.6-5.el6.noarch
centreon-clib-1.4.2-1.el6.x86_64

**Comment by julienmathis** [comment]
Hello, 

Can we have more information regarding your problem ? It's very hard to help with only module versions.

Thanks in advance.

cc @ganoze

**Comment by julienmathis** [comment]
No response. Please reopen if you have the asked info.

Thanks
