### ISSUE TITLE
database error. that's it?

### ISSUE THREAD

**Issue by george-vieira** [centreon/centreon#4186]
Database Error: Could not connect to database. 
Please contact your administrator.

moving between a localhost mysql to a central replicated server which I can log in from command line to the remote server with correct credentials. All that centreon tells me is it can't connect.
It would be nice if it gave a little more info, refused connection, timed out, password for 'centreon' failed, can't select database (ie priv on mysql incorrect)... anything!

You are using 2 config files for perl and php code, why not just centralize it into an INI style or other form which the 2 scripting languages can use a central config file making administration easier.

I got no idea if any other files need editing to change DB settings other than the centreon.conf.php and conf.pm files.

I've done this kind of change before with many previous versions but a pain every time I run into the same issue and the error shows no indication as to what, especially where command line works fine.

**Comment by julienmathis** [comment]
Hello, 

Thanks for using Centreon. That is realy good idea and it's that we have done for the version 3.0 of Centreon. We have only one ini file who have more parameters: it's more easy to change.

Do you find why you can't connect to the database ?

Regards,

**Comment by george-vieira** [comment]
Yeah it was eventually found and corrected. So many areas where DB info is recorded. The next one was found in broker where every broker section using db details needed to be changed.
I really think a central db recorded for all/any db related info should be used. Having built centreon with localhost as a db host and trying to move it to a dedicated db host can be a nightmare.
