### ISSUE TITLE
[2.7.1] liste déroulante - pb de focus sur les objets de la liste

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4189]
Bonjour,
un autre petit désagrément dans la sélection des objets des listes déroulantes.
si un objet de la liste se trouve au niveau du bord d'un champ redimensionnable en arrière plan, le pointeur de la souris se transforme en curseur d'agrandissement (cf PJ)
![centreon_2 7_liste_deroulante_pb_focus](https://cloud.githubusercontent.com/assets/8720203/13047733/7ac583c2-d3e1-11e5-8f20-5fc85ef8cbb4.png)

Le choix d'une option de la liste peut alors se révéler difficile.

cordialement,

**Comment by julienmathis** [comment]
Bonjour, 

Sur quelle version exact de navigateur rencontrez vous ce problème ?

Merci

**Comment by cmeschin** [comment]
Bonjour,
 Le problème semble résolu sur la 2.7.3. (le format de la liste déroulante semble légèrement différent, l'ascenseur à droite ne s'affiche pas de la même manière) cf PJ
J'utilise Firefox (actuellement en version 46)
![centreon_liste_deroulante_ok](https://cloud.githubusercontent.com/assets/8720203/15248565/3276327c-191b-11e6-966b-0cb698f40272.png)

cordialement,

**Comment by julienmathis** [comment]
Thanks
