### ISSUE TITLE
Save service dependency save nothing

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4190]
When I save a service dependency list of services and dependent services are not save.

**Comment by julienmathis** [comment]
Are you sure ? It works for me

**Comment by lpinsivy** [comment]
Yes ok in Centreon 2.7.2

**Comment by kduret** [comment]
Fixed here : https://github.com/centreon/centreon/commit/275fe857fe0e1586fc3267331804c72d5f8b8276
