### ISSUE TITLE
Bug with check_centreon_snmp_remote_storage

### ISSUE THREAD

**Issue by nikaro** [centreon/centreon#4193]
Output in Web interface :
```
Disk CRITICAL - no output (-p number expected... it doesn't exist, try another disk number)
```

But with in CLI with `sudo -u centreon-engine /usr/lib/nagios/plugins/check_centreon_snmp_remote_storage -H <IP_ADDRESS> -n -d "Swap Space" -w 80 -c 90 -v 2 -C public` it works fine.

It happens both on fresh install with CES ISO, or with packages installation on a fresh CentOS 6.

**Comment by julienmathis** [comment]
Hello,

Can you move this ticket in centreon/centreon-plugins projet ? 

Thanks in advance

**Comment by nikaro** [comment]
Yep, it's done.
