### ISSUE TITLE
WebService - internal.php > Error are not correctly catched, only receiving Error 500

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#4196]
I have a class that extends CentreonWebService and this calss is called using internal.php.

I'm trying to handle a DB error connection but it doesnt work as expected : 

When the connection can't be done, I only see Error 500 in the brower console instead of receiving error 400 with "Can't connect to reporting database".

Am I doing something wrong ? 

```
class ReportingPerformance extends CentreonWebService {
[ ... ]

  try {
    $this->reportingDB = $this->reportingDatabase->reportingConnect();
  } catch (Exception $e) {
    throw new RestBadRequestException ("Can't connect to reporting database");
  }
}
```

**Comment by lpinsivy** [comment]
Hi,

May be you should use in catch bloc:

CentreonWebService::sendJson("Can't connect to reporting database", 400);

Or add try/catch bloc when you init reportingDatabase property

**Comment by golgoth31** [comment]
Hi,
does the function reportingConnect() contains any "throw new Exception ...." ? if not, you will never catch anything.
Are you sure that your code is part of a "try/catch" bloc waiting for the exception "RestBadRequestException" ?

**Comment by Moujimouja** [comment]
Thanks guys, I've solved it by using the tips from lpinsivy and then managing to display correctly the error in my widget ;)
