### ISSUE TITLE
Graph Rebuild not working Centreon Core 2.5.2

### ISSUE THREAD

**Issue by TAM-AD** [centreon/centreon#4198]
Dear Supporters,

i have a problem with some graphs i try to regenerate through the Web-Frontend.
They are beeing marked as Rebulding but never finish (nor even start to be rebuild)
There are no entries about it in centcore.log or centstorage.log.
Anywhere else to look at or other logs to post here?

Regards

**Comment by julienmathis** [comment]
Do you see long query in mysql on data_bin table ?

**Comment by TAM-AD** [comment]
Hi Julien,

no, i don't see any long queries - nothing regarding centreon beeing logged in MySQL-Logs.

Regards
Timo

**Comment by julienmathis** [comment]
Did you find a solution ? Did you upgrade ? because 2.5.2 is now very old. Centcore don't manage the rebuild. It's centstorage or Centreon Broker depending if you use broker or not.
