### ISSUE TITLE
Design issue when there are lot of component

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4199]
In the Performance view, when there are lot of components, it's not really beautiful :-)
![cap 2016-02-19 a 16 15 46](https://cloud.githubusercontent.com/assets/10330979/13179430/3f21fff8-d724-11e5-833a-9a9a797024fa.png)

Thanks

**Comment by julienmathis** [comment]
This option will disapear in Centreon 2.8. Replaced by C3js Graphs
