### ISSUE TITLE
äöõü letters are not working after upgrade to 2.7.1

### ISSUE THREAD

**Issue by pavelsmn** [centreon/centreon#4203]
Reading main configuration file '/usr/share/centreon/filesGeneration/nagiosCFG/4/nagiosCFG.DEBUG'.
Error The name of servicegroup '&&&&&&_&&&&&&' contains one or more illegal characters.

On v2.6.6 all worked fine.
 
___
Pavel

**Comment by garnier-quentin** [comment]
I think it has been changed in htlmlentities (with &xxx;) and save in database. Could you change it in database ? Put the good values (in utf8). Maybe if you save the form in centreon-web, it will be saved without htlmentities.

**Comment by julienmathis** [comment]
I think you have all information to fix your problem.
