### ISSUE TITLE
Time Interval change isn't being reflected in the polling Engine config

### ISSUE THREAD

**Issue by bcdonadio** [centreon/centreon#4204]
I changed the Interval Length parameter in the Administration > Parameters > Monitoring page to 30s (instead of the default 60s). However, the interval_length paramater in the config file generated (/usr/share/centreon//filesGeneration/nagiosCFG/1/resource.cfg) is always set to 60, irrespective of the number I put in the configuration page.

Package versions:
```
[root@perseus 1]# rpm -qa | grep centreon
centreon-clib-1.4.2-1.el6.x86_64
centreon-broker-2.11.2-2.el6.x86_64
centreon-trap-2.7.1-10.el6.noarch
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-plugin-meta-2.7.1-10.el6.noarch
centreon-common-2.7.1-10.el6.noarch
centreon-engine-daemon-1.5.0-10.el6.x86_64
centreon-plugins-2.7.1-10.el6.noarch
centreon-broker-storage-2.11.2-2.el6.x86_64
centreon-perl-libs-2.7.1-10.el6.noarch
centreon-broker-cbd-2.11.2-2.el6.x86_64
centreon-engine-1.5.0-10.el6.x86_64
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-web-2.7.1-10.el6.noarch
centreon-base-config-centreon-engine-2.7.1-10.el6.noarch
centreon-poller-centreon-engine-2.7.1-10.el6.noarch
centreon-engine-extcommands-1.5.0-10.el6.x86_64
centreon-broker-core-2.11.2-2.el6.x86_64
centreon-broker-cbmod-2.11.2-2.el6.x86_64
centreon-connector-1.1.2-1.el6.x86_64
centreon-2.7.1-10.el6.noarch
```

Should I change it somewhere else, or is this a bug?

**Comment by lpinsivy** [comment]
Hi,

can you try this patch ?

`--- /usr/share/centreon/www/class/config-generate/engine.class.php.orig 2016-03-03 16:34:19.602768966 +0000
+++ /usr/share/centreon/www/class/config-generate/engine.class.php      2016-03-03 16:52:20.779592765 +0000
@@ -76,7 +76,6 @@
         max_host_check_spread,
         check_result_reaper_frequency,
         max_check_result_reaper_time,
-        interval_length,
         auto_rescheduling_interval,
         auto_rescheduling_window,
         low_service_flap_threshold,
@@ -199,7 +198,6 @@
         'max_host_check_spread',
         'check_result_reaper_frequency',
         'max_check_result_reaper_time',
-        'interval_length',
         'auto_rescheduling_interval',
         'auto_rescheduling_window',
         'low_service_flap_threshold',
@@ -292,9 +290,11 @@
     protected $attributes_array = array(
         'cfg_file',
         'broker_module',
+        'interval_length'
     );
     protected $stmt_engine = null;
     protected $stmt_broker = null;
+    protected $stmt_interval_length = null;
     protected $add_cfg_files = array();

     private function buildCfgFile($poller_id) {
@@ -335,6 +335,19 @@
         }
     }

+    private function getIntervalLength() {
+        if (is_null($this->stmt_interval_length)) {
+            $this->stmt_interval_length = $this->backend_instance->db->prepare("SELECT
+                `value`
+                FROM options
+                WHERE `key` = 'interval_length'
+            ");
+        }
+        $this->stmt_interval_length->execute();
+        $this->engine['interval_length'] = $this->stmt_interval_length->fetchAll(PDO::FETCH_COLUMN);
+    }
+
+
     private function getBrokerModules() {
         if (is_null($this->stmt_broker)) {
             $this->stmt_broker = $this->backend_instance->db->prepare("SELECT
@@ -367,9 +380,9 @@

         $this->buildCfgFile($poller_id);
         $this->getBrokerModules();
-
+        $this->getIntervalLength();
+
         $object = $this->engine;
-
         # Decode
         if (!is_null($object['illegal_macro_output_chars'])) {
             $object['illegal_macro_output_chars'] = html_entity_decode($object['illegal_macro_output_chars'], ENT_QUOTES);`

**Comment by bcdonadio** [comment]
Yes! The issue seems to have been solved with the provided patch.

Thanks.

**Comment by julienmathis** [comment]
@lpinsivy Can you commit please ?

**Comment by lpinsivy** [comment]
Already commited but i forgot # in commit number 10be12e00f204c4b8966a43cdf52d45335027c49
