### ISSUE TITLE
Amelioration - arrêt planifié récurrent - date spécifique

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4207]
Bonjour est-il possible d'ajouter dans la liste déroulante des jours, les "second", "troisième" et "quatrième" du mois en plus des "premier" et "dernier"?
![centreon_downtime_reccurent](https://cloud.githubusercontent.com/assets/8720203/13220885/df758820-d978-11e5-9ab4-5609a092952a.png)

cordialement,

**Comment by Ridene** [comment]
Bonjour, 

Nous prenons en compte votre demande. 
Elle est en cours en développement.

Nous vous remercions pour votre intérêt.

**Comment by thiuyendang** [comment]
CentOs6, CentOs7
OK 2.8.5 Centreon Web in English
For French, validation is pending because of another temporary issue (cannot currently change user language)
