### ISSUE TITLE
Trouble with Unhandled Problems filter

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#4208]
Hello

In Monitoring -> Status Détails
When Unhandled Problems filter is apply the services states of down host are display

**Comment by lpinsivy** [comment]
Hi

You prefer to do not display services states of down host with "Unhandled Problems" filter and display them with "Service Problems" filter only ?

Regards,

**Comment by Tpo76** [comment]
Hi,

Yes that it. Because there are no way to filter only services which don't come from an host down.
But I make a mistake it's not a bug, because that never works like this in older version of Centreon, but it could be interesting.

**Comment by julienmathis** [comment]
Hello,

I'm sorry, I disagree with this ask. If we do that, we will not see critical services of all host down. so we never see problems. 
In this view, at the difference of host problems view, we have to hide the problems of host handled (so not acknowledged or in downtime).
So here it's not possible to change the behavior of this page.

Regards,
