### ISSUE TITLE
[2.7.1] - Pb gestion des macros contenant un tiret

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4209]
Bonjour,
La fonction traitement des macros (proposition de configuration des services et description) ne semble pas gérer les macros contenant un tiret (par exemple PERFADATA-UNIT)

La Macro est gérée correctement au niveau des commandes mais il est impossible de leur affecter une description et elles ne sont pas proposées automatiquement pendant la configuration des services.
Pour exemple voici une commande pour laquelle l'ajout de description sur les macros PERFDATA-UNIT et PERFDATA-NAME est impossible (cf PJ)

    $USER3$/centreon_plugins.pl --plugin=database::mysql::plugin --mode=sql --host=$HOSTADDRESS$ --port=$_SERVICEPORT$ --username="$_SERVICEUSERNAME$" --password="$_SERVICEPASSWORD$" --warning="$_SERVICEWARNING$" --critical="$_SERVICECRITICAL$" --perfdata-unit="$_SERVICEPERFDATA-UNIT$" --perfdata-name="$_SERVICEPERFDATA-NAME$" --sql-statement="$_SERVICESQL$" --format="$_SERVICEFORMAT$"

![centreon_2 7 1_macro_configuration](https://cloud.githubusercontent.com/assets/8720203/13292968/221fca4a-db1e-11e5-8653-ebeddde6b3c0.png)

![centreon_2 7 1_macro_description](https://cloud.githubusercontent.com/assets/8720203/13292515/596e3a1a-db1c-11e5-9503-f89b3ca10fd4.png)
Est-ce volontaire car il faut éviter d'utiliser ces caractères ou bien est-ce un bug?

cordialement,

**Comment by querwin** [comment]
Patch is not working for me
