### ISSUE TITLE
[2.7.1] Traduction manquante sur avertissement

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4210]
Bonsoir,

je viens de tomber sur un message non traduit en français lors du paramétrage de l'intervalle de contrôle d'un service (valeur 1440)
![centreon_2 7 1_intervalle_controle](https://cloud.githubusercontent.com/assets/8720203/13293446/fd980c9e-db1f-11e5-84d3-80f48d15d084.png)

![cenrteon_2 7 1_traduction](https://cloud.githubusercontent.com/assets/8720203/13293327/85be88ce-db1f-11e5-93e1-55bb2ec4f8f9.png)

cordialement,

**Comment by lpinsivy** [comment]
Moreover we have to build another french translation rpm to include this string.
