### ISSUE TITLE
trap generation issue with db constraint error

### ISSUE THREAD

**Issue by george-vieira** [centreon/centreon#4213]
I upgraded from 2.6.x to 2.7.1 and even 2.7.2. I think I also tried fresh install from 2.7.1 from source 

Getting issues generating snmptrap with the error below:

Database generation
Error on poller (id:1): SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: extended_service_information.service_service_id

Poller (id:1): RELOADCENTREONTRAPD sent to centcore.cmd

**Comment by julienmathis** [comment]
To be checked

**Comment by garnier-quentin** [comment]
Fixed in the last version already. https://github.com/centreon/centreon/issues/4459

**Comment by julienmathis** [comment]
Thanks @garnier-quentin !
