### ISSUE TITLE
centreon-web : block parent service template to be itself, causing loop in conf generation

### ISSUE THREAD

**Issue by dmagniez** [centreon/centreon#4217]
centreon-web 2.7.2 
broker 2.11 
engine 1.5

few days ago, we tried to restart some poller, but can't generate the config, page get stuck
it's happen only on 3 pollers, others are generating fine.

the access.log generate a "PHP Fatal error: Allowed memory size of 3414163456 bytes exhausted (tried to allocate 130968 bytes) in /usr/local/centreon/www/class/config-generate/abstract/object.class.php on line 106"

We tried to increase the memory limit of php.ini from 128Mb to 3250Mb, the change is commited, the process use +3Gb, stop after 30 sec timeout php !

I don't think that it's memory_limit, but I can't figure out if it's a bad config somewhere ...

I tried to debug the incrimined php file, each loop increase a few memory  usage around 16Mb, then consumption drop from 16Mb to 3000Mb. Memory leak seems to appear in an other php file.

How can I debug others files ? trace something or?

**Comment by dmagniez** [comment]
found ! an error in the config file is causing a loop during generation.
in a service template, it's possible to have as parent template, itself.

is it possible to block this behaviour in centreon-web ?

**Comment by garnier-quentin** [comment]
That's right! I have introduced a infinite loop with following fix: https://github.com/centreon/centreon/issues/4197

Need to fix it! With a current checking object!

**Comment by garnier-quentin** [comment]
Could you test it ? Should be fix the loop.
