### ISSUE TITLE
Multiple ACL inheritance

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4218]
Hello,

we have created various Contact Groups and various ACL Groups. The ACL groups have different ressources assigned and also different action access. The goal is to assign two or more ACLs to a user so that it is possible to make differenes in the actions for different host(groups)

Example:

ACL-Group-1
|
| >Ressource: Host1
| >Action = Read Only

ACL-Group-2
|
| >Ressource: Host2
| >Action = Read Only + Downtime + Acknowledge

Contact-Group-A is assigned  ACL-Group-1 and ACL-Group-2

User-A is assigned to Contact-Group-A

Current behavior: The user can set Downtimes and Acknowledges for both hosts (1+2) instead only for Host2.

Is this a bug? If not how can we reach our goals?

**Comment by garnier-quentin** [comment]
Hi,

Right now, it's by design. You can set different acl actions. acl actions rights are added!

**Comment by itsul** [comment]
Hi,

can you add it as a feature request?

Logically it should be the better way to add acl actions only in connection with their ACL-Groups. Some of our customers as asked us for submitting this bug.

Or should the customers open a ticket in the customer portal (BAM/MBI) ?`

Regards

**Comment by lpinsivy** [comment]
The planned operation of the ACLs in Centreon does not allow this. All ACLs are cumulative.
Mo
