### ISSUE TITLE
Cannot remove plugin on plugin pack

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4219]
Hello team,

We are not able to remove plugins from Plugin pack management.
![cap 2016-03-02 a 10 35 52](https://cloud.githubusercontent.com/assets/10330979/13456275/b8276cc0-e062-11e5-9813-eeed9f54458c.png)

Thanks in advance for your help

**Comment by julienmathis** [comment]
Not the good place to do that :)
