### ISSUE TITLE
Check interval field should be limited

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#422]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 6446, https://forge.centreon.com/issues/6446
Original Date: 2015-06-29

---

Hello,

This request is linked to the general subject of fileds limitation by Centreon (another same request for the https://forge.centreon.com/issues/6445).

One of my users has set a bad check interval by mistake.
With this parameter, the check will be done next day.

This working process around the monitoring seems to be logic, but Centreon should limit and check this parameter.

Best regards.

**Comment by ganoze** [comment]
In Centreon Engine, in most cases the upper limit for check interval is one year. Beyond this limit an interval of a week is used and a warning is printed in the logs (Warning: Check of service 'description' on host 'host" could not be rescheduled properly.  Scheduling check for next week...).

I did not find any evidence of scheduling to the next day.
