### ISSUE TITLE
Split multi graphs

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4222]
Bonjour,

Lorsque que nous avons plusieurs graphs affichés dans la partie "Monitoring  >  Performances  >  Graphs", la fonction "split" ne fonctionne plus.

Fichier: graphs.php
Ligne: 438

438         // preg_split metric
439         var _split = 0;
440         if (document.formu2 && document.formu2.split && document.formu2.split.checked)  {
441             _split = 1;
442         }

Proposition : 

438         // preg_split metric
439         var _split = 0;
440         if (document.formu2 && document.formu2.split && document.formu2.split.checked)  {
441             _split = 1;
442         } else if (document.formu2 && document.formu2[0]){
443             var nbr = document.formu2.length;
444             for (i=0;nbr>i;i++){
445                 if (document.formu2[i].split && document.formu2[i].split.checked) {
446                     _split = 1;
447                 }else{
448                     _split = 0;
449                 }
450             }
451         }

**Comment by lpinsivy** [comment]
fix by commit 1eeccb533f3e537b116a663f00ba860c2058cada
