### ISSUE TITLE
Widget window is to small

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4224]
Hello,
the widget window is really smal, and not all text is readable without scrolling.

I found it was really better in old version. In attachment two screenshots from old and new version.
![2](https://cloud.githubusercontent.com/assets/2785700/13495871/64b2fb5e-e14d-11e5-9e3d-05d07b99cd38.PNG)
![1](https://cloud.githubusercontent.com/assets/2785700/13495872/64b88236-e14d-11e5-925f-03e27e70fd74.PNG)

Can we please get this fixed to next version (2.7.3)?

**Comment by lpinsivy** [comment]
Hi Florian,

Can you create this issue on Centreon-Widget github project ?

Regards,

**Comment by florian-asche** [comment]
Hi, i dont think, that this is a problem of the widget itself. It worked before the design update. Or is there some change that need to be done on the widget side?

**Comment by julienmathis** [comment]
All this problem of size will be fixed in the next version of widget for mid september.

**Comment by florian-asche** [comment]
Hi Julien,
im now using Version 2.8.1 and the Problem still exists.

**Comment by kozfelipe** [comment]
Hi, the problem still exists in version 2.8.24

![image](https://user-images.githubusercontent.com/25208457/41853155-7dd28370-7863-11e8-83dd-3485f5a6fa0f.png)

after~30seconds it self-resize to proper dimension

![image](https://user-images.githubusercontent.com/25208457/41853241-bb0536de-7863-11e8-8a12-c7799f11c50e.png)

**Comment by kozfelipe** [comment]
@lpinsivy I found the error

mismatch file path at iframe causing delay on widget resize:
![image](https://user-images.githubusercontent.com/25208457/41855107-2fd246b0-7868-11e8-84ea-768e824a86d2.png)

the same issue may be applied to the other widgets:

![image](https://user-images.githubusercontent.com/25208457/41855273-95687904-7868-11e8-9b8e-41fbb3e35119.png)
