### ISSUE TITLE
Monitoring - Performances: Some work todo

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4226]
Hi,

i looked at the other pages, and they are quiet perfect i think. But the Performance page need much attention i think.
![todo](https://cloud.githubusercontent.com/assets/2785700/13496315/c437e2ea-e14f-11e5-9fa9-01624e3994a0.PNG)

**Comment by florian-asche** [comment]
If i click Split Components, and then Display Status, Split Components check is gone. There is maybe a missing variable on transmit ?

**Comment by florian-asche** [comment]
The change to different pages is not the same design like for example "Events Logs" page.

**Comment by florian-asche** [comment]
The place for "Display Status" and "Split Components" is not good, maybe better with the other "graph select options"

**Comment by florian-asche** [comment]
If i select many graphs with "Split Components" it is not working.

**Comment by lpinsivy** [comment]
split will be next to download icons for each graph. Not a global option

**Comment by lpinsivy** [comment]
@julienmathis can you correct split issue ?

**Comment by florian-asche** [comment]
@julienmathis it whould be great, if you could also take a look at #4159.

**Comment by lpinsivy** [comment]
split fixed by commit 1eeccb533f3e537b116a663f00ba860c2058cada

I'll move the split checkbox

**Comment by querwin** [comment]
Hello,

I re-open this tickets because there are still some issues.

- When I split component on a graph, it's impossible to go back to a graph with no split
- Research for services is not working
- When I show only one graph, click on it is not doing anything

**Comment by florian-asche** [comment]
Hi @querwin: If i add multiple services (in my example two) and try to use the "select interval" function, it didnt work.
