### ISSUE TITLE
Lorsque l'on supprime un hote ou un/des services, la configuration du poller n'apparait pas comme modifié.

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon#4227]
Bonjour,

Si l'on MODIFIE un service ou hote, la configuration apparait comme modifié dans Configuration > Collecteurs.
Lorsque l'on SUPPRIME un hote ou un/des services, la configuration du poller n'apparait PAS comme modifié dans Configuration > Collecteurs.

Est-ce normal ?
Selon moi, la configuration devrait être considéré comme modifiée dans les 2 cas.

**Comment by sboulianne** [comment]
Quentin, je l'ai ouvert dans la bonne section maintenant ? :D

Merci l'ami.

**Comment by lpinsivy** [comment]
We have to store for deleted host the ID of poller which monitored it in order to use this info.

**Comment by garnier-quentin** [comment]
En effet, c'est la bonne section, je confirme ;)

**Comment by julienmathis** [comment]
L'id est bien stocké. Normalement, a première vu, mon commit corrige bien le problème. Tests a prévoir en plus mais je pense que c'est bon.
