### ISSUE TITLE
[2.7.2] Duplicate poller

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4234]
Lorsqu'on duplique un poller dans Engine configuration il serait bon de ne pas configurer les variables

Temp directory (Onglet Files ==> Sous catégorie Files)
Embedded Perl initialization file (Onglet Admin ==> Sous catégorie Perl)

car cela génère des warnings inutiles lors de l'exportation de la configuration

**Comment by benoiteolas** [comment]
Je rebondi sur ce ticket, une duplication de devait elle pas dupliquer à l'identique ?
Cad avec aucune modification d'aucune sorte, parce que si des champs sont modifiés/ajoutés, on ne peut plus parler de duplication, et ça va nous induire en erreur.

**Comment by julienmathis** [comment]
Oui je suis d'accord avec le retour de @benoiteolas. On duplique ou on duplique pas. Si le poller de base est mal configuré, tant pis.

**Comment by Sims24** [comment]
Hello @julienmathis 

Je rebondis sur ce ticket car justement ce n'est pas une duplication "identique", si je duplique un poller qui ne m'affiche pas le warning, le poller dupliqué lui me l'affichera. Je suis bien également d'accord avec le postulat de @benoiteolas bien sur.

Le duplicate et le create n'utilisent probablement pas exactement la même requête pour le INSERT. 

Je pense qu'on peut réouvrir ce ticket, reproduit à l'instant sur une 2.7.4

Merci
