### ISSUE TITLE
[Centreon] [Poller-display] Enhance centreonExternalCommand.class.php

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4241]
Hi,

A nice things would be to allow poller display users to set a downtime from the poller display interface.

Thx,

**Comment by julienmathis** [comment]
Thanks @Sims24 !!!

**Comment by Sims24** [comment]
Thank you @julienmathis  :)

**Comment by querwin** [comment]
Don't succeed to add a downtime from my poller display. Ihave this error in my apache logs : 

sh: -c: line 1: syntax error near unexpected token `newline'
sh: -c: line 1: `" >>'
