### ISSUE TITLE
Meta Service average calculation is wrong when a service is NOK

### ISSUE THREAD

**Issue by cemir** [centreon/centreon#4244]
Hi,

when you create a Meta Service of calculation type average, you should be able to discard NOK values:

for example, I have temperature probes on my racks, so I created a meta service to have the average temperature of the room, from time to time, one or more probes are in status unknow,  so I have a drop in my average temperature.
This is not a correct behavior, if you have 3 services in a meta service, and one is not ok, you should divide by 2, not by 3.

Regards

**Comment by leoncx** [comment]
This issues must be created into https://github.com/centreon/centreon-plugins.

We will recreate this ticket.

**Comment by kduret** [comment]
An option must be created in metaservice form to skip unknown states

Furthermore, generated meta_command must use new centreon-plugins instead of check_meta

**Comment by julienmathis** [comment]
Meta service are now working with centreon-plugins
