### ISSUE TITLE
[centreon-acl] Too many hosts/services!!

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4245]
Hi,

I have a problem. I create an ACL group with:
- all hosts
- filter on a poller X

If the poller X doesn't have a host/service, my user sees all hosts!!! It comes from the following functions 'getFilteredPollers' in 'centAcl-Func.php'. We do:
```
if ($DBRESULT->numRows()) {
        $host = array();
}
```

My request returns nothing because i don't have hosts!! I cant remove the 'if': even if i don't have pollers filter selected it goes in the function! We need to check if there is poller filters selected or not.

I think we have the same problem for filtered host categories (it's like the same code).

**Comment by garnier-quentin** [comment]
We cache hosts by poller in hostPollerCache. Why we don't use it ? Oo
So many things to optimize.

**Comment by lpinsivy** [comment]
@garnier-quentin I made some test with this function and it works:

1) I create a new poller (enabled) without host and ACL ressource to link all hosts and filtered on poller without host.? The result is empty

2) I added the orhter poller with host to ACL resource and the result is the list of hosts link to this poller.

But when I use Centreon  web, I can show all hosts event if I use first case. I think problem is from centreonACL.class.php file

**Comment by garnier-quentin** [comment]
I don't know how have you done that. Because i have done the test and it seems to work how i said.
