### ISSUE TITLE
Admin are no longer viewable in ACL, needed to clean ACL

### ISSUE THREAD

**Issue by smutel** [centreon/centreon#4247]
Hello,

Normally admin does not need to be in ACL.
But in centreon 2.6: 
- Admin users are taken into account for the count calculation
- Admin users are not visible in ACL groups configuration
- You can add an admin to an ACL group though Contact configuration

The provided patch is to display admin in ACL (as previously in Centreon).

Thanks.

**Comment by lpinsivy** [comment]
Admin are not listed in ACL
