### ISSUE TITLE
[2.7.2] ACL not working with metaservice graphs

### ISSUE THREAD

**Issue by cemir** [centreon/centreon#4249]
Hi,

there is an issue with ACL on metaservice graphs.

I have a group called dc-users with those params :
ressource access : PDU
menu access : home monitoring reporting
actions access : simple user

PDU is configured this way :
linked groups : dc-users
hosts groups : PDU
meta service : hum, temp

the two metaservices are based on services on hosts in hostrgroups PDU

Users in group dc-users are able to see all graphs and statuses on hosts/services in hostgroup PDU
but are not able to see graphs of metaservices

Regards

**Comment by cemir** [comment]
Issue is still present in 2.7.4 :+1: 
non admin users are able to see the metaservice but not the graphs of the metaservice

**Comment by Sims24** [comment]
Hi, 

Confirm this issue as highly critical for shared Centreon. Please @julienmathis  and @lpinsivy  could you take a look quickly please :) ?!

**Comment by Sims24** [comment]
Hi, 

@kduret This issue is solved. Thanks for this fix, it works !

cc @cemir.
