### ISSUE TITLE
SNMP TRAP - recherche

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4250]
Se rendre sur "Configuration" ==> "SNMP TRAP"
Faire une recherche dans la barre de recherche et cliquer sur un des résultats de la recherche
Faire des modifications et sauvegarder

La recherche a disparu après la sauvegarde et on se retrouve avec la liste initiale.

**Comment by Sims24** [comment]
Bonjour Loic, 

Tu es bien en 2.7.2 ?

**Comment by lolokai** [comment]
Oui

**Comment by Sims24** [comment]
Ok en effet, il me semble que tu avais ouvert un autre ticket similaire sur une autre page non ? Si tu peux mettre la référence pour aider les devs à voir ce dont tu parles. 

Merci

**Comment by querwin** [comment]
Wrong ticket id on the previous commit

**Comment by lpinsivy** [comment]
Work with Centreon web 2.8.12
