### ISSUE TITLE
SQL Error when ACL user try to see Servicegroup data in dashboard

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#4252]
Hi,

There is a SQL Error (in Centreon 2.6.6) when we try to see ServiceGroup information in the dashboard, I have this in sql-error.log : 

`2016-03-11 09:24|0|0|DB Error: unknown error QUERY : (SELECT sg_id, sg_name FROM hostgroup_relation, servicegroup_relation,servicegroup,  acl_res_group_relations, acl_resources_hg_relations  WHERE acl_res_group_relations.acl_group_id  IN (77,62)  AND acl_resources_hg_relations.acl_res_id = acl_res_group_relations.acl_res_id   AND servicegroup_relation.hostgroup_hg_id = hostgroup_relation.hostgroup_hg_id  AND servicegroup.sg_id = servicegroup_relation.servicegroup_sg_id ) UNION ALL ( SELECT sg_id, sg_name FROM  servicegroup, acl_resources_sg_relations, acl_res_group_relations  WHERE acl_res_group_relations.acl_group_id  IN (77,62)  AND acl_resources_sg_relations.acl_res_id = acl_res_group_relations.acl_res_id  AND acl_resources_sg_relations.sg_id = servicegroup.sg_id ) ORDER BY sg_name`

When I copy/paste this request in SQL tab in my phpmyadmin I see this error "Column 'sg_id' in field list is ambiguous" and if we correct that, it's the same error for sg_name. I'm not sure if it's necessary to put servicegroup.sg_id and servicegroup.sg_name OR acl_resources_sg_relations.sg_id and acl_resources_sg_relations.sg_name.

Thanks in advance !

**Comment by Hellnino18** [comment]
Hi,

Do you have an explanation plz for thi bug?

Thanks.

**Comment by julienmathis** [comment]
deprecated.
