### ISSUE TITLE
Command check_meta

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4253]
Hello,

The command check_meta is defined in the file /usr/share/centreon/www/class/config-generate/meta_command.class.php .
You should use variable "Plugins Directory path" defined in "Administration --> Parameters --> Monitoring"

Regards,

**Comment by julienmathis** [comment]
Hello, 

Why do you want to configure this command ? Meta is automated, we don't want to manage specific paths...

**Comment by s-duret** [comment]
Hello,

I opened this ticket in march 2016 and you resolve it on july 2016:
https://github.com/centreon/centreon/commit/cd4e2b817895a9aae1e66f37e7affcc90ee3fb23#diff-c97ad7d7ca61ce6430e1539a3c5de166

Now, the code is good but it wasn't in march 2016

**Comment by julienmathis** [comment]
Thanks !
