### ISSUE TITLE
graphs are compulsory

### ISSUE THREAD

**Issue by gvieira-nr** [centreon/centreon#4255]
I have over 500+ hosts and 7000+ services which is creating over 60GB+ of RRD files
I can't see any way to completely disable RRD files for services I have no need for visual metrics whether it being the performance graphs or the Up vs Down graphs.
If there is a way, it doesn't appear to be clearly visible but looks like every service automatically gets it.

Tried deleting the graphs from administration but they come back. There must be a clearer/easier way.

Centreon 2.7.2

**Comment by lpinsivy** [comment]
To disable graphs you have to edit your Centreon Broker configuration of central poller and to remove "central-rrd-master" entry (this entry generate RRD file) and to edit "central-broker-master" entry by removing "centreon-broker-master-rrd" output

Regards

**Comment by gvieira-nr** [comment]
That would remove ALL graphing, won't it? I just need to be able to disable status/performance db and rrd file data for most of the unneeded services being monitored. eg check_process is a yes or no (1 or 0) and I don't need rrd/db data for it but it's generating totally useless graphs which is taking up disk space and useless entries in data_bin. And I have heaps of services doing the same sort of thing.

My data_bin has now grown to 130GB and I've only just added 8.7K services and have many more to go. Of course I could adjust retention to be shorter but that's removing good information of useful service data rather than remove pointless data from service checks which I only care to alert if it's up or down.

Wouldn't it be better to have a feature when adding a new service to not add it to the metrics (I think it was mentioned in your documentation as an index_data??) automatically which causes it to generate performance graphs?

**Comment by george-vieira** [comment]
ok, just found out the purging was failing with permission denied on the script itself. 
/usr/local/centreon/cron/centstorage_purge was set to 640 not 750 and neither is nightly_tasks_manager. not sure which install/upgrade may have had the bug.

I didn't realise until now the purging was called from a cron and not within the broker service so didn't notice until a google search showed it existed *embarrassed*

**Comment by gvieira-nr** [comment]
ok, just found out the purging was failing with permission denied on the script itself. 
/usr/local/centreon/cron/centstorage_purge was set to 640 not 750 and neither is nightly_tasks_manager. not sure which install/upgrade may have had the bug.

I didn't realise until now the purging was called from a cron and not within the broker service so didn't notice until a google search showed it existed embarrassed
