### ISSUE TITLE
Centreon plugins repository

### ISSUE THREAD

**Issue by TheRealEgor** [centreon/centreon#4257]
I hate to raise an issue, but I thought I was good at searching and have come up empty.  

I'd like to submit a change to the `check_centreon_snmp_remote_storage` which comes with the centreon-plugins-2.7.2-7.el6.noarch RPM.  The only place I found this on GitHub was in what appears to be an old centreon-community repository (https://github.com/Centreon-Community/centreon-discovery) and hasn't been updated for 3 years.  

The change is simple, and allows the end user to account for %reserved in EXT3 and EXT4 file systems.  

If someone could point me to the right repo so I can see what I missed and close the issue, I'd appreciate it.

**Comment by garnier-quentin** [comment]
It's here ;)
https://github.com/centreon/centreon-plugins

Look for the branch 2.7.x. But try to use new plugins if you can.

**Comment by TheRealEgor** [comment]
thanks!  It's in my backlog to switch over to the new hotness "centreon-plugins", but in the mean time, I'd be great to get `check_centreon_snmp_remote_storage` updated with the ability to account for EXT reserved space.
