### ISSUE TITLE
[2.7.2] «Split Components» manquant sur Mozilla Firefox ESR

### ISSUE THREAD

**Issue by wwattiez** [centreon/centreon#4259]
Bonjour,

J'ai remarqué que l'option split component de la partie performance ne s'affiche pas sur Firefox ESR.

Je n'ai par contre aucun souci sur chrome ou edge.

J'ai vu qu'une autre issue existait pour ce problème mais elle à été résolue depuis.

![image](https://cloud.githubusercontent.com/assets/17874906/13807835/890d739c-eb63-11e5-9c36-40b9314fd30e.png)

Pourriez-vous vérifier si vous arrivez a recréér le même comportement ?

Merci d'avance.

**Comment by florian-asche** [comment]
Hi, there is a new Version (2.7.3) out. Can you please try if the problem is solved?

**Comment by lpinsivy** [comment]
should be closed in Centeron web 2.8.x with new charts display
