### ISSUE TITLE
probleme avec $ dans une commande avec un regexp

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon#4260]
Bonjour,

C'est un problème avec une commande de vérification de la CPU d'un hôte ESX via le plugin centreon_plugins mais je post ici étant donné que c'est un problème d'écriture d'une commande.

Je ne voudrais avoir que le "cpu_total" de la commande suivante :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --connector-hostname 127.0.0.1 --mode cpu-host --esx-hostname=cbh197.bdxdom.mck --filter-perfdata "cpu_total"
**OK: 'cbh197.bdxdom.mck' Total Average CPU usage '17.21%' on last 5 min | 'cpu_total'=17.21%;;;0;100 'cpu_total_MHz'=5129.00MHz;;;0;29776**

Mais j'ai aussi le cpu_total_MHz

J'utilise un filter et voici le résultat :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --connector-hostname 127.0.0.1 --mode cpu-host --esx-hostname=cbh197.bdxdom.mck --filter-perfdata "cpu_total$"
**OK: 'cbh197.bdxdom.mck' Total Average CPU usage '16.81%' on last 5 min | 'cpu_total'=16.81%;;;0;100**

Ca marche super !!

Je créer la commande dans Centreon :
$USER1$/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode cpu-host --esx-hostname=$HOSTADDRESS$ --filter-perfdata "cpu_total$" --connector-hostname=127.0.0.1

Et la ça plante. J'ai l'impression que c'est lié au "$". Si je l'enlève, la commande fonctionne mais du coup j'ai aussi le MHz.

J'ai aussi essayé avec un \$ et même problème.

Comment on peut faire une regexp dans une commande avec un $ pour que ça fonctionne ?

Merci pour le coup de main.

**Comment by garnier-quentin** [comment]
Hi,

To use the dollar character in a command, you need to write it twice: $$

**Comment by gerpion** [comment]
Hey Quentin,
Works great, thanks.
