### ISSUE TITLE
[2.7.4] Can't reload poller

### ISSUE THREAD

**Issue by kohl42** [centreon/centreon#4263]
Hi there,

Since fresh update this morning we can't reload/ restart pollers from the web interface. The icon is just not there anymore. Is this wanted?

**Comment by querwin** [comment]
Hello,

The system has changed. Now you can choose several pollers and use Apply Configuration.

ok for you ?

Regards,

**Comment by kohl42** [comment]
I see what you mean, as I could access through an old URL in my browser history. But I don't see how I can reach that page from the Web Interface itself. 
When I go in configuration > Pollers, I see my pollers, I can edit and all BUT no menu or icon to order them to restart.

I'm not sure I am clear... I just don't see wherefrom I can restart the poller since the upgrade.

**Comment by querwin** [comment]
You can see the new process in the attached screenshot.
![pollers](https://cloud.githubusercontent.com/assets/7510531/13813775/aa20c514-eb83-11e5-8506-3eb234c67ad4.png)

**Comment by kohl42** [comment]
ah, ok thanks! 
I wondered what that new button was for =)
