### ISSUE TITLE
Usability regression - graph display has been limited dramatically

### ISSUE THREAD

**Issue by TheRealEgor** [centreon/centreon#4266]
In previous version of Centreon I could access Views -> Graphs and view graphs in several different ways:

1.) By service groups - check box, all graphs in that service group show up.
2.) Pick a few hosts and view individual graphs easily (check boxes)

My hosts which have checks *entirely* based on HostGroups have no ability to locate the services by accessing the Monitoring -> Performances tab.  

Has this moved somewhere else, or were these features removed in 2.7.2 ?

**Comment by lpinsivy** [comment]
In Centreon Web 2.7.0 we remove access by servicegroups and by hostgroups.

You have to select services by adding host or by seleting services

**Comment by TheRealEgor** [comment]
If I understand your comment correctly and if I look at the new interface, what I used to be able to setup as a _Service Group_ with 35 unique services in Centreon configuration, and then "check" the box to view all the graphs for that specific Service Group, now I'm required to select all 35 different unique services every time I want to compare or analyze the graphs?

One checkbox 
![screen shot 2016-05-03 at 2 11 44 pm](https://cloud.githubusercontent.com/assets/11574720/14995276/947d72b2-1139-11e6-850d-5eb3a7b33ec4.png)
vs start typing each of 35 services, add them, and you can't save a view so you have to do that every time.
![screen shot 2016-05-03 at 2 16 30 pm](https://cloud.githubusercontent.com/assets/11574720/14995327/d82fabf6-1139-11e6-88d0-c6f9feb4430d.png)

If that is how it is going to stay, it is a feature or usability regression.

**Comment by lpinsivy** [comment]
Hi we re-add hostgroups and servicegroups filter for Centreon v2.8 version.

Regards,
