### ISSUE TITLE
[2.7.3] Select component bug (or enhancement request?)

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4267]
Hi team,

When selecting items with the new select component, it disapears after each selection. This is very annoying when you have to select a lot of items.

Please find video record here : https://cloudbox.it-optics.com/pydio/data/public/de9f30 (60 days valid link)

Could be related to https://github.com/centreon/centreon/issues/4173

Thank you for advance

**Comment by julienmathis** [comment]
Hello, 

I don't understand. You have now in 2.7.3 the possibility to : 
- select your items with search, 
- clic on items to add them to the form
- or clic on "select all" button to win a lot of time
- or select multiple items with shift key management 
- or select multiple items with crtl key management (linux and windows only)

What do you want more ?

**Comment by gslongo** [comment]
Hi,

Aaaahh

Then maybe I make something wrong but "select multiple items with shift key management" do no seems to work for me (Linux 64, latest Firefox ESR and latest Chrome). With this feature working then, yeah, it is complete :-)

**Comment by gslongo** [comment]
Dear Julien,

Could you confirm the "shift key management" feature should be working on Linux ?
I've tested on FF ESR38, FF45 (qualify ESR) and Chrome

Thank you

**Comment by julienmathis** [comment]
yes I confirm :)

**Comment by gslongo** [comment]
OK.. It is not working for me... How could I help?

**Comment by julienmathis** [comment]
this has been now improved. deprecated.
