### ISSUE TITLE
Command 'Perl Connector' was not found

### ISSUE THREAD

**Issue by PhilCANDIDO** [centreon/centreon#4272]
Hello,

After upgrade to Centreon 2.6 to 2.7 we have a problem when we try to use Perl connector.

In fact, when we add a command to a use it with a perl connector, we have an issue during the generating configuration process.

We have the following message : 
![2016-03-18_08h09_31](https://cloud.githubusercontent.com/assets/13585152/13870972/028129ca-ece1-11e5-973d-33c613d1d92d.png)

> _Reading main configuration file '/usr/share/centreon/filesGeneration/nagiosCFG/1/nagiosCFG.DEBUG'.
> Reading resource file '/usr/share/centreon//filesGeneration/nagiosCFG/1/resource.cfg'
> **Command 'Perl Connector' was not found**
> **Command 'Perl Connector' was not found**
> Checking global event handlers...
> Checking obsessive compulsive processor commands...
> 
> Checked 15 commands.
> Checked 0 connectors.
> Checked 6 contacts.
> Checked 0 host dependencies.
> Checked 0 host escalations.
> Checked 3 host groups.
> Checked 87 hosts.
> Checked 0 service dependencies.
> Checked 0 service escalations.
> Checked 0 service groups.
> Checked 858 services.
> Checked 7 time periods.
> 
> Total Warnings: 9
> Total Errors: 2_

When we look the files generated, we can see that the file connectors.cfg is empty.
![2016-03-18_08h12_18](https://cloud.githubusercontent.com/assets/13585152/13871000/3283e270-ece1-11e5-8940-1e21e4e3db63.png)

The problem is not blocking, but is on all Centreon architecture in v2.7.3.

**Comment by kadrika** [comment]
I think this is the issue we also had, and we fixed it like in here: https://github.com/centreon/centreon/issues/4045#issuecomment-195320487

**Comment by george-vieira** [comment]
what do you see in Configuration -> Commands -> Connectors?
Both perl and ssh connector should be defined there.

**Comment by PhilCANDIDO** [comment]
Yes, the connectors command are set correctly : 
![2016-03-18_09h23_47](https://cloud.githubusercontent.com/assets/13585152/13872491/525459ae-eceb-11e5-9fb8-cf7192879131.png)

The resource $USER3$ corresponds to the binary path : 
![2016-03-18_09h26_59](https://cloud.githubusercontent.com/assets/13585152/13872534/9b154720-eceb-11e5-8040-92d60a912f41.png)

In the poller definition the connector path is alos set correctly : 
![2016-03-18_09h28_19](https://cloud.githubusercontent.com/assets/13585152/13872557/cfc25580-eceb-11e5-85eb-ea6f6a7b4954.png)

**Comment by Sims24** [comment]
Hi Philippe, 

I think that if you remove $USER3$ from your connector definition like below 

![image](https://cloud.githubusercontent.com/assets/12429463/13904384/bbb7f50e-ee9e-11e5-839c-26dbb97ba048.png)

And set /usr/lib64/centreon-connector/ instead of /usr/lib64/centreon-connector (trailing slash is important I think). 

Will try to find the release note where there is a mention about this change.

**Comment by julienmathis** [comment]
@PhilCANDIDO Which version of Centreon ? 2.7.3 ?

**Comment by PhilCANDIDO** [comment]
@Sims24 I have add the '/' in the definition of the resource $USER3$ : 
![2016-03-23_08h06_55](https://cloud.githubusercontent.com/assets/13585152/13978077/677a2d86-f0ce-11e5-889e-65b740f7b26f.png)

On the connector definition I have delete the path : 
![2016-03-23_08h07_40](https://cloud.githubusercontent.com/assets/13585152/13978079/7c3d32f4-f0ce-11e5-992f-af10d4383b7b.png)

But the problem is the same.

As this does not solve the problem, I putted the old configuration.

**Comment by PhilCANDIDO** [comment]
Hello @julienmathis , the version of Centreon is 2.7.3.

![2016-03-23_08h13_43](https://cloud.githubusercontent.com/assets/13585152/13978167/3303d01a-f0cf-11e5-8580-c8d275b7a13b.png)


This problem appeared after an update from version 2.6.6 to 2.7.3 Centreon.

**Comment by Sims24** [comment]
Hi @PhilCANDIDO

What if you add the laste '/' on the poller definition and not in the macro definition ? 

Regards

**Comment by PhilCANDIDO** [comment]
I tested and the problem is the same.

**Comment by george-vieira** [comment]
you need to eliminate all possible things that could be causing the problem. to start off with, dont use macros, put the full path to the connector and eliminate that as the cause. then move onto other things.
deleting the path makes it run in the users (centreon-engine) home dir and use the $PATH environment, not reliable. This is why I said to use full path in the command line part.

Did ou also check logs for any messages, just a guess..
Have you tried running the binary and see if it throws any weird issues due to compiling errors or (guess some strange error here)...

**Comment by milect** [comment]
Hi, 
I have same problem..
problem start with generate config..

Reading main configuration file '/usr/share/centreon/filesGeneration/nagiosCFG/2/nagiosCFG.DEBUG'.
Warning temp_path variable ignored
Reading resource file '/usr/share/centreon//filesGeneration/nagiosCFG/23/resource.cfg'
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found

......


cat /usr/share/centreon//filesGeneration/nagiosCFG/23/connectors.cfg
###################################################################
#                                                                 #
#                       GENERATED BY CENTREON                     #
#                                                                 #
#               Developped by :                                   #
#                   - Julien Mathis                               #
#                   - Romain Le Merlus                            #
#                                                                 #
#                           www.centreon.com                      #
#                For information : contact@centreon.com           #
###################################################################
#                                                                 #
#         Last modification 2016-09-08 20:57                      #
#         By unknown                                              #
#                                                                 #
###################################################################


conectors are missing.



version before upgrade:

cat /usr/share/centreon//filesGeneration/nagiosCFG/2/connectors.cfg
###################################################################
#                                                                 #
#                       GENERATED BY CENTREON                     #
#                                                                 #
#               Developped by :                                   #
#                   - Julien Mathis                               #
#                   - Romain Le Merlus                            #
#                                                                 #
#                           www.centreon.com                      #
#                For information : contact@centreon.com           #
###################################################################
#                                                                 #
#         Last modification 2016-09-02 13:43                      #
#         By unknown                                              #
#                                                                 #
###################################################################

define connector {
    connector_name                 Perl Connector
    connector_line                 /usr/lib64/centreon-connector/centreon_connector_perl
}

define connector {
    connector_name                 SSH Connector
    connector_line                 /usr/lib64/centreon-connector/centreon_connector_ssh
}

**Comment by george-vieira** [comment]
stupid question but does it exist? 
I highly recommend those who are building servers from scratch and use debian(possibly ubuntu) to use this 1 script fully automated installer from https://github.com/GreenCom-Networks/centreon-install/
I use it all the time and helped a little bit on improvements.
