### ISSUE TITLE
[2.7.3] Poller Notification

### ISSUE THREAD

**Issue by Thiefoumongars** [centreon/centreon#4274]
Bonjour,

A partir de la version 2.7, la possibilité de désactiver toutes les notifications d'un poller à été retiré.
Est ce possible de la remettre en place ?
Avez vous un workaround en attendant ?

Cette option était utilisé dans le cadre d'une maintenance global d'une infrastructure ou d'un test de "disaster recovery", cela nous permettait de ne pas etre spamé et de suivre via l'interface web l'évolution et le status de nos Serveurs, services.

Par avance, merci

**Comment by Shini31** [comment]
Bonjour,

Vous pouvez toujours désactiver les notifications au niveau du moteur de supervision dans Configuration -> Pollers -> Engine configuration -> _Poller de votre choix_ -> Check Options -> Notifications

Cordialement.

**Comment by julienmathis** [comment]
Thank's @Shini31 !
