### ISSUE TITLE
Generate new Config not working

### ISSUE THREAD

**Issue by anismaj** [centreon/centreon#4275]
Hello,

When i click appy configuration, it's not working ( stopped at Progress (0%)	0% Preparing environment...)

![image](https://cloud.githubusercontent.com/assets/10830452/13875053/e4f7b732-ecfb-11e5-90d9-c3a875f4b137.png)

**Comment by jben94** [comment]
Hi,

Add the pollers in one line before apply configuration.

**Comment by julienmathis** [comment]
Yes ;) Select a poller please :)
