### ISSUE TITLE
[2.7.3] Configuration: host disabled = services unvisible

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#4276]
Hello,
when a host is disabled in configuration all of the attached services are hidden and, thus, they can't be modified.

**Comment by julienmathis** [comment]
yes. This has been changed in Centreon 2.6 motivated by multiple used asks....

**Comment by golgoth31** [comment]
Ok,
thanx for the answer.
Could you add a switch in the options to enable/disable this behavior, please ?

**Comment by lpinsivy** [comment]
implemented in Centreon web 2.8.x by a checkbox to display disabled hosts
