### ISSUE TITLE
Custom macros not evaluated in action_url

### ISSUE THREAD

**Issue by kohl42** [centreon/centreon#4277]
Since Centreon Web 2.7.x, we can't use custom links in action URL anymore, they don't get evaluated.
It was working on earlier version of Centreon Web.

For example :
`http://$HOSTADDRESS$:$_SERVICEHTTPPORT$/$_SERVICEMODULE$/test/about.html`

Only HOSTADDRESS gets translated.

**Comment by julienmathis** [comment]
I think there are no changes in 2.7 compared to 2.6. This has never been implemented.

**Comment by kohl42** [comment]
Well, then it didn't work on purpose but it worked. And it was pretty swell when you have many environnement running the same programs and you wanna create dynamic action link.

Can it be marked as wanted feature then?

**Comment by lpinsivy** [comment]
Done for action/notes URL for hosts and services in page "Status Details  >  Services"

Regards

**Comment by querwin** [comment]
I've got "About Blank" when I try to add link with custom maccro on host template and on service.

It's OK when I add link on service template and on host

**Comment by querwin** [comment]
My bad, typo error when I test

**Comment by Hellnino18** [comment]
Hi,

I'm in Centreon 2.6.6 (always...) the patch is working for Hosts and Services in page "Status Details > Services". But in Home (I think the file is tacticalOverviewXml.php) the SERVICE MACRO is not evaluated. The MACRO is set on the template $_SERVICEARG1$, in tactical overview I have in URL : %24_SERVICEARG1%24

Is it possible to correct this plz ?


Thx!
