### ISSUE TITLE
Massive submitPassivResults

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4281]
Bonjour,

Est-ce possible de faire un envoie massif de résultat pour les checks passives ?

Cordialement.

**Comment by julienmathis** [comment]
Salut, 

Par un web service ? Ou depuis l'interface web ?

**Comment by jben94** [comment]
Salut,

Si les deux solutions sont possibles, je suis preneur !
Mais de préférence depuis l'interface WEB.

**Comment by lpinsivy** [comment]
linked to #4350
