### ISSUE TITLE
Scroll bar in "Configuration - Hosts - Host Groups"

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4282]
Hi,

In Centreon 2.7.3 scroll bar in "Configuration - Hosts - Host Groups" > Linked Hosts, scroll bar is not available.

Best Regards

**Comment by bmareau** [comment]
Hi,

Problem is always present with : 
- Firefox (51.0.1)
- Centreon Web 2.7.x

Best regards

**Comment by BenoitPoulet** [comment]
Still present on Centreon Web 2.7.8 under :

- Google Chrome, Version 56.0.2924.87, Windows 10 64 bits
