### ISSUE TITLE
[2.7.3] Upgrade from 2.6.6 to 2.7.3, hostgroup widget issue

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4285]
Dear Team,

I've just upgraded a CES server from 2.6.6 to 2.7.3.
I've also updated widgets (by the web interface)

> [root@centreon ~]# rpm -qa|grep centr
> centreon-broker-storage-2.11.3-1.el6.x86_64
> centreon-broker-cbd-2.11.3-1.el6.x86_64
> centreon-widget-hostgroup-monitoring-1.3.0-4.el6.noarch
> centreon-broker-cbmod-2.11.3-1.el6.x86_64
> centreon-base-config-centreon-engine-2.7.3-9.el6.noarch
> centreon-widget-servicegroup-monitoring-1.3.0-4.el6.noarch
> centreon-widget-service-monitoring-1.4.2-1.el6.noarch
> centreon-connector-1.1.2-1.el6.x86_64
> centreon-engine-extcommands-1.5.0-10.el6.x86_64
> centreon-broker-core-2.11.3-1.el6.x86_64
> centreon-web-2.7.3-9.el6.noarch
> centreon-lang-fr_FR-2.7-2.el6.noarch
> centreon-widget-host-monitoring-1.4.2-1.el6.noarch
> centreon-connector-perl-1.1.2-1.el6.x86_64
> centreon-nagvis-1.1.1-3.el6.noarch
> centreon-common-2.7.3-9.el6.noarch
> centreon-plugins-2.7.3-9.el6.noarch
> centreon-engine-1.5.0-10.el6.x86_64
> centreon-plugin-meta-2.7.3-9.el6.noarch
> centreon-widget-graph-monitoring-1.3.0-3.el6.noarch
> centreon-clib-1.4.2-1.el6.x86_64
> centreon-perl-libs-2.7.3-9.el6.noarch
> centreon-trap-2.7.3-9.el6.noarch
> centreon-broker-2.11.3-1.el6.x86_64
> centreon-2.7.3-9.el6.noarch
> centreon-connector-ssh-1.1.2-1.el6.x86_64
> centreon-engine-daemon-1.5.0-10.el6.x86_64
> [root@centreon ~]# lsb_release -a
> LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
> Distributor ID:	CentOS
> Description:	CentOS release 6.7 (Final)
> Release:	6.7
> Codename:	Final
> 

The problem is hostgroup widgets are not complete. This problem has been validated on Firefox 45 and Chrome (latest).
Browser cache empty

![capture-centreon - it network monitoring - mozilla firefox-2](https://cloud.githubusercontent.com/assets/5636906/14013190/48e97934-f1ab-11e5-85a7-b2d1bd04e320.png)
![capture-centreon - it network monitoring - mozilla firefox-3](https://cloud.githubusercontent.com/assets/5636906/14013197/4fd8f314-f1ab-11e5-9c8b-ebfb341a81bf.png)

What is strange is the problem does not happens on another CES install, same version 2.7.3 : 
![capture-centreon - it network monitoring - mozilla firefox](https://cloud.githubusercontent.com/assets/5636906/14013208/628b7266-f1ab-11e5-8d08-5094b5d5e34a.png)

What's your mind about this ?

Maybe related to : https://github.com/centreon/centreon/issues/4214

This is a production server and is very annoying

Thank you !

**Comment by gslongo** [comment]
Dear team,

here is extract of log messages (httpd) :

`[Tue Mar 29 08:29:32 2016] [error] [client 192.168.0.121] PHP Notice:  Undefined index: entries in /usr/share/centreon/www/widgets/hostgroup-monitoring/src/index.php on line 123, referer: http://centreon/centreon/widgets/hostgroup-monitoring/index.php?widgetId=33&customViewId=1
[Tue Mar 29 08:29:32 2016] [error] [client 192.168.0.121] PHP Notice:  Undefined index: entries in /usr/share/centreon/www/widgets/hostgroup-monitoring/src/index.php on line 123, referer: http://centreon/centreon/widgets/hostgroup-monitoring/index.php?widgetId=33&customViewId=1
[Tue Mar 29 08:29:32 2016] [error] [client 192.168.0.121] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/widgets/hostgroup-monitoring/src/index.php on line 131, referer: http://centreon/centreon/widgets/hostgroup-monitoring/index.php?widgetId=33&customViewId=1
[Tue Mar 29 08:29:33 2016] [error] [client 192.168.0.121] PHP Notice:  Undefined index: entries in /usr/share/centreon/www/widgets/hostgroup-monitoring/src/index.php on line 123, referer: http://centreon/centreon/widgets/hostgroup-monitoring/index.php?widgetId=3&customViewId=1
[Tue Mar 29 08:29:33 2016] [error] [client 192.168.0.121] PHP Notice:  Undefined index: entries in /usr/share/centreon/www/widgets/hostgroup-monitoring/src/index.php on line 123, referer: http://centreon/centreon/widgets/hostgroup-monitoring/index.php?widgetId=3&customViewId=1
[Tue Mar 29 08:29:33 2016] [error] [client 192.168.0.121] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/widgets/hostgroup-monitoring/src/index.php on line 131, referer: http://centreon/centreon/widgets/hostgroup-monitoring/index.php?widgetId=3&customViewId=1`

Thanks

**Comment by gslongo** [comment]
By upgrading pear packages, it seems there is no error in the log files anymore. However, the widget is still not working ...

**Comment by gslongo** [comment]
Dear team,

I don't know what is happening but I have now only some hostgroups which are displayed (correctly) o_O All of the other hostgroups are not shown Ô_Ô
This definitely looks like a bug

Thanks

**Comment by gslongo** [comment]
Again,

I've found something :

1.  I create a new fictive host and add it to ALL hostgroups
2. I generate the config
3. The widget displays all host groups :

![capture-centreon - it network monitoring - mozilla firefox-1](https://cloud.githubusercontent.com/assets/5636906/14173277/31122706-f73d-11e5-850b-17cd8b949ef2.png)

4. I remove the fictive host
5. I Generate the configuration again
6. The widget is not up to date (even after a couple of minutes)

![capture-centreon - it network monitoring - mozilla firefox-2](https://cloud.githubusercontent.com/assets/5636906/14173297/58583102-f73d-11e5-9b80-1a123aa07c86.png)

7. The hostgroup monitoring page seems to be correct 

![capture-centreon - it network monitoring - google chrome](https://cloud.githubusercontent.com/assets/5636906/14173309/69e13356-f73d-11e5-9f8c-0c38a98e8595.png)

**Comment by BornToBeRoot** [comment]
We have the same issue after the upgrade from 2.6.6 to 2.7.3

Are there any new informations about this?

**Comment by BornToBeRoot** [comment]
Fixed by restarting the services:

```
/etc/init.d/centengine restart
/etc/init.d/cbd restart
```

**Comment by lpinsivy** [comment]
The widget is based on centreon_storage database filled by Centreon Broker from Centreon engine data.

**Comment by gslongo** [comment]
Dear Team,

The issue mentionned here : https://github.com/centreon/centreon/issues/4285#issuecomment-203873763 is still opened for us.

Restarting service doesnt make any change

We are running on 2.7.4

Could you please have a look ?

Thank you for advance
