### ISSUE TITLE
[2.7.3] [GRAPHS] No zoom feature anymore ?

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4286]
Dear Team,

Since the update to 2.7.X there is no zoom feature anymore in graph view page. In the past there was an icon available to make zoom faster. Now it disapeared. 
There is a "Select Interval" icon but I don't know how to use it and what it does.. nothing happens when I click on it

![capture-centreon - it network monitoring - mozilla firefox-4](https://cloud.githubusercontent.com/assets/5636906/14013545/595308c4-f1ad-11e5-988b-d2d37d4e5165.png)

Can you bring back this feature again ?

Thank you for advance,

Best regards,

**Comment by gslongo** [comment]
Thanks !

What is the release date of 2.7.4 ?

**Comment by julienmathis** [comment]
link to #4304
