### ISSUE TITLE
unable to link a host category to a host template

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4290]
Hello,

With centreon 2.7.3, I go the configuration page of a host template and, i add a host category and i save the modifications. But when i go back to same page the host category is no present anymore.

But when i go to the configuration page of a host category and i add a host template, the changes are saved normally.

**Comment by lpinsivy** [comment]
linked to #4268

**Comment by tseegers** [comment]
Hi,

Unfortunatly the problem is not solved with the version 2.7.4: When a host doesn't inherit of any macro, there is no problem. But when a host inherits a macro from a template, the problem happens. We need to delete the macro of the host, modify the host categories and save the changes, like this the changes are handled

**Comment by lpinsivy** [comment]
@tseegers in your case the problem is from another issue. You define in your template a custom macro named "SNNMPVERSION" but this macro is already present in host form. That's why you can save the form.
