### ISSUE TITLE
[2.7.3] (Services) Widget issue(s) -- Initial box sizing not correct

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4293]
Hi the Team,

I've found a bug on latest version. It happens at least on services widget and on Firefox ESR 45 (not on Google-Chrome).

The box size is not correct at the initial display. Clicking on "refresh" action resizes the box to the configured size.

Please see demo attached here :

https://cloudbox.it-optics.com/pydio/data/public/f3d1e1
(link valid for 60 days)

Thank you for advance !

**Comment by florian-asche** [comment]
Hello,

i can confirm this problem. It also appears in version 2.7.4

Regards,
Florian
