### ISSUE TITLE
ACL generation of configuration

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4294]
Hello,

In Centreon 2.7.3, when i give only one menu access:
![001](https://cloud.githubusercontent.com/assets/13485588/14105528/6c677f6e-f5ac-11e5-9f0e-c61235d89187.PNG)
And when i connect with this user, this is the page that the user see:
![0002](https://cloud.githubusercontent.com/assets/13485588/14105565/a8372350-f5ac-11e5-8406-987fcbf823cf.PNG)
The user cannot generate the configuration, he doesn't have access to any page of the poller.

In addition, in the ACL configuration, the buttons 	"No access   - Read/Write   - Read Only" are not present anymore:
![0004](https://cloud.githubusercontent.com/assets/13485588/14105631/1ba0bed2-f5ad-11e5-8768-14762e90cdee.PNG)

But i guess i should see this instead
![0006](https://cloud.githubusercontent.com/assets/13485588/14105668/5206392a-f5ad-11e5-81dd-f3a9070dc2ca.PNG)

Regards,

**Comment by querwin** [comment]
Fixed in 2.7.4 I think
