### ISSUE TITLE
Fix problem of labels with specials chars

### ISSUE THREAD

**Issue by julienmathis** [centreon/centreon#4295]
In the 2.7.3 version, encoding of database fields is not ok. We have develop a migration script in order to set data to the correct encoding type (UTF-8).

This script will be launch during the upgrade step.

**Comment by gslongo** [comment]
Hi Julien,

Could it be related to this issue ? https://github.com/centreon/centreon/issues/4285

Thanks !

**Comment by julienmathis** [comment]
hello @gslongo 

I don't think so. But we will check the #4285 

Regards
