### ISSUE TITLE
display arrangement

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4296]
Hi team,

It's impossible to see other templates selected, cannot possible to grow up the size of the windows?
![cap 2016-03-29 a 17 21 09](https://cloud.githubusercontent.com/assets/10330979/14113400/126bcd7c-f5d3-11e5-81c6-5311f32c5cc7.png)

Thanks

**Comment by querwin** [comment]
In 2.7.3, you can scroll in the case, if you want to see more service templates

**Comment by julienmathis** [comment]
Works for me
