### ISSUE TITLE
Centreon-Plugins - Checkboxes

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4297]
Hi,

if disable:

> Enable pagination and more actions

we dont need the checkboxes. There we can save some space for text.

**Comment by lpinsivy** [comment]
Hi @florian-asche 

Can you explain this issue because I don't understand it.

Regards,

**Comment by florian-asche** [comment]
Hi,

ok. No problem. One picture tells more than 1000 words. So here a screenshot.

![123](https://cloud.githubusercontent.com/assets/2785700/14259840/143a0738-faa9-11e5-9241-9190a3e88779.png)

**Comment by garnier-quentin** [comment]
More for centreon-widget but if there is no action, we shouldn't display the checkbox. You're right ;)

**Comment by lpinsivy** [comment]
Close and reoppen on https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/issues/45
