### ISSUE TITLE
Extend monitoring filters (multiselect + new filters)

### ISSUE THREAD

**Issue by jcduss59** [centreon/centreon#4299]
Hello,

It should be great to add the following filter in the monitoring views :
- A checkbox filter to select/unselect poller (when you got more than 10 pollers it is usefull) from the views
- A checkbox filter to select/unselect hostgroup/services groups from the views
- A filter to choose to display/hide downtimed services/hosts
- A filter to choose to display/hide acknowledged services/hosts

Thank you,
JC.

**Comment by lpinsivy** [comment]
Hi when you talk about "checkbox filter" you talk about multi select ?

**Comment by jcduss59** [comment]
In the monitoring view (and why not configutration) add the possibility to select (with check box is zone way to do it) one or more poller in the dropdown list. Not to filtre by only one poller at a time.

**Comment by zd14a** [comment]
Hello,

I'd like to bring up this topic again. We realized, that there is currently no possibility to list all acknowledged services/hosts. In older Centreon versions this filter was available under  Monitoring  -> Services ->  Details ->  Acknowledged

So it would great if you could add the filter, maybe in the "Service/Host status" dropdown, again.

Thanks in advance.

**Comment by Moujimouja** [comment]
Hi, 

With evolution between 2.8 and 19.10 you could search with come criteria that already solve a part of the problem.

With the new [event page in 20.04](https://docs.centreon.com/current/en/alerts-notifications/events-view.html#docsNav), you can now start filtering as you're expecting.

This view is in beta and will be improved and new filtering mechanism will be added.

I close the ticket
