### ISSUE TITLE
[2.7.3] [CRITICAL] Time informations in hosts/services. Bug or bad configuration ?

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4300]
Hi the team,

Today I discovered an issue with the time displayed in hosts/services page.
I'm under 2.7.3 and this is an upgraded install from 2.6.6 to 2.7.3. The 2.6.6 have not this issue (i'm sure).

There is a time drift of one hour between the server time and the interface (look at last check/next check) :

![capture](https://cloud.githubusercontent.com/assets/5636906/14168578/5ffb0228-f723-11e5-9cf4-35cfcc74190d.png)

- The server timezone is correct
- The php.ini timezone is correct
- The timezone web interface setting (Administration) is correct

What is your mind about this ?

Thanks

**Comment by querwin** [comment]
Hello,

What about the user timezone ? 

You can try to click on Admin (top right) and set a timezone. You'll need to deconnect / connect to see effects.

**Comment by gslongo** [comment]
Hi

As said timezone in admin parameters is set to the correct value

Thanks

**Comment by gslongo** [comment]
Dear querwin,

Looking into the code of centreonGMT.class.php I found function getMyGTMFromUser. Just for testing I did a timezone massive change to all users (some of them did not have any timezone set).
Now the time is correctly displayed. I don't know why gobal timezone was not used.

Maybe you should have a look that way

Regards

**Comment by querwin** [comment]
The logical view should be : 
- If the user have a timezone in its configuration, if he show a date, so this date is linked to his timezone
- If the user does not have a timezone and the global timezone is configured so if he shows a date, this date is linked to the global configuration.
-  If the user does not have a timezone, there is no global timezone, date are linked to the php.ini timezone.

I will look if all is OK about this in Centreon
