### ISSUE TITLE
[Feature Request] custom notification

### ISSUE THREAD

**Issue by tanguyvda** [centreon/centreon#4301]
A customer is asking for the possibility to customize the style of the notifications he receives.

For example making it looks like a table 

| **type**  | _RECOVERY_      | 
| **host**  | _tanguy_contact_ |
| **state** | _UP_                     | 
...

and the possibility to configure the background color of the cell, things like that. 

He mentioned having notifications templates in centreon to handle this.

---

Un client demande à avoir la possibilité de personnaliser le style des notifications qu'il reçoit

par exemple avoir un format type tableau 

| **type**  | _RECOVERY_      | 
| **host**  | _tanguy_contact_ |
| **state** | _UP_                     | 
...

et la possibilité de configurer la couleur du fond de la cellule entre autres choses

Il a évoqué le fait d'avoir des template de notification dans Centreon pour gérer ceci.

**Comment by masgo** [comment]
Do you mean e-mail notifications? This is already possible by changing the template. Go to `Configuration  >  Commands  >  Notifications` and look for the template you use, e.g., `host-notify-by-email`

There you find the `printf` command which is used to generate the mail body which is then piped to the mailer.

**Comment by lpinsivy** [comment]
linked to #5163
