### ISSUE TITLE
[2.7.3] Services configuration page, display bug

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4302]
Hi the team,

It seems I found an anoying bug on the services configuration page: From what I know, in this page, services in yellow/orange mean it are applied to multiple hosts. However, I've found services applied on only 1 host which are in orange : 

Please see video screenrecord : https://cloudbox.it-optics.com/pydio/data/public/2a5c87
(link is valid for 60 days)

This might be related to services which was applied to multiple hosts in the past.

What is your mind about it ?

Thank you for advance,

Best regards

**Comment by kadrika** [comment]
I have noticed the same thing,but I always had a host that was disabled that had this service. But it is quite hard to find out to which disabled host that service is also attached to.

**Comment by querwin** [comment]
Well done kadrika, it happens when the service is linked to disabled host.

We must improve help in order to explain this

**Comment by julienmathis** [comment]
can you give me the result of the following sql query on centreon DB : 
show create table host_service_relation;

I think you have constraint problem that provocate ghost entries in host_service_relation table.

**Comment by gslongo** [comment]
Here is :

`MariaDB [centreon]> show create table host_service_relation;
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                 | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| host_service_relation | CREATE TABLE `host_service_relation` (
  `hsr_id` int(11) NOT NULL AUTO_INCREMENT,
  `hostgroup_hg_id` int(11) DEFAULT NULL,
  `host_host_id` int(11) DEFAULT NULL,
  `servicegroup_sg_id` int(11) DEFAULT NULL,
  `service_service_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`hsr_id`),
  KEY `hostgroup_index` (`hostgroup_hg_id`),
  KEY `host_index` (`host_host_id`),
  KEY `servicegroup_index` (`servicegroup_sg_id`),
  KEY `service_index` (`service_service_id`),
  KEY `host_service_index` (`host_host_id`,`service_service_id`),
  KEY `host_host_id` (`host_host_id`,`service_service_id`),
  CONSTRAINT `host_service_relation_ibfk_1` FOREIGN KEY (`hostgroup_hg_id`) REFERENCES `hostgroup` (`hg_id`) ON DELETE CASCADE,
  CONSTRAINT `host_service_relation_ibfk_2` FOREIGN KEY (`host_host_id`) REFERENCES `host` (`host_id`) ON DELETE CASCADE,
  CONSTRAINT `host_service_relation_ibfk_3` FOREIGN KEY (`servicegroup_sg_id`) REFERENCES `servicegroup` (`sg_id`) ON DELETE CASCADE,
  CONSTRAINT `host_service_relation_ibfk_4` FOREIGN KEY (`service_service_id`) REFERENCES `service` (`service_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1814 DEFAULT CHARSET=utf8 |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
`

**Comment by julienmathis** [comment]
Ok it seems that it's ok. 

Can you check if the service concerned is not linked to a disabled host ? 

select host_name, host_activate, host_register FROM host WHERE host_id IN (SELECT host_host_id FROM host_service_relation WHERE service_service_id = <ID>);

Where <ID> is the service id that you can find in the page URL when you edit the service.

Thanks

**Comment by gslongo** [comment]
The sql command returns the following :
```
MariaDB [centreon]> select host_name, host_activate, host_register FROM host WHERE host_id IN (SELECT host_host_id FROM host_service_relation WHERE service_service_id = 735);
+-----------+---------------+---------------+
| host_name | host_activate | host_register |
+-----------+---------------+---------------+
| lx64host  | 0             | 1             |
| lisa      | 1             | 1             |
+-----------+---------------+---------------+
2 rows in set (0.00 sec)
```
lx64host has been deleted a long time ago... We cannot see it in the web interface anymore..

Do you think you can provide something like a coherency check script which could detect this king of situation for the entire database ?

Thanks

**Comment by julienmathis** [comment]
Oh yeah ! 

Since centreon 2.7.x, when you disable a host, you can't see his services in Configuration > Services.  That's why you see only one line, because the host is disabled. If you enable this host, the view will be back coherent. So it's normal. 

I will add a search field in order to show or hidden services of disabled hosts.

**Comment by lpinsivy** [comment]
already done
