### ISSUE TITLE
[2.7.3] ACL problem to see services in Reporting Dashboard

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#4303]
Account with limited acces cannot see services in reporting dashbord when host is selected.

![image](https://cloud.githubusercontent.com/assets/12545407/14172791/4afb7486-f73a-11e5-8ec4-e0d26588307f.png)

Thanks,

**Comment by sososofian** [comment]
Bonjour,
J'ai le même problème, avez-vous trouvé une solution?
Cordialement,

Hello,
I have the same problem, have you found a solution?
Regards,

**Comment by querwin** [comment]
Fixed since 2.7.5 version
