### ISSUE TITLE
[Amelioration] Service avec host parent different

### ISSUE THREAD

**Issue by Thiefoumongars** [centreon/centreon#4305]
Bonjour,

Je suis confronté à un problème, et recherche la meilleure solution (pour moi et pour tout le monde qui aurait cette problèmatique).
Je vous explique:
- J'utilise le check_nrpe afin d'excecuté des scripts pour des check bien particulier.
- Les check_nrpe sont lié a un HOSTA (et d'autre) (le service est lie a un service template qui est lié a un host template) 
- La ligne de commande nrpe reprend le hostaddress comme argument. (simplification de déploiement de nouveau check)
- Mon server NSclient est different de mon HOSTB.
- Un check du service NSclient est un place sur moin host NSclient 

Comment faire pour que le service nrpe du HOSTA est un lien de parenté avec le check NSclient du HOSTB afin d'évité les fausses alarme lorsque l'on redémarre le service NSclient ou le server complement ?

Merci d'avance de vos idées.
N'hésité pas si quelque chose n'est pas claire.

**Comment by querwin** [comment]
Peut être est il possible de passer par les dépendances de Centreon : https://documentation-fr.centreon.com/docs/centreon/en/2.7.x/administration_guide/02i.html#dependance-d-un-service

**Comment by Thiefoumongars** [comment]
C'est parfait, merci pour l'information.
