### ISSUE TITLE
[BUG] centreon KB

### ISSUE THREAD

**Issue by tanguyvda** [centreon/centreon#4306]
If you have a service with a space in his name the wiki link is not well handled by centreon KB 

(version 2.0.0 for Centreon 2.6 or version 2.1.0 forcentreon-Web 2.7)

---

Si vous avez un espace dans le nom d'un service alors centreon KB ne va pas bien gérer les liens wiki

(version 2.0.0 pour Centreon 2.6 ou version 2.1.0 pour centreon-Web 2.7

**Comment by cmeschin** [comment]
Bonjour,
Merci Tanguy pour la création du ticket.
Ce bug est pénalisant sur notre plateforme en raison de la volumétrie des services impactés.
Cela représente environ 60% des services soit plus de 16500 sondes.

Je pense qu'un "replace" des espaces en underscore au niveau du module proxy de KB devrait suffire mais ce n'est peut-être pas aussi simple et il y a peut-être d'autres caractères à gérer :)
cordialement,

**Comment by cmeschin** [comment]
Bonsoir,
est-il possible d'avoir une estimation de la version cible pour ce correctif?
Je sais que centreon-KB doit être intégré dans centreon-web 2.8 et les améliorations sur ce module ne sont probablement pas prioritaires mais s'il était possible d'avoir un petit patch avant, cela m'aiderai beaucoup.

merci d'avance pour toute information que vous pourriez me donner.
cordialement

**Comment by cmeschin** [comment]
Bonjour,
Le correctif a été intégré dans la 2.8 Beta et semble fonctionnel sur un petit périmètre.
Je ferai des tests sur un périmètre plus important dès que possible.
en attendant ce ticket peut donc être clot.

Merci.

**Comment by cmeschin** [comment]
Bonjour,
Les liens sont désormais bien gérés si les services contiennent des espaces.
Cependant, si les services contiennent des underscore, les liens ne se font plus correctement (centreon 2.8.2).
Cas reproductible avec un service nommé: "Ping_test" => lien non créé
Si le service contient des espaces et des underscrores, les liens ne sont pas créés.
Si le service se nomme "Ping test" donc sans aucun underscore alors le lien est bien créé.

Pouvez-vous vérifier, svp?

**Comment by cmeschin** [comment]
Bonjour,
Avez-vous pu avancer sur le sujet?

cordialement,
