### ISSUE TITLE
Avoid PHP Warning when open service whithout graph template

### ISSUE THREAD

**Issue by smutel** [centreon/centreon#4307]
Hello,

When you open the configuration of a service which does not contain graph template, the message below in error_log is displayed:

`[Tue Apr 05 09:10:33 2016] [error] [client XX.XX.XX.XX] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/centreon/www/lib/HTML/QuickForm/select2.php on line 649, referer: https://centreon-qa.xit.rxcorp.com/centreon/main.php?p=602`

Regards.

**Comment by lpinsivy** [comment]
Hi

We won't to apply many changes in same time.

Can you make two distinct pull request ?

Regards,

**Comment by smutel** [comment]
Hello,

I changed the pull request to take into account of this bug only.

Regards.

**Comment by querwin** [comment]
Thanks !
