### ISSUE TITLE
Error when saving "Administration > Parameters > Monitoring" page

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4308]
Bonjour,

A chaque sauvegarde la page « Administration > Paramètres >  Monitoring », un changement est effectué dans la base Centreon.

Dans la table "options" la colonne "value" ayant pour key "broker" prends pour valeur "ndo".
```
# mysql -u ... -p ...
# use centreon
# SELECT * FROM options WHERE `key` = 'broker';
+---------+---------+
| key      | value   |
+---------+---------+
| broker | ndo      |
+---------+---------+
```

Ceci a pour effet de causer des erreurs dans :
- MAP
`[error] PHP Notice: Undefined index: db_pass in /usr/share/centreon/www/modules/centreon-map-server/webServices/class/CentreonMap_DB_PdoConnector.class.php on line 0 `

- BI : Le script eventReportBuilder remonte l'erreur suivante
`"Error: Can't call method "query" on an undefined value at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 96." `

Il faut donc remettre la valeur ‘broker’ en base.
`# UPDATE `options` SET `value`= 'broker' WHERE `key` = 'broker';`

Cordialement

**Comment by leoncx** [comment]
Fix in commit:9c7babfb0326bb70bd0caa434c516bdf5eed2066
