### ISSUE TITLE
Garder les préférences pour les utilisateurs

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#431]
---

Author Name: **ROBIN matthieu** (ROBIN matthieu)
Original Redmine Issue: 5721, https://forge.centreon.com/issues/5721
Original Date: 2014-08-05

---

Bonjour,

Serait-il possible de garder (entre chaque session) pour chaque user les préférences de "cacher" l'interface? Je parle des petites flèches en haut à droite, celles qui permettent de cacher les bandeaux.

Merci d'avance.

**Comment by julienmathis** [comment]
un bouton a tout simplifié
