### ISSUE TITLE
Add a host categorie by the tab Relation is not possible

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#4315]
When add a host categorie by the tab Relation is not possible (no result found) but when add host on the host categorie is ok.

Configuration  >  Hosts  >  Centreon-Server : 
![categorie_hote_1](https://cloud.githubusercontent.com/assets/16045498/14351823/bcfe3dec-fcd1-11e5-81ba-b652272e6a21.jpg)

Configuration  >  Hosts  >  Categories : 
![categorie_hote_2](https://cloud.githubusercontent.com/assets/16045498/14351835/ca7d79ec-fcd1-11e5-83af-da2e150d27cb.jpg)

Regards,

**Comment by querwin** [comment]
Hello,

I think this is the same issue as : https://github.com/centreon/centreon/issues/4268

Regards,

**Comment by cmeschin** [comment]
Hello,
I have the same problem with a user submitted to ACL.
This problem can be solved by adding all host classes on the Filter tab. But this is not very convenient.
If a new class is added, the user does not automatically see.

If no category is selected, users have visibility into all categories. But no configuration is possible.
Can you add a check mark "Include all host categories" from the menu Filters tab "management of access resources" as for guests "include all hosts" and "include all groups of hosts."

thks,

**Comment by tseegers** [comment]
Hello,

The problem is still present in 2.7.8.

Indeed if we add a host categorie in the filter of the page "Administration  >  ACL  >  Resources Access" we can add an host in the selected categorie. But if the host is not member of any host categorie this solution doesn't work.

Regards
