### ISSUE TITLE
[2.7.3] Parent Host/Service Categories not working

### ISSUE THREAD

**Issue by Thiefoumongars** [centreon/centreon#4316]
Bonjour,
Les categories ne sont pas hérité du Host/Service template lors de la creation d'un host ou service, est ce un comportement normal ?
Quelque printscreen pour expliquer
![08-04-2016 10-38-06](https://cloud.githubusercontent.com/assets/12168075/14378674/878765bc-fd76-11e5-8325-efccfccc1187.jpg)
![08-04-2016 10-38-23](https://cloud.githubusercontent.com/assets/12168075/14378679/87beb5b2-fd76-11e5-8d5f-2c4e777dd928.jpg)
![08-04-2016 10-38-59](https://cloud.githubusercontent.com/assets/12168075/14378676/87b849a2-fd76-11e5-89e7-5a511fe1f266.jpg)
![08-04-2016 10-41-08](https://cloud.githubusercontent.com/assets/12168075/14378677/87b93b32-fd76-11e5-8a8c-440ad7519d10.jpg)
![08-04-2016 10-41-31](https://cloud.githubusercontent.com/assets/12168075/14378678/87bbf3d6-fd76-11e5-9a0a-49a1a3033ffd.jpg)
![08-04-2016 10-41-53](https://cloud.githubusercontent.com/assets/12168075/14378680/87bf766e-fd76-11e5-8630-567a6ccc1fe0.jpg)

**Comment by lpinsivy** [comment]
Bonjour,

Je ne comprend pas exactement ton besoin. il est normal que lorsque tu créé un hôte ou un service à partir d'un modèle que les champs déjà définis dans le modèle ne soient pas visible dans le formulaire de l'hôte ou du service.

C'est la moteur qui fera les liaisons lors de la lecture de sa configuration.
