### ISSUE TITLE
Massive change on services is limited to 1000 items

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#4318]
When selecting more than 1000 services in Configuration and doing a Massive Change (e.g. changing linked contact groups under the notification tab), only the first 1000 will actually be changed.

Centreon 2.7.2 (CES 3.3 iso + network update from 2.7.1).

Workaround: limit services per page to 100 and select page 11, page 12, page ...... and do your massive changes per 100 services. Which is a massive pain in the ass if you have a massive amount of services.

**Comment by querwin** [comment]
Not the good practice to do a such massive change

**Comment by btassite** [comment]
It may be necessary on large infrastructural or organizational changes, but that's beside the point, which is that it's not working as expected.
