### ISSUE TITLE
[2.7.3] Can't define Timezone/Location at host template level

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4319]
Hi, 

Do you plan to add the possibility to set Timezone/Location from host template ? 

Actually only available through hosts form. (maybe centreon-engine doesn't manage it ?).

Thanks,

**Comment by julienmathis** [comment]
@ganoze : does engine manage it ?

**Comment by ganoze** [comment]
@julienmathis of course it does ! There is no difference in Centreon Engine between templates and base objects aside from the register=0 flag.

**Comment by julienmathis** [comment]
Thanks. Planned for 2.8.0.

++

**Comment by Sims24** [comment]
Ok Thanks, 

We'll use the massive change until then..

++

**Comment by garnier-quentin** [comment]
We'll need to change the configuration generation also. because we set the default global timezone when there is no timezone set for the host.
To manage it easily, we need to add a default configuration for centreon-engine (otherwise it will cost to much in config generation).

**Comment by Tpo76** [comment]
Ineherit from host template doesn't seem to be apply on child host

**Comment by julienmathis** [comment]
@Tpo76 Where ?

**Comment by julienmathis** [comment]
so, downtimes do not managed TZ on templates

**Comment by julienmathis** [comment]
I just ask the team to change the method to get the timezone for recurring downtime. Timezone are now available in the realtime db and engine manage the inheritance. MON-802. 
This ask is linked but we can configure TZ on templates !!
