### ISSUE TITLE
Latency following upgrade to 2.7.3

### ISSUE THREAD

**Issue by kohl42** [centreon/centreon#4321]
I am confronted to a big latency problem when upgrading to 2.7.3 , few minutes after upgrade services and hosts latency rises to > 100s.

I'm back to 2.7.2 (after a restore), where latency is back to normal :

Active Service Latency:                 0.000 / 4.862 / 0.572 sec
Passive Service Latency:                0.119 / 2.018 / 1.043 sec
Active Host Latency:                    0.000 / 3.541 / 0.863 sec
Passive Host Latency:                   0.000 / 0.000 / 0.000 sec

I'd like to upgrade but I'm stuck, otherwise Centreon becomes completely inoperable. It's a CES installation from official repos.

**Comment by kohl42** [comment]
I'm thinking about pb with MySQL indexes, but I can't find the json files used to rebuild index. I couldn't find anything online about how to do that in 2.7.X
I took the json files from earlier release but it seems database model changed somehow, as I have many error while trying running it.

**Comment by Sims24** [comment]
Hi, 

Could you provide a dump of database schema ? With a tool like SchemaSync we'll be able to confirm (or not) your toughts.

**Comment by kohl42** [comment]
I'm attaching schema dump as well as json Index (computed via script export-mysql-indexes) for databas centreon and centreon-storage.
[mysqlCentreonIndex_json.txt](https://github.com/centreon/centreon/files/221209/mysqlCentreonIndex_json.txt)
[mysqlCentreonStorageIndex_json.txt](https://github.com/centreon/centreon/files/221210/mysqlCentreonStorageIndex_json.txt)
[centreon_schema_2016-04-15.sql.txt](https://github.com/centreon/centreon/files/221211/centreon_schema_2016-04-15.sql.txt)
[centreon_storage_schema_2016-04-15.sql.txt](https://github.com/centreon/centreon/files/221212/centreon_storage_schema_2016-04-15.sql.txt)

As a side note, I just upgraded to 2.7.4. Again latency exploded :+1: 

BEFORE upgrade 
Active Service Latency:                 0.000 / 65.959 / 0.836 sec
Passive Service Latency:                0.175 / 2.018 / 1.052 sec
Active Host Latency:                    0.000 / 3.106 / 0.880 sec
Passive Host Latency:                   0.000 / 0.000 / 0.000 sec

NOW 
Active Service Latency:                 0.000 / 277.222 / 131.824 sec
Passive Service Latency:                0.175 / 2.018 / 1.057 sec
Active Host Latency:                    0.000 / 277.213 / 215.950 sec
Passive Host Latency:                   0.000 / 0.000 / 0.000 sec

**Comment by Sims24** [comment]
I'll throw a look by the end of the day and let you know

**Comment by Sims24** [comment]
Hi, 

Your database Centreon is OK

On your centreon_storage may be this one : 

ALTER TABLE `centreon_acl` ADD INDEX `group_id_by_name` (`group_id`) USING BTREE, ADD INDEX `group_id_for_host` (`group_id`) USING BTREE;

But doesn't explain latency at all :( 

Check that the process service perfdata is not "magically" set to yes when you upgrade but anyway problem is not your database.

Is the my.cnf or centreon.cnf files are present under your database config dir ?

**Comment by kohl42** [comment]
Ok, so I add the index you mentionned, but as predicted no big change yet, still very laggy.

But... I had an activated process-service-perfdata left from before the time I migrated to CES. And it does set my problem! 
I've obviously overlooked the big changes coming with Centreon-broker. I'll look back at it as soon as I get some free time.

Thanks a lot though, you saved my day.
