### ISSUE TITLE
Custom Views don't fill screen / scale up to avaiable resolution

### ISSUE THREAD

**Issue by vlabmichl** [centreon/centreon#4326]
After upgrading our CES from 2.6 to 2.7.3 we encounter a bug with the custom views module.

The view doesn't scale up to the available resolution of the Y-axis. The widgets display only 4-5 dataset rows each and displays scrollbars for accessing the other 20 datasets.

![centreon_customviews_chrome](https://cloud.githubusercontent.com/assets/877285/14554360/ce67c442-02ec-11e6-9d84-3916e1d98d49.PNG)
![centreon_customviews_firefox](https://cloud.githubusercontent.com/assets/877285/14554361/ce6d0664-02ec-11e6-8730-bfb0dad7475b.PNG)

Our steps we made so far to solve this:
* We cleared the browser cache and deactivated caching of our Firefox completly -> no success.
* Installed Chrome on the same machine (default settings) -> no success
* Chrome no caching -> no success

**Comment by querwin** [comment]
Hello,

If possible can you try to delete and create a widget ?

Regards,

**Comment by vlabmichl** [comment]
* removed all widgets and views (except the last one which I can't delete)
* added a new view and some widgets -> no succes / no change

**Comment by florian-asche** [comment]
Same issue: #4293 some useful information there!

**Comment by vlabmichl** [comment]
Thanks for the input!
Workaround with manually refreshing the widget works in some cases but not everytime.

**Comment by florian-asche** [comment]
yes, thats correct. i wonder why... there has to be some sort of resize java-script function that is missing on widget load. and there is some if in it, that sometimes react and sometimes not. i wonder, what variable that could be...

**Comment by julienmathis** [comment]
A global upgrade of all widget will fix that.

**Comment by bmareau** [comment]
Hi,

Problem is always present in Firefox 51.0.1 with Centreon Web 2.8.4
![widget](https://cloud.githubusercontent.com/assets/13255513/23405639/7f0ea21a-fdbb-11e6-8842-48f6f841f96f.jpg)

Regards

**Comment by itsul** [comment]
Hi,
I can confirm this. Centreon Web 2.8.4, testet with Firefox 52.0 and 47.

**Comment by tseegers** [comment]
Hello,

The problem is still present in 2.8.23.

Bmareau mentionned it here as well:

https://github.com/centreon/centreon-widget-service-monitoring/issues/76
