### ISSUE TITLE
[Monitoring][Performance]

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4328]
Hi,

the filter for Servicegroup and Hostgroup is missing.

Regards Florian

**Comment by florian-asche** [comment]
Hi @querwin,
i need this in 2.7.5 or maybe in an patch earlier. Cant we get the missing functions from Monitoring - Event Logs? If you whould provide me a patch in form of a commit, i can test it, and my customers are happy.

**Comment by florian-asche** [comment]
My Customer also misses the easy select group and then see only the servers that are in this group. I whould like to add a function, "Only show results in searchfield, selected by other search fields". If i select group Test, i can only add servers in serverfield from group Test.

**Comment by Tpo76** [comment]
OK
