### ISSUE TITLE
[Graphs] Valeurs inversées

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4330]
Bonjour,

Dans les graphes lorsque nous demandons d'inverser les valeurs. Les valeurs Max et Min ne sont plus correct (Enfin pour nous).

Par exemple si nous prenons une interface réseau, traffic_in: valeurs négative [-x-0] et traffic_out: valeurs positives [0-x]. 
Nous avons un jolie graphique, avec la partie du haut occupé par le traffic_out et la partie du bas par le traffic_in. 
Mais les valeurs Max et Min du traffic_in sont erronées, car Min récupère des valeurs qui s'écarte du zéro alors que le Max ce rapprochant du zéro.

**Comment by benoiteolas** [comment]
Can we link this bug to this one ? https://github.com/centreon/centreon/issues/2888

**Comment by querwin** [comment]
Exact !

I close this one :)

**Comment by jben94** [comment]
Comme je n'ai pas vu de correctif ou d'avancement depuis 2015 !
voici un contournement pour ceux qui veulent !
![cent](https://cloud.githubusercontent.com/assets/16583698/14565337/fc6dd2b2-032a-11e6-8daf-9691f06b5c77.PNG)
