### ISSUE TITLE
Generating files... NOK after upgrade to 2.7.3

### ISSUE THREAD

**Issue by pavelsmn** [centreon/centreon#4333]
Hi!

Preparing environment... OK
Generating files... NOK
Aborted.
[ - ] Probe2
Reading main configuration file '/usr/share/centreon/filesGeneration/nagiosCFG/3/nagiosCFG.DEBUG'.
Reading resource file '/usr/share/centreon//filesGeneration/nagiosCFG/3/resource.cfg'
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Command 'Perl Connector' was not found
Warning Host 'xxxx' has no services associated with it!
Warning Host 'xxxx' has no services associated with it!
Checking global event handlers...
Checking obsessive compulsive processor commands...

Checked 27 commands.
Checked 0 connectors.
Checked 17 contacts.
Checked 0 host dependencies.
Checked 0 host escalations.
Checked 6 host groups.
Checked 23 hosts.
Checked 0 service dependencies.
Checked 0 service escalations.
Checked 0 service groups.
Checked 168 services.
Checked 3 time periods.

Total Warnings: 2
Total Errors: 14

Perl connector is installed and configured in poller settings.

**Comment by julienmathis** [comment]
Can you provide more information ? a diff of config file (before vs after).... ?

**Comment by julienmathis** [comment]
No enough informations.
