### ISSUE TITLE
[Widgets] Hostgroup widget bug because count disabled hosts

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon#4336]
Hi, 

Hostgroup widget report 4 services in critical state, but no service is in critical. Note that previously I delete 4 hosts with 4 ping services associated, maybe the issue is that the sql request get services for deleted hosts?

Thanks in advance,

![image](https://cloud.githubusercontent.com/assets/322320/14639435/09e6e950-063d-11e6-8118-56a9240bdf04.png)

**Comment by rk4an** [comment]
Maybe this line missing:

AND h.enabled = 1

on line 136 of /usr/share/centreon/www/widgets/hostgroup-monitoring/src/class/HostgroupMonitoring.class.php

**Comment by querwin** [comment]
Thanks for the feedback and the fix :)

I open in the good forge and I close this one
