### ISSUE TITLE
Poller disabled, error message:  "Invalid argument supplied for foreach()"

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4337]
Hi,

In centreon 2.7.4, if we disable a poller and try to reload his configuration, the error message which appear is not clear: "Invalid argument supplied for foreach()".

Is it possible to have a more explicit message that warns you that the poller is disable ?

Also, when a poller a disabled, the green cross is displayed, it make us thing that the poller is enable. Moreother, when a poller is enable we can see a red circle which make us think the poller is disabled.

Regards

**Comment by querwin** [comment]
Hello,

Fixed here : https://github.com/centreon/centreon/issues/4254
