### ISSUE TITLE
Sound alert issue

### ISSUE THREAD

**Issue by henrybcp** [centreon/centreon#4338]
Hey so I recently updated to the latest version of Centreon and have been messing with the UI notification audio alerts trying to get a sound to play every time a server check goes critical. It seems to work alright if I test out the sound clip from the general options interface, but it doesn't seem to consistently work if there is an actual problem. Every now and then it will make a sound upon a critical output from a check, but most of the time it doesn't work. Is this a bug?

**Comment by querwin** [comment]
Seems like a bug, I'm gonna test it

**Comment by querwin** [comment]
I've just try it out and it works for me
