### ISSUE TITLE
API Add getparam for objects

### ISSUE THREAD

**Issue by querwin** [centreon/centreon#4343]
Link to : 

https://github.com/centreon/centreon-clapi/issues/14

**Comment by sathieu** [comment]
I'm interested by this feature. Any pointer on where it should be coded?

**Comment by sathieu** [comment]
I've proposed a PR in #5783

**Comment by adr-mo** [comment]
UPDATE: #5946 (add possibility to get several params and fix 3 variables not found)

**Comment by adr-mo** [comment]
Looks good to me.

Tested with the latest update brought by #5946.
