### ISSUE TITLE
Use an INDEX on the ctime field of data_bin

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#437]
---

Author Name: **Matthieu Kermagoret** (Matthieu Kermagoret)
Original Redmine Issue: 3939, https://forge.centreon.com/issues/3939
Original Date: 2012-11-22

---

Please use an INDEX on the _ctime_ field of _data_bin_. This will be useful when rebuilding graphs where result is ORDERed BY _ctime_.

**Comment by julienmathis** [comment]
Will not be implemented, but a partition system will be in the next version
