### ISSUE TITLE
[Centreon 2.7.4] Centreon Web - Ghost hosts

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon#4370]
When viewing from the Admin account the number of hosts in the correct groups of hosts.
Monitoring  >  Status Details  >  Hostgroups Summary :
![22-04-16 05 56 00](https://cloud.githubusercontent.com/assets/15804154/14730418/f6c0b446-084e-11e6-91e7-d5e8fa23a955.png)

In one configuration group hosts the amount indicated :
![22-04-16 05 52 32](https://cloud.githubusercontent.com/assets/15804154/14730394/abea3014-084e-11e6-948e-165cbe0075af.png)

When viewing the same page from another account (with limited privileges) :
![22-04-16 05 57 40](https://cloud.githubusercontent.com/assets/15804154/14730437/2c74a3c2-084f-11e6-923c-74a6fd1158a1.png)

How can this be corrected?

**Comment by lpinsivy** [comment]
Hi,

Can you describe how you build your ACL ?

**Comment by maksimatveev** [comment]
@lpinsivy exactly what ACL are you interested in? Resources Access?

**Comment by lpinsivy** [comment]
Hi,

No problem i reproduce issue. I try to correct SQL request

**Comment by maksimatveev** [comment]
@lpinsivy can you tell sql-query that I can perform, to diagnose the problem.

**Comment by lpinsivy** [comment]
Can you try this correction ?

**Comment by maksimatveev** [comment]
@lpinsivy perfectly! the number of hosts is now correct!
