### ISSUE TITLE
Temps de disponibilité

### ISSUE THREAD

**Issue by bast0123** [centreon/centreon#4374]
Bonjour,

J'ai quelque chose qui me parait bizarre au niveau des rapports sur le temps de disponibilité.
J'ai un groupe de 3 hôtes, j'ai eu une coupure sur l'un de ces 3 hôtes, le temps sur cette journée apparait comme ceci pour le groupe : 
![centreon_bug_time](https://cloud.githubusercontent.com/assets/2530686/14736838/4b1d223e-0879-11e6-91d8-8f03fd4d421d.jpg)

Cependant quand je vais sur mon hôte qui a eu la coupure le temps apparait comme ceci sur la même journée :
![centreon_bug_time2](https://cloud.githubusercontent.com/assets/2530686/14736867/6baf7c68-0879-11e6-80f8-629369c9a3f4.jpg)

J'ai l'impression que le temps est divisé, ça ressemble à un bug ?
Si je ne me trompe pas, on aimerait en théorie avoir le temps d'indisponibilité du groupe, en additionnant les temps des hôtes ?

Cordialement,
Bastien

**Comment by querwin** [comment]
@Moujimouja : Any reasons why this could happen ?

**Comment by Moujimouja** [comment]
Bonjour,

C'est le fonctionnement normal du dashboard. L'information présentée est la moyenne du temps indisponible. Si on devait cumuler les temps alors on devrait aussi cumuler les temps de disponibilité et les journées ne durerai donc plus 24h mais 24h * nb host. Ce serait alors une autre représentation mais que les utilisateurs ne trouverai pas forcément plus adéquate.

C'est la représentation qui a été choisie pour rester simple ([ cf code ici ](https://github.com/centreon/centreon/blob/2.7.x/www/include/reporting/dashboard/xmlInformations/GetXmlHostGroup.php#L78))

Pour le moment si vous souhaitez des statistiques de disponibilité des hôtes et des services plus précise et détaillée, vous pouvez toujours jeter un coup d'oeil au module [Centreon MBI](https://documentation-fr.centreon.com/docs/centreon-bi-2/en/3.0.x/)

Notamment avec ce [genre de rapports ](https://documentation-fr.centreon.com/docs/centreon-bi-2/en/3.0.x/examples/Hostgroup-Availability-2.html) ou encore ce [rapport simple de listing](https://documentation-fr.centreon.com/docs/centreon-bi-2/en/3.0.x/examples/Hostgroup-Host-Availability-List.html) 

Avez vous d'autres question ou ce ticket peut être fermé ?

**Comment by bast0123** [comment]
Bonjour,

Désolé j'étais en congés et sans internet.
J'ai eu mes informations, merci de votre retour, on peut clôturer.

Et merci pour votre excellent travail :)
