### ISSUE TITLE
Special character in "Status details" page

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4379]
Hello,

There is a bug in Status Details page. Encodage of special characters is wrong.
![accent](https://cloud.githubusercontent.com/assets/11076322/14742334/f1a8d428-089b-11e6-8634-b7d19025f7a2.JPG)

Regards,

**Comment by Tpo76** [comment]
NOK
![special_character](https://cloud.githubusercontent.com/assets/11980015/16772927/41a43aae-4856-11e6-9464-0dc93fac5d8e.png)
