### ISSUE TITLE
Centreon 2.7.4 - Generate configuration doesnt work anymore

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon#4380]
Hello,
I was in 2.7.2 and since i've updated to 2.7.4 i cant export my configuration anymore.

When i clic on Export, i got : 
Progress (0%)
Préparing Environnement...

And nothing more.

Any ideas ?

**Comment by querwin** [comment]
Hello,

Any Apache logs ?

**Comment by gerpion** [comment]
Here are the apache logs :

[Mon Apr 25 09:52:59 2016] [notice] caught SIGTERM, shutting down
[Mon Apr 25 09:53:40 2016] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Apr 25 09:53:40 2016] [notice] Digest: generating secret for digest authentication ...
[Mon Apr 25 09:53:40 2016] [notice] Digest: done
[Mon Apr 25 09:53:40 2016] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 configured -- resuming normal operations
[Mon Apr 25 09:56:33 2016] [error] [client 10.24.116.51] PHP Notice:  Undefined offset: 0 in /usr/share/centreon/www/class/centreonGraph.class.php on line 355, referer: http://cbh14/centreon/widgets/graph-monitoring/index.php?widgetId=31&customViewId=10
[Mon Apr 25 09:56:34 2016] [error] [client 10.24.116.51] PHP Notice:  Undefined offset: 0 in /usr/share/centreon/www/class/centreonGraph.class.php on line 355, referer: http://cbh14/centreon/widgets/graph-monitoring/index.php?widgetId=31&customViewId=10
[Mon Apr 25 10:04:29 2016] [error] [client 10.24.117.229] PHP Notice:  Undefined index: action in /usr/share/centreon/www/include/home/customViews/rename.php on line 50, referer: http://cbh14/centreon/main.php?p=103
[Mon Apr 25 10:04:47 2016] [error] [client 10.24.117.229] PHP Notice:  Undefined offset: 1 in /usr/share/centreon/www/class/centreonWidget.class.php on line 237, referer: http://cbh14/centreon/main.php?p=103
[Mon Apr 25 10:05:32 2016] [error] [client 10.24.117.229] PHP Notice:  Undefined index: action in /usr/share/centreon/www/include/home/customViews/rename.php on line 50, referer: http://cbh14/centreon/main.php?p=103
[root@cbh14 httpd]#

**Comment by gerpion** [comment]
My bad Quentin, I didnt select any poller at all ..... in 2.7.2, Central was selected by default when no poller is selected in 2.7.4.

Maybe you should add an error message like : select a poller 

Best regards.
