### ISSUE TITLE
Disable requirement of ACL groups on add form

### ISSUE THREAD

**Issue by smutel** [centreon/centreon#4381]
Hello,

When you want to add a host with a no admin account, the option ACL groups is mandatory.
This option is useful but not mandatory in all case. For example if you have ACL groups setup with all hostgroups/all hosts option.

Thanks.

**Comment by querwin** [comment]
I add it on 2.7.5 Milestone. 

@julienmathis do you remember why we set tihs option as mandatory ?

**Comment by julienmathis** [comment]
If you don't do that, you will not be able to see the host that you create... We can't link the directly to the user. You have to link it to an ACL group.

We can't change this behavior.

**Comment by smutel** [comment]
Hello,

"If you don't do that, you will not be able to see the host that you
create".
It is not true if you have an ACL which already include All hosts & All
hostgroups.
This behaviour works when you have several ACL group and several views.
If you have only one ACL with the capability to see All hosts & All
hostgroups, do we should add a host to an ACL group?

Thanks.
Regards.


2016-06-13 11:04 GMT+02:00 Julien Mathis <notifications@github.com>:
