### ISSUE TITLE
[2.7.4]Bug in dashboard for showing services in hosts for non admin users

### ISSUE THREAD

**Issue by lermthya** [centreon/centreon#4383]
When you are not log admin, the dashboard not show any services in hosts definitions.
I have found errors in /var/log/centreon/sql-error.log

2016-04-26 12:20|0|0|DB Error: syntax error QUERY : (SELECT service_id, service_description FROM ( SELECT s.service_id, s.service_description FROM host_service_relation hsr, host h, service s, centreon_storage.centreon_acl WHERE h.host_id = '256' AND h.host_activate = '1' AND h.host_register = '1' AND h.host_id = hsr.host_host_id AND hsr.service_service_id = s.service_id AND s.service_activate = '1' AND centreon_storage.centreon_acl.host_id = h.host_id AND centreon_storage.centreon_acl.host_id = '256' AND centreon_storage.centreon_acl.group_id IN ('66') UNION SELECT s.service_id, s.service_description FROM host h, hostgroup_relation hgr, service s, host_service_relation hsr, centreon_storage.centreon_acl WHERE h.host_id = '256' AND h.host_activate = '1' AND h.host_register = '1' AND h.host_id = hgr.host_host_id AND hgr.hostgroup_hg_id = hsr.hostgroup_hg_idAND hsr.service_service_id = s.service_idAND centreon_storage.centreon_acl.host_id = h.host_id AND centreon_storage.centreon_acl.host_id = '256' AND centreon_storage.centreon_acl.group_id IN ('66') ) as t  ORDER BY LOWER(service_description)

The bug is located in /usr/share/centreon/www/class/centreonACL.class.php beetwen the lines 2033 and 2064

The original code for centreon 2.7.4 is:
   2033         } else {
   2034             $query = "(" . $request['select'] . $request['simpleFields'] . " "
   2035                 . "FROM ( "
   2036                 . "SELECT " . $request['fields'] . " "
   2037                 . "FROM host_service_relation hsr, host h, service s, $db_name_acl.centreon_acl "
   2038                 . "WHERE h.host_id = '" . CentreonDB::escape($host_id) . "' "
   2039                 . "AND h.host_activate = '1' "
   2040                 . "AND h.host_register = '1' "
   2041                 . "AND h.host_id = hsr.host_host_id "
   2042                 . "AND hsr.service_service_id = s.service_id "
   2043                 . "AND s.service_activate = '1' "
   2044                 . "AND $db_name_acl.centreon_acl.host_id = h.host_id "
   2045                 . "AND $db_name_acl.centreon_acl.host_id = '" . CentreonDB::escape($host_id) . "' "
   2046                 . "AND $db_name_acl.centreon_acl.group_id IN (" . $this->getAccessGroupsString() . ") "
   2047                 . "UNION "
   2048                 . "SELECT " . $request['fields'] . " "
   2049                 . "FROM host h, hostgroup_relation hgr, service s, host_service_relation hsr, $db_name_acl.centreon_acl "
   2050                 . "WHERE h.host_id = '" . CentreonDB::escape($host_id) . "' "
   2051                 . "AND h.host_activate = '1' "
   2052                 . "AND h.host_register = '1' "
   2053                 . "AND h.host_id = hgr.host_host_id "
   2054                 . "AND hgr.hostgroup_hg_id = hsr.hostgroup_hg_id"
   2055                 . "AND hsr.service_service_id = s.service_id"
   2056                 . "AND $db_name_acl.centreon_acl.host_id = h.host_id "
   2057                 . "AND $db_name_acl.centreon_acl.host_id = '" . CentreonDB::escape($host_id) . "' "
   2058                 . "AND $db_name_acl.centreon_acl.group_id IN (" . $this->getAccessGroupsString() . ") "
   2059                 . ") as t ";
   2060         }
   2061
   2062         $query .= $request['order'] . $request['pages'];
   2063
   2064         $services = $this->constructResult($query, $options);

And i modify with for correcting the SQL error:

2033         } else {
   2034             $query = "(" . $request['select'] . $request['simpleFields'] . " "
   2035                 . "FROM ( "
   2036                 . "SELECT " . $request['fields'] . " "
   2037                 . "FROM host_service_relation hsr, host h, service s, $db_name_acl.centreon_acl "
   2038                 . "WHERE h.host_id = '" . CentreonDB::escape($host_id) . "' "
   2039                 . "AND h.host_activate = '1' "
   2040                 . "AND h.host_register = '1' "
   2041                 . "AND h.host_id = hsr.host_host_id "
   2042                 . "AND hsr.service_service_id = s.service_id "
   2043                 . "AND s.service_activate = '1' "
   2044                 . "AND $db_name_acl.centreon_acl.host_id = h.host_id "
   2045                 . "AND $db_name_acl.centreon_acl.host_id = '" . CentreonDB::escape($host_id) . "' "
   2046                 . "AND $db_name_acl.centreon_acl.group_id IN (" . $this->getAccessGroupsString() . ") "
   2047                 . "UNION "
   2048                 . "SELECT " . $request['fields'] . " "
   2049                 . "FROM host h, hostgroup_relation hgr, service s, host_service_relation hsr, $db_name_acl.centreon_acl "
   2050                 . "WHERE h.host_id = '" . CentreonDB::escape($host_id) . "' "
   2051                 . "AND h.host_activate = '1' "
   2052                 . "AND h.host_register = '1' "
   2053                 . "AND h.host_id = hgr.host_host_id "
   2054                 . "AND hgr.hostgroup_hg_id = hsr.hostgroup_hg_id "
   2055                 . "AND hsr.service_service_id = s.service_id "
   2056                 . "AND $db_name_acl.centreon_acl.host_id = h.host_id "
   2057                 . "AND $db_name_acl.centreon_acl.host_id = '" . CentreonDB::escape($host_id) . "' "
   2058                 . "AND $db_name_acl.centreon_acl.group_id IN (" . $this->getAccessGroupsString() . ") "
   2059                 . ") as t ";
   2060         }
   2061
   2062         $query .= $request['order'] . $request['pages'] . ")";
   2063
   2064         $services = $this->constructResult($query, $options);

The modifications is located in lines:
2054, 2055: Add space before "
2065: close the query by addind the missing ")"

All work now enjoy

**Comment by lpinsivy** [comment]
Thank you for your help

Regards,

**Comment by lermthya** [comment]
I made a little mistake in the correction.
The ")" must not be close in line 2062. Because if we do this, the admin user don't work. 
So i close the ")" at the end of the line 2059.

The code became:

 2054                 . "AND hgr.hostgroup_hg_id = hsr.hostgroup_hg_id "
   2055                 . "AND hsr.service_service_id = s.service_id "
   2056                 . "AND $db_name_acl.centreon_acl.host_id = h.host_id "
   2057                 . "AND $db_name_acl.centreon_acl.host_id = '" . CentreonDB::escape($host_id) . "' "
   2058                 . "AND $db_name_acl.centreon_acl.group_id IN (" . $this->getAccessGroupsString() . ") "
   2059                 . ") as t )";
   2060         }
   2061
   2062         $query .= $request['order'] . $request['pages'];
   2063
   2064         $services = $this->constructResult($query, $options);
   2065
   2066         return $services;

The modifications is located in lines:
2054, 2055: Add space before "
2059: close the query by addind the missing ")"
2062: delete the close .")" move in line 2059

Sorry for the inconvenience. All work now.

**Comment by lermthya** [comment]
Hello

I made a little mistake in the correction.
The ")" must not be close in line 2062. Because if we do this, the admin
user don't work.
So i close the ")" at the end of the line 2059.

The code became:

2054 . "AND hgr.hostgroup_hg_id = hsr.hostgroup_hg_id "
2055 . "AND hsr.service_service_id = s.service_id "
2056 . "AND $db_name_acl.centreon_acl.host_id = h.host_id "
2057 . "AND $db_name_acl.centreon_acl.host_id = '" .
CentreonDB::escape($host_id) . "' "
2058 . "AND $db_name_acl.centreon_acl.group_id IN (" .
$this->getAccessGroupsString() . ") "
2059 . ") as t )";
2060 }
2061
2062 $query .= $request['order'] . $request['pages'];
2063
2064 $services = $this->constructResult($query, $options);
2065
2066 return $services;

The modifications is located in lines:
2054, 2055: Add space before "
2059: close the query by addind the missing ")"
2062: delete the close .")" move in line 2059

Sorry for the inconvenience. All work now.

2016-04-29 15:35 GMT+02:00 Laurent Pinsivy <notifications@github.com>:
