### ISSUE TITLE
CES3.3 - yum update fails due to checksum errors

### ISSUE THREAD

**Issue by oragain** [centreon/centreon#4385]
http://yum.centreon.com/standard/3.0/stable/x86_64/repodata/filelists.xml.gz: [Errno -1] Metadata file does not match checksum
Trying other mirror.
Error: failure: repodata/filelists.xml.gz from ces-standard-stable: [Errno 256] No more mirrors to try.

**Comment by querwin** [comment]
Maybe wrong timing...

I just try now and it seems to work.

Maybe, you can try a yum clean all before

**Comment by oragain** [comment]
Next time I install 3.3 I'll try that, but considering all the issues I ended up with on 3.3 I scratched that VM for the moment.
