### ISSUE TITLE
CES3.3 - IE - Critical services display superposes hosts and services

### ISSUE THREAD

**Issue by oragain** [centreon/centreon#4386]
![image](https://cloud.githubusercontent.com/assets/16800336/14825712/f731f4c8-0ba8-11e6-89cc-2c8b5f9d7e4c.png)

**Comment by querwin** [comment]
Which version of Internet Explorer are you using ?

Have you try to clean the browser cache ?

**Comment by oragain** [comment]
IE: 11.0.9600.18283
And yes I did try to clear the cache.

**Comment by querwin** [comment]
Ok I will try to reproduce the problem and I let you know

**Comment by querwin** [comment]
I've just tested on IE 11 (11.0.9600.18230).

There are some browser compatibility problems but I can't reproduce your case

**Comment by lpinsivy** [comment]
linked to #4510
