### ISSUE TITLE
CES3.3 - Web - Host and Service Ack not working

### ISSUE THREAD

**Issue by oragain** [centreon/centreon#4387]
Whether I select one or multiple services / hosts. They don't get acknowledge. (I tested in IE and Chrome)

Error that might be related:
[Tue Apr 26 12:10:33 2016] [error] [client 10.128.0.10] PHP Warning:  strlen() expects parameter 1 to be string, array given in /usr/share/centreon/www/lib/HTML/QuickForm/checkbox.php on line 126, referer: http://172.17.1.20/centreon/index.php?disconnect=1

**Comment by querwin** [comment]
Hello,

This is working for me. Do you have the same problems about downtimes ?
Are the services you want to acknowledge not in a OK status ?

Can you look at the centcore logs when you try to ackowledge a ressource ?

**Comment by oragain** [comment]
Sorry but I don't have that environment at the moment any more as I had too many issues with the new version. I also learned recently that 4.0 was in beta, so I am going to wait for CES 4.0 to do an upgrade
