### ISSUE TITLE
Problème des downtimes récurrents sur deux jours différents

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4388]
Si jamais on programme un DOWNTime récurrent de 19h à 7h du matin.
Il est nécessaire de faire deux temps d'arrêts : 19h - 23h59 et 00h - 07h.
Le problème : on reçoit tout de même un mail de notifications à 23h59 comme si le downtime s'arrêtait entre 23:59:01 et 23:59:59

**Comment by querwin** [comment]
Hello,

You're right about the two recurent downtimes but the downtime can be : 19h - 24h00 and 00h00 - 07h00, so no notifications will be sent.
