### ISSUE TITLE
Widget view changed

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4389]
Hello, 
The widget has changed :-/

Now
![piece jointe](https://cloud.githubusercontent.com/assets/10330979/14878004/f16bc96e-0d20-11e6-9d08-da75200b51b9.gif)

Before : 
![piece jointe](https://cloud.githubusercontent.com/assets/10330979/14878006/f6b16bea-0d20-11e6-9bf8-5bbfe9eea7d1.gif)

Can we have an option to show/hide this option?

Thanks in advance

**Comment by querwin** [comment]
Hello,

Whick widget have this problem ?

Can you open the ticket in the centreon-widget forge ?

https://github.com/centreon-widgets
