### ISSUE TITLE
Nginx configuration

### ISSUE THREAD

**Issue by drequivalent** [centreon/centreon#4391]
How to configure Nginx to work with Centreon web interface?
This is my current setup:
"server {
        root /usr/share/centreon/www;
        index index.php index.html index.htm;
        server_name localhost;
        location / {
                try_files $uri $uri/ /index.html;
        }
         rewrite ^/cetreon/(.*)$ /$1; #Rewrite because some links follow /centreon/ subdir
        location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
        }

}"

It works mostly okay if not for one thing. When I click to switch main menu (for example, Reporting), it disappears and just shows throbber that says "Loading..."
This is major showstopper. Please advise on how to get rid of it.

**Comment by sboulianne** [comment]
"rewrite ^/cetreon/"

Is it normal ?

**Comment by drequivalent** [comment]
See comment. Some links on pages follow /centreon/ subdir and everything breaks.

**Comment by drequivalent** [comment]
Anyone?

If necessary, I can provide you with temporary access to my installation - just so that you could see the problem.

**Comment by drequivalent** [comment]
Or wait, it doesn't break - it can live without that rewrite.
But the problem with menus is still present. If anyone runs Centreon with nginx (there should be someone, I can't be alone in this regard), please help.

**Comment by drequivalent** [comment]
Resolved. To anyone having this problem:O
Open your Nginx's mime.types file, and add xsl to "text/xml                                xml rss".
You should get this:
```
text/xml                                xml rss xsl;
```
Then restart your Nginx and clear all your browser's caches.
Then you get perfectly working menus.
