### ISSUE TITLE
[HELP] Add "centreon-nagvis" for opening Nagvis within Centreon web interface -  Centreon 2.7.4 - NagVis 1.8.5

### ISSUE THREAD

**Issue by florianocomercial** [centreon/centreon#4392]
Hi,

I installed "Centreon 2.7.4" and "Nagvis 1.8.5". The intergration with backend centreonbroker is OK, 

Now i would open Nagvis in Centreon web interface with "centreon-nagvis" Extension.

I downloaded centreon-nagvis from repository, package: "centreon-nagvis-1.1.1-3.el6.noarch", but do not create Nagvis menu.

The module is correct path:

![image](https://cloud.githubusercontent.com/assets/12894517/14908063/06fc95d8-0da8-11e6-94be-89d6de939a3b.png)

Is installed:

![image](https://cloud.githubusercontent.com/assets/12894517/14908068/24611dba-0da8-11e6-94cc-69376c9706f4.png)

And the notes are ok.

![image](https://cloud.githubusercontent.com/assets/12894517/14908070/296a856c-0da8-11e6-8134-bd504f39b292.png)

But not appear Nagios menu within the Centreon

![image](https://cloud.githubusercontent.com/assets/12894517/14908094/83e6a386-0da8-11e6-9748-4f7017f39d3e.png)

Can someone help me?

Thanks!

**Comment by querwin** [comment]
Hello,

This is a bug, open in the Centreon Nagvis forge : https://github.com/centreon/centreon-nagvis/issues/7

You can follow this ticket.

Regards,

**Comment by florianocomercial** [comment]
Thanks,


I solved my issue at the following site

http://www.sugarbug.web4me.fr/atelier/techniques/ihmweb/cartographie_supervision/centreon-nagvis/


![image](https://cloud.githubusercontent.com/assets/12894517/15081647/32503b52-139a-11e6-9e38-099f9ad1f01d.png)

**Comment by land14** [comment]
Hi 
can u guide how to install nagvis in centreon-standard-3.3-x86
