### ISSUE TITLE
Date format in monitoring page

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4396]
Hello,

The date format is not the same between "Monitoring --> Status Details" page and "Monitoring --> Downtimes" page.

"Monitoring --> Status Details" ==> DD/MM/AAAA
"Monitoring --> Downtimes" ==> MM/DD/AAAA

It will be better if the date format in downtimes page is DD/MM/AAAA

Regards,

**Comment by lpinsivy** [comment]
Hi

In UK it will be better to have YYYY/MM/DD or MM/DD/YYYY

But the date is displayed in too many different format in Centreon web.

**Comment by s-duret** [comment]
No matter the format, it must be the same in every pages.
Customer are confused when they navigate on the web interface...
