### ISSUE TITLE
IE11 - Problems with select 2

### ISSUE THREAD

**Issue by querwin** [centreon/centreon#4398]
There are a lot of problems with the select 2 on Centreon 2.7 using Internet Explorer 11.

When open a page with some select 2, there are all open.

The best way to see ot, it's on performances and event logs pages

**Comment by Tpo76** [comment]
OK

**Comment by garnier-quentin** [comment]
We have put a the version 4.0.1-rc.1. I think we should set following release: https://github.com/select2/select2/releases/tag/4.0.3

Not clean to put a rc.

**Comment by julienmathis** [comment]
Why do you reopen this ticket ?

**Comment by Ridene** [comment]
Select2's version was already upgraded to 4.0.3 and it works on IE 11.
