### ISSUE TITLE
Soft recovery after Non-OK->OK

### ISSUE THREAD

**Issue by masgo** [centreon/centreon#4399]
This is a feature request.

With non-OK states, we already can set via the retries setting how often the check is retried until the host is considered down (hard state). I want to have the same for the OK state, i.e., to be able to enforce **multiple successful retries** until the host is considered OK.

Sometimes hosts (or services) are down and recover for a short time before failing again. This is not the same as flapping, since flapping checks for frequent OK<->non-OK changes. My case is more like non-OK, non-OK, ...., non-OK, **OK**, non-OK, ... , non-OK

The problem is, that the short period of OK causes two notifications (a host-up and another host-down notification). 

Escalation schemes also do not work well, because the downtime counter starts again at zero.

**Comment by querwin** [comment]
Hello,

It's a major feature which change a lot of things in the way we're using centreon-engine.

By the way, it's not a problem about centreon-web but about centreon-engine. Can you open your ticket here : 

https://github.com/centreon/centreon-engine
