### ISSUE TITLE
[2.7.4] Contact Group in Contact Templates is missing, LDAP is not working

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4400]
Hi,
some time ago, before all the upgrades it was somewhere possible, to setup a ldap auth and if some new user login, user got created and his user got added to the Contact Groups specifyed i dont know in ldap or in Contact Templates.

Contact Groups is then linked to ACL.

At the moment if some new user login, user got created but no Group is added. So new User cannot login.

**Comment by lpinsivy** [comment]
Hi,

ACL Groups must be linked to LDAP Groups so why you need to add contactgroup in contact template form?

**Comment by lpinsivy** [comment]
No answer => closed
