### ISSUE TITLE
Manage system v and systemd init script for Centreon Engine

### ISSUE THREAD

**Issue by julienmathis** [centreon/centreon#4401]

**Comment by querwin** [comment]
I see the options in Centreon but I don't think it's ok

**Comment by julienmathis** [comment]
Why ?

**Comment by querwin** [comment]
i try to modify it in a poller configuration. I can see in my centcore.log : 

2016-07-27 12:49:48 - Init Script : 'sudo /etc/init.d/centengine reload' On poller xxxxxx (3)

Anytime

**Comment by julienmathis** [comment]
You have to validate this in a 100% systemd environment. It will not work if you have /etc/init.d/centengine script present on your server

**Comment by querwin** [comment]
So impossible to have Central in systemv and poller in systemd ?
