### ISSUE TITLE
Fullscreen Mode over GET parameter

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4408]
Please add a function to use like https: //server. de/centreon/main.php?p=20204&o=svcOV_pb& **full_screen=true**

A client ask about this function in combination with the autologin function. So that it can be used for a kiosk computer, so the existing space is used optimal and no space is lost by an unnecessary url bar or other stuff (buttons,..)

Furthermore the fullscreen mode should include the top counter statics on the right top corner. Or alternative a option so the user can decide if the top counter is shown or not.

**Comment by Sims24** [comment]
Hi @itsul 

Does https: //server. de/centreon/main.php?p=20204&min=1&o=svcOV_pb is what you want ? 

Thanks
