### ISSUE TITLE
Issue with Resources Configuration with multiple Pollers

### ISSUE THREAD

**Issue by DaStivi** [centreon/centreon#4409]
Hi,
there is an Issue when using multiple Pollers with Resource Configuration...

I've multiple "Names" (Variables, $UserX$) used with different Values for different Pollers, the Overview Shows the Poller assignment correctly, but as soon as i would like to edit a Name/Value with just a single poller assigned in the Edit View all Pollers are mysteriously selected in the "linked instances" field...

when saving without clearing the unnecessary pollers the config gets messed up!

![image](https://cloud.githubusercontent.com/assets/7464802/15207457/b7f01026-1826-11e6-90af-5336a572629d.png)

![image](https://cloud.githubusercontent.com/assets/7464802/15207497/e0634654-1826-11e6-9984-da78bd2bd927.png)

best regards
Stephan

**Comment by julienmathis** [comment]
Hello, 

Can you check that your problem is fixed with the linked commit ?

Thanks

**Comment by DaStivi** [comment]
i did the change manually as centreon-web 2.8 isn't in enterprise repo yet....
after changing the line in /usr/share/centreon/www/class/centreonInstance.class.php it doesn't look like that the issue is gone.. still when editing a resource where just one poller is selected on the next page all pollers or a different one is in it!
