### ISSUE TITLE
General Bug while selecting (input fields)

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4410]
After selecting a search result and selecting a second one, you have to delete the search string first. It should be auto cleared after an selection.

![image](https://cloud.githubusercontent.com/assets/12328177/15240255/a58d4a44-18e8-11e6-95a2-a430d56a2563.png)

It is annoyingly to delete it, specialy by adding hosts to hostgroups etc.

**Comment by benoiteolas** [comment]
I didn't agree with you. 
If you must select several items in a rows the current behavior is much better.

**Comment by julienmathis** [comment]
Yes I agree with @benoiteolas. It was a pre-requisits to keep it in memory when I ask developpers to implement this new element in forms.
