### ISSUE TITLE
Poller macro

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#4417]
Hi,

Can you please add new macro, that shows the poller where the device is monitored from.

**Comment by julienmathis** [comment]
Hello, 

Where do you need this macro ? notification ? URL action ? URL notes ?

Regards

**Comment by kadrika** [comment]
Mostly in email and SMS notifications.

**Comment by cgagnaire** [comment]
It is now done with POLLERID and POLLERNAME macros.
