### ISSUE TITLE
Display downtime and ack on service statuses page

### ISSUE THREAD

**Issue by bcournaud** [centreon/centreon#4420]
Centreon Web version 2.7.3

If a service is acknowledged or in downtime, it appears in the _Monitoring -> Status details -> Services_ page.
But if you click on an host, you have the listing of all the services, their statuses, but no information about their acknowledgment or downtime (cf images).

![selection_244](https://cloud.githubusercontent.com/assets/13016403/15383952/406b34a6-1d97-11e6-87c8-bf3efec403e7.png)

![selection_245](https://cloud.githubusercontent.com/assets/13016403/15383968/5a3f1f3c-1d97-11e6-9989-71321d9757aa.png)

**Comment by cmeschin** [comment]
Hello, as for the Downtimes and acks, can you add the Url links in this view?
thanks,
