### ISSUE TITLE
Custom View Parameters > Host categories, service categories and metric name : multiselect

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#4423]
Hi,

As asked in the issue #3876 , please improve the new parameters containing Host categories, service categories and metric name to be available as multiselect parameter too.

> > > MON-799

Thanks in advance

**Comment by mvisini** [comment]
Bonjour, 

pourquoi ce ticket a été fermé ? 
Cela n'est plus au programme ? 

Merci

**Comment by lpinsivy** [comment]
@mvisini On PR are closed, not this issue.

Maybe the code style was not correct.

**Comment by Moujimouja** [comment]
Implemented
