### ISSUE TITLE
Widget Servicegroup Monitoring Bug

### ISSUE THREAD

**Issue by kpal38** [centreon/centreon#4425]
Bonjour,

Je remarque un soucis aves les widgets:

Lorsque j'ajoute un widget "Servicegroup Monitoring" (version du widget 1.3.0).
Mon tableau ne s'affiche pas en face de l'écran, je dois déplacer le curseur vers la droite pour afficher mon tableau.

2eme problème:
Dans ce même widget, le lien vers le graphique et le lien vers la vue de la machine ne fonctionne pas: l'url de destination ne pointe pas vers le bon chemin: "L'erreur suivante s'est produite en essayant d'accéder à l'URL : http://main.php/?"

Quelqu'un a-t-il déjà rencontré ce type de problème ?

Merci d'avance pour vos réponses.

**Comment by julienmathis** [comment]
Bonjour, 

Problème corrigé. Mise en ligne ce jour même avec une version 1.3.1.

Bonne journée

**Comment by kpal38** [comment]
Bonjour,

Merci pour la mise à jour du widget, ça fonctionne parfaitement !

Par contre j'ai le même problème lorsque je vais dans "Monitoring -> Performance" et que j'ajoute un service. Le graphique se met à droite de la fenêtre au lieu de se mettre en face.

Merci :)
