### ISSUE TITLE
Refresh button on the page " service detailled"

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4427]
Hi team,

Is it possible to get a button to refresh the information on the page Service detailed?
<img width="1093" alt="cap 2016-05-20 a 13 48 42" src="https://cloud.githubusercontent.com/assets/10330979/15426896/b56fdaa4-1e91-11e6-85da-4a936b4266b6.png">

Thanks in advance.

**Comment by julienmathis** [comment]
test : F5 or cmd + R ? it's not enougth

**Comment by matthieu-robin** [comment]
It could, but we reload all the page, not only detailled datas, no?

See you tomorrow ;-)

**Comment by julienmathis** [comment]
Oh ! impossible to implement AJAX reload on this page... Sorry, we can't to that.
