### ISSUE TITLE
Add icon next to the text on right

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4428]
Hello team,

For a better ergonomic view, it should be fine to got some icons next to the text (on right) on this page:
<img width="1121" alt="cap 2016-05-20 a 13 50 18" src="https://cloud.githubusercontent.com/assets/10330979/15426925/eff2760a-1e91-11e6-8357-409e72cd11d4.png">

Thanks a lot

**Comment by Moujimouja** [comment]
Duplicates https://github.com/centreon/centreon/issues/4271
