### ISSUE TITLE
Poller list -> config changed

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4430]
On old Centreon version we got a color when the conf have changed on a poller, on the poller list page.
From 2.7, we have only the text.

Is it possible to add a color?
<img width="473" alt="cap 2016-05-20 a 13 55 02" src="https://cloud.githubusercontent.com/assets/10330979/15427032/8f8f83ba-1e92-11e6-813f-aeeb154716b0.png">

Thanks

**Comment by julienmathis** [comment]
Yes we will do it !
