### ISSUE TITLE
Macro of a Macro

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4431]
Hi team,

Is it possible to use a Macro ($HOSTNAME$) into a SERVICE or HOST Macro?

Thanks in advance

**Comment by Sims24** [comment]
Hi Matthieu, 

Not yet ... This is implemented here -> https://github.com/centreon/centreon-engine/issues/1

Waiting for release ... =) 

++

**Comment by Sims24** [comment]
same as https://github.com/centreon/centreon/issues/3791
