### ISSUE TITLE
Arbre de sélection dans les graphiques de performances

### ISSUE THREAD

**Issue by matth-le-roy** [centreon/centreon#4433]
Bonjour,

Dans la documentation Centreon actuellement en ligne il y a un paragraphe filtre qui dit : 

Il est possible de filtrer la sélection des ressources via :

La barre de recherche rapide en recherchant par hôte ou service
En parcourant l’arbre de sélection (menu de gauche) par groupe d’hôtes, puis par hôte, puis par service dont afficher le graphique
En parcourant l’arbre de sélection (menu de gauche) par groupe de services puis par service dont afficher le graphique.

Or cela n'est plus présent dans la version 2.7.4.

Est-ce que cela va être remis lors de prochaines version?

Car cela est un réel frein chez nous pour la migration vers la nouvelle version qui est vraiment mieux sur beaucoup d’aspects. Merci d'avance pour votre retour sur le sujet.

Cordialement,

Matthieu

**Comment by matth-le-roy** [comment]
Bonjour,

Finalement j'ai vu que le problème avait déjà été remonté et même corrigé dans #4328 .
Est-ce que je peux simplement remplacer les fichiers graphs.ihtml et graphs.php dans mes versions 2.7.3 et 2.7.4 de production ou est-ce que je doit attendre la sortie de la version 2.8?

PS : Merci pour l'excellent travaille fait sur ces nouvelles versions.

Cordialement,

Matthieu

**Comment by julienmathis** [comment]
Bonjour, 

Hélas, cela ne sera pas remis dans les prochaines versions. Mais dans la version 2.8, il sera possible de faire des recherche par hostgroup et servicegroup. Ce qui revient au même.

Est ok pour vous ?

**Comment by matth-le-roy** [comment]
Parfait, est-ce qu'il y a une date approximative de sortie pour la version qui aura la recherche par hostgroup et servicegroup incluse?

**Comment by julienmathis** [comment]
normalement mi-juin !

**Comment by matth-le-roy** [comment]
Merci.
