### ISSUE TITLE
RRSCached /  suite à  la génération de la configuration le fichier central-rrd.xml ne se met pas à jour

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#4434]
Suite à  la génération de la configuration le fichier central-rrd.xml ne se met pas à jour après mise en place de RRDCached.

<path><![CDATA[/var/rrdtool/rrdcached/rrdcached.sock]]></path>  Cette ligne n'est pas ajoutée

![mobaxterm_2016-05-23_10-54-37](https://cloud.githubusercontent.com/assets/16045498/15465489/01e25926-20d5-11e6-9847-7081c12e2a7f.png)

**Comment by garnier-quentin** [comment]
Duplicate #5461
