### ISSUE TITLE
Apostrophe doesn't work on Host Alias

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4439]
Apostrophe doesn't work on Host Alias, and forget to be mentioned on the CSV loader.

**Comment by julienmathis** [comment]
hello,

Which version ? It works fine on 2.7.4.

Regards,

**Comment by matthieu-robin** [comment]
On 2.7.4... 
Strange, I'll try again and let you know.

Thanks Julien

**Comment by julienmathis** [comment]
Pas moyen de reproduire de mon côté. Rouvre si tu y arrives...
