### ISSUE TITLE
Extended Status Mouseover

### ISSUE THREAD

**Issue by Justice81** [centreon/centreon#4442]
Hello,

we are moving our internal Monitoring from 2.5.1 to 2.7.3 and have some problems.

The extended status information is missing in the services list mouseover.

**Comment by julienmathis** [comment]
Bonjour, 

Je peux savoir dans quelle page ? 

Quel navigateur ?

Merci

**Comment by Justice81** [comment]
main.php?p=20201&o=svc&search=

Chrome 50.0, IE10, Firefox 46.0.1

**Comment by julienmathis** [comment]
Je n'ai aucun souci. Peux tu regarder avec les outils de debug du navigateur si tu as des warnings ou erreurs JS ?

**Comment by Justice81** [comment]
I hope google translated french right.

There are no errrors, but i think i found the problem.

it is in include/monitoring/status/Services/xml/makeXMLForOneService.php 

there is no code for extended status.


in 2.5.1 and NDO it works
include/monitoring/status/Services/xml/ndo/makeXMLForOneService.php 

![image](https://cloud.githubusercontent.com/assets/18530724/15547755/81dc192e-22a5-11e6-9e14-5893594d619e.png)



include/monitoring/status/Services/xml/broker/makeXMLForOneService.php 

![image](https://cloud.githubusercontent.com/assets/18530724/15547778/a316d43a-22a5-11e6-8497-f5d7d72daf1d.png)

I hope i am right with this.

**Comment by julienmathis** [comment]
Your french is good :) Sorry for speaking to you in french. 

Oh thank's. I will check that point.

**Comment by julienmathis** [comment]
Hello, 

I remember why we decide to remove long output. In some case, long output can take to much place when there are more that 10 lines per example. In this case we can't be able to display the popup correctly et efficiently.

The thing I can do is to limit to 4 lines per example the long output.

Ok for you ?

**Comment by Justice81** [comment]
Great,

4 lines would be enough the most times.

merci beaucoup

**Comment by julienmathis** [comment]
Sorry my commit was not clean. The last commit should be ok.

**Comment by Justice81** [comment]
i think your commit is not enough.

long_output is a seperate field in database  or am i wrong?

In the Get Service status was in the old version a " s.long_output," .  Line 112
(but if i implement this i get a error 500)

the include/monitoring/status/Services/xsl/popupForService.xsl needs to be edited too.

**Comment by Justice81** [comment]
Works really good.
even with more lines the performace ist very good.

**Comment by julienmathis** [comment]
What that meens ?

**Comment by querwin** [comment]
I think informations are missing for service notifications

**Comment by Tpo76** [comment]
Nope we just don't see any extend information on the mouseover popup.
I'm here tomorrow we can check if I understood something wrong.

**Comment by Tpo76** [comment]
https://github.com/centreon/centreon/pull/4575

**Comment by kduret** [comment]
![image](https://cloud.githubusercontent.com/assets/11978823/18082071/73e515d4-6e9d-11e6-9d34-fd2693f76e0d.png)
![image](https://cloud.githubusercontent.com/assets/11978823/18082087/87be9134-6e9d-11e6-987d-97a439abd448.png)
It works with Centreon 2.8.0-beta2

**Comment by Tpo76** [comment]
OK juste one more change #4675
