### ISSUE TITLE
fichiers générés contiennent des espaces en fin de ligne

### ISSUE THREAD

**Issue by GhilesKDH** [centreon/centreon#4445]
Bonjour, 
Sur la nouvelle version centreon 2.7.4
Les fichiers générés contiennent des espaces à la fin de la ligne exemple resource.cfg.
Ceci nous a posé des soucis sur quelques DEV, qui se basent sur les fichiers CFG générés.
Nous essayons d'adapter nos scripts, mais je tiens à vous donne mon feedback car je pense que c'est une petite régression, 
Cordialement,

**Comment by tanguyvda** [comment]
D'après des tests, le changement semble être apparu entre la 2.7.3 et la 2.7.4

**Comment by julienmathis** [comment]
@tanguyvda peux tu valider mon commit ?

**Comment by tanguyvda** [comment]
Je valide, plus d'espaces merci Julien

**Comment by GhilesKDH** [comment]
Merci @julienmathis pour ta réactivité :+1:

**Comment by querwin** [comment]
Le changement est apparu avec la 2.7.2.

Ce changement a été réalisé pour corriger ce ticket : https://github.com/centreon/centreon/issues/4145
