### ISSUE TITLE
activer automatiquement rotation des vues

### ISSUE THREAD

**Issue by nogomes** [centreon/centreon#4447]
Bonjour,

Pour une TV de supervision, nous avons créé un utilisateur dédié avec une URL d'autologin.

Si on ne rafraichit pas régulièrement la page du navigateur (rechargement de l'URL d'autologin), sa session expire. Pour contourner, nous utilisons une extension de navigateur qui rafraichit une page sur une période donnée.

Le problème est qu'avec ce rafraichissement (équivalent d'un F5), la page d'accueil est rechargée, et la rotation des Vues n'est plus active.

Serait-il possible de faire en sorte qu'on ne perde pas la rotation des vues lors d'un rafraichissement de la page d'accueil (par ex une option à passer dans l'URL) ?

Merci

Norbert

**Comment by julienmathis** [comment]
Quelle distribution utilises tu ?

**Comment by nogomes** [comment]
On a testé sur une Debian 8 et Ubuntu 15.10, avec Firefox et Chromium

**Comment by bcournaud** [comment]
Hi,

I have the same issue on Firefox 47.0 & Chromium 51.0.2704.79 Ubuntu 16.04 (64-bit).
The OS is Xubuntu 16.04

I guess it's also linked to the issue  #4402

Best regards,

**Comment by lpinsivy** [comment]
Works for me
