### ISSUE TITLE
perte des perfdata des méta-services au redémarrage du collecteur

### ISSUE THREAD

**Issue by nogomes** [centreon/centreon#4449]
Bonjour,

J'ai remarqué que lorsque je recharge la configuration de mon collecteur en le redémarrant (pas en rechargeant), je perds les graphes de performance de tous mes méta-services.

Est-ce normal et y'a t-il un moyen de les regénérer ?

Je suis en version 2.7.4

En vous remerciant

Norbert

**Comment by lpinsivy** [comment]
Hi

After many test I never lost my graphs of meta-services with reload and restart of central Centreon Engine.

So please what is your version of Centreon Engine and Centreon Broker components ?

Regards

**Comment by lpinsivy** [comment]
HI,

You can reproduce this issue.
Will try to correct it for next version.

Regards,

**Comment by lpinsivy** [comment]
fix by commit 03b6dbe
