### ISSUE TITLE
Acknowledg

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4450]
Bonjour,

Lors des redémarrage de nos pollers nous devons à chaque fois remettre en place les "Acknowledg", alors que nous avons bien coché la case : "Persistent".

WEB: 2.7.4
Centengine : 1.5.0
Broker : 2.11.3

Je viens de voir qu'une nouvelle version du Broker est en ligne, donc je ne sais pas si le problème a été corrigé dans la version 2.11.4

**Comment by ganoze** [comment]
Nous n'avons pas connaissance de bug de ce genre. La première piste qui me vient à l'esprit est une erreur de configuration de la rétention. Pouvez-vous m'indiquer quelle valeur ont les paramètres suivants.

* status file
* state retention option
* state retention file
* use retained program state option
* use retained scheduling info option
* retained * mask

De plus vous indiquez que le problème intervient lors du redémarrage des pollers. S'agit-il d'un redémarrage des machines ou des processus de Centreon ?

**Comment by jben94** [comment]
Bonjour,

Le redémarrage concerne que le processus "Centengine".

Il est possible qu'il y est une erreur dans notre configuration, voici des imprimes écran de notre configuration : 

![ret1](https://cloud.githubusercontent.com/assets/16583698/15848573/056cc300-2c8e-11e6-85a1-3dc9c2500911.PNG)
![ret2](https://cloud.githubusercontent.com/assets/16583698/15848575/0573487e-2c8e-11e6-9ce7-7d18a036a477.PNG)
![ret3](https://cloud.githubusercontent.com/assets/16583698/15848574/056fd720-2c8e-11e6-8f81-3345817465d3.PNG)

**Comment by jben94** [comment]
Comme vous l'aviez dit, une erreur de configuration s'était glissé dans un template.
Désolé et merci pour votre aide.
