### ISSUE TITLE
centreontrapd dead but pid file exists

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon#4464]
Hi,
I think many users have this issue so I decided to create a bug report.
I use Centreon2.7.4 and all the packages are up to date.

I generate centreontrappd.sdb but the service wont stay UP.
Please check this post too.
https://forum.centreon.com/forum/centreon-collect/centreon-trap/141529-centreontrapd-disappear-immediately

I checked all the things, I use the default config and it still dont work.

Thanks in advance.

Sébastien

**Comment by Naelwan** [comment]
Same issue for me, on both centreontrapd and centcore.

BR 
Thomas

**Comment by sboulianne** [comment]
Quentin told me its a known bug.
I began to check my config files with him and he told me thats should work fine.
I regenerate my config SNMP DBs and I tested it.
It looks like the issue is now resolved.

]# service centreontrapd status
centreontrapd (pid  19361) is running...

P.S: I use all the latest Centreon packages.
Thanks you very much guys.

**Comment by sboulianne** [comment]
Look fixed
