### ISSUE TITLE
Macro erased with a massive change

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4470]
Hello,

In centreon 2.7.4, i set a macro on a host (INTERFACEID) which inherits of template A. 

Then i replace template A by template B (whitch also use INTERFACEID), the macro haven't change, which is normal.
But when i replace the template via a massive change, the macro is erased.

Thank you!

**Comment by julienmathis** [comment]
moi aussi je viens de retester...

**Comment by julienmathis** [comment]
It works on host configuration page
