### ISSUE TITLE
Old css to remove in the plugin-pack

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4472]
Bonjour;

A la suppression d'un plugin-pack, c'est encore encore l'ancien design.

![old css](https://cloud.githubusercontent.com/assets/13255513/15955948/5f79a0f8-2ee5-11e6-9ca8-6530536f0525.jpg)

Cdlt

**Comment by julienmathis** [comment]
Will be fixed in Centreon 2.8 with new PP system.
