### ISSUE TITLE
Display Downtime Cycle in "Monitoring - Downtimes"

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4473]
Bonjour,

Serait-il possible de sélectionner une durée pour l'affichage des downtimes cycliques ?
Par défaut dans le menu "Monitoring - Downtimes", les downtimes cycliques ne s'affichent que 10 minutes avant de commencer. Il serait intéressant d'avoir le choix pour sélectionner une période (exemple : Dernières 24h).

Cdlt

**Comment by julienmathis** [comment]
Ce n'est pas un problème d'affichage. C'est juste qu'ils ne se créent que 10 minutes avant... Tout changement avec les prochaines évolutions. Ils seront créés à la fin du downtime. Ils seront donc visibles comme demandé ici.
