### ISSUE TITLE
"More Actions" do Not work for services in main status details page for centreon 2.7.4-8

### ISSUE THREAD

**Issue by asalaices** [centreon/centreon#4474]
None of the Actions work, however they do work when you click on the service and choose an "Option" .

My relevant Installed RPM's 

centreon-2.7.4-8.el6.noarch
centreon-base-config-centreon-engine-2.7.4-8.el6.noarch
centreon-broker-2.11.4-1.el6.x86_64
centreon-broker-cbd-2.11.4-1.el6.x86_64
centreon-broker-cbmod-2.11.4-1.el6.x86_64
centreon-broker-core-2.11.4-1.el6.x86_64
centreon-broker-storage-2.11.4-1.el6.x86_64
centreon-clib-1.4.2-1.el6.x86_64
centreon-common-2.7.4-8.el6.noarch
centreon-connector-1.1.2-1.el6.x86_64
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-engine-1.5.0-10.el6.x86_64
centreon-engine-daemon-1.5.0-10.el6.x86_64
centreon-engine-extcommands-1.5.0-10.el6.x86_64
centreon-perl-libs-2.7.4-8.el6.noarch
centreon-plugin-meta-2.7.4-8.el6.noarch
centreon-plugins-2.7.4-8.el6.noarch
centreon-poller-centreon-engine-2.7.4-8.el6.noarch
centreon-trap-2.7.4-8.el6.noarch
centreon-web-2.7.4-8.el6.noarch

**Comment by julienmathis** [comment]
Hello, 

In which page ?

Thanks

**Comment by julienmathis** [comment]
I forgot one question : which browser ?

**Comment by asalaices** [comment]
Wow ! Feel so lucky to get a response from the Man himself ;)

It happens on all the browsers I have tried:

Chrome

Firefox

Safari


The log from one of the "disable notification" operations in the main 
service status screen :


127.0.0.1 - - [10/Jun/2016:10:52:04 -0700] "GET 
/centreon/include/monitoring/status/Notifications/broker/notifications.php?sid=nl55j4aiedt0g3sm3s95beo3d3&refresh_rate=15000 
HTTP/1.0" 200 47 
"https://sample.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc&statusFilter=&select_instance=-1&host_search=regis&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bhost.corp.intuit.net%3BCatalog%2BPing%5D=1&o2=0&p=202&l=30&cmd=81&o=&limit=30&centreon_token=a2fb46498f457e3cb0df7a0127f19e16" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 
Firefox/46.0"

This one works (from the actual service detail screen)


127.0.0.1 - - [10/Jun/2016:10:53:50 -0700] "GET 
/centreon/include/monitoring/objectDetails/xml/serviceSendCommand.php?cmd=service_notifications&host_id=83&service_id=126&actiontype=1 
HTTP/1.0" 200 165 
"https://sample.intuit.net/centreon/main.php?p=20201&o=svcd&host_name=host.corp.intuit.net&service_description=Catalog+Ping" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 
Firefox/46.0"


If you have any more questions please do not hesitate to ask.


Thanks.


Adrian Salaices.

**Comment by julienmathis** [comment]
Hello, 

Ok thanks for all information. 

Possible to have a screen shot ? 

Thanks in advance

**Comment by asalaices** [comment]
Sorry .. Email got lost in SPAM ;)

*Does Not work from main status screen*




*Upon executing from the detail window, it works fine**
*



*Interestingly I see no error on the apache log or anywhere else that 
may indicate a problem *

127.0.0.1 - - [22/Jun/2016:11:15:38 -0700] "GET 
/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045 
HTTP/1.0" 200 84238 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=6ac9bdeef49be894806536cff1c43188" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:39 -0700] "GET 
/centreon/Themes/Centreon-2/Modalbox/Color/green_css.php HTTP/1.0" 200 
411 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:39 -0700] "GET 
/centreon/Themes/Centreon-2/Color/green_css.php HTTP/1.0" 200 4502 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:39 -0700] "GET 
/centreon/include/monitoring/status/Notifications/broker/notifications.php?sid=71mq9voa41bfq0bh7buvgm6261&refresh_rate=15000 
HTTP/1.0" 200 47 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:39 -0700] "GET 
/centreon/include/common/javascript/autologoutXMLresponse.php HTTP/1.0" 
200 125 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:39 -0700] "GET 
/centreon/include/monitoring/status/Services/xml/serviceXML.php?&search=&search_host=303&search_output=&num=0&limit=30&sort_type=last_state_change&order=ASC&date_time_format_status=d/m/Y%20H:i:s&o=svc_unhandled&p=202&host_name=&nc=0&criticality=0&statusService=svc_unhandled&statusFilter=&sSetOrderInMemory=0 
HTTP/1.0" 200 3421 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:40 -0700] "POST 
/centreon/include/monitoring/status/TopCounter/xml/statusCounter.php 
HTTP/1.0" 200 733 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:40 -0700] "POST 
/centreon/include/monitoring/status/Common/setHistory.php HTTP/1.0" 200 
- 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:40 -0700] "POST 
/centreon/include/monitoring/status/Common/setHistory.php HTTP/1.0" 200 
- 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:40 -0700] "POST 
/centreon/include/monitoring/status/Common/setHistory.php HTTP/1.0" 200 
- 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"
127.0.0.1 - - [22/Jun/2016:11:15:40 -0700] "GET 
/centreon/include/monitoring/status/Services/xml/serviceXML.php?&search=&search_host=303&search_output=&num=0&limit=30&sort_type=last_state_change&order=ASC&date_time_format_status=d/m/Y%20H:i:s&o=svc_unhandled&p=202&host_name=&nc=0&criticality=0&statusService=svc_unhandled&statusFilter=&sSetOrderInMemory=0 
HTTP/1.0" 200 3421 
"https://ptgops.intuit.net/centreon/main.php?p=202&o=svc&statusService=svc_unhandled&statusFilter=&select_instance=-1&host_search=303&search=&hostgroups=0&output_search=&o1=0&p=202&l=30&select%5Bserver303.corp.intuit.net%3BDisk-%252F%5D=1&o2=0&p=202&l=30&cmd=4&o=&limit=30&centreon_token=c54d2d62588564fa1c0c91feb812b045" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 
Firefox/47.0"

Please let me know if you need anything else.

Thanks

Adrian Salaices
