### ISSUE TITLE
Metaservice notification problem

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4475]
Hi,

In centreon 2.7.4, there is a problem with the notification of meta services (service-notify-by-email).

The name of the metaservice is changed by Meta_x (where x is the meta_id):

Subject of the email:
** PROBLEM alert - Meta Service Calculate Module For Centreon/**meta_1** is WARNING **

Body of the email:
***** centreon Notification *****

Notification Type: PROBLEM

Service: **meta_1**
Host: Meta Service Calculate Module For Centreon
Address: 127.0.0.1
State: WARNING

Date/Time: 10-06-2016 Additional Info : Average - traffic_in : 0.00

**Comment by julienmathis** [comment]
Hello,

Please use $SERVICEDISPLAYNAME$ in the command in order to have the name of the meta.

BR
