### ISSUE TITLE
[Monitoring][Performance] - Amélioration Filtre Hotes et Services

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4476]
Bonjour,

Est-il possible de mettre en place une option permettant de filtrer les hotes et les services de manière dépendante?
Il faudrait pour cela ajouter une case à cocher "ET/OU" entre le champ hôte et le champ service. (cf PJ)
![evolution_info_performance](https://cloud.githubusercontent.com/assets/8720203/16007411/89f5000e-3172-11e6-99d4-25f6e44dd919.png)

Actuellement, il n'y a aucune corrélation entre ces deux champs; un filtrage sur certains hôtes ne limitent pas le filtrage sur les services (option "OU").

Une seconde amélioration serait de pouvoir filtrer avec des caractères jocker (champ hote et service). a moins que ce ne soit déjà possible mais je n'ai pas trouvé la syntaxe (ni \* ni %) comme c'est actuellement le cas dans la vue supervision.

cordialement,

**Comment by lpinsivy** [comment]
Bonjour,

Si je comprends bien le filtre "OU" est le fonctionnement actuel et le filtre "ET" est un filtre d'inclusion. Seul les services sélectionnées sont visible ? N'est-ce pas le fonctionnement actuel en supprimant le contenu du filtre "hosts" et en ajoutant manuellement des services ?

Que pensez-vous de l'idée de préremplir le contenu du filtre "sevices" à partir des hôtes sélectionnés dans le filtre "hosts" puis de pouvoir ensuite modifier tout ou partie du contenu du filtre "services" ? L'diée serait de prendre un fonctionnement similaire à la page "EventLogs" ou les champs "hostgroups" et "servicegroups" peuvent remplir les champs "hosts" et "services"

**Comment by cmeschin** [comment]
Bonjour,

Le fonctionnement actuel est effectivement un "OU", mais n'est pas forcément à changer totalement car il peut convenir à certaines personnes  et probablement tout à fait fonctionnel sur de petites infrastructures avec un nombre limité de services.
Actuellement si je souhaite n'afficher que les services "traffic" des hôtes "Firewall", je suis obligé
   - soit de filtrer dans le champ service, les hôtes de type firewall et de sélectionner un à un chaque service dans la totalité de ceux affichés (parfois plusieurs dizaines voire centaines);
   - soit de filtrer dans le champ service, les services contenant "traffic" et sélectionner encore un à un les services souhaités parmi les tous les hôtes ayant au moins un service "traffic" (parfois plusieurs dizaines ou centaines).

Le problème actuel sur le champ service est que l'on ne peut pas filtrer sur l'hôte ET le service. c'est l'un ou l'autre (surement lié à la façon de construire l'information affichée). A moins qu'une syntaxe particulière existe mais je ne l'ai pas trouvée ou alors il y a un bug.

Préremplir le champ service risque d'alourdir l'interface et les temps de réponse.
Si je ne souhaite que deux ou trois services, je les ajoute alors que s'ils sont tous inclus je suis obligé de supprimer tous ceux que je ne veux pas => potentiellement moins pratique.

concernant la page eventlogs, je vient de découvrir la fonctionnalité de chargement des hôtes et services à partir des groups. personnellement je ne me sers de cette page que depuis un hôte ou un service et donc le filtre est automatiquement positionné :)
 
L'ajout des listes HostGroup et ServiceGroup dans la 2.8 facilitera les filtres actuels à condition qu'ils soient complémentaires ("ET")

La vue "détail des statuts" est pour moi parfaitement fonctionnelle avec les différents filtres complémentaires.

**Comment by Moujimouja** [comment]
Hi,

This behavior has been improved so that you can first select the perimeter (hostgroup or host) and then select the chart you want to display.

From my POV, this enhancement is deprecated because of evolutions already availabler on this page.

I close the ticket
