### ISSUE TITLE
Centreon not honoring "Notification Interval" or "First notification delay"

### ISSUE THREAD

**Issue by nvucinic** [centreon/centreon#4479]
Centreon 2.7.4 - Centreon Enterprise Server
Hello, Centreon is not honoring "Notification interval"  and "First notification delay" for any service. 
It's always kinda globally set to 1 minute for all services no matter what notification interval is set to.

**Comment by lpinsivy** [comment]
Hi,

Which version of Centreon Engine do you use ?

Regards,

**Comment by julienmathis** [comment]
Can we have more information please ?

**Comment by julienmathis** [comment]
No enough information.
