### ISSUE TITLE
Host and services configuration to csv

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#4486]
Hi,

Can you please add enhancement to that hosts.cfg and services.cfg can be exported to CSV file? We need to check and compare service/host configurations from time to time, to see if everything is configured exactly as we need. Using CSV file would do the magic perfectly.

**Comment by querwin** [comment]
Hello,

It's possible to do a full export using CLAPI : 

centreon -u admin -p centreon -e > /tmp/test

**Comment by kadrika** [comment]
I will test it tomorrow morning if the output is something I can use or or not.

**Comment by kadrika** [comment]
It is quite ok, but littlebit annoying to use clapi for it, instead of having to do one click in web.

**Comment by kadrika** [comment]
I also tried this in frontend, where we have almost 800 hosts and 6500 services the export does not work. It waits and waits and the export file is not generated. It seems to timeout or something like that.

**Comment by kadrika** [comment]
Any news about this? Will future versions have CSV file generation option? It would make our life much easier, as gives us complete overview of the configurations, and it would give us option to standardize our configurations and easily notice if someone has mis configured some notification thresholds, contacts etc.

**Comment by lpinsivy** [comment]
Hi,

We will not add the CSV export option in Centreon.

As explained by @querwin, CLI and REST API are present to manage configuration.

You can export full hosts configuration [using filtering option in CLAPI](https://documentation.centreon.com/docs/centreon/en/2.8.x/api/clapi/import_export.html#export-of-a-subset-of-objects)

Regards,
