### ISSUE TITLE
Change type of some fields

### ISSUE THREAD

**Issue by jerominos** [centreon/centreon#4488]
Hi,

in my database "centreon_storage", my tables : "hosts" and "services", the field "perfdata" is defined as a TEXT.

My problem is, i have some personnals plugins that generate perfdata taller than the number of characters allowed by this type of field.

Can i change the type to LONGTEXT ?

Do you think it is pertinent to be the default type for the futur ?

Regards,
Jérôme

**Comment by ganoze** [comment]
With the current implementation of Centreon Broker you should have no problem to store your perfdata in a LONGTEXT field.

IMHO updating this field to MEDIUMTEXT should be a reasonable default.

@julienmathis what do you think about this ?

**Comment by julienmathis** [comment]
Sorry I think that having so much metrics by service is completely useless. How are your graphs ? non readable as I imagine... I'm not ok to enlarge the field in the generic solution.

BR
