### ISSUE TITLE
[Feature Request] centreon-agent (something i'm working on)

### ISSUE THREAD

**Issue by george-vieira** [centreon/centreon#4490]
Hi,

I've been developing an passive agent for centreon (yes, yet another NSCA/NRDP, etc with a twist) and I was hoping you could speed up my research in one part of the system I'm developing.

I've been trying to work out from the centreon schema how to get a list of services for a host and it's command parameters. I thought of looking in the poller generate section but couldn't work it out.
One place I managed to get what appears to be correct info was from centreon_storage but that appears more a status output I received not a list of service checks for a host. So  I would have expected a newly added service would possibly not sure until first status is received (didnt get to check that yet).

Are you able to help with this info? This project will become a github project for freely use eventually when it's worth uploading.

**Comment by george-vieira** [comment]
god damn it, search for an hour and then post. minutes later I find it.

SELECT s.service_id, s.service_description FROM service s JOIN (SELECT hsr.service_service_id FROM host_service_relation hsr JOIN host h ON hsr.host_host_id = h.host_id WHERE h.host_name = '${host}' UNION SELECT hsr.service_service_id FROM hostgroup_relation hgr JOIN host h ON hgr.host_host_id = h.host_id JOIN host_service_relation hsr ON hgr.hostgroup_hg_id = hsr.hostgroup_hg_id WHERE h.host_name = '${host}' ) ghsrv ON s.service_id = ghsrv.service_service_id

**Comment by julienmathis** [comment]
Hello, 

Did you check this WS present in Centreon 2.8 ? 

https://github.com/centreon/centreon/blob/2.8.x/www/api/class/centreon_results_acceptor.class.php

You can call the centreon API and pass results by WS. If host and service are not created, the WS will do it...

This work is in dev but we will finish it very soon. May be you can work on the python or perl script to contact the WS ? 

Regards

**Comment by george-vieira** [comment]
I'm not trying to add to centreon automatically. I want passive checks managed by cenreon.
I kind of wanted to use centreon web interface to manage everything but with NSCA and NRDP knowing nothing what the master has configured, you would have to use ansible or puppet manage check configuration files etc into the monitored server. What I'm trying to do is write up a centreon agent service which occassionally pulls what centreon says it expects from the remote server and PUSH the config to the agent when the server requests for it. The agent service will then start running those checks periodically as per servers requests.

client(centreon_engine::getconfig) -> centreon::agentManager
client(centreon_engine) <- centreon(agentmanager::sendCheckConfigWithParams( proc_check, memory, blahcheck, blahblahcheck, etc )
client(centreon_engine::sendingPollingResults( proc_check, memory, blahcheck, blahblahcheck, etc)) -> centreon::agentManager
..
client(centreon_engine::sendingPollingResults( proc_check, memory, blahcheck, blahblahcheck, etc)) -> centreon::agentManager

..
client(centreon_engine::sendingPollingResults( proc_check, memory, blahcheck, blahblahcheck, etc)) -> centreon::agentManager
etc

So my only issue is just how could I best to send host specific parameters of these checks as 1 service with 20 hostgroups would usually have different thresholds but since its passive, these are usually defined by the remote server from whatever puppet/ansible would push.
Now to get centreon do it and without separating the same service to every hostgroup I was hoping we could add some lookup list when passive is selected.

So as an exmaple, if I create a check_memory passive service, instead of just status and message boxes shown, it would be great if I could have a hostgroup list with designated threshold values.
I've attached an example *love to have* option where I can set a check_dummy style script multiple subvalues which the remote agent can retrieve based on it's hostgroup.

does this make sense to what I'm trying to achieve. I just have no way from the DB side to determine how to find what hostgroup a querying agent host is from and how to get a lookup value for it.

The screenshot is a dummy check script and does nothing but my php server side agent lookup up which hostgroup the remote side agent is in and selects the check value for it and send it's config back.

![example](https://cloud.githubusercontent.com/assets/13330803/16296349/26374040-396f-11e6-832b-b5dfe7edd6d8.png)

**Comment by gvieira-nr** [comment]
ok, I think it'll be just easier to write the check to be similar to the check_service_cluster and have all hosts or hostgroups values in the 1 line like the cluster check.
eg. check_memory
$default:85:95$,$hg_mail_cluster:75:85$,$hg_mysql_cluster:95:97$

So my centreon agent service will get it's value from centreon which finds which hostgroup it appears in and uses it's value for each passive check, if not found it'll use default.

it would be nice if a special service check would allow per host,hostgroup or service group settings for passive checks, this would eliminate the need for puppet to push configs with thresholds all the time.

**Comment by george-vieira** [comment]
I've gotten stuck again and it seems the only way forward is to customize a menu for this which really isn't manageable.

My centreon-agent system is working, it's quite configurable and it's going down the path of being a puppet style agent which can talk to centreon masters to get the machines set of service checks required to be performed and act like a nagios style local agent so it only needs to notify the master on events.

Here's one JSON format of the most complicated service check I've created from ideas

{
    "service_check": {
        "enabled": false,
        "name": "Centreon Service Check Name",
        "schedule": "*/5 * * * *",
        "command":  "/usr/lib/nagios/plugins/check_server_load",
        "max_attempts": 3,
        "thresholds": {
            "default": {
                "warn": "1,1,1",
                "crit": "2,2,2"
            },
            "00:00-07:00": {
                "warn": "2,3,4",
                "crit": "5,4,3"
            },
            "07:01-19:18": {
                "warn": "8,6,4",
                "crit": "10,8,6"
            }
        },
        "prerun": "/scripts/do_this_before_the_check",
        "postrun": "/scripts/do_this_after_the_check",
        "onOK": "/scripts/do_this_if_ok",
        "onWarn": "/scripts/do_this_if_ok",
        "onError": "/scripts/do_this_if_error",
        "onUnknown": "/scripts/do_this_if_unknown",
    	"metrics": {
    	    "perftype": "nagios|centreon|grafite|influxdb",
    	    "metrictype": "graphite|collectd|etc",
    	    "url": "https://remote.server.com/url",
    	    "postvar": "val=value&state=$state"
    	}
    	"freshtime":	"180",
    	"freshmethod":	"lastcache|cmdrefresh"
    }
}

Most of these are quite explanatory but my current problem is that even with the agent requesting a configuration from the master and with the SQL I have which can identify what services checks needs to run for this host, command, thresholds, etc, I cannot get enough custom settings configured on the master side. eg if agent has 3 max attempts before hard/critical, master only needs 1 to send an alert, but master configuration for agent can't store both settings (1 for master, 3 attempts for agent).

This is pretty much what this whole request is, somehow making service checks have much more settings abilities and have settings set for each host or hostgroup so that I can write a master side module to propagate settings on request from the agents with configurations as above.

simple answer is to just use puppet, but this moves centralised management away and making things combersome at the same time.

**Comment by george-vieira** [comment]
I managed to get most of what I need to work by working around the limited configuration options of a standard command check as per first image attached, I use a large fake set of ARGs allowing my server side script to generate a service configuration (as previous comment above) json file to send to the centreon-agent.

My problem now comes back to my original image above needing to separate settings per host or hostgroup. eg threshold for a php cluster could be at 25 load but a small mail server may have load threshold of just 5.. but using service by hostgroup can't separate these thresholds.

I'm hoping centreon can provide a future proof way to allow a default setting which can be overridden for some hosts/hostgroups.

My only current solution is to duplicate the service for every hostgroup which if there's 200 host groups with a very common check like load_average, etc, this makes it unmanageable.

My only option atm, is to put a ARG set with overrides for each host/hostgroup which can be quite long too and not very visible with a small text box web UI.

Can centreon add any new feature or multi value type boxes for services that could be host/hostgroup based?

![commands](https://cloud.githubusercontent.com/assets/13330803/19228749/d90cd1c2-8f13-11e6-999a-34b919a280aa.png)

![service_settings](https://cloud.githubusercontent.com/assets/13330803/19228752/df8df490-8f13-11e6-884c-5dd3dfac2f46.png)

**Comment by lpinsivy** [comment]
Centreon doesn't want to manage service by hostgroup.
