### ISSUE TITLE
[CLAPI] problème génération configuration

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#4491]
J'ai testé l'application de la configuration d'un poller sur CES et DEBIAN avec clapi

**_1er Problème_**
le user centreon n'est pas autorisé à lire le dossier, ci-joint l'erreur

> [centreon@ces33 ~]$ ls -l /usr/share/centreon//filesGeneration/nagiosCFG/2
ls: impoossible d'ouvrir le répertoire /usr/share/centreon//filesGeneration/nagiosCFG/2: Permission non accordée

et sur centcore

> 2016-06-22 09:56:54 - Result : /usr/share/centreon//filesGeneration/nagiosCFG/2/*: Permission denied

Résolution

**sur Centreon (CES)** usermod -a -G apache centreon
**sur Debian** usermod -a -G www-data centreon 

**_2ème Problème_**
la méthode pollerrestart ne prend pas en compte le nom du poller mais l'id seulement. 
la commande

> centreon -u admin -p password -a POLLERRESTART -v poller1

erreur ci-dessous

> 2016-06-21 22:25:55 - Cannot restart Engine for poller
2016-06-21 22:25:55 - Init Script : 'sudo  restart' On poller  ()

J'ai modifié la ligne 307 de centreon.Config.Poller.class.php

> exec("echo 'RESTART:".$variables."' >> ". $this->centcore_pipe, $stdout, $return_code);

comme ceci

> exec("echo 'RESTART:".$host["id"]."' >> ". $this->centcore_pipe, $stdout, $return_code);

essai ok

> 2016-06-22 10:06:40 - Init Script : 'sudo /etc/init.d/centengine restart' On poller 172.16.209.71 (2)
2016-06-22 10:06:40 - Engine : .centengine restart: done.

**Comment by julienmathis** [comment]
Bonjour, 

Le problème de droit a été corrigé il y a très longtemps. Etrange que tu le rencontres encore...

Pour le deuxième point, déja corrigé : https://github.com/centreon/centreon/commit/b05c62e415fda115b2eb3b4d6248c9bdf19204d4#diff-5a550f2c707eb43e204624a1e59ea31d

Merci

**Comment by kermith72** [comment]
Bonjour Julien,

Pourtant j’utilise cette iso
 ces-standard-3.3-x86_64	Stable	16/12/2015 05:15 PM
et je fais la mise à jour avant l’installation.

**Comment by Tpo76** [comment]
Fonctionne.
Mais beaucoup d'erreurs lors de la génération le groupe apache n'appartenant pas à centreon.

PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 540
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 541

**Comment by julienmathis** [comment]
@querwin : you should fixed this problem on the rpm package. I can't do more.

**Comment by julienmathis** [comment]
@querwin : can you fix the problem on the rpm package ?

**Comment by kduret** [comment]
commit 715252c8f1eadf6092c139a36c9d05e51d33304b
