### ISSUE TITLE
[2.7.4] [Dashboard] Wrong query syntax in eventReportBuilder daily script

### ISSUE THREAD

**Issue by perkooo** [centreon/centreon#4494]
Hi, 

When rebuilding events, I have some errors popping some days (not every) 

Here is the trace : 

2016-06-22 13:34:41 - MySQL error: You have an error in your SQL syntax; check the
manual that corresponds to your MariaDB server version for the right syntax to use
near ' `in_ack` = '0', `last_update`= 0 WHERE `hoststateevent_id` = 1700' at line 1
(caller:
centreon::reporting::CentreonHostStateEvents:/usr/share/perl5/vendor_perl/centreo
/reporting/CentreonHostStateEvents.pm:164)
Query: UPDATE `hoststateevents` SET `end_time` = 1461920400, `ack_time`=
IFNULL(ack_time,NULL), , `in_ack` = '0', `last_update`= 0 WHERE
`hoststateevent_id` = 1700
 DBI::db=HASH(0x2caab68)->disconnect invalidates 1 active statement handle
(either destroy statement handles or call finish on them before disconnecting) at
/usr/share/perl5/vendor_perl/centreon/common/db.pm line 225.
2016-06-22 13:34:41 - MySQL error: You have an error in your SQL syntax; check the
manual that corresponds to your MariaDB server version for the right syntax to use
near ' `in_ack` = '0', `last_update`= 0 WHERE `hoststateevent_id` = 1704' at line 1
(caller:
centreon::reporting::CentreonHostStateEvents:/usr/share/perl5/vendor_perl/centreo
/reporting/CentreonHostStateEvents.pm:164)
Query: UPDATE `hoststateevents` SET `end_time` = 1461920400, `ack_time`=
IFNULL(ack_time,NULL), , `in_ack` = '0', `last_update`= 0 WHERE
`hoststateevent_id` = 1704

Reason for this is because of double comma in query here 'IFNULL(ack_time,NULL), ,' at line 164 of CentreonHostStateEvents.pm.

Could you please commit a fix on this ? 

Thx

cc @Sims24 @julienmathis @Moujimouja

**Comment by julienmathis** [comment]
Thanks ! 

already fixed here : https://github.com/centreon/centreon/commit/ccf2c256c6dd692a84e9f187008dbb5135b898a6#diff-ee24f5b17377d73413fa2c60633c180c

**Comment by perkooo** [comment]
Thanks !
