### ISSUE TITLE
[2.7.4] Changement Massif - suppression des valeurs de macro saisies

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4500]
Bonjour,

Lors d'un changement massif de modèle de service, les valeurs de macro qui avaient été surchargées sont supprimées/effacées. Cela fonctionnait en version 2.6.6.

Si un changement de modèle est effectué unitairement sur chaque service, le problème ne se pose pas.

concrètement avec un exemple:
Modele1 avec les macros suivantes (valeur prédéfinie):
   - NomService
   - Etat (Running)
   - Demarrage (Manual)
Modele2 avec les macros suivantes (valeur prédéfinie):
   - NomService
   - Etat (Running)
   - Demarrage (Auto)

selon le cas de supervision je choisi le modèle 1 ou le modèle 2 et la macro NomService est systématiquement surchargée.

cordialement,

**Comment by querwin** [comment]
Same as this ticket : 
https://github.com/centreon/centreon/issues/4470

**Comment by cmeschin** [comment]
Hi,
the issue #4470 is about host and the commit seems to be only for host.
Can you verify if it's really fix my problem?
thank you.
