### ISSUE TITLE
[WIDGET] MBI - Storage list near saturation

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4501]
Bonjour,

Il semble y avoir un problème d'affichage au niveau du remplissage du "Current usage".
Il indique une valeur (sans unité mais qui s'avère être le % utilisé) mais le remplissage de la barre ne semble correspondre à rien sauf au taux de remplissage mais pour lequel le 100% ne serait pas la barre pleine.
![widget_storage_linear_saturation_graphe](https://cloud.githubusercontent.com/assets/8720203/16332656/717d2078-39f7-11e6-94a3-78b73eb51d5a.png)

![widget_storage_linear_saturation_param](https://cloud.githubusercontent.com/assets/8720203/16332611/1971f66a-39f7-11e6-8ee4-db3dbb9e40c6.png)

centreon-Web 2.7.4
version widget 1.0.0
cordialement,

**Comment by Moujimouja** [comment]
Bonjour ,

Merci pour le retour, le problème a pu être constaté, il apparaît quand la vue utilisée dispose de 2 ou 3 colonne.

Merci à l'avenir de vous rapprocher du support Centreon pour toutes les questions liés à Centreon MBI ( les widgets MBI en font parti )

**Comment by cmeschin** [comment]
Bonjour,
J'ai l'impression que c'est plutôt l'inverse. Le phénomène apparait dans la vue utilisée est sur une ou deux colonnes et pas avec 3 colonnes.
La capture initiale correspond au widget sur 1 colonne.
Les deux ci-dessous respectivement sur 2 et 3 colonnes.
![widget_storage_linear_saturation_graphe_2colonnes](https://cloud.githubusercontent.com/assets/8720203/16450975/7bd8268c-3e00-11e6-84fd-8bc7c4e595f5.png)

![widget_storage_linear_saturation_graphe_3colonnes](https://cloud.githubusercontent.com/assets/8720203/16450985/8f312026-3e00-11e6-8709-32e332056ea9.png)

Mais c'est peut-être ce qui voulait être dis :)
cordialement,

**Comment by Moujimouja** [comment]
Oui je me suis trompé, c'est quand on est en mode 1 ou 2 colonne, pour le 3 c'est OK ( c'est une impression en fait ) .

Et ce problème n'était présent que sur le statut "OK" . C'est corrigé en 3.0.1 , sorti hier.

A+ !
