### ISSUE TITLE
Design MBI on Safari

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4503]
Hello team,
I think, there is an issue with the MBI design on Safari Mac. It's not like usual :-)

![cap 2016-06-27 a 10 13 26](https://cloud.githubusercontent.com/assets/10330979/16372990/03704726-3c50-11e6-88a6-0c90a44cc120.png)

Thanks a lot

**Comment by Moujimouja** [comment]
Hi,

Did you update to MBI 2.3.x or superiori to have Centreon 2.7 compatiblility ? 

If so, did you totally clear the cache of your browser  ?

**Comment by matthieu-robin** [comment]
I have updated all modules and Centreon Web to the latest version.
I have cleaned the cache, and it’s ok now.

Thanks Etienne!

> Le 27 juin 2016 à 13:15, Etienne G <notifications@github.com> a écrit :
> 
> Hi,
> 
> Did you update to MBI 2.3.x or superiori to have Centreon 2.7 compatiblility ?
> 
> If so, did you totally clear the cache of your browser ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/centreon/centreon/issues/4503#issuecomment-228718107>, or mute the thread <https://github.com/notifications/unsubscribe/AJ2jY_aSvLLTxzerBkDt68s9Q-6O1Wphks5qP7DegaJpZM4I-2q7>.
> 

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com
