### ISSUE TITLE
ACL: Don't see Service Categories on MBI

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4505]
Hello,
I don't see Services Categories on MBI if i haven't selected them on ACL Ressources Filters.
If I do this, I don't see all services on monitoring screen.

Can you please have a look? Thanks in advance.

**Comment by Moujimouja** [comment]
Hello,

Please contact Centreon support for Centreon MBI only related questions or try to click on "Update resources ACL" in General Option > Report Parameters.
