### ISSUE TITLE
 Date of new versions

### ISSUE THREAD

**Issue by sujeiitosuspeito** [centreon/centreon#4507]
Good evening,
I wonder if it already has a date for launch of version of Centreon-web-2.8
and also version of Centreon ces-3.4

Thank you and I look forward.

**Comment by julienmathis** [comment]
Hello, 

The version 2.8 of centreon web will be released as a beta version during july. Centreon 3.4 will be released in september. This version will contains Centreon 2.8 in stable state.

BR
