### ISSUE TITLE
howto documentation

### ISSUE THREAD

**Issue by george-vieira** [centreon/centreon#4513]
I'm having a horrible time trying to work out configuration required to setup the example architecture provided on your document site https://documentation.centreon.com/docs/centreon/en/2.5.x/architecture/03e.html

I've cloned the Central Master poller and changed : 
1. locahost to No
2. IP to reachable IP address of the new Slave
3. generated ssh keys for master for centreon user and put authorization_keys on slave host
4. clones the brokers and changed the names to not conflict and set the Requester to the Slave name

I can push host monitoring to it as a test and the engine monitors it, I can also push broker settings and it works.

But what I really would like is to have a hot standy monitoring server so if the master is down, so I can use the slave immediately. The database is a remote datanase which both master and slave has access to.

if not possible, how are both master/slave configured in detail because I can't see how failing over to slave and then back to master retains RRD file data when slave has the missing data the master lost during it's outage.?

I seem to be able to make the slave as a poller itself but the top 3 icons show all green with no latency, engines running etc but when you go to Poller configuration, the slave is marked as NO and not running.. seems contradicting.?

**Comment by gvieira-nr** [comment]
Also, If I can't have the centcore/engine/broker running on the slave, how is the fail over if the msater completely dies?
I have passive results being posted to the master, I have to use either a floating IP or DNS change and point it to the Slave. is this the suggested methods?

What about the configuration of the slave itself and switching to it master? Currently, most of my hosts monitored is on the master poller, I would need to delegate them all to the be polled from the Slave and then restart the services, correct? I guess ideally it would be preferred that the central master/slave don't poll or receive passive checks but the problem still remains if the remote poller dies, 100 or so hosts have to manually be delegated to another poller.
It would be nice to have a failover poller for hosts so if the primary fails, automatically another poller takes over. would this be possible in future?

I'm still trying to wrap my head around how to have this master and failover slave working :(

**Comment by lpinsivy** [comment]
https://documentation.centreon.com/docs/centreon-poller-display/en/latest/
