### ISSUE TITLE
Configuration > SNMP Traps > Generate, Sort the poller list alphabetically.

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon#4515]
Configuration > SNMP Traps > Generate
Can you sort the poller list alphabetically ?

Thanks you very much.

Sincerely

**Comment by julienmathis** [comment]
Already asked by you, already fixed but in Centreon Web 2.8 :)

**Comment by sboulianne** [comment]
hahahaha, thanks sir. :D
