### ISSUE TITLE
BUG: centreon 2.7.4 Duplicating poller does not clone "Object Configuration Directory" property

### ISSUE THREAD

**Issue by gvieira-nr** [centreon/centreon#4516]
It seems the when duplicating a poller and editing the config using right side screen edit button, displays the "Object Configuration Directory" as '/etc/centreon-engine/' but the original polller contained '/usr/local/centreon-engine/etc/' and so it seems some sort of default was used in code.

**Comment by lpinsivy** [comment]
not present in Centreon web 2.8.5, should be corrected
