### ISSUE TITLE
Erreur d'écriture

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4520]
Bonjour,

Si je ne me trompe pas, il y a une erreur d'écriture à la ligne 25 du fichier "hostDetails.ihtml" : 

Service Statuses > Service Status

**Comment by julienmathis** [comment]
Fix by https://github.com/centreon/centreon/commit/155b8c5ca76177b57fabb101adee651daf24239c#diff-1a94fa3fd60b865951134594dd34e48a
