### ISSUE TITLE
Erreur de page

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4521]
Bonjour,

Je pense qu'il y a une erreur à la ligne 28 du fichier serviceSchedule.xsl : 

main.php?p=201 > main.php?p=20202

**Comment by julienmathis** [comment]
Bonjour, 

Quelle version de Centreon ? Cette page n'est plus dispo dans la version 2.7.

Merci

**Comment by jben94** [comment]
Ah je n'ai pas vérifié si elle était encore utilisée. Nous avons commencé par la version 2.6 et maintenant nous sommes en 2.7 
C'est juste une modification que je dois faire à chaque update de centreon web. Nous sommes à la version 2.7.5 la dernière si je ne me trompe pas.

**Comment by julienmathis** [comment]
Oui mais cette page n'existe plus normalement. Pas normal que sur un 2.7.5 elle soit toujours accessible. L'installation comporte a mon avis des problèmes. 

https://github.com/centreon/centreon/blob/2.8.x/www/install/sql/centreon/Update-DB-2.6.6_to_2.7.0-RC1.sql#L732

**Comment by jben94** [comment]
Effectivement l'entrée en base de données n'existe plus mais le lien existe toujours entre les fichiers. Et à la suite de chaque mise à jour, je ré appliquais ce changement mais sans faire attention si la page pouvait être appelée.

www/include/monitoring/status/monitoringService.php > www/include/monitoring/status/Scheduling/serviceSchedule.php

www/include/monitoring/status/Scheduling/serviceSchedule.php > www/include/monitoring/status/Scheduling/serviceScheduleJS.php

www/include/monitoring/status/Scheduling/serviceScheduleJS.php > www/include/monitoring/status/Scheduling/xsl/serviceSchedule.xsl

**Comment by jben94** [comment]
Je pense que cette issue peut-être fermée. Désolé
