### ISSUE TITLE
[Centreon 2.7.5] Centreon Web - The lack of metrics for inverse graphs.

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon#4523]
Hi guys!
Search has not found the same problem.	
Gist: after upgrading to 2.7.5 when the inverted gpaphs of the metrics is not displayed.
![09-07-16 08 18 09](https://cloud.githubusercontent.com/assets/15804154/16706270/56992da2-45ae-11e6-95d7-276a6b348a6e.png)
![09-07-16 08 19 09](https://cloud.githubusercontent.com/assets/15804154/16706271/5e5c2706-45ae-11e6-836d-8a1cc753f357.png)
Can I do something wrong?

"Centreon 2.7.5
Released July 06,2016
...
CHANGELOG
Features and Bug Fixes
Fix: Max and Min was not correct for inverted curves"

Regards

**Comment by julienmathis** [comment]
Hello, 

Did you set the lower limit to 0 in graph template ?

BR

**Comment by maksimatveev** [comment]
@julienmathis Hi, Julien!
It was my mistake - for the service template forgot to specify the graph template. Once exposed, everything appears as it should.
Thank you)
![17 59 59 12-07-2016](https://cloud.githubusercontent.com/assets/15804154/16771804/8b5d0b18-485a-11e6-9a68-321793934ab0.png)

**Comment by julienmathis** [comment]
Great ! :)
