### ISSUE TITLE
No more graph into Centreon UI after migration from Ndo to Centreon Broker

### ISSUE THREAD

**Issue by sebastienmaury** [centreon/centreon#4524]
Hello,

Versions :
- Centreon Broker 2.10.3.
- Centreon 2.6.6
- Nagios 3.5

I've recently moved from NdoTools to Centreon Broker.
I've also switched from Centstorage to Centreon Broker.

Since then, Centreon UI doesn't display any more graph (see screenshots) :

![2016-07-11 16 21 20](https://cloud.githubusercontent.com/assets/19406829/16734141/bca4811e-4784-11e6-980e-aa4153025932.jpg)
![2016-07-11 16 22 30](https://cloud.githubusercontent.com/assets/19406829/16734142/bca5c1be-4784-11e6-8550-9ce0194d20d1.jpg)

When I check into DB, data_bin and index_data are correctly updated :
> select ctime from data_bin order by ctime DESC limit 10;
+------------+
| ctime      |
+------------+
| 1468247306 |
| 1468247306 |
| 1468247306 |
| 1468247306 |
| 1468247306 |
| 1468247306 |
| 1468247306 |
| 1468247306 |
| 1468247305 |
| 1468247305 |
+------------+
> date -d @1468247305
lun. juil. 11 16:28:25 CEST 2016

My RRD files are also correctly updated :
> date;ls -lrt | grep -c "11 juil"
lun. juil. 11 16:27:16 CEST 2016
243

I don't have any error in my log files (broker or centreon).

I've tried a rebuild of one graph, but it didn't change anything.

So the problem doesn't seem to be on the broker but on the web UI ...

Thanks in advance for your help.
Regards,
Sébastien

**Comment by sebastienmaury** [comment]
Some more details on the metric "ActiveDirectory".

Its metric id :
> SELECT metric_id from metrics, index_data where metrics.index_id=index_data.id AND host_name='MTP-ADIOPE2-MILLET' AND service_description='ActiveDirectory';
+-----------+
| metric_id |
+-----------+
|       136 |
|       134 |
|       135 |
|       133 |
+-----------+

Number of values for this metric :
> select count(*) from data_bin where id_metric = '136';
+----------+
| count(*) |
+----------+
|    16818 |
+----------+

> select ctime from data_bin where id_metric = '136' order by ctime DESC limit 10;
+------------+
| ctime      |
+------------+
| 1467902399 |
| 1467901499 |
| 1467900599 |
| 1467899699 |
| 1467898799 |
| 1467897899 |
| 1467896999 |
| 1467896099 |
| 1467895099 |
| 1467894199 |
+------------+

> date -d @1467894199
jeu. juil.  7 14:23:19 CEST 2016

Now the associated rrd :
> ll 136.rrd
-rw-r--r-- 1 spvdv1a1 spvdv1a1 150568 11 juil. 16:25 136.rrd

This timestamp is when i've done the rebuild.

> rrdtool dump 136.rrd > /tmp/136.xml

> tail /tmp/136.xml
			 <row><v>0.0000000000e+00</v></row>
			 <row><v>0.0000000000e+00</v></row>
			 <row><v>0.0000000000e+00</v></row>
			 <row><v>0.0000000000e+00</v></row>
			 <row><v>0.0000000000e+00</v></row>
			 <row><v>0.0000000000e+00</v></row>
			 <row><v>0.0000000000e+00</v></row>
		</database>
	</rra>
</rrd>

> date -d @1467892800
jeu. juil.  7 14:00:00 CEST 2016

As you can see, it has not been updated since 07 july (it's day i've switched to Cent Broker).

So maybe the problem is from Cent Broker who doesn't update properly performance data ...

Thanks in advance for your help.
Regards,
Sébastien

PS : This issue can be moved to the broker repository if needed.

**Comment by sebastienmaury** [comment]
What I don't understand it's that I have some correctly updated metrics.
For example : 

> SELECT service_description,host_name from metrics, index_data where metrics.index_id=index_data.id AND metric_id='2412';
+---------------------+---------------------+
| service_description | host_name           |
+---------------------+---------------------+
| Svchost             | VJF-TEMOPE1-BASELLE |
+---------------------+---------------------+

> select ctime from data_bin where id_metric = '2412' order by ctime DESC limit 10;
+------------+
| ctime      |
+------------+
| 1468249240 |
| 1468249240 |
| 1468248340 |
| 1468248340 |
| 1468247440 |
| 1468247440 |
| 1468246540 |
| 1468246540 |
| 1468245640 |
| 1468245640 |
+------------+

> date -d @1468249240
lun. juil. 11 17:00:40 CEST 2016

![2016-07-11 17 06 09](https://cloud.githubusercontent.com/assets/19406829/16735552/ccc49cf0-4789-11e6-8faa-7505e18b2c4a.jpg)

**Comment by sebastienmaury** [comment]
Hi,

My problem is solved.

Actually, I've done an import of my config files long ago (I think i wasn't even in Centreon 2.4.x) and during that import a macro has been added to all the hosts and services (HOST_ID and SERVICE_ID).
I've deleted those macros and everything works fine now :)

This issue can be closed.

Regards,
Sébastien

**Comment by julienmathis** [comment]
Thanks for your feedback !
