### ISSUE TITLE
Custom Views - User Not Admin - ACL

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#453]
---

Author Name: **PRADET Jeremie** (PRADET Jeremie)
Original Redmine Issue: 4410, https://forge.centreon.com/issues/4410
Original Date: 2013-04-22

---

Hello

When a user want to create custom with Graph Monitoring, he can't browser service list after select host.
But whit administrator account we can.

**Comment by julienmathis** [comment]
now ok
