### ISSUE TITLE
Service group to be clickable on Map4

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#4546]
Hi,

Could you please add enhancement so that service groups in MAP4 are also clickable in Web client.
(When clicking on it, it will open new tab with all the services that are in that service group. By default shows problematic services first). Thanks!

**Comment by centreonmap** [comment]
Hi Kadri,

as you can see the Centreon GitHub has been set private. For any request concerning this product please use the support platform.

Your demand has already been implemented in web client version 4.0.6. After update please use ctlr + f5 to clear your browser cache.

Regards,
Pierre GAUTIER
