### ISSUE TITLE
Generate config doesn't work 

### ISSUE THREAD

**Issue by non7top** [centreon/centreon#4547]
centreon-web-2.8.0-1468397825.7acffcb.el7.centos.noarch

When I try to generate config files here is what I get:

> [Sun Jul 24 18:02:50.122083 2016] [:error] [pid 437] [client 109.172.69.126:61214] PHP Fatal error:  Class 'CentreonDB' not found in /usr/share/centreon/www/include/configuration/configGenerate/xml/restartPollers.php on line 42, referer: http://mon2:18112/centreon/main.php?p=60902&poller=1

If I add include in restartPollers.php I then get another error:

>[Sun Jul 24 18:05:38.557380 2016] [:error] [pid 377] [client 109.172.69.126:61371] PHP Fatal error:  Call to a member function getPollerAclConf() on a non-object in /usr/share/centreon/www/include/configuration/configGenerate/xml/restartPollers.php on line 133, referer: 

Afterall no config files are generated.

**Comment by julienmathis** [comment]
This rpm is not stable, You shouldn't use it. Already fixed now in the branch 2.8.

Regards
