### ISSUE TITLE
Data_bin

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4549]
Bonjour,

Étant confronté à une grande volumétrie dans cette table (data_bin),
Est-ce qu'il ne serait pas plus facile de la gérer par partition (Et par jour) ?

Un "Delete" (Pour la rétention) sur une table comportant des milliers de lignes, provoque des ralentissements et parfois des blocage côté serveur de base de données.

**Comment by Sims24** [comment]
Bonjour, 

C'est en effet quelque chose que nous réalisons régulièrement, cela sera par défaut dans la version 2.8. 

Merci pour votre feedback,
