### ISSUE TITLE
[2.7] Configuration field too shorts

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#4552]
Hello,

In Centreon 2.7, at least in host or service configuration page, nearly all the fields are too shorts.

and that in all the tabs of the service/host config.

please look the example attached.

![capture](https://cloud.githubusercontent.com/assets/2464712/17137732/04d80bb8-533d-11e6-87c6-8eb4a2a3a45e.PNG)

**Comment by cmeschin** [comment]
Hi, this is the same as issue #4187 normally fixed on 2.7.3 but always present on 2.7.4
cordially

**Comment by julienmathis** [comment]
Fixed in Centreon 2.8. Style has been improved
