### ISSUE TITLE
Problème format date selon menu

### ISSUE THREAD

**Issue by mvisini** [centreon/centreon#4554]
Bonjour, 

je rencontre un problème de format d'affichage de la date.
La timezone est bien définie en Europe/Paris de partout, cependant voici ce que j'ai : 

- Monitoring  >  Status Details  >  Hosts => Le format est AAAA/MM/JJ dans Status Detail et dans Host informations.

- Monitoring  >  Status Details  >  Services => Le format des last_check est JJ/MM/AAAA, en passant la souris sur un service le format est également JJ/MM/AAAA dans la fenêtre qui apparaît.

- Monitoring  >  Downtimes => Dans les colonnes Start Time et End Time le format est sous la forme MM/JJ/AAAA

J'ai vérifié un peu partout dans les différents fichiers de conf. est le date format est bien défini comme "euro".

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.4

**Centreon Engine version**: 1.5.0

**Centreon Broker version**: 2.11.4

**OS**: CentOS 6.7

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare

**Comment by querwin** [comment]
Hello,

Same as this ticket : https://github.com/centreon/centreon/issues/4396
