### ISSUE TITLE
[2.7.6] Contact groups with accented characters, crash config generation

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#4555]
Hello,

If i add a contact group with an accented character and map this group to an host.

I will be unable to generate the centreon-engine configuration =

Error The name of contact group 'Pouet_Heures_ouvr&eacute' contains one or more illegal characters.
Error Cannot resolve contact group Pouet_Heures_ouvr&eacute'

In the database the data is written like this : Pouet_Heures_ouvr&eacute;e

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.5

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. in Configuration  >  Users  >  Contact Groups add user with an accented char
2. Map this group to an host for notifications
3. Generate the config for the poller on which it is attached

**Describe the results you received:**
Error The name of contact group 'Pouet_Heures_ouvr&eacute' contains one or more illegal characters.
Error Cannot resolve contact group Pouet_Heures_ouvr&eacute'

**Describe the results you expected:**
Configuration OK

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by garnier-quentin** [comment]
You can solve it if you go to the contact group page and save it. It should remove the htmlentities in database. And after you can generate the config files. 
If you have many contact groups with same problem, you can go to the database and do a replace mysql command.

**Comment by BenoitPoulet** [comment]
I just did the test :
1 - edit the group, remove all accent, save it
2 - re-edit the group, add : "é" , save it
3 - look into the database and found : 'Pout_Heures_ouvr&eacute;es'

**Comment by julienmathis** [comment]
Ok I just fix that for Centreon 2.8.x.
