### ISSUE TITLE
[2.7.6] Status graph doesn't have the same look as performance graph

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#4556]
Hello,

When we display the status graph, the look it completely different than the performance graph.

![capture status](https://cloud.githubusercontent.com/assets/2464712/17172257/7840b7dc-53f4-11e6-80a6-7ce141fb8ca9.PNG)

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.7.6

**Steps to reproduce the issue:**
1. Display a performance graph
2. Click the check box «Display Status»

**Describe the results you received:**
an ugly graph

**Describe the results you expected:**
a graph who have the same look as performance graph

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by querwin** [comment]
Hello,

Graph will change in the future version 2.8.0 to look more "sexy" ;)
