### ISSUE TITLE
problem with status information services

### ISSUE THREAD

**Issue by gajete** [centreon/centreon#4558]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**OS**: CES 2.6.6

**Problem:**

When i execute the script, i see all information status in SSH

`centreon@promssj01:/home/centreon $ /centreon/kit_basic/check_disk -w 5 -c 2
OK - Free MB:  / 511M  [79%]; /usr 3983M  [37%]; /var 709M  [38%]; /tmp 493M  [77%]; /home 4916M  [67%]; /opt 509M  [46%]; /var/pd 29341M  [99%]; /var/psf 506M  [98%]; /var/psf/segments 956M  [93%]; /orabin 17198M  [28%]; /usr/mqm 4062M  [80%]; /var/mqm 15179M  [99%]; /oraomsp01 71372M  [17%]; /orabackup 255407M  [99%]; /oraarcp01 583917M  [27%]; /var/afpds 30182M  [73%]; /orabrkp01 228609M  [18%]; /oraaxisest01 23363M  [45%]; /idxaxisep01 36601M  [89%]; /oraaxisep01 118704M  [77%]; /cores 5098M  [99%]; /oraomsglp01 36105M  [50%]; /orahisarcp01 10816M ** [2%]; /orasappecc01 389903M  [88%]; /archisarcp01 9921M  [97%]; /arcbrkp01 95453M  [93%]; /arcomsglp01 8833M  [86%]; /arcaxisep01 19361M  [94%]; /arcaxisest01 18625M  [91%]; /arcomsp01 347967M  [97%]; /arcarcp01 141723M  [92%]; /arcsappecc01 101855M  [99%]; /var/afpds_antics 204744M  [99%]; /pdfomspr/ES 72095M  [70%]; /home/netappcalife01Export 462646M  [75%]; /dumps 51134M  [99%]; /backup_arcp01 838449M  [79%]; /netapp 267459M  [91%]; /oraidmp01 6652M  [65%]; /arcidmp01 10126M  [99%]; /pdfomspr/CA 5830624M  [55%]; /centreon 267459M  [91%]; |  /=511MB;32;12;0;640 /usr=3983MB;531;212;0;10624 /var=709MB;92;37;0;1856 /tmp=493MB;32;12;0;640 /home=4916MB;361;144;0;7232 /opt=509MB;54;21;0;1088 /var/pd=29341MB;1472;588;0;29440 /var/psf=506MB;25;10;0;512 /var/psf/segments=956MB;51;20;0;1024 /orabin=17198MB;3067;1226;0;61344 /usr/mqm=4062MB;251;100;0;5036 /var/mqm=15179MB;761;304;0;15232 /oraomsp01=71372MB;20475;8190;0;409504 /orabackup=255407MB;12793;5117;0;255872 /oraarcp01=583917MB;104448;41779;0;2088960 /var/afpds=30182MB;2041;816;0;40832 /orabrkp01=228609MB;61337;24535;0;1226752 /oraaxisest01=23363MB;2555;1022;0;51104 /idxaxisep01=36601MB;2043;817;0;40864 /oraaxisep01=118704MB;7624;3049;0;152480 /cores=5098MB;256;102;0;5120 /oraomsglp01=36105MB;3571;1428;0;71424 /orahisarcp01=10816MB;4392;4392;0;439296 /orasappecc01=389903MB;22003;8801;0;440064 /archisarcp01=9921MB;508;203;0;10168 /arcbrkp01=95453MB;5113;2045;0;102272 /arcomsglp01=8833MB;508;203;0;10168 /arcaxisep01=19361MB;1020;408;0;20400 /arcaxisest01=18625MB;1020;408;0;20400 /arcomsp01=347967MB;17907;7162;0;358144 /arcarcp01=141723MB;7673;3069;0;153472 /arcsappecc01=101855MB;5113;2045;0;102272 /var/afpds_antics=204744MB;10240;4096;0;204800 /pdfomspr/ES=72095MB;5110;2044;0;102208 /home/netappcalife01Export=462646MB;30720;12288;0;614400 /dumps=51134MB;2560;1024;0;51200 /backup_arcp01=838449MB;52428;20971;0;1048576 /netapp=267459MB;14592;5836;0;291840 /oraidmp01=6652MB;508;203;0;10168 /arcidmp01=10126MB;508;203;0;10168 /pdfomspr/CA=5830624MB;524288;209715;0;10485760 /centreon=267459MB;14592;5836;0;291840
`

when i execute the same script on centreon web, in the page: **monitoring - services** the information status is **not completed**. I see only this:

`OK - Free MB: / 511M [79%]: /usr 3983M [37%]: /var 716M [38%]: /tmp 493M [77%]: /home 4914M [67%]: /opt 509M [46%]: /var/pd 29341M [99%]: /var/psf 506M [98%]: /var/psf/segments 956M [93%]: /orabin 17357M [28%]: /usr/mqm 4062M [80%]: /var/mqm 15179M [99%]: /oraomsp01 71372M [17%]: /orabackup 255407M [99%]: /oraarcp01 583917M [27%]: /var/afpds 30182M [73%]: /orabrkp01 228609M [18%]: /oraaxisest01 23363M [45%]: /idxaxisep01 36601M [89%]: /oraaxisep01 118704M [77%]: /cores 5098M [99%]: /oraomsglp01 36105M [50%]: /orahisarcp01 10816M ** [2%]: /orasappecc01 389903M [88%]: /archisarcp01 9921M [97%]: /arcbrkp01 95099M [92%]: /arcomsglp01 9453M [92%]: /arcaxisep01 19795M [97%]: /arcaxisest01 19474M [95%]: /arcomsp01 351593M [98%]: /arcarcp01 141090M [91%]: /arcsappecc01 101855M [99%]: /var/afpds_antics 204744M [99%]: /pdfomspr/ES 72094M [70%]: /home/netappcalife01Export 462646M [75%]: /dumps 51134M [99%]: /backup_arcp01 838449M [79%]: /netapp 267458M [91%]: /oraidmp01 6652M [65%`

can you help me please?

thanks
Alex

**Comment by garnier-quentin** [comment]
Do you use nrpe protocol ?

**Comment by gajete** [comment]
Yes, I use nrpe

**Comment by garnier-quentin** [comment]
It's the limit of the protocol  (1024 characters)
https://support.nagios.com/kb/article.php?id=518

**Comment by gajete** [comment]
thanks !!!
