### ISSUE TITLE
grafana dashboads in Centreon

### ISSUE THREAD

**Issue by sujeiitosuspeito** [centreon/centreon#4559]
Good evening everyone,
Anyone know if it is possible to integrate Centreon, with dashboards grafana viewer?
Thank you.

BR

**Comment by julienmathis** [comment]
Hello, 

With Centreon 3.4 (Web 2.8) you will be able to send data to Graphite. So you will be able to use grafana. But we don't plan to display grafana dashboard into Centreon.

Best regards
