### ISSUE TITLE
Possibility to disable check commands

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#4560]
Hi,

Please add enhancement that under Configuration -> commands -> checks  - can be disabled.

**Comment by querwin** [comment]
Hi,

Commands which are not used are not exported. So why do you want to desactivate it ?

**Comment by kadrika** [comment]
When configuring services the list from where to choose the correct command is huge. For example there are commands from old times, but I do not want to delete them and sometimes use them to test some services. And for the team it would also be easier to use the commands, because if the unnecessary commands are disabled, they do not choose incorrect ones by accident.
