### ISSUE TITLE
Tabulation dans instCentWeb.conf

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4561]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Voici un problème repéré à la suite de la mise à jour de Centreon Web 2.7.5 > 2.7.6.

Le nouveau fichier "instCentWeb.conf" généré contient une tabulation à la ligne "CENTREON_VARLIB", ce qui provoque des problèmes d'installation par la suite, par exemple avec centreon-bi.
Le problème n'est pas nouveau mais je n'avais pas fait encore de retour dessus.

**Comment by julienmathis** [comment]
N'est ce pas du à la saisie d'une tabulation dans un path pendant l'installation shell (tgz) ? ou alors utilises tu une version RPM ?

**Comment by jben94** [comment]
Non à chaque mise à jour, je suis obligé de repasser sur cette ligne. Mais juste celle-ci !

**Comment by jben94** [comment]
je met à jour comme ceci ./install -u [path to instCentWeb.conf]

**Comment by jben94** [comment]
Fix: #4816
