### ISSUE TITLE
Problème variable $res - centAcl.php

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4563]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Voici un problème repéré à la suite de la mise à jour de Centreon Web 2.7.5 > 2.7.6.

Des alertes PHP remontent que parfois la variable "$res" n'est pas un objet à la ligne 134, dans le fichier "centAcl.php".

De plus, voici deux modifications SQL effectuées : 

`+        $DBRESULT = $pearDB->query("SELECT host_id, host_name, acl_res_id FROM`host`,`acl_resources_host_relations`WHERE acl_resources_host_relations.host_host_id = host.host_id AND host.host_register = '1' AND host.host_activate = '1'");`
`-        $DBRESULT = $pearDB->query("SELECT host_id, host_name, acl_res_id FROM`host`,`acl_resources_host_relations`WHERE acl_resources_host_relations.host_host_id = host.host_id AND host.host_register = '1'");`

`+        $DBRESULT = $pearDB->query("SELECT host_id, host_name, acl_res_id FROM`host`,`acl_resources_hostex_relations`WHERE acl_resources_hostex_relations.host_host_id = host.host_id AND host.host_register = '1' AND host.host_activate = '1'");`
`-        $DBRESULT = $pearDB->query("SELECT host_id, host_name, acl_res_id FROM`host`,`acl_resources_hostex_relations`WHERE acl_resources_hostex_relations.host_host_id = host.host_id AND host.host_register = '1'");`

Le problème n'est pas nouveau mais je n'avais pas fait encore de retour dessus.

**Comment by julienmathis** [comment]
Quand tu lances la query suivante : SELECT `key`, `value` FROM `options` WHERE `key` IN ('ldap_auth_enable', 'ldap_last_acl_update')

quelle est le retour ? 

Pour les deux autres, je ne suis pas d'accord.  Les utilisateurs veulent voir dans la configuration les hosts désactivés pour pouvoir les activer par exemple à postériori.

**Comment by jben94** [comment]
Ok pour les deux requêtes SQL. 

La réponse de la query : 
'ldap_auth_enable', '1'
'ldap_last_acl_update', '1469806201'

**Comment by jben94** [comment]
j'ai modifié le fichier en rajoutant ceci : 

	if (PEAR::isError($res)) {
		print "Error to check is process running.";
		exit(1);
	}

**Comment by jben94** [comment]
J'ai fait ceci car j'avais eu des alertes mais il est vrai que normalement ça ne devrait pas arriver.

**Comment by jben94** [comment]
Je vais essayer de faire plus debug la semaine prochaine pour vous donner plus d'info si vous le souhaitez.

**Comment by jben94** [comment]
Je ferme ce ticket car il est beaucoup trop vieux et je ne suis plus à cette version.
