### ISSUE TITLE
Problème variable - centreonServicetemplates.class.php

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4564]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Voici un problème repéré à la suite de la mise à jour de Centreon Web 2.7.5 > 2.7.6.

Je pense qu'il y a un souci à la ligne 104 du fichier "centreonServicetemplates.class.php", $selectedServices est pris dans la condition.

Le problème n'est pas nouveau mais je n'avais pas fait encore de retour dessus.

**Comment by kduret** [comment]
Hi,

Do you have somme problem in Centreon due to this line ?
Do you have errors in your apache logs ?

**Comment by jben94** [comment]
Hi 

No, no mistake!

But if you entered the "if" you also can not enter the "else"!
As the variable in the "if" is just used in the "else", the part of the "if" can be removed.

```
            $selectedServices = '';
            $explodedValues = implode(',', $values);
            if (empty($explodedValues)) {
                $explodedValues = "''";
            } else {
                $selectedServices .= "AND s.service_id IN ($explodedValues) ";
            }
```

**Comment by kduret** [comment]
yeah correct :) 
Thank you for contribution
