### ISSUE TITLE
Problème variable $res - makeXMLForAck.php

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4565]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Voici un problème repéré à la suite de la mise à jour de Centreon Web 2.7.5 > 2.7.6.

Des alertes PHP remontent une erreur de variable "$res" à la ligne 109, dans le fichier "makeXMLForAck.php".

Le problème n'est pas nouveau mais je n'avais pas fait encore de retour dessus.

**Comment by julienmathis** [comment]
Corrigé. Mais étrange d'avoir ce genre d'erreur. Quels sont les cas pour lesquels ca arrive ?

**Comment by jben94** [comment]
En faite, cela fait un moment que j'avais repéré ce problème dans les logs erreurs de PHP. 
Mais je n'avais pas fait de retour, désolé. 
=>Ce qui implique que je ne me rappel plus dans quel cas cela arrive. Désolé

**Comment by jben94** [comment]
Je vais essayer de faire plus debug la semaine prochaine pour vous donner plus d'info si vous le souhaitez.
