### ISSUE TITLE
CLAPI - Fonction addRelations

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4566]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Est-ce que l'appel à la fonction ligne 248 ($this->addRelations($objectId, $instanceIds)) du fichier "centreonResourceCfg.class.php" est correct, car je ne vois pas cette fonction dans le fichier et ni dans la class extends "CentreonObject" ?

**Comment by jben94** [comment]
Hi @lpinsivy,

Are you sure that the problem is solved?
I see the call to function but I do not see the function "addRelations"

Regards.

**Comment by jben94** [comment]
Here is the function I put : 

```
    protected function addRelations($resourceId, $instances) {
        foreach ($instances as $instanceId) {
            $this->relObj->insert($instanceId, $resourceId);
        }
    }
```

**Comment by jben94** [comment]
Hi @lpinsivy , 
Do I have to open a new issue ?

**Comment by lpinsivy** [comment]
In fact I can't find the call to method "addPoller" in Centreon.

Is not only the call to method $this->addRelations is not correct but the function addPoller is never used and not necessary because another method "add" existe in www/class/centreon-clapi/centreonResourceCfg.class.php file

**Comment by jben94** [comment]
Hi @lpinsivy,

Ok thanks for the clarification
