### ISSUE TITLE
Update / upgrade broke /etc/centreon/conf.pm  (centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)

### ISSUE THREAD

**Issue by TheRealEgor** [centreon/centreon#4567]
**Centreon Web version**: 
centreon-web-2.7.6-4.el6.noarch

**Centreon Engine version**: 
centreon-engine-1.5.1-3.el6.x86_64

**Centreon Broker version**: 
centreon-broker-2.11.5-2.el6.x86_64
centreon-broker-core-2.11.5-2.el6.x86_64
centreon-broker-cbd-2.11.5-2.el6.x86_64
centreon-broker-cbmod-2.11.5-2.el6.x86_64
centreon-broker-storage-2.11.5-2.el6.x86_64
**OS**: 
CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

I recently updated Centreon via YUM which resulted in Centreon Core not able to connect to the database.  The behavior wasn't immediately evident until host/service enable/disable notifications and scheduling downtime did not work.  

The error has been seen before, but is found in `/var/log/centreon/centcore.log`

```MySQL error : cannot connect to database : Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)```

the fix was found by editing `/etc/centreon/conf.pm`.  

I found that the following vars did not populate on upgrade:
centreon_db
centstorage_db
db_host
db_user

Everything else populated including the password, however, the password was single quoted.  After filling in the variables, I may have had to double quote the db_password as it has a bracket in it.

You can probably just close the issue and keep it around for reference on others with similar problem.

**Comment by querwin** [comment]
Hello,

I can not reproduce.
How do you do the upgrade ?

When upgrading Centreon, we did not modify this file.

Regards,

**Comment by TheRealEgor** [comment]
I'm marking closed - not 100% sure how it broke.  It's useful for anyone who is having trouble with things that require CentreonCore to connect to the DB.  I didn't have any indication in the WebUI that there was a problem with CentCore but when scheduling downtime or any service/host actions failed it led me to track down the problem in logs.  It's not a hard bit of spelunking, but it may help someone googling in the future.
