### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4568]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Pour information : 

[02-Aug-2016 09:57:09] PHP Notice:  Undefined variable: session_id in /apps/sup/centreon/local/www/class/centreonSession.class.php on line 93
[02-Aug-2016 10:58:27] PHP Notice:  A session had already been started - ignoring session_start() in /apps/sup/centreon/local/www/include/configuration/configGenerate/xml/generateFiles.php on line 75
[02-Aug-2016 10:58:30] PHP Notice:  A session had already been started - ignoring session_start() in /apps/sup/centreon/local/www/include/configuration/configGenerate/xml/moveFiles.php on line 109

**Comment by mmphsb** [comment]
I confirm this issue. You can get rid of this communicates by adding if(!isset($_SESSION)), but moveFiles.php is not working. Configs are being generated, but not pushed to distributed pollers. I am positive it is not a permissions/SSH issue, as PHP code from moveFiles.php simply does not even try to execute this process. Running /usr/bin/centreon manually however works fine. This was introduced in one of latest updates (last two months). Before the update it worked well. When freshly installed from CES image, works fine too.

Not sure if it is related, but same update caused reporting data to stop being registered and poller statistics graphs does not generate anymore (graphs for particular services are fine too).

**Comment by popindavibe** [comment]
I also confirm, but only after update on a fresh install.
I got 2 Central, both plugged to CES repositories, and my "old" one is fine even after recent update to 2.7.6
However the most recent one has that same issue 

`[Wed Sep 14 11:54:39 2016] [error] [client X.X.X.X] PHP Notice:  A session had already been started - ignoring session_start() in /usr/share/centreon/www/include/configuration/configGenerate/xml/generateFiles.php on line 75, referer: http://X.X.X.X/centreon/main.php?p=60902&poller=1
[Wed Sep 14 11:54:39 2016] [error] [client X.X.X.X PHP Notice:  A session had already been started - ignoring session_start() in /usr/share/centreon/www/include/configuration/configGenerate/xml/moveFiles.php on line 109, referer: http://X.XX.X/centreon/main.php?p=60902&poller=1
sudo: no tty present and no askpass program specified
`
The sudo message is also quite strange as I can restart the poller from terminal for both **apache** and **centreon-engine** users.

**Comment by mmphsb** [comment]
Hi, any of you guys had luck with this issue? I would like to update my 2.7.0 instance as it has a lot of bugs, but the update cripples it completely.

**Comment by popindavibe** [comment]
no updates here. I didn't get time to investigate further on the new CES. 
Still, very strange issue, and in my case update on an "old" CES which has been regularly updated since 2.6.X the update did work well, as opposed to the recent one which was installed initially under 2.7.5 and broke after update. 
Unfortunately I won't have further time to spend on it, as I'm not in monitoring anymore and don't have anymore access to the machines.

**Comment by ludovic-lage** [comment]
Hi jben94,
I had the same problem but I think I have found the problem : 

Simply rename the variable "session_id" to "sessionId" and everythings is OK.

Sorry for my English, I'm French :)

**Comment by jben94** [comment]
@ludovic-lage,

On va le faire en français alors ;)
Merci pour ton aide, mais de mon côté le problème a été réglé. 
C'était surtout pour les prévenir.

D’ailleurs je pense que je vais fermer cet Issue.
Bonne journée.

**Comment by phiphi917** [comment]
what was the solution ?
Into my logs, I don't have the session id error.

[Mon May 08 03:04:20 2017] [error] [client 192.168.10.1] PHP Notice:  A session had already been started - ignoring session_start() in /usr/share/centreon/www/include/configuration/configGenerate/xml/generateFiles.php on line 75, referer: http://10.10.10.90/centreon/main.php?p=60902&poller=
[Mon May 08 03:04:20 2017] [error] [client 192.168.10.1] PHP Notice:  A session had already been started - ignoring session_start() in /usr/share/centreon/www/include/configuration/configGenerate/xml/moveFiles.php on line 109, referer: http://10.10.10.90/centreon/main.php?p=60902&poller=
