### ISSUE TITLE
Ajouter une options dans la liste des services et des hôtes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#457]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 4342, https://forge.centreon.com/issues/4342
Original Date: 2013-03-26

---

Ca serait vraiment pratique d'avoir une option "Host : Delete Downtimes" et "Services : Delete Downtime" depuis la vue des hôtes et des services (dans le menu : Plus d'actions...)

**Comment by julienmathis** [comment]
To hard to do that in a short time
