### ISSUE TITLE
Column "conf changed" is wrong when I remove a host

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4570]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6

**Steps to reproduce the issue:**
1. Add a host XXX on Poller A and export configuration
2. Move the host XXX from Poller A to Poller B

**Describe the results you received:**
In the page "Configuration --> Pollers", the column "Conf. changed" is set to "Yes" only for Poller B

**Describe the results you expected:**
In the page "Configuration --> Pollers", the column "Conf. changed" must be set to "Yes" for pollers A and B

**Additional information you think important (e.g. issue happens only occasionally):**
It's important to correct this bug because you can have duplicated services in monitoring if you don't export configuration on all pollers.

**Comment by lpinsivy** [comment]
PR #5549 corrige cela

**Comment by thiuyendang** [comment]
Please refer to PR 5549.
