### ISSUE TITLE
Disabled notifications show up in "View contact notifications"

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#4571]
Centreon Web version: 2.7.5-7
Centreon Engine version: 1.5.1-3
Centreon Broker version: 2.11.5-2
OS: CentOS 6.8 (CES 3.3 iso)
1. set notification groups on a service check
2. set "Enable Notification" to No on a service check
3. click "View contact notifications" under Users
4. select a user in a contact group that is set for above service check

The service check will show up, even though it is disabled.

**Comment by lpinsivy** [comment]
Hi

Thank you for your feebeck.

Yes Centreon display all services without check of the notification status

**Comment by kduret** [comment]
There are lot of problems in "view contact notifications".
Notifications inheritance does not really work...

**Comment by lpinsivy** [comment]
Corrected #4981
