### ISSUE TITLE
Prediction des dépendances d'hôtes et de services

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4572]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.5

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: .2.11.6

**OS**: CentOS

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Dupliquer un poller dans Configuration ==> Collecteurs
2. Dans Configuration ==> Collecteurs ==> Configuration du moteur de collecte ==> fichier de configuration généré ==> Onglet "Options de vérifications"
3. Les options Prédiction des dépendances d'hôtes et Prédiction des dépendances de services sont désactivés alors qu'elles devraient être activés pour permettre une meilleure gestion des dépendances par le moteur

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lolokai** [comment]
De même la détection du flapping est désactivé par défaut.

**Comment by julienmathis** [comment]
b1de999 is a bad commit.

**Comment by lpinsivy** [comment]
@julienmathis can you commit on master branch too ?

**Comment by lpinsivy** [comment]
@Dacchi can you merge on 2.8.X and master ?

**Comment by cgagnaire** [comment]
Still not totally perfect.
And now, in 2.8.9, when I duplicate a broker configuration, it duplicates an engine configuration. This is mental !
And there is also always so much option we don't use...
