### ISSUE TITLE
Erreur de traduction Configuration ==> Collecteurs ==> Configuration du moteur de collecte ==> Onglet Administrateur

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4574]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.5

**Additional information you think important (e.g. issue happens only occasionally):**

Dans l'onglet Administrateur de Configuration ==> Collecteurs ==> Configuration du moteur de collecte il y a une erreur de traduction (deux titres n'apparaissent pas : cf. capture ci-jointe)
<img width="1097" alt="capture d ecran 2016-08-04 a 17 27 34" src="https://cloud.githubusercontent.com/assets/2960490/17403465/e740366a-5a68-11e6-80ac-5c8077a7243d.png">

**Comment by julienmathis** [comment]
linked to #4782
