### ISSUE TITLE
Feature request: highlight alerts for last half hour in "unhandled problems" view

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#4576]
If you have many hundreds of hosts with thousands of services there is a large amount of alerts in the "unhandled problems" view at any one time, causing information overload.

It would be of great help if recent alerts "popped out", which would probably be best accomplished by a different background colour, based on the Duration column.

E.g. every alert older than half an hour could be the same default shade of red (which I changed locally to a lighter pink, the default was too unnerving with many alerts :)) and every newer alert could either be a different single colour or a sliding scale of say 5 minutes per colour between the default red and the "newest" red.

This would also enhance viewing groups of hosts/services while sorted on hostname (one logical unit of hosts/services with similar names going down at the same time would change the colour of a contiguous block).

**Comment by lpinsivy** [comment]
Hi

You can sort alert by duraction ASC to display most recent alerts. 

It's not enought ?

Regards,

**Comment by btassite** [comment]
It isn't when you have thousands of services and your monitor is full most of the time.

**Comment by btassite** [comment]
Oops, didn't mean to close it, just comment :)

**Comment by btassite** [comment]
The issue carries a "more-info-needed" tag, what other information do you need?

**Comment by lpinsivy** [comment]
I didn't understand the goal of this request.

If you have thousands of services in non-ok status, how highlight can change something?

**Comment by btassite** [comment]
Rolling highlight based on age. I.e. it's not a sea of red but whatever happened 5 minutes ago is bright red, 15 minutes ago light red and half an hour ago a pastel shade of pink. This way you can see whether something major is happening from across a busy NOC room instead of having to plant your nose on the screen all the time to read and parse the duration column, even if it's sorted on that :)

(and if it isn't sorted on it, recent things would "pop out", which would be useful to quickly determine if something is happening in a functional group, geographically etc.)

**Comment by lpinsivy** [comment]
May be create widget than can filter on duration?

**Comment by btassite** [comment]
I'd like that, thank you :)
