### ISSUE TITLE
How to get parent host name for a command 

### ISSUE THREAD

**Issue by PapaSchtrouuumpf** [centreon/centreon#4577]
Hello,

I have windows VM running in an ESX. I want to monitor their CPU usage. I use the following command in the terminal : 
./check_vmware_api -H ESX_NAME-u user-p password-N VM_NAME -l cpu -s usage -w 80 -c 90

It works well. but now I want to create this command in Centreon interface. To run this command I need the ESX's name in which the VM is running. Then, I chose give the ESX's name in the field "Parent hosts" of the VM.

How can I get this field "Parent host" in the command ? I want something like that : 

$USER1$/check_vmware_api -H **$PARENT_HOST$** -u $USER10$ -p $PASSWORD10$ -N $HOSTNAME$ -l cpu -s usage -w $ARG2$ -c $ARG3$

Thanks for your answers :)

**Comment by lpinsivy** [comment]
Hi

On your host definition you have to create a custom macro like "ESXNAME".

In your command definition you have to use $_HOSTESXNAME$.

Regards,

**Comment by PapaSchtrouuumpf** [comment]
Hi,
Thanks a lot for your answer. Simple and efficient !
Regards,
