### ISSUE TITLE
[2.7.6] - Centreon Database not fully populated

### ISSUE THREAD

**Issue by engee974** [centreon/centreon#4581]
---
## BUG REPORT INFORMATION

**Centreon Web version**:  2.7.6

**Centreon Engine version**: 2.0.0

**Centreon Broker version**: 3.0.0

**OS**: Debian 8 (Jessie)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MySQL 5.7.14 from mysql-repo (mysql-apt-config package)

**Steps to reproduce the issue:**
1. Install Centreon Engine, Broker, Connectors and Centreon Web from sources
2. enable the contreon apache conf : run 'a2enconf centreon'
3. Finalize the installation through the web interface 

**Describe the results you received:**
The login page is not correctly displayed 
The admin's login not working

**Describe the results you expected:**
Admin login works

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by AnotherIdea** [comment]
Problem seems to be when the installation wizard populate the DB. Especially the 'timeperiod' table.
tp_alias is a 20 VARCHAR column when the insertCmd-Tps.sql scripts try to add '24_Hours_A_Days_A_Week' for example.
Problem seems to be occuring only with mysql 5.7 as they default the parameter "STRICT_TRANS_TABLES" which make the SQL INSERT INTO fail.

As timeperiod table is not populated, contact table cannot be populated too.

Maybe more problems in the install script, I just found this one.

**Comment by julienmathis** [comment]
Fixed !
