### ISSUE TITLE
[Monitoring  >  Event Logs  >  System Logs] Unable to export data in CSV or XML

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4584]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Cenbtreon 2.8.0-beta1

**Steps to reproduce the issue:**
1. Go to "Monitoring  >  Event Logs  >  System Logs" menu
2. Select filters
3. Try to export data in CSV or XML

**Describe the results you received:**

Nothing appear

**Describe the results you expected:**

Download CSV or XML file

**Additional information you think important (e.g. issue happens only occasionally):**

"ReferenceError: log_4_host is not defined" in Debug broswer console

**Comment by querwin** [comment]
When export in CSV, we 've got monitoring event logs and not system logs
