### ISSUE TITLE
[Reporting  >  Dashboard  >  Hosts] Unable to export CSV

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4585]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Centreon web 2.0.8-beta1

**Steps to reproduce the issue:**
1. Go to "Reporting  >  Dashboard  >  Hosts" menu
2. Click on CSV export button

**Describe the results you received:**

Nothing appear

**Additional information you think important (e.g. issue happens only occasionally):**

[Thu Aug 11 10:50:46 2016] [error] [client X.X.X.X] PHP Notice:  Trying to get property of non-object in /usr/share/centreon/www/include/reporting/dashboard/DB-Func.php on line 251, referer: http://X.X.X.X/centreon/main.php?p=307
[Thu Aug 11 10:50:46 2016] [error] [client X.X.X.X] PHP Notice:  Trying to get property of non-object in /usr/share/centreon/www/include/reporting/dashboard/DB-Func.php on line 251, referer: http://X.X.X.X/centreon/main.php?p=307
[Thu Aug 11 10:50:46 2016] [error] [client X.X.X.X] PHP Fatal error:  Call to a member function getHostServiceAclConf() on a non-object in /usr/share/centreon/www/include/reporting/dashboard/DB-Func.php on line 251, referer: http://X.X.X.X/centreon/main.php?p=307

**Comment by querwin** [comment]
Ok for hosts but same problems fir histgroups and servicegroups
