### ISSUE TITLE
BetaTest 2.8B1 - Menu API rest is missing

### ISSUE THREAD

**Issue by NicolasLarrouy** [centreon/centreon#4586]
Centreon Web version: Centreon web 2.0.8-beta1 (updated from 2.7.6)

Steps to reproduce the issue:
1. Administration > ACL

Describe the results you received:

Administration > ACL > API rest ; is missing.

**Comment by lpinsivy** [comment]
Hi,

Why do you want to have this menu ?

Centreon CLAPI API use Centeron ACL restrictions as futur Centreon Rest API.

**Comment by NicolasLarrouy** [comment]
For testing API Rest : https://documentation.centreon.com/docs/centreon/en/2.8.x/api/api_rest/index.html
" To do API calls from a specific Centreon user, you need to have permission on the API. You can configure that on the menu Administration > ACL > API rest "

**Comment by lpinsivy** [comment]
Access is available but not in ACL menu. You have to edit your contact and go on second tab and select "Yes" for "Reach API".
