### ISSUE TITLE
[BetaTest] [Monitoring > Event Logs > System Logs] Pollers list host too

### ISSUE THREAD

**Issue by NicolasLarrouy** [centreon/centreon#4588]
Centreon Web version: Centreon 2.8.0-beta1 (updated from 2.7.6)

**Steps to reproduce the issue:**
1. Go to "Monitoring > Event Logs > System Logs" menu
2. Select Pollers

**Describe the results you received:**

List Pollers + Host

**Describe the results you expected:**

List only Pollers

**Note :** 
Bug not present on 2.7.6 version

**Comment by lpinsivy** [comment]
Hi

I can't reproduce this issue. My select display only Poller on fresh install and on a upgrade from Centreon 2.7.6.

Can you try to refresh page ?

**Comment by querwin** [comment]
I can't reproduce it either

**Comment by julienmathis** [comment]
ok closed
