### ISSUE TITLE
[Home > Poller Statistics > Graphs] Graph not with new method

### ISSUE THREAD

**Issue by NicolasLarrouy** [centreon/centreon#4589]
Centreon Web version: Centreon 2.8.0-beta1 (updated from 2.7.6)

**Steps to reproduce the issue:**
1. Go to "Home > Poller Statistics > Graphs"
2. Select Pollers

**Describe the results you received:**

Graph of Poller statistics with old method

**Describe the results you expected:**

Graph of Poller statistics with new method

**Comment by julienmathis** [comment]
Now ok
