### ISSUE TITLE
[ BetaTest ] [Reporting > Dashboard > Host Groups ] Failed to load data xml

### ISSUE THREAD

**Issue by NicolasLarrouy** [centreon/centreon#4590]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon 2.8 Beta 1 ( updated from 2.6.7 ) **: 

**Steps to reproduce the issue:**
1. Go to Reporting > Dashboard > Host Groups
2. Select Host Groups

**Describe the results you received:**
Popup error : Failed to load data xml from ./include/reporting/dashboard/xmlInformations/GetXmlHostGroup.php? .... Internal Server Error

![image](https://cloud.githubusercontent.com/assets/13872993/17593111/1eff65ea-5fe5-11e6-96a4-ecc318a47beb.png)

Graph print successfully

**Comment by garnier-quentin** [comment]
There is the same error for Service Groups!
