### ISSUE TITLE
centreonHost.class.php - Add method to get host_id by host_address

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4591]
Hi,
Is it possible to add a method to get host_id by his host_address on centreonHost.class.php?

The new function could be (based on  Method that returns the id of a host):
`    /**
     \* Method that returns the id of a host by his host_address
     *
     \* @param string $host_address
     \* @return int
     */
    public function getHostId_by_address($host_address)
    {
        static $ids = array();

```
    if (!isset($host_address) || !$host_address) {
        return null;
    }
    if (!isset($ids[$host_address])) {
        $rq = "SELECT host_id
               FROM host
               WHERE host_address = '" . $this->db->escape($host_address) . "'
               LIMIT 1";
        $res = $this->db->query($rq);
        if ($res->numRows()) {
            $row = $res->fetchRow();
            $ids[$host_address] = $row['host_id'];
        }
    }
    if (isset($ids[$host_address])) {
        return $ids[$host_address];
    }
    return null;
}
```

`

**Comment by lpinsivy** [comment]
Hi

You need this feature to develop widget or module ?

Regards,

**Comment by cmeschin** [comment]
Hi,
It's for a script, launched by a scheduler, who creates downtimes.
The IP address is actually the only safe value to identify host on centreon.

I can request the database directly but it's more clean with a method ;)
But if you have another existing method for find host_id, I take it.

Thanks.

**Comment by lpinsivy** [comment]
You can have ohst_id with Centreon API
