### ISSUE TITLE
Erreur d'affichage CONFIGURATION > HOTES > GROUPES D'HOTES > Hotes liés

### ISSUE THREAD

**Issue by osfrance** [centreon/centreon#4593]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.5

**OS**: CentOS release 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.)**: Vmware

**Steps to reproduce the issue:**
1. Aller dans CONFIGURATION > HOTES > GROUPES D'HOTES 
2. Choisir un groupe ayant beaucoup d’hôtes
3. Aller dans Hôte liés.

**Describe the results you received:**
Impossible de remonter dans la liste des hôtes liés.

**Describe the results you expected:**
Il n'y a pas d’ascenseur pour remonter et supprimer un hôte.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Already corrected in Centreon web 2.8.0
