### ISSUE TITLE
[Performance] No more last/min/max/average

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4595]
---
## BUG REPORT INFORMATION

**Centreon Web version**: Centreon Webn 2.8.0-beta1

**Steps to reproduce the issue:**
1. Go to "Monitoring > Performance"
2. Add a chart

**Describe the results you received:**

Last/Min/Max/Average value are not displayed

**Comment by querwin** [comment]
The Curves menu still presents options this ones but it's never display

**Comment by masgo** [comment]
Now 2.8.1 stable has been released a month ago - this bug is still here. 

Also not only is it not displayed in performance, Min/Max/Average values can no longer be seen anywhere else.

**Comment by leoncx** [comment]
Link to push request #5006

**Comment by masgo** [comment]
Thanks for re-adding this feature. 

There is still a little bug in the "last" values shown.

Here is an example of a temperature sensor which reports values with a precission of .1 °C. The sensor transmits its values via SNMP as integer value*1000 (21000 means 21 °C). 

These are the values shown under the Graph:
`Temperature
Last :21266.67
Min :21000.00
Max :23000.00
Average :22133.27`

While the sensor actually transmitted 21000. The perfdata is
`Temperature=21000milli°C;25000;27000;0;0`
