### ISSUE TITLE
Persistent acknowledge by default

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4598]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0-beta1

**Steps to reproduce the issue:**
1. Enable the checkbox 'persistent acknowledge' in "Administration > Parameters > Monitoring"
2. Go to "Monitoring > Downtimes > Comments" 
3. Click on "Add a Service comment" or "Add a Host comment"

**Describe the results you received:**
The checkbox "Persistent" is not enabled

**Describe the results you expected:**
The checkbox should be enabled by default

**Comment by lpinsivy** [comment]
Hi Quentin,

The option "Persistent" in "Administration > Parameters > Monitoring" menu is only for acknowledgement and not for comment. That's why your checkbox is not checked.

It's a enhancement to have the possibility to define in global option.

**Comment by garnier-quentin** [comment]
Weird that's not enable by default. I think we want the comment to be persistent (99% of time)
