### ISSUE TITLE
Problem to schedule downtime/comment for meta services

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4602]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-2.8.0-beta1

**Steps to reproduce the issue:**
1. Go to a real-time service details on a meta service
2. Click on the right to 'Schedule downtime for this service ' or 'Add a comment for this service'

**Describe the results you received:**

![screen_downtime_error](https://cloud.githubusercontent.com/assets/9079781/17623655/68f7160e-60a1-11e6-9da0-16bf1c7ff2ba.png)

![screen_ack_error](https://cloud.githubusercontent.com/assets/9079781/17623707/9b431df6-60a1-11e6-9ace-2448a44e658d.png)

**Describe the results you expected:**
Should have a good selection.

**Comment by querwin** [comment]
It's still impossible to add a comment to a meta service.

**Comment by querwin** [comment]
It's OK but I think it could be a good thing to have the same thing as for downtime.
