### ISSUE TITLE
Modification de groupe de traps SNMP

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4604]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.X

**OS**: CES

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Ajouter un groupe de traps SNMP
2. Modifier le groupe de traps ajouté
3.

**Describe the results you received:**
La modification n'est pas possible : les paramètres ne sont pas chargés.

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by querwin** [comment]
Salut Loic,

Je ne reproduis pas le problème sur ma machine de tests.

Est ce que tu as des d'erreurs apache qund tu essaies de sauvegarder ?

**Comment by lolokai** [comment]
Salut Quentin,
Non je n'ai pas d'erreurs Apache.
Centreon 2.7 a été mis à jour depuis une CES 3.3

**Comment by lolokai** [comment]
Le bug vient de se reproduire ce jour

**Comment by julienmathis** [comment]
Le bug a été corrigé en 2.8.x a priori. Incapable de le reproduire ce problème.

Es tu toujours dans la même situation ?
