### ISSUE TITLE
Add search in selectbox of HTPL in host form

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4607]
**Centreon Web version**: 2.8

**OS**: CES

**Steps to reproduce the issue:**
When we create a Host based on template, it's a list, and not a search menu. And on Service page, it's a search menu.
Can you have a look?

Thanks in advance

**Describe the results you received:**
![cap 2016-08-11 a 20 36 02](https://cloud.githubusercontent.com/assets/10330979/17729325/fa2b1d6c-6463-11e6-8a7b-99da37bf2a8a.png)

**Comment by sbraz** [comment]
@lpinsivy was this fixed?
