### ISSUE TITLE
2.7.6 - Not showing all graphes for one host in Performance -> Graph section

### ISSUE THREAD

**Issue by kortaone** [centreon/centreon#4610]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 
2.7.6
**Centreon Engine version**: 
1.5.1
**Centreon Broker version**: 
2.11.5
**OS**: 
debian 8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
LXC

**Steps to reproduce the issue:**
1. Go to centreon/main.php?p=204 ( Monitoring -> Performance -> Graph )
2. Select one host
3. Only graphes associed with the host are shown (Service by host) and not hostgroup based (Service by hostgroup)

**Describe the results you received:**
It show only graphes (service by host)

**Describe the results you expected:**
Show ALL graphes for the host ( included Service by hostgroup)

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Fixed in the last 2.8.2. To be checked

**Comment by julienmathis** [comment]
Fixed
