### ISSUE TITLE
FEATURE Eventlog "Log Period" Option

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4611]
Hi,

please add an (user) option to set the "Log Period" Option at the Event Log page. One of our customers has a large environment, so there are many log messages and it is very uncomfortable and slow if the filter is on "Last year" or something else (Monthly,...).

Regards
SuL

**Comment by lpinsivy** [comment]
Hi

On Event Logs page you can filter by predefined period or from range period with "From" & "To" filters.

On Centreon Web 2.8.0 any filters will be unset and any events will be display if user doesn't click on "Apply" button.

Regards,

**Comment by itsul** [comment]
Hi,

it is correct that is possible to set the filter. The problem is the inital page load at the beginning, if you have bad luck, the filter is at last moth or year and so the user has to wait until the whole data has finished loading. In the meantime it is  unpossible to click on anything else (not even change the navigation tab).

On 2.8.0 the unset function is a great idea.

What is the default value than?
No Eventlog display until the user selected the time period
or
Show up the last 30 (for example) Eventlogs ?

Regards

**Comment by lpinsivy** [comment]
No Eventlog display until the user selected the time period
