### ISSUE TITLE
Include Timeperiods" do not work

### ISSUE THREAD

**Issue by selfcracker** [centreon/centreon#4612]
**Steps to reproduce the issue:**

using the include timeperiod function do not work on my 2.7.6 centreon.

define two timeperiods

for example for all days : 00:30-01:00,01:30-02:00,02:30-03:00,03:30-04:00,04:30-05:00,05:30-06:00,06:30-07:00,07:30-08:00,08:30-09:00,09:30-10:00,10:30-11:00,11:30-12:00

and for all days

12:30-13:00,13:30-14:00,14:30-15:00,15:30-16:00,16:30-17:30,17:30-18:00,18:30-19:00,19:30-20:00,20:30-21:00,21:30-22:00,22:30-23:00

define a third timeperiod based on 00:00-00:00 and included the two first.

using this third on a service do not work schedule only to next days at 00:00

expected to get the first xx:30

Centreon Web version**: 2.7.6
Centreon Engine version**:  1.5.0
Centos 6.8

**Comment by selfcracker** [comment]
no one to look at my problem ?

**Comment by julienmathis** [comment]
include timeperiod works like the templates. So if you define, some period for monday in the included timeperiod, you can't add something in the timeperiod for your timeperiod... It's not an addition of periods. It's a replacement of period. 

It's a Nagios inheritage
