### ISSUE TITLE
New feature: Send notifications

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4613]
Hello team,

It could be fine to add new kind of notifications?
- Skype (http://skype4py.sourceforge.net/doc/html/)
- Whatapps (https://www.unixmen.com/send-nagios-alert-notification-using-whatsapp/)
- Slack 
- ...

Thanks in advance.

**Comment by leoncx** [comment]
Hello Matthieu,

A command for slack notification exists in https://github.com/centreon/centreon-plugins.

I think this request is for the project https://github.com/centreon/centreon-plugins

**Comment by matthieu-robin** [comment]
You're right, thanks a lot Max. I'll open this one on the centreon-plugins part.

Thanks!
