### ISSUE TITLE
Centreon binary

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4614]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: CES 3.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Exécuter la commande : centreon -u admin -p centreon -a SENDTRAPCFG -v 1

**Describe the results you received:**
On obtient cette erreur :
sh: /usr/share/centreon//bin/centGenSnmpttConfFile: Aucun fichier ou dossier de ce type

**Describe the results you expected:**
Cette commande est une ancienne commande qui permettait de générer les fichiers de conf snmptt. Il faudrait la remplacer pour qu'elle puisse générer la base SQLite + envoyer cette base au poller + Reload centreontrapd

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by querwin** [comment]
In 2.8.0-beta1, I've got this error : 

PHP Fatal error:  Class 'CentreonClapi\Centreon_Db_Manager' not found in /usr/share/centreon/www/class/centreon-clapi/centreonUtils.class.php on line 75
