### ISSUE TITLE
Problème après renommage d'un host

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4615]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Bonjour,
Nous avons eu un problème à la suite d'un renommage d'un host avec l'ajout d'un nouveau host portant l'ancien nom du host renommé.
Le problème se porte sur la mise à jour de la base de données, lié à la partie "Monitoring" (centreon_storage).
A la suite du restart du poller tout est redevenu normal.

Requête SQL : 

> SELECT services.host_id, services.description, services.service_id, hosts.host_id, hosts.name, centreon.host.host_id, centreon.host.host_name 
> FROM centreon_storage.services 
> left join hosts on hosts.host_id=services.host_id
> left join centreon.host on centreon.host.host_id=services.host_id
> where hosts.alias='arcb3sw2' and services.description='Interface' and services.enabled='1';

Résultat : 

> services.host_id, services.description, services.service_id, hosts.host_id, hosts.name, centreon.host.host_id, centreon.host.host_name
> '1034', 'Interface', '13630', '1034', 'arcb3sw2', '1034', 'arcb3sw2a'
> '4003', 'Interface', '43592', '4003', 'arcb3sw2', '4003', 'arcb3sw2'

Visu de la partie "Monitoring" : 

![monitoring](https://cloud.githubusercontent.com/assets/16583698/17850584/2993fefe-685e-11e6-9ce6-1691084be87f.PNG)

Conf hosts.cfg : 

> ...
> define host {
>     host_name                      arcb3sw2
>     alias                          arcb3sw2
>     address                        x.x.x.x
>     register                       1
>     timezone                       :Europe/Paris
>     use                            CISCO_SW_3650
>     _HOST_ID                       4003
> }
> ...
> define host {
>     host_name                      arcb3sw2a
>     alias                          arcb3sw2a
>     address                        x.x.x.x
>     register                       1
>     timezone                       :Europe/London
>     use                            CISCO_SW
>     _HOST_ID                       1034
> }
> ...

**Comment by lpinsivy** [comment]
Jben94, cela me parait normal car certaines pages Centreon utilisent les nom des objets et la plupart les ID.

Tant que la base n'est pas mise à jour suite à un redémarrage du poller, les accès par nom d'objet remontent les anciennes valeur.
