### ISSUE TITLE
Beta 2.8 Wrong menu name for poller statistics

### ISSUE THREAD

**Issue by querwin** [centreon/centreon#4616]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Centreon-2.8.0-beta1

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS-6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare

**Steps to reproduce the issue:**
1. Go to the menu : Home > Poller Statitstics

**Describe the results you received:** The menu to see poller statistics is now named : "Edit View"

**Describe the results you expected:** Expected to be "Graphs" or "Poller Graphs"

**Comment by BenoitPoulet** [comment]
Hello, 
This bug apply to 2.7.6, i had to fix myself by hand.

**Comment by lpinsivy** [comment]
Maybe only present on your platform but I add a SQL request in update beta1 -> beta2 to reset name.
