### ISSUE TITLE
Poller listing page is slow

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4624]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Steps to reproduce the issue:**
1. Have many entries in log_action table (more than 200k)

**Describe the results you received:**

The page takes 5 or 6 seconds to display

**Describe the results you expected:**

If we add the good index on log_action table, it takes less than 1sec:
```
CREATE INDEX action_log_date_idx ON log_action (action_log_date);
```

**Comment by lpinsivy** [comment]
Index was added only for installation.

For migration, a procedure in documentation/releasenote will be added.

**Comment by querwin** [comment]
It's working but I keep it open to not forgot to add it in documentation and release notes

**Comment by julienmathis** [comment]
@querwin : you can now validate upgrade
