### ISSUE TITLE
[Configuration > Status Details > Services] Wrong informations are displayed for meta service

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4626]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.x / 2.8.0-bet1

**Steps to reproduce the issue:**
1. Go to Monitoring > Status Details
2. Select meta service
3. Click on meta service name to access to details page

**Describe the results you received:**

* hostname "_Module_Meta" should not appear
* display "display_name" instead of "serviuce_description"
* Remove "Host Shortcuts" group
* Correct access to  "Configure service"
* Correct access and name to " View logs for service meta_1"
* Correct access and name to " View report for service meta_1"
* Remove "All Services" group
* Remove "Host GRoups" and "Service Catagorie" in "Links" group
* Correct all "Service Commands"

**Comment by kduret** [comment]
Linked commit : 
* 03b6dbe75c27d78b653fbf9ecba3955c2c994f52
* e5674abc4c75d42fba703f327429eb9c63b73cbc
* c3c936fc29648a93832ae6857d2a8aef7564eaf8
