### ISSUE TITLE
centreon_storage purge never completes (already covered by workaround required)

### ISSUE THREAD

**Issue by gvieira-nr** [centreon/centreon#4627]
---
## BUG REPORT INFORMATION

NOTE: I know this has been raised before about the purging issue and the solution given by centreon was to partition and that it's been done by the new version (is it production ready yet?), no temporarily fix or workarounds have been given for current 2.7.x versions
The Release Change notes for centreon as far as I can search, don't exist and can't find what changes between versions are.

**Centreon Web version**:  2.7.3

**Centreon Engine version**: 1.5.0

**Centreon Broker version**: 2.11.0 (I think, how else can we tell?)

**OS**: 
Debian Jessie

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware + physical DB server

**Steps to reproduce the issue:**
1. create nsca passive alerts for 20000+ services every minute, record for 2 days.
2. stop centcore service otherwise the purge SQL gets "exceeded timeout"
3. run purge crontab and good luck getting it to complete without the UI 3 icons not going red and not updating the UI pages
4. the "delete from logs where ctime < 1471890002" will sit there for hours and simply never completes

**Describe the results you received:**
Because we are using 1 minute passive results, this creates ~1.2 million records an hour or there abouts causing 10+GB of data and over 70+ million rows.

**Describe the results you expected:**
Purgable. 

**Additional information you think important (e.g. issue happens only occasionally):**
Need a workaround page for current systems and not "this is in a new version" as this doesn't help people with current production systems.
I'm struggling to figure out the right way to partition this table and correctly ALTER for new partitions and deleting the old. A page for high volume users would be good on how to improve currently installed systems.

**Comment by lpinsivy** [comment]
Hi,

With next version of Centreon Web 2.8.0 partitionning will be added by default during installation.

For previous installation, a procedure will be added in documentation to set up paritionning on existing tables.

Regards

**Comment by gvieira-nr** [comment]
ah ok. I've did quite a bit of tinkering as it's killing our production server and added the following (new field to get around timestamp INT(11) which I couldn't get to work with partitons).

after dropping the table. recreated with:
CREATE TABLE `logs` (
  `log_id` int(11) NOT NULL AUTO_INCREMENT,
  `ctime` TIMESTAMP ,
  `host_id` int(11) DEFAULT NULL,
  `host_name` varchar(255) DEFAULT NULL,
  `instance_name` varchar(255) NOT NULL,
  `issue_id` int(11) DEFAULT NULL,
  `msg_type` tinyint(4) DEFAULT NULL,
  `notification_cmd` varchar(255) DEFAULT NULL,
  `notification_contact` varchar(255) DEFAULT NULL,
  `output` text,
  `retry` int(11) DEFAULT NULL,
  `service_description` varchar(255) DEFAULT NULL,
  `service_id` int(11) DEFAULT NULL,
  `status` tinyint(4) DEFAULT NULL,
  `type` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`log_id`,ctime),
  KEY `host_name` (`host_name`(64)),
  KEY `service_description` (`service_description`(64)),
  KEY `status` (`status`),
  KEY `instance_name` (`instance_name`),
  KEY `ctime` (`ctime`),
  KEY `rq1` (`host_id`,`service_id`,`msg_type`,`status`,`ctime`),
  KEY `rq2` (`host_id`,`msg_type`,`status`,`ctime`),
  KEY `host_id` (`host_id`,`service_id`,`msg_type`,`ctime`,`status`),
  KEY `host_id_2` (`host_id`,`msg_type`,`ctime`,`status`)
) ENGINE=InnoDB AUTO_INCREMENT=71123623 DEFAULT CHARSET=utf8 PARTITION BY RANGE(UNIX_TIMESTAMP(ctime)) (
    PARTITION p20160824 VALUES LESS THAN (UNIX_TIMESTAMP('2016-08-25 02:30:00')),
    PARTITION p20160825 VALUES LESS THAN (UNIX_TIMESTAMP('2016-08-26 02:30:00')),
    PARTITION p20160826 VALUES LESS THAN (UNIX_TIMESTAMP('2016-08-27 02:30:00'))
);

then scripted the purge to not do the logs table and added the following bash.
# Cron for databin and logs purge
30 2 * * *  centreon    /usr/local/centreon/cron/centstorage_purge --config=/etc/centreon/conf.pm >> /var/log/centreon/centreon-purge.log 2>&1
30 2 * * *  root        /etc/centreon/centreonstorage_rotation >> /var/log/centreon/centreon-purge.log 2>&1

#!/bin/bash

#
# This replaces purging of the `logs` table in cron script /usr/share/perl5/centreon/script/centstorage_purge.pm by using partitions
#

retentiondays=2

ppreviname=p$(date +"%Y%m%d" --date="$retentiondays days ago")
ptmorwname=p$(date +"%Y%m%d" --date="tomorrow")

pprevidate=$(date +"%Y-%m-%d 02:30:00" --date="$retentiondays days ago")
ptmorwdate=$(date +"%Y-%m-%d 02:30:00" --date="tomorrow")

echo "[$(date)] retentiondays=$retentiondays previousday_name=$ppreviname previousday_date=$pprevidate tomorrow_name=$ptmorwname tomorrow_date=$ptmorwdate"

output=$(mysql centreon_storage -e "ALTER TABLE logs DROP PARTITION $ppreviname;" 2>&1)
result=$?
if [ $result -ne 0 ]; then
    echo "[$(date)] purge for $ppreviname failed, error : $output"
fi

output=$(mysql centreon_storage -e "ALTER TABLE logs ADD PARTITION ( PARTITION $ptmorwname VALUES LESS THAN (UNIX_TIMESTAMP('$ptmorwdate')));" 2>&1)
result=$?
if [ $result -ne 0 ]; then
    echo "[$(date)] partition create for $ptmorwname failed, error : $output"
fi

echo "[$(date)] $0 completed"

it hasn't rotated the first partition so hoping it'll work. no side affect so far with 2.7.3 schema but I guess this could break future DDL changes.

**Comment by gvieira-nr** [comment]
purge worked fine, newly created parition worked fine too. so quick fix solved it. it would be good to know if ctimestamp column is going to cause upgrade problems between 2.7.3 and up.
