### ISSUE TITLE
Beta 2.8 Handle Log Period in System log page

### ISSUE THREAD

**Issue by querwin** [centreon/centreon#4634]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0-beta1

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS-7

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Go to Monitoring > Event Logs > System Logs
2. use specific date to filter

**Describe the results you received:**
- The research is based on global period defined next

**Describe the results you expected:**
When enter a specific period, clean pre defined period

**Comment by lpinsivy** [comment]
No period are specified today

**Comment by querwin** [comment]
A new problem, I think linked to the commit : 

The Field, "From" and "To" are not working anymore.
