### ISSUE TITLE
Beta 2.8 Button to test connexion to mediawiki database

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4635]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.)**: VMware

**Steps to reproduce the issue:**
1. Go to Administration->Parameters->Knowledge Base

**Describe the results you received:** No button to test mediawiki's database connexion

**Describe the results you expected:** Button to test mediawiki's database connexion

**Comment by querwin** [comment]
Is it possible to have a better message when connection is not working ?

SQLSTATE[HY000] [2005] Unknown MySQL server host 'localhostaaa' (-2)
