### ISSUE TITLE
Beta 2.8 No success information in centreon-backup.log

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4636]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Activate Centreon Backup

**Describe the results you received:** Backup process has succeeded. No information in centreon-backup.log 

**Describe the results you expected:** Success information in centreon-backup.log

**Comment by kduret** [comment]
Fixed here : https://github.com/centreon/centreon/commit/0818e073b5f362d1fe93f8eeb0441f032fcf7d7a
