### ISSUE TITLE
Beta 2.8 LVM Snapshot does not save MySQL databases

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4638]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Activate Centreon backup
2. Choose LVM Snapshot type

**Describe the results you received:** No backup files for centreon and centreon_storage database

**Describe the results you expected:** Backup files for centreon and centreon_storage database

**Additional information you think important (e.g. issue happens only occasionally):** No error in centreon-backup.log

**Comment by kduret** [comment]
Logs fixed here : 0818e073b5f362d1fe93f8eeb0441f032fcf7d7a

logs for this error are : "Cannot backup with LVM snapshot. Maybe you can try with mysqldump"

Do you have enough space (1GB) on your VG where MySQL LVM is located ?

**Comment by Shini31** [comment]
```
df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_central28-lv_root
                       14G  2,1G   11G  16% /
tmpfs                 939M     0  939M   0% /dev/shm
/dev/sda1             477M   60M  393M  14% /boot
```

**Comment by kduret** [comment]
Can you give me result of "vgdisplay" command please ?

**Comment by Shini31** [comment]
```
vgdisplay 
  --- Volume group ---
  VG Name               vg_central28
  System ID             
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  3
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                2
  Open LV               2
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               15,51 GiB
  PE Size               4,00 MiB
  Total PE              3970
  Alloc PE / Size       3970 / 15,51 GiB
  Free  PE / Size       0 / 0   
  VG UUID               qPXlA6-5TlB-NR4C-6Y7u-yqDn-oREx-njUuyh
```

**Comment by kduret** [comment]
LVM snapshot is not possible if you don't have enough space in your VG.
In your case, FREE PE : 0
