### ISSUE TITLE
Beta 2.8 Missing $CENTREONPLUGINS$ ressource

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4639]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Update 2.7.6 to 2.8.0-beta2

**Describe the results you received:** $CENTREONPLUGINS$ ressource is missing

**Describe the results you expected:** Creation of $CENTREONPLUGINS$ ressource

**Comment by julienmathis** [comment]
This macro will be added by the Plugin Pack Manager.

Thanks
