### ISSUE TITLE
List only custom host and service templates if present

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4640]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Install Centreon PP

**Describe the results you received:** In host or service form creation locked and custom templates are listed

**Describe the results you expected:**  If locked and custom template exist, only list custom templates

**Comment by lpinsivy** [comment]
should be better to improve selection of template #5649
