### ISSUE TITLE
Beta 2.8 Bad value in curve

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4643]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Stop centreontrapd process
2. Add monitoring for centreontrapd process
3. Wait time that the curve appears (metric value = 0)
4. Start centreontrapd process
5. Wait time that the curve changes (metric value = 1)

**Describe the results you received:** Bad value => 0,807. it's impossible for a process.
![graph-process](https://cloud.githubusercontent.com/assets/333820/17974449/6b18fffc-6ae6-11e6-940b-7a9ed7401f6c.PNG)

**Describe the results you expected:** Good value => 1

**Comment by lpinsivy** [comment]
It's from RRDtool extract due to AVERAGE

**Comment by querwin** [comment]
Possible to think about deleting this points in RRD ?

**Comment by garnier-quentin** [comment]
The average from rrd is due to the retry check interval (1min). rrdtool is timed for each 5 minutes. So rrd is doing a big average. We need to remove that values. (no meaning) and use step chart.

**Comment by masgo** [comment]
This is probably related/the same issue.

I do 5 pings every 1 min. If I zoom-in the values are wrong.

A value of 98.3 is impossible with only 5 pings. This should be 100%
![issue 1b](https://cloud.githubusercontent.com/assets/1336992/21224662/8edad8fe-c2cd-11e6-81aa-ac8f6a091899.png)

This should be 0%
![issue 1a](https://cloud.githubusercontent.com/assets/1336992/21224690/af50e542-c2cd-11e6-8cc5-7e81066974d1.png)

This is the exported graph. So the error is probably from rrd
![issue1](https://cloud.githubusercontent.com/assets/1336992/21224710/bf551bc0-c2cd-11e6-9b7f-c1e1d1e030b0.png)


Could it be that rrd takes into account the _exact_ time a check was executed. In this case it might have been 11:40:05 .. and then it attributes most of the value to 11:40 and a small rest to 11:41? 

----

Is this also related? 

Packet loss can not be higher than 100% and 95% is also impossible with only 5 pings.
![issue2](https://cloud.githubusercontent.com/assets/1336992/21224736/df9ba818-c2cd-11e6-816c-086b9916a499.png)
