### ISSUE TITLE
Beta 2.8 Curve with an weird shape.

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4644]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Stop centreontrapd process
2. Add monitoring for centreontrapd process
3. Wait time that the curve appears (metric value = 0)
4. Start centreontrapd process
5. Wait time that the curve changes (metric value = 1)

**Describe the results you received:**  The curve drops below zero and then slowly rises to pass over 1 before stabilizing.
![graph-process-2](https://cloud.githubusercontent.com/assets/333820/17974558/dbeb852e-6ae6-11e6-80e2-7613adeab5d5.PNG)

**Describe the results you expected:** The curve should not go below 0 and above 1

**Comment by querwin** [comment]
Maybe we can use something like this in Curve Template ? When monitoring process for example.

http://c3js.org/samples/chart_step.html

**Comment by masgo** [comment]
I have the same bug on EVERY chart which has a sudden change in it. If it goes from 0 to some value one knows that its a fake value and ignore it. But this also happens with sudden changes from x to y. This leads to wrong conclusions about what happened.
