### ISSUE TITLE
[logAnalyserBroker] Doesn't work

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4649]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**:  2.7.x
**Centreon Engine version**: 1.5.x
**Centreon Broker version**: 2.11.x
**OS**: CentOS 6
---------------------------------------------------

Hi,

Script /usr/share/centreon/bin/logAnalyserBroker doesn't work, so it is impossible to rebuild logs.
```
# /usr/share/centreon/bin/logAnalyserBroker -p 1 -s 01-01-2016
Error: Cannot get archive log path at /usr/share/perl5/vendor_perl/centreon/script/logAnalyserBroker.pm line 285.
```
This problem is present since 2.7.x and comes from a error in database centreon_storage.
By default, SQL query return this:
```
# mysql centreon_storage
# SELECT `archive_log`, `archive_retention`, `nagios_log_file`  FROM `config` LIMIT 1;
*************************** 1. row ***************************
archive_log: 1
archive_retention: 365
nagios_log_file: /var/log/centreon-engine/nagios.log
```
It is necessary to change in database to enable the archive and use the right path.
```
# mysql centreon_storage
# UPDATE config SET archive_log = '1', nagios_log_file = "/var/log/centreon-engine/centengine.log" WHERE id='1';

# SELECT `archive_log`, `archive_retention`, `nagios_log_file`  FROM `config` LIMIT 1;
*************************** 1. row ***************************
archive_log: 1
archive_retention: 365
nagios_log_file: /var/log/centreon-engine/centengine.log
```

Best Regards

**Comment by lpinsivy** [comment]
Hi,

It's a configuration issue, note a bug.

**Comment by ganoze** [comment]
@lpinsivy Your commit was not added to the correct file. You used _www/install/sql/centreon/Update-DB-2.8.0-beta1_to_2.8.0-beta2.sql_ whereas it should have been in _www/install/sql/centstorage_.
