### ISSUE TITLE
Beta 2.8 Engine statistics graph not in C3/D3

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#4651]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Home -> Poller Statistics -> Graphs

**Describe the results you received:** Graph in PNG

**Describe the results you expected:** Graph in C3/D3

**Comment by lpinsivy** [comment]
Duplicate of #4589
