### ISSUE TITLE
[Event Logs] Can't filter by meta services

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4652]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.x / 2.8.0

**Steps to reproduce the issue:**
1. Configure meta service
2. Go to "Monitoring > Event Logs
3. Try to filter by meta service

**Describe the results you received:**

No meta service appear in sevice filter

**Describe the results you expected:**

Meta service name should be appear in list

**Comment by kduret** [comment]
Probably fixed here : 
* c3c936fc29648a93832ae6857d2a8aef7564eaf8
* 374ebd96c882f7a3609d98a27f71f1aceb634c4c
* f5f6ad99324b16a22d06af42761de053e996e3a3
