### ISSUE TITLE
[Notification popup] Wrong name for Business Activity

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4654]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.x / 2.8.0

**Steps to reproduce the issue:**
1. Configure BA
2. Enable notification by popup

**Describe the results you received:**

_Module_BAM / ba_1 is OK

**Describe the results you expected:**

Business Activity / "BA name" is OK

**Additional information you think important (e.g. issue happens only occasionally):**

Like Meta service correction

**Comment by querwin** [comment]
I've got 2 popups, one with the BA name and an other one with BA_id

**Comment by lpinsivy** [comment]
Need a modification of Centreon Engine to set display_name for BA

**Comment by querwin** [comment]
When BA status change, we have popup like : 

- Business Activity is Up

or every host status, I think that it doesn't have any sense.
