### ISSUE TITLE
[Dashboard] Services - Incorrect display

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4661]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.X / 2.8.0

**Steps to reproduce the issue:**
1. Go to "Dashboard > Hosts" menu
2. Select a host
3. Click on a service

**Describe the results you received:**

line "Scheduled downtime" is not display as the others

**Additional information you think important (e.g. issue happens only occasionally):**

![screenshot at aout 29 15-51-49](https://cloud.githubusercontent.com/assets/3351916/18053621/ae3844d8-6e00-11e6-89eb-f2354f2b5f59.png)

**Comment by julienmathis** [comment]
deprecated
