### ISSUE TITLE
Erreur de variable

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4664]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Bonjour,
Dans le fichier "class/centreonSession.class.php" et dans la fonction "getUser".
Nous avons une erreur avec la variable $session_id / $sessionId.
Cordialement.

**Comment by jben94** [comment]
Julien, tu as oublié de corriger la variable en fin de ligne 99

**Comment by julienmathis** [comment]
Oh oui ! Merci
