### ISSUE TITLE
[Notifications] metaservices contacts and contactgroups are not exported

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#4666]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.0-beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: Centos-7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Edit a metaservice
2. Add a contact or a contactgroup in notifications
3. Export configuration on central
4. Look at /etc/centreon-engine/meta_services.cfg

**Describe the results you received:**
No lines "contacts" or "contactgroups"

**Describe the results you expected:**
contacts c1,c2,c3
contacrgroups cg1,cg2,cg3

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
It's working for contactgroups but contacts are not generated
