### ISSUE TITLE
"Inherit only contacts/contacts group from host" help is empty

### ISSUE THREAD

**Issue by julienmathis** [centreon/centreon#4669]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0

**OS**: CES 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM

**Steps to reproduce the issue:**
1. clic on the help icon of option "Inherit only contacts/contacts group from host" in service form

**Describe the results you received:** the help is empty

**Describe the results you expected:** the should help me

**Comment by querwin** [comment]
duplicate : 

https://github.com/centreon/centreon/issues/4617
