### ISSUE TITLE
Question - Utilisation de la table "ods_view_details"

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4670]
Bonjour,

J'ai juste des questions sur l'utilisation de la table "ods_view_details", 
Je me demande à quoi sert-elle ? Et pourquoi elle est lié aux utilisateurs ?

Je vous pose la question car j'ai identifié que l'utilisation de cette table dans le fichier "centreonGraph.class.php" me crée de gros ralentissement sur l'affichage des graphiques. En retirant cette partie l'affichage est presque instantané.
De plus je remarque qu'elle ne se vide pas toute seul, par rapport aux utilisateurs et aux métrics plus présent en base. Est-ce normal ?

Merci par avance de vos réponse.
Cordialement.

**Comment by lpinsivy** [comment]
Cette table permet de récupérer la définition faites par l'utilisateur sur une courbe (changer la couleur, l'épaisseur, remplir l'intervalle entre la courbe et l'axe des abscisse, etc.).

**Comment by jben94** [comment]
Bonjour,
Je pensais que les tables "giv_components_template" et "giv_graphs_template" étaient là pour ce que tu dis.
Dans la table "ods_view_details", je vois la couleur et c'est une couleur aléatoire qui est enregistré dans cette table la première fois qu'un utilisateur va sur un graph.

**Comment by julienmathis** [comment]
Bonjour, 

cela permet de stocker la couleur aléatoire attitrée à une métrique non définie dans les curve templates. Cela permet que la couleur ne change pas à chaque affichage. 
Oui c'est encore utilisé. N'est ce pas un problème d'index mal positionné ou pas positionné ? 

Peut on avoir un explain sur la requête ? 

Merci

**Comment by jben94** [comment]
Bonjour,

Justement, de base cette table contient un seul index "dv_id", qui n'est pas utilisé dans la requête SQL lors du SELECT.

> CREATE TABLE `ods_view_details` (
>   `dv_id` int(11) NOT NULL AUTO_INCREMENT,
>   `index_id` int(11) DEFAULT NULL,
>   `metric_id` varchar(12) DEFAULT NULL,
>   `rnd_color` varchar(7) DEFAULT NULL,
>   `contact_id` int(11) DEFAULT NULL,
>   `all_user` enum('0','1') DEFAULT NULL,
>   PRIMARY KEY (`dv_id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

>         $DBRESULT = $this->DB->query(
>             "SELECT `rnd_color`
>                 FROM `ods_view_details`
>                 WHERE `index_id` = '" . $this->index . "'
>                     AND `metric_id` = '" . $l_mid . "'
>                     AND `contact_id` = '" . $this->user_id . "'"
>         );

Pour améliorer les performances, j'ai ajouter un index : 

> KEY `contact_index` (`contact_id`,`index_id`) USING BTREE

Modifié la requête SQL, comme ceci : 

> $this->DB->query("SELECT `rnd_color`,`metric_id` FROM `ods_view_details` WHERE `index_id` = '".$this->index."' AND `contact_id` = '".$this->user_id."'");

En mettant le résultat dans une variable, pour éviter de faire une requête SQL à chaque métrique demandé lors du "foreach" dans la fonction "initCurveList".

> explain SELECT `rnd_color`
>             FROM centreon.ods_view_details
>             WHERE `index_id` = '336'
>                 AND `metric_id` = '316'
>                 AND `contact_id` = '28';

Avant : 

>  id, select_type, table, type, possible_keys, key, key_len, ref, rows, Extra
> '1', 'SIMPLE', 'ods_view_details', 'ALL', NULL, NULL, NULL, NULL, '206086', 'Using where'

Après : 

>  id, select_type, table, type, possible_keys, key, key_len, ref, rows, Extra
> '1', 'SIMPLE', 'ods_view_details', 'ref', 'contact_index', 'contact_index', '10', 'const,const', '209', 'Using where'

**Comment by jben94** [comment]
J'ai aussi modifié la requête SQL lors de la construction de la class centreonGraph, en ajoutant l'insertion de la couleur aléatoire.

Car de base, vous faite un INSERT sans mettre de couleur, puis à l'appel de la fonction "getOVDColor" vous faite un UPDATE de la couleur aléatoire.
