### ISSUE TITLE
Beta 2.8 beta2 - Poller stats Graph design issue

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon#4672]
**Centreon Web version**: 2.8 beta2

**Steps to reproduce the issue:**
1. Go to Home/ Poller statistiques / graphs
2.
3.

**Describe the results you received:**
The graphs are still in old graph design

**Describe the results you expected:**
New design :-)

**Additional information you think important (e.g. issue happens only occasionally):**
![cap 2016-08-30 a 17 39 16](https://cloud.githubusercontent.com/assets/10330979/18095973/f90e4790-6ed8-11e6-8ec1-7ee3999d5b46.png)

**Comment by lpinsivy** [comment]
Duplicate with #4589
