### ISSUE TITLE
[BETA-2.8.0]Downtime with TZ

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#4677]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.0-Beta-2
**Centreon Engine version**: 
1.6.0
**Centreon Broker version**: 
3.0.0
**OS**: 
CentOs6
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Set TZ on two host one in Paris and one in Sydney
2.Set a downtime for this two host

**Describe the results you received:**
All downtime start at the same time

**Describe the results you expected:**
Normaly downtime must start with gap of 8 hours.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by querwin** [comment]
Problem reproduced with recurent and classic downtimes

**Comment by lpinsivy** [comment]
For your test, can you use this procedure:

Apply Europe/Paris for your user
Create a downtime on a host will start à 14h and your host have Sydney as timezone
The downtime must start at 14h on hot but in Sydney hour
