### ISSUE TITLE
[Feature Request] Define Perf-Data and Event-Retention seperately for Hosts and Services

### ISSUE THREAD

**Issue by TA-FFM** [centreon/centreon#4678]
Dear Developers,

i would like to ask you for a Feature to be implemented in Future Versions of Centreon. 
At the Moment it is only possible to define Retention via Admnistration/Parameters/Performance Management/Options for "Reporting retention duration (dashboard)/Logs retention duration/Retention Duration for Data in MySQL/RRDTool database size/Retention Duration for Downtimes and Retention Duration for Comments".
If possible, we would like to ask you to be able to set different times here for either Services or Hosts.

Regards
Timo

**Comment by garnier-quentin** [comment]
You can do it for the rrd files. In hostgroups, you have the rrd retention ;)

**Comment by julienmathis** [comment]
Sorry, but we think that it's not useful. We will not implement this functionality. Nevertheless, you can do it by hostgroups. We don't want to do it by services.
