### ISSUE TITLE
MACRO not evaluated, related to #4277

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#4681]
Hi,

I'm in Centreon 2.6.6 (always...) the patch is working for Hosts and Services in page "Status Details > Services". But in Home (I think the file is tacticalOverviewXml.php) the SERVICE MACRO is not evaluated. The MACRO is set on the template $_SERVICEARG1$, in tactical overview I have in URL : %24_SERVICEARG1%24

Is it possible to correct this plz ?

Thx!

Bug related to #4277

**Comment by julienmathis** [comment]
How do you define that ?  $_SERVICEARG1$

**Comment by Hellnino18** [comment]
In the service directly.

Exemple ARG1 = toto
![bug-macro](https://cloud.githubusercontent.com/assets/14218330/18171520/9dde30ca-7062-11e6-9d35-929f34882af8.PNG)

**Comment by lpinsivy** [comment]
sorry but since Centreon 2.7.0 we removed this page and replace it by a widget.

Can you create a new tickets on the https://github.com/Centreon-Widgets/centreon-widget-tactical-overview forge please.

Regards

**Comment by Hellnino18** [comment]
Done. Thx.
