### ISSUE TITLE
[2.8.0 beta2] centreonKB - cron configuration error

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4683]
Hi,
the centreonKB cron config is wrong.
# Cron for knowledge base
*/5 * * * * centreon /usr/share/centreon/cron/centKnowledgeSynchronizer.php >> /var/log/centreon/knowledgebase.log 2>&1

We must add "/usr/bin/php -q" in command line in /etc/cron.d/centreon line 26.
the good command is:
*/5 * * * * centreon /usr/bin/php -q /usr/share/centreon/cron/centKnowledgeSynchronizer.php >> /var/log/centreon/knowledgebase.log 2>&1

without this, centKnowledgeSynchronizer.php don't work.

thanks,

**Comment by querwin** [comment]
Thanks !

https://github.com/centreon/centreon/commit/b7450f6f4775f1a921a872a4b0498f330e865ff9
