### ISSUE TITLE
Host disabled always displayed in View Page

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#4685]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.6.6

**Centreon Engine version**: 1.4.15

**Centreon Broker version**: 2.10.3

**OS**: CES

Hi,

When a host is disabled in configuration page, the host is always viewable in View > Graphs. We need to delete it to not show it.

Cf attachment.
![bug-hosts-disabled-2](https://cloud.githubusercontent.com/assets/14218330/18195369/51485d4c-70eb-11e6-843c-51846833bccb.PNG)
![bug-hosts-disabled-1](https://cloud.githubusercontent.com/assets/14218330/18195370/5151c9e0-70eb-11e6-8d5d-0b25b4986523.PNG)

Thanks !

**Comment by lpinsivy** [comment]
Hi,

Thank you for your feeback but this version of Centreon Web is end of life : https://www.centreon.com/en/technical-support-expertise/support/software-policy/

We change the menu on latest version of Centreon.

Regards,

**Comment by Hellnino18** [comment]
Hi Laurent,

End of life : 16/12/2016, it's not the end today :)

Even in my test environnement (2.7.6), we can choose a disabled host.
