### ISSUE TITLE
[2.7.4] - problem with chains containing two consecutive spaces

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4686]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.4 but not restrictive and still present on 2.8

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 1.11.4

**OS**: CES 3.2

**Additional environment details (AWS, VirtualBox, physical, etc.):**
appears on firefox (recent), chrome (recent) and IE (recent) at least...

**Steps to reproduce the issue:**
1. create a service (or host because it's not restrictive on this object) with two consecutive spaces on the description, save (and deploy if you want to view on monitoring)
2.
3. 

**Describe the results you received:**
 on monitoring view (if you deployed) or configuration page, search this service. you must type the two spaces to find it but on display list, it appear with only one space. The browser truncate automatically double spaces.
this can cause misunderstandings in the treatment of events by not finding the desired service or configuration errors with the creation of duplicates

**Describe the results you expected:**
Saving the item is automatically replaced by one double spaces; either display as a warning for special characters which allows a user to correct his own input.
I don't know what is the better way.

**Additional information you think important (e.g. issue happens only occasionally):**

regards

**Comment by lpinsivy** [comment]
On host we replace space by underscore.

We will correct it for services.

**Comment by cmeschin** [comment]
why not but readability is less with underscores.

regards.

**Comment by cmeschin** [comment]
Hi,
This problem is always present on 2.8.2.
Is it really corrected because I don't see any fix linked on it.
Thanks for verification.
