### ISSUE TITLE
[2.8.0 beta2] Service Detail - incorrect layout

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4688]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0 beta2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0.0

**OS**: CES3.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. set a small screen resolution (1280*768 requirements) or a little bit bigger (1280*1024)
2. choose service with much perfdatas or big command line.
3. clic on service to view details.

**Describe the results you received:**
informations overlap on the right and horizontal scrollbar appears.
![service_detail](https://cloud.githubusercontent.com/assets/8720203/18227728/dc644ece-722e-11e6-9afb-699bd2651b78.png)

**Describe the results you expected:**
these details must be contained on a page without horizontal scrollbar.
the command line or perfdatas would be the reason of this overlap because displayed on single line. A display multilines would be better for these informations.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
We correct it to split performance data in order to correct thid issue.

Regards
