### ISSUE TITLE
[2.8.0 beta2] - Question on command line display on service details

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4689]
It's a good idea to display command line but it could contain secret informations (username and password for example) and it's maybe risky to display here. isn't it? :)

**Comment by julienmathis** [comment]
Secret informations are not displayed if they are in password custom macro.

**Comment by lpinsivy** [comment]
Yes, all custom macros marked as password are hidden.

Moreover, only admin and user with new ACL action checked can view command line.

Regards,
