### ISSUE TITLE
Problem with exception on timeperiods

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4690]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.6
**Centreon Engine version**: 1.5.1
**Centreon Broker version**: 2.11.5
**OS**: CentOS 6

**Steps to reproduce the issue:**
1. Create a timeperiod in "Configuration - Users - Time Periods" (example : Test)
![test_2](https://cloud.githubusercontent.com/assets/13255513/18247964/0a172dee-7376-11e6-9860-064fbac2294c.jpg)
1. Add timeperiod "Test" to an host
2. Reload Configuration

**Describe the results you received:**
Host is not checked soon as the timeperiod is activated.
However, if there are no exception host is checked.

**Describe the results you expected:**
Host should be checked from 14:40 to 15:00 every day of the week.
On September 5, host should be checked from 14:30 to 15:00 and from 15:00 to 16:00

Best Regards

**Comment by BenoitPoulet** [comment]
No you are wrong. 

The exception tell :  On September 5, host should be checked from 15:00 to 16:00

**Comment by maerlynn** [comment]
Hello,

The exception says it should be checked from 15:00 to 16:00 on September 5 and not 14:40 to 15:00, true, but services are not checked at all if the exception is placed.
On the services that are attached to this timeperiod, the next check is set to the next day.

In short, if there is an exception placed on a timeperiod, Centreon will not check services if you are in the time range exception.

It is really problematic in our environment.

Best regards.

**Comment by julienmathis** [comment]
Hello, 

This problem should be fixed with the version 1.7.0 of Centreon Engine. This version will be released soon.

Thanks
