### ISSUE TITLE
[Enhance] [centreon-widgets] - Widget-Engine-Status 1.0.1

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4692]
Hi,

Is it possible to have a list of active pollers in this widget?
When you have many pollers (more than twenty in my case) , a list of choice is better for configure this widget. ;)

regards.

**Comment by lpinsivy** [comment]
Hi @cmeschin 

Can you create this enhancment on correct forge please : https://github.com/Centreon-Widgets/centreon-widget-engine-status

Regards,

**Comment by cmeschin** [comment]
Arf... ok! done https://github.com/Centreon-Widgets/centreon-widget-engine-status/issues/4 :)
Are there a reason for that centreon-widgets is not in Centreon as centreon-plugins?
Are there other forge outsite Centreon and centreon-widgets?

regards

**Comment by lpinsivy** [comment]
It is easier for us to separate the Centreon web projects and the widgets to handle requests
