### ISSUE TITLE
[ 2.8.0-beta2 ] Can't hide the bottom grey bar

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#4695]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.0-beta2 

**Steps to reproduce the issue:**
1. Search a way to hide  the bottom grey bar who take 1cm for nothing
2.
3.

**Describe the results you received:**
Can't find any option

**Describe the results you expected:**
On option, a bouton, to hide this useless bar.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
You talk about the "footer" bar I suppose.

You can't hide it sorry.
