### ISSUE TITLE
[2.8.0-beta2] UI is flat design, but not the graph overlay

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#4696]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:   2.8.0-beta2 

**Steps to reproduce the issue:**
1. in "Monitoring  >  Status Details  >  Services > All" 
2. Put you mouse's cursor on a graph icon to show the graph (do not click)

**Describe the results you received:**
The graph is shown with an ugly grey shadow effect who break the elegant flat design

**Describe the results you expected:**
a flat design (no shadow) 

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by querwin** [comment]
fixed with this commit : https://github.com/centreon/centreon/commit/b008522864177298ab003fc0637a4bb913333a01
