### ISSUE TITLE
[ 2.8.0-beta2 ] not complete SNMP trap's Vendor name in service config

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#4698]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.0-beta2

**Steps to reproduce the issue:**
1. Go to "Configuration  >  SNMP Traps"
2. Look for a Vendor Name with an space in his name (like "Cisco Networks")
3. Now go to "Configuration  >  Services  >  Services by host", edit a service
4. In "Relations", "SNMP Traps", " Service Trap Relation", search for you vendor name

**Describe the results you received:**
You see the vendor name truncated avec the first space of his name. In my example you only see "Cisco" followed by the trap name

**Describe the results you expected:**
The full vendor name.

**Additional information you think important (e.g. issue happens only occasionally):**
And the field is **really** too short to shown vendor's name and the trap name.

**Comment by lpinsivy** [comment]
Do not mix up vendro name and alias!

We use vendor name in relation tab of services form.

**Comment by BenoitPoulet** [comment]
So be consistent, look this : 

![capture](https://cloud.githubusercontent.com/assets/2464712/18304473/e125894e-74e2-11e6-95f7-f19485cfbffd.PNG)

**Comment by BenoitPoulet** [comment]
do i need to open a new ticket for this or it's ok in this one ?
