### ISSUE TITLE
SSO Mixe

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4699]
Version centreon WEB : 2.7.6

Bonjour,

Je remarque que dans l'état actuel, il n'est pas possible d'avoir la double authentification.
Quand l'utilisateur a le droit d'utiliser le SSO, il ne peut plus faire d'authentification local. Avoir l'authentification local en cas de secours peut être pratique dans certain cas.

Pour avoir les deux cas, j'ai fais une petite modification dans la class "CentreonAuthSSO" : 

```
         if (isset($this->options_sso['sso_enable']) && $this->options_sso['sso_enable'] == 1 &&
             isset($this->options_sso['sso_header_username']) && $this->options_sso['sso_header_username'] != '' && $username == '') {
```

Car la variable "$username" est vide lorsqu'il y a un test de connexion via le SSO (Testé avec Kerberos).

**Comment by lpinsivy** [comment]
@Jben94,

SSO mixe already exist, it doesn't work?

Regards,

**Comment by jben94** [comment]
Bonjour,

Je n'ai peut être pas tout compris au fonctionnement, voici ma compréhension du code : 

- Quand un utilisateur à le droit de passer en mode SSO (Kerberos chez nous), la variable "$utilisateur" est toujours récupéré depuis une variable $_SERVER, même dans le mode MIXE, sauf si son adresse IP est en blacklist.

Ce que je voulais faire remonter dans cet Issue s'est que quand l'authentification (SSO) ne fonctionne pas, l'utilisateur ne peut pas saisir son login et password via la page de connexion standard.

**Comment by jben94** [comment]
Vous avez peut-être changé le code depuis la version 2.7.6 ?

**Comment by lpinsivy** [comment]
@jben94 I made a test on Centreon Web 2.7.6.

With SSO only, if SEO doesn't work you can't connect to Centreon with local account.
With SSO mixed, you can connect both SSO and local account.

I suppose it works as you want.

Regards
