### ISSUE TITLE
TRAPS SNMP - Erreur après recherche et modification

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4701]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.5

**OS**: CES 3.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtuel

**Steps to reproduce the issue:**
1. Se rendre dans Configuration - Traps SNMP
2. Faire une recherche dans le champ recherche
3. Cliquer sur un OID et le modifier

**Describe the results you received:**
Le champ recherche est remis à zéro

**Describe the results you expected:**
Que la recherche soit conservée 

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi lolokai,

Can you write your issue in english? This will allow for all people to understand the content.

Moreover it is more an enhancement than a bug.

Regards
