### ISSUE TITLE
Something wrong with parsing ARG with "

### ISSUE THREAD

**Issue by marek-knappe** [centreon/centreon#4704]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
Centreon 2.7.6

**Centreon Engine version**: 
Centreon 2.7.6
**Centreon Broker version**: 
Centreon 2.7.6
**OS**: 
RHEL
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker

**Steps to reproduce the issue:**
1. Install new centreon from RHEL/centos repo
2. Add new host with remote SNMP 
3. remote SNMP is saying about missing -p for snmp command

**Describe the results you received:**
SNMP command failed

**Describe the results you expected:**
SNMP command success

**Additional information you think important (e.g. issue happens only occasionally):**
The problem as i see is with parsing the ARG1 with ", as SWAP remote command have 
ARG1="Swap space" there is something wrong with parsing that into command.

I checked the debug log and command looks like:
[1473513961] [997] raw::run: cmd='/usr/lib/nagios/plugins/check_centreon_snmp_remote_storage -H HOST_IP -n -d "&quot" -w  -c  -v 2c -C qcommunitu', timeout=60

So clearly something with parsing. I changed that by changing the command to be "$ARG1" and value be Swap space (with no ""), but i think it should be checked by centreon team

**Comment by lpinsivy** [comment]
Thank you for your feeback.

With Centreon Web 2.8.0 we will add new Centreon plugins with new command lines.

REgards,

**Comment by marek-knappe** [comment]
Hey @lpinsivy,

you understand this incorectly - the problem is not with plugins itself, the problem is with PARSING plugin arguments.

if you put "something" to any plugin argument it will not work correctly.
