### ISSUE TITLE
Bug: Widget HTTP-Loader Scrollbar and needless space

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4706]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
Centreon 2.7.6

**OS**: 
CES

**Steps to reproduce the issue:**
1. Bug Add the HTTP Loader widget in a view
2. Bug Fix Height result in a scrollbar

**Describe the results you received:**
1. Widget is correctly loaded but has a space between top border and iframe windows
2. If there are iframes with less height than widget there should be no scrollbar

**Describe the results you expected:**
No space between top border and iframe

**Additional information you think important (e.g. issue happens only occasionally):**

/usr/share/centreon/www/widgets/httploader/index.php

Line64:
`padding 100px 0 0 0 `
to
`padding 0 0 0 0
`
and

line 80:
`<iframe id="test" width="100%" height="900px"></iframe>`
to
`<iframe id="test" width="100%" height="<?php echo $preferences['frameheight'];?>px"></iframe>`

Regards

**Comment by lpinsivy** [comment]
Hi,

Please open issue on correct project : https://github.com/Centreon-Widgets/centreon-widget-httploader

Regards,
