### ISSUE TITLE
[2.7.7] Host_id is present in Clapi export

### ISSUE THREAD

**Issue by querwin** [centreon/centreon#4707]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.7

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.5

**OS**: CentOS-6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Do an export of all objects or for a specific object
2.
3.

**Describe the results you received:**
I can see things like this in the export : 
SERVICE;setparam;Storwize;Components;host_id;443

So I can't import this export, when trying I've got this : 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'service_host_id' in 'field list'

**Describe the results you expected:**
host_id should not be in the export

**Comment by lpinsivy** [comment]
commit cd7ac4f6f52cf21988d22ac2cad619f0393e2e51
