### ISSUE TITLE
Filter for serviceXML.php possible?

### ISSUE THREAD

**Issue by HenriWahl** [centreon/centreon#4708]
Hi,

Nagstamon calls URLs like https://demo.centreon.com/centreon/include/monitoring/status/Services/xml/serviceXML.php?sort_type=status&limit=999&num=0&o=svcpb to get information about miserable hosts/services. Since later versions of Centreon, at least 2.7.6, there come ALL hosts/services as XML and not only the one needing help. Effect is as in https://github.com/HenriWahl/Nagstamon/issues/305. Is there any way to get a filtered result as before?

Regards

**Comment by BenoitPoulet** [comment]
Hello,

It's seems possible by adding «statusHost=hpb» for hosts and «statusService=svcpb» for their respecting page.

Regards.

**Comment by julienmathis** [comment]
@BenoitPoulet Yes ! 

Ok for you ? I can close ?

**Comment by HenriWahl** [comment]
Yes, works - at least the status counters in Nagstamon and Centreon web page are the same.

**Comment by HenriWahl** [comment]
According to https://github.com/HenriWahl/Nagstamon/issues/305#issuecomment-249825709 everything is allright.
