### ISSUE TITLE
[2.7.7] Tactical Overview Widget issue ?

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4710]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.7

**Centreon Engine version**: 1.5.1-3.el6.x86_64

**Centreon Broker version**: 2.11.5-2.el6.x86_64

**OS**:  CES

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Steps to reproduce the issue:**
1. Add Tactical Overview widget
2.
3.

**Describe the results you received:**
Widget shows negative value ?

**Describe the results you expected:**

Shouldn't shows negative values, right ? Look at the screenshot

![capture](https://cloud.githubusercontent.com/assets/5636906/18507274/f8633736-7a6f-11e6-8cc6-add917b9a95f.png)

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

Can you create issue on correct traker please : https://github.com/Centreon-Widgets/centreon-widget-tactical-overview

Add version of widget in ticket please.

Regards,
