### ISSUE TITLE
Enhancement - Purge old RRD files

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4715]
**Centreon Web version**: 2.7.6
**Centreon Engine version**: 1.5.1
**Centreon Broker version**: 2.11.3

Hello,

Can you add a purge of old RRD files?

If I delete services, I can see their RRD files in /var/lib/centreon/metrcis/ and /var/lib/centreon/status/ 

for example, you can delete RRD older than retention parameter.

regards

**Comment by julienmathis** [comment]
Moved here : https://github.com/centreon/centreon-broker/issues/65
