### ISSUE TITLE
PHP Notice:  Undefined index: x-centreon-token

### ISSUE THREAD

**Issue by LaurentEveris** [centreon/centreon#4716]
Hi, we are experimenting an error in Centreon 2.6.6 logs file. 

[Date] [error] [client X.X.X.X] PHP Notice:  Undefined index: x-centreon-token in /usr/share/centreon/www/lib/HTML/QuickForm.php on line 2035, referer: http://foo.bar:80/centreon/main.php?

An issue was closed  months ago:
https://github.com/centreon/centreon/issues/3869 with a solution: https://github.com/centreon/centreon/commit/ccc36beb037cbc2355b5fc1f7c77cdb526fbc4b6

But in my case I tried this solution including this code lines and it still appear in log file.
We  made an upgrade to 2.7.x but our server CPU was working at 100% of its capacity. And rolled back to previous version. 

I need a solution as soon as possible please because the log file ssl_error_log located in /var/log/httpd is growing too much.
Thanks for your support! Je suis français, n’hésitez pas à me répondre en français/anglais/espagnol si besoin est.

Laurent

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.6.6-5

**Centreon Engine version**: 1.4.15

**Centreon Broker version**: 2.10.1-6

**OS**: CentOS7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtual vmware

**Steps to reproduce the issue:**
1. Upgrade to 2.7
2.
3.

**Describe the results you received:**
CPU 100% 

**Describe the results you expected:**
No more php index error in log file

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi

Did you try to upgrade to the latest version of Centreon Web 2.7.7 ?

Regards,

**Comment by LaurentEveris** [comment]
Salut Laurent, je viens tout juste d'arriver chez notre cliente et il avait tout simplement mal copier la solution que je lui avais transmit. Tout est ok. Je cloture donc ce cas.
Merci pour ta réponse.
Laurent
