### ISSUE TITLE
Upgrade from 2.7.6 to 2.7.7 causes strage load fluctuations

### ISSUE THREAD

**Issue by masgo** [centreon/centreon#4718]
I am running a CES installation which monitors ~50 nodes and ~100 services. Last Thursday I updated from 2.7.6 to 2.7.7 via yum. Then I proceeded to do the update via the web interface. Since then, the load on the server follows a rather strange sinus line. 

![centreon-server-load](https://cloud.githubusercontent.com/assets/1336992/18626014/9a386c9e-7e52-11e6-9fff-cdefc8bfd0e5.png)

There are no other services running on the server and the load also does not correlate with the monitorred hosts/services. 

I rebooted the server Sunday evening (where the two peaks are closer together). But obviously nothing changed. 

Does anyone have an idea what is causing this?

Here is a 2 month view of the load. You can see the sudden change.
![centreon-server-load-2m](https://cloud.githubusercontent.com/assets/1336992/18626114/33562614-7e53-11e6-804c-4b263d0dbd15.png)

**Comment by masgo** [comment]
The host execution time also changed suddenly after the update:
![getstats_php](https://cloud.githubusercontent.com/assets/1336992/18635584/d3a83a3a-7e85-11e6-938d-3e4b1807dd2d.png)

**Comment by lpinsivy** [comment]
Hi,

Do you update also Centreon Engine and Centreon Broker?

Regards,

**Comment by masgo** [comment]
I updated all packages which yum showed me:

>     Updated centreon-2.7.6-4.el6.noarch                             @ces-standard-stable-noarch
    Update           2.7.7-4.el6.noarch                             @ces-standard-stable-noarch
    Updated centreon-base-config-centreon-engine-2.7.6-4.el6.noarch @ces-standard-stable-noarch
    Update                                       2.7.7-4.el6.noarch @ces-standard-stable-noarch
    Updated centreon-common-2.7.6-4.el6.noarch                      @ces-standard-stable-noarch
    Update                  2.7.7-4.el6.noarch                      @ces-standard-stable-noarch
    Updated centreon-perl-libs-2.7.6-4.el6.noarch                   @ces-standard-stable-noarch
    Update                     2.7.7-4.el6.noarch                   @ces-standard-stable-noarch
    Updated centreon-plugin-meta-2.7.6-4.el6.noarch                 @ces-standard-stable-noarch
    Update                       2.7.7-4.el6.noarch                 @ces-standard-stable-noarch
    Updated centreon-plugins-2.7.6-4.el6.noarch                     @ces-standard-stable-noarch
    Update                   2.7.7-4.el6.noarch                     @ces-standard-stable-noarch
    Updated centreon-trap-2.7.6-4.el6.noarch                        @ces-standard-stable-noarch
    Update                2.7.7-4.el6.noarch                        @ces-standard-stable-noarch
    Updated centreon-web-2.7.6-4.el6.noarch                         @ces-standard-stable-noarch
    Update               2.7.7-4.el6.noarch                         @ces-standard-stable-noarch

The web frontend shows version 2.7.7
The poller shows: `Centreon Engine 1.5.1`
yum shows me these versions:

>    centreon.noarch            2.7.7-4.el6
    centreon-broker.x86_64     2.11.5-2.el6
    centreon-common.noarch     2.7.7-4.el6
    centreon-engine.x86_64     1.5.1-3.el6
    centreon-nagvis.noarch     1.1.1-3.el6
    centreon-plugins.noarch    2.7.7-4.el6
    centreon-trap.noarch       2.7.7-4.el6
    centreon-web.noarch        2.7.7-4.el6

**Comment by masgo** [comment]
Maybe I found a solution. 

The `System Logs` showed a lot of `Max concurrent service checks (10/10) has been reached. ` messages. I changed the setting from 10 to 100 and it sees to work normal now.

**Comment by masgo** [comment]
Okay, that really solved the issue. - But why? 

I have 109 Services (including the local ones which check the load of the centreon server). The majority of the checks is executed every minute. With a maximum of 10 concurrent checks and an average execution time of below 3 seconds it should be possible to check more than 200 services without problems. 

Also: the setting was there for months, why die the update caused this effect?
