### ISSUE TITLE
[BETA]2.8 Connexion API REST

### ISSUE THREAD

**Issue by nutzmdm** [centreon/centreon#4719]
Je suis en train de me pencher sur l'utilisation de l'API REST et je ne comprend pas pourquoi les tokens de connexion sont effacés toutes les heures.
Il serait plus simple d'attribuer un token définitif à un utilisateur si il dispose du droit suffisant dans les ACL.  Ensuite on le récupère lors de l'authentification et on peut le stocker. Actuellement, si j'ai bien compris le fonctionnement de l'index.php correspondant, pour qu'un script qui fait appel à l'API ne demande pas une ré-authentification toutes les heures, je suis obligé de stocker les identifiants dans le navigateur pour les renvoyer régulièrement.

Il est cependant possible que ce fonctionnement soit temporaire puisqu'il existe une ligne:
`/* @todo Check if user already have valid token */`

**Comment by lpinsivy** [comment]
Hi,

Tokens are use for autologin With Centreon Web to replace "password". I suppose that your connection are reset due to session timeout.

Use a a definitive token could be a good ID.

Regards,

**Comment by desaille** [comment]
Hi, 

I try to use the REST API but i can't get autentication work. 
Everytime i got "400 bad parameters" error

here is my curl call 
`
curl -H "Accept: application/json" -X POST -d '{"username":"api","password":"api"}' http://localhost:55555/centreon/api/index.php?action=authenticate
`

I've try with another tools like DHC REST Client for Chrome but i didn't get it work.
This is my request : 

POST /centreon/api/index.php?action=authenticate HTTP/1.1
Host: localhost:55555
Accept: application/json
Content-Type: application/json

 {
    "username": "api",
    "password": "api"
  }

Is there anyone can help me ? 

Thanks,

**Comment by desaille** [comment]
we've found a workaround. 

if we use a x-form-www-urlencoded request like below we can get a authentication token. 

`curl --data "username=username&password=password" http://localhost:55555/centreon/api/index.php?action=authenticate`

**Comment by bevi9** [comment]
Thank you very much, I was looking for that!!! <3
