### ISSUE TITLE
Local - write_command

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#4725]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.6

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.4

**OS**: RedHat 6

Bonjour,

Quand nous sommes sur un poller-display, il est impossible d'envoyer des commandes externes de façon massives car le chemin de destination est forcé vers le fichier centcore.cmd (Centcore non utilisé sur les poller display) au lieu de prendre le chemin du "command_file" (centengine.cmd).

Pour permettre d’exécuter des commandes externes, j'ai modifié la fonction "write_command" et mis un condition afin de prendre le bon chemin.

**Comment by querwin** [comment]
Hello,

Maybe the same things as here : https://github.com/centreon/centreon/issues/4241 ?

@julienmathis

**Comment by jben94** [comment]
D'après moi ce n'est pas la même chose, si on regarde dans le fichier "www/include/monitoring/external_cmd/functions.php" dans la fonction "write_command", on remarque bien que le chemin du fichier "centcore.cmd" est forcé.

>     if (defined("_CENTREON_VARLIB_")) {
>         $destination = _CENTREON_VARLIB_."/centcore.cmd";
>     } else {
>         $destination = "/var/lib/centreon/centcore.cmd";
>     }

**Comment by julienmathis** [comment]
Il faut juste démarrer centcore. Et ca roule normalement.

**Comment by jben94** [comment]
sur les pollers-display ?
Je pensais que centcore devait être juste démarré sur le central.

**Comment by jben94** [comment]
Quand il est démarré, j'ai des erreurs de base de données : 

2016-09-30 00:09:40 - MySQL error : cannot connect to database dbname=/centreon/etc/snmp/centreon_traps/centreontrapd.sdb: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) (caller: centreon::common::db:/centreon/lib/perl/centreon/common/db.pm:266)

**Comment by Shini31** [comment]
Bonsoir,

Avez-vous installé le rpm centreon-poller-centreon-engine ?
Cette erreur se produit seulement lorsque le fichier /etc/centreon/conf.pm contient des informations spécifiques pour le fonctionnement d'un poller.

Cordialement.

**Comment by jben94** [comment]
Bonjour,

Ce n'est pas une installation par RPM. 
Mais je ne pense pas que ca soit le problème.

Comme c'est un poller la configuration me parait correcte. 
Comme j'ai indiqué dans mon premier post, mon problème est lié à la mise en place du poller display. 

Le lien depuis le detail des services fonctionne mais pas depuis la liste des services via le choix multiple. C'est pour cela que j'ai modifié la fonction pour qu'elle fonctionne comme le lien du service detail. 

Class: centreonExternalCommand.class.php > OK
Fichier: function.php > Corrigé

**Comment by jben94** [comment]
Je trouve cela bizar de démarrer un service de plus, juste pour avoir cette fonctionnalité. Alors que si le chemin est correct tout fonctionne correctement sans lancer centcore.

**Comment by jben94** [comment]
Shini31, désolé de ne pas vous avoir remercié pour votre aide.

**Comment by Shini31** [comment]
Justement pour faire fonctionner poller display il faut installer un central et non un poller comme c'est indiqué dans la documentation : https://documentation-fr.centreon.com/docs/centreon-poller-display/en/latest/Installation.html#depuis-le-repository
Le paquet centreon-base-config-centreon-engine sert à l'installation d'un central.

Les problèmes d'external command et de centcore viennent de là.

Cordialement.

**Comment by jben94** [comment]
Je viens de regarder la documentation, ils disent qu'il faut installer comme un central mais le configurer comme un poller. Toute la configuration des contrôles .... engine, broker, se fait sur les vrais centraux. 
Je pense qu'ils veulent dire qu'il y a l'interface web et la base données en plus des fichiers du poller. 

Si comprend bien, il faut pour vous démarré centcore pour régler ce problème et en avoir un nouveau. Qui peut être réglé juste avec une condition dans une fonction. J'ai du mal à comprendre ce point de vu.

Merci pour votre aide, je vais laisser ma modification qui fonctionne parfaitement et qui me génère plus d'erreur.
