### ISSUE TITLE
Bug: LDAP Auto import users

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4728]
---
## BUG REPORT INFORMATION

CES Beta (problem also in stable version 2.7.x):

centreon-syslog-server-1.2.5-6.el6.noarch
centreon-engine-daemon-1.6.0-1472141297.6301589.el6.x86_64
centreon-clib-1.4.2-1.el6.x86_64
centreon-broker-core-3.0.0-1472213579.939db56.el6.x86_64
centreon-connector-1.1.2-1.el6.x86_64
centreon-engine-1.6.0-1472141297.6301589.el6.x86_64
centreon-broker-storage-3.0.0-1472213579.939db56.el6.x86_64
centreon-trap-2.8.0-0.3.beta2.el6.noarch
centreon-common-2.8.0-0.3.beta2.el6.noarch
centreon-engine-extcommands-1.6.0-1472141297.6301589.el6.x86_64
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-broker-3.0.0-1472213579.939db56.el6.x86_64
centreon-broker-cbd-3.0.0-1472213579.939db56.el6.x86_64
centreon-base-config-centreon-engine-2.8.0-0.3.beta2.el6.noarch
centreon-perl-libs-2.8.0-0.3.beta2.el6.noarch
centreon-broker-cbmod-3.0.0-1472213579.939db56.el6.x86_64
centreon-web-2.8.0-0.3.beta2.el6.noarch
centreon-syslog-frontend-1.5.3-5.el6.el6.noarch
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-2.8.0-0.3.beta2.el6.noarch

**Steps to reproduce the issue:**
Normal setup from ldap integration and "auto import users" function.
![cent_1](https://cloud.githubusercontent.com/assets/12328177/18907009/2d5c7e3e-856a-11e6-8586-9b0914e986d7.PNG)

LDAP User "sulit" is assigned to ldap groups "Windows", "Linux", "Networking"

**Describe the results you received:**
At the first users login, the user is added to only one group "Windows"
![cent_3](https://cloud.githubusercontent.com/assets/12328177/18907129/ab503970-856a-11e6-964c-85ed0476ec9f.PNG)

**Describe the results you expected:**
At the first users login, the user should be added to centreon database with all ldap groups assigned (Windows,Linux,Networking).
![cent_exp](https://cloud.githubusercontent.com/assets/12328177/18907242/3261cae6-856b-11e6-995f-bf61c88f44be.PNG)

One consequence of this is that you can not see all host objects in monitoring view (only host from Windows-Hostgroup).

**Additional information you think important (e.g. issue happens only occasionally):**
In the user object there is only the Windows group assigned , if you add antoher ldap group to the user, the change will be ignored after the form is submitted.

**Comment by itsul** [comment]
Additional information from a colleague of mine: He has invested some time into research and the problem should be the cronjob (script) that assign the ldap groups incorrectly.

**Comment by kduret** [comment]
I have committed a fix, but I think it doesn't solve your problem.

Your LDAP groups (Linux and Networking) are linked to some Centreon objects ? (ACL group, host, service ...)
If not, LDAP groups are not imported in Centreon contactgroups.

**Comment by kduret** [comment]
linked commit : 
1e36fcdbd904d57694f75a100cd6919d0d42441c
