### ISSUE TITLE
Bug: Service Object change template/command args

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4729]
---
## BUG REPORT INFORMATION

centreon-syslog-server-1.2.5-6.el6.noarch
centreon-engine-daemon-1.6.0-1472141297.6301589.el6.x86_64
centreon-clib-1.4.2-1.el6.x86_64
centreon-broker-core-3.0.0-1472213579.939db56.el6.x86_64
centreon-connector-1.1.2-1.el6.x86_64
centreon-engine-1.6.0-1472141297.6301589.el6.x86_64
centreon-broker-storage-3.0.0-1472213579.939db56.el6.x86_64
centreon-trap-2.8.0-0.3.beta2.el6.noarch
centreon-common-2.8.0-0.3.beta2.el6.noarch
centreon-engine-extcommands-1.6.0-1472141297.6301589.el6.x86_64
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-broker-3.0.0-1472213579.939db56.el6.x86_64
centreon-broker-cbd-3.0.0-1472213579.939db56.el6.x86_64
centreon-base-config-centreon-engine-2.8.0-0.3.beta2.el6.noarch
centreon-perl-libs-2.8.0-0.3.beta2.el6.noarch
centreon-broker-cbmod-3.0.0-1472213579.939db56.el6.x86_64
centreon-web-2.8.0-0.3.beta2.el6.noarch
centreon-syslog-frontend-1.5.3-5.el6.el6.noarch
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-2.8.0-0.3.beta2.el6.noarch

**Steps to reproduce the issue:**
1. Create a template with different args
2. Add a service to a host and asign a service template to it
3. Edit the service object and change the template or command (with different args)

**Describe the results you received:**
ARGs are static in the view - nothing changed
![cent1](https://cloud.githubusercontent.com/assets/12328177/18952228/35b44b0e-8649-11e6-820d-9fadf6669d9a.PNG)

**Describe the results you expected:**
ARGs should change depending on template/command
![cent2](https://cloud.githubusercontent.com/assets/12328177/18952240/3b759a98-8649-11e6-801c-c24e2966989f.PNG)

**Additional information you think important (e.g. issue happens only occasionally):**
Seems to be a display problem only. If you submit the form, the args are changed correctly as far as possible

**Comment by hocinetwork** [comment]
+1

**Comment by Poels** [comment]
+1 i have updated in centreon-web 2.8.1 and i have the same issue.

**Comment by zskarman** [comment]
4810 is the similar issue.
