### ISSUE TITLE
Remove the capability for LDAP users to change the login/password

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4733]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.7

**Steps to reproduce the issue:**
1. Import ldap user
2. Connect with the new ldap user
3. Click on the username (myAccount page)

**Describe the results you received:**
I can change the login (can be dangerous). I can also put a password (useless).

**Describe the results you expected:**
I cannot change my login and set a password

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
done
