### ISSUE TITLE
problems whith command ssh Centreon GUI

### ISSUE THREAD

**Issue by gajete** [centreon/centreon#4734]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.6

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 
CES

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

When you run the script from the **command line result is correct**:

[centreon@XXXXXXXXXX ~]$ /usr/lib/nagios/plugins/ssh centreon@XXXXXXXXX -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no '/usr/local/nagios/custom/check_cpu -w '90' -c '95''
Warning: Permanently added 'XXXXXXXXXXXXX' (RSA) to the list of known hosts.
OK: Uso de CPU: usr=0%, sys=0%, idle=98%, wait=1% | usr=0% sys=0% idle=98%;90;95;0; wait=1%

When you run the **script by Centreon Gui, the result is incorrect**. The result is as follows:

Command Line	/usr/lib/nagios/plugins/ssh centreon@XXXXXX -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no '/usr/local/nagios/custom/check_cpu -w '90' -c '95''
Output	
Status	UNKNOWN

**Describe the results you expected:**

We expect the same result as if run by command line

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by querwin** [comment]
Hello,

Plugins are launched with users "centreon-engine". As I can see on your message, you try to launch it with user centreon.

Can you try with user centreon-engine ?

Regards,

**Comment by gajete** [comment]
Good afternoon,

effectively already operated correctly.

Thank you
