### ISSUE TITLE
Recherche TRAPS SNMP

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4735]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.7

**Centreon Engine version**: 1.5.1

**Centreon Broker version**: 2.11.5

**OS**: CES 3.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Se rendre dans configuration - SNMP Traps
2. Faire une recherche
3. Cliquer sur un OID et le modifier

**Describe the results you received:**
 Lors du retour sur la page d'accueil la recherche est perdue

**Describe the results you expected:**
Garder la recherche

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Fixed in Centreon 2.8.0.

Thanks :)
