### ISSUE TITLE
Problem with uptime and MacOS

### ISSUE THREAD

**Issue by sulian** [centreon/centreon#4736]
Hello,

the ```check_centreon_snmp_uptime``` command seems to do not work correctly with apple system

The command work well without the `-d` parameter (see screenshot), with param `d`, the result is always 0day(s) : 

localhost is centreon
zeus is macos server 10.5.8

![bug_uptime](https://cloud.githubusercontent.com/assets/2016950/19148930/77c27f54-8bbf-11e6-8f1f-98fe86e72c91.jpg)

problem is the same with macos 10.6 and macos server 10.4.11

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Centreon CES 3.3 (with CentOS)

**Comment by julienmathis** [comment]
Hello, 

Your problem concerns centreon-plugins. Can you open this ticket in centreon/centreon-plugins ?

Thanks

**Comment by sulian** [comment]
@julienmathis, I have post my problem in centreon-plugins. I don't know that the ```check_centreon_snmp_uptime``` command is part of centreon-plugins
