### ISSUE TITLE
[2.7.7] Virtual Metrics - Unable to save with "sigma" name

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4737]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.7

**Centreon Engine version**: 2.5.1

**Centreon Broker version**: 2.11.5

**OS**: CES3.2

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create the virtual metric "sigma" same as this article in blog http://blog.centreon.com/bonnes-pratiques-les-metriques-virtuelles-partie-2/?lang=fr
2. save

**Describe the results you received:**
an error appear like this:
![virtual_metric_sigma](https://cloud.githubusercontent.com/assets/8720203/19157306/2e4166f8-8be5-11e6-967f-91c954457a3f.png)

**Describe the results you expected:**
Save the virtual metric name without limitations or if restrictions are required, display them in the form or in the context help.

**Additional information you think important (e.g. issue happens only occasionally):**
this message appear in US or French language UI and independantly of ACL's.
the names "prediction" and "smooth" are created without error.

**Comment by lpinsivy** [comment]
Hi,

Sigma is a existing name in RRDtool function : https://oss.oetiker.ch/rrdtool/doc/rrdgraph_rpn.en.html

Regards,
