### ISSUE TITLE
Graph Popup display partially outside the screen

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4738]
---
## ENHANCE REPORT INFORMATION

**Centreon Web version**: 2.7.7 and 2.8 beta2

**Centreon Engine version**: 2.5.1

**Centreon Broker version**: 2.11.5

**OS**: CES 3.2

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
 On a small screen or with hosts and services with names long, the graph popup appear on the right of screen and partially outside of the screen
![graphe_outside_screen](https://cloud.githubusercontent.com/assets/8720203/19197005/08c7b8b8-8cb8-11e6-83aa-5d0a4e166205.png)
no horizontal scrollbar appear in this case

**Describe the results you expected:**
the graph must be centered on screen or at least placed on right border of screen.
no scroll bar should appear

**Additional information you think important (e.g. issue happens only occasionally):**
same results on recent chrome and firefox versions.

**Comment by CPbN** [comment]
Same behavior with _Service details_ popup in for example _Services by Hostgroup_ view.
May be a whole popup system issue which could be corrected globally.

**Comment by CPbN** [comment]
Perhaps it's in some kind related to https://github.com/centreon/centreon/pull/7140 ?

**Comment by CPbN** [comment]
Perhaps it's in some kind related to your PR https://github.com/centreon/centreon/pull/7140 @sc979 ?

**Comment by sc979** [comment]
Hi CPbN,
The scope of the PR 7140 was to fix the incoherent vertical display of the popups. But not the horizontal position.
I tried to fix the horizontal position, without success, the result was a blinking popup.
We must refacto this part of the front end legacy code.

Sincerely,

sc979
