### ISSUE TITLE
Add lazy load of c3 graph(s) in Monitoring > Performances > Graphs

### ISSUE THREAD

**Issue by Manu1400** [centreon/centreon#4740]
**Centreon Web version**: 2.8

**Describe the results you received:**

**Describe the results you expected:**
Charge graph in this page if graph is visible for can reduce performance issues on this page.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Manu1400** [comment]
Idea for a simple implementation : Insert in DOM a new blank image with lazy load (ie : with 
http://www.appelsiini.net/projects/lazyload ) and use event for this library to remplace the image to the graph.

**Comment by Manu1400** [comment]
Can use only on <img>.

**Comment by florian-asche** [comment]
Also for the graphs on Dashboard
