### ISSUE TITLE
BUG : apache user not present in CENTREON User alias in /etc/sudoers.d/centreon

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon#4741]
Hello,

Few days ago i made a fresh install of centreon (version 2.7.7) from sources on CENT OS 6. 

I was not able to Apply my configuration from the GUI. I had to restart centreon-engine in console mode to have it work. 

So i checked /var/log/secure.log and i figured out that apache was missing from the sudoers.

**Comment by julienmathis** [comment]
Hello, 

do you have installation logs ?
do you disable SELinux ?

Thanks in advance

**Comment by anthoc** [comment]
There is no selinux file in /etc/sysconfig, neither in /etc/selinux so i supposed that it was disabled. Where can i find the installations logs ?

Thank You
