### ISSUE TITLE
Truncate long output (of a status) in Monitoring > Status Details > Hosts

### ISSUE THREAD

**Issue by Manu1400** [centreon/centreon#4745]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.8 beta

**Centreon Engine version**: ?

**Centreon Broker version**: ?

**OS**: Tested on Linux with Google Chrome

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical computer

**Steps to reproduce the issue:**
1. Go to Monitoring > Status Details > Hosts
2. Select a host with a very long output without space
3. Look "Status Details" part (at right of webpage)

**Describe the results you received:**
"Status Details" have no space

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**
- http://10.30.2.110/centreon/main.php?p=20202&o=hd&host_name=Camera-Ip-Datacenter-01
- Output of status-critical : aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

Ideas for solution : 
- trunk the output (simple solution)
- use CSS Flex ?

**Comment by Moujimouja** [comment]
Fixed
