### ISSUE TITLE
URL hacking using SSO enabled

### ISSUE THREAD

**Issue by 5145h** [centreon/centreon#4746]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 
centreon-web-2.8.0-0.3.beta2.el6.noarch
**Centreon Engine version**: 
centreon-engine-1.6.0-1472141297.6301589.el6.x86_64
**Centreon Broker version**: 
centreon-broker-core-3.0.0-1472213579.939db56.el6.x86_64
**OS**: 
Red Hat Enterprise Linux Server release 6.8 (Santiago)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack instance

**Steps to reproduce the issue:**
1. Enable SSO Mixed from Administration  >  Parameters  >  Centreon UI
2. Access http://Centreon_IP/centreon/index.php?useralias=admin from browser 
3. Get full access without using password
4. The same behaviour with the rest of users configured with password.

**Describe the results you received:**
Logged in without using password

**Describe the results you expected:**
Access denied or please insert password for the user used or authentication failed.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by kduret** [comment]
linked commit 57813895edfdd804aa29efdbed87c8775cbfad55

**Comment by samuel4x4** [comment]
Hello,

Which version of Centreon will contains this fix?

Thanks.
