### ISSUE TITLE
No graphs created for curves based on multiword perfdata + fix

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#4747]
Centreon Web version: 2.7.7
Centreon Engine version: 1.5.1
Centreon Broker version: 2.11.5
OS: CentOS: 6.8
check_snmp_printer: v3.14159

Steps to reproduce the issue:
1. Check the toner level(s) for a printer by snmp:
   `/usr/lib/nagios/plugins/check_snmp_printer -H 1.2.3.4 -C public -x 'CONSUM ALL'`

For various printers (black, colour), the results received are:
`Toner X-YZ ABC is at 30% - OK!|Toner X-YZ ABC=30;20;5;`

`AB-1234C is at 99% - OK! AB-1234M is at 98% - OK! AB-1234Y is at 98% - OK! AB-1234K is at 98% - OK! Waste Toner is OK!|AB-1234C=99;20;5; AB-1234M=98;20;5; AB-1234Y=98;20;5; AB-1234K=98;20;5; Waste Toner=-3;20;5;`
1. define a check command:

`$USER1$/check_snmp_printer -H '$HOSTADDRESS$' -C '$ARG1$' -x '$ARG2$' -w '$ARG3$' -c '$ARG4$'`

This is called from a template with community string in $ARG1$, CONSUM ALL in $ARG2$, 10 and 5 for $ARG3$ and $ARG4$
1. under Monitoring/Performances/Curves, add a curve with Template Name "Toner_Printer_X", Data Source Name "XY-1234"

Expected result: graph is created with the curve defined above.

In the Centreon web interface under Monitoring, Status Details, Services the text response is correctly shown in the "Status information" column as well as the performance data in the popup window when hovering over the check (albeit broken down to a new line per contiguous string).

But the graph isn't created, the graph icon doesn't appear in front of the service.

Solution: escape $PERFDAT for the CONSUM ALL test in /usr/local/nagios/plugins/check_snmp_printer:

old line:
`PERFDAT="$PERFDAT $MARKER_NAME=$CURRENT_CAPACITY;$WARNING;$CRITICAL;"`

new line:
`PERFDAT="$PERFDAT \'$MARKER_NAME\'=$CURRENT_CAPACITY;$WARNING;$CRITICAL;"`

After this the perfdata markers are enclosed in single quotes and Centreon will build graphs.

**Comment by julienmathis** [comment]
Hello, 

So it's a plugin issue no ?

**Comment by btassite** [comment]
Not really because the workaround is for this particular plugin only, the problem is that arguably Centreon doesn't parse perfdata with whitespace correctly, unless some spec I don't know about says you can't have whitespace in perfdata.

For some plugins this is a trivial fix, for others it is not (e.g. ELF executables, which either need a recompile and support for the fix or a suboptimal wrapper script). It would be better to fix it in Centreon, unless there is a use case for parsing perfdata substrings separately.

**Comment by Sims24** [comment]
Hi @btassite , 

Actually, it's a plugin issue, because of development guidelines described here -> https://www.monitoring-plugins.org/doc/guidelines.html#AEN201 .

Centreon is handling correctly space in perfdata, but the label should be enclosed by quote. 

Moreover, this plugin is deprecated. Please use new ones from centreon-plugins github repository. 

Quick how-to : 

- cd /usr/local/src && git clone https://github.com/centreon/centreon-plugins
- cd centreon_plugins
- perl centreon_plugins.pl --plugin hardware::printers::standard::rfc3805::plugin --list-mode to check available modes and achieve a more complete monitoring :)
- e.g use /usr/lib/nagios/plugins/centreon_plugins.pl --plugin hardware/printers/standard/rfc3805/plugin --mode markersupply-usage --help to list all available option
- this one will not get you in trouble I sware ;)

**Comment by Sims24** [comment]
cc @julienmathis can close this. Thanks

**Comment by btassite** [comment]
Thanks, that answers my question (it's illegal to have unquoted whitespace in perfdata, which is what my fix solved).

I still have an issue with some (multiword) curves not creating graphs, as far as I can see the only difference with working ones now is that the perfdata contains UTF-8 characters for the non-working one.

Your plugin fixes this as it simply outputs "black" instead of whatever the printer's language setting supplies and --change-perfdata allows this to be massaged further, very nice.

I can't use it though as there is a problem with warning levels: when toner level is say at 19%, --mode markersupply-usage --warning 20 --critical 10 should return WARNING, but returns CRITICAL instead. It looks like it interprets the arguments as a minimum threshold, whereas this is a depletion warning, so it should be a maximum. Is there a switch for this or can you fix it? :)

This doesn't solve the original issue though, Centreon 

Centreon still has an issue with perfdata even escaped with single quotes, some curves don't create graphs, so far the only difference with other curves is that there are some UTF-8 characters in the output, not sure what to do with that on the check side.

**Comment by btassite** [comment]
Found searching through the plugin section: add a colon to the value to reverse warning/critical threshold from minimum to maximum (" --warning 20: --critical 10: ").

**Comment by btassite** [comment]
Ran into a new problem: on the commandline this works:

$ ./centreon_plugins.pl --plugin hardware::printers::standard::rfc3805::plugin --mode markersupply-usage --hostname 1.2.3.4 --warning 15: --critical 10: --change-perfdata 'black,ABCD12E'
OK: Marker supply usages are ok. | 'ABCD12E'=18.00%;15:;10:;0;100

When putting it in a Centreon check:
$USER1$/centreon_plugins.pl --plugin hardware::printers::standard::rfc3805::plugin --snmp-timeout 3 --mode markersupply-usage --hostname '$HOSTADDRESS$' --warning '$ARG1$': --critical '$ARG2$': --change-perfdata "$ARG3$,$ARG4$"

Centreon eats the perfdata starting with the closing single quote (and therefore graphing doesn't work):

$ mysql -NB centreon_storage -e "select services.perfdata from services where services.command_line like '%markersupply%';"
```
'ABCD12E
```

**Comment by btassite** [comment]
The plugin developer closed this in centreon-plugins noting it's not a plugin issue, therefore it must be a Centreon issue.

**Comment by masgo** [comment]
I think I ran into the same issue. I call the plugin like this
`perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin --snmp-version 2 --hostname 192.168.1.111 --mode markersupply-usage`

The result is:
`OK: Marker supply usages are ok. | 'Patrone Schwarz 37A HP CF237A#black'=95.00%;;;0;100 'Wartungskit HP 110V-J8J87A, 220V-J8J88A'=100.00%;;;0;100`

But in centreon service-details the performance data is shown as: `'Patrone Schwarz 37A HP CF237A#black`
The last `'` is missing and the values of the perf data are not evaluated. Therefore no graph is generated.

**Comment by lpinsivy** [comment]
With the following environment, everything works:
* Centreon Web 2.8.17
* Centreon Broker 3.0.11
* Centreon Engine 1.7.1

<img width="730" alt="screenshot at janv 26 11-25-47" src="https://user-images.githubusercontent.com/3351916/35435633-c38d64e6-028b-11e8-9ac2-0266df939008.png">
<img width="1258" alt="screenshot at janv 26 11-38-31" src="https://user-images.githubusercontent.com/3351916/35436118-75957704-028d-11e8-888b-b39ee77d40b7.png">

Please upgrade your platform

**Comment by masgo** [comment]
@lpinsivy Hi, it does not work for me with 

- Centreon Web 2.8.17
- Centreon Broker 3.0.11
- **Centreon Engine 1.8.1**

**Comment by lpinsivy** [comment]
Hi @masgo ,

Can you make a print screen of the service details page to see performance data?
