### ISSUE TITLE
[2.7.x] Save a service template not linked to another template take a long time

### ISSUE THREAD

**Issue by querwin** [centreon/centreon#4748]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.7

**OS**:  CentOS-6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare

**Steps to reproduce the issue:**
1. Create a service template
2. Not link it to another service template
3. Save
4. It takes a lot of times.

**Additional information you think important (e.g. issue happens only occasionally):**

You can try to do this but linked the service template to another and the problem is not here

**Comment by julienmathis** [comment]
Can't reproduce on 2.8.x.
