### ISSUE TITLE
You are not allowed to reach this page - URL not good - not commit 38cbfab

### ISSUE THREAD

**Issue by parrotga** [centreon/centreon#4750]
Hi

Centreon 2.6.1
Widget service-monitoring 1.4.2

since i upgrade the widget to 1.4.2 i can't see the graph, i have a blank/broken icon with a "You are not allowed to reach this page"

URL is not good, not exactly same problem than 
https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/commit/38cbfab2a6347ab1afd3807545b87b88ccc94cf7

https://monitoring.parrot.biz/main.php?p=4&mode=0&svc_id=xxxxxx;Ping-VPN
but in widget it search for 
https://monitoring.parrot.biz/main.php?p=204&mode=0&svc_id=xxxxxx;Ping-VPN

thanks for your help
regards

**Comment by julienmathis** [comment]
Hello, 

You widget is only compatible with Centreon 2.7. Please downgrade your widget.

Best regards
