### ISSUE TITLE
Options missing in notification tab

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#4752]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 
2.7.7
**Centreon Engine version**: 
1.5.1
**Centreon Broker version**: 
2.11.5
**OS**: 
6.8
**Additional environment details (AWS, VirtualBox, physical, etc.):**

One option is missing on all form for service, service template, host and host template in notifiaction tab.
Like describe in the help of filter part if we don't select "none", engine will send notification for everything but "none" options doesn't existe.

![issue](https://cloud.githubusercontent.com/assets/11980015/19526414/af072176-9624-11e6-976c-7b93c52e5db9.PNG)

**Comment by BenoitPoulet** [comment]
Isn't it the same as «notification enabled = Yes» ?
Just wondering.
