### ISSUE TITLE
[2.4.4] Centreon Web UI bug after update from 2.1.13 to 2.4.4 version

### ISSUE THREAD

**Issue by maraev** [centreon/centreon#4753]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 
2.4.4
**Centreon Engine version**: 
2.4.4
**Centreon Broker version**: 
-- IDO2DB
**OS**: 
OS RHEL6x. 
**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical
**Steps to reproduce the issue:**
After Updating Centreon from 2.1.13 to 2.3.9 I see a strange bug in the leftMenu Centreon Web UI (Dublicate "Downtime" item). After updating from 2.3.9 to 2.4.4 Categories item is dublicated as well. 
(see the picture below)
How can I fix that? And what is going wrong?
1. ./install -u 
Further the Next all the time
**Describe the results you received:**
Dublicate some item in the left vertical menu 
![cent_err_1](https://cloud.githubusercontent.com/assets/3273410/19552685/909ad59e-96b9-11e6-87c7-1b3af331954e.jpg)

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
hi,

I suppose you click twice on "Next" buttun during upgrade process.

So those version is not more supported but you can remove duplication from "topology" table from "centreon" database.
