### ISSUE TITLE
[Massive Change] Two "update mode" lines for service groups causing annoying behaviour

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4756]
---
## BUG REPORT INFORMATION

**Centreon Web version**: 2.7.7

**Centreon Engine version**: Not relevant

**Centreon Broker version**: Not relevant

**OS**: CES 3.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Configuration > Services 
2. Select x services and use "massive change action"
3. Go to relation tab, for service groups you have two lines to specify the update mode

**Describe the results you received:**
Massive change is not applied if you do not select "replacement" on the two lines

**Describe the results you expected:**
Only one line allowing to do the change correctly

**Additional information you think important (e.g. issue happens only occasionally):**

Thanks !

**Comment by Sims24** [comment]
Screenshot of the problem 

![image](https://cloud.githubusercontent.com/assets/12429463/19676357/38d75146-9a94-11e6-8066-177a9146eb16.png)

**Comment by julienmathis** [comment]
Already fixed in 2.8.x

**Comment by Sims24** [comment]
Thanks @julienmathis . Is it possible to apply patch on 2.7.x branch ?
