### ISSUE TITLE
Trying to implement SSO authentication

### ISSUE THREAD

**Issue by samuel4x4** [centreon/centreon#4757]
**Centreon Web version:** 
centreon-web-2.8.0-0.3.beta2.el6.noarch
**Centreon Engine version:** 
centreon-engine-1.6.0-1472141297.6301589.el6.x86_64
**Centreon Broker version:** 
centreon-broker-core-3.0.0-1472213579.939db56.el6.x86_64
**OS:** 
Red Hat Enterprise Linux Server release 6.8 (Santiago)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack instance

**Steps to reproduce the issue:**
1. Enable SSO Mixed from Administration > Parameters > Centreon UI
2. In our app hosted in a different domain, we have a html form that do a POST to the Centreon server
3. Submit that form

**Describe the results you received:**
SSO Authentication fail, the user is redirected to the login page

**Describe the results you expected:**
The received result is alright, SSO_AUTH_HEADER is not present, you can't attach http headers to a form.

**Additional information you think important (e.g. issue happens only occasionally):**
How can we attach the SSO_AUTH_HEADER header to the form POST submit? 

If we try 

curl -X POST -H "SSO_AUTH_HEADER: username" -H "Cache-Control: no-cache" –H CENTREON_HOST

we succeed to authenticate, but because we're not in a web browser, the session cookie is not set and you're not authenticated in the Centreon web application. 

Can you please give us an example of SSO implementation? Thanks

**Comment by samuel4x4** [comment]
#4746 @julienmathis, maybe you can help. Thanks!

**Comment by ganoze** [comment]
What do you want to do precisely ? Are you trying to use Centreon through another application ? Feel free to add additional architecture information.

Also you might be interested in looking for Centreon API or Centreon Clapi.

**Comment by samuel4x4** [comment]
Hi @ganoze ,

My app manage projects monitored by multiple monitoring tools (including Centreon). When the user choose to motorize a new project with Centreon, we communicate with Centreon API and sent there everything needed by Centreon in order to let the user to authenticate to the its GUI and to see logs from his projects. 

Then, from our app GUI, when the user see the list of his projects, he should can click on a project monitored by Centreon and go directly in the Centreon GUI, being automatically authenticated there. 

We're trying to accomplish this thru Centreon SSO. We can authenticate this way

curl -X POST -H "SSO_AUTH_HEADER: username" -H "Cache-Control: no-cache" –H CENTREON_HOST

but from the web browser we can't do a POST with headers. Also, knowing that we don't share the same web domain with the Centreon GUI, we can't set a cookie in the browser in order to be authenticated in Centreon.

We opened this issue in order to ask you if you have some SSO implementation examples. I explained you what we're trying to do. Maybe you can advice us, or maybe we need a different SSO implementation.

Thank you!

**Comment by ganoze** [comment]
It seems that Centreon's implementation of SSO will not suit your needs (https://documentation.centreon.com/docs/centreon/en/2.8.x/howto/sso.html).

However, for your use case, you might be interested in looking for Centreon autologin feature.

**Comment by samuel4x4** [comment]
Hi @ganoze,

Please check these issues #4874 and #4875. Even that, the autologin is a working option now, but how secure is it? Do you have any supplementary security suggestions?

**Comment by ganoze** [comment]
As replied in the other threads, the autologin feature should work again in the upcoming 2.8.3 release. Autologin is not much less secure than password-based authentication.

Unfortunately I cannot advise you for additional security tips. However if you have any suggestion, feel free to let me know and they'll be added to the documentation. Or better, send us a PR ;-)
