### ISSUE TITLE
SSO Mixed is handled as SSO Only

### ISSUE THREAD

**Issue by calofiremil** [centreon/centreon#4758]
---
## BUG REPORT INFORMATION

**Centreon Web version**: centreon-web-2.8.0-0.3.beta2.el6.noarch
**Centreon Engine version**: centreon-engine-1.6.0-1472141297.6301589.el6.x86_64
**Centreon Broker version**: centreon-broker-core-3.0.0-1472213579.939db56.el6.x86_64
**OS**: Red Hat Enterprise Linux Server release 6.8 (Santiago)
**Additional environment details (AWS, VirtualBox, physical, etc.):** Openstack instance

**Steps to reproduce the issue:**
1. Enable SSO authentication
2. Enable SSO Mixed 
3. Add my local IP into "SSO trusted client addresses" 
4. Open browser and try a normal form login to Centreon

**Describe the results you received:**
Your credentials are incorrect.

**Describe the results you expected:**
Login to Centreon successfully.

**Additional information you think important (e.g. issue happens only occasionally):**
1. From what i understand if check "SSO Mixed" i should be able to login to Centreon via browser form and via SSO.
2. If i remove my ip from  "SSO trusted client addresses" i can do a login using browser.

**Comment by calofiremil** [comment]
May be related to [#4757](https://github.com/centreon/centreon/issues/4757) and  [#4746](https://github.com/centreon/centreon/issues/4746)

**Comment by kduret** [comment]
SSO trusted clients must be the IP address of the SSO handler, not your local IP.

Can you retry and let me know if it works please ?

**Comment by samuel4x4** [comment]
Hi @kduret,

What @calofiremil tried to do is to authenticate to Centreon from his local computer where our app is installed. In this case I think it's about his local IP. 

When the SSO handler IP is added in the Centreon configuration with the "SSO mixed" option enabled, we expect to still have both options working, actually the basic auth with username and password form is not working anymore.

Thanks for your help!
