### ISSUE TITLE
[Centreon 2.7.7] Periodically Unreachable Host Status on Poller

### ISSUE THREAD

**Issue by fletcher02** [centreon/centreon#4761]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.7.7

**Centreon Engine version CENTRAL **: 1.5.1
**Centreon Engine version POLLER **: 1.5.1

**Centreon Broker version CENTRAL **: 2.11.5
**Centreon Broker version POLLER **: 2.11.5

**OS**: CentOS 6.8 Final
**OS POLLER**: CentOS 6.8 Final

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare ESXi 6.0

Actually, i have one host on my poller, for test. 

This host on poller is intentionally set in OK or DOWN status. But if i leave it in OK or DOWN status for a while, he switch to UNREACHABLE status and re-switch to OK mode, without any notifications (notifications are configured for OK,DOWN and UNREACHABLE and it's OK for DOWN and OK status).

No informations in /var/log/centreon-engine/centengine.log & centengine.debug (after activation debug mode in centengine config), /var/log/messages.

Did you have any ideas ? 

Thanks !

**Comment by Sims24** [comment]
Hi @fletcher02 

Please check time synchronization between your two servers. This is probably the centreon-broker instance parameter that is causing this. 

Let us know.

**Comment by fletcher02** [comment]
Hi @Sims24 

Thanks for reply to my issue.

I synchronized my servers with NTP, restart servers but after a while .... My host on poller switch from OK or DOWN status to UNREACHABLE and ...re-switch to OK or DOWN status without any notifications. 

Time on both servers are OK, NTP server on CENTRAL and POLLER configured on CENTRAL.

**Comment by Sims24** [comment]
Hi @fletcher02 

Could you upload your debug files ?

**Comment by fletcher02** [comment]
[debugfiles.zip](https://github.com/centreon/centreon/files/566493/debugfiles.zip)

HOST on the POLLER called RENNESMET23.

Thanks you

**Comment by Sims24** [comment]
@fletcher02 

Thanks for the files, looks like your issues match lines like this one in poller-module.log file : 

[1478080850] [0x285b340] error:   TCP: could not connect to 192.168.1.61:5669: Host unreachable
[1478080881] [0x285b340] error:   TCP: could not connect to 192.168.1.61:5669: Host unreachable

This is the problem I mentionned, your network or central broker should be unstable and then trigger some failover mechanism. 

If your connection doesn't come back in the next five minutes you have the issue. I convert some timestamp and this morning the outage lasts during 20 minutes, this explain the unreachable state.

**Comment by fletcher02** [comment]
Oh ... it's my fault, i left this log messages. When i restart my two servers, i have troubles with iptables so, time to recover a correct situation, log message like "could not connect to 192.168.1.61:5669" happen. Nota : For the test, iptables is OFF, on two servers.

When i write this line, my host is in UNREACHABLE status but, if i check connection between two servers, first by netstat -pan |grep 5669 : 
![image](https://cloud.githubusercontent.com/assets/23172150/19932778/80ea905a-a111-11e6-84ef-834e2550db8d.png)

My poller is correctly connect to my central. But my host is in UNREACHABLE : 

![image](https://cloud.githubusercontent.com/assets/23172150/19932972/31e8c732-a112-11e6-95e5-103ea3473f23.png)

I'll check my network connections and see if I have better.

Thanks you.

**Comment by julienmathis** [comment]
Hello, 

Do you have news ?

Thanks

**Comment by fletcher02** [comment]
Hello,

Unfortunately, no. My two hosts seems to be correctly synchronized but always the same symptoms. My only host on poller switch to UNREACHABLE status to OK and re-switch, etc ... 

Note that when I reload the configuration, the host gets a proper status, which makes me think that this is certainly linked to the Broker.

I keep looking.
Thanks for your following along.

**Comment by julienmathis** [comment]
Are you sure that you don't have another poller with the same host running in // ?

**Comment by fletcher02** [comment]
Hello,

Yes i'm absolutely sure. 

I created another host on the same poller and i'm sure that this host never was monitor and same symptoms, periodicaly switch to UNREACHABLE status for two hosts. 

In fact, I think we can say that periodically, the poller is unreachable and i don't know why....

**Comment by Sims24** [comment]
Hi @fletcher02 ,

Any remote session possible ?

**Comment by fletcher02** [comment]
Hi @Sims24,

Unfortunately no, but i can send configuration files without problems. 

For informations, CENTRAL

**Comment by lpinsivy** [comment]
Hi,

When problem appear, can you make a dump of centreon_storage.instances and centreon_storage.hosts tables ?

Regards,

**Comment by fletcher02** [comment]
After update to Centreon-Web 2.8.2 - Centreon Broker 3.0.2 - Centreon Engine 1.6.2, centreon works fine !
