### ISSUE TITLE
Notification late after freshness check

### ISSUE THREAD

**Issue by jbenicky** [centreon/centreon#4762]
I have passive check with freshness check after 3600s. After 1 hour status changes to warning. But notification is send after another hour.

![2016-10-31 16_48_23-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/13909031/19861109/a0f68b92-9f8b-11e6-82c5-f0188abb9dcb.png)

Configuration of service:
![2016-10-31 17_05_42-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/13909031/19861302/5287400e-9f8c-11e6-90d3-dc71f7fad0f2.png)

![2016-10-31 17_06_36-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/13909031/19861325/6b87059e-9f8c-11e6-99de-cee845b9d634.png)

![2016-10-31 17_07_03-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/13909031/19861335/78101882-9f8c-11e6-8fe7-3a80f4a25711.png)

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.6.6

**Centreon Engine version**: 1.4.15

**Centreon Broker version**:  2.10.2

**OS**: CentOS

**Additional environment details (AWS, VirtualBox, physical, etc.):** Vmware

**Steps to reproduce the issue:**
1. set passive check with freshness check after 3600 second, 
2. wait 1 hour, 
3. after another 1 hour notification is send.

**Describe the results you expected:**
I expect notification to be send right after changing status.

**Additional information you think important (e.g. issue happens only occasionally):**
When changing from warning to OK status, notification is send immediately.

**Comment by Sims24** [comment]
Hi @jbenicky ,

Please set "is volatile" option to yes and also, try to put 0 in notification interval field. 

Regards,

Simon

**Comment by julienmathis** [comment]
Can I close this ticket ?

**Comment by jbenicky** [comment]
Setting volatile didn't help to me, but you can close it. I've solved checking in different way.
