### ISSUE TITLE
Widgets Rotation do a important memory leaks

### ISSUE THREAD

**Issue by Manu1400** [centreon/centreon#4764]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: Linux

**Additional environment details (AWS, VirtualBox, physical, etc.):** physical

**Steps to reproduce the issue:**
1. On Centreon, install the Map 4 widget
2. Go to Custom view page (with Chrome or Firefox)
3. In this page, add two tabs : a tab with (1-n) Map 4 widget(s) and a empty tab
4. Activate rotation of widgets tabs of Centreon, in Centreon. i.e : rotate after 5 seconds.
5. Monitoring the memory of the browser used.
5. Wait 2 hours
6. Warning : Don't look the memory of the browser tab. Look the memory of the browser.

**Describe the results you received:** Tab crashed (because too many memory used)

**Describe the results you expected:** No memory leak when use the rotation feature with a complexe widget (ie : Map 4 widget)

**Additional information you think important (e.g. issue happens only occasionally):**
Difficult to "fix" that : Rotate of tab feature is deleted on jQuery UI.

Idea : Rewrite rotate.

**Comment by benoitb21** [comment]
Hello, 

Have you news concerning this pb?
To add, me, since many updates, It's impossible to click on Save in a map widget. I have this message: Error during save, please retry".

Thanks.
Centreon 2.8.15
Map 4.2.3

**Comment by lpinsivy** [comment]
@benoitb21 can you open a Centreon support ticket for Centreon Map widget issue please.

**Comment by benoitb21** [comment]
Hello.

The ticket (00031124) was opened at the 04 December 2017. But not solutions for the moment.

Regards

**Comment by JoaoAlecrim** [comment]
Hello,

We upgraded recently to version 2.8.26 and we are facing a huge memory leak on every browser, when rotating Custom Views. It's only expected to be corrected in v18.10?

Thank you.

**Comment by sc979** [comment]
@JoaoAlecrim ,
Your issue was closed because, the custom views' memory leak have been fixed on the 18.10.x
Regards,
sc979
