### ISSUE TITLE
preformance data not correctly interpreted

### ISSUE THREAD

**Issue by guillaumechardin** [centreon/centreon#4765]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  Centreon 2.7.6

**Centreon Engine version**: Centreon Engine 1.5.1

**Centreon Broker version**: Centreon Broker 2.11.5

**OS**: CentOS release 6.8 (Final) installed via CES DVD

**Additional environment details (AWS, VirtualBox, physical, etc.):** 1central, 2 pollers all using same CES release and last updates. Runing on vmware ESXi 5.5

**Steps to reproduce the issue:**
I'm using nrds to populate monitoring informations from remotes devices.
Performance data are sent like that : 
    'disk in use'=1826559.1MB; 'disk usage'=91.68%;80;90; 'disk total'=1992292.0MB;
RRD graph  is not render correctly. There are some issue with unit interpretation (see screeshot, 1MB instead 1826559MB)

![2016-11-03 09_45_46-clipboard](https://cloud.githubusercontent.com/assets/17491271/19959969/57c2ceec-a1aa-11e6-97c9-315e0972edda.png)

Tell me if more information needed.
G. CHARDIN

**Comment by leoncx** [comment]
Hello,

The chart seen good. The unit of the axis is MB and the line is draw at 1.8 M (million) who is the same of 1826559.
The unit look like the short name of human readable number.

Regards

**Comment by guillaumechardin** [comment]
Thanks, closing thread.
