### ISSUE TITLE
Icon status enabled in services categories is red whereas in hosts categories she is green 

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#4767]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.7
**Centreon Engine version**: 
1.5.1
**Centreon Broker version**: 
2.11.5
**OS**: 
Centos 6.8
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
![host categorie](https://cloud.githubusercontent.com/assets/16045498/20002738/a0925f56-a282-11e6-8091-f2da636b440d.jpg)
![service categorie](https://cloud.githubusercontent.com/assets/16045498/20002741/a3bee9f6-a282-11e6-8d00-6bf6c1866338.jpg)

2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Already fixed in the next version.
