### ISSUE TITLE
Graphs of disabled services are display for host in Performance => graph view when select all

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon#4775]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 1.6.1

**Centreon Broker version**: 3.0.1

**OS**: Centos 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Go to Monitoring => Performances => Graphs
2.  Select one host in filter by host
3. Click on "Charts" => "Select all"

**Describe the results you received:**
All service graphs are displayed even for those who are empty because the service is disabled

**Describe the results you expected:**
Only active service are displayed by default. An option to display disabled service (in case of the service is disable in the period for example)

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
refs #4842
