### ISSUE TITLE
[KB] add an action link to delete a wiki page

### ISSUE THREAD

**Issue by Singman33** [centreon/centreon#4776]
When you have a wiki page for a service or a host in KB module, you got 3 actions links :

- View wiki page
- Edit wiki page
- View history

Could you add a link to remove the page in wiki ?
Actually, you should go on the wiki page and remove it (if you have the rights to do that).

Thanks.
_PS : could not find the KB module on Github so posted here_

**Comment by lpinsivy** [comment]
Thank you for this idea.

ps: now KB is integrated in Centreon web so you post your idea in correct place ;)

**Comment by kduret** [comment]
this feature has been added here : 75844ad1aa330fcf5e1804f32419a0b28eb5da8a

**Comment by lpinsivy** [comment]
@kduret can you commit on master branch too ?
