### ISSUE TITLE
[KB] Error in link generation, bad reference to a class

### ISSUE THREAD

**Issue by Singman33** [centreon/centreon#4778]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.7-4.el6

**Centreon Engine version**: 1.5.1-3.el6

**Centreon Broker version**: 2.11.5-2.el6

**OS**: CentOS release 6.8

**Steps to reproduce the issue:**
1. create a wiki page via the action link "Create wiki page" for a service and validate it
2. wait for the cron job to run (5 minutes)
3. check the URL in the service config

**Describe the results you received:**
Nothing.
Checking /var/log/centreon/centreon-knowledge.log

> PHP Warning:  require_once(/usr/share/centreon/**www//www**/class/centreonLog.class.php): failed to open stream: No such file or directory in /usr/share/centreon/www/class/centreonDB.class.php on line 84
> PHP Fatal error:  require_once(): Failed opening required '/usr/share/centreon/**www//www**/class/centreonLog.class.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/share/centreon/www/class/centreonDB.class.php on line 84

**Describe the results you expected:**
A link in the URL field of the service

**Additional information you think important (e.g. issue happens only occasionally):**
Maybe a misconfiguration somewhere, but everything was upgraded with scripts, no manual configuration.

**Comment by lpinsivy** [comment]
Hi,

Which version of Centreon KB do you use ?

Regards,

**Comment by Singman33** [comment]
2.1.0

**Comment by cmeschin** [comment]
Hi,
this pb is solved in 2.8.2.
No more errors in log and Links were created on hosts, host_templates, services and service_templates

**Comment by Singman33** [comment]
Ok, I'm closing that issue.
