### ISSUE TITLE
Centreon IMP with Proxy server

### ISSUE THREAD

**Issue by Gilum** [centreon/centreon#4779]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 1.6.1

**Centreon Broker version**: 3

**OS**: Centos 6/7

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM with proxy only

**Steps to reproduce the issue:**
1. yum install centreon-pp-manager & enable extension
2. sign in Centreon IMP

**Describe the results you received:**
Fail

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**
Where is configure the proxy????

**Comment by Gilum** [comment]
Thank julien and congratulation !

**Comment by julienmathis** [comment]
Thanks ! :)

**Comment by lpinsivy** [comment]
Hi,

With type of proxy do you use ? 
Regular HTTP/HTTPS proxy with URL and port ? SOCKS v4/v5 host ? other ?

Regards,

**Comment by Gilum** [comment]
Basic http/https proxy, no auth, port 8080

**Comment by Gilum** [comment]
After the update to 2.8.2, the HTTP proxy does not work

Login error : Cannot access to IMP portal
Error Licence manager log : 2017-01-02 11:26|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance : Page not found
Proxy protocol : HTTP
Proxy URL : nproxad.xxxxxx.com
Proxy port : 8080

Test with curl : 
curl -I https://api.imp.centreon.com/api/license-manager/instance
HTTP/1.1 200 Connection established
Set-Cookie: BIGipServerynproxad_8080_pool=rd1o00000000000000000000ffff0a00cf66o8080; path=/

HTTP/1.1 404 Not Found
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods: GET
Access-Control-Allow-Methods: POST
Access-Control-Allow-Methods: PATCH
Access-Control-Allow-Origin: *
Content-Length: 44
Content-Type: application/json; charset=utf-8
Date: Mon, 02 Jan 2017 10:29:22 GMT
ETag: W/"2c-hfpdyo62anem8s/49Aeidw"
X-Powered-By: Express
Connection: keep-alive
