### ISSUE TITLE
[Centreon 2.7.8] Centreon Web - Last State Change in list problems.

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon#4783]
Hi guys!
Prompt as it is possible in the pages of "Monitoring > Status Details > Servises" (the same goes for "Monitoring  >  Status Details  >  Hosts") instead of "_Last Check_" get "_Last State Change_"? Maybe this is where you can change, but I can not find where. Maybe this information can be placed in "Host Informations"? Or are you to tell me where my case to change to get this result.

**Centreon Web version**: 2.7.8
**Centreon Engine version**: 1.5.1
**Centreon Broker version**:  2.11.5
**OS**: Oracle Linux Server release 6.8

**Steps to reproduce the issue: none**
**Describe the results you expected: Get on the list "Last State Change"**

Thank you!

**Comment by BenoitPoulet** [comment]
Hello,

This change is a new feature/behavior of Centreon 2.8, not 2.7.

**Comment by maksimatveev** [comment]
@BenoitPoulet Thanks for the reply. When do you plan to release version 2.8?

**Comment by BenoitPoulet** [comment]
It's already out : https://download.centreon.com/

**Comment by maksimatveev** [comment]
@BenoitPoulet repositories probably not:
```
[root@rnd-oms-centreon ~]# yum update
Загружены модули: security, ulninfo
Подготовка к обновлению
ces-standard                                                                                                           |  951 B     00:00     
ces-standard-deps                                                                                                      |  951 B     00:00     
ces-standard-deps-noarch                                                                                               |  951 B     00:00     
ces-standard-noarch                                                                                                    |  951 B     00:00     
public_ol6_UEKR4                                                                                                       | 1.2 kB     00:00     
public_ol6_UEKR4/primary                                                                                               | 9.5 MB     00:00     
public_ol6_UEKR4                                                                                                                      241/241
public_ol6_latest                                                                                                      | 1.4 kB     00:00     
Разрешение зависимостей
--> Проверка сценария
---> Package kernel-uek.x86_64 0:4.1.12-61.1.19.el6uek will be для установки
---> Package kernel-uek-doc.noarch 0:4.1.12-61.1.17.el6uek will be для обновления
---> Package kernel-uek-doc.noarch 0:4.1.12-61.1.19.el6uek will be an update
---> Package kernel-uek-firmware.noarch 0:4.1.12-61.1.19.el6uek will be для установки
--> Проверка зависимостей окончена
--> Проверка сценария
---> Package kernel-uek.x86_64 0:4.1.12-61.1.17.el6uek will be для удаления
---> Package kernel-uek-firmware.noarch 0:4.1.12-61.1.17.el6uek will be для удаления
--> Проверка зависимостей окончена
```

**Comment by maksimatveev** [comment]
@BenoitPoulet I understand you want to change the repository for the update?

**Comment by maksimatveev** [comment]
@BenoitPoulet https://documentation.centreon.com/docs/centreon/en/2.8.x/upgrade/from_packages.html
If to follow these instructions problems with version 2.7.8 does not arise?

**Comment by maksimatveev** [comment]
@BenoitPoulet Updated, what's next? I do not see the items in the menu where you can change the columns in the list.

**Comment by BenoitPoulet** [comment]
Hoooo no, i saw i miss read :|

i read "last check in place of "Last State Change". Sorry!

So it's not available in 2.8, and you enhancement request is still valid.

**Comment by julienmathis** [comment]
hello @maksimatveev 

Can you give me a sreenshot ? I don't find that in the code ...

**Comment by maksimatveev** [comment]
@julienmathis Hello! The list has a column "Last Check". I would like to get as it is instead a column "Last State Change", because it is easier to focus on the time of change of status.
![13 54 36 01-12-2016](https://cloud.githubusercontent.com/assets/15804154/20791443/234c58e2-b7ce-11e6-99b8-c6238f8b8516.png)
Maybe you can send an example of how this can be achieved? I would be very grateful to you =)

**Comment by julienmathis** [comment]
The column duration is not enough for you ? You want the date ? not the duration since the service is in this state ?

**Comment by maksimatveev** [comment]
@julienmathis Yes, for me it is important to be seen time and date of the status change. duration only allows us to estimate the elapsed time after the change. I understand that for the sake of this you might not wake that do not change, but can you tell me how to change something in the query?

**Comment by julienmathis** [comment]
You have this value in the popin. Is this not enough ? 

We just change the display in order to reduce the size of the column. But you have this data in the popup if you want.

**Comment by maksimatveev** [comment]
@julienmathis Yes, you're right - the data is in the pop-up message. like a similar display in zabbix
![2016-12-04 09 10 07](https://cloud.githubusercontent.com/assets/15804154/20864475/31a5afba-ba03-11e6-8966-4d2df238ec2e.png)
.

**Comment by julienmathis** [comment]
So is it enough for you ? Sorry I can't understand the listing in Russian :) 

Can I close this issue ?

**Comment by maksimatveev** [comment]
@julienmathis I'll close =)
