### ISSUE TITLE
[resolved] centreon web does not take changes

### ISSUE THREAD

**Issue by atlante77** [centreon/centreon#4785]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**centreon-web-2.7.7**: 

**centreon-engine-1.5.1**: 

**centreon-broker-2.11.5**: 

**UBUNTU 14.04.1**: 

**PHYSICAL SERVER:**

**nagios-plugins-2.1.3**

**centreon-connector-1.1.2**

**centreon-clib-1.4.2**
**Steps to reproduce the issue:**
1. Add/remove host in host configuration
2. Apply config ( Config -> Pollers -> Generate config, Run moni, move export, restart Monitoring) 
3. 

**Describe the results you received:**
Centreon web doesn't update number of hosts and services...

**Describe the results you expected:**
A web page with the good number of hosts & services

**Additional information you think important (e.g. issue happens only occasionally):**
If i do "/etc/init.d/centengine restart", the web page refresh with good informations.

**Comment by atlante77** [comment]
Hello,

I found the problem, ansible has removed centreon sudoers file.

Regards,

Atlante

**Comment by julienmathis** [comment]
Thanks !
