### ISSUE TITLE
widget lost in el7 repository

### ISSUE THREAD

**Issue by Gilum** [centreon/centreon#4789]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: Centos 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Compare centreon-widget*
2. in  http://yum.centreon.com/standard/3.4/el6/stable/noarch/RPMS/ 
3. and http://yum.centreon.com/standard/3.4/el7/stable/noarch/RPMS/ 

**Describe the results you received:**
11 rpm widget in el6 repository
1 rpm widget in el7 repository

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Widgets will be soon available :)

**Comment by julienmathis** [comment]
Hello, 

All widgets are now available in EL7 repository ! 

Have a nice day :)
