### ISSUE TITLE
Performance historical data lost : Service ID are not the same after being redeployed (with same name)

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#4795]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 1.6.1

**Centreon Broker version**: 3.0.1

**OS**: CentOS 6

**Steps to reproduce the issue:**
1. Have an host-1 based on a host-template-1. That host-template-1 has a service called "Service-1" with _used_ and _size_ metrics
2. Change the template on host-1 to host-template-2. That host-template-2 has a service called "Service-1" with _used_, _size_, _foo_,... metrics
3. Export configuration & restart.

**Describe the results you received:**
The Service-1 has a new service_id so, historical data are lost on the graph (and link to that data are also lost in DB I guess)

**Describe the results you expected:**
Because the name of the service is still the same, Service_ID should not have been changed and historical performance data should still be linked to the service.

**Comment by BenoitPoulet** [comment]
Hummm, if the the service became completely different because of the new template. (no perfdata, or perfdata in %, ....). 
What to do ?

**Comment by Sims24** [comment]
Hi, 

Linked with https://github.com/centreon/centreon/issues/4780 . 

As discussed, my first thought would be the same as Benoit. Most of the time we change template to change something, so the risk is to keep a lot of dirty / unused metrics within databases and rrds.

**Comment by lpinsivy** [comment]
Hi,

If you change a host's template to another one, Centreon will remove all services linked to previous template to create new services linked to new one. So the news services will have new ID.

It's impossible for Centreon to make a comparison between old and new services to determine if data can be kept.

Regards,
