### ISSUE TITLE
Centreon 2.8 installation stuck at Partitioning database tables on RHEL 7

### ISSUE THREAD

**Issue by jason354007** [centreon/centreon#4799]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Centreon 2.8.1

**Centreon Engine version**: Centreon Engine 1.6.1

**Centreon Broker version**: 3.0.1-1

**OS**: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical boxes

**Steps to reproduce the issue:**
1. Tried to install centreon from the http://yum.centreon.com/standard/3.4/el7/stable/ on a fresh RHEL 7 machine.
2.  Installation went fine but on the GUI it is stuck at Partitlioning tables.

**Describe the results you received:**
Centreon setup is  stuck at Partitlioning tables.

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by jason354007** [comment]
Is it because that mariadb is from standard rehdat repo and not the centreon repo ?

I have added the below parameters manually to my.cnf:

open_files_limit=32000
innodb_file_per_table=1


Still it is stuck at partitioning tables.

**Comment by julienmathis** [comment]
Which version of MySQL do you use ?

**Comment by jason354007** [comment]
Server version: 5.5.52-MariaDB MariaDB Server. This is installed from the RHEL 7 repo.

**Comment by Sims24** [comment]
Hi @jason354007 

Welcome in systemd world :)  

Take a look at :
https://ma.ttias.be/increase-open-files-limit-in-mariadb-on-centos-7-with-systemd/

That will fix your problem.

**Comment by jason354007** [comment]
Hi @Sims24 

Thanks for your feedback.

I already tried this but no luck so far...

Also, removed everything and reinstalled again using below:

yum install centreon-base-config-centreon-engine centreon

**Comment by Sims24** [comment]
Could you copy/paste result of : 

`ls -lrt /var/lib/mysql/centreon_storage/*`

thx

**Comment by jason354007** [comment]
The issue seems to be fixed now after restarting mariadb but this is really wierd that the parameters were set and mariadb was restarted before beginning the installation. After it got stuck  at the 7th step, restarting mariadb fixed the issue again.

Is the 8th step i.e. the final screen which shows that you have successfully installed centreon  no longer working as clicking on finish does not work any more ?

**Comment by julienmathis** [comment]
Strange your problem. We use centreon 10.1. -> http://yum.centreon.com/standard/3.4/el7/stable/x86_64/RPMS/

I check, and all information are in the documentation : https://documentation.centreon.com/docs/centreon/en/2.8.x/administration_guide/partitioning/index.html

**Comment by jason354007** [comment]
This issue can be closed now.

**Comment by zopar** [comment]
Hi 
I had the same problem the solution is in the installConfigurationDb.php
If your operating system is based on systemd (CentOS 7, Debian Jessie), add LimitNOFILE=32000 value on the service file /usr/lib/systemd/system/mariadb.service and reload systemd (systemctl daemon-reload).'

@developpers: please check why this file do not put the messages on webbrowser, probably is related to te  exitProcess(PROCESS_ID, 1, _
