### ISSUE TITLE
[2.8.1] Metrics hidden but present on graph

### ISSUE THREAD

**Issue by AlexisTEXIER** [centreon/centreon#4802]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 1.6.1

**Centreon Broker version**: 3.0.1

**OS**: CentOS 6.8 (CES 3.0 updradded to 3.4)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM on ESXi 6.0

**Steps to reproduce the issue:**
1. Go to Administration -> Parameters -> Performance Management/Data
2. Select a service
3. select metric
4. action -> hide graphs of selected service
5. Go to Monitoring -> Performances -> Graphs
6. select same service
7. "hidden metrics" are still visible

**Comment by julienmathis** [comment]
Hello, 

Sorry, we can't reproduce your problem. Possible to send screenshots ?

**Comment by AlexisTEXIER** [comment]
Sorry, but I revert my VM to the last snapshot before upgrade.

**Comment by julienmathis** [comment]
Sorry, it works for me. Please reopen this ticket is you encounter agin this problem.

Regards

**Comment by AlexisTEXIER** [comment]
Hello,

I've finally upgrade my centreon to 2.8.8.
I still have this issue.
Here is a view of the performance graph:
![image](https://user-images.githubusercontent.com/22889875/26867332-3516a20a-4b65-11e7-9fe6-2365c565e612.png)
Here is a view of the metric parameters:
![image](https://user-images.githubusercontent.com/22889875/26867406-7be04e7a-4b65-11e7-9a5d-05af416ab40c.png)
On the graph page, if I choose to export the graph as png, the metrics are well hidden.

For this service, I use virtual metrics to make sums of in and out traffic of different interfaces.

Regards
