### ISSUE TITLE
Split Componets still a choice in template 2.8.1

### ISSUE THREAD

**Issue by Notrik** [centreon/centreon#4803]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.1

Split Components is still a choice in the Graph template but not working and the feature was sadly removed in 2.8.1.

**Comment by florian-asche** [comment]
a) Yes please, a split all button. 

b) And the methode now used, is not good. All metrics should be unselected on first click on a metric. I want to select the metrics i want to see in the view. I dont want to unselect 50 metrics only to view one of them. Or is there a secret function that im missing?

**Comment by leoncx** [comment]
See merge request #5006
