### ISSUE TITLE
Centreon 2.8 - check_nrpe  plugin output is "option '?' requires an argument"

### ISSUE THREAD

**Issue by jason354007** [centreon/centreon#4806]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Centreon web 2.8.1

**Centreon Engine version**:  Centreon engine 1.6.0

**Centreon Broker version**:  Centreon Broker 3.0.1

**OS**: RHEL 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Pyhsical box

**Steps to reproduce the issue:**
1.  I am trying to call a powershell script using NSclient via check_nrpe. Earlier, I was using Nagios 3.5.2 with ndoutils 2  and centreon-2.4.1 for meta-service and the frontend and it worked fine..
2. Now using the centreon engine/centreon broker ,if I call the script  from the command line of server it works fine but on the centreon web frontend, it always shows this message  

> option

 '?' requires an 

> argument

3.  Below is the screenshot of the Resources  (Configuration  >  Pollers  >  Resources)

![centreon1](https://cloud.githubusercontent.com/assets/24270691/20818367/5d01199c-b82d-11e6-86f0-f9eca1bec9a5.JPG)

I have installed NRPE  from RHEL7 repository

`yum install nagios-plugins-nrpe`

**Describe the results you received:**
check_nrpe plugin output is "option '?' requires an argument"

**Describe the results you expected:**
If I execute the  command from " Monitoring  >  Status Details  >  Services > Executed Check Command Line" using the command line ,then it gives me the desired output and not this error.

**Additional information you think important (e.g. issue happens only occasionally):**
Is the behaviour of centreon-engine  and nagios different with check_nrpe ?

The permission of check_nrpe is root:root  which is by default from a yum install.

**Comment by julienmathis** [comment]
If you execute the command line with nagios user, is it ok ?

**Comment by jason354007** [comment]
Hi @julienmathis ,

I am not sure if this is possible to run from the command line with nagios user.

As a dependency,below are the pacakges that are installed from epel repo  with "yum install centreon-base-config-centreon-engine centreon"  :

> nagios-common.x86_64 0:4.0.8-2.el7                        
> nagios-plugins.x86_64 0:2.0.3-3.el7
> nagios-plugins-icmp.x86_64 0:2.0.3-3.el7                  
> nagios-plugins-perl.x86_64 0:2.0.3-3.el7


Below is the permission for check_nrpe:
```
ls -l /usr/lib64/nagios/plugins/check_nrpe
-rwxr-xr-x 1 root root 24704 Sep 19  2015 /usr/lib64/nagios/plugins/check_nrpe
```


Cannot login with a nagios user:
```
# cat /etc/passwd|grep nagios
nagios:x:899:899::/var/spool/nagios:/sbin/nologin
```

Below are the groups that are assigned when using the centreon el7 repo:
```
 #cat /etc/group|grep nagios
apache:x:48:nagios,centreon
nagios:x:899:centreon-engine,centreon-broker,apache
centreon-broker:x:897:centreon,nagios,centreon-engine,apache
centreon-engine:x:896:centreon-broker,apache,nagios,centreon
```

**Comment by querwin** [comment]
Have you activated the enable shell option or a connector ?

**Comment by julienmathis** [comment]
This plugins don't come from epel ?

**Comment by jason354007** [comment]
The NRPE plugin is also from epel.

> Installed Packages
> Name        : nagios-plugins-nrpe
> Arch        : x86_64
> Version     : 2.15
> Release     : 7.el7
> Size        : 41 k
> Repo        : installed
> From repo   : epel
> Summary     : Provides nrpe plugin for Nagios
> URL         : http://www.nagios.org
> License     : GPLv2
> Description : Nrpe is a system daemon that will execute various Nagios plugins
>             : locally on behalf of a remote (monitoring) host that uses the
>             : check_nrpe plugin.  Various plugins that can be executed by the
>             : daemon are available at:
>             : http://sourceforge.net/projects/nagiosplug
>             :
>             : This package provides the nrpe plugin for Nagios-related applications.
> 

```
rpm -qa|grep nagios-plugins-nrpe
nagios-plugins-nrpe-2.15-7.el7.x86_64

```

**Comment by jason354007** [comment]
Hi @querwin,

This is how the command is configured:

![cent1](https://cloud.githubusercontent.com/assets/24270691/20837135/ec9b13d0-b8a2-11e6-8392-2c27d16b5bcb.jpg)


This is how I am executing it from the command line and it works fine:
```
/usr/lib64/nagios/plugins/check_nrpe -H xx.xxx.xxx.xxx -u -t 60 -c alias_check_exch_cpu -a "-server def01-xyz"

OK:CPUUtilization = 10 % for DEF01-XYZ at 02.12.2016 07:26 |'CPUUtil'=10
```


Below is the screenshot from the resource config:

![resource](https://cloud.githubusercontent.com/assets/24270691/20837301/cbc42c7c-b8a3-11e6-86ec-2c37041101f6.JPG)

**Comment by jason354007** [comment]
I compiled "nrpe-2.15.tar.gz"  using user nagios and still no luck.

```
./configure --with-nagios-user=nagios --with-nagios-group=nagios --libexecdir=/usr/lib/nagios/plugins
make
make install-plugin
```

**Comment by querwin** [comment]
Hello,

In Additional Information, I can see "SSH Connector" is activated.

You just have to leave this case blank and it will be OK

**Comment by jason354007** [comment]
Thanks. It did fixed the issue.
