### ISSUE TITLE
ARG + MACROS now show up in the configuation

### ISSUE THREAD

**Issue by zskarman** [centreon/centreon#4810]
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.1

When i Select the new command the command macros + args not visible on the UI.
Because I already setup an macro and arg as well.
This is works in 2.7.8 UI. - >2_7_8.png
![2_7_8](https://cloud.githubusercontent.com/assets/24320218/20841394/ed5e9a10-b8b3-11e6-8783-716571b57910.PNG)

URL:centreon/main.php?p=60206&o=c&service_id=xxx

![issue1](https://cloud.githubusercontent.com/assets/24320218/20841287/8dcaae22-b8b3-11e6-8299-8f79688433be.PNG)

Rgs, Zsolt

**Comment by zskarman** [comment]
Guys,

could I get any comments on that bug?

**Comment by Sims24** [comment]
Hi @zskarman , 

Could you copy/paste command definition of check_nt_cpu and check_nrpe please ?

**Comment by zskarman** [comment]
$USER1$/check_nrpe -H $HOSTADDRESS$ $ARG1$
$USER1$/check_ping -H $HOSTADDRESS$ -t $ARG1$ -w $ARG2$ -c $ARG3$

**Comment by zskarman** [comment]
I've checked again and it look the issue, is with only the ARG,
When change the command, the attached ARGs not shows in the UI.
But if I saved and back to the edit, i can see the args.

**Comment by ganoze** [comment]
This is a duplicate of #4729.
