### ISSUE TITLE
[2.8.1] Monitoring view - force check - bad external command format

### ISSUE THREAD

**Issue by Leryan** [centreon/centreon#4817]
Hi,

When forcing a check from the monitoring view, the generated centreon-engine command is bad formatted:

```
EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;centreon-centralemariadb;;1481029146
```

My host is named `centreon-centrale` and the service is `mariadb`. A semi-colon is missing.

If i go directly on the service details and click on `Re-schedule the next check for this service (forced)`, the command is well formatted:

```
EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;centreon-centrale;mariadb;1481029158
```

Edit:

```
# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)

## after upgrade from Centreon 2.8.1 to 2.8.2:
# rpm -qa|grep centreon
centreon-broker-core-3.0.3-4.el7.centos.x86_64
centreon-engine-extcommands-1.6.2-2.el7.centos.x86_64
centreon-broker-cbd-3.0.3-4.el7.centos.x86_64
centreon-2.8.2-2.el7.centos.noarch
centreon-common-2.8.2-2.el7.centos.noarch
centreon-connector-perl-1.1.2-3.el7.centos.x86_64
centreon-connector-ssh-1.1.2-3.el7.centos.x86_64
centreon-clib-1.4.2-3.el7.centos.x86_64
centreon-broker-storage-3.0.3-4.el7.centos.x86_64
centreon-plugins-2.8.2-2.el7.centos.noarch
centreon-engine-daemon-1.6.2-2.el7.centos.x86_64
centreon-engine-1.6.2-2.el7.centos.x86_64
centreon-trap-2.8.2-2.el7.centos.noarch
centreon-web-2.8.2-2.el7.centos.noarch
centreon-plugin-meta-2.8.2-2.el7.centos.noarch
centreon-license-manager-1.0.1-3.el7.centos.noarch
centreon-broker-3.0.3-4.el7.centos.x86_64
centreon-perl-libs-2.8.2-2.el7.centos.noarch
centreon-broker-cbmod-3.0.3-4.el7.centos.x86_64
centreon-base-config-centreon-engine-2.8.2-2.el7.centos.noarch
centreon-pp-manager-2.1.1-1.el7.centos.noarch
centreon-connector-1.1.2-3.el7.centos.x86_64
```

**Comment by lpinsivy** [comment]
HI,

I made a test on Centreon Web 2.8.1 and I can't reproduce your issue:

[1481210845] [1018] EXTERNAL COMMAND: SCHEDULE_SVC_CHECK;centreon-centrale;mariadb;1481210843
[1481210849] [1018] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;centreon-centrale;mariadb;1481210847

Can you clean your browser cache and retry ?

**Comment by Leryan** [comment]
The bug appears with Chrome/Chromium, not with Firefox.

JavaScript bug?

**Comment by julienmathis** [comment]
I only use Chrome. I do not encounter this problem.

**Comment by Dacchi** [comment]
I can't reproduce with Chrome or Firefox

**Comment by Leryan** [comment]
Really? I just reproduced the problem…

Chromium 55.0.2883.87 (64-bit) on ArchLinux.

I forgot to mention that i run Centreon on CentOS 7, maybe a problem from the PHP code.

**Comment by julienmathis** [comment]
There are no link with the browser. 

From which page do you aknowlegde ? Ca we have a screenshot ?

**Comment by Leryan** [comment]
![2016-12-15-164754_1366x768_scrot](https://cloud.githubusercontent.com/assets/4390126/21230808/66e32f04-c2e6-11e6-9e18-d6c35861e457.png)

In this picture i seleted two services, but it's the same with only one service.

Here is what i have in the logs:

```
[root@centreon ~]# tail -F /var/log/centreon-engine/centengine.log 
[1481794682] [45] Processing object config file '/etc/centreon-engine/connectors.cfg'
[1481794682] [45] Processing object config file '/etc/centreon-engine/meta_commands.cfg'
[1481794682] [45] Processing object config file '/etc/centreon-engine/meta_timeperiod.cfg'
[1481794682] [45] Processing object config file '/etc/centreon-engine/meta_host.cfg'
[1481794682] [45] Processing object config file '/etc/centreon-engine/meta_services.cfg'
[1481794682] [45] Reading resource file '/etc/centreon-engine/resource.cfg'
[1481794682] [45] Warning: Service 'Connexion à MySQL' on host 'centreon-centrale' has no notification time period defined!
[1481794682] [45] Warning: Service 'Serveur Web' on host 'centreon-centrale' has no notification time period defined!
[1481794682] [45] Error: Module reloading failed: could not find symbol 'nebmodule_reload': /usr/lib64/centreon-engine/externalcmd.so: undefined symbol: nebmodule_reload
[1481794682] [45] Configuration reloaded, main loop continuing.
[1481816877] [45] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;centreon-centraleConnexion à MySQL;;1481816875
[1481816877] [45] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;centreon-centraleServeur Web;;1481816875
```

**Comment by julienmathis** [comment]
You don't give your version of Centreon Web. Please git it. Thanks

**Comment by Leryan** [comment]
2.8.1, as told in the issue title.

**Comment by Leryan** [comment]
Hello,

I still have this issue with Centreon 2.8.2 (upgraded this morning). It's OK with Firefox (50.1) but not with Chromium (55.0.2883.87).

**Comment by julienmathis** [comment]
This problem cannot be linked to the browser. 

https://github.com/centreon/centreon/search?utf8=%E2%9C%93&q=SCHEDULE_FORCED_SVC_CHECK

It's only on PHP that the problem can be located. 

Can you check that www/include/monitoring/external_cmd/functions.php  and www/include/monitoring/external_cmd/functionsPopup.php are in the last versions ?

Thanks

**Comment by Leryan** [comment]
I upgraded to Centreon 2.8.2 with the packages from CES, i checked the packages and it's ok.

**Comment by Leryan** [comment]
Not in the browser, sure? Here is the request captured:

```
p:20201
o:svc
statusService:svc
statusFilter:
select_instance:-1
host_search:
search:
hostgroups:0
servicegroups:0
output_search:
o1:0
p:20201
l:30
checkall:on
select[centreon-centraleConnexion+%C3%A0+MySQL]:1
select[centreon-centraleServeur+Web]:1
o2:0
p:20201
l:30
cmd:4
o:
limit:30
```

**Comment by Leryan** [comment]
You can see the `select[centreon-centralConnexion]`, no `;`.

Under Firefox, i get a `;` between the host and the service.

**Comment by julienmathis** [comment]
Ho yes ! You're right... You have find something. I will install your version of FF and test that. Thanks

**Comment by Leryan** [comment]
The problem is under chromium 55.0.2883.87, and was there with version 54 too :p

I don't have any time to investigate further on this problem but I'm available for any test request.

**Comment by julienmathis** [comment]
Can't reproduce with : 

- Chromium 43
- Chrome 55.0.2883.95
- Firefox 50.1

Please try with another desktop.

**Comment by Leryan** [comment]
Ok so it works with Chrome's latest binaries but not with my Chromium.

From another computer on another distro it works well, chromium & chrome & firefox.

So… it appears to be related to ArchLinux's Chromium or libraries -_-
