### ISSUE TITLE
[2.8.1]Question about check_meta command 

### ISSUE THREAD

**Issue by jason354007** [centreon/centreon#4825]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  Centreon web 2.8.1

**Centreon Engine version**: Centreon engine 1.6.0

**Centreon Broker version**: Centreon Broker 3.0.1

**OS**:  RHEL 7.2

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical

**Steps to reproduce the issue:**
1.  While using Nagios 3,5,1 with Centreon 2.4.1, I was using the below meta service command:

```
define command{
        command_name                    check_meta
        command_line                    /usr/lib/nagios/plugins/check_meta_service -i $ARG1$ --legacy
}
```

but now with centreon engine, the check_meta command is below by default:

define command {
    command_name                   check_meta
    command_line                   $CENTREONPLUGINS$/centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --mode=metaservice --centreon-config=/etc/centreon/conf.pm --meta-id $ARG1$
}

2.  How can I use  the below check_meta with centreon engine ?

```
define command{
        command_name                    check_meta
        command_line                    /usr/lib/nagios/plugins/check_meta_service -i $ARG1$ --legacy
}

```

I edited the /etc/centreon-engine/meta_commands.cfg  but when I export the configuration file it is gone and replaced by the default one.

**Describe the results you received:**

I want to use check_meta as  

> /usr/lib/nagios/plugins/check_meta_service -i $ARG1$ --legacy

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

"check_meta" command is a command from Centreon for Meta-Services.

Since the creation of Centreon Plugins project, Centreon replace all check_centreonxxx by new plugins.

So this command is automatically generate by Centreon and you can't edit it.

Regards,

**Comment by jason354007** [comment]
Hi,

I get the output from both the commands. 


For the below command:  Meta service status is CRITICAL 
```

$ /usr/lib/centreon/plugins/centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --mode=metaservice --centreon-config=/etc/centreon/conf.pm --meta-id 54
CRITICAL: MAX - value : 100.000000 | 'a[value]'=100.00;0:2;0:1;;
```



For the below command:  Meta service status is OK.  
```
$ /usr/lib/nagios/plugins/check_meta_service -i 54 --legacy
Max - value : 100.00|value=100.00
```

Is it possible to get the same out from centreon_centreon_central.pl ?

I tried to edit meta_commands.cfg  with "check_meta_service" and it gives me the expected result on the web front. 

But when I export the configuration, the meta_commands switch to centreon_centreon_central.pl again.

**Comment by jason354007** [comment]
![centreon](https://cloud.githubusercontent.com/assets/24270691/21054968/f322f618-be2f-11e6-888f-5f013fad0746.PNG)

This is the meta service definition I am using. 

The performance data of both the services is :+1: 



> 'SVCAvail'=100

Do, I need to change the warning and critical thresholds in order to achieve the desired result  ?

Also, there is no way to use check_meta_service from now onwards ?

**Comment by julienmathis** [comment]
Why do you want to use the old plugin ?

**Comment by jason354007** [comment]
This issue can be closed. I was able to fix it using the centreon plugins by setting up the thresholds.

**Comment by julienmathis** [comment]
thanks
