### ISSUE TITLE
[2.8.1] « View graph for host » sends to empty performance page

### ISSUE THREAD

**Issue by bcournaud** [centreon/centreon#4828]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VCenter

**Steps to reproduce the issue:**
1. Go to monitoring page and click on a host
2.On the right, click "View graphs for host"

**Describe the results you received:**
I land on the performance page, but no graph is displauyed.
I have to select the host and the services in the filter part.

If I have an host named "host-name", the url I'm sent to is : https://centreon/centreon/main.php?p=20401&mode=0&svc_id=host-name

**Describe the results you expected:**

I was expected to see all the graph of the host "aws-admin"

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by ganoze** [comment]
Already fixed in 2.8.1.
