### ISSUE TITLE
Clapi export not working

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon#4829]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 1.6.1

**Centreon Broker version**: 3.0.1

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**

Run clapi with "-e" option (export) 

**Describe the results you received:**
The export failed
Stack trace:
/usr/share/centreon/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
 /usr/share/centreon/lib/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
 /usr/share/centreon/lib/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement->execute(Array)
 /usr/share/centreon/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT contactg...', Array)
 Zend_Db_Adapter_Pdo_Abstract->query('SELECT contactg...', Array)
/usr/share/centreon/lib/Centreon/Object/Relation/Relation.php(189): Centreon_Object_Relation->getResult('SELECT contactg...', Ar in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php on line 234

**Describe the results you expected:**
Successfull clapi export

**Additional information you think important (e.g. issue happens only occasionally):**
It may be related to https://github.com/centreon/centreon/issues/4705
And associated commit : https://github.com/centreon/centreon/commit/9d564e28aed490fe9879a66a2c7d0bc0c4983ed5

**Comment by jason354007** [comment]
Same issue on RHEL 7 as well. Cannot do clapi export. Is there a temporary work around  to this problem ?

**Comment by fixlair** [comment]
I used this very ugly temporary Workaround : I copied the bin/centreon and www/class/centreon-clapi just before the commit that I suspect broke this feature : https://github.com/centreon/centreon/commit/9d564e28aed490fe9879a66a2c7d0bc0c4983ed5.


So to sum up I checkout this revision : https://github.com/centreon/centreon/commit/9b2c347393b4bedee7635728baeee2c8578af93a and copied bin/centreon and www/class/centreon-clapi in my version 2.8.1 and export work again :)

**Comment by lpinsivy** [comment]
Hi,

I Can't reproduce your bug using Centreon Web 2.8.2.

No error with export and a complete Centreon Clapi export

**Comment by thiuyendang** [comment]
Not reproduced with Centreon Web 2.8.5 (CentOs6 CentOs7).
