### ISSUE TITLE
[2.7.8] Widgets actions not working on last update and Firefox ESR 45.5.1

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4830]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.7.1

**Centreon Engine version**:  centreon-engine-1.5.2-1.el6.x86_64

**Centreon Broker version**: centreon-broker-2.11.5-2.el6.x86_64

**OS**: CES (up to date)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
Updated installations on the latest version of all components (including widgets)

**Describe the results you received:**
There seems to have a bug in the last widget update (eg service widget). actions are doing nothing on Firefox ESR 45.5.1 (latest). Example "Acknowledge" or "Force immediate check"

**Describe the results you expected:**
....

**Additional information you think important (e.g. issue happens only occasionally):**
I think this might be considered as critical ?

**Comment by gslongo** [comment]
Still present on Firefox ESR 45.6

**Comment by julienmathis** [comment]
Hello, 

This problem has been fixed here : https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/commit/3a0447568612a57c4dad00139e83e2da1691c1ff

Please update your widget version.

Thanks
