### ISSUE TITLE
Widget: "Locked" option doesn't work in Centreon 2.7.8

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4834]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.7.8
**Centreon Engine version**: 1.5.2
**Centreon Broker version**: 2.11.5

**Steps to reproduce the issue:**
1. Create view with admin account
2. Share view with "Locked ? = No" option
3. Log in with in other user
4. Test changing view

**Describe the results you received:**
The option "Locked?" in Share View (Widgets) has no impact.
If I select "No", other users can't modify the view.

**Describe the results you expected:**
If I select "No", other users can modify the view.

Best Regards

**Comment by lpinsivy** [comment]
custom view mechanism was rewrite into Centreon web 2.8.5
