### ISSUE TITLE
Max value for check latency in the widget Widget-engine-status

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4835]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.8
**Centreon Engine version**: 
1.5.2
**Centreon Broker version**: 
2.11.5
**OS**: 
CES 3.3

**Steps to reproduce the issue:**
1 .In the part "check latency" of the widget "Widget-engine-status",the Max value for hosts and services are the same.

**Describe the results you received:**
In check latency, the max value for services is wrong, in reality it is the max value for hosts

**Describe the results you expected:**
Have the real max value for hosts

**Additional information you think important (e.g. issue happens only occasionally):**

![toto](https://cloud.githubusercontent.com/assets/13485588/21229099/b19395e4-c2e0-11e6-9508-6a8dd71f9cb7.jpg)

You can see the real value in the database with this request: 
select * from nagios_stats where instance_id=x;

**Comment by julienmathis** [comment]
Hello, 

Please can you open your ticket in the good project ? 

https://github.com/Centreon-Widgets/centreon-widget-engine-status

Thanks in advance.

**Comment by tseegers** [comment]
Sure: https://github.com/Centreon-Widgets/centreon-widget-engine-status/issues/6
