### ISSUE TITLE
[Question | 2.8.2] timezone

### ISSUE THREAD

**Issue by snaki4** [centreon/centreon#4840]
Centreon 2.8.2, question about timezone under user and host.

How notification and check time will work when centreon server is in UTC timezone, php.ini set to be in UTC, but server has EST configured for example. Will that follow UTC timing or it will convert time in EST and apply EST's time ?

I.e. I do want to monitor server in EST from 1am to 2am. Shall I just create time period 01:00-02:00 and apply to the server or I have to create time-period in UTC which will reference to EST time?

How user timezone is affected by this? Will user get notification based on host configuration? What is the role of that one?

Thank you!

**Comment by julienmathis** [comment]
Hello, 

The check period will be scalled from the server timezone (configured in Configuration > Host).

The notification period depends from 2 elements : 
- first the host timezone
- filtered on each user by the user timezone.

The configured timezone of your monitoring server is now taken in account for the timezone calculation.

Best resgards
