### ISSUE TITLE
Question regarding  export poller configration

### ISSUE THREAD

**Issue by jason354007** [centreon/centreon#4841]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 1.6.2

**Centreon Broker version**: 3.0.3

**OS**: RHEL 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Steps to reproduce the issue:
1. What is the correct procedure to restart Centreon from the GUI ?

I have configured a new host and service.  In order to make the changes permanent, I have exported the poller configuration like below:

![error2](https://cloud.githubusercontent.com/assets/24270691/21265054/cbdd6726-c39f-11e6-8386-1e0acc96ea64.JPG)

and then

![error3](https://cloud.githubusercontent.com/assets/24270691/21265063/d5cfd5ca-c39f-11e6-96c7-31296895e737.JPG)

 Is this the correct way ?

I have tried with both reload and restart and it does not change.

The changes still did not reflect unless I do the below explicitly from the command line after performing the above steps:

`systecmctl restart centengine
`

**Describe the results you received:**
Host and service not reflecting on the web GUI after exporting the poller configuration unless centengine was explicitly restarted.

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Hello, 

Yes you have to start centcore if you want to apply configurations. 

Can you confirm that it works now after the restart of the centcore process ?

Thanks

**Comment by jason354007** [comment]
No luck Restarting centcore.
 

> 1. Export Poller configuration as above.
> 2.  systemctl restart centcore

It does not work. 

but the below works:

> 1. Export Poller configuration as above.
> 2. systemctl restart centengine


Please let me know .

**Comment by julienmathis** [comment]
No. You don't need to restart engine. UI do it.

**Comment by Sims24** [comment]
@jason354007 do you have any file like /etc/sudoers.d/centreon on the remote poller ?

**Comment by jason354007** [comment]
Yes. It is there.

]# cat /etc/sudoers.d/centreon
## BEGIN: CENTREON SUDO
#Add by CENTREON installation script
User_Alias      CENTREON=nagios,centreon,centreon-engine,centreon-broker
Defaults:CENTREON !requiretty
# Snmptt Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/snmptt restart
# Snmptrapd Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/snmptrapd restart
## Centreontrapd Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd restart
## Centreontrapd Reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd reload
## Centreontrapd Stop
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd stop
## Centreontrapd Start
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd start
## CentStorage
CENTREON   ALL = NOPASSWD: /etc/init.d/centstorage *
# Centengine Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine restart
# Centengine stop
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine start
# Centengine stop
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine stop
# Centengine reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine reload
# Broker Central restart
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd restart
# Broker Central reload
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd reload
# Broker Central start
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd start
# Broker Central stop
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd stop
# Centreon Engine central restart for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl restart centengine
# Centreon Engine central reload for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl reload centengine
# Centreon Engine central start for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl start centengine
# Centreon Engine central stop for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl stop centengine
## END: CENTREON SUDO

**Comment by julienmathis** [comment]
Hello, 

I think you have a problem. Centreon UI don't make "systemctl restart centengine" but "service centengine restart" 

Please convert your sudo config file in order to manage that. 

Did you configure this file manualy ?

Regards,

**Comment by Sims24** [comment]
@jason354007 did youselect systemv instead of sytemv in your poller configuration ?

**Comment by jason354007** [comment]
Hello @julienmathis  @Sims24,

I have done the installation from the standard centreon 3.4 repo by following the below URL:

https://documentation.centreon.com/docs/centreon/en/2.8.x/installation/from_packages.html

By Default, it was set to systemv . I changed it to systemd now and again exported poller configuration and restarted centcore. Still the changes do not get permanent and it reflects the old status.


Below is my poller configuration:

![poller](https://cloud.githubusercontent.com/assets/24270691/21346549/1bc3fe3c-c6a5-11e6-9113-73752a181604.JPG)

I have not configured anything manually.

**Comment by jason354007** [comment]
Did the same check on a fresh Centos 7.2 install and the monitoring engine doesn't get restarted with either systemd or systemv after exporting the poller config.


These are the packages that gets installed:

```
$ rpm -qa|grep centreon
centreon-clib-1.4.2-3.el7.centos.x86_64
centreon-broker-cbd-3.0.3-4.el7.centos.x86_64
centreon-base-config-centreon-engine-2.8.2-2.el7.centos.noarch
centreon-broker-3.0.3-4.el7.centos.x86_64
centreon-engine-extcommands-1.6.2-2.el7.centos.x86_64
centreon-poller-centreon-engine-2.8.2-2.el7.centos.noarch
centreon-engine-daemon-1.6.2-2.el7.centos.x86_64
centreon-common-2.8.2-2.el7.centos.noarch
centreon-broker-core-3.0.3-4.el7.centos.x86_64
centreon-perl-libs-2.8.2-2.el7.centos.noarch
centreon-connector-perl-1.1.2-3.el7.centos.x86_64
centreon-broker-cbmod-3.0.3-4.el7.centos.x86_64
centreon-engine-devel-1.6.2-2.el7.centos.x86_64
centreon-broker-storage-3.0.3-4.el7.centos.x86_64
centreon-connector-ssh-1.1.2-3.el7.centos.x86_64
centreon-engine-1.6.2-2.el7.centos.x86_64
centreon-clib-devel-1.4.2-3.el7.centos.x86_64
centreon-plugin-meta-2.8.2-2.el7.centos.noarch
centreon-trap-2.8.2-2.el7.centos.noarch
centreon-connector-1.1.2-3.el7.centos.x86_64
centreon-plugins-2.8.2-2.el7.centos.noarch
centreon-web-2.8.2-2.el7.centos.noarch
centreon-2.8.2-2.el7.centos.noarch
```

I can see the systemd daemons(except centcore which is sysVinit)
```
~]$ locate centengine|grep systemd
/etc/systemd/system/centengine.service
/etc/systemd/system/multi-user.target.wants/centengine.service

~]$ locate cbd|grep systemd
/etc/systemd/system/cbd.service
/etc/systemd/system/multi-user.target.wants/cbd.service

~]$ locate centcore|grep init.d
/etc/rc.d/init.d/centcore
/usr/share/centreon/examples/centcore.init.d
```

**Comment by jason354007** [comment]
Hello,

Any idea what could be wrong here ?

**Comment by jason354007** [comment]
It was fixed after putting apache in the sudo config. It looks like the installation from packages does not put  apache in "/etc/sudoers.d/centreon" .


Also,  I had to add this which was missing with the installation: 
# Centreon Broker central restart for systemd
CENTREON ALL = NOPASSWD: /bin/systemctl restart cbd
# # Centreon Engine central reload for systemd
CENTREON ALL = NOPASSWD: /bin/systemctl reload cbd
# # Centreon Engine central start for systemd
CENTREON ALL = NOPASSWD: /bin/systemctl start cbd
# # Centreon Engine central stop for systemd
CENTREON ALL = NOPASSWD: /bin/systemctl stop cbd
# ## END: CENTREON SUDO

**Comment by lpinsivy** [comment]
We change sudoers for centreon

## BEGIN: CENTREON SUDO

User_Alias      CENTREON=%centreon
Defaults:CENTREON !requiretty

# centreontrapd
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd reload

# Centreon Engine
CENTREON   ALL = NOPASSWD: /sbin/service centengine start
CENTREON   ALL = NOPASSWD: /sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -v *

# Centreon Broker
CENTREON   ALL = NOPASSWD: /sbin/service cbd start
CENTREON   ALL = NOPASSWD: /sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd reload

## END: CENTREON SUDO
