### ISSUE TITLE
[Centreon 2.8.2] Sql error with meta services

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#4843]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 1.6.2

**Centreon Broker version**: 3.0.3

**OS**: CentOS (Centreon 3.3 update 3.4)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. create metaservice 
![install_glpi2016-12-19_07-06-04_pm](https://cloud.githubusercontent.com/assets/12350746/21323541/437f96b6-c61e-11e6-95c4-296351eafe89.png)
2. export configuration
3. result 
![install_glpi2016-12-19_07-07-52_pm](https://cloud.githubusercontent.com/assets/12350746/21323588/7a6a6908-c61e-11e6-9a29-72e33b886cd6.png)

**Describe the results you received:**

UNKNOWN: SQL Query error: SELECT metrics.metric_id, metrics.metric_name, metrics.current_value FROM index_data, metrics WHERE index_data.service_description LIKE '%load%' AND index.id = metrics.index_id

**Describe the results you expected:**

index.id does not exist but index_data.id

**Additional information you think important (e.g. issue happens only occasionally):**

The meta service worked with the old version 3.3
![install_glpi2016-12-19_06-27-09_pm](https://cloud.githubusercontent.com/assets/12350746/21323718/155c99fe-c61f-11e6-8077-d8e1f0e4e0dd.png)

**Comment by julienmathis** [comment]
Hello @kermith72, 

This problem has already been fixed :)

https://github.com/centreon/centreon-plugins/commit/d4812fce09b9e3764e1c7afe75a32a6c5be8ed6b#diff-0012ad42ad35062c6c89a22d5f82bfc7

Best regards,
