### ISSUE TITLE
Filesystem has duplicate UUID 

### ISSUE THREAD

**Issue by JackTor** [centreon/centreon#4847]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web-2.8.2-2.el6.noarch
**Centreon Engine version**: 
centreon-engine-1.6.2-2.el6.x86_64
**Centreon Broker version**: 
centreon-broker-3.0.3-4.el6.x86_64
**OS**: 
CentOS release 6.8 x86_64 (CES 3.4)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM Xen server

**Steps to reproduce the issue:**
1. Backup LVM Snapshot form command Line or automatic with crontab, execcute script /usr/share/centreon/cron/centreon-backup.pl
2. Error message: XFS (dm-8): Filesystem has duplicate UUID xxxxxx - can't mount
3. No backup with LVM

**Describe the results you received:**
mount: wrong fs type, bad option, bad superblock on /dev/mapper/vg-dbbackup,
       missing codepage or helper program, or other error
   En algunos casos se encuentra información en syslog, pruebe
   dmesg | tail   o algo parecido

**Describe the results you expected:**
backup with extension .tar.gz

**Additional information you think important (e.g. issue happens only occasionally):**
FIlesystem is in XFS
--- Volume group ---
  VG Name               vg
  System ID             
  Format                lvm2
  Metadata Areas        2
  Metadata Sequence No  46
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                6
  Open LV               6
  Max PV                0
  Cur PV                2
  Act PV                2
  VG Size               303,89 GiB
  PE Size               4,00 MiB
  Total PE              77797
  Alloc PE / Size       72678 / 283,90 GiB
  Free  PE / Size       5119 / 20,00 GiB
  VG UUID               hDr6xa-R3rh-gXiD-22cB-TMFG-OtfJ-og8FaW

**Comment by JackTor** [comment]
I has fixed this, add lines to file /usr/share/centreon/cron/centreon-backup-mysql.sh:

235 output_log "Reparando Sistema de Archivos XFS"
236 xfs_repair -L /dev/$vg_name/dbbackup
237 output_log "Generated new UUID"
238 xfs_admin -U generate /dev/$vg_name/dbbackup
239 newuuid=$(xfs_admin -u /dev/vg/dbbackup| awk '{ print $3 }')
240 output_log "UUID /dev/$vg_name/dbbackup is: $newuuid "

However, i'm not sure it's the right thing to do, (excuse my english)

**Comment by lpinsivy** [comment]
Yes It's an issue due to XEN system.

Correct way is to generate a new UUID http://linux-tips.com/t/xfs-filesystem-has-duplicate-uuid-problem/181
