### ISSUE TITLE
PHP compatibility to a supported version

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#4848]
Since Centreon 2.6 you have introduced compatibility with PHP 5.4, but PHP 5.4 is deprecated. Can you provide a version that will support actual PHP versions > 5.5?

Regards,
Jochen

**Comment by Shini31** [comment]
FYI

https://secure.php.net/supported-versions.php

**Comment by nicutor** [comment]
So, is Centreon 2.6.x compatible with php 5.6.x and later? Can anyone answer on this?

Thanks

**Comment by lpinsivy** [comment]
Hi,

I think no.

Centreon .7.x and 2.8.X are compatible with 5.5 but not with version >= 5.6

**Comment by lpinsivy** [comment]
We are working for PHP7 support
