### ISSUE TITLE
[CLAPI] Bad handle of accentuded chars

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#4853]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**:  1.6.0

**Centreon Broker version**:  3.0.0

**OS**:  RedHat 6.8

**Steps to reproduce the issue:**
1. Create an hostname "Windows-Serv**é**rs"
2. List hostgroups with clapi :  $ "/usr/bin/centreon" -u admin -p "xxxxxxx" -o HG -a show

**Describe the results you received:**
54;Windows-Serv▒rs;All windows serv▒rs

**Describe the results you expected:**
54;Windows-Servérs;All windows servérs

**Additional information you think important (e.g. issue happens only occasionally):**
I found this by trying to add (at creation time) a host to a hostgroup with accent in his name.

So the problem seems to be everywhere in hostgroup manipulation.

**Comment by lpinsivy** [comment]
should be ok

# /usr/share/centreon/bin/centreon -u superadmin -p centreon -o HG -a show
id;name;alias
53;Linux-Servers;All linux servers
54;Windows-Servérs;Windows-Servérs
