### ISSUE TITLE
Dashboard is Undetermined

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4854]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: 1.6.1

**Centreon Broker version**: 3.0.1

**Steps to reproduce the issue:**
1. Add a new host with all services in OK state
2. Go to "reporting --> dashboard"

**Describe the results you received:**
Dashboard is in status "undetermined"
![dashboard](https://cloud.githubusercontent.com/assets/11076322/21501470/989c3d0e-cc48-11e6-8612-36cc38d2d54c.JPG)

**Describe the results you expected:**
I want to see 100% OK

**Comment by maksimatveev** [comment]
@s-duret https://github.com/centreon/centreon/issues/4849

**Comment by maksimatveev** [comment]
@s-duret 
I eliminated as follows:
`/usr/share/centreon/cron/eventReportBuilder -r`
`/usr/share/centreon/cron/dashboardBuilder -r`
If an error occurs:
`Error: Can't call method "query" on an undefined value at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 96.`
Then
`UPDATE centreon.options SET value='broker' WHERE value='ndo';`

**Comment by maksimatveev** [comment]
@s-duret also:
https://github.com/centreon/centreon/issues/436
https://github.com/centreon/centreon/issues/3057

**Comment by Thibaut-ids** [comment]
Hello,

I have the same problem as s-duret.
I tried all the suggested solutions, but that did not help. The dashboard is still 100% indeterminate.

Centreon Web : 2.8.2
Centreon engine : 1.6.2
Centreon broker : 3.0.2

Thanks fro your help !

**Comment by maksimatveev** [comment]
@Thibaut-ids I am assuming that the problem is specific to you.
should help command in my first message:
![17 41 57 04-01-2017](https://cloud.githubusercontent.com/assets/15804154/21645964/508610d6-d2a5-11e6-8e12-845ae2c72263.png)

**Comment by Thibaut-ids** [comment]
I have already tested these commands but it does not return any errors. On the other hand, when try to rebuild dashboard (/usr/share/centeron/cron/dashboardbuilder -r), I need to specify a start and end date.
![image](https://cloud.githubusercontent.com/assets/23074308/21646330/06a5fa1c-d296-11e6-9fd9-80b810a932ca.png)

**Comment by maksimatveev** [comment]
@Thibaut-ids "undeterminate" for any period?

**Comment by Thibaut-ids** [comment]
@maksimatveev What do you mean by any periods?

**Comment by maksimatveev** [comment]
@Thibaut-ids weekly, monthly, etc.

**Comment by Thibaut-ids** [comment]
@maksimatveev Yes the status is "undeterminate" for any period. But I am a trainee and I did not leave my computer on for several days. But since Monday it turns 24/24

**Comment by Yorlin974** [comment]
Same issue, on a fresh install, @s-duret any news ?

**Comment by Thibaut-ids** [comment]
It's a fresh install.

**Comment by usawa** [comment]
Hi, I confirm I've the same issue, fresh install of Centreon 3.4 distribution using your ISO image. I tried a lot of things, without any success. All other things seems to work correctly.

**Comment by kduret** [comment]
Fixed here : 
f8b4223c4cb8e1e20f455efc23ba53fe11216d95
3c58414552fc47e883a882ec817dc34908fca947
