### ISSUE TITLE
Cas Authentication Status

### ISSUE THREAD

**Issue by Zwordi** [centreon/centreon#4856]
Hello,

As few people we are looking for a way to connect to our Centreon 2.7.7 using our CAS server.

I saw that on https://github.com/centreon/centreon/blob/2bcd4b2c28b29aea9310222f3d1c1b2f5d16506b/www/include/Administration/parameters/DB-Func.php
Which is about the 2.6 version of Centreon.

No big deal just wanna to get a status.

Thanks

**Comment by lpinsivy** [comment]
Hi,

Centreon web 2.7.x and 2.8.x allows to use SSO authentication.

Regards,
