### ISSUE TITLE
Configuration of Host Templates Relations now showing properly

### ISSUE THREAD

**Issue by boupjof** [centreon/centreon#4858]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 1.6.2

**Centreon Broker version**:  3.0.3

**OS**:  CES

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Configuration -> Hosts -> Templates -> Relations
2. The Linked Service Templates tiny no resizable box is difficulte to use
3.

**Describe the results you received:**
http://imgur.com/a/ZA0lm

**Comment by lpinsivy** [comment]
yo ucan now resize this area
