### ISSUE TITLE
[2.8.2] base-centreon-dummy command

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon#4859]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**

**Describe the results you received:**
can't execute command

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**
the command given by pp-manager isn't functional:
$USER1$/check_centreon_dummy - $ARG1$ - o $ARG2$
it should be:
$USER1$/check_centreon_dummy -s $ARG1$ -o $ARG2$

as it's given by pp, it's not writeable in the web interface....

**Comment by lpinsivy** [comment]
Thank you to report this issue.

It will be corrected tomorrow ith an update of the base-generic pack.

Regards,

**Comment by julienmathis** [comment]
This problem is now fixed !

**Comment by golgoth31** [comment]
thx !
