### ISSUE TITLE
Duplicate comments with external command on host monitoring page - Aknowledge

### ISSUE THREAD

**Issue by hocinetwork** [centreon/centreon#4862]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 1.6.2

**Centreon Broker version**: 3.0.3

**OS**: Centos 6.8

When i aknowledge two hosts consecutively in the host monitoring page, the second displayed the same comment as the first. I have a duplicate comment for the two hosts.

/var/log/httpd/access_log : 
![image](https://cloud.githubusercontent.com/assets/22976562/21567804/61f1249a-ceaf-11e6-8961-c99339eeca79.png)

The second host should have "GITHUB02" as comment.

This issue seems to be the same as #4170

**Comment by julienmathis** [comment]
To be validated

**Comment by leoncx** [comment]
Hello @hocinetwork,

Can you create a merge request for your commit ?

I will merge when is done.

Thank for your help 

Regards,
