### ISSUE TITLE
Monitoring - Performances - Graphs (Filters)

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4872]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
 Centreon 2.8.2
**Centreon Engine version**: 
 Centreon Engine 1.6.2
**Centreon Broker version**: 
 Centreon Broker 3.0.3
**OS**: 
 CentOS release 6.8 (Final)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM

**Steps to reproduce the issue:**

1. Open Centreon
2. Goto Monitoring - Performances - Graphs

**Describe the results you received:**
The "Filter by Host", "Filter by Hostgroup", "Filter by Servicegroup" should be above the "Chart" Period.... Because this Filters get applied on the Chart search field. The User read from top to bottom!

The Note on the right side, should be on the left and corrected to "Chart search field Filters".

If someone uses the "Filter by Host", "Filter by Hostgroup", "Filter by Servicegroup" it is better to display the result somehow instead of making the results accessable in the "Chart" field. Maybe display the Graphs but i whould wish, that we can add some sort of other cool function like the list in the old Centreon version. (One of my customers REALLY love that, so we his centreon version is due to that wish still on the old centreon 2.6 version. 

![graphs](https://cloud.githubusercontent.com/assets/2785700/21788245/d509950e-d6cd-11e6-8ec7-7d08097cc21c.PNG)

**Describe the results you expected:**
see above

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

The goal of this new view is to build a chart dashboard and not to display all available graphs. That's we change the system and add "filters".

Regards,

**Comment by florian-asche** [comment]
Hi, ok i understand that. I filter, and then the graphs i selected are displayed.

But i whould filter, and then select the Chart. The filters should come first. (1) 
I whould add a name for the Chart section like "Display charts". (2)
And i whould rename the "Chart" description for the search field, to something like "Select chart to display" (3). 

By the way, i had something in mind like you want to remove host/service group, and replace it by tags. One single search field whould make much more sense then.

**Comment by lpinsivy** [comment]
We prefer to keep this ux to for people to keep more importants filters on top
