### ISSUE TITLE
Centreon Download Package missing

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4873]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
centreon-web-2.8.2 Package is missing in Centreon Web section. Maybe more packages are missing?

**Describe the results you expected:**
check and fix!

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Sorry Florian. It's now OK.

Thanks for your feedback
