### ISSUE TITLE
Autologin works only with SSO enabled

### ISSUE THREAD

**Issue by samuel4x4** [centreon/centreon#4874]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.1-2.el6.noarch 
**Centreon Engine version**: centreon-engine-1.6.0-1472141297.6301589.el6.x86_64 
**Centreon Broker version**: centreon-broker-3.0.0-1472213579.939db56.el6.x86_64 
**OS**: Red Hat Enterprise Linux Server release 6.8 (Santiago)
**Additional environment details (AWS, VirtualBox, physical, etc.):** Openstack instance

I'm trying to enable and use the autologin authentication: https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/contact.html?highlight=autologin#centreon-authentication

**Steps to reproduce the issue:**
1. Disable SSO authentication
2. Enable Autologin
3. Set autologin key for specific user
4. Open index.php?autologin=1&useralias=userAlias&token=autologinKey

**Describe the results you received:**
User is not authenticated.

**Describe the results you expected:**
User is authenticated.

**Additional information you think important (e.g. issue happens only occasionally):**
User is authenticated if both "SSO authentication" and "Autologin" options are checked. Is Autologin linked to SSO?

**Comment by ganoze** [comment]
This will be fixed in the 2.8.3 release of Centreon Web.
