### ISSUE TITLE
Only `useralias` parameter is checked on "autologin" authentication

### ISSUE THREAD

**Issue by samuel4x4** [centreon/centreon#4875]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.1-2.el6.noarch 
**Centreon Engine version**: centreon-engine-1.6.0-1472141297.6301589.el6.x86_64 
**Centreon Broker version**: centreon-broker-3.0.0-1472213579.939db56.el6.x86_64 
**OS**: Red Hat Enterprise Linux Server release 6.8 (Santiago)
**Additional environment details (AWS, VirtualBox, physical, etc.):** Openstack instance

I'm trying to enable and use the autologin authentication: https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/contact.html?highlight=autologin#centreon-authentication

**Steps to reproduce the issue:**
1. Enable SSO authentication (not working with SSO disabled, check #4874)
2. Enable Autologin
3. Set autologin key for specific user
4. Open index.php?autologin=1&useralias=userAlias&token=wrongAutologinKey or index.php?autologin=1&useralias=userAlias or index.php?useralias=userAlias

**Describe the results you received:**
User is authenticated in all cases.

**Describe the results you expected:**
User is not authenticated.

**Additional information you think important (e.g. issue happens only occasionally):**
The token and autologin parameters are not considered, you can put there anything you want or just don't specify them. Only the useralias is checked.

**Comment by samuel4x4** [comment]
#4874

**Comment by lpinsivy** [comment]
Can you check this patch https://github.com/centreon/centreon/commit/cb4b2a6255f9c9c07b3a0f097764dad8403ea932

**Comment by ganoze** [comment]
Cannot reproduce with the upcoming 2.8.3 release of Centreon Web.
