### ISSUE TITLE
[CLAPI] Export ACLs

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4879]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.7.8
**Centreon Engine version**: 1.5.2
**Centreon Broker version**: 2.11.5
**OS**: CENTOS 6.8

**Steps to reproduce the issue:**
1. Export objects : # centreon -u admin -p centreon -e > /tmp/clapi-export.txt
2. Check in file /tmp/clapi-export.txt , but object ACL are not present

**Describe the results you received:**
When exporting the configuration via CLAPI, ACL are not exported

**Describe the results you expected:**
When exporting the configuration via CLAPI, all objects should be exported. ACL also.

Regards

**Comment by Sims24** [comment]
Hi, confirm I have the same issue.

Regards

**Comment by lpinsivy** [comment]
Hi,

It's not a bug. The Centreon source code is defined to do not export : ACL objects, LDAP and Centeron global settings.

I modified documentation to prevent users

Commit f6640678cf83deb34cfa433f2ad9d67a93f6511a

**Comment by lpinsivy** [comment]
Done in Centreon Web 2.8.12
