### ISSUE TITLE
Demo System

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#4880]
Is there no demo system anymore? Cant find information on the new website.
Some feedback: i dont like the new website.

**Comment by BenoitPoulet** [comment]
Hello,

I can add that the IRC channel disappear from https://www.centreon.com/centreon-monitoring-platform-community/

Please take care of the community :)

**Comment by lpinsivy** [comment]
Hi,

Demo is available on demo.centreon.com (admin/centreon)

We will re-add demo information page on new website soon.

Regards,

**Comment by julienmathis** [comment]
Done.
