### ISSUE TITLE
[2.8.2] Configuration field too shorts

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#4881]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.2

In Centreon 2.8, at least in host or service configuration page, nearly all the fields are too shorts.

and that in all the tabs of the service/host config.

please look the example attached.

Already reported 2 times as #4552 , #4187 

![too_short](https://cloud.githubusercontent.com/assets/2464712/21840828/e46a050c-d7df-11e6-8e83-d4c6cca82b82.png)

**Comment by lpinsivy** [comment]
Les champs ont été élargi

<img width="916" alt="screenshot at sept 08 14-33-35" src="https://user-images.githubusercontent.com/3351916/30211822-b7377fee-94a2-11e7-864a-33eb95cd6b06.png">
