### ISSUE TITLE
[2.8.2] Curves properties (stacking, transparency...)

### ISSUE THREAD

**Issue by Gleamix** [centreon/centreon#4884]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.2
**Centreon Engine version**: 
1.6.2
**Centreon Broker version**: 
3.0.3
**OS**: 
Debian 8.6
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Xen hypervisor 4.7

**Steps to reproduce the issue:**
1.Go to Monitoring  >  Performances  >  Curves
2.Try to customize curves (add stacking order, transparency, filling...)

**Describe the results you received:**

Graph isn't displayed as expected (the stacking order is wrong, transparency remains the same whatever percentage I typed)

![image](https://cloud.githubusercontent.com/assets/25056830/21849548/9bf50b42-d806-11e6-9887-3ed92825cefa.png)

**Describe the results you expected:**

Correct display :
![image](https://cloud.githubusercontent.com/assets/25056830/21849541/8e355296-d806-11e6-91d7-a56a6b61cf44.png)

**Additional information you think important (e.g. issue happens only occasionally):**

It was working fine in 2.7.x until I updated to 2.8.x (I tried 2.8.1 and 2.8.2).
Config :

![image](https://cloud.githubusercontent.com/assets/25056830/21849570/af531a58-d806-11e6-8c0f-bb901ebe486d.png)

**Comment by lpinsivy** [comment]
Problem still present with testing version 
![srvt-build-centos-7-memory](https://cloud.githubusercontent.com/assets/3351916/23712830/569406b2-0424-11e7-8324-b69525f658fa.png)
![screenshot at mars 08 17-25-12](https://cloud.githubusercontent.com/assets/3351916/23712838/5f82c650-0424-11e7-8c35-840ce4f589c9.png)

**Comment by Gleamix** [comment]
Hello, I've upgraded to 2.8.5 (with engine to 1.7.1 and broker to 3.0.4) and it's still not working for me : 

![image](https://cloud.githubusercontent.com/assets/25056830/24543532/487ce40c-1600-11e7-9502-96cb3bb01f42.png)

I've tried deleting and recreating curves properties : 

![image](https://cloud.githubusercontent.com/assets/25056830/24543580/6d09144e-1600-11e7-8c59-7e3b7270a716.png)
