### ISSUE TITLE
Trend in graph views

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#4887]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 1.6.0

**Centreon Broker version**: 3.0

**OS**: CentOS

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VIRTUAL MACHINE

**Steps to reproduce the issue:**
1. Go on "Monitoring" ==> "Performances"
2. Select one graph
3. Click on this graph

**Describe the results you received:**
Before Centreon Web 2.8 when you click on the graph you had the trend of the service (one graph by period : daily, weekly, monthly and yearly

**Describe the results you expected:**
I would like to recover this functionality

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lolokai** [comment]
Up !

**Comment by lpinsivy** [comment]
added
