### ISSUE TITLE
the new "executed check command line" in the service's details page breaks the layout

### ISSUE THREAD

**Issue by GuillaumeBernard** [centreon/centreon#4889]
Hello, 

With Centreon Web 2.8.2, the new "executed check command line" in the service's details page is great, but it breaks the web page layout when the command line is long.

Regards
Guillaume

**Centreon Web version**: 
2.8.2

**Steps to reproduce the issue:**
1. Use a long command line to check a service
2. Go to page with the service's details
3. ...
4. Profit!

**Describe the results you received:**
The command line is long:
![image](https://cloud.githubusercontent.com/assets/16776408/21887569/ba7f2006-d8c0-11e6-9c4f-d792ac249bef.png)
The web page layout is broken:
![image](https://cloud.githubusercontent.com/assets/16776408/21887571/bdd4a96a-d8c0-11e6-9981-cf2835c3de14.png)

**Describe the results you expected:**
Non-broken page layout

**Comment by lpinsivy** [comment]
already fixed by 0f2c20a967bd509290d95dc920074c7339b3478c
