### ISSUE TITLE
[Auto-Discovery] - Add option "Update element already exists (Yes/No)"

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#4890]
Hi,

Is it possible (or maybe already planned) to add an option to activate (or not) updates of existing services when a rule is activate (like "Disable elements not found")

Currently, if a service already exists in the conf but not strictly similar, like the discovered items, they will be updated automatically and reset to the default thresholds.
On disks, these updates are frequent after a few times of use.

This option, set to "No", would make it possible to no longer touch the elements already discovered and updated manually thereafter.
It would also allow the use of custom variables and threshold management based on disk size only on newly discovered items. These custom variables are currently unusable if the thresholds have been updated after the initial discovery.
In the interface, the indication of an update possibility must be retained. This lets you know which services are modified and possibly force the update.
This option, set to "Yes", would retain current operation.

Regards,
===============================================================
Bonjour,

Est-il possible (ou peut-être déjà prévu) d'ajouter une option (Oui/Non) permettant d'activer ou non la mise à jour des services déjà existant dans la configuration?

Actuellement, un service qui existerait déjà dans la configuration mais qui ne respecterait pas totalement les éléments découverts par la règle, se voit être mis à jour automatiquement.
Or sur les disques notamment, il n'est pas rare que l'on ait à ajuster le seuil d'alerte au bout de quelques temps; la volumétrie de production ayant fait son oeuvre.

Cette option, positionnée à "Non", permettrait de ne plus toucher aux éléments déjà découverts et mis à jour manuellement par la suite.
Elle permettrait également  d'utiliser les custom variables et la gestion des seuils en fonction de la taille des disques uniquement sur les nouveaux éléments découverts. Cette fonction est actuellement inutilisable si les seuils ont été mis à jour ultérieurement à la découverte initiale.
Dans l'interface, l'indication d'une possibilité d'update doit être conservée. Cela permet de savoir quels sont les services modifiés et d'éventuellement forcer la mise à jour.
Cette option, positionnée à "Oui", conserverait sont fonctionnement actuel.

Cordialement,

**Comment by cmeschin** [comment]
Hi,
Have you any news about this?

thanks.

**Comment by lpinsivy** [comment]
Hi @cmeschin done in Centreon Auto Discovery [18.10.4](https://documentation.centreon.com/docs/centreon-auto-discovery/en/latest/release_notes/18.10/centreon-auto-discovery-18.10.4.html)
