### ISSUE TITLE
[CUSTOM VIEW] Listing of widget with infinite scroll displays at least 3 times each widget

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#4892]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2
**OS**: CentOS 6.7

**Steps to reproduce the issue:**
1. Go to custom view
2. Click on "Add widget" 
3. Scroll down the widget list 

**Describe the results you received:**

The list is reloaded and each widget appears at least 3 times

**Describe the results you expected:**

Only one occurence of each widget in the listing

**Comment by thiuyendang** [comment]
Issue not hit in Centreon Web 2.8.5 (CentOS6 or 7)
