### ISSUE TITLE
Centreon IMP with Proxy server

### ISSUE THREAD

**Issue by Gilum** [centreon/centreon#4896]
After the update to 2.8.2, the HTTP proxy does not work

Login error : Cannot access to IMP portal
Error Licence manager log : 2017-01-02 11:26|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance : Page not found
Proxy protocol : HTTP
Proxy URL : nproxad.xxxxxx.com
Proxy port : 8080

Test with curl :
curl -I https://api.imp.centreon.com/api/license-manager/instance
HTTP/1.1 200 Connection established
Set-Cookie: BIGipServerynproxad_8080_pool=rd1o00000000000000000000ffff0a00cf66o8080; path=/

HTTP/1.1 404 Not Found
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods: GET
Access-Control-Allow-Methods: POST
Access-Control-Allow-Methods: PATCH
Access-Control-Allow-Origin: *
Content-Length: 44
Content-Type: application/json; charset=utf-8
Date: Mon, 02 Jan 2017 10:29:22 GMT
ETag: W/"2c-hfpdyo62anem8s/49Aeidw"
X-Powered-By: Express
Connection: keep-alive

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

https://github.com/centreon/centreon/issues/4779#issuecomment-269955585

**Comment by lpinsivy** [comment]
Hi,

Did you use the latest version of centreon-pp-manager and centreon-license-manager too?

**Comment by Gilum** [comment]
Yes last version for all.
No traffic send to proxy server with tcpdump.

**Comment by Thibaut-ids** [comment]
Hi,

I have the same issue. 

Login error : Cannot access to IMP portal

2017-01-19 16:01|0|0|[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance : Page not found

Proxy protocol : HTTP
Proxy URL : 192.168.xx.xx
Proxy port : 8080

**Comment by kozfelipe** [comment]
Hi,
We need a proxy authentication field at the proxy option section

**Comment by Thibaut-ids** [comment]
It could be fine. But I do not have proxy authentication, so the problem does not come from there.

**Comment by Gilum** [comment]
Proxy whiout authentication it's ok after ugrade 2.8.5 !

 Thank @kduret
