### ISSUE TITLE
Empty Dashboard and uninitialized value $state in string ne during eventReportBuilder 

### ISSUE THREAD

**Issue by vincenteam44** [centreon/centreon#4897]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**:  1.6.2

**Centreon Broker version**:  Centreon Broker 3.0.3

**OS**:  CentOS release 6.8 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMware Virtual Machine on ESX server

**Steps to reproduce the issue:**

1. Add a new host with all services in OK state
2. Go to "reporting --> dashboard"

**Describe the results you received:**

![image](https://cloud.githubusercontent.com/assets/25186162/22041523/81174db6-dd07-11e6-940b-55e7afec8635.png)

**Describe the results you expected:**

I'd like to have information dashboard ;-)

**Additional information you think important (e.g. issue happens only occasionally):**

`[root@vmlcentreon centreon]# cat eventReportBuilder.log
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 148.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonHostStateEvents.pm line 188.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
2017-01-07 03:00:01 - Starting program...
2017-01-07 03:00:01 - Processing period: Fri Jan  6 00:00:00 2017 => Sat Jan  7 00:00:00 2017
2017-01-07 03:00:01 - Exiting program...
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonHostStateEvents.pm line 188.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
`
Reports rebuild print same errors.

`[root@vmlcentreon centreon]# su -l centreon -c "/usr/share/centreon/cron/eventReportBuilder -r"
2017-01-17 22:56:50 - Starting program...
2017-01-17 22:56:50 - Processing period: Fri Jan  6 00:00:00 2017 => Sat Jan  7 00:00:00 2017
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 148.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonHostStateEvents.pm line 188.
Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
2017-01-17 22:56:50 - Processing period: Sat Jan  7 00:00:00 2017 => Sun Jan  8 00:00:00 2017
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonHostStateEvents.pm line 188.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
`

Thanks in adavnce

Vincent

**Comment by kozfelipe** [comment]
edit /usr/share/perl5/vendor_perl/centreon/script/eventReportBuilder.pm

modify getDbLayer() to return "broker" instead "ndo", since the query fails to select a key = 'broker' at centreon.options

`# get db layer
sub getDbLayer() {
    my $self = shift;

    my ($status, $res) = $self->{cdb}->query("SELECT `value` FROM `options` WHERE `key` = 'broker'");
    if (my $row = $res->fetchrow_hashref()) { 
        return $row->{'value'};
    }
    return "broker"; #fix
}`

**Comment by vincenteam44** [comment]
Perfect ! Thank you @kozfelipe ;-)

![image](https://cloud.githubusercontent.com/assets/25186162/22084707/6b78e24c-ddd1-11e6-9b84-5c8b31559e95.png)

**Comment by kduret** [comment]
Fixed here : 
f8b4223c4cb8e1e20f455efc23ba53fe11216d95
3c58414552fc47e883a882ec817dc34908fca947
