### ISSUE TITLE
[2.8.2] Graph is smoothed to much

### ISSUE THREAD

**Issue by masgo** [centreon/centreon#4898]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.2
**Centreon Engine version**: 
1.6.2
**Centreon Broker version**: 

**OS**: 
CentOS 6
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  goto Monitoring  >  Performances  >  Graphs
2. draw some graph for a longer period of time, e.g., 30 days
3.

**Describe the results you received:**
A very smoothed graph suggesting there where no sudden changes in the metrix

**Describe the results you expected:**
A graph showing me the reality 

**Additional information you think important (e.g. issue happens only occasionally):**
This is a graph taken from the centreon demo which shows the traffic for 30 days:
![screenshot-demo centreon com 2017-01-18 02-05-43](https://cloud.githubusercontent.com/assets/1336992/22046829/8c876d4a-dd23-11e6-8104-fa82cf6e43dd.png)

This is the exported PNG which is created by the old RRDtool. You can clearly see that there are quite some interesting changes in traffic. Look for example at the small spike between each day. This is completley gone in the smoothed new rendering.
![fw-alger-traffic-external-1](https://cloud.githubusercontent.com/assets/1336992/22046852/aa506854-dd23-11e6-98fa-04cbd22990d7.png)

**Comment by BenoitPoulet** [comment]
I agree, it's a bit too rounded

**Comment by euidzero** [comment]
Please do not smooth by default. You are using interpolation which give false representation of data like negative round trip times (e.g. check_http). Please favor correctness over aesthetic. Monitoring data are by essence discrete data : smoothing is not relevant. Even worse : it induces interpretation errors that can be tragic in production environnement.

**Comment by masgo** [comment]
There has been a change in smoothing in version 2.8.9, but it is no real improvement. It did eliminate the bug where the graph showed values which can not exist (e.g., negative values for ping or traffic), but it still has issues.

It seems like the data is sampled down to only certain values and then only these values are visualized. For example if I show the last 30 days the values are sampled down to only one value per 4 hour. This simply shows much less data than what the previous visualization did. 

Here are some screenshots taken from https://demo.centreon.com/ for the graph `fw-alger - traffic-external` to illustrate the issue. As we can see, the graphs are no longer smooth, but since the sampling is so coarse, they are still a lot worse than the previous version. 

The optimal solution would probably be to determine the resolution of the screen (or more precise: how many pixel will the graph occupate) and then sample it down to as many values as there are pixels.


![centreon-289-vis-error 1](https://user-images.githubusercontent.com/1336992/27012706-a198282c-4ed5-11e7-99f2-e628d82e715f.png)

![centreon-289-vis-error 2](https://user-images.githubusercontent.com/1336992/27012708-a4544e9c-4ed5-11e7-96fd-e0e1e6dc4325.png)

![centreon-289-vis-error 3](https://user-images.githubusercontent.com/1336992/27012709-a716150c-4ed5-11e7-86e8-c05c7d685c72.png)

**Comment by lpinsivy** [comment]
Will be done with #7676
