### ISSUE TITLE
Setting downtime through nagvis 1.9

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#4899]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 1.6.2

**Centreon Broker version**: 3.0.3

**OS**: CentOS 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

Nagvis 1.9b11 has integrated the possibility to set downtimes and acknowledge directly from there GUI. We have successful integrated the acknowledge paths like
`="/centreon/main.php?p=20201&o=svcak&cmd=15&host_name=[host_name]&service_description=[service_description]&en=1`
but we are not able to set the downtime paths because Centreon needs the host_id and service_id for them like
`/centreon/main.php?p=21001&o=a&host_id=14&service_id=148`
Unfortunatly nagvis does not offer macros for the host_id and service_id, but maybe Centreon offers a url to open the downtime dialog using the host_name and service_name. Anybody has a solution for them?

Regards,
Jochen

**Comment by lpinsivy** [comment]
Hi,

Sorry but since many version of Centreon we prefer use ID instead of name for objects.

Maybe when we will have a REST API to set downtime you will use it.

Regards,
