### ISSUE TITLE
Browsers native login/password form autocompletion doesn't work

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#490]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 3833, https://forge.centreon.com/issues/3833
Original Date: 2012-10-28

---

Hi, 

The names choosen for the login form, and maybe other reasons (input nodes not closed, ...) breaks the capacity of major browsers to autocomplete it if the user choosed to enable the feature : 

<td><input type="text" name="*useralias*" value="" class="inputclassic"* >*</td>
<td><input type="password" name="*password*" value="" class="inputclassicPass"* >*</td>

pch

**Comment by julienmathis** [comment]
It work's fine for me
