### ISSUE TITLE
EventReportBuilder error

### ISSUE THREAD

**Issue by Arkantium** [centreon/centreon#4906]
I have error in:
/usr/share/centreon/cron/eventReportBuilder -r

My Version:
Centreon 2.8.2
MariaDB 5.5.47

> Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
> Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonServiceStateEvents.pm line 189.
> Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 88.

I have test to fix with
`# get db layer
sub getDbLayer() {
    my $self = shift;

    my ($status, $res) = $self->{cdb}->query("SELECT `value` FROM `options` WHERE `key` = 'broker'");
    if (my $row = $res->fetchrow_hashref()) { 
        return $row->{'value'};
    }
    return "broker"; #fix
}`

And i have this result:
Use of uninitialized value $statusCode in string ne at 

> /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 148.
> Use of uninitialized value $statusCode in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonProcessStateEvents.pm line 148.
> Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
> Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonHostStateEvents.pm line 188.
> Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
> Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonHostStateEvents.pm line 188.
> Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonDownTime.pm line 134.
> Use of uninitialized value $state in string ne at /usr/share/perl5/vendor_perl/centreon/reporting/CentreonHostStateEvents.pm line 188.

**Comment by kozfelipe** [comment]
seems you fixed CentreonServiceStateEvents.pm

**Comment by julienmathis** [comment]
Already fixed for Centreon Web 2.8.3 : https://github.com/centreon/centreon/commit/ccf2c256c6dd692a84e9f187008dbb5135b898a6
