### ISSUE TITLE
[EventLog] Select servicegroup does not work

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#4907]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.x

**Steps to reproduce the issue:**
1. Go to "Monitoring  >  Event Logs" menu
2. Select services group
3. Select period and click on "Apply Period"

**Describe the results you received:**

Nothing appear

**Describe the results you expected:**

Should see events

**Comment by s-duret** [comment]
Doesn't work in Centreon 2.8.4

**Comment by lpinsivy** [comment]
fixed by commit 1a3b3a4166161e4ca29f5a853f1a43179b87ff44 91585fedcf13b2612793f8e5cd5dec1acf3025e2 29f2d54527e941dadedccbb69e8cc03d1a395ab6 bb2c29328e59fe0d022aae53a8e228e3ddedd4c3
