### ISSUE TITLE
Evolution Downtime - Possibilité de choisir le second et/ou  troisième jour du mois

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#4908]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.8
**Centreon Engine version**: 
1.5.2
**Centreon Broker version**: 
2.11.5
**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Actuellement il n'est pas possible de configurer un downtime récurrent pour le second ou troisième jour du mois.

**Describe the results you expected:**
Avoir la possibilité de choisir le second ou troisième jour du mois pour y placer un downtime récurrent.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by OpensourceMonitoringRepository** [comment]
et le 4eme aussi cela peut arriver :D

**Comment by Jordan91** [comment]
Actuellement il est possible de faire le premier et dernier du mois mais effectivement un mois avec 5 dimanche cela arrive :) Comme ce mois ci d'ailleurs

**Comment by OpensourceMonitoringRepository** [comment]
Bonjour Laurent,

Nous aurions besoin d'un patch pour la plateform.

Peux tu me donner un delais ?

merci pour ton aide.

**Comment by cmeschin** [comment]
Bonjour,
demande identique à celle-ci #4207.
