### ISSUE TITLE
[2.8.2] Correct the values obtained in the pop-up messages on the graphs

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon#4909]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**Centreon Engine version**: 1.6.2

**Centreon Broker version**: 3.0.3

**OS**: Oracle Linux 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):** physical machine

**Steps to reproduce the issue:**
1. Create a check of interface using the centreon-plugins:
./centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=interfaces --snmp-version=2c --snmp-community=public --hostname=172.31.255.13 --interface='^Ten-GigabitEthernet1/0/20$' --name --add-traffic --nagvis-perfdata
2. Get the check result:
OK: Interface 'Ten-GigabitEthernet1/0/20' Traffic In : 2.63Gb/s (26.26%), Traffic Out : 465.80Mb/s (4.66%) | 'in'=328232525.20;;;0;1250000000 'out'=58224480.27;;;0;1250000000

**Describe the results you received:**
On the graphs to get a different result
![14 44 55 20-01-2017](https://cloud.githubusercontent.com/assets/15804154/22148442/290cb52e-df1f-11e6-800a-e94d264eda30.png)

**Describe the results you expected:**
In the pop-up message should be: Out 2.63G, and In 465.80M

**Additional information you think important (e.g. issue happens only occasionally):**
Related topics not found may bad looking.

**Comment by BenoitPoulet** [comment]
Hello,

The graph values seems to be fine, the unit is in bit (lowercase b), not in byte (uppercase b)

**Comment by maksimatveev** [comment]
Create https://github.com/centreon/centreon-plugins/issues/583 in centreon-plugins

**Comment by lpinsivy** [comment]
So this ticket can be closed ?

**Comment by maksimatveev** [comment]
@lpinsivy Yes, more will continue to ask Quentin
