### ISSUE TITLE
Arguments "$ARGn" are not detected when selecting command

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4910]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.1

**Centreon Engine version**: Not relevant

**Centreon Broker version**: Not relevant

**OS**: Centreon-3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare virtual machine

**Steps to reproduce the issue:**
1. Create a command check_test like "$USER1$/check_test $ARG1$ $ARG2$
2. Go to a service template definition and select check_test as service command
3.

**Describe the results you received:**
My Args doesn't show up 

**Describe the results you expected:**
My Args appears and I'm able to set value for

**Additional information you think important (e.g. issue happens only occasionally):**
If I save my form and come edit again, arguments appears.

**Comment by julienmathis** [comment]
Already fixed in version 2.8.3.
