### ISSUE TITLE
[KB] LInk error in KB configuration

### ISSUE THREAD

**Issue by querwin** [centreon/centreon#4912]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.2

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Use KB in Centreon 2.8.x
2. Try to go to a monitoring procedure
3.

**Describe the results you received:**

The address, of the link is http://localhost/centreon/include/configuration/configKnowledge/proxy/proxy.php?host_name=xxxxx 

**Describe the results you expected:**

This should not be localhost but the adress of my Centreon

**Comment by julienmathis** [comment]
@loiclau Can you give us the fix ?
