### ISSUE TITLE
Downtimes

### ISSUE THREAD

**Issue by djedje68** [centreon/centreon#4918]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.2

**Centreon Engine version**:  1.6.2

**Centreon Broker version**: 3.0.3

**OS**: CentOS 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware
ISO Centreon 3.4

**Steps to reproduce the issue:**
1. Go to Configuration > Services > Donwtimes
2. Add a downtimes
3. 

**Describe the results you received:**
The downtime does not appear in the services downtimes but in the host's downtime.

**Describe the results you expected:**
When we create a downtine for services, it must be appear to services downtime

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Have to be checked.

**Comment by julienmathis** [comment]
Fixed by #5000
