### ISSUE TITLE
Broker's "Add with wizard" is broken

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon#4925]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3-2.el6

**Centreon Engine version**: 1.7.0-2.el6

**Centreon Broker version**: 3.0.3-4.el6

**OS**: CES

**Steps to reproduce the issue:**
1. Choose "Add with wizard" from the "Broker configuration" menu
2. Complete the wizard

**Describe the results you received:**
- 3 more entries are added to "Engine configuration"
- each has a with a broker directive set to `/usr/lib64/nagios/cbmod.so /etc/centreon-broker/poller-module.xml`

**Describe the results you expected:**
From what I understand, the wizard should:
- not add 3 more engine configs
- add a broker directive set to `/usr/lib64/nagios/cbmod.so /etc/centreon-broker/central-module.xml` to the existing "Engine configuration"

**Comment by lpinsivy** [comment]
New wizard from 18.10.0 correct this
