### ISSUE TITLE
LDAP - Values in table options are NULL 

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#4929]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.8
**Centreon Engine version**: 
1.5.2
**Centreon Broker version**: 
2.11.5
**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to administration->parameters->LDAP and select connector
2. Change enable yes to no and save , i return automatically on  administration->parameters->LDAP
3. i click on enable on my connector and i see the interface centreon without the "good" screen
4. The value is table options are set NULL
5. The GUI is not avalaible

**Describe the results you received:**
The GUI is not avalaible and value in table options are NULL

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by leoncx** [comment]
I can reproduce this issue.

Can you attach the sql-error.log ?

**Comment by Jordan91** [comment]
Hi, 

In attach the file sql-error.log 

Best regards, 


[sql-error (2).zip](https://github.com/centreon/centreon/files/821014/sql-error.2.zip)

**Comment by lpinsivy** [comment]
corrected by 0e64884

**Comment by thiuyendang** [comment]
Centreon Web 2.8.5, CentOS6, CentOS7
Add a new connecter LDAP
Enable it
Disable
GUI still OK
