### ISSUE TITLE
Describe arguments does not work with % character in command line

### ISSUE THREAD

**Issue by jdelvecchio** [centreon/centreon#4930]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.3-2.el7.centos

**Centreon Engine version**: 
1.7.0-2.el7.centos

**Centreon Broker version**: 
3.0.3-4.el7.centos

**OS**: 
CentOS Linux release 7.3.1611 (Core) 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare VM

**Steps to reproduce the issue:**
1. Edit a command

2. Add the % character inside the command line, here's an example of a command where I encounter the bug : 
`$USER1$/check_snmp_storage.pl -H $HOSTADDRESS$ -l $ARG1$ -x $ARG2$  -X $ARG3$ -L $ARG4$ -e -m '$ARG5$' -q FixedDisk -w $ARG6$% -c $ARG7$% -f
`
3. Clic on 'Describe Arguments'

**Describe the results you received:**
The describe arguments window is blank.
With the browser debugging, I can see a failed JS call, here is the request URL that fails :
![selection_054](https://cloud.githubusercontent.com/assets/11552866/22428033/cc44d4e0-e705-11e6-847f-c2a34e996a67.png)

**Describe the results you expected:**
The describe arguments window opens up normally.

**Additional information you think important (e.g. issue happens only occasionally):**
The issue only happens when there is a % character in the command Line of a command.
If I delete the % in the command Line, the describe arguments window shows up normally.

**Comment by leoncx** [comment]
@jdelvecchio Can you test in version 2.8.4 of Centreon Web. 

I am tried your command, it's working for me.

**Comment by julienmathis** [comment]
Hello, 

Can we have a feedback ? 

Thanks

**Comment by jdelvecchio** [comment]
Still got the problem after upgrade, so I searched a little bit deeper.

It is firewall related, our IPS blocks the request with the message 'Invalid escaped char in URL' caused by the addition of the character  '%' in the command-line.

This is the exact request that is considered malicious for the reason above :

http://monitoring.society.com/centreon/include/configuration/configObject/command/formArguments.php?cmd_line=$USER1$/check_snmp_storage.pl%20-H%20$HOSTADDRESS$%20-l%20$ARG1$%20-x%20$ARG2$%20%20-X%20$ARG3$%20-L%20$ARG4$%20-e%20-m%20%27$ARG5$%27%20-q%20FixedDisk%20-w%20$ARG6$%%20-c%20$ARG7$%%20-f&textArea=

Sorry I didn't consider the firewall first, hope you guys didn't put too much work into trying to resolve that issue on the application-side.

I guess the issue can be closed, thanks again !

**Comment by thiuyendang** [comment]
Not reproduced in 2.8.5 centOs6/7.
