### ISSUE TITLE
Duplicate Poller and illegal characters

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4931]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

**Steps to reproduce the issue:**
1. Duplicate a poller from poller list
2. The engine configuration is also duplicated

**Describe the results you received:**
In engine configuration, i have a wrong illegal characters configuration. Like:
```
~!$%^&amp;*&quot;|&#039;&lt;&gt;?,()=
```

**Describe the results you expected:**
I should have a good illegal character configuration
```
~!$%^&*"|'<>?,()=
```

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by rsliotta** [comment]
Hello. This is NOT working.  Please see the post entitled 'Version 2.8.5 - Hostgroup and Servicegroup' in the forum under Centreon Web Interface

**Comment by bbnono** [comment]
Hi, 
I just upgrade from 2.8.4 to 2.8.6 and the problem (solve one mouth ago by edit in db) is back.
Did this ticket was really solve ?
