### ISSUE TITLE
[2.8] Reporting for service

### ISSUE THREAD

**Issue by Gleamix** [centreon/centreon#4934]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Reporting - Dashboard
2. Select a host which has services configured
3. Click one of its services

**Describe the results you received:**
There is a display problem, graph is misaligned so timeline is stuck to the right

![image](https://cloud.githubusercontent.com/assets/25056830/22463352/820e8cde-e7b1-11e6-8510-44f064568cb1.png)

**Describe the results you expected:**
Get same display than host monitoring

**Additional information you think important (e.g. issue happens only occasionally):**
Since 2.8.1

**Comment by maksimatveev** [comment]
I confirm that there is a problem with displaying. This report is for services.
