### ISSUE TITLE
Column "conf changed" problem 2.8.x

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon#4935]
Hi,

When I add a service directly to a host in Configuration/Services, every poller's "Conf Changed" property change to YES and not only the affected poller.

**Comment by lpinsivy** [comment]
Hi,

Can you use the template to create issue (indicates Centreon Web version, Os version, ...)

Regards,

**Comment by julienmathis** [comment]
Hello, 

Sorry, I can't reproduce your problem on version 2.8 of the web component. Can you confirm that you are on version 2.7 ? 

Thanks

**Comment by Tomszy** [comment]
No.  We are using 2.8.4. And we still have this issue.

**Comment by lpinsivy** [comment]
linked to #4570
