### ISSUE TITLE
[2.8.3] Multiple engine configuration when using broker wizard

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#4936]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware Workstation 12

**Steps to reproduce the issue:**
1. In 'Configuration > Pollers > Broker configuration', use the wizard
2. Create broker configuration for Central

**Describe the results you received:**
The 3 configurations for the broker are created, but also 3 engine configurations named liked the broker configurations as "Centreon Engine central-broker-master

**Describe the results you expected:**
Only the broker configurations should be created

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
same than #4925 ?

**Comment by cgagnaire** [comment]
Damn, right...
