### ISSUE TITLE
[2.8.x] Wrong graph scale

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4939]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.3

**Steps to reproduce the issue:**
1. Need a service which check a disk (like 200GB) with small difference

**Describe the results you received:**
![courbe](https://cloud.githubusercontent.com/assets/9079781/22506794/ad5c340a-e882-11e6-968c-51bb0d2a0e73.png)

As you can, i can't get the difference between values. If i go to the graph, i always see the same value (like 47,6GB)

**Describe the results you expected:**
A different scale.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
should be corrected
