### ISSUE TITLE
Rediriger les requète HTTP vers HTTPS lorsque l'on se connecte au GUI de Centreon Central.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#494]
---

Author Name: **Sébastien Boulianne** (Sébastien Boulianne)
Original Redmine Issue: 6168, https://forge.centreon.com/issues/6168
Original Date: 2015-03-02
Original Assignee: Julien Mathis

---

Bonjour,

Je crois que ca serait une bonne idée de permettre la connexion HTTPS seulement sur le GUI du Centreon Central.
Je crois que ce tuto devrait être implenté dans la prochaine version de Centreon pour plus de sécurité
http://gtsup.fr/supervision/connexion-securisee-https-sur-nagios-et-centreon/

Qu'en pensez-vous ?

Merci!

Sébastien

**Comment by julienmathis** [comment]
C'est un problème d'intégration et de configuration de Apache. Rien de possible dans la version officielle.
