### ISSUE TITLE
[2.8.x] Graph and wrong export in number of curves

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#4940]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.x

**Steps to reproduce the issue:**
1. Have a service with two perfdatas (can be more)

**Describe the results you received:**
I select only curve. When i export the graphics, i have a png with all curves.

**Describe the results you expected:**
i should have a png with curves selected

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
corrected
