### ISSUE TITLE
[2.8.3] Centreon Graphs not appear since update of Centreon

### ISSUE THREAD

**Issue by Ale171** [centreon/centreon#4941]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2..8.3

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: CES

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Monitoring Section
2. Select a graph

**Describe the results you received:**

No graphs appear since the update of Centreon CES 3.2 to CES 3.4

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

I do not understand how graphics work under Centreon. My supervision works correctly but not graphics

**Comment by julienmathis** [comment]
Hello, 

Do you have error in broker logs ?

Do you have javascript error ?

Regards

**Comment by nowx-gh** [comment]
Have the same issure right now.
centreon web 2.8.4
broker 3.0.3
engine 1.7.0

I get a javascript error everytime  i hoover over the mini graphs in "Monitoring -> Status Details".
The same error appears when i load the performance charts. No graph is shown.

No error in broker logs.

Java-Script error:

`Uncaught Error: x is not defined for id = "data1".
    at https://nsm11.lsag.net/centreon/include/common/javascript/charts/c3.min.js:2:11673
    at Array.forEach (native)
    at e.i.convertDataToTargets (https://nsm11.lsag.net/centreon/include/common/javascript/charts/c3.min.js:2:11630)
    at e.i.initWithData (https://nsm11.lsag.net/centreon/include/common/javascript/charts/c3.min.js:1:8544)
    at e.i.init (https://nsm11.lsag.net/centreon/include/common/javascript/charts/c3.min.js:1:5736)
    at new d (https://nsm11.lsag.net/centreon/include/common/javascript/charts/c3.min.js:1:307)
    at Object.k.generate (https://nsm11.lsag.net/centreon/include/common/javascript/charts/c3.min.js:1:5147)
    at CentreonGraph.initGraphMetrics (https://nsm11.lsag.net/centreon/include/views/graphs/javascript/centreon-graph.js:173:23)
    at CentreonGraph.initGraph (https://nsm11.lsag.net/centreon/include/views/graphs/javascript/centreon-graph.js:104:14)
    at https://nsm11.lsag.net/centreon/include/views/graphs/javascript/centreon-graph.js:52:12`

**Comment by julienmathis** [comment]
hello, 

Do you have error in error_log log file of Apache server ? 

Thanks

**Comment by nowx-gh** [comment]
no errors in apache error.log

Seems there is a "NaN" (not a number) error somewhere. Maybe thats the key.

![2017-02-14_20h52_12](https://cloud.githubusercontent.com/assets/15085166/22946538/fa071a84-f2f7-11e6-8ccd-ad8ab4c8f2d8.png)

**Comment by Ale171** [comment]
Hi,

Sorry for late,

I get an error in central-broker-master.log :

![image](https://cloud.githubusercontent.com/assets/24827386/23115372/b4a50d10-f744-11e6-9bb3-411e03c7d38f.png)

No error in error_log and no java-script error.

I have an other error if i click on graphs :+1:

**Comment by Ale171** [comment]
Hello,

I'm looking in /var/lib/centreon/metrics and i saw that my rrd files are no longer update since the last update of Centreon. I think the problem comes from here, why my rrd files are no longer update ?

**Comment by Sims24** [comment]
Hi @Ale171 , 

Can you perform the following command : 

`rrdtool dump xxx.rrd
`
and confirm that your data source name is "value" (at the very beginning of the output of the previous command). 

Regards

**Comment by Sims24** [comment]
@Ale171 

Also check that this commande return two lines, one containing rrd and the other containing sql.

`ps aux | grep cbd
`
Here your rrd broker isn't running because it should listen on 5670 tcp port locally.

**Comment by Ale171** [comment]
Hi @Sims24 

Thanks for your reply,

`ps aux | grep cbd`

`496      16681  0.9  0.6 1698696 26624 ?       Sl   09:42   0:13 /usr/sbin/cbd /etc/centreon-broker/central-broker.xml
496      16682  0.2  1.0 637720 42312 ?        Sl   09:42   0:02 /usr/sbin/cbd /etc/centreon-broker/central-rrd.xml
`

And the 2nd command :

`rrdtool dump xxx.rrd`

![image](https://cloud.githubusercontent.com/assets/24827386/23158129/481dbb3a-f81e-11e6-8c5d-9dca4e36d420.png)

**Comment by Sims24** [comment]
what does 

`netstat -plantu | grep cbd`

returns ?

**Comment by Ale171** [comment]
`netstat -plantu | grep cbd`

`tcp        0      0 0.0.0.0:5669                0.0.0.0:*                   LISTEN      16681/cbd`
`tcp        0      0 0.0.0.0:5670                0.0.0.0:*                   LISTEN      16682/cbd`
`tcp        0      0 IPCentral:5669          IPPoller1:54792         ESTABLISHED 16681/cbd`
`tcp        0      0 IPCentral:60862         IPPoller2:3306          ESTABLISHED 16681/cbd`
`tcp        0      0 IPCentral:5669          IPPoller3:46032          ESTABLISHED 16681/cbd`
`tcp        0      0 IPCentral:5669          IPPoller4:38309         ESTABLISHED 16681/cbd`
`tcp        0      0 IPCentral:60856         IPDatabase:3306          ESTABLISHED 16681/cbd`


I saw in central-rrd-master.log :

`[1487668154] error:   RRD: failed to update value in file '/var/lib/centreon/status/2418.rrd': opening '/var/lib/centreon/status/2418.rrd': Permission non accordée`
`[1487668184] error:   RRD: failed to update value in file '/var/lib/centreon/status/2186.rrd': opening '/var/lib/centreon/status/2186.rrd': Permission non accordée`

**Comment by Sims24** [comment]
permission issue. 

you should check that rrd files have 664 mask and belong to centreon or centreon-broker users. Also directories above.

**Comment by Ale171** [comment]
ls -l /var/lib/centreon/metrics

-rw-r--r-- 1 root root 450088 2 févr. 14:28 999.rrd

if i put centreon-broker centreon-broker with chown instead of root root does it work ?

**Comment by Sims24** [comment]
sure

**Comment by Ale171** [comment]
It works !

Thx @Sims24 !

**Comment by nowx-gh** [comment]
Any idea for my javascript error?

My RRD files are correct, if i download through centreon-web the graph is just fine.

**Comment by Sims24** [comment]
@nowx-gh 

not really .. could you try this query against your monitoring db : 

`SELECT len_storage_rrd , len_storage_mysql FROM centreon_storage.config`

**Comment by nowx-gh** [comment]
@Sims24 sure and thx for trying.
```
MariaDB [centreon_storage]> SELECT len_storage_rrd , len_storage_mysql FROM centreon_storage.config
    -> ;
+-----------------+-------------------+
| len_storage_rrd | len_storage_mysql |
+-----------------+-------------------+
|               3 |                 3 |
+-----------------+-------------------+
1 row in set (0.00 sec)

MariaDB [centreon_storage]> use centreon;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [centreon]> SELECT len_storage_rrd , len_storage_mysql FROM centreon_storage.config;
+-----------------+-------------------+
| len_storage_rrd | len_storage_mysql |
+-----------------+-------------------+
|               3 |                 3 |
+-----------------+-------------------+
```

**Comment by Sims24** [comment]
@nowx-gh 

Strange, you want to keep 3 days of rrd and mysql ? or you meant month when you have set 3 ?

Don't think it's the issue but ... could you paste result of : 

ls -lha /var/lib/centreon/metrics/*

few line should be ok. 

Thanks

**Comment by nowx-gh** [comment]
3 days was just a test. I kept 180days, millions of sql lines.
thought maybe thats the problem, so I shrunk it to 3 days bat problem still exists.

````
root@nsm11:~# ls -lha /var/lib/centreon/metrics/*
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:17 /var/lib/centreon/metrics/191.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:17 /var/lib/centreon/metrics/192.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:17 /var/lib/centreon/metrics/193.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:17 /var/lib/centreon/metrics/194.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:18 /var/lib/centreon/metrics/195.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:18 /var/lib/centreon/metrics/196.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:18 /var/lib/centreon/metrics/197.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:18 /var/lib/centreon/metrics/198.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:15 /var/lib/centreon/metrics/199.rrd
-rw-rw-r-- 1 centreon        centreon        440K Sep 23 10:25 /var/lib/centreon/metrics/1.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:15 /var/lib/centreon/metrics/200.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:15 /var/lib/centreon/metrics/201.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:15 /var/lib/centreon/metrics/202.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:16 /var/lib/centreon/metrics/203.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:16 /var/lib/centreon/metrics/204.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:16 /var/lib/centreon/metrics/205.rrd
-rw-r--r-- 1 centreon-broker centreon-broker 440K Feb 21 13:16 /var/lib/centreon/metrics/206.rrd
```

**Comment by Sims24** [comment]
@nowx-gh sry but looks like rrd are updated, probably a full web issue, @julienmathis  will help you better than me on this ;) 

did you upgrade you're centreon ? from which version ?

**Comment by nowx-gh** [comment]
@julienmathis 2.7.x (ok) -> 2.8.3 (not ok) -> 2.8.4 (not ok)

within 2.7.x graphs were shown just fine.
as I mentioned above, downloading the rrds through centreon-web is wokring fine. so RRDs getting updated. no broker errors. seems javascript or something wrong in my DB (Not a Number, NaN)

**Comment by nowx-gh** [comment]
@julienmathis 
@Sims24 

found the problem.
I'm using rrdtol 1.5.5 (Ubuntu 16.04.2 LTS)

xport from rrd returns "NaN" instead of unix time.
With rrdtool 1.4.7 (Centreon VM) xport returns correct unixtime. 

for testing purposes I used the rrdtool commandline options generated by ```centreonGraphServices.class.php```

example command:
```
/usr/bin/rrdtool xport  --start 1487797256 --end 1487883656 --maxrows 10 DEF:v0=/var/lib/centreon/metrics//14.rrd:value:AVERAGE XPORT:v0:v0
```

output (version 1.5.5)
```
<?xml version="1.0" encoding="ISO-8859-1"?>

<xport>
  <meta>
    <start>1487808000</start>
    <end>1487894400</end>
    <step>10800</step>
    <rows>8</rows>
    <columns>1</columns>
    <legend>
      <entry>v0</entry>
    </legend>
  </meta>
  <data>
    <row><v>NaN</v></row>
    <row><v>NaN</v></row>
    <row><v>NaN</v></row>
    <row><v>NaN</v></row>
    <row><v>NaN</v></row>
    <row><v>NaN</v></row>
    <row><v>NaN</v></row>
    <row><v>NaN</v></row>
  </data>
</xport>
```


output (version 1.4.7)
```
<?xml version="1.0" encoding="ISO-8859-1"?>

<xport>
  <meta>
    <start>1487808000</start>
    <step>10800</step>
    <end>1487808000</end>
    <rows>9</rows>
    <columns>1</columns>
    <legend>
      <entry>v0</entry>
    </legend>
  </meta>
  <data>
    <row><t>1487808000</t><v>NaN</v></row>
    <row><t>1487818800</t><v>NaN</v></row>
    <row><t>1487829600</t><v>NaN</v></row>
    <row><t>1487840400</t><v>NaN</v></row>
    <row><t>1487851200</t><v>NaN</v></row>
    <row><t>1487862000</t><v>NaN</v></row>
    <row><t>1487872800</t><v>NaN</v></row>
    <row><t>1487883600</t><v>NaN</v></row>
    <row><t>1487894400</t><v>NaN</v></row>
  </data>
</xport>
```

is there anything else i can do? open feature request or something like that?

**Comment by Ale171** [comment]
Hi,

Can you checked rights of rrd files ?

`ls -l /var/lib/centreon/metrics`

You must have this : 

`-Rw-r--r-- centreon-broker centreon-broker 450088 09 mai 998.rrd`

If you not have rw-r--r-- and centreon-broker centreon-broker, the problem comes from here i think.

**Comment by Ale171** [comment]
Hi,

Can you checked rights of rrd files ?

ls -l /var/lib/centreon/metrics

You must have this :

-Rw-r--r-- centreon-broker centreon-broker 450088 09 mai 998.rrd

If you not have rw-r--r-- and centreon-broker centreon-broker, the problem comes from here i think.

**Comment by barte91** [comment]
Hi Ale171,

Thanks for your reply,I already check my permission on metrics and are ok


```
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8339.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8340.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8341.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8342.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8343.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8344.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8345.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8346.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8347.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8348.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8349.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8350.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8351.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8352.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8353.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8354.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8355.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8356.rrd
-rw-rw-r-- 1 centreon-broker centreon-broker 2247208 May  9 08:33 8357.rrd
```

**Comment by Ale171** [comment]
And for this : 

`ls -l /var/lib/centreon/`

You must have this : 

`drwxrwxr-x. 2 centreon centreon 94208 22 mai 08:39 metrics`
`drwxrwxr-x. 2 centreon centreon 102400 22 mai 08:39 status`

**Comment by barte91** [comment]
Yes, All rights are ok:

```
ls -l /var/lib/centreon
drwxrwxr-x  2 centreon centreon   4096 May  5 10:04 broker-stats
drwxrwxr-x. 2 centreon centreon   4096 May  3 15:19 centcore
drwxrwxr-x. 2 centreon centreon  61440 May  3 15:19 centplugins
drwxrwxr-x. 2 centreon centreon   4096 May  3 15:19 log
drwxrwxr-x. 2 centreon centreon 253952 May  3 15:19 metrics
drwxrwxr-x. 5 centreon centreon   4096 May  3 15:19 nagios-perf
drwxrwxr-x. 2 centreon centreon   4096 May  3 15:19 perfdata
drwxrwxr-x. 2 centreon centreon  69632 May  3 15:19 status

```

**Comment by barte91** [comment]
I resolve my problem, I delete the old metrics and RRD files and now I see the graphs
Thanks for support

**Comment by slytara** [comment]
@nowx-gh: Have you solved your problem. I have exactly the same 
Regards
