### ISSUE TITLE
[2.8.3] Generate conf error

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4942]
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

**Centreon Engine version**:  centreon-engine-1.7.0-2.el6.x86_64

**Centreon Broker version**: 

**OS**:  CES 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1. Generate configuration files in pollers view
2.
3.

**Describe the results you received:**
[ - ] Central
Reading main configuration file '/usr/share/centreon/filesGeneration/engine/1/centengine.DEBUG'.
Reading resource file '/usr/share/centreon//filesGeneration/engine/1/resource.cfg'
**Cannot resolve service escalation**
Checking global event handlers...
Checking obsessive compulsive processor commands...

Checked 73 commands.
Checked 2 connectors.
Checked 11 contacts.
Checked 0 host dependencies.
Checked 22 host escalations.
Checked 36 host groups.
Checked 156 hosts.
Checked 0 service dependencies.
Checked 96 service escalations.
Checked 4 service groups.
Checked 799 services.
Checked 5 time periods.

Total Warnings: 0
Total Errors: 1

**Describe the results you expected:**
... Files generateds

**Additional information you think important (e.g. issue happens only occasionally):**
Happened after a lot of updates in web configurator
How can I find where is the error ?

Thank you

**Comment by gslongo** [comment]
Dear team,

Any follow up on this ?

Thanks !

**Comment by julienmathis** [comment]
Hello, 

Can you give us information regarding your problem ?

**Comment by ganoze** [comment]
@gslongo Ideally, could you provide the generated configuration directory /usr/share/centreon//filesGeneration/engine/1/ ?

**Comment by gslongo** [comment]
Hi,
I don't really know what happend. What I did is : I disabled all the hosts I've added  => This solved the conf generation
After that I reactivated all the hosts one by one in order to locate which one is causing the issue. I finally reactivated all the hosts and the conf generation is now OK.. it seems ... o_O

**Comment by ganoze** [comment]
Alright. Your issue being solved I will now close this ticket.

Should the bug happend again, feel free to reopen this ticket or create a new one.

In all cases, thank you for your feedback that helps make Centreon better :-)

**Comment by flippym** [comment]
Hi, I'm having the same error in the generated configuration, after updated the software. 

It seems to be due to the newly created $CENTREONPLUGINS$ in Configurations > Pollers > Resources, which is created without any value.

**Comment by ganoze** [comment]
@flippym I cannot think of any direct link between the CENTREONPLUGINS macro and service escalations errors. Could you provide your /usr/share/centreon//filesGeneration/engine/ directory to ensure that I am not mistaken ?

If your error is not precisely **Cannot resolve service escalation**, feel free to open a new issue.
