### ISSUE TITLE
Massive Change on Hosts activate Stalking Option Up

### ISSUE THREAD

**Issue by leo29041982** [centreon/centreon#4946]
-------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3 
**OS**:  Debian Jessie

**Steps to reproduce the issue:**
if i edit one Option via Configuration  >  Hosts -> Massive Changes, automaticly "Stalking Options	Up" is checked.

**Comment by lpinsivy** [comment]
Still present in testing version centreon-web-2.8.5-1488975989.8ab7d7d
