### ISSUE TITLE
[BUG] Recurrent Downtimes Display

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4947]
----------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.3
**Centreon Engine version**: 1.7.0
**Centreon Broker version**: 3.0.3
**OS**: CentOS 6.8

**Steps to reproduce the issue:**
1. Open "Monitoring - Downtimes - Recurrent Downtimes"
2. Add a new downtime with service relation
3. Save
4. Open "Monitoring - Downtimes - Recurrent Downtimes"
5. Recurrent downtime does not appear

**Describe the results you received:**
In "Monitoring - Downtimes - Recurrent Downtimes", all downtimes should be present

**Describe the results you expected:**
In "Monitoring - Downtimes - Recurrent Downtimes" are only recurrent downtimes for hosts.

**Additional information you think important (e.g. issue happens only occasionally):**
In URL, there is " &type=h " : 
`http://10.30.1.2/centreon/main.php?p=21003&type=h`

To correct it, you must run the following command in base 'centreon : 
`UPDATE topology SET topology_url_opt='' WHERE topology_page=21003;`

**Comment by julienmathis** [comment]
Fixed by #5001
