### ISSUE TITLE
[2.8.3]  SSO Only does not work

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#4948]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: CentOS Centreon 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual Machine VMware

**Steps to reproduce the issue:**
1. After activating the mode SSO Only 

**Describe the results you received:**
I can still log on to Centreon without SSO authentication

**Describe the results you expected:**
After the previous version I could not connect, see the screenshot
![install_glpi2017-02-07_03-26-33_pm](https://cloud.githubusercontent.com/assets/12350746/22695100/d6527ccc-ed49-11e6-902d-62b59f2fb173.png)

**Additional information you think important (e.g. issue happens only occasionally):**
Otherwise the mixed mode SSO works well

**Comment by lpinsivy** [comment]
Its seams that Apache doesn't provide login to Centreon to authenticate user
