### ISSUE TITLE
CLAPI Error message "PHP Warning:  Cannot stat license file:"

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4949]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.3
**Centreon Engine version**: 
1.7
**Centreon Broker version**: 
3.0.3
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
With a centreon 3.4 fresh install, type /usr/share/centreon/bin/centreon -u admin -p centreon

**Describe the results you received:**
The following message appears: 
"PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on line 0"

**Describe the results you expected:**
The message shouldn't be displayed. 

**Additional information you think important (e.g. issue happens only occasionally):**
To solve the problem we need to delete the line "/usr/share/centreon/www/modules/centreon-pp-manager/license" in the file "/etc/php.d/zendguard.ini"

**Comment by sharky172** [comment]
+1

**Comment by julienmathis** [comment]
Hello, 

Can you update the pp-manager module. This problem has been fixed. 

Regards

**Comment by sharky172** [comment]
thanks
