### ISSUE TITLE
Rotation log centreontrapd

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#495]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 6437, https://forge.centreon.com/issues/6437
Original Date: 2015-06-18

---

Sur les serveurs satellites, les logs de centreontrapd ne sont pas automatiquement logroté, ce qui peut saturer /var/log/ assez rapidement.

Pour corriger ce problème : 

- Ajouter /etc/logrotate.d/centreon
- Ce fichier contient :

/var/log/centreon/*.log {
compress
daily
notifempty
missingok
rotate 7
size 20M
}

**Comment by Tpo76** [comment]
le fichier centreon-2.6.2/logrotate/centreontrapd ne c'est pas installé à la mise à jour.
Sinon la configuration du fichier est bonne.
