### ISSUE TITLE
[2.8.4] Problem with removal of service/host

### ISSUE THREAD

**Issue by Dodofox** [centreon/centreon#4950]
Hi,

I have a problem but i really don't know if it's a mistake in my configuration or an issue in centreon. 

When i delete a service, or a host, the service still be in the monitoring page. And still be monitored. When i redeploye service from host, in configuration page i can see the service two times, but only one time in the monitoring page....

**Comment by Dodofox** [comment]
Since the last update 2.8.4-5 the problem is partially resolved.

Now when i'm delete a service, after poller deployment the service is correctly removed from monitoring page. 

But, When i'm delete a Service and recreate it by clicking on "deploy service" from host configuration. That Service which i removed before could be seen twice on service configuration, but only one time on monitoring page.

**Comment by lpinsivy** [comment]
Hi,

correct on Centreon web 2.8.6. Just a problem with listing of services
