### ISSUE TITLE
[Enhancement] Downtimes - Display of deleted downtimes

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4953]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.3
**Centreon Engine version**: 1.7.0
**Centreon Broker version**: 3.0.3

**Steps to reproduce the issue:**
1. Add a downtime in "Monitoring - Downtimes - Downtimes"
2. In "Start Time" indicate a date in the future
3. Save
4. Cancel this downtime "Monitoring - Downtimes - Downtimes"

**Describe the results you received:**
Downtime remains displayed until the "start time" planned

**Describe the results you expected:**
Downtime should be deleted directly and no longer be displayed 

Best Regards

**Comment by julienmathis** [comment]
Problem reproduce. This problem come from Broker or Engine. Not the UI.

**Comment by ganoze** [comment]
More specifically the issue comes from Centreon Broker that was not properly setting the cancellation flag on downtimes that were removed without being started. This should be fixed with the upcoming 3.0.4 release of Centreon Broker that will be released along Centreon Web 2.8.5.
