### ISSUE TITLE
[BUG] "Home > Poller Statistics > Graphs" only works for Central

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#4954]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.3
**Centreon Engine version**: 1.7.0
**Centreon Broker version**: 3.0.3

**Steps to reproduce the issue:**
1. Go in "Home > Poller Statistics > Graphs" menu
2. In "Poller" filter, choose any poller except 'Central'

**Describe the results you received:**
Page always returns to the page of the graphs of 'Central'

**Describe the results you expected:**
Pollers graphs should be displayed

Best Regards

**Comment by f-amundi** [comment]
Bonjour,

Petit détail supplémentaire, lorsque l'on définit dans la configuration d'un poller X l'option "Localhost ?" à "Yes", c'est ce poller X qui est choisi par défaut dans la vue "Home > Poller Statistics > Graphs".

Lorsque l'on choisi un autre poller Y, on revient toujours sur le poller X.
Centreon 2.8.4

Cdt,

**Comment by BlackstormFirst** [comment]
In addition, i have multiple time the same poller name into the list (probably from old pollers install that were created with the same name but actually deleted)

CentWeb: 2.8.4
CentEngine: 1.7.0
CentBroker: 3.0.3

**Comment by lpinsivy** [comment]
Hi,

In your configuration do you enable "Enable Broker Statistics Collection" option in "Administration  >  Parameters  >  CentCore" menu and restart centcore process ?

Moreover, do you enable "Statistics" option in Centreon Broker definition on "General" tab and generate/export/restart poller?

Regards,

**Comment by lpinsivy** [comment]
The bug is when you select another item, page reload with "Central" default value.

**Comment by f-amundi** [comment]
Hello,

In my case both option are enabled. The real problem is when you have multiple pollers, only the 'Central' poller is displayed. When you select another poller in the list, it automatically goes back to the 'Central' poller.

**Comment by cgagnaire** [comment]
Fixed in 2.8.9.
