### ISSUE TITLE
"Executed Check Command Line" is wrong for services associated to hostgroups

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon#4955]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4-4.el6

**Centreon Engine version**: 1.7.0-2.el6

**Centreon Broker version**: 3.0.3-4.el6

**OS**: CES

**Steps to reproduce the issue:**
1. Create a service associated to a hostgroup containing multiple hosts
2. Check the value of "Executed Check Command Line" for all hosts

**Describe the results you received:**
"Executed Check Command Line" is the same for all services. The macros seem to be expanded from the first host of the hostgroup.

**Describe the results you expected:**
The HOST macros should be expanded correctly, resulting in the right command line being shown.

![bug](https://cloud.githubusercontent.com/assets/4833332/22735022/33a6921a-edf8-11e6-8487-4d6567e12d10.png)

**Comment by leo29041982** [comment]
Problem: No Host selected...
file: www\include\monitoring\objectDetails\serviceDetails.php
old: 
`$service_status["command_line"] = hidePasswordInCommand($service_status["check_command"], $service_status["service_id"]);`
new: 
`$service_status["command_line"] = hidePasswordInCommand($service_status["check_command"], $service_status["service_id"], $host_id);`

file: www\include\monitoring\objectDetails\common-func.php
old: 
`function hidePasswordInCommand($command_name, $service_id)`
new: 
`function hidePasswordInCommand($command_name, $service_id, $host_id)`

old: 
`$query_command_name = "SELECT host_id, check_command, command_line FROM services WHERE service_id = '".$service_id."'";`
new: 
`$query_command_name = "SELECT host_id, check_command, command_line FROM services WHERE host_id = '".$host_id."' AND service_id = '".$service_id."'";`

**Comment by sbraz** [comment]
@leo29041982 Nice, you should make a PR I guess :)

**Comment by julienmathis** [comment]
Thanks a lot for your fix !
