### ISSUE TITLE
Unexpected STDERR output from centreon CLI command

### ISSUE THREAD

**Issue by hecko** [centreon/centreon#4956]
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  v. 2.7.8 

**Centreon Engine version**: n/a

**Centreon Broker version**: n/a

**OS**: CES 3.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMW

**Steps to reproduce the issue:**
1. Disable  centreon-bam-server module in centreon web interface which has expired license
2. Run centreon api from CLI: centreon -u clapi -p testtest -o SERVICE -a SHOW
3. output in stderr: PHP Warning:  The license has expired (license file: /usr/share/centreon/www/modules/centreon-bam-server/license/merethis_lic.zl) in Unknown on line 0

**Describe the results you received:**
The stderr should not contain the warning as the BAM module is disabled in centreon web interface

**Describe the results you expected:**
Possibly information in stdout, but not in stderr

**Additional information you think important (e.g. issue happens only occasionally):**
difficult to automate anything with `centreon` cli command if unexpected outputs are present in stderr

**Comment by julienmathis** [comment]
Sorry, this error is managed by PHP, not Centreon. This error is displayed when PHP is starting. 

Please ask for a new licence or remove the path of BAM in zend configuration file.

**Comment by hecko** [comment]
This breaks api when license expires. Im not sure this is the best practice
approach.

Dňa 13.2.2017 11:45 PM používateľ "Julien Mathis" <notifications@github.com>
napísal:
