### ISSUE TITLE
"View logs for service XXX" doesn't work

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#4958]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Steps to reproduce the issue:**
1. Go on "Monitoring" page
2. Click on a service
3. Click on "View logs for service XXX"
4. Select a period and click on "Apply period"

**Describe the results you received:**
I see all hosts and services

**Describe the results you expected:**
I would like to see only the service I select

**Comment by julienmathis** [comment]
Hello, 

It work's for me. Is the user admin or not ?

**Comment by s-duret** [comment]
Hello,

Yes I'm admin and I tested that on two platforms

**Comment by julienmathis** [comment]
Ok I found
