### ISSUE TITLE
Blank page on Monitoring>Status Details>Hosts with acl

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#4960]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.3
**Centreon Engine version**: 
1.7
**Centreon Broker version**: 
3.0.3
**OS**: 
Centreon

**Steps to reproduce the issue:**
1. Login with a non-admin user
2.Go to the page Monitoring  >  Status Details  >  Hosts and clik on the graph logo (next to the hostname) or on the name of the host and then on "View graphs for host x"
3. An empty page is displayed

**Describe the results you received:**
An empty page

**Describe the results you expected:**
You shoud see the graph of the host

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by kduret** [comment]
licked commit : 4c9d3bfc4c6aeac40e3327fc69f0fb086cb1328c
