### ISSUE TITLE
From Centreon web centreon-engine does not get reloaded/restarted

### ISSUE THREAD

**Issue by anzevi** [centreon/centreon#4962]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: Centos 7.2 and Centos 7.3

**Additional environment details (AWS, VirtualBox, physical, etc.):** VirtualBox

**Steps to reproduce the issue:**
1. Fresh install of Centreon
2. do any kind of change (create host, service, command, whatever...)
3. Export configuration and restart/reload engine

**Describe the results you received:**
engine reload/restart (`tail -f /var/log/centreon-engine/centengine.log`)

**Describe the results you expected:**
engine is not reloaded/restarted 
I can see the changes that I made in local files in `/etc/centreon-engine/`, but they are not applied since the engine is not reloaded/restarted.

**Additional information you think important (e.g. issue happens only occasionally):**
This was working ok on 2.8.1 and 2.8.2 (not sure about 2.8.3) but it's not working on 2.8.4 (tried upgrade from 2.8.3 ==> 2.8.4 and clean install of 2.8.4)
I checked manually entries in `sudoers.d/centreon` and tested manually with sudo and it works. But it does not work when reloading/restarting from centreon web. (same goes for local and remote poller)

**workaround:** created post generation command to sudo restart the engine

**Comment by julienmathis** [comment]
Hello 

a new version of Centreon Web has been released : 2.8.4-5. Can  you update your rpm ?

Thanks

**Comment by anzevi** [comment]
> a new version of Centreon Web has been released : 2.8.4-5. Can you update your rpm ?

sorry, I updated bug report with the minor versions as well. I had the `2.8.4-5` version so the problem is in this version as well.

**Comment by cgagnaire** [comment]
Works for me with this configuration in for my poller definition : 
Monitoring Engine Init Script : centengine / systemd

**Comment by anzevi** [comment]
> Monitoring Engine Init Script : centengine / systemd

This did the trick. Thank you.

**Comment by luanaqa** [comment]
Hello,

I have the same issue. 

I upgrade centreon web from 2.8.7 to 2.8.8, than 2.8.9, but not works for me.

When I add host or add service and deploy the configuration restarting the centengine from WebUI, ( Monitoring Engines > Actions > Option "Restart Monitoring Engine"), it's not works.

Information regarding sudoers: /etc/sudoers.d/centreon

## BEGIN: CENTREON SUDO

User_Alias      CENTREON=%centreon
Defaults:CENTREON !requiretty

# centreontrapd
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd *

# Centreon Engine
CENTREON   ALL = NOPASSWD: /sbin/service centengine start
CENTREON   ALL = NOPASSWD: /sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -v *
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine *

# Centreon Broker
CENTREON   ALL = NOPASSWD: /sbin/service cbd start
CENTREON   ALL = NOPASSWD: /sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd *

## END: CENTREON SUDO
