### ISSUE TITLE
CentWeb 2.8.4 / Disable sound not working

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon#4973]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**OS**: Debian 8.7 - Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linu

**Additional environment details (AWS, VirtualBox, physical, etc.):** Vm on VMware Esxi 6.5

**Steps to reproduce the issue:**
1. On the web interface click on the icon to disable the sound on notification (the icon switch) but if you receive a new notification, the sound is played.
2. click on another menu or refresh the page, the icon back to the classic sound notification, as if you never disable it.
3. Same issue for the "edit mode" icon on the main page.

**Describe the results you received:**
1. sound not disabled and choice not saved.
2. edit mode always enabled on the main page.

**Describe the results you expected:**
1. When you click to disable sound, it should disable the sound and the selection should be retained from this page to others.
2. When you click on the "edit mode" icon, buttons should not be displayed until you click another time on the "edit mode" icon.

**Additional information you think important (e.g. issue happens only occasionally):**
all time

**Comment by julienmathis** [comment]
Hello, 

Which browser ?

Thanks

**Comment by BlackstormFirst** [comment]
Hi,
I'm using Chrome Version 56.0.2924.87 (64-bit) without special extensions. (only addblock+ but enterely disabled for this host target)

**Comment by BlackstormFirst** [comment]
1/
Ok, from one of the last commit, someone add the following line into the file: www/include/monitoring/status/Notifications/notifications_action.php

--> session_write_close();

Comment this line or remove it to resolve the issue.
This commit refer to these modifications: https://github.com/centreon/centreon/commit/ab1b8a4b0296b14564336dbb1e0eefd58fc8b5ec

I think others files may also have this issue, not tested, but it should.

2/
For the "edit mode" issue i will take a look, i will check if something like that is linked.
