### ISSUE TITLE
No inheritance in query of notified contacts (Monitoring view)

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#4981]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
 2.8.3
**Centreon Engine version**: 
 3.0.3
**Centreon Broker version**: 
1.7.0
**OS**: 
 CentOS release 6.8 (Final)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Steps to reproduce the issue:**
1. Create a service/host based on a template.
2. Attach different contacts/contact-groups to the template and the host/service itself
3. Save and export the configuration
4. Go to the Monitoring View an click on a service/host
5. Look at the bottom-right box "Notification" in a service, or the corresponding box in the host within the "Host Information"-tab.

**Describe the results you received:**
You'll see the contacts/groups which are configured in the host/service. The inherited contacts/groups from the templates are not displayed.

**Describe the results you expected:**
I expect the same output as the "View notification for user"-button, found under `Configuration -> Users`. Here the notified contacts are queried correctly, with the inherited configuration of the attached templates.

**Comment by cgagnaire** [comment]
In 2.8.9, contacts/contacts groups defined on the templates will be shown wether or not you check the "additive inheritance" on the service. Same behaviour when you check the "Inherit only contacts/contacts group from host".
