### ISSUE TITLE
[Problem to restart Centengine after upgrade from Centreon v2.7.8  to  v2.8.4]

### ISSUE THREAD

**Issue by PhilCANDIDO** [centreon/centreon#4983]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: CentOS 6.8 64bits

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM on VMware ESxi 5.5

**Steps to reproduce the issue:**
1. Connect to ssh Centreon Central with centreon user
2. Execute command "$ /etc/init.d/centengine restart"
3. Result "Password:"

**Describe the results you received:**
ask password.

**Describe the results you expected:**
Restart centengine.

**Additional information you think important (e.g. issue happens only occasionally):**
The file "/etc/sudoers.d/centreon" is present and correctly informed.

# ll /etc/sudoers.d/centreon
-r--r----- 1 root root 1793 Feb 14 14:42 /etc/sudoers.d/centreon

The problem is also on all pollers in the infrastructure.

**Comment by BlackstormFirst** [comment]
Hello,
try with centreon-engine user not with centreon user.
For Debian the script is started with this user (if the soft was correctly compiled)

**Comment by PhilCANDIDO** [comment]
We are on CentOS distribution. 
The user use to execute the command is not centreon-engine, but is centreon (this the option in web interface).

The command is push to remote server by centcore process. We can see the messages in log file : 
2017-02-14 15:34:40 - Start: Send config files on poller 4
2017-02-14 15:34:40 - Result :
2017-02-14 15:34:40 - End: Send config files on poller 4
2017-02-14 15:34:40 - Start: Send Centreon Broker config files on poller 4
2017-02-14 15:34:40 - Result :
2017-02-14 15:34:40 - End: Send Centreon Broker config files on poller 4
sudo: no tty present and no askpass program specified
2017-02-14 15:34:40 - Init Script : 'sudo /etc/init.d/centengine restart' On poller 172.23.10.42 (4)

but the command result of the command is always : 
$ sudo /etc/init.d/centengine restart
[sudo] password for centreon:

**Comment by BlackstormFirst** [comment]
can you edit your /etc/sudoers.d/centreon plz ?
can you check into your init file the user and group used to start the process ?
Just to be sure.
It's clearly a right issue.
NB: I have no sudoers on my side on my central, only on pollers.
I am on CentWeb 2.8.4, Engine 1.7.0 and Broker 3.0.3 (on debian and Raspberry, without major issues)

-> i will try to help, but i need to go at a custumer for now, maybe back in hour.

**Comment by PhilCANDIDO** [comment]
I haven't tyhe problem on Centreon 2.8 fresh installation. The problem is only on installation after a upgrade freom centreon 2.7 to centreon 2.8.

I found the problem. It's located in /etc/sudoers.d/centreon.

Here the file after the upgrade : 
```
## BEGIN: CENTREON SUDO

User_Alias      CENTREON=%centreon
Defaults:CENTREON !requiretty

# centreontrapd
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd reload

# Centreon Engine
CENTREON   ALL = NOPASSWD: /sbin/service centengine start
CENTREON   ALL = NOPASSWD: /sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -v *

# Centreon Broker
CENTREON   ALL = NOPASSWD: /sbin/service cbd start
CENTREON   ALL = NOPASSWD: /sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd reload

## END: CENTREON SUDO
```

Because the initial Centreon installation was version 2.5, the init command is "/etc/init.d/centengine"

So I add the following commands and now the process work fine : 
```
## BEGIN: CENTREON SUDO

User_Alias      CENTREON=%centreon
Defaults:CENTREON !requiretty

# centreontrapd
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd reload
**CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd ***

# Centreon Engine
CENTREON   ALL = NOPASSWD: /sbin/service centengine start
CENTREON   ALL = NOPASSWD: /sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -v *
**CENTREON   ALL = NOPASSWD: /etc/init.d/centengine ***

# Centreon Broker
CENTREON   ALL = NOPASSWD: /sbin/service cbd start
CENTREON   ALL = NOPASSWD: /sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd reload
**CENTREON   ALL = NOPASSWD: /etc/init.d/cbd ***

## END: CENTREON SUDO
```
 thx for your help.

**Comment by PhilCANDIDO** [comment]
Issue is solved.

**Comment by julienmathis** [comment]
Hello Philippe, 

Can you update the centreon-web rpm in version 2.8.4-5 ? We fixed a packaging problem in the last version of the rpm.

Thanks

**Comment by jronzon** [comment]
Bonjour,

J'ai le même problème après avoir monté de version en 2.8.5 depuis la 2.7.8.
J'ai modifié le fichier sudoers.d/centreon en rajoutant les lignes avec /etc/init.d/... mais ça ne fonctionne toujours pas.
Log centcore.log : 
sudo: no tty present and no askpass program specified

cat /etc/sudoers.d/centreon
## BEGIN: CENTREON SUDO

User_Alias      CENTREON=%centreon
Defaults:CENTREON !requiretty

# centreontrapd
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd *

# Centreon Engine
CENTREON   ALL = NOPASSWD: /sbin/service centengine start
CENTREON   ALL = NOPASSWD: /sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -v *
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine *

# Centreon Broker
CENTREON   ALL = NOPASSWD: /sbin/service cbd start
CENTREON   ALL = NOPASSWD: /sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd *
## END: CENTREON SUDO

**Comment by Sims24** [comment]
Hi @jronzon 

Please ensure that only "centengine" is set as the init script parameter in "configuration > pollers".

If you have /etc/init.d/centengine it won't work, this behaviour has changed but /etc/init.d/ is not automaticaly removed.

**Comment by jronzon** [comment]
Configuration poller
 Script d'initialisation du moteur de supervision :	centengine
 Binaire du moteur de supervision	: /usr/sbin/centengine
 Binaire de statistiques du moteur de supervision	: /usr/sbin/centenginestats

**Comment by Sunseeker69** [comment]
I've the same issue from Centreon 2.8.4 to 2.8.8

**Comment by vhsantos** [comment]
Hi,

the bug is still unresolved on 2.8.24 (ISO installed).
when you go to Configuration > Pollers > Central and select the "Update Informations", you can see on logs this error.

to fix it, is necesary to add 

`CENTREON ALL = NOPASSWD: /usr/sbin/centengine *`

without the "-v" to centreon's sudores files.
