### ISSUE TITLE
[2.8.4] : Graph Split component is available in graph template, but not working!

### ISSUE THREAD

**Issue by PhilCANDIDO** [centreon/centreon#4990]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare ESXi 5.5

**Steps to reproduce the issue:**
1.In graph Template select "Split Components" options 

![image](https://cloud.githubusercontent.com/assets/13585152/22978788/6df86398-f394-11e6-8888-c11567ea2c4e.png)

2. In "Monitoring  >  Performances  >  Graphs" the graph is not splited.
![image](https://cloud.githubusercontent.com/assets/13585152/22978866/ac9d8380-f394-11e6-8635-b0b20c7fe774.png)

Read informations is very difficult. Unselect data source by clicking is very fastidious when you have a lot of data source.

**Comment by leoncx** [comment]
Hello,

We're working to find the best solution to display charts with a lot of metrics. Splitting can be a solution but maybe not the best.

Just to be sure to really understand your need, can you explain a bit more why you need to split ? What's your final goal when you can see only one curve ?

Thanks in advance

**Comment by PhilCANDIDO** [comment]
Hello Leon,

The aim is to divide all the data sources present in a graph into separate graphs.
But only one data source per graph. In order to reproduce the same behavior as previous versions of Centreon.

This options is always present in graph template in Centreon 2.8 
![image](https://cloud.githubusercontent.com/assets/13585152/23016060/7daed3d4-f435-11e6-91fc-293e66a2cd22.png)

But is not working. The split button has disappeared.

Leon, if you want you can contact me directly on my email. 

---
Ex in Centreon 2.7 when you use split button
Graph before split : 
![image](https://cloud.githubusercontent.com/assets/13585152/23015908/ecf70ed8-f434-11e6-9d42-072233360d07.png)

Graph after split : 
![image](https://cloud.githubusercontent.com/assets/13585152/23015982/253d6ecc-f435-11e6-8dbc-30eb4e4bbef6.png)
