### ISSUE TITLE
Hostgroups hidden in monitoring

### ISSUE THREAD

**Issue by cbertholio** [centreon/centreon#4993]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.2

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 
CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create several hostgroups with many hosts (~50 hostgroups and 1600 hosts)
2. Export configuration to collectors
3. Some hostgroups aren't visible in monitoring tab

**Describe the results you received:**
See attached files ...
![hostgroups configuration](https://cloud.githubusercontent.com/assets/13978531/23013176/e273ba5c-f429-11e6-9a05-b6061a6abcc7.png)
![hostgroups supervision](https://cloud.githubusercontent.com/assets/13978531/23013177/e274e422-f429-11e6-98c7-cc7ce8eb869e.png)

**Describe the results you expected:**
ALl hostsgroups with hosts must be visible in monitoring tab

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Hello, 

Are you sure that hosts in hostgroups are enabled ? Are you sure your have restarted all pollers ?

I just test with 9000 hosts in hosts during benchmark test and I can't see the behavior...

**Comment by cbertholio** [comment]
Hello,
As you can see on attache file, all hostgroups are enabled.
The pollers are often restarted. 
It's works well since few weeks and we have got this issue a day ... maybe cause by wrong parameters ?

Have you tested with one hundred hostgroups for example ? 

![2017-02-17_08h39_59](https://cloud.githubusercontent.com/assets/13978531/23056647/b04f78fe-f4ec-11e6-854e-9d6f1fc524ec.png)

**Comment by cbertholio** [comment]
N'y aurait-il pas un rapport avec l'utilisation de l'API REST pour ajouter des hosts dans Centreon svp ?

**Comment by julienmathis** [comment]
Pourquoi, durant mes derniers tests, tout a été ajouté par les API.

Comment sont ajoutés tes hostgroups ?

**Comment by cbertholio** [comment]
Tous les "changes" sont effectués en script Powershell avec l'API REST de Centreon.
Le problème a été "contourné" la semaine dernière en désactivant tous les hostgroups et en envoyant la configuration. Il n'y avait plus de hostrgoup en supervision puis le fait de les réactiver et de renvoyer la config a rétablit la situation. Vous pouvez clôturer cet incident.

**Comment by julienmathis** [comment]
Thanks for your feedback !
