### ISSUE TITLE
Poller States: Christmas tree after 25 minutes

### ISSUE THREAD

**Issue by 5145h** [centreon/centreon#4996]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.3-2.el6.noarch

**Centreon Engine version**: centreon-engine-1.7.0-2.el6.x86_64

**Centreon Broker version**: centreon-broker-3.0.3-4.el6.x86_64

**OS**: Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Additional environment details (AWS, VirtualBox, physical, etc.):** Openstack instance

**Steps to reproduce the issue:**
1. logs.MYI crashed after filling the shared FS(/var/lib/mysql) of 10GB
2. Resized/doubled the FS
3.  mysqlcheck -c -u root -p --all-databases ; myisamchk logs.MYI ; myisamchk -o logs.MYI ; myisamchk -of logs.MYI -> all ok
4. Reduced the retention durations of reporting/logs/data in MySQL/RRDTool
5. executed the purge cron script
6. from Mysql shell: OPTIMIZE TABLE centreon_storage.logs; (causing the logs.MYI to reduce from ~4GB to ~few hundred MB)
7. Restarted all the services on Central and on the Poller

**Describe the results you received:**
Poller states section: 
    -shows Poller Central and/or Satellite(1st and single distant poller)/or both in not running state (turning red)
    - Some database poller updates are not active: check you Monitoring platform (turning red/yellow)
Configuration -> Pollers -> Last update column turns yellow and then becomes normal  and changes the time displayed with time in the past(eg. current time 15:56 and it displays 14:43, etc etc)

Restarting cbd clears the above situation for another 25 minutes(everything turns green).

Logs:
/var/log/centreon/centcore.log:
cat: /var/lib/centreon-broker/satellite-rrd-stats.json: No such file or directory - repeating for ever

/var/log/centreon-broker/central-broker-master.log:
Centreon Broker 3.0.3 log file opened
[1487247747] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'

/var/log/centreon-broker/central-module-master.log
Centreon Broker 3.0.3 log file opened
[1487247189] config:  log applier: applying 1 logging objects
[1487247189] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1487247747] error:   TCP: error while writing to peer 'localhost:5669': Socket is not connected

/var/log/centreon-broker/central-rrd-master.log
Centreon Broker 3.0.3 log file opened
[1487247747] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'

/var/log/centreon/sql-error.log
No errors.

/var/lib/mysql/hostname.log 
~1100 lines of queries for a second of dump

under /var/lib/centreon-broker:
# ll
total 123900
prw-r--r-- 1 centreon-broker centreon-broker         0 Feb 16 13:22 central-broker-master-stats.json
-rw-r--r-- 1 centreon-broker centreon-broker         8 Feb 16 13:22 central-broker-master.unprocessed
-rw-rw-r-- 1 centreon-engine centreon-engine         8 Feb 16 13:13 central-module-master.unprocessed
-rw-r--r-- 1 centreon-broker centreon-broker 100000000 Feb 16 16:05 central-rrd-master.queue.central-rrd-master-input-177
-rw-r--r-- 1 centreon-broker centreon-broker  26854419 Feb 16 16:05 central-rrd-master.queue.central-rrd-master-input-178
prw-r--r-- 1 centreon-broker centreon-broker         0 Feb 16 13:22 central-rrd-master-stats.json
-rw-r--r-- 1 centreon-broker centreon-broker         8 Feb 16 13:22 central-rrd-master.unprocessed
srwxr-xr-x 1 centreon-broker centreon-broker         0 Feb 16 13:22 command.sock

**Describe the results you expected:**
Normal behaviour

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by BlackstormFirst** [comment]
Hi,
2.8.3 have many bugs with the generated conf (and some sql issues), use 2.8.4 with broker 3.0.3 and engine 1.7.0.
2.8.5 incomming will resolve some other little bugs (graphs, options not saved...)

**Comment by 5145h** [comment]
I'm a bit concerned about the fact that a Stable version is acting so weird.

Anyone? 
Are there any tools to check the integrity of the database?
Any ideas?

**Comment by julienmathis** [comment]
Hello, 

it seems that you have problem with your MySQL instance and not Centreon. When you don't make an optimize, is centreon working fine ?

**Comment by 5145h** [comment]
Hi, 

I have executed the Optimze to get rid of the unneeded indexes which grew the size of the logs.MYI table to near 10GB. 
Is there a way to check the sanity of the centreon/centreon_storages DBs or of the tables together with the relations between them?

Thanks.

**Comment by lpinsivy** [comment]
It a MySQL problem and Centreon can't replace MySQL itself
