### ISSUE TITLE
[2.8.4] centreon_storage ghost host

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#4997]
Centreon Web 2.8.4-5
Centreon Engine 1.6.1
Centreon Broker 3.0.1
CentOS release 6.8 (Final)
MariaDB 5.5.53
CES VirtualBox

I had this particular host trying to collect data from another hostgroup service captured from tcpdump.
I tried disabling that host, but the collection did not stop.
I tried to delete that host, but the collection did not stop, even though all services were reloaded / config exported.
I tried to run centstorage purge script manually, but the host's service is still present at cent_storage hosts table.

The other hosts from its hostgroup are working fine.

host already deleted:
![image](https://cloud.githubusercontent.com/assets/25208457/23035720/3ec84402-f467-11e6-92e7-e0d306871d5b.png)

![image](https://cloud.githubusercontent.com/assets/25208457/23033479/5ec54f1e-f45f-11e6-82ae-efcb7763a97c.png)

![image](https://cloud.githubusercontent.com/assets/25208457/23035583/bbcfe15e-f466-11e6-9e46-b5ff2fdb8290.png)

![image](https://cloud.githubusercontent.com/assets/25208457/23033721/5dbe3300-f460-11e6-8101-5fa9d5abbd32.png)

![image](https://cloud.githubusercontent.com/assets/25208457/23035362/f5b0aa62-f465-11e6-8a44-ff1d6dcb7538.png)

**Comment by julienmathis** [comment]
Hello, 

When you speak about host, you mean poller ? A host do not collect. A poller collect information about hosts :)

Right ?

**Comment by kozfelipe** [comment]
Exactly, my poller is collecting service information from another hostgroup for this host that is already deleted

**Comment by julienmathis** [comment]
Do you check the value of the field "enabled" in hosts table ? Strange that the host is not disabled. For history reason, we never delete a host when you remove it in the configuration. We only disable it in the database. This is the same for services.

**Comment by kozfelipe** [comment]
![image](https://cloud.githubusercontent.com/assets/25208457/23470260/b00b7194-fe84-11e6-801d-650ce7fc9584.png)

![image](https://cloud.githubusercontent.com/assets/25208457/23469956/e3aa1ef2-fe83-11e6-9a76-0239ec9608df.png)

As you can see, this host (RTED-DSA01-01) has a read only community named _Telebr@s2013_ , eitherway the poller insists to request collection from another hostgroup with the community _tlbr_public_

**Comment by kozfelipe** [comment]
Im closing it. I had to reinstall everything

**Comment by hocinetwork** [comment]
Hi

I have the same issue for hosts monitored by one poller in a distributed architecture (1 central + 5 satellite).

After delete a host, export config and restart engine, the host is disabled in the database and do not appear in monitoring page. After 5 minutes, host is enabled in centreon_storage and appear in monitoring view.

Could you help me with this ?

**Comment by leandroschatts** [comment]
Hello,
Any fix this issue?

@kozfelipe whats is your e-mail?


Thanks.

**Comment by kozfelipe** [comment]
@leandroschatts kozfelipe@gmail.com
