### ISSUE TITLE
Graphing tool to allow "trends/predict"

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#50]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 3581, https://forge.centreon.com/issues/3581
Original Date: 2012-08-24

---

Hi, 

It could be interesting to provide some basic trend tools in View > Graphs. 
See the _storage-graph-base.jpg_ file. 

In a scenario where I can : 
- click "split components"
- click on a new "show trend"

I can detect that my /u0 partition will grow to make a crash approx. on Sunday night (not the best period...). We can't wait the sysadmin comes back to the office (not a production host). 

It can be set by a simple rrdtool expression like : 

```
VDEF:slope=metric_id,LSLSLOPE VDEF:inter=metric_id,LSLINT CDEF:trend=metric_id,POP,COUNT,slope,*,inter,+

```

who gives a y=ax+b function extracted from least square lines (_storage-graph-predict.jpg_)

pch

**Comment by lpinsivy** [comment]
It is possible to use virtual metrics
