### ISSUE TITLE
Custom View/ edit mode Button not working

### ISSUE THREAD

**Issue by cancom-monitoring-parschalk** [centreon/centreon#5008]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.4-5.el6

**Centreon Engine version**:  1.7.0-2.el6

**Centreon Broker version**:  3.0.3-4.el6

**OS**:  CentOS release 6.8 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare

**Steps to reproduce the issue:**
1. Login as non-admin user
2. Got to HOME -> Custom View -> click the "edit mode" Button

**Describe the results you received:**
Nothing happens

**Describe the results you expected:**
see the "add view" "edit view" and so on

**Additional information you think important (e.g. issue happens only occasionally):**
issue happens only with non-admin user that connect through a VPN.

**Comment by thiuyendang** [comment]
* Tested with admin user and non admin user
* Centreon web 2.8.5
* Centos6, CentOs7
**Test case description** : 
- log in Centreon Web 
-  Home > Custom view page displayed by default
- Click on Edit mode icon (pencil)
- log out
- log in once again
- Edit mode menus (Add view and so on) are not displayed anymore,

**Comment by iigorkarpov** [comment]
It impacts admin users as well, at least those who connect through a VPN.
