### ISSUE TITLE
The button "Deploy Service" generates duplicate services.

### ISSUE THREAD

**Issue by nakasix** [centreon/centreon#5010]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: N/A

**OS**: CES 3.4.1

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create Host with Host Template.
2. Deploy Service

**Describe the results you received:**
Duplicate service (CPU, MEMORY, etc...)
![capture](https://cloud.githubusercontent.com/assets/11419742/23127787/90427cb8-f77c-11e6-8da8-df99d2888a4e.PNG)

**Describe the results you expected:**
Unique Service

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by bdeschut** [comment]
We confirm this behavior in our environment as well (2.8.4)

**Comment by philipp1992** [comment]
can confirm this bug too. Is there any workaround?
