### ISSUE TITLE
Downtimes - BAM -> Display real BA name instead of _Module_

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#5014]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.x

**Steps to reproduce the issue:**
1. Set a downtime on a BA
2. Go to Monitoring -> Downtime page
3. See (as in picture) the _Module_BAM_x informations

**Describe the results you received:**

![image](https://cloud.githubusercontent.com/assets/6620287/23202184/2824ce30-f8dd-11e6-824d-55e328336036.png)

**Describe the results you expected:**

In the host name column put the name of the BA and a "-" in the service column

**Comment by thiuyendang** [comment]
OK Centreon Web 2.8.6 CentOS6

**Comment by thiuyendang** [comment]
OK Centreon Web 2.8.6 CentOS7 (after various environment fixes)
NB : before BAM module is installed, Monitoring > Downtimes page displays nothing (only menus are visible)
