### ISSUE TITLE
[2.8.x] open_files_limit error during installation

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#5017]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4-5

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware vSphere 6.0.0

**Steps to reproduce the issue:**
1. Do the web installation of Centreon
2. Go to step 7

**Describe the results you received:**
Got an error regarding database configuration "Add open_files_limit=32000 in my.cnf file under the [mysqld] section and restart MySQL Server."

**Describe the results you expected:**
Database configuration and so on

**Additional information you think important (e.g. issue happens only occasionally):**
With MariaDB 10 on CentOS 7 the directive "open_files_limit" has no effect anymore.
This value is now set on the service description file "/usr/lib/systemd/system/mariadb.service" as : 
_# Number of files limit. previously [mysqld_safe] open-file-limit
LimitNOFILE=32000_
You will need to do a "systemctl daemon-reload" before restarting the service.

**Comment by julienmathis** [comment]
We will change the message, but all is indicated into the documentation : 

https://documentation.centreon.com/docs/centreon/en/2.8.x/administration_guide/partitioning/index.html?highlight=limitnofile
