### ISSUE TITLE
[2.8.3] Problem with add host

### ISSUE THREAD

**Issue by Ale171** [centreon/centreon#5018]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: CES

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Add a host in Configuration, Hosts
2. Export the configuration

**Describe the results you received:**

When i add a host in Configuration, Hosts and i export the configuration, the host appear on the poller in /etc/centreon-engine/hosts.cfg but he doesn't appear in database centreon_storage in table hosts so he doesn't appear in Supervision on web interface. I think i have a problem of connection between the central and my database so i check logs centreon-broker : 

watchdog.log : 

`[1487774220] info:    watchdog: sending update signal to process 'central-rrd'`
`[1487774538] info:    watchdog: sending update signal to process 'central-broker `

central-broker-master : 

`[1487837092] error:   could not prepare insertion query for event 'host' in table 'rt_hosts': could not prepare query: Unknown column 'timezone' in 'field list' QMYSQL3: Unable to prepare statement
`

`[1487842554] error:   SQL: could not execute prepared statement: Cannot add or update a child row: a foreign key constraint fails (`centreon_storage`.`services`, CONSTRAINT `services_ibfk_1` FOREIGN KEY (`host_id`) REFERENCES `hosts` (`host_id`) ON DELETE CASCADE) QMYSQL3: Unable to execute statement`

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
Hello, 

You have problem with update process. This has been fixed in the last 2.8.4 version of Centreon Web.

Please launch this query in centreon_storage DB : 

-- OPTIMIZE Monitoring
ALTER TABLE services ADD INDEX last_hard_state_change (last_hard_state_change);

-- Add Timezone in hosts TABLE
ALTER TABLE `hosts` ADD COLUMN `timezone` varchar(64) DEFAULT NULL AFTER `statusmap_image`;

And restart Broker and Engine.

Regards

**Comment by Ale171** [comment]
It works ! Thanks @julienmathis 

Other problems are fix in the last 2.8.4 version of Centreon Web ?
