### ISSUE TITLE
Poller Configuration for Centos 7

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#5022]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

For Poller on Centos 7, what's about Monitoring Engine Init Script.
For centos 6, I use /etc/init.d/centengine with systemv.
But for centos 7, etc/init.d/centengine does not exist. We must use systemctl ...

Thanks,

**Comment by anzevi** [comment]
> For Poller on Centos 7, what's about Monitoring Engine Init Script.



It's just "centengine". And make sure u select "systemd" from the dropdown menu. 

This is my whole config that works perfectly fine on Centos 7:

<img width="894" alt="screen shot 2017-02-23 at 16 52 40" src="https://cloud.githubusercontent.com/assets/12727931/23266639/a64a7038-f9e8-11e6-997c-95acc28b8477.png">

Cheers

**Comment by romsworld** [comment]
Thanks,

Could you check on log of centcore.log if you have

2017-02-23 16:56:09 - Init Script : 'sudo /etc/init.d/centengine restart' On poller x.x.x.x

when you restart your poller.

Thanks,

**Comment by julienmathis** [comment]
Hello, 

Please just use the service name. For Centreon Engine, only use centengine.

**Comment by romsworld** [comment]
I do it, but is it normal that I have on centcore.log "Init Script : 'sudo /etc/init.d/centengine restart'"

This can not work.
My Central is on Centos6, and one of poller is centos7. Is it a problem?

**Comment by romsworld** [comment]
Hum...
I close this case. I don't know why, but when a I change /etc/init.d/centengine by centengine, perhaps I don't click on save :)
It's ok now,
 Init Script : 'sudo centengine restart'

**Comment by julienmathis** [comment]
Thanks :)
