### ISSUE TITLE
/var/lib/centreon-broker/PollerXXX-brocker-stats.json: No such file or directory

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#5024]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.03

**OS**: Centos 6

Hi,
I have a lot of line in centcore.log 👍
 cat: /var/lib/centreon-broker/PollerXXX-brocker-stats.json: No such file or directory

Have I forget something to configure ?

Thanks,

**Comment by 5145h** [comment]
Hi, 

Upgraded to 2.8.7 and still have this error in centcore.log
What was the fix?

Thanks.

**Comment by lpinsivy** [comment]
It means that you didn't Enable Broker Statistics Collection option in "Administration  >  Parameters  >  CentCore" menu
