### ISSUE TITLE
Non-Admin User PHP Error Add Downtime

### ISSUE THREAD

**Issue by cancom-monitoring-parschalk** [centreon/centreon#5025]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.4-5.el6

**Centreon Engine version**:  1.7.0-2.el6

**Centreon Broker version**:  3.0.3-4.el6

**OS**:  CentOS release 6.8 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare

**Steps to reproduce the issue:**
1. As Non-Admin User go to "Monitoring - Downtime"
2. Click "Add a Downtime"

**Describe the results you received:**
A white blank screen

**Describe the results you expected:**
Add Downtime - General Information 

**Additional information you think important (e.g. issue happens only occasionally):**
Under /var/log/httpd/error_log : 
 [Fri Feb 24 08:44:46 2017] [error] [client 172.**.***.7] PHP Warning:  require_once(../errors/alt_error.php): failed to open stream: No such file or directory in /usr/share/centreon/www/include/monitoring/downtime/AddDowntime.php on line 57, referer: http://10.**.*.4/centreon/main.php?p=21001
[Fri Feb 24 08:44:46 2017] [error] [client 172.**.***.7] PHP Fatal error:  require_once(): Failed opening required '../errors/alt_error.php' (include_path='/usr/share/centreon/www/class:/usr/share/centreon/www/lib:.:/usr/share/pear:/usr/share/php') in /usr/share/centreon/www/include/monitoring/downtime/AddDowntime.php on line 57, referer: http://10.**.*.4/centreon/main.php?p=21001

**Comment by julienmathis** [comment]
duplicate #4952
