### ISSUE TITLE
IE - Display problem - Superposes services in "Monitoring" menu

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5030]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.7.8 / 2.8.4
**Browser**: IE 11.713.10586.0

**Steps to reproduce the issue:**
1. Open Centreon in "Monitoring - Status Details - Services by Hostgroup"
Or
2. Open Centreon in "Monitoring - Status Details - Services by Servicegroup"
Or
3. Open Centreon in "Monitoring - Status Details - Hostgroup Summary"
Or
4. Open Centreon in "Monitoring - Status Details - Services grid"

**Describe the results you received:**
In Centreon Web 2.7
![2 7](https://cloud.githubusercontent.com/assets/13255513/23304676/4bde96a2-fa9b-11e6-91d9-652a4b160525.jpg)

In Centreon Web 2.8
![2 8](https://cloud.githubusercontent.com/assets/13255513/23304689/57be354a-fa9b-11e6-92d2-4bb1f978706b.jpg)

Best Regards

**Comment by Ridene** [comment]
Hi, 

We add the bug to the pipe and it will be resolved soon. 
Thank you for your report. 

Best Regards

**Comment by Moujimouja** [comment]
Hi,

Bug can't be reproduce d in 20.04 with Microsoft Edge. I close the case
