### ISSUE TITLE
[2.8.4] Centreontrap failed to start

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#5031]
**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: CentOs 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWARE

It is not possible to start centreontrapd.
The configuration file is actually
```
#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
        # databases credentials
        centreon_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        centstorage_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        db_type => 'SQLite',
        # server type (0: central, 1: poller)
        mode => 1
);

1;
```
The problem is that centreon is generating the trap database under /etc/snmp/centreon_traps/1/centreontrapd.sdb. The path where the centreontrapd.sdb is now located can be changed if you create a new Poller and is not always under /etc/snmp/centreon_traps/1

Workaround
we created a link to the new centreontrapd.sdb so the config is correct and the service is startet.

**Comment by nowx-gh** [comment]
Today I run into the same problem. Can confirm this.

**Comment by joschi99** [comment]
There is another issue with traps: the central system is not able to put the trap db on pollers.

**Comment by joschi99** [comment]
It seems working on Poller with version 2.8.5, but on central system the problem is still there.

**Comment by itsul** [comment]
Hi,
I can confirm that the problem still exists with Centreon 2.8.5 on the central system.
Here the centreontrapd.pm:

```
#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
        # databases credentials
        centreon_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        centstorage_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        db_type => 'SQLite',
        # server type (0: central, 1: poller)
        mode => 1
);

1;
```

I changed the path to "/etc/snmp/centreon_traps/1/" and set the mode to "0" and
centreontrapd started again.

**Comment by lpinsivy** [comment]
@joschi99 we change RPM for Centreon web 2.8.6 to do no install this file on Central because it is not necessary
