### ISSUE TITLE
Multiple Host group in view OR parent host group

### ISSUE THREAD

**Issue by mvisini** [centreon/centreon#5039]
Bonjour,

Dans un widget "host monitoring" ou "service monitoring" serait-il possible de faire en sorte de pouvoir sélectionner un ou plusieurs groupe d'hôte ou groupe de service ?

Ou alors de pouvoir créer des groupes d'hôtes parents et de pouvoir les sélectionner dans notre vue.

Aujourd'hui nous sommes obligés de créer un widget par groupe d'hôte/service. Ce qui n'est pas pratique dans certain cas.

Merci de votre retour

Mathieu

**Comment by julienmathis** [comment]
Bonjour, 

Ce besoin remonte souvent, nous avons bien en tête d'améliorer ce point. Par contre, je n'ai pas de délais à fournir pour le moment.

Merci

**Comment by mvisini** [comment]
Bonjour, 

merci de votre retour. Nous allons donc prendre notre mal en patience et nous débrouiller autrement pour le moment :)

Il est vrai que je n'ai pas vu ce sujet dans les TODO des 2.8.4 ou 2.8.5..

**Comment by jben94** [comment]
Bonjour,

De notre côté nous avons aussi ressenti ce besoin, nous avons donc effectué les changements et maintenant il est possible de choisir plusieurs groupes d'hôte dans nos widgets.

Je vais essayer d'envoyer mes modifications sur le github dès possible.

**Comment by jben94** [comment]
Modifications envoyées, 
en espèrent de n'avoir rien oubliée ;)

**Comment by mvisini** [comment]
Merci @jben94 !!

**Comment by jben94** [comment]
Ils ont fermés mon Pull request avec un message qui n'a rien avoir avec mes modifications !
Donc ils n'ont pas pris en compte la demande, je ne pense pas que la fonctionnalité soit dans les prochaines versions.

**Comment by mvisini** [comment]
Ne serait-ce pas la #4423  dans la ToDo list de la version 2.8.6 ?

**Comment by jben94** [comment]
Ah peut-être !
Pas facile de s'y retrouver dans tous ces Issues en double. 
Mais bon le principal c'est que sa soit mis en place, même si je n'ai toujours pas compris le message que l'on m'a mis pour justifier la fermeture du Pull Request. 
Bonne fin de journée.

**Comment by mvisini** [comment]
Bonjour @jben94. 
Maintenant que ma plateforme est en 2.8.4 j'ai essayé de modifier les fichiers que tu as mis à disposition pour ajouter dans les vues les multiples hostgroupe / servicegroup.

Déjà je n'ai pas ce dossier, et donc fichier :(
**www/install/**(sql/centreon/Update-DB-2.8.4_to_2.8.5.sql)

Ensuite lorsque je mets en place le nouveau fichier www/class/centreonWidget.class.php et que je retourne sur mon interface centreon, lorsque je veux modifier une vue le popup qui s'ouvre est blanc.
Il ni a aucune donnée à l'intérieur pour configurer le widget :(

As-tu une idée ?

**Comment by jben94** [comment]
Bonjour @mvisini 

**www/install/(sql/centreon/Update-DB-2.8.4_to_2.8.5.sql)**

Ce fichier est présent lors d'une mise à jour (Ici de la version 2.8.4 > 2.8.5), les fichiers sont ensuite déplacés dans un répertoire appelé "installDir", le plus simple est de prendre la requête SQL et de l'injecter directement dans votre base de données centreon.

> ALTER TABLE widget_parameters ADD COLUMN `multiple` TINYINT(1) NOT NULL DEFAULT 0 AFTER `field_type_id`;

Si tu as encore une page blanche, est-ce que tu peux me transmettre tes logs du service WEB ?

**Comment by jben94** [comment]
As tu changé les autres fichiers : 

List.class.php 
Params.class.php 

?

**Comment by mvisini** [comment]
Oui, j'ai recréé les fichiers complètement à partir des tiens.

**Comment by jben94** [comment]
Est-ce que sa fonctionne ou toujours pas ?

**Comment by mvisini** [comment]
Ah je n'avais pas vu ton commentaire pour la modif de la bdd .. 
Désolé !

Maintenant j'ai de nouveau accès aux param de mon widget. 
Par contre je ne vois pas comment sélectionner plusieurs groupes d'hôtes ou plusieurs groupes de service.

**Comment by jben94** [comment]
Ok, cool.

Est-ce que tu as effectué ces changements voir ici : https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/pull/75 ou https://github.com/Centreon-Widgets/centreon-widget-host-monitoring/pull/23 ?

**Comment by jben94** [comment]
normalement tu devrais avoir un select à choix multiple
