### ISSUE TITLE
License Manager – Log spam from cronjobs

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#5040]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.4
**Centreon Engine version**: 
1.7.0
**Centreon Broker version**: 
3.0.3
**OS**: 
CentOS release 6.8 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM Guest

**Steps to reproduce the issue:**
1. Execute a Centreon-cronjob on a Centreon 2.8 installation without a subscription, or let the system execute a cronjob for itself.

**Describe the results you received:**
```
[root@centreon ~]# sudo -u apache php /usr/share/centreon/cron/centAcl.php
PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on 
[root@centreon ~]# 
```
```
[root@centreon ~]# tail  /var/log/centreon/centAcl.log 
PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on line 0
PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on line 0
PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on line 0
PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on line 0
PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on line 0
...
```

**Describe the results you expected:**
If there is no license file, the logs shouldn't be spammed with described message.

**Comment by julienmathis** [comment]
Please update license-manager. This problem has already been fixed.

**Comment by itsul** [comment]
Hi,

I think we already have the latest version, at least there is no newer one in the repository:
```
rpm -q centreon-license-manager
centreon-license-manager-1.0.1-3.el6.noarch
```
The DB Scheme is also at version 1.0.1 and the module is installed.
Anything we can check? We get this one on every machine I checked.

CLAPI gets also this error (#4949). PP-Manager is latest version.
```
rpm -q centreon-pp-manager
centreon-pp-manager-2.1.3-1.el7.centos.noarch
```
