### ISSUE TITLE
Installing a centreon poller on centos 7

### ISSUE THREAD

**Issue by ELmane** [centreon/centreon#5042]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8

**Centreon Engine version**: 1.7

**Centreon Broker version**: 2.11

**OS**: Centos 7

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
I installed centreon poller on centos7. When configuring the web page the poller in not running

**Comment by julienmathis** [comment]
Sorry, we don't understand and we don't have enough information to help us.
