### ISSUE TITLE
Install with 3.4.1 ISO - Anaconda Error on Virtualbox

### ISSUE THREAD

**Issue by h4wkmoon** [centreon/centreon#5047]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualbox

**Steps to reproduce the issue:**
1.Download ISO from Centreon web site.
2.create a VM using virtualbox
3.boot from ISO, using text mode

**Describe the results you received:**
text popup with an anaconda error : "KeyError: ceschoice"

**Describe the results you expected:**
installation going on

**Additional information you think important (e.g. issue happens only occasionally):**
issue happens every time.

**Comment by nailyk-fr** [comment]
I test two days ago a text [install](http://iso.download.centreon.com/stable/3.4/centreon-standard-3.4-x86_64.iso)  on virtualbox (4.3.36/debian 8) and it went fine. 
What version of virtual-box do you use? On what OS?

**Comment by h4wkmoon** [comment]
Last stable.
The issue was with the lack of memory. Increasing the memory solved everything.
