### ISSUE TITLE
Blank Page on Service Description 

### ISSUE THREAD

**Issue by djamsite** [centreon/centreon#5050]
Centreon Web 2.8.4
Centreon Engine 1.7.0
Centreon Broker 3.0.3
RHEL release 7.3
PHP 5.4.16

On new Centreon server everything works except, when you try to get to service description:

**http://server/centreon/main.php?p=20201&o=svcd&host_name=FQDN&service_description=Service_name**

![image](https://cloud.githubusercontent.com/assets/26168076/23557260/66db14b2-0027-11e7-9fab-c2e1270faa09.png)

The page keeps loading for few seconds and then goes blank , the only error i can see is in httpd log 

[pid XXX] AH00052: child pid XXXX exit signal Segmentation fault (11) #1

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

I suppose you have an infinite loop because your service should use a template and this template uses itself.

Please check in your centreon database relation between service template.

Regards

**Comment by djamsite** [comment]
Hi, 

Thanks for the info, that did it :)

I had template with same name linked to the service template ( so it went into a loop as you mentioned)

As soon as removed the settings the service description started working .

Thanks for the help
