### ISSUE TITLE
Acknowledgement - Sticky option

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#5056]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.8
**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. A service  passes in critical state with this output "TOTO"
2. I set up an acknowledge (without sticky option)
3. The same service stay in critical statut but with an another output "TATA"
4. The acknowledge is always disable

**Describe the results you received:**

The acknowledge is always disable

**Describe the results you expected:**

The acknowledge is always enable

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
I suppose you check the box "Is Volatile" on your service or template
