### ISSUE TITLE
[downtimeManager] Remove deletion of downtimes not linked to objects 

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5057]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.x

**Steps to reproduce the issue:**
1. Create a downtime using CLAPI and don't link this one to host, service or group
2. Wait for execution of downtimeManager cron

**Describe the results you received:**

Downtime definition had been deleted

**Describe the results you expected:**

Downtime definition sould persist to continu configuration of this one

**Comment by lpinsivy** [comment]
ref c2ad113011fe12940ffb2dc260c99b9799c4fb59 for Centreon 2.7.x

**Comment by thiuyendang** [comment]
Tested on Centreon Web 2.8.5, centOs6 centOs7
OK
Using CLAPI to add a recurrent downtime, add a specific period, waiting 5 min for Cron to execute, the downtime is not deleted.

**Comment by thiuyendang** [comment]
Tested again on 2.8.5 Centreon Web env upgraded from 2.8.4, CentOS6 and CentOS7. OK
