### ISSUE TITLE
Knowledgebase - Delete wiki page not functional

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5059]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.4
**Centreon Engine version**: 1.7.0
**Centreon Broker version**: 3.0.3

**Steps to reproduce the issue:**
1. Open Knowledgebase menu : "Configuration - Knowledge base - Hosts"
2. Try to delete page. Clic on "delete wiki page"

**Describe the results you received:**
Wiki page is not deleted

**Describe the results you expected:**
Wiki page should be deleted

Best Regards

**Comment by loiclau** [comment]
https://github.com/centreon/centreon/commit/67345895c888b781fb3ccca7438a5c4a50896543
