### ISSUE TITLE
Services escalations configuration not generated

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#506]
---

Author Name: **Remi BUISSON** (Remi BUISSON)
Original Redmine Issue: 3042, https://forge.centreon.com/issues/3042
Original Date: 2012-02-06

---

Hi,

I have one centreon 2.2.2 and a test one on 2.3.3 on which services escalations are not generated.
My test is:
- create an host group
- add a server in this group
- attach a service to this host group
- create a service group
- attach to service to it
- setup an escalation on this service group

Thanks.

Rémi

**Comment by julienmathis** [comment]
duplicate closed
