### ISSUE TITLE
Base Graph 1000/1024

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon#5069]
**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: Centos 6

Hello.

Since my migration from 2.7.8 to 2.8.4, my disk graphs are false.
![image](https://cloud.githubusercontent.com/assets/19145945/23800199/afee230e-05ab-11e7-9fca-a046380babbd.png)
![image](https://cloud.githubusercontent.com/assets/19145945/23800269/f28ef2ec-05ab-11e7-8b49-39b3562a79f5.png)

My "size" curve is normally at 60GB, but in my graph, I can see this curve at 64.4G.
The base of my graph is 1024, but the graph generated is base 1000.

Thanks.

**Comment by ganoze** [comment]
It is likely that this bug will be fixed in the 2.8.6 release of Centreon Web.

**Comment by thiuyendang** [comment]
Test : migration d'un Centreon Web 2.7.8 vers 2.8.6.2 -> disk size non identique (6.48 Gb -> 6.96 Gb) sur le graphe.
Voir avec Leoncx si correction intégrée dans le build du 14/2/17.

**Comment by thiuyendang** [comment]
Vu avec Leoncx ce jour : le correctif a été déplacé dans la version 2.8.7.
A retester ultérieurement.

**Comment by thiuyendang** [comment]
Testé 2.8.7 Centreon Web, CentOS7
Upgrade de 2.8.5 vers 2.8.7.
Référence : memory de esx alger 01, size 8 Go avant migration.
Idem après migration.
Correction OK

**Comment by cgagnaire** [comment]
Still not good for me in 2.8.9.
Base is not in 1024. Scale looks like I have 10K GB. Legend is not human readable. That should be enough :p 

Web UI : 
![image](https://cloud.githubusercontent.com/assets/23257354/26304977/b7e910fc-3eed-11e7-9406-780edcb06120.png)

RRD export : 
![image](https://cloud.githubusercontent.com/assets/23257354/26305031/f57df0b8-3eed-11e7-8789-bc5f9c513341.png)

**Comment by cgagnaire** [comment]
And if I don't set any template, the unit is on "bit", not "byte" : 
![image](https://cloud.githubusercontent.com/assets/23257354/26309488/85295c20-3efd-11e7-8e25-4b0e6a93e26b.png)

**Comment by thiuyendang** [comment]
With 2.8.9-5, widget Graph monitoring 1.5.2-1
Migration from 2.7.11 to 2.8-9-5
Graph Memory : 
- incorrect unit
- legend not human readable

In 2.7.11 : 
![2_7_11](https://cloud.githubusercontent.com/assets/25612980/26496480/fd521af2-4227-11e7-9304-0bfb0306273f.png)

In 2.8.9-5 (Graph monitoring 1.5.2-1)
![2_8_9_memory](https://cloud.githubusercontent.com/assets/25612980/26496762/10a7e7e8-4229-11e7-898b-628a07b41f3a.png)

**Comment by thiuyendang** [comment]
b is still not the correct unit for memory graph

**Comment by thiuyendang** [comment]
In 2.8.9-11, units are fixed but : 
-  memory size is lower than in 2.7.7 (before :  8 GB, now  almost 7.5 GB )
Before
![2_7_11](https://cloud.githubusercontent.com/assets/25612980/26633432/aeb4a8b6-4613-11e7-9d2d-d3862aa8e5f9.png)
Now
![memory_289_11](https://cloud.githubusercontent.com/assets/25612980/26633483/d4b313c2-4613-11e7-860f-3d19b0ee6e94.png)

- split chart : for ping graph, RTA curve has the same and unit than the PL curve
Before split
![beforesplit_ping_289_11](https://cloud.githubusercontent.com/assets/25612980/26634058/abb380d6-4615-11e7-88fc-899db85dfb21.png)

After split 
![memory_289_11](https://cloud.githubusercontent.com/assets/25612980/26633982/6b0665b2-4615-11e7-9ec2-5b49a24a88d2.png)

**Comment by thiuyendang** [comment]
OK 2.8.9-11 when graph template is not used.

**Comment by thiuyendang** [comment]
OK ping graph split.
NB : graph template can be linked on Configuration service page or on Command configuration page.
