### ISSUE TITLE
Disabled Host Templates Cause Config Generation to Error Out

### ISSUE THREAD

**Issue by apu-slall** [centreon/centreon#5073]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: Red Hat Enterprise Linux Server Release 7.3 (64-Bit)

**Additional environment details (AWS, VirtualBox, physical, etc.):** vSphere ESXi 6.0

**Steps to reproduce the issue and results:**
1. Disable more than one host template
2. Generate Config. This will give an error saying "Error while processing a config file: Parsing of host failed in file '/usr/share/centreon//filesGeneration/engine/1/hostTemplates.cfg' on line 125: already exists"
3. Reviewing the '/usr/share/centreon//filesGeneration/engine/1/hostTemplates.cfg' file will show entries like the following...
define host {
    timezone                       :America/Los_Angeles
}
The second entry like this is where the config says its fails because of "duplicates". 

4. To verify that this happens with that I can re-enable all the Host Templates.
5. Generating the config again will not result in any errors. 

**Expected Results :** I feel that if a host template is "disabled" in the UI it should not even be present in this config. But that is just my take on it. All in all there should not be any error just because I have multiple Host Templates disabled. 

Below are screenshots showing these steps.
![step_01-disable some host templates](https://cloud.githubusercontent.com/assets/26387221/23864354/7d1fc84e-07cf-11e7-94f9-a204b868f668.png)
![step_02 1-genereateconfiggiveserror](https://cloud.githubusercontent.com/assets/26387221/23864355/7d1ff65c-07cf-11e7-953f-682bfe9cbbc3.png)
![step_02 2-genereatedhosttemplateconfigfile](https://cloud.githubusercontent.com/assets/26387221/23864356/7d208644-07cf-11e7-8572-632446f7c517.png)
![step_03-reenableallhosttemplates](https://cloud.githubusercontent.com/assets/26387221/23864352/7d1f77a4-07cf-11e7-89df-aff230ac1351.png)
![step_04-genereateconfigwithouterrors](https://cloud.githubusercontent.com/assets/26387221/23864353/7d1f99fa-07cf-11e7-90ef-c04d7ce1cd9e.png)

**Comment by apu-slall** [comment]
I have some additional information on this which I think will either help identify it as a bug or a a works as designed. This seems to happen to me when I disable Host Templates that are linked to hosts. If I disable Host Profiles that are not in use then I dont get the same errors. 

With that this may be a works as designed type thing, but still would be nice to not get those errors, so maybe something to look forward to in a future release. Anyways feel free to let me know that its just a works as designed type thing, and close this out. 

Thank you.

**Comment by lpinsivy** [comment]
Should be corrected in Centreon Web 2.8.x branch
