### ISSUE TITLE
[2.8.5] [bug] Failed configuration break poller

### ISSUE THREAD

**Issue by nailyk-fr** [centreon/centreon#5075]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: Don't know how to find it :s

**OS**: CentOS 7, centreon installed through repos. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware esxi 4.5, Nagvis with [backend](https://raw.githubusercontent.com/centreon/centreon-nagvis-backend/master/GlobalBackendcentreonbroker.php). 

**Steps to reproduce the issue:**
1. Create a faulty configuration (My case was a service without check command)
2. Reload/Restart poller
3. Action is reported as OK: 
![capture d ecran - 14032017 - 12 05 53](https://cloud.githubusercontent.com/assets/16372405/23897777/b4b63f9c-08ae-11e7-8124-f2976ab65694.png)

**Describe the results you received:**
If reload has been choose, configuration isn't changed. 
If restart has been choose, poller is now empty: 
![capture d ecran - 14032017 - 12 07 51](https://cloud.githubusercontent.com/assets/16372405/23897808/e010efc0-08ae-11e7-848d-06e8ad8032e4.png)
Error is present into log _/var/log/centreon-engine/centengine.log_:

> [1489488148] [593] Error: Configuration parsing failed in file '/etc/centreon-engine/services.cfg' on line 43: Service 'edfqsfqsdgd' has no check command (property 'check_command')

**Describe the results you expected:**
Web UI shown an error (maybe the log one?) 

**Additional information you think important (e.g. issue happens only occasionally):**
If it possible reload old configuration when failed, or use _--verify-config_ before restart. 

Thanks.

**Comment by nailyk-fr** [comment]
You are right!
With '-v', if there is an error a red warning and problem get displayed. With the same error without -v everything seems to go smoothly and poller is stopped. 
IMHO it is a bug as without '-v' poller shouldn't be stopped and/or a warning should be displayed. 
Thanks for your time.

**Comment by lpinsivy** [comment]
Hi,
It's not a software bug. Documentation recommend to generate and test configuration before to move and restart poller.

https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/deploy.html

Regards,
