### ISSUE TITLE
Service name auto change at save

### ISSUE THREAD

**Issue by bbnono** [centreon/centreon#5078]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7

**Centreon Broker version**: 3.0.3

**OS**: Centos

**Additional environment details (AWS, VirtualBox, physical, etc.):** On a physical machine supply with an actual Centos 7 as master and 3 vmware esx virtual poller on Centos 7

**Steps to reproduce the issue:**
1. Change the name of service
2. Save
3.

**Describe the results you received:**
I want to name my service : manager service globe 
After saving, the service was name : ner sevice be

**Describe the results you expected:**
i want the name : manager service globe

**Additional information you think important (e.g. issue happens only occasionally):**
This issue is occasional but was create on service who was attach to central or poller.

**Comment by bbnono** [comment]
Voici les exemples en images. Si quelqu'un a une idée, ce truc est un enfer. Dès que l'on bouge un serveur de poller, il change de nom le host ou un service.

![centreon_after_save](https://cloud.githubusercontent.com/assets/26428107/24041704/e2cbccf0-0b0e-11e7-9867-1869d3747155.png)
![centreon_before_save](https://cloud.githubusercontent.com/assets/26428107/24041705/e2d8246e-0b0e-11e7-80c1-5a61bfe28d9e.png)

**Comment by cgagnaire** [comment]
Related to https://github.com/centreon/centreon/issues/4931
Will be fixed with 2.8.5

**Comment by julienmathis** [comment]
Yes ! Thanks Collin!
