### ISSUE TITLE
Custom View - "Set Default" button not working

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5079]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.4
**Centreon Engine version**: 1.7.0
**Centreon Broker version**: 3.0.3

**Steps to reproduce the issue:**
1. Create multiple custom views
2. Choose one and clic on "Set default" button
3. Change of page (or Logout of Centreon Web)
4.  Back to the page

**Describe the results you received:**
Custom view was not saved as "Default" and another view is displayed.

**Describe the results you expected:**
Custom view should be saved by default and when we leave and return to the page, we back on the right view.

**Additional information you think important (e.g. issue happens only occasionally):**
In Centreon Web 2.7.8 it works. There is a pop-up to show that is saved.
![custom view](https://cloud.githubusercontent.com/assets/13255513/23986229/63e06dce-0a23-11e7-911d-d849dddcb08c.jpg)

**Comment by zd14a** [comment]
I can confirm this problem in our installation (also 2.8.4). I tracked the network traffic and there is no request sent to the centreon after I click that button. Therefore the database entries stay the same and the Default View does not change.

**Comment by lpinsivy** [comment]
Corrected with new system of custom view

**Comment by thiuyendang** [comment]
Test en 2.8.5 sur une VM 2.8.4 upgradée en 2.8.5 (CentOs6 et CentOs7); reproduction du bug sur 2.8.4 OK.
Correction OK
