### ISSUE TITLE
Graphs in IE streched

### ISSUE THREAD

**Issue by zd14a** [centreon/centreon#5081]
I really love the new graphs but unfortunately in the Internet Explorer I cannot view two graphs at the same time, as the second one is so much streched that you cannot use it.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: CES 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Open Intenet Explorer and Login
2. Open Monitoring -> Performances
3. Add a Chart
4. Add another Chart

**Describe the results you received:**
In the Internet Explorer the second graph is many times wider than the first one. 

![wronggraph](https://cloud.githubusercontent.com/assets/25201923/24000071/7ff1c9e0-0a5a-11e7-9653-7bdef2f71dfc.png)

**Describe the results you expected:**
In other Browsers all Graphs have the same size, this should be the same in the IE.

**Additional information you think important (e.g. issue happens only occasionally):**
IE Version used is 11.0.9600.17041, Updateversion 11.0.7

**Comment by adr-mo** [comment]
Tests were done with:

- **Google Chrome** v62.0.3202.94
- **IE11** v11.15.16299.0
- **Microsoft EDGE** v41.16299.15.0
- **Firefox** v57.0

Graphs are well displayed

Looks good to me
