### ISSUE TITLE
Enhancement - Advanced ACL

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#5082]
An idea for the future. Advanced ACL.
By advance I mean, that we (admin users) can define exactly which lines users see or modify in host/service configuration. We run often into several problems. First is that users need to see SNMP community name, but I do not want them to be able to change configuration, so good option will be to have configuration Read option. The users can see configuration but not change it.
Second problem we have is that users are allowed to configure hosts and services but we would like to have option which defines, which lines they can change. For example only hostname, alias, ip, community, hostgroup etc. I think it cant be hard to configure option, as all the lines and boxes in host configuration and service configuration part are always the same. Only difference is MACROS. 
Lately we have run into problems, that users just change settings they actually do not need to touch, and that causes lot of problems.

**Comment by lpinsivy** [comment]
Hi,

1. Readonly access have been implemented.
2. You must give access to the configuration to a person with product training and responssable
