### ISSUE TITLE
Module Centreon NagV 1.1.1 is not installing

### ISSUE THREAD

**Issue by ipus2017** [centreon/centreon#5085]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: Centos 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Steps to reproduce the issue:**
1. Install module Centreon NagVis 1.1.1
2.
3.

**Describe the results you received:**

2017-03-17 10:46|0|0|DB Error: no such field QUERY : -- Topology
INSERT INTO topology (topology_id, topology_name, topology_icone, topology_parent, topology_page, topology_order, topology_group, topology_url, topology_url_opt, topology_popup, topology_modules, topology_show) VALUES ('', 'Nagvis', NULL, 4, 403, 20, 1, './modules/centreon-nagvis/index.php', NULL, '0', '1', '1');
2017-03-17 10:46|0|0|DB Error: no such field QUERY : -- Admin page
INSERT INTO topology (topology_id, topology_name, topology_icone, topology_parent, topology_page, topology_order, topology_group, topology_url, topology_url_opt, topology_popup, topology_modules, topology_show) VALUES ('', 'Nagvis', NULL, 5, 513, 11, 1, './modules/centreon-nagvis/nagvis-config.php', NULL, '0', '1', '1');
2017-03-17 10:46|0|0|DB Error: no such field QUERY : INSERT INTO topology (topology_id, topology_name, topology_icone, topology_parent, topology_page, topology_order, topology_group, topology_url, topology_url_opt, topology_popup, topology_modules, topology_show) VALUES ('', 'Nagvis Configuration', NULL, 513, 51301, 20, 1, './modules/centreon-nagvis/nagvis-config.php', NULL, '0', '1', '1');

**Describe the results you expected:**

Expected a configuration button on Centreon portal

**Additional information you think important (e.g. issue happens only occasionally):**

Nagvis 1.7.10 core is setup and operational

**Comment by julienmathis** [comment]
Hello, 

Can you open this ticket on nagvis project ? This is not a problem in Centreon Web

Thanks
