### ISSUE TITLE
Incoherent Graph Title 

### ISSUE THREAD

**Issue by Lebowskijul** [centreon/centreon#5086]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.03

**OS**: CentOS 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):**VMware

**Steps to reproduce the issue:**
1. From Monitoring Status Details view, click on the histogram icon of one of the services
2. The graph loaded is the correct one but the title is wrong

**Describe the results you received:** The graph loaded is the correct one but the title is wrong

**Describe the results you expected:** The graph loaded should have the correct title

**Additional information you think important (e.g. issue happens only occasionally):** When selecting the graph directly from the Performances tab, the title is correct.

In this example I am looking at ei1cscc.btz check_memory_used:
![graph_eic1scc memory_used_status_details](https://cloud.githubusercontent.com/assets/26509288/24074801/f6e3446e-0c0f-11e7-9029-16014b316f3c.png)

When I click on the histogram icon, I get the graph with the title of the nas2btzscc check_memory _used:
![graph_eic1scc memory_used_perf_graph](https://cloud.githubusercontent.com/assets/26509288/24074804/02713b42-0c10-11e7-9361-af02f4f727db.png)

**Comment by julienmathis** [comment]
Already fixed : #4964
