### ISSUE TITLE
Installation process stuck on Partitioning database tables

### ISSUE THREAD

**Issue by pamedee** [centreon/centreon#5088]
Hello!

Installing new vm using centreon iso. Process stuck on Partitioning database tables. I tested with clean Centos 7 also (using Centreon repo), but got same problem anyway. 

Version of centreon 3.4.1 / 2.8.4

**Comment by lpinsivy** [comment]
Hi,

Do you have errors in following files:

- /var/log/centreon/sql-error.log
- /var/lib/mysql/<server_name>.err
- /var/log/httpd/error_log

**Comment by pamedee** [comment]
Hi,

sql-error.log is not existed.
*.err:
Status information:

Current dir: /var/lib/mysql/
Running threads: 0  Stack size: 295936
Current locks:
lock: 0x7fb621418508:

lock: 0x7fb653ca0388:

lock: 0x7fb653c9df88:

lock: 0x7fb653c72588:

lock: 0x7fb653c71b88:

lock: 0x7fb653c70788:

lock: 0x7fb653c6fd88:

lock: 0x7fb653c98b88:

lock: 0x7fb63a261d88:

lock: 0x7fb653ff7388:

lock: 0x7fb653c6f388:

lock: 0x562c6a0d21e0:

lock: 0x562c6a0d2100:

lock: 0x562c6a0d1140:

lock: 0x562c6a0d1060:

lock: 0x562c6a0d0f80:

lock: 0x562c6a0d1300:

lock: 0x562c6a0cf540:

lock: 0x562c6a0d2020:

lock: 0x562c6a0cfc40:

lock: 0x562c6a0cfee0:

lock: 0x562c6a0cfb60:

lock: 0x562c6a0cfe00:

lock: 0x562c6a0cfa80:

lock: 0x562c6a0cfd20:

lock: 0x562c6a0d0260:

**Comment by pamedee** [comment]
Finally process is finished. But It needs 7 hours on server SSD.  Very strange, never seen this problem before...

**Comment by pamedee** [comment]
Tried today one more time. 
/var/log/httpd/error_log is full of this lines: 

[Tue Mar 21 14:17:44 2017] [error] [client 192.168.1.1] PHP Warning:  file_put_contents(../../tmp/createTables): failed to open stream: No such file or directory in /usr/share/centreon/www/install/steps/functions.php on line 128, referer: http://monitoring.codeborne.com/centreon/install/setup.php
[Tue Mar 21 14:17:44 2017] [error] [client 192.168.1.1] PHP Warning:  file_put_contents(../../tmp/createTables): failed to open stream: No such file or directory in /usr/share/centreon/www/install/steps/functions.php on line 128, referer

No errors in mysql log and cat: /var/log/centreon/sql-error.log: No such file or directory.

**Comment by itsul** [comment]
We could confirm this issue:
.

Webserver Log is full with:
[Fri Mar 24 08:09:26.044270 2017] [:error] [pid 32744] [client 172.xx.xx.4:63972] PHP Warning:  file_put_contents(../../tmp/xxx): failed to open stream: No such file or directory in /usr/share/centreon/www/install/steps/functions.php on line 128, referer: http://172.xx.xx.33/centreon/install/setup.php

**Comment by igormarqs** [comment]
i have this same error when build from source. any way to fix this??

**Comment by kadrika** [comment]
I also have the same problem. Is there a fix that I could try?

**Comment by igormarquesc** [comment]
i fix it after import db again. update create new tables and idk why this get stuck. after import db again all is good

**Comment by linceaerian** [comment]
More logs on the subject (also from a fresh install on CentOS 7 and the notes from #4799 applied)

/var/log/centreon/centcore.log
```
2017-08-18 12:00:19 - MySQL error : cannot connect to database centreon: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "Aucun fichier ou dossier de ce type") (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-08-18 12:00:19 - MySQL error : cannot connect to database centreon: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "Aucun fichier ou dossier de ce type") (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-08-18 12:00:19 - MySQL error : cannot connect to database centreon: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "Aucun fichier ou dossier de ce type") (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2017-08-18 12:00:19 - Error when getting server properties
```
/var/log/httpd/error_log

```
[Fri Aug 18 11:56:46.670527 2017] [:error] [pid 8132] [client 192.168.43.96:51249] PHP Warning:  file_put_contents(../../tmp/insertTopology): failed to open stream: No such file or directory in /usr/share/centreon/www/install/steps/functions.php on line 128, referer: http://192.168.43.93/centreon/install/setup.php
[Fri Aug 18 11:56:46.677323 2017] [:error] [pid 8132] [client 192.168.43.96:51249] PHP Warning:  file_put_contents(../../tmp/insertBaseConf): failed to open stream: No such file or directory in /usr/share/centreon/www/install/steps/functions.php on line 128, referer: http://192.168.43.93/centreon/install/setup.php
[Fri Aug 18 11:56:46.696253 2017] [:error] [pid 8132] [client 192.168.43.96:51249] PHP Warning:  file_put_contents(../../tmp/insertACL): failed to open stream: No such file or directory in /usr/share/centreon/www/install/steps/functions.php on line 128, referer: http://192.168.43.93/centreon/install/setup.php
```

Database deported to another host.
Database type: MariaDB.

It seems to do the first steps without error until getting to the partition part where it fail.
The connection to the database is working, the install script create the different databases.

@igormarqs Do you have a procedure for your fix ?
