### ISSUE TITLE
No args field when create a new service.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#509]
---

Author Name: **Manuel Rodrigo** (Manuel Rodrigo)
Original Redmine Issue: 3931, https://forge.centreon.com/issues/3931
Original Date: 2012-11-20
Original Assignee: Sylvestre Ho

---

Hi to all,
I am using Nagios 3 and Nagvis 1.7.3 with Centreon 2.3.9 over SuSE 11 SP2 x64.
Well, when I tried to create a new service, it seems to be impossible due the args field is not available. It repeats when tries to create a new service template. 
I post some screen prints.
Thanks in advance.

**Comment by julienmathis** [comment]
no response
