### ISSUE TITLE
Live Top 10 Memory Usage - Filter by hostgroup does not work

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5090]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.2

**OS**: Centreon 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a Live Top 10 Memory Usage widget
2. Try to filter using HostGroup
3. Add service description and metric name

**Describe the results you received:**
Filter by Hostgroup doesn't work

**Describe the results you expected:**
Filter by Hostgroup works

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
@lolokai can you create ticket on correct tracker please: https://github.com/Centreon-Widgets/centreon-widget-live-top10-memory-usage
