### ISSUE TITLE
Change page after a search on Services Templates / Host Templates

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5096]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.1

**OS**: Centreon 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual Machine

**Steps to reproduce the issue:**
1. Go to Configuration ==> Services ==> Services Templates (or Configuration ==> Hosts ==> Hosts Templates)
2. Make a search choose a general word in order to show severals pages
3. Try to change page

**Describe the results you received:**
First try : It does not work
After first try : It works

**Describe the results you expected:**
First try : It works without another try

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
should be corrected because it works with Centreon web 2.8.12
