### ISSUE TITLE
[BUG] Setting Downtime for Service Using the Monitoring > Downtime Page for ACL Users

### ISSUE THREAD

**Issue by shiraazlall** [centreon/centreon#5097]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**:  2.8.4
**Centreon Engine version**:  1.7.0
**Centreon Broker version**: 3.0.3

**OS**: Red Hat Enterprise Linux Server Release 7.3 (64-Bit)

**Additional environment details (AWS, VirtualBox, physical, etc.):** vSphere ESXi 6.0

**Steps to reproduce the issue:**
**IMPORTANT NOTE:** This is not the case for admin users for whom ACLs are not effective. For my admin users I am able to create service downtimes through the "Monitoring > Downtime" pages

For a regular users with ACLs applied setting downtime for services through one method works, but does not work using another method.

Working Method:
STEP 01: Get to the page where all services are listed. 
- Monitoring > Status Details  > Services (Change Services Status to 'All')
- Using the "Top Counter" on the top right, select the one to show all services.
STEP 02: Click the checkbox next to the service that you wanted to schedule downtime for. 
STEP 03: From the actions drop down menu select "Services: Set Downtime"
STEP 04: A windows will pop up with downtime information. Click "Set downtime" to submit the form.

This process is successful in setting downtime. This can be reviewed through the Downtime page (Monitoring > Downtime).

Not Working Method:
Using the Individual Service Status Page
STEP 01: Get to the page where all services are listed. 
- Monitoring > Status Details  > Services (Change Services Status to 'All')
- Using the "Top Counter" on the top right, select the one to show all services.
STEP 02: Select an individual service to bring up its status page.
STEP 03: From the menu on the right select "Schedule downtime for this service"
STEP 04: This will take you to another page under "Monitoring  >  Downtimes  > HOSTNAME". Enter a comment and click "Save"

This process will be unsuccessful in setting downtime. This can be reviewed through the Downtime page (Monitoring > Downtime).Alternatively you can also go to "Monitoring > Downtime > Add a downtime > Select the "Services" radio button and finish the form that way, but it will yield the same results. 

**Describe the results you received:**
I was not able to set downtime as a regular user. 

**Describe the results you expected:**
I should be able to set downtime. 

**Additional information you think important (e.g. issue happens only occasionally):**
It does not impact admin users.

**Comment by neithnivod** [comment]
Same Problem ist with:
Centreon Web version: 2.8.5
Centreon Engine version: 1.7.1
Centreon Broker version: 3.0.5

It looks like the ACL for Monitoring -> Downtimes -> Downtimes -> 'Add a downtime' (redirect to main.php?p=21001&o=a) is not working correct. It keeps saying "You are not allowed to reach this page".

**Comment by neithnivod** [comment]
This is a duplicate problem and you can find a workaround here until 2.8.6 is released:
https://github.com/centreon/centreon/issues/4952

I am quite new to Github and not sure how I link it correctly.
