### ISSUE TITLE
Add obsfucation on services details

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5098]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.1

**OS**: Centreon 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go on Monitoring - Services Details
2. Click on a service which use a password
3.

**Describe the results you received:**
On Executed Check Command Line field the --password argument is obsfucated

**Describe the results you expected:**
It will be perfect if you add obsfucation for these arguments --snmp-community / --privpassphrase and --authpassphrase

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lolokai** [comment]
If you add simple quote for the --password argument it does not obsfucate anymore the password : can you correct this please ?

**Comment by lpinsivy** [comment]
obsfucation can only be added for macro with password tags.
