### ISSUE TITLE
[BUG] ACL - Servicegroup

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5101]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.4
**Centreon Engine version**: 1.7.0
**Centreon Broker version**: 3.0.3

**Steps to reproduce the issue:**
1. Create a servicegroup "test"
2. Create user with ACLs but who has access to the servicegroup
3. Export configuration and reload ACLs
4. Connect with user account
5. In "Monitoring - Status Details - Services", try to select "test" in filter "servicegroup"

**Describe the results you received:**
Servicegroup is not present in filter servicegroup while it's available in : 
- "Monitoring - Status Details - Services by Servicegroup" page
- "Monitoring - Status Details - Services by Servicegroup" filter "Servicegroup"

**Describe the results you expected:**
We should see servicegroup "test" in filter servicegroup of "Monitoring - Status Details - Services" page.

Regards

**Comment by Sims24** [comment]
Hi, 

Do you have an active service in this servicegroup ? If not it may be possible that broker doesn't insert it in the realtime table but somehow in other pages centreon may display it :)

**Comment by julienmathis** [comment]
PR #5222

**Comment by cgagnaire** [comment]
Fixed in 2.8.9.

**Comment by thiuyendang** [comment]
OK 2.8.9
