### ISSUE TITLE
! Proposition d'ajout de fonctionnalité : Mode maintenance 

### ISSUE THREAD

**Issue by mvisini** [centreon/centreon#5102]
Bonjour, 

une petite idée d'amélioration qui serait vraiment très intéressante :)

il serait intéressant d'intégrer un mode maintenance, je m'explique : 
- Ce mode permettrait en un clique (ou deux :)) de stopper tous les notifications (email, sms, etc..)
- Il pourrait aussi permettre de sortir des stats (calcul des disponibilités, etc..) les valeurs qui pourraient remonter pendant cette plage de maintenance
- Il pourrait également permettre de modifier tous les graphes en intégrant d'une façon visuelle cette plage de maintenance
- Enfin, un peu comme l'évolution en cours des downtimes, nous pourrions activer ce mode maintenance avec une date de début et une date de fin. Ou alors l'activer uniquement avec une date de début, puis ensuite le désactiver.

Bien évidemment ce mode devrait pouvoir fonctionner sur une installation multi pollers.

L'idée de cette amélioration étant de fournir des données de graphes, stats, etc.. les plus pertinentes possibles sans qu'une maintenance ne vienne les polluer et empêcher une représentation réelle du fonctionnement des équipements surveillés.

**Comment by lpinsivy** [comment]
- Ce mode permettrait en un clique (ou deux :)) de stopper tous les notifications (email, sms, etc..)

C'est ce que font les downtimes/acquittements

- Il pourrait aussi permettre de sortir des stats (calcul des disponibilités, etc..) les valeurs qui pourraient remonter pendant cette plage de maintenance

Je ne comprends pas le besoin

- Il pourrait également permettre de modifier tous les graphes en intégrant d'une façon visuelle cette plage de maintenance

Les downtimes/acquittements sont désormais visibles sur les graphiques en activant l'option (Centreon Web 2.8.x)

- Enfin, un peu comme l'évolution en cours des downtimes, nous pourrions activer ce mode maintenance avec une date de début et une date de fin. Ou alors l'activer uniquement avec une date de début, puis ensuite le désactiver.

Possible de mettre un downtimes sur un poller et donc toutes ses ressources
