### ISSUE TITLE
new feature: custom menus/functions

### ISSUE THREAD

**Issue by george-vieira** [centreon/centreon#5106]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.8+

**Centreon Engine version**: 
1.5.0+

**Centreon Broker version**: 
?

**OS**: 
debian jessie

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware

With my system I'm developing along on issue #4490 , I have a working host side agent service which performs all the checks and posts state changes to central broker server and can accept requests from central centreon server for service(s) status and force checks on any service.

One feature I need within the UI is the ability to perform a force check on a service without waiting for the output or exit code as this is an API call to the passive agent service on the monitored host. My problem is that the API command line code returns json a status and message if successful post to the remote agent. Problem is that this is ending up on the service line in the UI.
I don't want to output the remote services forced check output as this could be slow responses or checks run for minutes.etc. This is why I need a force and not action it's output/exit.

Is there a way I can modify the menu which contains "Service: schedule immediate check (forced)" to include another the same but does not expect output or exitcode?

thanks.

**Comment by lpinsivy** [comment]
Hi,;

Today you can modify this list of actions without hardcode it in Centreon Web.

Regards,

**Comment by george-vieira** [comment]
OK, but can you please show how. Is this something within the database like some top menus? if so, which where etc?
Other menus I looked for in the past were hard coded so I assumed this was as well.

**Comment by lpinsivy** [comment]
sorry you can't
