### ISSUE TITLE
cannot export poller configuration : sh: -v: command not found

### ISSUE THREAD

**Issue by jdelvecchio** [centreon/centreon#5107]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web.noarch               2.8.4-5.el7.centos
**Centreon Engine version**: 
centreon-engine.x86_64          1.7.0-2.el7.centos
**Centreon Broker version**: 
centreon-broker.x86_64          3.0.3-4.el7.centos
**OS**: 
CentOS Linux release 7.3.1611 (Core) 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare VM

**Steps to reproduce the issue:**
1. Go to configuration -> Poller -> Export configuration
2. Choose a poller
3. Click on 'export'

![selection_067](https://cloud.githubusercontent.com/assets/11552866/24405113/f4f6bd8c-13c3-11e7-8498-4adfb8f830f2.png)

**Describe the results you received:**
Generating files... NOK
Aborted.      [ - ] Central       sh: -v: command not found

**Describe the results you expected:**
Poller reloads normally

**Additional information you think important (e.g. issue happens only occasionally):**
Issue always happens.
I've managed to catch the command line that is executed :
```log
\_ /usr/sbin/httpd -DFOREGROUND
apache   32752  0.0  0.0  11628  1348 ?        S    08:36   0:00  |   \_ sh -c  -v /usr/share/centreon/filesGeneration/engine/1/centengine.DEBUG 2>&1
apache   32756  0.0  0.0  11628   192 ?        R    08:36   0:00  |       \_ sh -c  -v /usr/share/centreon/filesGeneration/engine/1/centengine.DEBUG 2>&1
```

**Comment by lgcosta** [comment]
@jdelvecchio you have a localhost poller ?
I have the same issue, but, i don't have a localhost poller. The debug test is running only localhost.
```
       /**
         * Get Nagios Bin
         */
        $DBRESULT_Servers = $this->_DB->query(
            "SELECT `nagios_bin` FROM `nagios_server` WHERE `localhost` = '1' ORDER BY `ns_activate` DESC LIMIT 1"
        );
        $nagios_bin = $DBRESULT_Servers->fetchRow();
        $DBRESULT_Servers->free();

        /*
         * Launch test command
         */
        if (isset($nagios_bin["nagios_bin"])) {
            exec(
                escapeshellcmd(
                    $nagios_bin["nagios_bin"] . " -v "
                    . $this->nagiosCFGPath . $idPoller . "/centengine.DEBUG"
                ),
                $lines,
```
Because the this SELECT only in localhost

Is a bug ?!

**Comment by lpinsivy** [comment]
No it is not a bug. Centreon need a local poller to test configuration.
