### ISSUE TITLE
Problem with Hide graphs of selected services 

### ISSUE THREAD

**Issue by ulsfr** [centreon/centreon#5108]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
Centreon 2.8.5
**Centreon Engine version**: 
Centreon Engine 1.7.0
**Centreon Broker version**: 
Centreon Broker 3.0.4
**OS**: 
centos-release-6-8.el6.centos.12.3.x86_64
**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM Vmware CES 

**Steps to reproduce the issue:**
1.Add a new service with 2 or more metrics (test with 2 and 4)
2.Add a virtual metric for view in graph (add 2 metrics for exemple)
3.Administration  >  Parameters  >  Data  : _Hide graphs of selected services_ for all metrics 

**Describe the results you received:**
Monitoring  >  Performances  >  Graphs I view graph with all services (standard and virtual)

If I view the *.png file, is correct, the metrics is hide

**Describe the results you expected:**
Monitoring  >  Performances  >  Graphs I view graph with services virtual only 

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
More over, some hidden curves still displayed

![screenshot at sept 08 11-22-19](https://user-images.githubusercontent.com/3351916/30205156-50d32042-9488-11e7-9818-9cf9d9cf072a.png)

<img width="1093" alt="screenshot at sept 08 11-22-07" src="https://user-images.githubusercontent.com/3351916/30205165-559514fa-9488-11e7-9276-ce8a08617dc4.png">

**Comment by cgagnaire** [comment]
Fixed by @garnier-quentin.
