### ISSUE TITLE
Search filters are not persistent

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#5109]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4 and 2.7.8

**OS**: RedHat 6

**Steps to reproduce the issue:**
1. Go to : Configuration  >  Hosts  >  Host Groups
2. Enter something as filter in the search field, click on Search
3. Edit an Hostgroup
4. Save it, or go back to the list via the breadcrumb
5. Your filter is gone

**Describe the results you received:**
Your search string is gone, you see all the hostgroups

**Describe the results you expected:**
I expect search string to be persistent

**Additional information you think important (e.g. issue happens only occasionally):**
This bug is global.
The only place where the search string is persistent is here : 

- Configuration  >  Services
- Configuration  >  Hosts

Everywhere else the search string is deleted when you edit something and save it.

**Comment by maksimatveev** [comment]
In 2.8.5 is similar.

**Comment by BenoitPoulet** [comment]
Still a pain to use Centreon everyday

**Comment by Cancom-Monitoring** [comment]
Similar in 2.8.16
1) go to Hostgroups
2) Define Filter -> Search
3) Go to page 2 (or whatever)
-> Filter is gone. (so for every linked page you wanna go, you have to define the filter again...)

**Comment by BenoitPoulet** [comment]
Still in 2.8.25

**Comment by adr-mo** [comment]
Hi @BenoitPoulet 

Thanks for the feedback 💯 

This issue will be fixed in the **18.10.5 release**

Regards,
