### ISSUE TITLE
Web access to service and service template description is slow after update 2.8.4

### ISSUE THREAD

**Issue by hocinetwork** [centreon/centreon#5111]
Thank you to describe your issue in English.
--> Web access to configuration/service description and service template description is very slow. Pages are generated after 40s, monitoring and all other tabs are OK. This behavior appears after update to 2.8.4 version from 2.8.3.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3.4

**OS**: Centos 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Go to Configuration / Service by Host
2. Click on any services

**Describe the results you received:**
It takes 40s to display the service details

**Describe the results you expected:**
Usually it takes 1s max

**Additional information you think important (e.g. issue happens only occasionally):**
**mysqltunner result :**
-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
    Remove Anonymous User accounts - there are 2 anonymous accounts.
    MySQL started within last 24 hours - recommendations may be inaccurate
    Enable the slow query log to troubleshoot bad queries
    Configure your accounts with ip or subnets only, then update your configuration with skip-name-resolve=1
    Adjust your join queries to always utilize indexes
Variables to adjust:
    query_cache_size (>= 8M)
    join_buffer_size (> 4.0M, or always use indexes with joins)
    innodb_buffer_pool_size (>= 80G) if possible.
    innodb_log_file_size should be equals to 1/4 of buffer pool size (=32M) if possible.

/etc/my.cnf.d/centreon.cnf

[server]
innodb_file_per_table=1

open_files_limit = 32000

key_buffer_size = 256M
sort_buffer_size = 32M
join_buffer_size = 8M
thread_cache_size = 64
read_buffer_size = 512K
read_rnd_buffer_size = 256K
max_allowed_packet = 8M
query_cache_size = 8M

# For 4 Go Ram
#innodb_additional_mem_pool_size=512M
#innodb_buffer_pool_size=512M

# For 8 Go Ram
#innodb_additional_mem_pool_size=1G
#innodb_buffer_pool_size=1G

log-slow-queries=/var/log/mysql-slow-queries.log
long_query_time = 1
log-queries-not-using-indexes

Do you have any idea ?

Thanks

**Comment by lpinsivy** [comment]
Hi,

I suppose you use LDAP authentication and you may have one of your LDAP servers not available.
This generate a timeout before access to service configuration page.

Can you check all your LDAP server ?

This must be corrected in Centreon web 2.8.5

Regards,

**Comment by maksimatveev** [comment]
Centreon Web version: 2.8.5
Generated in 0.899 seconds

**Comment by hocinetwork** [comment]
Hi

It was "Search group base DN" form. We filled out this form for making tests. I left empty this form and now it's OK. The 2 LDAP servers was reachable and 389 open.

Thanks and regards
