### ISSUE TITLE
[Chart] curves units are displayed on incorrect side

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5113]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Steps to reproduce the issue:**
1. Go to "Monitoring > Performances > Graphs" menu
2. Select chart to display with two different unit

**Describe the results you received:**

Unit are displayed with correct scale

**Describe the results you expected:**

Unit should displayed with correct scale

![image002](https://cloud.githubusercontent.com/assets/3351916/24453448/2ed96b02-1488-11e7-9e2a-740016e9d1ad.png)

**Comment by thiuyendang** [comment]
Centreon Web 2.8.7
CentOS7
Monitoring > Performance > Graphs
Ping
Units and scales OK when 2 Y axis.

**Comment by thiuyendang** [comment]
Sur un ping : deux courbes (rta et pl), si l'on ne visualise qu'une des courbes, seule l'axe Y avec la bonne unité et la bonne échelle doit être visible.

**Comment by cgagnaire** [comment]
OK in 2.8.9.

**Comment by thiuyendang** [comment]
Tests  2.8.9 CentOS6  + 7
Ping (RTA + PL curves)
Scales and units OK
When we disable one curve, both Y axis remain but scale and unit are alright.
The curves are properly located on the graph.
