### ISSUE TITLE
[2.8.5]

### ISSUE THREAD

**Issue by vladnosferatu** [centreon/centreon#5114]
Exporting the pollers

sudo: centreon : command not allowed ; TTY=unknown ; PWD=/var/spool/centreon ; USER=root ; COMMAND=centengine restart

is missing the "/sbin/service"
should be 
sudo: centreon : TTY=unknown ; PWD=/var/spool/centreon ; USER=root ; COMMAND=/sbin/service centengine restart

**Comment by lpinsivy** [comment]
Please use the default issue template as well as a human-readable title!

We need more information on your platform: Centreon Engine and Broker version? OS version ? ...

Regards,

**Comment by vladnosferatu** [comment]
problem fixed. restart the main server
