### ISSUE TITLE
[2.8.5] Splited chart png export misnamed

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#5120]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vSphere 6.0.0

**Steps to reproduce the issue:**
1. Go to 'Monitoring > Performances' and select a chart
2. Split the chart
3. Export one of the resulting chart

**Describe the results you received:**
The file is named '-.png'. Same for every charts.
The title above the chart is 'graph on'.

**Describe the results you expected:**
The file name might be "hostname"-"service name"-"metric name".png or some.
The title might be the same as the one in the none split chart.
Well, like it was before, I don't remember.

**Comment by kduret** [comment]
Fixed here : 498ee9006a9a2024c29bc82f725898f84e29a9ca

**Comment by cgagnaire** [comment]
Fixed in 2.8.9.

**Comment by thiuyendang** [comment]
test 2.8.9-5 
Name of png file = host-service.png
