### ISSUE TITLE
Splited chart png export misnamed doesn't work with HTTPS

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5121]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Additional environment details (AWS, VirtualBox, physical, etc.):** use HTTPS to connect to Centreon web UI

**Steps to reproduce the issue:**
1. Go to "Monitoring  >  Performances  >  Graphs" menu
2. Select a chart and click on "split" button
3. Click on PNG export

**Describe the results you received:**

Internal error 500

**Describe the results you expected:**

The PNG

**Additional information you think important (e.g. issue happens only occasionally):**

apache logs: PHP Fatal error:  Call to undefined method DB_Error::numRows() in /usr/share/centreon/www/class/centreonGraph.class.php on line 310

**Comment by thiuyendang** [comment]
to test with https connexion

**Comment by thiuyendang** [comment]
OK with https
