### ISSUE TITLE
[2.8.5] Charts upper limit different from template

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#5123]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vSphere 6.0.0

**Steps to reproduce the issue:**
1. Go to 'Monitoring > Performances > Templates' and set an upper limit for a chart template
2. Link the chart template to a service or service template
3. Go to 'Monitoring > Performances > Graphs' and select a service's chart that use the modified chart template

**Describe the results you received:**
On the chart, the upper limit is somehow multiplied : 
 - if 5 is defined, it will show 50 (x10)
 - if 55 is defined, it will show 550 (x10)
 - if 555 is defined, it will show 55,0K (x100)
 - if 5555 is defined, it will show 5,50M (x1000) 

**Describe the results you expected:**
The correct upper limit defined in the template.

**Additional information you think important (e.g. issue happens only occasionally):**
I have notice this only with one unit charts. The upper limit definition doesn't seem to have any effect for multiple units charts.

**Comment by kduret** [comment]
Fixed here : 1906b357628620500125b1f26f2122f23ff3b6d3

**Comment by cgagnaire** [comment]
In 2.8.9, limits are taken into account, but... it will be even better if there are really put on the charts :)
If I set 0/100 for a CPU chart, I get a -10/110, so it looks like I have a continual 10% CPU usage.
![image](https://cloud.githubusercontent.com/assets/23257354/26300238/da865332-3edd-11e7-9967-5a5c182fde24.png)

**Comment by Sims24** [comment]
hi, 

globally that's prelly annoying to have this kind of "blank space" between axis and curve(s). should I open a separate ticket for this ? 

![da865332-3edd-11e7-9967-5a5c182fde24](https://cloud.githubusercontent.com/assets/12429463/26300513/a003048e-3ede-11e7-9ea5-e6a8f7f40fd4.png)

Thanks

**Comment by Sims24** [comment]
ping @kduret about my last update just in case you're already working on it ;) that would be great to remove theses extra spaces =) 

thanks!

**Comment by kduret** [comment]
@Sims24 issue here ;)

**Comment by thiuyendang** [comment]
OK 2.8.9-11
