### ISSUE TITLE
$HOSTADDRESS$ macro is interpreted as the same for all hosts in a group.

### ISSUE THREAD

**Issue by natman** [centreon/centreon#5124]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.4
**Centreon Engine version**: 
1.7.0-2
**Centreon Broker version**: 
3.0.3-4
**OS**: 
el6
**Additional environment details (AWS, VirtualBox, physical, etc.):**
ovirt

**Steps to reproduce the issue:**
1.add a group of hosts
2.attach services to this group
3.open monitoring of a service

**Describe the results you received:**
All services are executed on all the hosts with one unique ip address came from the $HOSTADDRESS$ macro

**Describe the results you expected:**
services should be executed with the own ip address of each host

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

I try your procedure and for all my services created from a service linked to a hostgroup, they use IP address of each host.

Can you check executed command line from service detail page ?

Regards,

**Comment by lpinsivy** [comment]
No more information I close this issue
