### ISSUE TITLE
Long URL monitoring page

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5125]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.4
**Centreon Engine version**: 
1.7
**Centreon Broker version**: 
3
**OS**: 
CES

**Steps to reproduce the issue:**
1. In the monitoring page, select for example 100 services et select an action for example "Schedule immediate check".
2. The new URL is very long (for example more than 4000 caracters)

**Describe the results you received:**
Some Web browser limit the size of the URL to 2000 caracters, this can block the display of page

**Comment by lpinsivy** [comment]
Yes it is a limitation of web browser but it is not a regular behavior to reschedule 100 services in the same time
