### ISSUE TITLE
[2.8.5] Centreon Web - Fix Column Sorting

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon#5127]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**: Oracle Linux 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Administration  >  Parameters  >  Centreon UI
2. Problem display properties:
Sort by	Duration
￼Order sort	**Descending**
3. Monitoring  >  Status Details  >  Services
![2017-03-31 22 32 58](https://cloud.githubusercontent.com/assets/15804154/24566648/eb56d022-1662-11e7-90f6-4348d8346f6b.png)

**Describe the results you received:** Sorting in descending order does not work in columns.

**Describe the results you expected:** Sorting of results can be adjusted through sorting parameters (Administration  >  Parameters  >  Centreon UI > Problem display properties).

**Additional information you think important (e.g. issue happens only occasionally):** 
Correct sorting does not work not only for duration. But also for services and other columns.

**Comment by maksimatveev** [comment]
The problem occurred after the upgrade to version 2.8.5.

**Comment by lpinsivy** [comment]
I suppose this issue is linked with #5116

**Comment by maksimatveev** [comment]
@lpinsivy Hello. Is this problem added to any of your projects to solve it?

**Comment by Az3RuS** [comment]
I have the same problem with version 2.8.8.
Parameters in Administration > "Centreon UI" > "Maximum page size" "Display properties" "Problem display properties" do not apply !
One solution ?

**Comment by lpinsivy** [comment]
Should be corrected by #5517
