### ISSUE TITLE
View Service default if Host have character +

### ISSUE THREAD

**Issue by ulsfr** [centreon/centreon#5128]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
Centreon 2.8.5
**Centreon Engine version**: 
Centreon Engine 1.7.0
**Centreon Broker version**: 
Centreon Broker 3.0.3
**OS**: 
centos-release-6-8.el6.centos.12.3.x86_64
**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware

**Steps to reproduce the issue:**
1. Add host with character + in name
2. Add standard service linked with the host
3. Configuration  >  Pollers  Export configuration 
4. GO Monitoring  >  Status Details  >  Services and click on service

**Describe the results you received:**
Message : "The related host no longer exists in Centreon configuration. Please reload the configuration."

**Describe the results you expected:**
View with detail info Service

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
linked to #4883
