### ISSUE TITLE
[2.8.5] Problem with traffic graph - incomplete graph

### ISSUE THREAD

**Issue by o71** [centreon/centreon#5129]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Centreon Web version: 2.8.5

Centreon Engine version: 1.7.1

Centreon Broker version: 3.0.5

OS: Debian 8

**Steps to reproduce the issue:**
1. I use the service "Service Traffic-Generic-Name" :
/usr/lib/centreon/plugins/centreon_linux_snmp.pl
	--plugin=os::linux::snmp::plugin
	--mode=interfaces
	--hostname=192.168.X.X
	--snmp-version='2c'
	--snmp-community='public' 
	--interface='^eth0$'
	--name
	--add-status
	--add-traffic
	--warning-in-traffic='80'
	--critical-in-traffic='90'
	--warning-out-traffic='80'
	--critical-out-traffic='90'

2 .I have 3 problems with the graph of this service

![traffic-graph](https://cloud.githubusercontent.com/assets/2280629/24576900/6448c10a-16c4-11e7-8412-9174b9406722.PNG)

- The graph is incomplete for traffic in : The value is 180M however the "curve" is near to zero
- There is a 'Traffic In' on the top with the 'Traffic out', it's strange

![traffic-graph-zoom](https://cloud.githubusercontent.com/assets/2280629/24576885/1ef91d02-16c4-11e7-9a44-a4bbcd78bd7c.PNG)

- When I select a more restricted period (20:30 to 23:00) I have not the same value for 22:00 : traffic in 156M and not 180M, traffic out 821k and not 930k, why ?

Another picture 'graph split' :

![traffic-graph-split](https://cloud.githubusercontent.com/assets/2280629/24576951/2ca070d0-16c5-11e7-9978-5c44f94fb3cb.PNG)

Sorry for my English,

Thank you

**Comment by lpinsivy** [comment]
Hi,

The problem is still present with latest version of Centreon Web ?

**Comment by o71** [comment]
Hi,

Thank for your email.

My version is 2.8.11.
I have do a test, but there's a big problem. Now I can't see the
traffic_in, I think that's because the number is negative ?
Can you solve it ? After I will do some others tests.

[image: Images intégrées 2]



2017-08-17 13:28 GMT+02:00 Laurent Pinsivy <notifications@github.com>:

**Comment by o71** [comment]
I have some others tests.

The value is positive with this command : 
`/usr/lib/centreon/plugins/centreon_linux_snmp.pl
	--plugin=os::linux::snmp::plugin
	--mode=interfaces
	--hostname=192.168.X.X
	--snmp-version='2c'
	--snmp-community='public' 
	--interface='.*'
	--name
	--add-status
	--add-traffic
	--critical-status=''
	--warning-in-traffic='80'
	--critical-in-traffic='90'
	--warning-out-traffic='80'
	--critical-out-traffic='90'
	--verbose
`

But it's negative with it : 
`/usr/lib/centreon/plugins/centreon_linux_snmp.pl
	--plugin=os::linux::snmp::plugin
	--mode=interfaces
	--hostname=192.168.X.X
	--snmp-version='2c'
	--snmp-community='public' 
	--interface='^eth0$'
	--name
	--add-status
	--add-traffic
	--warning-in-traffic='80'
	--critical-in-traffic='90'
	--warning-out-traffic='80'
	--critical-out-traffic='90'`

Why ?

**Comment by o71** [comment]
Do you want more information ?

**Comment by Sims24** [comment]
Hi, 

As seen together it was a graph template issue. 

Thanks

**Comment by ygini** [comment]
@Sims24 and how did you solved it? Because I've exactly the same issue. Only traffic_out is visible on my graph, traffic_in is in legend but not visible on the graph itself. Even if I've valid input values.
