### ISSUE TITLE
[Chart] scale in charts using CPU template is wrong

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5130]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Centreon web 2.8.5

**Steps to reproduce the issue:**
1. Monitor CPU and link "CPU" chart template to this service
2. Go to "Monitoring  >  Performances  >  Graphs" and select service

**Describe the results you received:**

Max scale value is 10 000 (without "%" unit) and it is impossible to see curves.

**Describe the results you expected:**

Max scale value must be "100%".

**Additional information you think important (e.g. issue happens only occasionally):**
![screenshot at avr 03 10-17-23](https://cloud.githubusercontent.com/assets/3351916/24600838/c23c9a78-1856-11e7-9fb7-19e82a276e77.png)

**Comment by lpinsivy** [comment]
linked to #5123

**Comment by romsworld** [comment]
Same pb.
You can pu value "10" on Upper Limit to fix it...

**Comment by thiuyendang** [comment]
OK 2.8.9-11
Refer to #5123
