### ISSUE TITLE
Filter on the status host/service on the motiroring isn't working

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#5131]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.5
**Centreon Engine version**: 
1.7.0
**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Click on the warning/critical icon 
2. What is shown is all the services 
3.If you refresh the page , the filter is working

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi, should be corrected by ca498ffaf59732d448a590e45f665f133e88f04a

**Comment by thiuyendang** [comment]
Checked in Centreon Web 2.8.6 (engine 1.7.2-2)  CentOS6 and 7,, filters for hosts and services runs properly without refreshing the web page.
