### ISSUE TITLE
[2.8.5] Scroll bars on widgets

### ISSUE THREAD

**Issue by Gleamix** [centreon/centreon#5137]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Add a graph widget
2.
3.

**Describe the results you received:**

There are scroll bars on the right and bottom side hiding captions

![image](https://cloud.githubusercontent.com/assets/25056830/24742021/a7613e12-1aa8-11e7-8bb7-94dbb199e771.png)

**Describe the results you expected:**

The whole graph should be displayed without scroll bars like older versions

**Additional information you think important (e.g. issue happens only occasionally):**

Since upgrade to 2.8.5

**Comment by kozfelipe** [comment]
same issue (graph-monitoring plugin)

![image](https://cloud.githubusercontent.com/assets/25208457/25340698/ec16bd88-28dc-11e7-8d1e-ae6b9c1e3248.png)

**Comment by kduret** [comment]
Fix here : https://github.com/Centreon-Widgets/centreon-widget-graph-monitoring/commit/dcbf32cadf8d668c558b9a7d3f11049164e9a365
