### ISSUE TITLE
non-Admin-Users are able to add downtimes for a poller

### ISSUE THREAD

**Issue by Cancom-Monitoring** [centreon/centreon#5138]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**: CentOS release 6.8 (Final)

**Steps to reproduce the issue:**
1. Edit AddDowntime.php and replace the line

if (!$centreon->user->access->checkAction("schedule_downtime")) {

with

if (!$centreon->user->access->checkAction("host_schedule_downtime") || !$centreon->user->access->checkAction("service_schedule_downtime")) {

(see Bug Report https://github.com/centreon/centreon/issues/4952) 

2. Login as non-Admin-User
3. Go to Centreon Webinterface and browse to 'Monitoring -> Downtimes' 
4. Click on the button 'Add a Downtime'

**Describe the results you received:**
The page now shows different 'Downtime type'. Besides 'Host', 'Services', 'Hostgroup' and 'Servicegroup' a non-Admin-User also can choose 'Poller'. If 'Poller' is chosen, the non-Admin-User is able to set downtimes for all available Pollers (including Centreon Central)

**Describe the results you expected:**
A non-Admin-User should not be able to set downtimes for a Poller unless with an ACL he is allowed to.

**Additional information you think important (e.g. issue happens only occasionally):**
comment out the following lines to remove the radio button named 'Poller':

//$dtType[] = HTML_QuickForm::createElement(
//            'radio',
//            'downtimeType',
//            null,
//            _("Poller"),
//            '4',
//            array($disabled, 'id' => 'poller', 'onclick' => "toggleParams('poller');")
//        );

Best regards,
Daniel Friedlmaier

**Comment by lpinsivy** [comment]
Corrected in 19.10.4
