### ISSUE TITLE
[2.8.5] Filter services

### ISSUE THREAD

**Issue by vurmil** [centreon/centreon#5140]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: Centos

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware

**Steps to reproduce the issue:**
1. Click 
![image](https://cloud.githubusercontent.com/assets/15263415/24747927/3c7b694a-1abe-11e7-9dd5-5f0a7378909c.png)

2. Wait a few second (This does not always happen)
![image](https://cloud.githubusercontent.com/assets/15263415/24748044/ba17cba0-1abe-11e7-9941-faa478e86428.png)

3. or select all services and "Scheldue immediate check (Forced)
![image](https://cloud.githubusercontent.com/assets/15263415/24748103/eb183d34-1abe-11e7-95e4-9e295f8c5a76.png)

And u see all "Status"

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Fix by ca498ffaf59732d448a590e45f665f133e88f04a
