### ISSUE TITLE
The round of the curves

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#5143]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**: RH 6.8

Hi,

The round of the curves, false the reality of the values.

![image](https://cloud.githubusercontent.com/assets/16583698/24797728/d95be35a-1b92-11e7-9811-b438235d7a07.png)

This graph can not take a negative value
Excel export : 

![image](https://cloud.githubusercontent.com/assets/16583698/24797690/a2c81930-1b92-11e7-81ec-adb403b7961e.png)

**Comment by Shini31** [comment]
Still present since 2.8 beta:
- https://github.com/centreon/centreon/issues/4643
- https://github.com/centreon/centreon/issues/4644

**Comment by cgagnaire** [comment]
Looks good in 2.8.9 !

**Comment by thiuyendang** [comment]
curves not rounded in 2.8.9
