### ISSUE TITLE
Bad value on fresh install for Central Server

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5145]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**: CES 3.4.1

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Install Centreon with parameter Central Only
2. After install : update with yum update centreon*
3. Install and configure MariaDB
4. Do the web installation
5. Go on Configuration ==> Pollers ==> Central

**Describe the results you received:**
Central is not considered as default poller (field default poller set to "No")
Centreontrapd field as an incorrect value : centreontrapd instead of /etc/init.d/centreontrapd
Centreon Broker logs is empty

**Describe the results you expected:**
Default poller set to "Yes"
Centreontrapd : /etc/init.d/centreontrapd
Centreon Broker : /var/log/centreon-broker/

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lolokai** [comment]
Add :

In Monitoring Engine Init Script we have : /etc/init.d/centengine

But sudoers.d file is :

## BEGIN: CENTREON SUDO

User_Alias      CENTREON=%centreon
Defaults:CENTREON !requiretty

# centreontrapd
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd reload

# Centreon Engine
CENTREON   ALL = NOPASSWD: /sbin/service centengine start
CENTREON   ALL = NOPASSWD: /sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -v *

# Centreon Broker
CENTREON   ALL = NOPASSWD: /sbin/service cbd start
CENTREON   ALL = NOPASSWD: /sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd reload

## END: CENTREON SUDO

Sudo does not work

**Comment by lolokai** [comment]
Correction :

Monitoring Engine Init Script should be : centengine
 Centreontrapd init script path : centreontrapd

You should also change the name of field because it lead into error.

**Comment by lpinsivy** [comment]
should be corrected
