### ISSUE TITLE
Critical/Warning Escalation in a Single Meta-service

### ISSUE THREAD

**Issue by jason354007** [centreon/centreon#5146]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**:  RHEL 7.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. I have written a plugin in which if the status is WARNING , it will return 1 and trigger a Priority 2 ticket.
If the status is CRITICAL, it will return 2 and trigger a Priority 1 Ticket.
2.  Can we achieve this in a single meta-service ? If yes, please advise.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
HI,

I didn't understand your wish, can you explain?

Regards,

**Comment by lpinsivy** [comment]
No more information, I close this issue
