### ISSUE TITLE
miss Command Line Centreon on Clapi ?

### ISSUE THREAD

**Issue by ccoupeau** [centreon/centreon#5152]
Hey everyone,

I'm actually reorganizing my Centreon with some scripts and command line Centreon Clapi but i dont find all command i wanna use.

Do you know if the following commands exist : 

- Command would permit me to create an "Host Template" ?
- Command would permit me to link an "Host Parallel Templates to an Host Template" ?
- Command would permit me to "Link Service Templates to Host Template" ?

I didnt find it on the official documentation of Centreon Clapy ....

Thx for answer, 

You can save my life .... and so much time :o.

**Comment by Dacchi** [comment]
Hello,

For Host Templates, you can use all the commands available for Host as it's (almost) the same object.
You can find the documentation here => https://documentation.centreon.com/docs/centreon/en/2.8.x/api/clapi/objects/hosts.html#hosts

Regards

**Comment by ccoupeau** [comment]
Hum, i dont see how use this commands to add a new "Host Template" from this documentation (and others demands).
If it's almost the same, this command would work : 
[centreon@[...]]$ centreon -u [...] -p [...] -o template -a ADD -v "[...]"
Object TEMPLATE not found in Centreon API.

But this doesnt work :(

**Comment by Dacchi** [comment]
For all commands you just need to replace the object name HOST by HTPL.
In your example it would 

[centreon@[...]]$ centreon -u [...] -p [...] -o HTPL -a ADD -v "[...]"

For Host Templates, there's some limitations described here => https://documentation.centreon.com/docs/centreon/en/2.8.x/api/clapi/objects/host_templates.html#overview

**Comment by Sims24** [comment]
Hi @ccoupeau 

My personnal experience make me think that the simpliest way is to make a full extract to see the format of the lines and understand which dependencies exists between objects and then use script to create such file based upon this format and import it through CLAPI -i option. 

In your case it's HTPL but as there is no documentation about parameter, it's prelly tough.

**Comment by ccoupeau** [comment]
Hey,

Thx for all guys !
I get all i needed now thanks to you :)
I never saw option "HTPL" before .... ! Sorry ^^

Have a good day !
