### ISSUE TITLE
ACL / graphs - chart box. All hosts/services displayed

### ISSUE THREAD

**Issue by Cancom-Monitoring** [centreon/centreon#5154]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Centreon 2.8.5

Monitoring  >  Performances  >  Graphs:
Users can see host/service names in the "chart" box, even if ACL doesn't allow this.

**Steps to reproduce the issue:**
1. ACL "TEST" defined, add hosts and services allowed like "TEST-H-xy" and "TEST-S-xy"
2. Add host and Service "ABC-H-xy" "ABC-S-xy" (which do not! belong to the ACL)
3. Login with a user of the ACL "TEST",  go to Monitoring  >  Performances  >  Graphs
4. Type at least 3 (existing) characters in the "Chart" box, and you will see all (existing) hosts/services names.

Long term short:
Users can see host/service names in the chart box, when they are searching.
However, results will not be displayed (in a graph), if you klick on a result

This behaviour only belongs to the "chart" field, others (like "filter by host") not affected.

**Comment by lpinsivy** [comment]
Can't reproduce with Centreon Web 2.8.12, should be resolved
