### ISSUE TITLE
2.8.5 - REST API get service status

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon#5155]
Hello,

We are currently trying the rest API implemented in centreon 2.8.X. 

Is it actually possible to return the status (OK, WARNING, CRITICAL ..) of a specified service on a specifed host ? It seems that for now we can only modify configuration through the API.

Thank you !

Anthony

**Comment by anthoc** [comment]
Hi Dacchi.

OK :(  Thank you for your fast answer !

**Comment by khba** [comment]
Is there any other way of retrieving a host or service status through a web service, API or anything ?

**Comment by george-vieira** [comment]
I highly recommend using mklivestatus, as much as it's not REST API (I've done something similar for this so can't be hard), it provides live status directly from centreon engine even if central DB is down you still get a live status.

**Comment by khba** [comment]
That's what I finally did, thanks!
