### ISSUE TITLE
Reporting in PDF

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5162]
[EN]
Hi there,

In the Reporting tab, it is possible to export to CSV format, it would be good to be able to do it in PDF format also.

Thanks in advance.
[EN]

[FR]
Bonjour,

dans l'onglet Reporting, il est possible d'exporter au format CSV, il serait bien de pouvoir le faire au format PDF également.

Merci par avance.
[FR]

ma version actuelle :
Centreon 2.8.5
Centreon Engine 1.7.1
MariaDB 5.5.53

**Comment by maksimatveev** [comment]
@fredo1988 The idea is not bad, but I use CSV -> PDF. This also makes it possible to draw up such a report for its tasks. At the discretion of the developers =)

**Comment by fredo1988** [comment]
@maksimatveev yes why not but my boss is impatient and prefer to press a button :)

**Comment by Moujimouja** [comment]
Hi,

Thanks for your feedback but this feature will not be implemented in Centreon. 

Just in case you don't know, you could have a look on Centreon MBI that gives you advanced reporting features and of course automatic PDF export of Centreon statistics (that you can automatically send to your boss via mail ;)). It may interest you.

- [Sample of reports](https://documentation.centreon.com/docs/centreon-bi-2/en/latest/_downloads/00_Centreon-BI-Samples-of-Reports.pdf)
- [Documentation](https://documentation.centreon.com/docs/centreon-bi-2/en/latest/)

Be aware that this is a commercial product.

Let me know if you have questions. If not, I'll close this ticket.
