### ISSUE TITLE
Export services with thresholds

### ISSUE THREAD

**Issue by Thibaut-ids** [centreon/centreon#5164]
Hi,

I would like to know if it was possible to do a service export with their criticality thresholds. I know that I can export my configuration with clapi but that's not what I'm interested in here.

My aim is to provide the services of each host with their thresholds.

Thanks.

**Comment by lpinsivy** [comment]
Hi,

It's not possible in Centreon.

Regards,

**Comment by Thibaut-ids** [comment]
Hi,

I have found a solution to work around my problem. I made a script that makes a query in base and sends the data, once formatted, by mail.

Thanks.
