### ISSUE TITLE
ASCII interprétation Comments

### ISSUE THREAD

**Issue by lesijac** [centreon/centreon#5166]
[EN]
Hi there,

There is a display bug in the comments, tab monitoring, downtime, Commments. Some characters are not well interpreted.

Thanks in advance.
[EN]

[FR]
Bonjour,

il y a un bug d'affichage dans les commentaire, onglet monitoring, downtimes, Commments. certains caractère ne sont pas bien interprétés.

Merci par avance.
[FR]

![image](https://cloud.githubusercontent.com/assets/25640319/25221052/0b0e2afe-25b4-11e7-8dd3-6bc74f2c5dba.png)

ma version actuelle :
Centreon 2.8.5
Centreon Engine 1.7.1
MariaDB 5.5.53

**Comment by Moujimouja** [comment]
Hi,

This is fix in the latest Centreon version. You should update to version >= 19.10 to benefit from the latest evolutions & patches.

Have a nice day
