### ISSUE TITLE
Graphs -> Traffic curves are not correctly managed when using custom period parameters

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#5168]
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5
**OS**: CentOS 6

**Steps to reproduce the issue:**
1. Display a traffic graph with traffic_in < 0 and traffic-out > 0 
2. Change the period using the custom period parameters
3. Mouse over traffic_in 
--> result : it highlights the traffic_out
--> expected : highlight the traffic_in

1. Display a traffic graph with traffic_in < 0 and traffic-out > 0 
2. Change the period using the custom period parameters
3. Click on one curve to hide it
 --> result : it hides both curves
 --> result : hide only the corresponding curve

![traffic_bug](https://cloud.githubusercontent.com/assets/6620287/25228959/afa16bca-25ce-11e7-90e3-4ad79415fe0c.gif)

**Comment by lpinsivy** [comment]
I can't reproduce this on future next release 2.8.6

**Comment by leo29041982** [comment]
Can confirm it with 2.8.5

**Comment by leo29041982** [comment]
Still with 2.8.6 with Chrome and Firefox. Even with Dropdown Period Switch to 6 hours and back to 3 hours.

![image](https://cloud.githubusercontent.com/assets/24585227/25420047/731796c0-2a56-11e7-82bd-5b4a32009f7b.png)

**Comment by Moujimouja** [comment]
So we don't need more information, we need to fix that :-p

**Comment by lpinsivy** [comment]
It works on Centreon Web 2.8.9
