### ISSUE TITLE
[2.7.8] Problem multi downtime manual.

### ISSUE THREAD

**Issue by mickael-decastro** [centreon/centreon#5169]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  Centreon Web 2.7.8

**Centreon Engine version**:  Centreon Engine 1.5.3

**Centreon Broker version**: Centreon Broker 2.11.8

**OS**:  CentOS release 6.7 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.)**: It is a virtual machine (Vmware)

**Steps to reproduce the issue:**
1. Select a service to set downtime
2. Select Start time and End Time using the calendar.
3. Validate downtime.
4. Select another service to set a downtime (on the same page)
5. Select Start time and End Time using the calendar.
 

**Describe the results you received:**
The selection  (Start time and End Time) doesn't work. 

**Describe the results you expected:**
The Start Time and End Time should be match with the previous selection. 

**Additional information you think important (e.g. issue happens only occasionally):**
If we reload the page,  problem disappear.

**Comment by lpinsivy** [comment]
Hi,

Which menu did you use to set your downtimes?

Regards

**Comment by lpinsivy** [comment]
No more information to reproduce i close this issue
