### ISSUE TITLE
Problem of scale 'y'

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#5176]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.1

**Centreon Broker version**: 3.0.5

**OS**: RH6.8

Problem of scale 'y' when using two axes.

With one axes:

![image](https://cloud.githubusercontent.com/assets/16583698/25381052/a6b32002-29b2-11e7-9e18-a6121c85b7c4.png)

With two axes:

![image](https://cloud.githubusercontent.com/assets/16583698/25381114/d8e36320-29b2-11e7-981d-962b9e10e3a7.png)

Change of code "centreon-graph.js" : 

```
      if (axis.hasOwnProperty('y2')) {
        axis.y2.tick = {
          format: this.roundTick
        };
      }
```
By,
```
      if (axis.hasOwnProperty('y2')) {
        axis.y2.tick = {
          format: this.roundTick
        };
        axis.y.tick = {
            format: this.roundTick
        };
      }
```

The result : 

![image](https://cloud.githubusercontent.com/assets/16583698/25381262/51197618-29b3-11e7-986b-bb371282d32c.png)

**Comment by lpinsivy** [comment]
@jben94 should be OK with Centreon Web 2.8.9 version?

**Comment by jben94** [comment]
Hi @lpinsivy,

If the problem has been resolved we can close the issue.
We have not yet scheduled an update, so we can not check for the moment.
