### ISSUE TITLE
[2.8.6] Argument description

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon#5178]
La description des arguments ne suis pas les consignes lors de l'ajout d'une commande.
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.6

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.5

**OS**: CentOS 6.9

**Steps to reproduce the issue:**
1. Commands > Add
2. $USER1$/check_http -w $ARG1$ -c $ARG2$ -H $HOSTADDRESS$
3. Describe arguments
4. $ARG1$: WARNING [sec]
5. $ARG2$: CRITICAL [sec]

Il est impossible d'entrer certains caracteres dans le champ, par exemple "(".

1. Services > Templates
2. Check HTTP > Args
Argument: WARNING sec ARG2: CRITICAL sec
ARG2

**Comment by jmelus** [comment]
Same problem. Arguments are not correctly stored in DB.

**Comment by kozfelipe** [comment]
**Argument Descriptions:**

![image](https://cloud.githubusercontent.com/assets/25208457/26125854/d64488a8-3a59-11e7-99d6-fd0ec9a8537e.png)

**Argument Display:**

![image](https://cloud.githubusercontent.com/assets/25208457/26125910/07465b70-3a5a-11e7-8a4f-a2a1df2d48b3.png)

Also, I couldnt set an argument example that would appear in the right field

**Comment by lpinsivy** [comment]
@kozfelipe I can't reproduce your issue on Centreon Web 2.8.9.

@stefanotoro I can't reproduce your issue too. I can save my form with () characters

![screenshot at juin 14 11-04-34](https://user-images.githubusercontent.com/3351916/27126374-8534b500-50f7-11e7-8f4c-ae726ea13203.png)

**Comment by kozfelipe** [comment]
@lpinsivy 2.8.9 might have solved my issue. I recreated arguments description for my command, and it shows correctly at display

**Comment by stefanotoro** [comment]
Effectively in 2.8.9 it seems to be corrected. I don’t have any error now.

Thank you
