### ISSUE TITLE
Host names don't get correctly safed in 2.8.6 CES

### ISSUE THREAD

**Issue by olafbecker** [centreon/centreon#5182]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.6

**Centreon Engine version**: 
1.7.2 

**Centreon Broker version**: 
3.0.5

**OS**: 
CentOS-6.9 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ISO CES 

**Steps to reproduce the issue:**
Servers get screwed up with special numbering since last upgrade. 

**Describe the results you received:**
You have a host called : sf1-dmz01  results in sf1-dmz1 
If you do  sf1-dmz03 it results in sf1-dmz 

**Describe the results you expected:**
sf1-dmz03 should stay that way when saved.

**Additional information you think important (e.g. issue happens only occasionally):**
![centreon-name-issue](https://cloud.githubusercontent.com/assets/15946174/25461891/9098e15a-2ab9-11e7-87bc-9fc8cd56f0dd.JPG)

**Comment by cgagnaire** [comment]
Hi,
It looks like you're having problems with illegal character treatment.
You should apply this patch : https://github.com/centreon/centreon/commit/c015bce8e79c2235a0254661e758f8be7243065d
And then look at the "Admin" form of your engines configuration and change those 2 lines : 
Illegal Object Name Characters : \~!$%^&*"|'<>?,()=
Illegal Macro Output Characters : `\~$^&"|'<>
Hope it'll do the trick.

**Comment by olafbecker** [comment]
Ok I checked the filed you listed above and mine where really strange : 
Illegal Object Name Characters : ~!$%^&#38;#38;*&#38;#34;|&#38;#39;&#38;#60;&#38;#62;?,()=
Illegal Macro Output Characters : `~$^&#38;#38;&#38;#34;|&#38;#39;&#38;#60;&#38;#62; 

So I correct the Object and Macro Characters as mentioned above. But looking the patch it looks completely different on my end. So do I still change the code or not ? 

The mentioned patch was already applied because I do use Version 2.8.6 

    isset($ret["illegal_object_name_chars"]) && $ret["illegal_object_name_chars"] != null ?
        $rq .= "'".htmlentities($ret["illegal_object_name_chars"], ENT_QUOTES, "UTF-8")."',  " : $rq .= "NULL, ";
    isset($ret["illegal_macro_output_chars"]) && $ret["illegal_macro_output_chars"] != null ?
        $rq .= "'".htmlentities($ret["illegal_macro_output_chars"], ENT_QUOTES, "UTF-8")."',  " : $rq .= "NULL, ";

Even I replace it just for giggles but it still happens.  

Any other suggestions ?

**Comment by olafbecker** [comment]
I fixes when I leave both field empty which is not ideal but it works for now. 

Somehow when i put those Chars in it translate them while it be stored back to the Database.

**Comment by lpinsivy** [comment]
It's a problem on 2.8.6 version. OK in 2.8.7

Regards,
