### ISSUE TITLE
custom views plugin Widget Preferences for Hosts [hostgroup-monitoring]

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5183]
[EN]
Hi there,

Today in the report sheet, only 4 reports, ok, warning, critical and unknown.
However, when a service / host is aknowledge or downtime, this is not stipulated. I suggest adding 2 colors corresponding to the downtime and acknowledge (violet and yellow) in order to have a closer view of the reality.

If a host is in critical but acknoledge then display only one yellow and not red dot.

Thanks in advance.
[EN]

[FR]
Bonjour,

aujourd'hui dans le bilan, seul 4 rapports, ok , warning, critical et unknown.
cependant, quand un service/host est aknowledge ou downtime, cela n'est pas stipulé. je suggère d'ajouter 2 couleurs correspondant au downtime et acknowledge (violet et jaune) afin d'avoir une vue au plus près de la réalité.

si un host est en critical mais acknoledge alors n'afficher qu'une pastille jaune et non rouge.

Merci par avance.
[FR]

![capture](https://cloud.githubusercontent.com/assets/25640319/25477882/5408e9f2-2b3f-11e7-8873-089a0af7c162.PNG)

ma version actuelle :
Centreon 2.8.5
Centreon Engine 1.7.1
MariaDB 5.5.53

**Comment by lpinsivy** [comment]
Can you move your request to this project: https://github.com/centreon/centreon-widget-hostgroup-monitoring/issues

Regards,

**Comment by fredo1988** [comment]
requet move to this project: https://github.com/centreon/centreon-widget-hostgroup-monitoring/issues
