### ISSUE TITLE
"Illegal Characters" parameter is bullshited

### ISSUE THREAD

**Issue by pateretou** [centreon/centreon#5184]
Hi

since the last upgrade (2.8.5) it's appear the "Illegal Characters" parameters (**Illegal Object Name Characters** and  **Illegal Macro Output Characters** in **Configuration  >  Pollers  >  Engine configuration / Admin** ) are simply overwritten by strange "protected" characters : 

Before saving a centengine setup : 

![image](https://cloud.githubusercontent.com/assets/5527345/25478337/01ee462e-2b41-11e7-87c7-8fd757a36a49.png)

after saving : 

![image](https://cloud.githubusercontent.com/assets/5527345/25478356/0d3edd18-2b41-11e7-8095-b33314aed3ae.png)

that's a very very annoying issue.
Will update directly in the DB

**Comment by cgagnaire** [comment]
Hi,
You should apply this patch : https://github.com/centreon/centreon/commit/c015bce8e79c2235a0254661e758f8be7243065d
And then change those 2 lines : 
Illegal Object Name Characters : \~!$%^&*"|'<>?,()=
Illegal Macro Output Characters : `\~$^&"|'<>

**Comment by pateretou** [comment]
Top merci :)

**Comment by julienmathis** [comment]
fixed in version 2.8.8

**Comment by cgagnaire** [comment]
OK in 2.8.9.

**Comment by thiuyendang** [comment]
After saving a change of Broker Configuration, Illegal Object Name Characters and Illegal Macro Output Characters are not modified.
OK 2.8.9.
