### ISSUE TITLE
[ACL] Bug on Access Groups

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#5189]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.6

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create 2 ressources access. RessourceA and RessourceB
2. Create 1 Access Groups and add RessourcesA and RessourceB on authorization information tab.
3.Save
4. Reopen the access group. You can see only RessourceA.
I thinks it's a diplay problem because when you check directly on RessourceA, or B, you can see that Acessgroup is link correclty.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Tpo76** [comment]
Can't remove Ressource in a Access Group

**Comment by thiuyendang** [comment]
TPO76 comment : true.

**Comment by lpinsivy** [comment]
fixed by 6080f2cfd381bc927b0ea4aea6df987f1cf3c614

**Comment by thiuyendang** [comment]
OK 2.8-12-2, centOS6 et 7
