### ISSUE TITLE
[2.8.6] Special characters are converted in Curves

### ISSUE THREAD

**Issue by sandwedge** [centreon/centreon#5190]
This may be a duplicate of #5184 but I do believe this only deals with web and curves not engine.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
`Centreon 2.8.6`

**OS**:  
`CentOS 7`

**Additional environment details (AWS, VirtualBox, physical, etc.**
Installed from RPMs on a fresh vanilla AWS image

**Steps to reproduce the issue:**
1. Create a Curve
2. Use an ampersand in the template name and save it.

**Describe the results you received:**
Ampersands are incorrectly converted or incorrectly displayed.  They were not in previous version (2.7.x)

**Describe the results you expected:**
To see and ampersand converted correctly or not converted in my Template name or the form restrict what I can insert.

**Comment by lpinsivy** [comment]
Works with Centreon web 2.8.12, should be corrected
