### ISSUE TITLE
fortigate no performance data

### ISSUE THREAD

**Issue by schmm2** [centreon/centreon#5191]
Hello there

I'm using the network::fortinet::fortigate::plugin in the VPN mode.
the traffic usage is reported correctly. sadly I don't get any performance data.
Other modes like CPU or Memory work as expected, performance data is returned and displayed in a graph.

Is there a parameter more I need to add?

Greetings & Thanks for your time

**Comment by garnier-quentin** [comment]
Hi,

Could you provides us the plugin output ? You can execute it in command line ?

**Comment by schmm2** [comment]
Image attached.
Everything works fine. Just no Perf Data.
Maybe I need to add another parameter to the plugin?

<img width="599" alt="screen shot 2017-05-02 at 01 03 01" src="https://cloud.githubusercontent.com/assets/11064825/25607091/41bbe22a-2f15-11e7-9dac-8caca1175cff.png">

**Comment by schmm2** [comment]
Did you have time to look into this issue?
Is there anything I can help you find the solution?

**Comment by garnier-quentin** [comment]
I don't think it's a centreon-plugins issue. I think if you execute the plugin direclty in a shell, you'll have perfdata in output

**Comment by schmm2** [comment]
I will check and post the results. Thanks :)

**Comment by schmm2** [comment]
Special. The perfdata is here...in icinga I don't see any perfdata. All values are set to 0.
In other modes for example cpu, the data is shown perfectly.

<img width="947" alt="screen shot 2017-05-11 at 00 50 00" src="https://cloud.githubusercontent.com/assets/11064825/25924628/0889ee18-35e4-11e7-8f75-616e5e59cbbb.png">

**Comment by garnier-quentin** [comment]
You should open the issue in icinga forum/github.
