### ISSUE TITLE
API Create on-demand downtime

### ISSUE THREAD

**Issue by vincenteam44** [centreon/centreon#5192]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.6
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.5
**OS**: 
CentOS release 6.9 (Final)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare Virtual Machine

**Steps to reproduce the issue:**
1. Add downtime through Postman and Centrean Rest API:
![image](https://cloud.githubusercontent.com/assets/25186162/25608383/e7e347f6-2f1a-11e7-810e-8cb1ff982a14.png)
![image](https://cloud.githubusercontent.com/assets/25186162/25608398/f6a342be-2f1a-11e7-8961-9a190fde79ad.png)

https://documentation.centreon.com/docs/centreon/en/2.8.x/api/clapi/objects/index.html

https://documentation.centreon.com/docs/centreon/en/2.8.x/api/api_rest/index.html#downtimes

2. Only recurrent downtime creation is available

**Describe the results you received:**
I can create recurrent downtime through Rest API but no information how to create one shot downtime.

**Describe the results you expected:**
I would like to know if it's possible to create downtime on the fly ? For example when running application maintenance update we want to send Centreon dowtime to service or service group involved in application update.
Since application update can be done at every moment, it can't be a reccurent downtime...
Any solution ? 

**Additional information you think important (e.g. issue happens only occasionally):**

Thanks

**Comment by adrianoguilhermetti** [comment]
Any solution to this problem?
I use Centreon 2.7.1 and also need this functionality.
Thank you!
