### ISSUE TITLE
NRPE daemon -> NRPE: Unable to read output

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#5193]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.6

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.5

**OS**: Centreon3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**

centreon-nrpe-daemon-2.15-2.el6.x86_64

**Steps to reproduce the issue:**
1. When I test this line
    /usr/lib/nagios/plugins/check_centreon_nrpe -H 127.0.0.1 -c check_load

**Describe the results you received:**
Here is the result
  NRPE: Unable to read output

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

The paths in the configuration file are not good

command[check_users]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10
command[check_load]=/usr/lib64/nagios/plugins/check_load -w 15,10,5 -c 30,25,20
command[check_hda1]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /dev/hda1
command[check_zombie_procs]=/usr/lib64/nagios/plugins/check_procs -w 5 -c 10 -s Z
command[check_total_procs]=/usr/lib64/nagios/plugins/check_procs -w 150 -c 200

it is necessary

command[check_users]=/usr/lib/nagios/plugins/check_users -w 5 -c 10
command[check_load]=/usr/lib/nagios/plugins/check_load -w 15,10,5 -c 30,25,20
command[check_hda1]=/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -p /dev/hda1
command[check_zombie_procs]=/usr/lib/nagios/plugins/check_procs -w 5 -c 10 -s Z
command[check_total_procs]=/usr/lib/nagios/plugins/check_procs -w 150 -c 200

**Comment by lpinsivy** [comment]
should be ok in latest rpm
