### ISSUE TITLE
LDAP authentication failed since 2.8.6 upgrade or Poller remove

### ISSUE THREAD

**Issue by vincenteam44** [centreon/centreon#5196]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.6
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.5
**OS**: 
CentOS release 6.9 (Final)
**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare Virtual Machine

**Steps to reproduce the issue:**
1. Upgrade Centreon from 2.8.4 to 2.8.6
2. Delete old Poller information in Web UI
3.LDAP authentication fail

**Describe the results you received:**
![image](https://cloud.githubusercontent.com/assets/25186162/25659454/2b3ab3d4-3008-11e7-98d6-a8f90580aec3.png)

As Local Admin account i can't access LDAP site setup:
![image](https://cloud.githubusercontent.com/assets/25186162/25659471/3c4f15e8-3008-11e7-8ef8-2a27cdc89cfb.png)

Ldap search OK:
![image](https://cloud.githubusercontent.com/assets/25186162/25659904/382eb9b2-300a-11e7-9b31-981ab0c9942a.png)

ldapsearch.log:
![image](https://cloud.githubusercontent.com/assets/25186162/25660061/e6dbaf06-300a-11e7-92fb-8917c2034dca.png)

login.log
![image](https://cloud.githubusercontent.com/assets/25186162/25660079/fbe2ebbc-300a-11e7-82bd-0438d772f610.png)

**Describe the results you expected:**
Successfull authentication ;-)

**Additional information you think important (e.g. issue happens only occasionally):**
* Internal AD infrastructure is ok

**Comment by mvBoy** [comment]
Hi, 

Exactly same issue for me.
My configuration :
*OS : CentOS release 6.9 (Final) (up to date)
*Centreon 2.8.6
*Centreon Engine 1.7.1 
*Database : MariaDB 10.1.23
*Dedicated Server
*AD on WindowsServer 2012R2

When I import a user, in database I see NULL in contact.contact_passwd (whith or without store password option in LDAP) and I can't open my LDAP connexion to change settings.
Thanks.

**Comment by thiuyendang** [comment]
2.8.7 Centreon Web, CentOS6 et 7
OK
