### ISSUE TITLE
After using split chart, curves are not displayed anymore (period filter not applied)

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5198]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.7

**Centreon Engine version**:  1.7.2

**Centreon Broker version**: 3.0.5

**OS**: centOS7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to page Monitoring > Performance > Graphs
2. Select a chart (ping for example) and a period (last 3 days e.g.)
3. Click  split chart button

**Describe the results you received:**
Fields From and To are properly filled with dates related with the selected period filter but curves have disappeared.

**Describe the results you expected:**
Curves should be split in several graphs

Before split 

![beforesplit](https://cloud.githubusercontent.com/assets/25612980/25698168/0f9d6d54-30be-11e7-9fbc-19668a7fe1f2.png)

After split 
![aftersplit](https://cloud.githubusercontent.com/assets/25612980/25698235/5c3e2e50-30be-11e7-9397-b526945079c9.png)

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by kduret** [comment]
Works for me with Centreon 2.8.x branch

Probably fixed in 2.8.9 : 
981e755d20cd6a3ac0e65986c996aaa588ce0f3a
1906b357628620500125b1f26f2122f23ff3b6d3
3e25ef7352845644ca20ef7740f0e18fec63aaec
f861ec274b17dc0fb4081759c7aa35c6b584ed0d

**Comment by thiuyendang** [comment]
KO in 2.8.9-6
The curves are displayed but the wrong period is applied after split.

Before split 
![beforesplitperiod](https://cloud.githubusercontent.com/assets/25612980/26545719/03305eac-4467-11e7-9179-be5e327e3f71.png)

After plit
![aftersplitperiod](https://cloud.githubusercontent.com/assets/25612980/26545726/0c41f2ee-4467-11e7-8ab3-1548f52dad14.png)

**Comment by thiuyendang** [comment]
OK 2.8.9-7
After split chart, period choosen by user is properly applied to all curves.
