### ISSUE TITLE
discarding membership between host 623 and host group 75 on instance 60: could not execute prepared statement: Duplicate entry '75' for key 'PRIMARY' QMYSQL3: Unable to execute statement

### ISSUE THREAD

**Issue by DRAKUN** [centreon/centreon#5200]
Hello i have this message error when i check my log file 

discarding membership between host 623 and host group 75 on instance 60: could not execute prepared statement: Duplicate entry '75' for key 'PRIMARY' QMYSQL3: Unable to execute statement
discarding membership between host 623 and host group 134 on instance 60: could not execute prepared statement: Duplicate entry '134' for key 'PRIMARY' QMYSQL3: Unable to execute statement
discarding membership between host 623 and host group 132 on instance 60: could not execute prepared statement: Duplicate entry '132' for key 'PRIMARY' QMYSQL3: Unable to execute statement
discarding membership between host 623 and host group 62 on instance 60: could not execute prepared statement: Duplicate entry '62' for key 'PRIMARY' QMYSQL3: Unable to execute statement
discarding membership between host 623 and host group 240 on instance 60: could not execute prepared statement: Duplicate entry '240' for key 'PRIMARY' QMYSQL3: Unable to execute statement

discarding membership between service (623, 358) and service group 2 on instance 60: could not execute prepared statement: Duplicate entry '2' for key 'PRIMARY' QMYSQL3: Unable to execute statement
discarding membership between service (623, 358) and service group 4 on instance 60: could not execute prepared statement: Duplicate entry '4' for key 'PRIMARY' QMYSQL3: Unable to execute statement

SomeOne can help me to fixit

**Comment by julienmathis** [comment]
Please, Follow our guideline to open a issue. We have no version, no information regarding your setup... It's very hard to help us.
Please give us the following informations.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**


**Steps to reproduce the issue:**
1.
2.
3.


**Describe the results you received:**


**Describe the results you expected:**


**Additional information you think important (e.g. issue happens only occasionally):**
