### ISSUE TITLE
Wrong tool tip display on chart with two units when one of the curves is disabled

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5203]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.7

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.5

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Go to Monitoring > Performances > Graphs
2. Display a ping chart
3. disable PL curve by clicking on the colored square under the graph
4. Move along  the remaining curve (that should be rta curve)

**Describe the results you received:**
- tooltip shows value of the disabled curve

![tooltip](https://cloud.githubusercontent.com/assets/25612980/25751277/b812e094-31b4-11e7-93eb-73002509da3f.png)

**Describe the results you expected:**
- tooltip should show values of the pl curve

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by kduret** [comment]
Fixed here : 3e25ef7352845644ca20ef7740f0e18fec63aaec

**Comment by thiuyendang** [comment]
OK 2.8.9
