### ISSUE TITLE
Feature request: automatic downtime during bank holiday

### ISSUE THREAD

**Issue by GuillaumeBernard** [centreon/centreon#5207]
Hello,

In Centreon, I declared a service that checks if a file exists. If the file doesn't exist during a work day, it means that there is a problem. But it's normal that the file doesn't exist during bank holiday.
Currently, we set a downtime manually during bank holidays, but sometimes we forget to do it and the service goes "critical".

I would like to be able to put this service in downtime automatically during bank holidays.

Regards,
Guillaume Bernard

**Comment by kduret** [comment]
You can use recurrent downtimes to do it : Monitoring -> Downtimes -> Recurrent downtimes

**Comment by GuillaumeBernard** [comment]
Hello,

This works for fixed bank holiday, but not for moving bank holidays like Easter Monday or Ascension Day.

Regards,
Guillaume

**Comment by lpinsivy** [comment]
Hi,

It is possible to send punctual downtimes for a specific date using "Monitoring > Downtimes > Downtimes" menu.

The downtimes will be store by Centreon Engine.
