### ISSUE TITLE
InfluxDB broker output config not stored properly

### ISSUE THREAD

**Issue by mickael-decastro** [centreon/centreon#5208]
BUG REPORT INFORMATION

Centreon Web version: 2.8.7

Centreon Engine version: 1.7.2

Centreon Broker version: 3.0.5

OS: CentOS 6.8

Additional environment details (AWS, VirtualBox, physical, etc.): VM on vmware environment

Steps to reproduce the issue:

1 - Go to Configuration -> Pollers -> Broker configuration
2 - Add InfluxDB output somewhere
3 - Enter metric and status colums
4- save

Describe the results you received:
Metrics and status are saved with the first entry empty. When we re-open the influxdb configuration we see metric and status entries with default type and tag. 

Describe the results you expected:
All metric columns get saved with the right parameters (type and tag). Without an empty entry. 

Additional information you think important (e.g. issue happens only occasionally):
Happens always. When generating the configuration, the parameters broker .xml are ok but an empty entry for metric and status are present.

**Comment by tmaff** [comment]
is it possible to edit the settings manual? :S

**Comment by lpinsivy** [comment]
Seems to be corrected on Centreon Web 2.8.11
