### ISSUE TITLE
Impossible to save any changes in the configuration of centreon-engine

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5209]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.7
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.5
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1. Go to Configuration  >  Pollers  >  Engine configuration > 
2. Modify any element and confirm
3. Go back to this page, the changes has been saved

**Comment by tseegers** [comment]
Hello,

Update: The problem is present for any changes made in "Configuration  >  Pollers  >  Engine configuration"

**Comment by Dacchi** [comment]
A fix is available here 4f941fefdab59994abc2e307f0dd01825a3c93b5

**Comment by cgagnaire** [comment]
OK in 2.8.9.

**Comment by thiuyendang** [comment]
OK 2.8.9 CentOS6
