### ISSUE TITLE
Single quote transformed into &#39; 

### ISSUE THREAD

**Issue by 5145h** [centreon/centreon#5211]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.6-4.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.7.2-3.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-3.0.5-2.el7.centos.x86_64

**OS**: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Additional environment details (AWS, VirtualBox, physical, etc.):** Vm

**Steps to reproduce the issue:**
1. Web GUI -> Configuration -> Commands
2. Define command.
3.  Write the command in the textarea of the "Modify command" form as follows:
`$CENTREONPLUGINS$/centreon_plugins.pl --plugin=network::juniper::ex::plugin --mode=hardware --component=fru --snmp-version=$ARG1$ --snmp-community=$ARG2$ --hostname $HOSTADDRESS$ --warning='fru-temperature,.*,$ARG3$' --critical='fru-temperature,.*,$ARG4$'`

** Describe the results you received:**
`$CENTREONPLUGINS$/centreon_plugins.pl --plugin=network::juniper::ex::plugin --mode=hardware --component=fru --snmp-version=$ARG1$ --snmp-community=$ARG2$ --hostname $HOSTADDRESS$ --warning=&#39;fru-temperature,.*,$ARG3$&#39; --critical=&#39;fru-temperature,.*,$ARG4$&#39;`

**Describe the results you expected:**
`$CENTREONPLUGINS$/centreon_plugins.pl --plugin=network::juniper::ex::plugin --mode=hardware --component=fru --snmp-version=$ARG1$ --snmp-community=$ARG2$ --hostname $HOSTADDRESS$ --warning='fru-temperature,.*,$ARG3$' --critical='fru-temperature,.*,$ARG4$'`

**Additional information you think important (e.g. issue happens only occasionally):**
I have the following patch applied: https://github.com/centreon/centreon/commit/c015bce8e79c2235a0254661e758f8be7243065d

```

**Comment by lpinsivy** [comment]
Linked to #5205
