### ISSUE TITLE
Services missing in configuration for disabled hosts

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#5212]
Centreon 2.7.7
Centreon Engine 1.5.1
Centreon Broker 2.11.5

If under Configuratoin -> Hosts you disable HostX, the services belonging to HostX under Configuration -> Services -> Services by Host the services belonging to HostX will not be visible.

Workaround: temporarily enable HostX again, don't reload poller until you check/change whatever you need and disable it again. I'm using this for duplicated hosts for new hostgroups which are prepared ahead of time but have slightly different services per host for example.

**Comment by lpinsivy** [comment]
Hi

Know issue with Centreon Web 2.7.x.

A new option was added into 2.8.x to display these.
