### ISSUE TITLE
[2.8.7] Some features do not work in data Performance Management

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#5213]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.7

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.6

**OS**: centreon 3.4.1

fresh install and update 2.8.5 -> 2.8.7

Administration  >  Parameters  >  Data
Previous and next page do not work
The list of actions does not work (generate, delete, etc)

**Comment by kermith72** [comment]
Still does not work with version 2.8.8

**Comment by cgagnaire** [comment]
Works for me. 2.8.8-4.

**Comment by cgagnaire** [comment]
Well, I may have been to quick : the pagination still not work.
