### ISSUE TITLE
[2.8.7] Missing argument 1 for PEAR::isError()

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon#5214]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.7

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.6

**OS**: CentOS 6.9

**Steps to reproduce the issue:**
1. centreon -u admin -p password -a applycfg -v Central

**Describe the results you received:** Error message, but configuration seems to be applied
PHP Warning:  Missing argument 1 for PEAR::isError(), called in /usr/share/centreon/www/class/centreonHost.class.php on line 1257 and defined in /usr/share/pear/PEAR.php on line 250

**Comment by karhm** [comment]
i have the same problem
Centreon Web version: 2.8.8

Centreon Engine version: 1.7.2

Centreon Broker version: 3.0.6

OS: CentOS 7.2

Steps to reproduce the issue:

centreon -u admin -p password -a applycfg -v Central
**Describe the results you received:** Error message, but configuration seems to be applied
PHP Warning: Missing argument 1 for PEAR::isError(), called in /usr/share/centreon/www/class/centreonHost.class.php on line 125 and defined in /usr/share/pear/PEAR.php on line 250

**Comment by julienmathis** [comment]
Please apply the patch and validate that it's ok for you.

Thanks in advance !

**Comment by stefanotoro** [comment]
Salut,

Patch appliqué, problème corrigé !

Merci infiniment
Bonne suite

Stefano

**Comment by cgagnaire** [comment]
Works in 2.8.9.

**Comment by stefanotoro** [comment]
Thanks !

**Comment by thiuyendang** [comment]
OK 2.8.9, no more error when lauching CLAPI command
