### ISSUE TITLE
[2.8.8] Deploy Service action won't work

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#5215]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vSphere 6.0

**Steps to reproduce the issue:**
1. Go to 'Configuration > Hosts'
2. Edit a host by adding a new host template
3. Select the host and select 'Deploy Service' on the 'More actions...' dropdown menu

**Describe the results you received:**
I have a blank page and this error in httpd error log : 
[Thu May 11 17:43:36.328593 2017] [:error] [pid 35267] [client 10.40.1.159:55046] PHP Fatal error:  Uncaught exception 'Exception' with message 'Error while insert service Cpu' in /usr/share/centreon/www/class/centreonService.class.php:1390\nStack trace:\n#0 /usr/share/centreon/www/class/centreonHost.class.php(1794): CentreonService->insert(Array)\n#1 /usr/share/centreon/www/include/configuration/configObject/host/DB-Func.php(2348): CentreonHost->deployServices(59)\n#2 /usr/share/centreon/www/include/configuration/configObject/host/host.php(133): applytpl(Array)\n#3 /usr/share/centreon/www/main.php(250): include_once('/usr/share/cent...')\n#4 {main}\n  thrown in /usr/share/centreon/www/class/centreonService.class.php on line 1390, referer: http://10.30.2.131/centreon/main.php?p=601

**Describe the results you expected:**
New services from the host template attached to my host.

**Additional information you think important (e.g. issue happens only occasionally):**
This does not happen when all the services are already deployed :p

**Comment by cgagnaire** [comment]
Related to https://github.com/centreon/centreon/issues/5010

**Comment by cgagnaire** [comment]
For information, my database server is a MariaDB 10.1.19.
And I can deploy services using the 'Create Services linked to the Template too' option.

**Comment by cgagnaire** [comment]
Fixed in 2.8.9.

**Comment by thiuyendang** [comment]
OK 2.8.9-6
