### ISSUE TITLE
Centreon Web GUI - Blank Page After LDAP authentication

### ISSUE THREAD

**Issue by dataenligne** [centreon/centreon#5216]
Hi,
We have recently updated Centreon RPMs. 
We are now using the following:
```
centreon-plugins-2.7.10-3.el6.noarch
centreon-engine-1.5.3-1.el6.x86_64
centreon-plugin-meta-2.7.10-3.el6.noarch
centreon-broker-storage-2.11.8-2.el6.x86_64
centreon-clib-1.4.2-1.el6.x86_64
centreon-trap-2.7.10-3.el6.noarch
centreon-engine-extcommands-1.5.3-1.el6.x86_64
centreon-broker-2.11.8-2.el6.x86_64
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-common-2.7.10-3.el6.noarch
centreon-web-2.7.10-3.el6.noarch
centreon-engine-daemon-1.5.3-1.el6.x86_64
centreon-broker-cbmod-2.11.8-2.el6.x86_64
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-base-config-centreon-engine-2.7.10-3.el6.noarch
centreon-broker-core-2.11.8-2.el6.x86_64
centreon-connector-1.1.2-1.el6.x86_64
centreon-perl-libs-2.7.10-3.el6.noarch
centreon-2.7.10-3.el6.noarch
centreon-broker-cbd-2.11.8-2.el6.x86_64
```

For some reason, after being authenticated at the centreon web login prompt, we're getting a blank page.

Authentication is being made through LDAP.

httpd error log file shows the following:
```
[Thu May 11 22:16:39 2017] [error] [client some-ip-here] PHP Notice:  Undefined property: CentreonLDAP::$db in /usr/share/centreon/www/class/centreonLDAP.class.php on line 171, referer: http://monitoring.some-domain.com/centreon/index.php

[Thu May 11 22:16:39 2017] [error] [client some-ip-here] PHP Fatal error:  Call to a member function escape() on a non-object in /usr/share/centreon/www/class/centreonLDAP.class.php on line 171, referer: http://monitoring.some-domain.com/centreon/index.php
```

Do you guys have any ideas what might wrong?

**Comment by NicolasLarrouy** [comment]
Same.
Update from 2.7.8

**Comment by Dacchi** [comment]
Hello

Fixes are available here
    + 610a983eb81fda81e6a1c5f66cd7e7af1116d8c8
    + 5f6d0e7e42a56893964adf60da40878f5425e400

**Comment by dataenligne** [comment]
Hi  Dacchi,
I have applied these fixes and now getting the following error:
`[Fri May 12 09:47:53 2017] [error] [client some_ip_here] PHP Fatal error:  Call to undefined method CentreonLDAP::debug() in /usr/share/centreon/www/class/centreonLDAP.class.php on line 207, referer: http://monitoring.dataenligne.com/centreon/index.php`

Please let me know if you need further information.

Thanks!

**Comment by thiuyendang** [comment]
Checked with Centreon-web 2.7.11, centOS6.
LDAP configuration OK
LDAP search filters OK 
LDAP connection OK
