### ISSUE TITLE
[2.8.7] - Timezone / Location BUG !! 

### ISSUE THREAD

**Issue by gabrielfsousa** [centreon/centreon#5218]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.7
**Centreon Engine version**: 1.7.2
**Centreon Broker version**: 3.0.6
**OS**:  CentOS - 6.9
---------------------------------------------------
---------------------------------------------------
Exporting is saving the wrong TIME ZONE on hosts.cfg :(

![image](https://cloud.githubusercontent.com/assets/722744/25991519/517ecc5c-36fb-11e7-9a1f-190067b75179.png)

when i export the configuration , the file  hosts.cfg i have 

![image](https://cloud.githubusercontent.com/assets/722744/25991788/772a2162-36fc-11e7-8583-41723f5e3791.png)

on 2.8.5 version this was working good...
if theres anything i can do in my side , please tell, i use alot TZ

**Comment by gabrielfsousa** [comment]
can you tell me what i have to change... i need this urgent !!

**Comment by Sims24** [comment]
Can confirm this, all timezone are generated from value in "Administration > Options  > Monitoring". 

Even if I set a timezone on my host, the "default value" for contact and hosts will be used. 

High impact here as it generatse a lot of false positive issues !

**Comment by Sims24** [comment]
@gabrielfsousa bug has been spotted, the team are working actively on it. In the meantime you can play with the "default value" to minimize impacts. 

thanks

**Comment by gabrielfsousa** [comment]
@Sims24  in Administration  >  Parameters  >  Monitoring ?

**Comment by Sims24** [comment]
Sorry in Administration Options Monitoring UI. One of the last parameter at the bottom of the page .

**Comment by gabrielfsousa** [comment]
i dont have Monitoring UI :(

![image](https://cloud.githubusercontent.com/assets/722744/26154643/421715e2-3b08-11e7-8979-0ae57474c147.png)

**Comment by Sims24** [comment]
@gabrielfsousa sorry bad memory here :) but Centreon UI is the right one ... Just did some miiix ! 

Anyway, you issue should be fixed with https://github.com/centreon/centreon/commit/05a42adc30de328f3f5ede930411032871ba0e08

Please confirm us that it actually solve your issue. 

thanks

**Comment by gabrielfsousa** [comment]
i will update the php files, THANKS A LOT !!

**Comment by Sims24** [comment]
@loiclau thanks for your work. We'll get a feedback on it from @gabrielfsousa soon

**Comment by gabrielfsousa** [comment]
it WORKS !!!  thanks a lot

**Comment by cgagnaire** [comment]
Fixed in 2.8.9.

**Comment by thiuyendang** [comment]
Checked with 2.8.9 CentOS6
- Changed Timezone for one host
- Exported configuration
- Verified hosts.cfg

The new value of the host timezone is properly saved.

**Comment by thiuyendang** [comment]
/usr/share/centreon/filesGeneration/engine/1/hosts.cfg

1 = poller id
