### ISSUE TITLE
2.8.8  Service Trap Relation empty

### ISSUE THREAD

**Issue by loiclau** [centreon/centreon#5223]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.8

**Steps to reproduce the issue:**
1. Add a Service Trap Relation for a service

**Describe the results you received:**
element not found

**Describe the results you expected:**
element found

**Comment by loiclau** [comment]
Fix with https://github.com/centreon/centreon/commit/eafa50b51e81700f27a54aaac8d070eba9b6ac87

**Comment by Tpo76** [comment]
OK for the trap relation with service, but when we send a trap to one poller it doesn't work I have this return in centreontrapd.log

`Cant find a host. Request: SELECT host_id, host_name FROM host WHERE host_address =...`

Anything change in /etc/centreon/centreontrapd.pm ?
```
our %centreontrapd_config = (
        # databases credentials
        centreon_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        centstorage_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        db_type => 'SQLite',
        # server type (0: central, 1: poller)
        mode => 1
);

1;
```

**Comment by Tpo76** [comment]
ref : #5264
