### ISSUE TITLE
2.7.10 - Génération Configuration Problème

### ISSUE THREAD

**Issue by ptitpopey** [centreon/centreon#5224]
Bonjour,

Suite upgrade en version CES 2.7.10, plantage lors de la génération des fihciers de conf avant le rechargement du poller.

Erreur sous GUI \:
Préparation de l'environnement... OK
Génération des fichiers... NOK (Exception received : Not writeable directory '/usr/share/centreon//filesGeneration/nagiosCFG/1' [file: /usr/share/centreon/www/class/config-generate/backend.class.php] [line: 114] )
Avorté.

Problème identifié \:
Mauvais droit sur répertoire /usr/share/centreon/filesGeneration/broker/1 et sur répertoire /usr/share/centreon/filesGeneration/nagiosCFG/1

bash# ll /usr/share/centreon/filesGeneration/broker/
total 4,0K
drwxrwsr-x 2 root centreon 4,0K 15 mai   15:55 1

bash# ll /usr/share/centreon/filesGeneration/nagiosCFG/
total 4,0K
drwxrwsr-x 2 root centreon 4,0K 15 mai   15:55 1

L'upgarde 2.7.10 devrait créer le répertoire avec les droits suivants \:
bash# ll /usr/share/centreon/filesGeneration/broker/
total 4,0K
drwxrwsr-x 2 centreon centreon 4,0K 15 mai   15:55 1

bash# ll /usr/share/centreon/filesGeneration/nagiosCFG/
total 4,0K
drwxrwsr-x 2 centreon centreon 4,0K 15 mai   15:55 1

Infos groupe \:
bash#  groups apache
apache : apache nagios centreon centreon-broker centreon-engine

Process Apache \:
apache   16064  2654  1 14:10 ?        00:01:27 /usr/sbin/httpd

**Comment by lpinsivy** [comment]
Cant' reproduce. Upgrade Centreon Web 2.7.5 to 2.7.10-3

**Comment by ptitpopey** [comment]
This bug appear during upgrade 2.7.8 to 2.7.10

**Comment by ptitpopey** [comment]
Pour info, à chaque rechargement les droits sont modifiée en root. Obligé de changer les doits à chaque fois

**Comment by lpinsivy** [comment]
La documentation n'est pas à jour. Centreon CLAPI API doit être exécuté avec l'utilisateur 'centreon' et non l'utilisateur 'root'

Correction des répertoires (depuis l'utilisateur 'root'):
```
chmod 02775 /usr/share/centreon/filesGeneration/broker/1
chmod 02775 /usr/share/centreon/filesGeneration/broker/N (N == other pollers)
chmod 02775 /usr/share/centreon/filesGeneration/nagiosCFG/1
chmod 02775 /usr/share/centreon/filesGeneration/nagiosCFG/N (N == other pollers)
chmod 644 /usr/share/centreon/filesGeneration/broker/1/*.xml
chmod 644 /usr/share/centreon/filesGeneration/broker/N/*.xml (N == other pollers)
chmod 644 /usr/share/centreon/filesGeneration/nagiosCFG/1/*.xml
chmod 644 /usr/share/centreon/filesGeneration/nagiosCFG/N/*.xml (N == other pollers)
chmod 664 /etc/centreon-broker/*
chmod 664 /etc/centreon-engine/*
```

Se connecter en 'centreon' :
`# su - centreon`

Générer la configuration :
```
$ centreon -u admin -pcentreon  -a APPLYCFG -v 1

2017-05-16 13:55:59 - APPLYCFG
Configuration files generated for poller '1'

OK: Nagios Poller 1 can restart without problem...

OK: All configuration files copied with success.

centengine restart: done                                   [  OK  ]
Return code end : 0
```

**Comment by ptitpopey** [comment]
En executant CLAPI API avec l'utilisateur centreon, je n'ai plus de problème de droit sur répertoire. Merci pour l'info.

Cependant j'obtiens une erreur lors de l'execution des deux commades suivantes :\
bash# su - centreon -c '/usr/share/centreon/bin/centreon -u toto -p titi -a POLLERGENERATE -v 1'

PHP Fatal error:  Call to undefined function posix_geteuid() in /usr/share/centreon/www/class/centreon-clapi/centreonUtils.class.php on line 135

bash# su - centreon -c '/usr/share/centreon/bin/centreon -u toto -p titi -a CFGMOVE -v 1'

PHP Fatal error:  Call to undefined function posix_geteuid() in /usr/share/centreon/www/class/centreon-clapi/centreonUtils.class.php on line 135

**Comment by Dacchi** [comment]
Bonjour,

l'extension POSIX de PHP de semble pas être active.

Quel est votre distribution? (A l'avenir pour faciliter les diagnostiques pourriez-vous  suivre ce guide => https://github.com/centreon/centreon/blob/2.8.x/project/creating-issue.md)

**Comment by ptitpopey** [comment]
il s'agit de la version packagée CES
CentOS release 6.9 (Final)
2.6.32-696.1.1.el6.i686

Problème corrigé en installant le package php-process

Merci pour votre aide

**Comment by lpinsivy** [comment]
La précédente méthode n'est pas la bonne.

Après génération de la configuration via l'interface web, les droits ne sont plus bon.

Please see 137260cdaaef0b154c3946bbe8591b7728a4c93f

You can use root user

**Comment by ptitpopey** [comment]
code changé. Plus de problème. Merci
