### ISSUE TITLE
icon rub.png / info2.png : incorrect path in widget

### ISSUE THREAD

**Issue by Rico29** [centreon/centreon#5228]
The path of the image file for rub.png and info2.png is not corect when a graph is added as a qidget in "custom views".

Path is : http://x.x.x.x/centreon/widgets/graph-monitoring/img/icons/info2.png
should be : http://x.x.x.x/centreon/img/icons/info2.png

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 

**OS**: CentOS release 6.9 (Final)

**Steps to reproduce the issue:**
1. add a graph as widget in "custom views"
2. see "missing image" icon at bottom right of the graph
3.

**Describe the results you received:**

jquery.js:2548 GET http://x.x.x.x/centreon/widgets/graph-monitoring/img/icons/info2.png 404 (Not Found)

**Describe the results you expected:**
jquery.js:2548 GET http://x.x.x.x/centreon/img/icons/info2.png

**Comment by Guillaume28** [comment]
That will be fixed in the upcoming version of Centreon (2.8.9) and widget graph-monitoring.

**Comment by thiuyendang** [comment]
information button (extra legend) is hidden in custom views for graph monitoring widget
