### ISSUE TITLE
[2.7.10] Can delete SNMP traps definition

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5230]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.10

**Centreon Engine version**: 1.5.3

**Centreon Broker version**: 2.12.0

**OS**: EL7

**Additional environment details (AWS, VirtualBox, physical, etc.):** : VMware

**Steps to reproduce the issue:**
1. Select SNMP trap definition
2. Try to delete it using "more actions > delete"

**Describe the results you received:**

SNMP trap definition is not deleted

**Describe the results you expected:**

Should be delete

**Additional information you think important (e.g. issue happens only occasionally):**

From /var/log/httpd/error_log:

[Wed May 17 10:16:54.436660 2017] [:error] [pid 5435] [client X.X.X.X:63909] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/centreon/www/class/centreonTraps.class.php on line 138, referer: http://10.30.2.129/centreon/main.php?p=61701

**Comment by lpinsivy** [comment]
Same issue with 2.8.8 version

**Comment by loiclau** [comment]
https://github.com/centreon/centreon/commit/da236871afaac044d640facace2fa8c110bf5694
