### ISSUE TITLE
[2.7.x/2.8.X] Old school style in popup

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5232]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.x / 2.8.x

**Centreon Engine version**: N/A

**Centreon Broker version**: N/A

**OS**: N/A

**Steps to reproduce the issue:**
1. Edit a command
2. Click on "Describe arguments" or "Describe macros" button

**Describe the results you received:**

A popup appear to describe arguments/macros with Centreon Web 2.6.x CSS style

**Describe the results you expected:**

Centreon Web 2.7.x/2.8.X CSS style

![screenshot at mai 17 11-01-54](https://cloud.githubusercontent.com/assets/3351916/26146564/ea69f420-3af0-11e7-9e5f-ab873414bb0f.png)

**Comment by lpinsivy** [comment]
And if you can change the message for macro to:

Sorry, your command line does not contain any $_MACRO$ macro.

**Comment by cgagnaire** [comment]
Fixed in 2.8.9.

**Comment by thiuyendang** [comment]
OK 2.8.9 CentOS6 CentOS7
