### ISSUE TITLE
[2.8.8] Issue when adding new connector

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5233]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: N/A

**Centreon Broker version**: N/A

**OS**: N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):** : N/A

**Steps to reproduce the issue:**
1. Go to "Configuration  >  Commands  >  Connectors" menu
2. Click on 'Add" button
3. Fill fields and save

**Describe the results you received:**

Error message

**Describe the results you expected:**

Go back to connector listing

**Additional information you think important (e.g. issue happens only occasionally):**

After refresh, new connector appear in listing

![screenshot at mai 17 11-10-50](https://cloud.githubusercontent.com/assets/3351916/26146821/cef3ed9e-3af1-11e7-9acc-8edb453c028f.png)

**Comment by thiuyendang** [comment]
OK 2.8.9.
Checked : 
- adding a connector
- modifying a connector
- duplicating
- deleting
