### ISSUE TITLE
[2.7.10] Edit contact - can't access to H/S notification commands

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5236]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.10

**Steps to reproduce the issue:**
1. Go to "Configuration  >  Users  >  Contacts / Users" menu
2. Edit/Add contact
3. try to select host/service notification commands

**Describe the results you received:**

Empty list

**Describe the results you expected:**

List of commands

**Additional information you think important (e.g. issue happens only occasionally):**

From /var/log/httpd/error_log:

[Wed May 17 11:50:05.567453 2017] [:error] [pid 5559] [client X.X.X.X:49375] PHP Notice:  A session had already been started - ignoring session_start() in /usr/share/centreon/www/class/centreonSession.class.php on line 98, referer: http://X.X.X.X/centreon/main.php?p=60301&o=c&contact_id=40
[Wed May 17 11:50:05.582197 2017] [:error] [pid 2357] [client X.X.X.X:49374] PHP Fatal error:  Uncaught exception 'Exception' with message 'An error occured' in /usr/share/centreon/www/include/common/webServices/rest/centreon_configuration_command.class.php:93\nStack trace:\n#0 /usr/share/centreon/www/include/common/webServices/rest/webService.class.php(252): CentreonConfigurationCommand->getList()\n#1 /usr/share/centreon/www/include/common/webServices/rest/internal.php(67): CentreonWebService::router()\n#2 {main}\n  thrown in /usr/share/centreon/www/include/common/webServices/rest/centreon_configuration_command.class.php on line 93, referer: http://X.X.X.X/centreon/main.php?p=60301&o=c&contact_id=40

**Comment by lpinsivy** [comment]
Should be linked to #5229

**Comment by Laexar** [comment]
Hi,

The problem is line 73 in /usr/share/centreon/www/include/common/webServices/rest/centreon_configuration_command.class.php :

The column command_activate does not seem to exist anymore in the command table for centreon database.
So you basically just have to replace :
$queryCommand .= "AND command_type = ? AND command_activate = 1 ";
by :
$queryCommand .= "AND command_type = ? ";
