### ISSUE TITLE
[ACL] Bug when you add severals access groups

### ISSUE THREAD

**Issue by nikitito** [centreon/centreon#5239]
Hello,
When I add severals access groups on a user, there are conflicts between access groups.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.5
**Centreon Engine version**: 
1.5.1
**Centreon Broker version**: 
2.11.2
**OS**: RHEL 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Steps to reproduce the issue:**
1.Create two access groups, one which authorize to modify hosts and another which doesn't allows it.
2.Create an user and affect both access groups that you've juste created.
3.Reload configuration and login with this user

**Describe the results you received:**
I cannot modify hosts even if one of the access groups allows it

**Describe the results you expected:**
I want that the user can modify hosts even if one of his access group doesn't authorizes.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
This situation has been fixed in Centreon Web 2.8.x version (ok in Centreon Web 2.8.9).
