### ISSUE TITLE
Aucune courbe dans mes graphiques

### ISSUE THREAD

**Issue by kpal38** [centreon/centreon#5241]
Version Centreon: 2.8.8

Bonjour,

Je vous écrit car je n'ai aucune courbes sur mes graphiques, (le plan apparait bien), Les Performances Data sont Ok mais rien n'est affiché sur le graphique:

![2017-05-17 09_25_08-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/15361791/26152691/47e974e2-3b08-11e7-994c-ff754e80c518.png)

![2017-05-17 09_25_33-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/15361791/26152696/4bab31b0-3b08-11e7-9e5e-a627c4680549.png)

Tous mes services ont le même soucis.

Merci d'avance pour votre aide.

**Comment by Cancom-Monitoring** [comment]
Salut,
as-tu fait une mis-a-jour (de quelle version)?
tu avait des courbes avant?

**Comment by kpal38** [comment]
Oui je fait les mise à jour régulièrement, dès qu'il y en a des nouvelles je les fait. J'avais des courbes avant cela fait quelques semaines que je n'ai plus rien

**Comment by Sims24** [comment]
Hi, 

This is a duplicate of https://github.com/centreon/centreon/issues/5130 

Fix expected for 2.8.9.  Please close this issue and follow things through the link above
