### ISSUE TITLE
[2.7.10] Check command doesn't appear in Service Template.

### ISSUE THREAD

**Issue by nakasix** [centreon/centreon#5242]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.10

**Centreon Engine version**: 1.5.3

**Centreon Broker version**: How to find this information ?

**OS**: CES / CentOS release 6.9 (Final)

**Steps to reproduce the issue:**
1. Go to Configuration -> Services -> Templates.
2. Add or Select a template.
3. Select a "Check Command" and wait, wait, wait and wait :)

**Describe the results you received:**
Check command doesn't appear.
![capture](https://cloud.githubusercontent.com/assets/11419742/26155192/a4cf5ece-3b12-11e7-89fc-3a31552d89c4.PNG)

**Additional information you think important (e.g. issue happens only occasionally):**
In Apache Log : "PHP Fatal error:  Uncaught exception 'Exception' with message 'An error occured' in /usr/share/centreon/www/include/common/webServices/rest/centreon_configuration_command.class.php:93\nStack trace:\n#0 /usr/share/centreon/www/include/common/webServices/rest/webService.class.php(252): CentreonConfigurationCommand->getList()\n#1 /usr/share/centreon/www/include/common/webServices/rest/internal.php(67): CentreonWebService::router()\n#2 {main}\n  thrown in /usr/share/centreon/www/include/common/webServices/rest/centreon_configuration_command.class.php on line 93"

**Comment by lpinsivy** [comment]
linked to #5229
