### ISSUE TITLE
[centreon-knowledgebase] enhancement delete option

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#5243]
**Centreon Web version**: 2.8.8

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Knowledgebase
2. choose an host or service who have a wiki page or create it
3. Delete this wiki page

**Describe the results you received:**
Page is deleted on wiki, but the link in centreon configuration stay present.

**Describe the results you expected:**
empty ehi_notes_url in configuration if link is with this format './include/configuration/configKnowledge/proxy/proxy.php...' and only with this format to preserve other links managed outside of kb

**Additional information you think important (e.g. issue happens only occasionally):**
 This enhance is to conserve an integrity with the links in the monitoring and to avoid dead links
This action can be set directly over delete action or by synchronizer if it find deletion page on recent changes

cordially

**Comment by adr-mo** [comment]
**Fixed in 18.10.5**
