### ISSUE TITLE
Severity of 'host category'

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5245]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Steps to reproduce the issue:**
1. I used the API to set the severity of an host category.
2. Then I used the API to unset it.

**Describe the results you received:**
The box "severity type" on centreon web is still checked.

**Describe the results you expected:**
This box should be unchecked.

**Comment by thiuyendang** [comment]
Checked in 2.8.9-8. API command to unset Severity check box for Host Category OK
