### ISSUE TITLE
[CENTREON 2.8.8] - TIMEZONE Macro HOSTLOCATION unsupported in commands

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#5246]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. set Timezone on a host
![image](https://cloud.githubusercontent.com/assets/8720203/26160974/e63bbe06-3b22-11e7-8e44-b59c22fcb7a0.png)

2. define a command with macro $_HOSTLOCATION$ like this
`$CENTREONPLUGINS$/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=time --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --timezone='$_HOSTLOCATION$' --warning='$_SERVICEWARNING$' --critical='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$`
3. deploy configuration

**Describe the results you received:**
timezone is not set on command:
`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=time --hostname=X.X.X.X --snmp-version='2c' --snmp-community='XXX'  --timezone='' --warning='' --critical=''`

**Describe the results you expected:**
timezone should be set in command:
`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=time --hostname=X.X.X.X --snmp-version='2c' --snmp-community='XXX'  --timezone='Europe/Paris' --warning='' --critical=''`

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi, can you try to use "$HOSTTIMEZONE$ instead of $_HOSTLOCATION$ ?

**Comment by cmeschin** [comment]
Hi Laurent,
It's not work...
the command:
`$CENTREONPLUGINS$/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=time --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --timezone='$HOSTTIMEZONE$' --warning='$_SERVICEWARNING$' --critical='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$`

and result:
`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=time --hostname=X.X.X.X --snmp-version='2c' --snmp-community='public'  --timezone='' --warning='' --critical=''`

This Macro is not available on DropDown list from commands. It is New?

regards,

**Comment by thiuyendang** [comment]
In 2.8.10, macro &HOSTTIMEZONE& has been added in the dropdown list in commands page but no output is returned from this macro.

**Comment by thiuyendang** [comment]
The output issue is fixed with centreon-engine 1.8. 
I close this ticket and will create another one in centreon-engine project

**Comment by cmeschin** [comment]
Hi,
thanks thiuyendang but there is an error on issue link 84. It pointing on centreon project but it should be linked on centreon-engine project (https://github.com/centreon/centreon-engine/issues/84) ;)
