### ISSUE TITLE
figures not allowed into hostname

### ISSUE THREAD

**Issue by euidzero** [centreon/centreon#5247]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web-2.8.6-4.el6

**Centreon Engine version**: 
centreon-engine-1.7.1-2.el6.x86_64

**Centreon Broker version**: 
centreon-broker-3.0.5-2.el6.x86_64

**OS**: 
centos6
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. add a host
2. put number in the hostname : a2b3c
3.save
4. list hosts
5. re edit host

**Describe the results you received:**
host is now named abc

**Describe the results you expected:**
hostname should still be a2b3c

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by euidzero** [comment]
Same problem with service name.

**Comment by julienmathis** [comment]
Hello, 

Can you check this ticket : #5184 ? 

Thanks

**Comment by euidzero** [comment]
I confirmed this is solved in 2.8.8 

BUT : the upgrade process does not fix the Illegal Char fields in the Engine Configuration leaving the user with the problem until he read the instructions in the issue comments.

**Comment by thiuyendang** [comment]
OK 2.8.9-7
