### ISSUE TITLE
"Recovery notification delay" is not written to centreon-engine's configuration

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon#5249]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8-4.el6

**Centreon Engine version**: 1.7.2-3.el6

**Centreon Broker version**: 3.0.7-1.el6

**OS**: CES

**Steps to reproduce the issue:**
1. Create a host template with a non-null "Recovery notification delay"
2. Re-generate the configuration

**Describe the results you received:**
The file `/etc/centreon-engine/hostTemplates.cfg` does not contain a `recovery_notification_delay` line when it should.

**Additional information you think important (e.g. issue happens only occasionally):**
All I see [in the code that generates the config](https://github.com/centreon/centreon/blob/c8e779e1c77c189c794d5ea58f50eca0eaf5419a/www/class/config-generate/hosttemplate.class.php#L113) is `first_notification_delay`, no trace of `recovery_notification_delay`.

**Comment by thiuyendang** [comment]
2.8-9-10 OK
Add a host template with a recovery notification delay value
Add a host and link to the host template
Export configuration
Check file hostTemplates.cfg -> OK
