### ISSUE TITLE
Duplicate host template doesn't work

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#5252]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Additional environment details (AWS, VirtualBox, physical, etc.):** Chrome 58.0.3029.110 (64-bit)

**Steps to reproduce the issue:**
1. Go to Configuration --> Hosts --> Templates
2. Use pagination to go on another page (not the first page)
3. Duplicate a template
![duplicate](https://cloud.githubusercontent.com/assets/11076322/26239806/d1d70756-3c7e-11e7-990d-6ac4dd47444a.png)

**Describe the results you received:**
Template isn't duplicated

**Describe the results you expected:**
Template should be duplicated

**Additional information you think important (e.g. issue happens only occasionally):**
URL is strange when you use pagination:
http://10.30.1.2/centreon/main.php?p=60103&num=1&limit=30&poller=&template=&search=&type=&o=&search_type_service=1&search_type_host=1&search_service=

**Comment by cgagnaire** [comment]
It looks the same for every actions.

**Comment by cgagnaire** [comment]
There is kind of the same behaviour on the 'Administration > Parameters > Performance Management > Data' page.
Url like : http://10.30.2.131/centreon/main.php?p=50119&num=1&limit=30&poller=&template=&search=&type=&o=&search_type_service=1&search_type_host=1

**Comment by cgagnaire** [comment]
Related to https://github.com/centreon/centreon/issues/5213

**Comment by Tpo76** [comment]
OK

**Comment by cgagnaire** [comment]
It's not completely done though.
When I'm on page 2, I duplicate a HTPL, I disable it with the 'disabled' button on the right.
No more actions possible on the page.
We can also see that the last action is "keeped" on the drill-down 'More actions...' menu.

**Comment by thiuyendang** [comment]
Moved back this ticket to do

**Comment by cgagnaire** [comment]
This behaviour is visible in other pages (ACL, Users, ...)

**Comment by thiuyendang** [comment]
OK for Duplication. Will create another ticket for the remaining issue
