### ISSUE TITLE
Any call to the API return a "Bad parameters"

### ISSUE THREAD

**Issue by chris968** [centreon/centreon#5257]
I tried with curl:

curl  'http://centreon.mydom.local/api/index.php?action=action&object=centreon_clapi' -H 'Content-Type:
 application/json' -H 'centreon-auth-token: rgrthtyhrethrthehre=' --data 'action=show&object=HOST'

Or with postman and RESTer(firefox) but the API return a  "Bad parameters" on whatever we tried to reach.
The error message seems trow by this section in api/class/webService.class.php:

228         /* Test if route is defined */
229         if (false === isset($_GET['object']) || false === isset($_GET['action'])) {
230             static::sendJson("Bad parameters", 400);
231         }

**Comment by kduret** [comment]
Please try to send data in JSON format.

Something like that : 
curl 'http://centreon.mydom.local/api/index.php?action=action&object=centreon_clapi' -H 'Content-Type:
application/json' -H 'centreon-auth-token: rgrthtyhrethrthehre=' --data '{"action": "show", "object":"HOST"}'

**Comment by julienmathis** [comment]
Yes don't forget to use JSON format :)
more information are available here : https://documentation.centreon.com/docs/centreon/en/2.8.x/api/api_rest/index.html
