### ISSUE TITLE
[2.8.8] Data pagination

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5259]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Centreon 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Administration ==> Parameters
2. Go to Data (below the Performance Management field)
3. Try to navigate between pages

**Describe the results you received:**
Pagination does not work

**Describe the results you expected:**
Pagination should work

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by cgagnaire** [comment]
Related to https://github.com/centreon/centreon/issues/5213

**Comment by cgagnaire** [comment]
Pagination is working with https://github.com/centreon/centreon/commit/0ccb5e5de11ec0cdc8e9ace260abc3ac3d8ac8d0 fix, but when I do an action on page 2, it brings me back to the first page while the pagination toolbar is still on page 2.

**Comment by cgagnaire** [comment]
Works great !

**Comment by thiuyendang** [comment]
OK 2.8.9 CentOS6
