### ISSUE TITLE
[ACL] Impossible de voir un service dupliqué

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#526]
---

Author Name: **jeremy rouanne** (jeremy rouanne)
Original Redmine Issue: 5860, https://forge.centreon.com/issues/5860
Original Date: 2014-10-06

---

Bonjour,

Lorsqu'un utilisateur est soumis à des ACL et qu'il duplique un service, il lui est impossible de voir le service dupliqué ?

Avez-vous déjà rencontré ce problème ?

Merci d'avance.

**Comment by leoncx** [comment]
Duplicate #2861
