### ISSUE TITLE
InfluxDb I only have metric from Central ( no metrics from other poller )

### ISSUE THREAD

**Issue by Judunet** [centreon/centreon#5261]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8-4

**Centreon Engine version**: 1.7.2-3

**Centreon Broker version**: 3.0.7-1

**OS**: Redhat 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1 - Go to Configuration -> Pollers -> Broker configuration
2 - Add InfluxDB output somewhere
3 - Enter metric and status colums
4- save

**Describe the results you received:**
I receiving all data metric on influxDb for Central, but not for all poller

**Describe the results you expected:**
All metrics data for all poller, 

**Additional information you think important (e.g. issue happens only occasionally):**
I have 1 server Central (centreon-web + centreon-engine), 2 poller (centreon-engine)

Here is my configuration for InfluxDB output
```
<output>
  <name><![CDATA[central-broker-influxdb]]></name>
  <cache><![CDATA[yes]]></cache>
  <db_host><![CDATA[10.xx.xx.xx]]></db_host>
  <db_port><![CDATA[8086]]></db_port>
  <db_user><![CDATA[xxx]]></db_user>
  <db_password><![CDATA[xxxxxxxxxxxx]]></db_password>
  <db_name><![CDATA[preproduction]]></db_name>
  <metrics_timeseries><![CDATA[$INSTANCE$.$SERVICE$.metrics]]></metrics_timeseries>
  <status_timeseries><![CDATA[$INSTANCE$.$SERVICE$.status]]></status_timeseries>
  <type><![CDATA[influxdb]]></type>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[number]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$METRIC$]]></value>
   <name><![CDATA[metric]]></name>
  </metrics_column>
 </output>
 ```

**Comment by lpinsivy** [comment]
Hi,

Do you receive real time data from your pollers in Centreon web interface ?
