### ISSUE TITLE
Missing functions setseverity and unsetseverity for host group service

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5262]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I tried to use setseverity and unsetseverity with the API.

Describe the results you received:
It told me that the functions are not implemented.

Describe the results you expected:
It should have worked according to the documentation and the buttons corresponding to these functions exist on Centreon Web.

**Comment by loiclau** [comment]
9ad0b85b468d8630d0ea013a7c8281b6f4743c92
