### ISSUE TITLE
[2.7.11] Error with downtime's overlays

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#5263]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.7.11

**Centreon Engine version**:  1.5.3

**Centreon Broker version**:  2.11.8-2.

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Add a downtime on a service
2. Wait the downtime to begin
3. in  "Monitoring  >  Status Details  >  Services" move you mouse over the downtime icon

**Describe the results you received:**
I only the the throbber.

**Describe the results you expected:**
The little overlay with the downtime informations

**Additional information you think important (e.g. issue happens only occasionally):**
Error in httpd.log : 
PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/include/monitoring/downtime/xml/broker/makeXMLForDowntime.php on line 116, referer: http://10.66.113.54/centreon/main.php?p=202

**Comment by thiuyendang** [comment]
Checked Centreon-Web 2.7.11-8 CentOS6 OK

**Comment by thiuyendang** [comment]
Issue not hit in 2.8.9
