### ISSUE TITLE
[2.7.11] Migration 2.7.11 to 2.8.x does not work

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#5265]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.11

**Centreon Engine version**: 1.5.3

**Centreon Broker version**: 2.8.11

**OS**: Centreon 3.3

After the update with the following commands

> rm -f /etc/yum.repos.d/ces-standard.repo
wget http://yum.centreon.com/standard/3.4/el6/stable/centreon-stable.repo -O /etc/yum.repos.d/centreon-stable.repo
service centengine stop
service cbd stop
yum update centreon centreon-widget* ces-release

After the update, the file /usr/share/centreon/www/install/sql/centreon/Update-DB-2.7.11_to_2.8.0-beta1.sql does not exist

The update can not be done

![install_glpi2017-05-22_09-46-52_pm](https://cloud.githubusercontent.com/assets/12350746/26326902/95e50e84-3f3d-11e7-9056-42b54bfec8ec.png)

Before the web update, copy the file /usr/share/centreon/www/install/sql/centreon/Update-DB-2.7.10_to_2.8.0-beta1.sql by renaming it 
> cp /usr/share/centreon/www/install/sql/centreon/Update-DB-2.7.10_to_2.8.0-beta1.sql /usr/share/centreon/www/install/sql/centreon/Update-DB-2.7.11_to_2.8.0-beta1.sql

Edit line and remplace 2.7.9 for 2.7.11
> UPDATE informations SET value = '2.8.0-beta1' WHERE CONVERT( informations.key USING utf8 ) = 'version' AND CONVERT ( informations.value USING utf8 ) = '2.7.11' LIMIT 1;

**Comment by kduret** [comment]
Already fixed here : f6a97a685967c6a2f81072d5d7e24b34dd1ac465

**Comment by thiuyendang** [comment]
OK 2.8.9-5 CentOS6
Migration from 2.7.11 to 2.8.9-5
Refer to #5220
