### ISSUE TITLE
[GRAPH] Problem with external graph usage (Widgets, Centreon BAM)

### ISSUE THREAD

**Issue by Moujimouja** [centreon/centreon#5270]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9
**Centreon BAM version**: 3.5.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Try to display the graph using the mouse over on Monitoring > Business Activity 
2.Graph doesn't appear

1.Try to display the graph using the mouse over on Monitoring > Business Activity  > BA detail page > Trends tab
2.Graph doesn't appear

![image](https://cloud.githubusercontent.com/assets/6620287/26363912/e1a37432-3fe2-11e7-9b8e-61544793c0ed.png)

**Describe the results you expected:**
The graph should appear

**Comment by loiclau** [comment]
fix with 07e290b77d677dcb7104b01940e608226d809fa5

**Comment by thiuyendang** [comment]
2.8.9 : OK pour les widgets Centreon
A tester pour les graphes des Business Activities du module BAM

**Comment by cgagnaire** [comment]
Works too!

**Comment by thiuyendang** [comment]
OK 2.8.9-6
