### ISSUE TITLE
Activation environment macros when duplicate a poller

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5271]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Centreon3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Duplicate a poller
2. Go to Engine Configuration ==> Select the new configuration
3. Go to Tuning tab
4. 

**Describe the results you received:**
No value was set for Enable environment macros field : when you will generate the configuration the configuration will not be generated

**Describe the results you expected:**
Select the Default value

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

When I duplicate a poller from "Configuration  >  Pollers" or "Configuration  >  Pollers  >  Engine configuration", the value for "Enable environment macros" is always "Default".
