### ISSUE TITLE
[2.8.9] Can't duplicate trap definition

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#5272]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.0.7

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware vSphere 6.0

**Steps to reproduce the issue:**
1. Go to 'Configuration > SNMP Traps'
2. Select a trap
3. Select 'Duplicate' in the 'More actions...' drop-down list

**Describe the results you received:**
Nothing happen

**Describe the results you expected:**
My trap should be duplicated

**Additional information you think important (e.g. issue happens only occasionally):**
No error on httpd or centreon sql logs

**Comment by thiuyendang** [comment]
OK 2.8.10. CentOS7
OK 2.8.10 CentOS6
