### ISSUE TITLE
[2.8.9] Several SNMP trap groups configuration malfunctioning

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#5273]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.0.7

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware vSphere 6.0

**Steps to reproduce the issue:**
1. Go to 'Configuration > SNMP Traps > Group'
2. Clic on the 'Add' button
3. Fill the 'Name' field, and add some traps

**Describe the results you received:**
My group gets created, but when I want to edit it, the 'Name' field is empty and there is no traps on the select to.
I can't duplicate or delete a group.

**Additional information you think important (e.g. issue happens only occasionally):**
I get this error when I clic on 'Add'
![image](https://cloud.githubusercontent.com/assets/23257354/26403675/56848014-408f-11e7-9772-fffefbb19f02.png)

I get this error when I try to duplicate a group : 
2017-05-24 14:41|0|0|DB Error: value count on row QUERY : INSERT INTO traps_group VALUES (NULL)

**Comment by lpinsivy** [comment]
Can't reproduce with future release 2.8.9
