### ISSUE TITLE
[2.8.8] Labels in graphs are not aligned ONLY IN service's detail

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#5274]
# BUG REPORT INFORMATION

**Centreon Web version:** 2.8.8

**Centreon Engine version:** 1.7.2

**Centreon Broker version:** 3.0.5

OS: RedHat 6

Additional environment details (AWS, VirtualBox, physical, etc.):

Steps to reproduce the issue:
  - Monitoring  >  Status Details  >  Services 
  - Click on a service with multiple metrics
  - Scroll down
  - Put you mouse on the graph

Describe the results you received:
Labels are centered, leading to something difficult to read 
**and the display is different than when we display it under «Monitoring  >  Performances  >  Graphs»**

![37b42a92-2aa3-11e7-805a-4f7940399da3](https://cloud.githubusercontent.com/assets/2464712/26405280/222971c0-4095-11e7-9472-d8336a0902b0.png)

Describe the results you expected:
Label must be left align OR same everywhere in Centreon

Additional information you think important (e.g. issue happens only occasionally):

**Comment by lpinsivy** [comment]
Hi

Works fine with Centreon web 2.8.9

![screenshot at juin 14 11-04-34](https://user-images.githubusercontent.com/3351916/27124424-56de9596-50f1-11e7-9070-9efbe8aa909a.png)

**Comment by BenoitPoulet** [comment]
Hello,

The bug is not solved, you are checking in the wrong way. Please have a look at this video :
https://dl.businessdecision.com/file.php?h=R1af63793a3f22173a2fc508a2b7d79ef

**Comment by lpinsivy** [comment]
All right is not ok in popin in service details page.
