### ISSUE TITLE
Cannot insert numbers in service description field

### ISSUE THREAD

**Issue by lgigil** [centreon/centreon#5275]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: centos-release-6-9.el6.12.3.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualbox

**Steps to reproduce the issue:**
1. Create a new service and associate it to an host
2. Modify the description value of the service adding a number (for example: test 123)
![screen2](https://cloud.githubusercontent.com/assets/1210859/26494058/464b3eec-421d-11e7-8e29-b68ec1429a7c.PNG)
3. Click on save and go to the service list to check it.

**Describe the results you received:**
The number in the description is replaced with 1 (for example: test 1)
![screen1](https://cloud.githubusercontent.com/assets/1210859/26494059/464d4548-421d-11e7-9d2d-4bae5f62b49e.PNG)

**Describe the results you expected:**
The description of the service should be renamed as I did

**Additional information you think important (e.g. issue happens only occasionally):**
This issue happens always and with every service I try to rename.

**Comment by lpinsivy** [comment]
Should be corrected by #4931

Please correct too your Centreon Engines configuration in admin tab:
Illegal Object Name Characters : ~!$%^&*"|'<>?,()=
Illegal Macro Output Characters : `~$^&"|'<>

**Comment by lgigil** [comment]
Thank you so much!
It worked substituting the HTML entities that I had in the Illegal Characters field with the relative symbol that you provided me.

**Comment by thiuyendang** [comment]
Moved this ticket to Nothing to do
OK in 2.8.9-13
