### ISSUE TITLE
Problem with the functions addcontact and setcontact of the ACL Groups

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5277]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I tried to use setcontact and addcontact of ACL Group with the API.

Describe the results you received:
It seemed to worked but nothing changed on Centreon Web.

Describe the results you expected:
It should be written on Centreon Web that a contact was add or set on the ACL group.

**Additional information you think important (e.g. issue happens only occasionally):**
On the API, I have to use the alias of the contact and not its name. On Centreon Web the names are written and not the alias, maybe the problem is due to that.

**Comment by loiclau** [comment]
admin don't need acl
