### ISSUE TITLE
Poller last updated

### ISSUE THREAD

**Issue by DRAKUN** [centreon/centreon#5279]
Hi i have hard problem with yellow flag in poller list.
Many of my poller are in this status , i restart all service nothing
Please help 

![2017-05-27 15_55_59-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/366065/26523315/a044c7c8-4304-11e7-8635-9d86106ed67d.png)

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.7.7
**Centreon Engine version**: 
1.5
**Centreon Broker version**: 

**OS**: 
RAspeberry
**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by DRAKUN** [comment]
I dont know where is the problem.....

**Comment by DRAKUN** [comment]
Very very complicated for me 

![2017-05-27 19_28_11-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/366065/26523908/bfe21046-4312-11e7-942d-e49fb42d8b63.png)

**Comment by lpinsivy** [comment]
Hi,

Do you have temporary files in /var/lib/centreon-broker on your pollers ?

**Comment by DRAKUN** [comment]
Nothing folder is empty

**Comment by julienmathis** [comment]
Are your poller synchronized with ntp server ? because, this is the poller who send this information.

**Comment by DRAKUN** [comment]
Yes its synchronized correctly 
vi /etc/ntp.conf
server central_Ip_address

**Comment by lpinsivy** [comment]
Still present?

I suppose an issue with CBD and you have retention file in /var/lib/centreon-broker on central server

**Comment by WIL200** [comment]
Hi, I have the same problem, but /var/lib/centreon-broker is not empty. what to do ??
