### ISSUE TITLE
Delete SNMP Traps

### ISSUE THREAD

**Issue by Gilum** [centreon/centreon#5282]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**
PHP 5.3.3

**Steps to reproduce the issue:**
1. Configuration => SNMP Traps
2. Select traps
3. Delete action and confirm

**Describe the results you received:**
SNMP Traps not delete

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**
[Mon May 29 17:29:36 2017] [error] [client #########] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/centreon/www/class/centreonTraps.class.php on line 143, referer: http://#################/centreon/main.php?p=617

**Comment by julienmathis** [comment]
Hello, 

Your problem has been fixed 14 days ago by this fix : da236871afaac044d640facace2fa8c110bf5694

Can you test and validate ?

thanks in advance

**Comment by Gilum** [comment]
Fix OK, SNMP traps deleted ! Thank @julienmathis

**Comment by thiuyendang** [comment]
OK 2.8.10, CentOS6, CentOS7
