### ISSUE TITLE
[2.8.8] Impossible to change max event queue size

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#5285]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.8
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.7
**OS**: 
CentOS 6.9
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go in Configuration -> Poller -> Broker Configuration
2. Select anny broker configuration and change "Event queue max size" parameters and Save
3. Come back on your broker configuration

**Describe the results you received:**
The parameter stay at 100000

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by julienmathis** [comment]
It's because it's the lower value accepted. If you want to change the value is that you want to set an upper value.

It's not a bug, but a best practice.
