### ISSUE TITLE
[2.8.8] Sorting by duration and Maximum page size change

### ISSUE THREAD

**Issue by Az3RuS** [centreon/centreon#5287]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):** Hyper-V

**Steps to reproduce the issue:**
1. Go in Administration > Parameters > Centreon UI
2. Change fields "Maximum page size" "Display properties" "Problem display properties"
3. Go in Monitoring > Status Details

**Describe the results you received:** Sorting in descending order does not work in columns and limit per page = 30 (By deafault)
Parameters in Administration > "Centreon UI" > "Maximum page size" "Display properties" "Problem display properties" do not apply !

**Describe the results you expected:** That the list is sorted by duration in ascending order and that the default number of clients is 100.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by grosbedos** [comment]
Hi,

Seriously ? 2.8.11 ? It's very complicated for us to work, we don't see new arrival problem on our monitoring !

Best regards

**Comment by thiuyendang** [comment]
OK for sort by duration in 2.8.12-4.
Issue with the "Limit per page for monitoring" parameter -> I'm going to create a new ticket
