### ISSUE TITLE
Remove chart padding

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#5288]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Steps to reproduce the issue:**
1. Look at a chart

**Describe the results you received:**
![image](https://cloud.githubusercontent.com/assets/11978823/26591873/4f3b1668-455f-11e7-957d-0ed74117988b.png)

**Describe the results you expected:**
Chart without padding

**Comment by thiuyendang** [comment]
OK 2.8.9-11
