### ISSUE TITLE
[2.8.8] - host configuration can not be saved or modified

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#5290]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: SL 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare

**Steps to reproduce the issue:**
1. create a new host
2. save the configuration
3. change poller or host template
4. save the configuration

**Describe the results you received:**
nothing happens. after pressing the save button the page refresh, but the configuration will not saved and the host configuration page is still there without any error or information

**Describe the results you expected:**
the configuration will be saved.

**Additional information you think important (e.g. issue happens only occasionally):**
The problem can be reproduced, but is occasionally. It seem's to be connected to some host template. All our host templates are connected to a generic template, Using a cisco router host template, all operations working fine. Using a windows server host template, we can not more save changes on the host.

**Comment by joschi99** [comment]
The problem seem's related with ticket #5246. If I remove the macro $_HOSTLOCATION$ then I can save the configuration without any problems.

**Comment by julienmathis** [comment]
Your host has been added by the UI or the API ?

**Comment by joschi99** [comment]
The host is added by UI.

**Comment by lpinsivy** [comment]
Hi,

I can't reproduce the problem on futur bugfix version 2.8.9.

1. Create an host with custom macro and save it
2. edit host and move to another poller and save
3. Host are move to the other poller.

Regards,

**Comment by joschi99** [comment]
Thanks. I will test this problem on the new version 2.8.9 as soon as is available. However the problem seem's related on the macro $_HOSTLOCATION$ and not on generic host macros.

**Comment by joschi99** [comment]
I tested the case on the new version 2.8.9, but the problem is still there, please reopen the case.

Thanks
