### ISSUE TITLE
Problem with setting gmt in API

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5291]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I followed the documentation in order to modify the gmt in "Settings" with the API.

Describe the results you received:
The number I gave sets the country at the "number" position in the list of countries. For exemple 1 selects the first country in the list, and 34 the 34th country.

Describe the results you expected:
According to the documentation, the number should corresponds to the gmt value, for exemple 2 (for GMT+2).

**Comment by julienmathis** [comment]
Oh no, you should have the possibility to set the timezone by his name : "Europe/Paris".

**Comment by julienmathis** [comment]
No it doesn't work... Sorry. We have to fix it
