### ISSUE TITLE
Problem with icon_image and map_icon_image of Host group

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5292]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I followed the documentation in order to modify the icon_image in "Host group" with the API.

Describe the results you received:
The value of icon_image on Centreon Web is empty.

Describe the results you expected:
I should be able to attribute an image to icon_image.

Additional information
I have the same problem with setparam map_icon_image in "Host group".

**Comment by loiclau** [comment]
4b645e7fe4a3bb0aaa437f9c207c3bd281cd426a
