### ISSUE TITLE
Add option to disable "strict host checking" for centcore

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon#5298]
**Centreon Web version**:  All (2.8.8 actually)

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Debian 8.8 (Linux Supervision 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux)

**Additional environment details (AWS, VirtualBox, physical, etc.): VmWare Esxi 6.5

**Steps to reproduce the issue:**
1. Have a poller with dynamic address.
2. Try to update/reload/ask the poller from the central

**Describe the results you received:**
"Host key verification failed.
No ECDSA host key is known for X.X.X.X and you have requested strict checking."
Need to clear entries... recheck all ssh exchanges... check all command to be sure it's working correctly...

**Describe the results you expected:**
No action required if the ip change. (except the change about the collector ip into the interface)

**Additional information you think important (e.g. issue happens only occasionally):**
Hello,
---> Please add an option on collector seetings gui to force the "strict host key checking" on the central side if you want to keep it ^^
Please, no option like that should be **hardcoded**, a lot of time was waste the first time and each time one of our pollers have its ip changed. (having a fixed ip is not a fix and it's not always possible :) )

In addition, if you try to add a "config" file into the .ssh directory of centreon and/or centreon-engine, it's not overwriting the hardcoded commands line...

Thanks in advance for the update ^^

**Comment by BlackstormFirst** [comment]
To help you... apprently the only sources of the "StrictHostKeyChecking=yes" hardcoded commands are into this file: "/usr/share/perl5/centreon/script/nagiosPerfTrace.pm" lines 53, 67 and 69.

To resolve it, just remove the entire option line "-o StrictHostKeyChecking=yes".

These options should be (and are) managed by the system config and never be hardcoded for flexibility, security and others... an option should be available into the GUI if you want to force it...

**Comment by cgagnaire** [comment]
Handled now with Gorgone.
