### ISSUE TITLE
CentWeb 2.8.8 - Sudo file not updated

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon#5299]
**Centreon Web version**: 2.8.8 (and probably also the oldest)

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Debian 8.8

**Additional environment details (AWS, VirtualBox, physical, etc.):** Esxi 6.5

**Steps to reproduce the issue:**
1. Try to reload/restart a poller with a recent release after an upgrade from previous one.

**Describe the results you received:**
Nothing

**Describe the results you expected:**
Poller restarted/reloaded...

**Additional information you think important (e.g. issue happens only occasionally):**
Hi,
Apparently, centweb commands is now using "/usr/sbin/service *" against "/etc/init.d/*" so if your sudo file is not up to date.. you must add the new commands form...

I just upgrade all my pollers with revision 2.8.8 and force the sudo file to be updated with the upgrade but that seems that not updated the commands into the file or the file itself...

Please take a look ^^
Thanks

**Comment by lpinsivy** [comment]
Should be corrected in packaging of latest version
