### ISSUE TITLE
API For Gesthosts method on Instance object add json keys

### ISSUE THREAD

**Issue by Abeatbowl** [centreon/centreon#5300]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8
**Centreon Engine version**: 1.7.1
**Centreon Broker version**: 3.0.7
**OS**: CentOS release 6.7 (Final)

I want to get all hosts that are monitored by a poller using API Rest. 
I use postman to test the request before I implement it in a powershell Module.
Here is the request I send : 

- Header : 
`centreon_auth_token:XXX`

- Body : 
```
{
	"action": "GETHOSTS",
	"object": "INSTANCE",
	"values": "1"
}
```

**Results received:**
As you can see in the json returned, the first result is seen as colunm name for the others hosts : 
```
  "result": [
    {
      "5304": "5368",
      "srv1": "srv2",
      "ip1": "ip2"
    },
    {
      "5304": "5832",
      "srv1": "srv3",
      "ip1": "ip3"
    },
    {
      "5304": "3238",
      "srv1": "srv4",
      "ip1": "ip4"
    },
[TRUNCATE ...]
    {
      "5304": "3242",
      "srv1": "srv649",
      "ip1": "ip649"
    }
  ]
}
```

**Results expected:**
```
  "result": [
    {
      "id": "5368",
      "hostname": "srv2",
      "address": "ip2"
    },
    {
      "id": "5832",
      "hostname": "srv3",
      "address": "ip3"
    },
    {
      "id": "3238",
      "hostname": "srv4",
      "address": "ip4"
    },
[TRUNCATE ...]
    {
      "id": "3242",
      "hostname": "srv649",
      "address": "ip649"
    }
  ]
}
```

**Comment by jphilaire** [comment]
Hello,
I agree with Abeatbowl.
One more thing, in Centreon Web version: 2.8.9, you can only specify the poller name. It is not possible to specify the poller ID. It could be great if you can specify the poller name or the poller ID.
Thanks.

**Comment by lpinsivy** [comment]
Moreover, do not list _MODULE hosts
