### ISSUE TITLE
My graphs are not displayed on my centreon 

### ISSUE THREAD

**Issue by nicodsia44** [centreon/centreon#5302]
Hello,

My Centreon server is installed for 6 months et displayed my graphes correctly.
Since the beginning of this week, I just have a little white rectangle instead of my graphes.

In the log httpd, I have : 

[Thu Jun 01 18:20:05 2017] [error] [client 10.33.28.105] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not
found in /usr/share/centreon/www/class/centreonGraphService.class.php on line 189, referer: http://10.33.31.36/centreon/main.php?p=202
[Thu Jun 01 18:20:05 2017] [error] [client 10.33.28.105] PHP Warning:  simplexml_load_string(): ERROR: can't make an xport without contents in /usr/share/c
entreon/www/class/centreonGraphService.class.php on line 189, referer: http://10.33.31.36/centreon/main.php?p=202
[Thu Jun 01 18:20:05 2017] [error] [client 10.33.28.105] PHP Warning:  simplexml_load_string(): ^ in /usr/share/centreon/www/class/centreonGraphService.cla
ss.php on line 189, referer: http://10.33.31.36/centreon/main.php?p=202

However, when I do an export CSV, I have datas on my file.

I tryed to remove my rrd files, to rebuild rrddatabase, unsuccessfully.

**Centreon Web version**: 2.8.2

**Centreon Engine version**:  1.7.0

**Centreon Broker version**:  3.0.3

**OS**: CentOs 6

**Describe the results you received:**
No graphs when my cursor in over the graph icon

**Describe the results you expected:**
Graphs when my cursor in over the graph icon

Please, can someone help me ?

**Comment by kozfelipe** [comment]
Same Issue

![image](https://cloud.githubusercontent.com/assets/25208457/26725753/646ef216-4776-11e7-9bc0-b29e252b7a57.png)
`[Fri Jun 02 09:20:28 2017] [error] [client *******] File does not exist: /usr/share/centreon/www/include/common/javascript/numeral.min.js, referer: *******/centreon/main.php?p=202`

**Comment by nicodsia44** [comment]
No, it is not the same issue. You have an error 404, but I have an error 500 Internal Server Error.

What do you have in the httpd logs ?

**Comment by kozfelipe** [comment]
Got mine fixed on update 2.8.8 to 2.8.9

**Comment by lpinsivy** [comment]
Hi do not forget to clean browser cache when you update Centreon web.
