### ISSUE TITLE
[2.8.8]Ldap manual import doesn't work

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#5303]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.8
**OS**: 
rhel7
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. config LDAP
2.Manually import user

**Describe the results you received:**
New user add in contact table

**Describe the results you expected:**
User was never created
Every thing fine in auto import mode

**Additional information you think important (e.g. issue happens only occasionally):**
Don't see any trouble in ldap.log, httpd/error_log or sql-eroor.log

**Comment by lpinsivy** [comment]
Hi @Tpo76 

I don't understand. LDAP user are imported or not with manual LDAP import ?

I made some test on Centreon Web 2.8.9 and everything works well. I can import manually LDAP user.

Regards,

**Comment by Tpo76** [comment]
Trouble is with manual importation.
I just try on 2.8.9 and it doesn't work.

I just say that auto import work to additional information.

**Comment by lpinsivy** [comment]
Can't reproduce with Centreon web 2.8.11, should be corrected
