### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5304]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I tried to use "setservice" from "Service categories" with the API.

Describe the results you received:
The function isn't implemented.

Describe the results you expected:
According to the documentation, it should exist.

Additional information
I have the same problem with "setservicetemplate".

**Comment by loiclau** [comment]
dd1806359f0bc3d3e2da2400c5a4bc66675cee62
