### ISSUE TITLE
Gap between Centreon timezone and checks hours

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5306]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Set timezone Europe/London to user (Configuration > Users)
2. Set timezone Europe/London to Centreon UI (Administration > Parameters)
3. Check one performance graph (ping for example)

**Describe the results you received:**
Last check time is not the same than Centreon time (gap about 1 hour)

![time_gap](https://cloud.githubusercontent.com/assets/25612980/26777634/4637b462-49de-11e7-9b7c-8aacde4c6de3.png)

**Describe the results you expected:**
x axis last time should be same time than Centreon time.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
duplicate or #5307
