### ISSUE TITLE
Gap between Statuses graph time and last service check time

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5307]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Set timezone Europe/London to user
2. Set timezone Europe/London to Centreon UI
3. Check one performance graph (ping)

**Describe the results you received:**
Last status check time is not the same than Centreon UI time and different from the last service check time too.

![time_gap](https://cloud.githubusercontent.com/assets/25612980/26777859/1f8b7b4a-49df-11e7-966c-3d56bdc67e82.png)

**Describe the results you expected:**
All times should be the same.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Should be correct because can't reproduce in Centreon web 2.8.12
