### ISSUE TITLE
"Centreon Web Directory" value ignored by the License Manager module

### ISSUE THREAD

**Issue by tbal82** [centreon/centreon#5308]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Any

**Centreon Engine version**: Any

**Centreon Broker version**: Any

**OS**: Any

**Steps to reproduce the issue:**
I want my monitoring UI to be accessible on https://mymonitoring.mydomain.com/ and not https://mymonitoring.mydomain.com/centreon/, so I :
1. Change the httpd conf file to disable "Alias /centreon /usr/share/centreon/www/" and reload httpd
2. Change the "Centreon Web Directory" value under Administration -> Parameters to "/"
3. Go to Administration -> Extensions -> Subscription

**Describe the results you received:**
I get the following error message : Cannot access to IMP portal

**Describe the results you expected:**
You should see the login page to IMP

**Additional information you think important (e.g. issue happens only occasionally):**
The browser debugger shows that the page tries to reach "/centreon/include/common/webServices/rest/internal.php?object=centreon_license_manager&action=stepStatus", no matter what the value in "Centreon Web Directory" is

**Comment by lpinsivy** [comment]
You right centreon-license-manager don't use "Administration > Parameters > Centreon UI > Centreon Web Directory" value

**Comment by mikael-andre** [comment]
Hello,

I've got the same issue.
