### ISSUE TITLE
[BUG] Delmacro isn't working

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5309]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I created a macro attached to an "Host group service".
I tried to delete this macro.

Describe the results you received:
The function did not work.

Describe the results you expected:
The macro should be deleted.

**Comment by loiclau** [comment]
6ddae23b5a14dd4dc4b4e513fdf6daad72a40803
