### ISSUE TITLE
Contact group additive inheritance isn't implemented

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5311]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I used the API to enable contact group additive inheritance of an host group service.

Describe the results you received:
The function is not implemented.

Describe the results you expected:
It should have worked.

**Comment by loiclau** [comment]
2a4883fd8459c60247f1c02941dface4041ba82d
