### ISSUE TITLE
[2.8.8] Severity is not imported into a poller display

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#5312]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Centeon 3.4.1

**Additional environment details (AWS, VirtualBox, physical, etc.):**

centreon-display 1.5.2 and centreon-display 1.6.0

The criticality configuration is not imported into the polling display

Central

![install_glpi2017-06-06_03-54-04_pm](https://cloud.githubusercontent.com/assets/12350746/26832738/b041ecea-4ad0-11e7-8a22-87729c7432be.png)

Poller-display

![install_glpi2017-06-06_03-54-17_pm](https://cloud.githubusercontent.com/assets/12350746/26832746/b9b8c19a-4ad0-11e7-99eb-344c08b957e7.png)

**Comment by lpinsivy** [comment]
Can you open it on https://github.com/centreon/centreon-poller-display

Regards,

**Comment by lpinsivy** [comment]
Are you sure that severity are not imported or just image linked to severity ?

Can you sort items by severity ?

**Comment by kermith72** [comment]
I just tested with a version 1.6.0, I have the severity with the hosts and the services. But the services severity list does not load
Services
![install_glpi2017-06-14_11-25-23_am](https://user-images.githubusercontent.com/12350746/27125518-d606d2b8-50f4-11e7-8c5a-6e03e2f75b2e.png)

Hosts
![install_glpi2017-06-14_11-24-29_am](https://user-images.githubusercontent.com/12350746/27125555-f175a9ca-50f4-11e7-9ba7-06d12f4f714f.png)


Pictures are not imported too

**Comment by lpinsivy** [comment]
OK

Can you create a ticket on correct forge: https://github.com/centreon/centreon-poller-display/issues ?

Regards,

**Comment by kermith72** [comment]
@lpinsivy 

it is done

https://github.com/centreon/centreon-poller-display/issues/10
