### ISSUE TITLE
[2.8.8] Creating a broker configuration generates a duplicate engine configuration

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#5313]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Centreon 3.4.1

When adding a configuration with a wizard or manually, an engine configuration is added too

add a poller
Conf broker
![install_glpi2017-05-31_09-56-48_am](https://cloud.githubusercontent.com/assets/12350746/26833130/e00dde56-4ad1-11e7-8080-dfc62b87cc54.png)

Conf engine
![install_glpi2017-05-31_10-10-42_am](https://cloud.githubusercontent.com/assets/12350746/26833100/c0539b50-4ad1-11e7-97e5-f9717618f141.png)

add a poller display
Conf broker
![install_glpi2017-06-06_04-07-04_pm](https://cloud.githubusercontent.com/assets/12350746/26833268/43d36abe-4ad2-11e7-9e66-9cf767e9dca3.png)

Conf engine
![install_glpi2017-06-06_12-41-20_pm](https://cloud.githubusercontent.com/assets/12350746/26833187/07957ec0-4ad2-11e7-9e83-775461a5869d.png)

**Comment by lpinsivy** [comment]
I think it's a problem of documentation:

1. Create a new poller using "Configuration > Pollers" menu
2. Add a borker configuration using wizard from "Configuration  >  Pollers  >  Broker configuration".
3. Check that new entry in "Configuration  >  Pollers  >  Engine configuration" is linked to correct poller definition from step 1.
4. Add optional broker output

What do you think ?

**Comment by kermith72** [comment]
I tried this solution with the wizard, I create a new poller
![install_glpi2017-06-06_06-16-42_pm](https://user-images.githubusercontent.com/12350746/26839821-7e9f3800-4ae4-11e7-9422-9e7545f17071.png)

I use wizard for the broker configuration
![install_glpi2017-06-06_06-15-20_pm](https://user-images.githubusercontent.com/12350746/26839838-845c6664-4ae4-11e7-82bb-cf71822b35f4.png)

I found two engine configuration
![install_glpi2017-06-06_06-19-27_pm](https://user-images.githubusercontent.com/12350746/26839913-b45acdf6-4ae4-11e7-90cc-8d545e48b832.png)

and wizard does not work for pollers display configuration

**Comment by omercier** [comment]
Hi Eric,
This has been fixed in the later versions and Poller Display is now replaced by Remote Server, so I'm closing the issue.
Regards
