### ISSUE TITLE
Purge of BI reports

### ISSUE THREAD

**Issue by abdoulosseni** [centreon/centreon#5318]
Hello Team,

I am looking for a method (script) to remove old BI report.

From GUI, to remove a report, I do : 
- Reporting  >  Monitoring Business Intelligence: I select the reports and I click on trash
- Reporting  >  Monitoring Business Intelligence  >  Trash: I select the report and I click on delete

I need to know the structure of the database to performe the purge.
Or is there a PHP class I can use to do it ?

Best regards

Abdoul OSSENI

**Comment by Moujimouja** [comment]
Hello,

Centreon MBI is a commercial product, you normally have access to Centreon helpdesk. Could you please open that request on Centreon helpdesk please so we can discuss about the problem you're talking about ? 
 
Thanks in advance

**Comment by Moujimouja** [comment]
Thanks for opening a ticket on our support, I close this issue.

**Comment by abdoulosseni** [comment]
Thanks.
