### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5319]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I used the function setseverity from "Host group service" with the API.

Describe the results you received:
The function is not implemented but can be parameterized on Centreon Web.

Describe the results you expected:
The function should be implemented.

Additional information
There is the same problem with the function Unsetseverity from "Host group service".

**Comment by loiclau** [comment]
9ad0b85b468d8630d0ea013a7c8281b6f4743c92
