### ISSUE TITLE
Extra legend shows more curves than those displayed on the graph

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5322]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Monitoring > Performances > Graphs
2. Select a CPU chart with several curves
3. Click on the information icon ("i") to display the extra legend

**Describe the results you received:**
 Extra legend shows 9 curves whereas Only 3 curves are displayed.

![image](https://user-images.githubusercontent.com/25612980/26871735-75bb0e7c-4b74-11e7-920a-63479be838cc.png)

**Describe the results you expected:**
Extra legend should only display 3  colored squares.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
This is not a bug.

It's because your service have 9 CPU stored in RRD database but some of those have 0 as value and their curves aren't displayed.
