### ISSUE TITLE
Centweb and traps from pollers.

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon#5324]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Debian 8.8

**Additional environment details (AWS, VirtualBox, physical, etc.):** Vmaware esxi 6.5

**Steps to reproduce the issue:**
1. Have multiple pollers with local ip 127.0.0.1 (also maybe with another ip if they have the same)
2. Send a trap from one them.

**Describe the results you received:**
All plugin trap (with this ip) show a warning (or critical if that was configured).

**Describe the results you expected:**
Only the good one should display the warning

**Additional information you think important (e.g. issue happens only occasionally):**
Maybe i miss something into the trap configuration. Need to take a look.

**Comment by BenoitPoulet** [comment]
The system is based on (IP of the sender)-TrapOID couple.
If several system have the same IP and have the same TrapOID assigned so.... they all match

**Comment by lpinsivy** [comment]
You can use routing in traps definition to forward traps.

**Comment by BlackstormFirst** [comment]
Hello,
Thanks for answers ^^

Maybe if the command had a field for the poller_id we would be able to differentiate it, no ?
So if you are monitoring multiple environments with the same fixed ip (or with the loopback address) for the poller, it will be ok...

--> The system is based on (IP of the sender)-TrapOID couple.

So i think in a multi pollers env. you should have something to differentiate it, to know where really come from the trap infos, like i said above otherwise, yes, each time you are trying to monitor a costumer that use the same network as another, and you want to use OID traps, you will have a Christmas tree... ?!

--> You can use routing in traps definition to forward traps.

Routing ? why should i use routing ?.. traps are working correctly except that... but thanks i will take a look... maybe that will help to differentiate the right poller...

Traps are sent to the poller... and pollers push stats/notif/graph to the central...
I think it's not linked to the routing... but only on the centrale which do not know where to get the right infos when it receive the notif from the poller...

I am wrong ?

**Comment by lpinsivy** [comment]
Sorry @BlackstormFirst for the dealy of answer.

Do you have many "centreon-engine" processus on the same Centreon central server?
