### ISSUE TITLE
[2.8.8] Unable to select all services in escalation form

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5325]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: N/A

**Centreon Broker version**: N/A

**OS**: N/A

**Steps to reproduce the issue:**
1. Go to "Configuration  >  Notifications  >  Escalations" menu
2. Edit or create a new escalations
3. Try to add all services into escalation with "Select all" and click on OK

**Describe the results you received:**

No services seleted

**Describe the results you expected:**

All services should be selected

**Comment by thiuyendang** [comment]
OK in 2.8.10  with a limited number of services to select,  otherwise page cannot be displayed by web browser.
