### ISSUE TITLE
file-response

### ISSUE THREAD

**Issue by hcornet** [centreon/centreon#5327]
Hello,

I come from the forum or in the doc to search for information about the file automatic installation reply.

I have not found anything.

So I do not know if anyone to continue using the "./install.sh -f file-response" and / or "./install.sh -u file-response"

I'm looking for documentation on it.

Thank you

**Comment by lpinsivy** [comment]
Hi,

If I remember correctly this is this file: https://github.com/centreon/centreon/blob/2.8.x/varinstall/vars

You have to copy it and modify with your path.

Regards,

**Comment by hcornet** [comment]
thank you

It is true that the file does not have a name speaking, but it is him that I looked for

**Comment by lpinsivy** [comment]
Great, good luck to build your own file.

Regards,
