### ISSUE TITLE
Metrics hidden but present on graph

### ISSUE THREAD

**Issue by AlexisTEXIER** [centreon/centreon#5328]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**:  1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS 6.8 (CES 3.0 updradded to 3.4)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM on ESXi 6.5

**Steps to reproduce the issue:**
1. Go to Administration -> Parameters -> Performance Management/Data
2. Select a service
3. select metric
4. action -> hide graphs of selected service
5. Go to Monitoring -> Performances -> Graphs
6. select same service
7. "hidden metrics" are still visible

That's the same issue I reported in #4802 

Here are the screenshots asked at that time:
- performance graph
![image](https://user-images.githubusercontent.com/22889875/26965877-1aad0b40-4cf8-11e7-8a28-68c5d1838780.png)
- metrics parameters
![image](https://user-images.githubusercontent.com/22889875/26965895-27c1a066-4cf8-11e7-954d-5646ed764181.png)

On the graph page, if I choose to export the graph as png, the metrics are well hidden.

For this service, I use virtual metrics to make sums of in and out traffic of different interfaces.

Regards

**Comment by AlexisTEXIER** [comment]
Upgraded to 2.8.9, issue still present.

**Comment by julienmathis** [comment]
Hello, 

Sorry, I just test and it works for me. 

Can you empty you js cache and try again. 

Thanks in advance

**Comment by AlexisTEXIER** [comment]
Hello,

Sorry if it's a silly question, but how did I empty the js cache ?
If it the browser cache -> no change.

Regards

**Comment by lpinsivy** [comment]
Should be corrected, not present in version 2.8.12
