### ISSUE TITLE
Color horizontal axis when checked values equal to 0

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5330]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Due to the fact that the bottom pad has been deleted in release 2.8.9.

**Steps to reproduce the issue:**
1. Go to Monitoring > Performances > graphs
2. Select a Ping chart and display it
3. check the curves when value = 0 on Y axis.

**Describe the results you received:**
when checked values = 0, curve is not visible, it looks like  we have no point on the curve.
![image](https://user-images.githubusercontent.com/25612980/26967516-c9133b18-4cfe-11e7-9be0-ef1ac2acba61.png)

**Describe the results you expected:**
Replace the 0 value part by a colored line

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Complex to do this and need to move abscisse axe to -1 to display curves equal to 0.
