### ISSUE TITLE
Widget graph monitoring empty since 2.8.9

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon#5331]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

Hello since the last update 2.8.8 to 2.8.9, my all graph widgets in Custum views are empty.

And when I look in the httpd logs, I see:
 **PHP Notice:  Undefined variable: servicePreferences in /usr/share/centreon/www/widgets/graph-monitoring/index.php on line 124, referer: https://xxxx.xxx.xxx//centreon/main.php?p=1**

![image](https://user-images.githubusercontent.com/19145945/26970954-8a731966-4d0b-11e7-9c80-b42f746887d4.png)

Thanks

**Comment by msaerowz** [comment]
same behaviour here:
PHP Notice:  Undefined variable: servicePreferences in /usr/share/centreon/www/widgets/graph-monitoring/index.php on line 124, referer: http://xxx/centreon/widgets/graph-monitoring/index.php?widgetId=29

**Comment by florian-asche** [comment]
You need to update the widget package/files and them you need to update in administration - widgets

**Comment by kozfelipe** [comment]
it seems theres an error with auto refresh of tactical-overview widget too

`[Fri Jun 09 10:53:14 2017] [error] [client *************] PHP Notice:  Undefined variable: servicePreferences in /usr/share/centreon/www/widgets/graph-monitoring/index.php on line 124, referer: http://*************/centreon/main.php?p=103
[Fri Jun 09 10:53:14 2017] [error] [client *************] PHP Notice:  Undefined index: autoRefresh in /usr/share/centreon/www/widgets/tactical-overview/src/hosts_status.php on line 82, referer: http://*************/centreon/main.php?p=103`

**Comment by lpinsivy** [comment]
New release centreon-widget-graph-monitoring-1.5.2-3 available.

Regards,

**Comment by benoitb21** [comment]
Perfect, 
thanks.

**Comment by SistemasEnergy** [comment]
Good afternoon, how I could update centreon-widget-graph-monitoring to version 1.5.2-3? I'm so noob with Centreon sorry.

Thanks in advance and regards
