### ISSUE TITLE
Centengine binds port 5669 before cbd

### ISSUE THREAD

**Issue by 5145h** [centreon/centreon#5332]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.8-4.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.7.2-3.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-cbd-3.0.7-1.el7.centos.x86_64

**OS**: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM

**Steps to reproduce the issue:**
1. yum update
2. systemctl restart centcore ; systemctl restart centengine; systemctl restart cbd
3.  netstat -plantu | grep 5669

**Describe the results you received:**
```
tcp        0      0 0.0.0.0:5669            0.0.0.0:*               LISTEN      8243/centengine
tcp        0      0 127.0.0.1:64290         127.0.0.1:5669          ESTABLISHED 8276/cbd
tcp        0      0 127.0.0.1:5669          127.0.0.1:64290         ESTABLISHED 8243/centengine
```

**From central-broker-master.log:**

```
Centreon Broker 3.0.7 log file opened
[1497017415] config:  log applier: applying 1 logging objects
[1497017415] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1497017429] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: cannot listen on port 5669: The bound address is already in use
[1497017459] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: cannot listen on port 5669: The bound address is already in use
```

**Describe the results you expected:**
```
# netstat -plantu | grep 5669
tcp        0      0 0.0.0.0:5669            0.0.0.0:*               LISTEN      8327/cbd
tcp        0      0 127.0.0.1:64300         127.0.0.1:5669          ESTABLISHED 8328/cbd
tcp        0      0 127.0.0.1:5669          127.0.0.1:64300         ESTABLISHED 8327/cbd
```

**Additional information you think important (e.g. issue happens only occasionally):**
If I stop centengine and restart cbd I have the expected result.
Centengine in debugging mode restarted after cbd binds to 5669 does not complain at all.

**Comment by lpinsivy** [comment]
Hi,

In the configuration of Centreon Broker module linked to your Centreon Engine, did you leave the field "Host to connect to" empty?

![screenshot at juin 13 14-36-12](https://user-images.githubusercontent.com/3351916/27082593-b5b5467a-5045-11e7-8ee4-42cff08a8de5.png)

Regards,

**Comment by 5145h** [comment]
Hi, 

It has 'localhost' by default.

BR.

**Comment by julienmathis** [comment]
@ganoze can you help us ?

**Comment by ganoze** [comment]
@5145h could you send your central-module-master.xml and your centengine.cfg files to check them please ?

**Comment by 5145h** [comment]
[configs.zip](https://github.com/centreon/centreon/files/1087499/configs.zip)

**Comment by ganoze** [comment]
Thank you very much. Your Centreon Engine configuration is not correct. You load cbmod.so by using _/etc/centreon-broker/central-broker.xml_, whereas you should use _/etc/centreon-broker/central-module.xml_.

Once fixed, your issue should disappear.

**Comment by 5145h** [comment]
Hi, 

Thanks a lot. My bad.
Though wouldn't be possible to verify somehow if the .xml that is loaded with cbmod.so is a correct module .xml - something like nagios is checking it's .cfg before starting the process?

I think this could be closed.

BR.

**Comment by ganoze** [comment]
Of course a file verification would be a must have, but this is not currently on our top priorities,

PR are more than welcome though ;-)
