### ISSUE TITLE
/usr/sbin/service into /etc/sudoers.d/centreon but this file does not exist on centos 6.9

### ISSUE THREAD

**Issue by lkappel** [centreon/centreon#5333]
I just updated all my pollers with revision 2.8.9. There are entries /usr/sbin/service into /etc/sudoers.d/centreon but this file (/usr/sbin/service) does not exist on centos 6.9 ...

Please, take a look

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web-2.8.9-19.el6.noarch

**Centreon Engine version**: 
root@central:/etc/sudoers.d# rpm -qilf /etc/sudoers.d/centreon
Name : centreon-poller-centreon-engine Relocations: (not relocatable)
Version : 2.8.9 Vendor: (none)
Release : 19.el6 Build Date: jeu. 08 juin 2017 17:53:27 CEST
Install Date: ven. 09 juin 2017 10:16:38 CEST Build Host: 8b69d8fd46e7
Group : Networking/Other Source RPM: centreon-2.8.9-19.el6.src.rpm
Size : 2522 License: GPLv2
Signature : DSA/SHA1, jeu. 08 juin 2017 17:53:29 CEST, Key ID f6fc4ae38a7652bc
URL : http://www.centreon.com
Summary : Rights and file for pollers (including central)
Description :
This package add rights and default directories for a poller
managed by Centreon. This includes the default central poller.
/etc/centreon/centreontrapd.pm
/etc/centreon/conf.pm
/etc/sudoers.d/centreon
/var/lib/centreon
/var/log/centreon
/var/run/centreon

**Centreon Broker version**: 
centreon-broker-cbd-3.0.7-1.el6.x86_64

**OS**: 
root@central:/etc/sudoers.d# cat /etc/redhat-release
​C​entOS release 6.9 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox 5.1

**Steps to reproduce the issue:**

**Describe the results you received:**
root@central:/ ls -l /usr/sbin/service
ls: impossible d'accéder à /usr/sbin/service: Aucun fichier ou dossier de ce type

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Already done!
