### ISSUE TITLE
Graph period displayed does not match selected zoom period

### ISSUE THREAD

**Issue by jcoerch** [centreon/centreon#5334]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**OS**: CentOS 6

**Steps to reproduce the issue:**
1. Go to "Monitoring > Performances > Graphs" menu
2. Select chart to display
3. Zoom on chart

**Describe the results you received:**
In this example, I try to zoom from 2017-03-01 at 01:00:00 to 2017-03-20 at 09:00:00

![a](https://user-images.githubusercontent.com/29310007/27023504-20de9346-4f53-11e7-8432-245dbd655164.jpeg)

And the result show me the graph from 2017-03-05 at 17:00:00 to 2017-03-24 at 19:00:00

![b](https://user-images.githubusercontent.com/29310007/27023515-24fcf4c2-4f53-11e7-9ff9-ac1bc5b570c5.jpeg)

**Comment by kduret** [comment]
Duplicated #5112

**Comment by kduret** [comment]
Fixed here : 65da8503013e031e9e6b556e8a2b663c8d8a63ca

**Comment by thiuyendang** [comment]
OK in 2.8.10, centOS6 and centOS7
