### ISSUE TITLE
[2.8.9] Installation with sources, Centreon plugins are not copied

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#5336]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.9 (source tar.gz)

**Centreon Engine version**:  1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Debian 8

After installing Centreon web sources, Centreon plugins are not copied to /usr/lib/nagios/plugins

**Comment by lpinsivy** [comment]
Hi @kermith72 

Are you talking about old Centreon Plugins "check_centreon_xxxx" or news Centreon Plugins ?

Regards,

**Comment by kermith72** [comment]
Hi @lpinsivy 

old Centreon Plugins "check_centreon_xxxx" of course

Regards,

**Comment by lpinsivy** [comment]
This plugins have been removed because their are obsoletes.

The goal is to use new Centreon Plugins.

Regards,
