### ISSUE TITLE
"Extended status information" in Event logs

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#5337]
**Centreon Web version**: 2.8.5

**Centreon Engine version**: 3.0.7

**Centreon Broker version**: 1.7.2

**OS**: 6.8

Would it be possible to have the "Extended status information" in the page of the "Event logs", to have the detail of the problems.

For example, we display the return of the "curl" command for a WEB page check with a proxy and authentication.

When we want to understand the problems that occurred in the night, we no longer have the result of the checks.

**Comment by julienmathis** [comment]
Hello, 

For the moment, this is not possible. We have to change broker and DB structur eto do that. 

So in the next major value may be.

**Comment by omercier** [comment]
Hi,
I understand the need. This would imply a huge storage consumption and additional network load, but why not.
I added it to my backlog for later.
Regards
Refs: MON-11064
