### ISSUE TITLE
Autologin + fullscreen options

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon#5338]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

Hello,

I use the "Custom Views" page with a Raspberry and a large screen, in order to have a Supervision Screen in our office room.

To don't manage the startup of the system, I use the autologin parameters with the token.

But, I know it's possible to use the "fullscreen" option with the parameters "min=1"
https://xxxx.xxxx.xxx/centreon/main.php?p=103&min=1
It's ok, but when I cumulate the 2 options, it doesn't work.
OK for the autologin, but the "fullscreen" option doesn't work.

I think that the autologin process isn't write to check if the "min" parameter exists.

You can help me.

Thanks

**Comment by thiuyendang** [comment]
Checked in 2.8.10, CentOS7 and CentOS6, both options can be combinated (autologin + fullscreen)

**Comment by benoitb21** [comment]
Hello,
Since version 18.10, I have the problem again.

**Comment by benoitb21** [comment]
Globally, I think that the min=1 doesn't work

**Comment by thiuyendang** [comment]
min=1 option works but not with autologin, for sure.
Try with another page

**Comment by benoitb21** [comment]
I see that the min=1 works just if we have the "p=xxx" parameter is present.

So the autologin works just if you insert a "p" parameter.

**Comment by thiuyendang** [comment]
OK, I don't contest your issue, we will take it into account, don't worry about it.

**Comment by thiuyendang** [comment]
Semble corrigé en 18.10.2

**Comment by cgagnaire** [comment]
Fixed on 19.04.x and 19.10.x by #8262
