### ISSUE TITLE
[2.8.9] Graphic metrics not very useable

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon#5339]
**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS 6.9

**Steps to reproduce the issue:**
Graphics works, but the metrics is not very usable. Since 2.8.9, CPU report value of 110 (before 11K). Memory report values with 3 decimals after the point (190.375 MB), not important for us.

Look at the screen shots below.
Thank you !

Best regards

<img width="1159" alt="cpu plugin" src="https://user-images.githubusercontent.com/28057146/27067659-3dac8028-500c-11e7-9ded-f64932d6dbd2.png">
<img width="1157" alt="memory plugin" src="https://user-images.githubusercontent.com/28057146/27067660-3dadafb6-500c-11e7-9f19-0ce2e871edf4.png">
<img width="1158" alt="storage plugin" src="https://user-images.githubusercontent.com/28057146/27067658-3dab2174-500c-11e7-9ba7-b1d4c027fe9d.png">

**Comment by kduret** [comment]
Hi,

Cpu usage unit is percent, so why 11K is better than 110.0 ?

I agree with you 3 decimals is not important for your metrics, but it's a general setting and may be usefull for other metrics.
We will think about put the number of decimals as preferences.

**Comment by stefanotoro** [comment]
Hi,

11K is not better than 110, but 110 is not the real value. For me the good value is 100 (%).
Thank you !

**Comment by kduret** [comment]
You are probably using a CPU graph template (Max value is set to 110)
If you want to update it, you have to go to Monitoring > Performances > Templates

**Comment by stefanotoro** [comment]
Okay, Upper Limit set to 100.

Thank you
