### ISSUE TITLE
Extra legend don't format the data correctly

### ISSUE THREAD

**Issue by lkco** [centreon/centreon#5340]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CES

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Monitoring > Performances > Graphs
2. Select a Disk chart with perfdata
3. Click on the information icon ("i") to display the extra legend

**Describe the results you received:**
Extra legend shows perfdata in bytes
http://www.hostingpics.net/viewer.php?id=846666Slection004.png

**Describe the results you expected:**
Extra legend should be display perfdata in GBytes like that rrdtool image

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by kduret** [comment]
Fixed in 2.8.9 : 023fa8f211ca295b835cdfc20afce40ad54deada
