### ISSUE TITLE
[2.8.9] Special chars in perfdata breaks graph legend

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#5342]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CES 3.4/CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.): VMWare,KVM,Physical

**Steps to reproduce the issue:**
1. Create a check command with a backslash or percent char in perfdata. 
For example |'test%'=0;;;; or |'\test'=0;;;;.
Unfortunately that's common for various NSClient++ checks like physikal memory or disk space.
2. Go to monitorig and look at the perfdata hover

**Describe the results you received:**
The metric legend in the perfdata hover is missing and the design looks broken.
In the graph details the legend is missing, too.

**Describe the results you expected:**
The metric legend should be displayed correctly.

**Comment by mwielander** [comment]
![bug_graph_screenshot_2017-06-30_12-05-13](https://user-images.githubusercontent.com/29795430/27731295-a2adac26-5d8c-11e7-8f08-2069c53e5713.png)

here an example

**Comment by mwielander** [comment]
![bug_graph_screenshot_2_2017-06-30_12-05-13](https://user-images.githubusercontent.com/29795430/27731363-f33d536c-5d8c-11e7-9f23-ce02677ab066.png)

second screenshot

**Comment by mwielander** [comment]
![bug_graph_perfdata_screenshot_2017-06-30_12-05-13](https://user-images.githubusercontent.com/29795430/27731600-faf29ed6-5d8d-11e7-90b2-d2184d18486f.png)

here perfdata example

**Comment by kduret** [comment]
Fix blank spaces in metric name : 6ea903575cb47a48fa7c0c408939fad84ee7ac86

**Comment by lpinsivy** [comment]
linked to #5554 and should be fix by #5579
