### ISSUE TITLE
filesGeneration/engine not exported to satellite poller

### ISSUE THREAD

**Issue by UNK-CJO** [centreon/centreon#5347]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Hi, 

After upgrade from Centreon 2.7 our existing poller stopped receiving configuration changes from master. All configurations files are generated inside /usr/share/centreon/filesGeneration/engine/* but they are never sent to our remote pollers. By manually send these files thanks to scp command and after doing an engine reload, all configurations are applied.

There's no issues with ssh and ssh keys, the autologin from our central to the poller with private key works well for the centreon user. 

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Debian jessie

**Additional environment details (AWS, VirtualBox, physical, etc.): 
Physical centcore and virtual poller

**Steps to reproduce the issue:**
1. Add an host checked by a remote poller
2. Processing reload 
3. Check if the host is present inside the monitoring view

**Describe the results you received:**
Host is present in configuration but not in monitoring view, configuration files in /usr/share/centreon/filesGeneration/engine/* are updated but not in /etc/centreon-engine on the poller

**Describe the results you expected:**
/usr/share/centreon/filesGeneration/engine/* copied to poller inside /etc/centreon-engine

**Comment by lpinsivy** [comment]
HI,

Did you restart centcore process? Is still running? Do you have error in /var/log/centcore.log file?

Regards,

**Comment by UNK-CJO** [comment]
Hi, 

Centcore process was restarted several times, the server too. 

There's no error in centcore.log file but there's a sudo prompt every time I reload the configuration : 
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: pas de tty présent et pas de programme askpass spécifié

**Comment by lpinsivy** [comment]
Hi,

sudo problem can only have an impact on restart/reload Centreon Engine process but not to send configuration files to the poller.

Can you enable debug in centcore:
1. Edit /etc/sysconfig/centcore and replace "error" by "debug".
2. Go to "Administration > Parameters > Debug" and enable debug for centcore
3. Restart centcore
4. Export configuration to a poller using Centreon Web interface.

**Comment by UNK-CJO** [comment]
Hi, 

Thanks for this, we are moving closer to outcome. It's look like a permission problem : 
2017-06-15 10:52:15 - Enable Debug in Centcore
2017-06-15 10:52:17 - 5376 Receiving order to stop...
2017-06-15 10:52:17 - Centcore stop...
2017-06-15 10:52:17 - Starting centcore engine...
2017-06-15 10:52:47 - Start: Send config files on poller 4
2017-06-15 10:52:47 - Result : /usr/share/centreon//filesGeneration/nagiosCFG/4/*: Permission denied
2017-06-15 10:52:47 - End: Send config files on poller 4
2017-06-15 10:52:47 - Start: Send Centreon Broker config files on poller 4
2017-06-15 10:52:47 - Result :
2017-06-15 10:52:47 - End: Send Centreon Broker config files on poller 4
2017-06-15 10:52:48 - Init Script : 'sudo /etc/init.d/centengine reload' On poller 172.16.1.3 (4)
2017-06-15 10:52:48 - Engine : Reloading centengine configuration (via systemctl): centengine.service.

This problem is not present when i do this manually with the centreon user, could you confirm me wich rights are needed ?

Best regards

**Comment by lpinsivy** [comment]
Hi,

I don't understand why centcore try to send configuration /usr/share/centreon/filesGeneration/nagiosCFG/4/ and not from /usr/share/centreon/filesGeneration/engine/4/

Can you give me rights from /usr/share/centreon/filesGeneration directory and sub directories ?

# ls -lah /usr/share/centreon/filesGeneration/
total 20K
drwxrwsr-x.  5 centreon centreon 4,0K  8 juin  17:53 .
drwxr-xr-x. 14 root     root     4,0K  2 mai   14:57 ..
drwxrwsr-x. 13 centreon centreon 4,0K 15 juin  17:16 broker
drwxrwsr-x  13 centreon centreon 4,0K 15 juin  17:16 engine
drwxrwsr-x. 11 centreon centreon 4,0K 10 nov.   2016 nagiosCFG

**Comment by UNK-CJO** [comment]
Hi, 

You'll find rights just bellow : 
total 20K
drwxrwsr-x  5 root     root     4,0K juin   9 11:26 .
drwxr-xr-x 14 root     root     4,0K mars   1  2016 ..
drwxrwsr-x  7 centreon centreon 4,0K juin  15 10:57 broker
drwxrwsr-x  5 centreon centreon 4,0K juin  15 10:57 engine
drwxrwsr-x  6 centreon centreon 4,0K juin   8 17:35 nagiosCFG

best regards

**Comment by julienmathis** [comment]
Did you just update Centreon ?

**Comment by UNK-CJO** [comment]
Hi,
I updated Centreon last week on friday.

**Comment by julienmathis** [comment]
Did you restart centcore ? I think the old version of centcore is still running and so this instance have old paths in memory. 

Please do a restart on centcore

**Comment by UNK-CJO** [comment]
Like i told to lpinsivy, server was rebooted 2 or 3 times since the upgrade.
Just bellow an output of centcore process on my server : 
centreon 28269  0.0  0.0 141136 18908 ?        S    juin15   0:06 /usr/bin/perl /usr/share/centreon/bin/centcore --logfile=/var/log/centreon/centcore.log --severity=error --config=/etc/centreon/conf.pm
root     28952  0.0  0.0  12748  2216 pts/0    S+   17:42   0:00 grep centcore

**Comment by lpinsivy** [comment]
no error in /var/log/centreon/centcore.log about SSH ?

**Comment by UNK-CJO** [comment]
Hi, 

Thanks for your help. 
I see just one thin in centcore.log but it's about the files path used : 

2017-09-07 09:21:38 - Init Script : 'sudo /etc/init.d/centengine reload' On poller 172.16.1.3 (4)
2017-09-07 09:21:38 - Engine : Reloading centengine configuration (via systemctl): centengine.service.
2017-09-07 09:22:01 - Start: Send config files on poller 3
2017-09-07 09:22:01 - Result : /usr/share/centreon//filesGeneration/nagiosCFG/3/*: No such file or directory
2017-09-07 09:22:01 - End: Send config files on poller 3

Files are present inside /usr/share/centreon/filesGeneration/nagiosCFG/3/

Now i'm used to do manually scp and reload command thanks to the centreon account. 
But it will be better with the web interface 👍

**Comment by UNK-CJO** [comment]
Hi, 

I restarted upgrade process with the latest version of centreon web, it works like a charm now. 
Thanks for you help.

**Comment by pmpintogil** [comment]
Hi, i have that centreon version:
Core:
Centreon version 2.8.28
Centreon Engine 1.8.1
Centreon Web 3.4
Poller:
Centreon Engine 1.8.1

I has the same problem, the core configuration UI not update the poller local cfg file, but if the update is maked on CLI, the file is upgraded.

Some Help Please.
