### ISSUE TITLE
[2.8.9] - host configuration can not be saved or modified

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#5348]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: SL 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare

**Steps to reproduce the issue:**
1. create a new host through a host template which uses a service template that includes the macro $_HOSTLOCATION$; for example windows ntp time check
2. save the configuration
3. change poller or host template
4. save the configuration

**Describe the results you received:**
nothing happens. after pressing the save button the page refresh, but the configuration will not saved and the host configuration page is still there without any error or information

**Describe the results you expected:**
the configuration will be saved.

**Additional information you think important (e.g. issue happens only occasionally):**
Please review case #5290, that you closed, but problem is not resolved. If you need additional informations I can reproduce the problem.

**Comment by kduret** [comment]
Hi,

It's fixed in 2.8.10 : 15676ae5fb8c499ba0cc8ae8fd985f17f5bd3f62

SQL query to fix your problem : 
`DELETE FROM nagios_macro WHERE macro_name = '$_HOSTLOCATION$';`

**Comment by thiuyendang** [comment]
Fix checked in release 2.8.10, centOS6 and CentOS7.
