### ISSUE TITLE
Meta-services with an accent in Output

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5349]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.0.11

**OS**: CES 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Create a meta-service with an accent in the output
2. Save
3.

**Describe the results you received:**
The meta-service is not saved

**Describe the results you expected:**
The meta-service should be saved

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
@lolokai I can't reproduce your issue

![screenshot at juin 16 14-52-45](https://user-images.githubusercontent.com/3351916/27227381-8af38f04-52a3-11e7-814a-93502bf30153.png)
![screenshot at juin 16 14-53-00](https://user-images.githubusercontent.com/3351916/27227383-8cc39126-52a3-11e7-80b5-1465eff9186a.png)

**Comment by lpinsivy** [comment]
Duplicate #5204
