### ISSUE TITLE
Change host template clears all services and graphs

### ISSUE THREAD

**Issue by bdeschut** [centreon/centreon#5350]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.6
**Centreon Engine version**: 1.7.2
**Centreon Broker version**: 3.0.5
**OS**: CentOS release 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware Virtual Centreon - pollers running on Dell hardware

**Steps to reproduce the issue:**
1. Create host using a host template
2. <replace the host with new hardware>
3. Change host template

**Describe the results you received:**
All current services (that were linked with the service templates that are linked with the old host template) are deleted, services for the new host template are added

**Describe the results you expected:**
1. If a service from the old host template is not in the new host template, the service remains on the host.
2. If a service is in the new host template but not in the old host template, it is added
3. If a service is in both templates, the data is retained but uses the arguments from the service template linked to the new host template
3. If a service is in both templates, but disabled, it should remain disabled. Because of the "wipe all" and "re-add", these services are enabled again

**Additional information you think important (e.g. issue happens only occasionally):**
We have certain devices for example Check Point firewall 4800, which are being replaced by 5800 models. We have host templates for both models. When replacing the firewalls (hardware upgrade from 4800 to 5800), I change the host template and apply it, but this seemed to wipe all graphs, which is not what I expected.

I found issue #4780, but as it should have been fixed in 2.8.5 and I'm not sure it's about the same issue, I am creating this new ticket. Additionally, I can't seem to find any documentation referencing this specific subject.

Kind regards,
Bob

**Comment by Sims24** [comment]
Hi,

This is the expected behaviour, as mentionned by @lpinsivy here https://github.com/centreon/centreon/issues/4795 it's very difficult (lot of query behind I think) to manage what you want.

**Comment by bdeschut** [comment]
Thank you for your answer.

I can understand that it will require some development, but it doesn't seem impossible?
If there is a service name match between the current service and one from the new host template AND the current services template ID matches the service template ID of the new host template -> leave the service as is. It might be more complicated, but it would already cover most scenario's I think.

I can't even change the host template without applying service templates as well, given that at any point in the future, we might re-apply the service templates.

I don't know how other customers handle this? Am i doing it wrong? Do they just agree with losing all data when changing the host template? I can imagine that certain data retention policies don't even allow this.
If the permanent answer is "By design" and "Won't fix", I think we will have to consider other monitoring solutions.

regards,
Bob

**Comment by lpinsivy** [comment]
Hi,

It's more complex than you explain. Indeed we can't keep same service and graph if performance data of service template (may be using new plugin) changes.

We have to cover many cases with this enhancement.

It is not impossible but not schedule for next few months.

However, change a host template is not an operation made so frequently.

Regards,

**Comment by btassite** [comment]
We change host templates regularly as many things keep evolving. The whole point of having templates is to not have to change every single check every time some underlying check changes. This could be circumvented with wrapper scripts that replace the original checks but that adds load and lower level complexity.
