### ISSUE TITLE
"Split Graph" doesn't display the virtual metric graph

### ISSUE THREAD

**Issue by sizeur** [centreon/centreon#5353]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.7
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1. Create a virtual metric and apply it to a graph
2. Go to Monitoring  >  Performances  >  Graphs and click on "Split Chart"

**Describe the results you received:**
The graph is splitted indeed but the virtual metric are absent:
![splitgraph](https://user-images.githubusercontent.com/13485588/27221635-8e09cbaa-5289-11e7-8a15-1ead110e365e.jpg)

**Describe the results you expected:**
Could it be possible to display the virtual metric as well ?

**Comment by lpinsivy** [comment]
Moreover, virtual metric is not displayed into legend.

<img width="1085" alt="screenshot at aout 31 17-42-13" src="https://user-images.githubusercontent.com/3351916/29932165-c38adee2-8e73-11e7-832c-6190ae14dc39.png">
