### ISSUE TITLE
"Fill in" option in graph doesn't work with "VDEF" DEF type

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5354]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.7
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1. Create a virtual metric with the option "Hidden Graph And Legend" and with a DEF Type "VDEF":
![image](https://user-images.githubusercontent.com/13485588/27222123-5aea88fc-528b-11e7-8fec-c43a4a3f3ed5.png)

2. Create a second virtual metric CDEF based on the first one:
![image](https://user-images.githubusercontent.com/13485588/27222160-8957922a-528b-11e7-87b9-3ecdf297fb14.png)

3.  Create a new template curve which used the second virtual metric and disable the option "Filling"
![image](https://user-images.githubusercontent.com/13485588/27222908-84bde072-528e-11e7-8ae6-558d906fec90.png)

4. Go to Monitoring  >  Performances  >  Graphs

**Describe the results you received:**
The curve is always "filled in", when ever the option is enabled or not:
![image](https://user-images.githubusercontent.com/13485588/27222942-aab64c4c-528e-11e7-98d5-6d6752c57a76.png)

**Describe the results you expected:**

The option "Fill in" should be taken into account

**Comment by thiuyendang** [comment]
Tested in 2.8.10, CentOS6, CentOS7 : OK
