### ISSUE TITLE
Virtual Metric problems with French language package

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5355]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.7
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1. Download and install the FR language package centreon-lang-fr_FR-2.8 from download.centreon.com
2. Change the language of a user for fr_FR.UTF-8
3. Create a virtual metric like below and you get an error message "Wrong RPN syntax (RRDtool said:)
![image](https://user-images.githubusercontent.com/13485588/27224187-0e96d2e0-5294-11e7-9317-c5906ef3b10b.png)

**Describe the results you received:**
The value of the virtual metric is wrong in the graph, but once you switch the language to English again the value are correct and you don't have this error message anymore

**Comment by thiuyendang** [comment]
OK 2.8.10 CentOS6
OK 2.8.10 CentOS7
