### ISSUE TITLE
Limite Linked Host Services in Service Groupe

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5360]
[EN]
Hello, 
I tried to create a Service Group with around 400 Linked Host service. When I browse into the SG, my web browser crash. It also appears that the poller cannot reload anymore. 
Thanks in advanced
[EN]

[FR]
Bonjour,
J’ai créé un Service groupe avec environ 400 Linked Host service. Si j’essaye de l’ouvrir mon navigateur crash. Il semblerait que le poller ne puisse plus recharger sa conf également. 
Merci par avance.
[FR]

ma version actuelle :
Centreon 2.8.9
Centreon Engine 1.7.2
MariaDB 5.5.53

**Comment by lpinsivy** [comment]
Manage hundred of objects using web interface is not the best way. Centreon had developed API for automatisation.
