### ISSUE TITLE
SNMP Trap, not all parameters are saved on creation

### ISSUE THREAD

**Issue by tanguyvda** [centreon/centreon#5361]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS release 6.9 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. create a new trap
2. tick the advancing matching mode box 
3. fill the already made @OUTPUT@ matching rule (or add a new one)
4. save

**Describe the results you received:**
After saving, the advanced matching rule is no longer configured

**Describe the results you expected:**
After saving, I want my matching rule to still be there (nom d'un caribou !)

**Additional information you think important (e.g. issue happens only occasionally):**
you can easily make it works by editing again your trap and save its configuration, it will now works, looks like it just fails on the trap creation

Have a nice day

**Comment by lpinsivy** [comment]
should be solved by PR #5415 of #5361 issue
