### ISSUE TITLE
The "select all" button doesn't work

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5362]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.7
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1.Go to  any menu where the "select all" button is present, for example Configuration  >  Services  >  Service Groups and select on "Select all" button, nothing is added:
![image](https://user-images.githubusercontent.com/13485588/27379483-ac0f6bdc-567b-11e7-820e-eae06ed46248.png)

**Describe the results you received:**
Nothing is selected when we click on "select all"

**Describe the results you expected:**
The field should select all the element present when we click on "Select all"

**Comment by julienmathis** [comment]
It works for me but it's very long. How much services do you have ?

**Comment by tseegers** [comment]
Hello Julien, i try to add 7 services and after 1 minute nothing appears in the field. I have checked on two servers with two different browsers and the problem is still present.

**Comment by julienmathis** [comment]
Which browser ?

**Comment by bmareau** [comment]
Hi,

Same problem with "Monitoring - Downtimes - Add Downtime".
But just with "Services".

Chrome 59.0.3071.109
Centreon Web 2.8.9

**Comment by lpinsivy** [comment]
linked to #5389 ?

**Comment by lpinsivy** [comment]
Should be fixed. I close issue
