### ISSUE TITLE
[2.8.9] - Max graph scale is not set correctly according template

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#5363]
**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: centOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. set template storage with 
     Lower Limit=0
     Upper Limit= Set to Max
like this:
![centreon_disk_storage_template](https://user-images.githubusercontent.com/8720203/27381114-d57d61c6-5681-11e7-83e1-73b91842cffe.png)

2. display graph  who have this template
3. 

**Describe the results you received:**
The disk in example has 60Gb size
max size not set correctly, the scale is bound of max value in period.

see below:
Graph of last 3 hours

![centreon_disk_3hours](https://user-images.githubusercontent.com/8720203/27381239-61f31e7a-5682-11e7-8b51-0e80ba6ce753.png)
and graph of last 7 days

![centreon_disk_7days](https://user-images.githubusercontent.com/8720203/27381245-671469c2-5682-11e7-99b8-1c7a15d168c9.png)

**Describe the results you expected:**
The max value on scale should be at 60Gb

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Because the warning and critical lines are displayed the chart takes critical thresholds at maximum
