### ISSUE TITLE
 [2.8.9] - Problem with ldap contactgroups with name members with acent

### ISSUE THREAD

**Issue by tpaxle** [centreon/centreon#5368]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS 5.9

**Additional environment details (AWS, VirtualBox, physical, etc.): Microsoft Active Directory with Windows Server 2008R2

**Steps to reproduce the issue:**
1. Create a Group in ldap: Group_A
2. Create a new User in ldap. The name must have acent "José xxx xx xx".
3. The new user must be member of Grupo_A.
3. Import User "José xxx" from ldap in Centreon
4. Configure notification host over any host or service with contactgroup "Group A (ldap..)"
5. Export configuration

**Describe the results you received:**
review definition of contactgroup "Group_A" in /etc/centreon-engine/contactgroups.cfg. it's showed only members without agent, new user doesn't appear.

**Describe the results you expected:**
I expect that all user in Group_A must be in definition of /etc/centreon-engine/contactgroups.cfg

**Comment by lpinsivy** [comment]
Hi,

Did you use version 3 of the protocol?

Regards,

**Comment by tpaxle** [comment]
Hi,

We use version 2. We are going to try.

Regards

**Comment by lpinsivy** [comment]
Hi,

Your new user are correctly imported into Centreon ?
With correct accent ?

Regards,
