### ISSUE TITLE
[2.8.8] Missing feature - Disable perfdata

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon#5369]
**Centreon Web version**:2.8.8
**Centreon Engine version**:1.7.2
**Centreon Broker version**:3.0.7
**OS**: Oracle Linux 7
**Additional environment details** :Virtual
**Steps to reproduce the issue:** 
In Centreon 2.6 there was a good feature to disable perfdata in templates or in services , But it is missing from 2.8.

![image](https://user-images.githubusercontent.com/25457811/27403972-b6f59264-56cc-11e7-9451-8fe9ff5e06ab.png)

**Describe the results you expected:**
We would like to disable perfdata in this version too.

Thanks,

Tamas

**Comment by julienmathis** [comment]
It was working on version 2.6 only if you used centstorage. So we have remove centstorage. So we prefer not manage this function with centreon broker. 

The main part of our users want to have graphs when plugin generate perfdata. So I think it's useless to maintain this kind of functionnality. We have better features to implement.

We will not implement this is the futur.
