### ISSUE TITLE
no Graphs with rrdtool 1.6.0 (Debian 9.0 Stretch), rrdtool v1.4.8 works

### ISSUE THREAD

**Issue by leo29041982** [centreon/centreon#5370]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.9

**OS**: Debian 9.0 Stretch

**rrdtool**: 1.6.0 from Debian Stretch
**php** 5.6.30 from packages.sury.org/php/

**Steps to reproduce the issue:**
1. Show Graph via Popup or menue

**Describe the results you received:**
No Graph displayed.

With rrdtool v 1.4.8 installed from Debian Jessie repository on a Stretch graphs are displayed.

with rrdtool v1.6.0:
![image](https://user-images.githubusercontent.com/24585227/27421889-8e2a3c44-572c-11e7-9d12-d9692c8824d5.png)

with rrdtool v1.4.8:
![image](https://user-images.githubusercontent.com/24585227/27421936-c65db974-572c-11e7-9678-dd76108ae13a.png)

No errors in any logfiles!

**Comment by julienmathis** [comment]
Hello, 

It's normal. For the moment, Centreon Broker is only compatible with rrdtool 1.4.8. It's not a priority to upgrade that. 

Thanks for your feedback
