### ISSUE TITLE
Add centreon knowledge base compatibility with recent mediawiki

### ISSUE THREAD

**Issue by loiclau** [centreon/centreon#5379]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.5
**OS**: 
centos7

**Steps to reproduce the issue:**
1. Install mediawiki 1.28
2. Configure knowledge base
3. Delete a knowledge page

**Describe the results you received:**
the page is not deleted

**Describe the results you expected:**
the page is deleted

**Additional information you think important (e.g. issue happens only occasionally):**
Mediawiki authentication change since 1.27

**Comment by cmeschin** [comment]
Hi, any news about this enhancement?
thanks,

**Comment by lpinsivy** [comment]
@cmeschin not yet scheduled

**Comment by adr-mo** [comment]
**Fixed in 18.10.5**
