### ISSUE TITLE
Many "central-rrd-master.queue.central-rrd-master-output" and input files ...

### ISSUE THREAD

**Issue by tmaff** [centreon/centreon#5380]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9

**Centreon Engine version**: 
1.7.2

**Centreon Broker version**: 
3.0.7
**OS**: 
CentOS7

**Steps to reproduce the issue:**
1. I list the directory "/var/lib/centreon-broker" and see many many files ..

**Describe the results you received:**

-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:15 central-rrd-master.queue.central-rrd-master-input-10
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:16 central-rrd-master.queue.central-rrd-master-input-11
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:17 central-rrd-master.queue.central-rrd-master-input-12
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:18 central-rrd-master.queue.central-rrd-master-input-13
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:19 central-rrd-master.queue.central-rrd-master-input-14
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:20 central-rrd-master.queue.central-rrd-master-input-15
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:21 central-rrd-master.queue.central-rrd-master-input-16
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 23 10:07 central-rrd-master.queue.central-rrd-master-input-17
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:08 central-rrd-master.queue.central-rrd-master-input-3
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:09 central-rrd-master.queue.central-rrd-master-input-4
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:12 central-rrd-master.queue.central-rrd-master-input-67
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:13 central-rrd-master.queue.central-rrd-master-input-68
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:14 central-rrd-master.queue.central-rrd-master-input-69
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:12 central-rrd-master.queue.central-rrd-master-input-7
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:15 central-rrd-master.queue.central-rrd-master-input-70
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:16 central-rrd-master.queue.central-rrd-master-input-71
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:17 central-rrd-master.queue.central-rrd-master-input-72
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:18 central-rrd-master.queue.central-rrd-master-input-73
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:19 central-rrd-master.queue.central-rrd-master-input-74
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:21 central-rrd-master.queue.central-rrd-master-input-76
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:22 central-rrd-master.queue.central-rrd-master-input-77
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:23 central-rrd-master.queue.central-rrd-master-input-78
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:24 central-rrd-master.queue.central-rrd-master-input-79
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:13 central-rrd-master.queue.central-rrd-master-input-8
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:25 central-rrd-master.queue.central-rrd-master-input-80
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:26 central-rrd-master.queue.central-rrd-master-input-81
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:27 central-rrd-master.queue.central-rrd-master-input-82
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:28 central-rrd-master.queue.central-rrd-master-input-83
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 20:29 central-rrd-master.queue.central-rrd-master-input-84
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 19:14 central-rrd-master.queue.central-rrd-master-input-9
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 22 13:52 central-rrd-master.queue.central-rrd-master-output
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 22 22:07 central-rrd-master.queue.central-rrd-master-output1
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:08 central-rrd-master.queue.central-rrd-master-output10
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:08 central-rrd-master.queue.central-rrd-master-output11
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:08 central-rrd-master.queue.central-rrd-master-output12
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:08 central-rrd-master.queue.central-rrd-master-output13
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:08 central-rrd-master.queue.central-rrd-master-output14
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 27 23:42 central-rrd-master.queue.central-rrd-master-output15
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 28 08:30 central-rrd-master.queue.central-rrd-master-output16
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 28 17:10 central-rrd-master.queue.central-rrd-master-output17
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 29 01:58 central-rrd-master.queue.central-rrd-master-output18
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 29 10:23 central-rrd-master.queue.central-rrd-master-output19
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 23 06:47 central-rrd-master.queue.central-rrd-master-output2
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output20
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output21
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output22
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output23
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output24
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output25
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output26
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output27
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output28
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output29
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 23 14:30 central-rrd-master.queue.central-rrd-master-output3
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:12 central-rrd-master.queue.central-rrd-master-output30
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  2 19:02 central-rrd-master.queue.central-rrd-master-output31
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  3 18:20 central-rrd-master.queue.central-rrd-master-output32
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  4 03:05 central-rrd-master.queue.central-rrd-master-output33
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  4 11:45 central-rrd-master.queue.central-rrd-master-output34
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  4 20:30 central-rrd-master.queue.central-rrd-master-output35
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  5 05:07 central-rrd-master.queue.central-rrd-master-output36
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  5 13:53 central-rrd-master.queue.central-rrd-master-output37
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  6 09:47 central-rrd-master.queue.central-rrd-master-output39
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 23 22:39 central-rrd-master.queue.central-rrd-master-output4
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  6 15:40 central-rrd-master.queue.central-rrd-master-output40
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  7 00:34 central-rrd-master.queue.central-rrd-master-output41
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  7 09:14 central-rrd-master.queue.central-rrd-master-output42
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  7 17:39 central-rrd-master.queue.central-rrd-master-output43
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  8 02:22 central-rrd-master.queue.central-rrd-master-output44
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  8 11:07 central-rrd-master.queue.central-rrd-master-output45
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  8 20:03 central-rrd-master.queue.central-rrd-master-output46
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  9 04:41 central-rrd-master.queue.central-rrd-master-output47
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  9 13:18 central-rrd-master.queue.central-rrd-master-output48
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun  9 21:44 central-rrd-master.queue.central-rrd-master-output49
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 24 07:09 central-rrd-master.queue.central-rrd-master-output5
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:15 central-rrd-master.queue.central-rrd-master-output50
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:15 central-rrd-master.queue.central-rrd-master-output51
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:16 central-rrd-master.queue.central-rrd-master-output52
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:16 central-rrd-master.queue.central-rrd-master-output53
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:16 central-rrd-master.queue.central-rrd-master-output54
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:17 central-rrd-master.queue.central-rrd-master-output55
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:21 central-rrd-master.queue.central-rrd-master-output56
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 17:43 central-rrd-master.queue.central-rrd-master-output57
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 12 22:59 central-rrd-master.queue.central-rrd-master-output58
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 13 07:47 central-rrd-master.queue.central-rrd-master-output59
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 24 15:27 central-rrd-master.queue.central-rrd-master-output6
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 13 15:52 central-rrd-master.queue.central-rrd-master-output60
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 14 00:43 central-rrd-master.queue.central-rrd-master-output61
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 14 09:36 central-rrd-master.queue.central-rrd-master-output62
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 14 18:01 central-rrd-master.queue.central-rrd-master-output63
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 15 03:05 central-rrd-master.queue.central-rrd-master-output64
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 15 11:52 central-rrd-master.queue.central-rrd-master-output65
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:28 central-rrd-master.queue.central-rrd-master-output66
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:31 central-rrd-master.queue.central-rrd-master-output67
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:31 central-rrd-master.queue.central-rrd-master-output68
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:31 central-rrd-master.queue.central-rrd-master-output69
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 25 01:29 central-rrd-master.queue.central-rrd-master-output7
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:32 central-rrd-master.queue.central-rrd-master-output70
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:32 central-rrd-master.queue.central-rrd-master-output71
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:32 central-rrd-master.queue.central-rrd-master-output72
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:33 central-rrd-master.queue.central-rrd-master-output73
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:33 central-rrd-master.queue.central-rrd-master-output74
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:33 central-rrd-master.queue.central-rrd-master-output75
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 14:40 central-rrd-master.queue.central-rrd-master-output76
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 19 18:11 central-rrd-master.queue.central-rrd-master-output77
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 20 03:10 central-rrd-master.queue.central-rrd-master-output78
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 20 11:59 central-rrd-master.queue.central-rrd-master-output79
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 25 10:15 central-rrd-master.queue.central-rrd-master-output8
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 20 19:54 central-rrd-master.queue.central-rrd-master-output80
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 21 04:47 central-rrd-master.queue.central-rrd-master-output81
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 21 13:17 central-rrd-master.queue.central-rrd-master-output82
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 21 22:01 central-rrd-master.queue.central-rrd-master-output83
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 06:53 central-rrd-master.queue.central-rrd-master-output84
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 22 15:44 central-rrd-master.queue.central-rrd-master-output85
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 23 10:09 central-rrd-master.queue.central-rrd-master-output86
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 23 10:13 central-rrd-master.queue.central-rrd-master-output87
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 23 18:43 central-rrd-master.queue.central-rrd-master-output88
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 24 03:36 central-rrd-master.queue.central-rrd-master-output89
-rw-rw-r--.  1 centreon-broker centreon-broker  96M May 25 18:57 central-rrd-master.queue.central-rrd-master-output9
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 24 12:27 central-rrd-master.queue.central-rrd-master-output90
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 24 21:13 central-rrd-master.queue.central-rrd-master-output91
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 25 06:13 central-rrd-master.queue.central-rrd-master-output92
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 25 15:00 central-rrd-master.queue.central-rrd-master-output93
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 25 23:48 central-rrd-master.queue.central-rrd-master-output94
-rw-rw-r--.  1 centreon-broker centreon-broker  96M Jun 26 08:38 central-rrd-master.queue.central-rrd-master-output95
-rw-rw-r--.  1 centreon-broker centreon-broker  29M Jun 26 11:06 central-rrd-master.queue.central-rrd-master-output96

**Describe the results you expected:**
Normaly one or more files but so many files? Is that normal?

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by jben94** [comment]
Hi @tmaff ,

It is not normal !

Are your charts up to date?
You use rrdcached?
Do not you have disk access (I/O) problems?

**Comment by tmaff** [comment]
Hi @jben94 

> Are your charts up to date?
What you mean with "Are your charts up to date?" I use the default settings of the plugins .. :)

> You use rrdcached?
Yes/no it is installed but not configured (Administration >Parameters > RRDTool => Enable RRDCached = no). Is this an important function?

>  Do not you have disk access (I/O) problems?
No the I/O are ok, the server is on an good status.

**Comment by jben94** [comment]
Hi,

Your graphs are up to date?
Do your graphs have curves drawn on them?
Have your RRD files been modified less than a few minutes ago?

**Comment by tmaff** [comment]
Hm no. I checked now and i see last datas are from 22.05.2017 :S

>  Have your RRD files been modified less than a few minutes ago?
Yes:
-rw-rw-r--. 1 centreon-broker centreon-broker 72577024 Jul  3 17:00 central-rrd-master.queue.central-rrd-master-output115

**Comment by jben94** [comment]
Hi,

RRD files are not the files you are talking about.
They must end with ".rrd" and are in the directory: "/var/lib/centeron/metrics"

What do logs say?

/var/log/centreon-broker/central-rrd-master.log
or
/var/log/centreon-broker/central-broker-master.log

For me, you have a graph problem.
Example of functional graph:

![image](https://user-images.githubusercontent.com/16583698/27819041-b19f829a-6098-11e7-8d13-40ed88480267.png)

Do yours work ?

**Comment by tmaff** [comment]
Hi,
okay the most files are from the 22.05.2017:
-rw-rw-r--. 1 centreon centreon  450088 May 10 13:03 4483.rrd
-rw-rw-r--. 1 centreon centreon  450088 May 10 13:02 4484.rrd
-rw-rw-r--. 1 centreon centreon  450088 May 22 09:30 4485.rrd
-rw-rw-r--. 1 centreon centreon  450088 May 22 09:32 4486.rrd
-rw-rw-r--. 1 centreon centreon  450088 May 22 09:30 4487.rrd
-rw-rw-r--. 1 centreon centreon  450088 May 22 09:30 4488.rrd

[root@centreon metrics]# ls -lah 1704.rrd
-rw-rw-r--. 1 centreon centreon 368K Jul  4 09:46 1704.rrd

The "/var/log/centreon-broker/central-rrd-master.log" log says:
[root@centreon metrics]# tail /var/log/centreon-broker/central-rrd-master.log
[1499153338] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153398] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153458] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153518] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153578] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153638] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153698] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153758] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153818] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
[1499153878] error:   RRD: failed to update value in file '/var/lib/centreon/metrics/1704.rrd': '/var/lib/centreon/metrics/1704.rrd' is too small (should be 450088 bytes)
Hmm ..?

The " /var/log/centreon-broker/central-broker-master.log" Logs says:
[root@centreon metrics]# tail  /var/log/centreon-broker/central-broker-master.log
[1498547338] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1498547338] config:  applier: 11 modules loaded
[1498815058] config:  main: configuration update requested
[1498815058] config:  log applier: applying 1 logging objects
[1498815058] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1498815058] config:  applier: 11 modules loaded
[1498834858] config:  main: configuration update requested
[1498834858] config:  log applier: applying 1 logging objects
[1498834858] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'

The last working graph is from 22.05.17 :S Hm yes but only to 22.05. A new check with an new graph is complete empty. Strange. Any idea?

**Comment by jben94** [comment]
Hi,

You have a problem with the RRD file "1704.rrd", it was badly created.
It is not the right size.

Deletes it and it will be recreated automatically.

**Comment by tmaff** [comment]
@jben94 that was the solution. Many thanks!!

**Comment by marsuboss** [comment]
Hello, 

I have too many files :

-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:33 central-broker-master.queue.centreon-broker-master-rrd
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:34 central-broker-master.queue.centreon-broker-master-rrd1
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:44 central-broker-master.queue.centreon-broker-master-rrd10
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:45 central-broker-master.queue.centreon-broker-master-rrd11
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:46 central-broker-master.queue.centreon-broker-master-rrd12
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:47 central-broker-master.queue.centreon-broker-master-rrd13
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:48 central-broker-master.queue.centreon-broker-master-rrd14
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:49 central-broker-master.queue.centreon-broker-master-rrd15
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:50 central-broker-master.queue.centreon-broker-master-rrd16
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:51 central-broker-master.queue.centreon-broker-master-rrd17
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:52 central-broker-master.queue.centreon-broker-master-rrd18
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:53 central-broker-master.queue.centreon-broker-master-rrd19
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:35 central-broker-master.queue.centreon-broker-master-rrd2
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:53 central-broker-master.queue.centreon-broker-master-rrd20
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:54 central-broker-master.queue.centreon-broker-master-rrd21
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:56 central-broker-master.queue.centreon-broker-master-rrd22
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:56 central-broker-master.queue.centreon-broker-master-rrd23
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:57 central-broker-master.queue.centreon-broker-master-rrd24
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:58 central-broker-master.queue.centreon-broker-master-rrd25
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:59 central-broker-master.queue.centreon-broker-master-rrd26
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:00 central-broker-master.queue.centreon-broker-master-rrd27
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:01 central-broker-master.queue.centreon-broker-master-rrd28
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:02 central-broker-master.queue.centreon-broker-master-rrd29
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:36 central-broker-master.queue.centreon-broker-master-rrd3
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:03 central-broker-master.queue.centreon-broker-master-rrd30
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:04 central-broker-master.queue.centreon-broker-master-rrd31
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:05 central-broker-master.queue.centreon-broker-master-rrd32
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:05 central-broker-master.queue.centreon-broker-master-rrd33
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:06 central-broker-master.queue.centreon-broker-master-rrd34
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:07 central-broker-master.queue.centreon-broker-master-rrd35
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  08:08 central-broker-master.queue.centreon-broker-master-rrd36
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  10:50 central-broker-master.queue.centreon-broker-master-rrd37
-rw-rw-r--   1 centreon-broker centreon-broker  22M 24 oct.  11:54 central-broker-master.queue.centreon-broker-master-rrd38
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:38 central-broker-master.queue.centreon-broker-master-rrd4
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:39 central-broker-master.queue.centreon-broker-master-rrd5
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:40 central-broker-master.queue.centreon-broker-master-rrd6
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:41 central-broker-master.queue.centreon-broker-master-rrd7
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:42 central-broker-master.queue.centreon-broker-master-rrd8
-rw-rw-r--   1 centreon-broker centreon-broker  96M 24 oct.  07:43 central-broker-master.queue.centreon-broker-master-rrd9


But i verify log and no error. Any idea?

**Comment by jben94** [comment]
Hi,

To have logs, you have to activate them here. 

![image](https://user-images.githubusercontent.com/16583698/31990035-34d7274c-b974-11e7-952f-259b10d073f1.png)

is it good for you?
