### ISSUE TITLE
[2.8.9] - Many messages in logs "*-master.log", overflow

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon#5385]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: OracleLinux 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Some services were configured as "Services by host group". In order to configure the dependencies, these services were added to the host templates as "Linked Service Templates"
2. Saving and updating the configuration
3. With the dependencies configured, the configuration was not updated. Removing the customized dependencies for services allowed the configuration to be saved.

**Describe the results you received:**
1. Overflow of the following logs with duplicate messages:

central-broker-master.log :
```
[1498574347] debug:   compression: 0xd9b330 uncompressed 39 bytes to 28 bytes
[1498574347] debug:   BBDO: got new header with a size of 12, source of 1, destination of 0 and an ID of 196613
[1498574347] debug:   BBDO: unserialized 28 bytes for event of type 196613
```

central-module-master.log :
`[1498574346] info:    callbacks: generating log event`

central-rrd-master.log :
`[1498574347] debug:   BBDO: got new header with a size of 12, source of 1, destination of 0 and an ID of 196613`
2. Data for graphs is not updated

**Describe the results you expected:**
1. Graphics are updated
2. Logs do not overflow

**Additional information you think important (e.g. issue happens only occasionally):**
central-broker-master-perfdata - Output
State CONNECTING
Statussleeping before reconnection
Last connection attempt2017-06-27 18:47:21
Event processing speed 0.00 events/s
Queued events 100001
Input accepted events type all
Output accepted events type all

**Comment by maksimatveev** [comment]
I had to stop the server otherwise the logs would occupy all the free space

**Comment by lpinsivy** [comment]
HI,

I suppose ou enable debug mod for Centreon Broker.

Can you disable debug, generate, export configuration and restart "cbd" service ?

**Comment by maksimatveev** [comment]
@lpinsivy Hello. It does not matter, I had to reinstall the program and restore everything from the backup copies =(
