### ISSUE TITLE
Config generation is too long

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#5388]
Config generation is too long cause timezone inheritance

@jben94 sent a PR : #5383 

But we need to use centengine parameter "use_timezone" to mange default timezone

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Steps to reproduce the issue:**
1. Add lot of inheritance between host/host templates
2. Generate configuration

**Describe the results you received:**
It takes too long time

**Describe the results you expected:**
Increase performance

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by jben94** [comment]
Hi,

It is true, I have just corrected my modifications and take into account the inheritance between host / host templates

https://github.com/jben94/centreon/tree/Genconfig_optimization
https://github.com/centreon/centreon/compare/master...jben94:Genconfig_optimization

**Comment by thiuyendang** [comment]
In 2.8.9, for 348 hosts  (with host template inheritance) and 3046 services -> 435 s
In 2.8.10-3 for same hosts and services -> 262 s
We saved 173 s, about 39.78%

**Comment by garnier-quentin** [comment]
performance is still poor. Should be faster. Could you test with centreon 2.7.x also ?

**Comment by jben94** [comment]
Hi,

With my changes and with host template inheritance
https://github.com/centreon/centreon/compare/master...jben94:Genconfig_optimization

Hosts : 3902 - Services : 32 033

real    0m50.440s
user    0m22.545s
sys     0m2.500s
