### ISSUE TITLE
new option for graph stacking

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#54]
---

Author Name: **Emylou Mavic** (Emylou Mavic)
Original Redmine Issue: 4316, https://forge.centreon.com/issues/4316
Original Date: 2013-03-18

---

Hi, 

In graphic stacking, a new suggestion would be to be able to define which metric is the referentiel for staking the other. 

Like if there is 5 metrics, being able to stack 3 together, and 2 together on the same graph. 

Is it clear enough ? Please let me know.

Do you think it is feasible ? 

Best regards,

**Comment by ganoze** [comment]
We do not want to invest development time on graphs. Also stacking is not widely used so we will not implement it any time soon.
