### ISSUE TITLE
Contacts/contactgroups inheritance

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#5400]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: CentOS7

**Steps to reproduce the issue:**
1. Create an host linked with a contacgroup
2. Create a service template linked to a contactgroup
3. Create a service which inherits previous service template

**Describe the results you received:**
Host contactgroup is notified

**Describe the results you expected:**
Host contact is not notified because service template contactgroup overrides it

**Comment by thiuyendang** [comment]
Checked on Centreon Web 2.8.10-3 (branch 2.8.10)
Created a host linked to contact group 1 including user 1
Created a service template linked to contact group 2 including user 2
Create a service using the service template

User 1 is notified (contact linked to host), User 2 (contact linked to service template) is not notified.

**Comment by lpinsivy** [comment]
I have a different way:
Host have contact_a and group_contact_a linked
Service inherit from STPL1
STPL1 have contact_b and group_contact_b linked
STPL1 inherit from STPL2
STPL2 have contact_c and group_contact_c linked

In details page of my service I have:

- contact_b & contact_c
- contact_group_b & contact_contact_group_c

But options additive inheritance are not set and generated CFG seems correct !

centreon-engine-1.7.3-1.el7.centos.x86_64

**Comment by ganoze** [comment]
@lpinsivy As seen together, the notified contacts and groups of the details page is computed by Centreon Web, and therefore does not guarantee how Centreon Engine will react.

@thiuyendang With your exact scenario I was not able to reproduce your notification issue. With your test case only User 2 is getting notified when service state changes. Do you have more information on your scenario ?

**Comment by thiuyendang** [comment]
I had an issue with the email address for user 2.
Several test cases:
- Downtime on host + service : mail is sent to user 1 and user 2 at downtime start time and end time
- Downtime on host : user 1 is notified
- Downtime on service: user 2 is notified
- Status change on host : only user 1 is notified
- Status change on service: only user2 is notified
All test cases passed.
