### ISSUE TITLE
Monitoring Services by Hostgroup : improvement order suggestion

### ISSUE THREAD

**Issue by Tithib** [centreon/centreon#5402]
In monitoring tab, "Services by Hostgroup" is usefull, but it would be greater if services were ordered when they have the same status. 
So, in the file /www/include/monitoring/status/ServicesHostGroups/xml/serviceGridByHGXML.php
I suggest to remplace on _line 181_ :
`    $rq1 .= " order by tri asc";`
with
`    $rq1 .= " order by tri asc, s.description asc";`

It's a tiny modification, but all the services are ordered and if you have, as I have, lots of similar hosts with same services, it's very easier to read and find differences between hosts.

Thanks for your great tool.

**Comment by thiuyendang** [comment]
OK 2.8.12-4, centOS6, centOS7
