### ISSUE TITLE
Directory "Var/spool/centreon" not created by Centreon-common.rpm

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5405]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CentOS7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a VM to install a remote poller
2. Follow documentation to configure poller on the central server
3. Check the SSH keys exchange step of the process

**Describe the results you received:**
Error message "could not chdir to home directory /var/spool/centreon : no such file or directory
Effectively, the directory centreon is absent on the poller VM.

**Describe the results you expected:**
The directory has to be automatically created.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Tetsumaki** [comment]
Hi, same problem here on central and poller server.

**Comment by ganoze** [comment]
The installation procedure within the documentation was not up to date. It is necessary to disable SELinux *before* installing packages. Could you retry with the reworked documentation page https://documentation.centreon.com/docs/centreon/en/2.8.x/installation/from_packages.html ?

**Comment by thiuyendang** [comment]
Checked with centOS7 and CentOS6.
If I set "disabled" to selinux before installing packages then all directories are properly created.
