### ISSUE TITLE
[BUG] Poller/Hang or Stuck making all Host/Service Unknow after some time. 

### ISSUE THREAD

**Issue by ankitsnlq** [centreon/centreon#5407]
**BUG REPORT INFORMATION**

Centreon Web version: 2.8.9

Centreon Engine version: 1.7.2

Centreon Broker version: 3.0.7

OS: Red Hat Enterprise Linux Server release 7.3 (Maipo)

Additional environment details: Rackspace VM/Vmware Hypervisor.

This is fresh Centreon Installation on Redhat 7 with only 2 hosts getting monitored. I have only 30 services/2 Host in this Centreon. After setting and adding new Host everything worked fine with all checks ran correctly and output was showing in Centreon web. But after few minute around 5 to 10 min, both host and 30 services went into the Unkown state. 

To resolve I have to restart Centreon engine and it will run checks again and everything will be fine for some more time and again the same issue. Or I can leave it in unknown state and Centreon will rerun checks and everything will be fine again. It is happening again and again. 

I don't have changed any Poller/Engine/Broker config all running on default config which comes with the default installation. 

> Screenshots. 
> URL: https://i.imgur.com/gDJPMl4.png ( Here all thing running fine) After few minute check next image. 
> URL: https://i.imgur.com/WdrZqgz.png (Host/Service all in the Unknown state). 

Update : 
When it happens Before some time all check not running on their schedule time. So last check status for service shows 1hrs or 2 hrs instead of 5 minutes or less. 
Force Check Also don't work during this period.

Thank You,
Arun Singh

**Comment by Sims24** [comment]
Hi,

Do you have only a central server or also a poller ? 

Please give us result of following commands : 

`grep timeout /etc/centreon-broker/*xml `

Thanks

**Comment by ankitsnlq** [comment]
Hi Sims24,

Thank you for response. 

Poller/Centreon everything is on the same server. 

The output from the command you provided. 

```

/etc/centreon-broker/central-broker.xml:  <buffering_timeout><![CDATA[0]]></buffering_timeout>
/etc/centreon-broker/central-broker.xml:  <buffering_timeout><![CDATA[0]]></buffering_timeout>
/etc/centreon-broker/central-broker.xml:  <buffering_timeout><![CDATA[0]]></buffering_timeout>
/etc/centreon-broker/central-broker.xml:  <buffering_timeout><![CDATA[0]]></buffering_timeout>
/etc/centreon-broker/central-module.xml:  <buffering_timeout><![CDATA[0]]></buffering_timeout>
/etc/centreon-broker/central-rrd.xml:  <buffering_timeout><![CDATA[0]]></buffering_timeout>
/etc/centreon-broker/central-rrd.xml:  <buffering_timeout><![CDATA[0]]></buffering_timeout>
```
Thank You,
Arun Singh

**Comment by Sims24** [comment]
Do you have any error in your log files (poller-module.log or central-broker-master.log)

**Comment by ankitsnlq** [comment]
Only the service errors nothing else.

**Comment by lpinsivy** [comment]
Did you update to Centreon Broker 3.0.8?

Problem persist?
