### ISSUE TITLE
[Documentation] Partitioning : French documentation is wrong, english is ok

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#5408]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8 (Online doc)

**Steps to reproduce the issue:**
1. Go to https://documentation-fr.centreon.com/docs/centreon/en/2.8.x/administration_guide/partitioning/index.html#partitionnement-des-bases-de-donnees
2. Try to perform partitioning following example for data_bin behind link at the bottom of the page

**Describe the results you received:**
Error message on partitioning (cannot find config file with strange concatenation)

**Describe the results you expected:**
Updated documentation and success with partitionning command

**Additional information you think important (e.g. issue happens only occasionally):**
Should stick to english version which works ;)  

Thanks!

**Comment by lpinsivy** [comment]
So replace:

# php /usr/share/centreon-partitioning/bin/centreon-partitioning.php -m /etc/centreon/centreon-partitioning/partitioning-data_bin.xml

by

# php /usr/share/centreon/bin/centreon-partitioning.php -m data_bin

?

**Comment by Sims24** [comment]
Yes, maybe also specify retention management between version, because from what I understand we do not use xml files anymore to define number of partition right ? 

Thanks

**Comment by cgagnaire** [comment]
There is 3 new fields that are not so self-explanatory :)
![image](https://user-images.githubusercontent.com/23257354/28074562-3170ec8c-6659-11e7-8e90-ec26868cddd9.png)

**Comment by lpinsivy** [comment]
done in 18.10.x and 19.04.x documentation
