### ISSUE TITLE
Wizard for Broker configuration create an useless and wrong Engine configuration record

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5409]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CentOS7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install a remote poller
2. Configure the remote poller
3. Use the wizard to add the broker configuration for the remote poller

**Describe the results you received:**
One engine configuration record for the remote poller is created when using the wizard while it has already been created when we have duplicated Poller configuration.
Otherwise, the externalcmd.so line is missing in Data tab.

**Describe the results you expected:**
The new engine conf is not useful in this case.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Done with new wizard of Centreon 18.10.0
