### ISSUE TITLE
Saved parameters are not applied

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5410]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.9
**OS**: CentOS 6

**Steps to reproduce the issue:**
1. Edit "Administration > Parameters > Centreon UI > Problem display properties"
2. "Sort problems by :" Duration 
3. "Order sort problems :" Descending
4. Go to the page "Monitoring - Status Details - Services"

**Describe the results you received:**
Services are not sorted. It is necessary to modify a filter for the change to be applied

**Describe the results you expected:**
On first loading of the page, filters should be applied

Regards

**Comment by lpinsivy** [comment]
Linked to #5287 ?

**Comment by thiuyendang** [comment]
Please refer to #5287
