### ISSUE TITLE
Web browser unable to display Centreon Web page Notification > Escalation when we want to select all services

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5414]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Configuration > Notifications > Escalations
2. Add or modify an escalation
3. In Impacted Resources tab, click on "select all" button for Services by host part.

**Describe the results you received:**
Google Chrome displays an error message, saying it cannot display the page because of memory.

**Describe the results you expected:**
All services have to be added in the fiel Services by host

**Additional information you think important (e.g. issue happens only occasionally):**
With 385 services, it works but not for 1300 services. The issue is probably related to number of services to select.

**Comment by lpinsivy** [comment]
Hi,

The best way is to create a group of services because it is more easily than to manage than 1300 objects in escalation.

Regards,
