### ISSUE TITLE
PHP END OF LIFE // Documentation

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon#5423]
Hi,

the documentation says that in need PHP Version ">= 5.3.0 & < 5.5". In the release notes somewhere 2.6... i read, that 5.3 is not working anymore. The documentation needs to be fixed. 

Also i want to inform you, that PHP 5.4.X hit the end of life.  See http://php.net/supported-versions.php

Do you guys have a plan for supporting PHP 7.X?

**Comment by lpinsivy** [comment]
Hi,

Yes we are working on PHP 7 support (use PDO, remove obsolete code, may be upgrade to smarty 3, etc.).
