### ISSUE TITLE
[2.8.9] Adding host template with massive change behavior

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#5426]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.0.8

**Steps to reproduce the issue:**
1. Have multiple hosts with multiple host templates,
2. Select those hosts and do a 'Massive Change',
3. Add a new template with 'Incremental mode'.

**Describe the results you received:**
The new template freshly added is in second position

**Describe the results you expected:**
The new template freshly added should be in last position, as "position matter"

**Comment by lpinsivy** [comment]
@cgagnaire seems to be work on Centreon Web 2.8.12, can you confirm?

**Comment by cgagnaire** [comment]
I still have this behavior on 2.8.13 and 2.8.16.
