### ISSUE TITLE
Poller Reload in browser not working after update

### ISSUE THREAD

**Issue by Isagr** [centreon/centreon#5436]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.8
**OS**:
Centos6

**Steps to reproduce the issue:**
1. Upgrade Centreon 2.7.x to 2.8.9
2. After upgrade , export configuration of the poller don't do anything.
3. Connect by ssh to the poller, do "service centengine restart", Configuration is taken into account. 

**Describe the results you received:**
The poller don't update it's configuration using the web interface.
Checking /var/log/centreon-engine/centengine.log shows that nothing happens.
Do "service centengine restart" in command line and configuration is taken into account. 

**Describe the results you expected:**
I should be able to reload configuration using the web interface.

**Additional information you think important (e.g. issue happens only occasionally):**
Reloading the configuration of Central is working well.

**Comment by vurmil** [comment]
I have the same problem after updating from 2.7.8 to 2.7.9 - CES

**Comment by lpinsivy** [comment]
Hi,

Do you have error in /var/log/centreon/centcore.log when you restart/reload poller using the Centreon web interface?

**Comment by Isagr** [comment]
Hi,

Yes, I have the message :
``sudo: no tty present and no askpass program specified``

**Comment by lpinsivy** [comment]
Problem with Centreon sudoers file.

I suppose it had been correct in RPM spec for latest version of Centreon.
