### ISSUE TITLE
"View notifications" doesn't work

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#5441]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Steps to reproduce the issue:**
1. Configure contacts for notifications only on hosts and host templates
2. Do not add contact or contact group on service and its service template

**Describe the results you received:**
When i go to "Configuration --> Users --> View notifications", I only see the notifications for my host and not for my service.
![view_notif](https://user-images.githubusercontent.com/11076322/28158950-b3045532-67bb-11e7-9a47-c56b83366ff8.JPG)
I don't see the notification for my service in this page but I have notification for this service. The proof:
![logs-notif](https://user-images.githubusercontent.com/11076322/28158995-cec6b080-67bb-11e7-995f-0d64c93b26fd.jpg)

**Describe the results you expected:**
See notification for service in "View notifications" even if i configure contacts and contact groups on my host

**Comment by lpinsivy** [comment]
Hi,

If you enable notification for services without contacts or contactgroups, Centreon Engine will inherits contacts and contactgroups from host definition.

Regards,

**Comment by s-duret** [comment]
Hi,

I know it but whatever I configure contact on my host or on my service, I should see the service in page "Configuration --> Users --> View notifications".
Am i wrong?

Regards

**Comment by lpinsivy** [comment]
Linked to #4981
