### ISSUE TITLE
Performance statistics not received anymore

### ISSUE THREAD

**Issue by bdeschut** [centreon/centreon#5443]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.9
**Centreon Engine version**: 1.7.2
**Centreon Broker version**: 3.0.8
**OS**: Centreon Enterprise Server / CentOS release 6.9 (Final)
212 hosts, ~4000 services

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual central server, physical pollers

**Steps to reproduce the issue:**
Not sure, issue started happening after a disconnected poller (~3 hours) came back online
According to Configuration > pollers, all pollers are online, but Last Update is the time the disconnected poller came back up.
In the Monitoring > status details, host / service checks have "Last Check" multiple hours ago (again, time the poller connected)

**Describe the results you received:**
Mail alerts are still working, the pollers are still polling. I hope they are storing their performance data in the failover files.

**Describe the results you expected:**
It would have been nice that the central node still received the performance data from the remote pollers.

**Additional information you think important (e.g. issue happens only occasionally):**
I have verified connectivity between the pollers and the central node, connections on port tcp/5669 are ok. Time between central and pollers is synched. Configuration wise, nothing relevant was changed today (did make some changes in the last weeks on poller / engine / broker level - for example, adding failover files to the broker configs, apply best practices as described by the documentation for both engine and broker).

On the central server, the central-broker-master.log file is full of messages like:
“[1499957123] error:   SQL: could not store service group membership (poller: 5, host: 83, service: 221, group: 1): could not execute prepared statement: Duplicate entry '83-221-1' for key 'host_id' QMYSQL3: Unable to execute statement”

-> poller 5 is the poller which came back online after being disconnected today

Please advise

PS: we are in the process of buying a maintenance license, but centreon sales pointed us here for now.

**Comment by bdeschut** [comment]
Update: we have fixed the problem

Execute the following on central and all pollers:
(command 1 on central and pollers, command 2 on central and all pollers, ...)
service centengine stop; service cbd stop
mkdir /var/lib/centreon-broker/old1
mv /var/lib/centreon-broker/* /var/lib/centreon-broker/old1
rm -f /var/log/centreon-engine/retention.dat
service cbd start; service centengine start

Still not sure what the problem was though

Consequences:
Needed to do a scheduled immediate check - forced for all hosts and services
All ack's and downtimes are gone

Feel free to close this issue, but if you want to investigate further (bug?), you can always contact me.

Regards,
Bob

**Comment by lpinsivy** [comment]
Sorry for the delay of answer and thank you for your feedback.

**Comment by piozylka** [comment]
> Update: we have fixed the problem
> 
> Execute the following on central and all pollers:
> (command 1 on central and pollers, command 2 on central and all pollers, ...)
> service centengine stop; service cbd stop
> mkdir /var/lib/centreon-broker/old1
> mv /var/lib/centreon-broker/* /var/lib/centreon-broker/old1
> rm -f /var/log/centreon-engine/retention.dat
> service cbd start; service centengine start
> 
> Still not sure what the problem was though
> 
> Consequences:
> Needed to do a scheduled immediate check - forced for all hosts and services
> All ack's and downtimes are gone
> 
> Feel free to close this issue, but if you want to investigate further (bug?), you can always contact me.
> 
> Regards,
> Bob

Thx for this solution, I have been dealing with this problem for a week. Finally all works as supposed to.
Good job
