### ISSUE TITLE
notification hors jours férier

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5444]
[EN]
Hello,
I think this feature does not exist automatically,
I would like to be able to add a holiday option in the notification,
Ie to avoid receiving notifications on a Friday for example,
A fully automatic process, because if I understand correctly, for the time being, I have to inform myself by hand on public holidays, a long-term risk.
Thanks for your feedback.
[EN]

[FR]
Bonjour,
je pense que cette fonctionnalité n'existe pas automatiquement,
je souhaiterais pouvoir ajouter une option jours férié dans la notification, 
c'est à dire d'éviter de recevoir des notifications un vendredi férier par exemple,
un process complètement automatique, car si je comprend bien, pour le moment, je dois moi même renseigner à la main les jours fériés, un risque sur le long terme.
Merci pour votre retour.
[FR]

ma version actuelle :
Centreon 2.8.9
Centreon Engine 1.7.2
MariaDB 5.5.53

**Comment by lpinsivy** [comment]
Hi,

It is possible to do this with exception in a timeperiod.

For example:
january 1		00:00-24:00	; New Year's Day
2008-03-23		00:00-24:00	; Easter (2008)
2009-04-12		00:00-24:00	; Easter (2009)
monday -1 may		00:00-24:00	; Memorial Day (Last Monday in May)
july 4			00:00-24:00	; Independence Day
monday 1 september	00:00-24:00	; Labor Day (1st Monday in September)
thursday 4 november	00:00-24:00	; Thanksgiving (4th Thursday in November)
december 25		00:00-24:00	; Christmas
december 31		17:00-24:00	; New Year's Eve (5pm onwards)

**Comment by fredo1988** [comment]
Hi,

thanks, but it's not automatics for all date.

**Comment by lpinsivy** [comment]
Yes but it is impossible to manage this without external application.
