### ISSUE TITLE
Multiple checkbox with the same name

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5446]
BUG REPORT INFORMATION

Centreon Web version: 2.8.8

Steps to reproduce the issue:
I use the massive change options on several hosts

Describe the results you received:
On the notification tab, 5 check box have the same name: 'update mode'

Describe the results you expected:
Change this name to make it more explicit

Additional information:
There is the same problem on the relation tab.

**Comment by cgagnaire** [comment]
Related to https://github.com/centreon/centreon/issues/5266

**Comment by lpinsivy** [comment]
Yes I close this one and keep original one.
