### ISSUE TITLE
AutoDiscovery - Exclusion Hosts

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon#5448]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: Centos

Hello,

I use the Auto Discovery Module, I have a problem about the discovery of disks on many hosts.
I use the Windows-SNMP template to target the hosts, but in my Windows Servers, I have a few hosts used to make saves, and during the night there are many mounted disks. But I don't want this disks because it's temporary
How do to exclude a group hosts in a Rule? If it's not possible, Is it possible to improve this function?

Thanks.

**Comment by lpinsivy** [comment]
You can use exclusion/inclusion based on $name$ in your rules definition

**Comment by benoitb21** [comment]
No, I can't used an exclusion $name$ because I can't specify a name of disk. Just filtered many hosts in a global template.
In my Windows servers, I have many proxy VEEAM hosts which mount many disks during the save. So it is the reason that I want exclude this hosts group.

**Comment by lpinsivy** [comment]
Move to auto Disco project (hidden)
