### ISSUE TITLE
EventLog - need event duration

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#545]
---

Author Name: **Guillaume Watteeux** (Guillaume Watteeux)
Original Redmine Issue: 2233, https://forge.centreon.com/issues/2233
Original Date: 2011-03-25

---

Bonjour,

lorsque l'on affiche le journal d’évènement pour un service, nous avons les informations suivantes:
Jour, heures, Hôte/Service, Statu, Type, R, Statut détaillé, contact, Commande

Dans l'interface nagios cette fois-ci:
Event start time, event end time, event duration, event/state type, event/state information.
I
Les 3 premiers champs sont pour moi très important et permettent une meilleur compréhension du problème. Nous avons également l'information sous Centreon, mais moins claire, cela nécessite de faire des calculs de date.

Si c'est possible d'implémenter une meilleur visibilité de l'Evenlog pour ce cas ci :).

**Comment by julienmathis** [comment]
Ceci ne va pas etre possible dans les event log qui sont sans traitement. Mais nous gardons l'idée pour les système de corrélation à venir.
