### ISSUE TITLE
Truncate centreon_storage.services and centreon_storage.hosts

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#5450]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9
**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

Is it possible to truncate this tables whithout risk and restart all pollers after ?:
centreon_storage.services and centreon_storage.hosts

When I select all line on mysql,  I can see there are a lot of old entry with last_update column.

Thanks

**Comment by Sims24** [comment]
Truncate is not really the best solution. In the meantime you can close the entry looking at the flag "enabled" for example.
