### ISSUE TITLE
Added commands are not saved in Centreon-Web 

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5454]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10-3

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.0.8

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MariaDB  Server version : 10.2.7

**Steps to reproduce the issue:**
1. Add a command
2. Save

**Describe the results you received:**
The new command is not saved

**Describe the results you expected:**
The command is saved.

**Additional information you think important (e.g. issue happens only occasionally):**
Fresh Install CentOS6, from packages.
Related to id of the graph template.

**Comment by lpinsivy** [comment]
Works for me
