### ISSUE TITLE
[CLAPI] Duplicate CMD in export

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5455]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.9

**Steps to reproduce the issue:**
Run this command (same problem with export clapi in file) : 
`# centreon -u USER-p PASSWD -e | grep 'CMD;ADD' | sort | uniq -c | cut -c 1-100
`

**Describe the results you received:**
```   2 CMD;ADD;App-CentreonBroker-Retention-Local;2;$CENTREONPLUGINS$/centreon_centreon_central.pl
      2 CMD;ADD;App-Centreon-MySQL-Partitioning;2;$CENTREONPLUGINS$/centreon_centreon_database.pl --
      2 CMD;ADD;App-DB-MySQL;2;$CENTREONPLUGINS$/centreon_mysql.pl --plugin=database::mysql::plugin
      2 CMD;ADD;App-DB-MySQL-Database-Size;2;$CENTREONPLUGINS$/centreon_mysql.pl --plugin=database::
      2 CMD;ADD;App-DB-MySQL-Long-Queries;2;$CENTREONPLUGINS$/centreon_mysql.pl --plugin=database::m
      2 CMD;ADD;App-DB-MySQL-Qcache-Hitrate;2;$CENTREONPLUGINS$/centreon_mysql.pl --plugin=database:
      2 CMD;ADD;App-DB-Oracle;2;$CENTREONPLUGINS$/centreon_oracle.pl --plugin=database::oracle::plug
      2 CMD;ADD;App-DB-Oracle-ASM-Diskgroup-Usage-Generic-Name;2;$CENTREONPLUGINS$/centreon_oracle.p
```

**Describe the results you expected:**
CMD should be export only once.

Best Regards

**Comment by Sims24** [comment]
Hi @lpinsivy @bmareau,

Spotted this issue, will make a PR about it but it's really "dumb" :

We don't need parent::export($filters) in this cas www/class/centreon-clapi/centreonCommand.class.php. Remove it in export function around line 200 and you will avoid double export in full and filtered export. 

Thanks
