### ISSUE TITLE
Resources access cannot be removed from Admin  > ACL > Access groups (Authorized information tab)

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5456]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.08

**OS**: centOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a contact group linked to an ACL group
2. Create a resources access record and link it to the access group, save
3. Remove the resources access record in Authorizations information tab of Admin > ACL > Access Groups page, save
4. Edit the access group again

**Describe the results you received:**
The removed resources access record is not removed

**Describe the results you expected:**
The resources access record is removed

**Additional information you think important (e.g. issue happens only occasionally):**
The link between access group and resources access record can be broken in Admin > ACL > Resources access in General information tab

**Comment by lpinsivy** [comment]
It's working
