### ISSUE TITLE
Properly export interval length in *storage* endpoints

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon#5461]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CentOS 7

**Steps to reproduce the issue:**
1. Change _interval length_ in Administration -> Parameters -> Monitoring
2. Generate poller configuration

**Describe the results you received:**
The <interval> field of central-broker-master's _storage_ output is still set to 60 seconds.

**Describe the results you expected:**
The <interval> field of central-broker-master's _storage_ output should be set to the new value.

**Additional information you think important:**
@leoncx take a look and it concerns all global variables used by Centreon Broker.

**Comment by thiuyendang** [comment]
OK 2.8.13-1
