### ISSUE TITLE
API Token died after a time

### ISSUE THREAD

**Issue by lgcosta** [centreon/centreon#5463]
Hi,

I created a token for the API using the procedures listed in the documentation successfully, I can use the API normally, however, after some time I can not use the token anymore, and it is necessary to create a new token.

I did not find in the documentation anything to talk about this, session time, etc?

Is this a feature or a problem?

How could I ever have the same token? Without losing validity?

Centreon 2.8.9

Thanks

**Comment by lpinsivy** [comment]
Hi,

There is a limitation to 1h, after previous token are deleted from database.

Regards,
