### ISSUE TITLE
[2.8.8] Need some delay in filtering at Monitoring>Status Details>Services 

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon#5464]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.7

**OS**: Oracle Linux 7

**Additional environment details (AWS, VirtualBox, physical, etc.):** Virtual

**Steps to reproduce the issue:**
1. Go to this page: Monitoring>Status Details>Services 
2. When we try to filter for a service/host/output/..., it is starting the filter immediately and if we type a bad word and we fix it, the web page is loading a lot of time till we get the correct results.

**Describe the results you received:**
The filtering is too fast. 

**Describe the results you expected:**
 We would like some delay in filtering (5-6 sec)
1. Typing the filter words
2. Wait 5-6 sec
3. Start the filtering

**Comment by lpinsivy** [comment]
Hi,

Your feedback need to change the comportement of the search in the software.

I'll analyse it and try to find the best solution.

**Comment by lpinsivy** [comment]
Hi,

How many services and hosts do you have?
Can you update performance of your DBMS?

Regards,

**Comment by Tomszy** [comment]
We have 226000 services and 11438 hosts.
![image](https://user-images.githubusercontent.com/25457811/29559907-b1e003f6-8730-11e7-9767-7826212435af.png)

**Comment by lpinsivy** [comment]
Did you perform optimization on your MySQL server?

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
