### ISSUE TITLE
Unable to change the severity of a host template

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5472]
BUG REPORT INFORMATION

Centreon Web version: 2.8.10

Steps to reproduce the issue:
I create a host template and link it to a severity
I save the modifications.
I change the severity of the host template.
I save the modification.

Describe the results you received:
The severity has not changed

Describe the results you expected:
I should be able to change the severity of a host template.

**Comment by lpinsivy** [comment]
Linked to cfe4634094d8c7f3617953b1ca18b37064819ae3 but need to delete line "$parameters['externalObject']['object'] = 'centreonHostcategories';" from /usr/share/centreon/www/class/centreonHost.class.php

=> need to check all impacts

**Comment by thiuyendang** [comment]
OK 2.8.12-2, centOS6

**Comment by thiuyendang** [comment]
Tests en 2.8.12-4, centOS6 et 7.
OK
