### ISSUE TITLE
[2.8.10]  Centreon-Broker 3.0.8 : process 'central-broker-master' terminated unexpectedly

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon#5474]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.10
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.8
**OS**: 
CentOS 6.9
**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Upgrade of Centreon 2.8.9 to 2.8.10
2. Restart the Central Poller

**Describe the results you received:**
Here an part of the "/var/log/centreon-broker/watchdog.log" : 
![image](https://user-images.githubusercontent.com/29780310/28672092-0adcb2bc-72df-11e7-8733-fa4236cac29a.png)

I also capture some strange lines in the "/var/log/centreon-broker/central-broker-master.log"
![image](https://user-images.githubusercontent.com/29780310/28672275-981cc77a-72df-11e7-8e67-5acac7d00dc7.png)

It seems that the Centreon Broker continually crash and restart due to corrupt data.

**Describe the results you expected:**
The Centreon-Broker and the Central Poller should be running.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by ganoze** [comment]
Could you reproduce this issue while generating a debug file on central-broker-master ? This debug file can be configured in Configuration -> Pollers -> Broker configuration -> central-broker-master in the Logger tab. You will need to enable all logs (debug, info, config, error) to the most detailed verbosity and to enable thread ID logging.

This file will help me understand where the std::bad_alloc exception is coming from. I suspect the compression layer to be involved but I do not have any proof yet.

**Comment by Crash-Fox** [comment]
Here the 'central-broker-master.log' (I cut it a bit because the file weigh 635Mo) :
[central-broker-master-log.txt](https://github.com/centreon/centreon/files/1182429/central-broker-master-log.txt)

**Comment by ganoze** [comment]
Could you also send your /var/lib/centreon-broker//central-broker-master.queue.central-broker-master-sql1 file ?

The std::bad_alloc error can come from any of the following issue. Your file seems to contain interesting corrupted data.

  - not enough memory on the server
  - the process cannot allocate enough memory
  - the Qt uncompression function attempts to allocate too much memory because of the corrupted data
  - Broker badly handles the corrupted compression buffer
  - ...

**Comment by Crash-Fox** [comment]
The file 'central-broker-master.queue.central-broker-master-sql1 is too big for the file limitation (10MB). How can i send it to you via mail ?


'

**Comment by ganoze** [comment]
Could you upload it to some file sharing service like Dropbox ?

**Comment by Crash-Fox** [comment]
Here a zip file containing the 'central-broker-master.queue.central-broker-master-sql1' file :
[central-broker-master.queue.central-broker-master-sql1.txt.zip](https://github.com/centreon/centreon/files/1182624/central-broker-master.queue.central-broker-master-sql1.txt.zip)

**Comment by ganoze** [comment]
Thank you very much for this file ! The first thing _cbd_ noticed is that the file is corrupted. It might have been generated with a pre-3.0.8 version of Centreon Broker (in which case this should not happen again).

However with the file content I was able to succesfully profile _cbd_ memory consumption while uncompressing it.  On my machine with 4 GB RAM, _cbd_ allocated more than 2.1GB of memory. On a machine with fewer memory this explains the std::bad_alloc error. That much of memory is needed by the compression layer in an attempt to uncompress a corrupted data block. _cbd_ successfully detects that the block is corrupted if enough memory is available.

So as a consequence, the only thing I can adivse you is to remove all failing retention files.

**Comment by Crash-Fox** [comment]
Thank you for your informations. I have a last question where do i find these failing retention files ?

**Comment by ganoze** [comment]
These are all files that generate processing errors. In your case it currently is central-broker-master.queue.central-broker-master-sql1. Once deleted, processing should continue. However if a failure occurs again, please delete the next retention file (central-broker-master.queue.central-broker-master-sql**X** with X being the lowest possible number).

**Comment by Crash-Fox** [comment]
Okay thank you now it's working
