### ISSUE TITLE
sh: -v: command not found

### ISSUE THREAD

**Issue by 5145h** [centreon/centreon#5477]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.10-4.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.7.2-3.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-3.0.8-1.el7.centos.x86_64

**OS**: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Upgrade from 2.8.9 to 2.8.10
2. Trying to export config on pollers
3.

**Describe the results you received:**
sh: -v: command not found
see the attached file
**Describe the results you expected:**
The export to work as before the upgrade.

**Additional information you think important (e.g. issue happens only occasionally):**

![-v](https://user-images.githubusercontent.com/21243985/28706683-fd91c90e-737d-11e7-9a43-100424ccfb78.JPG)

**Comment by lpinsivy** [comment]
Did you modify your sudoers files?

Can you send us it?

**Comment by 5145h** [comment]
The issue is not present anymore after upgrading to 2.8.11.
