### ISSUE TITLE
Duplicate severity should remove link to objects

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5478]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Steps to reproduce the issue:**
1. Create a host severity
2. Link this severity to a host
3. Duplicate severity

**Describe the results you received:**

The duplicated severity is linked to host

**Describe the results you expected:**

The duplicate severity must not be linked to host

**Additional information you think important (e.g. issue happens only occasionally):**

A host can be linked only one time with a severity.

**Comment by thiuyendang** [comment]
OK 2.8.12-4 centOS6, centOS7.
Duplicated severity is not linked to host neither host template.
