### ISSUE TITLE
Possibility to generate graphs from outputs of multiple plugins

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#548]
---

Author Name: **martin hejna** (martin hejna)
Original Redmine Issue: 1316, https://forge.centreon.com/issues/1316
Original Date: 2009-11-08

---

Hi,
it's possible to extend meta services to check and generate graphs with multiple curves from different plugins ? For example combine several CPU load data on different machines into one graph and report Warning/Critical state if some of them are out of the predefined values. Today Average, Sum, Min and Max functions are available for calculation type and so one curve is generated.

Thank you

**Comment by lpinsivy** [comment]
duplicate of #3714
