### ISSUE TITLE
Macro $SERVICEOUTPUT$ not interpreted in "Action URL"

### ISSUE THREAD

**Issue by remilkoch** [centreon/centreon#5483]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 

**OS**: CentOS release 6.8 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare

**Steps to reproduce the issue:**
1. In "Extended Information" / "Action URL" of a service
2. use the macro $SERVICEOUTPUT$ in it
3. Save conf and check 

**Describe the results you received:** the link in monitoring don't interpret the macro

**Describe the results you expected:** $SERVICEOUTPUT$ should display the service output...

**Additional information you think important (e.g. issue happens only occasionally):** in action URL, others macros are well interpreted (i.e. $HOSTNAME$ or $SERVICEDESC$)

**Comment by remilkoch** [comment]
![centreon-serviceoutput](https://user-images.githubusercontent.com/30599944/28784918-21f01e88-7615-11e7-9c02-740fc919199c.jpg)

**Comment by lpinsivy** [comment]
Hi,

For hosts notes et actions url, only the following macros are translated:

- $HOSTNAME$
- $HOSTALIAS$
- $HOSTADDRESS$
- $INSTANCENAME$
- $HOSTSTATE$
- $HOSTSTATEID$
- $INSTANCEADDRESS$

For services notes et actions url, only the following macros are translated:

- $SERVICEDESC$
- $SERVICESTATEID$
- $SERVICESTATE$
- $HOSTNAME$
- $HOSTALIAS$
- $HOSTADDRESS$
- $INSTANCENAME$

To create tickets from Centreon, you can use [the Centreon Open Tickets module](https://documentation.centreon.com/docs/centreon-open-tickets/en/latest/)
