### ISSUE TITLE
[2.8.10] Cannot update proxy settings

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5490]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CES el6.x86_64

**Steps to reproduce the issue:**
1. Go to Administration  >  Parameters  >  Centreon UI
2. Try to erase Proxy user or Proxy password filled fields
3. Save

**Describe the results you received:**
Fields wont clear

**Additional information you think important:**
cant do it not even logged as admin with full permission to those settings

**Comment by lpinsivy** [comment]
Hi,

I can't reproduce on Centreon 2.8.11.

"Proxy user" and "Proxy password" are detected as credentials by browser. Maybe that is why when you save this form you save information previously store in your browser cache.

Regards

**Comment by kozfelipe** [comment]
@lpinsivy you are right!

It was an autofill form from chrome. Im sorry to bother.
