### ISSUE TITLE
[2.8.10] Reporting Dashboard messed up

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5491]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CES el6.x86_64

**Steps to reproduce the issue:**
1. Go to Reporting  >  Dashboard  >  Hosts
2. Select a report from any host using different user profiles

**Describe the results you received:**
 non-admin users receive some weird reports for any periods.
In my case:
admin gets normal state breakdowns 100% OK 0% Undetermined
operator users get 200%(100%) OK -100% Undetermined
read-only users get 300~400% (100%) OK -100% Undetermined

Here is a breakdown as admin:
![image](https://user-images.githubusercontent.com/25208457/28842621-be08fe7e-76d4-11e7-8879-af76fe6c1b75.png)

same host as non-admin user:
![image](https://user-images.githubusercontent.com/25208457/28842724-15b310c4-76d5-11e7-84bb-57ce727c3cf1.png)

same bug captured from https://demo.centreon.com/centreon/main.php?p=307
![image](https://user-images.githubusercontent.com/25208457/28842667-f0dec22a-76d4-11e7-9316-e2da601d31ba.png)

**Comment by BenoitPoulet** [comment]
Arghh, how can this kind of bug be delayed ? 
This is bloking all Centreon MBI reports.
No manager/customer can accept a monitoring system who cannot give availability information.

**Comment by Moujimouja** [comment]
Hello Benoit,

When you say it's blocking Centreon MBI reports, can you please be more specific ? What kind of reports ? 
_If you experience a problem with Centreon MBI in general, please open a ticket on Centreon's support_

**Comment by BenoitPoulet** [comment]
Hello,
It's blocking because we are using host/services availability in our CentreonMBI reports.
If the values are wrong in database, we  can't use them.

**Comment by Moujimouja** [comment]
It seems to be only an interface-related problem. Data in database are OK so Centreon MBI should be OK too. Are you experiencing some wrong data display in MBI Reports ?
