### ISSUE TITLE
Unable to change the geo_coordinates of a meta service

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5493]
BUG REPORT INFORMATION

Centreon Web version: 2.8.10

Steps to reproduce the issue:
I create a meta service with the geo_coordinates configured
I save the meta service
I change the geo_coordinates of the meta service.
I save the modification.

Describe the results you received:
The geo_coordinates has not changed

Describe the results you expected:
I should be able to change the geo_coordinates of a host template.

**Comment by thiuyendang** [comment]
ok 2.8.12-4, centOS6, centOS7.
