### ISSUE TITLE
Implied contact of a meta service is deleted during duplication

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5495]
BUG REPORT INFORMATION

Centreon Web version: 2.8.10

Steps to reproduce the issue:
I create a meta service with the "implied contact" configured
I save the meta service
I duplicate the meta service.
I check the properties of the new meta service

Describe the results you received:
The "implied contact" is now empty

Describe the results you expected:
The "implied contact" field shouldn't be modified when a meta service is duplicated.

**Comment by thiuyendang** [comment]
OK in 2.8.12-4, centOS6, centOS7
