### ISSUE TITLE
The ACL of a contact and of a contact group is deleted during duplication

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5497]
BUG REPORT INFORMATION

Centreon Web version: 2.8.10

Steps to reproduce the issue:
I create a contact with a "access list group" configured
I save the contact
I duplicate the contact.
I check the properties of the new contact

Describe the results you received:
The "access list group" is now empty

Describe the results you expected:
The "access list group" field shouldn't be modified when a contact is duplicated.

Additional information:
There is the same problem with the contact groups

**Comment by thiuyendang** [comment]
OK 2.8.12-1, centOS6, centOS7.
