### ISSUE TITLE
Knowledge Base - display API errors

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5502]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Additional environment details (AWS, VirtualBox, physical, etc.):**: mediawiki123

**Steps to reproduce the issue:**
1. Install mediawiki
2. Configure access in Centreon
3. Add a wiki page
4. delete wikipage

**Describe the results you received:**

nothing and page not deleted

**Describe the results you expected:**

A pop-in displaying API error message

**Additional information you think important (e.g. issue happens only occasionally):**

Centreon wiki class receive:

array(2) {
  ["warnings"]=>
  array(1) {
    ["tokens"]=>
    array(1) {
      ["*"]=>
      string(51) "Action 'delete' is not allowed for the current user"
    }
  }
  ["tokens"]=>
  array(0) {
  }
}
{"result":true}

**Comment by lpinsivy** [comment]
With v1.28.0 of mediawiki the call to url: "/include/common/webServices/rest/internal.php?object=centreon_wiki&action=deletePage" return "Method not found"

**Comment by zskarman** [comment]
hi,

is it possible to put this ticket to the 2.8.13?  because this is the last issue in the 2.8.12 release, and we are waiting for that.

Thank you Zsolt

**Comment by lpinsivy** [comment]
Yes :D

**Comment by cmeschin** [comment]
Hi, Have you any news about this?
thanks

**Comment by adr-mo** [comment]
**Fixed in 18.10.5**
