### ISSUE TITLE
Knowledge Base - refresh page after deletion

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5503]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Additional environment details (AWS, VirtualBox, physical, etc.)**: mediawiki123

**Steps to reproduce the issue:**
1. Create a wiki page
2. Delete page 

**Describe the results you received:**

The Centreon menu indicates that I can delete the wiki page

**Describe the results you expected:**

If page is correctly deleted, refresh menu and display possibility to create wiki page

**Comment by loiclau** [comment]
work fine

**Comment by thiuyendang** [comment]
OK in 2.8.10, 2.8.12.centOS6, centOS7.
All actions (create page, view page, edit page, delete page) are OK.
