### ISSUE TITLE
Meta service - unable to add more than one contact

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5506]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.10

**Steps to reproduce the issue:**
1. Create/add a meta service
2. Select at minimum 2 contacts
3. Save
4. Edit the meta service

**Describe the results you received:**

Contacts are not saved

**Describe the results you expected:**

Contacts are not saved

**Comment by thiuyendang** [comment]
OK in 2.8.12-4, centOS6, centOS7
