### ISSUE TITLE
Problem with escalation's name during a duplication

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5512]
BUG REPORT INFORMATION

Centreon Web version: 2.8.10

Steps to reproduce the issue:
I create an escalation
I save it
I duplicate this escalation

Describe the results you received:
An ' 1' is added to the initial escalation name instead of a '_1'.

Describe the results you expected:
An '_1' should be added at the end of the initial name.

**Comment by thiuyendang** [comment]
OK 2.8.12-4; centOS6, centOS7
