### ISSUE TITLE
[2.8.11] service-monitoring permission vulnerability

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5514]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.11

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**Service Monitoring Widget version**: 1.5.4

**Steps to reproduce the issue:**
1. Enable **pagination and more actions** to a service-monitoring widget and turn it public.
2. Load this existing view for a user with no actions permission such as downtime set.
3. Try to set a downtime through widget actions with this user

**Describe the results you received:**
Guest users are able to run non-authorized actions through widget

Also found at https://github.com/centreon/centreon-widget-service-monitoring/issues/67

**Comment by Guillaume28** [comment]
Hello kozfelipe,

We tried to reproduce your problem but with all restrictions access ACL we have no access to any actions in the widgets.
Also we construct the list of ACL in the widgets so we secure it ->
https://github.com/centreon/centreon-widget-service-monitoring/blob/master/service-monitoring/src/toolbar.php
If you have any question for another problem do not hesitate to contact us.

**Comment by kozfelipe** [comment]
Im on vacation right now. As soon as I get back, ill try to reproduce it again and record step by step. thank you

**Comment by Guillaume28** [comment]
Hello @kozfelipe, do you have upgrade your widget service-monitoring ?
The version 1.6.1 will solved your problem.

**Comment by kozfelipe** [comment]
@Guillaume28 It is on version 1.6.1 

![image](https://user-images.githubusercontent.com/25208457/30930860-53bf52ce-a399-11e7-88ef-2158490e131e.png)

Issue still remains

![image](https://user-images.githubusercontent.com/25208457/30930765-1236c058-a399-11e7-8832-1c2b56f6f01c.png)

![image](https://user-images.githubusercontent.com/25208457/30930909-8693cfae-a399-11e7-8e58-c0bb98126fab.png)

**Comment by kozfelipe** [comment]
this might be related to https://github.com/centreon/centreon/issues/5747

**Comment by kozfelipe** [comment]
@Guillaume28 Today I recreated all ACL I had, and now widget works properly. Thank you
