### ISSUE TITLE
[2.8.11] Desabled hosts visible in reporting

### ISSUE THREAD

**Issue by RymRabehi** [centreon/centreon#5516]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.11

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CentOS 7

**Steps to reproduce the issue:**
1. Go to Reporting  >  Dashboard  >  Hosts
2. Select a host

**Describe the results you received:**
Disabled hosts are visible in the list.

**Describe the results you expected:**
Disabled hosts should not appear.

**Comment by lpinsivy** [comment]
Hi,

If we hide disabled host in the select box, how can you generate a report of availability of this one without enable the host ?

If you enable the host, someone can generate the configuration and add this "disabled" host in the monitoring.

I prefer to let disabled host in the select box.

**Comment by RymRabehi** [comment]
Hi,

Ok, thanks for your answer.

Rym R.
