### ISSUE TITLE
Command disappears during a connector duplication

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5518]
BUG REPORT INFORMATION

Centreon Web version: 2.8.10

Steps to reproduce the issue:
I create a connector with a command attached
I save it
I duplicate this connector

Describe the results you received:
The command has disappeared

Describe the results you expected:
Nothing should disappear during a duplication

**Comment by lpinsivy** [comment]
A command can only use 1 connector. So if you duplicate connector, we don't duplicate association connection to commands.
