### ISSUE TITLE
[2.8.11] - Reporting Dashboard Bug

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#5520]
Hello, 

We noticed an issue with Reporting Dashboard Menu. 
As Admin user everything works fine. But when the User is non-Admin reports are all wrong and not exact especially with service groups report. 

a non admin user gets this as a result : 
<img width="813" alt="centreon" src="https://user-images.githubusercontent.com/28105870/28974271-bc5454c4-792d-11e7-8dfc-9d42f457b177.png">

is there any solution ?

regards

**Comment by kozfelipe** [comment]
https://github.com/centreon/centreon/issues/5491

**Comment by lpinsivy** [comment]
I close this issue because the other one is opened
