### ISSUE TITLE
2.8.11 update

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#5521]
Hello, 

I have a monitoring platform composed of one central and 3 pollers. 
Central was running web 2.8.4 and i updated it to 2.8.11. 
After that i noticed that i can't push changes to my pollers !
Is there any thing i must do on pollers ?

centreon-engine is on centreon-engine.x86_64 0:1.7.0-2.el6
Centreon-broker is on centreon-broker.x86_64 0:3.0.3-4.el6

Thank you for you help because i am now stuck and have a lot of changes to apply.

Regards

**Comment by saharawolf** [comment]
Can anyone help please ?

thank you.

**Comment by Sims24** [comment]
Hi, 

Do you have any message in /var/log/centreon/centcore.log ? Please restart centcore and check for error when you're pushing your config.

**Comment by saharawolf** [comment]
got this error 
 Start: Send config files on poller 2
2017-08-07 17:50:25 - Result :
2017-08-07 17:50:25 - End: Send config files on poller 2
2017-08-07 17:50:25 - Start: Send Centreon Broker config files on poller 2
2017-08-07 17:50:25 - Result : scp: /etc/centreon-broker/watchdog.xml: Permission denied
2017-08-07 17:50:25 - End: Send Centreon Broker config files on poller 2
sudo: no tty present and no askpass program specified
any clue ?

**Comment by Sims24** [comment]
Probably two problems : 

- user and groups on remote poller, check permissions on /etc/centreon-broker/ centreon should be able to write into (nevertheless if you do not have poller-display module on it you should not have to copy this file)

- check the path of systemctl command on your remote poller and make sure that you can run the command (should fail with the same error you get in the web ui) : 

ssh IP.OF.THE.POLLER "sudo /path/systemctl restart centengine"

**Comment by saharawolf** [comment]
hi, 

I checked permissions and even put a 777 on centreon-broker folder without success.

I am on cenros 6 i do not have systemctl command but i tried with this 
su - centreon
ssh poller "sudo service centengine restart"
sudo: no tty present and no askpass program specified

what i do not understand is that everything was fine before i updated centreon web. i was on 2.8.4 and updated it to 2.8.11

**Comment by Sims24** [comment]
ok my bad the problem is probably related to your sudoers on the remote poller. Please copy past content of /etc/sudoers.d/centreon and aslo that it's correctly included from /etc/sudoers legacy file.

**Comment by saharawolf** [comment]
this is the contenet of the file on my poller.
############################
## BEGIN: CENTREON SUDO
#Add by CENTREON installation script
User_Alias      CENTREON=%centreon
Defaults:CENTREON !requiretty
# Snmptt Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/snmptt restart
# Snmptrapd Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/snmptrapd restart
## Centreontrapd Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd restart
## Centreontrapd Reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd reload
## Centreontrapd Stop
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd stop
## Centreontrapd Start
CENTREON   ALL = NOPASSWD: /etc/init.d/centreontrapd start
# Centengine Restart
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine restart
# Centengine stop
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine start
# Centengine stop
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine stop
# Centengine reload
CENTREON   ALL = NOPASSWD: /etc/init.d/centengine reload
# Test config
CENTREON   ALL = NOPASSWD: /usr/sbin/centengine -v *
#Broker Central restart
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd restart
# Broker Central reload
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd reload
# Broker Central start
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd start
# Broker Central stop
CENTREON   ALL = NOPASSWD: /etc/init.d/cbd stop
# Broker central restart for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl restart cbd
# Broker central reload for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl reload cbd
# Broker central start for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl start cbd
# Broker central stop for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl stop cbd
# Centreon Engine central restart for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl restart centengine
# Centreon Engine central reload for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl reload centengine
# Centreon Engine central start for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl start centengine
# Centreon Engine central stop for systemd
CENTREON   ALL = NOPASSWD: /bin/systemctl stop centengine
## END: CENTREON SUDO

on sudoers legacy i have 

includedir /etc/sudoers.d

**Comment by saharawolf** [comment]
i have three pollers, all three sopped working since the update.

anyway to rollback ?

regards

**Comment by saharawolf** [comment]
2017-08-08 12:38:30 - Start: Send config files on poller 2
2017-08-08 12:38:30 - Result :
2017-08-08 12:38:30 - End: Send config files on poller 2
2017-08-08 12:38:30 - End: Send config files on poller 2
2017-08-08 12:38:30 - Start: Send Centreon Broker config files on poller 2
2017-08-08 12:38:30 - Result : scp: /etc/centreon-broker/watchdog.xml: Permission denied
2017-08-08 12:38:30 - End: Send Centreon Broker config files on poller 2
2017-08-08 12:38:30 - End: Send Centreon Broker config files on poller 2
sudo: >>> /etc/sudoers: syntax error near line 112 <<<
sudo: parse error in /etc/sudoers near line 112
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
unable to initialize policy plugin

**Comment by Sims24** [comment]
Difficult to rollback in your case. 
For the sudo error I think that you've remove the "#" at the beginning of the line include. You should not do that it's not a comment it's sudo specific.

For the command test instead : 

su - centreon
ssh poller "sudo /etc/init.d/centengine restart"

Can you screenshot you COnfiguration > pollers > <click on pollername> 

thanks

**Comment by saharawolf** [comment]
I have this question 

I have only done a "yum update centreon" so only the centreon web part was updated. Centreon broker and centreon engine are still not on the last version.

Is it necessary to update everything else ? is there a comptibility issue ?

**Comment by Sims24** [comment]
No it's not a compatibility issue here, purely rights of your system users. 

But you should always upgrade broker and engine especially because of some very important bugfix on broker since 3.0.3.
