### ISSUE TITLE
Problème génération des graphes

### ISSUE THREAD

**Issue by Ale171** [centreon/centreon#5523]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.3

**OS**: CentOS

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Dans Supervision, Détails des status
2. Vérification des graphes
3.

**Describe the results you received:**

J'ai eu un bug à cause de l'espace disque sur mon central il y a quelques jours, j'ai réglé le problème et tout est réparti, sauf les graphes qui ne se génère plus depuis ce temps, je ne sais pas d'où ca vient, aucun problème dans les logs, et les fichiers rrd ne sont plus alimentés depuis la date du problème.

**Describe the results you expected:**

Retrouver mes graphes.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Sims24** [comment]
Bonjour @Ale171  

Le manque d'espace disque a dû corrompre un RRD.  Le fichier incriminé doit être visible dans /var/log/centreon-broker/central-rrd-master.log. Un fois ce fichier supprimé cela devrait pouvoir rattrapé le delta de données dans vos graphiques.

**Comment by Ale171** [comment]
Bonjour

Merci pour la rapidité de votre réponse,

Je n'ai pas d'erreur de logs dans ce fichier ni dans les autres, existe t'il un autre moyen de vérifier si un fichier RRD est corrompu ?

`[1502089831] config:  applier: 11 modules loaded`
`[1502089846] config:  main: configuration update requested`
`[1502089846] config:  log applier: applying 1 logging objects`
`[1502089846] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'`
`[1502089846] error:   TLS: GNU TLS run-time version is incompatible with the compile-time version (2.12.23): please update your GNU TLS library`
`[1502089846] config:  applier: 11 modules loaded`
`[1502089854] config:  main: configuration update requested`
`[1502089854] config:  log applier: applying 1 logging objects`
`[1502089854] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'`
`[1502089854] error:   TLS: GNU TLS run-time version is incompatible with the compile-time version (2.12.23): please update your GNU TLS library`
`[1502089854] config:  applier: 11 modules loaded
`

**Comment by Ale171** [comment]
Pour info : 

Lorsque je vais dans Administration, Paramètres, Données,

Tous mes graphiques sont indiqués "Yes" dans la colonne "En attente de reconstruction"

**Comment by Sims24** [comment]
Il vous faut mettre à jours votre version de GNU TLS puis redémarrer centreon-broker.

Pour la reconstruction des graphs, cela provient d'une action manuelle mais si vous en avez beaucoup il y a de fortes chances pour que cela échoue. Si c'est le cas, il faudrait annuler cette action via la requête suivante : 

UPDATE `centreon_storage`.`index_data` SET `must_be_rebuild`='0';

Pouvez vous lister les fichiers dans dans /var/lib/centreon-broker ?

**Comment by Ale171** [comment]
J'ai mis à jour GNU TLS

`yum update gnutls`

Quand je redémarre cbd, des erreurs apparaissent maintenant : 


![image](https://user-images.githubusercontent.com/24827386/29017335-b5f8f686-7b56-11e7-8e6b-066a645bccb1.png)

Quels sont ces fichiers RRD qui essayent d'être supprimés ?

Pour les fichier de /var/lib/centreon-broker : 

![image](https://user-images.githubusercontent.com/24827386/29017369-d211d37e-7b56-11e7-8139-b766f8b91917.png)

**Comment by Sims24** [comment]
Lorsque vous demandez un rebuild des RRDs, broker les supprime pour les recréer, ici il n'a pas trouvé les fichiers en question.

Les graphs sont repartis ?

**Comment by Ale171** [comment]
Non toujours pas,

par contre le broker essaye de supprimer un fichier RRD et du coup cela spam mes logs.

**Comment by Ale171** [comment]
Par contre,

Quand je fais un ls -l, les fichiers dans metrics et statuts possèdent bien la date du jour contraitement à tout à l'heure, peut-être faut-il attend encore un peu

**Comment by Ale171** [comment]
Tout est reparti, je ne sais pas trop comment,

En tout cas merci @Sims24 pour ton aide :)

**Comment by Sims24** [comment]
La version de GNU Tls probablement ;) 

De rien ! Fermes l'issue si c'est ok pour toi

**Comment by Ale171** [comment]
Bon finalement tout c'était arrêter au bout d'une heure, mais j'ai trouvé la solution, j'explique ça peut servir à d'autres : 

Mon broker m'indiquait des fichiers corrompus dans /var/lib/centreon-broker/
1. j'ai supprimer tous les fichiers de rétention perfdata et input.
2. J'ai supprimer tous mes graphes depuis l'interface web.
3. J'ai stoppé centengine et cbd sur tous mes pollers
4. J'ai stop et start cbd sur mon central
5. J'ai lancé centengine et cbd un par un sur mes satellites
6. Exporter la conf sur tous les pollers.

Maintenant tous mes graphes sont repartis, et je n'ai plus aucune erreur.
