### ISSUE TITLE
centreon ui notification (popin and sound) loop on ok status

### ISSUE THREAD

**Issue by bbnono** [centreon/centreon#5524]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.11

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8-1

**OS**: centos 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical servers for central and poller

**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**
I have a loop on the ui notification on 3 servers issue produce when we have an electric issue. The poller is up more time than the server due to an APC.
When the server gone up , the poller is already done and now all is up but the central send us ui notification for service and host gone up since 4 days !

**Describe the results you expected:**
I think the issue is on the register data, but don't found what data is not store.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

The notifications UI works for the other hosts/services issues?

The clock of the server is synchronised on a NTP server?

Regards,
