### ISSUE TITLE
Problem when reloading poller

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#5528]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.5

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: RH 6.8

**Steps to reproduce the issue:**
1. Take equipment with services
2. Put all these services downtime
3. Change its "host template"
4. Delete all these services
5. Deploy the services associated with the "host template"
6. Reload the poller

**Describe the results you received:**

In the real-time part (Monitoring> Status Details> Services) we still have the old services that are present

**Comment by BenoitPoulet** [comment]
Sometime you need to restart, reload is not enough.

**Comment by lpinsivy** [comment]
linked to #5321
