### ISSUE TITLE
Service/Host Templates wiped out after upgrade from 2.8.9 to 2.8.10

### ISSUE THREAD

**Issue by 5145h** [centreon/centreon#5529]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.10-4.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.7.2-3.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-3.0.8-1.el7.centos.x86_64

**OS**: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM

**Steps to reproduce the issue:**
1. Yum update
2. 
3.

**Describe the results you received:**
Service/Host templates tab empty

**Describe the results you expected:**
The templates manually defined by me weren't there anymore

**Additional information you think important (e.g. issue happens only occasionally):**
I think that if the upgrade removes the already existent service/host templates, there should be an export option in order to not lose the work done on creating and customizing these templates.

**Comment by lpinsivy** [comment]
Hi,

The update should never remove the templates made by users.

Can you check in the file /var/log/centreon/sql-error.log if any errors appear during update processus ?

Regards,
