### ISSUE TITLE
Dependent host deleted during a service dependency duplication

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5531]
BUG REPORT INFORMATION

Centreon Web version: 2.8.10

Steps to reproduce the issue:
I create a service dependency with a dependent host configured
I save it
I duplicate this dependency

Describe the results you received:
The field "dependent host" is empty

Describe the results you expected:
This field should be the same than the original dependency's one

**Comment by thiuyendang** [comment]
OK in 2.8.12-1, CentOS6.

**Comment by thiuyendang** [comment]
OK in 2.8.12-1, centOS7
