### ISSUE TITLE
Input text not aligned in Curves page

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#5534]
Centreon Web version: 2.8.11

Centreon Engine version: 1.7.2

Centreon Broker version: 3.0.8

OS: CentOS6

Additional environment details (AWS, VirtualBox, physical, etc.):

Steps to reproduce the issue:
1. Go to Monitoring  >  Performances  >  Curves
2. Edit a curve

The result : 

![curves-not-aligned](https://user-images.githubusercontent.com/14218330/29163249-2c87527c-7dbc-11e7-9c8b-47f5ab8e7f02.PNG)

Behavior expected : Everything aligned

Thanks in advance :)

**Comment by thiuyendang** [comment]
OK 2.8.12-4, CentOS6/7
