### ISSUE TITLE
Adding LDAP account deleting Centreon UI field values and Host templates

### ISSUE THREAD

**Issue by ianishant** [centreon/centreon#5535]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.11

**Centreon Engine version**: 1.5.3

**Centreon Broker version**: 2.11.8

**OS**: RHEL 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Steps to reproduce the issue:**
1. Administration->LDAP
2. Add a new LDAP config
3. Save

**Describe the results you received:**
Some values from Centreon UI got erased (centreon.options table) resulting in weired behaviour of UI and also resulted in missing of Host template field while adding a new host

**Describe the results you expected:** 

LDAP configuration added and UI should work as normal with Host template field visible for new host addition

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

Do you have error in /var/log/centreon/sql-error.log file?
Do you have  error in /var/log/heetpd/error_log file?

Result seems similar to #4929

Regards,
