### ISSUE TITLE
All poller configuration files have "Last modifiction By Unknown"

### ISSUE THREAD

**Issue by ianishant** [centreon/centreon#5536]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.11

**Centreon Engine version**: 1.5.3

**Centreon Broker version**: 2.11.8

**OS**: RHEL 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Steps to reproduce the issue:**
1. Add a service for a host
2. Push configuration  on poller
3. View any configuration file (say hosts.cfg) it says:
#### Last modification 2017-08-10 10:17                      #
#         By unknown   

**Describe the results you received:**

#### Last modification 2017-08-10 10:17                      #
#         By unknown  

**Describe the results you expected:**

#### Last modification 2017-08-10 10:17                      #
#         By <name of user>

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

We added this enhancment to CEntreon web 2.8.5 by pull request #4822

Regards,
