### ISSUE TITLE
[2.8.11] CLAPI Import not working

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#5541]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.11

**Centreon Engine version**:  1.7.2

**Centreon Broker version**:  3.0.8

**OS**: CentOS 7.3

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical

**Steps to reproduce the issue:**
1.Export configuration with CLAPI:
`centreon -u admin -p xxx -e > /tmp/config.txt`

2.Import the configuration (on a fresh installation for example):
`centreon -u admin -p xxx -i /tmp/config.txt`

**Describe the results you received:**
The import aborts with the following PHP error: 
`PHP Fatal error: Class '\CentreonClapi\centreon' not found in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php on line 840`

**Describe the results you expected:**
The config dump will be imported without error.

**Additional information you think important (e.g. issue happens only occasionally):**
The problem is the first line in the dump:
`{OBJECT_TYPE};{COMMAND};{PARAMETERS}`
If I delete this, importing is working without a problem.
So the parsing seems to have a problem with the header line.

**Comment by lpinsivy** [comment]
Solved by commit 5805a5978d5a45e6366bc7e578d32794205510e4
