### ISSUE TITLE
[2.8.11] traps_group table have not primary key with fresh install

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#5543]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.11

**Steps to reproduce the issue:**
1. Fresh install of 2.8.x
2. Look at traps_group table

**Describe the results you received:**
There is not primay key

**Describe the results you expected:**
There is a primary key. If not, inserted groups don't have id

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by zskarman** [comment]
Hi,

is it possible to close this case this week? and publish the 2.8.15?
Regards, Zsolt
