### ISSUE TITLE
Probleme configuring the ACL Resource of a ACL Group

### ISSUE THREAD

**Issue by mariegallardo** [centreon/centreon#5544]
BUG REPORT INFORMATION

Centreon Web version: 2.8.10

Steps to reproduce the issue:
I create a ACL Group with a ACL Resource configured
I save it
I remove the first ACL Resource and attach another on to the ACL Group

Describe the results you received:
The ACL Group is linked with two ACL Resources: the new one and the removed one.

Describe the results you expected:
The ACL Group should be linked only with the new ACL Resource

**Comment by lpinsivy** [comment]
linked to #5189
