### ISSUE TITLE
croned centAcl LDAP sync removes all ContactGroups on unexpected error

### ISSUE THREAD

**Issue by p3r7** [centreon/centreon#5547]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.8

**Centreon Engine version**: 1.5.2

**Centreon Broker version**: 2.11.5

**OS**: CentOS 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
We were in a situation of an LDAP server sometimes taking a lot of time to answer.

1. Run script /usr/share/centreon/cron/centAcl.php (via cron or manually)

**Describe the results you received:**

All our LDAP contact groups + associations (users, ACLs, custom views) got deleted.

**Describe the results you expected:**

The script to be more resilient against timeouts or any other kind of LDAP errors.

**Additional information you think important (e.g. issue happens only occasionally):**

My analysis is that when function CentreonContactgroup::syncWithLdap() gets run we can have this edge-case:
- LDAP connection can establish itself apparently correctly (CentreonLDAP::connect() does not return false).
- a timeout, or any other error, can occur during the CentreonLDAP::findGroupDn(), during the ldap_read() or ldap\_get\_entries() calls.

In this case, the script assumes that the group is missing in the LDAP server and proceeds to remove its declaration in the centreon DB.

Function CentreonLDAP::findGroupDn() should call [ldap\_errno](http://php.net/manual/en/function.ldap-errno.php) after ldap\_read() / ldap\_get\_entries() and analyze its result to detect if the object is really missing or if a technical error occurred.

**Comment by p3r7** [comment]
For those facing the same issue, I've made a small script to force the declaration of LDAP contact groups.

https://gist.github.com/p3r7/1965c70c4eeb84c30bad513404a2518c

This only re-creates associations with contacts. ACL and custom view associations were lost and needed to be recreated manually (or from a backup).

**Comment by p3r7** [comment]
Also, as far as I understand, the same bug could appear in version 2.8.x, so the corrective could be beneficial to the  latest releases.

**Comment by lpinsivy** [comment]
for Centreon Web 2.8.x 4cce9ee59433dc7863d0adb3fcee658589370277
