### ISSUE TITLE
[Centreon 2.8.11] CLAPI export with --select Filter give PHP Warning and non result

### ISSUE THREAD

**Issue by mwielander** [centreon/centreon#5548]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.11

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  execute clapi export with --select filter

**Describe the results you received:**
[root@centreon ~]# centreon -u admin -p 'password' -e --filter-type='^(HOST|SERVICE)$' --select='HOST;test'
PHP Warning:  trim() expects parameter 1 to be string, array given in /usr/share/centreon/lib/Centreon/Object/Object.php on line 282
PHP Warning:  trim() expects parameter 1 to be string, array given in /usr/share/centreon/lib/Centreon/Object/Relation/Relation.php on line 176
PHP Warning:  trim() expects parameter 1 to be string, array given in /usr/share/centreon/lib/Centreon/Object/Relation/Relation.php on line 176
PHP Warning:  trim() expects parameter 1 to be string, array given in /usr/share/centreon/lib/Centreon/Object/Relation/Host/Template/Host.php on line 134
PHP Warning:  trim() expects parameter 1 to be string, array given in /usr/share/centreon/lib/Centreon/Object/Relation/Relation.php on line 176
PHP Warning:  trim() expects parameter 1 to be string, array given in /usr/share/centreon/lib/Centreon/Object/Relation/Relation.php on line 176
PHP Warning:  trim() expects parameter 1 to be string, array given in /usr/share/centreon/lib/Centreon/Object/Relation/Relation.php on line 176
[root@centreon ~]#

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Corrected in next released 2.8.12
