### ISSUE TITLE
No graphics with backslash

### ISSUE THREAD

**Issue by FlorentEvolucare** [centreon/centreon#5554]
**Following the migration of the 2.7.0 Centreon version to 2.8.11. The graphics for a service no longer appear if the service description contains a backslash \.** 

_With backslash\_
![image](https://user-images.githubusercontent.com/31096125/29408569-ffe82010-8348-11e7-9d36-f27ee0f1ffad.png)
![image](https://user-images.githubusercontent.com/31096125/29408675-60bc16b2-8349-11e7-9332-e10809eb4de3.png)

_Without a backslash_
![image](https://user-images.githubusercontent.com/31096125/29408608-22aedf8a-8349-11e7-8205-75235a4fa8a8.png)
![image](https://user-images.githubusercontent.com/31096125/29408658-49a502c2-8349-11e7-96b0-9e107401902d.png)

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.11

**Centreon Engine version**: 
Centreon Engine 1.7.2

**Centreon Broker version**: 

**OS**: 
CentOS release 6.9 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-v

**Steps to reproduce the issue:**
1. remove the \ in the service description
2. add a \ in the service desciption
3. remove the \ in the service description

**Describe the results you received:**
Whenever a backslash is inserted into the service description, the graphic is not displayed

**Describe the results you expected:**
The graphic should be displayed but this is not the case if a backslash is present.

**Additional information you think important (e.g. issue happens only occasionally):**
As soon as there is a backslash in the description of the service it is impossible to visualize its graph.

**Comment by FlorentEvolucare** [comment]
After verification, the problem is not related to a version migration. Even since a new installation the anomaly occurs.

**Comment by thiuyendang** [comment]
OK in 2.8.13-1 when service description contains special characters such as backslash or colon

**Comment by FlorentEvolucare** [comment]
What are the patches to apply to avoid this problem?

**Comment by thiuyendang** [comment]
Hello, 

please, refer to Pull request # 5565  : https://github.com/centreon/centreon/pull/5565
