### ISSUE TITLE
No configuration modification detected by Centreon Web when host groups are created

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5555]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.12

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS6, CentOS7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  Go to Configuration > Hosts > Hosts Groups
2. Add a host group and save
3. Go to Configuration > Pollers page

**Describe the results you received:**
Column "Conf Changed" contains "No".

**Describe the results you expected:**
Column "Conf Changed" contains "Yes".

**Additional information you think important (e.g. issue happens only occasionally):**
If the configuration is not exported, user will not see the new host groups in Monitoring > Status Details > Service by Hostgroup.

**Comment by lpinsivy** [comment]
Hi,

From Centreon web interface, you can see the following message:

`* Only services and hosts are taken in account in order to calculate this status. If you modify a template, it won't tell you the configuration had changed.`
