### ISSUE TITLE
Add 24:00 option in date filter to downtime

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5558]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.11

**Steps to reproduce the issue:**
1. Go to "Monitoring - Downtimes"
2. Add Downtime
3. Click on time filter.

**Describe the results you received:**
It's impossible to set 24:00. "24" is not present.

**Describe the results you expected:**
Have the choice to selecting "24"

Regards

**Comment by BenoitPoulet** [comment]
Hello,

But you can select "00:00", i think it's the same.

**Comment by lpinsivy** [comment]
Yes select 00:00 for day+1

Regards,
