### ISSUE TITLE
[2.8.11] - Unable to change the severity of a service template

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#5559]
BUG REPORT INFORMATION

Centreon Web version: 2.8.11

Steps to reproduce the issue:
I create a service template and link it to a severity
I save the modifications. 
I change the severity of the service template.
I save the modification.

Describe the results you received:
The severity has not changed

Describe the results you expected:
I should be able to change the severity of a host template.

Ticket #5472 describes the same problem on host templates and this case is very similar.

**Comment by lpinsivy** [comment]
This problem is corrected by commit cfe4634094d8c7f3617953b1ca18b37064819ae3

**Comment by thiuyendang** [comment]
OK for host template and service template
