### ISSUE TITLE
Host category / severity inherit services

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5560]
[EN]
Hello,
I need to know if when adding a host in a category with severity, the services associated with this host inherit this severity?
Thanks for your feedback.
[EN]

[FR]
Bonjour,
j'ai besoins de savoir si lors de l'ajout d'un host dans une catégorie avec sévérité, les services associés à ce host hérites de cette sévérité?  
Merci pour votre retour.
[FR]

ma version actuelle :
Centreon 2.8.11
Centreon Engine 1.7.2
MariaDB 5.5.53

**Comment by lpinsivy** [comment]
Hi,

No their is no inheritance for services when you apply a severity on an host.

Regards,

**Comment by fredo1988** [comment]
HI there,

thank you for your answer, is it possible to integrate this on the next version?

Regards,

**Comment by lpinsivy** [comment]
Hi,

Thank you for your feedback. To understand your need, I have some question:

Do you use severity of host in Centreon web monitoring menu?
Or do you simply want to use an inheritance mechanism to make it easier to set up severities on your services?

Moreover, do you think that all the services of a host must necessarily have the same severity?

Regards,
