### ISSUE TITLE
notification retry after time periode past

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5566]
[EN]
Hello,
When configuring notifications on specific time ranges, is the alert sent after returning to the opening hours?

example:
The week, office hours 9: 00-17: 00,
An error is detected at 18:00, so no alert, the next day at 9:00 am if the error is still present, will a notification be sent?

I configured my template as follows:
Notification Interval = 0
First notification delay = 5
Recovery notification delay = 0
Thanks for your feedback.
[EN]

[FR]
Bonjour,
lorsque l'on configure les notifications sur des plages horaires spécifique, est ce que l'alerte est envoyé après le retour aux heures d'ouverture?

exemple:
la semaine, horaire de bureau 9h00-17h00,
une erreur est détectée à 18h00, donc pas d'alerte, le lendemain à 9h00 si l'erreur est toujours présente, une notification sera t'elle envoyée?

j'ai configuré mes template comme suit :
Notification Interval = 0
First notification delay = 5
Recovery notification delay =0

Merci pour votre retour.
[FR]

ma version actuelle :
Centreon 2.8.11
Centreon Engine 1.7.2
MariaDB 5.5.53

**Comment by lpinsivy** [comment]
Hi,

All notifications are deleted if they are outside the notification period.

But if the problem persists (non-ok check) when the notification period is enabled, a notification will be sent.

Regards,

**Comment by fredo1988** [comment]
Hi,
thanks, but 
I test this and two results, 
# if I configured directly on service the time period, it's ok, notification will be send after time periode is enable.
# if I used escaldation, the notification not send.

My configuration: 
 on service exemple : 
![image](https://user-images.githubusercontent.com/25640319/29668178-899d7e7c-88df-11e7-8a87-58d1d20e7748.png)
 on escalade exemple:
![image](https://user-images.githubusercontent.com/25640319/29668240-b9fcbcf4-88df-11e7-928f-de82b58d7e8e.png)

![image](https://user-images.githubusercontent.com/25640319/29668277-e347f902-88df-11e7-9479-27fdfe0293fb.png)

**Comment by lpinsivy** [comment]
Hi,

It is normal with your configuration of escalation because escalation start with 1 and not 0.
Its means that escalation is waiting for second notification of the non-ok status before to start.
But in your service you configure notification intervalle to 0 so only one notification.

If you start notification to 0, it should be work.
