### ISSUE TITLE
Widget global health display

### ISSUE THREAD

**Issue by millecentdix** [centreon/centreon#5573]
Hello,

I have a special issue with the widget centreon-widget-global-health.noarch 1.0.0-42.el6 in the custom view.
My account is administrator and the view works fine. This view is shared with other users.
For other users who have not administration rights, the view do not work for the services.
For the hosts, I tried to add the line $pearDB as said in the ticket #5161 and that solved my problem.

Thanks for all work.

Extract of my ssl_error_log : 

[Wed Aug 23 14:43:12 2017] [error] [client xxxxxxxx] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/widgets/global-health/src/global_health.php on line 234, referer: https://xxxxxxxxxx/centreon/widgets/global-health/index.php?widgetId=133&customViewId=22

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.11-3.el6

**Centreon Engine version**: 
1.7.2-3.el6

**Centreon Broker version**: 
3.0.8-1.el6

**OS**: 
CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by imnotme** [comment]
Same issue with plugin pack page :

**Comment by imnotme** [comment]
Same issue with plugin pack page : 
PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/modules/centreon-pp-manager/core/manager/functions.php on line 0, referer: https://monit.local/centreon/main.php?p=617

Same version (update from 2.8.9 to 2.8.11)

**Comment by lpinsivy** [comment]
linked to https://github.com/centreon/centreon-widget-global-health/issues/2
