### ISSUE TITLE
Time Range exceptions invalid format

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5578]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.11
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.8
**OS**: 
Centreon

**Steps to reproduce the issue:**
1. Create a Time Range exceptions with a format "1 january" for example

**Describe the results you received:**

When you export the configuration you have an error message:
Reading main configuration file '/usr/share/centreon/filesGeneration/engine/1/centengine.DEBUG'.
Error while processing a config file: Parsing of object definition failed in file '/usr/share/centreon//filesGeneration/engine/1/timeperiods.cfg' on line 42: Invalid line '1 january 00:00-24:00'
One or more problems occurred while processing the config files.

**Describe the results you expected:**
We should be able to set a downtime for the same date every year ( like it is described in the [documentation ](https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/timeperiod.html#time-range-exceptions) )

**Comment by thiuyendang** [comment]
OK, the format has been changed in documentation to fit the format used by Centreon Web.
