### ISSUE TITLE
Update plugins - Problem with the command OS-Windows-SNMP-Memory

### ISSUE THREAD

**Issue by o71** [centreon/centreon#5585]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.11

**Centreon Engine version**: 1.7.2

**OS**: CES

Hello,

With the last update of the plugins. The command "OS-Windows-SNMP-Memory" doesn't work

If I look the help of the new plugins (/usr/lib/centreon/plugins/centreon_windows_snmp.pl --mode=memory --plugin=os::windows::snmp::plugin --help). I see that --warning and --critical are replaced by --warning-* and --critical-*.

If I use --warning-memory=80 its works.

But the problem is that the command in the interface of centreon is'nt modified :
![command OS-Windows-SNMP-Memory](https://user-images.githubusercontent.com/2280629/29640944-8f0abf2e-8861-11e7-9925-64fe4e76271d.png)

Thanks

**Comment by Sims24** [comment]
Hi, 

Known issue we will fix this today through publication of a new release of the pack. 

Thanks,

**Comment by Sims24** [comment]
@o71 fix has been pushed online, you should not have the problem anymore

Thanks,

**Comment by o71** [comment]
I have do no update for the moment perhaps with 2.8.12 ?
Thanks

**Comment by lpinsivy** [comment]
@hgpit some Plugin Packs had updated today.

everything is now ok?

**Comment by o71** [comment]
@Sims24  have solve the problem with a SQL query (update). So I can't confirm that the update have solve it. Perhaps other people can cofirm ?

Thanks

**Comment by mandevnull** [comment]
Hello, i have the same problem, the command was modified with parameter -memory but not the template. I'm using CES and i don't have any "yum update" yet

**Comment by mandevnull** [comment]
sorry the versions:
centreon-web-2.8.12-7.el6.noarch
centreon-2.8.12-7.el6.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20170807-1.el6.noarch
centreon-pp-manager 2.2.0

**Comment by lpinsivy** [comment]
did you update the Plugin Pack "Linux SNMP" ?

**Comment by mandevnull** [comment]
the version of plugin pack linux snmp is: centreon-plugin-Operatingsystems-Linux-Snmp-20170807
but the problem is with the check /usr/lib/centreon/plugins/centreon_windows_snmp.pl. Parameters --warning-memory and critical-memory. In the templat/command is --warning='$_SERVICEWARNING$' --critical='$_SERVICECRITICAL$' $_

**Comment by mandevnull** [comment]
Hello, any news about this bug? thanks

**Comment by lpinsivy** [comment]
You right,

We will change the Plugin Packs soon

**Comment by lpinsivy** [comment]
Command OS-Windows-SNMP-Memory is OK but not OS-Linux-SNMP-Memory

**Comment by lpinsivy** [comment]
So I installed latest Plugin Packs version of Windows and Linux SNMP and my command are:

`$CENTREONPLUGINS$/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning-memory='$_SERVICEWARNING$' --critical-memory='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$`

`$CENTREONPLUGINS$/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning='$_SERVICEWARNING$' --critical='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$`

So for me they are ok. Can you try to reinstall your Plugin Packs ?

**Comment by mandevnull** [comment]
do you mean reinstall centreon-plugin-Operatingsystems-Windows-Snmp ? I have tried reinstall but i continue see the same (i attach screenshot screen1.png). Also i reinstall centreon-plugins-base.noarch, centreon-plugins.noarch, centreon-pp-manager. In configuration/plugin pack, i see all the plugin packs but i don't see any logo, and if i click in any plugin i don't do nothing, is strange

**Comment by lpinsivy** [comment]
Hi, "centreon-plugin-Operatingsystems-Windows-Snmp" is the Plugin and not the Plugin Packs.

Please go to "Configuration > Plugin packs" to reinstall the "Linux SNMP" Plugin Pack.

**Comment by mandevnull** [comment]
ok, with firefox works ok, but with chrome i have this problem in plugin packs. Also i don't have the check in the plugin pack that i have installed

**Comment by lpinsivy** [comment]
Did you try to clean broswer cache with chrome? I use chrom on mac without problem

**Comment by mandevnull** [comment]
yes, ok  problem solved, thanks
