### ISSUE TITLE
Update of centreon-pp-manager - Objects timeperiods not installed

### ISSUE THREAD

**Issue by o71** [centreon/centreon#5586]
**Centreon Web version**: 2.8.11

**Centreon Engine version**: 1.7.2

**OS**: CES

Hello,

I have this error :

![image](https://user-images.githubusercontent.com/2280629/29641610-a1119eec-8864-11e7-9462-a83c195898b5.png)

What does it mean ? How to solve it ?

Thanks

**Comment by Sims24** [comment]
Hello @o71 

I cannot reproduce this one. Could you provide us more details on theses points : 

- Did you upgrade centreon-pp-manager through "Administration > Extensions" ? 
- Is this a fresh install ?
- Did you try to use "reinstall" button ? 

Can you provide logs if any related (containing centreon-pp-manager) in /var/log/centreon/sql-error.log ? 

Thanks

**Comment by o71** [comment]
- My version is 2.2.0 : 
![image](https://user-images.githubusercontent.com/2280629/29654122-38c780e8-88ac-11e7-841b-d270420cf57e.png)

- It' not a fresh install but all was ok before update

- I try use reinstall but always the same problem

-I have this error in sql-error.log :+1: 
`2017-08-24 00:01|0|0|DB Error: no such table QUERY : SELECT slug, name FROM mod_ppm_categories ORDER BY name
`

**Comment by o71** [comment]
But I can to the query now :

![image](https://user-images.githubusercontent.com/2280629/29654357-29580690-88ad-11e7-9741-c6a7b63de699.png)

**Comment by Sims24** [comment]
Could you please attach /usr/share/centreon-packs/pluginpack_base-generic-3.1.3.json file ? 

Also any new error in sql-error when you try to perform the reinstall ?

Thanks, 
Simon

**Comment by o71** [comment]
I test it :
- I have restore a backup (pp-manager 2.1.3) : 
![image](https://user-images.githubusercontent.com/2280629/29656435-b733f968-88b4-11e7-8efb-f65de9a13001.png)
- I don't know why I don't see the plugin packs here : 
![image](https://user-images.githubusercontent.com/2280629/29656477-d3120ada-88b4-11e7-85e9-4f9374c5f581.png)
- I have an error sql with this version :
`2017-08-24 10:08|0|0|DB Error: no such table QUERY : SELECT slug, name FROM mod_ppm_categories ORDER BY name
`
- I do update (I click update here) : 
![image](https://user-images.githubusercontent.com/2280629/29656527-fba04ade-88b4-11e7-8b94-ff6cc919c5e1.png)
- It's ok no sql error and no error in Configuration>Plugin pack> Configuration
- But if I test reinstall to see I have it :

![image](https://user-images.githubusercontent.com/2280629/29655740-481ffbbe-88b2-11e7-8933-fba7560a4e01.png)

- no sql error

I have no file in /usr/share/centreon-packs/, it's empty

**Comment by o71** [comment]
I do another test :+1: 
- I install a plugin pack, I have never install 'FTP Server'
- I have the error with objects timeperiods
- I can't desinstall the plugin pack :

Thanks for your help

**Comment by hgpit** [comment]
We are experiencing the same problem since upgrading Centreon from v2.8.11 to v2.8.12.
We have a paid subscription.

Our Windows SNMP plugin is playing up, so I am trying to re-install it, but I'm not sure whether this error is preventing the plugin from re-installing (our plugin error persists after trying).

Is there a target date for this to be sorted?

**Comment by Sims24** [comment]
Should be online. Can you try to upgrade it ? 

Thanks,

**Comment by lpinsivy** [comment]
@hgpit some Plugin Packs had updated today.

everything is now ok?

**Comment by o71** [comment]
Sorry for the delay. All is ok now !

Thanks a lot
