### ISSUE TITLE
Centreon plugin pfSense modes missing in release 20170807

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon#5590]
**centreon-plugin-Network-Firewalls-Pfsense-Snmp 20170807**

After update of plugin pfSense from release 20161212, the list-mode completely changed:

**Modes Available in 20161212**
   blocked-packets
   memory-dropped-packets
   runtime

**Modes Available in 20170807**
   list-pfinterfaces
   packet-stats
   pfinterfaces
   runtime

The new plugin same similar to centreon-plugins from Git:
./centreon_plugins.pl --plugin apps::pfsense::snmp::plugin --list-mode
   list-pfinterfaces
   packet-stats
   pfinterfaces
   runtime

Where can i get the old modes (blocked-packets and memory-dropped-packets) ?

Thank you
Best regards

**Comment by Sims24** [comment]
Yes, names have changed but all/some modes have been merged to make it more efficient.

Thanks

**Comment by stefanotoro** [comment]
Ok understantd, but there is a list of changes (changelog) that i can read before installing ?
Because of applying "simple" updates break all/some results...

Thank you

**Comment by Sims24** [comment]
Please follow tag we set on centreon_plugin on a regular basis.

https://github.com/centreon/centreon-plugins/releases

**Comment by stefanotoro** [comment]
Thanks !
