### ISSUE TITLE
new version of plugin pack page incompatible with HTTPS.

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5599]
[EN]
Hello,
The new version of the plugins pack page does not work correctly in HTTPS mode.
Thanks for your feedback.
[EN]

[FR]
Bonjour,
la nouvelle version de la page des plugins pack ne fonctionne pas correctement en mode HTTPS
Merci pour votre retour.
[FR]

HTTPS:
![image](https://user-images.githubusercontent.com/25640319/29703303-40632bc6-8975-11e7-8b2d-16d36b04ac83.png)

HTTP:
![image](https://user-images.githubusercontent.com/25640319/29703277-2eb6d4a4-8975-11e7-8b1b-c0b77f62b058.png)

ma version actuelle :
centreon-pp-manager : 2.2.0
Centreon 2.8.11
Centreon Engine 1.7.2
MariaDB 5.5.53

**Comment by Sims24** [comment]
Hi, 

This is rather a cache issue. Could you try hit Ctrl-F5 when your on the page through HTTPS

**Comment by fredo1988** [comment]
Great!

it's OK thanks :)
