### ISSUE TITLE
Check Queries of Centreon Plugin Centrale

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5600]
[EN]
Hello,
I use the "Queries" plugin Centreon of the Template "App-DB-MySQL-Queries-custom"
But it goes back to me an error: "CRITICAL: Total requests = 856"
Can you help me understand this error?
Thanks for your feedback.
[EN]

[FR]
Bonjour,
j'utilise le plugin "Queries" Centreon du Template "App-DB-MySQL-Queries-custom"
mais il me remonte une erreur: "CRITICAL: Total requests = 856"
pouvez vous m'aidez à comprendre cette erreur?
Merci pour votre retour.
[FR]

ma version actuelle :
Centreon 2.8.11
Centreon Engine 1.7.2
MariaDB 5.5.53

**Comment by Sims24** [comment]
Hello, 

This is because of default threshold that are to low. You should not be worried by queries number unless it reaches around 1500 or 2000 queries. Change WARNING and CRITICAL macro value.

**Comment by fredo1988** [comment]
hi it's OK thanks :)
