### ISSUE TITLE
ACK | DT | Comment not working

### ISSUE THREAD

**Issue by mfy2a** [centreon/centreon#5604]
Hi there,

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.11

**Centreon Engine version**: centreon-engine-1.7.2-3

**Centreon Broker version**: centreon-broker-cbd-3.0.8-1

**OS**: centos7

**Steps to reproduce the issue:**
1. When i ack or downtime a service/host i still get notifications.

i can see in my cmd file( /var/lib/centreon/centcore.cmd) :
```EXTERNALCMD:1:[1503907788] ACKNOWLEDGE_HOST_PROBLEM;worker3_018;2;0;1;admin;Acknowledged by admin```

but nothing in /var/lib/centreon-engine/rw/centengine.cmd

what am i missing ?

**Comment by lpinsivy** [comment]
Hi,

Can you see if centcore process is running ?

Because if the  /var/lib/centreon/centcore.cmd is present, centcore is not running and didn't export command to poller (Engine).

Regards,

**Comment by mfy2a** [comment]
Hi,
yes it's running : 

> ps faux centreo+   360  0.1  0.1 740256 19332 ?        Ssl  Aug28   3:07 /usr/sbin/centengine /etc/centreon-engine/centengine.cfg

> sudo /bin/systemctl status  centengine.service
Active: active (running) since Mon 2017-08-28 11:40:37 CEST; 1 day 11h ago

may i delete  /var/lib/centreon/centcore.cmd file ?

**Comment by lpinsivy** [comment]
No do not delete this file. It must be deleted by centcore itself.

Do you have error in /var/log/centreon/centcore.log?

**Comment by mfy2a** [comment]
even when i try to write a comment on a host ... i got nothing on the UI but the event is present here : 
/var/lib/centreon/centcore.cmd
>> EXTERNALCMD:1:[1504171737] ADD_HOST_COMMENT;worker3_011;1;admin;test

any idea ?

**Comment by mfy2a** [comment]
hummm maybe you get something...
>> /var/lib/centreon-engine/rw/centengine.cmd Permission denied

prw-r--r-- 1 centreon-engine centreon-engine 0 Aug 28 10:44 /var/lib/centreon-engine/rw/centengine.cmd

**Comment by mfy2a** [comment]
with the good writes, everything is working \o/

thank you for your help
