### ISSUE TITLE
Parent/Child relation are not exported with CLAPI

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5605]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.10
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.8
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1. Create a Parent relation between two hosts we can see it with the following command:
centreon -u admin -p centreon -o HOST -a "getparent" -v "hote_fils"
id;name
14;Centreon-Server

2. But we export the configuration this relation is not present anymore: 
(centreon -u admin -p centreon -e > /tmp/clapi_export.txt) 

grep '^HOST;.*hote_fils*' clapi_export.txt
HOST;ADD;localhost;localhost;127.0.0.1;;Central;
HOST;setparam;localhost;host_active_checks_enabled;2
HOST;setparam;localhost;host_passive_checks_enabled;2
HOST;setparam;localhost;host_checks_enabled;2
HOST;setparam;localhost;host_obsess_over_host;2
HOST;setparam;localhost;host_check_freshness;2
HOST;setparam;localhost;host_event_handler_enabled;2
HOST;setparam;localhost;host_flap_detection_enabled;2
HOST;setparam;localhost;host_retain_status_information;2
HOST;setparam;localhost;host_retain_nonstatus_information;2
HOST;setparam;localhost;host_notifications_enabled;2
HOST;setparam;localhost;contact_additive_inheritance;0
HOST;setparam;localhost;cg_additive_inheritance;0
HOST;setparam;localhost;host_locked;0
HOST;setparam;localhost;host_register;1
HOST;setparam;localhost;host_activate;1
HOST;addtemplate;localhost;OS-Linux-SNMP-custom

**Describe the results you received:**
The Parent/child relation is not saved when you export your configuration with CLAPI

**Comment by adr-mo** [comment]
Got a parent host and a child host.

During the export of the configuration I've got the addparent line related to the concerned hosts.

Looks good to me.
