### ISSUE TITLE
[2.8.8] Services come back to pending status

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon#5613]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: Oracle Linux 7.3

**Additional environment details (AWS, VirtualBox, physical, etc.):** Virtual

**Steps to reproduce the issue:**
1. I added about 2000 new checks into centreon.
2. Every day(more times), 1000+ test come back into pending status.(this happened 4 times in this morning). I don't understand why. 
3. When we login into poller and restart the centengine service, the pending services disappear.
4. In addition when a lot of test come back to pending the centengine service stuck on some poller and need to login and restart them every time.

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/25457811/29864173-3081d33c-8d72-11e7-9c8b-e2b367b41a28.png)

No errors in log files.

**Describe the results you expected:**

 We don't want that the test always come back in pending status again and again.

**Comment by lpinsivy** [comment]
Hi,

I can sse some issues with your poller states from your print screen.

Do you have issue with a poller each time you see pending services?

Regards,

**Comment by Tomszy** [comment]
Yes we have issue each time.
 I think I know what cause the problem.
We are are getting this error message in central-broker-master.log
![image](https://user-images.githubusercontent.com/25457811/29973145-c9d7c998-8f2e-11e7-82e9-aeea5b643fbd.png)
We need to reload the cbd after these errors, but after the reload many service come back to pending status again and again...  and some poller always stuck after this operation and we need to restart centengines after it.

**Comment by lpinsivy** [comment]
Linked to #5609
