### ISSUE TITLE
Trouble with cache in search bar for some form

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#5615]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.12
**Centreon Engine version**: 
1.7.1
**Centreon Broker version**: 
3.0.8
**OS**: 
CentOS 6
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. In this menu
 - host
 - hostgroup
 - host categories
 - service categories
 - contact/user
 - contact template
 - contact group
 - time periods
2. Search "Hello"
3. Create an object named "Hello" and save

**Describe the results you received:**
The filter bar is empty instead of have "Hello"

**Describe the results you expected:**
Keep the last filter in the search bar

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by cgagnaire** [comment]
Solved at some point
