### ISSUE TITLE
Can't see Graphs 

### ISSUE THREAD

**Issue by barte91** [centreon/centreon#5618]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Centreon Web version:  2.8.12 

Centreon Engine version:  1.7.2 

Centreon Broker version: 3.0.8

OS: CentOS 6.5

**Describe the results you received:**
After I upgrade from Centreon 2.8.9 to 2.8.12 I can't see the graphs, in attachment what I see
![errorcentreon](https://user-images.githubusercontent.com/19166634/29925440-9f9bc4b4-8e60-11e7-957f-8eb4adb679cf.JPG)

And here the error_log of my Apache:
[Thu Aug 31 15:14:22 2017] [error] [client xxx.xxx.xxx.xxx] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found in /usr/share/centreon/www/class/centreonGraphService.class.php on line 228, referer: http://xxx.xxx.xxx.xxx/centreon/main.php?p=204&mode=0&svc_id=MMMMM;Ping
[Thu Aug 31 15:14:22 2017] [error] [client xxx.xxx.xxx.xxx] PHP Warning:  simplexml_load_string(): ERROR: can't make an xport without contents in /usr/share/centreon/www/class/centreonGraphService.class.php on line 228, referer: http://xxx.xxx.xxx.xxx/centreon/main.php?p=204&mode=0&svc_id=MMMMM;Ping
[Thu Aug 31 15:14:22 2017] [error] [client xxx.xxx.xxx.xxx] PHP Warning:  simplexml_load_string(): ^ in /usr/share/centreon/www/class/centreonGraphService.class.php on line 228, referer: http://xxx.xxx.xxx.xxx/centreon/main.php?p=204&mode=0&svc_id=MMMMM;Ping

**Describe the results you expected:**
See the Graphs

**Comment by lpinsivy** [comment]
Hi,

can you try to apply patch #5565

**Comment by barte91** [comment]
Hi,

I do the correction but the display can't see anymore... do you have a solution?

In attachment you can find the file I've modified.



[centreonGraphService.txt](https://github.com/centreon/centreon/files/1269451/centreonGraphService.txt)
[graphs.txt](https://github.com/centreon/centreon/files/1269450/graphs.txt)
[serviceDetails.txt](https://github.com/centreon/centreon/files/1269452/serviceDetails.txt)

**Comment by barte91** [comment]
Hi all,

I resolved, i delete all rrd file in folder metrics and status and now I cxan see the graphs.
Thanks a lot for a support,

Close the case
