### ISSUE TITLE
Disable STRICT SQL_mode for MySQL 5.7 and MariaDB 10.2

### ISSUE THREAD

**Issue by Dr-B0T** [centreon/centreon#5620]
Hello,

I've just install Centreon on CentOs 7 from repository, following the documentation.
Centreon and CentOs are Fresh install.

I can't create a service template. When I click save, it returns to the service template list, but the template is not created.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon.noarch / 2.8.12-7.el7.centos

**Centreon Engine version**: centreon-engine.x86_64 / 1.7.2-3.el7.centos

**Centreon Broker version**: centreon-broker.x86_64 / 3.0.8-1.el7.centos

**OS**: CentOS Linux release 7.3.1611 (Core)

**Additional environment details (AWS, VirtualBox, physical, etc.)**: VM on virtualbox 

**Steps to reproduce the issue:**
1. Install Centreon following the [documentation](https://documentation.centreon.com/docs/centreon/en/latest/installation/from_packages.html)
2. Go through install process in web browser
3. Click on Configuration, Services, Templates, Add
4. Fill alias and name, and save

**Describe the results you received:**
Return to Services Template list with the new template not created

**Describe the results you expected:**
Return to Services Template list with the new template created

**Additional information you think important (e.g. issue happens only occasionally):**

Log file : /var/log/centreon/sql-error.log 

`2017-09-03 22:53|0|0|DB Error: unknown error QUERY : INSERT INTO service (service_template_model_stm_id, command_command_id, timeperiod_tp_id, command_command_id2, timeperiod_tp_id2, service_description, service_alias, service_is_volatile, service_max_check_attempts, service_normal_check_interval, service_retry_check_interval, service_active_checks_enabled, service_passive_checks_enabled, service_obsess_over_service, service_check_freshness, service_freshness_threshold, service_event_handler_enabled, service_low_flap_threshold, service_high_flap_threshold, service_flap_detection_enabled, service_retain_status_information, service_retain_nonstatus_information, service_notification_interval, service_notification_options, service_notifications_enabled, contact_additive_inheritance, cg_additive_inheritance, service_use_only_contacts_from_host, service_stalking_options, service_first_notification_delay, service_recovery_notification_delay,service_comment, geo_coords, command_command_id_arg, command_command_id_arg2, service_register, service_activate, service_acknowledgement_timeout) VALUES ( NULL, NULL, NULL, NULL, NULL, 'test', 'test', '2', NULL, NULL, NULL, '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', NULL, NULL, '2', 0, 0, 'NULL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1',NULL)`

Running sql via command line :

use centreon;
sql request...
`ERROR 1265 (01000): Data truncated for column 'service_use_only_contacts_from_host' at row 1`

describe service;
```
+--------------------------------------+-----------------------+------+-----+---------+----------------+
| Field                                | Type                  | Null | Key | Default | Extra          |
+--------------------------------------+-----------------------+------+-----+---------+----------------+
...
| service_use_only_contacts_from_host  | enum('0','1')         | YES  |     | 0       |                |
...
+--------------------------------------+-----------------------+------+-----+---------+----------------+
```

The request try to insert 'NULL' on enum field.

/usr/share/centreon/www/include/configuration/configObject/service/DB-Func.php line 860 :

`isset($ret["service_use_only_contacts_from_host"]["service_use_only_contacts_from_host"]) && $ret["service_use_only_contacts_f     rom_host"]["service_use_only_contacts_from_host"] != null ? $rq .= "'".$ret["service_use_only_contacts_from_host"]["service_use_on     ly_contacts_from_host"]."', " : $rq .= "'NULL', ";`

Replacing 'NULL' by '0' fix the bug :)

**Comment by lpinsivy** [comment]
Hi,

did you enable strict mode on your MySQL server?

MariaDB [centreon]> SHOW GLOBAL VARIABLES LIKE "%strict%";
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| gtid_strict_mode           | OFF   |
| innodb_strict_mode         | OFF   |
| strict_password_validation | ON    |
+----------------------------+-------+

Regards,

**Comment by B-o-t** [comment]
Hello :)
Indeed, strict mode is activated, by default I guess. I've setup mariadb before installing Centreon

+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| gtid_strict_mode           | OFF   |
| innodb_strict_mode         | ON    |
| strict_password_validation | ON    |
+----------------------------+-------+

I will diasble it and try again.

Just to know, do you plan to modify the code anyway?

Regards,

**Comment by B-o-t** [comment]
I just made the modification, but still got the initial error :

`MariaDB [centreon]> SHOW GLOBAL VARIABLES LIKE "%strict%";
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| gtid_strict_mode           | OFF   |
| innodb_strict_mode         | OFF   |
| strict_password_validation | ON    |
+----------------------------+-------+
3 rows in set (0.002 sec)

MariaDB [centreon]> INSERT INTO service (service_template_model_stm_id, command_command_id, timeperiod_tp_id, command_command_id2, timeperiod_tp_id2, service_description, service_alias, service_is_volatile, service_max_check_attempts, service_normal_check_interval, service_retry_check_interval, service_active_checks_enabled, service_passive_checks_enabled, service_obsess_over_service, service_check_freshness, service_freshness_threshold, service_event_handler_enabled, service_low_flap_threshold, service_high_flap_threshold, service_flap_detection_enabled, service_retain_status_information, service_retain_nonstatus_information, service_notification_interval, service_notification_options, service_notifications_enabled, contact_additive_inheritance, cg_additive_inheritance, service_use_only_contacts_from_host, service_stalking_options, service_first_notification_delay, service_recovery_notification_delay,service_comment, geo_coords, command_command_id_arg, command_command_id_arg2, service_register, service_activate, service_acknowledgement_timeout) VALUES ( NULL, NULL, NULL, NULL, NULL, 'test', 'test', '2', NULL, NULL, NULL, '2', '2', '2', '2', NULL, '2', NULL, NULL, '2', '2', '2', NULL, NULL, '2', 0, 0, 'NULL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '1',NULL);
ERROR 1265 (01000): Data truncated for column 'service_use_only_contacts_from_host' at row 1`

**Comment by lpinsivy** [comment]
Hi,

Can you give me your schema of the centreon.service table?

Regards,

**Comment by B-o-t** [comment]
Hello,

This is the services schema :

MariaDB [centreon]> describe service;
```
+--------------------------------------+-----------------------+------+-----+---------+----------------+
| Field                                | Type                  | Null | Key | Default | Extra          |
+--------------------------------------+-----------------------+------+-----+---------+----------------+
| service_id                           | int(11)               | NO   | PRI | NULL    | auto_increment |
| service_template_model_stm_id        | int(11)               | YES  | MUL | NULL    |                |
| command_command_id                   | int(11)               | YES  | MUL | NULL    |                |
| timeperiod_tp_id                     | int(11)               | YES  | MUL | NULL    |                |
| command_command_id2                  | int(11)               | YES  | MUL | NULL    |                |
| timeperiod_tp_id2                    | int(11)               | YES  | MUL | NULL    |                |
| service_description                  | varchar(200)          | YES  | MUL | NULL    |                |
| service_alias                        | varchar(255)          | YES  |     | NULL    |                |
| display_name                         | varchar(255)          | YES  |     | NULL    |                |
| service_is_volatile                  | enum('0','1','2')     | YES  |     | 2       |                |
| service_max_check_attempts           | int(11)               | YES  |     | NULL    |                |
| service_normal_check_interval        | int(11)               | YES  |     | NULL    |                |
| service_retry_check_interval         | int(11)               | YES  |     | NULL    |                |
| service_active_checks_enabled        | enum('0','1','2')     | YES  |     | 2       |                |
| service_passive_checks_enabled       | enum('0','1','2')     | YES  |     | 2       |                |
| initial_state                        | enum('o','w','u','c') | YES  |     | NULL    |                |
| service_parallelize_check            | enum('0','1','2')     | YES  |     | 2       |                |
| service_obsess_over_service          | enum('0','1','2')     | YES  |     | 2       |                |
| service_check_freshness              | enum('0','1','2')     | YES  |     | 2       |                |
| service_freshness_threshold          | int(11)               | YES  |     | NULL    |                |
| service_event_handler_enabled        | enum('0','1','2')     | YES  |     | 2       |                |
| service_low_flap_threshold           | int(11)               | YES  |     | NULL    |                |
| service_high_flap_threshold          | int(11)               | YES  |     | NULL    |                |
| service_flap_detection_enabled       | enum('0','1','2')     | YES  |     | 2       |                |
| service_process_perf_data            | enum('0','1','2')     | YES  |     | 2       |                |
| service_retain_status_information    | enum('0','1','2')     | YES  |     | 2       |                |
| service_retain_nonstatus_information | enum('0','1','2')     | YES  |     | 2       |                |
| service_notification_interval        | int(11)               | YES  |     | NULL    |                |
| service_recovery_notification_delay  | int(11)               | YES  |     | NULL    |                |
| service_notification_options         | varchar(200)          | YES  |     | NULL    |                |
| service_notifications_enabled        | enum('0','1','2')     | YES  |     | 2       |                |
| contact_additive_inheritance         | tinyint(1)            | YES  |     | 0       |                |
| cg_additive_inheritance              | tinyint(1)            | YES  |     | 0       |                |
| service_inherit_contacts_from_host   | enum('0','1')         | YES  |     | 1       |                |
| service_use_only_contacts_from_host  | enum('0','1')         | YES  |     | 0       |                |
| service_first_notification_delay     | int(11)               | YES  |     | NULL    |                |
| service_acknowledgement_timeout      | int(11)               | YES  |     | NULL    |                |
| service_stalking_options             | varchar(200)          | YES  |     | NULL    |                |
| service_comment                      | text                  | YES  |     | NULL    |                |
| geo_coords                           | varchar(32)           | YES  |     | NULL    |                |
| command_command_id_arg               | text                  | YES  |     | NULL    |                |
| command_command_id_arg2              | text                  | YES  |     | NULL    |                |
| service_locked                       | tinyint(1)            | YES  |     | 0       |                |
| service_register                     | enum('0','1','2','3') | NO   |     | 0       |                |
| service_activate                     | enum('0','1')         | NO   |     | 1       |                |
+--------------------------------------+-----------------------+------+-----+---------+----------------+
```

**Comment by lpinsivy** [comment]
Ok your table schema is correct.

**Comment by B-o-t** [comment]
Actually I think this is because the request try to insert 'NULL' instead of NULL
I just tried by removing the singe quote, and it worked well ;)

**Comment by lpinsivy** [comment]
Yes but I have the same code with mysql  Ver 15.1 Distrib 10.1.19-MariaDB and it's work for me but yes it is strange to work with quote for enum('0','1') field type.

**Comment by acdmail** [comment]
It seems that Centos 7 is coming with maria db 10.3 which by default has the sql_mode set to some stricter settings this is leading to described issues in my install I was unable to create service templates & create commands without providing the graph template (was working before).
So as a workaround try to put sql_mode to '' as a fix most probably default mariadb install should be used and /var/log/centreon inspected to see where and what to correct in centreon sources

**Comment by lpinsivy** [comment]
@acdmail thank you for your feedback, we will modify the documentation

Regards,

**Comment by cgagnaire** [comment]
Strict mode is now handled in 20.04.x serie with MariaDB 10.3.
