### ISSUE TITLE
[2.8.12] Cannot create command if Graph Template is not selected

### ISSUE THREAD

**Issue by B-o-t** [centreon/centreon#5621]
Hello,

I've just install Centreon on CentOs 7 from repository, following the documentation.
Centreon and CentOs are Fresh install.

I can't create a command if I don't specify a Graph template (even if the help said "The optional definition of a graph template will be used as default graph template, when no other is specified."
When I click save, it returns to the commands list, but the command is not created.

**Centreon Web version**: centreon.noarch / 2.8.12-7.el7.centos

**Centreon Engine version**: centreon-engine.x86_64 / 1.7.2-3.el7.centos

**Centreon Broker version**: centreon-broker.x86_64 / 3.0.8-1.el7.centos

**OS**: CentOS Linux release 7.3.1611 (Core)

**Additional environment details (AWS, VirtualBox, physical, etc.)**: VM on virtualbox 

**Steps to reproduce the issue:**
1. Install Centreon following the [documentation](https://documentation.centreon.com/docs/centreon/en/latest/installation/from_packages.html)
2. Go through install process in web browser
3. Click on Configuration, Commands, one of  "Checks, Notifications, Discovery or Miscellaneous", Add
4. Fill Command Name, Command Line, and Save

**Describe the results you received:**
Return to Commands list with the new command not created

**Describe the results you expected:**
Return to Commands list with the new command created

**Additional information you think important (e.g. issue happens only occasionally):**

Log file : /var/log/centreon/sql-error.log 

`DB Error: unknown error QUERY : INSERT INTO command (command_name, command_line, enable_shell, command_example, command_type, graph_id, connector_id, command_comment, command_activate) VALUES ('test', 'testcmd', '0', '', '2', '', NULL, '', '1')`

Running sql via command line :

use centreon;
sql request...
`ERROR 1366 (22007): Incorrect integer value: '' for column 'graph_id' at row 1`

describe command;
```
+------------------+------------------+------+-----+---------+----------------+
| Field            | Type             | Null | Key | Default | Extra          |
+------------------+------------------+------+-----+---------+----------------+
...
| graph_id         | int(11)          | YES  |     | NULL    |                |
...
+------------------+------------------+------+-----+---------+----------------+
```

The request try to insert '' on interger field.

/usr/share/centreon/www/include/configuration/configObject/command/DB-Func.php line 228 :

`'" . $ret["graph_id"] . "',`

Replacing by : 

`" . (isset($ret["graph_id"]) && !empty($ret["graph_id"]) ? "'" . $ret['graph_id'] . "'" : "NULL") . ",`

**Same for updating :**

/usr/share/centreon/www/include/configuration/configObject/command/DB-Func.php line 183 :

``"`graph_id` = '" . $pearDB->escape($ret["graph_id"]) . "', " .``

Replacing by : 

``"`graph_id` = " . (isset($ret["graph_id"]) && !empty($ret["graph_id"]) ? "'" . $pearDB->escape($ret['graph_id']) . "'"     : "NULL") . ", " .``

fix the bugs :)

**Comment by lpinsivy** [comment]
should be linked to #5620

**Comment by B-o-t** [comment]
Hi,

On this one, when disabling strict mode, the command is added

Regards
