### ISSUE TITLE
[2.8.8] Every services and hosts goes to Unknown status. Broker 3.0.8.

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon#5622]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.8

**Centreon Engine version**:  1.7.2

**Centreon Broker version**: 3.0.8

**OS**: Oracle Linux 7.3

**Additional environment details (AWS, VirtualBox, physical, etc.):** Virtual

**Steps to reproduce the issue:**
It is a reopened issue. We thought 3.0.8 broker update will solve this issue but unfortunately not solved.
1. Sometime every tests and hosts goes to Unknown status
2. No error in log files.
Fixing:
Need 1 or 2 cbd and centengine restart and the checks will come back

**Describe the results you received:**
 
![](https://user-images.githubusercontent.com/25457811/29810962-20245f08-8ca2-11e7-95d4-9f822d6ee512.png)

**Describe the results you expected:**

It should be good if it will be never happen in the future.

**Comment by lpinsivy** [comment]
linked to #5609
