### ISSUE TITLE
[2.8.12] Bad metric label in Meta service graphs

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#5629]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.12

**Centreon Engine version**:  1.7.2

**Centreon Broker version**:  3.0.8

**OS**:  CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical

**Steps to reproduce the issue:**
1. Define a meta service with perfdata
2. look at the graph
3.

**Describe the results you received:**
The metric is always called "value"

**Describe the results you expected:**
Before the metric name was the same as the metric selected for the calculation.
I would like the same behavior as before

**Additional information you think important (e.g. issue happens only occasionally):**
Here is a screenshot of you demo site, showing the problem.
![sans titre](https://user-images.githubusercontent.com/2464712/30069948-53391062-9262-11e7-9215-c07ebe54de3a.png)

**Comment by BenoitPoulet** [comment]
Hello, 

Still present in 2.8.15

**Comment by lpinsivy** [comment]
@BenoitPoulet The demo have some issues with MetaService linked to #5651

**Comment by mvisini** [comment]
Désolé pour le doublon, je n'étais pas parvenu jusqu'à ce ticket dans mes recherches.
Avez-vous une date de correctif ?

**Comment by lpinsivy** [comment]
The issue is from the plugin itself, not Centreon Web: https://github.com/centreon/centreon-plugins/issues/874

**Comment by mvisini** [comment]
Ah ok merci ! La modif a été effectuée, un reload de service est nécessaire ensuite ?

**Comment by lpinsivy** [comment]
Oui il y a un peu de traitement:

1. Récupérer l'index via l'ID du meta-service

```
MariaDB [centreon_storage]> select * from index_data where service_id = 2862;
+-------+--------------+---------+---------------------+------------+----------------+---------+--------+--------+---------+-----------------+--------------+-----------+---------------+
| id    | host_name    | host_id | service_description | service_id | check_interval | special | hidden | locked | trashed | must_be_rebuild | storage_type | to_delete | rrd_retention |
+-------+--------------+---------+---------------------+------------+----------------+---------+--------+--------+---------+-----------------+--------------+-----------+---------------+
| 85709 | _Module_Meta |     218 | meta_13             |       2862 |           NULL | 0       | 0      | 0      | 0       | 0               | 2            |         0 |          NULL |
+-------+--------------+---------+---------------------+------------+----------------+---------+--------+--------+---------+-----------------+--------------+-----------+---------------+
```

2. Récupérer les ID des metrics associées:

```
MariaDB [centreon_storage]> select * from metrics where index_id = 85709;
+-----------+----------+-------------+------------------+-----------+---------------+------+----------+---------------------+------+----------+---------------------+--------+------+------+--------+-----------+
| metric_id | index_id | metric_name | data_source_type | unit_name | current_value | warn | warn_low | warn_threshold_mode | crit | crit_low | crit_threshold_mode | hidden | min  | max  | locked | to_delete |
+-----------+----------+-------------+------------------+-----------+---------------+------+----------+---------------------+------+----------+---------------------+--------+------+------+--------+-----------+
|     14840 |    85709 | load1       | 0                |           |          0.92 |    1 |        0 |                   0 |   10 |        0 |                   0 | 0      | NULL | NULL | NULL   |         0 |
|     14839 |    85709 | value       | 0                |           |           1.1 |    1 |        0 |                   0 |   10 |        0 |                   0 | 0      | NULL | NULL | NULL   |         0 |
+-----------+----------+-------------+------------------+-----------+---------------+------+----------+---------------------+------+----------+---------------------+--------+------+------+--------+-----------+
```

3. Merger les anciennes données avec les nouvelles (14839 -> 14840)

`MariaDB [centreon_storage]> UPDATE data_bin SET id_metric = 14840 WHERE id_metric = 14839;`

4. Supprimer l'ancienne entrée 'value'

`MariaDB [centreon_storage]> DELETE FROM metrics WHERE metric_id = 14839;`


5. Régénérer le graphique.

avant:
![screenshot at fevr 02 10-18-08](https://user-images.githubusercontent.com/3351916/35725698-973eac98-0802-11e8-9ec5-8d99b3892f68.png)

après:
![screenshot at fevr 02 10-19-25](https://user-images.githubusercontent.com/3351916/35725704-9be1f48a-0802-11e8-9b26-333b042ca599.png)

**Comment by mvisini** [comment]
Merci pour les manip :)
Après les avoir réalisés sur un meta service.
=> OK pour les données récupérée **jusqu'à** l'instant _t_ elles ont bien repris le bon label
=> En revanche, **à partir** de l'instant _t_ elles apparaissent de nouveau en _value_

Ça règle donc le problème pour les données passées mais par pour les futures.

Mathieu

**Comment by mvisini** [comment]
![image](https://user-images.githubusercontent.com/19703479/35728272-5e5a979e-080b-11e8-9e05-f81ef68f9259.png)

**Comment by lpinsivy** [comment]
Il faut restart Centreon Broker je pense

**Comment by mvisini** [comment]
Malheureusement cela ne change rien, j'ai toujours ma métrique _value_ qui revient dans ma table.
Et son id s'incrémente, précédemment 22835, elle devient maintenant 22836

![image](https://user-images.githubusercontent.com/19703479/35734278-e1db781c-0820-11e8-8652-f43589fed9bb.png)

**Comment by lpinsivy** [comment]
As tu des données de rétention pour tes broker ?

**Comment by mvisini** [comment]
oui

**Comment by lpinsivy** [comment]
Je pense que comme broker à encore des données de rétention, il va continuer de créer la métrique "value".

Attends la fin de la lecture des fichiers de rétention, coupe Broker sur le serveur Central, applique la procédure.

**Comment by mvisini** [comment]
Ok je regarde en ce sens.
Sinon ce problème sera-t-il réglé à la prochaine MAJ ?

**Comment by lpinsivy** [comment]
Cela vient du plugin. Il faut donc attendre la modification du plugin puis de la génération du nouveau paquet centreon-plugin-meta

**Comment by BenoitPoulet** [comment]
Bonjour,

Au 31/07, paquet : centreon-plugin-meta-2.8.24-1.el7.centos.noarch

Bug tjs présent.

**Comment by cgagnaire** [comment]
This has been fixed in the plugin here https://github.com/centreon/centreon-plugins/pull/882.
