### ISSUE TITLE
centreon-pp-manager doesn't appear

### ISSUE THREAD

**Issue by romnvll** [centreon/centreon#5631]
Hello, 
i try to use plugin pack, but i can't see module menu under administration .
thank you

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web-2.8.12-7.el6.noarch

**Centreon Engine version**: 
centreon-engine-1.7.2-3.el6.x86_64
**Centreon Broker version**: 
centreon-broker-cbd-3.0.8-1.el6.x86_64
**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Administration --> plugin pack --> Setup --> blankpage
2.
3.

**Describe the results you received:**
The sql errors :
==> /var/log/centreon/sql-error.log <==
2017-09-06 09:26|0|0|DB Error: no such table QUERY : SELECT slug, name FROM mod_ppm_categories ORDER BY name

Apache Errors:
[Wed Sep 06 10:11:22 2017] [error] [client 192.168.X.X] PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/modules/centreon-pp-manager/core/manager/functions.php on line 0, referer: http://192.168.x.x/centreon/main.php?p=507

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Sims24** [comment]
Hi @romnvll 

Did you upgrade your pp manager through Administration > Extension ? (green arrow on the right of the pp-manager line). 

Thanks

**Comment by romnvll** [comment]
Hello @Sims24 
Thank you for your anwser, but pp manager doesn't appear too in extension


Graph Monitoring | Widget for displaying RRD graphs | 1.5.2 | Centreon |  
Host Monitoring | Widget for displaying host monitoring information | 1.6.0 | Centreon |  
Hostgroup Monitoring | Widget for displaying hostgroup monitoring information | 1.6.0 | Centreon |  
Service Monitoring | Widget for displaying service monitoring information | 1.6.0 | Centreon |  
Servicegroup Monitoring | Widget for displaying servicegroup monitoring information | 1.6.0 | Centreon |

**Comment by lpinsivy** [comment]
Hi,

You use wrong menu, please use "Administration > Extensions > Modules"

Regards,

**Comment by Sims24** [comment]
My bad thanks @lpinsivy !

**Comment by romnvll** [comment]
Thank you, but Extensions > modules doesn't appear too 
![image](https://user-images.githubusercontent.com/1440006/30105397-be9c38ac-92f8-11e7-8b06-c76b96a6e1cd.png)

**Comment by lpinsivy** [comment]
@romnvll do you have admin account? may be you can't access to "Modules" menu due to your ACL.

**Comment by romnvll** [comment]
@lpinsivy 
yes it's an admin account, can you give me the id page ? may be i can put in the url ...

**Comment by lpinsivy** [comment]
No you can't and you need right to access to this menu.

You have to contact your Centreon administrator.

**Comment by romnvll** [comment]
i'm the centreon administrator, and i haven't got any acl.

**Comment by lpinsivy** [comment]
Sorry.

What is the result of this SQL request on centreon database.

select * from topology where topology_parent = 507;

**Comment by romnvll** [comment]
there is the result :
MariaDB [centreon]> select * from topology where topology_parent = 507;
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
| topology_id | topology_name | topology_parent | topology_page | topology_order | topology_group | topology_url                                        | topology_url_opt | topology_popup | topology_modules | topology_show | topology_style_class | topology_style_id | topology_OnClick | readonly |
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
|         239 | Widgets       |             507 |          NULL |              2 |             30 | NULL                                                | NULL             | NULL           | NULL             | 1             | NULL                 | NULL              | NULL             | 1        |
|         240 | Widgets       |             507 |         50703 |             30 |              1 | ./include/options/oreon/widgets/widgets.php         | NULL             | NULL           | NULL             | 1             | NULL                 | NULL              | NULL             | 1        |
|         261 | Plugin packs  |             507 |          NULL |              3 |             40 | NULL                                                | NULL             | NULL           | NULL             | 1             | NULL                 | NULL              | NULL             | 1        |
|         262 | Setup         |             507 |         50704 |             40 |             40 | ./modules/centreon-pp-manager/core/manager/main.php | NULL             | NULL           | NULL             | 1             | NULL                 | NULL              | NULL             | 1        |
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+

**Comment by lpinsivy** [comment]
Your configuration is not correct in 'centreon' database.

Can you check if no one delete entries in topology table using MariaDB history?

Configuration must by:

MariaDB [centreon]> select * from topology where topology_parent = 507;
+-------------+------------------+-----------------+---------------+----------------+----------------+------------------------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
| topology_id | topology_name    | topology_parent | topology_page | topology_order | topology_group | topology_url                                                     | topology_url_opt | topology_popup | topology_modules | topology_show | topology_style_class | topology_style_id | topology_OnClick | readonly |
+-------------+------------------+-----------------+---------------+----------------+----------------+------------------------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
|         111 | Modules          |             507 |         50701 |             10 |              1 | ./include/options/oreon/modules/modules.php                      | NULL             | NULL           | NULL             | 1             | NULL                 | NULL              | NULL             | 1        |
|         228 | Dynamic Services |             507 |          NULL |              0 |             11 | NULL                                                             | NULL             | 0              | 0                | 1             | NULL                 | NULL              | NULL             | 1        |
|         229 | Configure        |             507 |         50711 |             10 |             11 | ./modules/centreon-dsm/core/configuration/services/slots.php     | NULL             | 0              | 0                | 1             | NULL                 | NULL              | NULL             | 1        |
|         258 | Modules Options  |             507 |          NULL |              0 |             20 | NULL                                                             | NULL             | 0              | 0                | 1             | NULL                 | NULL              | NULL             | 1        |
|         296 | Widgets          |             507 |          NULL |              2 |             30 | NULL                                                             | NULL             | NULL           | NULL             | 1             | NULL                 | NULL              | NULL             | 1        |
|         422 | Widgets          |             507 |          NULL |              2 |             30 | NULL                                                             | NULL             | NULL           | NULL             | 1             | NULL                 | NULL              | NULL             | 1        |
|         423 | Widgets          |             507 |         50703 |             30 |              1 | ./include/options/oreon/widgets/widgets.php                      | NULL             | NULL           | NULL             | 1             | NULL                 | NULL              | NULL             | 1        |
|         511 | Map 4            |             507 |          NULL |              0 |             19 | NULL                                                             | NULL             | 0              | 0                | 1             | NULL                 | NULL              | NULL             | 1        |
|         512 | Options          |             507 |         50788 |             10 |             19 | ./modules/centreon-map4-web-client/views/options/listOptions.php | NULL             | 0              | 0                | 1             | NULL                 | NULL              | NULL             | 1        |
|         533 | Subscription     |             507 |         50707 |             40 |              1 | ./modules/centreon-license-manager/frontend/app/index.php        | NULL             | 0              | 1                | 1             | NULL                 | NULL              | NULL             | 1        |
+-------------+------------------+-----------------+---------------+----------------+----------------+------------------------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+

**Comment by romnvll** [comment]
Hello Laurent,
thank you very much for your answer
there is my sql request :
select * from topology where topology_parent = 507;
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
| topology_id | topology_name | topology_parent | topology_page |
topology_order | topology_group | topology_url
           | topology_url_opt | topology_popup | topology_modules |
topology_show | topology_style_class | topology_style_id | topology_OnClick
| readonly |
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
|         239 | Widgets       |             507 |          NULL |
   2 |             30 | NULL
 | NULL             | NULL           | NULL             | 1             |
NULL                 | NULL              | NULL             | 1        |
|         240 | Widgets       |             507 |         50703 |
  30 |              1 | ./include/options/oreon/widgets/widgets.php
| NULL             | NULL           | NULL             | 1             |
NULL                 | NULL              | NULL             | 1        |
|         261 | Plugin packs  |             507 |          NULL |
   3 |             40 | NULL
 | NULL             | NULL           | NULL             | 1             |
NULL                 | NULL              | NULL             | 1        |
|         262 | Setup         |             507 |         50704 |
  40 |             40 | ./modules/centreon-pp-manager/core/manager/main.php
| NULL             | NULL           | NULL             | 1             |
NULL                 | NULL              | NULL             | 1        |
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+

so ... you haven't got "Plugin packs"

2017-09-07 10:22 GMT+02:00 Laurent Pinsivy <notifications@github.com>:

**Comment by lpinsivy** [comment]
Can you give me the result of:

# rpm -qa | grep -i centreon | egrep -v "(pack|plugin|widget)" | sort

**Comment by romnvll** [comment]
Thank you for your help ...

[root@centreon ~]# rpm -qa | grep -i centreon | egrep -v
"(pack|plugin|widget)" | sort
centreon-2.8.12-7.el6.noarch
centreon-base-config-centreon-engine-2.8.12-7.el6.noarch
centreon-broker-3.0.8-1.el6.x86_64
centreon-broker-cbd-3.0.8-1.el6.x86_64
centreon-broker-cbmod-3.0.8-1.el6.x86_64
centreon-broker-core-3.0.8-1.el6.x86_64
centreon-broker-storage-3.0.8-1.el6.x86_64
centreon-clib-1.4.2-1.el6.x86_64
centreon-common-2.8.12-7.el6.noarch
centreon-connector-1.1.2-1.el6.x86_64
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-engine-1.7.2-3.el6.x86_64
centreon-engine-daemon-1.7.2-3.el6.x86_64
centreon-engine-extcommands-1.7.2-3.el6.x86_64
centreon-license-manager-1.0.1-3.el6.noarch
centreon-nagvis-1.1.1-3.el6.noarch
centreon-perl-libs-2.8.12-7.el6.noarch
centreon-poller-centreon-engine-2.8.12-7.el6.noarch
centreon-pp-manager-2.2.0-4.el6.noarch
centreon-release-3.4-4.el6.noarch
centreon-syslog-frontend-1.5.4-1.el6.noarch
centreon-syslog-server-1.2.5-6.el6.noarch
centreon-trap-2.8.12-7.el6.noarch
centreon-web-2.8.12-7.el6.noarch


2017-09-08 14:11 GMT+02:00 Laurent Pinsivy <notifications@github.com>:

**Comment by lpinsivy** [comment]
Can you execute this request on 'centreon' database:

INSERT INTO topology VALUES(NULL, 'Modules', 507, 50701, 10, 1 './include/options/oreon/modules/modules.php', NULL, NULL, NULL, 1, NULL, NULL, NULL, 1);

**Comment by romnvll** [comment]
Thank you for your answer .

i don't know why i have some issues into my database ....

INSERT INTO topology VALUES(NULL, 'Modules', 507, 50701, 10, 1
'./include/options/oreon/modules/modules.php', NULL, NULL, NULL, 1, NULL,
NULL, NULL, 1);

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual
that corresponds to your MariaDB server version for the right syntax to use
near ''./include/options/oreon/modules/modules.php', NULL, NULL, NULL, 1,
NULL, NULL, ' at line 1



2017-09-08 17:55 GMT+02:00 Laurent Pinsivy <notifications@github.com>:

**Comment by romnvll** [comment]
query is ok ... sorry
missing "," between "1" and "include"

but my blank page stil alive :(

[image: Images intégrées 1]

2017-09-11 9:59 GMT+02:00 Vallee Romain <vallee.romain@gmail.com>:

**Comment by lpinsivy** [comment]
Did you have access to "Administration > Extensions > Modules" menu?

**Comment by romnvll** [comment]
Thank you very much for your help.
But no, i can't see Modules menu
![image](https://user-images.githubusercontent.com/1440006/30277840-3b46f3f6-9709-11e7-8124-fd9484ef6693.png)

**Comment by lpinsivy** [comment]
Can you give me the result of "select * from topology where topology_parent = 507;" request to be sure that information is correct in DB?

**Comment by romnvll** [comment]
yes of course ...

MariaDB [centreon]> select * from topology where topology_parent = 507;
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
| topology_id | topology_name | topology_parent | topology_page |
topology_order | topology_group | topology_url
           | topology_url_opt | topology_popup | topology_modules |
topology_show | topology_style_class | topology_style_id | topology_OnClick
| readonly |
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
|         239 | Widgets       |             507 |          NULL |
   2 |             30 | NULL
 | NULL             | NULL           | NULL             | 1             |
NULL                 | NULL              | NULL             | 1        |
|         240 | Widgets       |             507 |         50703 |
  30 |              1 | ./include/options/oreon/widgets/widgets.php
| NULL             | NULL           | NULL             | 1             |
NULL                 | NULL              | NULL             | 1        |
|         261 | Plugin packs  |             507 |          NULL |
   3 |             40 | NULL
 | NULL             | NULL           | NULL             | 1             |
NULL                 | NULL              | NULL             | 1        |
|         262 | Setup         |             507 |         50704 |
  40 |             40 | ./modules/centreon-pp-manager/core/manager/main.php
| NULL             | NULL           | NULL             | 1             |
NULL                 | NULL              | NULL             | 1        |
|         314 | Modules       |             507 |         50701 |
  10 |              1 | ./include/options/oreon/modules/modules.php
| NULL             | NULL           | NULL             | 0             |
NULL                 | NULL              | NULL             | 0        |
+-------------+---------------+-----------------+---------------+----------------+----------------+-----------------------------------------------------+------------------+----------------+------------------+---------------+----------------------+-------------------+------------------+----------+
5 rows in set (0.00 sec)


do you think it's an schema issue ?

2017-09-12 12:16 GMT+02:00 Laurent Pinsivy <notifications@github.com>:

**Comment by lpinsivy** [comment]
Ok the field topology_show don't have correct value:

UPDATE topology SET topology_show = '1' WHERE topology_page = '50701' AND topology_name = "Modules";

**Comment by romnvll** [comment]
Whaooouuu !!!
![image](https://user-images.githubusercontent.com/1440006/30323920-5f211066-97bf-11e7-86ff-063e223fbe75.png)

![image](https://user-images.githubusercontent.com/1440006/30323996-acde6cfe-97bf-11e7-96b5-570a0cd908d2.png)

i can begin to use the plugin pack !!!
thank you very very much Mister Ipinsivy :)

**Comment by romnvll** [comment]
so another issue :(
i fallow this guide
https://documentation-fr.centreon.com/docs/centreon/en/2.8.x/configuration_guide/imp/index.html#impconfiguration

and i don't have the "squarre" like this screenshot
![image](https://user-images.githubusercontent.com/1440006/30324680-36cf5cfa-97c2-11e7-9f88-3babfffa0031.png)

and in my apache log :
==> /var/log/httpd/error_log <==
[Tue Sep 12 13:39:52 2017] [error] [client 192.168.15.33] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/centreon/www/modules/centreon-pp-manager/webServices/rest/centreon_pp_manager_pluginpack.class.php on line 152, referer: http://xxx.xxx.xxx.xxx/centreon/main.php?p=65001
