### ISSUE TITLE
Object TIMEPERIOD not found in Centreon API.

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#5637]
Centreon 2.8.12
Centreon Engine 1.7.2
Centreon Broker 3.0.8

```
$ centreon -u user -p pass -o TIMEPERIOD -a show
Object TIMEPERIOD not found in Centreon API.
```

same with Centreon 2.7.7
Centreon Engine 1.5.1
Centreon Broker 2.11.5

(`centreon -V` reports "Centreon CLAPI version undefined" in both versions, not sure if that has any bearing on this)

**Comment by lpinsivy** [comment]
Should by TP and not TIMEPERIOD

Regards,

**Comment by btassite** [comment]
Aha! :) Then I guess the ticket should be changed to "Documentation change request" for these:
https://documentation.centreon.com/docs/centreon-clapi/en/latest/objects/time_periods.html
https://github.com/centreon/centreon-clapi/blob/master/doc/objects/time_periods.rst

**Comment by chgautier** [comment]
Validated in PR #5843
