### ISSUE TITLE
Filter field does not work in service groups monitoring screen

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#564]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 6462, https://forge.centreon.com/issues/6462
Original Date: 2015-07-09

---

Hello,

I'm using Centreon 2.6.1.

I defined lots of service groups and I have to filter my monitoring page with the search field but it does not work.
I'm able to confirm that this problem exists for all service groups monitoring page.

Best regards.

**Comment by julienmathis** [comment]
@Dacchi It's ok now ?

Thanks to update the status of this ticket
