### ISSUE TITLE
Macro NOTIFICATIONRECIPIENTS ignores notification times

### ISSUE THREAD

**Issue by masgo** [centreon/centreon#5646]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.12 

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Use the macro NOTIFICATIONRECIPIENTS in a notification command
2. Have two users as recipients for a host
3. Have one user set to receive notifications 24/7 and the other to working hours only
4. Have a DOWN event outside of the working hours

**Describe the results you received:**
Only the first user got notified. The second user was not notified because it was outside of his notification period. (worked as expected)
The macro NOTIFICATIONRECIPIENTS used to notify the first user contains both names. This is wrong, since the second user was not notified.

**Describe the results you expected:**
NOTIFICATIONRECIPIENTS should only contain the users which really get notified.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

It is impossible to do this because macro contains configuration and are build during the read of configuration

**Comment by masgo** [comment]
:-( okay. Too bad, since this would be really nice. 

Maybe you can update the documentation to reflect that the macro outputs every recipient which is configured (regardless if the notification is actually send out).
