### ISSUE TITLE
Virtual metrics not display in list of curves

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5647]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.12

**Steps to reproduce the issue:**
1. Create a virtual metric for a chart
2. Go to "Monitoring  >  Performances  >  Graphs"
3. Select chart

**Describe the results you received:**

virtual metric curve is displayed but not it name in list of curves

**Describe the results you expected:**

See the virtual metric curve name in list of curve

<img width="1077" alt="screenshot at sept 08 11-19-10" src="https://user-images.githubusercontent.com/3351916/30204945-8cd80018-9487-11e7-9119-cb70968029a6.png">

**Comment by florian-asche** [comment]
And in the Graph-Widget from Dashboard the line is displayed but legend missing. 
![bildschirmfoto_2017-10-28_00-35-35](https://user-images.githubusercontent.com/2785700/32127589-1b48be84-bb78-11e7-83e5-49a808ed95d1.png)

**Comment by lpinsivy** [comment]
will be corrected by #7676
