### ISSUE TITLE
Timeout centcore

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#5657]
Hi,

I do not understand the closing of this issue (https://github.com/centreon/centreon/issues/4153), I agree that you use json. But you made like a "cat" to copy the json?

See line 254 of centcore.pm
https://github.com/centreon/centreon/blob/2.8.x/lib/perl/centreon/script/centcore.pm

```
        # Copy the stat file into a buffer
        my $statistics_file = $data->{cache_directory} . "/" . $data->{config_name} . "-stats.json";
        $cmd = "$self->{ssh} -q $server_info->{ns_ip_address} -p $port 'cat \"" . $statistics_file . "\" > $statPipe'";
        ($lerror, $stdout) = centreon::common::misc::backtick(command => $cmd,
                                                              logger => $self->{logger},
                                                              timeout => $self->{cmd_timeout}
);
```

Regards

**Comment by lpinsivy** [comment]
Sorry I made a mistake.

But this code indicates that a timeout "timeout => $self->{cmd_timeout}" is used during the "cat" command.

It didn't work?

**Comment by jben94** [comment]
Hi @lpinsivy,

This timeout has the effect on the local server (with the command: "ssh -q ...") and not on the remote server (with the command: "cat ...").

Sometimes the command remains blocked on the remote server, not locally. 
On the remote server we have reached the maximum allowed TCP connections and that blocked all the network connections of the server.

Regards
