### ISSUE TITLE
No reports/graphs in Centreon 8.4.12-7 on Centos 7

### ISSUE THREAD

**Issue by florism** [centreon/centreon#5666]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon-web version**:  2.8.12-7

**Centreon Engine version**: 1.7.2-3

**Centreon Broker version**: 3.0.8-1

**OS**: Centos 7.3.1611

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical installation from Centreon yum repository

**Steps to reproduce the issue:**
1.go to  Monitoring->performances->Graphs is empty
2.go to Reporting->dashboard->Host all undetermined
3.

**Describe the results you received:**
empty, undetermined see above

**Describe the results you expected:**
Show graphs for ping, currently no services attached.
Show Linux snmp information information in reporting

check on host is base_host_alive
template is OS_Linux-SNMP

**Additional information you think important (e.g. issue happens only occasionally):**
In monitoring->performances-> graphs the javascript buttons next to the refresh buttons
do not show up (swithCols 2 and 3) Also the refresh button does not seem to refresh anything.
/var/lib/centreon/status is empty.
Monitoring->Status details->Hosts shows the host as up
Log file /var/log/centreon-broker/central-rrd-master.log has the following line stats: FIFO thread will exit due to the following error: FIFO fd has pending error in it.

**Comment by florism** [comment]
Fixed this by adding an additional output for rrd, which was not in the configuration

**Comment by lpinsivy** [comment]
So one Centreon Broker output was not present after fresh Centreon installation?

**Comment by florism** [comment]
That is correct, I've been pulling my hairs on that.
