### ISSUE TITLE
2.8.12 / 2.8.13 - Acknoledge Problem

### ISSUE THREAD

**Issue by ptitpopey** [centreon/centreon#5672]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.12

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: CentOS release 6.9 (Final)

**Détails**:
Impossible d'acquitter un service depuis le menu déroulement "Plus d'action..."
Pour pouvoir acquitter un service il faut aller dans le service puis cliquer sur Acquittés

**Logs : /var/log/centreon/centcore.log**
2017-09-14 12:25:59 - Ip address not defined for poller 0

**Comment by ptitpopey** [comment]
Logs : /var/log/centreon/centcore.log
2017-09-14 12:25:59 - Ip address not defined for poller 0

**Comment by ptitpopey** [comment]
Problème trouvé. Il s'agit d'un problème de path dans le fichier de configuration /etc/centreon/conf.pm.

**Ancien fichier :**
#############################################
'# File Added by Centreon
#

$centreon_config = {
       VarLib => "/var/lib/centreon",
       CentreonDir => "/usr/share/centreon/",
       "centreon_db" => "centreon",
       "centstorage_db" => "centreon_storage",
       "db_host" => "localhost:3306",
       "db_user" => "centreon",
       "db_passwd" => 'MDP'
};

'# Central or Poller ?
$instance_mode = "central";

'# Centreon Centcore Command File
$cmdFile = "/var/lib/centreon/centcore.cmd";

'# Deprecated format of Config file.
$mysql_user = "centreon";
$mysql_passwd = 'MDP';
$mysql_host = "localhost:3306";
$mysql_database_oreon = "centreon";
$mysql_database_ods = "centreon_storage";

1;

**Nouveau fichier :**
#############################################
'# File Added by Centreon
#

$centreon_config = {
       VarLib => "/var/lib/centreon/",
       CentreonDir => "/usr/share/centreon/",
       "centreon_db" => "centreon",
       "centstorage_db" => "centreon_storage",
       "db_host" => "localhost:3306",
       "db_user" => "centreon",
       "db_passwd" => "centreon"
};

# Central or Poller ?
$instance_mode = "central";
$cmdFile = "/var/lib/centreon-engine/rw/centengine.cmd";


**La différence vient du path de la varibale $cmdFile qui change :**
$cmdFile = "/var/lib/centreon/centcore.cmd"; NOK
$cmdFile = "/var/lib/centreon-engine/rw/centengine.cmd"; OK

**Comment by ptitpopey** [comment]
Le changement de configuration a permis de réaliser des acquittements sur certains services. Le problème se pose toujours.

**Comment by ptitpopey** [comment]
**Debug strace**
nanosleep({1, 0}, 0x7ffd64bb05d0)       = 0
stat("/var/lib/centreon//centcore.cmd", {st_mode=S_IFREG|0644, st_size=215, ...}) = 0
stat("/var/lib/centreon//centcore.cmd_read", 0x1d78130) = -1 ENOENT (No such file or directory)
stat("/var/lib/centreon//centcore.cmd_read", 0x1d78130) = -1 ENOENT (No such file or directory)
stat("/var/lib/centreon//centcore.cmd", {st_mode=S_IFREG|0644, st_size=215, ...}) = 0
rename("/var/lib/centreon//centcore.cmd", "/var/lib/centreon//centcore.cmd_read") = 0
open("/var/lib/centreon//centcore.cmd_read", O_RDONLY) = 6
ioctl(6, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7ffd64bb01b0) = -1 ENOTTY (Inappropriate ioctl for device)
lseek(6, 0, SEEK_CUR)                   = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=215, ...}) = 0
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
read(6, "EXTERNALCMD:0:[1505465161] ACKNO"..., 4096) = 215
read(6, "", 4096)                       = 0
poll([{fd=5, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
write(5, "O\0\0\0\3SELECT * FROM `nagios_serve"..., 83) = 83
read(5, "\1\0\0\1\30<\0\0\2\3def\10centreon\rnagios_se"..., 16384) = 2135
poll([{fd=5, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
write(5, "^\0\0\0\3SELECT nagios_user FROM `cf"..., 98) = 98
read(5, "\1\0\0\1\1H\0\0\2\3def\10centreon\ncfg_nagio"..., 16384) = 99
poll([{fd=5, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
write(5, "_\0\0\0\3SELECT command_file FROM `c"..., 99) = 99
read(5, "\1\0\0\1\1J\0\0\2\3def\10centreon\ncfg_nagio"..., 16384) = 101
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2945, ...}) = 0
write(4, "2017-09-15 10:46:01 - Ip address"..., 58) = 58
close(6)                                = 0
unlink("/var/lib/centreon//centcore.cmd_read") = 0
stat("/var/lib/centreon//centcore/", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
open("/var/lib/centreon//centcore/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 6
getdents(6, /* 2 entries */, 32768)     = 48
getdents(6, /* 0 entries */, 32768)     = 0
close(6)                                = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], SA_RESTORER, 0x394a60f7e0}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0

**Comment by ptitpopey** [comment]
**Le menu "Plus d'action..." Services : Acquitter pose problème et n'arrive pas à determiner le poller affecté au service. Dans mon cas il indique le poller 0 alors que le service est sur le poller 2.**

**Comment faire pour corriger ce problème ?**

**Comment by ptitpopey** [comment]
Cause du problème trouvée : 

Dans le fichier centreonExternalCommand.class.php vers la ligne 264, une nouvelle condition est apparue depuis la version 2.7.11.

Cette condition empêche d'acquitter un host ayant un hostname composé que de chiffre.
Dans ce cas la requête SQL pour rechercher l'instance_id se base sur le host_id et non sur le hostname.

if (preg_match("/^[0-9]*$/", $host)) {
            $DBRESULT = $this->DBC->query("SELECT instance_id FROM hosts WHERE hosts.host_id = '" .
                CentreonDB::escape($host) . "' AND hosts.enabled = '1'");
        } else {
            $DBRESULT = $this->DBC->query("SELECT instance_id FROM hosts WHERE hosts.name = '" .
                CentreonDB::escape($host) . "' AND hosts.enabled = '1' LIMIT 1");
        }

**Comment by ptitpopey** [comment]
Voici la différence de code entre les versions 2.7.11 et 2.8.12.

Ce changement de code entraine l'impossibilité d'acquitter des services dans le host dispose d'un hostname composé seulement de chiffre.

**old version : 2.7.11**

*file : www/include/monitoring/external_cmd/functions.php*

    function acknowledgeService($param) {
    ....
        $flg = ......, GetMyHostPoller($pearDB, urldecode($param["host_name"])));

*file : www/include/common/common-Func.php*

    function GetMyHostPoller($pearDB, $host_name = NULL) {
    if (!isset($host_name))
    return 0;
    $DBRESULT = $pearDB->query("SELECT id FROM nagios_server, ns_host_relation, host WHERE host.host_name = '".CentreonDb::escape($host_name)."' AND host.host_id = ns_host_relation.host_host_id AND ns_host_relation.nagios_server_id = nagios_server.id LIMIT 1");
    $nagios_server = $DBRESULT->fetchRow();
    if (isset($nagios_server['id'])) {
    return $nagios_server['id'];
    }
    $sql = "SELECT id FROM nagios_server WHERE localhost = '1' LIMIT 1";
    $res = $pearDB->query($sql);
    if ($res->numRows()) {
    $row = $res->fetchRow();
    return $row['id'];
    }
    return 0;
    }

**new version : 2.8.12**

*file : www/class/centreonExternalCommand.class.php*
    
    public function acknowledgeService(
    ...
    $pollerId = $this->getPollerID($hostName); 
    public function getPollerID($host = null)
    {
        if (!isset($host)) {
            return 0;
        }
    
        /*
         * Check if $host is an id or a name
         */
        if (preg_match("/^[0-9]*$/", $host)) {
            $DBRESULT = $this->DBC->query("SELECT instance_id FROM hosts WHERE hosts.host_id = '" .
                CentreonDB::escape($host) . "' AND hosts.enabled = '1'");
                error_log("SELECT instance_id FROM hosts WHERE hosts.host_id = '" .CentreonDB::escape($host) . "' AND hosts.enabled = '1'");
        } else {
            $DBRESULT = $this->DBC->query("SELECT instance_id FROM hosts WHERE hosts.name = '" .
                CentreonDB::escape($host) . "' AND hosts.enabled = '1' LIMIT 1");
                error_log
        }
        $row = $DBRESULT->fetchRow();
        if (isset($row['instance_id'])) {
            return $row['instance_id'];
        }
        return 0;
    }

**Comment by Moujimouja** [comment]
Hi,

Since that time we've worked on a new event page to manage current alert. The problem can't be reproduce here.
