### ISSUE TITLE
[2.8.12]: ACL - user have access to ressources, that are not assigned in host group

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#5680]
Centreon Web version: 2.8.12

Centreon Engine version: latest

Centreon Broker version: latest

OS: supported

Steps to reproduce the issue:
Create a simple user, assign a acl group with restricted resource access through host groups.

Describe the results you expected:
The user can access only to the hosts assigned in the host group

**Comment by joschi99** [comment]
Additional info:
the host group has assigned 9 hosts, but the user can see 26 hosts, but there are more then 100 hosts in the system. no idea why he can see 26 hosts.

**Comment by oasisck** [comment]
It's pretty similar than my issue [#5671](https://github.com/centreon/centreon/issues/5671)

**Comment by lpinsivy** [comment]
@oasisck sorry but this issue is not linked.

Can you check if an ACL is not linked to a contactgroup linked to this user?

**Comment by joschi99** [comment]
The problem seem's not depending if the ACL is assigned to a user or a user group. In both cases we have the same behavior.

**Comment by lpinsivy** [comment]
I try to reproduce issue but I can't.

My user only see expected hosts in my hostgroups.

Can you export your contacts, contactgroups, and ACL definition with CLAPI?

**Comment by joschi99** [comment]
Hi @lpinsivy 

I found the problem. This is not a bug, but the problem was a wrong configuration of the ACL Ressource. The flag "include all servicegroups" was active, unfortunately I did not checked this enough.

Excuse me for this. I will close the issue. Thank you very much.

Regards,
Jochen
