### ISSUE TITLE
Graphs in IE streched Part 2 

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#5683]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.12

**Steps to reproduce the issue:**
1. Open Internet explorer and login
2. Open Monitoring > Status details
3. Click a host with many graphs and go to performance tabs

**Describe the results you received:**
![strech](https://user-images.githubusercontent.com/9079781/30633549-560fc4d0-9dec-11e7-9876-558d8f563adb.png)

**Describe the results you expected:**
Should be displayed well (like Firefox and Chrome browser)

**Additional information you think important (e.g. issue happens only occasionally):**
IE 11.

Also have that issue: #5081

**Comment by lpinsivy** [comment]
Do you have error in IE console?

**Comment by adr-mo** [comment]
Tests were done with:

- **Google Chrome** v62.0.3202.94
- **IE11** v11.15.16299.0
- **Microsoft EDGE** v41.16299.15.0
- **Firefox** v57.0

Graphs are well displayed

Looks good to me
