### ISSUE TITLE
base-centreon-ping returns NAN on host monitoring but not on service monitoring, so host seems down

### ISSUE THREAD

**Issue by florism** [centreon/centreon#5689]
Centreon-web version: 2.8.13

Centreon Engine version: 1.7.2-3

Centreon Broker version: 3.0.8-1

OS: Centos 7.3.1611

Additional environment details (AWS, VirtualBox, physical, etc.):
Physical installation from Centreon yum repository
Virtual

Steps to reproduce the issue:

Centreon base-centreon-ping returns nan to hostcheck in host configuration, but works
fine in service configuration. Service is up host is down

Describe the results you received:
see above

Describe the results you expected:
see above
both host and service should be up

check on host is base_centreon-ping

template is OS_Linux-SNMP and generic-active-host

Additional information you think important (e.g. issue happens only occasionally):
<img width="739" alt="nan" src="https://user-images.githubusercontent.com/31914125/30642050-8777230c-9e09-11e7-9d2e-15164a724aa3.png">

**Comment by lpinsivy** [comment]
"generic-active-host" template uses "base_host_alive" for command:

`$USER1$/check_icmp -H $HOSTADDRESS$ -w 3000.0,80% -c 5000.0,100% -p 1`

And Ping service uses "base_centreon_ping" command:

`$USER1$/check_icmp -H $HOSTADDRESS$ -n $_SERVICEPACKETNUMBER$ -w $_SERVICEWARNING$ -c $_SERVICECRITICAL$`

So to test host, only one ICMP packet is sent and 5 for Ping service.

I suppose you have network outage.

**Comment by florism** [comment]
Mmh that's odd, we don't . I will try removing the template and just use the custom checks.
And the "Not a number " is normal ?

**Comment by lpinsivy** [comment]
Where do you see "NaN" in Centreon web?

**Comment by florism** [comment]
In the status information from the host, see the image I attached above.
It sais CRITICAL - <ip> rta nan, lost 100%
If I aadd the base-centreon-ping to the service, it will also attach it to the host, so I reckon it's using the same test for both ?

**Comment by lpinsivy** [comment]
If you have 100% of packets lost, it is ok to have NaN for RTA, is not it?

**Comment by florism** [comment]
Ok tracked it down to base-centreon-ping, even though the host is up it returns NaN, on the ser vice level it does not however. I'm now using base_host_alive which seems to work fine.

**Comment by 9hili9** [comment]
I'm late to the party, but I thought it might be helpful to add this.  It appears that it's the reliance on service-level macros which causes this command to fail, when used as a host check. Testing with:

`$USER1$/check_icmp -H $HOSTADDRESS$ -n -w -c`

generates the response:

`CRITICAL - $HOSTADDRESS$: rta nan, lost 100%`

even if the target host is up. It would be useful to have a more explict error response from "check_icmp", when it's called with malformed arguments.
