### ISSUE TITLE
Google chrome generates wrong url for graphics

### ISSUE THREAD

**Issue by Geek2France** [centreon/centreon#5690]
Hello,

i use centreon 2.8.12 and it works well with firefox 55.0.3.

But i found an issue with google chrome (chromium to be precise).
I go to monitoring->status details and when i click on the graph icon i'm redirected to a page with an url like : http://_myserver_/centreon/main.php?p=204&mode=0&svc_id=ralbsas46CHECK-LOAD-AVERAGE

Normally, i should have this url : http://_myserver_/centreon/main.php?p=204&mode=0&svc_id=ralbsas46;CHECK-LOAD-AVERAGE
It misses the ";" between the host and the service.

**Comment by lpinsivy** [comment]
Hi,

Was is your version of chromium?

Regards,

**Comment by Geek2France** [comment]
Version 60.0.3112.113 (Build de développement) Fedora Project (64 bits)

Regards

**Comment by lpinsivy** [comment]
Thank you for answer

**Comment by Geek2France** [comment]
Hello, have you planned to fix this issue or identified the problem ?

Regards.

**Comment by lpinsivy** [comment]
Hi,

This bug is considered as minor because chromium [is not supported by Centreon](https://documentation.centreon.com/docs/centreon/en/2.8.x/installation/prerequisites.html#prerequisites).

We prefer to focus in blocking/critical bug first then major and after minor.

Regards,
