### ISSUE TITLE
Install Plugin Packs Manager from sources

### ISSUE THREAD

**Issue by bvilliot** [centreon/centreon#5692]
Hi,

I've installed Centreon from sources, and there is no modules installed with it. Here is what I see in Modules page :
![image](https://user-images.githubusercontent.com/5849947/30650012-1cc5540c-9e22-11e7-8ea0-34e2ed66ee94.png)
I didn't find Plugin Pack Manager sources on Github and website.
I tried to copy modules from another instance installed from Centreon package, but I get this in Plugin Pack page :
![image](https://user-images.githubusercontent.com/5849947/30650421-1f60c6c8-9e23-11e7-9e80-a49974263c33.png)

Is there a solution to install Plugin Pack Manager on a Centreon installed from sources ?

Thank you

**Comment by masterdead** [comment]
Try to enable short_open_tag in php.ini
