### ISSUE TITLE
Ranking of ascending / descending guests NOK

### ISSUE THREAD

**Issue by lorenzo8769** [centreon/centreon#5695]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.13

**Centreon Engine version**:  1.8.0

**OS**:  centreon-3.4.1.x86_64.iso

Ranking of ascending / descending guests NOK

The ascending / descending ranking no works  after configuring the correct option (Administration> Parameters> Centreon UI)

Bug?

Laurent

**Comment by lpinsivy** [comment]
Can you try with "Problem display properties" options?

**Comment by lorenzo8769** [comment]
Same pb with:

Display properties
and
Problem display properties

**Comment by lpinsivy** [comment]
Reproduce the problem:
1. set filters for "Display properties" and "Problem display properties"
2. got to "Monitoring  >  Status Details  >  Services > All"
3. go to another menu ""Monitoring  >  Status Details  >  Hosts"
4. go back to "Monitoring  >  Status Details  >  Services", filter stay to "All" but sort is not correct.

**Comment by chgautier** [comment]
Bug reproduced on 2.8.13
Bug no longer found on 2.8.15

**Comment by thiuyendang** [comment]
Close action for chgautier.

**Comment by lorenzo8769** [comment]
Hello,

Centreon Web version: 2.8.15
Centreon Engine version: 1.8.0
OS: centreon-3.4.1.x86_64.iso

**Unresolved bug on 2.8.15 for Host - but Service is OK**

    1-set filters for "Display properties" and "Problem display properties" (ex: Duration)
    2-got to "Monitoring > Status Details > Hosts> filter stay to "All" but sort is not correct.

Cordialement,
Laurent

**Comment by lpinsivy** [comment]
You right, still present for  Monitoring > Status Details > Hosts with "All" filter

**Comment by lorenzo8769** [comment]
Hi,

The issue must be in 2.8.16?

Laurent

**Comment by lpinsivy** [comment]
In fact I test again with Centreon web 2.8.15:

Display properties: "Last check" ascending
Problem display properties: "Duration" ascending

When I go to "Monitoring  >  Status Details  >  Services" menu, items are sorted by "Duration" ascending
When I change filter to "All",  items are sorted by "Last check" ascending

So it is ok

**Comment by lorenzo8769** [comment]
Hi,
It's not ok for me.
When I configure the "Descending" Duration and access to **Monitoring > Status Details > Hosts > All**,  it's incorrect
Laurent

**Comment by adr-mo** [comment]
Hi,
The issue no longer exists with the **latest version of Centreon**

This is a 2.8.x related bug which is no longer supported

**Closing the ticket**

Regards,
