### ISSUE TITLE
Reporting issue

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#5696]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.11

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.
On Reporting > Dashboard, value of duration is very strange.
I have undetermined value with -604800s for ex.

**Describe the results you received:**

**Describe the results you expected:**

![image](https://user-images.githubusercontent.com/12545407/30697016-d61dc842-9edd-11e7-869e-337286fcbbc6.png)

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
should be linked to #5491

**Comment by kozfelipe** [comment]
I think you may close this one since its fixed at 2.8.14

**Comment by romsworld** [comment]
Yes you can.
