### ISSUE TITLE
issue after upgrade 2.8.13

### ISSUE THREAD

**Issue by sonidp** [centreon/centreon#5701]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.13

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.9

**OS**: centos 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Maria DB 5.5.57

**Steps to reproduce the issue:**
1.upgrade from 2.8.11 to 2.8.13
2.check cisco ASA template and we don't have data after upgrade
3.

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/31224883/30739562-2617d918-9f8e-11e7-988c-1ae63682e89f.png)

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

Can you check the executed command line from detail of one service and tri to execute this command with "centreon-engine" user on poller?

**Comment by sonidp** [comment]
Hi,
I finded the problem. I don't know why,but the name of Cisco plugin has been chaneged. Just i have renommed it.
In other Centreon plateforme i have a problem with perl library when updated to 2.8.13. I have do  rollback because i don'd find a resolution (revert snaphot). 
Thanks
