### ISSUE TITLE
RFE: "First notification delay" for escalation notification

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#5704]
CES 3.4.1 iso updated to Centreon 2.8.13, Engine 1.8.0, Broker 3.0.9.

Object: get a single service notification, get a single escalation notification after 15 minutes without repeating either.

Currently this can't be done without repeating service notifications or ugly self modifying timeperiod kludges.

Can a "First notification delay" similar to the service's notification be added to the escalation definitions? Then you could set the service notification's Notification Interval to 0, the escalation's First Notification to 1 and First notification delay to 15.

**Comment by lpinsivy** [comment]
Escalation is used to prevent a higher level to manage the alert. Why add a delay?

**Comment by btassite** [comment]
Maybe I'm misunderstanding the definition of escalation: "If admin x does not press ACK on service alert y after 15 minutes, send an SMS to manager z".

How do I reach this goal:
A single service notification is sent as a service transitions from OK to a Hard state of Critical.
A single additional service notification is sent to a different Contact Group 15 minutes later (if service has not returned to OK state).
No other notifications are sent until the service changes state again.

This currently doesn't seem possible without causing a flood of notifications that doesn't stop until the service state changes again, which is a nightmare for thousands of services already warning quite a lot.

**Comment by lpinsivy** [comment]
If your service is monitored every 5 minutes (normal check interval) you can configure:

service:

- Notification Interval: 15
- First notification delay: 0
- Recovery notification delay: 0
- Implied Contacts: contact_1

Escalation:

- First Notification: 1
- Last Notification: 0
- Notification Interval: X
- Implied Contacts: contact_2

So the first notification will be sent to contact_1 and the second (15min after) will be sent to contact_2 every Xmin. You can stop a the first escalation be define '2' for 'Last Notification'

**Comment by btassite** [comment]
Unfortunately that means sending new service notifications every 15 minutes forever (i.e. until status change).

This is a problem if for example you have a service going critical just before the weekend, the escalation goes out once but the admins who receive the regular notification will be swamped with notifications for 2+ days.

Since according to #5706 Notification Interval 0 is not supported for service notifications in combination with an escalation, I guess I'd like to change the RFE to:

Please include a field Last Notification in service notifications too. That's still one notification too much (2 service notifications, 1 escalation notification) but that way at least the flood would be stopped.

**Comment by lpinsivy** [comment]
So for your case, if a services change state (OK to CRITICAL) you want:

1. Send a notification for some contacts
2. If after 15 minutes the service is not acknowledge, send notification using another  way to another contacts

**Comment by btassite** [comment]
Exactly. This can already be done, but I also need:
3. no more notifications sent for 1. after the initial one.

**Comment by lpinsivy** [comment]
@btassite sorry for the long delay.

If you define an escalation from 2 notification to infinity (0).
The contacts linked to the resources will receive only the first notification.

**Comment by btassite** [comment]
Thank you, I quickly tested this with 1 minute intervals, but for now this seems more workable:
the service notification contacts will receive 2 notifications and the escalation contacts 1 (at the same time as the second for the service notification contacts), and no notifications for either after that.

On OK both service notification contacts and escalation contacts will receive a single immediate OK notification which is OK too.
