### ISSUE TITLE
PHP Fatal error:  Class 'CentreonClapi\CentreonUserLog' not found in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php on line 489

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5710]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.13

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.9

**OS**: CentOS 6 - Install from RPM

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Try to use Centreon CLAPI using a LDAP User

**Describe the results you received:**
PHP Fatal error:  Class 'CentreonClapi\CentreonUserLog' not found in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php on line 489

**Describe the results you expected:**
CENTREON_PATH should be recognized

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi @lolokai can you try this path:

```
                 if ($row['contact_passwd'] == $pass) {
                     return 1;
                 } elseif ($row['contact_auth_type'] == 'ldap') {
-                    $CentreonLog = new CentreonUserLog(-1, $this->DB);
-                    $centreonAuth = new CentreonAuthLDAP(
+                    $CentreonLog = new \CentreonUserLog(-1, $this->DB);
+                    $centreonAuth = new \CentreonAuthLDAP(
                         $this->DB,
                         $CentreonLog,
                         $this->login,
```

Regards,

**Comment by lpinsivy** [comment]
@lolokai did you test?

**Comment by adr-mo** [comment]
Ok it has been validated.

I've imported a LDAP user on Centreon and allowed him to be an admin and reach the API.

Before applying the patch I've got a PHP fatal error.
Once the patch was applied there was no PHP fatal error anymore and API returned the results that I had requested.

PR: #5725
