### ISSUE TITLE
Top counter services OK / Total wrong for ACL users

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#5713]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.13

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.9

**OS**: CES

**Steps to reproduce the issue:**
1. Create user with ACL
2. Add user with 2 ressources group
3. Connect with this user
4. Top counter is wrong because total services of each ressource group are summed.

**Describe the results you received:**
Total services wrong (Values are summed)

**Describe the results you expected:**
The good value of total services for user with ACL

How it is configured : 
![bug-counter-acl](https://user-images.githubusercontent.com/14218330/30907321-9ec5f260-a37a-11e7-986d-530e6feab147.PNG)

Admin view : 
![nombre-services-total-admin](https://user-images.githubusercontent.com/14218330/30907322-9ec8c940-a37a-11e7-87e2-9e61f621e693.PNG)

ACL User view : 
![nombre-services-total-acl](https://user-images.githubusercontent.com/14218330/30907323-9ec93100-a37a-11e7-91ee-2fd3cb381212.PNG)

Thanks for your help!

**Comment by lpinsivy** [comment]
Corrected by pull request #5703

**Comment by thiuyendang** [comment]
OK CentOS6 2.8.14-5
