### ISSUE TITLE
Order by Duration instead of Host

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5715]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.13

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.9

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Monitoring - Status Details
2. Select All Services
3.

**Describe the results you received:**
Result is ordered by Duration

**Describe the results you expected:**
Result should be ordered by Host Name

**Additional information you think important (e.g. issue happens only occasionally):**
Maybe you can add a Parameter to choose

**Comment by lpinsivy** [comment]
You can choose the sorting by defining options in "Administration  >  Parameters  >  Centreon UI > Problem display properties".

Regards,

**Comment by lolokai** [comment]
Ok perfect I didn't know that this feature existed sorry :)
