### ISSUE TITLE
[Widget] - Sharing View - Reset button is not working

### ISSUE THREAD

**Issue by adr-mo** [centreon/centreon#5727]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.13

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.10

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a view
2. Add a Widget
3. Click on "Share a View" button
4. Select some contacts in the fields
5. Click on reset button

**Describe the results you received:**

When I click on the reset button nothing happens

**Describe the results you expected:**

All the fields are set to their previous states
**Additional information you think important (e.g. issue happens only occasionally):** Tests done with Chrome 61.0.3163.100

**Comment by Moujimouja** [comment]
Hi,

It has been fixed. I close this issue.
