### ISSUE TITLE
Logs are missing randomly

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#5728]
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.13

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 

**OS**:  CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware Virtual appliance

**Steps to reproduce the issue:**
1. Delete service from host 
2. Go to Administration -> Logs
3. Search for that host or service

**Describe the results you received:**
4.Loads the page for at least 20 seconds
5. Does not show any results for that particular host (it shows other changes I have made)

**Describe the results you expected:**
I would like to see what services/hosts I have deleted.

**Additional information you think important (e.g. issue happens only occasionally):**
-

**Comment by lpinsivy** [comment]
Hi,

I can't reproduce with admin account.

Do you use an admin account or an account with ACL?

**Comment by kadrika** [comment]
Admin account

**Comment by kadrika** [comment]
I tested it several times, it does not happen all the time, randomly logs are missing.

**Comment by kozfelipe** [comment]
Hi, I get this issue often. I also get logs pagination issue.

**Comment by lpinsivy** [comment]
@kadrika can you send me your Centreon databases (excepting "centreon_storage.data_bin" tables) by MP to analyse?

**Comment by kadrika** [comment]
Hi,
We upgraded our monitoring some weeks ago to Centreon 2.8.16. After that I have not noticed that problem. If I do, I will let you know.
