### ISSUE TITLE
The table 'log_action_modification' is full

### ISSUE THREAD

**Issue by 5145h** [centreon/centreon#5738]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.4-5.el6.noarch

**Centreon Engine version**: centreon-engine-1.7.0-2.el6.x86_64

**Centreon Broker version**: centreon-broker-3.0.3-4.el6.x86_64

**OS**: RHEL 6.8

**Additional environment details (AWS, VirtualBox, physical, etc.):** Openstack instance

**Steps to reproduce the issue:**
1. Set contact autologin key, add host, etc through Rest API
2. Get error 500 Internal server error and SQLSTATE[HY000]: General error: 1114 The table 'log_action_modification' is full" 
3.

**Describe the results you received:**
Got error` 500 Internal server error` and `SQLSTATE[HY000]: General error: 1114 The table 'log_action_modification' is full` 

**Describe the results you expected:**
Work as expected

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

Do you set innodb_file_per_table = 1 in your MySQL/MariaDB configuration ?

```
MariaDB [centreon_storage]> show global variables like "%innodb_file_per_table";
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_file_per_table | ON    |
+-----------------------+-------+
```

Regards,

**Comment by 5145h** [comment]
Hi, 

It's a default installation. But I checked and it's ON:

```
# mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 10880350
Server version: 5.5.53-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use centreon_storage;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [centreon_storage]>  show global variables like "%innodb_file_per_table";
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_file_per_table | ON    |
+-----------------------+-------+
1 row in set (0.00 sec)

```

**Comment by lpinsivy** [comment]
What is the value of "innodb_data_file_path"?

```
MariaDB [centreon]> show global variables like "innodb_data_file_path";
+-----------------------+------------------------+
| Variable_name         | Value                  |
+-----------------------+------------------------+
| innodb_data_file_path | ibdata1:12M:autoextend |
+-----------------------+------------------------+
```

What is the size of /var/lib/mysql/ibdata1 file?

Do you still have place on MariaDB data filesystem ?

Regards,

**Comment by 5145h** [comment]
```
[root@monaas-test-centreon ~]# df -h | grep mysql
/dev/vdb               20G  3.3G   16G  18% /var/lib/mysql

[root@monaas-test-centreon ~]# mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 10881061
Server version: 5.5.53-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use centreon
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [centreon]> show global variables like "innodb_data_file_path";
+-----------------------+------------------------+
| Variable_name         | Value                  |
+-----------------------+------------------------+
| innodb_data_file_path | ibdata1:10M:autoextend |
+-----------------------+------------------------+
1 row in set (0.00 sec)

MariaDB [centreon]>
```

**Comment by lpinsivy** [comment]
So you have enough space to extend /var/lib/mysql/ibdata1 file

Did you try to restart MariaDB service?
Can you try to upgrade to MariaDB-5.5.57 available in Centreon repository?

**Comment by 5145h** [comment]
Hi, 

I have already upgraded Centreon to the latest version and now the issue do not exist anymore.

Thanks. 
Can be closed.
