### ISSUE TITLE
[Major] Centreon's performance is incredibly degraded for ACL users

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5745]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.14

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.9

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CES box

**Describe the results you received:**
The web pages are taking too long to load, specially top counter calculation (~5min) and poller's export configuration (a whole day) (only for non-admin users)

**Describe the results you expected:**
I expect those users to have same performance load as admin does (almost instantly).

**Additional information you think important (e.g. issue happens only occasionally):**

These are recent sql logs that may be probable cause:

`2017-10-05 10:52|0|0|DB Error: unknown error QUERY : SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 ELSE 0 END) AS WARNING_TOTAL, SUM(CASE WHEN s.state = 1 AND (s.acknowledged = '1' OR s.scheduled_downtime_depth = '1')     THEN 1 ELSE 0 END) AS WARNING_ACK_DT, SUM(CASE WHEN s.state = 2 THEN 1 ELSE 0 END) AS CRITICAL_TOTAL, SUM(CASE WHEN s.state = 2 AND (s.acknowledged = '1' OR s.scheduled_downtime_depth = '1')     THEN 1 ELSE 0 END) AS CRITICAL_ACK_DT, SUM(CASE WHEN s.state = 3 THEN 1 ELSE 0 END) AS UNKNOWN_TOTAL, SUM(CASE WHEN s.state = 3 AND (s.acknowledged = '1' OR s.scheduled_downtime_depth = '1')     THEN 1 ELSE 0 END) AS UNKNOWN_ACK_DT, SUM(CASE WHEN s.state = 4 THEN 1 ELSE 0 END) AS PENDING_TOTAL FROM hosts h, services s, instances i WHERE i.deleted = 0 AND h.enabled = 1 AND s.enabled = 1 AND i.instance_id = h.instance_id AND h.host_id = s.host_id AND (h.name NOT LIKE '_Module_%' OR h.name LIKE '_Module_Meta%') AND s.service_id IN ( SELECT DISTINCT service_id FROM centreon_acl WHERE centreon_acl.group_id IN ('2'))
`

**Comment by lpinsivy** [comment]
Hi,

A user with ACL can't have exactly the same performance than an admin user. 

Centreon web needs to check access to menus, to resources and actions on resources.
The SQL request time depends of the complexity of your ACL (number of ACL groups linked to user, number of ressources, etc.)

How many hosts and services do you have ?
How many ACL groups ?
What is your average ACL groups linked by user ?

**Comment by lpinsivy** [comment]
Moreover, what is your version of MariaDB server?
Did you perform optimization?

**Comment by kozfelipe** [comment]
We have over 7600 services, 2400 hosts.
We have only central poller.

We have only one ACL group linked per user
2 ACL groups: Vizual Only, Registration Team

Centreon's DB is remote, running on MariaDB 5.5.54-0ubuntu0.12.04.1, its taken care of by the infrastructure team. What kind of optimization I may suggest them to perform?

**Comment by kozfelipe** [comment]
update: We just upgraded hardware and MariaDB to 5.7.19-0ubuntu0.16.04.1, but now poller wont start

![image](https://user-images.githubusercontent.com/25208457/31409705-2d8828c0-ade3-11e7-9dc5-f0c62eb491da.png)

**Comment by kozfelipe** [comment]
Due Database upgrade and mostly ACLs, Manus and Actions recreation, performance is quite fine now.

Users were getting ACL policy twice, by its access list relation and its contact group ACL relation.

Any database optimization advice are welcome
