### ISSUE TITLE
ACL non-authorized Users can export configuration

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5747]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.14

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.9

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CES box

**Describe the results you received:**
Non-Authorized users can export configuration even though they belong to an Action Access group which has unchecked Generate Configuration Files action, plus no Poller Menu visualization

**Additional information you think important (e.g. issue happens only occasionally):**
![image](https://user-images.githubusercontent.com/25208457/31240211-3e165196-a9d6-11e7-8e61-dc03eead0e94.png)

![image](https://user-images.githubusercontent.com/25208457/31240259-6edf58d6-a9d6-11e7-9dc3-bad1c0f6186c.png)

![image](https://user-images.githubusercontent.com/25208457/31240289-89460d5a-a9d6-11e7-85f5-ea7b047a810e.png)

![image](https://user-images.githubusercontent.com/25208457/31240370-ce45c724-a9d6-11e7-94bb-18dd0e9aba44.png)

**Comment by lpinsivy** [comment]
Hi

Can't reproduce with Centreon Web 2.8.14.

I suppose your "Guest" user is linked to another ACL group of link to a contactgroup linked to another ACL Group

**Comment by kozfelipe** [comment]
Hi

My Centreon Web is on 2.8.14

My guest, just like all the vizualization-only accounts are linked to only one contact group, only one ACL group per contact group.

**Comment by lpinsivy** [comment]
Can you check in your "guest" contact that "Is admin" is not set to "Yes"?

**Comment by kozfelipe** [comment]
@lpinsivy its not set Admin for guest or any other vizualization account

**Comment by kozfelipe** [comment]
I recreated all ACLs Menus and actions, and now it works properly
