### ISSUE TITLE
Number "0" not displayed in the top counter "OK" and "pending" services where there are no services yet.

### ISSUE THREAD

**Issue by smichelet** [centreon/centreon#5758]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.14

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.9

**OS**: CentOS Linux release 7.4.1708 (Core)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EC2 Instance

**Steps to reproduce the issue:**
1. When the instance in newly installed and have 0 hosts and 0 services.
2.
3.

**Describe the results you received:**
When the instance in newly installed and have 0 hosts and 0 services, I have the following issue in the top counter. The number 0 is not displayed for the pending and OK services. We only see a blue or green background. Please, look at the screenshot.

**Describe the results you expected:**
I expect to have the number "0" displayed in the top counter for the pending and OK services.

**Additional information you think important (e.g. issue happens only occasionally):**
![001](https://user-images.githubusercontent.com/19533272/31341277-5092d020-ad09-11e7-9160-a15338440092.png)

**Comment by chgautier** [comment]
Validated in PR #5826
