### ISSUE TITLE
[Centreon 2.8.14] centreon_windows_snmp mode storage problem

### ISSUE THREAD

**Issue by o71** [centreon/centreon#5759]
Centreon Web version: 2.8.14

Centreon Engine version: 1.8.0

OS: CES

Hello,

When I mount an 'iso' file on a Windows machine a new drive is added (here K :).

The drive K: is not listed in the list of drives using the plugin 'centreon_windows_snmp.pl' but the size of drive K: replace the size of the drive O.

Here are the screenshots:

![Before I add iso and K drive](https://user-images.githubusercontent.com/2280629/31342918-6e48ba58-ad0e-11e7-92f2-49b626ceef57.png)

![After](https://user-images.githubusercontent.com/2280629/31342946-84fe9916-ad0e-11e7-8268-4db09d7dc354.png)

Here my command :

/usr/lib/centreon/plugins/centreon_windows_snmp.pl
	--plugin=os::windows::snmp::plugin
	--mode=storage
	--hostname=X.X.X.X
	--snmp-version='2c'
	--snmp-community='public' 
	--storage='.*'
	--name
	--regexp
	--display-transform-src='^(..).*'
	--display-transform-dst='$1'
	--warning='80'
	--critical='90'
	--verbose

All is ok after I eject the K drive, but my graph :

![image](https://user-images.githubusercontent.com/2280629/31343128-03a859dc-ad0f-11e7-9216-06721c400ec4.png)

Thanks

**Comment by lpinsivy** [comment]
Hi, I create a linked ticket on the correct forge.

Regards,
