### ISSUE TITLE
All Centreon freeze when I access to "View contact Notification"

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5760]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.14

**Steps to reproduce the issue:**
1. Go to "Configuration > Users > Contacts / Users" menu
2. Click on "View contact Notification"
3. Select contact

**Describe the results you received:**

Centreon web freeze and make several minutes to display result or crash

**Describe the results you expected:**

Display result without blocking all Centreon

**Comment by thiuyendang** [comment]
Execution request duration has decreased with the fix. Tested with 2.8.18-3 el6
