### ISSUE TITLE
[Knowledge Base] Search function non functionnal

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#5762]
**Centreon Web version**:  2.8.11

**OS**: centOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Template Hosts or Tempalte Services in KB
2. search any word of template name

**Describe the results you received:**
none template is displayed

**Describe the results you expected:**
display the templates searched

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

For me only service template doesn't work.

Can you try this patch:

```
@@ -126,7 +126,7 @@
         "WHERE service_register = '0' " .
         "AND service_locked = '0' ";
     if (isset($_REQUEST['searchServiceTemplate']) && $_REQUEST['searchServiceTemplate']) {
-        $query .= " AND service_description LIKE ' % " . $_REQUEST['searchServiceTemplate'] . " % ' ";
+        $query .= " AND service_description LIKE '%" . $_REQUEST['searchServiceTemplate'] . "%' ";
     }
     $query .= "ORDER BY $orderby $order LIMIT " . $num * $limit . ", " . $limit;
     print $query;
```

Regards,

**Comment by cmeschin** [comment]
Hi Laurent,
Effectively, it's only for service template, sorry.
So, which file should I modify, please?

**Comment by lpinsivy** [comment]
Sorry I forgot to put name of file: /usr/share/centreon/www/include/configuration/configKnowledge/display-serviceTemplates.php

**Comment by lpinsivy** [comment]
@cmeschin can you try the fix?

**Comment by cmeschin** [comment]
Hi,
The fix is OK.
Thanks.

**Comment by thiuyendang** [comment]
OK in 2.8.16-2, el7.
