### ISSUE TITLE
[Centreon-Web] Image Upload non functionnal

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#5763]
**Centreon Web version**:  2.8.9

**OS**:  CentOS 6.8 (CES server)

**Steps to reproduce the issue:**
1. Go to Upload media in admin menu.
![image](https://user-images.githubusercontent.com/8720203/31397237-c6ea94f6-ade5-11e7-8084-22f8628a3f27.png)

2. choose an image and upload it.

**Describe the results you received:**
The image is uploaded in /usr/share/centreon/filesUpload/images/
The image is not visible in dropdown list on service or host params

**Describe the results you expected:**
The image should be upload in /usr/share/centreon/www/img/media/
or in subdirectory if defined

**Additional information you think important (e.g. issue happens only occasionally):**
I must move image in desired folder
`mv /usr/share/centreon/filesUpload/images/my-image.png /usr/share/centreon/www/img/media/Clients/`

**Comment by lpinsivy** [comment]
Works with Centreon web 2.8.13 on el6 and Centreon Web 2.9.14 on el7
