### ISSUE TITLE
centreontrapd service is not running after reboot

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5768]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.14

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Reboot OS (after iso Centreon web installation for example)
2.
3.

**Describe the results you received:**
all services are running except centreontrapd service.

**Describe the results you expected:**
all services have restarted.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by cyrmoon** [comment]
same problem

**Comment by lpinsivy** [comment]
Which OS ?

**Comment by cyrmoon** [comment]
The iso centreon 3.4.1, cents ans 6.9

Envoyé par Blue<http://www.bluemail.me/r?b=10777>
Le 11 janv. 2018, à 10:08, Laurent Pinsivy <notifications@github.com<mailto:notifications@github.com>> a écrit:

Which OS ?

**Comment by lpinsivy** [comment]
The /etc/centreon/conf.pm configuration file is ok?
Can you enable debug mode for Centreontrapd in Centreon Web ui and check errors in /var/log/centreon/centreontrapd.log file?

**Comment by adr-mo** [comment]
**No answer for now more than 1 months**

Closing this issue.

Regards,
