### ISSUE TITLE
Could not complete SSL Handshake

### ISSUE THREAD

**Issue by Ale171** [centreon/centreon#5771]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  CES 3.4.1

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0.3

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  J'essaye de lancer la commande check_nrpe

**Describe the results you received:**

Je met en place un environnement de test sur la nouvelle version 3.4.1, et en essayant de lancer la commande check_nrpe, j'ai un message d'erreur : Not complete SSL Handshake. Sur mon environnement de prodution en CES 3.2, la commande NRPE passe sans aucun soucis sur les mêmes serveurs ou je teste.

**Describe the results you expected:**

Que faire donc pour régler le problème ? Je pense que cela vient de mon central ou de mes pollers ?

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

What is your version of NRPE ?
Did you enable SSL in NRPE daemon?
Did you allow poller IP address in nrpe.cfg file on NRPE daemon?

**Comment by Ale171** [comment]
Hi,

Version of NRPE : NSClient++ 0,4,1,90 2013-02-04
How can i enable SSL in NRPE daemon ? 
Yes i allow poller ID address in NRPE.cfg file on NRPE daemon.

I think the problem comes from my poller because with my pollers in production (CES 3.2), it works very well

**Comment by Ale171** [comment]
Any ideas ?

**Comment by zskarman** [comment]
Hi,

The 3.4.1 should contains new check_nrpe version and not works with the nsclient agent version is < 0.4.3.x
We can run example with 0.4.3.143 with TLS 1.2 only which is the most secure now.
Rgs, Zsolt
