### ISSUE TITLE
Using ISO to install Centreon Web : fix format for "start monitoring" section 

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5772]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.14

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. for french and english version of documentation, Centreon  Installation >Using Centron, section "Start monitoring"

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/25612980/31447408-33b7579c-aea2-11e7-892f-c4ff131879a7.png)

**Describe the results you expected:**
![docinstalliso](https://user-images.githubusercontent.com/25612980/31447621-bfa78718-aea2-11e7-9be5-a7bda5e108b1.png)

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by adr-mo** [comment]
Steps are well formated.

Looks good to me

**Comment by adr-mo** [comment]
Validated.

Closing the ticket
