### ISSUE TITLE
Real time host filter doesn't works with some SQL wildcard

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#5777]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.12
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.8
**OS**: 
RedHat 7.2
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create host named Server-Windows-DC
2. Try to use sql wildcard in host filter on real time monitoring page server%dc
3. Can also works with host filter "bisous%dc"

**Describe the results you received:**
Centreon not display your search but display every host

**Describe the results you expected:**
Juste have host with name like server"something"DC

**Additional information you think important (e.g. issue happens only occasionally):**
Works with any URL Encoding %BA, %BE %DC...

**Comment by Moujimouja** [comment]
Hi,

Since the 20.04, we've released a new page to manage resource status that is compatible with regular expression. 

This will not be fixed nor improve on the "old" monitoring pages.

I close the case.
