### ISSUE TITLE
Documentation : Centreon Web Installation from Centreon iso -> screenshots to be replaced

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5787]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.14

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: centOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Connect new VM to last available ISO
2. Compare start page picture to the one in current documentation
3.

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/25612980/31552850-e127a8ea-b038-11e7-9cef-b985e05a16ef.png)

![image](https://user-images.githubusercontent.com/25612980/31553421-bd242c96-b03a-11e7-97f6-5c28e66ab07e.png)

**Describe the results you expected:**
![image](https://user-images.githubusercontent.com/25612980/31552961-3c6a96a4-b039-11e7-8619-a1d07b241a44.png)
![image](https://user-images.githubusercontent.com/25612980/31553389-9f9b1d4c-b03a-11e7-984d-bb851897f8a1.png)

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by adr-mo** [comment]
**Deprecated.**
