### ISSUE TITLE
plugin storage disk : Unknow

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5800]
[EN]
Hello,

we are using the plugin pack: Centreon-plugin to get  the storage usage of the FS of our Linux.

In the same configuration, we have some machines for which this metric goes : UNKNOWN

Network snmp streams are open. The other metrics are well (CPU / RAM etc ...)

I notice that the machine facing the issue have a lot of FS (more than 10).

the command :
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=XX.X.XX.XX --snmp-version='2c' --snmp-community='XXXXXXXX'  --storage='.*' --name --regexp --display-transform-src='' --display-transform-dst='' --warning='90' --critical='95' --verbose --storage '^(?!(/dev/shm)|(/mnt)$)'

status information:
UNKNOWN: SNMP Table Request: Timeout

Thanks in advance.
Regards
[EN]

[FR]
Bonjour,

nous utilisons le plugin pack : centreon-plugin pour remonter l'utilisation du stockage des FS de nos Linux. 

A même configuration, nous avons quelques machines pour lesquelles ce metric remonte : UNKNOWN

Les flux network snmp sont bien ouvert. En dehors du Disk-Global le reste remonte bien (CPU/RAM etc...)

Je constate que les machines qui posent problème ont beaucoup de FS. 

la commande : 
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=XX.X.XX.XX --snmp-version='2c' --snmp-community='XXXXXXXX'  --storage='.*' --name --regexp --display-transform-src='' --display-transform-dst='' --warning='90' --critical='95' --verbose --storage '^(?!(/dev/shm)|(/mnt)$)'

status information :
UNKNOWN: SNMP Table Request : Timeout

Merci par avance.
Cordialement.

[FR]

ma version actuelle :
Centreon 2.8.14
Centreon Engine 1.8.0
MariaDB 5.5.53

**Comment by lpinsivy** [comment]
Hi,

Can you try to use the mode --list-storage to know if you can list storage ?

**Comment by fredo1988** [comment]
Hi there,

thanks for your feedback, but I find,
use this option : '--snmp-force-getnext' in macro SNMPEXTRAOPTIONS on services Disk-Global 

Regards,

**Comment by lpinsivy** [comment]
Great !

**Comment by Sims24** [comment]
Note: most of the time it should be used as soon as you monitor an AWS instance
