### ISSUE TITLE
Correction orthographique  Configuration > Plugin-pack > Configuration

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#5803]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.x
**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Pas de plugins-pack
2. Affichage de " Auccun plugin pack trouvé"
3.

**Describe the results you received:**

Affichage de " Auccun plugin pack trouvé"
**Describe the results you expected:**

Affichage de " Aucun plugin pack trouvé"

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Already corrected.

Waiting release of new version
