### ISSUE TITLE
Centreon traffic plugin - SNMPv3 context

### ISSUE THREAD

**Issue by bdeschut** [centreon/centreon#5807]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**:  2.8.13
**Centreon Engine version**: 1.8.0
**Centreon Broker version**: 3.0.9
**OS**: Centos 6 (Centreon ISO)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare central - HW pollers

**Steps to reproduce the issue:**
1. Configure monitoring for Check Point VSX, containing VS0, VS1 (and more like VS2, ...) - or any device that can use SNMPv3 context to switch between virtual systems
2. Configure interface monitoring using the centreon traffic plugin

**Describe the results you received:**
traffic plugin works for VS0 for some time, but doesn't work for VS1, .... After some time, the plugin starts working for VS1, but not for VS0 (or VS2, ...). This switches between the VS's.
So for clarity, the traffic plugin works for one VS (multiple interfaces), then switches to another VS
Error when the commands fail:
UNKNOWN: No entry found (maybe you should reload cache file)

**Describe the results you expected:**
I expected to have the traffic plugin working for all interfaces for all VS'es

My two cents: I think that somehow the plugin is using the same cache file(s) for this, and the checks are "fighting" over control of the ache file(s)

Extra info:
- I showed this behavior to Cyrille BAUGE (Centreon), who asked me to log a github issue for this.
- if you remove the *interface* cache files on the poller and run one of the commands manually immediately after that: they always work.

example commands:
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=x.y.z.25 --snmp-community=my_comm --snmp-version=3 --interface=^eth7.400$ --name --add-status --add-traffic --oid-filter=ifDesc --oid-display=ifDesc --snmp-username=my_user --authprotocol=MD5 --authpassphrase=my_auth_pass --privprotocol=DES --privpassphrase=my_priv_pass --contextname=ctxname_vsid2

/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=x.y.z.25 --snmp-community=my_comm --snmp-version=3 --interface=^eth5.200$ --name --add-status --add-traffic --oid-filter=ifDesc --oid-display=ifDesc --snmp-username=my_user --authprotocol=MD5 --authpassphrase=my_auth_pass --privprotocol=DES --privpassphrase=my_priv_pass --contextname=ctxname_vsid1

I have tried with and without "--oid-filter=ifDesc --oid-display=ifDesc", same result.

Please advise.

kind regards,
Bob

**Comment by Sims24** [comment]
Hello Bob, 

Thanks for opening this issue. We will handle it in dedicated centreon-plugins repository. https://github.com/centreon/centreon-plugins/issues/786
