### ISSUE TITLE
reccurent downtime : host inheritence

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon#5811]
[EN]
Hello,

In "downtime recurrent" when I add an host 👍 

- are the service automatically inhereted or should I add it manually
- if not could you add a check box : "host inheritence"

thank you in advance
[EN]

[FR]
Bonjour,

je souhaiterais savoir si dans la configuration des downtimes récurents lorsque j'ajoute un host :

- si les services sont hérités automatiquement ou si je dois également ajouter tous les services du host
- sinon pourrions nous vous demander d’implémenter une case "host inheritence" à cocher 

Merci par avance 
[FR]

ma version actuelle :
Centreon 2.8.14
Centreon Engine 1.8.0
MariaDB 5.5.53

**Comment by lpinsivy** [comment]
Hi,

When you defined Recurrent downtimes and you had hosts, all services are included automatically.

Regards,
