### ISSUE TITLE
Graphing can't handle range with colon for warning/critical level

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#5813]
Centreon version 2.7.7, Centreon Engine 1.5.1, Centreon Broker 2.11.5

If you define a service check like this (the colons denote a "less than" range, in this case return critical if not at least one process with the given name is found)
`/usr/lib/nagios/plugins/check_nrpe -H 1.2.3.4 -c check_proc_regex -a username "foo.*bar.*" 1: 1:`

Centreon creates a graph with huge warning and critical numbers, presumably because of the colons:

![check_proc_regex_range](https://user-images.githubusercontent.com/16683565/31938698-88f41da6-b8b8-11e7-89b3-1e26efa62658.png)

**Comment by Sims24** [comment]
Hi, 

It's a wontfix on 2.7 but correctly handled in 2.8.

**Comment by btassite** [comment]
OK, thanks :)
