### ISSUE TITLE
Administration->logs view is unexpectedly empty

### ISSUE THREAD

**Issue by protoism** [centreon/centreon#5815]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.12
**Centreon Engine version**: 
1.7.2
**Centreon Broker version**: 
3.0.8
**OS**: 
Centos 6.5
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical, Old Ces upgraded with yum

**Steps to reproduce the issue:**
No idea

**Describe the results you received:**
Administration->logs window empty

**Describe the results you expected:**
Administration->logs not empty

**Additional information you think important (e.g. issue happens only occasionally):**
Not clear how it happen, possibly an host has been removed.
Anyway patching /usr/share/centreon/www/include/Administration/configChangelog/viewLogs.php we were able to workaround the issue

...
                        foreach ($tabHost as $key => $value) {
                            #Luca: check su $value, ho situazioni in cui $value is NULL!
                            if($value)
                              $hosts[] = $centreon->CentreonLogAction->getHostName($value);
                        }
...

**Comment by lpinsivy** [comment]
Hi,

Can you execute the following SQL request on your centreon_storage database?

`MariaDB [centreon_storage]> select * from log_action where action_log_date > "$TIMESTAMP_START" and action_log_date < "$TIMESTAMP_START";`

By replacing $TIMESTAMP_START and $TIMESTAMP_START

**Comment by protoism** [comment]
Hi all,
thanks for caring.

echo "select * from log_action where action_log_date > '2017-10-01
00:00:00';" | mysql -uroot -p centreon_storage > log_action.txt

Attached (zipped) output

Luca.



2017-10-27 10:58 GMT+02:00 Laurent Pinsivy <notifications@github.com>:

**Comment by lpinsivy** [comment]
Hi,

Can you put upload on github directly because I can't access

Regards,

**Comment by protoism** [comment]
echo "select * from log_action where action_log_date > '2017-10-01 00:00:00';" | mysql -uroot -p centreon_storage > log_action.txt

[log_action.zip](https://github.com/centreon/centreon/files/1437861/log_action.zip)

**Comment by lpinsivy** [comment]
Did you duplicate hosts or services?
We detected a bug of duplication of host, new services aren't present into logs menu.

**Comment by protoism** [comment]
Hi Laurent,
yes we do that very often.


2017-11-02 15:18 GMT+01:00 Laurent Pinsivy <notifications@github.com>:

**Comment by lpinsivy** [comment]
We find the issue and A pull request correct this.

It will be for next Centreon Web bugfix version 2.8.18

**Comment by piozylka** [comment]
problem still exists in centreon 2.8.22
Administration->Logs is empty
