### ISSUE TITLE
The poller is running, but top icons show "Not running".

### ISSUE THREAD

**Issue by nakasix** [centreon/centreon#5821]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.14

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.10

**OS**: Debian GNU/Linux 8.9 (jessie)

**Steps to reproduce the issue:**
1. Configure a new Poller in other LAN.
2. Nat IP of Central.
3. Join Poller to Central.

**Describe the results you received:**
The poller is running and informations are monitoring, but top icons show "Not running".

![icons](https://user-images.githubusercontent.com/11419742/32041664-2c2f114c-ba35-11e7-8280-e1b61ca34d9b.JPG)
![poller](https://user-images.githubusercontent.com/11419742/32041671-3244cfc2-ba35-11e7-89c2-027f295c4488.JPG)

**Comment by lpinsivy** [comment]
Hi,

What are the result of following SQL request on your centreon database?

`SELECT name FROM nagios_server WHERE ns_activate = '1';`

And from centreon_Storage database?
```
SELECT `last_alive` AS last_update, `running`, name, instance_id FROM instances WHERE deleted = 0 
SELECT stat_value, i.instance_id, name  FROM `nagios_stats` ns, instances i  WHERE ns.stat_label = 'Service Check Latency'  AND ns.stat_key LIKE 'Average'  AND ns.instance_id = i.instance_id AND i.deleted = 0
```

Regards,

**Comment by nakasix** [comment]
Hello,

**centreon :**

> +---------+
> | name    |
> +---------+
> | Central |
> | CLI1    |
> | PAR3    |
> | MRS1    |
> +---------+

**centreon_storage :**

> +-------------+---------+---------+-------------+
> | last_update | running | name    | instance_id |
> +-------------+---------+---------+-------------+
> |  1509030128 |       1 | Central |           1 |
> |  1509030129 |       1 | CLI1    |           2 |
> |  1509030128 |       1 | PAR3    |           3 |
> |  1509030127 |       1 | MRS1    |           4 |
> |  1508857512 |       0 | CLI1    |           5 |
> +-------------+---------+---------+-------------+

and

> +------------+-------------+---------+
> | stat_value | instance_id | name    |
> +------------+-------------+---------+
> | 0.162      |           1 | Central |
> | 0.110      |           2 | CLI1    |
> | 0.103      |           3 | PAR3    |
> | 0.097      |           4 | MRS1    |
> +------------+-------------+---------+

Regards,

**Comment by zskarman** [comment]
Hi,

We got the similar issue, it looks, the poller has not updated their details to the broker.
Means all of the check results has updated exept the poller's status

Rgs, Zsolt

**Comment by lpinsivy** [comment]
@nakasix do you have network latency or retnetion files with CLI1 poller?

**Comment by nakasix** [comment]
@lpinsivy Hello, How can I check this ? Thank you.

**Comment by zskarman** [comment]
There is no latency, just end time in the centreon_storage.instances.

**Comment by lpinsivy** [comment]
You can check the directory /var/log/centreon-broker

**Comment by nakasix** [comment]
In /var/log/centreon-broker directory, i have "poller-module.log".
```
root@fidcl-pollercli1-infra-01:/home/user# ls -al /var/log/centreon-broker/
total 12
drwxrwxr-x 2 centreon-broker centreon-broker 4096 oct.  24 17:45 .
drwxr-xr-x 8 root            root            4096 oct.  27 06:25 ..
-rw-rw-r-- 1 centreon-engine centreon-engine  911 oct.  27 09:45 poller-module.log
```
Moreover, the content of "poller-module.log" file is :
```
root@fidcl-pollercli1-infra-01:/home/user# cat /var/log/centreon-broker/poller-module.log
Centreon Broker 3.0.10 log file closed
Centreon Broker 3.0.10 log file opened
[1509096350] config:  log applier: applying 1 logging objects
[1509096350] [0x7f9c59665740] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
```

**Comment by lpinsivy** [comment]
@nakasix, @zskarman it happens every time or punctual?

**Comment by zskarman** [comment]
somtimes not often but happens.

**Comment by nakasix** [comment]
@lpinsivy It happens from the beginning for my CLI1 poller, but all others pollers are OK.

**Comment by lpinsivy** [comment]
@nakasix I didn't see but you have 2 entry for CLI1

```
+-------------+---------+---------+-------------+
| last_update | running | name | instance_id |
+-------------+---------+---------+-------------+
| 1509030128 | 1 | Central | 1 |
| 1509030129 | 1 | CLI1 | 2 |
| 1509030128 | 1 | PAR3 | 3 |
| 1509030127 | 1 | MRS1 | 4 |
| 1508857512 | 0 | CLI1 | 5 |
+-------------+---------+---------+-------------+
```

Can you execute the following SQL request and restart CLI1

`DELETE FROM instances WHERE instance_id = 5;`

**Comment by nakasix** [comment]
@lpinsivy Thank you, it's OK ! But, I don't know why there were two instances of CLI1.

Regards,

**Comment by lpinsivy** [comment]
May be you duplicate your configuration?
