### ISSUE TITLE
Unable to use clapi for APPLYCFG

### ISSUE THREAD

**Issue by pfilbin90** [centreon/centreon#5835]
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.2
**Centreon Engine version**: 
MariaDB 10.1.21
**Centreon Broker version**: 
Not sure (how do I found this)
**OS**: 
centos 7
**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
1. sudo ./centreon -u username -p password APPLYCFG -v Central

**Describe the results you received:**
I get the error:

sudo: /etc/init.d/centengine: command not found
If I don't run sudo, then I get the error "Please check that your parameters are valid"

**Describe the results you expected:**
The poller refresh to work correctly.

**Comment by lpinsivy** [comment]
Hi,

Since Centreon web 2.8.2 we change the Centreon's sudoer file : 

```
## BEGIN: CENTREON SUDO

User_Alias      CENTREON=%centreon
Defaults:CENTREON !requiretty

# centreontrapd
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /sbin/service centreontrapd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centreontrapd reload

# Centreon Engine
CENTREON   ALL = NOPASSWD: /sbin/service centengine start
CENTREON   ALL = NOPASSWD: /sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /sbin/service centengine reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine start
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service centengine reload

# Centreon Broker
CENTREON   ALL = NOPASSWD: /sbin/service cbd start
CENTREON   ALL = NOPASSWD: /sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /sbin/service cbd reload
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd start
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd stop
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd restart
CENTREON   ALL = NOPASSWD: /usr/sbin/service cbd reload

## END: CENTREON SUDO
```

**Comment by pfilbin90** [comment]
Which file exactly? What is the path for this file?
Thanks

**Comment by lpinsivy** [comment]
File is /etc/sudoers.d/centreon

Regards,

**Comment by pfilbin90** [comment]
With the updated sudoers file, I still receive the same error when I try to run:

`./centreon -u admin -p password -a APPLYCFG -v 1`

The error output is:
```
PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on line 0
2017-11-01 16:50:25 - APPLYCFG
Configuration files generated for poller '1'

Warning: Centreon Poller 1 can restart but configuration is not optimal. Please see debug bellow :
---------------------------------------------------------------------------------------------------
[1509551426] [12715] Reading main configuration file '/usr/share/centreon//filesGeneration/engine/1/centengine.DEBUG'.
[1509551426] [12715] Processing object config file 
  ## Other warnings edited out for this comment ##
[1509551426] [12715] Total Warnings: 37
[1509551426] [12715] Total Errors:   0

---------------------------------------------------------------------------------------------------

OK: All configuration files copied with success.

sudo: /etc/init.d/centengine: command not found

Return code end : 1
```

**Comment by lpinsivy** [comment]
Hi,

On CentOS 7 we use "systemd" instead of systemv to manage processus that is why you don't have entry for "centengine" in the /etc/init.d/ directory.

Moreover, we correct this in Centreon Web 2.8.14 : https://github.com/centreon/centreon/commit/2fd77dc379e0f1f8471918809c9ab2a2673cec17#diff-5a550f2c707eb43e204624a1e59ea31d

You can change only the line 230 for this patch or update Centreon.

Regards,

**Comment by pfilbin90** [comment]
Thank you so much for the help, it has been very useful.  I still don't quite understand what needs to be done in order to get the clapi poller command to work properly.  

When you say "You can change only the line 230 for this patch" does that mean I can change just one file within my current centreon server?  Which file?
Do I have to implement the code that you linked here 
[2fd77dc#diff-5a550f2c707eb43e204624a1e59ea31d](https://github.com/centreon/centreon/commit/2fd77dc379e0f1f8471918809c9ab2a2673cec17#diff-5a550f2c707eb43e204624a1e59ea31d)?  If I have to implement this code, how do I do this? 
Thank you again for all the assistance.

**Comment by lpinsivy** [comment]
Edit the file /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php

Change line 230:
`$msg_restart = exec("sudo " . $nagios_init_script . " reload", $stdout, $return_code);`

By:
`$msg_restart = exec("sudo service " . $nagios_init_script . " reload", $stdout, $return_code);`

And change line 310:
`: $nagios_init_script = "/etc/init.d/centengine";`

By:
` : $nagios_init_script = "centengine";`

And line 321:
`$msg_restart = exec(escapeshellcmd("sudo " . $nagios_init_script . " restart"), $lines, $return_code);`

By:
```
 $msg_restart = exec(
    escapeshellcmd("sudo service " . $nagios_init_script . " restart"),
    $lines,
    $return_code
);
```

**Comment by pfilbin90** [comment]
Well, I feel like I'm getting closer and closer.
Here is the error that I'm getting now:
```
OK: Centreon Poller 1 can restart without problem...

OK: All configuration files copied with success.

Redirecting to /bin/systemctl reload  cbd.service
Redirecting to /bin/systemctl reload  /etc/init.d/centengine.service
Failed to reload etc-init.d-centengine.service.mount: Unit etc-init.d-centengine.service.mount failed to load: No such file or directory.

Return code end : 6
```

Also tried POLLERRELOAD and got the same error message.  What's next? :D

**Comment by pfilbin90** [comment]
@lpinsivy Are there any more changes to do with this or should I just take the plunge and try to upgrade Centreon instead?
Thanks

**Comment by lpinsivy** [comment]
@pfilbin90 can you update to latest version to have full correction ?

**Comment by pfilbin90** [comment]
@lpinsivy I have updated to latest versions.  
My current versions are as follows:
**Centreon Web version:**
2.8.16
**Centreon Engine version:**
1.8.1-1.el7.centos
**Centreon Broker version:**
3.0.7-1.el7.centos

I'm still getting the below error when running APPLYCFG.  What is causing this command to load centengine from "/etc/init.d"? That's not the correct location, right?  You said before that on Centos7 you use "systemd"

```
OK: All configuration files copied with success.

Redirecting to /bin/systemctl reload  cbd.service
Redirecting to /bin/systemctl reload  /etc/init.d/centengine.service
Failed to reload etc-init.d-centengine.service.mount: Unit etc-init.d-centengine.service.mount failed to load: No such file or directory.

Return code end : 6
```

**Comment by pfilbin90** [comment]
All I need is to be able to restart/reload the poller from within Centos.  If the CLAPI is broken, are there bash commands that I can use instead?  
If not, can I reinstall the CLAPI from scratch some how?

**Comment by lpinsivy** [comment]
Yes on CentOS 7 the command is:
# systemctl restart cbd

You can't reinstall CLAPI because the API is included into Centreon Web.
