### ISSUE TITLE
Recurring Downtimes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#584]
---

Author Name: **Constantin Lotz** (Constantin Lotz)
Original Redmine Issue: 3737, https://forge.centreon.com/issues/3737
Original Date: 2012-10-02

---

Hey there,

an awesome feature would be the following:

- Schedule recurring downtimes, for example: Downtime for all / or specific services each Saturday morning from 9-12.
I'm not sure if it is possible to disable the e-mail notification if a downtime is set for a service. I think i asked that some months ago, and it's not - so this would result in 10000 Mail notification for a downtime start & downtime end for each service. That would not be great.
So maybe the "Sheduled Downtime" should not set a downtime for a service, but set notification disabled for all these hosts in that specific time window. ( And add a notice msg on the service or sth. like that )

Kind regards,
Constantin

**Comment by julienmathis** [comment]
Recurring Downtime are now available.
