### ISSUE TITLE
Custom MACRO not interpreted in URL

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon#5846]
Hi,

Since we are in Centreon 2.8.13, (from 2.6), the custom MACRO ($_HOSTMYMACRO$) are not interpreted in "Host Extended Infos" => URL. This is a link to our wiki, and I get that : 

https://myurl.domain.tld/index.php/$_HOSTMYMACRO$#Goodhostname

In host configuration, this is what I declared : https://myurl.domain.tld/index.php/$_HOSTMYMACRO$#$HOSTNAME$

with HOSTMYMACRO : text_12_34

In Centreon 2.6 this works.

Thanks for your help (same problem in template or directly in host configuration).

**Comment by lpinsivy** [comment]
Hi,

I try with Centreon web 2.8.15 and custom macro are interpreted.

Did you generate and export configuration then restart poller?

**Comment by Hellnino18** [comment]
Hi Laurent,

It works in Monitoring > Status Details > Services page, but in Monitoring > Status details > Hosts, it doesn't work. My custom MACRO isn't replaced and in my URL I have %24MYCUSTOMMACRO%24

And yes I have generated, exported then restart my poller.

**Comment by lpinsivy** [comment]
@Hellnino18 can you try this patch on www/include/monitoring/status/Hosts/xml/hostXML.php:

```
@@ -375,7 +375,7 @@
         $str = str_replace("\$HOSTSTATE\$", $obj->statusHost[$data['state']], $str);

         $str = str_replace("\$INSTANCEADDRESS\$", $instanceObj->getParam($data['instance_name'], 'ns_ip_address'), $str);
-        $obj->XML->writeElement("hnu", CentreonUtils::escapeSecure($hostObj->replaceMacroInString($data["notes_url"], $str)));
+        $obj->XML->writeElement("hnu", CentreonUtils::escapeSecure($hostObj->replaceMacroInString($data["name"], $str)));
     } else {
         $obj->XML->writeElement("hnu", "none");
     }
```

**Comment by Hellnino18** [comment]
@lpinsivy thx it works 👍

**Comment by adr-mo** [comment]
OK everything looks good to me.
