### ISSUE TITLE
Inoperant Contact group additive inheritance check box for a service

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5852]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.15

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: el6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Service template  ST linked to contact group 1 CG1
2. Service configured with ST, linked to contact group 2 CG2
3. Check box Contact group additive inheritance set to yes in Notification tab for ST and Service, Notification enabled set to yes
4. After configuration export, go to Monitoring > Status details > Service

**Describe the results you received:**
 CG2 is displayed in Contact groups notified for this service

**Describe the results you expected:**
 CG1 and CG2 are displayed in Contact groups notified for this service

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by cgagnaire** [comment]
This PR fixe this problem : https://github.com/centreon/centreon/pull/5802

**Comment by cgagnaire** [comment]
And the informations shown in the 'Status details' page come from the database so you don't need to reload the configuration.

**Comment by lpinsivy** [comment]
linked to #4869

**Comment by lpinsivy** [comment]
linked to #6176 & #6467
