### ISSUE TITLE
 "Interval Length" modified is not exported

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#5856]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.15

**Centreon Engine version**: 1.8.x

**Centreon Broker version**: 3.0.x

**Steps to reproduce the issue:**
1. Go to "Administration  >  Parameters  >  Monitoring" 
2. Modify "Interval Length"
3. Export configuration of a poller

**Describe the results you received:**

"Interval Length" is not modified

**Describe the results you expected:**

"Interval Length" must be modified

**Additional information you think important (e.g. issue happens only occasionally):**

Need to edit poller an save before export configuration to have correct "Interval Length"

**Comment by lpinsivy** [comment]
should be fixed by #5567

**Comment by adr-mo** [comment]
Fixed a long time ago.

Can now be closed...
