### ISSUE TITLE
[Question] DB Cleanup

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5864]
Is there any built-in tool that cleanup database for duplicate entries such as ghost hosts and services.
Ive been getting lots of duplicate entries over the year
![image](https://user-images.githubusercontent.com/25208457/32525765-2cba6648-c40d-11e7-8343-ee7f42634371.png)

**Comment by lpinsivy** [comment]
No their is no tool for that.

But are you sure is duplication and not 2 different couple "host / service" ?
