### ISSUE TITLE
Selenium compatibility with centreon

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#5872]
Hi, 

I am using Selenium for web automation testing and i would like to integrate it with centreon monitoring so that i got alerts when tests fails.
I successfully configured Selenium 2.45.0 to work with centreon Selenium Plugin. but this version of SELENIUM is deprecated and compatibility with new browsers like firefox > 47 is not possible.
it is necessary for me to test using an updated version of firefox and for that i must go to selenium 3.x. but it seems that centreon plugin is not compatible with these versions.

Can you please confirm the compatibility with your plugin or if there is any update ?
have you successfully got this to work ?

thank you for your help.

regards.

**Comment by saharawolf** [comment]
Any clue please ?

**Comment by Sims24** [comment]
Hello @saharawolf 

Centreon does not support Selenium 3 today as there has been a lot of change on it regarding to v2. 

We will work on it, not before 2018, anyway we would be glad if you share your use case and insights on selenium v3 in order we can make our work as efficient as possible. 

There is already a ticket on centreon-plugins github, please follow issue from there https://github.com/centreon/centreon-plugins/issues/529 

@lpinsivy will close this ticket as it's rather a plugin issue. 

Thanks ! 
Simon
