### ISSUE TITLE
hi ,installed centreon,the centreon web is a loop of Upgrade

### ISSUE THREAD

**Issue by kevindwei** [centreon/centreon#5874]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.15
**Centreon Engine version**: 
1.8.0-2.el6 
**Centreon Broker version**: 
3.0.10-3.el6
**OS**: 
centos6
**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker install cento6 from dockerfile

**Steps to reproduce the issue:**
1.when i installed centreons from docker file 
2.i open web localhost\centreons and configure the centreon
3.when i click the step 8 finish,the page goto upgrade,and when 5 Upgrade finished,it go to the first step to upgrade ,why is it current a loop of upgrade ? 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by kevindwei** [comment]
centreon-engine.x86_64 0:1.8.0-2.el6 
 centreon-broker.x86_64 0:3.0.10-3.el6

**Comment by lpinsivy** [comment]
Can you access to httpd logs and check for errors ?
Regards,

**Comment by kevindwei** [comment]
no errors happend from /etc/httpd/logs/error_log 

 $tail   /etc/httpd/logs/error_log 
[Fri Nov 10 14:14:00 2017] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Nov 10 14:14:00 2017] [notice] Digest: generating secret for digest authentication ...
[Fri Nov 10 14:14:00 2017] [notice] Digest: done
PHP Warning:  Cannot stat license file: /usr/share/centreon/www/modules/centreon-license-manager/license in Unknown on line 0
[Fri Nov 10 14:14:00 2017] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 configured -- resuming normal operations

**Comment by kevindwei** [comment]
[root@default /]# tail /var/log/centreon/centcore.log 
2017-11-10 14:17:40 - MySQL error : cannot connect to database centreon: Access denied for user 'centreon'@'localhost' (using password: YES) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)

**Comment by lpinsivy** [comment]
SELinux is disabled ?

**Comment by kevindwei** [comment]
yes .today, i install on my vm machine with centos6.9,  it is ok.    why on docker  installed  happend that?

**Comment by lpinsivy** [comment]
Hi,

I don't what was the issue with docker to generate a loop.
