### ISSUE TITLE
Massive change erase contact notification for service

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5877]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.15
**Centreon Engine version**: 
1.8
**Centreon Broker version**: 
3.0
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1. Add a contact notification on 2 services separatly
2. Do a massive change on this 2 service (for example add a notification interval)
3. Go back to the notification tab of the service, the contact are not present anymore

**Describe the results you received:**
The contact is erased

**Describe the results you expected:**
The contact should not be erased

**Comment by sangevin** [comment]
Got this on 2.8.11 too.

**Comment by adr-mo** [comment]
I've been trying to reproduce the issue in 2.8.15.

Everything works perfectly.

I've checked that the patch was included in the latest version and it is.

Same issue for the host has been fixed #5878
