### ISSUE TITLE
homepage menu ba has not Views

### ISSUE THREAD

**Issue by kevindwei** [centreon/centreon#5888]
**Centreon Web version**: 
2.8.15
**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 
centos6
**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware10

**question:
why i login the centrons, homepage menu ba has not Views?

**Comment by lpinsivy** [comment]
Hi,

Which Centreon web interface menu are you talking about? "Home > Custom Views"?

This is a personal dashboard, so you have to create your own views.

Regards,

**Comment by kevindwei** [comment]
No,not "Home > Custom Views". Previous versions of the home page has Views,

**Comment by lpinsivy** [comment]
Sorry but I don't understand with menu you are talking about.

Can you make print screen?
