### ISSUE TITLE
ACL filter by host category not working when host category is empty

### ISSUE THREAD

**Issue by sebastien-prudhomme** [centreon/centreon#5893]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.11 (but 2.8.x seems affected too)

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a host category with no hosts
2. Create an ACL ressource with all hosts, all service and filter on the previous host category

**Describe the results you received:**

Users associated to the ACL see all hosts and services

**Describe the results you expected:**

Users associated to the ACL see only hosts and services of the category (in that case, no hosts)

**Additional information you think important (e.g. issue happens only occasionally):**

Bug seems to be introduced by this commit 9809316e9af30da07eb0594555b7ec3149fd4d8b

First part of the should be something like that (check first if there are some hosts categories, then check if there are hosts in these hosts categories):

```php
    $request = "SELECT hc_id " .
            "FROM acl_resources_hc_relations, acl_res_group_relations, acl_resources " .
            "WHERE acl_resources_hc_relations.acl_res_id = acl_res_group_relations.acl_res_id " .
            "AND acl_res_group_relations.acl_group_id = '" . $acl_group_id . "' " .
            "AND acl_resources_hc_relations.acl_res_id = acl_resources.acl_res_id " .
            "AND acl_resources.acl_res_id = '" . $res_id . "' " .
            "AND acl_res_activate = '1'";
    $DBRESULT = $pearDB->query($request);

    if (!$DBRESULT->numRows()) {
        return $host;
    }

    $request = "SELECT host_host_id " .
            "FROM acl_resources_hc_relations, acl_res_group_relations, acl_resources, hostcategories_relation " .
            "WHERE acl_resources_hc_relations.acl_res_id = acl_res_group_relations.acl_res_id " .
            "AND acl_res_group_relations.acl_group_id = '" . $acl_group_id . "' " .
            "AND acl_resources_hc_relations.acl_res_id = acl_resources.acl_res_id " .
            "AND acl_resources.acl_res_id = '" . $res_id . "' " .
            "AND hostcategories_relation.hostcategories_hc_id = acl_resources_hc_relations.hc_id " .
            "AND acl_res_activate = '1'";
    $DBRESULT = $pearDB->query($request);

    if (!$DBRESULT->numRows()) {
        return array();
    }
```

**Comment by lpinsivy** [comment]
HI,

This is not a bug but the regular behavior.

The categories are used as a included union filter. So "All hosts" U "empty" = "empty".

Regards,

**Comment by sebastien-prudhomme** [comment]
But i got "All hosts" U "empty" = "All hosts", so this is a bug for me :-)

**Comment by lpinsivy** [comment]
No the union between "All hosts" & "empty" = "empty".

Categories is "& union" filters

**Comment by sebastien-prudhomme** [comment]
Sorry, in french.

Dans la documentation Centreon:

```
Les filtres par collecteur ou par catégorie d’objet sont des filtres d’inclusion (UNION). Seuls les objets appartenant à ces filtres en plus des groupes d’objets (hôtes et services) seront visibles.
```

Ce que j'en comprend, puisque "seul les objets appartenant à ces filtres...seront visibles"  c'est : aucun hôte n'appartenant au filtre, aucun hôte ne devrait s'afficher. Hors là tout s'affiche.

De plus si j'ajoute un hôte au filtre en question, l'utilisateur ne voit bien que ce simple hôte et pas tous les hôtes.

**Comment by lpinsivy** [comment]
Si tous les hôtes sont inclus et aucunes catégories n'est sélectionnée = tous les hôtes
Si tous les hôtes sont inclus et des catégories non vident sont sélectionnées = alors seulement l'union des deux est sélectionnés.

Une catégorie vide n'est pas considérée comme une catégorie valide

**Comment by sebastien-prudhomme** [comment]
Je ne peux être d'accord avec l'affirmation "Une catégorie vide n'est pas considérée comme une catégorie valide".

Lorsqu'on automatise les choses pour la création des machines, des groupes, des droits d'accès, etc, il arrive que les référentiels servant à cette automatisation ne soient alimentés que partiellement parce que les projets démarrent, sont déjà affectés à des personnes mais que les machines ne sont pas encore créées.

Si j'en reviens aux concepts mathématiques évoqués pour ces ACL, ne voit d'ailleurs pas le rapport avec l'union.

Ici il s'agit plus d'une intersection de 2 ensembles, sinon je vois mal comment il pourrait y avoir filtrage. Hors l'intersection de n'importe quel ensemble (ici tous les hôtes) avec l'ensemble vide (ici les hôtes de tel catégorie) est l'ensemble vide.
