### ISSUE TITLE
 Syslog module is not  be present

### ISSUE THREAD

**Issue by kevindwei** [centreon/centreon#5895]
---------------------------------------------
**Centreon Web version**: 
2.8.15

**OS**: 
centos6.9
**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware

**Steps to reproduce the issue:**
1.i installed centreon-syslog-server by yum and centreon-syslog-frontend by (./install.sh -u /etc/centreon)
2.Go on menu 'Configuration > Extensions > Modules' ,but  Syslog module is not  be present

**Comment by lpinsivy** [comment]
Hi,

The Centreon Syslog module is no more supported by Centreon developper team.

But why you use RPM for server part and tarball for frontend part?
