### ISSUE TITLE
Amélioration de l'information des versions

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon#5899]
Pouvez-vous s'il vous plaît améliorer le flux d'information quant aux nouvelles versions disponibles et distribuer clairement le release note.

De manière claire, c'est Impossible de savoir quelle est la version de Centreon disponible en production aujourd'hui. Merci de maintenir la page "Releases"

De même pour les autres projets, entre-autres centreon-plugins.

Merci !

**Comment by lpinsivy** [comment]
Merci pour le retour,

page mise à jour : https://github.com/centreon/centreon/releases

Cdt,

**Comment by stefanotoro** [comment]
Excellent. Beau travail.
Merci
Salutations
