### ISSUE TITLE
deprecated "Logger"

### ISSUE THREAD

**Issue by simo212** [centreon/centreon#590]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Get your module version***

For example, it is possible to get graph monitoring widget's version using following commands

-- For the RPM based systems --

```
$ rpm -qa | grep centreon-widget-graph-monitoring
```

-- For the deb based systems --

```
$ dpkg -l | grep centreon-widget-graph-monitoring
```
***Operating System***

*CentOS, Debian ...*

***Browser used***

- [ ] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. I reached the Custom View
3. And so on...

### Logs

**PHP error logs**

```
tail -f /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log
```

**Comment by ponchoh** [comment]
@simo212 this doesn't look like a "code related" issue (_deprecated "Logger"_). Please do expand on it.

**Comment by omercier** [comment]
@simo212 your issue gives no relevant information. Can you explain what is the problem?
Otherwise we will have to close this issue.

**Comment by simo212** [comment]
I never published this post, I am closing it. 
I think my account has been hacked
