### ISSUE TITLE
Service notification is sent for host contact with disabled contact inheritance options

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#5902]
Centreon version 2.7.7, Centreon Engine 1.5.1, Centreon Broker 2.11.5

config:
Host X's notification contact is set to contact A.
Host X, service Y's Implied Contacts field is empty and Contact additive inheritance option is unselected. Implied Contact Groups has 2 groups.

what happens:
Service Y sends notification to contact A and to the two Contact Groups.

what should happen:
Service Y should not send notification to contact A, only to the two Contact Groups.

Note: can't see this reflected in the db:
`$ mysql centreon -e "select service_description,service_alias from service where service.service_id in (select service_service_id from contact_service_relation where contact_id in (select contact_id from contact where contact_name='A'))"`
returns the two services contact A is visible for under Implied Contacts (this incidentally belongs to another host too)

**Comment by thiuyendang** [comment]
Not reproduced in 2.8.16-8
