### ISSUE TITLE
Nagvis in ces-standard-3.3

### ISSUE THREAD

**Issue by land14** [centreon/centreon#5907]
Hi

Can you please guide how to integrate Nagvis with centreon-standard-3.3-x86

Regards,
Mohan.

**Comment by lpinsivy** [comment]
Hi,

You can find documentation here : https://documentation.centreon.com/docs/centreon-nagvis/en/latest/

Regards,

**Comment by land14** [comment]
Hi 

i am unable to follow NagVis backend installation doc.

**Comment by land14** [comment]
Hi Please help me

**Comment by land14** [comment]
hi Are u their..

**Comment by lpinsivy** [comment]
Hi,

Why are you unable to follow NagVis backend installation?

**Comment by land14** [comment]
1)i have downloaded Download NagVis 1.7 and they told to extract to /usr/local/nagvis but their is no nagvis directory. I created manually nagvis directory and i extract.
2)they told to use 10-centreon.conf  and we have to edit 10-centreon.conf and copy given conf. file
3) they told to do below things but i did not understand.
# cd /tmp
# git clone http://<login>:git.centreon.com/centreon-nagvis-backend.git
[...]
# cd centreon-nagvis-backend
# cp GlobalBackendcentreonbroker.php /usr/local/nagvis/share/server/core/classes/

4) And their is no nagvis.ini.php in below location.
/usr/local/nagvis/nagvis.ini.php 

Please help i am new for for Linux.

**Comment by kozfelipe** [comment]
try at /usr/local/nagvis/etc/nagvis.ini.php

**Comment by kozfelipe** [comment]
you can modify /usr/local/nagvis/etc/nagvis.ini.php-sample to /usr/local/nagvis/etc/nagvis.ini.php

**Comment by land14** [comment]
hi 

their is no directory with the name of nagvis 

mv centreon-nagvis-backend / GlobalBackendcentreonbroker.php / usr /share/ nagvis/ share/server/ core / classes /

How to do above step.

**Comment by kozfelipe** [comment]
you should move your downloaded GlobalBackendcentreonbroker.php to /usr/local/nagvis/share/server/core/classes/GlobalBackendcentreonbroker.php if you followed the tutorial steps

**Comment by land14** [comment]
Sorry i have some dout

1)  After edit nagvis.ini.php

default thing i should remove and past below lines ?

[global]
authmodule = "CoreAuthModSQLite"
authorisationmodule = "CoreAuthorisationModSQLite"
dateformat = "Ymd H: i: s"


2) how to give permission for     file_group = "apache" 


3) After this line in website  Do not forget to enter the password of the database.
some configuration is their, where i have past the line.

Totally confused  please help me in spending some time.

**Comment by kozfelipe** [comment]
Im confused about your quotes, which guide are you following?
You must adapt [backend_centreonbroker] at nagvis.ini.php to your needs

**Comment by land14** [comment]
http://www.sugarbug.fr/atelier/techniques/ihmweb/cartographie_supervision/centreon-web28x_nagvis-185/

**Comment by kozfelipe** [comment]
1. I recommend you leave [global] intact
2. if you are using CentOS / CES leave `file_group="apache"` at [global]
3. 

> [backend_centreonbroker]
backendtype="centreonbroker"
statushost=""
dbhost="localhost" _(your database host)_
dbport=3306
dbname="centreon_storage"
dbuser="centreon" _(your database user)_
dbpass="motdepasse" _(your database password)_
dbinstancename="default"
htmlcgi="/centreon"
