### ISSUE TITLE
Oracle plugin : Multiple databases per server

### ISSUE THREAD

**Issue by boupjof** [centreon/centreon#5908]
Hello,

My question is in the title, is there a good way to monitor more tahn one database per server ? Actualy macro command and template are host based.
I can duplicate host to sufix it with database SID ?
Maybe, release a templace with service based macro ?

Thanks for helping

**Comment by lpinsivy** [comment]
Hi,

Today the best way is to use one "virtual" host per SID to monitor multiple SID on one DBMS

Regards,

**Comment by boupjof** [comment]
Sorry I dont reply.
Thanks for your help your solution is perfect for my usage.
