### ISSUE TITLE
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

### ISSUE THREAD

**Issue by DRAKUN** [centreon/centreon#5914]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**:  VM

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

I had already installed my poller but his status is always not running ( RED) and in some log file , i have this messages 

**Additional information you think important (e.g. issue happens only occasionally):**

[root@ centreon]# tail -f /var/log/centreon/centcore.log
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
cat: /var/lib/centreon-broker/prd003-module-stats.json: No such file or directory
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
cat: /var/lib/centreon-broker/prd003-module-stats.json: No such file or directory
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
cat: /var/lib/centreon-broker/prd003-module-stats.json: No such file or directory
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
cat: /var/lib/centreon-broker/prd003-module-stats.json: No such file or directory
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
cat: /var/lib/centreon-broker/prd003-module-stats.json: No such file or directory

tail -f /var/log/centreon/nagiosPerfTrace.log
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by lpinsivy** [comment]
Hi,

What is your version of Centreon Web, Centreon Broker and Centreon Engine?
What is the distribution version?
Can you see in "Monitoring > Status Details" the items monitored by your poller?
Do you success the SSH key exchange? Can you connecte from 'centreon'@central to 'centreon'@poller' using SSH?

Regards,

**Comment by DRAKUN** [comment]
yes i can connect well.
I have installed the last Vm downloaded on this centreon web site

**Comment by kozfelipe** [comment]
you did not passed the ssh key to remote server properly

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
