### ISSUE TITLE
Contact missing from CLAPI export addcontact lines

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#5916]
Centreon version 2.7.7, Centreon Engine 1.5.1, Centreon Broker 2.11.5

All CLAPI export lines starting with `HOST;addcontact;` or `SERVICE;addcontact;` are missing the contact name, so will fail on import.
Lines starting with `HOST;addcontactgroup;` and `SERVICE;addcontactgroup;` do have the contact group names, so will be OK on import.

Example:
add to host A notification contacts B and C, notification contact group D
in the `centreon -e` output you'll see:

```
HOST;addcontactgroup;A;D
HOST;addcontact;A;
HOST;addcontact;A;
```

instead of what you should see:

```
HOST;addcontactgroup;A;D
HOST;addcontact;A;B
HOST;addcontact;A;C
```

**Comment by lpinsivy** [comment]
Please use Centreon 2.8.x because v2.7.x is no more supported

**Comment by btassite** [comment]
Unfortunately I need this functionality precisely because I want to import the config in 2.8.x :)
I guess I can clone the production system, update the clone to 2.8.x, then export the config and import it in the new environment.
