### ISSUE TITLE
Delay in centreon's graphics

### ISSUE THREAD

**Issue by machado701** [centreon/centreon#5919]
I have a delay of more than a day on my centreon's graphics.
I don't understand why, can you help please ?.

Thx
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.11
**Centreon Engine version**: 
1.7.2-3
**Centreon Broker version**: 
3.0.8-1
**OS**: 
RHEL 7.3
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

Can you check is you don't have temporary files in /var/lib/centreon-broker/ directory about RRD?
Do you have a special timezone set in Centreon web interface?
Can you check also the date of modification of RRD files into /var/lib/centreon/metrics/ directory?

Regards,

**Comment by machado701** [comment]
Hello
I 've a lot of file named central-rrd-master.queue.central-rrd-master-output2* in the directory /var/lib/centreon-broker/
Timezone defined in Centreon web interface : Europe/Paris
The date of modification of RRD file into /var/lib/centreon/metrics/ directory are good (Nov 27 11:18).

**Comment by lpinsivy** [comment]
Ok your have temporary files about RRD output of Centreon Broker RRD.

It's means that can't write performance data into RRD files as quickly as it receives data.

Can you check I/O of the /var/lib/centreon/metrics and /var/lib/centreon/status disk ?

The databases of Centreon are stored on the same disk?

May be you have to externalize the databases on another server to separate I/O and/orto use RRDCacheD to reduce I/O for RRD : https://documentation.centreon.com/docs/centreon/en/2.8.x/faq/performance.html#rrdcached

Regards,

**Comment by machado701** [comment]
Thanks for these informations.

I've a lot of I/O into this disk but the database is already installed on another server.
The RRDCacheD is not activated into my server, I will try to test this option.

Regards.

**Comment by machado701** [comment]
I don't have any file like : /etc/sysconfig/rrdcached or /var/rrdtool/rrdcached/rrdcached.sock in my server...
Is it normal ?

**Comment by lpinsivy** [comment]
If you don't start rrdcached yes you don't /var/rrdtool/rrdcached/rrdcached.sock

RRdCacheD is provides by rrdtool-1.4.7-1.el6.rfx.x86_64

**Comment by machado701** [comment]
I've rrdtool-1.4.8-9.el7.x86_64 installed in my server.
And when I activate rrdcached in the web interface I don' have any files like /etc/sysconfig/rrdcached or /var/rrdtool/rrdcached/rrdcached.sock

**Comment by lpinsivy** [comment]
You have to enable rrdcached from Centreon but to start process too ;)

`# service rrdcached start`

**Comment by machado701** [comment]
I've an error when i execute : # service rrdcached start
"Failed to start rrdcached.service: Unit rrdcached.service failed to load: No such file or directory."

**Comment by lpinsivy** [comment]
I suppose a problem with the configuration of rrdcached
