### ISSUE TITLE
Open-ticket - Create ticket in command line

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon#592]
Hello ! 

 

I would like to create a ticket in the command line before create a eventhandler script.

 

I use this synthax : 

/usr/lib/centreon/plugins/centreon_notification_centreon_opentickets_api.pl --plugin notification::centreon::opentickets::api::plugin --mode=open-service --api-hostname='IP' --api-port=80 --api-proto=http --api-username=admin --api-password='mypassword' --rule-name='Rule JIRA' --host-id=69 --service-id=355 --service-output='SNMP Table Request: Timeout' --service-state='UNKNOWN'  

I’ve this error : 

Method not found

 

I’m not sure, what is the “service-output” and someone know any solution ?

Centreon version : 22.04

**Comment by ponchoh** [comment]
# 👋 

@Xinerys , at the moment the "centreon_openticket" web service is only present on 22.10, please [upgrade](https://docs.centreon.com/docs/upgrade/upgrade-from-22-04/)

🚧

**Comment by Xinerys** [comment]
@ponchoh  Ok it's done :) i have the last version :)

**Comment by Xinerys** [comment]
And now the command to create a ticket is working :)

**Comment by Xinerys** [comment]
@ponchoh i would like to create a envent handlers who open a ticket if the service is "CRITICAL"

I understood who create script and the command in "Miscellaneous" and active the event handler in the host.

But i have big difficult to create the script can you help me ?

**Comment by ponchoh** [comment]
@Xinerys great news! For the script, I invite you to start a conversation through https://thewatch.centreon.com/ as the community can better help you there.

**Comment by Xinerys** [comment]
Thank.
