### ISSUE TITLE
Pollers not running after upgrading from 2.7.13 to 2.8.16

### ISSUE THREAD

**Issue by fallais** [centreon/centreon#5923]
Hello,

I upgraded from **2.7.13** to **2.8.16** by following this procedure : https://documentation.centreon.com/docs/centreon/en/2.8.x/upgrade/from_packages.html

Everything went fine, but my pollers are not showing up now.
The version seems not to be updated. And it is in NO state, but if I check in CLI on the pollers, they are running.

![centreon](https://user-images.githubusercontent.com/4034856/33269895-83e8615c-d382-11e7-93c4-6de47ad266dc.png)

I tried to search in all the issue, especially this one : https://github.com/centreon/centreon-engine/issues/86. But no luck.

OS is CentOS 6.9

Could you please help ?
Thanks a lot.

**Comment by lpinsivy** [comment]
Do you have Centreon Broker temporary files on your pollers?

**Comment by fallais** [comment]
Thanks a lot for helping me.
I'm really sorry but I do not know what is a **Centreon Broker temporary files**..

How can I check this please ?

**Comment by fallais** [comment]
Let me add that OS is **CentOS 6.9**

**Comment by fallais** [comment]
I restored my snapshot and tried to do it again, I followed exactly the procedure, I deleted all the retention files before doing it (I found them with the command `find / -name *.retention`).

But the result is the same.
The **Last Updated** of the pollers is yellow.
And the hosts and services are not updated anymore.

Please help, thanks.

**Comment by Sims24** [comment]
Hello @fallais , 

Looks like your pollers still in old centreon-engine version and then also old centreon-broker version. You need to upgrade your poller to have Centreon-engine 1.8.x and Centreon-broker 3.0.X. 

There is no backward compatibility between major version of scheduler and broker.

Hope this help

**Comment by fallais** [comment]
Hello, I did not say it, but it followed the procedure for all my pollers as well..

**Comment by Sims24** [comment]
Can you provide result of : 

#on pollers 
grep cbmod /var/log/centreon-broker/centengine.log

#on central 
Send logfiles in /var/log/centreon-broker/ directory ?

**Comment by fallais** [comment]
# Pollers

There is no `/var/log/centreon-broker/centengine.log` on pollers.
Only `v-srv-centreon-pooler-001-broker-master.log` and `watchdog.log`

But there is :

```
[root@v-srv-centreon-pooler-001 yum.repos.d]# grep cbmod /var/log/centreon-engine/centengine.log
[1511957923] [1730] Event broker module '/usr/lib64/nagios/cbmod.so' deinitialized successfully
[1511958511] [7466] Event broker module '/usr/lib64/nagios/cbmod.so' initialized successfully
```

## cat /var/log/centreon-broker/v-srv-centreon-pooler-001-broker-master.log

```
Centreon Broker 2.11.8 log file closed
Centreon Broker 3.0.11 log file opened
[1511958511] config:  state applier: broker_name is not  valid: allowed characters are ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 -_
```

# Central

## cat /var/log/centreon-broker/central-broker-master.log

```
...
...
Centreon Broker 2.11.8 log file closed
Centreon Broker 3.0.11 log file opened
[1511958505] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
```

## cat /var/log/centreon-broker/central-module-master.log

```
...
...
Centreon Broker 2.11.8 log file closed
Centreon Broker 3.0.11 log file opened
[1511958498] config:  log applier: applying 1 logging objects
[1511958498] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1511958498] error:   TCP: could not connect to localhost:5669: Connection refused
```

## cat /var/log/centreon-broker/central-rrd-master.log

```
...
...
Centreon Broker 2.11.8 log file closed
Centreon Broker 3.0.11 log file opened
[1511958505] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
```

## cat /var/log/centreon-broker/watchdog.log

```
Centreon Broker 3.0.11 log file opened
[1511958505] info:    watchdog: starting process 'central-broker-master'
[1511958505] info:    watchdog: process 'central-broker-master' started (PID 1238)
[1511958505] info:    watchdog: starting process 'central-rrd-master'
[1511958505] info:    watchdog: process 'central-rrd-master' started (PID 1239)
```

**Comment by Sims24** [comment]
Your broker name is invalid, please post your xml config file from pooler-001 /etc/centreon-broker/.xml.

`[1511958511] config:  state applier: broker_name is not  valid: allowed characters are ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 -_
`

Thanks a lot,
Simon

**Comment by fallais** [comment]
Hello,

Here it is.

```
[root@v-srv-centreon-pooler-001 ~]# cat /etc/centreon-broker/v-srv-centreon-pooler-001.xxx.xxx.fr-module.xml
<centreonBroker>
 <broker_id><![CDATA[4]]></broker_id>
 <broker_name><![CDATA[v-srv-centreon-pooler-001.xxx.xxx.fr-module]]></broker_name>
 <poller_id><![CDATA[2]]></poller_id>
 <poller_name><![CDATA[v-srv-centreon-pooler-001.xxx.xxx.fr]]></poller_name>
 <module_directory><![CDATA[/usr/share/centreon/lib/centreon-broker]]></module_directory>
 <log_timestamp><![CDATA[1]]></log_timestamp>
 <log_thread_id><![CDATA[0]]></log_thread_id>
 <event_queue_max_size><![CDATA[100000]]></event_queue_max_size>
 <command_file><![CDATA[]]></command_file>
 <cache_directory><![CDATA[/var/lib/centreon-broker]]></cache_directory>
 <logger>
  <name><![CDATA[/var/log/centreon-broker/v-srv-centreon-pooler-001-broker-master.log]]></name>
  <config><![CDATA[yes]]></config>
  <debug><![CDATA[no]]></debug>
  <error><![CDATA[yes]]></error>
  <info><![CDATA[no]]></info>
  <level><![CDATA[low]]></level>
  <max_size><![CDATA[50000000000]]></max_size>
  <type><![CDATA[file]]></type>
 </logger>
 <output>
  <name><![CDATA[v-srv-centreon-pooler-001.xxx.xxx.fr-module-master]]></name>
  <port><![CDATA[5669]]></port>
  <host><![CDATA[v-srv-centreon-central.xxx.xxx.fr]]></host>
  <retry_interval><![CDATA[60]]></retry_interval>
  <buffering_timeout><![CDATA[0]]></buffering_timeout>
  <protocol><![CDATA[bbdo]]></protocol>
  <tls><![CDATA[auto]]></tls>
  <negociation><![CDATA[yes]]></negociation>
  <one_peer_retention_mode><![CDATA[no]]></one_peer_retention_mode>
  <compression><![CDATA[auto]]></compression>
  <type><![CDATA[ipv4]]></type>
 </output>
 <stats>
  <type><![CDATA[stats]]></type>
  <name><![CDATA[v-srv-centreon-pooler-001.xxx.xxx.fr-module-stats]]></name>
  <json_fifo><![CDATA[/var/lib/centreon-broker/v-srv-centreon-pooler-001.xxx.xxx.fr-module-stats.json]]></json_fifo>
 </stats>
</centreonBroker>
```

**Comment by fallais** [comment]
Seeing this I now understand the dots are not allowed.. right ?
How can I fix this please ?

**Comment by fallais** [comment]
If I change the broker name in the GUI and generate the configuration again, I do not have this error anymore but a new one.

`Centreon Broker 3.0.11 log file opened
[1512049460] config:  state applier: endpoint name '.' is not valid: allowed characters are ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 -_`

What is the endpoint name please ? How can I change it ?

**Comment by fallais** [comment]
I fixed it.
I needed to change both the **Name** in the **General** tab of the broker configuration and the **Name** in the **output** tab of the broker configuration.

Then, I generated the configuration and exported it.
Finally, do not forget a `service centengine restart` and `service cbd restart`
