### ISSUE TITLE
Unable to APPLYCFG with clapi - etc-init.d-centengine.service.mount: No such file or directory

### ISSUE THREAD

**Issue by pfilbin90** [centreon/centreon#5926]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.9
**Centreon Engine version**: 
MariaDB 10.1.24
**Centreon Broker version**: 
3.0.7-1.e17.centos
**OS**: 
centos7
**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
1. cd /usr/share/centreon/bin
2. sudo ./centreon -u user -p pass -a APPLYCFG -v 1

**Describe the results you received:**

```
OK: All configuration files copied with success

Redirecting to /bin/systemctl reload cbd.service
Redirecting to /bin/systemctl reload /etc/init.d/centengine.service
Failed to reload etc-init.d-centengine.service.mount: Unit etc-init.d-centengine.serice.mount failed to load: No such file or directory.

Return code end : 6

```

**Describe the results you expected:**
I need to be able to restart the poller from the linux command line via a remote script.  Is there any other way to do this if the CLAPI will not function properly?

**Additional information you think important (e.g. issue happens only occasionally):**
/etc/sudoers.d/centreon has already been updated to the newest version

**Comment by lpinsivy** [comment]
Duplicate of #5835
