### ISSUE TITLE
centreon sudo issue

### ISSUE THREAD

**Issue by gabrielfsousa** [centreon/centreon#5927]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.12

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.8

**OS**: centos 7.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware

**Steps to reproduce the issue:**
exporting configuration 

**Describe the results you received:**

```
sudo: pam_unix(sudo:auth): conversation failed
sudo: pam_unix(sudo:auth): auth could not identify password for [centreon]
sudo: pam_sss(sudo:auth): authentication failure; logname= uid=1004 euid=0 tty= ruser=centreon rhost= user=centreon
sudo: pam_sss(sudo:auth): received for user centreon: 10 (User not known to the underlying authentication module)
sudo: centreon : command not allowed ; TTY=unknown ; PWD=/var/spool/centreon ; USER=root ; COMMAND=service centengine restart
```

![image](https://user-images.githubusercontent.com/722744/33321529-edf584e2-d43d-11e7-8b0c-c08fc2a97576.png)

**Comment by lpinsivy** [comment]
Hi,

Did you change default sudoer configuration or apply restriction on user right ?

**Comment by gabrielfsousa** [comment]
no

**Comment by lolokai** [comment]
Maybe SELinux ?

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
