### ISSUE TITLE
Export to PNG shows wrong max value

### ISSUE THREAD

**Issue by bdeschut** [centreon/centreon#5929]
**Centreon Web version**: 2.8.13
**Centreon Engine version**: 1.8.0
**Centreon Broker version**: 3.0.9
**OS**: CentOS release 6.9 (Final)

**Steps to reproduce the issue:**
1. Centreon Web > Monitoring > Performances
2. Add a traffic graph, press "i" to show min / max values
3. export to png
4. Note differences between min / max values

**Describe the results you received:**
Differences in min / max values between webui and exported png

**Describe the results you expected:**
The same values

Screenshots can be provided.

**Comment by bdeschut** [comment]
![after_export](https://user-images.githubusercontent.com/13234750/33369783-e52e395e-d4f5-11e7-84cd-93e6080e19e0.PNG)
![before_export](https://user-images.githubusercontent.com/13234750/33369785-e5d1274a-d4f5-11e7-8b00-7b78938be7d9.PNG)

**Comment by lpinsivy** [comment]
<img width="1373" alt="Sans titre" src="https://user-images.githubusercontent.com/3351916/61278943-711a9f00-a7b5-11e9-9bd9-7c3fa010ac6f.png">

Still present

**Comment by cgagnaire** [comment]
Fixed by @garnier-quentin
