### ISSUE TITLE
[DOC] Spelling error

### ISSUE THREAD

**Issue by sizeur** [centreon/centreon#5931]
Hello, in the french doc there is a missing letter in this title:

"Executer une commande spciale"

https://documentation-fr.centreon.com/docs/centreon/en/2.8.x/administration_guide/02k.html#executer-une-commande-spciale

**Comment by lpinsivy** [comment]
corrected by https://github.com/centreon/centreon/commit/c2194dae66dc0133e3777e954a288e1e88158290
