### ISSUE TITLE
Centreon stucks on Partitioning database tables	

### ISSUE THREAD

**Issue by troptop** [centreon/centreon#5935]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web-2.8.16-8.el7.centos.noarch

**Centreon Engine version**: 
centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**: 
centreon-broker-3.0.11-1.el7.centos.x86_64

**OS**: 
Centos 7
**Additional environment details (AWS, VirtualBox, physical, etc.):**
I make test on AWS

**Steps to reproduce the issue:**
1. Start the centreon installation
2. Follow the instruction until the step 7 
3. On step 7 the "Partitioning database tables" fails

**Describe the results you received:**
On the web page I get : 
Step | Status
-- | --
Configuration database | OK
Storage database | OK
Creating database user | OK
Setting up basic configuration | OK
Setting up configuration file | OK
Partitioning database tables | STUCK

**Describe the results you expected:**

Step | Status
-- | --
Configuration database | OK
Storage database | OK
Creating database user | OK
Setting up basic configuration | OK
Setting up configuration file | OK
Partitioning database tables | OK

**Additional information you think important (e.g. issue happens only occasionally):**
I know that we have to setup open_files_limit  or LimitNOFILE parameter to make it works. but it is not posible on AWS. I would like to know if there is another workaround or another version that does not have this restriction

**Comment by lpinsivy** [comment]
Hi,

Sorry but if you can't LimitNOFILE parameters the partitioning will crash in the future.
