### ISSUE TITLE
API - Get metrics values

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5938]
I couldnt find any documentation about object centreon_metric (metricsDataByService) at API REST.

**Comment by lpinsivy** [comment]
Hi,

Most of classes from www/api/class are developed to build select2 components for Centreon web forms.

**Comment by kozfelipe** [comment]
@lpinsivy 
I thought it was something similar to zabbix api data samples (https://www.zabbix.com/documentation/3.0/manual/api/reference/history/get?s[]=history&s[]=get)

**Comment by lpinsivy** [comment]
@kozfelipe so you want an API to extract metrics for a service.

This is a new feature ;)

**Comment by kozfelipe** [comment]
yes indeed

**Comment by nutzmdm** [comment]
There is no documentation for that but it'a already possible

**Comment by kozfelipe** [comment]
@lpinsivy , @nutzmdm Hi,

Is there a way to retrieve event logs timeline avaiability of a service though API?

![image](https://user-images.githubusercontent.com/25208457/35974304-b3aff0dc-0cbf-11e8-9de3-01d844620dd1.png)

I managed to retrieve its xml response from /include/eventLogs/xml/data.php, but I rather get it as json

**Comment by nutzmdm** [comment]
It's possible by using function "getStatusByService" from API

**Comment by kozfelipe** [comment]
@nutzmdm much appreciated

**Comment by lpinsivy** [comment]
@kozfelipe yes you can use something like:

`curl -s -k 'api.domain.tld/centreon/api/index.php?object=centreon_metric&action=metricsDataByService&ids=9_49&start=1561959592&end=1561970392' -H 'Content-Type: application/json' -H 'centreon-auth-token: jAw9wRP8NreB2aUYKDFkgW27HBzd9ifKOSAsgT5Tc6E='`

**Comment by kozfelipe** [comment]
@lpinsivy thanks ill check metricsDataByService although getStatusByService works too
