### ISSUE TITLE
Trap notification - bin file

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon#5940]
Hello,

Our setup : Centreon ISO - Centreon 2.8.16.

I am having a problem with trap alert notification. 
Indeed, I receive a mail with a file (ATT00001.bin) containing the text of the alert while it should be in the body of the mail. 
For instance :
 _***** centreon Notification *****
Notification Type: PROBLEM
Service:  Trap
Host: xxxx_

I would like to display this text directly in the body of the message. Is there a specific adjustment to the trap ?
Thank you.

**Comment by lpinsivy** [comment]
Hi

How do you receive the other alert by email?

Process is the same for active and passive service alert.

**Comment by boogaaloo** [comment]
All alerts are sent by the same command : host-notify-by-email.
Maybe this is a special character problem of the text of the alert...

**Comment by lpinsivy** [comment]
Do you use "host-notify-by-email" for hosts and "service-notify-by-email" for services (including traps)?

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
