### ISSUE TITLE
[Documention] Wrong info in DSM

### ISSUE THREAD

**Issue by Coolgeek789** [centreon/centreon#5941]
Documentation issue : 

In the documentaion for DSM there is "This service can stay disable in order to not show it in the monitoring page." in section "Configure Traps links".

The service the SNMP trap is linked to need to be enable for DSM to work.

**Comment by lpinsivy** [comment]
@garnier-quentin can you confirm?

**Comment by lpinsivy** [comment]
Corrected by this commit: https://github.com/centreon/centreon-dsm/commit/f9ad9c9f4fc6f87e618b00ffaa2d791608cd0047
