### ISSUE TITLE
[BDD] Table data_bin 

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#5944]
Hi,

I notice that the values entered in the 'value' column do not correspond to the retrieved value.

Example : 

- Value sent by the broker to the BDD: 

> INSERT INTO data_bin  (id_metric   , ctime, status, value)  VALUES (1608648, 1512389084, 0, '1.50634928e+08')

- Value entered in Database:

![image](https://user-images.githubusercontent.com/16583698/33561132-1c9e7c80-d912-11e7-8f06-899bfeb0e050.png)

- If we change the Float to Double field type

![image](https://user-images.githubusercontent.com/16583698/33561144-27aa68fa-d912-11e7-98d1-02814cd24f0c.png)

we notice that the values are more precise with a double type field.

Regards

**Comment by lpinsivy** [comment]
Hi @jben94!

What about the size to store Double against Float ?

**Comment by jben94** [comment]
Hi,

Float is coded on 4 bytes, against 8 bytes for the Doubles.
So yes it's true that it takes more space but the values are more real.

Data with the Double field:
![image](https://user-images.githubusercontent.com/16583698/33600039-64240cfa-d9a8-11e7-9342-8c6ffe13245e.png)


Data without the Double field:
![image](https://user-images.githubusercontent.com/16583698/33600086-7f6c9950-d9a8-11e7-95eb-c898425047d0.png)

**Comment by adr-mo** [comment]
Hi @jben94,

This will not be changed right now.

Although if there is any interest in doing this you could use the **stream_connectors**

Regards,

**Comment by jben94** [comment]
Hi @adr-mo ,

I no longer have this problem because I am no longer at the same customer. 
And I use the stream_connectors at my new client.

Regards,

**Comment by adr-mo** [comment]
Ok thanks for the answer

Regards
