### ISSUE TITLE
[DOC] Centreon Knowledgebase improvement

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#5947]
The documentation of Centreon Knowledge Base can be improved, between these 2 pages we have to perform some actions which are not described in the documentation:

https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/knowledge_base/prerequisites.html
https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/knowledge_base/wikiaccess.html

Between this 2 pages we could add this actions:

1) Create a database  for media wiki:
CREATE DATABASE wikidb;
GRANT ALL PRIVILEGES ON wikidb.* TO 'wikiuser'@'localhost' IDENTIFIED BY 'password';

2) Connect to the web interface with this address and complete the installation
YourIpAdresse/wiki/index.php

3) Copy the file localsetting.php in /usr/share/mediawiki/

4) Edit the file /etc/httpd/conf.d/mediawiki.conf and comment the following lines:
Path Formating
RewriteRule ^/*$ /wiki/index.php?title=Main_Page [L,QSA]
RewriteRule ^/*(.+)$ /wiki/index.php?title=$1 [PT,L,QSA]

5) Also, you have to reload the configuration of your poller if you want to want the icon to be present in the monitoring page.

**ATTENTION**: **The point 4 is very important**, if you don't comment these lines the centreon users will not be able to delete a page and the icon present in the Monitoring page which redirect to the wiki article will not be displaid.

**Comment by lpinsivy** [comment]
Hi,

This is the procedure to install mediawiki.

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
