### ISSUE TITLE
[CBD] : No insert in tables metrics and data_bin since last update

### ISSUE THREAD

**Issue by PhilCANDIDO** [centreon/centreon#5949]
---------------------------------------------------
Problem Description
---------------------------------------------------
Since last update to Centreon 2.8.16, we have a problem with table metrics.

We have the message in /var/log/centreon-broker/central-broker-master.log 

**[1512575241] error:   storage: insertion of metric 'srp' of index 8005 failed: could not execute prepared statement: Out of range value for column 'warn' at row 1 QMYSQL3: Unable to execute statement**

On Centreon Central, in directory /var/lib/centreon-broker, we have a lot of files "central-broker-master.queue.central-broker-perfdata-master."

Afert few hour the FS /var/lib/centreon-broker is full. No informations are displayed in Centreon interface.

I tried to truncate the following tables : 

- TRUNCATE TABLE data_bin;
- TRUNCATE TABLE data_stats_daily;
- TRUNCATE TABLE data_stats_monthly;
- TRUNCATE TABLE data_stats_yearly;
- TRUNCATE TABLE metrics;

I tried to insert manually data in table metrics, and it works.
Table data_bin keep empty too.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.16

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.11

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare Esxi 5.5

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Did you update Centreon Broker too or just Centreon web?
