### ISSUE TITLE
Result of Host status list in Rest API is empty

### ISSUE THREAD

**Issue by fallais** [centreon/centreon#5951]
Hello,

Is it normal that the route `api.domain.tld/centreon/api/index.php?object=centreon_realtime_hosts&action=list` does not return anything but an empty array `[]` please ?

I follow this documentation : https://documentation.centreon.com/docs/centreon/en/2.8.x/api/api_rest/index.html#host-status

Thanks a lot.

**Comment by lpinsivy** [comment]
Hi,

Can you use the issue template to describe your issue because we need your platform software version

Regards,

**Comment by fallais** [comment]
Hello,

I am in the very last version **2.8.16** running on **CentOS 6.9**

Regards

**Comment by lpinsivy** [comment]
I can't reproduce:

# curl -s 'http://X.X.X.X/centreon/api/index.php?action=authenticate' --data 'username=superadmin&password=centreon'
# curl -s 'http://X.X.X.X/centreon/api/index.php?action=list&object=centreon_realtime_hosts' -H 'Content-Type: application/json' -H 'centreon-auth-token: NWE1NjJjMzQ1Yzc5MTQuOTk0NDY3MDM='

=> display list of all hosts.

Do you use a restricted account?

**Comment by fallais** [comment]
What should I check in the user configuration page to verify this please ? But I do not think so..

**Comment by lpinsivy** [comment]
In the Centreon web interface in "Configuration > Contacts", check if user can reach API.

**Comment by fallais** [comment]
![image](https://user-images.githubusercontent.com/4034856/35221166-71962a0c-ff79-11e7-9e45-2a67dae7e443.png)

And yes the user is in "All" group in ACLs

**Comment by lpinsivy** [comment]
And this user can view resources in Centreon web interface.

**Comment by fallais** [comment]
Yes it can, unless I am mistaken

**Comment by lpinsivy** [comment]
> Yes it can, unless I am mistaken

Did you made a connection test with Centreon web interface using this account?

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
