### ISSUE TITLE
Disappointing graph date

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#5957]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.16
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 
3.0.10
**OS**: 
rhel7
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
If you aren't in the same timezone of centreon server.
The date displaying in graph are little bit disappointing like in this screenshot.
![image](https://user-images.githubusercontent.com/11980015/33893454-bb870ed0-df5b-11e7-8663-bd4438121a56.png)

 
In graph the date is set with the system time.

**Describe the results you received:**
It's could be better if date was set with timezone centreon's configuration.

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
I move the timezone of my user from Paris to NY, graph date is correct with PR #7676

![Uploading Sans titre.png…]()
