### ISSUE TITLE
Reinstall Centreon from scratch

### ISSUE THREAD

**Issue by troptop** [centreon/centreon#5961]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8

**Centreon Engine version**: 
3.4
**Centreon Broker version**: 

**OS**: 
Centos 7
**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS Ec2 Instance

**Steps to reproduce the issue:**
1.Install centreon
2. Delete databases, conf.pm, centreon.conf.php

**Describe the results you received:**
Centreon Fails

**Describe the results you expected:**
Reinstall centreon process running

**Additional information you think important (e.g. issue happens only occasionally):**

I would like to know what are the steps to perform to reinstall from scratch centreon.
What are the pre-requisite to reinstall centreon.

Thank you

**Comment by proxyconcept** [comment]
I think you should first delete databases and config files, then install centreon.

To understand when centreon display the install or the upgrade interface, look at the main controller /usr/share/centreon/www/index.php :
- when you install or upgrade centreon, you have a subfolder named "install" at the web root folder : /usr/share/centreon/www/install
- if the "install" subfolder exists and you don't have a config file /etc/centreon.conf.php => starting web install process
- if the "install" subfolder exists and you already have a config file /etc/centreon.conf.php => starting web upgrade process
- at the end of the web install or upgrade process : the "install" subfolder is removed

So if you want to redo the upgrade process, you must have the install subfolder : grab it from the package or simply remove and install the package (then you can copy the subfolder if you want to renew this operation)

**Comment by lpinsivy** [comment]
+1

**Comment by troptop** [comment]
I did it again in local, and it was working. But with AWS I could not do it.
A little bit strange.
But thank you for your anwser.
I am going to stay with the version 2.7 for a while as it is working perfectly on AWS.
I am looking forward to use the 2.8

**Comment by lpinsivy** [comment]
Do you use AWS CentOS 7 AMI?
