### ISSUE TITLE
Downtime - Possibility to define default duration

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#5963]
Hi,

When we set a downtime in fixed mode, by default, there are value of start time and end time. The difference beteween the both is 2 hours. I will prefered to have 30min.
But is it possible to change this default value ?

Thanks

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
This value is hard coded. I change this to an enhancement.

**Comment by CPbN** [comment]
Would make sense to take the value of the already existing duration option :

<img width="632" alt="opt" src="https://user-images.githubusercontent.com/40244829/54959570-cce8c000-4f59-11e9-80d8-f635f7657858.png">

In addition, this would require less development 👍

**Comment by CPbN** [comment]
See PR #7357 for a fix 👍

**Comment by sc979** [comment]
Hi @romsworld ,
The pull request with the modifications have been merged : https://github.com/centreon/centreon/pull/8486,
and will be merged on the specified next targeted version after validation.
Best Regards,
sc979
