### ISSUE TITLE
[2.8.16] Hostgroup alias rename, not visible in the monitoring view

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#5967]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.16

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.11

**OS**:  CentOS  7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ALL

**Steps to reproduce the issue:**
1. Create an hostgroup, add an host into it
2. Regenerate the conf + restart
3. Change : name hostgroup **alias**
4. Regenerate the conf + restart

**Describe the results you received:**
Look into : Monitoring  >  Status Details  >  Hostgroups Summary
The host alias do not change

**Describe the results you expected:**
In Monitoring  >  Status Details  >  Hostgroups Summary, the alias must be shown properly

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

In fact Hostgroup alias is never set in centreon_storage database.
The web interface use "<hg_name> ( <hg_name> )".
The best way is to remove "( <hg_name> )" part.

Regards,

**Comment by BenoitPoulet** [comment]
Hello,

Bad news, i was planning to use this field to link Centeon to our CMDB database : put in Alias the serial number the the hostgroup in our CMDB.

**Comment by lpinsivy** [comment]
@BenoitPoulet as a workaround you can use another field like "Notes", "Notes URL" or "Action URL".

**Comment by BenoitPoulet** [comment]
@lpinsivy  Good idea.
But are theses fields manageable by the API ? (read and write) 

1. I only the fields "name" & "alias"
2. The search can not be configured as strict or non-strict. (i'm looking only for 1 HG, the request send me 2)

This request 
```
{
  "action": "show",
  "object": "hg",
  "values": "0000_PF_Interne"
}
```
Result : 
```
{
    "result": [
        {
            "id": "559",
            "name": "0000_PF_Interne",
            "alias": "0000_PF_Interne"
        },
        {
            "id": "661",
            "name": "0000_PF_Interne_Network",
            "alias": "0000_PF_Interne_Network"
        }
    ]
}
```

**Comment by lpinsivy** [comment]
No the search use SQL LIKE function.
And I don't know if you can configure "Notes", "Notes URL" or "Action URL" with API. Check the documentation or create tickets if not.
