### ISSUE TITLE
Strange caracters in Plugin-Pack & subscription menu

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon#5975]
Since I don't know when, I have this in Configuration  >  Plugin pack  >  Configuration and in Administration  >  Extensions  >  Subscription
![screenshot](https://user-images.githubusercontent.com/30388990/34359575-6bd9a89e-ea59-11e7-9c78-8d97b3b1ba9f.jpg)
What happen ?

**Comment by lpinsivy** [comment]
Hi,

Can you try to restart Apache?

**Comment by oasisck** [comment]
Hi,
Same things and I just yum update

**Comment by lpinsivy** [comment]
What is your version of PHP and php-zend-guard-loader?

# rpm -qa | egrep "php.*(cli|guard)"
php-zend-guard-loader-6.0.0-4.el7.centos.x86_64
php-cli-5.4.16-43.el7_4.x86_64

**Comment by oasisck** [comment]
A bit different indeed
php-zend-guard-loader-5.5.0-3.el6.art.x86_64
php-cli-5.3.3-49.el6.x86_64

**Comment by thiuyendang** [comment]
Couldn't reproduce issue, whereas same configuration (CentOS 6.9, Apache 2.2.15, Centreon Web installed with iso 3..4.2 and upgraded until 2.8.17 version, same php-cli and zend-guard)
LM 2.2.0, PPM 1.0.1 installed

**Comment by oasisck** [comment]
Ok thanks, I started from CES2 and I tested Nagvis for Centreon one time.
Anyway, I think I clean install one day
