### ISSUE TITLE
Problème d'utilisation des Traps SNMP dans Centreon 3.4.1

### ISSUE THREAD

**Issue by cyrmoon** [centreon/centreon#5979]
Bonjour, je m' excuse par avance si ce sujet fait partie des sujets déjà résolus, mais je n' arrive pas à faire marcher les traps avec centreon 3.4.1.
Pour identifier le problème, j' ai rentré centreon comme hôte en 127.0.0.1, avec le logiciel "snmpB" j' ai recupéré un iod de centreon avec la commande "snmpwalk  -v2c -c public 127.0.0.1 .1.3.6.1.2.1.2.2.1.7.1"
J' ai donc comme retour " IF-MIB::ifAdminStatus.1 = INTEGER: up(1)"
J' ai crée la trap snmp correspondante, créer un modèle de service passif avec le relation vers la trap "ifAdminStatus", crée le service correspondant. Fais un export de configuration.

Quand je fais un test d envoi de trap vers centreon avec la commande :
 " snmptrap -v2c -c public 127.0.0.1 '' 1.3.6.1.2.1.2.2.1.7 1.3.6.1.2.1.2.2.1.7.1 i 2"
je n' ai pas d' erreur mais le statut du service reste en ok ou en pending. Rien ne se passe.
J' ai bien des trames qui arrive dans /var/log/centeontrapd/

Qu' est que j' ai manqué? vous pouvez m' aider. Les services cpd et centreontrapd tournent bien.

Est ce que je devrais passer par centreon-dsm pour gérer les traps snmp ou c 'est inutile?

Rectification le service centreontrapd status me met " centreontrapd est mort mais le pid existe"
un "service centreontrapd start" lance bien en ok. Mais si je refais un "service centreontrapd status" après, j' ai le même message.

**Comment by lpinsivy** [comment]
Bonjour,

Il ne faut pas confondre le SNMP actif (snmpget/snmpwalk) et les traps SNMP (passif).

L'OID 1.3.6.1.2.1.2.2.1.7 est l'état ifAdminStatus d'une carte réseau et est accessible uniquement en actif.

Centreon propose les Traps SNMP standard linkUp (.1.3.6.1.6.3.1.1.5.4) et linkDown (.1.3.6.1.6.3.1.1.5.3).

**Comment by cyrmoon** [comment]
Merci de cette réponse juste, mais mon objectif est de créer des tapis passifs pour un switch dlink 3120, je peux donc travailler avec les oid du switch pour créer des traps ds centreon. Qu en pensez vous ? J ai fait des essais après avoir configuré l agent snmp du switch et rien n arrivé ds centreon. Centreontrapd ne fonctionne qu avec certains oid ?

**Comment by lpinsivy** [comment]
Si les traps SNMP ne sont pas définies dans Centreon et si elles ne sont pas rattaché à un service passif de l'hôte, alors elle ne sont pas traitées.

https://documentation-fr.centreon.com/docs/centreon/en/2.8.x/administration_guide/02k.html?highlight=trap#faq

**Comment by cyrmoon** [comment]
merci je vais essayer ca.

**Comment by KablanHenock** [comment]
Bonjour,
Moi aussi j'ai le même soucis sauf que dans mon cas des services passif on bien été associé au Traps SNMP standard linkUp (.1.3.6.1.6.3.1.1.5.4)  et quand je génère un trap depuis le server distant vers le poller pour simuler l'envoi d'un trap je n'ai aucune alarme sur mon central et toutes les trap générées sont logguées dans le /var/log/snmptrap.log et le /var/spool/centreontrapd/#xxxxxxxxx. 

j'ai besoin d'aide pour fixer ce problème

**Comment by KablanHenock** [comment]
je précise que j'ai suivi la documentation ci-dessous:

https://documentation-fr.centreon.com/docs/centreon/en/2.8.x/configuration_guide/advanced_configuration/traps.html

cdlt
