### ISSUE TITLE
[trap] Add a regexp system

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon#5980]
Hi,

For example, an equipment can send like 300 traps with specific OIDs. It's a mess to configure 300 traps in centreon-web.
The solution would be to have 2 modes in traps: REGEXP (new mode) and UNIQ (current mode). How it will work ? we look for in "UNIQ" traps and after in "REGEXP" traps.

**Comment by cgagnaire** [comment]
Here is a proposition : https://github.com/centreon/centreon/pull/5983

**Comment by lpinsivy** [comment]
@cgagnaire can you explain your PR with comment please?

Should be for next major version.

**Comment by cgagnaire** [comment]
@lpinsivy its done by the way

**Comment by lpinsivy** [comment]
done by #7679
