### ISSUE TITLE
Centreon 2.8.3 no templates (generic)

### ISSUE THREAD

**Issue by Elikha** [centreon/centreon#5981]
Bonjour à tous j'avais un problème avec centreon 2.8.3 , d'abord j'ai suivi à la lettre les indication d'installation du Poller mais ça met toujours "Non- en cours d'execution" et je ne sais pas pourquoi (peut-être faudrait faire un host/service pour que ça puisse marcher mais ça me parait illogique).

Et autre chose aussi les templates (host/service) sont vides , j'ai essayé d'installer (les paquets de centreon IMP) mais en vain les plugin-packs sont aussi vides (peut être lié au problème d'accès  à internet du serveur dû au proxy ...).
Merci par avance.

**Comment by lpinsivy** [comment]
Bonjour,

Il serait préférable de créer un ticket par problème, d'utiliser le template proposé et si possible de décrire ces derniers en anglais afin que l'ensemble des utilisateurs puissent bénéficier du retour d'expérience.

Depuis Centreon 2.8.0, il n'y à plus de templates car ceux-ci sont maintenant proposé par Centreon IMP (sans nécessité de créer un compte Centreon IMP trial).

il faut effectivement avoir un accès à Internet et Centreon Web 2.8.2 apporte cette possibilité de paramétrer un proxy via le menu "Administration > Parameters > Centreon UI".
