### ISSUE TITLE
'Hostgroup' Downtimes with LDAP user (no admin) does not work

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#5988]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.17
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.11

**Steps to reproduce the issue:**
1. Connect with LDAP user (no admin) on Centreon Web
2. Go on "Monitoring - Downtimes" 
3. Add a downtime on 'Hostgroup'

**Describe the results you received:**
Downtime is not saved

**Describe the results you expected:**
Downtime should be saved

Best Regards

**Comment by Moujimouja** [comment]
Hi,

Thanks for the feedbacks. I can't reproduce on 20.04 version.

I close the case.
