### ISSUE TITLE
[CLAPI] - service setparam: unable to change description

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#5991]
I don't know if it's a bug or an enhancement :)
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.16

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.11

**OS**: centOS 6.9 (CES3.4)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Try to rename service description about case sensitive like this
`/usr/share/centreon/bin/centreon  -u clapi -p pass -o service -a setparam -v "MY-HOST;P_-_CRON;description;P_-_Cron"`

**Describe the results you received:**
Object already exists

**Describe the results you expected:**
Object renamed with correct case sensitive
P_-_CRON -> P_-_Cron

Actually, I must make two actions for that:
rename the service with a temporary name like P_-_CRON -> P_-_Cron2
   `/usr/share/centreon/bin/centreon  -u clapi -p pass -o service -a setparam -v "MY-HOST;P_-_CRON;description;P_-_Cron2"`
rename another time with final name P_-_Cron2 -> P_-_Cron
  ` /usr/share/centreon/bin/centreon  -u clapi -p pass -o service -a setparam -v "MY-HOST;P_-_Cron2;description;P_-_Cron"`

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

In Centreon, Name of service or host is not case sensitive. That why CRON = cron
