### ISSUE TITLE
graphs are slowly move the interface on the left

### ISSUE THREAD

**Issue by pkriko** [centreon/centreon#5996]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.x

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. choose any chart in Monitoring  >  Performances  >  Graphs
2. Play with the double arrow to go back in time
3.

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/32265250/34615052-b8b49fac-f233-11e7-9d33-b5fa474d4a97.png)

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Can't reproduce with PR #7676
