### ISSUE TITLE
Partitioning tbale Logs - Cannot create new partition

### ISSUE THREAD

**Issue by barte91** [centreon/centreon#5997]
Centreon Web Version: 2.8.16
Centreon Engine version: 1.8.1
Centreon Broker version:  3.0.11
OS: Centos 6

I've an erro on my DB from any days.... I found the error in attachment in file /var/log/centreon/centreon/centreon-partitioning.log

This is very strange, the partitioning that want create is in the past (p1970....) why?
There is any workaround for this problem?
![errorcentreon](https://user-images.githubusercontent.com/19166634/34624058-13def0a6-f254-11e7-877e-76c9125b3277.JPG)

**Comment by lpinsivy** [comment]
@cgagnaire can you check?
