### ISSUE TITLE
Proxy-Pac centreon

### ISSUE THREAD

**Issue by Elikha** [centreon/centreon#6001]
Bonjour,

Je souhaiterais que mon serveur ait accès à internet et mon entreprise utilise un proxy (proxy pac), donc j'aurais besoin de votre aide s'il vous plait pour savoir comment configurer le proxy sur centos 6.8 pour pouvoir utiliser Wget et Yum.

Merci par avance.

**Comment by lpinsivy** [comment]
Have a look to Cntlm Authentication Proxy to implement proxy-pac on your server

**Comment by Elikha** [comment]
hello !
Thanks for your answer, I searched on cntlm but I didn't understand main of this and also I think that if I wanna use cntlm I should install it on centos before.
So by this way I would need to do in console Yum install cntlm but the problem is the proxy block yum and wget request.

**Comment by lpinsivy** [comment]
Have a look to 

- https://gist.github.com/lpf23/d3c4e1ef158c7fb4a909
- https://www.centos.org/docs/5/html/yum/sn-yum-proxy-server.html

**Comment by Elikha** [comment]
Thanks you @lpinsivy  but my main problem is how I will download cntlm rpm package (the 1st step of the 1st link) on my centos (because there is no graphic interface on my server and the only way to download is wget / yum but they are blocked by proxy).
