### ISSUE TITLE
[Minor] Periodic SQL Error

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#6002]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.11

**OS**: 2.6.32-696.16.1.el6.x86_64

**Steps to reproduce the issue:**
Errors present in sql-error.log every day at the same time

**Describe the results you received:**

`2018-01-06 01:42|0|0|DB Error: unknown error QUERY : DELETE FROM centreon_acl WHERE group_id NOT IN (SELECT DISTINCT acl_group_id FROM centreon.acl_groups WHERE acl_group_activate = '1')`

`2018-01-06 01:42|0|0|DB Error: no database selected QUERY : DELETE FROM centreon_acl WHERE group_id NOT IN (SELECT DISTINCT acl_group_id FROM centreon.acl_res_group_relations)`

`2018-01-06 01:42|0|0|DB Error: no database selected QUERY : SELECT acl_res_id, all_hosts, all_hostgroups, all_servicegroups FROM acl_resources WHERE acl_res_activate = '1' AND (all_hosts IS NOT NULL OR all_hostgroups IS NOT NULL OR all_servicegroups IS NOT NULL)`

`2018-01-07 01:42|0|0|DB Error: unknown error QUERY : DELETE FROM centreon_acl WHERE group_id NOT IN (SELECT DISTINCT acl_group_id FROM centreon.acl_groups WHERE acl_group_activate = '1')`

`2018-01-07 01:42|0|0|DB Error: no database selected QUERY : DELETE FROM centreon_acl WHERE group_id NOT IN (SELECT DISTINCT acl_group_id FROM centreon.acl_res_group_relations)`

`2018-01-07 01:42|0|0|DB Error: no database selected QUERY : SELECT acl_res_id, all_hosts, all_hostgroups, all_servicegroups FROM acl_resources WHERE acl_res_activate = '1' AND (all_hosts IS NOT NULL OR all_hostgroups IS NOT NULL OR all_servicegroups IS NOT NULL)`

`2018-01-08 01:42|0|0|DB Error: unknown error QUERY : DELETE FROM centreon_acl WHERE group_id NOT IN (SELECT DISTINCT acl_group_id FROM centreon.acl_groups WHERE acl_group_activate = '1')`

`2018-01-08 01:42|0|0|DB Error: no database selected QUERY : DELETE FROM centreon_acl WHERE group_id NOT IN (SELECT DISTINCT acl_group_id FROM centreon.acl_res_group_relations)`

`2018-01-08 01:42|0|0|DB Error: no database selected QUERY : SELECT acl_res_id, all_hosts, all_hostgroups, all_servicegroups FROM acl_resources WHERE acl_res_activate = '1' AND (all_hosts IS NOT NULL OR all_hostgroups IS NOT NULL OR all_servicegroups IS NOT NULL)`

**Additional information you think important (e.g. issue happens only occasionally):**
the error occurs every 01:42 AM

```
[root@OP-CENTREON centreon]# cat /etc/cron.d/centreon
# ########################################
#
# Cron Configuration for Centreon
#
PATH=/sbin:/bin:/usr/sbin:/usr/bin

# rewrite file with new cron line
CRONTAB_EXEC_USER=""

############################
# Cron for CentACL
* * * * * apache /usr/bin/php -q /usr/share/centreon/cron/centAcl.php >> /var/log/centreon/centAcl.log 2>&1

############################
# Cron for Centreon-Downtime
*/5 * * * * apache /usr/bin/php -q /usr/share/centreon/cron/downtimeManager.php >> /var/log/centreon/downtimeManager.log 2>&1

############################
# Cron to build state events
0 3 * * * centreon /usr/share/centreon/cron/eventReportBuilder --config=/etc/centreon/conf.pm >> /var/log/centreon/eventReportBuilder.log 2>&1

# Cron to build reporting
0 6 * * * centreon /usr/share/centreon/cron/dashboardBuilder --config=/etc/centreon/conf.pm >> /var/log/centreon/dashboardBuilder.log 2>&1

# Cron for knowledge base
*/5 * * * * centreon /usr/bin/php -q /usr/share/centreon/cron/centKnowledgeSynchronizer.php >> /var/log/centreon/knowledgebase.log 2>&1

##########################
# Cron for Centreon-Backup
30 3 * * * root /usr/share/centreon/cron/centreon-backup.pl >> /var/log/centreon/centreon-backup.log 2>&1
```

```
[root@OP-CENTREON centreon]# cat /etc/cron.d/centstorage
# ########################################
#
# Cron Configuration for Centreon
#
PATH=/sbin:/bin:/usr/sbin:/usr/bin

# rewrite file with new cron line
CRONTAB_EXEC_USER=""

# Cron for tracing Nagios Poller Performances
*/5 * * * * centreon /usr/share/centreon/cron/nagiosPerfTrace --config=/etc/centreon/conf.pm >> /var/log/centreon/nagiosPerfTrace.log 2>&1

# Cron for databin and logs purge
0 2 * * * centreon /usr/bin/php /usr/share/centreon/cron/centstorage_purge.php >> /var/log/centreon/centreon-purge.log 2>&1

# Cron for database partitioning
0 4 * * * centreon /usr/bin/php /usr/share/centreon/cron/centreon-partitioning.php >> /var/log/centreon/centreon-partitioning.log 2>&1
```

**Comment by lpinsivy** [comment]
Hi,

This SQL request is from /usr/share/centreon/cron/centAcl.php cron ACL but this cron is executed every 5 minutes. So why only an error around 01:42 AM!!!

Do you have another tools running around 01:42 AM

**Comment by kozfelipe** [comment]
I have no other tools beside the centreon's native backup. Thats a mistery why only the 01:42 execution generates error on centAcl.php

**Comment by lpinsivy** [comment]
Hi,

How many ressources (hosts, services, hostgroups, servicegroups ACL groups) do you have?

**Comment by kozfelipe** [comment]
Hi,

hosts: 2613
services: 8993 enabled, over 2k disabled
hostgroups: 62
servicegroups: 3
metaservices: 289
accessgroups: 2

**Comment by lpinsivy** [comment]
No backup on your LDAP servers around 01:42 AM?

**Comment by kozfelipe** [comment]
All my backups starts at 3:30 AM

**Comment by kozfelipe** [comment]
I'm closing this issue since this error has no critical impact over my environment. Soon I will be creating more satellite pollers to reduce overload during cron jobs. I appreciate your attention.

**Comment by lpinsivy** [comment]
Sorry to do not find root cause :(
