### ISSUE TITLE
'warning' option rejected by centreon_linux_snmp.pl

### ISSUE THREAD

**Issue by hgpit** [centreon/centreon#6004]
Hi,

Very recently (most likely since the last 2.8.17 Centreon update), some SNMP services aren't completing the checks.

For instance we use the SNMP storage check against our linux servers to check the storage of the '/' partition. These have worked fine for months and months.

The error we get is: 
**Unknown option: warning at /usr/lib/centreon/plugins/centreon_linux_snmp.pl line 142.**

I have tried running the check on the command line. The '/usr/lib/centreon/plugins/centreon_linux_snmp.pl' script doesn't appear to accept a 'warning' option/argument any longer?!

[root@svr-h002777 ~]# sudo -u centreon /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=svr-h003671 --snmp-version='2c' --snmp-community='hgp-ro' --storage '/' --name --display-transform-src='' --display-transform-dst='' --warning='80' --critical='90'
Unknown option: warning at /usr/lib/centreon/plugins/centreon_linux_snmp.pl line 142.

If I run it without the 'warning' option argument:
sudo -u centreon /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=svr-h003671 --snmp-version='2c' --snmp-community='hgp-ro' --storage '/' --name --display-transform-src='' --display-transform-dst=''
OK: Storage '/' Usage Total: 524.41 GB Used: 189.47 GB (36.13%) Free: 334.94 GB (63.87%) | 'used'=203438063616B;;;0;563078672384

If I inspect my plugin packs via the GUI, the Linux SNMP Plugin says 3.0.14 is installed with no updates available. I have rebooted the entire server, the **yum update** shows no outstanding updates.

Any suggestions on getting my check to work again would be very much appreciated.

Best Regards.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**:  1.8.1

**Centreon Broker version**:  3.0.11

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical dedicated server

**Steps to reproduce the issue:**
1. Run the Linux SNMP check with warning or critical options
2.
3.

**Describe the results you received:**
Check fails with "Unknown option: warning at /usr/lib/centreon/plugins/centreon_linux_snmp.pl line 142."

**Describe the results you expected:**
The check should complete.

**Additional information you think important (e.g. issue happens only occasionally):** Happens every time against all our linux hosts where the SNMP storage check is being used.

**Comment by kadrika** [comment]
I had the same issue. Fixed it by using --warning-usage and --critical-usage, instead of --warning and --critical.

**Comment by Sims24** [comment]
Please see below : 

https://github.com/centreon/centreon/issues/6006

**Comment by stefanotoro** [comment]
It seems that centreon_synology.pl does not work anymore with --warning and --critical, even whith --warning-usage and --critical-usage. For example
/usr/lib/centreon/plugins/centreon_synology.pl --mode cpu --hostname 10.91.96.16 --warning-usage 90 --critical-usage 95.
Updated today with Global Version: 20181019
