### ISSUE TITLE
Alternative Path to RRDTool Database For Monitoring Engine Statistics not working

### ISSUE THREAD

**Issue by 5145h** [centreon/centreon#6005]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.17-10.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-3.0.11-1.el7.centos.x86_64

**OS**: Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM

**Steps to reproduce the issue:**
1. I did configure an alternative path for RRDTool Database For Monitoring Engine Statistics to /centreon/nagios-perf/
2. 
3.

**Describe the results you received:**
The files are still generated under the default path /var/lib/centreon/nagios-perf/

**Describe the results you expected:**
The files to be generated under the configured path
[root@Central nagios-perf]# pwd
/centreon/nagios-perf
[root@Central nagios-perf]# ll
total 0

**Additional information you think important (e.g. issue happens only occasionally):**
`# ll /var/lib/centreon/nagios-perf/`
total 52
drwxrwxr-x 2 centreon centreon 4096 Mar 31  2017 perfmon-1
drwxr-xr-x 2 centreon centreon 4096 Jan  9 13:20 perfmon-10
drwxr-xr-x 2 centreon centreon 4096 Jan 10 08:20 perfmon-11
drwxr-xr-x 2 centreon centreon 4096 Jan 10 08:15 perfmon-12
drwxr-xr-x 2 centreon centreon 4096 Jan 10 08:30 perfmon-13
drwxrwxr-x 2 centreon centreon 4096 Mar 31  2017 perfmon-2
drwxrwxr-x 2 centreon centreon 4096 Jun  7  2017 perfmon-3
drwxrwxr-x 2 centreon centreon 4096 Jun  8  2017 perfmon-4
drwxrwxr-x 2 centreon centreon 4096 Jun  9  2017 perfmon-5
drwxrwxr-x 2 centreon centreon 4096 Nov 14 15:25 perfmon-6
drwxrwxr-x 2 centreon centreon 4096 Nov 14 15:45 perfmon-7
drwxrwxr-x 2 centreon centreon 4096 Dec  6 16:35 perfmon-8
drwxrwxr-x 2 centreon centreon 4096 Dec 19 08:15 perfmon-9
![nagios-perf](https://user-images.githubusercontent.com/21243985/34935627-2eefa9fe-f9e7-11e7-8334-63e89e316a19.JPG)

**Comment by lpinsivy** [comment]
Hi,

You right, this path is hard coded in the cron.
What was the reason to move this RRD file?

Regards,

**Comment by 5145h** [comment]
Hi Laurent, 

We have limited FSs and wanted to avoid FS full.

Thanks,
BR
