### ISSUE TITLE
Centreon not processing retention files

### ISSUE THREAD

**Issue by CyprienCentreon** [centreon/centreon#6007]
Hello

I now have the control "Broker-retention" in critical due to some service i had to shutdown two days ago

CRITICAL: Some failover(s) are active
**Informations d'état étendues | Checking config '/etc/centreon-broker/central-rrd.xml'
failover 'poller-rrd-display-failover': 0 file(s) found (0.00 B)
skipping temporary: no configuration set
Checking config '/etc/centreon-broker/central-broker.xml'
failover 'poller-perfdata-display-failover': 1 file(s) found (348.38 KB)
failover 'poller-rrd-display-failover': 1 file(s) found (903.07 KB)
failover 'poller-sql-display-failover': 1 file(s) found (348.38 KB)skipping temporary: no configuration set**

If i list my folder **/var/lib/centreon-broker/** i see that files are from 2 days ago
**-rw-rw-r--   1 centreon-broker centreon-broker 356738 15 janv. 12:45 poller_sql-display-failover.retention
-rw-rw-r--   1 centreon-broker centreon-broker 356738 15 janv. 12:45 poller_perfdata-display-failover.retention
-rw-rw-r--   1 centreon-broker centreon-broker 924743 15 janv. 14:23 poller_rrd-display-failover.retention**

i understand that this alert is still on because the retention files are still present.
What i don't understand is why they are still present ?
Centreon is not suppose to process data which is into the retention files ? and delete them when it's finished ?

Best regards

Cyprien

**Comment by lpinsivy** [comment]
Hi,

Yes Centreon will process data and delete retention file but maybe Centreon is still ready files.
Can you check is Centreon Broker logs?

**Comment by CyprienCentreon** [comment]
I did already, and it shows as below: 

**/var/log/centreon-broker/poller01-broker-display.log**
[1516179623] debug:   multiplexing: acknowledging 0 events from poller01-sql-display event queue
[1516179623] debug:   failover: reading event from endpoint 'poller01-rrd-display'
[1516179623] debug:   failover: reading event from multiplexing engine for endpoint 'poller01-rrd-display'
[1516179623] debug:   multiplexing: acknowledging 0 events from poller01-rrd-display event queue
[1516179623] debug:   failover: reading event from multiplexing engine for endpoint 'poller01-perfdata-display'
[1516179623] debug:   multiplexing: acknowledging 0 events from poller01-perfdata-display event queue
[1516179623] debug:   failover: reading event from multiplexing engine for endpoint 'poller01-sql-display'
[1516179623] debug:   multiplexing: acknowledging 0 events from poller01-sql-display event queue
[1516179623] debug:   failover: reading event from endpoint 'poller01-rrd-display'
[1516179623] debug:   failover: reading event from multiplexing engine for endpoint 'poller01-rrd-display'
[1516179623] debug:   multiplexing: acknowledging 0 events from poller01-rrd-display event queue
[1516179623] debug:   failover: reading event from multiplexing engine for endpoint 'poller01-perfdata-display'

**Comment by lpinsivy** [comment]
Do you have SQL errors in /var/log/centreon/sql-error.log on Centreon central server?

**Comment by CyprienCentreon** [comment]
i checked both on poller and central, but they are both from more than 1 month ago, so irrelevant in this case...

**Comment by lpinsivy** [comment]
can you check the /var/lib/centreon-broker/*.json statistic file of your broker and check the values:

- queue_file_enabled
- queue_file_enabled
- queued_events
- state
- status
- failover

**Comment by CyprienCentreon** [comment]
I have for the three json files, the following results, i removed from the answer a few fields such as read_filters, write_filters, and last_connection_attempt when it was same value as last_connection_attempt.

**/var/lib/centreon-broker/poller01-module-stats.json**
"endpoint poller01-display-output":
{
	"queue_file_enabled":"no",
	"queue_file_path":"/var/lib/centreon-broker//poller01-module.queue.poller01-display-output",
	"queued_events":"652",
	"state":"connected",
	"status":"reading event from multiplexing engine",
	"unacknowledged_events":"652",
	"failover":{}
},
	"endpoint poller01-module-output":
{
	"memory_file_path":"/var/lib/centreon-broker//poller01-module.memory.poller01-module-output",
	"queue_file_enabled":"no",
	"queue_file_path":"/var/lib/centreon-broker//poller01-module.queue.poller01-module-output",
	"queued_events":"433",
	"read_filters":"all",
	"state":"connected","status":"reading event from multiplexing engine",
	"unacknowledged_events":"433","write_filters":"all","failover":{}
}}

**/var/lib/centreon-broker/poller01-broker-display-stats.json**
"endpoint (external commands)":
{
	"event_processing_speed":"0","last_connection_attempt":"-1","last_connection_success":"-1",
	"last_event_at":"1516180142",
	"memory_file_path":"/var/lib/centreon-broker//poller01-broker-display.memory.(external commands)",
	"queue_file_path":"/var/lib/centreon-broker//poller01-broker-display.queue.(external commands)",
	"queued_events":"0","read_filters":"all",
	"state":"listening","write_filters":""
},
"endpoint poller01-broker-display":
{
	"last_connection_attempt":"-1","last_connection_success":"-1","last_event_at":"1516022832",
	"memory_file_path":"/var/lib/centreon-broker//poller01-broker-display.memory.poller01-broker-display",
	"queue_file_path":"/var/lib/centreon-broker//poller01-broker-display.queue.poller01-broker-display",
	"queued_events":"0",
	"state":"listening",
	"write_filters":"","poller01-broker-display-10":{"bbdo_input_ack_limit":"1000",
	"bbdo_unacknowledged_events":"477",
	"last_event_at":"1516616385",
	"queue_file_enabled":"no",
	"queued_events":"0",
	"state":"connected",
	"unacknowledged_events":"0","write_filters":""}
},
"endpoint poller01-rrd-display":
{
	"bbdo_input_ack_limit":"1000","bbdo_unacknowledged_events":"0",
	"event_processing_speed":"4.06667","last_connection_attempt":"1516022832","last_connection_success":"1516022832",
	"last_event_at":"1516616385",
	"memory_file_path":"/var/lib/centreon-broker//poller01-broker-display.memory.poller01-rrd-display",
	"queue_file_enabled":"no",
	"queue_file_path":"/var/lib/centreon-broker//poller01-broker-display.queue.poller01-rrd-display",
	"queued_events":"676","read_filters":"all","state":"connected","status":"reading event from multiplexing engine",
	"unacknowledged_events":"676","write_filters":"all","failover":{"event_processing_speed":"0","last_connection_attempt":"-1",
	"last_connection_success":"-1",
	"last_event_at":"1516022832",
	"queue_file_enabled":"no",
	"queued_events":"676",
	"read_filters":"all",
	"state":"connecting",
	"status":"",
	"unacknowledged_events":"676",
	"write_filters":"all","failover":{}}
},
"endpoint poller01-sql-display":
{
	"event_processing_speed":"4.06667",
	"last_connection_attempt":"1516022832",
	"last_connection_success":"1516022832","last_event_at":"1516616385",
	"memory_file_path":"/var/lib/centreon-broker//poller01-broker-display.memory.poller01-sql-display",
	"queue_file_enabled":"no","queue_file_path":"/var/lib/centreon-broker//poller01-broker-display.queue.poller01-sql-display",
	"queued_events":"0","read_filters":"all","state":"connected","status":"reading event from multiplexing engine","unacknowledged_events":"0",
	"write_filters":"all","failover":{"event_processing_speed":"0","last_connection_attempt":"-1","last_connection_success":"-1",
	"last_event_at":"1516022832","queue_file_enabled":"no","queued_events":"0","read_filters":"all","state":"connecting",
	"status":"",
	"unacknowledged_events":"0",
	"write_filters":"all",
	"failover":{}}
},
"endpoint poller01-perfdata-display":{
	"memory_file_path":"/var/lib/centreon-broker//poller01-broker-display.memory.poller01-perfdata-display",
	"queue_file_enabled":"no",
	"queue_file_path":"/var/lib/centreon-broker//poller01-broker-display.queue.poller01-perfdata-display",
	"queued_events":"0","read_filters":"all","state":"connected","status":"reading event from multiplexing engine",
	"unacknowledged_events":"0","write_filters":"all","failover":{"event_processing_speed":"0","last_connection_attempt":"-1",
	"last_connection_success":"-1",
	"queue_file_enabled":"no",
	"queued_events":"0","read_filters":"all",
	"state":"connecting",
	"status":"","unacknowledged_events":"0",
	"write_filters":"all",
	"failover":{}}
}}

**/var/lib/centreon-broker/poller01-rrd-display-stats.json**
"endpoint poller01-rrd-display":{
	"last_connection_attempt":"-1",
	"last_connection_success":"-1","last_event_at":"1516022832",
	"memory_file_path":"/var/lib/centreon-broker//poller01-rrd-display.memory.poller01-rrd-display",
	"queue_file_path":"/var/lib/centreon-broker//poller01-rrd-display.queue.poller01-rrd-display",
	"queued_events":"0",
	"state":"listening",
	"poller01-rrd-display-1":{"bbdo_input_ack_limit":"1000","bbdo_unacknowledged_events":"249","event_processing_speed":"3.33333",
	"last_event_at":"1516616600","queue_file_enabled":"no",
	"queued_events":"0","read_filters":"all","state":"connected",
	"unacknowledged_events":"0","write_filters":""}
},
"endpoint poller01-rrd-display":{
	"memory_file_path":"/var/lib/centreon-broker//poller01-rrd-display.memory.poller01-rrd-display",
	"queue_file_enabled":"no",
	"queue_file_path":"/var/lib/centreon-broker//poller01-rrd-display.queue.poller01-rrd-display",
	"queued_events":"13","read_filters":"all",
	"state":"connected",
	"status":"reading event from multiplexing engine",
	"unacknowledged_events":"0",
	"failover":{
		"event_processing_speed":"0","last_connection_attempt":"-1",
		"last_connection_success":"-1","last_event_at":"1516022832",
		"queue_file_enabled":"no","queued_events":"13",
		"state":"connecting",
		"status":"","unacknowledged_events":"0",
		"failover":{}
	}
}}

**Comment by lpinsivy** [comment]
What is your version of Centreon Broker ?

**Comment by CyprienCentreon** [comment]
Hello, here are the versions of the differents modules: 

rpm -qa | grep -i centreon\-broker
centreon-broker-3.0.11-1.el6.x86_64
centreon-broker-core-3.0.11-1.el6.x86_64
centreon-broker-cbd-3.0.11-1.el6.x86_64
centreon-broker-cbmod-3.0.11-1.el6.x86_64
centreon-broker-storage-3.0.11-1.el6.x86_64

**Comment by CyprienCentreon** [comment]
Do you have some other leads ?

**Comment by lpinsivy** [comment]
Did you rename on of the output of this broker?

**Comment by CyprienCentreon** [comment]
No, we didn't rename the output of the broker

**Comment by CyprienCentreon** [comment]
Please find attached the zip
[broker_retention_files.zip](https://github.com/centreon/centreon/files/1689473/broker_retention_files.zip)

**Comment by CyprienCentreon** [comment]
Hello, did you have time to have a look at the files ?

**Comment by lpinsivy** [comment]
OK I understand now your architecture.

You have 1 Centreon central server and another one with the module Centreon Poller Display 1.6.x.

So on the remote poller with the Centreon Poller Display module, some retention files are not executed.
In the web interface on distant poller, all information displayed are up to date?

**Comment by CyprienCentreon** [comment]
Yes that's right for the infrastructure
But yes, all information displayed are up to date.

**Comment by CyprienCentreon** [comment]
Do you have some other leads ?
I still cannot explain why the error is still there

**Comment by CyprienCentreon** [comment]
Please could you remove me from a doubt: failover files of sql, perfdata, and rrd are not only usefull when they are redundacy about servers ?
like if i had a central and a two pollers with the same config, one in active mode and the other in passive mode ?

This would explain why in my architecture, a central and a poller, the failover files are not processed.

**Comment by CyprienCentreon** [comment]
Please, if you have any information on the subject ?

**Comment by CyprienCentreon** [comment]
UP, if anyone have any information ?
