### ISSUE TITLE
Centcore Optimization

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#601]
---

Author Name: **Kevin Duret** (Kevin Duret)
Original Redmine Issue: 5079, https://forge.centreon.com/issues/5079
Original Date: 2013-12-26

---

Hi,

I think it should be nice to optimize Centcore.
For example :
- use single quotes instead of double quotes to avoid syntactic evaluation.
- use "and" instead of "&&"

Regards,

**Comment by julienmathis** [comment]
deprecated
