### ISSUE TITLE
Question about GET 'acknowledge'

### ISSUE THREAD

**Issue by uncleflo** [centreon/centreon#6017]
/usr/share/centreon/www/include/core/header/htmlHeader.php, line 208, branch 2.8.16-for-release, specifically the part on $_GET["acknowledge"] .

There are other php pages using $_GET["acknowledge"] .

Where is GET acknowledge set ? Is this some old overlooked residu during a feature removal ? I can not find any url x/y/z.php?acknowledge=abc

The reason for asking, is I need to know what format the value abc is. Is this a full string? 0 or 1? Alphanumeric? Or should it just be removed?

I am working on securing (parts of) centreon, and the code with $_GET["acknowledge"] as-is needs fixing

**Comment by lpinsivy** [comment]
regarding code source of monitoring menu pages, value is 0 or 1.

```
if ($o == "svcgrid_ack_1" || $o == "svcOV_ack_1" || $o == "svcSum_ack_1") {
    $rq1 .= "AND hosts.host_id IN ( "
        . "SELECT s.host_id FROM services s "
        . "WHERE s.acknowledged = '1' "
        . "AND s.enabled = 1) ";
}
```

If you are working on securing Centreon, can you provide your changes?

**Comment by uncleflo** [comment]
Thank you for your pointer. Yes, changes will be shared, currently ongoing work

**Comment by uncleflo** [comment]
@lpinsivy see pull request [6049](https://github.com/centreon/centreon/pull/6049)
