### ISSUE TITLE
ACL Ressources - Meta-Services graphics display

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#6018]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.15

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.10

**OS**: RH 6.9

**Steps to reproduce the issue:**
1. Go to the page : Monitoring > Performances
2. Put in the filter, Chart: meta

**Describe the results you received:**
Non-admin ACL problem, see discussion:  https://github.com/centreon/centreon/commit/4c9d3bfc4c6aeac40e3327fc69f0fb086cb1328c

- Problem with adding double quotes
- If the user does not see any Meta-service, here is what appears:
![image](https://user-images.githubusercontent.com/16583698/35222366-f564cd4e-ff7d-11e7-807c-6b49150ab585.png)

![image](https://user-images.githubusercontent.com/16583698/35222262-9fda3fbc-ff7d-11e7-8f82-5eca6276c6a8.png)

**Additional information you think important (e.g. issue happens only occasionally):**

Here are the changes made. https://github.com/jben94/centreon/commit/782799743e42b489408b31b5f5c60ffaa31d0df8

**Comment by lpinsivy** [comment]
linked to #5867
