### ISSUE TITLE
Lost recently created hosts/services + other bugs after Centreon Web 2.8.17 update

### ISSUE THREAD

**Issue by larkoie** [centreon/centreon#6020]
Hi,
This saturday we restarted the server hosting our centreon apps. When Centreon started it was updating the Centreon Web to 2.8.17 (from 2.8.16).
We already did this update on the dev server which has the same config than this production server. 

However after the update, we were not able to login anymore with our LDAP users. I had to log with the internal centreon admin user and re-enable ldap authentication on all the users profiles.
I also noticed that the hosts+services+commands that I've created on thursday and friday just disappeared from the web-ui. I checked in the DB and the config files and there was no trace of it!
I recreated them and since then it's running fine but this crazy behavior is not making me confident about the next server restart.
I did subscribed to the free account for the additional plugin pack last week and installed some of them. After ther update/restart, the plugin manager and licence manager extensions were disabled and all the plugin packs were uninstalled. I re-installed the extensions but when i want to connect to the "subscription" page i have an error : "**Error during getting IMP Company Token.**" and in the **_license-manager.log_** i have this line : "**[RestConflictException] https://api.imp.centreon.com/api/license-manager/instance : Instance already registered**."

**edit** : Also lost all our ACL... (no trace in the DB)
Found out that a lot of tables were purged (from centreon-purge.log) just after the server reboot. I guess that it purged the metrics tables from the no more existing hosts.
Also found in the Web-UI logs that it says the last changed before the server reboot (january 21st) was on the 15th while i'm 100% positive that I added 2 hosts, several commands and several service templates and services on the 18th and 19th. It's a total mystery, i don't get it :(

![2018-01-24 14_57_50-centreon - it network monitoring](https://user-images.githubusercontent.com/33937394/35336138-b9b0c0f0-0117-11e8-89aa-9c214457073f.png)

**I did not see anything looking bad in the logs. Does anybody have an idea on what could have happened during the upgrade or/and restart of the server that could cause that?
When an item is created in the DB, what could cause it's deletion without human intervention? is there a global retention file/table that was not saved and the server restart erased it or something like this?**

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: Latest i guess

**OS**: CentOS 7

Thanks for your help.
Cheers

**Comment by lpinsivy** [comment]
Hi,

The migration from Centreon 2.8.16 to Centreon web 2.8.17 didn't manage SQL server except this query:
```
-- Change version of Centreon
UPDATE `informations` SET `value` = '2.8.17' WHERE CONVERT( `informations`.`key` USING utf8 ) = 'version' AND CONVERT ( `informations`.`value` USING utf8 ) = '2.8.16' LIMIT 1;
```
https://github.com/centreon/centreon/blob/2.8.x/www/install/sql/centreon/Update-DB-2.8.16_to_2.8.17.sql

So the root cause is from another action, maybe a rollback of configuration from a backup/snapshot made by a user...

**Comment by larkoie** [comment]
Thanks for your answer.
I thought about this but when checking the general logs of the server + the other applications it looks like there was no other downtime than the reboot and there are no gap in the logs.
On top of this, the ACL were configured almost a month ago and LDAP as "Authentication source" was set 2 months ago for each users so it can't be related to a backup/snapshot restoration as we would have lost lot's of other things.
I could not find any clue on the web about somebody who faced the same things it's weird. And the fact that we can see lots of metrics/status tables purged in the centreon-purge.log right after the reboot indicates that it was not a global rollback right? (because if it was the case the metric/status table would not be there either)

**Comment by lpinsivy** [comment]
If entries was deleted in Centreon configuration, it's regular operation for centreon-purge to delete entries in 'centreon_storage' table.

The problem is why items from the Centreon configuration was deleted (LDAP configuration, some hosts and service,s ACL, ...).
The Centreon Web upgrade from 2.8.16 to 2.8.17 only change in database the version of the product...

**Comment by larkoie** [comment]
Thanks for the databases changes contained in this upgrade.
I double checked everything on the OS/platform side and could not find any evidence of other lost data in my other applications. It only happened to Centreon.
Do you have any idea of what could have done this? Is there a retention file somewhere that did not write the changes I made to the actual config files/Database tables?
I searched for something like this but from my understanding adding items like hosts, services, commands is pretty straightforward as it writes it to the DB instantly and then add it to the config files once the poller is restarted with the "generate config files" + "Move export files" options selected.

**Comment by lpinsivy** [comment]
They are no temporary file use by Centreon web interface. All changes are stored into database.

For your second issue, send an email to imp[at]centreon.com

**Comment by larkoie** [comment]
OK I'll check with them and post the solution when i have it. Appreciate your help, thanks!

**Comment by larkoie** [comment]
Update for the "Error during getting IMP Company Token."
It's a missing value for the key "impCompanyToken" in database "centreon", table "options".
You can't retrieve the value by yourself, you have to ask imp team which token is linked with your account.
Once they give it to you simply update the value in the DB.

**Comment by lpinsivy** [comment]
@larkoie please contact  imp[at]centreon.com

**Comment by larkoie** [comment]
@lpinsivy yes that's what I did, my previous post is the solution they gave me 👍
