### ISSUE TITLE
Centreon IMP with Proxy server

### ISSUE THREAD

**Issue by TaJeb** [centreon/centreon#6021]
BUG REPORT INFORMATION :

Centreon WEB 2.8.17
OS: Centos 6/7

Problem : Configuration > plugin pack > setup  is empty, and i can't sign on Centreon IMP on Administration > extension > subscription, error message is Cannot access to IMP portal

After investigation, i found that proxy could not establish connection to Centreon IMP servers (Page not found)

the same error is reported on /var/log/centreon/license-manager.log 
"[RestNotFoundException] https://api.imp.centreon.com/api/license-manager/instance : Page not found"

Any help please
Issue similar to #4896

**Comment by lpinsivy** [comment]
Can you define proxy settings in "Administration > Parameters > Centreon UI" menu ?

**Comment by TaJeb** [comment]
I have already defined proxy URL and proxy port in Administration > Parameters > Centreon UI, when I test proxy configuration I get this error : Could not establish connection to Centreon IMP servers (Page not found)

I get the same error if i leave it empty, we are using proxy and it's work for other machines

**Comment by lpinsivy** [comment]
What kind of proxy do you use?

**Comment by TaJeb** [comment]
Bluecoat proxy used to control web navigation and prevent access to some website

**Comment by lpinsivy** [comment]
can you test with curl the access from your Centreon web server:

`$ curl -x PROXY-SERVER:PORT -U USER:PASS https://api.imp.centreon.com/api`

**Comment by TaJeb** [comment]
As a result I get this message : curl: (7) couldn't connect to host

And below the result if i try "curl -I https://api.imp.centreon.com/api"

HTTP/1.1 200 Connection established
Date: Fri, 26 Jan 2018 11:15:02 GMT
Proxy-Connection: Keep-Alive
Via: 1.1 XXproxyXX

curl: (60) Peer certificate cannot be authenticated with known CA certificates
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by lpinsivy** [comment]
So you use a proxy with SSL.

Can you try with your certificates: 
`$ curl -k https://api.imp.centreon.com/api -v –key key.pem –cacert ca.pem –cert client.pem`

**Comment by TaJeb** [comment]
As a deduction from the result of your command : 
Connection OK to proxy
Establish HTTP proxy tunnel to api.imp.centreon.com:443 OK
Connection to host Host: api.imp.centreon.com Blocked

I tried also "curl -I -k https://api.imp.centreon.com/api/license-manager/instance" the result is : 
HTTP/1.1 302 Moved Temporarily
Date: Fri, 26 Jan 2018 12:49:33 GMT
Connection: close
Via: HTTPS/1.1 xxproxyxx
Location: http://IP:15871/cgi-bin/blockpage.cgi?ws-session=445511554

**Comment by lpinsivy** [comment]
Maybe you have an issue with your internal proxy. Can you autorise access to https://api.imp.centreon.com?

**Comment by TaJeb** [comment]
Ok, thanks I'll try your suggestion and keep you in touch

**Comment by julienmathis** [comment]
any update ?

**Comment by TaJeb** [comment]
Hello,

It's work if I don't use proxy server at all, I am trying to configure proxy server to let trafic pass through.

I'll keep you in touch.

Thanks

**Comment by ayoubelmimouni** [comment]
i have the same prob but with 404 error 
GET http://192.168.174.133/centreon/api/internal.php?object=centreon_pp_manager_pluginpack&action=ListInstalledOrdered&locale=en 404 (Object not found)
help please
