### ISSUE TITLE
[2.8.17] Graph template with base 1024 add a "B" to number

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#6025]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**:  centreon-engine-1.8.0

**Centreon Broker version**: centreon-broker-3.0.10

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Edit a check command, select "Storage" as graph template (or any template with 1024 as Base)
2. Look a graph who is using this check command
3. Put you mouse en the graph and look the numbers

**Describe the results you received:**
a B is added

**Describe the results you expected:**
just the number, exactly like the Base = 1000

![erreur template](https://user-images.githubusercontent.com/2464712/35570855-ac4df0fa-05d0-11e8-8b71-3385261db261.png)

**Comment by lpinsivy** [comment]
can't reproduce with PR #7676
