### ISSUE TITLE
Can't go to another page than "1" in Administration>Data when filtering results

### ISSUE THREAD

**Issue by larkoie** [centreon/centreon#6026]
Hi,
I'm reporting a very minor bug in the Centreon Web UI. 
When you are in **Administration** > **Data** and that you filter results by hosts or services it loads the corresponding Metrics list and sets you on page 1 of the list. When you click the next icon (true for every navigation icon :next, previous or directly a page number), it resets the filter so you get to the next page but without filter, resulting for example in page 2 of all the metrics instead of page 2 of the metrics from the services starting with "disk".
As a workaround 

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Go to Admin > Data
2.Filter by service starting with "disk" for example
3.Once on the first page of the filtered results, click next or directly another page number from the list

**Describe the results you received:**
You get to the 2nd page but the results are no more filtered, meaning it's the 2nd page of the whole metrics.

**Describe the results you expected:**
You get to the correct page number within the filtered results and can check the metrics you want for bulk modification (rebuild rrd database, delete graphs etc...)

**Additional information you think important (e.g. issue happens only occasionally):**
I have this behavior on both our Staging and Production servers and both on Chrome and Firefox so I assume it's a bug in the Web UI and not on my side.

Here it's filtered by service name = disk
![2018-01-30 15_17_20-1](https://user-images.githubusercontent.com/33937394/35572708-7bbceff4-05d5-11e8-89fd-75dc40be3a94.png)
Then I click on the next icon
![2018-01-30 15_17_36-1](https://user-images.githubusercontent.com/33937394/35572707-7ba0a16e-05d5-11e8-85bf-f6e43a16f2be.png)
I'm at page 2 but the filter is gone
![2018-01-30 15_17_46-1](https://user-images.githubusercontent.com/33937394/35572706-7b82f0ba-05d5-11e8-8c1e-3180f113b68e.png)

**Comment by lpinsivy** [comment]
Duplicate of #5109
