### ISSUE TITLE
Timeout issue when duplicating a service

### ISSUE THREAD

**Issue by realitix** [centreon/centreon#6028]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.5.4
**Centreon Engine version**: 2.5.4
**Centreon Broker version**: 2.5.4 
**OS**: CentOS

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- 1 VM for Centreon Engine
- 1 VM for MySQL Database
- 10 Centreon Web
- 40 Centreon Broker

** Describe the issue: **

Hello,

We are using Centreon 2.5.4 and we are experiencing timeout problems with some functionalities.
The problem may come from the big data volume we have.

In our MySQL tables, we have all theses data:

- hosts: 3500
- service: 68000
- acl: 371000

When we try to duplicate a service from an existent one to a new one, we experience often a timeout.
When we are connected as administrator, there is no timeout problem and all works as expected so we
suspect that the problem may be related to the ACL system.

We already tried several "OPTIMIZE" on tables but without success.

Is this problem knew and fixed in a newer version ?
I didn't find any issue related to this problem on the github bug tracker.

Have you got any clues about how to fix this problem ?
 - Could we add index on certain columns ?
 
Thanks for your reply,
Sincerely,
Jean-Sébastien Bevilacqua
LINAGORA

**Comment by lpinsivy** [comment]
Hi,

The Centreon Web 2.5.4 was released in January 2015 and is no more supported.

I suspect a timeout due to LDAP timeout connection.
Can you check the availability of all LDAP servers configured in "Administration > Parameters > LDAP".

Moreover, we improved the configuration of objects for users with ACL in latest version of Centreon.

**Comment by realitix** [comment]
Thanks @lpinsivy for your answer.
I will check for the LDAP connection.
