### ISSUE TITLE
Log rotate failed el7

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#6034]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.17
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 
3.0.1
**OS**: 
Centos 7 and RedHat 7

**Steps to reproduce the issue:**
1.[root@localhost ~]# logrotate -f /etc/logrotate.d/centreon
error: skipping "/var/log/centreon/centAcl.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/centcore.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/centreon-backup.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/centreon-partitioning.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/centreon-purge.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/dashboardBuilder.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/downtimeManager.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/eventReportBuilder.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/knowledgebase.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/login.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/centreon/nagiosPerfTrace.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.

**Describe the results you received:**
See above

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**
To solve the problem add "su root root" in the file /etc/logrotate.d/centreon

**Comment by lpinsivy** [comment]
@tseegers can you try:

```
 /var/log/centreon/*.log {
    su centreon centreon

    compress
    daily
    notifempty
    copytruncate
    missingok
    rotate 7
    size 20M

    create 644 centreon centreon
 }
```

**Comment by cgagnaire** [comment]
Works by adding `su centreon centreon` in /etc/logrotate.d/centreon and also `su centreon-broker centreon-broker` in /etc/logrotate.d/cbd.

But this directive will raise errors for CentOS 6 installation as it is unknown for the logrotate version installed : 
```
error: centreon:2 unknown option 'su' -- ignoring line
error: centreon:2 unexpected text
```

**Comment by lpinsivy** [comment]
So 1 version for el6 (actual) and another for el7 this one with sudoer for centreon-broker

**Comment by CPbN** [comment]
> `create 644 centreon centreon`

What about logs in `/var/log/centreon` which are not owned by `centreon` user but by `apache` user, such as `centAcl.log` and `downtimeManager.log` ?

Thank you :+1:

**Comment by CPbN** [comment]
@ganoze (or Centreon team), could you please re-open this issue ?
I'm still facing it with Centreon 18.10, for `/var/log/centreon-broker/` folder.
This folder has `775` permissions, thus logrotate skips it because it has "insecure permissions".
If this folder must keep these permissions, we then need `su root root` in `/etc/logrotate.d/cbd` too.
Thank you :+1:

**Comment by ganoze** [comment]
@CPbN I just opened issue centreon/centreon-broker#188 and PR centreon/centreon-broker#187 for the Centreon Broker flavour of this bug. Feel free to watch it.
