### ISSUE TITLE
Maj 2.7 -> 2.8 : Problème meta services (value)

### ISSUE THREAD

**Issue by mvisini** [centreon/centreon#6036]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.12

**OS**: CentOS 6.9

Bonjour, depuis la mise à jour d'une version 2.7.8 à 2.8.17 nous avons un phénomène étrange sur les meta services.

Désormais les valeurs retournées ne se nomment plus "Traffic_In", "load", etc.. mais "Value".
Par conséquent les graphes associés on changés et seule une ligne de valeur apparaît.

J'ai essayé de recréer un méta service de zéro, et le résultat est le même.

Est-ce un bug de votre côté ? 

Mathieu

**Comment by BenoitPoulet** [comment]
C'est un bug qui existe depuis au moins septembre 2017 mais qui n'a pas été corrigé depuis.

Voici mon bug report : #5629

**Comment by lpinsivy** [comment]
duplicate of #5629
