### ISSUE TITLE
Problème label graphe Traffic 2.8.17

### ISSUE THREAD

**Issue by mvisini** [centreon/centreon#6037]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.12

**OS**: CentOS 6.9

Bonjour, lorsque je vais dans le monitoring détail et que je cherche le résultat d'un check traffic mes valeurs sont bonnes.  Les performances data sont OK.
![image](https://user-images.githubusercontent.com/19703479/35691709-81a29720-0779-11e8-891e-f2f79d77f7f0.png)

En revanche dans mon graphe, la couleur est bonne mais les labels sont inversés..

![image](https://user-images.githubusercontent.com/19703479/35691777-b7b3e698-0779-11e8-82f8-744cb3b57b39.png)

Cela me le fait pour tous mes services traffic (~2000).
Je précise que les Templates n'ont pas été modifiés et que je n'ai aucune curve pour ces graphes.

Mathieu

**Comment by mvisini** [comment]
Bonjour, 

juste pour préciser que les labels sont revenus dans le bon état sans aucune action de notre part.
Pourtant les caches avaient bien été vidés.

**Comment by lpinsivy** [comment]
@mvisini cela est étrange. A part un problème de cache navigateur je ne vois pas.

Je clos le ticket.

**Comment by mvisini** [comment]
Assez étrangement le bug est revenu sans aucune explication. 
Les labels sont donc de nouveau inversés..

**Comment by lpinsivy** [comment]
Quand tu regardes le contenu de l'appel (option développeur de ton navigateur), tu as quoi comme résultat ? Tu peux copier le JSON ?

**Comment by mvisini** [comment]
Pourrais-tu me donner plus d'informations sur ce que tu attends comme JSON ? 

Voici une réponse json pour mon graph :+1: 

_**service_id | 104_1238
-- | --
data | […]
0 | {…}
data | […]
unit | Bits/s
color | #0DCC11
negative | false
stack | false
crit | null
warn | null
label | traffic_out
type | area
1 | {…}
data | […]
unit | Bits/s
color | #1203FB
negative | true
stack | true
crit | null
warn | null
label | traffic_in
type | area**_

Ici on peut voir que le traffic_in est en bleu alors que dans le graph il est bien bleu.
![image](https://user-images.githubusercontent.com/19703479/36904530-24f3969a-1e31-11e8-9bf4-2f23fd76dc00.png)

**Comment by lpinsivy** [comment]
> Ici on peut voir que le traffic_in est en bleu alors que dans le graph il est bien bleu.

Donc c'est bon ?

**Comment by mvisini** [comment]
Oups, erreur de ma part. Le traffic_in est bleu dans la légende, mais sur le graph cela correspond au vert.

**Comment by lpinsivy** [comment]
We can't reproduce the problem. I lose this issue
