### ISSUE TITLE
[2.8.17] No cumulated perfdata after update to 2.8 

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#6038]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.12

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical/VM

**Steps to reproduce the issue:**
1. Configure Service with Perfdata. RRDTool retention period is default 180 days.

**Describe the results you received:**
The rra[0] ring is purged correctly after the retention duration.
But also the cumulative rra[1] (12 dots are summed up to one datapoint) is purged after 180 days.
So I only have perfdata for 180 days and 5 minutes resolution.

**Describe the results you expected:**
In Centreon 2.7 the graphs also rendered the second rra[1] ring. So I have detailed resolution
for 180 days and cumulated values for ~6 years. Also with the update all data in rra[1] older than the retention period was deleted. If I want to keep the perfdata longer, I must keep rra[0] ring, which need much more disk space.

**Additional information you think important (e.g. issue happens only occasionally):**
"new scheme", rra[0] has values for 180 days, rra[1] too.
```
rrd_version = "0003"
step = 300
last_update = 1517578682
header_size = 792
ds[value].index = 0
ds[value].type = "GAUGE"
ds[value].minimal_heartbeat = 3000
ds[value].min = NaN
ds[value].max = NaN
ds[value].last_ds = "1.384000"
ds[value].value = 2.5394200000e+02
ds[value].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 51841
rra[0].cur_row = 33496
rra[0].pdp_per_row = 1
rra[0].xff = 5.0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 4321
rra[1].cur_row = 3531
rra[1].pdp_per_row = 12
rra[1].xff = 5.0000000000e-01
rra[1].cdp_prep[0].value = 9.6652600000e+00
rra[1].cdp_prep[0].unknown_datapoints = 0
```
"old scheme", rra[0] has values for 180 days, but rra[1] has cumulated values for 6 years.
```
rrd_version = "0003"
step = 300
last_update = 1517579220
ds[total].type = "GAUGE"
ds[total].minimal_heartbeat = 3000
ds[total].min = NaN
ds[total].max = NaN
ds[total].last_ds = "1.808980e+04"
ds[total].value = 2.1707760000e+06
ds[total].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 51840
rra[0].cur_row = 12845
rra[0].pdp_per_row = 1
rra[0].xff = 5.0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 51840
rra[1].cur_row = 41461
rra[1].pdp_per_row = 12
rra[1].xff = 5.0000000000e-01
rra[1].cdp_prep[0].value = 1.6280820000e+05
rra[1].cdp_prep[0].unknown_datapoints = 0
```

**Comment by lpinsivy** [comment]
Hi,

I suppose it was a previous issue to have a RRD designed for 6 years.

The value defined for "Retention duration for performance data in RRDTool databases" field in "Administration > Parameters > Performance Management > Options" menu is the maximum duration of the RRD files.

**Comment by itsul** [comment]
Hi,

I think till Centreon 2.7 every installation I know, had this behaviour.
The option in "Performance Management" only affected the data ring rra[0].
rra[1] was automatic created. With the same length than ring rra[0], but 12 points in rra[1] were cumulated to 1 point in rra[0]. So I have 180 days in rra[0] and 6 years in rra[1]. RRDTool has rendered both rings, so our Centreon installations had perfdata for half a year in detail and 6 years cumulated.

Since Centreon 2.8 ring rra[1] is also cut after180 days. So I have still two rings, but the cumulated one has not more data then the detailed one.

So when the retention in "Performance Managemend" is relevant, you should delete the rra[1] ring?
It will be also created in new centreon installations.

But I think, it was not a bad feature. For older data, the values do not need to be such detailed and with a cumulated ring, the rrd files are smaller, than with just one detailed ring over the same time.
You know what I mean?
