### ISSUE TITLE
Purge of downtimes table

### ISSUE THREAD

**Issue by clairedy** [centreon/centreon#6040]
Hi,
I would like to purge the downtimes table. Do you know if this table can be purged simply by deleting records or if there is a link to other tables? I have seen an "in_dowtime" field in the servicestateevents and hoststateevents tables, but I do not know how it is populated.

Configuration :
Centreon 2.5.4
MariaDB 5.5
CentOS 6.6

Thanks,

**Comment by lpinsivy** [comment]
Hi

You can delete items for this table by datetime without impact for old events.
