### ISSUE TITLE
2.8.17 : Service description disappeared in graph

### ISSUE THREAD

**Issue by mvisini** [centreon/centreon#6044]
Hello, 

since the maj (2.7 -> 2.8.17) the service description disappeared from the graph.

Ex in 2.7.X:
![image](https://user-images.githubusercontent.com/19703479/35855687-34f3d038-0b34-11e8-9f3f-cc9839891f8d.png)

And in 2.8.17:
![image](https://user-images.githubusercontent.com/19703479/35855775-62535346-0b34-11e8-8e0d-56bdcd2fb2c5.png)

Any addon on php code for that ? 

Thanks

**Comment by lpinsivy** [comment]
Hi,

Did you have javascript errors when you load the chart ?

**Comment by mvisini** [comment]
No js error. 
In the centreon demo UI (demo.centreon.com), there's no service description in the performance page.
So, is it a will ?

**Comment by julienmathis** [comment]
The title is written outside of the graph, on the top of the graph. I think you have a specific need, I think for example that you want to export graph or make copy. 

We cannot add the title in the graph and outside the graph - it's redondant
