### ISSUE TITLE
Bulk change: activate notifications on 14000 services

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#6045]
Hi, 

I must enable notifications on 14000 services and it is just impossible to do it manually.
Is there any way to do this in bulk or at leas 1000 services at a time ?

Thank you

**Comment by Adeiko** [comment]
You can use the Clapi notifications_enabled. 

https://documentation.centreon.com/docs/centreon-clapi/en/latest/objects/services.html?highlight=notifications

**Comment by lpinsivy** [comment]
Hi,

You should use template of service. This allows to only change parameters on one object (template).
