### ISSUE TITLE
Downgrade Centreon

### ISSUE THREAD

**Issue by VuNgocTan** [centreon/centreon#6050]
Hello guys. Can I downgrade Centreon from 2.8.17 to 2.7 ?

**Comment by VuNgocTan** [comment]
by the way, can I install centreon-vmware on centreon 2.8.17 ?

**Comment by lpinsivy** [comment]
Hi,

No there is no process to downgrade Centreon.

And yes you can install centreon-vmware on Centreon web 2.7.x and 2.8.x using YUM

**Comment by VuNgocTan** [comment]
thank you for your reply, I was waiting for this. Please help me with this issue,when I use this: "yum install centreon-plugin-Virtualization-VMWare-client". It says that:

> No package centreon-plugin-Virtualization-VMWare-client available.
Error: Nothing to do

What should I do ? :(

**Comment by lpinsivy** [comment]
Name of packages changes:

centreon-plugin-Virtualization-Vmware2-Connector-Plugin.noarch: for the client
centreon-plugin-Virtualization-VMWare-daemon.noarch: for the daemon

You need both

**Comment by VuNgocTan** [comment]
thanks, but now I got new issue with the plugin

> UNKNOWN: Container connection problem |

zzz it keeps coming, already try with --serverity=debug

**Comment by lpinsivy** [comment]
Some errors in /var/log/centreon/centreon_vmware.log ?

**Comment by VuNgocTan** [comment]
> 2018-02-20 11:20:17 - Cannot bind ipc '/tmp/centreon_vmware/routing.ipc': No such file or directory
2018-02-20 11:20:17 - Maybe dirctory not exist. We try to create it!!!
2018-02-20 11:20:17 - 'default' Login to VirtualCenter server failed: Server version unavailable at 'https://vcenter:443/sdk/vimService.wsdl' at /usr/local/share/perl5/VMware/VICommon.pm line 545.

2018-02-20 11:20:27 - 'default' Login to VirtualCenter server failed: Server version unavailable at 'https://vcenter:443/sdk/vimService.wsdl' at /usr/local/share/perl5/VMware/VICommon.pm line 545.

2018-02-20 11:20:38 - 'default' Login to VirtualCenter server failed: Server version unavailable at 'https://vcenter:443/sdk/vimService.wsdl' at /usr/local/share/perl5/VMware/VICommon.pm line 545.


here is the log, what is the "server version unavailable" ?

**Comment by VuNgocTan** [comment]
>  eval { $result = $xml_parser->parse_string($response->content) };
    544       if ($@) {
    545          die "Server version unavailable at '$url'";

this is the code from line 543 -> 545 in the file VICommon.pm mention above

**Comment by lpinsivy** [comment]
Hi,

` Cannot bind ipc '/tmp/centreon_vmware/routing.ipc'`

Did you start process with root user?

What is your version or perl-VMware-vSphere and your vCenter?

**Comment by VuNgocTan** [comment]
Hi Ipinsivy, I did start it with the root user, and the version of the perl-VMware-vSphere and vCenter is the latest version.
