### ISSUE TITLE
Host duplication fails

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#606]
---

Author Name: **Anonyme** (Anonyme)
Original Redmine Issue: 3677, https://forge.centreon.com/issues/3677
Original Date: 2012-09-17

---

Hi,

when I try to duplicate the same host twice, the first attempt creates a copy as expected (like "toto_1"), the second attempt fails without error... I guess it tries to re-create toto_1 whereas it already exists :p

Centreon version : 2.3.9

**Comment by lpinsivy** [comment]
duplicate of #3606
