### ISSUE TITLE
"Disabled hosts" filter does not stay if change of page

### ISSUE THREAD

**Issue by benrobert** [centreon/centreon#6060]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17-10

**Centreon Engine version**: 1.8.1-1

**Centreon Broker version**: 3.0.12-1

**OS**: tested both on CentOS 7.4 and CentOS 6.5

**Steps to reproduce the issue:**
1. Go to Configuration  >  Services  >  Services by host
2. Check the filter "Disabled hosts" and click on search
3. Make sure you have several pages of result. Then change of page

**Describe the results you received:**
The "Disabled hosts" filter  is unchecked and you access to the list of non disabled hosts.

**Describe the results you expected:**
The "Disabled hosts" filter  should stay checked and you should access to the selected page

**Additional information you think important:**
If you select again the "Disabled hosts" filter and click on search, you access to the wanted page. You have to do this for each page changement.

**Comment by benrobert** [comment]
Lots of similarities with this issue but on a different filter : https://github.com/centreon/centreon/issues/6026

**Comment by lpinsivy** [comment]
Duplicate of #5109
