### ISSUE TITLE
Cancel flexible RTDOWNTIME is not working

### ISSUE THREAD

**Issue by durnote** [centreon/centreon#6062]
**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.8.1

**OS**:  CentOS 7.4

**Steps to reproduce the issue:**
1. I upgraded to 2.8.17  so I could use new feature to CANCEL realtime downtimes
2. Adding new realtime downtime works perfectly fine
3. Cancelining realtime downtime fails

**Steps to reproduce issue**
--create downtime
centreon -u user -p pass -o RTDOWNTIME -a ADD -v "HOST;MyHost;2018/02/12 10:00;2018/02/14 12:00;1;;my comments;1;"

--show id of downtime
centreon -u user -p pass -o RTDOWNTIME -a SHOW -v "HOST;MyHost;"

this will output:
211;MyHost...    (what we need here is 211 which is downtime id)

--finally, try canceling this downtime
centreon -u user -p pass -o RTDOWNTIME -a CANCEL -v "211"

When executed it completes successfully (no error) and if you run -a SHOW again it will not be able to find that downtime again. However, if you go to Centreon Web GUI you could still see downtime is present and activated on host.  Refreshing page / logout / login doesn't help as it is still there.

**Comment by lpinsivy** [comment]
Hi,

Can you check if for each action (ADD/CANCEL) you have entry in  file on poller:

```
[1519047385] [5801] EXTERNAL COMMAND: SCHEDULE_HOST_DOWNTIME;localhost;1519047000;1519054200;1;0;;superadmin;'my comments'
[1519047385] [5801] EXTERNAL COMMAND: SCHEDULE_HOST_SVC_DOWNTIME;localhost;1519047000;1519054200;1;0;;superadmin;'my comments'
[1519047385] [5801] HOST DOWNTIME ALERT: localhost;STARTED; Host has entered a period of scheduled downtime
.....
[1519047443] [5801] EXTERNAL COMMAND: DEL_HOST_DOWNTIME;13301
[1519047443] [5801] HOST DOWNTIME ALERT: localhost;CANCELLED; Scheduled downtime for host has been cancelled.
```

Regards,

**Comment by Poil2Q** [comment]
https://github.com/centreon/centreon/blob/2.8.x/www/class/centreon-clapi/centreonRtDowntime.class.php#L752 : 

**_Why we can't delete flexible downtime ?_**

 `    public function getCurrentDowntime($id)
    {
        $query = "SELECT * FROM downtimes WHERE ISNULL(actual_end_time) " .
            " AND end_time > " . time() . " AND internal_id = " . $id;
        return $this->getResult($query, array(), 'fetch');
    }`

So we can delete fixed downtime but not a flexible ?? it's fabulous !!!

We can reproduce this bug on the interface.....

**Comment by cgagnaire** [comment]
Fixed here https://github.com/centreon/centreon/pull/8211
