### ISSUE TITLE
GRAPH - The scale and curve is different according to the unit of time

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#6063]
**Centreon Web version**: 
2.8.17
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 
3.0.12
**OS**: 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**

Monitoring  >  Performances  >  Graphs

1.Display graph with period => 12H
![scale_02](https://user-images.githubusercontent.com/16045498/36211751-6e97c424-11a2-11e8-9c7a-34797ec3c098.jpg)

2.Display graph with period => 24H

![scale_01](https://user-images.githubusercontent.com/16045498/36211758-751e01dc-11a2-11e8-8f9d-d137770d1639.jpg)

**Describe the results you received:**

Different value for the scale and tha value return for CPU is wrong and different between these two frame of time
**Describe the results you expected:**

A same value for the scale and curve

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
@Jordan91 RRD only display the trend and not the real values
