### ISSUE TITLE
[API REST] - user with readonly ACL's on configuration can disable and delete hosts

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6064]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.17

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.12

**OS**: centos 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. create a user with readonly ACL's on configuration like this:
![cenreon_api_user](https://user-images.githubusercontent.com/8720203/36285044-6545234a-12aa-11e8-934e-99d2dbc19798.png)

2. use API REST and try to disable a host like this:
{
  "action": "disable",
  "object": "host",
  "values": "central"
}

**Describe the results you received:**
host "central" is disabled and can be also deleted.
services are impacted too.

**Describe the results you expected:**
action should be unauthorised due to ACL's.

**Additional information you think important (e.g. issue happens only occasionally):**
disable action is not logged.

**Comment by Dodofox** [comment]
This bug is still there. Please give us information about the fix. 

thanks.

**Comment by lpinsivy** [comment]
Hi we can't correct it easily on API v1 because it was not desinged to use ACL.

We will start to develop v2

**Comment by cmeschin** [comment]
Hi @lpinsivy ,
I haven't not yet tested API v2.
Is ACL's rights are implemanted in V2 or not yet?

If yes, you can close this issue.
Regards

**Comment by lpinsivy** [comment]
Hi @cmeschin Yes ACL are implemented in API v2.

Regards,
