### ISSUE TITLE
REST API - Acknowledgments add / remove / list

### ISSUE THREAD

**Issue by gdelafond** [centreon/centreon#6068]
Hello,

It would be nice to be able to set and delete acknowledgement through the API for both host and services.

List hosts and services that have been acknowledged would be nice too.

Thank you.

**Comment by kadrika** [comment]
+1

**Comment by fredericx** [comment]
+10

**Comment by C-Bam** [comment]
+1 too
Here is a use case with teams:

![image](https://user-images.githubusercontent.com/41115346/48407452-e2e2aa80-e747-11e8-9210-0ce213e2e35d.png)

The supervisor receive a notification on MS Teams, and can click "Acquitter" (Aknowledge).

I'd like to be able to send the aknowledgement properly then

**Comment by lordtaki** [comment]
This is something we need too.
+1

**Comment by lsquillace** [comment]
+1

**Comment by lpinsivy** [comment]
PR #7187

**Comment by adr-mo** [comment]
Hi all,

This improvement has been done in the [latest](https://github.com/centreon/centreon/releases/tag/18.10.4) release of Centreon.

Thanks for your feedback :100: 

Closing the ticket.
