### ISSUE TITLE
API REST can't get list of hosts by hostgroup id

### ISSUE THREAD

**Issue by anismaj** [centreon/centreon#6070]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  Centreon 2.8.17

**Centreon Engine version**: NR

**Centreon Broker version**:  NR

**OS**:  Centos7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Run API command to list host by hostgroup  id: https://xx.xx.xx/centreon/api/index.php?action=list&object=centreon_realtime_hosts&hostgroup=4

**Describe the results you received:**

500 internal server error

**Describe the results you expected:**

List of hosts by hostgroup

**Additional information you think important (e.g. issue happens only occasionally):**
I have a problem to show a list of hosts based on hostgroup id using the Centreon API. 
I can list all host using API but when i add parameters hostgroup i receive the error 500 internal server error.

Can you help me please.

Thanks

**Comment by lpinsivy** [comment]
You right:

```
PHP Warning:  Invalid argument supplied for foreach() in /usr/share/centreon/www/api/class/centreon_realtime_hosts.class.php on line 371
PHP Notice:  Undefined index: fields in /usr/share/centreon/www/api/class/centreon_realtime_hosts.class.php on line 388
PHP Fatal error:  Call to undefined method DB_Error::fetchRow() in /usr/share/centreon/www/api/class/centreon_realtime_hosts.class.php on line 435
```

**Comment by Moujimouja** [comment]
Hi,

Problem can't be reproduce on 19.10.x nor 20.04 version.

I also recommend you to use the new API that comes with Centreon 19.10 and get continuoulsy improved in Centreon 20.04 and future versions. 

You can of course still use the Rest v1 version. [Some info here](https://docs.centreon.com/current/en/api/introduction.html).

Some doc can be found [here](https://docs.centreon.com/api/centreon-web/#tag/Monitoring-Server/paths/~1configuration~1monitoring-servers/get)

I close the issue.
