### ISSUE TITLE
View contact notification

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#6073]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.17
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 
3.0.11
**OS**: 
Centreon 3.3

**Steps to reproduce the issue:**
1. Create a host linked to a user for notification
2. Create a service linked to previous host with "Inherit only contacts/contacts group from host" checked
2. Go to Configuration  >  Users  >  Contacts / Users > View contact notification

**Describe the results you received:**
The service is not listed

**Describe the results you expected:**
The service should be present in the popup

**Comment by chgautier** [comment]
Fixed with PR #6340 on branch 6073-fix-view-contact-notifications. Once we link the created service with the "Inherit only contacts/contacts group from host" option checked to the previously created host, the service is present in the pop-up after selecting the user it is linked to.
