### ISSUE TITLE
[DOC] Remote Poller Configuration docs 2.8.x outdated

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#6075]
I needed to add a new poller due overload issues, then I followed this guide:
https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/poller/02configuration.html

The guide screens are outdated to version 2.8.17 (There is no Engine field at Monitoring Engine Information Session)

At the engine edition step there wont be a central-module.xml to replace with poller1-module.xml

The following step: 

> Go into the menu: Configuration ==> Pollers ==> Centreon-Broker ==> Configuration

should be replaced by: 

> Go into the menu: Configuration ==> Pollers ==> Broker configuration

It describes how to configure the engine during the first few steps, shortly afterwards, it says to use the broker wizard **which generates another engine entry**. I made the ssh key exchange.

I went through all steps but my poller is still not running.

![image](https://user-images.githubusercontent.com/25208457/36445002-9f7edc0e-165b-11e8-950b-8650b46cd146.png)

I couldnt find anything related to this message from poller-module.log:
`[1519140199] config:  state applier: instance information are not set: please fill broker_id and broker_name
`
I dont know what is this  ![CDATA[10.30.3.19]] in my poller-module.xml

I wonder what is missing, this is a fresh install of the remote poller

**Comment by kozfelipe** [comment]
thanks a lot

**Comment by adr-mo** [comment]
**Fixed and merged.**

Closing the issue.

Regards,
