### ISSUE TITLE
Enregistrement des données de performance dans la table 'data_bin'

### ISSUE THREAD

**Issue by Akatizi** [centreon/centreon#6077]
Bonjour,

Ce n'est pas un problème mais juste une question sur différentes options, je ne comprend pas a quoi ça sert.

Dans configuration => Collecteur => Configuration de Centreon Broker, dans central-broker-master et l'Output 3 - Perfdata Generator (Centreon Storage), il y a l'option "Enregistrement des données de performance dans la table 'data_bin'", elle sert a quoi ?

De même pour central-rrd-master, Output 1 - RRD file generator, l'option "Enregistrement des données de performance dans la table 'data_bin'", elle sert à quoi par rapport à la première question ?

De ce fait est-il possible de ne pas enregistrer les données de performance dans la BDD mais seulement utilisé les fichiers RRD ?

Merci d'avance

**Comment by lpinsivy** [comment]
Hi,

The option "Store performance data in data_bin" allow or not the Centreon Broker to store performance data into centreon_storage.data_bin table.
If you disable this option, you will not be able to rebuild a RRD database in case of a crash.

On the latest version of Centreon Web, the option "Store performance data in data_bin" is no more available for the output "RRD file generator". Only the options "Write metrics" and "Write status" allow or not to insert performance data and status data into RRD file.

Regards,
