### ISSUE TITLE
Error: Host/Service check command execution failed: pipe creation failed: Too many open files

### ISSUE THREAD

**Issue by adrianoguilhermetti** [centreon/centreon#6079]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.17-10

**Centreon Engine version**: centreon-engine-1.8.1-1

**Centreon Broker version**: centreon-broker-3.0.12

**OS**: CentOS Linux release 7.4.1708 (Core)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Steps to reproduce the issue:**
Hello,
I was checking the CentreonEngine log file (centengine.log) and found the errors below.
They occur quite frequently:
```
tail -f /var/log/centreon-engine/centengine.log
...
[1519252467] [4794] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Host check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Host check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Host check command execution failed: pipe creation failed: Too many open files
[1519252467] [4794] Error: Host check command execution failed: pipe creation failed: Too many open files
...
```

**Additional information you think important (e.g. issue happens only occasionally):**
I have already configured Linux kernel parameters:

```
[root@srvl-33 ~]# cat /etc/sysctl.conf
fs.file-max = 10485760
fs.nr_open = 10485760
[root@srvl-33 ~]#
```

I already configured the PAM:

```
[root@srvl-33 ~]# cat /etc/pam.d/login
#%PAM-1.0
auth [user_unknown=ignore success=ok ignore=ignore default=bad] pam_securetty.so
auth       substack     system-auth
auth       include      postlogin
account    required     pam_nologin.so
account    include      system-auth
password   include      system-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    optional     pam_console.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      system-auth
session    include      postlogin
-session   optional     pam_ck_connector.so
session    required     /lib/security/pam_limits.so
session    required     pam_limits.so
[root@srvl-33 ~]#
```

I already configured the limits.conf

```
[root@srvl-33 ~]# cat /etc/security/limits.conf
# /etc/security/limits.conf

root soft nproc 524288
root hard nproc 524288
root soft nofile 1046576
root hard nofile 1046576
root soft stack 10240

mysql soft nproc 524288
mysql hard nproc 524288
mysql soft nofile 1046576
mysql hard nofile 1046576
mysql soft stack 10240

oracle soft nproc 524288
oracle hard nproc 524288
oracle soft nofile 1046576
oracle hard nofile 1046576
oracle soft stack 10240

apache soft nproc 524288
apache hard nproc 524288
apache soft nofile 1046576
apache hard nofile 1046576
apache soft stack 10240

centreon soft nproc 524288
centreon hard nproc 524288
centreon soft nofile 1046576
centreon hard nofile 1046576
centreon soft stack 10240

nagios soft nproc 524288
nagios hard nproc 524288
nagios soft nofile 1046576
nagios hard nofile 1046576
nagios soft stack 10240

centreon-engine soft nproc 524288
centreon-engine hard nproc 524288
centreon-engine soft nofile 1046576
centreon-engine hard nofile 1046576
centreon-engine soft stack 10240

centreon-broker soft nproc 524288
centreon-broker hard nproc 524288
centreon-broker soft nofile 1046576
centreon-broker hard nofile 1046576
centreon-broker soft stack 10240
You have mail in /var/spool/mail/root
[root@srvl-33 ~]#
```

But even using with these settings, the error messages in the "centengine.log" log file persist.

Does anyone know what it can be?

Thank you

**Comment by lpinsivy** [comment]
Hi,

SELinux is enable on your server?

Regards,

**Comment by adrianoguilhermetti** [comment]
HI,

No, SELinux is disabled:

[root@srvl-33 ~]# cat /etc/selinux/config

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=disabled
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted

[root@srvl-33 ~]#

Thank you.

**Comment by bouda1** [comment]
Hi,

Could you give the result of the following commands when you have the problem:
`lsof | wc -l'
`lsof -c cbd | wc -l`

Thank you.

**Comment by adrianoguilhermetti** [comment]
Hi bouda1,

Your command did not run, I think it has some syntax error:

[root@srvl-33 ~]#
[root@srvl-33 ~]# lsof | wc -l'lsof -c cbd | wc -l`
>
> ^C
[root@srvl-33 ~]#


I performed 2 other commands below. If not what you need, could you please give me the command with the correct syntax?

[root@srvl-33 ~]# lsof -c cbd | wc -l
239
[root@srvl-33 ~]# lsof | wc -l
347349
[root@srvl-33 ~]#

Thank You.
Adriano

**Comment by pmpintogil** [comment]
I have the same problem, in my POLL01 logs:


2018/02/28 | 10:33:25 | POLL01 | Error: Host check command execution failed: pipe creation failed: Demasiados ficheros abiertos
2018/02/28 | 10:33:25 | POLL01 | Error: Host check command execution failed: pipe creation failed: Demasiados ficheros abiertos
2018/02/28 | 10:33:25 | POLL01 | Error: Host check command execution failed: pipe creation failed: Demasiados ficheros abiertos
2018/02/28 | 10:33:25 | POLL01 | Error: Host check command execution failed: pipe creation failed: Demasiados ficheros abiertos
2018/02/28 | 10:33:25 | POLL01 | Error: Host check command execution failed: pipe creation failed: Demasiados ficheros abiertos

I try to found a solution but nothing, the platform works very good, but with that error.

**Comment by adrianoguilhermetti** [comment]
My checks fail because of this error.

**Comment by lpinsivy** [comment]
Sorry problem of synthax with github.

Command was:
```
lsof | wc -l
lsof -c cbd | wc -l
```

So you have only 239 open files for Centreon Broker and 347349 opended in total.

Which process opened the other files?
Did you installed others application in your server than Centreon components?

**Comment by adrianoguilhermetti** [comment]
Hi lpinsivy,

   No problem. I ran the commands again, below the result:

[root@srvl-33 ~]#
[root@srvl-33 ~]# lsof | wc -l
254706
[root@srvl-33 ~]# lsof -c cbd | wc -l
240
[root@srvl-33 ~]#

Answering your questions:
We only have Centreon installed on this server, it is exclusive to Centreon. We have nothing else running on it

An observation:
The execution of these commands (lsof) were at a time when the Centreon server was "quiet", with a low number of checks running.
As soon as this problem happens again "Error: Host / Service check command execution failed: pipe creation failed: Too many open files" I will re-execute the result of the commands.

Thank You.

**Comment by adrianoguilhermetti** [comment]
[root@srvl-33 centreon-engine]#
[root@srvl-33 centreon-engine]# lsof | wc -l; lsof -c cbd | wc -l
110231
238
[root@srvl-33 centreon-engine]# tail -f /var/log/centreon-engine/centengine.log | grep Too

[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[1519995068] [638] Error: Service check command execution failed: pipe creation failed: Too many open files
[root@srvl-33 centreon-engine]#  lsof | wc -l;lsof -c cbd | wc -l
113581
238
You have new mail in /var/spool/mail/root
[root@srvl-33 centreon-engine]# vi /etc/sysctl.conf

**Comment by adrianoguilhermetti** [comment]
Hi lpinsivy,
Is there no parameter in Centreon that determines the number of files opened by it?

Thank You.
Adriano

**Comment by adrianoguilhermetti** [comment]
Hello

Anybody know?

Any return?

**Comment by adrianoguilhermetti** [comment]
We have some BUG at Centeron!

I say this because the "number of files opened" is very, very far from the limit configured in the Operating System, this has already been reported and sent for analysis of voices in the posts made previously in this ISSUE.

We have already called for support of Linux (RedHat) for analysis, and we have nothing / no problem and / or BUG with the Operating System.

We hired a consulting firm specializing in Linux that verified this "open file limit" problem, this consultancy also confirmed that the "file open limit" is way above the "open files quantity", either by the Centeron (in general ) or any other type of process. I remember again that we only have Centreon installed on this server, it is dedicated exclusively to Centreon, plus no other software and / or application.

I know we do not have support from Centreon, but this problem is extremely critical and it's been a long time. The company's directors are already analyzing other monitoring tools in the market, due to the non-solution of this problem, as this is impacting and much our operation / monitoring.

I am at your disposal to send again data and / or evidence of the "configuration made of limit of files that can be opened" and the "amount of files opened".

Thank you!

**Comment by lpinsivy** [comment]
Hi @adrianoguilhermetti,

What is the value for "Maximum Concurrent Service Checks" field (in "Configuration  >  Pollers  >  Engine configuration" menu on "Tuning" tab)?

What is the value of `lsof -c cent | wc -l` ?

**Comment by adrianoguilhermetti** [comment]
Hi lpinsivy,

We decreased value from the "Concurrent Maximum Service Check" to 990 (before it was 1500) in order to lessen the occurrence of these error. This reduced errors by approximately 40%.

The following is the result of the requested command:

[root @ srvl-33 centreon-engine] #
[root @ srvl-33 centreon-engine] # lsof -c cent | wc-1
472
[root @ srvl-33 centreon-engine] #

Thank you!
Adriano

**Comment by adrianoguilhermetti** [comment]
[info.txt](https://github.com/centreon/centreon/files/2124951/info.txt)

Hello Sims24,

Attached the file "info.txt" with the requested output

PS: the output of the "ps aux" command was truncated because there was confidential information, such as password appearing.

Thank You.

Adriano

**Comment by adrianoguilhermetti** [comment]
Another ISSUE closed without a solution.

**Comment by vonhovic** [comment]
Hello,

any resolusion of this problem? I have same symptoms as [adrianoguilhermetti]. 
Also current open files not matching actual max open files limit and still reach error above.

**Comment by adrianoguilhermetti** [comment]
> Hello,
> 
> any resolusion of this problem? I have same symptoms as [adrianoguilhermetti]. Also current open files not matching actual max open files limit and still reach error above.

Hi [vonhovic]
Unfortunately no, Centreon didn't give us a solution or was able to pinpoint the problem.
Due to several issues we faced with Centreon, we abandoned it as a monitoring tool, we had to replace it.
