### ISSUE TITLE
Security issue : Reflected Cross-Site Scripting using "any" Search field

### ISSUE THREAD

**Issue by larkoie** [centreon/centreon#6082]
Hi guys,

We had an internal vulnerability testing on our centreon instance and it came out with this  Cross-Site scripting issue using the Recurrent downtimes search. Please find the security team recommendations at the end.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.0.3

**OS**: CentOS7

**Steps to reproduce the issue:**
1.Log into the application with any valid user.
2. Click on the “Monitoring” tab.
3. Click on the “Downtimes” option.
4. Click on the “Recurrent downtimes” option.
5. In the “Name” input field, type the following script: 
1"/><script>window.open("http://myredirectionpage.com/page.html")</script>.
6. Click on the “Search” button.

**Describe the results you received:**
The script will execute a fake login page.

**Describe the results you expected:**
Nothing happens.

**Additional information you think important (e.g. issue happens only occasionally):**
**Important Note:**
o This vulnerability was flagged with a "Low" risk since the execution is through the POST method implies that the user is lured to enter a malicious input at certain fields lowering the probability of a successful attack.
o This issue is present throughout the application. Links listed below are just additional examples of other occurrences. Consider an application-wide fixing strategy.

**Recommendation(s):**
1. If possible, do not allow this information to be reflected or sent back to the user.
2. If this is not possible, then HTML encode all the data so that tags and scripts are interpreted as plain text by the browser.
3. Implement strong and positive validation to ensure that user input only contains the expected characters, data type, format, range, and size.

**Comment by attritionorg** [comment]
If you have to authenticate and type/paste the payload into a field, that is not reflected.

**Comment by avihlbi** [comment]
Hi, it the issue above affects other versions besides 2.8.17? and it's not clear if it was fixed in 2.8.20 or not.
Thank you

**Comment by lpinsivy** [comment]
Has been fixed by following PR #7732 with sanitize: https://github.com/centreon/centreon/blob/master/www/include/monitoring/recurrentDowntime/listDowntime.php#L47
