### ISSUE TITLE
Security issue : Weak session management (session fixation attack)

### ISSUE THREAD

**Issue by larkoie** [centreon/centreon#6083]
Hi guys,

We had an internal vulnerability testing on our centreon instance and it came out with this weak session management issue that could lead to a session fixation attack. Please find the security team recommendations at the end.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.0.3

**OS**: CentOS 7

**Steps to reproduce the issue:**
1.Access to the application’s login page.
2. In the browser’s address bar type the following script: javascript:alert(document.cookie.substring(document.cookie.indexOf ("PHPSESSID"))); and press the Enter key.
3. Take note of the session cookie value before accessing the application.
4. Log in to the application as any valid user role.
5. In the browser’s address bar type the following script: javascript:alert(document.cookie.substring(document.cookie.indexOf ("PHPSESSID"))); and press the Enter key.

**Describe the results you received:**
the current session does not change after the login. An attacker can perform a session fixation attack due this poor session management

**Describe the results you expected:**
The current session should change once logged in.

**Additional information you think important (e.g. issue happens only occasionally):**
Recommendation(s):

1. Implement session tracking to ensure only authenticated users can access to data.
2. Use role-based security to check user permissions before any action is taken, including displaying, inserting, updating, and deleting data.
3. Another option is to use digital certificates to ensure messages are from a trusted connection and have not been modified while in transit.

**Comment by avihlbi** [comment]
Hi, it the issue above was fixed? and does it affect other versions besides 2.8.17? 
Thank you

**Comment by lpinsivy** [comment]
First, using HTTPS as explained in our documentation, you can see cookie with our browser.

Secondly, PHPSESSID change:

<img width="951" alt="phpsessid_1" src="https://user-images.githubusercontent.com/3351916/100752559-09381900-33e9-11eb-81dc-360aec26d26f.png">

<img width="951" alt="phpsessid_2" src="https://user-images.githubusercontent.com/3351916/100752581-0f2dfa00-33e9-11eb-97ed-3e2c1ea5ac86.png">
