### ISSUE TITLE
after upgrade 2.8.17 to 2.8.18 

### ISSUE THREAD

**Issue by vurmil** [centreon/centreon#6085]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: CES

**Additional environment details (AWS, VirtualBox, physical, etc.):** Vmware

**Steps to reproduce the issue:**
After upgrade centreon from 2.8.17 to 2.8.18
**top**
mysql %CPU **313.9**
Load Average: 15.67, 16.09, 15.94 (earlier it did not exceed 1.50)

MariaDB [(none)]> show processlist;
....
| 19416657 | centreon | localhost | centreon_storage | Query   | 8660 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416757 | centreon | localhost | centreon_storage | Query   | 8510 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416840 | centreon | localhost | centreon_storage | Query   | 8367 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416852 | centreon | localhost | centreon_storage | Query   | 8358 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416886 | centreon | localhost | centreon_storage | Query   | 8342 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416893 | centreon | localhost | centreon_storage | Query   | 8340 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416903 | centreon | localhost | centreon_storage | Query   | 8335 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416929 | centreon | localhost | centreon_storage | Query   | 8318 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416954 | centreon | localhost | centreon_storage | Query   | 8295 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
| 19416967 | centreon | localhost | centreon_storage | Query   | 8293 | Sending data | SELECT SUM(CASE WHEN s.state = 0 THEN 1 ELSE 0 END) AS OK_TOTAL, SUM(CASE WHEN s.state = 1 THEN 1 EL |    0.000 |
.....

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Can you check if all steps of this pull request are available on your server: https://github.com/centreon/centreon/pull/5992/files?

**Comment by vurmil** [comment]
I'm check, all files the same

**Comment by lpinsivy** [comment]
Do you use admin or account with ACL?
How many hosts/services/hostgroups/servicegroups?
How many users connected?

Regards,

**Comment by vurmil** [comment]
I'm use admin account
Host ~ 3500, Services ~60000, HostGroups ~100, ServiceGroup ~40
Today ~5users (with ACL)

**Comment by kduret** [comment]
Hi,

Can you check if you have index2 in centreon_acl table of database centreon_storage ? Using following query : 
SHOW CREATE TABLE centreon_acl;

if there is not index2 in centreon_acl, execute the following query : 
ALTER TABLE centreon_acl ADD INDEX `index2` (`host_id`,`service_id`,`group_id`);

Does it solve your problem ?

**Comment by vurmil** [comment]
CREATE TABLE `centreon_acl` (
 `host_id` int(11) DEFAULT NULL,
 `service_id` int(11) DEFAULT NULL,
 `group_id` int(11) DEFAULT NULL,
 KEY `group_id_by_name` (`group_id`),
 KEY `group_id_for_host` (`group_id`),
 KEY `index1` (`group_id`,`host_id`,`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

I create index2 and now is much better :)

Thanks!!!

**Comment by lpinsivy** [comment]
Ok we made a mistake, see PR https://github.com/centreon/centreon/pull/6093/files

Can you execute this SQL request on your 'centreon_storage' database ?

`ALTER TABLE centreon_acl ADD INDEX `index2` (`host_id`,`service_id`,`group_id`)`
