### ISSUE TITLE
Reporting Dashboard Issue

### ISSUE THREAD

**Issue by DeadPixhell** [centreon/centreon#6094]
---------------------------------------------------
Issue REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Centreon Web 2.8.10

**Centreon Engine version**: Centreon Engine 1.7.2

**Centreon Broker version**: Centreon Broker 3.0.8

**OS**: CentOs 6.4 64Bits

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We have 1 serveur for hypervisor
We have 2 pollers
We have 1 server for database with maria db
MariaDB version : mysql  Ver 15.1 Distrib 10.1.29-MariaDB
All of them are on Wmware

**Steps to reproduce the issue:**
- We have some host and services that are in 100% undetermined state in Reporting->dashboard
- Check for this host or service are good for the periode
1.  /usr/share/centreon/cron/eventReportBuilder -r -s 2018-02-20 -e 2018-02-27
2.  /usr/share/centreon/cron/dashboardBuilder -r -s 2018-02-20 -e 2018-02-28
3. All of our services and host are Undetermined for the periode

**Describe the results you received:**
We have lost all dashboard every host or services are in undetermined state
I have added screen shoot, i hope it clearer with it
![image](https://user-images.githubusercontent.com/12892834/36738058-dff036d0-1bdc-11e8-911b-097f4332b1e8.png)
![image](https://user-images.githubusercontent.com/12892834/36738177-334e7b02-1bdd-11e8-827b-8563865470bf.png)

**Describe the results you expected:**
Rebuilding broken host and services dashboard

**Additional information you think important (e.g. issue happens only occasionally):**
I have looked in the Database
SELECT * FROM centreon.contact_param WHERE cp_contact_id IS NULL;

ID | cp_key | cp_value | cp_contact_id
-- | -- | -- | --
1 | report_hour_start | 0 |  
2 | report_minute_start | 0 |  
3 | report_hour_end | 24 |  
4 | report_minute_end | 0 |  
5 | report_Monday | 1 |  
6 | report_Tuesday | 1 |  
7 | report_Wednesday | 1 |  
8 | report_Thursday | 1 |  
9 | report_Friday | 1 |  
10 | report_Saturday | 1 |  
11 | report_Sunday | 1 |  

SELECT * FROM centreon.cron_operation;

id | name | command | time_launch | last_modification | system | module | running | pid | last_execution_time | activate
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | logAnalyser |   | 1453856402 | 0 | 1 |   | 1 | 23150 | 0 | 1
2 | centAcl.php |   | 1519744741 | 0 | 1 |   | 0 |   | 0 | 1
3 | nagiosPerfTrace |   | 1519744501 | 0 | 1 |   | 1 | 22339 | 1 | 1
4 | centstorage_purge |   | 1500940802 | 0 | 1 |   | 1 | 11328 | 2353 | 1
5 | eventReportBuilder |   | 1519727200 | 0 | 1 |   | 1 | 23327 | 99 | 1
6 | dashboardBuilder |   | 1519727125 | 0 | 1 |   | 1 | 23171 | 6 | 1
7 | logAnalyserBroker |   |   | 0 | 1 |   |   |   | 0 | 1

Could you help me ?

Thanks
JJY

**Comment by lpinsivy** [comment]
Can select the ID of one host with this issue and execute the following request on your centreon_storage database:

`SELECT * FROM log_archive_host WHERE host_id = 'HOST_ID' AND date_end >= '1519081200' AND date_end < '1519686000';`

**Comment by DeadPixhell** [comment]
Hello lpinsivy,

Thanks for your help,

There is the result for request:
**SELECT * FROM log_archive_host WHERE host_id = '1508' AND date_end >= '1519081200' AND date_end < '1519686000';**

log_id | host_id | UPTimeScheduled | UPnbEvent | UPTimeAverageAck | UPTimeAverageRecovery | DOWNTimeScheduled | DOWNnbEvent | DOWNTimeAverageAck | DOWNTimeAverageRecovery | UNREACHABLETimeScheduled | UNREACHABLEnbEvent | UNREACHABLETimeAverageAck | UNREACHABLETimeAverageRecovery | UNDETERMINEDTimeScheduled | MaintenanceTime | date_end | date_start
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
641362 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519081200 | 1518994800
676181 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519167600 | 1519081200
677034 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519254000 | 1519167600
677887 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519340400 | 1519254000
678740 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519426800 | 1519340400
679593 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519513200 | 1519426800
680446 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519599600 | 1519513200






I have relaunch this comand yesterday
/usr/share/centreon/cron/eventReportBuilder -r -s 2018-02-20 -e 2018-02-27
/usr/share/centreon/cron/dashboardBuilder -r -s 2018-02-20 -e 2018-02-28

We have more data but not everything 
![image](https://user-images.githubusercontent.com/12892834/36777919-7c55f882-1c6b-11e8-925a-9663341c3a46.png)
the host (host id 1508) still undtermined and one services too.
I have looked in centreon the status of the host is green

log_id | host_id | UPTimeScheduled | UPnbEvent | UPTimeAverageAck | UPTimeAverageRecovery | DOWNTimeScheduled | DOWNnbEvent | DOWNTimeAverageAck | DOWNTimeAverageRecovery | UNREACHABLETimeScheduled | UNREACHABLEnbEvent | UNREACHABLETimeAverageAck | UNREACHABLETimeAverageRecovery | UNDETERMINEDTimeScheduled | MaintenanceTime | date_end | date_start
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
682152 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519772400 | 1519686000
683005 | 1508 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 86400 | 0 | 1519772400 | 1519686000

**Comment by DeadPixhell** [comment]
why in the database it's says undetermined, when the host is up all time ?

**Comment by lpinsivy** [comment]
For only one host no. You must rebuild for all object on dedicated period

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
