### ISSUE TITLE
[Widget] Top 10 widget doesn't refresh

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon#6096]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: N/A

**Centreon Engine version**: N/A

**Centreon Broker version**: N/A

**OS**: N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

centreon-widget-live-top10-cpu-usage-1.1.1
centreon-widget-live-top10-memory-usage-1.1.1

**Steps to reproduce the issue:**
1. Add a custom view
2. Add TOP 10 widget
3. Wait for refresh

**Describe the results you received:**

Data never change

**Describe the results you expected:**

Data are updated

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by adr-mo** [comment]
Ok validation done. Auto refresh of the widgets is now working.
Code done here:
https://github.com/centreon/centreon-widget-live-top10-cpu-usage/commit/cb0455bef60c88eaa98b501765e5a31f9c4efb46
https://github.com/centreon/centreon-widget-live-top10-memory-usage/commit/080e05418fa9a2cf98d5ee33d25619d15620e3c6
