### ISSUE TITLE
centreon export command crashes with heavy load

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#6105]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web-2.8.18-7.el6.noarch

**Centreon Engine version**: 
centreon-engine-daemon-1.8.1-1.el6.x86_64

**Centreon Broker version**: 
centreon-broker-cbd-3.0.13-1.el6.x86_64

**OS**: 
CentOS release 6.9 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM

**Steps to reproduce the issue:**
1.  strace /usr/bin/centreon -u admin -p 'password' -e 2> /tmp/debug.log 1> /tmp/output.log
2.
3.

**Describe the results you received:**
The command is stuck in memory "forever" and consumes CPU / memory. The dump stops on the first HOST dump :

> CG;addcontact;Supervisors;msartiaux;msartiaux
HOST;ADD;Centreon-Server;Monitoring Server;127.0.0.1;;Central;
HOST;setparam;Centreon-Server;host_active_checks_enabled;2
HOST;setparam;Centreon-Server;host_passive_checks_enabled;2
HOST;setparam;Centreon-Server;host_checks_enabled;2
HOST;setparam;Centreon-Server;host_obsess_over_host;2
HOST;setparam;Centreon-Server;host_check_freshness;2
HOST;setparam;Centreon-Server;host_event_handler_enabled;2
HOST;setparam;Centreon-Server;host_flap_detection_enabled;2
HOST;setparam;Centreon-Server;host_process_perf_data;2
HOST;setparam;Centreon-Server;host_retain_status_information;2
HOST;setparam;Centreon-Server;host_retain_nonstatus_information;2
HOST;setparam;Centreon-Server;host_notification_interval;0
HOST;setparam;Centreon-Server;host_notification_options;d,u,r,f
HOST;setparam;Centreon-Server;host_notifications_enabled;2
HOST;setparam;Centreon-Server;contact_additive_inheritance;0
HOST;setparam;Centreon-Server;cg_additive_inheritance;0
HOST;setparam;Centreon-Server;host_snmp_version;0
HOST;setparam;Centreon-Server;timezone;Europe/London
HOST;setparam;Centreon-Server;host_locked;0
HOST;setparam;Centreon-Server;host_register;1
HOST;setparam;Centreon-Server;host_activate;1

And the end of the strace is like this :

> open("/tmp", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 7
getdents(7, /* 31 entries */, 32768)    = 1856
getdents(7, /* 0 entries */, 32768)     = 0
close(7)                                = 0
stat("/tmp/zend_cache---1d290a213a4870dfb6ef153d29a86386", {st_mode=S_IFREG|0600, st_size=31, ...}) = 0
stat("/tmp/zend_cache---1e98fd88ad42008088ecdd4f642919dd", {st_mode=S_IFREG|0600, st_size=29, ...}) = 0
stat("/tmp/zend_cache---32ad8241ef93b0e100116bf4283782c5", {st_mode=S_IFREG|0600, st_size=28, ...}) = 0
stat("/tmp/zend_cache---96b26c8dc6ba53264cc9c9c2cc3468b3", {st_mode=S_IFREG|0600, st_size=35, ...}) = 0
stat("/tmp/zend_cache---9727f9bc7f9b76be5c2410b70c3b2cdc", {st_mode=S_IFREG|0600, st_size=27, ...}) = 0
stat("/tmp/zend_cache---a6e86dcd8f50a1276315216e171f46ea", {st_mode=S_IFREG|0600, st_size=28, ...}) = 0
stat("/tmp/zend_cache---b46a94658484847eafe542e7934f64ca", {st_mode=S_IFREG|0600, st_size=31, ...}) = 0
stat("/tmp/zend_cache---b52a125d96798776df01aa35ffb1985d", {st_mode=S_IFREG|0600, st_size=29, ...}) = 0
stat("/tmp/zend_cache---c1b27344e3e037cd963a29620026f3e7", {st_mode=S_IFREG|0600, st_size=26, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---1d290a213a4870dfb6ef153d29a86386", {st_mode=S_IFREG|0600, st_size=97, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---1e98fd88ad42008088ecdd4f642919dd", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---32ad8241ef93b0e100116bf4283782c5", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---96b26c8dc6ba53264cc9c9c2cc3468b3", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---9727f9bc7f9b76be5c2410b70c3b2cdc", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---a6e86dcd8f50a1276315216e171f46ea", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---b46a94658484847eafe542e7934f64ca", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---b52a125d96798776df01aa35ffb1985d", {st_mode=S_IFREG|0600, st_size=97, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---c1b27344e3e037cd963a29620026f3e7", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
open("/tmp", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 7
getdents(7, /* 31 entries */, 32768)    = 1856
getdents(7, /* 0 entries */, 32768)     = 0
close(7)                                = 0
stat("/tmp/zend_cache---1d290a213a4870dfb6ef153d29a86386", {st_mode=S_IFREG|0600, st_size=31, ...}) = 0
stat("/tmp/zend_cache---1e98fd88ad42008088ecdd4f642919dd", {st_mode=S_IFREG|0600, st_size=29, ...}) = 0
stat("/tmp/zend_cache---32ad8241ef93b0e100116bf4283782c5", {st_mode=S_IFREG|0600, st_size=28, ...}) = 0
stat("/tmp/zend_cache---96b26c8dc6ba53264cc9c9c2cc3468b3", {st_mode=S_IFREG|0600, st_size=35, ...}) = 0
stat("/tmp/zend_cache---9727f9bc7f9b76be5c2410b70c3b2cdc", {st_mode=S_IFREG|0600, st_size=27, ...}) = 0
stat("/tmp/zend_cache---a6e86dcd8f50a1276315216e171f46ea", {st_mode=S_IFREG|0600, st_size=28, ...}) = 0
stat("/tmp/zend_cache---b46a94658484847eafe542e7934f64ca", {st_mode=S_IFREG|0600, st_size=31, ...}) = 0
stat("/tmp/zend_cache---b52a125d96798776df01aa35ffb1985d", {st_mode=S_IFREG|0600, st_size=29, ...}) = 0
stat("/tmp/zend_cache---c1b27344e3e037cd963a29620026f3e7", {st_mode=S_IFREG|0600, st_size=26, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---1d290a213a4870dfb6ef153d29a86386", {st_mode=S_IFREG|0600, st_size=97, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---1e98fd88ad42008088ecdd4f642919dd", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---32ad8241ef93b0e100116bf4283782c5", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---96b26c8dc6ba53264cc9c9c2cc3468b3", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---9727f9bc7f9b76be5c2410b70c3b2cdc", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---a6e86dcd8f50a1276315216e171f46ea", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---b46a94658484847eafe542e7934f64ca", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---b52a125d96798776df01aa35ffb1985d", {st_mode=S_IFREG|0600, st_size=97, ...}) = 0
stat("/tmp/zend_cache---internal-metadatas---c1b27344e3e037cd963a29620026f3e7", {st_mode=S_IFREG|0600, st_size=98, ...}) = 0
poll([{fd=4, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
write(4, "D\0\0\0\3SELECT host_parent_hp_id,ho"..., 72) = 72
read(4, "\1\0\0\1\2p\0\0\2\3def\10centreon\30host_host"..., 16384) = 1333
                                                                                     

It always stops at the same point. fd 4 is a unix socket (mysql, I assume)..

I can't find where is the problem

**Describe the results you expected:**
Dump completed without any error

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

I suppose you have a problem in your configuration.

```
# time /usr/bin/centreon -u superadmin -p 'centreon' -e > /tmp/output.log

real	0m34.349s
user	0m20.415s
sys	0m5.502s

# ls -lah /tmp/output.log
-rw-r--r-- 1 root root 60M 15 mars  10:46 /tmp/output.log

# wc -l /tmp/output.log
1099883 /tmp/output.log
```

**Comment by gslongo** [comment]
Hi,

Hum, maybe, but the system is working fine. Dumps was working in the past. How could I find the config which causes issue ?

Thanks

**Comment by lpinsivy** [comment]
Did you try gain since last time because we correct export using CLAPI?
