### ISSUE TITLE
Downtime comments charset issue

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#6111]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: 2.6.32-696.20.1.el6.x86_64

**Steps to reproduce the issue:**
1. Go to Monitoring  >  Downtimes  >  Comments
2. Add a comment with special characters preferably
3. Notice comment visualization

**Describe the results you received:**
Charset visualization is different than charset edition

**Describe the results you expected:**
Charset visualization has to be fixed

![image](https://user-images.githubusercontent.com/25208457/37032456-5d796e20-2121-11e8-942c-7e22ae8f61e8.png)

**Additional information you think important (e.g. issue happens only occasionally):**

Service monitoring widget visualization is ok

![image](https://user-images.githubusercontent.com/25208457/37032570-c086e6aa-2121-11e8-9e9f-b97c94f5b207.png)

**Comment by Moujimouja** [comment]
Hi,

This is fix in the latest Centreon version. You should update to version >= 19.10 to benefit from the latest evolutions & patches.

Have a nice day
