### ISSUE TITLE
some database poller updates are not active check your monitoring platform

### ISSUE THREAD

**Issue by Elikha** [centreon/centreon#6120]
Hello everyone,

I have a distribued centreon plateform but every morning I notice an error "some database poller updates are not active check your monitoring platform"...

And I also noticed that if I do a reboot of the central server or restart /etc/init.d/Mysql the problem disappears.

So, by this way I need you help to fix it.

Best regards.

**Comment by lpinsivy** [comment]
Hi,

This error message means that some pollers may have retention queue of data.

Next time can you check:

- Number of connected user in MySQL
- "Last Update" fields in "Configuration > Pollers" menu
- If you have retention files in 'var/lib/centreon-broker/*.retention ' of your poller and central server.

**Comment by Elikha** [comment]
All gone right when I resolved the problem of partitionning in table 'logs' cause the date of partitionning was 1970 and 2018 ...
But How can I know the number of connected user in MySQL ?
And also why on my poller centreontrapd is all time down and if I do ./centreontrapd restart then ./centreontrapd status I had an error like 'centreontrapd est mort mais le fichier PID existe'.

Also, in /var/log/centreon/centreontrapd file the error is "2018-03-15 11:57:29 - 27573 - Mode: poller"
"2018-03-15 11:57:29 - 27573 - MySQL error: no such table: cfg_nagios (caller: centreon::script::centreontrapd:/usr/share/perl5/vendor_perl/centreon/script/centreontrapd.pm:1168)
Query: SELECT `command_file` FROM `cfg_nagios` WHERE `nagios_activate` = '1' LIMIT 1"

**Comment by lpinsivy** [comment]
> But How can I know the number of connected user in MySQL ?
use show full processlist;

you don't have cfg_nagios table in 'centreon' database?
Can you check the file /etc/centreon/conf.pm?
