### ISSUE TITLE
centreon 2.5.4 widget

### ISSUE THREAD

**Issue by navigationH** [centreon/centreon#6124]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.5.4

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: 
centeros 6.0
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.   can't open custiom viex-->host widget
2.
3.

**Describe the results you received:**
File does not exist: /usr/local/centreon/www/include/common/javascript/centreon/popin.js, referer: http://x.x.x.x/centreon/widgets/host-monitoring/index.php?widgetId=9

**Describe the results you expected:**
what happen? help me ,please~

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

The Centreon Web 2.5.4 is [no more supported](https://documentation.centreon.com/docs/centreon/en/2.8.x/life_cycle.html#centreon-oss).

Can you update to Centreon Web 2.8.x version please.

Regards,

**Comment by navigationH** [comment]
@lpinsivy yes ,i will update to centreon web 2.7.X,but ,i can find the RPM-GPG-KEY.dag.txt,

**Comment by lpinsivy** [comment]
Centreon Web 2.7.x is no more supported too.

http://yum-1.centreon.com/standard/3.4/el6/stable/RPM-GPG-KEY-CES
