### ISSUE TITLE
Graph problem - On large interval

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#6133]
Closing too fast, there is no duplication of issue https://github.com/centreon/centreon/issues/6116

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: RH 6.9

**Steps to reproduce the issue:**
1. Go to Performance
2. Choose a graph, which takes the number of users connected to a wifi terminal for example.
3. Change the time interval

**Describe the results you received:**

We have a problem with the displayed values, which are related to the number of rows retrieved during an 'xport rrdtool'.

The displayed values should be the warning limit, first horizontal line

![image](https://user-images.githubusercontent.com/16583698/37096283-747d2560-2218-11e8-898f-0a8971d086fd.png)

![image](https://user-images.githubusercontent.com/16583698/37096302-85f5e700-2218-11e8-8aa7-105d1e2c5171.png)

**Describe the results you expected:**

![image](https://user-images.githubusercontent.com/16583698/37096392-bfa28210-2218-11e8-9784-8d70ead83244.png)

![image](https://user-images.githubusercontent.com/16583698/37096416-cef5fcce-2218-11e8-912a-c477447f3469.png)

**Comment by lpinsivy** [comment]
@jben94 I don't understand your issue

**Comment by jben94** [comment]
Hi,

- If we zoom out, the curve is average and with very little calculation points.
- If we zoom in, the values of the curves are true

Regards

**Comment by jben94** [comment]
To fix the problem we have changed the parameters of the xport function of rrdtool
