### ISSUE TITLE
check_centreon_snmp_remote_storage reports wrong results

### ISSUE THREAD

**Issue by Poilaucul** [centreon/centreon#6135]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.7.13-1.el6.noarch

**Centreon Engine version**: centreon-engine-1.5.3-1.el6.x86_64

**Centreon Broker version**: centreon-broker-2.11.8-2.el6.x86_64

**OS**: CentOS release 6.9 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Steps to reproduce the issue:**

1. Use command "check_centreon_snmp_remote_storage" to check disk size of a remote RedHat/CentOS 6.X host with around 10TB mounted partition

2. From Centreon:

[root@centreon centreon]# /usr/lib/nagios/plugins/check_centreon_snmp_remote_storage -H 172.16.2.213 -n -d add -w 80 -c 90 -v 2 -C public
Disk CRITICAL - /add TOTAL: 1021.728GB USED: 6561.229GB (642%) FREE: -5539.501GB (-542%)|size=1097072603136B used=7045066018816B;877658082508;987365342822;0;1097072603136
[root@centreon centreon]#

3. On the remote host:

[root@remotehost ~]# df -h /add/
Filesystem      Size  Used Avail Use% Mounted on
/dev/drbd0      9.0T  6.5T  2.6T  72% /add
[root@remotehost ~]#

**Describe the results you received:**

Disk CRITICAL - /add TOTAL: 1021.728GB USED: 6561.112GB (642%) FREE: -5539.384GB (-542%)
size=1097072603136B used=7044940513280B;987365342822;1020277520916;0;1097072603136

**Describe the results you expected:**

Disk /add TOTAL: 9214GB USED: 6562GB (72%) FREE: 2653GB (28%)

**Additional information you think important (e.g. issue happens only occasionally):**

Seems to appear when partition size exceeds a certain value

**Comment by lpinsivy** [comment]
Hi,

The old Centreon plugins are no more supported.
Please use the new project https://github.com/centreon/centreon-plugins

Regards,

**Comment by Sims24** [comment]
As a side note it's a snmp limit regarding counter size. 

You should use an other medium tout check very large fs
