### ISSUE TITLE
[2.8.x] WebUI : Too many keepalive calls

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#6144]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.18

**Steps to reproduce the issue:**
1. Open a session on Centreon 
2. Go into Configuration screen
3. With Firefox, strike the F12 key to open the dev. pannel, go into the Network tab
4. Have a look at all the keepalive calls

**Describe the results you received:**
![capture](https://user-images.githubusercontent.com/2464712/37584538-2e85a996-2b56-11e8-8897-8082d47de2d6.PNG)
A call every 15seconds. I think this frequency is too high for nothing.
When you have a lot of user , you webserver is flooded by theses calls.

**Describe the results you expected:**
Something more peaceful, like a call every minute

**Comment by lpinsivy** [comment]
Hi @BenoitPoulet 

This is launch by your browser (javascript) to update frequently your session.
This impact on the web server is really minor, isn't it?

**Comment by BenoitPoulet** [comment]
Hello,

Yes, low impact on the load, but not on the log files.

I have around 170 000 keepalives par day, that's a lot, and i think most of them are not needed.

So for me, this is an unnecessary load, reduce it is optimization.

**Comment by lpinsivy** [comment]
We will keep it in mind for next minor version
