### ISSUE TITLE
SQL Deadlock when reloading/restarting the configuration

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon#6149]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 

**OS**: CentOS 6.9

**Steps to reproduce the issue:**
1. Go to **Configuration --> Poller --> Export configuration**
2. Select one or more collectors
3. Select "Deplacer les fichiers générés" and "Redémarrer l'ordonnanceur"
4. Click on the Export button

**Describe the results you received:**
After few seconds, the error **SQLSTATE[40001]: Serialization Failure: 1213 Deadlock found ... [file:/usr/share/centreon/www/class/config-generate/generate.class.php] [line: 112]** is displayed.

**Describe the results you expected:**
It shouldn't appeared and we  shouldn't have to continuosly restart this process (for exporting and reloading/restarting the configuration on collectors) until no Deadlock error appeared.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Can you perform a "show full processlist;" SQL query on your DB to understand why when you generae configuration?

**Comment by Crash-Fox** [comment]
Hi thanks for your reply,

I have this error when I want to export the configuration an all my collectors (seven in total). And especially on the servers where I have the most hosts (> 1000 hosts).

Here, the output of the SQL query **show full processlist;**:
[show_full_processlist.txt](https://github.com/centreon/centreon/files/1847684/show_full_processlist.txt)

**Comment by lpinsivy** [comment]
duplicate #6192
