### ISSUE TITLE
Centreon-broker - influxdb output macro problem

### ISSUE THREAD

**Issue by mavynet** [centreon/centreon#6153]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18-6

**Centreon Engine version**: 1.8.1-1

**Centreon Broker version**: 3.0.13-1

**OS**: CentOS el7

**Steps to reproduce the issue:**
1. Create a new output for centreon-broker of type InfluxDB
2. Use the $HOST$ or $SERVICE$ macro for the metric name or tag and set broker logging to "Very detailed"
3. Export configuration to the centreon server and restart cbd service

**Describe the results you received:**
in the broker log file:
[1521549268] [0x7fef0acf6700] error:   influxdb: could not generate query for metric 7562: influxdb: could not find information on service (77, 1329)
[1521549273] [0x7fef0acf6700] error:   influxdb: could not generate query for metric 9265: influxdb: could not find information on service (132, 1448)
[1521549288] [0x7fef0acf6700] error:   influxdb: could not generate query for metric 7573: influxdb: could not find information on service (107, 1445)

**Describe the results you expected:**
Correct output generation of influxdb queries

**Additional information you think important (e.g. issue happens only occasionally):**
On the previous versions it was working correctly. Currently working on another Centreon instance using Broker 3.0.10-3, Web 2.8.15-4, Engine 1.8.0-2

Also I've noticed that if you change something in the "Logger" tab of the broker, the influx output is messed up. Probably this is an UI bug.

Thanks for the help

**Comment by lpinsivy** [comment]
Hi,

Can you put working influxdb output broker and non working to see the difference?

**Comment by mavynet** [comment]
This one works:
` <output>
  <name><![CDATA[Influxdb]]></name>
  <cache><![CDATA[yes]]></cache>
  <db_host><![CDATA[10.171.22.35]]></db_host>
  <db_port><![CDATA[8086]]></db_port>
  <db_user><![CDATA[centreon]]></db_user>
  <db_password><![CDATA[centpass]]></db_password>
  <db_name><![CDATA[centreon]]></db_name>
  <metrics_timeseries><![CDATA[$METRIC$]]></metrics_timeseries>
  <status_timeseries><![CDATA[status]]></status_timeseries>
  <type><![CDATA[influxdb]]></type>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$SERVICE$]]></value>
   <name><![CDATA[service]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$TIME$]]></value>
   <name><![CDATA[time]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$SERVICE$]]></value>
   <name><![CDATA[service]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$TIME$]]></value>
   <name><![CDATA[time]]></name>
  </metrics_column>
 </output>
`
This one doesn't:
` <output>
  <name><![CDATA[InfluxDB]]></name>
  <cache><![CDATA[yes]]></cache>
  <db_host><![CDATA[10.171.22.35]]></db_host>
  <db_port><![CDATA[8086]]></db_port>
  <db_user><![CDATA[centreon]]></db_user>
  <db_password><![CDATA[centpass]]></db_password>
  <db_name><![CDATA[centreon]]></db_name>
  <metrics_timeseries><![CDATA[$METRIC$]]></metrics_timeseries>
  <status_timeseries><![CDATA[status]]></status_timeseries>
  <type><![CDATA[influxdb]]></type>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$TIME$]]></value>
   <name><![CDATA[time]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$TIME$]]></value>
   <name><![CDATA[time]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[false]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$VALUE$]]></value>
   <name><![CDATA[value]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$METRICID$]]></value>
   <name><![CDATA[metric_id]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$INDEXID$]]></value>
   <name><![CDATA[index_id]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$HOST$]]></value>
   <name><![CDATA[host]]></name>
  </status_column>
  <metrics_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$SERVICE$]]></value>
   <name><![CDATA[service]]></name>
  </metrics_column>
  <status_column>
   <is_tag><![CDATA[true]]></is_tag>
   <type><![CDATA[string]]></type>
   <value><![CDATA[$SERVICEID$]]></value>
   <name><![CDATA[service_id]]></name>
  </status_column>
 </output>
`

If I remove the macros for $SERVICE$ and $HOST$ it works ok.

BR

**Comment by mavynet** [comment]
Update: Just figured out that the problem appears only for active checks on hosts monitored from a remote poller. For the hosts monitored from central server it works ok, Also for passive checks from remote poller it works ok.

Is there something I should set differently for active hosts on remote pollers? Or should I make a different broker output for each remote poller?

**Comment by mavynet** [comment]
Hi again. After some time working OK, the issue reappeared after /var filesystem got full and the broker couldn't write in the influxdb cache file.

Now all metrics return errors about error: influxdb: could not generate query for metric XXXXX: influxdb: could not find information on host XXX

Any help would be appreciated.
Thanks

**Comment by mavynet** [comment]
I've managed to install the new strem connector and I receive a similar error using the script from the example on centreon documentation:

Tue 24 Jul 2018 02:32:13 PM EEST: WARNING: event_queue:add: host_name for id 52 not found. Restarting centengine should fix this.
Tue 24 Jul 2018 02:32:13 PM EEST: WARNING: event_queue:add: service_description for id 52.346 not found. Restarting centengine should fix this.
Tue 24 Jul 2018 02:32:14 PM EEST: WARNING: event_queue:add: host_name for id 52 not found. Restarting centengine should fix this.
Tue 24 Jul 2018 02:32:14 PM EEST: WARNING: event_queue:add: service_description for id 52.345 not found. Restarting centengine should fix this.
Tue 24 Jul 2018 02:32:14 PM EEST: WARNING: event_queue:add: host_name for id 52 not found. Restarting centengine should fix this.
Tue 24 Jul 2018 02:32:14 PM EEST: WARNING: event_queue:add: service_description for id 52.344 not found. Restarting centengine should fix this.
Tue 24 Jul 2018 02:32:36 PM EEST: WARNING: event_queue:add: host_name for id 54 not found. Restarting centengine should fix this.
Tue 24 Jul 2018 02:32:36 PM EEST: WARNING: event_queue:add: service_description for id 54.412 not found. Restarting centengine should fix this.

Please let me know if you need more details
