### ISSUE TITLE
Centreon-broker : Insert in data_bin failed due to status field type

### ISSUE THREAD

**Issue by FredericBarbier** [centreon/centreon#6156]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.19

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical

**Steps to reproduce the issue:**
1. Install Centreon 2.8.19
2. Create host and linked services with perfdata on central

**Describe the results you received:**
No graph are generated and displayed.
We have this messages in /var/log/centreon-broker/central-broker-master.log : 

**[1521542335] error:   storage: could not insert data in log_data_bin: could not execute query: Data truncated for column 'status' at row 1 QMYSQL: Unable to execute query (INSERT INTO data_bin  (id_metric   , ctime, status, value)  VALUES (4813, 1521541756, 0, '1.0000000000e+00'), (4814, 1521541757, 0, 1.0000000000e+00), ...**

In generated query, status is inserted as int value, but data_bin table status type is enum : 

+-----------+---------------------------+------+-----+---------+-------+
| Field     | Type                      | Null | Key | Default | Extra |
+-----------+---------------------------+------+-----+---------+-------+
| id_metric | int(11)                   | YES  | MUL | NULL    |       |
| ctime     | int(11)                   | YES  |     | NULL    |       |
| value     | float                     | YES  |     | NULL    |       |
| status    | enum('0','1','2','3','4') | YES  |     | NULL    |       |
+-----------+---------------------------+------+-----+---------+-------+

It seems there is a mismatch on status field type.

The only workaround found so far is to alter the data_bin table with : 

`ALTER TABLE data_bin MODIFY status TINYINT`

With this workaround graphs are displayed normally.

Is there a real mismatch bug or installation issue ?

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

What is your SGBD and version ?

**Comment by FredericBarbier** [comment]
Hi thanks for your reply,

We are using **MariaDB**: 10.2.9

**Comment by lpinsivy** [comment]
we didn't test MariaDB 10.2 but only 10.0 and 10.1.

Can you downgrade?

**Comment by barte91** [comment]
I've the same problem, there is any solution without downgrade MariaDB?

**Comment by adr-mo** [comment]
Hi @barte91 

For now we are not compatible for now with the **mariadb 10.2**.
Only **10.1.x and 10.0.x** are supported for now.

Regards,
