### ISSUE TITLE
Services count not accurate

### ISSUE THREAD

**Issue by springequinox** [centreon/centreon#6157]
**Hi,**
I just want to ask if anyone knows why why Service (Critical) count on _Unhandled problems_ seem to be high - but when we check on the monitoring console, we only see few alerts.
_Thanks in advance :)_

**Comment by lpinsivy** [comment]
Hi,

Can you use the template of issue and try to put print screen and more description.

Regards,

**Comment by springequinox** [comment]
![services](https://user-images.githubusercontent.com/28866759/37848290-98830706-2f0e-11e8-9ca8-2600fec826cd.PNG)

The red one indicates the _number of Unhandled problems_  [numerator]  over the Total number of alerts [denominator]
**22/297**




![services1 1](https://user-images.githubusercontent.com/28866759/37848147-08365b94-2f0e-11e8-8539-2736532e23b2.PNG)


This photo displays the current Unhandled alerts in Critical.


As you can see, there is a big difference in the count of Unhandled alerts.
**22 vs 4**



We also have the same setup for Warning alerts and it goes well so far.


**_What could be the problem?_**

**Comment by springequinox** [comment]
Can I get an answer for this?

**Comment by lpinsivy** [comment]
Can you use the template of issue, especially to know the versions of the components?
