### ISSUE TITLE
Configuration / Services templates : pagination & search issue

### ISSUE THREAD

**Issue by omercier** [centreon/centreon#6161]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.19-4.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-core-3.0.13-1.el7.centos.x86_64

**OS**: centos-release-7-4.1708.el7.centos.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):** several types of hardware or virtual environments

**Steps to reproduce the issue:**
1. Go to Configuration / Services templates
2. Perform a search that gives at least two pages of results
3. Click on page 2

**Describe the results you received:**
Nothing happens.

**Describe the results you expected:**
Display page 2.

**Additional information you think important (e.g. issue happens only occasionally):** Happens every time. We should check whether other menus have the same behaviour.

**Comment by kozfelipe** [comment]
#5728

**Comment by lpinsivy** [comment]
maybe related to #5109

**Comment by adr-mo** [comment]
Hi @omercier 

Thanks for the feedback 💯 

This issue will be fixed in the **18.10.5 release**

Regards,
