### ISSUE TITLE
Services Grid, Services by (host|service)groups display "All" instead of "Problems" as the filter suggests

### ISSUE THREAD

**Issue by omercier** [centreon/centreon#6162]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.19-4.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-core-3.0.13-1.el7.centos.x86_64

**OS**: centos-release-7-4.1708.el7.centos.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):** several types of hardware or virtual environments
**Steps to reproduce the issue:**
1. Go to Monitoring / Status Detail / Services grid
2. Or go to Monitoring / Status Detail / Services by Hostgroups
3. Or go to Monitoring / Status Detail / Services by Servicegroups

**Describe the results you received:**
"Display details" filter (which, by the way, is not well named, maybe "Status filter" would be better ) is set to "Problems" BUT actually displays "All". You have to apply another filter and then get back to "Problems" to actually display problems only.

**Describe the results you expected:**
Displaying problems only, as the filter suggests.

**Additional information you think important (e.g. issue happens only occasionally):** none

**Comment by CPbN** [comment]
This tiny change corrects the issue, switching back to the "All" filter :
```
--- www/include/monitoring/status/ServicesHostGroups/serviceGridByHG.php.orig	2018-08-27 17:22:09.859387360 +0200
+++ www/include/monitoring/status/ServicesHostGroups/serviceGridByHG.php	2018-08-27 17:22:28.412623975 +0200
@@ -104,7 +104,6 @@
     $form->addElement('select', 'typeDisplay', _('Display'), $aTypeAffichageLevel1, array('id' => 'typeDisplay', 'onChange' => "displayingLevel1(this.value);"));
     $form->addElement('select', 'typeDisplay2', _('Display '), $aTypeAffichageLevel2, array('id' => 'typeDisplay2', 'onChange' => "displayingLevel2(this.value);"));
     
-    $form->setDefaults(array('typeDisplay2' => 'pb'));
 
     $tpl->assign("order", strtolower($order));
     $tab_order = array("sort_asc" => "sort_desc", "sort_desc" => "sort_asc");
```

Same fix in other concerned views :
`www/include/monitoring/status/Services/serviceGrid.php`
`www/include/monitoring/status/ServicesServiceGroups/serviceGridBySG.php`

**Comment by CPbN** [comment]
Issue still present in 18.10.2 (#6951 helps).

**Comment by CPbN** [comment]
There must be a proper solution, but here's a working crappy workaround :
At the end of `www/include/monitoring/status/ServicesHostGroups/serviceGridByHG.php` :
```
<script type="text/javascript">
jQuery(function () {
var sel1 = document.getElementById("typeDisplay").value;
var sel2 = document.getElementById("typeDisplay2").value;
_o = sel1 + '_' + sel2;
setTimeout(function(){monitoring_refresh()},1000);
</script>
});
```

Edit : issue still present in 18.10.3.

**Comment by CPbN** [comment]
I found the correct workaround here :
https://github.com/centreon/centreon/blob/master/www/install/sql/centreon/Update-DB-2.7.1.sql

Strangely, even on a fresh install, these requests are not applied.
And in the default SQL installation schema, error remains :
https://github.com/centreon/centreon/blob/master/www/install/insertTopology.sql#L34

Edit : issue still present in 18.10.3.

**Comment by CPbN** [comment]
See PR #7327 for the correct fix :+1:
