### ISSUE TITLE
Configuration / Hosts: Pagination/search issue

### ISSUE THREAD

**Issue by omercier** [centreon/centreon#6164]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.19-4.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-core-3.0.13-1.el7.centos.x86_64

**OS**: centos-release-7-4.1708.el7.centos.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):** several types of hardware or virtual environments

**Steps to reproduce the issue:**
1. Go to Configuration / Hosts (you need to have at least two pages, so you might need to display 10 hosts per page)
2. Go to page 2 or higher
3. Type something in the "name" filter and click on "search". IMPORTANT: choose a filter that matches at least one host but fewer than the number of elements displayed by n pages where n is the page number you chose in step 2. To be more clear, if you are displaying page 2, type a search criteria that displays elements only on 1 page.

**Describe the results you received:**
No hosts are displayed.

**Describe the results you expected:**
My search matches several hosts, so I expected to see them. But I suppose the WUI still tries to display page two, so there is nothing to be displayed...

**Additional information you think important (e.g. issue happens only occasionally):**
This is an annoying bug and I had a hard time figuring how to reproduce it, but if you follow the steps, it will happen every time.

**Comment by lpinsivy** [comment]
should be link to #6161

**Comment by adr-mo** [comment]
Hi @omercier 

Thanks for the feedback 💯 

This issue will be fixed in the **18.10.5 release**

Regards,
