### ISSUE TITLE
Services Not Displaying in Console/Graphical Bug

### ISSUE THREAD

**Issue by pfilbin90** [centreon/centreon#6165]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.4

**Centreon Engine version**: 
MariaDB 10.1.21

**Centreon Broker version**: 
3.0.7-1.e17.centos

**OS**: 
centos 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on AWS m4.xlarge.  1 remote poller also on AWS

**Steps to reproduce the issue:**
1. Click Monitoring > Click Status > Click Hosts
2. Click on a Host 

**Describe the results you received:**
Sometimes the "Service Status" tab is populated, and nothing appears wrong.  However, sometimes it's just a blank white screen with no information (even if it is confirmed that this host has Services attached).  

**Describe the results you expected:**
A fully populated Service Status tab with the Details of each service on a host listed.

**Additional information you think important (e.g. issue happens only occasionally):**
This issue only happens occasionally.  A restart of the the centreon services (cbd, centcore, centengine) does not fix the issue

**Comment by lpinsivy** [comment]
Hi,

Next time can you try to use your browser debug and check javascript error.

Unable to reproduce.
