### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#6166]
Centreon version 2.8.17
Centreon Engine 1.8.1
Centreon Broker 3.0.12
CES 3.4.1 (CentOS 6.9)

```
# yum update
Loaded plugins: fastestmirror
Setting up Update Process
Loading mirror speeds from cached hostfile
 * base: ftp.freepark.org
 * extras: ftp.freepark.org
 * updates: ftp.freepark.org
http://ftp.freepark.org/pub/linux/distributions/centos/6.9/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 500 Internal Server Error"
Trying other mirror.
http://mirror.digitalnova.at/CentOS/6.9/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 500 Internal Server Error"
Trying other mirror.
http://mirror.inode.at/data/centos/6.9/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 500 Internal Server Error"
Trying other mirror.
```
etc. (total something like 32 servers)

Not sure what's going on, is there currently a Centreon repo issue and should I try later, or is it maybe something networking related? I last updated successfully on Feb 21st.

**Comment by lpinsivy** [comment]
Hi,

The errors displayed are not about Centreon but about mirror.inode.at repo issue.
Try to retry latter.

**Comment by btassite** [comment]
FYI: found solution: it was not a problem with a specific repo; an upstream proxy provider borked something.

As a workaround commented out proxy= line in /etc/yum.conf
Of course if you must go through a proxy that won't work, you need to ask your proxy provider to fix the error on their end :)
