### ISSUE TITLE
[2.8.19] - Recurrent downtimes performance problem

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#6168]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.19

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
1. open or create a new recurrent downtime

**Describe the results you received:**
You need to wait 10-20 seconds before Period is opened

**Comment by lpinsivy** [comment]
I suppose your account use ACL?

**Comment by joschi99** [comment]
Yes

**Comment by lpinsivy** [comment]
When you plan downtime using ACL, this synchronise rights with your LDAP server. Do you have timeout for one of your LDAP server?

**Comment by joschi99** [comment]
I checked the problem again and I don't think that the problem is related on the ACL's:

* I have the problem also using a admin account
* there is no LDAP for authentication, only local users

**Comment by lpinsivy** [comment]
do you have error in /var/log/httpd/error_log ?
can you enable slow queries logs in MySQL/MariaDB ?

**Comment by joschi99** [comment]
This problem is on newer versions resolved. At the moment using 2.8.26 the performance is ok
