### ISSUE TITLE
Password field is not working

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon#6173]
Hello guys,

I have already opened a request at the plugin section, but it's not the right section:
https://github.com/centreon/centreon-plugins/issues/925

I cannot use the password field in my host template. In the check command it's showing up in clear text. The other template which I have created a few weeks ago is working perfect.

Thank you very much.

Bets regards, Mike

**Comment by lpinsivy** [comment]
Do you use "regex" characters in your recent password?

**Comment by MikeW83** [comment]
Sorry, but I don't know exactly what you mean. I use the same command line template in other services attached to other hosts and there is no problem. And one service is showing the password and the other don't show it.

**Comment by lpinsivy** [comment]
and the password is the same for working and not working?

**Comment by MikeW83** [comment]
Yes, is the same. I crated a host, added the template, filled out username and password. I did this twice without duplication. One is working and one is not.

**Comment by MikeW83** [comment]
I'm using inheritance in my host and service templates. I have a template for Microsoft Exchange to set username and password for using with wmi in my command.
The same macro and variables are used within the other template. Which is not a copy of my Exchange template. All templates has been created manually. Also the inheritance.

**Comment by MikeW83** [comment]
I found the issue. In my base template there was the username and password filled out. I only searched in the template one step above. No everything is working correctly.

**Comment by MikeW83** [comment]
I have the same issue again but in another way:

No I have manually crated a service where the command should use the password and username defined in the host variables. My host entry looks like this:
![centreon-password](https://user-images.githubusercontent.com/35097389/42437486-8c036ef0-835d-11e8-97fd-2546623a566e.PNG)

But when I check the command which is called in the service I see the password. There is no issue with linked templates or anything else.

**Comment by MikeW83** [comment]
Push!
We have customers that must not see this password.
Any thoughts about it?
