### ISSUE TITLE
Contacts inherited from multi template host are not notified

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon#6177]
**Centreon Web version**: 2.8.19

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: CentOS release 6.8 (Final)

Physical Server

**Steps to reproduce the issue:**
1. Create a Host template A with a contact group A with contact group additive inheritance.
2. Create a Host template B inherited from host template A with a contact group B with contact group additive inheritance.
3. Create a Host C based on template B and Template A (because template A is generic, and template B as some services linked related to this type of host)
4. Look at the Host Status Details > Host Informations in Notification Section you will see contact group A & B.

**Describe the results you received:**
- If i take down the Host C, only Contact Group A is notified

**Describe the results you expected:**
- Contact Group A & B Should be notified.

Thank You

**Comment by anthoc** [comment]
The problem seems to be well known and corrected, but despite the status of the bug identified a year ago (https://github.com/centreon/centreon-engine/issues/76), it seems that it's not working. :( Thank You.

**Comment by lpinsivy** [comment]
It is a normal behavior of [template usage](https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/models.html?highlight=template#associative-type-inheritance). Only the first settings of a template (priority order) will be used.

Contact / Contactgroup inheritance will be used only for inheritance father / son template

**Comment by anthoc** [comment]
Hello,

Thank you for your answer. 

About this point : 

4. Look at the Host Status Details > Host Informations in Notification Section you will see contact group A & B.

Is that normal that all contacts are displayed despite the fact that they are not really notified ? 

Thank you

**Comment by lpinsivy** [comment]
No should be a bug

**Comment by lpinsivy** [comment]
should be linked to #6176
