### ISSUE TITLE
[2.8.19] command Host/Getparam not result with REST API

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#6178]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.19

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: CentOS 7 - Centreon 3.4.6

The following clapi command returns this result

`[root@centreon346-7 ~]# centreon -u admin -p password -o HOST -a getparam -v "Central;alias"
alias : serveur supervision Centreon iso CentOS 7`

the REST API command does not return any results

`curl -s 'http://127.0.0.1/centreon/api/index.php?action=action&object=centreon_clapi' -H 'Content-Type: application/json' -H "centreon-auth-token: $(curl -s -d "username=admin&password=password" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://127.0.0.1/centreon/api/index.php?action=authenticate | sed -e 's/^{"authToken":"//' -e 's/"}$//')" --data '{"action":"getparam", "object":"host", "values":"Central;alias"}'
{"result":[]}`

but if I put an invalid host the command returns an error

`curl -s 'http://127.0.0.1/centreon/api/index.php?action=action&object=centreon_clapi' -H 'Content-Type: application/json' -H "centreon-auth-token: $(curl -s -d "username=admin&password=password" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://127.0.0.1/centreon/api/index.php?action=authenticate | sed -e 's/^{"authToken":"//' -e 's/"}$//')" --data '{"action":"getparam", "object":"host", "values":"nasmaison72;alias"}'
"Object not found:nasmaison72"`

**Comment by RymRabehi** [comment]
Hi,

I also have the same issue. Nevermind which values I try to get, it returns an empty array.

Regards,
Rym R.

**Comment by bdeschut** [comment]
It seems like it ignores the first parameter that is provided

When I use the following:
{'values': '<myhostname>;snmp_community|snmp_version|snmp_community', 'action': 'getparam', 'object': 'HOST'}
It returns:
{'result': ['snmp_version : 3', 'snmp_community : ']}

So:
1 parameter return nothing
2 parameters returns the result for the 2nd parameter
3 parameters returns the result for the 2nd and third parameter
...

Kind regards,
Bob
