### ISSUE TITLE
[2.8.19] SQL Deadlock

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon#6192]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.19

**Centreon Engine version**: 1.8.1

**OS**: CentOS 6.9

**Steps to reproduce the issue:**
1. Go to Configuration --> Poller --> Export configuration
2. Select one or more collectors
3. Select "Deplacer les fichiers générés" and "Redémarrer l'ordonnanceur"
4. Click on the Export button

**Describe the results you received:**
After few seconds, the error **SQLSTATE[40001]: Serialization Failure: 1213 Deadlock found ... [file:/usr/share/centreon/www/class/config-generate/generate.class.php] [line: 112]** is displayed.

**Describe the results you expected:**
It shouldn't appeared and we shouldn't have to continuosly restart this process (for exporting and reloading/restarting the configuration on collectors) until no Deadlock error appeared.

**Additional information you think important (e.g. issue happens only occasionally):**
Please find attached to this ticket the show full processlist output (txt file.
[show_full_processlist.txt](https://github.com/centreon/centreon/files/1889168/show_full_processlist.txt)
)

**Comment by lpinsivy** [comment]
How many pollers?
How many average hosts/services by pollers?

**Comment by Crash-Fox** [comment]
We have currently 6 collectors
The repartition of hosts/services is very different from each of them:

- Collector 1: 644 Hosts
- Collector 2: 92 Hosts
- Collector 3: 1366 Hosts
- Collector 4: 194 Hosts
- Collector 5: 128 Hosts
- Collector 6: 1502 Hosts

**Comment by lpinsivy** [comment]
Do you use MySQL (version) or MariaDB (version)?

**Comment by Crash-Fox** [comment]
We use MySQL 5.6.20

**Comment by lpinsivy** [comment]
Do you use MySQL optimisation? from Centreon documentation? Can you enable slow queries debug and give us the log ?

**Comment by Crash-Fox** [comment]
By MySQL Optimization you mean raising the "Maximum queries per transaction" in the configuration page of "central-broker-master" ? Do I have to raise this field in both the "Broker SQL database" part and the "Perfdata Generator (Centreon Storage)" ?

**Comment by Crash-Fox** [comment]
Hello,

I worked in a company where the management of the BDD is done by a specific team, so I can't active the "Slow Queries Debug" and furthermore not on the production environnement.

They tell me that they're not convinced about activating the "Slow Queries Debug", because with the actual configuration in our Centreon environnement it will generated a lot of volumetry. But they are more interested in replaying the requests that are generated during the "reload/restart configuration". So can you give me the list of requests that are executed during this operation ?

**Comment by lpinsivy** [comment]
@Crash-Fox 

When you install Centreon using RPM, Centreon provides MySQL optimizations (/etc/my.cnf.d/centreon.cnf):

```
#
# Custom MySQL/MariaDB server configuration for Centreon
#
[server]
innodb_file_per_table=1

open_files_limit = 32000

key_buffer_size = 256M
sort_buffer_size = 32M
join_buffer_size = 4M
thread_cache_size = 64
read_buffer_size = 512K
read_rnd_buffer_size = 256K
max_allowed_packet = 8M

# For 4 Go Ram
#innodb_additional_mem_pool_size=512M
#innodb_buffer_pool_size=512M

# For 8 Go Ram
#innodb_additional_mem_pool_size=1G
#innodb_buffer_pool_size=1G
```

So I suppose you don't use a dedicated MySQL server but the same server for many application.

Moreover it is not possible to give you a list of SQL operations because it is very important.

Without "Slow Queries Debug" it will be very difficult to help you. Maybe run "SHOW FULL PROCESSLIST" when you restart/reload a poller?

**Comment by Crash-Fox** [comment]
Hello, 

When the **Slow Query Debug** will be activated on MySQL. Beyond which thresold do you considerate a **Slow SQL** request ?

**Comment by lpinsivy** [comment]
more than 3 seconds

**Comment by adr-mo** [comment]
Hi @Crash-Fox 

Closing this ticket, since no news for more than **2 months**

Regards,
