### ISSUE TITLE
Poller definition is not updated under Monitoring Centreon 2.5.0

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#62]
---

Author Name: **Ivo Kostrhoun** (Ivo Kostrhoun)
Original Redmine Issue: 5669, https://forge.centreon.com/issues/5669
Original Date: 2014-07-08
Original Assignee: Julien Mathis

---

Under if I change poller definition under Configuration> Centreon
it is not updated in rolldown menu in Monitoring >Services (or host)

For example i deleted all old pollers but they are still in rolldown Poller menu in Monitoring> services. When I choose no poller - there is lot of duplicity record because I changed name od defaut poller "Central" to "Brno_Main"... Under rolldown menu i still have both of them.

**Comment by ganoze** [comment]
This bug was fixed in an already released version of Centreon.
