### ISSUE TITLE
All users souldn't be able to share custom views

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#620]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 3850, https://forge.centreon.com/issues/3850
Original Date: 2012-10-31

---

Hi, 

I think that we should be able to allow users/groups to share custom views via "Actions ACL" (disabled by default). 

In 2.4-RC6 all of them (including Guest) can : 
- share & impose a view to others
- view all accounts names (!)

pch

**Comment by julienmathis** [comment]
Already implemented. Thanks
