### ISSUE TITLE
[2.8.21] - API Clapi method ApplyTPL doesn't work

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#6207]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.21

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: Centreon 3.4.6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Add centreon plugins pack
2. Add  host with clapi
`centreon -u admin -p password -o host -a add -v "test3;test3;127.0.0.1;OS-Linux-SNMP-custom;central;"`
3. When I want to apply the OS-Linux-SNMP-custom template I get this message and the template is not applied
`centreon -u admin -p password -o host -a applytpl -v test3`
`Please check that your parameters are valid`
4. if I create all services by hand, the applycfg method works
`# centreon -u admin -p password -o service -a add -v "test3;Ping;Base-Ping-LAN-custom"`
`# centreon -u admin -p password -o service -a add -v "test3;Memory;OS-Linux-Memory-SNMP-custom"`
`# centreon -u admin -p password -o service -a add -v "test3;Load;OS-Linux-Load-SNMP-custom"`
`# centreon -u admin -p password -o service -a add -v "test3;Swap;OS-Linux-Swap-SNMP-custom"`
`# centreon -u admin -p password -o service -a add -v "test3;Cpu;OS-Linux-Cpu-SNMP-custom"`
`# centreon -u admin -p password -o host -a applytpl -v test3`

Note: with version 2.8.20, it's works ;)

**Comment by lpinsivy** [comment]
Corrected with Centreon web 2.8.22
