### ISSUE TITLE
User Permission

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#6213]
**Centreon Web version**: 2.8.19

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: 2.6.32-696.20.1.el6.x86_64

**1° Issue** - API User can edit configuration even though its ACL Menu is set to read only

> Is it possible to create an API read-only user?

**2° Issue** - read-write users can only manage users from their own ACL group

**Steps to reproduce the issue:**
1. With a non-admin user, import another LDAP user
2. Place recent imported user in a different ACL group
3. Once this user is placed in another ACL group, it cant be visualized by its creator

**Describe the results you received:**
users imported by LDAP form can only be managed by admin 

**Describe the results you expected:**
My configuration team should have the rights to edit users from all ACL groups

**Comment by lpinsivy** [comment]
Since Centreon web 2.8.22 we separated real time and configuration access.

Yes the access to API configuration is oly with admin rights due to old design of this one.

**Comment by kozfelipe** [comment]
@lpinsivy I get the answer for the first issue, but I still dont understand why users with configuration access can't manage other non-admin users (2° issue).

**Comment by lpinsivy** [comment]
"Reach API Configuration" & "Reach API Realtime" is only for Rest API (as explained) in help.

CLAPI is only for admin account (old implementation).

**Comment by kozfelipe** [comment]
@lpinsivy I get the API answer (1° issue). My concern is about the second issue.
