### ISSUE TITLE
Contact group inheritance not working if set additional contactgroup for host

### ISSUE THREAD

**Issue by interstar001** [centreon/centreon#6214]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.21
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.14
**OS**: centreon-3.4.6.el6.x86_64 and SLES11SP4

**Additional environment details (VirtualBox, Hyper-V):**

**Steps to reproduce the issue:**
1. Create contacts test1, test2, test3
2. Create contactgroup ngroup1 and add contact test1 
3. Create contactgroup ngroup2 and add contact test2
4. Create contactgroup ngroup3 and add contact test3
5. Create host template template1 and add ngroup1
6. Create host template template2 and add ngroup2 and template1
7. Create host1 and add template2
8. Apply configuration and force a notification event for host1 --> test1 and test2 are notified
9. Add ngroup3 to host1 and set "Contact additive inheriatance"
10. Apply configuration and force a notification event for host1 --> only test3 where notified

**Describe the results you received:**
In Monitoring --> Status Details --> Host --> Host informations --> Notifications all Contact Groups wrere displayed
Contact_groups in host.cfg is set correct to +ngroup3
The contact_group values in hostTemplates.cfg are correct set
Set from "Contact additive inheriatance" in the Templates has not a effect, only Contacts from ngroup3 where notified.

**Additional information you think important (e.g. issue happens only occasionally):**
In centreon 2.7.x whith centreon-engine 1.5.1 this Notification has worked fine.

**Comment by anthoc** [comment]
Same problem for me : https://github.com/centreon/centreon/issues/6177

**Comment by lpinsivy** [comment]
duplicate
