### ISSUE TITLE
[2.8.22] CLAPI export uses resource macro name instead of id for setparam

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#6221]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.22

**Steps to reproduce the issue:**
1. Use CLAPI export option

**Describe the results you received:**
Setparam action for RESOURCECFG object uses macro name.

**Describe the results you expected:**
Setparam action for RESOURCECFG object uses macro id.

**Comment by chgautier** [comment]
Fix OK on PR #6222. Upon using the CLAPI export option, the RESOURCECFG setparam option uses the object's macro id instead of its macro name.
