### ISSUE TITLE
[2.8.22] CLAPI export uses contact name instead of alias in ACL group setcontact actions

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#6223]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.22

**Steps to reproduce the issue:**
1. Use CLAPI export option
2. Import configuration in fresh install

**Describe the results you received:**
"Object not found" errors appear when setting contacts to ACL groups

**Describe the results you expected:**
No errors

**Additional information you think important (e.g. issue happens only occasionally):**
CLAPI export uses contact name instead of alias in ACL group setcontact actions

**Comment by chgautier** [comment]
Fix OK on PR#6224. Upon importing the config file on a freshly installed Centreon, no errors occur concerning ACL contact groups.
