### ISSUE TITLE
Centcore is connecting to local db whereas it's configured with distance database server.

### ISSUE THREAD

**Issue by kbeaugrand** [centreon/centreon#6227]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: centos 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on docker 

**Steps to reproduce the issue:**
1. Start a database on a second machine
2. Start the configuration of centreon using web interface
3. Finish the centreon's configuration

**Describe the results you received:**
Unable to get centreon instance working properly.
The web interface is looping on upgrade...
Centreon core's logs containing this: 
_2018-04-22 17:25:16 - MySQL error : cannot connect to database centreon: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:266)
2018-04-22 17:25:16 - Error when getting server properties_

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**
Always

**Comment by kbeaugrand** [comment]
I'm also experimenting an issue when the database is set up on the same docker container. 

Centcore tells that cannot log in mysql db using centreon username and a password that's well configured in conf.pm

Regards,

**Comment by lpinsivy** [comment]
If you use external database, please configure /etc/centreon/conf.pm and restart centcore process.

**Comment by kbeaugrand** [comment]
Hi, 
Thank for have take time to awnser me.

As I said conf.pm is well configured....

**Comment by lpinsivy** [comment]
Can you copy the content of /etc/centreon/conf.pm and /etc/centreon/centreontrapd.pm (if it exists)?

**Comment by kbeaugrand** [comment]
Hi, 

Sorry I made a mistake, the file was well configured and I'd errors but time didn't match. 
Sorry for that.

Regards,
