### ISSUE TITLE
Latency problems on pollers

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#6236]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.19

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* Central: KVM
* 1 Poller: VMWare
* 2 Pollers physical hardware

**Describe the results you received:**
We have 1 Central (with MariaDB 10.1)  and 3 pollers.
Central: 584 Hosts, 4151 Services
Poller 3: 548 Hosts, 5889 Services
Poller 1: 188 Hosts, 1962 Services
Poller 2: 136 Hosts, 848 Services
For 98% of all checks we use centreon plugins 20180409.

On Centreal and Poller 3 we have very high service latency times around 200 seconds and also more. The CPU on Central and Poller is around 20%, but load is between 5 and 7. Diskio is not high.

No matter why we have this problems. Any ideas?

Regards,
Jochen

**Comment by lpinsivy** [comment]
You can try to run this SQL request to determine with commands use execution time:

```
SELECT h.name, s.description, s.execution_time, s.command_line 
FROM hosts AS h, instances AS i, services AS s 
WHERE h.host_id = s.host_id 
AND h.instance_id = i.instance_id 
AND i.name = "Central" 
ORDER BY execution_time DESC LIMIT 10;
```

note: replace "Central" by the name of your instance

**Comment by joschi99** [comment]
Hi @lpinsivy ,
i checked out the commands with most execution time:
![image](https://user-images.githubusercontent.com/6400595/39326703-23d5bab4-4996-11e8-8c94-c643f965269a.png)
The DNS Request is in status "unknown", server is not responding at DNS requests. The other commands are regarding IDRAC & ILO Hardware using Centreon Plugins. Commands are working, but very bad performance.

If i look the top 50, i can see checks for storages, oracle ecc, and 99% are using centreon plugins. Execution time is between 10 seconds and 3 seconds.

**Comment by lpinsivy** [comment]
If you perform  IDRAC & ILO command manually I suppose you will have bad execution time too?
Same for SNMP/SQL requests with Centreon Plugins.

for me the Centreon Plugins are not in question but protocol used and answer time.

**Comment by joschi99** [comment]
Hi @lpinsivy,
i solved the problem. It was a wrong setup on engine configuration. Everything is now working fine and latency is < 0,5 seconds.

Thanks,
Jochen

**Comment by pmpintogil** [comment]
In some cases that problem is for a bad DNS configuration on the server, if you configure a inaccessible DNS y will be have a high latency problems.
