### ISSUE TITLE
If user can access to ACL menu, allow only view ACL's for which this user has access and not all ACL's

### ISSUE THREAD

**Issue by qladriere** [centreon/centreon#6242]
If user can access to ACL menus, the user can see and modify all ACL's (not only the ones for which this user has access)

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: Redhat 6.9

**Steps to reproduce the issue:**
1. Create specific ACL for a user
2. Provide access to ACL menu's
3. User can modify also ACL's linked to other users

**Describe the results you received:**
The user which has access to ACL menus can access to all ACL's, not only the ones attached to him

**Describe the results you expected:**
User can only access to ACL's which are linked to his profile

**Comment by lpinsivy** [comment]
Sorry but this is not the definite operation. If a user can access to a 'Administration' menu in write mode, he can modify all items of this menu.
