### ISSUE TITLE
If poller is disabled, hosts monitored by this poller are still displayed in the monitoring.

### ISSUE THREAD

**Issue by qladriere** [centreon/centreon#6244]
If poller is disabled, hosts monitored by this poller are still displayed in the monitoring. The 'last check" value is set to the moment where you disabled the poller but the hosts & services are still there.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: Redhat 6.9

**Steps to reproduce the issue:**
1. In Config/poller, disable a poller
2. In Monitoring/status details, hosts monitored by this poller are still there

**Describe the results you received:**
When a poller is disabled, hosts monitored by this poller are still there

**Describe the results you expected:**
Remove from monitoring hosts which are monitored by a poller which is disabled. 

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
When you disable a poller, this one is still running or you stop also the centengine process too?

**Comment by qladriere** [comment]
Hello,

I've just disabled it. Centengine, cbd,... are still running.

**Comment by lpinsivy** [comment]
You need to stop all services of the poller too
