### ISSUE TITLE
Allow user to export the "realtime" monitoring status (Monitoring/Status details) via web interface

### ISSUE THREAD

**Issue by qladriere** [centreon/centreon#6245]
Make the possibility to export the realtime monitoring status (Monitoring/Status details) via web interface. In "reporting"/'dashboard", you have the possibility to export in CSV. Here the idea should be to allow a user to export what he can see in "Monitoring"/"Status details" to Excel sheet, for example. --> in the aim to send a report of current state, for example.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: Redhat 6.9

**Steps to reproduce the issue:**
1. Navigate to Monitoring/Status details. There you are not able to export to Excel, for example, what you can see on the screen (current hosts/services states).

**Describe the results you received:**
Not able to export to Excel, for example, the current services/hosts states

**Describe the results you expected:**
Be able to export to Excel, for example, the current services/hosts states

**Comment by lpinsivy** [comment]
Hi,

You can export in CSV the status of hosts and services using the associated widget.

Regards,

**Comment by qladriere** [comment]
Hello,
Thanks for the info. I'll install the appropriate widget.
