### ISSUE TITLE
Centreon Rest API only usable by an admin user

### ISSUE THREAD

**Issue by qladriere** [centreon/centreon#6246]
Centreon Rest API only usable by an admin user. For me it's a security breach. Should be better if also linked to ACL (can allow access only on "export config part", for example --> which is useful for HA infrastructure as I want to automate : as soon as you switch from one server to the other, need to export again the config in the aim to be sure that files in /etc/centreon-engine & /etc/centreon-broker are up-to-date.)

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: Redhat 6.9

**Steps to reproduce the issue:**
1. Create a user who can reach API but who is not defined as admin
2. Try to use /usr/share/centreon/bin/centreon command

**Describe the results you received:**
Centreon CLAPI is for admin users only.

**Describe the results you expected:**
Can be used by other type of users based on ACL

**Comment by lpinsivy** [comment]
Recently we have separated the access to the real-time part and the configuration part for the REST APIs in Centreon Web 2.8.22.

Unfortunately, the design of configuration API doesn't use ACL profil. So all user will access to configuration API will be "administrator" of the configuration.
But for real time REST API, we use ACL.

**Comment by lpinsivy** [comment]
We plain to write a v2 API using full get/set param with ACL.
