### ISSUE TITLE
Problems installing Centreon Web with nagios/ndoutils

### ISSUE THREAD

**Issue by AnthonyPiva** [centreon/centreon#6247]
Hi, im trying to install nagios w/ ndoutils, cause i tried with centreon-engine/broker, and i got so many erros, so, i tried to install with nagios.

Im a newbie at this, so, i apologize for everything from now on.

Centreon Web version: 2.8.21

OS: Debian 8 

Additional environment details (AWS, VirtualBox, physical, etc.):  Docker Container

Steps to reproduce the issue:
1. Download centreon and decompressed it
2. Run ./install.sh -i
3. Run web installation

I got these notices below after open step 1 in web installation:
[Wed Apr 25 14:48:20.726866 2018] [:error] [pid 8263] [client ::1:44896] PHP Notice:  Undefined index: centreon_engine_lib in /usr/local/centreon/www/install/steps/functions.php on line 243, referer: http://localhost/centreon/install/setup.php
[Wed Apr 25 14:48:20.726901 2018] [:error] [pid 8263] [client ::1:44896] PHP Notice:  Undefined index: centreonbroker_cbmod in /usr/local/centreon/www/install/steps/functions.php on line 244, referer: http://localhost/centreon/install/setup.php

And, at the web interface, i got this in steps 3 and 4
![screenshot_20180425_131642](https://user-images.githubusercontent.com/20929700/39258785-358a0dfc-488b-11e8-8ae3-955638f3e2a1.png)
![screenshot_20180425_131816](https://user-images.githubusercontent.com/20929700/39258786-35ac8166-488b-11e8-95d5-80fea8085cb5.png)

Asking for me for:

Centreon Engine Library (*.so) directory, but, when i used nagios, i didnt find any .so lib file on step 3

And:

Centreon Broker module (cbmod.so), but, didnt find any too.

I read some articles bout some older versions, and in these, centreon web were supposed to ask u some of nagios paths, and ndoutils binary
![image](https://user-images.githubusercontent.com/20929700/39259183-25431514-488c-11e8-95eb-d3b386bd55db.png)
![image](https://user-images.githubusercontent.com/20929700/39259188-2b1c34d4-488c-11e8-8280-29087b4e0783.png)

And, after steps 3 and 4, i got other 2 notices, with centreon-engine or nagios, it doesnt matter, i always got these 2 notices below:

[Wed Apr 25 16:21:23.538635 2018] [:error] [pid 8262] [client ::1:45702] PHP Notice:  Undefined index: MONITORING_ENGINE in /usr/local/centreon/www/install/steps/process/process_step3.php on line 39, referer: http://localhost/centreon/install/setup.php
[Wed Apr 25 16:26:05.889051 2018] [:error] [pid 8266] [client ::1:45828] PHP Notice:  Undefined index: BROKER_MODULE in /usr/local/centreon/www/install/steps/process/process_step4.php on line 39, referer: http://localhost/centreon/install/setup.php

Any help would be appreciated

**Comment by lpinsivy** [comment]
Hi,

Since Centreon Web 2.7.0, their is no more compatibility with Nagios/NDOutil.
Moreover, Centreon doesn't support officially docker containers.
Finally, Centreon web doesn't support yet PHP 7.x

Have a look to [official documentation](https://documentation.centreon.com/docs/centreon/en/2.8.x/installation/index.html) to install Centreon.
