### ISSUE TITLE
[Widget] New widget, show only a big metric

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#6248]
Hello,

A nice widget, i would like to have in Centreon. A widget to show a big metric as we can see in this screenshot :

https://grafana.com/blog/assets/img/blog/v3.0/zabbix_app.png

**Comment by lpinsivy** [comment]
Hi @BenoitPoulet what is the difference with #6249?

**Comment by BenoitPoulet** [comment]
HI,
#6249 was a general request to be able to build dashboard with different number of columns for each row.

**Comment by lpinsivy** [comment]
impossible with actual system of dashboarding
