### ISSUE TITLE
New Feature: Centreon Web UI Docker

### ISSUE THREAD

**Issue by lgcosta** [centreon/centreon#6272]
Hi,

I created a repository for implementing the Centreon web interface in Docker. I already use it in production and am making it available for future implementations and assist in documenting the deployment of a Centreon environment in Docker.

I already have a version of docker for the engine, however, i'm updating it for Centos 7 and soon i'll be publishing as well.

I hope it helps someone.

Any questions please contact us.

Github source

https://github.com/lgcosta/docker-centreon-web

Thanks !

Luiz Gustavo Costa

**Comment by lpinsivy** [comment]
Thank you for your participation

**Comment by lgcosta** [comment]
To better help deploy the docker environment, i created an automatic build of the code in the docker hub, it follows the address:

https://hub.docker.com/r/gugabsd/docker-centreon-web/

Thanks !

**Comment by cgagnaire** [comment]
Thanks @lgcosta,
I'm closing this ticket as we are working closer together on those subjects.
