### ISSUE TITLE
read-write users can only manage users from their own ACL group

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#6278]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.19

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: 2.6.32-696.20.1.el6.x86_64

read-write users can only manage users from their own ACL group

**Steps to reproduce the issue:**
1. With a non-admin user, import another LDAP user
2. Place recent imported user in a different ACL group
3. Once this user is placed in another ACL group, it cant be visualized by its creator

**Describe the results you received:**
users imported by LDAP form can only be managed by admin 

**Describe the results you expected:**
My configuration team should have the rights to edit users from all ACL groups

**Comment by lpinsivy** [comment]
Hi @kozfelipe 

This looks like a case of service providers and you have to define "administrator" for each customer, right?

We keep this in mind for future development.

Regards,

**Comment by kozfelipe** [comment]
great, thanks
