### ISSUE TITLE
Plugin_Riverbed=>	Unknown option: warning-wan2lan-lan at /usr/lib/centreon/plugins/centreon_riverbed-steelhead.pl line 142.

### ISSUE THREAD

**Issue by CedricTnr** [centreon/centreon#6279]
Hi,

Since i updated my riverbed plugin (version 3.0.13)  i have these issues:

Bandwidth-Optimization=> Unknown option: warning-wan2lan-lan at /usr/lib/centreon/plugins/centreon_riverbed-steelhead.pl line 142.

Bandwidth-Passthrough => Unknown option: warning-traffic-in at /usr/lib/centreon/plugins/centreon_riverbed-steelhead.pl line 142.

Load-Average => Unknown option: warning-average at /usr/lib/centreon/plugins/centreon_riverbed-steelhead.pl line 142.

I checked my old configuation and i noticed some modifications about command lines used. In the centreon_riverbed-steelhead.pl file there is nothing about these new missing arguments. 

I have a centreon 2.8.22 uptodate.

Someone can help me? I would fix this issue.

Thx

**Comment by Sims24** [comment]
Hi @CedricTnr did you also upgrade centreon-plugin package on all pollers ? 

Thanks

**Comment by CedricTnr** [comment]
Hi @Sims24,

Yes i updated the poller
"Le paquet centreon-plugin-Network-Riverbed-Steelhead-Snmp-20171208-1.el6.noarch est déjà installé dans sa dernière version" => ....already installed in the last version.

**Comment by Sims24** [comment]
@CedricTnr please test with attached rpm and give us your feedback. 
[rpm.zip](https://github.com/centreon/centreon/files/2001420/rpm.zip)

**Comment by CedricTnr** [comment]
@Sims24 same results.

**Comment by Sims24** [comment]
Looks like a repo issue. Please use this command that should fix verything : 

`yum install http://yum-1.centreon.com/standard/3.4/el7/stable/noarch/RPMS/centreon-plugin-Network-Riverbed-Steelhead-Snmp-20180427-1.el7.noarch.rpm`

Thanks

**Comment by CedricTnr** [comment]
Hi @Sims24 !

Thank you a lot,  it works like a charm now. 

Have a nice day
