### ISSUE TITLE
autocomplete off for MACRO PASSWORD

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#6283]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create an host macro which is a password macro
2. Modify the macro
3. Save
4. Click on the host

**Describe the results you received:**
Google Chrome do auto completion with my password to access to Centreon

**Describe the results you expected:**
Is it possible to add autocomplete="no" into macro's form ?

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by jaltmeyer** [comment]
Hi,

It seems that are some autocomplete="off" in the code, but this keyword is not allowed in the HTML spec : https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete
_(i.e. the "on" and "off" keywords are not allowed)_

So, IMHO, it's not an enhancement but a bug. Not severe when it's a search field, but can be serious on others fields.

Regards,
