### ISSUE TITLE
Localhost Poller not running

### ISSUE THREAD

**Issue by GFui** [centreon/centreon#6286]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: RedHat Linux 7.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It's a machine without internet connection so I installed all by source

**Steps to reproduce the issue:**
1. service cbd status -> Centreon Broker watchdog is running.
2. service centengine status -> running OK
3. service centcore status -> running OK

**Describe the results you received:**
So It seems all OK but centreon show poller not running...and I don't understand why

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by mlaurense** [comment]
I'm experiencing the exact same problem as @GFui . Clean install of CentOS 7.5.1804, and followed the guide for package installation (https://documentation.centreon.com/docs/centreon/en/latest/installation/from_packages.html). All services are running fine, but Configuration > Pollers shows Running as 'NO'.

I've done the above three times now, each time starting with a fresh CentOS installation. This is no coincidence or user error.

I'm guessing there is some setting missing from the installation guide...

**Comment by GFui** [comment]
I'm thinking that installing by source is a mistake because It don't get a good configuration, but I have no more options...

**Comment by mlaurense** [comment]
Managed to get it to work by executing this step, which is listed under 'installing a poller':
```
$ su - centreon
$ ssh-keygen -t rsa
```
And then rebooted the server. The poller now shows up as 'Running: Yes'.
