### ISSUE TITLE
LDAP special characters don't works

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#6288]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.15
**Centreon Engine version**: 
1.8.1

**Steps to reproduce the issue:**
1. Users ldap login with special characters
2. They can't login
3. Special characters => $ß)=?

**Describe the results you received:**
They can't login

**Describe the results you expected:**
They can login

**Comment by lpinsivy** [comment]
@Jordan91 

What kind of LDAP is used?
With version on protocol?

**Comment by bmareau** [comment]
Hi,

Same problem in **Centreon 2.8.23** with accent : **é è à**
LDAP Version: 6.3.9600.16384
Windows 2012 Server R2 Standard

Regards

**Comment by Jordan91** [comment]
Hi,

Same issue with other caracter => _

**Comment by lpinsivy** [comment]
@bmareau @Jordan91 LDAP protocol 2 or 3 in Centreon web configuration?

**Comment by bmareau** [comment]
@lpinsivy : LDAP V3

**Comment by chkirt** [comment]
Same issue with ë caracter
LDAP v2
Windows Active Directory 2012

**Comment by adr-mo** [comment]
Hi @chkirt 

The LDAP v2 does not correctly support special characters.

Closing this ticket.

Regards,
