### ISSUE TITLE
Yum update didn't finish with the upgrade via Centreon web interface

### ISSUE THREAD

**Issue by severinsimko** [centreon/centreon#6292]
Hi,

we wanted to update the Centreon from 2.8.9. to the newest 2.8.22 version, we run the yum update centreon, according to the https://documentation.centreon.com/docs/centreon/en/2.8.x/upgrade/from_packages.html . What happened is that it updated all the packages but when we wanted to finish the update via Centreon Web Interface then we didn't get the update page. We restarted the centreon services ( centcore,centengine, cbd), httpd and mysql, but to no avail. 

We realized that the update didn't create any install bundle in the /usr/share/centreon/installDir/ folder as it was in the previous update.

At this moment we are not able to restart the pollers:

Preparing environment... OK
Generating files... NOK (Exception received : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'use_timezone' in 'field list' [file: /usr/share/centreon/www/class/config-generate/engine.class.php] [line: 362] )
Aborted.

I found a similar issue here: https://github.com/centreon/centreon/issues/5295 but it didn't explain what went wrong and how to fix it.

The Centreon is running on CentOS 6.9.

thanks!

**Comment by lpinsivy** [comment]
Hi, I installed a VM with Centreon 2.8.9 and finish installation. Then I upgrade to version 2.8.22 without problem.

Any issue during yum update process?
