### ISSUE TITLE
centreon_windows_snmp memory mode, threshold issue with "free" mode

### ISSUE THREAD

**Issue by kykyo** [centreon/centreon#6300]
Hi, when i check with this command 
/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname ****** --snmp-community ******* --warning-memory=12 --free

result = WARNING: RAM Total: 159.96GB Used: 140.22GB (87.66%) Free: 19.74GB (12.34%) | 'free'=21196111872B;0:20610117795;;0;171750981632

with /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname ***** --snmp-community *****--warning-memory=13 --free

result = OK: RAM Total: 159.96GB Used: 140.22GB (87.66%) Free: 19.74GB (12.34%) | 'free'=21196111872B;0:22327627612;;0;171750981632

if i have less than 13% free memory, i have no warning and if i have more than 12% free memory i have a warning. (I checked with other threshold value, 5, 10, 15 etc.... and same result, i tested the absolute mode and same result again )
the threschold comparison should be inverted.

I checked the file, my temporary solution is create a threshold_check_free function with operand inverted and use it if i use the free option.

**Comment by lpinsivy** [comment]
@kykyo can you create your issue on the [Centreon Plugins github](https://github.com/centreon/centreon-plugins/issues) please.

**Comment by kykyo** [comment]
ok sorry. i'll do that tomorrow and i'll explain what i have done in detail (@Sims24, i have already test different things and it can't work, but my modification works).
