### ISSUE TITLE
Influxdb without authentication

### ISSUE THREAD

**Issue by solune** [centreon/centreon#6304]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22-1

**Centreon Engine version**: 1.8.1-1

**Centreon Broker version**: centreon-broker-influxdb-3.0.14-1

**OS**: Centos 7.5

How configure centreon-broker-influxdb to connect to influxdb without authentication (authentication disabled in influxdb) ?
user and password are mandatory : 
[1527256634] error:   influxdb: no 'db_user' defined for endpoint 'central-broker-master-influxdb'

**Comment by lpinsivy** [comment]
@solune you should use [Centreon Stream Connectors](https://documentation.centreon.com/docs/centreon/en/2.8.x/developer/writestreamconnector.html)
