### ISSUE TITLE
service flapping between previous and current configuration

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#6306]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: 2.6.32-696.23.1.el6.x86_64

This is one of many cases

**Steps to reproduce the issue:**
1. edit service's argument
2. apply to poller

**Describe the results you received:**
service monitoring is flapping between previous and current configuration

**Describe the results you expected:**
previous command  argument should be forgotten

**Additional information you think important (e.g. issue happens only occasionally):**

![image](https://user-images.githubusercontent.com/25208457/40563016-a53ff754-6039-11e8-8112-10689121a3b1.png)

![image](https://user-images.githubusercontent.com/25208457/40563214-60acfd34-603a-11e8-9b04-c2b3edc120f4.png)

![image](https://user-images.githubusercontent.com/25208457/40563177-41971c72-603a-11e8-81cc-af577a7aec73.png)

![image](https://user-images.githubusercontent.com/25208457/40563236-7b6c401c-603a-11e8-9595-73ceb73aee6a.png)

![image](https://user-images.githubusercontent.com/25208457/40563367-de48d20e-603a-11e8-83ad-dd50a039b565.png)

**Comment by lpinsivy** [comment]
Don't you have 2 centengine process running in the same time?

**Comment by kozfelipe** [comment]
![image](https://user-images.githubusercontent.com/25208457/40665842-acccce22-6334-11e8-8a1b-e19d595170fa.png)
