### ISSUE TITLE
The Chinese field cannot be written to the configuration file when configuring email alert information

### ISSUE THREAD

**Issue by zheddiewen** [centreon/centreon#6308]
- /usr/local/bin/swaks -f aa@bb.com -t $CONTACTEMAIL$ -s mail.aa.com --header "Subject: ** $NOTIFICATIONTYPE$ HostAlert: $HOSTNAME$ is $HOSTSTATE$ **" -au robot -ap 2018  --body "Monitor\n\n AlertType: $NOTIFICATIONTYPE$\n HostName: $HOSTNAME$\n State: $HOSTSTATE$\n IPAddr: $HOSTADDRESS$\n Additional Info: $HOSTOUTPUT$\n Date/Time: $LONGDATETIME$\n"
- For example When I replace AlertType or HostName with Chinese ,  I  export configuration ,can not write to the configure file. display nothing in the configure file
- Thanks for HELP
- eddie

**Comment by lpinsivy** [comment]
Can you respect issue template please

**Comment by zheddiewen** [comment]
Sorry! 
I will pay attention later

**Comment by zheddiewen** [comment]
- OS: CentOS 7.4
- Centreon Web version: 2.8.21
- Centreon Engine version: 1.8.1
- I replace AlertType or HostName with Chinese , I export configuration ,can not write to the configure file. display nothing in the configure file
- THX for help

**Comment by lpinsivy** [comment]
I change one of my hostname to "我的服务器"

I export configuration and I can find it:

```
define host {
    host_name                      我的服务器
    alias                          我的服务器
    address                        127.0.0.1
    register                       1
    use                            OS-Windows-NSClient-05-NRPE-custom
    _HOST_ID                       314
}
```

I don't understand your issue. Can you add some print screen and all steps to reproduce?
Which locale do you use on your Centreon server?

**Comment by zheddiewen** [comment]
Wa!! Great ! you know chinese.
- I configure email alert 
 
![cen3](https://user-images.githubusercontent.com/30824531/41754771-6ba47578-7606-11e8-9d38-4715089e72c9.png)
When i exec  Configuration Files Export, i get below
![cen4](https://user-images.githubusercontent.com/30824531/41754812-ac1d0728-7606-11e8-9f84-00dae0641327.png)
But when i change the word to chinese i get like
![cen1](https://user-images.githubusercontent.com/30824531/41754842-cffbcada-7606-11e8-87b3-b2003e55be96.png)
![cen2](https://user-images.githubusercontent.com/30824531/41754849-db4719a8-7606-11e8-9f75-57629eafdba9.png)

Hope i express clearly 
i believe it's unicode problem

**Comment by zheddiewen** [comment]
Anyone can help me?

**Comment by zheddiewen** [comment]
- Anyone can help me?

**Comment by zheddiewen** [comment]
the same issue  https://github.com/centreon/centreon/issues/6449
