### ISSUE TITLE
Service description removes parentheses when adding from API

### ISSUE THREAD

**Issue by braun1928** [centreon/centreon#6310]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: CentOS 7 (from Centreon ISO)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM on VMware 6.5

**Steps to reproduce the issue:**
Run CLAPI or REST API to add a service using parentheses, e.g.:
`# centreon -u admin -p password -o service -a add -v 'centreon;Traffic: Intel(R) 82574L Gigabit Network Connection;generic-active-service'`

**Describe the results you received:**
The parentheses are removed from the description.

**Describe the results you expected:**
They should be kept.

**Additional information you think important (e.g. issue happens only occasionally):**
This is an inconsistency with the web UI -- you can add a service description with parentheses normally -- and with the check_parameter_arguments, that accepts parentheses correctly for its value using CLAPI.

I tried escaping the parentheses in all possible forms, thinking it could be a problem with bash expansion (single quotes, double quotes, backslashes, etc.), but it wasn't the issue. The same behavior exists when using REST, so it must be in the shared API code.

**Comment by lpinsivy** [comment]
@braun1928 the web interface use the same:

Traffic: Intel(R) 82574L Gigabit Network Connection => Traffic: IntelR 82574L Gigabit Network Connection

This is due to Centreon Engine default configuration and "Illegal Object Name Characters" setting: ~!$%^&*"|'<>?,()= in "Configuration  >  Pollers  >  Engine configuration" menu on "Admin tab".
