### ISSUE TITLE
HTML code instead of accented characters in graphs

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#6318]
Centreon version 2.8.22
Centreon Engine 1.8.1
Centreon Broker 3.0.14

service graphs show HTML source (e.g. `&Eacute;` `&aacute;`) instead of accented characters (e.g. É, á).
When clicking on the export image icon the correct accented characters are put in the image.

**Comment by lpinsivy** [comment]
corrected by PR #7676 

![Sans titre](https://user-images.githubusercontent.com/3351916/61942286-658b5d00-af99-11e9-8aaa-254b0652c54e.png)
