### ISSUE TITLE
Datestamps don't respect Timezone/Location setting

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#6329]
Centreon version 2.8.22
Centreon Engine 1.8.1
Centreon Broker 3.0.14

For each user datestamps in monitoring view, setting downtime etc. should respect the Timezone/Location setting for that user, e.g. Europe/Somecapital would be "2018-05-29" but under monitoring and downtime start/end dates appear as "2018/05/29", while during setting a downtime they appear in the Start Time/End Time fields as "05/29/2018"

**Comment by lpinsivy** [comment]
linked to #6154, for next version

Regards,
