### ISSUE TITLE
Enhancement on host CLAPI getinstance method

### ISSUE THREAD

**Issue by gbloquel** [centreon/centreon#6334]
As mentioned in the documentation to remove a host you need to generate configuration file and reload the poller
see [host delete](https://documentation.centreon.com/docs/centreon/en/2.8.x/api/clapi/objects/hosts.html#del) 

With host methods clapi or REST API there is a way to update the poller (`setinstance`) but no method to get poller (getinstance)

When I decided to remove a host I does not know the poller then  I need to :

1. get all pollers
1. Iterate on each poller
1.  and get all hosts on poller
1. check if the host is available on this poller
1. and if true then  I find this poller

All these operations are ineffecient but works.

Have you planned to implement the `getinstance` method ?

Best regards

**Comment by richardlawley** [comment]
I submitted this in PR #6230
