### ISSUE TITLE
Centreon + HTTP2 = Chrome does not render Ajax request

### ISSUE THREAD

**Issue by olivier-monaco** [centreon/centreon#6337]
How to reproduce:
- Install Centreon with Apache
- Install Nginx as a reverse proxy to access Centreon with HTTP2 enabled
- Open Centreon in Google Chrome

Problem: all Ajax loaded zone are not rendered (eg. service problem list empty) on Chrome but all works fine on Firefox.

Problem comes from: https://github.com/centreon/centreon/blob/e7032cb919caf9ae5521021727c7d6176899e10d/www/include/common/javascript/xslt.js#L263

The `xsltRequest.statusText` is an empty string. Remove `xsltRequest.statusText == "OK"` and it works again.

**Comment by rmceoin** [comment]
I'm getting this issue when Centreon is running as an instance on Google Cloud Platform behind a Google Load Balancer with HTTPS/2.

Indeed the solution was to remove `xsltRequest.statusText == "OK"`.  

There's already `xsltRequest.status == 200` so isn't the check for statusText redundant?  I've confirmed that status does equal 200 even when the statusText is empty.

Looking around it seems that HTTPS/2 may not provide the text that ends up in statusText and that some browsers emulate the older HTTP protocols. 

https://stackoverflow.com/questions/41632077/why-is-the-statustext-of-my-xhr-empty

> HTTP/2 does not define a way to carry the version or reason phrase that is included in an HTTP/1.1 status line.

**Comment by conradoqg** [comment]
Same here, Centreon behind caddy proxy. Removed that part and it worked.

**Comment by ADN182** [comment]
+1 Thank guy for the fix ! I use a synology as a reverse proxy and now it's works !

**Comment by BenoitPoulet** [comment]
For tracking and for other people, bug still present in 19.04.5 , and Apache HTTP/2

**Comment by mat44444** [comment]
Thank for the patch that solve the issue we have when people acces with Chrome under a reverse proxy NGINX in https

**Comment by cgagnaire** [comment]
Fixed for 19.10.x and 20.04.x series.
