### ISSUE TITLE
Not able to acknowledge when host_name contains '/' or ':'

### ISSUE THREAD

**Issue by omercier** [centreon/centreon#6339]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: CentOS6 and 7

**Steps to reproduce the issue:**
1. create a host named 'http://test' (or any name containing / or : ) and add at least one service that will result in a non ok state + generate + apply configuration
2. once the service is in a non ok state, try to acknowledge it

**Describe the results you received:**
nothing happens and the following line appears in centcore.log: 

> Ip address not defined for poller 0

**Describe the results you expected:**
I expected the service to be acknowledged.

**Comment by Moujimouja** [comment]
Hi,

Thanks for your feedback.

I can't reproduce it on 19.10.x nor 20.04.x so I close this issue.

Have a nice evening
