### ISSUE TITLE
[2.8.23] Invalid accentuated chars transcription in timeperiod exception models

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6359]
Hi,
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.23

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. create a new timeperiod with accentuates chars like "jours fériés"
2. open the dropdown list of timeperiod exception models
3. see invalid chars

**Describe the results you received:**
![centreon_timeperiod](https://user-images.githubusercontent.com/8720203/41126437-c9c4069c-6aa7-11e8-8584-2c5307aed4aa.png)

and in bonus this one :)

![centreon_formulaire](https://user-images.githubusercontent.com/8720203/41126968-96d98494-6aa9-11e8-9bda-2a7ca4d9135b.png)

**Describe the results you expected:**
Have a timeperiod properly labeled

thanks

**Comment by cmeschin** [comment]
Hi,
the accentuates chars are solved in 20.10.
But the typo bonus is still present :)
![image](https://user-images.githubusercontent.com/8720203/113865324-3daf4d80-97ac-11eb-8904-c371714ebb37.png)

You can close it if you consider is done.
Kind regards

**Comment by lpinsivy** [comment]
Hi @cmeschin will be fixed by https://github.com/centreon/centreon/pull/9732

Regards,
