### ISSUE TITLE
No notifications from metaservices

### ISSUE THREAD

**Issue by FlorentinC** [centreon/centreon#6371]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.23

**OS**: 
CentOS7

**Steps to reproduce the issue:**
1. Create a metaservice
2. Change the tresholds to have a CRITICAL or WARNING alert

**Describe the results you received:**
I don't receive any mail about this metaservice
Contacts ans contacts groups inforamation is empty in the status page but it's filled 
in /etc/centreon-engine/meta_services.cfg

**Describe the results you expected:**
I want to be alerted like a normal service

**Additional information you think important (e.g. issue happens only occasionally):**
I already tried by to send a blank mail, it doesn't work either

**Comment by lpinsivy** [comment]
I suppose is linked to this bug #5651.

Can you check in database using this SQL request:

`MariaDB [centreon]> select count(service_description) from service where service_description like "Meta_%" group by service_description;`

Regards,

**Comment by FlorentinC** [comment]
It returns 1

**Comment by lpinsivy** [comment]
So you have only one meta service configured?

can you put a print screen of your Meta service configuration page and put the content of the meta_services.cfg file?

**Comment by FlorentinC** [comment]
![image](https://user-images.githubusercontent.com/23255238/41666324-918c7cb6-74aa-11e8-95f9-da3fa43b81d5.png)
Where is meta_service.cfg ?

**Comment by FlorentinC** [comment]
Here is /etc/centreon-engine/meta_services.cfg
`define service {
    service_description            meta_5
    display_name                   Temperature_salle
    host_name                      _Module_Meta
    check_command                  check_meta!5
    max_check_attempts             3
    normal_check_interval          1
    retry_check_interval           1
    active_checks_enabled          1
    check_period                   24x7
    notification_period            24x7
    register                       1
    contact_groups                 Supervisors
    contacts                       Administrator
    _SERVICE_ID                    632
`

**Comment by FlorentinC** [comment]
Result to `SELECT service_id, description, display_name FROM services WHERE description LIKE 'meta_%' ` : 
![image](https://user-images.githubusercontent.com/23255238/41724559-187296fc-756e-11e8-8428-b324f02e204d.png)

**Comment by adr-mo** [comment]
Hi @FlorentinC 

This issue has been fixed in the **18.10.x** versions of Centreon.

Closing the ticket.

Regards,
