### ISSUE TITLE
[clapi] export is too long when lot of parentship

### ISSUE THREAD

**Issue by kduret** [centreon/centreon#6372]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.23

**Steps to reproduce the issue:**
1. Create lot of hosts
2. Create lot of parentship between these hosts
3. Export hosts with clapi

**Describe the results you received:**
Export take too much time and CPU is 100%

**Describe the results you expected:**
Export is faster

**Comment by chgautier** [comment]
Fix OK on PR #6373. Adding numerous hosts and giving each of them parent/child relations does not hinder the export execution time.
