### ISSUE TITLE
[Graph] Only 10 days of data for grah

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon#6374]
Hello there,

My Centreon is running for past a year now, but due to a lack of disk space, I had to lower the retention duration for only 10 days. But now I got more space disk, so I increased data retention like this : 
![image](https://user-images.githubusercontent.com/26572075/41538486-d2e55764-730b-11e8-8ccc-20b4d3a21fb2.png)

I would like to know why with all services, my graph are only displaying 10 days of data, like this : 
![image](https://user-images.githubusercontent.com/26572075/41538584-fb969dd0-730b-11e8-9212-c32dce052111.png)

Did I miss a command to apply the correct retention period ?

**Comment by lpinsivy** [comment]
You need to regenerate all your graphs to apply the new retention value using "Administration  >  Parameters  >  Data" menu.

Regards,
