### ISSUE TITLE
Better management of dependancies  

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#638]
---

Author Name: **Julien Mathis** (Julien Mathis)
Original Redmine Issue: 3972, https://forge.centreon.com/issues/3972
Original Date: 2012-12-03

---

When you have a dependency between service/host on different poller, dependency are not added in configuration files (good thing). Despite, you don't have a message to tell: 'Dependancy "xxx" are skipped because of link between different pollers'.

**Comment by julienmathis** [comment]
No need now. Correlation will do the job.
