### ISSUE TITLE
Change text for NOTIFICATIONTYPE

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#6399]
Hi,

Is t il possible to change text of NOTIFICATIONTYPE macro ?
I would like to replace PROBLEM by INCIDENT
https://documentation.centreon.com/docs/centreon-engine/en/latest/user/configuration/basics/standard_macros.html#notificationtype

Thanks,

**Comment by lpinsivy** [comment]
Hi @romsworld unfortunatly it is not possible because hardcoded into Centreon Engine.

May be notification command can run a script this script change PROBLEM value to INCIDENT before to call regular notification command ?
