### ISSUE TITLE
Plugin Packs Manager has lost all icons after update

### ISSUE THREAD

**Issue by casnaveu** [centreon/centreon#6407]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:   

**Centreon Engine version**:    Centreon Engine 1.8.1

**Centreon Broker version**:   3.0.14-1

centreon-broker-debuginfo.x86_64            3.0.14-1.el6                centreon
centreon-broker-devel.x86_64                3.0.14-1.el6                centreon
centreon-broker-graphite.x86_64             3.0.14-1.el6                centreon
centreon-broker-influxdb.x86_64             3.0.14-1.el6                centreon    

**OS**:   CentOS 6.8  (ova)

**Additional environment details (AWS, VirtualBox, physical, etc.):** 

![image](https://user-images.githubusercontent.com/40629303/41969346-6a488f8e-7a07-11e8-9394-84daa4708c2d.png)

**Steps to reproduce the issue:**
1.  UI -> Configuration -> Plugin Packs     ( and nothing there) 
2.
3.

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/40629303/41968481-e36a3fa0-7a04-11e8-90f4-9d3ccd5d4dbe.png)

**Describe the results you expected:**

![image](https://user-images.githubusercontent.com/40629303/41969215-f9418ffc-7a06-11e8-9af0-37881c58c032.png)

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by casnaveu** [comment]
Is anyone there? Some indication on how to proceed?

**Comment by vcegarra** [comment]
Hi, try to clear caché from browser, or login on private mode on Chrome, could be a problem of cache.

**Comment by lpinsivy** [comment]
@casnaveu, @vcegarra yes it look like an issue of cache browser

**Comment by casnaveu** [comment]
You are right, it was an issue of cache browser, thank you

________________________________
De: Laurent Pinsivy <notifications@github.com>
Enviado: miércoles, 22 de agosto de 2018 10:52:44
Para: centreon/centreon
Cc: CASTILLO NAVARRO, Eusebio; Mention
Asunto: Re: [centreon/centreon] Plugin Packs Manager has lost all icons after update (#6407)


@casnaveu<https://github.com/casnaveu>, @vcegarra<https://github.com/vcegarra> yes it look like an issue of cache browser
