### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by GFui** [centreon/centreon#6414]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.22

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: Red Hat 7.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Machines without internet connection
Old installation is one VM different to the new.

Hello guys I'm working on a migration from an old installation of centreon (centreon 2.6.6 + nagios 4.1.1 +ndoutils) and I want to move all the data from the old to the new centreon (web 2.8.22, centreon-engine 1.8.1) 
My question is if there is a way to migrate all the data like hosts, services, commands to the new installation.

Thanks.

**Comment by therikb** [comment]
Hi GFui,

take a look here:
https://github.com/centreon/nagiosToCentreon

**Comment by lpinsivy** [comment]
or you can dump your old centreon database, import into new server, pass all upgrade and change the pollers configuration (Nagios to Centreon Engine Params, NDO to Centreon Broker params)

**Comment by GFui** [comment]
@therikb Hi, thanks for your reply.
When I follow the steps and finally install the script, I run perl nagios_reader_to_centreon_clapi.pl --help and it says "Can't open perl script "nagios_reader_to_centreon_clapi.pl": No such file or directory"

**Comment by GFui** [comment]
@lpinsivy thanks for your reply but, 
I don't understand exactly how to do that...

**Comment by lpinsivy** [comment]
You can dump your 'centreon' database from your old server and import the dump on the new server.
Then perform upgrade with web upgrade interface.
Then configure the scheduler to use Centreon Engine parameters and not Nagios.
Replace NDOtools by Centreon Broker configuration.
