### ISSUE TITLE
version 2.8.24

### ISSUE THREAD

**Issue by thedjinhn** [centreon/centreon#6422]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.24
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 

**OS**: 
centos6
**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware

**Steps to reproduce the issue:**
1. when creating a service and/or editing a service
2. it is impossible to change the name of the host

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by cedrictemple** [comment]
Hi,

I have the same error and i fix the problem by repairing the centreon database :

```
mysqlcheck -e centreon
```

Then, it works properly.
