### ISSUE TITLE
question about cdb

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#6428]
Hi,

Do you know why, each time i restart cdb, cdb need to parse a lot of retention file ?
I don't understand.

Thanks,

![image](https://user-images.githubusercontent.com/12545407/42187591-de678f3a-7e50-11e8-8bba-50fbbcf5fdfc.png)

**Comment by lpinsivy** [comment]
When you restart and not reload CBD, CBD put in retention files memory data.

**Comment by romsworld** [comment]
Yes, but why the data is 2017 !
I don't find retention file on poller. CDB analyse old data, and I don't find the source.

**Comment by romsworld** [comment]
Yes all servers are sync with ntp.

De : Laurent Pinsivy <notifications@github.com>
Envoyé : mercredi 11 juillet 2018 11:28
À : centreon/centreon <centreon@noreply.github.com>
Cc : Nicolas COULIN <nicolas.coulin@kleegroup.com>; Author <author@noreply.github.com>
Objet : Re: [centreon/centreon] question about cdb (#6428)


your servers are synchronized with ntp server?

**Comment by lpinsivy** [comment]
It's really strange because start time is in 2017  too.
What is the result of "date" command on these servers?

**Comment by romsworld** [comment]
[centreon@CENT-002 postfix]$ date
mer. juil. 11 14:18:55 CEST 2018

De : Laurent Pinsivy <notifications@github.com>
Envoyé : mercredi 11 juillet 2018 12:00
À : centreon/centreon <centreon@noreply.github.com>
Cc : Nicolas COULIN <nicolas.coulin@kleegroup.com>; Author <author@noreply.github.com>
Objet : Re: [centreon/centreon] question about cdb (#6428)


It's really strange because start time is in 2017 too.
What is the result of "date" command on these servers?

**Comment by romsworld** [comment]
In fact, probelm occurs when I restart centcore too

**Comment by lpinsivy** [comment]
which are your OS and Centreon versions?

**Comment by romsworld** [comment]
Centos 6.6 and last version of centreon, 2.8.25, but pb occured since 2.8

De : Laurent Pinsivy <notifications@github.com>
Envoyé : lundi 27 août 2018 11:57
À : centreon/centreon <centreon@noreply.github.com>
Cc : Nicolas COULIN <nicolas.coulin@kleegroup.com>; Author <author@noreply.github.com>
Objet : Re: [centreon/centreon] question about cdb (#6428)


which are your OS and Centreon versions?

**Comment by lpinsivy** [comment]
did you perform Centreon Broker upgrade on all pollers?
did you restart cbd on Centreon central server and centengine on all servers?

Regards,

**Comment by romsworld** [comment]
All servers is up to date, and all servers have been reboot.

**Comment by lpinsivy** [comment]
@bouda1 any idea?
