### ISSUE TITLE
LDAP IMPORT

### ISSUE THREAD

**Issue by atlante77** [centreon/centreon#6433]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  Centreon 2.8.24

**Centreon Engine version**: Centreon Engine 1.7.2

**Centreon Broker version**: Centreon Broker 3.0.7

**OS**:  Ubuntu 14.04

**Additional environment details (AWS, VirtualBox, physical, etc.): physical (16core/64Go)

**Steps to reproduce the issue:**
1. Import User from LDAP
2.
3.

**Describe the results you received:**
0 error and 0 import. I have nothing

**Describe the results you expected:**
New user in the list

**Additional information you think important (e.g. issue happens only occasionally):**
root@centreon:~# tail -f /var/log/centreon/ldapsearch.log 
[03/07/2018 16:33]LDAP Connect : trying url : ldap://xxxxxx.xxxxxx.xxx:389/
[03/07/2018 16:33]LDAP Connect : Credentials : CN=SVC_Centreon,OU=Services_Accounts,OU=xxxxxx,DC=xxxxxx,DC=com
[03/07/2018 16:33]LDAP Search : Base DN : dc=xxxxxxxx,dc=com
[03/07/2018 16:33]LDAP Search : Filter : (&(samAccountName=USER)(objectClass=user)(samAccountType=xxxxxxx))
[03/07/2018 16:33]LDAP Search : Size Limit : 60
[03/07/2018 16:33]LDAP Search : Timeout : 60
[03/07/2018 16:33]LDAP Search : Error : Success
[03/07/2018 16:33]LDAP Search : 1 entries found
[03/07/2018 16:33]LDAP Search : 1
[03/07/2018 16:11] LDAP Search : XML Output :

**Comment by lpinsivy** [comment]
Are you sur about your filter?

` (&(samAccountName=USER)(objectClass=user)(samAccountType=xxxxxxx))`

**Comment by atlante77** [comment]
Hello Ipinsuvy,

Yes i'm sure because when i did my search request : Centreon found the user.
in reality, it's like :  (&(samAccountName=USER)(objectClass=1611166...)(samAccountType=xxxxxxx))

regards,

Atlante

**Comment by atlante77** [comment]
I find an error in logs @lpinsivy : 
```
# tail -f /var/log/apache2/error.log
[Tue Jul 10 14:34:39.236422 2018] [:error] [pid 17855] [client 172.17.15.211:51122] PHP Warning:  Illegal string offset 'action' in /usr/share/centreon/www/include/configuration/configObject/contact/ldapImportContact.php on line 129, referer: https://monitoring.xxxxx.com/main.php?p=60301&o=li
```

**Comment by lpinsivy** [comment]
So you can find people using Centreon LDAP import form but not import them?

**Comment by atlante77** [comment]
yes @lpinsivy

**Comment by atlante77** [comment]
Can i have an update ? It's really important Centreon worked fine before my upgrade to the lastest version.

**Comment by atlante77** [comment]
@lpinsivy : how can we proceed ? I must create every user manually and setup ldap information evertytime....
thakns in advance

**Comment by atlante77** [comment]
Someone here ?

**Comment by adr-mo** [comment]
Hi @atlante77,

The **2.8.x** version is now deprecated.

Could you please try to upgrade to the latest versions **18.10.x or 19.04.x** ?

If issue is still there feel free to reopen the ticket.

Regards,
