### ISSUE TITLE
Some Translate word no valid in centreon-web

### ISSUE THREAD

**Issue by zheddiewen** [centreon/centreon#6435]
- **Centreon Web version**:  centreon-web-2.8.24

- **Centreon Engine version**:  centreon-engine-1.8.1-1

- **Centreon Broker version**:  3.0.14

- **OS**:  CentOS 7.5
- I want to translate centreon to chinese.But i find some page can not to translate, For example: in login page. i translate Login: to 用户名:   Password to 密码  Connect to 登陆 but it's no valid
![image](https://user-images.githubusercontent.com/30824531/42253342-f06b53e6-7f73-11e8-8e66-a9757673056c.png)
- some word can not find in message.po 
![image](https://user-images.githubusercontent.com/30824531/42253382-1cfd48b0-7f74-11e8-985c-a1fd8ab58321.png)
- Thanks for reply

**Comment by lpinsivy** [comment]
Hi @zheddiewen,

Did you follow this [procedure](https://www.centreon.com/en/blog/tutorial-how-to-translate-centreon/) to translate Centreon?

Regards,

**Comment by zheddiewen** [comment]
- Hello @lpinsivy 
- Yes I follow this tutorial

**Comment by lpinsivy** [comment]
Can you send me your messages.po file?

**Comment by lpinsivy** [comment]
I found the issue, on tsmarty2centreon.php please change line 50:

`$extensions = array('tpl', 'ihtml');`

to:

`$extensions = array('tpl', 'ihtml', 'html');`

**Comment by zheddiewen** [comment]
- Thank for your help @lpinsivy

**Comment by sbrizini** [comment]
Hi @zheddiewen,

If you wish us to integrate your translation into Centreon, the last section of the [procedure](https://www.centreon.com/en/blog/tutorial-how-to-translate-centreon/) describes how to do it.

We would love to share your translation with he community and assist you if you need any help with that.

Regards,

**Comment by zheddiewen** [comment]
@sbrizini  Thanks, I will share the translation with the community!

**Comment by zheddiewen** [comment]
@sbrizini How can i push translate to the repo https://github.com/centreon/centreon-translations.git? Could you give me privileges? Thanks

**Comment by sbrizini** [comment]
Hi @zheddiewen ,

You can't push your translation into the project. 
You have to clone our project into your own github, add your translation and ask for a pull request from our github.

Here's an excerpt from the [procedure](https://www.centreon.com/en/blog/tutorial-how-to-translate-centreon/):

Participate to Centreon project
Once your translation is up-to-date, you can ask to the Centreon team to add your translation to Centreon project. This will allow for all person using Centreon to have access to your translation on their Centreon platform.

Create an account on GitHub
Fork centreon/centreon project on GitHub
Add your translated *.mo and *.po files to lang/<your_lang>/LC_MESSAGES directory
Commit your change on your project
Create a pull request on centreon/centreon project
We will add your translation to Centreon.

Thank you for your help!

**Comment by zheddiewen** [comment]
@sbrizini I have created a pull request on centreon/centreon project.
