### ISSUE TITLE
moving hosts from central poller to remote poller does not stop polling on central poller 

### ISSUE THREAD

**Issue by lindererik** [centreon/centreon#6463]
Hi
I'm running centreon 2.8.19. I have 1 central poller and 2 distributed pollers. 

when I move a host from the central poller to a distributed poller (and redeploy), the gui is updated and the checks are run on the new poller BUT they still continue to run on the central poller. I tried restarting services on the central poller but no luck as I still see the test being performed.

it could be a problem similar to #4997

any Ideas?

**Comment by lpinsivy** [comment]
Hi,

When you move an object you need to generate both configuration of impacted poller and export them.

**Comment by lindererik** [comment]
apparently after deep analysis, it is due to a DB corruption causing centreon to behave strangely.
