### ISSUE TITLE
Can't export config : Allowed memory size of xxx bytes exhausted

### ISSUE THREAD

**Issue by larkoie** [centreon/centreon#6468]
Hi,

We are facing another "Allowed memory size of xxx bytes exhausted" when reloading our central poller.
I've spent 4 hours on this but could not find the issue, could you please have a look at this? Thanks

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.11

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
920 hosts
9500 services

**Steps to reproduce the issue:**
1.Reload the conf from UI

**Describe the results you received:**
Nothing happens in the UI (progress stays at 0%)
Following error in apache logs : 
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65 bytes) in /usr/share/centreon/www/class/config-generate/generate.class.php on line 88, referer: https://mycentreon.com/centreon/main.php?p=60902&poller=1`

**Describe the results you expected:**
The conf is generated, moved and the poller is restarted

**Additional information you think important (e.g. issue happens only occasionally):**
We did not mass import new hosts or services. The issue occurs every time we try to export the new config but I could not find what's the issue behind this. 
Looking at the file in question (/usr/share/centreon/www/class/config-generate/generate.class.php) it looks like the issue occurs when preparing the following MySQL insert :
`$stmt = $this->backend_instance->db_cs->prepare("INSERT INTO index_data (host_id, service_id, host_name, service_description) VALUES (:host_id, :service_id, :host_name, :service_description) ON DUPLICATE KEY UPDATE host_name=VALUES(host_name), service_description=VALUES(service_description)");`

When using CLAPI it works fine.

Any help appreciated thanks.

**Comment by itsul** [comment]
Raise the memory_limit parameter in your /etc/php.ini to a higher limit. Currently it is set to 16M if I see this right. You can easily try 256M or 512M.

Best regards.

**Comment by larkoie** [comment]
@itsul thanks for the input. 
memory_limit was set to 128M. Raised it to 256M and restarted the whole centreon + httpd services and it works!
Many thanks!
