### ISSUE TITLE
The service Status filter is lost when performing an action on services or when reloading the page

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon#6476]
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.24-1.el7.centos

**Centreon Engine version**: 1.8.1-1.el7.centos

**Centreon Broker version**: 3.0.14-1.el7.centos

**OS**: CentOS 7

**Steps to reproduce the issue:**
1. Open `/centreon/main.php?p=20201&o=svc`
2. Change the `Service Status` filter to `Unhandled problems`
3. Schedule an immediate check of a service or refresh the page

**Describe the results you received:**
The `Unhandled problems` filter is lost.

**Describe the results you expected:**
The `Service Status` filter should not be reset.

**Additional information you think important (e.g. issue happens only occasionally):**
This was not a problem in older versions because the service status was stored in the URL (`o=svc_unhandled`).

**Comment by BenoitPoulet** [comment]
Reported years ago.

Never fixed : #5109

**Comment by sbraz** [comment]
I would say it's slightly different since your issue is related to configuration and mine is related to host/services status.

**Comment by BenoitPoulet** [comment]
Still present in 2.8.25

**Comment by adr-mo** [comment]
Hi @sbraz 

Thanks for the feedback 💯 

This issue will be fixed in the **18.10.5 release**

Regards,
