### ISSUE TITLE
Widget height is too small and not configurable

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon#6480]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Centreon Web version: 2.8.24-1.el7.centos

Centreon Engine version: 1.8.1-1.el7.centos

Centreon Broker version: 3.0.14-1.el7.centos

OS: CentOS 6

**Steps to reproduce the issue:**
* Add a widget which displays a large number of services.

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/4833332/42948310-81a7d3be-8b6f-11e8-9eb0-ac1d6742e5a1.png)
The widget is too small and there is no way to change its height.

**Describe the results you expected:**
The widget height should be configurable or it should fit the window height.

**Comment by lordtaki** [comment]
In the configuration of the widget, increase the number of results.
Please note that you have to wait the widget to resfresh itself once (do not refresh yourself, you can decrease the resfresh interval) to resize automatically.

**Comment by sbraz** [comment]
Results is already set to 50. Am I missing something?

**Comment by lordtaki** [comment]
What is the setting of the refresh of this widget?
How long did you wait on the view page?

**Comment by lordtaki** [comment]
Administration / Extensions / Widgets

**Comment by sbraz** [comment]
@lpinsivy I've updated `centreon-widget-hostgroup-monitoring.noarch` from 1.6.2 to 1.6.3 and checked that `data.js` contains the changes from https://github.com/centreon/centreon-widget-host-monitoring/commit/8dac01694d89eac194019507627e6e81cadfef9f but it still doesn't seem to work.

**Comment by BenoitPoulet** [comment]
@sbraz Try to flush your browser cache (yes really, CTRL+F5 is not enough).
I still had the bug after upgrade, only the flush cache of FF show me the fix.

**Comment by sbraz** [comment]
@BenoitPoulet I've created a new empty Firefox profile and the height is still too small.

**Comment by lordtaki** [comment]
Did you wait 30 seconds for an automatic refresh?

**Comment by sbraz** [comment]
I set `Refresh Interval (seconds)` to 5 and yes, I waited 30 seconds. Even if that worked, I don't understand why I'd have to wait for 30 seconds before the widget is properly displayed. It should have the right size the first time it loads the list of hosts, otherwise that would be another bug…

**Comment by sbraz** [comment]
@lpinsivy after debugging the code, I found that there were two problems.
The main problem is that whenever [this line](https://github.com/centreon/centreon-widget-host-monitoring/blob/2e379b059ae6e1e4eac143e36d3dd6bb8cddb187/host-monitoring/data.js#L42) is called, I get an exception during the call to `append`. In Firefox:
```
SyntaxError: expected expression, got ';'[Learn More] jquery.js:8:21
    jQuery 4
    
    globalEval
    
    globalEval
    
    domManip
    
    append
    success http://xxxx/centreon/widgets/host-monitoring/data.js:42
    jQuery 4
    
    fire
    
    fireWith
    
    done
    
    callback
```

In Chrome:
```
VM128:8 Uncaught SyntaxError: Unexpected token ;
    at eval (<anonymous>)
    at jquery.js:349
    at Function.globalEval (jquery.js:350)
    at domManip (jquery.js:6092)
    at jQuery.fn.init.append (jquery.js:6272)
    at Object.success (data.js:42)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at done (jquery.js:9843)
    at XMLHttpRequest.callback (jquery.js:10314)
```

Because of this the `iResize` code is never called. By the way, I have no idea what it's doing inside an `append` function since we're not appending anything.

The other problem is that the code to obtain the height of the table was not the right one, this has since been fixed in https://github.com/centreon/centreon-widget-host-monitoring/commit/2b06b612caf64029813824f5035fb0b3520ee19c.

I spent an hour trying to find out why the call to `jQuery("#hostMonitoringTable").empty().append(htmlData)` fails _despite actually updating the data_. I assume it has to do with an event handler somewhere that tries to do something when the table is updated but I couldn't locate it.

I ended up catching the exception to make it work locally…
```diff
diff --git a/host-monitoring/data.js b/host-monitoring/data.js
index 585a8fc..7bc6ba5 100644
--- a/host-monitoring/data.js
+++ b/host-monitoring/data.js
@@ -39,10 +39,8 @@ function loadPage()
 {
     jQuery.ajax("./src/index.php?widgetId=" + widgetId + "&page=" + pageNumber, {
         success: function (htmlData) {
-            jQuery("#hostMonitoringTable").empty().append(htmlData).append(function() {
-                var h = document.getElementById("hostMonitoringTable").scrollHeight;
-                parent.iResize(window.name, h);
-            });
+            try { jQuery("#hostMonitoringTable").empty().append(htmlData) } catch (e) {};
+            parent.iResize(window.name, jQuery("#hostMonitoringTable").prop("scrollHeight"));
             jQuery('.checkall').on('change', function() {
                 var chck = this.checked;
                 $(this).parents().find(':checkbox').each(function () {
```

**Comment by adr-mo** [comment]
Hi @sbraz 

We are goind to investigate this issue.

It is now in the **backlog**

Regards

**Comment by adr-mo** [comment]
I @sbraz this has been fixed in the latest versions of the Centreon :wink: 

![image](https://user-images.githubusercontent.com/31647811/91062342-dda8d400-e62c-11ea-8e4b-3c80509e400c.png)


I'll close this issue.

Regards
