### ISSUE TITLE
centreon-broker fails to insert data due to wrong data type for column warn_threshold_mode

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#65]
---

Author Name: **Moritz Bunkus** (Moritz Bunkus)
Original Redmine Issue: 5993, https://forge.centreon.com/issues/5993
Original Date: 2014-11-27

---

openSUSE 13.1, MySQL 5.6.12
Centreon 2.5.3
Centreon Broker 2.6.3

This is a fresh installation of the aforementioned versions mostly
with default settings. The databases have just been set up via the
web-based setup wizard. I've also configured centreon to use
centreon-broker, added a service to check, started Nagios &
centreon-broker. Now I get the following error messages in the broker
log file (/var/lib/centreon-broker/central-broker-master.log in my
case):

[1415718350] error:   storage: insertion of metric 'time' of index 1 failed: Data truncated for column 'warn_threshold_mode' at row 1 QMYSQL3: Unable to execute statement

Looking at the source code in storage/src/stream.cc I see the
:warn_threshold_mode parameter being bound to the warn_mode variable
which is of type bool. However, the column in the database is of type
ENUM('0', '1'), and it looks like that SQL code like »…
warn_threshold_mode = FALSE« doesn't fit into a 1-char ENUM.

Note that the centreon-broker SQL schema file (sql/mysql_schema.sql)
declares the column as type BOOLEAN while centreon's SQL schema files
(both www/install/createTablesCentstorage.sql and
www/install/sql/centstorage/Update-CSTG-2.4.4_to_2.4.5.sql) declare it
as ENUM('0, '1').

The same applies to the crit_threshold_mode column.

**Comment by julienmathis** [comment]
@ganoze What do you think about this issue ? Fixed ?

**Comment by ganoze** [comment]
Absolutely not ! Never heard of this issue however it seems real according to sources. Two solutions : 

* fix Centreon Broker to use the enum
* fix Centreon schema to use a boolean

This concerns both warn_threshold_mode and crit_threshold_mode. I would personnally prefer the second solution (enum('0', '1') are horrible constructs) but I leave it up to you to decide.
