### ISSUE TITLE
No pagination on a Recurrent Downtime search

### ISSUE THREAD

**Issue by jaltmeyer** [centreon/centreon#6501]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.24-1

**Centreon Engine version**: 1.8.1-1

**Centreon Broker version**: 3.0.14-1

**OS**: CentOS 7

**Steps to reproduce the issue:**
1. Create a recurrent downtime, like "test" for example
2. Duplicate this downtime more than 10 times (for the example)
3. Make a search for "test" and limit to 10 rows

**Describe the results you received:**
We should have a result with a pagination on the page, but not :

![20180730-162409](https://user-images.githubusercontent.com/38248555/43403520-84212510-9415-11e8-9fbd-95ff25749efb.png)

**Describe the results you expected:**
We should have a pagination like here with no search :
![20180730-162859](https://user-images.githubusercontent.com/38248555/43403600-bb5cc3c2-9415-11e8-9f05-8ade3b034191.png)

**Comment by adr-mo** [comment]
**It is now fixed for the 2.8.x branch**

Patch is coming for the 18.10.x
