### ISSUE TITLE
How to upgrade 2.7.13 to latest 2.8.x

### ISSUE THREAD

**Issue by gabyfulchic** [centreon/centreon#6505]
Hi everyone,
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.7.13 

**OS**:  VM virtualbox Centos 6.10

My centreon is installed following this guide :  https://documentation.centreon.com/docs/centreon/en/2.7.x/installation/from_packages.html

But i can't upgrade it to the 2.8.x latest version. I tried following this link : https://documentation.centreon.com/docs/centreon/en/2.7.x/upgrade/from_packages.html

But after the commands nothing happens.
I've tried to reboot, to restart httpd, and same restarting centreon i keep my centreon to the old version. I'm training to upgrade because a server in production need to upgrade to 2.8 via 2.7.13 so it could be very helpful if you help me ;) 

After following upgrade commands : 
![image](https://user-images.githubusercontent.com/22600727/43465979-d46f9be0-94de-11e8-882f-8e891166400b.png)

Warmly FULCHIC Gaby

**Comment by gabyfulchic** [comment]
So, No one can answer on the centreon forum, and no one can answer on the centreon github ?
Did you forgot what you've wrote on your web page ? 
![image](https://user-images.githubusercontent.com/22600727/43593372-e93325a2-9677-11e8-848b-466ca6da397e.png)
Sorry if you imagine me as a weird guy but i really feel alone on my project...
I know that you have a life and a work like me.

Warmly FULCHIC Gaby

**Comment by Sims24** [comment]
Probably that looking to the documentation of the version you want to reach would be a better way to achieve what you want : 

https://documentation.centreon.com/docs/centreon/en/2.8.x/upgrade/from_packages.html

**Comment by gabyfulchic** [comment]
Thank you for your reply.
I'll try this right now. 👍

**Comment by gabyfulchic** [comment]
all well worked. Ty

**Comment by gabyfulchic** [comment]
After all the donwloads on the new repo and the update of centreon. I keep having my centreon on 2.7.13.
So, do you know what sould i've bad done ? I've just followed the 2.8 upgrade tuto but when i'm reaching my ip to trigger the upgrade on the web centreon i just continue to see my centreon 2.7.13 without any process to upgrade.
I've trie to reach this http://<ipaddr>/centreon/install/step_upgrade/step1.php but a page without any css appears and when i trigger next it does nothing.
Warmly FULCHIC Gaby

**Comment by lpinsivy** [comment]
Did you try to restart Apache and clean your browser cache?
