### ISSUE TITLE
Plugin pack manager menu, https encoding problem

### ISSUE THREAD

**Issue by Moulagofre** [centreon/centreon#6508]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.14

**Centreon Engine version**: 
1.8.1

**Centreon Broker version**: 
3.0.14

**OS**: 
Centos7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos VM on XenServer physical machine

**Steps to reproduce the issue:**
1. Configure apache access to https only
2. Navigate to Configuration  >  Plugin Packs  >  Manager

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/19334022/43520803-47537f68-9594-11e8-8f64-fb28442057dc.png)

**Describe the results you expected:**

The selection menu.

**Additional information you think important (e.g. issue happens only occasionally):**

Works well with http

**Comment by lpinsivy** [comment]
Hi @Blazfhem can you update your Centreon web version as well as the Plugin Packs Manager.

Then reload Apache daemon.
