### ISSUE TITLE
ACL inconsistency in the Downtime menu

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#6512]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.23
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 
3.0.14
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1. Create a user with a limited Resources Access group, and give him the menu access "Recurrent downtimes : Read Only"

**Describe the results you received:**
The user under ACL can see all the the recurrent downtimes even the ones who are linked to the host he is not supposed to see.

**Describe the results you expected:**
The user should only see the downtimes which are linked to the ressources he is supposed to see.

**Comment by loiclau** [comment]
#6962
