### ISSUE TITLE
bug with google chrome on monitoring view

### ISSUE THREAD

**Issue by OpensourceMonitoringRepository** [centreon/centreon#6515]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.24
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 
3.0.14

**OS**: 
Redhat 6.8
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. connect with latest google chrome on centreon
2. select monitoring services view

**Describe the results you received:**
1. no icone for graph
2. it's work with mozilla

**Describe the results you expected:**
to have graph icones with google chrome on monitoring services view.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
What is your OS and your Chrome version?

On macOS 10.13.6 with Chrome version 68.0.3440.106 (Build officiel) (64 bits), I can see icon:

![screenshot at aout 21 13-47-32](https://user-images.githubusercontent.com/3351916/44400312-00d6af80-a54b-11e8-94ad-adb65a9222fd.png)

**Comment by adr-mo** [comment]
**No answer for now more than 6 months**

Closing this issue.

Regards,
