### ISSUE TITLE
insertBaseConf.sql incompletely applied as it does not provide values for NOT NULL columns

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#652]
---

Author Name: **Moritz Bunkus** (Moritz Bunkus)
Original Redmine Issue: 5989, https://forge.centreon.com/issues/5989
Original Date: 2014-11-27

---

Centreon 2.5.3
Centreon Broker 2.6.3

Tested on openSUSE 13.1 with MySQL 5.6.12 and MariaDB 5.5.33

I'm installing Centreon with Centreon Broker on a fresh and clean
openSUSE system with »./install -i«. After installation I visit the
web interface and set up the MySQL databases.

Afterwards I can login, but there are no hosts or services at
all. Investigating further shows that several of the tables that
should contain data do not contain any data at all. I've looked into
the »insertBaseConf.sql«, and it turned out that all queries up to and
including the INSERTs for table »giv_components_template« have been
run.

The INSERTs for table »giv_graphs_template« and all following INSERTs
where not executed successfully.

When I now execute the following query (copied from
»insertBaseConf.sql«)…

INSERT INTO `giv_graphs_template` (`graph_id`, `name`, `vertical_label`, `width`, `height`, `base`, `lower_limit`, `upper_limit`, `bg_grid_color`, `bg_color`, `police_color`, `grid_main_color`, `grid_sec_color`, `contour_cub_color`, `col_arrow`, `col_top`, `col_bot`, `default_tpl1`, `stacked`, `split_component`, `scaled`, `comment`) VALUES(1, 'Default_Graph', 'Value', 550, 140, 1000, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '#FF0000', NULL, NULL, '1', NULL, NULL, '1', NULL);

…I get this error message:

ERROR 1364 (HY000): Field 'size_to_max' doesn't have a default value

Seems that the execution of insertBaseConf.sql was aborted after that
one failed query.

In order to reproduce:

1. Install Centreon Broker 2.6.3 and Centreon 2.5.3 on a fresh
   openSUSE 13.1 system using mostly defaults for the answers

2. Run the web-based setup procedure and let it create the databases

3. Connect to the »centreon« database

4. »SELECT COUNT(*) FROM giv_graphs_template« will return 0.

5. Looking at one of the later tables shows that they're empty as
   well: »SELECT COUNT(*) FROM host« returns 0 as well proving that
   the insertion script has been aborted.

**Comment by julienmathis** [comment]
Sorry, but I can't size_to_max field in your query... Did you do a mistake ?
