### ISSUE TITLE
Problem with Nagvis

### ISSUE THREAD

**Issue by GFui** [centreon/centreon#6522]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Hi, I have this problem. Centreon Web: 2.6.6, Nagvis: 1.8.5
I can't see Nagvis from centreon... in my httpd logs I have this

(This is from error_log)
[Thu May 31 17:05:40 2018] [error] [client XXX.XX.XX.XXX PHP Parse error: syntax error, unexpected '/' in /usr/local/centreon/www/modules/centreon-nagvis/index.php on line 22, referer: https://XXX.XX.XX.XX/centreon/main.php?p=403

But in index.php all seems to be OK.. It was working a few days ago...
Thanks!

**Comment by lpinsivy** [comment]
Hi can you create the issue on the comunity ptoject https://github.com/centreon/centreon-nagvis
