### ISSUE TITLE
Cant show legend on my graphs

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon#6525]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.24-1.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-3.0.14-1.el7.centos.x86_64

**OS**: CentOS Linux release 7.5.1804 (Core)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Using the service template  OS-Windows-Disk-Generic-Name-SNMP
2. Going to Monitoring > Performances > Curves
3. On used, checking Print max value, min value, average

**Describe the results you received:**
On the graph, i have no legend at all, just the metric name with the color square on its left

**Describe the results you expected:**
Having a legend with the value of max, min and average

**Additional information you think important (e.g. issue happens only occasionally):**
Same things for all my graphs (cpu, memory, disk, traffic and so)

Thanks for your help

**Comment by lpinsivy** [comment]
On the graph click on the "i":

<img width="629" alt="screenshot at aout 21 13-33-56" src="https://user-images.githubusercontent.com/3351916/44399201-ef8ba400-a546-11e8-9899-90654d2cbb3d.png">
<img width="625" alt="screenshot at aout 21 13-34-05" src="https://user-images.githubusercontent.com/3351916/44399205-f2869480-a546-11e8-99ea-acf00a8159b0.png">

**Comment by gerpion** [comment]
Hello

Ah cool, it's working perfectly but only when you are going into the performance graph.
When you see the graph in Monitoring > Status details, when you have the hover, you cant clic on the "i".

**Comment by lpinsivy** [comment]
yes it is a preview without full access to all actions ;)
