### ISSUE TITLE
ACL not properly working in Charts filter

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#6534]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.16

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual host

**Steps to reproduce the issue:**
1. log in with user that should only see CustomerA
2. go to Monitoring-> Performances 
3. write for example Ping to the Chart box

**Describe the results you received:**
4. there are services shown starting with Meta-XXXX
5. CustomerA sees all other customers services. He cant see the graphs, but in the list there are all other customers.

**Describe the results you expected:**
6. Only services that are attached to CustomerA should be shown, not other customers services with other customer names.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by mvisini** [comment]
Same pb in 2.8.25...
