### ISSUE TITLE
Centreon flipping header - Enhancement

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#6546]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.25

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: Centreon 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Activate flipping header

**Describe the results you received:**
If you have critical services you don't see OK services

![alerts](https://user-images.githubusercontent.com/2960490/44386993-3a9cbb80-a535-11e8-9b34-bc192733306c.PNG)

**Describe the results you expected:**
You should be able to see OK services even if you have critical services

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Crash-Fox** [comment]
The same should applied to Pending Services and also for the host we should be able to see both Down, Unreachable and OK Hosts

**Comment by lpinsivy** [comment]
Hi @lolokai & @Crash-Fox.

Thank you for your feedbacks. We propose to display only issue to focus on them and not to display all information. Access to all status is available by clicking on the associated host or service icon.

Moreover, for pending service, a new icon will appear.

Regards,

**Comment by Crash-Fox** [comment]
I understand your point of view. But before the flipping banner we can access all categories of hosts and services with one click nom two.

**Comment by lolokai** [comment]
Hi @lpinsivy ,
I understand your point of view but the problem is that our customers are disturbed by this new view which do not permit them to compare the ratio of ok services with non-ok services.

**Comment by lolokai** [comment]
Maybe we can add an option to display Ok services ?

**Comment by lpinsivy** [comment]
In case of all resources are in OK status you have:
![screenshot at aout 22 13-25-57](https://user-images.githubusercontent.com/3351916/44462764-f3d2c280-a615-11e8-9db1-ef561ab2466f.png)

To access to all information, you can click on "hosts" and "services" icons

The goal here is to focus on non-ok issues in non-ack or non-downtimes state.

For the ratio, maybe we can add in small policy size the x**/Y** part in bubble

**Comment by lolokai** [comment]
Ok for add x**/Y** part in bubble ;)
