### ISSUE TITLE
Load the default page when user is already authenticated

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#6548]
Hi,

The _Default page_ setting works at user login (when user enters his username/password). Perfect.

However, it does not work when the browser is already authenticated, and user navigates to `http://server/centreon`. User is then not redirected and sees the _Home > Custom Views_ page.

Could it be possible to load the _Default page_ here too ?

Thank you very much :+1: 

Edit : issue still present in 19.10.10.

**Comment by UrBnW** [comment]
See #8354 for a fix 👍

**Comment by kduret** [comment]
Fixed with Centreon Web 20.04.1
