### ISSUE TITLE
No commands with fresh install centreon-3.4.6.el7.x86_64 with external DB

### ISSUE THREAD

**Issue by mvisini** [centreon/centreon#6556]
Hello, 

in my new lab i try to make a fresh install of centreon on centos7 with your centreon-3.4.6.el7.x86_64.iso.
I installed a central server without database and a 'database only' from your iso
My web interface is OK but i've no commands in Configuration/Commands
I tried to push a script in /usr/lib/nagios/plugins and created a command related that, it works fine.

I don't know why i've no commands..
I proccessed to the upgrade yet (2.8.25), but the problem is always here.

Any idea ?

Thanks

Mathieu

**Comment by lpinsivy** [comment]
Hi,

The basic commands and template are provides from free Centreon Plugin Packs.

Go to "Administration > Extensions > Modules" and install centreon-license-manager & centreon-pp-manager.
Then go to "Configuration > Plugin Packs" and install the available Plugin Packs.

Documentation => https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/imp/index.html

Regards,
