### ISSUE TITLE
[DOC] Fix the documentation relative to the resource parameters on the API syntax

### ISSUE THREAD

**Issue by jaltmeyer** [centreon/centreon#6560]
The documentation of Centreon still use the old syntax, with the ID in the CLAPI arguments, but from 2.8.25 and these PR https://github.com/centreon/centreon/pull/6457 https://github.com/centreon/centreon/pull/6222 the name of the object must be used.

The API part of the documentation must be change accordingly.

**Comment by lgcosta** [comment]
Create a fix at:
https://github.com/centreon/centreon/pull/6510/commits/357ed877fee2e37148c04a098da20147229eecf2
@jaltmeyer

**Comment by adr-mo** [comment]
**Fixed and merged**

Closing this issue.
