### ISSUE TITLE
Migrate a centreon 

### ISSUE THREAD

**Issue by gabyfulchic** [centreon/centreon#6564]
**Centreon Web version**: 2.7.13

**Centreon Engine version**: 1.5.3

**Centreon Broker version**:  2.11.8

**OS**: Centos6

**Additional environment details (AWS, VirtualBox, physical, etc.):** OVH VPS

I've got a centreon full configured and with a lot of plugins modified. I've migrated it in a test node with some tar -czvf and mysqldump the first time. 
Like the server is not in version 2.8.x the backup features does not exist. So i wanted to know if it was possible to backup properly to centos 7 and centreon 2.8 ? :) i'll completely all re-install beaucase i'll change the os.

Warmly FULCHIC Gaby

**Comment by lpinsivy** [comment]
Hi @gabyfulchic .

1. You can dump your SQL databases ('centreon' & 'centreon_storage').
2. Backup directories of your plugins
3. Backup SSH keys
4. Install a Centreon in lastest version
5. insert your dump
6. Perform all upgrade using web upgrade process
7. Modify your centreon password in your Centreon Broker configuration is the password for 'centreon' user changed
8. unarchive your plugins

Regards,

**Comment by gabyfulchic** [comment]
Ok ty very much ! @lpinsivy 
All seems to work !
