### ISSUE TITLE
Problème avec le retour de la commande check_nt

### ISSUE THREAD

**Issue by hvad** [centreon/centreon#6574]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.14 

**Centreon Engine version**: 1.8.0

**Centreon Broker version**: 3.0.10

**OS**: CentOS 6.8

**Steps to reproduce the issue:**
1. Executer check_nt vers un hote qui a un agent NSClient++ mais qui n'autorise pas Centreon a le contacté.

Comme ci dessous : 
 /usr/lib64/nagios/plugins/check_nt -H xxx.xxx.xxx.xxx -p 12489 -v CLIENTVERSION

2. Le code retour de la commande est 1 

echo $?
1

3. Mais Centreon Engine ne voit pas l'hôte non joignable.

**Describe the results you received:**
Machine UP dans Centreon 

**Describe the results you expected:**
Machine DOWN dans Centreon

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lgcosta** [comment]
Have you tried manually to run the command as centreon user?, example (as root):
```
sudo -u centreon /usr/lib64/nagios/plugins/check_nt -H xxx.xxx.xxx.xxx -p 12489 -v CLIENTVERSION
```
Check if it runs normally or some error occurs.

**Comment by hvad** [comment]
Hi,

It's same issue with centreon user or not... Problem wasn't code return but centreon-engine didn't see return code = 1. 

Why centreon didn't say host down ?

**Comment by lpinsivy** [comment]
@hvad the return code (echo $? after execute your command) is 1?
