### ISSUE TITLE
Centreon & SELinux

### ISSUE THREAD

**Issue by hvad** [centreon/centreon#6575]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: toutes 

**Centreon Engine version**:  toutes 

**Centreon Broker version**:  toutes 

**OS**: CentOS 6.x

Rendre Centreon compatible SELinux.

**Comment by Sims24** [comment]
Hi @hvad 

Would you agree to test and provide feddback on some selinux configuration that make Centreon running with selinux enabled ? If so, feel free to send me an email

**Comment by adr-mo** [comment]
**No answers for now more than 6 months**

Closing this issue

Regards,

**Comment by hvad** [comment]
Centreon is not compatible with SELinux. And i not advice for Centreon for security reason.
In my enterprise will not use this product anymore.
