### ISSUE TITLE
Export broken in 2.8.25 (HGSERVICE)

### ISSUE THREAD

**Issue by richardlawley** [centreon/centreon#6578]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.25

**Centreon Engine version**: 2.8.25

**Centreon Broker version**: 2.8.25

**OS**: CentOS 7 (latest updates applied)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a HostGroup
2. Add a Service to the HostGroup - you must specify a command
3. Run `centreon -u USER -p PASS -e`

**Describe the results you received:**

`HGSERVICE;ADD` line is printed, then program crashes with error:
> PHP Fatal error:  Call to undefined method Centreon_Object_Command::getInstance() in /usr/share/centreon/www/class/centreon-clapi/centreonHostGroupService.class.php on line 977

**Describe the results you expected:**

Export produced with no errors

**Additional information you think important (e.g. issue happens only occasionally):**

Only happens if a HostGroup exists with a Service attached, and that service has a check command defined.  Problem goes away if service is removed, or if check command is left blank.

**Comment by burncycl** [comment]
Also present in 2.8.26.

**Comment by lukehuxley** [comment]
The PHP fatal error is also thrown when performing an export, like so:
>$ /usr/bin/centreon -u <user> -p <password> -e
>PHP Fatal error:  Call to undefined method Centreon_Object_Command::getInstance() in /usr/share/centreon/www/class/centreon-clapi/centreonHostGroupService.class.php on line 977

**Comment by boogaaloo** [comment]
Hi,

Any updates, any informations ?

**Comment by lpinsivy** [comment]
HI @boogaaloo Centreon 2.8.x is no more supported and I think we already fix this issue
