### ISSUE TITLE
SQL injection on serviceXML.php

### ISSUE THREAD

**Issue by zskarman** [centreon/centreon#6579]
Hi Team,

I have security scan on my instance and it's detected an possible SQL injection on the UI.
Version: 2.8.25

Code is: 
GET /centreon/include/monitoring/status/Services/xml/serviceXML.php?
&search=&search_host=&search_output=&num=0&limit=30&sort_type=host_name
&order=ASC%2c(select*from(select(sleep(20)))a)&date_time_format_status=Y/m/d
%20H:i:s&o=svc_unhandled&p=20201&host_name=&nc=0&criticality=0&statusServ
ice=svc_unhandled&statusFilter=&sSetOrderInMemory=1 HTTP/1.1

Details: Use parameter queris. The order parameter appears to be vulnerable to SQL injection attacks. The payload
,(select*from(select(sleep(20)))a) was submitted in the order parameter. The
application took 22250 milliseconds to respond to the request, compared with 4268
milliseconds for the original request, indicating that the injected SQL command
caused a time delay.

Regards, Zsolt

**Comment by cgagnaire** [comment]
Fixed here https://github.com/centreon/centreon/commit/973866854a7156c0dd7e0115249ae718b6110de3
