### ISSUE TITLE
Session Token in URL

### ISSUE THREAD

**Issue by zskarman** [centreon/centreon#6580]
Hi Team,

I have found an security risk on the following page: centreon/index.php?
disconnect=1&redirect=
%27p=20201&statusFilter=ok&o1=3&o2=3&criticality=0&host_search=555-
555-0199@example.com&o=&search=555-555-
0199@example.com&statusService=svcpb&centreon_token=21ecef152c9a01
ddfc000617e0cd843f&limit=30&output_search=555-555-
0199@example.com&cmd=42%27

Suggession: Applications should use an alternative mechanism for transmitting session tokens,
such as HTTP cookies or hidden fields in forms that are submitted using the POST
method.

Regards, ZSolt

**Comment by lpinsivy** [comment]
Please move to HTTPS using the following documentation: https://docs.centreon.com/current/en/administration/secure-platform.html

Regards,
