### ISSUE TITLE
Cross-site Scripting Issue

### ISSUE THREAD

**Issue by zskarman** [centreon/centreon#6581]
Hi Team,

Could you please fix the following cross-site scripting issue?

The value of the limit request parameter is copied into an HTML comment. The
payload rdbvr--><script>alert(1)</script>do1x6 was submitted in the limit
parameter.:
GET /centreon/include/monitoring/status/Services/xml/serviceXML.php?
&search=&search_host=&search_output=&num=0&limit=30rdbvr--%3e%3cscript
%3ealert(1)%3c%2fscript
%3edo1x6&sort_type=host_name&order=ASC&date_time_format_status=Y/m/d
%20H:i:s&o=svc_unhandled&p=20201&host_name=&nc=0&criticality=0&statusServ
ice=svc_unhandled&statusFilter=&sSetOrderInMemory=1 HTTP/1.1

![image](https://user-images.githubusercontent.com/24320218/44851003-4556ff00-ac5f-11e8-99f0-7394f658750d.png)

Regards, Zsolt

**Comment by lpinsivy** [comment]
should be fixed by #8291
