### ISSUE TITLE
perf graph cpu2 doesn't display

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon#6591]
Hey everyone, I post my issue as mentioned here https://github.com/centreon/centreon-plugins/issues/1125
I just noticed that on all cpu graph, with 4 cores or more, windows or linux plugin, there aren't cpu2 perf graph.
Centreon v.2.8.24 on CentOS7
![cpu2](https://user-images.githubusercontent.com/30388990/45105613-ef89c780-b134-11e8-9c80-029b37671251.JPG)

**Comment by lpinsivy** [comment]
If you go in "Administration  >  Parameters  >  Data" menu and you select your host/service. Can you see the "cpu2" metric available?

**Comment by oasisck** [comment]
Yes I see every metric relate to cpu plugin for all hosts
Same host than last screenshot
![capture](https://user-images.githubusercontent.com/30388990/45220820-c3df1c80-b2af-11e8-8f99-dfb839c94061.JPG)

**Comment by oasisck** [comment]
Resolved by upgrading to 18.10
