### ISSUE TITLE
Notifications still sent when parent host is down

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#6596]
Centreon version 2.8.22
Centreon Engine 1.8.1
Centreon Broker 3.0.14

host2 has parent host1, child host3
host1 has service1, host2 has service2, host3 has service3

All hosts don't have anything selected for notification statuses, but use host templates which have down, unreachable and up checked under notifications.

All hosts and services are up.

host1 does down, changes status to "DOWN", notification sent - as expected
service1 changes status to "CRITICAL", no notification is sent - as expected
service2 changes status to "CRITICAL", notification sent - should not be sent, since host2 is dependent on host1, which is down
host2 goes down, changes status to "UNREACHABLE", notification sent - should not be sent, since host2 is dependent on host1, which is down
service2 changes status to "OK", notification sent - should not be sent, since host2 is down (with status "UNREACHABLE" instead of "DOWN")*
service2 changes status to "CRITICAL", notification is not sent - as expected
service2 changes status to "OK", notification is not sent - as expected
host2 comes back up, changes status to "OK", notification sent - should not be sent, since host2 is dependent on host1, which is still down
service2 changes status to "CRITICAL", notification sent - should not be sent, since host2 is dependent on host1, which is down

Also notice how a notification is sent out when service2 goes OK the first time and not sent the second time, there seems to be no obvious logic to that.

*) if the timing of the service check is such that it goes critical before Centreon notices the host itself went down a notification is sent in any case, I think there should be a service check notification option to force the host check the service belongs to before deciding whether to send a notification, but that's another discussion.

After unchecking unreachable status for notification in the host templates:

host1/service1 are down/critical
host2 goes down, changes status to "UNREACHABLE", notification not sent - as expected
service2 changes status to "CRITICAL", notification not sent - as expected
service2 changes status to "OK", notification not sent - as expected
host2 comes back up, changes status to "OK", no notification sent - as expected
service2 changes status to "CRITICAL", notification sent - should not be sent, since host2 is dependent on host1, which is down
host2 goes down, changes status to "UNREACHABLE", notification not sent - as expected
service2 changes status to "OK", notification sent - should not be sent, since host2 is down (with status "UNREACHABLE" instead of "DOWN")
service2 changes status to "CRITICAL", notification is not sent - as expected
service2 changes status to "OK", no notification sent - as expected

So somewhat better, but service notification still ignores host relationships and  there is no way to set parent/child relationships for services to hosts or other services.

**Comment by ppoektos** [comment]
Why nobody care about this major issue?

**Comment by lpinsivy** [comment]
@ppoektos this issue was discribed for following versions:
Centreon version 2.8.22
Centreon Engine 1.8.1
Centreon Broker 3.0.14

They are no more supported and I suppose the bug is no more present into Centreon 21.04.
If is still present, you can reopen this issue
