### ISSUE TITLE
[CentreonKnowledge] Nested Wiki Article

### ISSUE THREAD

**Issue by C-Bam** [centreon/centreon#6599]
---------------------------------------------------
INFORMATION
---------------------------------------------------
**Centreon** 2.8.25

It is more a request than a bug reporting.

Today, CentreonKnowledge works like this:

Say we have a Linux Server > WebServers > ParisWebServers > Server001

The link to the wikipage will be to the first that exists with priority to Server001, then ParisWebServers, then WebServers, then Linux Server

So if I put some info in Linux Server Wiki and in Server001 Wiki, the only accessible information is Server001

**Behavior I expect**

When you click on Serv001 Wiki, you may have the choice between all parent Wikis
This might be done by storing many URL in parameter for instance

Even better though I think it might be complicated : Automatically adding links to related wiki pages in articles

**Comment by lpinsivy** [comment]
IN fact it is an issue of inheritance. If the object is present on the child, we will not read the parent
