### ISSUE TITLE
[API] Enhancement - Add the ability to sort results on get methods

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6600]
Hi,

It would be convinient to be able to sort results with get methods like "ORDER BY" in SQL.
This argument could be optionnal in request and in this form for the "get_service" method for example:
```
{
  "action": "show",
  "object": "service",
  "values": "DISK",
  "sortby": "host name ASC;description DESC"
}
```
the sort method can take one or more values.
options ASC and DESC are optionnal too with ASC by default.

What do you think about it?
thanks.

**Comment by lpinsivy** [comment]
Available using APIv2 => https://docs.centreon.com/api/centreon-web/#tag/Host/paths/~1monitoring~1hosts/get
