### ISSUE TITLE
Recovery notification delay (notification options) inheritance issue ?

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#6601]
Hi,

I have a **generic** service template configured like this :

![screen shot 2018-09-09 at 15 45 47](https://user-images.githubusercontent.com/40244829/45265226-1c492200-b448-11e8-80be-a4540b92762e.png)

Then I have a **linux-cpu** service template, which inherits from the **generic** one, configured like this :

![screen shot 2018-09-09 at 15 52 18](https://user-images.githubusercontent.com/40244829/45265261-64684480-b448-11e8-9e87-9a4841224bd6.png)

Finally, a **cpu** service which inherits from the **linux-cpu** service template.

**cpu** service should send its recovery notification 5 minutes (300 seconds) after service recovered.
Unfortunately, it sends it immediately.

If I modify the **cpu** service itself, enforcing its _Recovery notification delay_, I get the expected behavior.

Is there then any issue with _Recovery notification delay_ inheritance, or more globally with notification options inheritance ?

Thank you very much !

Edit : issue still present in 18.10.4.

**Comment by CPbN** [comment]
May I ask you some feedback regarding this issue ?
Thank you very much !

**Comment by lpinsivy** [comment]
Similare to #6602.

**Comment by CPbN** [comment]
May I ask you if you perhaps have some news regarding this annoying issue ?
Thank you very much :+1:

**Comment by CPbN** [comment]
As it sounds like an inheritance issue, I'm not sure it's related to engine itself ?
I don't know if inheritance resolution takes place at configuration generation time, or later-on...
@lpinsivy @ganoze ?
