### ISSUE TITLE
[2.8.25] AD Authentification not working

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon#6609]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.25

**Centreon Engine version**: 1.8.1

**OS**: CentOS 6.9

**Steps to reproduce the issue:**
1. Change the user search base in the LDAP parameter.
2. Connect to Centreon with an AD account.

**Describe the results you received:**
Users try to connect to Centreon Web using there new and old passwords but they can't.

**Describe the results you expected:**
Users should succeed to connect to the web interface of Centreon using the credentials of there AD accounts.

**Comment by lpinsivy** [comment]
Did you enable "store password" ? If the Centreon can't connect to LDAP server, it will compare password with sotred.

**Comment by Crash-Fox** [comment]
Thanks for you response. I made sure that this option was not selectionned during my manipulation. I'm sorry that I didn't put that in my original ticket.
