### ISSUE TITLE
Use of class CentreonCfgWriter

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#661]
---

Author Name: **Sylvestre Ho** (Sylvestre Ho)
Original Redmine Issue: 2314, https://forge.centreon.com/issues/2314
Original Date: 2011-04-29
Original Assignee: Sylvestre Ho

---

The files (gen*.php) which are located in 'www/include/configuration/configGenerate/' should use the class CentreonCfgWriter

**Comment by julienmathis** [comment]
deprecated
