### ISSUE TITLE
[BUG] Macro SERVICENOTESURL: inconsistant value

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6612]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.25
**Centreon CLAPI version**: 1.8.0
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.14
**OS**: CentOS release 6.10 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. create a notification with macro SERVICENOTESURL
2. set a service with this notification
3. generate an alert to notify

**Describe the results you received:**
the value of SERVICENOTESURL were truncated of "&" character beetween host name and the "service_description" string
like this:
`./include/configuration/configKnowledge/proxy/proxy.php?host_name=host1service_description=TEST-notification_EVT-Std`

The parameters of the query are therefore invalid, and the proxy could'nt translate the good url

**Describe the results you expected:**
the "&" character must be present in the output
like this:
`./include/configuration/configKnowledge/proxy/proxy.php?host_name=host1&service_description=TEST-notification_EVT-Std`

regards.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by cmeschin** [comment]
to solve this problem, I add this sed function before "| @MAILER@..." in command line:
`| sed -e \"s#\(host_name=\)\([-a-zA-Z0-9_].*\)\(service_description=\)#\1\2\&\3#g\"`

**Comment by C-Bam** [comment]
Hey,
I have the very same problem
Thanks for you solution!

I had to tweak it a little to  have it work as intended

`| sed -e "s#\\(host_name=\\)\\([-a-zA-Z0-9_].*\\)\\(service_description=\\)#\\1\\2\\&\\3#g" | @MAILER@`

**Comment by lpinsivy** [comment]
@ganoze issue with Engine when it replace value of macro?

**Comment by C-Bam** [comment]
The issue is not only linked to the mailer or to printf.

When a use it with curl it gives the same issues

`/usr/bin/curl -H "Content-Type: application/json" -d "{\"text\":\"http://xyz.abc/centreon/$SERVICENOTESURL$" https://outlook.office.com/webhook/...`

Hope it helps 👍

**Comment by ganoze** [comment]
This is related to [illegal_macro_output_chars](https://documentation.centreon.com/docs/centreon-engine/en/latest/user/configuration/basics/main_configuration_file_options.html#illegal-macro-output-characters) option.

**Comment by adr-mo** [comment]
Hi @cmeschin @C-Bam 

This **cannot be fixed** as ganoze explained.

The only solutions are the ones that you provided (meaning workarounds)

Regards,
