### ISSUE TITLE
Server Status, data_bin not partitionned

### ISSUE THREAD

**Issue by gabyfulchic** [centreon/centreon#6615]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.25

**Centreon Engine version**:  1.8.1

**Centreon Broker version**:  3.0.14

**OS**:  CentOS7

**Additional environment details (AWS, VirtualBox, physical, etc.):** OVH VPS

**Steps to reproduce the issue:**
1. Go to the Crentreon GUI => tab Administration->Server Status
2. Here, the 4 tabs display me : table is not partitionned

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/22600727/45612581-b3733280-ba63-11e8-9519-39f3ab9e89d6.png)

Need i to configure something in the /usr/share/centreon/config/partition.d/ .xml files ?
Or need i to launch the php script to partition my db ?

Warmly FULCHIC Gaby :D

**Comment by lpinsivy** [comment]
Hi,

Your platform is a fresh install or an update from previous installation (Centreon web < 2.8.x)?

**Comment by adr-mo** [comment]
Hi @gabyfulchic 

No answer for now more than **2 months.**

But you can check the documentation related to this. https://documentation.centreon.com/docs/centreon/en/latest/administration_guide/partitioning.html?#migrating-unpartitioned-tables

Closing this issue.

Regards,
