### ISSUE TITLE
Add an option to CLAPI to target a specific host

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon#6617]
Hi,

We use to make the following addition to /usr/share/centreon/bin/centreon, it adds a -H option to specify a hostname, so our central server is able to act not only on itself but also on another Centreon server. We do this because we have multiple Centreon environments and an application which is hosted on a particular Centreon server is used to manage the multiple environments.

I find this handy and wonder if it can be integrated in Centreon so I wouldn’t have to report this local change anytime Centreon is upgraded.

```
$ diff centreon.ori centreon
58a59
> $shortopts .= "H:"; /* Host */
100,102c101,115
< $dbConfig['host'] = $conf_centreon['hostCentreon'];
< $dbConfig['username'] = $conf_centreon['user'];
< $dbConfig['password'] = $conf_centreon['password'];
---
> if (isset($options['H']))
> {
>         $dbConfig['host'] = $options['H'];
>         $dbConfig['username'] = 'username';
>         $dbConfig['password'] = '*******';
> }
> else
> {
>         $dbConfig['host'] = $conf_centreon['hostCentreon'];
>         $dbConfig['username'] = $conf_centreon['user'];
>         $dbConfig['password'] = $conf_centreon['password'];
> }
> 
> 
> 
```
Here the username and the password are hardcoded but the corresponding option may be used instead ($options['u'] & $options['p']).

What’s your opinion ?

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.7.13

**Centreon Engine version**: 1.5.3

**Centreon Broker version**: 2.11.8

**OS**: CentOS 6

**Comment by lpinsivy** [comment]
Sorry but the command line API can only access to one server.

You can use Rest API to connect to different servers

**Comment by StefThomas** [comment]
@lpinsivy What is the problem making this functionnality not desirable ? Is it some security related considerations ?

Does the HTTP Rest API made to replace Centreon CLAPI in the futur ? The documentation says the Rest API currently only covers 95% of what CLAPI does…

**Comment by StefThomas** [comment]
OK, merci pour la réponse rapide en tous cas.
