### ISSUE TITLE
massive change - hostgroup - stop at 1000

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon#6623]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.26

**OS**: centos

**Additional environment details (AWS, VirtualBox, physical, etc.):**
virtual

**Steps to reproduce the issue:**
1. create 1050 hosts
2. create a hostgroup
3. select all hosts with paging at max to get all of them on a single page. select all checkbox, select massive change
4. add in increment the new hostgroup. click ok.

**Describe the results you received:**
Only the first 1000 are added

**Describe the results you expected:**
All checked hosts should be added

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by itsul** [comment]
Hi @mathieuchateau ,


probable this is not a bug or error. Check your Webserver log, i think you reach your PHP.ini limits.

Take a look at /etc/php.ini (CentOS7). Set the max_input_vars to anything above 1.000. After that restart your webserver "systemctl restart httpd" and try again.

Keep in mind, that you also can reach different timeout limits from your INI file (like execution timeout) depends on the sum of hosts you want to change.

Regards
