### ISSUE TITLE
Autologin + url with parameters svc_id

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon#6631]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.26

**Centreon Engine version**: 1.8.1

Hello,

I have a problem when I use the autologin parameter.
My url is composed of 
main.php?p=204&svc_id=12345678;Ping&autologin=1&useralias=user&token=token

p=204 correspond at the "Performances" page

When I click on it, Centreon sign in me and redirect me on the page main.php?p=204 only. 
The svc_id is removed.

I must re-click on it to go on the wanted url.

Can you help me.

Thanks.

**Comment by lolokai** [comment]
Any news for this bug ?

**Comment by lolokai** [comment]
It do not work with Centreon 19.04 also
