### ISSUE TITLE
Getopt.pm on centreon_linux_snmp.pl mode cpu

### ISSUE THREAD

**Issue by LLFT** [centreon/centreon#6639]
**Centreon Web version**: 2.8.26
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 
**centreon-pp-manager**: 2.4.0
**centreon-license-manager**: 1.1.0
**Pluggin** :
- centreon-plugin-Operatingsystems-Windows-Snmp-20180821-1
- centreon-plugin-Operatingsystems-Linux-Snmp-20180821-1

**Problem** :
 `/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=10.61.1.2 --snmp-version='2c' --snmp-community='public'  --warning='80'  --critical='90'
Unknown option: warning at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.
`
**Soluce** : 
`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=10.61.1.2 --snmp-version='2c' --snmp-community='public'  --warning-core='80'  --critical-core='90'
OK: 1 CPU(s) average usage is 1.00 % - CPU '0' usage : 1.00 % | 'total_cpu_avg'=1.00%;;;0;100 'cpu'=1.00%;0:80;0:90;0;100
`
**OS**: CentOS Linux version 2.6.32-754.2.1.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Fri Jul 13 12:50:12 UTC 2018

**Comment by lpinsivy** [comment]
You right, help indicates:

```
    --warning
            Threshold warning in percent.

    --critical
            Threshold critical in percent.
```

**Comment by lpinsivy** [comment]
I close this ticket, issue is opened on correct tracker.
