### ISSUE TITLE
Centreon Compatibility with PHP 7.X

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon#6649]
---------------------------------------------------
SECURITY REPORT INFORMATION
---------------------------------------------------

I would like to know when Centreon will be compatible with the **7.X versions of PHP**. Because the PHP version currently in production and use by our Centreon environnement is vulnerable to security breaches.

**Comment by kozfelipe** [comment]
https://github.com/centreon/centreon/issues/5652

**Comment by lpinsivy** [comment]
The next major version will be compatible with PHP .7.1.x and > only.
