### ISSUE TITLE
Show poller name in poller status bar

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#672]
---

Author Name: **Damien Duponchelle** (Damien Duponchelle)
Original Redmine Issue: 4182, https://forge.centreon.com/issues/4182
Original Date: 2013-02-06

---

Hello,

When the poller status bar is showing an issue, the concerned poller name is not displayed.

It will be very powerfull to display this information in order to diagnose performance issue more easily.

Regards.

**Comment by julienmathis** [comment]
Done since a long time
