### ISSUE TITLE
Purge RRD file ?

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon#6731]
Hi,

My directory /var/lib/centreon/metrics is very big : 400Go.
Can we delete old files that are more than one day old
A metric can be composed of several rrd files over time ?

Thanks,

**Comment by bouda1** [comment]
If you don't have any check scheduled with a period of one day, and if you don't have any rrd retention, this action should not be too risky.

**Comment by romsworld** [comment]
Retetion is set for 1 year.
Is for that I ask if a metric can be composed of several rrd files over time ?

**Comment by bouda1** [comment]
No, one metric is stored in one rrd file.
My remark on retention was you should check the /var/lib/centreon-broker directory if it contains files of the form '*-rrd-*.queue.*'. That could also explain your rrd files are not updated and if you remove your rrd files older than one day, you could remove ones that you use...

**Comment by romsworld** [comment]
OK I understand, so no latency for rrd file, and no queue file is present.
So RRD file can have 1 month, or 1 year of data, it's the same things.

**Comment by bouda1** [comment]
RRD file are allocated when they are created, at that time we know how many days will be stored in them. Then, there size does not change anymore, just their content is updated. So, the only rrd files you can remove are files you don't write into anymore, obsolete files.
