### ISSUE TITLE
[2.8.26] Path for centreon-broker logs is not exported correctly

### ISSUE THREAD

**Issue by GuillaumeHAL** [centreon/centreon#6794]
**---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------**
**Centreon Web version**: 
2.8.26
**Centreon Engine version**: 
2.8.1
**Centreon Broker version**: 
3.0.14
**OS**: 
Red Hat Enterprise Linux Server release 6.9 (Santiago)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
--

Steps to reproduce the issue:
1. In Centreon GUI, in Configuration / Poller menu choose Central
2. In the middle of the form, in the "Centreon Broker" part,
3. Modify "Centreon Broker logs" path with another existent path (different to default [/var/log/centreon-broker/watchdog.log] ) .
4. Export the Central configuration (without restart)
5. On Central server, check the watchdog.xml file and the path for the log is still the default path:
 <log><![CDATA[/var/log/centreon-broker/watchdog.log]]></log>

**Describe the results you received:**
When Centreon is installed in specific paths, (not the default paths) and when I export Central configuration, the path for centreon-broker log is not the one specified in Centreon GUI.
The GUI always export the default path.

So when I start or restart cbw, the init script say that cbw is started, the pid file is created, BUT centreon-broker is not stared in fact because the default "centreon-broker log" doen't exists.
When trying to stop cbw, the message says "FAILLURE" cause pid exists and no process with this PID (maybe cbw crash cause path doesn't exists...)

**Describe the results you expected:**
Possibility to use a not-default path for Centreon-Broker logs

**Additional information you think important (e.g. issue happens only occasionally):**
--

**Comment by GuillaumeHAL** [comment]
Modifications made on my server, all is ok now !

**Comment by lpinsivy** [comment]
@GuillaumeHAL thank you for your feedback

**Comment by adr-mo** [comment]
Validated in 2.8.27 release by https://github.com/centreon/centreon/pull/6919
