### ISSUE TITLE
[centreon KnowledgeBase] - link new pages doesn't work when forces authenticating enabled

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6815]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.25
**Centreon CLAPI version**: 1.8.0
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.14
**OS**: CentOS release 6.10 (Final)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MediaWiki 1.28

**Steps to reproduce the issue:**
1. enable forced authenticating on MediaWiki with this parameter: 
   in `/var/www/html/includes/DefaultSettings.php`
   set `$wgGroupPermissions['*']['read'] = true; `

2. create a new page via centreon KB
3. wait 5 minutes for cron executes... 

**Describe the results you received:**
CentreonKB is unable to get new pages with forced authenticating
the link doesn't created on related service.

**Describe the results you expected:**
CentreonKB is enable to get new pages with or without forced authenticating
the link is created on related service

**Additional information you think important (e.g. issue happens only occasionally):**
This activation is required for certification 27001.

Thanks.

**Comment by cmeschin** [comment]
Hi @lpinsivy,
Have you any news?
It's heavy to manage because it's not the same team who create KBs and manage services configuration.

Thanks.

**Comment by lpinsivy** [comment]
@cmeschin it is not about mediawiki user configuration right?

**Comment by cmeschin** [comment]
Hi @lpinsivy ,
the user "CptCentreon" is "bureaucrate" and "administrateur" in mediawiki.

Sorry in my original post i made a mistake. I reversed true / false value.
To enable forced authenticating the option "$wgGroupPermissions['*']['read']" must be set to "false", not "true";

by default (or if not defined) this option is set to true.
In this configuration, cenrteonKB could create links in URL hosts or URL services fields.

If this option is set to false, the authenticate is required and centreonKB couldn't create links.

Regards,

**Comment by adr-mo** [comment]
**Fixed in 18.10.5**
