### ISSUE TITLE
selection filters do not persist when navigating pagination

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6831]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.25
**Centreon CLAPI version**: 1.8.0
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.14
**OS**: CentOS release 6.10 (Final)
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. check the "disabled hosts"
2. make a selection on services configuration page to have somes pages
3. navigate on next page or another one you want

**Describe the results you received:**
the checkbox is unchecked and the selection is only for hosts activated

**Describe the results you expected:**
the checkbox must be persistant when navigating pagination

**Additional information you think important (e.g. issue happens only occasionally):**

Thanks

**Comment by adr-mo** [comment]
Hi @cmeschin,

Thanks for the feedback 💯 

This issue will be fixed in the **18.10.5 release**

Regards,
