### ISSUE TITLE
selection filters do not persist when saving settings

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6832]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version: 2.8.25
**Centreon CLAPI version: 1.8.0
**Centreon Engine version: 1.8.1
**Centreon Broker version: 3.0.14
**OS: CentOS release 6.10 (Final)
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. make selection on hosts (ip address or name) to have some results
2. edit a host and save
3.

**Describe the results you received:**
filters doesn't persist and all hosts are displayed (number per page too, reset to 30).

**Describe the results you expected:**
filters must be persist

**Additional information you think important (e.g. issue happens only occasionally):**

thanks

**Comment by adr-mo** [comment]
Hi @cmeschin,

Thanks for the feedback 💯 

This issue will be fixed in the **18.10.5 release**

Regards,
