### ISSUE TITLE
Reporting uptime wrong due to new server

### ISSUE THREAD

**Issue by erottier** [centreon/centreon#6847]
**Centreon version**: 
2.8.26

**Steps to reproduce the issue:**
1. Create a new server around the 15th (month doesn't matter)
2. Wait until the end of the month
3. Get a host report the whole month (as many businesses do I guess)

**Describe the results you received:**
~50% uptime, ~50% undetermined
(depends on the de current days in the month and the exact time of host creation)

**Describe the results you expected:**
100% uptime. Because the servers was live since the 15th (in my example) it's 100% up in it's lifetime.
Because the server was created at the half-month mark, the first two weeks should not have been reported IMO.

**Additional information you think important (e.g. issue happens only occasionally):**
I don't care if it is reported as undetermined, but when I create a new server object my Uptime should not be screwed up by it as it currently is.

**Comment by lpinsivy** [comment]
Hi @erottier, that is why we have two column:
- Total time
- Mean time (should be renamed "meaning full")

Regards,

**Comment by erottier** [comment]
OK, thanks. I will use the 'mean time' for my next report.
Mean time is really misleading indeed.

I would rename it to 'Host Lifetime Up' or 'Lifetime Up' or something.
