### ISSUE TITLE
Got bogus version XX in httpd error logs

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon#6851]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10.0

**Centreon Engine version**: 18.10.0

**Centreon Broker version**: 18.10.0

**OS**: CentOS 7 with Software Collections

**Steps to reproduce the issue:**
1. Install Centreon with default httpd
2. Use Centreon web interface
3. Sometimes the following error appears.

**Describe the results you received:**

`[Mon Oct 15 14:25:47.166825 2018] [proxy_fcgi:error] [pid 19992] [client 10.42.42.42:45506] AH01068: Got bogus version 10, referer: https://mycentreon/centreon/main.get.php?p=62605`

**Describe the results you expected:**

No error at all. This seems related to apache bug [49671](https://bz.apache.org/bugzilla/show_bug.cgi?id=49671). Default CentOS 7 version of httpd is 2.4.6 (not containing fix) whereas Software Collections embed 2.4.27 (fixed).

**Comment by ganoze** [comment]
Should be fixed with Centreon 19.04.

**Comment by lpinsivy** [comment]
Closed in 19.04 by using httpd24-httpd instead og httpd
