### ISSUE TITLE
[2.8.26] - Broker RRD configuration -> RRD file directory for metrics empty

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#6867]
**Centreon Web version**: 2.6.26

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: CentOS 6.10

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMWare

**Steps to reproduce the issue:**
1. Go to Configuration  >  Pollers  >  Broker configuration
2. Open Central RRD configuration
3. Go to tab Output

**Describe the results you received:**
RRD path for metrics is empty
RRD path for status is empty

![2018-10-19 13_04_37-centreon - it network monitoring](https://user-images.githubusercontent.com/6400595/47214955-dfa20c00-d39f-11e8-84da-c9e5dfef41b6.png)

**Describe the results you expected:**
RRD path for metrics should be: /var/lib/centreon/metrics
RRD path for status should be: /var/lib/centreon/status

**Additional information you think important (e.g. issue happens only occasionally):**
For this reason the Broker are not generating the RRD-Files -> error:   RRD: could not create file '/tmpl_31104000_300_0.rrd': creating '/tmpl_31104000_300_0.rrd': Permission denied

On table cfg_centreonbroker_info in database centreon both fields are set with correct path. No idea, why path is not shown and not exportet correctly. I tried also to delete the Central RRD configuration and recreate a new but still same problem.

Thanks

**Comment by lpinsivy** [comment]
Hi @joschi99 you can configure those path in "Administration  >  Parameters  >  Options" menu:

- /var/lib/centreon/metrics/
- /var/lib/centreon/status/

rights should be "centreon-broker:centreon-broker"

**Comment by joschi99** [comment]
Hi @lpinsivy ,

I'm not able to save this options, the page is empty for the most values:
![image](https://user-images.githubusercontent.com/6400595/47900355-e9863d80-de7c-11e8-976d-2df65c871375.png)

If I check the related table on database `SELECT * FROM `cfg_centreonbroker_info` where config_id=2` the values are there.
The apache log show the error
`[Fri Nov 02 08:53:05 2018] [error] [client 192.168.120.68] PHP Warning:  array_map() [<a href='function.array-map'>function.array-map</a>]: Argument #2 should be an array in /usr/share/centreon/www/include/Administration/parameters/centstorage/form.php on line 48, referer: https://i-vertix.pgum.local/centreon/main.php?p=501&o=c`
