### ISSUE TITLE
18.10 Autodiscovery

### ISSUE THREAD

**Issue by sizeur** [centreon/centreon#6912]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10
**Centreon Engine version**: 
18.10
**Centreon Broker version**: 
18.10
**OS**: 
centreon

**Steps to reproduce the issue:**
1. Install auto-disvocery via yum and finalize the install in the web interface
2. Go to Configuration  >  Services  >  Rules and create a rule

**Describe the results you received:**
Base or table or view not found: 1146 TAble 'centreon.mod_auto_disco_instrule_relation' doesn't exist
![image](https://user-images.githubusercontent.com/13485588/47653225-53a29800-db88-11e8-97c6-c73cd5480020.png)

**Comment by tseegers** [comment]
To create the missing table i have executed the update script:
mysql -u root centreon < /usr/share/centreon/www/modules/centreon-autodiscovery-server/UPGRADE/centreon-autodiscovery-server-2.4.0/sql/upgrade.sql

But now when i scan a host in the web interface i get this error message in /var/log/messages:
Oct 29 14:25:18 centreon1810 kernel: centreon_autodi[12543]: segfault at 0 ip 00007fc0dad1baf1 sp 00007fff3c8a50a8 error 4 in libc-2.17.so[7fc0dac8f000+1c3000]

**Comment by cgagnaire** [comment]
Hi @sizeur,
Do you still have the segfault problem when launching a discovery ?
