### ISSUE TITLE
[18.10] Advanced poller configuration TLS issue

### ISSUE THREAD

**Issue by markeur** [centreon/centreon#6914]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 

**Centreon Engine version**: 18.10

**Centreon Broker version**: 18.10

**OS**: centos 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-V

**Steps to reproduce the issue:**
1. Generate all needed certificate, key, … as said in the documentation

2. Place certificate in /etc/centreon-broker/ for each central/poller
3. reload the configuration

**Describe the results you received:**
The poller and the central don't restart and the Datbase updates are not active.

*edit*: After some reload of the configuration the central become active, the poller not. The log file of the poller show that the central are not responding to TLS solicitation of the poller, it's why the poller is craching

**Describe the results you expected:**
All poller restart and the flow between the poller and the central is secured  by TLS
**Additional information you think important (e.g. issue happens only occasionally):**
![tls-issue](https://user-images.githubusercontent.com/16294256/47694087-41336780-dc37-11e8-83ac-818a948725f5.PNG)

**Comment by lpinsivy** [comment]
@bouda1 can you check if documentation is ok?

**Comment by markeur** [comment]
It's seems after the use of the switched commands of fix(doc): update installation documentation to full EL7 #6913 it's work. I will proceed to more test and confirm.

**Comment by markeur** [comment]
Ok it seems work after added all .key and .crt for the central-module-master output in addition as the doc and restart all server service with the following command systemctl restart cbd centcore centreontrapd centengine.
After reload all pollers by following documentation
I will try for a more longer time and confirm

**Comment by omercier** [comment]
Hi @markeur,
Sorry for the long wait.
I believe it is still working correctly, and I'm closing the issue.
Regards
