### ISSUE TITLE
os::windows::snmp::plugin --mode=processcount with process-path set

### ISSUE THREAD

**Issue by rodrigobiagi** [centreon/centreon#6923]
---------------------------------------------------
os::windows::snmp::plugin --mode=processcount with process-path set
---------------------------------------------------

**Centreon Web version**: 2.8.26

**Centreon Engine version**: 1.8.1 

**Centreon Broker version**: 3.0.3

**OS**: CentOS 7 

**Steps to reproduce the issue:**
Hello, I am testing latest version 2.8.26 of Centreon with CentOS 7 in the company and I encountered the following problem.
by command line the plugin works.

./centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=10.150.31.101 --snmp-community='centreon' --snmp-version='2c' --memory --process-name='AppServer.exe' --regexp-name --process-path='F:\workdir\protheus\bin\appserver' --warning 1 --critical 1: --verbose
OK: Number of current processes running: 1 - Total memory usage: 108.68 MB - Average memory usage: 108.68 MB | 'nbproc'=1;0:1;1:;0; 'mem_total'=113958912B;;;0; 'mem_avg'=113958912.00B;;;0;
Process '15096' [memory: 108.68 MB] [status: running] [name: AppServer.exe] [path: F:\workdir\protheus\bin\appserver]

for web interface has problem
Does not display metrics and even process availability
Possibly due to the process-path field,
--process-path = 'F: \ workdir \ protheus \ bin \ appserver_CRITICAL 1:'

i set fields:
PROCESSNAME - AppServer.exe
PROCESSPATH - F:\workdir\protheus\bin\appserver
CRITICAL - 1:

After save and reload Poller
Monitoring --> Status Details --> Services
and select service configured show this:

/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=10.171.67.101 --snmp-version='2c' --snmp-community='centreon' --process-name='AppServer.exe' --process-path='F:\workdir\protheus\bin\appserver_CRITICAL 1:' --process-args='' --regexp-name --regexp-path --regexp-args --warning='' --critical=''

**Comment by lpinsivy** [comment]
Hi, can you creat an issue on the [Centreon Plugins github](https://github.com/centreon/centreon-plugins) project please.

Regards,
