### ISSUE TITLE
[API REST / CLAPI] Ability to create on-demand downtime

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6925]
Hi,
Can you add the possibility to create real-Downtime with API (API REST and CLAPI)
Is was requested in #5192 but it solmved with only "New class for showing downtimes", not for create downtimes

thanks.
**Centreon Web version**: 2.8.25
**Centreon CLAPI version**: 1.8.0
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.14
**OS**: CentOS release 6.10 (Final)

**Comment by lpinsivy** [comment]
@cmeschin yes it's already done. Please access to [this chapter of documentation](https://documentation-fr.centreon.com/docs/centreon/en/18.10/api/clapi/objects/realtime_downtimes.html)
