### ISSUE TITLE
[18.10] Old session doesn't show monitoring details

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#6927]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10

**Centreon Engine version**: 18.10

**Centreon Broker version**: 18.10

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware

**Steps to reproduce the issue:**
1. Log in,
2. Wait for a long time without using the web UI (in my case, my PC goes in hibernate mode),
3. Come back to the web UI.

**Describe the results you received:**
Every menus are accessible.
Edition can be made to the configuration.
Nothing appears in the 'Monitoring > Status Details' pages.
The date and time are stucked since hibernation.

**Describe the results you expected:**
Access to data in 'Monitoring > Status Details' pages.
Date and time up to date.

**Additional information you think important (e.g. issue happens only occasionally):**
I'm not logged out when I come back from hibernate mode.
If I log out and back in, everythings fine.

**Comment by lpinsivy** [comment]
@cgagnaire for me old session should be disconnected

**Comment by omercier** [comment]
Then if the session is disconnected the user shouldn't be able to browse the menus as @cgagnaire described, but should be redirected immediately to the login screen, don't you think?
I confirm that I often get a "zombie" session when I come back after a while. I seem to have access to all the menus, but my session is actually closed, so I cannot perform any modification.

**Comment by lpinsivy** [comment]
should be solved
