### ISSUE TITLE
[18.10] Event Logs export

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#6929]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10.0

**Centreon Engine version**: 18.10.0

**Centreon Broker version**: 18.10.0

**OS**:  3.10.0-862.14.4.el7.x86_64

**Steps to reproduce the issue:**
1. Go to Monitoring  >  Event Logs
2. Export any logs

**Describe the results you received:**
javascript error: `logs is not defined`

**Describe the results you expected:**
CSV / XML

**Additional information you think important (e.g. issue happens only occasionally):**
I notice function logs (eventLogs.php) is using a formu parameter rather than formu2 https://github.com/centreon/centreon/blob/215be6733c80ddf1c4fa8d97e8bd7eb2c105d4c6/www/include/eventLogs/viewLog.php#L574

**Comment by lpinsivy** [comment]
should be corrected by #6897

**Comment by kozfelipe** [comment]
fixed in 19.04.0
