### ISSUE TITLE
Problem with composer.json (ci.int.centreon.com)

### ISSUE THREAD

**Issue by mathieuraux** [centreon/centreon#6932]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  18.10.0

**OS**: CentOs for Raspberry Pi

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Raspberry Pi

**Steps to reproduce the issue:**
1. Exec the centreon web installer : ./install.sh -i

**Describe the results you received:**
Problem with one step, i can't install some PHP dependencies because the following URL is no longer available : ci.int.centreon.com

This is the error 

  [Composer\Downloader\TransportException]
  The "http://ci.int.centreon.com/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by ganoze** [comment]
This was fixed by PR #7160 (included in Centreon Web 18.10.4).
