### ISSUE TITLE
Servicegroup-Dropdown in relation with ACL does not work properly

### ISSUE THREAD

**Issue by cfuck** [centreon/centreon#6935]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.8

**Centreon Engine version**: 1.7.2

**Centreon Broker version**: 3.0.14

**OS**: lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.10 (jessie)
Release:        8.10
Codename:       jessie

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare 

**Steps to reproduce the issue:**
1. Create new user
2. Create own Resource Access with access to one Servicegroup 
3. Map Resources Access to Access Group 
4. Map User to Access Group

**Describe the results you received:**
If I log in with the new user I am unable to use the Servicegroup dropdown (Monitoring->Status Details). 
We tried with one servicegroup and with more than one servicegroup.
If we log in with the admin user, we are able to see all servicegroups in the dropdown.

**Describe the results you expected:**
We expect to see the all mapped servicegroups in the dropdown on page "Monitoring->Status Details".

**Comment by lpinsivy** [comment]
Ok on Centreon Web 2.8.25

Create an user
Create an "Ressources Access" with access to 1 servicegroup
Create an "Access Groups" and link this one to the user and link too the Resource Access
Connect with the user, the servicegroup is available in "Monitoring > Status Details" pages
