### ISSUE TITLE
Save host config - connection reset and settings not saved

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon#6940]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.26

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: Centos

**Additional environment details (AWS, VirtualBox, physical, etc.):** AWS

**Steps to reproduce the issue:**
1. Open host configuration
2. Save settings
3. Get connection reset error on browser and settings not saved

**Describe the results you received:** connection reset error on browser

**Describe the results you expected:** Saving host settings

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

With kind of browser do you use?
how many minutes do you sty on form before click on "Save button"?

**Comment by adr-mo** [comment]
Hi @R00T88 

No answer given for now more than **2 months**.

Closing this issue.

Regards,
