### ISSUE TITLE
Proxy & Plugin Pack manager

### ISSUE THREAD

**Issue by sizeur** [centreon/centreon#6941]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10
**Centreon Engine version**: 
18.10
**Centreon Broker version**: 
18.10
**OS**: 
18.10

Helllo,

Our Centreon server connects to the internet by proxy. Our proxy opens the SSl connections, checks it and reencrypts it.
This leads to the situation that the SSL traffic is not encrypted by the original certificate but by a self-signed certificate of the proxy.
(for example we have to use the option --no-check-certificate when using wget).

We have the problem that the Plugin Packs Manager shows nothing and the “Test Proxy Configuration” in Administration/Parameter fails.
There is no option telling Centreon to ignore that the certificate is a self-signed one.

So we changed /usr/share/centreon/www/class/centreonRestHttp.class.php to deactivate ssl verification, we added the line
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

Could we add an option in the web interface to add this functionality ?

**Comment by lpinsivy** [comment]
Hi @sizeur the best way is to install your proxy certificate on Centreon server to do no use this option or to use non-self-signed certificate
