### ISSUE TITLE
[18.10] services issue on poller

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon#6944]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10

**Centreon Engine version**: 18.10

**Centreon Broker version**: 18.10

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. install Poller from 18.10 ISO
2. 
3.

**Describe the results you received:**
1-centengine.service is not running
2-cbd.service is not existing

**Describe the results you expected:**
Poller working as a kind poller

**Additional information you think important (e.g. issue happens only occasionally):**
Centreon Central updated from 2.8.26 to 18.10 like a charm
Poller was on CentOS6 so I installed a new one to replace the old one.
I can see a running poller in Centreon Web when I 'systemctl start centengine.service' on poller but it doesn't receive any action (acknowledge, downtime,...)
By debugging, I conclude there is no cbd.service on my brand new poller.
cbd file/folder present in system twice : 
/etc/logrotate.d/cbd
/etc/sudoers.d/centreon

Yours faithfully

**Comment by Pilow974** [comment]
Check /var/log/auth.log for errors... if the poller has same ip address as old one, you could have a 'known hosts' issues with ssh (new key on new poller, old key on central).

**Comment by oasisck** [comment]
I double checked that. User centreon ssh perfectly to poller
I even generated a new key to be sure
The old one is shutdown

**Comment by lpinsivy** [comment]
@oasisck thank you for your feedback.

Unfortunately, event if we set in RPM package auto start for Centreon service, those action are not performed.
We are currently updating the documentation.
Can you execute the following actions on your poller:

```
# systemctl enable centreontrapd
# systemctl enable cbd
# systemctl enable centengine

# systemctl start centreontrapd
# systemctl start cbd
# systemctl start centengine
```

**Comment by oasisck** [comment]
done
```
[root@poller1 ~]# systemctl enable centreontrapd
centreontrapd.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig centreontrapd on
[root@poller1 ~]# systemctl enable cbd
Failed to execute operation: No such file or directory
[root@poller1 ~]# systemctl enable centengine
Created symlink from /etc/systemd/system/multi-user.target.wants/centengine.service to /usr/lib/systemd/system/centengine.service.
[root@poller1 ~]# systemctl start centreontrapd
[root@poller1 ~]# systemctl start cbd
Failed to start cbd.service: Unit not found.
[root@poller1 ~]# systemctl start centengine

```

**Comment by kozfelipe** [comment]
> I conclude there is no cbd.service on my brand new poller.

yes, you are right

> I can see a running poller in Centreon Web when I 'systemctl start centengine.service' on poller but it doesn't receive any action (acknowledge, downtime,...)

I had the same issue when I added my poller throught wizard. I managed to get it working by manually insert.

I notice after wizard first executtion, it doesnt work anymore. The poller-wizard page removes itself

**Comment by oasisck** [comment]
I installed, enable and start centreon-broker-cbd on poller but no change from centreon-web

**Comment by kozfelipe** [comment]
mine is working without cbd service

**Comment by oasisck** [comment]
> mine is working without cbd service.
> I followed these steps https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/poller/02configuration.html

I double checked that too. Anyway, I renamed poller, broker-poller, engine-poller in -old and disabled all for following your guide => same thing, Poller is up, supervision work on existant hosts but no actions work on a host supervise by my poller (e.g disable notification on service, force check,...)

Can you confirm me that you installed a poller with the new ISO and actions work ?

**Comment by kozfelipe** [comment]
yes my recent poller was created by the new ISO

![image](https://user-images.githubusercontent.com/25208457/48129299-36e51f00-e270-11e8-9dd8-641461494195.png)

![image](https://user-images.githubusercontent.com/25208457/48129363-6e53cb80-e270-11e8-8bc7-1d52ab23c21e.png)

![image](https://user-images.githubusercontent.com/25208457/48129382-77dd3380-e270-11e8-863a-8daff3be00bb.png)

![image](https://user-images.githubusercontent.com/25208457/48129401-8297c880-e270-11e8-8dad-9c8b8a89a812.png)

![image](https://user-images.githubusercontent.com/25208457/48129593-21242980-e271-11e8-9d19-d278d4af6fae.png)

**Comment by oasisck** [comment]
I have exactly same parameters (except Sao Paulo ;-) )

I found a workaround : new poller from 3.4.6 ISO upgrade to 18.10 => like a charm
And indeed, even in 3.4.6, there isn't cbd.service. Only centengine.service and centreontrapd are presents for a poller.

Maybe update documentation about services on poller to avoid confusion about that.

Thanks
