### ISSUE TITLE
It seems that centreon_synology.pl does not work anymore with --warning and --critical, even whith --warning-usage and --critical-usage. For example

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon#6945]
/usr/lib/centreon/plugins/centreon_synology.pl --mode cpu --hostname 10.91.96.16 --warning-usage 90 --critical-usage 95.
Updated today with Global Version: 20181019

_Originally posted by @stefanotoro in https://github.com/centreon/centreon/issue_comments#issuecomment-436302122_

**Comment by stefanotoro** [comment]
I tried with --warning-average and --critical-average and it work. It is the really the new arguments?
Thank you

**Comment by stefanotoro** [comment]
For information, for us, same changes apply for plugins:
- centreon_freebsd_snmp.pl
- centreon_linux_snmp.pl
- centreon_windows_snmp.pl

**Comment by vince1408** [comment]
Same problem, I use : centreon_linux_snmp.pl and centreon_windows_snmp.pl
Exemple : 
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=x.x.x.x --snmp-version='2c' --snmp-community='xx'  --warning-usage '80'  --critical='90'

Unknown option: warning-usage at /usr/lib/centreon/plugins/centreon_linux_snmp.pl line 142.

Thanks

**Comment by cgagnaire** [comment]
Hi,
As stated in the plugin help, it is now --warning/critical-average/core.
