### ISSUE TITLE
Centreon-plugins "execute command failed"

### ISSUE THREAD

**Issue by yauckburally** [centreon/centreon#6947]
Hello, I'm implementing a snmp check with centreon-plugins.pl to monitor disks states on a Fujitsu DX storage system.

The command is : 

$USER1$/centreon-plugins/centreon_plugins.pl --plugin=snmp_standard::plugin --mode string-value --hostname $HOSTADDRESS$ --snmp-community $_HOSTSNMPCOMMUNITY$ --snmp-version $_HOSTSNMPVERSION$ --oid-table .1.3.6.1.4.1.211.1.21.1.150.2.19.2.1.3 --map-values='2=>broken,4=>notsupported,5=>present,6=>readying,7=>recovering,64=>partbroken,66=>formatting,67=>unformatted,68=>notexist,69=>copying' --filter-table-value='^((?!3).)*$' --format-ok='%{filter_rows} Disques detectes en bon etat' --critical-regexp='broken|notsupported|present|readying|recovering|partbroken|formatting|unformatted|notexist|copying' --format-critical='Etat %{details_critical} Detecte'

When I execute the command directly on the shell and replacing macros with good values,it's working.
But The service in Centreon returns "Execute command failed".
In centengine.log i got this line : 
Error: Service check command execution failed: missing separator '''

The box "Enable Shell" is checked on the command.

Do you know what I'm missing ?

Thanks

**Comment by Pilow974** [comment]
did you try to escape all special characters ? even if Enable Shell is checked ?
