### ISSUE TITLE
Problem after update to 18.10 

### ISSUE THREAD

**Issue by und3ath** [centreon/centreon#6949]
Hi . After upgrading centreon to 18.10.0 and upgraded remote poller according to the documentation we cannot generate configuration for the poller . 
When we click on generate configuration file , it stuck at 0% and nothing is done. 

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 28.10.0

**Centreon Engine version**: 28.10.0

**Centreon Broker version**: 28.10.0

**OS**: Centos 7

**Comment by ebourgui** [comment]
Hi. I've had the same problem. I cleared my webbrowser's cache and now it works!

**Comment by und3ath** [comment]
thanks , it's seems to work now , but it take up to 3min to generate configurations files .

**Comment by lpinsivy** [comment]
@ebourgui @und3ath thank you for your feedback.

So everything works correctly now?

**Comment by und3ath** [comment]
No, sometimes it take few minutes and generate configs files with success , sometime it get stuck at 0% . 

We have 9 pollers only one for now is upgraded to 18.10.0 . This strange behaviour is present on updated and non updated pollers . 

![test](https://user-images.githubusercontent.com/15632488/48134175-73794080-e299-11e8-8e33-d293ec7eea21.png)

**Comment by und3ath** [comment]
It seems to be working using clapi to generate, move and reload poller ;
the timestamp of file are updated under /usr/share/centreon/filesGeneration. 
Otherwise if i generate config with web interface it seems files are not generated at all .

**Comment by und3ath** [comment]
I figured out after reviewing the code under https://github.com/centreon/centreon/blob/master/www/include/configuration/configGenerate/xml/generateFiles.php#L110

A Fw rules has been modified and our ldap was not reachable . (timeout and breaking process) 
After fixing firewall rules averything seems to work correctly now !

**Comment by wackou72** [comment]
Hello,
mine is also slow, when connecting to the webinterface, it take arround 10 sec or more to connect with an AD account.
Generating the conf take arround 20 sec/30 sec.

**Comment by jben94** [comment]
Hi,

It is the synchronization of information between LDAP and Centreon which is long. For me, it's 2 minutes !
In particular, the 'syncWithLdap()' function in the 'CentreonContactgroup' class. She will pick up all members of all groups to update Centreon.

it would be better to put this synchronization in crontab, no?

```
./class/centreonAuth.LDAP.class.php:                    $cgs->syncWithLdap();
./class/centreonContactgroup.class.php:    public function syncWithLdap()
./include/configuration/configGenerate/xml/generateFiles.php:    $cgObj->syncWithLdap();
```

**Comment by itsul** [comment]
Hi,

I can confirm this, too.
But with Centreon 2.8.26 (Central + 8 Poller, 70k Services).
Export takes over 90 seconds, when I comment the syncWithLDAP function in generateFiles.php it goes down to 30. We must use nested ldap groups, so this might have also an performance impact.
I think it's a good idea, to undock it from the exporting function.

**Comment by lpinsivy** [comment]
#7130
