### ISSUE TITLE
Mark all hosts UNREACHABLE when poller is down

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#695]
---

Author Name: **Bruno Legros** (Bruno Legros)
Original Redmine Issue: 3267, https://forge.centreon.com/issues/3267
Original Date: 2012-04-26

---

Automaticaly mark all hosts UNREACHABLE (or "not supervised") when the concerned poller is down.

This will avoid to have non-up-to-date status on the interface.

**Comment by lpinsivy** [comment]
solved
