### ISSUE TITLE
Unable to edit commands?

### ISSUE THREAD

**Issue by jakefoster2018** [centreon/centreon#6950]
Just deployed 18.10 and for some reason i cant edit the commands that are pre-installed?  Any new commands i create i can edit - but those that are pre-installed (or part of a plugin pack i guess) are greyed out and when i click on them it doesnt allow me to edit them?

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon version**:  18.10

**OS**:  Centos 7.5

**Additional environment details (AWS, VirtualBox, physical, etc.):** running in azure

**Steps to reproduce the issue:**
1. Configuration
2.Commands
3.Select Any pre-installed command
4. unable to edit the command

**Describe the results you received:**
Unable to edit the command

**Describe the results you expected:**
I should be able to edit the command

**Comment by lpinsivy** [comment]
Hi @jakefoster2018 , with command do you try to edit ?

**Comment by jakefoster2018** [comment]
Literally any command that is out of the box isnt available to edit, I click into the command and it doesn’t allow me to edit it:

[cid:image001.png@01D4769E.83E091B0]

[cid:image004.jpg@01D4769E.83FAF780]

Centreon goes into ‘View command’ rather than ‘modify command’

Kind Regards,
Jake

Planned Absence: NA
Click<https://outlook.office365.com/owa/calendar/c1f8b536cf3f4b22b4e1be598a4e9c15@prosperity247.com/aa19aba4a1394af29f86740b592d8f6f2170893118312489449/calendar.html> for my schedule

**Comment by adr-mo** [comment]
Hi @jakefoster2018 

Commands from Plugin Packs **can't be edited**.

Closing this issue.

Regards,
