### ISSUE TITLE
Add en_GB locale

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#6954]
Hi,

Could it be possible to add `en_GB` (`.UTF8` ?) locale so that we can have time in 24h format in the new banner ?

![screen shot 2018-11-07 at 22 10 27](https://user-images.githubusercontent.com/40244829/48161075-fe7a2b00-e2d9-11e8-85f6-d87d4312c9d8.png)

Thank you very much 👍 

Edit : issue still present in 19.10.10.

**Comment by lpinsivy** [comment]
@CPbN We plan in our backlog to have the possibility to choose 12H or 24H format.

Thank you for your feedback

Regards,

**Comment by CPbN** [comment]
Perfect thank you @lpinsivy :+1:

**Comment by leo29041982** [comment]
issue still present in 19.10.4.!

**Comment by UrBnW** [comment]
Closing this as there's already #6550.
