### ISSUE TITLE
Add macro HOSTCATEGORY and SERVICECATEGORY in notifications

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6956]
---------------------------------------------------
ENHANCEMENT
---------------------------------------------------

**Centreon Web version**: 2.8.25
**Centreon CLAPI version**: 1.8.0
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.14
**OS**: CentOS release 6.10 (Final)

We have already HOSTGROUPNAME, HOSTGROUPALIAS, SERVICEHOSTALIAS and SERVICEHOSTNAME.

Can you add the macros below for notifications:
- HOSTCATEGORYALIAS
- HOSTCATEGORYNAME
- SERVICECATEGORYALIAS
- SERVICECATEGORYNAME

Thanks.

**Comment by omercier** [comment]
Thanks @cmeschin! 
I added it to my backlog.
