### ISSUE TITLE
Doc : Exchange key for RS , missing command 

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#6958]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
When following RS installation doc (administration guide), user comes in this page:

administration_guide/poller/ssh_key.html

No mention of how to set a password for user Centreon

![image](https://user-images.githubusercontent.com/25612980/48202837-48105780-e366-11e8-9481-0a0737e22204.png)

Whereas it is written in installation/from_VM.html#connexion

![image](https://user-images.githubusercontent.com/25612980/48202794-257e3e80-e366-11e8-8e71-b245218a6f34.png)

**Comment by adr-mo** [comment]
**Fixed and merged**

Closing this issue.
