### ISSUE TITLE
Problem Upgrade to 18.10

### ISSUE THREAD

**Issue by barte91** [centreon/centreon#6960]
---------------------------------------------------
PROBLEM REPORT INFORMATION
---------------------------------------------------

Centreon Web version: 18.10.0 

Centreon Engine version: 18.10.0 

Centreon Broker version: 18.10.0 

OS: CentOS 7

Additional environment details (AWS, VirtualBox, physical, etc.):VM on VMware

Steps to reproduce the issue:
I've a problem when I upgrade from Centreon 2.8.26 to 18.10, my VM is Centos 7, when I update to 18.10, I can't see the menu like you see below:

![centreonproblem](https://user-images.githubusercontent.com/19166634/48258541-97619100-e415-11e8-83c0-f92e064970d8.JPG)

Anyone can help me?

**Comment by barte91** [comment]
I see also this error in /var/log/httpd/error.log

>  [proxy:error] [pid 28005] AH00959: ap_proxy_connect_backend disabling worker for (1.1.1.1) for 60s
> [proxy_fcgi:error] [pid 28005] [client 1.1.1.2:15098] AH01079: failed to make connection to backend: 1.1.1.1

I read can be an error on php-fpm... can you explain me how can I check this?

**Comment by lpinsivy** [comment]
Hi

Did you try to clean the cache of your browser?

**Comment by barte91** [comment]
Hi, 

Yes, I've already try to clean the cache but the problem still again.
Now I try to delete the VM and re-try to update to 18.10, now I've a different problem, there is some wrong on my httpd, when I go to my centreon on web i see the error:

> "Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
> More information about this error may be available in the server error log."

In my log on httpd I see this lines:

> [Tue Nov 20 11:38:40.747839 2018] [mpm_prefork:notice] [pid 2148] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16 configured -- resuming normal operations
[Tue Nov 20 11:38:40.747878 2018] [core:notice] [pid 2148] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Tue Nov 20 11:38:42.312668 2018] [core:alert] [pid 2154] [client myClient:9147] /usr/share/centreon/www/.htaccess: RewriteRule not allowed here, referer: http://192.168.100.112/centreon/main.php?p=20201&o=svc_critical&search=
[Tue Nov 20 11:38:42.515651 2018] [core:alert] [pid 2155] [client myClient:9148] /usr/share/centreon/www/.htaccess: RewriteRule not allowed here, referer: http://mycentreonIP/centreon/main.php?p=20201&o=svc_critical&search=
[Tue Nov 20 11:38:42.540579 2018] [core:alert] [pid 2156] [client myClient:9149] /usr/share/centreon/www/.htaccess: RewriteRule not allowed here, referer: http://mycentreonIP/centreon/main.php?p=20201&o=svc_critical&search=
[Tue Nov 20 11:38:42.541194 2018] [core:alert] [pid 2157] [client myClient:9150] /usr/share/centreon/www/.htaccess: RewriteRule not allowed here, referer: http://mycentreonIP/centreon/main.php?p=20201&o=svc_critical&search=
[Tue Nov 20 11:38:56.416434 2018] [core:alert] [pid 2158] [client myClient:9155] /usr/share/centreon/www/.htaccess: RewriteRule not allowed here, referer: http://mycentreonIP/centreon/main.php?p=20201&o=svc_critical&search=
[Tue Nov 20 11:42:42.262908 2018] [core:alert] [pid 2155] [client myClient:9385] /usr/share/centreon/www/.htaccess: RewriteRule not allowed here

It seems like my httpd load a PHP 5.4 nd not PHP7.1, do you know why? can you explain me how to resolve the error?
Thansk a lot for you help!!!

**Comment by barte91** [comment]
Resolved by reconfigure apache
