### ISSUE TITLE
Not check services with scheduling config to Normal Check Interval

### ISSUE THREAD

**Issue by ragansis** [centreon/centreon#6964]
Last version 2.8.24 of I have the center, in the Service Scheduling option when I set the Normal option Verification interval with value of zero (0) or blank, it does not take the default value (5), so it does not check In no interval of time, the Interval Leght option has a value of 30, can anyone help me?

**Comment by lpinsivy** [comment]
@ragansis if your service inherit from a template and if the value is defined in your template your service will use this value or the overwritten value.
