### ISSUE TITLE
some database poller updates are not active

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#6968]
Hi all, 

I have a small problem with my monitoring since this morning it does not update the configuration and the "last updated" filed is yellow on all my pollers including central.
![image](https://user-images.githubusercontent.com/28105870/48432677-fa805a00-e76c-11e8-9a9a-38646559e99b.png)

I have restarted cdb, centengine without success. 
On log files i haven't find any clue.
Can anyone help please ?

Thank you

**Comment by markeur** [comment]
Hey @saharawolf,
I had the same problem can you try to update the configuration (in centreon central) after apply the following command servicectl restart cdb centcore centengine centreontrapd
and wait for couple of minutes

Regards.

**Comment by lpinsivy** [comment]
Thank you for your feedback, we will try to manage this.
Some time it takes few minutes to update this menu.

**Comment by wmariuss** [comment]
> Hey @saharawolf,
> I had the same problem can you try to update the configuration (in centreon central) after have applied the following command systemctl restart mysql httpd cdb centcore centengine centreontrapd
> and wait for couple of minutes
> 
> Regards.

We have same issue started today. So your solution does not work in our case.

**Comment by omercier** [comment]
Hi,
I believe this has been fixed a while ago.
Feel free to open a new issue with an up-to-date version of Centreon.
Regards
