### ISSUE TITLE
[18.10] Centreon Remote Server Add - Config file name attribute for cbd-broker and cdb-rrd

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#6977]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon version**: 18.10

**OS**: Redhat 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Add a Remote Server using the wizard

**Describe the results you received:**
Centreon Broker's files are automatically generated by Centreon. But the "Config file name" attribute is not central-broker.xml and central-rrd.xml which is the default name of cbd. Instead of having central-broker.xml and central-rrd.xml you have [SERVERNAME]-broker.xml and [SERVERNAME]-rrd.xml.
When you export the config and restart cbd on the Remote Server Centreon Broker doesn't work correctly.

**Describe the results you expected:**
You should have central-broker.xml and central-rrd.xml.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi @lolokai,

For a new server, the name of Centreon Broker configuration files will contain the name of the server.

Which error do you have?

**Comment by lolokai** [comment]
It works now :) Maybe I was too impatient sorry
