### ISSUE TITLE
[18.10] Add a Centreon Remote Server - Centreon Connector path is empty

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#6978]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10

**OS**: RedHat 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Create a Centreon Remote Server
2. 
3.

**Describe the results you received:**
The field Centreon Connector path is empty

**Describe the results you expected:**
The field Centreon Connector path should be : /usr/lib64/centreon-connector

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
@lolokai can you confirm that if you had a new server using wizard is the same?

Regards,

**Comment by lolokai** [comment]
Yes I confirm
