### ISSUE TITLE
[18.10] Centreon Remote Server Add - Brokername contains "." or another special characters

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#6979]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10

**OS**: RedHat 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Add a Centreon Remote Server with a servername contains "." or another special characters
2.
3.

**Describe the results you received:**
Centreon Broker refuse to start because the name of the config contains a special characters. Log file :
Centreon Broker 18.10.0 log file opened
[1542363211] config:  state applier: broker_name is not  valid: allowed characters are ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 -_

**Describe the results you expected:**
Make Centreon Broker works with special characters or replace special characters by acceptable character

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Resolved by #7133
