### ISSUE TITLE
[Export] Lots of CONTACT definitions in exports, size of export *20

### ISSUE THREAD

**Issue by Tagazoc** [centreon/centreon#6981]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.26-3

**Centreon Engine version**: 1.8.1-1

**Centreon Broker version**: 3.0.14-1

**OS**: Centos 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Export everything with `centreon -u admin -p centreon -e`

**Describe the results you received:**
My export file has a size of 136 MB, usually 6,7 MB. It is filled with "CONTACT;ADD" and "CONTACT;addparam" lines at 99%. It takes a lot of time and generates Centreon warnings.

**Describe the results you expected:**
An export with less than 255018 lines for each contact.

**Additional information you think important (e.g. issue happens only occasionally):**
I searched a bit and I think I found the problem, it has to do with the fact that "`contact alias`" is used where "`contact name`" were previously used (enhancements on exports in 2.8.25 ?). There are typos in several files in directory `/usr/share/centreon/www/class/centreon-clapi`, where "`contact_name`" must be replaced by "`contact_alias`" :

- `centreonService.class.php`, line 1559 : double typo, exports is on `$element['contact_name']` instead of $celement['contact_alias']
- `centreonHost.class.php`, line 1305 : `contact_name` instead of `contact_alias`
- `centreonServiceTemplate.class.php`, line 1069 : `contact_name` instead of `contact_alias`
- `centreonHostGroupService.class.php`, line 1074 : here, the `$celements` var gets "`contact_name`" parameter (why ?), but export is on "`element['contact_name']`" instead of "`celement['contact_name']`".

Of course I don't understand all aspects of the code, so those corrections may not be sufficient for all usages, but for me it was and I got back my 6,7 MB export size.

Keep up the good work
Tagazoc

**Comment by cgagnaire** [comment]
Fixed somewhere
