### ISSUE TITLE
Widget Host monitoring empty when filter on severity

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#6988]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10
**Centreon Engine version**: 
18.10
**Centreon Broker version**: 
18.10

**Additional environment details (AWS, VirtualBox, physical, etc.):**
centreon-widget-host-monitoring-18.10.0-11.el7.centos.noarch

**Steps to reproduce the issue:**
1. Add a widget Host Monitoring and configure a filter 'ORDER BY' - 'Severity'
![image](https://user-images.githubusercontent.com/13485588/48889364-e6f08580-ee35-11e8-8fd2-116ab7ede169.png)

**Describe the results you received:**
The widget remains empty, even if you have severties set on host/services

![image](https://user-images.githubusercontent.com/13485588/48889391-0a1b3500-ee36-11e8-91e0-4fdb18cad048.png)
![image](https://user-images.githubusercontent.com/13485588/48889443-3cc52d80-ee36-11e8-8a12-d33dfecc4dde.png)

**Comment by loiclau** [comment]
#7104
