### ISSUE TITLE
[2.8.26] No file locking when writing to centengine.cmd?

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#6989]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.26

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: CentOS 6

**Additional environment details (AWS, VirtualBox, physical, etc.)**: Physical

**Steps to reproduce the issue:**
1. Have an installation with many passive services (perl scripts, writting in centengine.cmd, flocking implemented)
2. Use also SNMP-Traps

**Describe the results you received:**
The external commands from the snmp traps are sometimes written right into other external commands.
In the best case, the command could not be  processed or just the output is damaged.
But it'salso possible, that the perfdata part is mixed up resulting in creating new garbage metrics.

In the engine log it looks just like this:
`[1542784926] [5765] EXTERNAL COMMAND: PROCESS_SERVICE_CHECK_RESULT;mysystem01;passive_service_by_perl;0;OK: Just some text that is interrupted just here[1542784925] PROCESS_SERVICE_CHECK_RESULT;mytrapsystem;trap_GlobalHealth;2;GlobalHealth: 4 (1=OK, 4=Degraded, 7=Down) - CS-SNMP_Mgr VLP0 4 Global System State`

**Describe the results you expected:**
The external command regarding the trap should be written after the one before.

**Additional information you think important (e.g. issue happens only occasionally):**
In the past, we had the additional problem, when two external scripts where writing into centengine.cmd, they were mixed up too. The problem was much more intensive.
So we implemented a file locking in all our external perl scripts like this:

```
use Fcntl ':flock';
<somecode>
open(CMD,"+<$cmdFile")||$np->nagios_die("cant open $cmdFile for writing passive checks");
flock(CMD, LOCK_EX) ||$np->nagios_die("cant lock $cmdFile");
print CMD $txt;
close(CMD);
<othercode>
```

So we looked into centreontrapd.pm and centcore.pm (on the central, centreontrapd.pm writes into centcore.cmd?) and both writes directly in the cmdfile. Is there some kind of file locking missing there? Or do you have an idea, what we can change to avoid this?
Thanks in advance!

**Comment by lpinsivy** [comment]
Hi @itsul 

Somme PR have been performed on Centreon 18.10: 
https://github.com/centreon/centreon/pull/6797
https://github.com/centreon/centreon/pull/6888

Can you try this?

Regards,

**Comment by adr-mo** [comment]
Hi @itsul 

No answer given for more than **2 months**

Closing this issue.

Regards,
