### ISSUE TITLE
Mistake in the translation 'visualisation'

### ISSUE THREAD

**Issue by sizeur** [centreon/centreon#6991]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10
**Centreon Engine version**: 
18.10
**Centreon Broker version**: 
18.10

This is a mistake in the english translation of the menu:
![image](https://user-images.githubusercontent.com/13485588/48902977-7d36a280-ee5a-11e8-8ee3-e63d607042e1.png)

In english Visualisation => Visualization 

Besides i am not sure Visualization is the best translation, maybe 'overview' would be better ?

**Comment by Moujimouja** [comment]
Hi,

Thanks for your feedback, this menu has been reworked so you don't have this error in 19.10.x nor 20.04.x.

I close this issue
