### ISSUE TITLE
Mediawiki package missing on 18.10 repository

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#6992]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10
**Centreon Engine version**: 
18.10
**Centreon Broker version**: 
18.10

Hello, 

The mediawiki package is missing on the centreon 18.10 repository:

![image](https://user-images.githubusercontent.com/13485588/48909291-29818480-ee6d-11e8-97e5-56bee3df4c5c.png)

![image](https://user-images.githubusercontent.com/13485588/48909474-aad91700-ee6d-11e8-94e0-268cbc9721be.png)

**Comment by lpinsivy** [comment]
@tseegers we don't want anymore to add external packages in Centreon repository.
The user have to follow official documentation of mediawiki.

Regards,
