### ISSUE TITLE
Service Notification issue / Inherit contact from host

### ISSUE THREAD

**Issue by magicbret** [centreon/centreon#6999]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.24

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.14

**OS**: CentOS Linux release 7.5.1804

**Additional environment details (AWS, VirtualBox, physical, etc.):** VMware hosted

**Steps to reproduce the issue:**

1. Create a service with the following notification configuration
- Notification Enabled : Yes
- Inherit only contacts/contacts group from host : No
- Implied Contacts : Empty
- Contact additive inheritance : Not checked
- Implied Contact Groups : Empty
- Contact group additive inheritance : Not checked

2. Link this service to a host that already have a notification contact associated

3. Generate and move the configuration

**Describe the results you received:**
In the services.cfg file, i can see a line with the contact that is configured in the host

host_name                       TEST 
    service_description        PING 
    contacts                       John_Doe 
    notification_period        NOC-Hours 
    register                        1 
    notifications_enabled    1

**Describe the results you expected:**
As i set "**Inherit only contacts/contacts group from host : No**", i expect to not have any contact info in the service. So even if service notification are enabled, i should not receive any email.

This situation could happen if you delete a contact that was associated to 1 or several services. The contact field will be empty but the service notification enabled, as i specified no inheritance, i should not receive any email

**Additional information you think important (e.g. issue happens only occasionally):**
The host and services configuration has been exported from a old version of Centreon (2.6.6) with CLAPI and imported in the new one.
In the Old Centreon, the same configuration did not generated any email

**Comment by magicbret** [comment]
Nobody ? 

For info, here is the SQL request that shows the services for which the notification is enabled but whitout any contact or contactgroup and with the inheritance disabled.

> SELECT 
  host.host_name
, service.service_description 
, service.service_id
, service.service_notifications_enabled
, service_inherit_contacts_from_host
, host_service_relation.service_service_id
, host_service_relation.host_host_id AS hsr_host_id
, host.host_id AS host_id
FROM 
  centreon.service as service
  LEFT JOIN  centreon.contact_service_relation as contact_service_relation
  ON service.service_id = contact_service_relation.service_service_id
  LEFT JOIN centreon.contactgroup_service_relation as contactgroup_service_relation
  ON service.service_id = contactgroup_service_relation.service_service_id
  JOIN centreon.host_service_relation as  host_service_relation
  ON service.service_id = host_service_relation.service_service_id
  JOIN centreon.host as host
  ON host.host_id = host_service_relation.host_host_id
 where contact_service_relation.contact_id is null and contactgroup_service_relation.contactgroup_cg_id is null and service.service_notifications_enabled='1' and service_inherit_contacts_from_host='0';

**Comment by lpinsivy** [comment]
Hi @magicbret,

If you doesn't defined any contacts or contactgroups of your services (using template or not). The scheduler will get contacts/contactgroups from host automatically.

Regards,
