### ISSUE TITLE
Host / Service widgets clear selected items when autorefreshing

### ISSUE THREAD

**Issue by lordtaki** [centreon/centreon#7001]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: centreon-web-2.8.26-3.el7.centos.noarch

**Centreon Engine version**: centreon-engine-1.8.1-1.el7.centos.x86_64

**Centreon Broker version**: centreon-broker-3.0.14-1.el7.centos.x86_64

**OS**: 3.10.0-514.2.2.el7.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Widgets : 1.6.3

**Steps to reproduce the issue:**
1. Select multiple hosts or services via the widget
2. Wait for the automatic refresh

**Describe the results you received:**
All previous selected items are cleared of selection

**Describe the results you expected:**
All previous selected items are still selected after the refresh

**Additional information you think important (e.g. issue happens only occasionally):**
Problem does not exist when using Monitoring / Status Details view

**Comment by adr-mo** [comment]
Hi @lordtaki, 

This issue has been fixed with the new version 18.10.1 of the widget.

(_related commit: https://github.com/centreon/centreon-widget-host-monitoring/commit/041d50bc2e0d0ff229d3d39023ce19816ca9deec_)

Closing the issue.

Thanks again for your feedback :100: 

Regards,

**Comment by lordtaki** [comment]
Hi @adr-mo,
we are using, for the moment, centreon 2.8.26 and centreon-widget-service-monitoring-1.6.3-1.el7.centos.noarch.
Can we apply only this commit?

**Comment by adr-mo** [comment]
Hi @lordtaki,

The patch has been done also for the **1.6.x** branch of the widgets.
I'll notice our **Release Manager** so that we can release a new version of those widgets (_in 1.6.x version_)

Regards
