### ISSUE TITLE
[2.8.26] ACL for admin user

### ISSUE THREAD

**Issue by kabreu** [centreon/centreon#7007]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.26

**Centreon Engine version**:  1.8.1

**Centreon Broker version**: 3.0.14

**OS**:  CentOS7

**Steps to reproduce the issue:**
1. Create an **admin** user
2. In the user configuration -> Centreon authentication, associate the user with an ACL

**Describe the results you received:**
In the ACL page, the number of contact is updated but inside the ACL configuration, the admin user isn't present and you can't remove him.

**Describe the results you expected:**
Can't add user to ACL (since admin user have all the right and don't need to be added to ACL) or don't update the numbers of contacts or make it so the user appears in the ACL configuration menu.

**Additional information you think important (e.g. issue happens only occasionally):**
If you create a non admin user, add it to ACL, then give him admin rights, same thing happens. User is disapearing from the ACL, but the number of contact doesn't change.

**Comment by kozfelipe** [comment]
if I am correct, ACL users can only view contacts from their own ACL group. In my opinion, they should at least visualize them

**Comment by lpinsivy** [comment]
Admin doesn't have ACL
