### ISSUE TITLE
Templates reset option

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon#7008]
Hi,

I would like to propose a option/button to add to Centreon monitoring host and service configuration - template reset.
It would be really good to have option to reset all configuration to be template based with only one click, by that I mean if the service or host is configured using templates and somebody adds or changes any of the parameters inside the host or service configuration (not in template), then there would be a option to reset to template defaults. Also it would be good to have in host or service configuration list view some indicator, that shows, if only template defaults are being used or not.

Why there is a  need for this - it is almost impossible to understand (or takes forever to look it up) what has been configured manually in the host or service. Sometimes there a a need to test some options and you do not remember what you changed and want to revert back to defaults, then it is quite hard. Also it would be good, it the Centreon system highlights in different color what has been configured manually, and what options are coming from the templates.

**Comment by lpinsivy** [comment]
@kadrika 

On host and service form, Centreon proposes to see which fields are overwrittend and which fields are from the templates.

for example, there is a color system for macro. And for other fields, if is filled it means that your overwritten this parameters

**Comment by kadrika** [comment]
Yeah, that I know, but the problem, is that it takes so so so much time to go through each service and host manually one by one.

**Comment by lpinsivy** [comment]
This option is dangerous because most of resources based on template need credentials (DBMS, LDAP, etc) and if you reset everything, the monitoring will crash.
