### ISSUE TITLE
Macro type 'password' not hidden anymore

### ISSUE THREAD

**Issue by sizeur** [centreon/centreon#7012]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10
**Centreon Engine version**: 
18.10
**Centreon Broker version**: 
18.10

**Steps to reproduce the issue:**
1. Create a macro type 'password' on a host with a host template:
![image](https://user-images.githubusercontent.com/13485588/49216794-34d43300-f3cc-11e8-9f0b-1088d6174100.png)

2. Change the host template on the host
![image](https://user-images.githubusercontent.com/13485588/49216815-4584a900-f3cc-11e8-808f-0ba817d586af.png)

**Describe the results you received:**
The macro is not hidden anymore

**Comment by cgagnaire** [comment]
Fixed in latest versions.
