### ISSUE TITLE
[18.10] Graph not visible

### ISSUE THREAD

**Issue by markeur** [centreon/centreon#7014]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10

**Centreon Engine version**: 18.10 

**Centreon Broker version**: 18.10

**OS**: centos 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-V management

**Steps to reproduce the issue:**
1. Create a service attached to an host
2. Show the service's graph

**Describe the results you received:**
The graph window appear but not the graph (see attached picture)

**Describe the results you expected:**
The graph appear on the window

**Additional information you think important (e.g. issue happens only occasionally):**
![image](https://user-images.githubusercontent.com/16294256/49268250-6f57d180-f499-11e8-9f00-d4bea02515dc.png)

**Comment by kozfelipe** [comment]
check your browser for scripts error, you might need to clear your cache

**Comment by markeur** [comment]
Hello @kozfelipe, 
I try this without out success apparently rrd files are missing because of central-rrd-master service receiving rung CRC from BDOO after adding tls encryption.

**Comment by lpinsivy** [comment]
@markeur why do you encrypt flow between local SQL Broker and RRD Broker?

**Comment by markeur** [comment]
@Ipinsivy This flow is not encrypted (only flow between poller and central), I don't know why but after have changed certificate all are restored. Maybe I configure some think rong.
