### ISSUE TITLE
Check Centreon Dummy not included

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#7019]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10
**Centreon Engine version**: 
18.10
**Centreon Broker version**: 
18.10
**OS**: 
CentOS 7
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install base-generic PP.
2. Set up one host or service by using generic-passive-host-custom or generic-passive-service-custom.
3. Generate & export the configuration.

**Describe the results you received:**
 Your return in Centreon is "(no output return from plugin)" state UNKNOWN

**Describe the results you expected:**
Before the 18.10 version the installation included centreon-plugins package, this one included a check_centreon_dummy plugin used as a fake response for all passive checks.
But, with the 18.10 version centreon-plugins package is now obsolete, so this plugin is not installed anymore, but also removed by the update process and is not include in any other package.
It's could be useful to create a centreon-plugin-dummy package to allow people to install it and maybe deploy this one by default, like the centreon-plugin-Applications-Monitoring-Centreon-Central plugin.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Rico29** [comment]
+1 for this problem

**Comment by mathieuchateau** [comment]
+1

**Comment by cgagnaire** [comment]
We now use centreon-plugins dummy check.
