### ISSUE TITLE
Autologin + Fullscreen

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon#7021]
#5338 

**Centreon Web version**: 18.10

**Centreon Engine version**: 18.10

**Centreon Broker version**: 18.10

Hello, 

Since version 18.10, I have the autologin problem again.
When I use the autologin option in parameters, my "min=1" parameter is lost. (svc_id parameter also #6631 )

It's a big problem for me, because I use these options on my display screen with raspberry.

Thanks

**Comment by lolokai** [comment]
I have the same problem

**Comment by cgagnaire** [comment]
Fixed on 19.04.x and 19.10.x by https://github.com/centreon/centreon/pull/8262
