### ISSUE TITLE
SSO activated but not doing anything

### ISSUE THREAD

**Issue by larkoie** [centreon/centreon#7022]
Hi,
I activated SSO authentication in Centreon. I'm using Apache mod_auth_openidc to handle the authentication and pass the correct header to Centreon.
It's not working but does not display any error so I'm out of idea where to look.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.17

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Apache mod_auth_openidc to handle the SSO authentication/Authorization

**Steps to reproduce the issue:**
1.Go to Administration > Parameters > Centreon UI
2.Tick "Enable SSO Authentication"
3.Select "SSO Only" in SSO mode
4.Add my Apache reverse proxy IP in the trusted client addresses
5.Set the correct "SSO login header"

**Describe the results you received:**
I'm redirected to the classic centreon login page without any error displayed

**Describe the results you expected:**
I'm logged in centreon through SSO without having to enter my credentials again

**Additional information you think important (e.g. issue happens only occasionally):**
Nothing at all in the logs : 
login.log
ldap.log

**Comment by larkoie** [comment]
Yes,
I've activated the debug mode for the authentication logs and it says : 
2018-12-04 15:45|-1|0|0|[WEB] No contact found with this login : ''

I guess that the "SSO login header" is somehow missconfigured but I don't get why as I have a pretty standard oidc config on Apache.
Do you know a way to check which headers are received by centreon web?

**Comment by lpinsivy** [comment]
Is you have this message, it means that the user doesn't exist into "Configuration > Users > Contacts / Users".

Maybe you need to connect your LDAP server and enable "Auto Import" user to import missing users automatically.

Regards,

**Comment by larkoie** [comment]
I'm able to login manually with this user. It exists both in centreon DB and LDAP with the same username.
I really think that Centreon just doesn't receive any username and thus can't do anything.
The issue is that i'm not able to see what Centreon is receiving

**Comment by larkoie** [comment]
I was able to change it to HTTP and capture trafic in a tcpdump.
On the Centreon server I can see every header, including the one I declared in Centreon SSO configuration : 
```
GET /centreon/index.php HTTP/1.1
Host: myserver.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fr;q=0.8
Cache-Control: max-age=0
Cookie: my_cookie
DNT: 1
Referer: https://federation.com/authorization.ping
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
X-Forwarded-For: 10.x.x.x, 10.x.x.x
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-User: username
my_sub: username
my_country: FR
my_employeetype: Employee
my_firstname: firstname
my_mail: email@my.com
my_oracleid: username
my_groupIDmemberOf: group1, group2
my_lastname: lastname
my_SM_USER: username
my_iss: https://federation.com/fss
my_nonce: JvB1EHb4dyVzyXwiYMhu7Q0Ie8eN9UiVL6wE0VNVcgE
OIDC_access_token: UErJ1726UxmiuIzJyRnjwA2wqQuX
OIDC_access_token_expires: 1544031038
X-Forwarded-Host: myserver.com
X-Forwarded-Server: myserver.com
Connection: Keep-Alive
```
In centreon the SSO header is : SM_USER
(I also tried with my_SM_USER but it doesn't work either)

If my Centreon server get this HTTP request, it should be able to get the correct username from "my_SM_USER" right?

**Comment by larkoie** [comment]
After further testing I confirm that it looks like Centreon is never able to catch the header or at least the header content.
I've changed the header name, the header I used and whatever I try, centreon's login.log always states : 
`2018-12-11 13:38|-1|0|0|[WEB] No contact found with this login : ''`

I've took dumps from Centreon server and from proxy server and each time I find the same headers in it so I don't think it's a proxy issue.

Is there a way to debug this on Centreon side?

**Comment by larkoie** [comment]
Hi,
I'm still clueless on this one. I'm sure that Centreon gets the correct headers because I was able to pass the traffic to http and capture it on the centreon server with a tcp dump.
Do you know a way to get more explicit error message from centreon?
thanks

**Comment by lpinsivy** [comment]
It look like Centreon can't catch the username (SSO login header) from HTTP.
Check your configuration

**Comment by larkoie** [comment]
I tried to change the "sso login header" name in the centreon config with lots of headers that are present in the frame captured by tcp dump but none worked.
Is there a way to see which value is received by centreon, by turning on some debugging logs maybe?
thanks

**Comment by lpinsivy** [comment]
Sorry there is not default login for this.

Which version of Centreon do you use? Maybe I can help you to debug this
