### ISSUE TITLE
Multiple UNKNOW with WMI monitoring

### ISSUE THREAD

**Issue by ragansis** [centreon/centreon#7023]
I have many services monitored with the check_wmi_plugin but lately many of these services are placed in UNKNOW with a process timeout message, is there any configuration to be done on the windows side so that the WMI works properly?

**Comment by Sims24** [comment]
Hi @ragansis 

Don't know too much about this plugin. Afraid I will not be able to help you a lot .. Could you paste the output associated to the UNKNOWN message, that could help.

Also, can you check that the Windows server is not overloaded when UNKNOWN states show up. 

Rgds
