### ISSUE TITLE
Question: centreon-nrpe-daemon 18.10 repositories for CentOS 6, Debian and Ubuntu

### ISSUE THREAD

**Issue by nicutor** [centreon/centreon#7037]
Hi to all!

I am using centreon-nrpe-daemon 18.10 on CentOS 7, but I need it for CentOS 6 too.
I also need this package on Debian/Ubuntu and I cannot find anywhere an apt repository to be able to install this package.

Can you guide me in the right direction?

If there is no repository, from where I can get the source or such..

Or what should I do?

Thank you.

**Comment by nicutor** [comment]
Anyone?

**Comment by lpinsivy** [comment]
Hi,

Centreon 18.10 is only available for CentOS v7.
For CentOS 6, use Centreon 3.4 packages.

**Comment by StefThomas** [comment]
Centreon NRPE daemon isn’t at version 18.10… That is the version of Centreon (of Centreon Web exactly…) Centreon NRPE Daemon exists in two versions, on an up-to-date Centreon 18.10.1 :

centreon-nrpe-daemon-2.15-4.el7.centos.x86_64
centreon-nrpe3-daemon-3.2.1-7.el7.centos.x86_64

Globally, Centreon 18.10 is no more compatible with CentOS 6, only CentOS 7

For CentOS 6 you must stay at Centreon 3.4
