### ISSUE TITLE
Warning & Critical --free work in CLI not in GUI

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon#7041]
Hi team,
Explicit picture for my issue
![capture](https://user-images.githubusercontent.com/30388990/49802187-7fe73200-fd4c-11e8-8ddc-a724be5a6e7e.JPG)
And the result in CLI
```
-bash-4.2$ ./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=172.20.91.204 --container=DC2 --mode=datastore-usage --datastore-name=DC2_LUN2$ --filter --warning=214748364800: --critical=53687091200: --filter-perfdata=\(used\|free\) --disconnect-status='CRITICAL' --units B --free
WARNING: Datastore 'MD3820i_DC2_LUN2' Total: 1023.75 GB Used: 956.60 GB (93.44%) Free: 67.15 GB (6.56%) Provisioned: 956.60 GB (93.44%) | 'free'=72106377216B;214748364800:;53687091200:;0;1099243192320
```
Why ?

Regards

**Comment by cgagnaire** [comment]
Hi @oasisck,
There is a difference between your command line and the GUI, the --units option is missing.
So the thresholds on your GUI are percentages of total value.
You must add --units='B' on the UI.

**Comment by oasisck** [comment]
Holy **** ><
So sorry for this thoughtlessness
Works like a charm obviously 👍

**Comment by cgagnaire** [comment]
No worries :)
