### ISSUE TITLE
Centreon stoped graphing

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#7050]
Hi, 

I woke up this morning with centreon showing error can not access database. i worked on that and after restarting mysql Centreon worked again. well almost worked again. 
Monitoring is fine but i have no graph since the incident that happened yesterday around 8pm. 
i restarted centengine and cbd on central but no graphs yet.
Checked the centreon, centreon-broker and centengine log files without any relevant error.
tried the rebuild rrd from gui, but no success.

Can you please help with that ?

Thank you all

**Comment by lpinsivy** [comment]
Hi,

The Centreon Broker RRD use retention files (/var/lib/centreon-broker directory).
No error in /var/log/centreon-broker/central-rrd.log?

**Comment by wserard** [comment]
Hello @lpinsivy ,
I had the same problem. They are no error in my central-rrd.log file : 

Centreon Broker 18.10.1 log file opened
[1545791071] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1545791385] config:  main: configuration update requested
[1545791385] config:  log applier: applying 1 logging objects
[1545791385] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1545791385] config:  applier: 12 modules loaded
Centreon Broker 18.10.1 log file closed
Centreon Broker 18.10.1 log file opened
[1545791753] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'

**Comment by wserard** [comment]
In addition, data download give me the following set of data but download the graph send nan value as you can see on the picture.

time;humantime;used_Driver text;used_I/O;used_Processor 
545803053;2018-12-26   13:44:13;50973100.000000;12811700.000000;40.000000
1545803653;2018-12-26   13:54:13;50972400.000000;12810000.000000;40.000000
1545804253;2018-12-26   14:04:13;50988500.000000;12810000.000000;40.000000
1545804853;2018-12-26   14:14:13;50972600.000000;12810000.000000;40.000000
1545805453;2018-12-26   14:24:13;50972400.000000;12810000.000000;40.000000
1545806053;2018-12-26   14:34:13;50974100.000000;12810000.000000;40.000000
1545806653;2018-12-26   14:44:13;50972400.000000;12810000.000000;40.000000
1545807247;2018-12-26   14:54:07;50972100.000000;12810000.000000;40.000000
1545807847;2018-12-26   15:04:07;50988600.000000;12810000.000000;40.000000
1545808447;2018-12-26   15:14:07;50967500.000000;12803200.000000;40.000000
1545809047;2018-12-26   15:24:07;50971200.000000;12808300.000000;40.000000
1545809647;2018-12-26   15:34:07;50971200.000000;12808300.000000;40.000000
1545810247;2018-12-26   15:44:07;50971000.000000;12808300.000000;40.000000
1545810847;2018-12-26   15:54:07;50971200.000000;12808300.000000;40.000000

![access_a_suzhou-memory-1](https://user-images.githubusercontent.com/33144962/50439770-368f0900-092e-11e9-957a-864ae1c19215.png)

**Comment by wserard** [comment]
After have done several tests (destroy graph, restart , rrd database reconstruction, .rrd file suppression) the only change is that no grid graph are generate. I think it's "normal" because no data are detected by the graph but .rrd file have some data.

As you can see below (return of the command: rrdtool dump "one_rrdfile".rrd):

 <row><v>2.                                                                                                                                                             4639577778e+01</v></row>
                         <row><v>1.                                                                                                                                                             9960305556e+01</v></row>
                         <row><v>2.                                                                                                                                                             4367330556e+01</v></row>
                         <row><v>1.                                                                                                                                                             9199419444e+01</v></row>
                         <row><v>2.                                                                                                                                                             4518391667e+01</v></row>
                         <row><v>2.                                                                                                                                                             4767783333e+01</v></row>
                         <row><v>2.                                                                                                                                                             4979558333e+01</v></row>
                         <row><v>2.                                                                                                                                                             4601327778e+01</v></row>
                         <row><v>2.                                                                                                                                                             5341886111e+01</v></row>
                         <row><v>2.                                                                                                                                                             5346338889e+01</v></row>
                         <row><v>2.                                                                                                                                                             0499152778e+01</v></row>
                         <row><v>2.                                                                                                                                                             6020686111e+01</v></row>
                         <row><v>2.                                                                                                                                                             5609122222e+01</v></row>
                         <row><v>2.                                                                                                                                                             5900294444e+01</v></row>
                         <row><v>2.                                                                                                                                                             5241188889e+01</v></row>
                         <row><v>2.                                                                                                                                                             5836308333e+01</v></row>
                         <row><v>2.                                                                                                                                                             5480313889e+01</v></row>
                         <row><v>2.                                                                                                                                                             5870566667e+01</v></row>
                         <row><v>2.                                                                                                                                                             5845297222e+01</v></row>
                         <row><v>2.                                                                                                                                                             5413091667e+01</v></row>
                         <row><v>2.                                                                                                                                                             6212491667e+01</v></row>
                         <row><v>2.                                                                                                                                                             5325747222e+01</v></row>
                         <row><v>2.                                                                                                                                                             5615002778e+01</v></row>
                         <row><v>2.                                                                                                                                                             5404550000e+01</v></row>
                         <row><v>2.                                                                                                                                                             5001044444e+01</v></row>

**Comment by wserard** [comment]
I think I found the problem:
According to Broker-statistic the central-rrd-master-output is blocked (see following picture) but no log problem message.
 
Maybe a too low powerful server? 
Is it possible to flush the task queue?
Can you help me to solved the problem?
![image](https://user-images.githubusercontent.com/33144962/50554550-4d9b7580-0cf7-11e9-95e7-975f9df73f78.png)

**Comment by wserard** [comment]
Hello, 
I  confirm in my case it was because the serveur was not enough powerfull so I double VCPU and RAM now all are working.
