### ISSUE TITLE
Mistake in french translation for 'notification sound'

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon#7074]
In  Administration  >  Paramètres  >  Mon compte 

It is written "Notifications sonorres", should be "Notifications sonores" (with only one r)
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10.1

**Centreon Engine version**: 18.10.0

**Centreon Broker version**: ?

**OS**: CentOS 7

**Comment by sc979** [comment]
Bonjour StefThomas,
La PR est en cours de revue et sera mergée dans le meilleur délai.
Cordialement,
sc979
