### ISSUE TITLE
Centreon 18.10 Ack/downtime/External commands fails

### ISSUE THREAD

**Issue by lencell** [centreon/centreon#7078]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10.1

**Centreon Engine version**: 18.10.0

**Centreon Broker version**: 18.10.1

**OS**: CentOS Linux release 7.6.1810 (Core)

**Additional environment details (AWS, VirtualBox, physical, etc.):** Hyper-V Virtual Machine, installed from the ISO centreon-18.10-5.el7.x86_64 available on https://download.centreon.com

**Steps to reproduce the issue:**
1. Select a **Host** or a **Service** in the **Monitoring** menu
2. Select **acknowledge**, **set downtime** or any of the other choices
3. Validate the box

**Describe the results you received:**
Nothing happens

**Describe the results you expected:**
Service or Host, Ackowledged/downtimed/any of the other choice applied

**Additional information you think important (e.g. issue happens only occasionally):**
Happens 100% of the time, never worked since the install (yesterday the 20th of December)
I had this issue occasionaly on pollers of previous versions so I checked that the file `/var/lib/centreon-engine/rw/centengine.cmd` exists, is a valid FIFO and belong to centreon-engine, `/usr/lib64/centreon-engine/externalcmd.so` is also properly configured in the engine configuration panel. Everything seems ok
Lastly the call from the web page seems properly logged in httpd access log:

    [21/Dec/2018:10:28:55 +0100] "GET /centreon/include/monitoring/external_cmd/cmdPopup.php?cmd=72&comment=Acquitt%C3%A9%20par%20someuser&sticky=true&persistent=true&notify=false&ackhostservice=true&force_check=true&author=someuser&select[centreon-central]=1&select[somemachine.tld]=1 HTTP/1.1

I found nothing more related to this in the various log files (`/var/log/{centreon,centreon-broker,centreon-engine}/*.log`)

I can provide more information if requested

**Comment by StefThomas** [comment]
I can’t reproduce… Could it be a permission issue? Did you try with an account which has administrator privileges ?

If it’s not already done you should activate the debug in your poller’s engine configuration, you’ll get more info than in the usual log.

**Comment by sc979** [comment]
Hi lencell,
1- Can you tell us which language you use ?
2- Can you send us the external command found in :
`tailf /var/log/centreon-engine/centengine.log | grep DOWNTIME`
when you add a downtime.
3- And can you send us the php7 log in : 
`/var/opt/rh/rh-php71/log/php-fpm/centreon-error.log`

Thanks in advance.
Best Regards,
sc979

**Comment by lencell** [comment]
Hi, thanks to both of you for your answers.

I tried with the admin account that is created with the initial setup (although I renamed it so it's not "admin")

I tried with the following languages:

- fr_FR.UTF-8
- en_US.UTF-8
- en_US

`cat /var/log/centreon-engine/centengine.log | grep -i DOWNTIME`
Gave no output, (I tried to set a downtime and run it after)

the php7 log is only 16 lines long, which contains the 3 following errors:

    [21-Dec-2018 10:31:58 Europe/Paris] PHP Notice:  Undefined index: centreon in /usr/share/centreon/www/include/monitoring/external_cmd/popup/popup.php on line 49
    [21-Dec-2018 10:31:58 Europe/Paris] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /usr/share/centreon/www/class/centreonLang.class.php on line 135
    [21-Dec-2018 11:44:26 Europe/Paris] PHP Notice:  Undefined offset: 1 in /usr/share/centreon/www/index.php on line 112

As for the debug mode for the poller, I tried it right after I opened this issue, by checking `log everything` with the `highly detailed` option but it got me nothing interesting

Best Regards,

**Comment by lpinsivy** [comment]
First edit /etc/sysconfig/centcore and change "error" to "debug"
Second go to "Administration > Parameters > Centcore" menu and enable debug
And Restart centcore process:

`systemctl restart centcore ` 

Then can you check in /var/log/centreon/centcore.log if you can see your downtime?

**Comment by lencell** [comment]
Restarting centcore did the trick, I think the problem is that it was not started in the first place and it's the only thing I didn't checked.

So no bug, just a problem between the chair and the keyboard, although if I can suggest a change for your next release of CES: enabling by default the services cbd, centengine and centcore, as the first two were not started either (after a reboot or otherwise) and caused me a bit of trouble too.
You probably have the commands already although I will still put them here for reference:

    # Enable autostart
    systemctl enable cbd
    systemctl enable centcore
    systemctl enable centengine
    # Start the services
    systemctl start cbd
    systemctl start centcore
    systemctl start centengine

Thanks a lot to everyone for your support.
