### ISSUE TITLE
Centcore is not able to manage SNMP Trap with HTML link (Symantec, Veritas)

### ISSUE THREAD

**Issue by arnaud-michel** [centreon/centreon#7081]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
centreon-web-18.10.0-21.el7.centos.noarch

**Centreon Engine version**: 
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64

**Centreon Broker version**: 
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64

**OS**: 
CentOS Linux release 7.5.1804 (Core)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare

**Steps to reproduce the issue:**
1. implement passive service
2. execute following command
snmptrap -v2c -c public hostip '' oid s 'output with HTML link that we can find in Veritas or Symantec Trap'

**Describe the results you received:**
 tail -f /var/log/centreon/centcore.log
2018-12-20 16:43:50 - External command on Central Server: (1) : "...
sh: underline: command not found
sh: color:: command not found
sh: -c: line 1: unexpected EOF while looking for matching `"'
sh: -c: line 2: syntax error: unexpected end of file

with special joker characters
tail -f /var/log/centreon/centcore.log
Permission denied
sh: underline/: Permission denied
sh: color:: command not found

The trap is finally not handled by the system and stay stuck in centcore.cmd pipe file.

**Describe the results you expected:**
The trap has to be treated by the system

**Additional information you think important (e.g. issue happens only occasionally):**
Characters ';' are transformed in ':'.

**Comment by lpinsivy** [comment]
Illegal characters will now be removed with PR #7206

**Comment by adr-mo** [comment]
@arnaud-michel fixed with the new release 18.10.4.

Closing the issue
