### ISSUE TITLE
network::cisco::meraki::cloudcontroller::snmp::plugin ISSUE

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#7092]
Hello, 

I have been trying the Centreon SNMP plugin to poll snmp info from Meraki Dashboard. 
It works fine but it seems that the plugin truncate the results. 
I have 23 Meraki APs but when i execute the command i only get 13 APs on the results. Instead when i do snmpwalk i can see all the 23. 
Is this a known bug or limitation on Centreon Plugin ? 
Can you please help with that Issue ?

Thank you

**Comment by garnier-quentin** [comment]
I think it comes from a bug in the meraki snmp agent. it doesn't follow the rules and it didn't keep the order. 
https://stackoverflow.com/questions/20657294/snmp-getbulkrequest-with-multiple-oids-which-is-returned-response-oids-order

Try with the option --subsettable=0, it should be ok.

**Comment by saharawolf** [comment]
Great thank you

**Comment by saharawolf** [comment]
Does this plugin capable of monitoring interface traffic ? Or does it just
show status of interfaces ?
Thank you

Le ven. 28 déc. 2018 à 15:40, othman ghandi <othman.ghandi@gmail.com> a
écrit :

**Comment by lpinsivy** [comment]
Should monitor interfaces
