### ISSUE TITLE
CES 3.4 & 18.10: PID file not absolute on CentOS 7

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#7095]
**Centreon Web version**: 2.8.26, 18.10

**OS**: CentOS 7.6

The services for centcore and centreontrapd are still scripts under /etc/init.d. On CentOS 7 on both services apears the message `PID file not absolute. Ignoring`

**Comment by garnier-quentin** [comment]
It's not relevant. Following processes use systemd.
