### ISSUE TITLE
Repository >>http://yum.centreon.com/standard/18.10/el7/stable/noarch/repodata<< NOK

### ISSUE THREAD

**Issue by Robvred** [centreon/centreon#7103]
Hi,

It seems that the official Centreon repository is not updated OK.

http://yum.centreon.com/standard/18.10/el7/stable/noarch/repodata/317bdb833ae86b9f47841086de3b528d5f41af60a6807a9016dafe973dc42369-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found

Kindly could you check?

Kind Regards,

**Comment by sc979** [comment]
Hi Robvred,
Indeed, there's a problem. We'll check it.
Best Regards,

**Comment by lpinsivy** [comment]
Regarding the http://yum.centreon.com/standard/18.10/el7/stable/noarch/repodata/repomd.xml file, all needed files are present.

Are you using a proxy to connect to Internet? maybe a cache issue.

**Comment by Robvred** [comment]
Something strange, now works fine...

I think it was not an proxy cache issue, because I clear this one after few tests.
