### ISSUE TITLE
[18.10.2] Problem with a New Installation of Centreon 

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon#7106]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**OS**: CentOS 7.6

**BDD**: MySQL Server 8.0 Enterprise License

**Additional environment details (AWS, VirtualBox, physical, etc.):** VM

**Steps to reproduce the issue** :
Follow the instructions regarding the installation of a Centreon server without a local BDD until Step 7.

![image](https://user-images.githubusercontent.com/29780310/50648391-61570e00-0f7b-11e9-8530-7dd4b2f9b6fd.png)

**Describe the results you received:**
The installation is stuck during the "**Partitioning database tables**".

**Comment by wserard** [comment]
Hi @Crash-Fox,
it append to me too if you understand French you can have a look at site web page: http://www.sugarbug.fr/blog/files/centreon_timeout_partitionning.html

**Comment by lpinsivy** [comment]
Do you try with 18.10.0 or 18.10.2 version?

**Comment by Crash-Fox** [comment]
Hi @lpinsivy 
Thanks for your response. I try with the 18.10.2 version.

**Comment by adr-mo** [comment]
**No answer for now more than 1 months**

Closing this issue.

Regards,
