### ISSUE TITLE
Dependencies have become invisible in configuration

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#7109]
Centreon version 2.8.22
Centreon Engine 1.8.1
Centreon Broker 3.0.14

Under Configuration/Notifications/Hosts and Configuration/Notifications/Meta Services all items have disappeared, /etc/centreon-engine/dependencies.cfg and /usr/share/centreon/filesGeneration/engine/1/dependencies.cfg only contain the header (with a correct date for the last export action on poller reload).

The parent and child relations are still visible when going to a host's configuration in the web UI, in a CLAPI config export and /etc/centreon-engine/hosts.cfg resp. /usr/share/centreon/filesGeneration/engine/1/hosts.cfg contain the correct "parents" lines.

Tried restarting the poller, "service centcore restart; service centengine restart; service cbd restart; service mysql restart", none of these helped.

Haven't tried adding new dependencies yet as I'm afraid the current config will disappear too, although I'm not even sure it even works right now..

**Comment by btassite** [comment]
Addendum: configured meta services are visible under Monitoring/Services and Configuration/Services/Meta Services, which is the exact opposite of #6396 (and present in /etc/centreon-engine/meta_services.cfg)

(CLAPI export doesn't contain meta services, see #6606, so I can't check the meta service notification config)

**Comment by btassite** [comment]
Also, viewing config/monitoring as admin, so everything should be visible regardless of ACLs, correct? In any case, the user is part of a contact group which is assigned to an ACL with view permissions for the menu (which should also be moot as if this were set to invisible it should also hide the whole menu, not just the contents, correct?)

**Comment by btassite** [comment]
Can't seem to edit comments :) ACL also has explicit Menu Access read/write permission for Notifications/Dependencies/Hosts and Meta Services, resource access to all hosts/hostgroups/servicegroups and almost all actions enabled (with a few exceptions like "Generate SNMP Trap configuration")

**Comment by lpinsivy** [comment]
Sorry but I don't understand your issue.

Dependancies are not link to host parentship.
Dependancies allow to describe logic (and not physic) relationship. for example a connection to a website with LDAP credentials depend of availability of the LDAP server.

**Comment by btassite** [comment]
Also I tested the parent/child relationship and that worked IIRC :)

**Comment by lpinsivy** [comment]
dependencies and parentship are not the same.
So if you configure parentship, you don't configure escalation (notification) of dependencies

**Comment by btassite** [comment]
https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/advanced_configuration/dependancy.html categorizes the parent/child relationships as the physical form of dependencies, while the dependencies under Configuration > Notifications > Hosts  for example are categorized as logical dependencies.

So far I only get that the latter has more options, like allowing service dependencies, but my question relates to how notification is handled. Does it matter under which of the two I define a host dependency from the perspective of notification?

**Comment by lpinsivy** [comment]
If you define parentship and you don't select "UNREACHABLE" filter for notification, you will receive only notification for DOWN parent host.

If you define dependencies, you can define if the scheduler have to control hosts linked to parent and/or if the scheduler have to notify regarding the status of the parent.

**Comment by btassite** [comment]
OK, so if I understand correctly:
1. if you configure host A as parent of host B and host A goes down, then host B goes down host B is in state UNREACHABLE and will not notify if only DOWN status is selected for its notification or in contact notification settings.
2. if you configure a dependency with master host A and dependent host B, leave Execution Failure Criteria unselected (or select None) and set Notification Failure Criteria to Down and Unreachable you have basically the same as under 1., correct?

**Comment by lpinsivy** [comment]
Yes
