### ISSUE TITLE
centreon_centreon_poller.pl where is Dummy ??

### ISSUE THREAD

**Issue by LLFT** [centreon/centreon#7122]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10.2

**Centreon Engine version**: 18.10.2

**Centreon Broker version**: 18.10.2

**OS**: Centos 7

**Steps to reproduce the issue:**
1. Create a service model with a generic-passive-service reference model / Creer un modèle de service avec pour modèle de référence generic-passive-service
2. Or the order / Ou la commande : /usr/lib/centreon/plugins/centreon_centreon_poller.pl --plugin=apps::centreon::local::plugin --mode=dummy --status='OK' --output='Service is OK'

**Describe the results you received:**

The associated service returns: **UNKNOWN: mode 'dummy' doesn't exist (use --list-mode option to show available modes).**
Only the broker-stats, centreon-plugins-version, downtime-trap, metaservice and retention-broker modes are available.

**Describe the results you expected:**

Not an error message with an unknown output

**Comment by mavynet** [comment]
It work s ok here using centreon-plugin-Applications-Monitoring-Centreon-Poller-20190111-102147.el7.centos.noarch

# /usr/lib/centreon/plugins/centreon_centreon_poller.pl --plugin=apps::centreon::local::plugin --mode=dummy --status="OK" --output="Service is OK"
OK: Service is OK

**Comment by LLFT** [comment]
Retour système : 

`Le paquet centreon-plugin-Applications-Monitoring-Centreon-Poller-20190111-102147.el7.centos.noarch est déjà installé dans sa dernière version`

Retour commande : 

```
/usr/lib/centreon/plugins/centreon_centreon_poller.pl --plugin=apps::centreon::local::plugin --mode=centreon-plugins-version
OK: Centreon Plugins Global Version '20180821'
```

**Comment by LLFT** [comment]
Please, can you show me the origin of your package ? 

`yum info centreon-plugin-Applications-Monitoring-Centreon-Poller`

Thanks,

**Comment by lpinsivy** [comment]
```
Nom                 : centreon-plugin-Applications-Monitoring-Centreon-Poller
Architecture        : noarch
Version             : 20190111
Révision            : 102147.el7.centos
Taille              : 215 k
Dépôt               : installed
Depuis le dépôt     : centreon-stable-noarch
Résumé              : Centreon Plugin
URL                 : https://www.centreon.com/
Licence             : ASL 2.0
Description         : Centreon plugin
```

**Comment by LLFT** [comment]
Hello, I come back to you because I return the problem following an update.

```
 yum info centreon-plugin-Applications-Monitoring-Centreon-Poller
Modules complémentaires chargés : fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.crazyfrogs.org
 * centos-sclo-rh: centos.crazyfrogs.org
 * centos-sclo-sclo: centos.crazyfrogs.org
 * extras: centos.crazyfrogs.org
 * updates: centos.mirror.ate.info
Paquets installés
Nom                 : centreon-plugin-Applications-Monitoring-Centreon-Poller
Architecture        : noarch
Version             : 20191002
Révision            : 125310.el7.centos
Taille              : 252 k
Dépôt               : installed
Depuis le dépôt     : centreon-stable-noarch
Résumé              : Centreon Plugin
URL                 : https://www.centreon.com/
Licence             : ASL 2.0
Description         : Centreon plugin
```
Do you have any idea why this obsolete plugin is coming back ?

```
/usr/lib/centreon/plugins/centreon_centreon_poller.pl --plugin=apps::centreon::local::plugin --mode=centreon-plugins-version
OK: Centreon Plugins Global Version '20180821
```
