### ISSUE TITLE
Centreon 2.5.1 to 2.5.2	DB Error: no such field during upgrade

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#713]
---

Author Name: **Avo Badamyan** (Avo Badamyan)
Original Redmine Issue: 6465, https://forge.centreon.com/issues/6465
Original Date: 2015-07-15

---

Go this error message upgrading Centreon.
_You seem to be having trouble with your upgrade.
You may refer to the line that causes problem in order to find out more about the issue.
The SQL files are located in /usr/share/centreon/www/install/sql/
But do not edit the SQL files unless you know what you are doing. Refresh this page when the problem is fixed.
Need help do not know how to fix._

Need help.

**Comment by julienmathis** [comment]
Already fixed
