### ISSUE TITLE
[DOC] Missing command in "install from packages" procedure

### ISSUE THREAD

**Issue by omercier** [centreon/centreon#7137]
I just followed the french version of the  "install from packages" procedure, with separated database server and after "yum install centreon-database" I am told to run "systemctl restart mysql" but when I do it I get:
# systemctl restart mysql
Warning: mysql.service changed on disk. Run 'systemctl daemon-reload' to reload units.

Can you add "systemctl daemon-reload" before the restart command?

**Comment by adr-mo** [comment]
Documentation updated for the 18.10.4 **release.**

Closing the issue
