### ISSUE TITLE
Notification manquante

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#714]
---

Author Name: **m m** (m m)
Original Redmine Issue: 5928, https://forge.centreon.com/issues/5928
Original Date: 2014-11-03

---

Bonjour,
j'ai un soucis de notification sur un cas qui s'est présenté ce matin.

Ma configuration:
Mes users ont une notification period (heure ouvrée a partir de 7h30).
Mes host, service, ect... sont en H24.

Ainsi, si a 7h30, une alerte détectée a 1h par exemple est toujours active, il notifie a 7h30.

Ce fonctionnement a marché hier (un serveur est tombé dans la nuit de lundi a mardi --> Notification le mardi a 7h30)
Ce meme serveur est retombé cette nuit, detecté par nagios a 1h00, mais pas de notification.

Qu'en pensez vous ?

**Comment by julienmathis** [comment]
Sans log, sans autres informations, c'est très dur de se prononcer :)
