### ISSUE TITLE
Centreon Logo Modification

### ISSUE THREAD

**Issue by bhowbhow** [centreon/centreon#7143]
Hey,
I'm trying to modify the logo in sidebar and sidebar mini. Replace the original logo with the my updated one. Still the old logo is reflecting even after updating the old logo. 
Took the service restart and also restarted the VM. 

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: Centreon 18.10.0

**Centreon Engine version**: Centreon 18.10.0

**Centreon Broker version**: Centreon 18.10.0

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):** VirtualBox

**Steps to reproduce the issue:**
1. Replace the origin images inside /usr/share/centreon/www/front_src/src/img. 
2. Restart apache.

**Describe the results you received:** The old logo was still intact.

**Describe the results you expected:** The new logo to be reflected in the webpages.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment]
Hi,

Sorry but it is not intended by the software to be able to modify the logo by yours.
I think this comes from a browser cache problem.

Regards,
