### ISSUE TITLE
CentreonWeb generate / export poller configuration doing noting on Firefox 64.0 Quantum

### ISSUE THREAD

**Issue by MiStErLu** [centreon/centreon#7147]
I just upgrade my centreon to the latest avaliable version (18.10.2)
When i go the "Configuration" => "Pollers" => "Pollers" and i want to upgrade my poller configurations files it's doing nothing. 
I use Firefox Quantum 64.0 (64bits) version (i am on linux Ubuntu 18.04).

If i use Google Chrome version 70.0.3538.77 (Build officiel) (64 bits) (i am on linux Ubuntu 18.04) it work perfectly. The poller are restarted.

I think there is a bug in the javascript

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10.2

**Centreon Engine version**: 18.10.0

**Centreon Broker version**: 18.10.1

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Login with Firefox Quantum 64.0 (64bits)
2. Try to export config
3. Nothing append.

**Describe the results you received:**

**Describe the results you expected:**

In the Javascript console you will see :+1: 

ReferenceError: $$ is not defined[En savoir plus]
centreonToolTip.js:22:3
CentreonToolTip/this.render
https://XXXXXXXXXXXXXXXXXX/centreon/class/centreonToolTip.js:22:3
<anonyme>
https://XXXXXXXXXXXXXXXXXX/centreon/main.get.php:227:5
Error: cannot call methods on progressbar prior to initialization; attempted to call method 'value' jquery.min.js:1:1968
error
https://XXXXXXXXXXXXXXXXXX/centreon/include/common/javascript/jquery/jquery.min.js:1:1968
$.widget.bridge/$.fn[name]/<
https://XXXXXXXXXXXXXXXXXX/centreon/include/common/javascript/jquery/jquery-ui.js:246:14
each
https://XXXXXXXXXXXXXXXXXX/centreon/include/common/javascript/jquery/jquery.min.js:1:3031
each
https://XXXXXXXXXXXXXXXXXX/centreon/include/common/javascript/jquery/jquery.min.js:1:998
$.widget.bridge/$.fn[name]
https://XXXXXXXXXXXXXXXXXX/centreon/include/common/javascript/jquery/jquery-ui.js:236:5
updateProgress
https://XXXXXXXXXXXXXXXXXX/centreon/main.get.php:603:28
generationProcess
https://XXXXXXXXXXXXXXXXXX/centreon/main.get.php:300:9
onclick
https://XXXXXXXXXXXXXXXXXX/centreon/main.get.php:1:1

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by pkriko** [comment]
Hello @MiStErLu 

Could you clear your cache or better use the private navigation of your browser and retry ?

Regards,

**Comment by lpinsivy** [comment]
@MiStErLu still have problem after cleaning browser cache?

**Comment by MiStErLu** [comment]
I upgrade to Firefox 65 and the problem never reappear. I try many time to clean my cache but it's doesn't solve the problem.

**Comment by lpinsivy** [comment]
So no more issue with Firefox 65?

**Comment by adr-mo** [comment]
**No answer for now more than 1 months**

Closing this issue.

Regards,
