### ISSUE TITLE
Error 500 after upgrade to 18.10

### ISSUE THREAD

**Issue by gabyfulchic** [centreon/centreon#7153]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10

**Centreon Engine version**: 18.10

**Centreon Broker version**: 18.10

**OS**: Centos7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

It's a vps. I've juste tried to update my centreon from 2.8.26 to 18.10 but after following the official doc :
https://documentation-fr.centreon.com/docs/centreon/fr/18.10/upgrade/from_packages.html, i'm getting an error 500 on my chrome page. I think about a php error because of the logs.

**Steps to reproduce the issue:**
1. Follow doc to update from 2.8.26 to 18.10.3
2. Go to web nav to finish the upgrade

The httpd error log :
![image](https://user-images.githubusercontent.com/22600727/51691119-706d3100-1ffa-11e9-9883-c90fe5b8c295.png)

The chrome page :
![image](https://user-images.githubusercontent.com/22600727/51691146-7fec7a00-1ffa-11e9-8196-44681d627b06.png)

Additional info :
![image](https://user-images.githubusercontent.com/22600727/51691197-a27e9300-1ffa-11e9-8368-cbf7587d7545.png)

So if you have information to debug this i'll tank you ;) 

warmly FULCHIC Gaby

**Comment by kozfelipe** [comment]
you may find something at /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log rather than httpd log

**Comment by gabyfulchic** [comment]
More informations : 
php -v : 5.4.6
httpd -v : 2.4.6
scl --list : rh-php71
ss -altp : showing me the php-fpm on 9042 and the apache web server on 443/80

**Comment by gabyfulchic** [comment]
![image](https://user-images.githubusercontent.com/22600727/51748113-b7672f00-20ab-11e9-8856-5ec4d325cb3e.png)
I don't have any file centreon-error.log but i've got a error.log :/

**Comment by gabyfulchic** [comment]
The error occur when i put the new /usr/share/centreon/* path.
Maybe because a new php7.1 syntax is not accepted by my php version. :/

**Comment by kozfelipe** [comment]
seems like a php conflict

**Comment by gabyfulchic** [comment]
yeah.. do you have any idea about resolving my problem :/ ?

**Comment by kozfelipe** [comment]
I had some migration issues too. I recommend backup your files and launch a brand new install.

**Comment by gabyfulchic** [comment]
Ok i'll try and informate you about my progress

**Comment by lpinsivy** [comment]
@gabyfulchic do you still have issue?

**Comment by heavyvetal7** [comment]
The same issue. 
Is there any solution?

**Comment by adr-mo** [comment]
Hi @heavyvetal7,

First of all thanks for the feedback :100: 

Could you please make sure that Apache service and rh-php71-php-fpm are **correctly started** ?

`systemctl status httpd`
`systemctl status rh-php71-php-fpm`

Regards,

**Comment by heavyvetal7** [comment]
Hi, thanks for your reply!

After a few days of searching for the solution I reverted the VM snapshot and rolled the changes back.
I've removed php5 and installed php71. Error 500 was gone but Centreon UI was not operational =(

I'll give it another try during next maintenance window as this is a production Centreon server.

**Comment by adr-mo** [comment]
Hi @heavyvetal7,

Ok thanks for the reply.

@gabyfulchic Do you still have this issue ?

Regards,

**Comment by adr-mo** [comment]
Hi,

The 18.10 version of Centreon is no longer supported. Please upgrade to a supported version ( version >= 19.04.0).

If the issue remains do not hesitate to reopen an issue.

Regards
