### ISSUE TITLE
No plugin packs found

### ISSUE THREAD

**Issue by jeremyit** [centreon/centreon#7156]
Hi,
No plugin packs found 
centreon-license-manager and centreon-pp-manager installed and OK status.
No proxy, Internet connectivity ok

Centreon 18.10 fresh install system with data and config from a 2.8.26 migration.

**Comment by Walther19** [comment]
I have this problem too. When open this page from inkognito tab it's load ok.

**Comment by jeremyit** [comment]
not for me :(

**Comment by Walther19** [comment]
You should login on page Administration-Extension-Subscription before that.

**Comment by jeremyit** [comment]
not better :/

**Comment by lpinsivy** [comment]
Do you use proxy to connect Internet from your central server?

**Comment by jeremyit** [comment]
Direct to the gateway without proxy

**Comment by lpinsivy** [comment]
can you test:
`curl -XPOST https://api.imp.centreon.com/api/auth/instance`

you should obtain
`{“code”:400,“message”:“The argument companyToken is required.“}`

**Comment by jeremyit** [comment]
Yes it is.
```
~]# curl -XPOST https://api.imp.centreon.com/api/auth/instance
{"code":400,"message":"The argument companyToken is required."}
```

**Comment by lpinsivy** [comment]
No error in browser debug console when accessing on Plugin Pack page?

**Comment by jeremyit** [comment]
Error 500
![ppmerror](https://user-images.githubusercontent.com/46191916/53011876-becaef80-3441-11e9-9b5f-2ced70bcaf72.JPG)

**Comment by lpinsivy** [comment]
@jeremyit can you give me the answer (Réponse)?

**Comment by jeremyit** [comment]
I posted a screenshot from debug console.
When I access Plugin pack manager page, there is an HTTP error 500

url request is : http://*****/centreon/api/internal.php?object=centreon_pp_manager_pluginpack&action=ListInstalledOrdered&locale=fr

**Comment by lpinsivy** [comment]
Ok can you give the errors present in "/var/opt/rh/rh-php71/log/php-fpm/centreon-error.log" file when you access to this page?

`# tailf /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log`

**Comment by jeremyit** [comment]
```
[19-Feb-2019 16:15:41 Europe/Paris] PHP Fatal error:  Uncaught Exception: Error while getting media directory  in /usr/share/centreon/www/class/centreonMedia.class.php:92
Stack trace:
#0 /usr/share/centreon/www/class/centreonMedia.class.php(181): CentreonMedia->getMediaDirectory()
#1 /usr/share/centreon/www/class/centreonMedia.class.php(171): CentreonMedia->createDirectory('ppm')
#2 /usr/share/centreon/www/modules/centreon-pp-manager/core/class/Installation/OperationManager.php(108): CentreonMedia->addDirectory('ppm')
#3 /usr/share/centreon/www/modules/centreon-pp-manager/core/class/Installation/Install.php(28): CentreonPluginPackManager\Installation\OperationManager->__construct(Object(CentreonPluginPackManager\ImpApi), Object(CentreonPluginPackManager\Imp))
#4 /usr/share/centreon/www/modules/centreon-pp-manager/core/class/Installation/Provider.php(35): CentreonPluginPackManager\Installation\Install->__construct(Object(CentreonPluginPackManager\ImpApi), Object(CentreonPluginPackManager\Imp))
#5 /usr/share/centreon/vendor/pimple/pimple/src/Pimple/Container.php(1 in /usr/share/centreon/www/class/centreonMedia.class.php on line 92

```

**Comment by lpinsivy** [comment]
What is the rights on the /usr/share/centreon/www/img/media/ directory?

`# ls -lah /usr/share/centreon/www/img/media/`

What is the version of your components?

`# rpm -qa | egrep "(centreon\-web|centreon\-pp\-manager)"`

**Comment by jeremyit** [comment]
```
centreon-pp-manager-18.10.2-1.el7.centos.noarch
centreon-web-18.10.2-3.el7.centos.noarch
```
```
# ls -lah /usr/share/centreon/www/img/media/
total 0
drwxrwxr-x. 2 centreon centreon  19 22 janv. 10:37 .
drwxrwxr-x. 6 centreon centreon 172 22 janv. 10:37 ..
-rwxrwxr-x  1 centreon centreon   0 28 déc.  13:44 .keep
```

**Comment by lpinsivy** [comment]
We are looking packaging of centreon-pp-manager for upgrade from v1.4.x version.

This is the workaround:

```
# mkdir -p /usr/share/centreon/www/img/media/ppm
# chown -R apache:apache /usr/share/centreon/www/img/media/ppm
```

**Comment by jeremyit** [comment]
Workaround doesn't work for me.
Same error 500 in debug console and in centreon-error.log

**Comment by lpinsivy** [comment]
SElinux is disable?

centreon is member of apache group and apache a member of centreon group?

```
# cat /etc/group | egrep "(apache|centreon)"
nagios:x:999:centreon-engine,centreon-broker,apache
centreon:x:998:centreon-engine,centreon-broker,apache
apache:x:48:nagios,centreon
centreon-broker:x:994:centreon,nagios,centreon-engine,apache
centreon-engine:x:993:centreon-broker,apache,nagios,centreon 
```

**Comment by jeremyit** [comment]
SElinux is disable
Yes, centreon is member of apache group
Apache member of centreon group
```
centreon:x:999:centreon-engine,centreon-broker,apache
nagios:x:998:centreon-engine,centreon-broker,apache
centreon-broker:x:994:centreon,nagios,centreon-engine,apache
apache:x:48:nagios,centreon
centreon-engine:x:991:centreon-broker,apache,nagios,centreon
```

**Comment by lpinsivy** [comment]
Can you check if "Images Directory" is defined into "Administration > Parameters > Monitoring" and the value is correct (should be "/usr/share/centreon/www/img/media/")

**Comment by jeremyit** [comment]
Yes! that's fix it !
