### ISSUE TITLE
New Translation files not working in Centreon 18.10 / CentOS 7

### ISSUE THREAD

**Issue by Kevin1904** [centreon/centreon#7163]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 18.10.2-3

**Centreon Engine version**: 18.10.0-4

**Centreon Broker version**: 18.10.1-1

**OS**: centos el7

**Translation files not working in CentOS 7**

Using the new files "messages.po" and "help.po" to create the corresponding ".mo" files and adding them to /usr/share/centreon/www/locale/de_DE.UTF-8/LC_MESSAGES

When i change the language to de_DE.UTF-8 in my profile in centreon-web, I get a blank page.
Using Chrome Development Console i find the server response:
**"Translation files does not exists"**

I used the method described on the following page: [https://www.centreon.com/en/blog/tutorial-how-to-translate-centreon/](url)

I see a "messages.ser" file, but mine are "*.mo". Do I have to convert them again?

Need some advice, thank you!

**Comment by sc979** [comment]
Hi Kevin1904,
Like the "messages.mo", the "messages.ser" is needed and should be compiled too for the 18.10.

The tutorial in the blog will be updated, as soon as the process is validated by the QA.
But, could you try the following commands :
Move in the "centreon-translation" folder
$ php ./centreon-github/bin/centreon-translations.php de messages.po messages.ser
$ chown apache.apache messages.ser
$ sudo cp *.ser /usr/share/centreon/www/locale/de_DE.UTF-8/LC_MESSAGES
$ sudo service httpd restart

Please tell me if it's working for you.
BTW : Could you share your translation with us ? We're in need of this kind of contribution

Best Regards
sc979

**Comment by Kevin1904** [comment]
Thanks for your reply. Your method worked fine, thanks very much!!
We will fine tune the translation and share it with you, once we're finished.

Regards
kevin

**Comment by sc979** [comment]
Nice,
I'm closing this ticket.
If you have another issue, feel free to open another ticket ;)

NB : The translation "tutorial"  will be removed from the blog and added/updated in the official documentation :
https://documentation.centreon.com

Best Regards
sc979
