### ISSUE TITLE
Remote Server Watchdog.xml /var/log/centreon-broker/watchdog.log/watchdog.log block cbd

### ISSUE THREAD

**Issue by germain-denis** [centreon/centreon#7164]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10
**Centreon Engine version**: 
18.10
**Centreon Broker version**: 
18.10
**OS**: 
Centos7
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. After update central in 18.10-0 and remote servers in 18.10.2-3, while exporting configuration on remote server, file watchdog.xml from remote has this line: 
`"<log><![CDATA[/var/log/centreon-broker/watchdog.log/watchdog.log]]></log>"`

**Describe the results you received:**
while exporting configuration on remote server, file watchdog.xml from remote has this line: 
`"<log><![CDATA[/var/log/centreon-broker/watchdog.log/watchdog.log]]></log>"`
And it will block cbd : /usr/sbin/cbwd /etc/centreon-broker/watchdog.xml
watchdog: log: could not open file '/var/log/centreon-broker/watchdog.log/watchdog.log': N'est pas un dossier
**Describe the results you expected:**
`"<log><![CDATA[/var/log/centreon-broker/watchdog.log]]></log>"`

To solve this issue you need to go in Configuration > Poller > The_remote_server
In Centreon Broker logs you need to put the path to the log folder e.g /var/log/centreon-broker
And not the full path to the file like this /var/log/centreon-broker/watchdog.log

**Comment by kozfelipe** [comment]
https://github.com/centreon/centreon/issues/7070

**Comment by lpinsivy** [comment]
duplicate
