### ISSUE TITLE
Filter with autodiscovery

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon#7166]
Hello,

I use autodiscovery to apply a template for my each Netapp Volume.
But I want select a specific Template in fonction of the name volume.

So I know do a exclusion with the rule, but how do just a filter in order to apply the template on a specific name only.

To exclude the volumes containing "XDP", I select "Exclusion" > $name$ > XDP
But to filter just the volumes containing "XDP", how do that?

Thanks

**Comment by lpinsivy** [comment]
Hi @benoitb21 you can use "inclusion" to match only value "XDP" for $name var.
but you will need to create as many rules as there are volume types.

**Comment by benoitb21** [comment]
Thanks, 
But just with the "inclusion" I have all volumes.
It's now ok if I use:
Inclusion "XDP"
+ Exclusion ".*"

Why not...
