### ISSUE TITLE
Wrong time value for status’s age

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon#7168]
Hi,

I don’t have the expected value in the log if I look at the status's age column (Duration & Hard state duration). The time delta is not always the same and I have this issue both on Centreon 2.7, 2.8 and 18.10… this makes me think there is no bug and I just don’t understand how this works.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2,7, 2,8, 18.10

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMWare VM

**Steps to reproduce the issue:**
1. Look at any "hard state duration" of a service
2. In the very same time, issue the command : date -d <-hard state duration>, for example : date -d "-1month 13hour 18minute", it will give you a datetime in the past.
3. Search this datetime in the logs of the service

Result : can’t find it ! The last hard status change is at another datetime in the logs

To tell it another way : the hardsate duration column disagrees with the event logs…

I expect to get the same datetime than the date command had gave me first.

---

I just made another test now, confirmed :( I hope my explanation is ok. I make myself available to answer any question you may have.

**Comment by StefThomas** [comment]
I just made another test… In fact, the right date command to issue is :

date -d "-1month -13hour -18minute" (the minus sign must be in front for all units…

I will make some more tests this afternoon so I can confirm I have the kind of bug I described, or not…

**Comment by StefThomas** [comment]
Made some more tests. Great case of PEBCAK, from my user and myself…

Closing. Sorry for the noise.

**Comment by sc979** [comment]
Hi StefThomas,
I'm glad you found the cause.
sc979
