### ISSUE TITLE
Using HTTPS with Centreon web dashboard

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#7174]
Hi, 

I would like to migrate centreon web interface to using HTTPS instead of HTTP. 
I followed a tutorial to do that, now i can access the dashboard with HTTPS but HTTP is still working. 
Can you please help me to implement a redirection so that if a user tape http on the url it is automatically redirected to the secure page ?

thank you

**Comment by kozfelipe** [comment]
hi,
this is my working 10-centreon conf

```
#
# Section add by Centreon Install Setup
#

Alias /centreon /usr/share/centreon/www/

RewriteEngine on
ReWriteCond %{SERVER_PORT} !^443$
RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [NC,R,L]


<LocationMatch ^/centreon/(.*\.php(/.*)?)$>
  ProxyPassMatch fcgi://127.0.0.1:9042/usr/share/centreon/www/$1
</LocationMatch>

ProxyTimeout 300

<Directory "/usr/share/centreon/www">
    DirectoryIndex index.php
    Options Indexes
    AllowOverride all
    Order allow,deny
    Allow from all
    Require all granted
    <IfModule mod_php5.c>
        php_admin_value engine Off
    </IfModule>

    AddType text/plain hbs
</Directory>
```

although I had to remove my /usr/share/centreon/www/.htaccess
