### ISSUE TITLE
Widget Duration error

### ISSUE THREAD

**Issue by v0strik0v** [centreon/centreon#7180]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Centreon Web version : 18.10.2

Centreon Engine version : 18.10.0

Centreon Broker version : 18.10.1

OS : CentOS 7.6.1810

**Steps to reproduce the issue:**
1. Create a widget (host or service monitoring) in the custum views
2. Select some elements with the hostgroup filter
3. In the column "Duration", the value is sometimes displayed correctly (ex : 50 min 49s ago) and most of the time displayed like this (5 février 2019 14:31:14) or (-2511y -1M ago)

I've different timezone for the equipments but I was perfectly working in version 2.8.26

![centreon 18 10 widgets duration error](https://user-images.githubusercontent.com/24812165/52350707-22dbc580-29f7-11e9-9179-a086cb37b3ec.png)

**Comment by adr-mo** [comment]
Hi @v0strik0v,

Thanks for the feedback !

Indeed this a known problem that is currently in our backlog.

This should be fixed in future releases.

Regards,

**Comment by sc979** [comment]
Hi @v0strik0v,

You can download the fixes here :
https://github.com/centreon/centreon-widget-host-monitoring/pull/62
https://github.com/centreon/centreon-widget-service-monitoring/pull/114
These, still need the QA homologation before being released.
Please gives us feedback.

Best regards,
sc979

**Comment by v0strik0v** [comment]
Bonjour,

Je vous confirme que le correctif fonctionne très bien !
Merci pour votre réactivité.

Cordialement,
v0strik0v
