### ISSUE TITLE
Can't export with filter (Widget service-monitoring)

### ISSUE THREAD

**Issue by SofieneB** [centreon/centreon#7181]
Hello,

We can't export with the widget "service-monitoring" when we select, for exemple, one hostgroup 

Version : Centreon 18.10.2

Best regards,

**Comment by sc979** [comment]
Hi SofieneB,

Can you try this fix please : 
https://github.com/centreon/centreon/pull/7167

It will be released soon, and may fix your issue.

Best Regards,
sc979
