### ISSUE TITLE
Can't restart poller via the GUI

### ISSUE THREAD

**Issue by MayusYT** [centreon/centreon#7182]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8,8

**Centreon Engine version**:  1.7.2

**Centreon Broker version**:  3.0.7

**OS**:   Debian Jessie

**Additional environment details (AWS, VirtualBox, physical, etc.):**   VirtualBox

**My Issue**
When I want to restart my poller via the webinterface, it says there are too many parameters.

![](https://i.imgur.com/eyI9MtW.png)

Doesnt seem to be reproducible.

**Comment by lpinsivy** [comment]
Hi @MayusYT Do you try Centreon Web 2.8.8 ? (can you try 2.8.26 version).

**Comment by MayusYT** [comment]
Hello,
As it didn't work I uninstalled centreon but I would install it again if it
worked on a raspberry pi. Are there manuals/ guides for the raspberry pi 3?

**Comment by kozfelipe** [comment]
https://documentation.centreon.com/docs/centreon/en/latest/installation/from_sources.html
you could try debian guide

**Comment by adr-mo** [comment]
**No answer for now more than 1 months**

Closing this issue.

Regards,
