### ISSUE TITLE
event handler used in service template are not add to generated service v2.8.19

### ISSUE THREAD

**Issue by crocoolivier** [centreon/centreon#7185]
Hi,
Centreon version : 2.8.19

I added an event handler to a service template but it does not replicate to the generated service.
Please could you verify that?
In the servicetemplate.cfg, we can see the event handler but not in the services.cfg.

Thx in advance,

**Comment by lpinsivy** [comment]
Hi @crocoolivier 
Your event handler is defined in serviceTemplates.cfg right?

If yes, Centreon Engine will use this definition.

**Comment by crocoolivier** [comment]
right. I will test it and i will say you. ( Today or tomorrow)

**Comment by crocoolivier** [comment]
Hi,
It's ok event handler works in 2.8.26 with service template. I'm sorry i can't test with v2.8.19.
Thanks you for your time.
