### ISSUE TITLE
No more option to disable processing of perfdata

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon#7197]
I would like to be able to disable processing of perfdata for some services.

I saw you closed #5369 telling that everybody wants graph generation as soon as there are perfdata. This is false. I need to disable some of them because of resource consumption (space in /var/lib/centreon/metrics).

Please make this functionality available again.

My compagny is in the process of getting an EPP licence to use the plugins pack manager and to get support on the product after been using the free software part for more seven years now. I will ask again in few weeks for the restoring of this functionality as a paying customer…

In a more general manner : try not to get rid of functionalities assuming “nobody is using it” it’s obviously always false… I’m aware of refactoring needs and code maintainability but please do not follow the G.N.O.M.E way in getting rid of all the functionalities.

I’m a bit concern with Centreon’s last technical choices (like rejecting one of my patch on CLAPI without any technical reason…). This **regression** on perfdata is not getting me good feelings about the roadmap :(

**Comment by lpinsivy** [comment]
@StefThomas the Centreon plugin has an option to select perfdata that you want to see in a graph.

So to do not generate perfdata, just filter on non-existent data:

```
 # /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=127.0.0.1 --snmp-community=public --snmp-version=2c
OK: 1 CPU(s) average usage is 2.00 % - CPU '0' usage : 2.00 % | 'total_cpu_avg'=2.00%;;;0;100 'cpu'=2.00%;;;0;100
```

```
# /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=127.0.0.1 --snmp-community=public --snmp-version=2c --filter-perfdata=no
OK: 1 CPU(s) average usage is 1.00 % - CPU '0' usage : 1.00 % |
```

If you are using Plugin Packs, edit a template (to apply on all service will inherite from template) or a single service and define "--filter-perfdata=no" for custom macro "EXTRAOPTIONS".

**Comment by StefThomas** [comment]
Thanks for the workaround.

This is a solution for the particular problem I have with the plugin _centreon_cisco_wlc.pl_ when monitoring an AP controller which is controlling more than 600 AP… but it’s not a general solution. If a plugin doesn’t have a filtering feature (or a perfdata on/off feature) I’m screwed (I need to modify the plugin, at least).

Please make the "process perfdata = yes/no" option available again.

And also, please, don’t remove a functionality that works, without a solid technical argument and without being sure it really is unused or a good alternative is available.

I’m disappointed by this sudden change in Centreon policy against the community and the will to remove the “not much used” features in Centreon… This is kind of upsetting for the future of the product :(

**Comment by lpinsivy** [comment]
Hi,

I understand your point of view, but it is not a regression of Centreon.

When Centreon was using (a long time ago) an internal process to generate perfdata from Nagios perfdata file (Centstorage), we used to add this option to have the possibility to optimize the operation on perfdata.

Since Centreon Broker, we optimized the process and now we generate automatically RRD files when a service have performance data.

If you don't want to generate RRD files, the only way is to manage the plugin to do not generate performance data.

You have also the possibility to manage the retention of data by reducing the size of RRD files:

- globally on "Administration > Parameters > Options" menu
- or by hostgroups

We do not want to reintroduce this option for Centreon Broker.

**Comment by StefThomas** [comment]
I know about the retention setting but that is a global setting.

I’m sorry you doesn’t want to admit it but from a user point of view there was a functionality at version X and this functionality is absent in next versions. This IS a regression from a users point of view. You force your users to change their workflow.

You choose optimization against functionality. Let see in the future if it is a good choice !

If I want to process perfdata for a given plugin but only for some hosts I’ll have to double the command or at least the service template (one with perfdata, one without). This is awfully not convenient at all.

This is your choice, I respect it and so close the case. I still think you’re going in the wrong direction.

Have a nice day.

**Comment by DonKiShoot** [comment]
Regression :-(
