### ISSUE TITLE
[18.10] The related host no longer exists in Centreon configuration. Please reload the configuration.

### ISSUE THREAD

**Issue by GitWatin** [centreon/centreon#7213]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

Centreon V18.10

***Operating System***

Centos 7 (Centreon ISO)

***Additional environment details (AWS, VirtualBox, physical, etc.):***

<h3> Description </h3>

 on RMS i can't see the state of service because i have this error 
The related host no longer exists in Centreon configuration. Please reload the configuration.
But when i fly over the icon i see the actual status of services

<h3> Steps to Reproduce </h3>

1. Create the service on Central
2. Reload config file 
3. Go to monitoring>Status Details > click on service

<h3> Describe the received result </h3>
The received result is : "The related host no longer exists in Centreon configuration. Please reload the configuration."
<h3> Describe the expected result </h3>
Expected result is see the correct page
<h3> Additional relevant information (e.g. frequency, ...) </h3>

@lpinsivy  i see on a older issues you have already encountered this problem

**Comment by lpinsivy** [comment]
Hi @snakeeyes5135

This error means that you try to access to a non existing object in configuration but still present in real time because the engine continu to monitor it (configuration not exported and Centreon Engine not restarted).

Because with your procédure, it is impossible to get this issue

Can you confirm?

**Comment by snakeeyes5135** [comment]
Hi @lpinsivy 

Many thanks for your answer

I configure 3 RMS and i have this issue only on two RMS
the last one running good 

I have already rexport config and restart but the problem still here 

Do you want some log ?? 

Regards

**Comment by burncycl** [comment]
I have the same problem. I'm adding and removing nodes using the CLAPI. Hosts end up "orphaned" in the database. They show up in the Host Status GUI, but not in the Configuration GUI.

**Comment by burncycl** [comment]
Additonally, when I add hosts using the CLAPI they show up in the GUI Configuration. The poller reports there is an update change. I then push the update through GUI (or with CLAPI), the newly added hosts do not show up in Centreon Host Status.

**Comment by AtConnect** [comment]
We confirm the problem, the modify is takes successfully, we reload, the host name is not changed, after the click on the host we have the error, but if i modify the hostname in the url i can go on the host

**Comment by hecko** [comment]
+1

**Comment by lpinsivy** [comment]
Hi,

Bugs related to a new configuration with RELOAD option for Centreon Engine has been corrected on the Centreon 19.10 version.
