### ISSUE TITLE
plugin=network::juniper::mag::plugin thresholds on graphs

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#7235]
Hello, 

i was working with the users mode for plugin network::juniper::mag::plugin. 
Graphs are working but i can't see warning and critical thresholds lines. As you can see below, we can not see this on graph, the line is blue and keeps being blue even on critical status. 

![image](https://user-images.githubusercontent.com/28105870/53501967-06d2bd80-3aa5-11e9-9a47-07104aea9ad0.png)

I would like to have something like that: 
![image](https://user-images.githubusercontent.com/28105870/53502146-67fa9100-3aa5-11e9-97fa-7d0528d70a79.png)

Tried to configure a template and a curve but it did not do the trick.

Can you help with this please ?

Regards

**Comment by CPbN** [comment]
See #7343.
