### ISSUE TITLE
Full screen mode Bug (div bug maybe)

### ISSUE THREAD

**Issue by gabyfulchic** [centreon/centreon#7236]
I'm using a Centos7.
Centreon 18.10.
On a OVH VPS.

I've set an autlogin connection to our centreon and made a script clicking on the full screen button at the right bottom.
I've set a Custom View with the service status and the engine status. (btw 2 widgets)
But when i watch the screen i just see a white bandage. (Maybe the difference between div full screen and the div main section expand.
My web page is launched in cmd with chromium in kiosk and incognito mode. 

``` -The first indication is to show you what i don't want to see (the top of letters from a sentence).```

```-The second indication in the picture is the white bandage not allowing me to display the full widgets informations :D ```

![image](https://user-images.githubusercontent.com/22600727/53559933-916df800-3b4b-11e9-80df-baefa996a476.png)

Warmly,
FULCHIC Gaby

**Comment by gabyfulchic** [comment]
I'm using the binary chromium to launch the web page, i'll try to update it or to change the browser so.
Ty for your response. And sorry for the delay.

Warmly,
FULCHIC Gaby

**Comment by adr-mo** [comment]
Hi @gabyfulchic 

Changing the browser **fixed the issue** ?

Regards,
