### ISSUE TITLE
Widget harmonization with Status Details

### ISSUE THREAD

**Issue by lordtaki** [centreon/centreon#7260]
<h1>ENHANCEMENT</h1>

When you have a service acknowledged and in downtime, the service monitoring widget displays this service differently than in Status Details.

Widget : yellow background
Status Details : purple background

It creates confusion on the user side.
By default it seems they expect to have the background in purple.

**Comment by sc979** [comment]
Hi lordtaki,

Indeed, this is an odd behavior. It's fixed and will be released in the next version.
You already apply the correction by downloading the file modified in this commit :
https://github.com/centreon/centreon-widget-service-monitoring/commit/e6db7ebae6e7b20ac17d74f6aa2330b270814d45
The file to replace is : `table.ihtml` in  `/usr/share/centreon/www/widgets/service-monitoring/src`

Sincerely,

sc979
