### ISSUE TITLE
Script Event Handler error

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon#727]
BOnjour, j'ai un script qui doit executer une commande si l'etat UNKNOWN HARD est confirmé au bout de 3 tentatives ou si  UNKNOWN SOFT est confirmé au bout de 3 tentatives.

Cependant dès que j'ajoute un nombre de tentative sur l'etat type HARD, j'ai une erreur :

[root@test eventhandler]##bash open-jira-service-inc.sh UNKNOWN HARD 2

Error : open-jira-service-inc.sh: ligne105: Erreur de syntaxe : fin de fichier prématurée

script : 
`#!/bin/sh

#Titre : Ce script permets de créer un ticket INCIDENT

case "$1" in

OK)
        ;;

WARNING)
    ;;

UNKNOWN)

    case "$2" in

    SOFT)
#Troisieme variable derriere la commande d'execution du script ($SERVICEATTEMPT$)
            case "$3" in

        #"3)" identifie le nombre de tentative avant d'executer le script
            3)

        #Troisieme variable derriere la commande d'execution du script ($SERVICEATTEMPT$)

        #"3)" identifie le nombre de tentative avant d'executer le script

        #commande à executer
            /usr/lib/centreon/plugins/centreon_notification_centreon_opentickets_api.pl --plugin notification::centreon::opentickets::api::plugin --mode=open-service --api-hostname='' --api-port=80 --api-proto=http --api-username='' --api-password='' --rule-name='jira' --host-id="$4" --service-id="$5" --service-output="$6" --service-state="$2" --select='jira_project=Incidents ' --select='jira_issuetype=Incident'

            ;;

            esac

        ;;

    HARD)
        case "$3" in

        #"3)" identifie le nombre de tentative avant d'executer le script
            3)

       #commande à executer
         /usr/lib/centreon/plugins/centreon_notification_centreon_opentickets_api.pl --plugin notification::centreon::opentickets::api::plugin --mode=open-service --api-hostname='' --api-port=80 --api-proto=http --api-username='' --api-password='' --rule-name='jira' --host-id="$4" --service-id="$5" --service-output="$6" --service-state="$2" --select='jira_project=Incidents ' --select='jira_issuetype=Incident'

        ;;

        esac

    ;;

esac

exit 0

`

Any idea ?

**Comment by omercier** [comment]
Hi @Xinerys, 
This issue is not bug-related, but if you still need help, you can go to https://thewatch.centreon.com/ and expose your problem. 
PS: I could not read your script because of bad markdown code block, take care of the format of your message ;-)
