### ISSUE TITLE
Graph can't have a integer value 

### ISSUE THREAD

**Issue by Benaly97** [centreon/centreon#7270]
<h1>Graph can't have a integer value</h1>

<h3> Prerequisites </h3>

***CentOS 6.8 , web 2.8.26, centengine 1.8.1, centreon-broker 3.0.16 ***

I monitore a integer value but the graph display a float number;

==> In the centstorage database, the field data_bin contain integer value such as the perfdata in the output of the plugin
==> In the rrd database there are a value such as the value in the graph, with a float value, so i think the problem is the rrd database 
==> The rrdtool info comand on my database give this response : 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
#rrdtool info /var/lib/centreon/status/499.rrd 
filename = "/var/lib/centreon/status/499.rrd"
rrd_version = "0003"
step = 1
last_update = 1552393621
header_size = 792
ds[value].index = 0
ds[value].type = "GAUGE"
ds[value].minimal_heartbeat = 3000
ds[value].min = NaN
ds[value].max = NaN
ds[value].last_ds = "100"
ds[value].value = 0,0000000000e+00
ds[value].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 51841
rra[0].cur_row = 50556
rra[0].pdp_per_row = 300
rra[0].xff = 5,0000000000e-01
rra[0].cdp_prep[0].value = 1,2100000000e+04
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 4321
rra[1].cur_row = 3717
rra[1].pdp_per_row = 3600
rra[1].xff = 5,0000000000e-01
rra[1].cdp_prep[0].value = 1,6210000000e+05
rra[1].cdp_prep[0].unknown_datapoints = 0
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
- the consolodation function is set to AVERAGE
- the step is set to : 1
It is calculate a average of one value in the rrdtool update, but i don't know why this value change in the rrd database

**Comment by lpinsivy** [comment]
Hi @Benaly97 you rights RRA are designed by Centreon to store float instead of integer.
We don't plan yet to offer the possibility to change this
