### ISSUE TITLE
RRD Graph Generation > The user that execute the export is also disconnected

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#728]
---

Author Name: **Etienne Gautier** (Etienne Gautier)
Original Redmine Issue: 6001, https://forge.centreon.com/issues/6001
Original Date: 2014-11-28

---

This request is linked to the fix made here : https://forge.centreon.com/issues/5239 which still contains a bug.

Bug description : If a user _foo_ is connected to Centreon and calls the generateImage.php using akey=XXXXXX&username=bar , the user _bar_ *+AND the user _foo_+* are disconnected.

There should be a check to make sure the session ID killed is linked to the user with the given autologin key.

Proposition : 

if (isset($_GET['akey'])) {
  $pearDB->query("DELETE FROM session WHERE session_id = '".$pearDB->escape($mySessionId)."' *AND user_id = (SELECT contact_id from contact where contact_autologin_key = '".$_GET['akey']."')*");
}

**Comment by kduret** [comment]
Linked to #3516

**Comment by Tpo76** [comment]
OK
