### ISSUE TITLE
Host contact groups displayed instead of service contact groups in Service Details View

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon#7288]
Hello,

We are currently encountering this issue in Centreon Web Version 2.8.27. 
I tried to reproduce the case using centreon-vm version **centreon-central-18_10-3.el7.ova** and it seems to be still present in this version.

<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***

centreon-central-18_10-3.el7.ova

<h3> Description </h3>

Despite the fact that we had different contacts in services configuration than in host notification configuration, the  "Contact groups notified for this service" display the Host contacts list

<h3> Steps to Reproduce </h3>

1. Create a host template A and add a contact group A to this template
2. Create a service template B and add a contact group B to this template
3. Link the service template B to the host template A
4. Create a New host based on host template A and generate linked services
5. In Monitor View, Reach the Status Details View for the service linked to the new host generated from the service template B 
6. Look at Notifications > Contact groups notified for this service

<h3> Describe the received result </h3>

You will see the contact group A instead of the group contact B

<h3> Describe the expected result </h3>

You are supposed to see the contact group B

<h3> Additional relevant information (e.g. frequency, ...) </h3>

Thank You :)

**Comment by adr-mo** [comment]
Hi @anthoc,

Thanks for the feedback 💯

We we'll check for this issue, if it is confirmed, we will open an internal ticket and fixe the issue.

Regards,

**Comment by anthoc** [comment]
Hello,

Do you have any information about this issue please ? We upgraded to 19.03 and it's still there.

Thank you 

Regards,

**Comment by lpinsivy** [comment]
Should be corrected by https://github.com/centreon/centreon/pull/7917
