### ISSUE TITLE
[Feature] Generate graphs for hosts themselves

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7304]
Hi,

For now, graphs are generated only for services.
It would however be nice to generate graphs for hosts themselves.
This could be possible using the performance data from the host check command.
Would in most cases be a latency graph.

Thank you very much :+1:

Edit : not present in 19.04.0.

**Comment by adr-mo** [comment]
Hi @CPbN,

This needs to be discussed with our **Product Manager** @lpinsivy 

We'll let you know if it will be taken into account for the next sprints.

Regards,

**Comment by CPbN** [comment]
@adr-mo, perfect, thank you very much for your response, and for discussing this !

**Comment by CPbN** [comment]
As a workaround, here is a broker Stream connector Lua script (Neb filter) which grabs hosts' performance data to feed `host-latency` passive services, thus generating latency graphs.

This example also filters-out localhost data, and some ("unwanted") performance metrics.
It needs broker and engine to be on the same host, but could be enhanced for distributed infras.

```
function init(conf)
  -- used to deduplicate input, see https://github.com/centreon/centreon-broker/issues/201
  output = ""
end

function write(d)
  -- no need to generate a localhost latency graph
  if string.find(d.output, " - localhost ") then
    return true
  end
  local host_name = broker_cache:get_hostname(d.host_id)
  if not host_name then
    return true
  end
  local state = d.state
  if state ~= 0 then
    state = 2
  end
  local new = "[" .. d.last_update .. "] PROCESS_SERVICE_CHECK_RESULT;" .. host_name .. ";host-latency;" .. state .. ";" .. d.output:sub(1, -2) .. " | " .. d.perfdata:gsub("'?rtm..'?=[^ ]* " , "") .. "\n"
  if new ~= output then
    local file = io.open('/var/lib/centreon-engine/rw/centengine.cmd', 'a')
    file:write(output)
    file:close()
  end
  output = new
  return true
end

function filter(category, element)
  if category == 1 and element == 14 then
    return true
  end
  return false
end
```

**Comment by lpinsivy** [comment]
Hi @CPbN we don't plan to generate graph for host.

The workaround is to create a service for this host.

Regards,

**Comment by CPbN** [comment]
Hi @lpinsivy, and thank you for your answer.
From my point of view, with an additional service, we poll devices twice for the same thing, instead of using perfdata which has already been generated by the host check command. This is sort of "useless" workload.
In addition, using perfdata from the host check command would generate a more accurate graph, in respect with the host alerts which could have been generated.
There's the workaround above, but this could certainly be done more flawlessly.
This is just my point of view :-)
Thank you :+1:

**Comment by lpinsivy** [comment]
@CPbN Thank you for your feedback. I keep this in mind
