### ISSUE TITLE
Widget : Storage list near saturation

### ISSUE THREAD

**Issue by maffeltranger** [centreon/centreon#7307]
Hello everyone ! 

Do you know if there is a way to download this widget nowadays ? Can't find any information about it. (Centreon version 18.10.3)

https://documentation.centreon.com/docs/centreon-bi-2/en/3.1.x/widgets/mbi-storage-list-near-saturation.html

Thanks !

Regards

**Comment by Moujimouja** [comment]
Hello,

You can't download it directly, it's part of Centreon EMS solutions that needs a commercial license. This widgets belongs to "[Centreon MBI](https://documentation.centreon.com/docs/centreon-bi-2/en/latest/)".

If you need more information on Centreon MBI and/or Centreon EMS you may contact our sales services (sales@centreon.com)

[Centreon EMS solution](https://www.centreon.com/en/solutions/centreon-ems/):
![Capture d’écran 2019-03-21 à 15 17 13](https://user-images.githubusercontent.com/6620287/54758450-7ba09f80-4bec-11e9-9084-f08d13289bd9.png)
