### ISSUE TITLE
Graphs: strange char & missing dates in exports

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7310]
Hi,

There are 2 issues with exported graphs, see the example below :
- a strange `\l` character is visible in the last line of the legend ;
- From / to dates are missing / empty.

![tools-sys-cpu](https://user-images.githubusercontent.com/40244829/54745988-4fc0f200-4bcb-11e9-8f56-d0ebd31d170d.png)

Thank you 👍 

Edit : please see #7316 for a fix.

Edit : issue still present in 19.04.3.

**Comment by adr-mo** [comment]
Hi @CPbN,

Thanks for the feedback :100: 

I have just tried on my server several exports

- Using **FROM** (manual date) **TO** (manual date)
- Using **pre-defined timeperiods**

![Central-Server-Load](https://user-images.githubusercontent.com/31647811/54752837-bb14bf00-4bdf-11e9-96f3-29418b1250e2.png)

I do **not** have the issues that you have encountered.

Do you have this issue on all the graphs, or only this one ?

Regards,

**Comment by adr-mo** [comment]
Also I found an issue, exporting splitted graphs does not work here is the patch for this if you encounter this issue. I have opened an issue https://github.com/centreon/centreon/issues/7312 for it and made the patch https://github.com/centreon/centreon/pull/7314

**Comment by CPbN** [comment]
So, same issue from both "Graphs" and "Chart split" views.

I have issue on all graphs, on 2 different servers.
Servers are installed following the documentation, from packages :
https://documentation.centreon.com/docs/centreon/en/latest/installation/from_packages.html
Everything's uptodate (`yum makecache ; yum update` does not update anything).

I verified, in `generateImage.php`, `$obj->checkArgument("end", $_GET, time())` correctly returns a timestamp (seconds from 1970).

I tried to change my Centreon user locale, same issue.
Strangely enough, the only locale available on my uptodate Centos 7 servers is the following :
```
# localectl list-locales
en_US.utf8
```

I also tried to change / play with the graph template, but it did not help.

I'm still investigating, but I'm not sure where to look at.

Thank you 👍

**Comment by CPbN** [comment]
OK, going through the code I found the issue for the start / end issue.
I went to Administration / My Account, Timezone / Location was empty.
I set a timezone and now it's OK 👍
Perhaps we could take the server's timezone if user did not set its own timezone.

There's still the `\l` char remaining though.

**Comment by CPbN** [comment]
OK, going through the code I found the issue for the start / end issue.
I went to Administration / My Account, Timezone / Location was empty.
I set a timezone and now it's OK 👍
Perhaps we could take the server's timezone if user did not set its own timezone.

There's still the `\l` char remaining though.
Culprit is certainly somewhere there :
https://github.com/centreon/centreon/blob/18.10.3/www/class/centreonGraph.class.php#L969

**Comment by CPbN** [comment]
I simply removed `. "\\l "` from the quoted line above, and it solves the issue :

![tools-sys-cpu-2](https://user-images.githubusercontent.com/40244829/54762841-27e68400-4bf5-11e9-862b-2a37590208fd.png)

Perhaps we should also remove it from line 969.

**Comment by adr-mo** [comment]
Nice @CPbN !

Do not hesitate to open a pull request :100: 

Thanks !

Regards,

**Comment by CPbN** [comment]
Please see #7316 :+1: 
Thank you !
