### ISSUE TITLE
NRPE: No output returned from plugin after Upgrade to 18.10.3

### ISSUE THREAD

**Issue by liquitwalker** [centreon/centreon#7311]
**Prerequisites**
Centreon V18.10

**Operating System**

Centos 7 (Centreon ISO)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtual machine running under VMware

**Description**

Upgraded Centreon from 2.8.26 to 18.10.3.
The upgrade itself worked fine. Unfortunately, I encountered one big problem: 
All my checks done by NRPE return "(No output returned from plugin)". 
If I use 'check_nrpe' manually via shell, all the checks work fine and return their output. 

**Steps to Reproduce**

Create the service on Central
Export configuration
Go to monitoring > Status Details -> Services -> See status information of service

**Describe the received result**

The received result is : "No output returned from plugin"

**Describe the expected result**

Expected result is to see the output of the NRPE check

**Additional relevant information (e.g. frequency, ...)**

All possible network problems (e.g. firewall) were already checked by me.

**Comment by Fen0l** [comment]
Hi, Had the same problem and the issue was related to the centreon-plugins and nagios-plugins package upgrade. Scripts went from /usr/lib to /usr/lib64 and broke all my commands.
 Does the path and permission are corrects ?

**Comment by lpinsivy** [comment]
The documentation explains how to migrate specially for plugins : https://documentation.centreon.com/docs/centreon/en/latest/migration/upgradetoCentreon18.10.html#synchronizing-the-plugins
