### ISSUE TITLE
[GRAPHS] Can't export 'splitted' graphs 

### ISSUE THREAD

**Issue by adr-mo** [centreon/centreon#7312]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***
```
[root@localhost ~]# rpm -qa | grep centreon-web
centreon-web-18.10.3-5.el7.centos.noarch
```
***Operating System***

```
[root@localhost ~]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
```

<h3> Description </h3>

It is not possible to export 'splitted' graphs.

<h3> Steps to Reproduce </h3>

1. Go to Monitoring -> Performances -> Graphs
2. Select a service that has several metrics
3. Display those by splitting the main graph
4. Try to export

<h3> Describe the received result </h3>

**ERROR 500**

<h3> Describe the expected result </h3>

Graph exported.

**Comment by CPbN** [comment]
I'm facing this too :
```
PHP Fatal error:  Uncaught Error: Class 'PEAR' not found in /usr/share/centreon/www/include/views/graphs/generateGraphs/generateMetricImage.php:74
Stack trace:
#0 {main}
  thrown in /usr/share/centreon/www/include/views/graphs/generateGraphs/generateMetricImage.php on line 74
```

**Comment by CPbN** [comment]
OK, I just saw your patch, let's test it.

**Comment by adr-mo** [comment]
Hi @CPbN,

Okay thanks ! :100: 

Regards,

**Comment by CPbN** [comment]
OK @adr-mo, patch corrects the issue 👍 Thx !

**Comment by adr-mo** [comment]
@CPbN Nice :+1: 

This ticket will enter our delivery process, and the patch should be available for the next release.

Regards,
