### ISSUE TITLE
Upgrade from 2.8.27 to 18.10

### ISSUE THREAD

**Issue by ArnoMLT** [centreon/centreon#7317]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon
centreon-license-manager-common-18.10.2-1.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190221-145606.el7.centos.noarch
centreon-broker-core-18.10.1-1.el7.centos.x86_64
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-license-manager-18.10.2-1.el7.centos.noarch
centreon-18.10.3-5.el7.centos.noarch
centreon-widget-grid-map-18.10.0-6.el7.centos.noarch
centreon-widget-servicegroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-widget-graph-monitoring-18.10.0-6.el7.centos.noarch
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-database-18.10.3-5.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190221-145606.el7.centos.noarch
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Database-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190221-145606.el7.centos.noarch
centreon-broker-storage-18.10.1-1.el7.centos.x86_64
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-poller-centreon-engine-18.10.3-5.el7.centos.noarch
centreon-pp-manager-18.10.4-1.el7.centos.noarch
centreon-base-config-centreon-engine-18.10.3-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-18.10.0-6.el7.centos.noarch
centreon-widget-hostgroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-widget-engine-status-18.10.0-9.el7.centos.noarch
centreon-widget-tactical-overview-18.10.0-6.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-18.10.0-6.el7.centos.noarch
centreon-release-18.10-2.el7.centos.noarch
centreon-perl-libs-18.10.3-5.el7.centos.noarch
centreon-widget-host-monitoring-18.10.1-1.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190221-145606.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190221-145606.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190221-145606.el7.centos.noarch
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Databases-Mysql-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190221-145606.el7.centos.noarch
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64
centreon-broker-cbmod-18.10.1-1.el7.centos.x86_64
centreon-web-18.10.3-5.el7.centos.noarch
centreon-common-18.10.3-5.el7.centos.noarch
centreon-broker-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Dns-20190221-145606.el7.centos.noarch
centreon-widget-service-monitoring-18.10.2-1.el7.centos.noarch
centreon-trap-18.10.3-5.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190221-145606.el7.centos.noarch

```

***Operating System***

*CentOS 7*

<h3> Description </h3>

I attempted to migrate from 2.8.27 (rpm based install on centos 6) to 18.10 (ISO version 18.10.3).
Following the doc [https://documentation.centreon.com/docs/centreon/en/latest/migration/upgradetoCentreon18.10.html](https://documentation.centreon.com/docs/centreon/en/latest/migration/upgradetoCentreon18.10.html)

On new Centreon, after the database import, no lateral menu is shown.

It seems the step 4 'database migration' doesn't do anything because there is no sql procedure to migrate from 2.8.27. Only 2.8.26 to 18.10.0
work around : renamed Update-DB-2.8.26_to_18.10.0.sql to Update-DB-2.8.27_to_18.10.0.sql and edit : 
`DELETE FROM `options` WHERE `key` = 'centcore_illegal_characters';`

**Comment by adr-mo** [comment]
Hi @ArnoMLT,

What is the exact version of the ISO that you used to install Centreon ? Was it this one ?
https://download.centreon.com/index.php?product=centreon-18.10-8.el7.x86_64&action=ask&id=4845

Regards,

**Comment by ArnoMLT** [comment]
Hi,
Yes I downloaded it 2 days ago with this link : [http://iso.download.centreon.com/stable/centreon-18.10-8.el7.x86_64.iso](http://iso.download.centreon.com/stable/centreon-18.10-8.el7.x86_64.iso)
from this page [https://download.centreon.com/index.php?action=download&id=4845](https://download.centreon.com/index.php?action=download&id=4845)

**Comment by adr-mo** [comment]
Ok in fact there is a big issue there.

Thanks for the feedback :100:

We are going to make things right and correct this ASAP !

Regards,

**Comment by adr-mo** [comment]
@ArnoMLT This will be fixed by the 18.10.4 that will be released soon.

https://github.com/centreon/centreon/tree/18.10.4/www/install/sql/centreon

**Comment by ArnoMLT** [comment]
OK so I postpone the upgrade until 18.10.4 is released
Thanks !

**Comment by adr-mo** [comment]
Hi @ArnoMLT,

The 18.10.4 has now been **released**.

Let me know if your issue has been fixed.

I'll close the issue if it is the case.

Regards,

**Comment by ArnoMLT** [comment]
Start again with a fresh install from iso + yum update.
When processing http://xxxx/centreon/install/upgrade.php, step 3 still shows 18.10.3 but the end of the upgrade is ok.
I'm in 18.10.4, and the issue is gone !

Thanks a lot for your reactivity 👍

**Comment by adr-mo** [comment]
You are more than welcome.

Thanks again for the feedback.

**FYI** The issue you have encountered with the release note (18.10.3 displayed instead of 18.10.4) is a **known issue** related to browser cache.

Closing the issue.

Regards,
