### ISSUE TITLE
[2.8.27] Recurrent downtime not working

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon#7319]
Centreon Web version: centreon-web-2.8.27
Centreon Engine version: centreon-engine-1.8.1
Centreon Broker version: centreon-broker-3.0.16

OS: CentOS release 7 (Final)

Additional environment details (AWS, VirtualBox, physical, etc.):
310 hosts for 2512 services
1 central and 2 poller

Steps to reproduce the issue:

Configure recurrent downtime for a host
Stop/reboot a host within recurrent downtime
Receive a notification

Describe the results you received:
Receive a notification

Describe the results you expected:
No notification in the recurrent downtime

Additional information you think important (e.g. issue happens only occasionally):
 /var/log/centreon/downtimeManager.log is empty
no logs in Centreon Engine regarding  EXTERNAL COMMAND: SCHEDULE_HOST_DOWNTIME

**Comment by R00T88** [comment]
Before upgrade from 2.8.26 to 2.8.27 there was downtime handled correctly


[1552579803] [6327] EXTERNAL COMMAND: SCHEDULE_HOST_DOWNTIME;server1;1552580400;1552588200;1;0;0;Downtime cycle;[Downtime cycle #5]
[1552579803] [6327] EXTERNAL COMMAND: SCHEDULE_HOST_SVC_DOWNTIME;server1;1552580400;1552588200;1;0;0;Downtime cycle;[Downtime cycle #5]
[1552580400] [6327] HOST DOWNTIME ALERT: server1;STARTED; Host has entered a period of scheduled downtime

After upgrade if recurrent downtime is set it's not handled anymore

**Comment by R00T88** [comment]
This are the file permission on /var/log/centreon

![image](https://user-images.githubusercontent.com/9050487/54840658-c47c5500-4ccd-11e9-8cac-76ea5442258e.png)

/var/log/centreon-broker
![image](https://user-images.githubusercontent.com/9050487/54842344-fc859700-4cd1-11e9-9f02-f4807c879f4e.png)

**Comment by adr-mo** [comment]
Hi @R00T88,

Thanks for the feedback :100: !

Could you please confirm that everything is working fine regarding the **centcore** process.

`systemctl status centcore` 

Could you also check for errors in the centcore logs ?

`tail -f /var/log/centreon/centcore.log`

Regards,

**Comment by R00T88** [comment]
Hi @adr-mo 
upgrading centreon from 2.8.26 to 2.8.27 change owner of file central-module-master.log in /var/log/centreon-broker from centreon-engine to centreon-broker
after adjust permission and restart both centengine and httpd all works perfect

Thanks

**Comment by adr-mo** [comment]
Hi,

Ok nice so I'll close the issue if it is ok for you.

Thanks 💯

Regards,
