### ISSUE TITLE
Graphs: dual y-axis graph exports have a single axis

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#7329]
Hi,

Let's take this dual y-axis graph as an example :

![ex](https://user-images.githubusercontent.com/40244829/54865528-e544b900-4d66-11e9-8e9f-7d926f3c3268.png)

As you can see, its exported version only has one y-axis :

![ex2](https://user-images.githubusercontent.com/40244829/54865491-78312380-4d66-11e9-8c5b-2331a197e9a1.png)

Could we then make the exported graphs with 2 y-axis ?

Thank you very much 👍 

Edit : issue still present in 19.04.3 (not re-tested, closing this then, feel free to re-open if needed).

**Comment by adr-mo** [comment]
Hi @CPbN 

Thanks for the feedback :100: 

We will check for this issue, if it is confirmed, we will open an internal ticket and fixe the issue.

Regards,
