### ISSUE TITLE
Graphs: series without unit do not trigger a second y-axis

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7330]
Hi,

Let's take these series as an example :

![ex1b](https://user-images.githubusercontent.com/40244829/54865600-2a1d1f80-4d68-11e9-8550-8054a30083eb.png)

They generate the nice dual y-axis graph below :

![ex1](https://user-images.githubusercontent.com/40244829/54865606-330df100-4d68-11e9-8e51-18f06452ace1.png)

Perfect.

Now, let's change the units so that packets are no more in % but absolute, so no unit :

![ex2b](https://user-images.githubusercontent.com/40244829/54865615-4caf3880-4d68-11e9-8fcc-0e2e13037f6c.png)

Unfortunately, now, as you can see, the generated graph has only one y-axis :

![ex2](https://user-images.githubusercontent.com/40244829/54865618-5c2e8180-4d68-11e9-87b1-3dc9d60e4a87.png)

Could we then consider the series without unit different from the others, so that they can be related to a second y-axis ?

Thank you very much 👍 

Edit : issue still present in 19.04.0.

**Comment by adr-mo** [comment]
Hi @CPbN 

Thanks for the feedback :100: 

We will check for this issue, if it is confirmed, we will open an internal ticket and fixe the issue.

This might need discussions with our **Product Manager** @lpinsivy 

Regards,

**Comment by CPbN** [comment]
Fixed in #7341 👍
