### ISSUE TITLE
Disabling "Display Autologin shortcut" has no effect

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7331]
Hi,

Even with "Display Autologin shortcut" disabled :
(in Administration / Centreon UI / Authentication properties)

![set](https://user-images.githubusercontent.com/40244829/54877978-2059f180-4e26-11e9-8834-4eeb08a2718e.png)

Autologin link shows :

![auto](https://user-images.githubusercontent.com/40244829/54877990-441d3780-4e26-11e9-8aa9-8e41ac57c14f.png)

Could we then correct this ?

Thank you 👍

Edit : issue still present in 19.10.0-beta.2.

**Comment by CPbN** [comment]
Crappy workaround :

In `www/static/js/main.*.chunk.js :`

Replace :
`i&&r.a.createElement(r.a.Fragment,null,r.a.createElement("button",{className:"submenu-user-button"`

With :
`i&&r.a.createElement(r.a.Fragment,null,r.a.createElement("button",{className:"submenu-user-button hidden-input"`

**Comment by adr-mo** [comment]
Hi @CPbN 

Thanks for the feedback :100: 

We we'll check for this issue, if it is confirmed, we will open an internal ticket and fixe the issue.

Regards,

**Comment by CPbN** [comment]
Still facing this small issue in 19.10.0-beta.2.
Perhaps we could then merge this tiny fix.
Thank you 👍

**Comment by CPbN** [comment]
Fixed by #7340, thank you.
