### ISSUE TITLE
enh: Remove process_perf_data directive in Centreon

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#7333]
Hi,

Engine configuration talks about `process_perf_data` directive :

![eng](https://user-images.githubusercontent.com/40244829/54883134-819fb600-4e62-11e9-9ba1-59c00fcb2001.png)

However, sounds like the option has disappeared, as per the host (template) config :

![sc](https://user-images.githubusercontent.com/40244829/54883131-79e01180-4e62-11e9-9766-0136ad5f9765.png)

Same for service (template).

Any reason why ?

Thank you 👍

Edit : issue still present in 19.10.10.

**Comment by adr-mo** [comment]
Hi @CPbN,

Thanks for the feedback :100: 

We we'll check for this issue, if it is confirmed, we will open an internal ticket and fixe the issue.

Regards,

**Comment by lpinsivy** [comment]
Those options must be disappear.

To export performance data use [Centreon Stream connector](https://documentation.centreon.com/docs/centreon/en/latest/developer/writestreamconnector.html).

**Comment by UrBnW** [comment]
Closing as not important, feel free to re-open if needed...
