### ISSUE TITLE
Centreontrapd error after latest upgrade

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon#7336]
CES: 18.10.4

Hello,

Since the latest update (Web 18.10.4) i have an error with Centreontrapd process.

The service doesn't run anymore...

This is the errors log:

Mar 25 11:45:59 Centreon.localdomain centreontrapd[7858]: 2019-03-25 11:45:59 - 7858 - ********** Net-SNMP version 5.0702 Perl module enabled **********
Mar 25 11:45:59 Centreon.localdomain centreontrapd[7858]: 2019-03-25 11:45:59 - 7858 - Mode: poller
Mar 25 11:45:59 Centreon.localdomain centreontrapd[7858]: 2019-03-25 11:45:59 - 7858 - MySQL error: no such table: cfg_nagios (caller: centreon::script::centreontrapd:/usr/share/perl5/vendor_perl/centreon/script/centreontrapd.pm:1188)
Mar 25 11:45:59 Centreon.localdomain centreontrapd[7858]: Query: SELECT `command_file` FROM `cfg_nagios` WHERE `nagios_activate` = '1' LIMIT 1
Mar 25 11:45:59 Centreon.localdomain centreontrapd[7858]: 2019-03-25 11:45:59 - 7858 - Can't call method "fetchrow_array" on an undefined value at /usr/share/perl5/vendor_perl/centreon/script/centreontrapd.pm line 1189.
Mar 25 11:45:59 Centreon.localdomain centreontrapd[7858]: 2019-03-25 11:45:59 - 7858 - Main process exit.

Thanks.

**Comment by leandroschatts** [comment]
Hello,
I have the same error.

**Comment by PhilippeA1** [comment]
Hello,
I have the same error : 

mar 29 10:59:14 Centreon systemd[1]: Started Centreon Trapd Daemon is a Centreon program that manage traps.
mar 29 10:59:14 Centreon centreontrapd[7770]: 2019-03-29 10:59:14 - 7770 - ********** Net-SNMP version 5.0702 Perl module enabled **********
mar 29 10:59:14 Centreon centreontrapd[7770]: 2019-03-29 10:59:14 - 7770 - Mode: poller
mar 29 10:59:14 Centreon centreontrapd[7770]: 2019-03-29 10:59:14 - 7770 - MySQL error: no such table: cfg_nagios (caller: centreon::sc...m:1188)
mar 29 10:59:14 Centreon centreontrapd[7770]: Query: SELECT `command_file` FROM `cfg_nagios` WHERE `nagios_activate` = '1' LIMIT 1
mar 29 10:59:14 Centreon centreontrapd[7770]: 2019-03-29 10:59:14 - 7770 - Can't call method "fetchrow_array" on an undefined value at ...e 1189.
mar 29 10:59:14 Centreon centreontrapd[7770]: 2019-03-29 10:59:14 - 7770 - Main process exit.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by JohnTianGuo** [comment]
I have this same issue too. and when i upgrade the remote poller to the centreon-central 
but in the web pages ,in the Configuration-> not found the pollers and other menu,only remaining the Users and Groups
how can I solve this? 
give me help please.

**Comment by dburtin** [comment]
It seems the problem lies in the file /etc/centreon/centreontrapd.pm, at least if you're using central poller.
It does not contain extra options for centreontrapd, but what should be the content of /etc/centreon/conf.pm for a remote poller.
I renamed /etc/centreon/centreontrapd.pm, now centreontrapd is starting without errors.

**Comment by BlackstormFirst** [comment]
Hi, still no official answers ? :)

@dburtin, thanks that help to restart the service on my dev env.

Now we are waitting for an official patch from Centreon ^^

Best regards,

**Comment by PhilippeA1** [comment]
Hi,    
Rename /etc/centreon/centreontrapd.pm correct the problem.

Best regards

**Comment by JohnTianGuo** [comment]
thank for all of you i correct this issue 。

**Comment by tetsumaki** [comment]
Hi, same problem with fresh install.

Content of /etc/centreon/centreontrapd.pm (poller mode) :

```
# cat /etc/centreon/centreontrapd.pm
#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
        # databases credentials
        centreon_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        centstorage_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        db_type => 'SQLite',
        # server type (0: central, 1: poller)
        mode => 1
);

1;
```

Step to reproduce :

```
# cd /etc/snmp/centreon_traps/
# rm -rf *
```

Go to Configuration  >  SNMP Traps  >  Generate and regenerate your conf.

```
# tree /etc/snmp/centreon_traps
/etc/snmp/centreon_traps
├── 1
│   └── centreontrapd.sdb
├── 10
│   └── centreontrapd.sdb
├── 11
│   └── centreontrapd.sdb
├── 2
│   └── centreontrapd.sdb
├── 3
│   └── centreontrapd.sdb
├── 4
│   └── centreontrapd.sdb
├── 5
│   └── centreontrapd.sdb
├── 6
│   └── centreontrapd.sdb
├── 7
│   └── centreontrapd.sdb
├── 8
│   └── centreontrapd.sdb
└── 9
    └── centreontrapd.sdb
```

Db SQLite create in **id** folder (1 for central, 2 for poller, 3 for other poller, etc).

Normaly, db is create in :

- `/etc/snmp/centreon_traps/centreontrapd.sdb`

and not in :

- `/etc/snmp/centreon_traps/X/centreontrapd.sdb`

If you launch centreontrapd, he try to launch db in :`/etc/snmp/centreon_traps/centreontrapd.sdb` and he create new file centreontrapd.sdb with size 0.

````
# su - centreon -c '/usr/bin/perl /usr/share/centreon/bin/centreontrapd --severity=debug --config=/etc/centreon/conf.pm  --config-extra=/etc/centreon/centreontrapd.pm'
2019-04-09 12:44:15 - 8947 - ********** Net-SNMP version 5.0702 Perl module enabled **********
2019-04-09 12:44:15 - 8947 - ********** MIBS:  **********
2019-04-09 12:44:15 - 8947 - centreontrapd launched....
2019-04-09 12:44:15 - 8947 - PID: 8947
2019-04-09 12:44:15 - 8947 - Mode: poller
2019-04-09 12:44:15 - 8947 - MySQL error: no such table: cfg_nagios (caller: centreon::script::centreontrapd:/usr/share/perl5/vendor_perl/centreon/script/centreontrapd.pm:1188)
Query: SELECT `command_file` FROM `cfg_nagios` WHERE `nagios_activate` = '1' LIMIT 1

2019-04-09 12:44:15 - 8947 - Can't call method "fetchrow_array" on an undefined value at /usr/share/perl5/vendor_perl/centreon/script/centreontrapd.pm line 1189.

2019-04-09 12:44:15 - 8947 - Main process exit.
````

Error and create empty file :

````
# du -h centreontrapd.sdb
0       centreontrapd.sdb
# tree
.
├── 1
│   └── centreontrapd.sdb
├── 10
│   └── centreontrapd.sdb
├── 11
│   └── centreontrapd.sdb
├── 2
│   └── centreontrapd.sdb
├── 3
│   └── centreontrapd.sdb
├── 4
│   └── centreontrapd.sdb
├── 5
│   └── centreontrapd.sdb
├── 6
│   └── centreontrapd.sdb
├── 7
│   └── centreontrapd.sdb
├── 8
│   └── centreontrapd.sdb
├── 9
│   └── centreontrapd.sdb
└── centreontrapd.sdb

11 directories, 12 files
````

For me, it's a critical bug.

**Comment by garnier-quentin** [comment]
It seems like a package bug. Change "/etc/centreon/centreontrapd.pm" file:
```
# cat /etc/centreon/centreontrapd.pm
#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
        # server type (0: central, 1: poller)
        mode => 0
);

1;
```

**Comment by tetsumaki** [comment]
@garnier-quentin yes, mode central work's fin but the package is fixed soon for poller mode ?

**Comment by lolokai** [comment]
Hello,
I have the same issue.
Regards,

**Comment by lpinsivy** [comment]
We change the packaging in 18.10.5 and 19.04.2, can you update and check ?

for a poller you must have:
```
#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
        # databases credentials
        centreon_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        centstorage_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        db_type => 'SQLite',
        # server type (0: central, 1: poller)
        mode => 1
);

1;
```

Regards,

**Comment by PhilippeA1** [comment]
With update 19.04.2 the problem is solved, but the file /etc/centreon/centreontrapd.pm has "mode => 0" : 
#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
        # databases credentials
        centreon_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        centstorage_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        db_type => 'SQLite',
        # server type (0: central, 1: poller)
        **mode => 0**
);

1;

**Comment by lpinsivy** [comment]
@PhilippeA1 on a poller ?

**Comment by PhilippeA1** [comment]
@lpinsivy where can i see if on a poller ?

**Comment by lpinsivy** [comment]
If you install/update a Centreon central server you must have:

```
#############################################
# File Added by Centreon
#

$centreon_config = {
       VarLib => "/var/lib/centreon",
       CentreonDir => "/usr/share/centreon/",
       "centreon_db" => "CENTREON_DB",
       "centstorage_db" => "CENTREON_STORAGE_DB",
       "db_host" => "HOST",
       "db_user" => "USER",
       "db_passwd" => "PASSWORD"
};

# Central or Poller ?
$instance_mode = "central";

# Centreon Centcore Command File
$cmdFile = "/var/lib/centreon/centcore.cmd";

# Deprecated format of Config file.
$mysql_user = "USER";
$mysql_passwd = "PASSWORD";
$mysql_host = "HOST";
$mysql_database_oreon = "CENTREON_DB";
$mysql_database_ods = "CENTREON_STORAGE_DB";

#1;
```

And on simple remote poller:

```
#############################################
# File Added by Centreon
#
our %centreontrapd_config = (
        # databases credentials
        centreon_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        centstorage_db => "dbname=/etc/snmp/centreon_traps/centreontrapd.sdb",
        db_type => 'SQLite',
        # server type (0: central, 1: poller)
        mode => 1
);

1;
```

**Comment by PhilippeA1** [comment]
on central

**Comment by lpinsivy** [comment]
@PhilippeA1 so it is ok now ?

**Comment by PhilippeA1** [comment]
yes, it's ok. Thank.
