### ISSUE TITLE
Downtime - GUI wrongly compute end date

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#7337]
Hi,

When you set a downtime, the popup shows with pre filled values.
If you are near the end of the day, and the downtime period is across 2 days, the end day is wrongly computed.

As shown below, where day should be 26 instead of 25.
There's certainly the same issue with month and year.

<img width="653" alt="down" src="https://user-images.githubusercontent.com/40244829/54959794-8778c280-4f5a-11e9-9ae6-65ef3bd6829e.png">

_If you are used to quickly set downtimes with default settings, and don't pay attention to the end date, downtime will be accepted by the popup but will not then show up anywhere, which is at first tricky to understand._

Thank you 👍

Edit : issue still present in 19.10.10.

**Comment by adr-mo** [comment]
Hi @CPbN 

Again thanks for the feedback :100: 

We are going to check, if confirmed we will open an internal ticket and let you know when the patch will be available :+1: 

Regards,

**Comment by CPbN** [comment]
This is in some kind related to #5963, perhaps 2 issues could be solved in one PR :)

**Comment by CPbN** [comment]
See PR #7357 for a fix 👍

**Comment by CPbN** [comment]
See PR #7606 for a fix :+1:

**Comment by sc979** [comment]
Hi @UrBnW ,
The pull request with the modifications have been merged : https://github.com/centreon/centreon/pull/8486,
and will be merged on the specified next targeted version after validation.
Best Regards,
sc979
