### ISSUE TITLE
[Poller status] - Configuration not marked modified when change hostgroup/servicegroup with clapi

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#7350]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***

**Centreon Web version**: 2.8.26
**Centreon CLAPI version**: 1.8.0
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.16

***Operating System***

**OS**: CentOS release 6.10 (Final)

***Additional environment details (AWS, VirtualBox, physical, etc.):***

<h3> Description </h3>

When servicegroup or hostgroup is modified by CLAPI, the poller configuration status isn't marked "changed"

<h3> Steps to Reproduce </h3>

1. make a modification threw CLAPI on a hostgroup or servicegroup with a command like this
`$path_clapi/centreon  -u $user_clapi -p $pass_clapi -o SG -a addservice -v "${servicegroup};${host},${service}"`
2. go to poller menu

<h3> Describe the received result </h3>
None poller marked "conf changed"

<h3> Describe the expected result </h3>
Poller should be marked "conf changed"

<h3> Additional relevant information (e.g. frequency, ...) </h3>
It's probably the same with API Rest but not tested.

**Comment by lpinsivy** [comment]
Hi @cmeschin. It is the same with web form, CLAPI or API.

If you didn't edit direct properties of hosts or services the column "changed" will always display "no".
It is very difficult to calculate the indirect impacts (groups, templates, ...) and to display this on the poller listing page.

**Comment by cmeschin** [comment]
Hi @lpinsivy .
Ok I understand. I try to get this information by another way.
If I find a quickly method, I'll send back here.

Thanks.

**Comment by lpinsivy** [comment]
@cmeschin thank. I will close this ticket. Do not hesitate to reopen if you have a solution.

Regards,
