### ISSUE TITLE
[2.8.27] Enable debug properties

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon#7364]
Centreon Web version: centreon-web-2.8.27
Centreon Engine version: centreon-engine-1.8.1
Centreon Broker version: centreon-broker-3.0.16

OS: CentOS release 7 (Final)

Additional environment details (AWS, VirtualBox, physical, etc.):
310 hosts for 2512 services
1 central and 2 poller

Steps to reproduce the issue:

Enable a debug options for example "Centcore Engine debug" and click Save.

Describe the results you received:

Impossible to validate, one or more field is incorrect
Can't write in directory --> /var/log/centreon/
Settings are not saved

Describe the results you expected:

Save configuration

Additional information you think important (e.g. issue happens only occasionally):

![image](https://user-images.githubusercontent.com/9050487/55311371-0beba980-5463-11e9-809a-e5b2e74ecaf0.png)

![image](https://user-images.githubusercontent.com/9050487/55311427-2de52c00-5463-11e9-953f-c6e433990f42.png)

**Comment by lpinsivy** [comment]
apache user is part of centreon groups?

```
# cat /etc/group | grep apache
centreon:x:996:centreon-engine,centreon-broker,apache
nagios:x:995:centreon-engine,centreon-broker,apache
centreon-broker:x:993:centreon,nagios,centreon-engine,apache
apache:x:48:nagios,centreon
centreon-engine:x:991:centreon-broker,apache,nagios,centreon
```
