### ISSUE TITLE
Centreon LDAP sync ISSUE

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#7368]
Centreon 2.8.27
Hello, 

We are using LDAP configuration for authentication on the web portal. The ldap configuration is configured to not store the password on centreon Database. it should only get the information from Ldap Server. 

So we noticed that if the user changes his password on the LDAP server, it seems that Centreon doesn't get the update. So the user can not login using its new password. Communication with the server is OK and nothing specific on the log file. 

Can you please help with this issue? is it a known bug and if so is there any patch ?

Thank you

**Comment by adr-mo** [comment]
Hi @saharawolf,

Thanks for the feedback :100: 

Several patches are coming related to LDAP mechanism.

We'll check for your issue when doing the validation.

Regards,

**Comment by lpinsivy** [comment]
Should be fixed by https://github.com/centreon/centreon/pull/8713
