### ISSUE TITLE
[Widget] when shared as public, the preferences are not saved

### ISSUE THREAD

**Issue by pkriko** [centreon/centreon#7383]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***

centreon-web-18.10.4-9.el7.centos.noarch
centreon-widget-httploader-18.10.0-6.el7.centos.noarch

***Operating System***

CentOS 7

***Additional environment details (AWS, VirtualBox, physical, etc.):***

<h3> Description </h3>

When I share a view using `public`, the preferences of my widget http-loader (the URL) are not saved and restore when an another user load this view

<h3> Steps to Reproduce </h3>

1. create a new view with http-loader wigdet, change the url by http://cric.grenoble.cnrs.fr/Administrateurs/Outils/CalculMasque/ ; and check the box `public`
2. Login on Centreon with another user, add exisiting by `load from exiting view`

![image](https://user-images.githubusercontent.com/32265250/55536099-3a62c200-56b9-11e9-8a24-e65a19f34246.png)

<h3> Describe the received result </h3>
I still have the old url on my view :

![image](https://user-images.githubusercontent.com/32265250/55536202-73029b80-56b9-11e9-9b5d-cb7c3a22d33f.gif)

<h3> Describe the expected result </h3>
I would like the preferences are saved when I share with `public`

<h3> Additional relevant information (e.g. frequency, ...) </h3>

**Workaround**

If I set my user in the locked user or the unlocked user, here the preferences are save (I have a new entry into table `widget_preferences`)
Also work with the group_user.

I can't say for the moment if all the widgets know the same issue.

**Comment by pkriko** [comment]
I tried with another widgets (hostgroup-monitoring, graph-monitoring) the bug is also present.

But, a good new, once the user had load the view, and I modify it on my previous user (the owner), the IHM set this user into the locked_user and everything went well.

**Comment by cgagnaire** [comment]
Should be fixed by https://github.com/centreon/centreon/pull/7408
