### ISSUE TITLE
Home Page --> Widget --> Service-Monitoring --> Unable to filter HostGroup

### ISSUE THREAD

**Issue by Clebam** [centreon/centreon#7394]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***
Centreon 18.10.4

***Operating System***
Centos 7
(from legit 18.10 iso)

<h3> Description </h3>
It happens with the widget Service Monitoring
When I want to filter by hostgroup, no hostgroup is displayed.

If I try to manually type the hostgroup name and save, it won't work too.

If I filter hostgroup with another widget, say, host monitoring, it works. (It should be noted, that the selection is a drop down list there, while it is a different type in service monitoring)

Obviously, the hostgroups exists

<h3> Steps to Reproduce </h3>

1. Log into Centreon
2. (French UI) Go to Accueil > Vue personnalisées
3. Toggle Edit mode with the pen on the upper right corner
4. Click "Ajouter widget" and select "Service Monitoring" (give it some title)
5. Click the wrench icon to edit settings
6. Find Hostgroup and click the select area. 

Nothing happens while it should display the hostgroups.

<h3> Describe the received result </h3>

No hostgroup is displayed

<h3> Describe the expected result </h3>

Hostgroup should be displayed

<h3> Additional relevant information (e.g. frequency, ...) </h3>

I think this issue dates from the very last update. Before that, I could select properly the hostgroups.

(By the way, it should be noted, that the previous Service Monitoring I had set with hostgroup filter keeps running fine. Though, I can't update or change their hostgroup)

**Comment by CPbN** [comment]
#7370 fixes this :+1:

**Comment by Clebam** [comment]
@CPbN Great, will this be delivered with the next coming release 19.04 ?

**Comment by CPbN** [comment]
Sounds like yes, as it has been merged to both 18.10 and 19.04 branches.

**Comment by tanguyvda** [comment]
you'll be able to close #7358 too i've tested on my widget and this value looks much better than the old one :)

**Comment by CPbN** [comment]
I think feel free to close both now, to clean the queue :)

**Comment by sc979** [comment]
Thanks @CPbN and @tanguyvda for your feedbacks. 
@Clebam : Indeed, the z-index of the widget have changed and recovered the dropdown list of hostgroups.
As said, the PR https://github.com/centreon/centreon/pull/7370 correct this issue. You can apply yourself the code modification, or wait for the release of the 18.10.5 / 19.04.0. We'll try the release these ASAP ;)
I'm closing this PR.
Regards,
sc979
