### ISSUE TITLE
Centreon 18.10.04 blank page after login

### ISSUE THREAD

**Issue by Fen0l** [centreon/centreon#7402]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***

For the RPM based systems
```
[root@centreon]# rpm -qa | grep centreon
centreon-license-manager-common-18.10.2-1.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190221-145606.el7.centos.noarch
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-widget-live-top10-memory-usage-18.10.0-6.el7.centos.noarch
centreon-widget-engine-status-18.10.0-9.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-18.10.0-6.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-release-18.10-2.el7.centos.noarch
centreon-web-18.10.4-9.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190221-145606.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190221-145606.el7.centos.noarch
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-broker-core-18.10.1-1.el7.centos.x86_64
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-broker-cbmod-18.10.1-1.el7.centos.x86_64
centreon-license-manager-18.10.2-1.el7.centos.noarch
centreon-widget-grid-map-18.10.0-6.el7.centos.noarch
centreon-widget-servicegroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-widget-graph-monitoring-18.10.0-6.el7.centos.noarch
centreon-common-18.10.4-9.el7.centos.noarch
centreon-perl-libs-18.10.4-9.el7.centos.noarch
centreon-poller-centreon-engine-18.10.4-9.el7.centos.noarch
centreon-base-config-centreon-engine-18.10.4-9.el7.centos.noarch
centreon-widget-host-monitoring-18.10.1-1.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190221-145606.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190221-145606.el7.centos.noarch
centreon-broker-storage-18.10.1-1.el7.centos.x86_64
centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-pp-manager-18.10.4-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-widget-tactical-overview-18.10.0-6.el7.centos.noarch
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-trap-18.10.4-9.el7.centos.noarch
centreon-widget-service-monitoring-18.10.2-1.el7.centos.noarch
centreon-broker-18.10.1-1.el7.centos.x86_64
centreon-plugin-Network-Cisco-Standard-Snmp-20190221-145606.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190221-145606.el7.centos.noarch
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
```
***Operating System***

*CentOS 7 on vCenter 6.5*

<h3> Description </h3>

Since yesterday, after a login we cannot reach the centreon UI. Everyting else is working because we still received alerts on mail and the page who already had the web UI open is still working.

The only error from the centreon central is related to our integration with our LDAP. From `/var/log/centreon/sql-error.log`

```
2019-03-25 10:42|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
2019-03-25 10:42|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
2019-03-25 10:42|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
2019-03-25 10:42|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
2019-03-25 10:42|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
```

<h3> Steps to Reproduce </h3>

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. Blank page

**Comment by sc979** [comment]
Hi @Fen0l,
The blank page isn't linked to the sql errors in the `ldap.log`. These logs were fixed by this PR : https://github.com/centreon/centreon/pull/7278 .
If you had an issue with the ldap connection, a warning about your credentials should appear.
Can you check in the developer mode if you have ".js" broken or missing files with a 404 status ?
Regards,
sc979

**Comment by Fen0l** [comment]
Thank for the hit. Indeed it is not related but it's the only error on our logs.

I have made some investigation this morning and when I reach main.php, we have a blank page and a 40 error while reaching the favicon.

When I reach main.get.php i have my array with the monitoring. So the centreon-web interface is working. 

Very strange, we can still watch the monitoring but cannot reach everything else

**Comment by sc979** [comment]
Pease, can you check your php log and send it : 
`tail -f /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log`
Regards,
sc979

**Comment by Fen0l** [comment]
Sure,

```
[10-Apr-2019 16:47:37 Europe/Paris] PHP Notice:  Undefined offset: 1 in /usr/share/centreon/www/index.php on line 112
[10-Apr-2019 16:47:48 Europe/Paris] PHP Notice:  Undefined offset: 1 in /usr/share/centreon/www/index.php on line 112
```

They appear only when I try to connect myself. When I am already connected, no error logged.

**Comment by sc979** [comment]
Hum,
These log have been corrected from this annoying notice. But it's not linked to your issue neither.

It seems more and more obvious, that it's linked only to the front side.

Since when have you this issue ?
Is it after an upgrade of centreon ?
Of some other packages ?
Can you give us more details on how it happened ?

Regards

**Comment by Fen0l** [comment]
Sure, we dealt with a lot of problem with the upgrade of Centreon from 2.8 to 18.10. But, to be simple,

I have deployed last Friday 2 new servers from the official ISO using the existing database running under Centreon 18.10. We did that because our servers were totally broken, dependencies bugs, plugins corrupted etc...

The week-end went well until Monday morning, we could not reach the web UI, blank page. We did nothing during this time. It is very very strange. We faced some metasploit engine trying to detect vulnerabilities on the system but nothing more.

**Comment by sc979** [comment]
Sorry for the delay,
Right now, we're overwhelmed.
The issue may be linked to the imported databases. But it's odd that it worked fine on friday and no more on monday.
Can you run manually each sql's upgrade scripts from the base version of your database, to the current version of your Centreon.
You'll find them here :
`https://github.com/centreon/centreon/tree/master/www/install/sql`
Regards,
sc979

**Comment by Fen0l** [comment]
Hello,

Thanks. I have ran all the sql migration scripts based on my upgrade path but still the same problem. I have double check the tolopogy and tolopogy_js table but they are the same than the one from the insertTopology.sql script

**Comment by sc979** [comment]
Hi,
Can you execute this :
`$ yum reinstall -y centreon-web-18.10.4-9.el7.centos.noarch`
then go in your centreon folder (/usr/share/centreon) and in delete the `install` sub folder, located under `www` :
`$ rm -rf /usr/share/centreon/www/install`
Then try again in the "private browsing mode" of you browser.
Regards,
sc979

**Comment by Fen0l** [comment]
It works. Great thanks ! Strange problem there.

**Comment by cristianandres9** [comment]
> Hola @ Fen0l ,
> La página en blanco no está vinculada a los errores de SQL en `ldap.log`. Estos registros fueron corregidos por este PR: [# 7278](https://github.com/centreon/centreon/pull/7278) .
> Si tuvo un problema con la conexión ldap, debería aparecer una advertencia sobre sus credenciales.
> ¿Puede verificar en el modo de desarrollador si tiene archivos ".js" rotos o faltantes con un estado 404?
> Saludos,
> sc979

Tengo un problema similar y me da este mensaje en modo desarrollo
![image](https://user-images.githubusercontent.com/63620117/134184597-5a7d3d51-0be6-4564-b66c-3e8b2f7cee83.png)

**Comment by sc979** [comment]
@cristianandres9 ,

I am sorry, to tell you that I do not speak spanish.
Could you speak in English ?

deepl.com translates your sentence as :
"I have a similar problem and I am getting this message in development mode."

This issue is caused by chunk JS files.
Did you try to reinstall your packages ? (cf April, 18 2019 reply)
Which version of Centreon do you use ?

Regards,

sc979

**Comment by cristianandres9** [comment]
> @ cristianandres9 ,
> 
> Lo siento, decirte que no hablo español.
> ¿Podrías hablar en inglés?
> 
> deepl.com traduce tu oración como:
> "Tengo un problema similar y recibo este mensaje en modo de desarrollo".
> 
> Este problema es causado por archivos JS fragmentados.
> ¿Intentó reinstalar sus paquetes? (véase la respuesta del 18 de abril de 2019)
> ¿Qué versión de Centreon utiliza?
> 
> Saludos,
> 
> sc979

Hello, thanks for your help, the information indicated on the 15th, I solved the error as you indicated
