### ISSUE TITLE
Password in service command line are shifted one argument to the right

### ISSUE THREAD

**Issue by germain-denis** [centreon/centreon#7414]
Centreon 18.10

Steps

Create a new Command :
![image](https://user-images.githubusercontent.com/42431424/55965510-b96d7280-5c44-11e9-9bdd-1574c0893d2b.png)

Create a new Service :
![image](https://user-images.githubusercontent.com/42431424/55965704-19641900-5c45-11e9-94dc-0540b3ba7dea.png)

Key are password:
![image](https://user-images.githubusercontent.com/42431424/55965673-0a7d6680-5c45-11e9-8d25-a3993bc6a036.png)

When you check the command line in Monitoring  >  Status Details  >  Services

Resutls : /usr/lib/centreon/plugins//check_sendinblue_credits.sh checktype apikeyaccount *** *** critical

What we should have : /usr/lib/centreon/plugins//check_sendinblue_credits.sh checktype *** *** warning critical

**Comment by CPbN** [comment]
Hi,
In 19.10.0-rc.1, this patch leads to the following :
_'Unable to hide passwords in command'_

The following test fails :
`if (count($aCommandLineWithMacros) == count($aCommandLineExecuted)) {`
In my test command I have `count($aCommandLineWithMacros)` = 15 and `count($aCommandLineExecuted)` = 26...
This is rather expected, as macros can contain spaces...

Could we fix this @lpinsivy please ?

Many thx 👍
