### ISSUE TITLE
Remote database installation

### ISSUE THREAD

**Issue by Singman33** [centreon/centreon#7422]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>
Centreon 18.10 el7 x86_64 ISO

<h3> Description </h3>
When trying to install Centreon with a remote database server, the install process stop with an error message about LimitNOFILE and I'm unable to go further.

<h3> Steps to Reproduce </h3>
Install from the ISO CD, choose either with or without DB, and enter the IP of the remote database server. Message show at stage 7.

<h3> Extra informations </h3>
Database server is Ubuntu 18.04 with MariaDB :

```
# systemctl status mariadb
* mariadb.service - MariaDB 10.1.38 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           `-limits.conf
   Active: active (running) since Sun 2019-04-14 09:14:40 UTC; 5s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 2250 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 2248 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)
  Process: 2149 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _WSREP_STAR
  Process: 2147 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 2146 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 2221 (mysqld)
   Status: "Taking your SQL requests now..."
    Tasks: 27 (limit: 4915)
   CGroup: /system.slice/mariadb.service
           `-2221 /usr/sbin/mysqld
```

I have done the modifications to set LimitNOFILE parameter on systemd :
```
# cat /etc/systemd/system/mariadb.service.d/limits.conf
[Service]
LimitNOFILE=32000
```

**Comment by adr-mo** [comment]
Hi @Singman33 

Thanks for the feedback :100: 

Just to make sure have **perfectly** followed the documentation ?

`https://documentation.centreon.com/docs/centreon/en/latest/installation/from_packages.html#database-management-system`

Regards,

**Comment by Singman33** [comment]
Hi, sorry for the delay, a lots of work here :)
Yes, I followed the docs to create the limits.conf, and systemctl is showing that conf file is read by MariaDB daemon. I will investigate if I could see MariaDB parameters in the running engine instead of conf files.

**Comment by lpinsivy** [comment]
Hi @Singman33 we recently update the documentation, can you check? https://documentation.centreon.com/docs/centreon/en/latest/installation/from_packages.html#installing-mysql-on-the-dedicated-server
