### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by twitram** [centreon/centreon#7425]
Hello,
I have a problem with the French translation. Some parts of the web interface like this one are not translated. How do we make it so?
Best Regards
![image002](https://user-images.githubusercontent.com/14791276/56120530-90afea80-5f6e-11e9-8d5c-96b9216fc9a4.png)

**Comment by sc979** [comment]
Hi twitram,
You can edit yourself the translation files. Just follow the steps described here :
`https://www.centreon.com/blog/tuto-comment-traduire-centreon/`
Indeed, it seems that this part was not translated :'(
We'll do it as soon as possible.
Regards,
sc979

**Comment by sc979** [comment]
Hi twitram,
The referenced PR has been merged on the 2.8.x / 18.10.x and 19.04 branches.
So you can fix your issue right now by following the tutorial, or wait for the next release of these branches.
Regards,
sc979
