### ISSUE TITLE
New update, new plugin issue

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon#7427]
CES: 18.10.4 (updated 2019/04/15)

Hello,
This morning i've updated my CentOS7 and now the Linux "Memory" results are break.

The related plugin is : "centreon_linux_snmp.pl"

You have changed the "warning" and "critical" default values syntaxes into the plugin but not updated the database with something similare to the older !!! :(
or something goes wrong with this plugin update...

So the command is not usable anymore without changes... and this is a grayed commands...
The plugin refer to the command: "OS-Linux-SNMP-Memory"

I don't found any CLAPI command to re-display or alterate the grayed CMD part...
Except editing directly the database and that is clearly not flexible... i don't have any other idea about that.

The older had the "normal" syntax... why would you like to add some oddies and multiple syntax values for that ??? add another parameter if you want but please don't break the usual syntax...

Thanks.

**Comment by Singman33** [comment]
A work around :
. duplicate the offending command (I found 2 of them, os-linux-snmp-memory and app-db-mysql-queries), and add -usage or -total after warning and critical
. create a new service template using that command
. modify your service chech with that template

**Comment by BlackstormFirst** [comment]
Hi, thanks for this work around ^^

**Comment by garnier-quentin** [comment]
The plugin-packs is also updated. If you use rpm, you also need to update centreon-pack package and do the update in centreon-pp manager. After that, it should work as expected.

**Comment by BlackstormFirst** [comment]
Hello and thanks Quentin,
I always check after an update the centreon-pp upgrade status and the plugin pack status (blue for updates, otherwise green or orange), that time, just after the update i didn't see any available upgrades... but this morning after you notice me to check again... i had blue content.

And just after, i check the desired command line... in fact... all are working correctly now.

I can really say thanks ^^ buts thanks again for the time you take to answer to me.

N.B: When you try to update plugins, you always have an error like 'missing autodiscover object' pop-up ^^

Have a nice day.
Best Regards,

**Comment by mauriciodeliz** [comment]
279/5000
Hello.

Set the parameter below.

from:
--warning = '$ _ SERVICEWARNING $' --critical = '$ _ SERVICECRITICAL $'

for:
--warning-usage = '$ _ SERVICEWARNING $' --critical-usage = '$ _ SERVICECRITICAL $'

If adjusting, I was able to follow up normally, leaving the unknown to OK.

Tks!
