### ISSUE TITLE
Upgrading the poller ,display error

### ISSUE THREAD

**Issue by JohnTianGuo** [centreon/centreon#7443]
How strange it is ,according the official document step by step ,when I run the order：

#yum update centreon*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
http://yum.centreon.com/standard/18.10/el7/stable/i386/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: centreon-stable. Please verify its path and try again

Please help and support me if you know how to solve this issue ,thanks in advance .

**Comment by adr-mo** [comment]
Hi @JohnTianGuo,

Thanks for the feedback :100: 

The URL you provided in the issue description does not exist in our repositories.
`http://yum.centreon.com/standard/18.10/el7/stable/` is the one.

Could you check your repository file ?

`cat /etc/yum.repos.d/centreon.repo`

Regards,

**Comment by JohnTianGuo** [comment]
> Hi @JohnTianGuo,
> 
> Thanks for the feedback 
> 
> The URL you provided in the issue description does not exist in our repositories.
> `http://yum.centreon.com/standard/18.10/el7/stable/` is the one.
> 
> Could you check your repository file ?
> 
> `cat /etc/yum.repos.d/centreon.repo`
> 
> Regards,

the  content i checked in the file you mentioned ,as follow:

name=Centreon open source software repository.
baseurl=http://yum.centreon.com/standard/18.10/el7/stable/noarch/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES

[centreon-stable]
name=Centreon open source software repository.
baseurl=http://yum.centreon.com/standard/18.10/el7/stable/$basearch/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES

[centreon-testing-noarch]
name=Centreon open source software repository. (UNSUPPORTED)
baseurl=http://yum.centreon.com/standard/18.10/el7/testing/noarch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES

[centreon-testing]
name=Centreon open source software repository. (UNSUPPORTED)
baseurl=http://yum.centreon.com/standard/18.10/el7/testing/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES

[centreon-unstable-noarch]
name=Centreon open source software repository. (UNSUPPORTED)
baseurl=http://yum.centreon.com/standard/18.10/el7/unstable/noarch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES

[centreon-unstable]
name=Centreon open source software repository. (UNSUPPORTED)
baseurl=http://yum.centreon.com/standard/18.10/el7/unstable/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES

[centreon-canary-noarch]
name=Centreon open source software repository. (UNSUPPORTED)
baseurl=http://yum.centreon.com/standard/18.10/el7/canary/noarch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES

[centreon-canary]
name=Centreon open source software repository. (UNSUPPORTED)
baseurl=http://yum.centreon.com/standard/18.10/el7/canary/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES

if you are pleasure ,please feedback ,thanks in advance

**Comment by adr-mo** [comment]
Hi @JohnTianGuo 

As far as I can see the `$basearch` is resolved as **i386**
I'm making reference to your first message

> #yum update centreon*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
http://yum.centreon.com/standard/18.10/el7/stable/i386/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: centreon-stable. Please verify its path and try again

This means that the poller is currently running on a **32-bits** operating system.

Unfortunately this kind of architecture is **not supported** by Centreon.

Please refer to the following documentation (_note_)

https://documentation.centreon.com/docs/centreon/en/latest/installation/prerequisites.html#operating-systems

Regards,
