### ISSUE TITLE
I want a call from centreon support team or anyone who can talk with me in English

### ISSUE THREAD

**Issue by JohnTianGuo** [centreon/centreon#7456]
I will go crazy now .
need to talk with centreon support team or anyone who can help me

**Comment by s-duret** [comment]
Hi @JohnTianGuo 
Did you try to contact the Centreon Support today ?
Can you send an e-mail to support@centreon.com and specify your phone number and the subject of your call ? we will call you back.
Thanks

**Comment by JohnTianGuo** [comment]
> Hi @JohnTianGuo
> Did you try to contact the Centreon Support today ?
> Can you send an e-mail to [support@centreon.com](mailto:support@centreon.com) and specify your phone number and the subject of your call ? we will call you back.
> Thanks

the mail i just send ,tks  in advance .

**Comment by s-duret** [comment]
I just answered to you by e-mail.
I close this issue.
