### ISSUE TITLE
[ API Rest ] - How can I export the times when the hosts were down?

### ISSUE THREAD

**Issue by TimuranB** [centreon/centreon#7457]
Hello all,
I'm working with Rest API and I would like to export the metrics with the different status of the host.
How can I export them?
Thank you in advance.

**Comment by lpinsivy** [comment]
Hi,

The real time API allows only to get list of resources in actual status.
There is no API for reporting and we don't plan to develop them.

**Comment by TimuranB** [comment]
Hey @lpinsivy ,
thank you for your reply. 
I will try to use a Centreon Stream connector.
Best regards.
