### ISSUE TITLE
plugin=os::linux::snmp::plugin cpu-detailed csv export mismatch 

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon#7477]
Hello, 

We  noticed that when we export in CSV format a graphic data for CPU-Detailed mode of the plugin, idle and steal data are reversed. 
For example on the graphic below, the idle % is the one having 99 % of usage and steal is 0%
![image](https://user-images.githubusercontent.com/28105870/56582939-4fec4d00-65d0-11e9-9fe7-ac51d1104a72.png)

But if we look at CSV export for the same graph, we see that it is steal column that is receiving the data: 
![image](https://user-images.githubusercontent.com/28105870/56583046-92158e80-65d0-11e9-96c1-ce85d5f694c1.png)

So the CSV is showing wrong column names, we have verified and it is the graphic that has the correct output. 

Can you please review the plugin to correct this issue ? 

plugin Linux SNMP version 3.2.0

Thank you

**Comment by lpinsivy** [comment]
Related to #6285 and #5959

we will work soon on it.
