### ISSUE TITLE
why the menu "Monitoring-Performaces " lost ?

### ISSUE THREAD

**Issue by JohnTianGuo** [centreon/centreon#7479]
the first pictures is the demo from official web site:
![web-s1](https://user-images.githubusercontent.com/48991627/56650479-b4cfa200-66b9-11e9-97b8-2b57cb31536c.png)
the second pictures is my new install web pages from github code 18.10.5:
![migration-s1](https://user-images.githubusercontent.com/48991627/56650542-d597f780-66b9-11e9-8580-4d5beb8429d6.png)

please help me for this .
thanks in advance ,best regards

**Comment by adr-mo** [comment]
Hi @JohnTianGuo 

> the second pictures is my new install web pages from github code 18.10.5

This code is currently in a **unstable** mode. Not validated yet by the QA team.
We do not support issues opened on **UNSUPPORTED** versions of the software
