### ISSUE TITLE
Graphique de performances des méta-services

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#748]
---

Author Name: **Loic FONTAINE** (Loic FONTAINE)
Original Redmine Issue: 5987, https://forge.centreon.com/issues/5987
Original Date: 2014-11-26

---

Lorsqu'on est dans "Configuration" ==> "Services" ==> Méta-services et qu'on clique sur l'icône "graphique de performance" d'un méta-service alors la page Vues ==> Graphs se charge mais sans afficher le graphique de performances

**Comment by julienmathis** [comment]
Cela ne le fait plus en 2.6.1
