### ISSUE TITLE
Could not load the Perl module 'Config::IniFiles'....

### ISSUE THREAD

**Issue by JohnTianGuo** [centreon/centreon#7480]
some services give these hints ,as follow:

Could not load the Perl module 'Config::IniFiles' Can't locate Config/IniFiles.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 13) line 1.

or 

Could not load the Perl module 'Config::IniFiles' Can't locate Config/IniFiles.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 14) line 1.

**Comment by adr-mo** [comment]
Hi @JohnTianGuo,

Please make sure to install the perl dependencies needed.

Otherwise this will not work

Regards,

**Comment by JohnTianGuo** [comment]
> Hi @JohnTianGuo,
> 
> Please make sure to install the perl dependencies needed.
> 
> Otherwise this will not work
> 
> Regards,

thanks for your supporting and i will try to install the necessary dependencies .
best wish

**Comment by adr-mo** [comment]
Okay, I'll close the issue now
