### ISSUE TITLE
 No output returned from plugin

### ISSUE THREAD

**Issue by JohnTianGuo** [centreon/centreon#7481]
some services give these hints as follow :

No output returned from plugin
as the pictures below：
![output-1](https://user-images.githubusercontent.com/48991627/56650818-67076980-66ba-11e9-9a73-14af94bff5b7.png)

**Comment by adr-mo** [comment]
Hi @JohnTianGuo,

Thanks for the feedback :100: 

Have you made sure that plugin is actually here and executable ?

Could you please check in this detailed service page the `Executed Check Command Line`

You can copy the command line by clicking the dedicated button and execute it on your server (_SSH_).

Thanks

Regards,

**Comment by JohnTianGuo** [comment]
> Hi @JohnTianGuo,
> 
> Thanks for the feedback 
> 
> Have you made sure that plugin is actually here and executable ?
> 
> Could you please check in this detailed service page the `Executed Check Command Line`
> 
> You can copy the command line by clicking the dedicated button and execute it on your server (_SSH_).
> 
> Thanks
> 
> Regards,

can you apply the command line i will execute them ?
thanks in advance .

**Comment by adr-mo** [comment]
Hi,

I can't that is something that **YOU** need to do.

On the `Monitoring -> Status Details -> Services`  click on the service that has the issue.

At the bottom of the detail page you'll find a section like the one on the picture.

![image](https://user-images.githubusercontent.com/31647811/56685417-37645b80-66d2-11e9-9b70-e49b58c534a8.png)

You have a little button that allows to copy the command line.
Execute this command on your server that you need to access through **SSH**

Regards,
