### ISSUE TITLE
click these menus ,display blank 

### ISSUE THREAD

**Issue by JohnTianGuo** [centreon/centreon#7482]
when i click these menus as the below picture shown：
![Snipaste_2019-04-25_01-26-28](https://user-images.githubusercontent.com/48991627/56680186-5cb89000-66f9-11e9-9f5f-87d9ead3e909.png)
why display blank ?

**Comment by quanghungb** [comment]
Hi, 

Please could you provide more details about your Centreon version ?

Regards.

**Comment by adr-mo** [comment]
Hi @JohnTianGuo 

Thanks for the feedback 💯 

Please use the **ISSUE_TEMPLATE** for bug report.

Without those information we will not able to diagnostic your issue.

Regards,

**Comment by JohnTianGuo** [comment]
> Hi,
> 
> Please could you provide more details about your Centreon version ?
> 
> Regards.

first i upgrade from unstable version 18.10.5 to 19.04.0  the version information as follow 

![Snipaste_2019-04-25_05-52-27](https://user-images.githubusercontent.com/48991627/56696480-8801a600-671e-11e9-8929-ec487d923db8.png)

Best Regards

**Comment by adr-mo** [comment]
Hi @JohnTianGuo,

As **discussed** on Slack I'll now close this issue because CENTREON does not support migrations from **unstable versions**

You are trying to migrate your plateform from 18.10.5 that has not been **tested & released** yet.

Regards,
