### ISSUE TITLE
[19.04] Administration > Logs 

### ISSUE THREAD

**Issue by germain-denis** [centreon/centreon#7487]
Version : centreon-web-19.04.0-3.el7.centos.noarch

Go in Administration > Logs

Change the page (for example 4) : 
![image](https://user-images.githubusercontent.com/42431424/56747865-bdbd8380-674c-11e9-98af-6a2c1cc552f9.png)

You will indeed be on page 4, but the 1 will still be bold and you cannot come back to page 1. Same for every page. 
![image](https://user-images.githubusercontent.com/42431424/56747966-ee9db880-674c-11e9-831e-9f0a597f65cd.png)

**Comment by adr-mo** [comment]
Hi @germain-denis 

Thanks for the feedback :100: 

We are aware of this issue, and it is currently being fixed.

It will be available in the **19.04.1** release

Regards,

**Comment by sc979** [comment]
Hi @germain-denis ,
I tested the modifications of the related PR. If urgently needed, you can already make a backup of the modified files and apply the PR.
I'm waiting for the CI's results and QA validation, before merging.
Regards,
sc979

**Comment by germain-denis** [comment]
Thank you.

Excellent work as always !
