### ISSUE TITLE
Centreon 19.04 Fresh Install - Split database

### ISSUE THREAD

**Issue by oragain** [centreon/centreon#7491]
<h1> BUG INFORMATION </h1>
Centreon 19.04 Fresh Install - Split database - Install stuck at step 7; Setting up basic configuration.

<h3> Prerequisites </h3>
Central:
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

Database Server:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Databse Engine:
mysql  Ver 15.1 Distrib 10.3.14-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

***versions***
19.04

For the RPM based systems

-- Copy/Paste the result of the following command --
```
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-common-19.04.0-3.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190412-141630.el7.centos.noarch
centreon-engine-19.04.0-2.el7.centos.x86_64
centreon-license-manager-19.04.0-1.el7.centos.noarch
centreon-base-config-centreon-engine-19.04.0-3.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190412-141630.el7.centos.noarch
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Database-20190412-141630.el7.centos.noarch
centreon-release-19.04-1.el7.centos.noarch
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190412-141630.el7.centos.noarch
centreon-engine-extcommands-19.04.0-2.el7.centos.x86_64
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-web-19.04.0-3.el7.centos.noarch
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Dns-20190412-141630.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190412-141630.el7.centos.noarch
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ftp-20190412-141630.el7.centos.noarch
centreon-trap-19.04.0-3.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190412-141630.el7.centos.noarch
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-plugin-Operatingsystems-Linux-Snmp-20190412-141630.el7.centos.noarch
centreon-engine-daemon-19.04.0-2.el7.centos.x86_64
centreon-poller-centreon-engine-19.04.0-3.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190412-141630.el7.centos.noarch
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-perl-libs-19.04.0-3.el7.centos.noarch

```
***Operating System***

see above in prerequisite

***Additional environment details (AWS, VirtualBox, physical, etc.):***
Virtualization stack: proxmox

<h3> Description </h3>

Centreon 19.04 Fresh Install - Split database - Install stuck at step 7; Setting up basic configuration.

<h3> Steps to Reproduce </h3>

Please describe precisely the steps to reproduce the encountered issue.

Do a fresh install of Centreon 19.04 with split server database. Do not configure the centreon user or databases only the root user on the DB server.

<h3> Describe the received result </h3>
Install stays stuck at basic configuration
Databases are created on the RDBMS.
User does not get created on the RDBMS

<h3> Describe the expected result </h3>
Installation should finish

<h3> Additional relevant information (e.g. frequency, ...) </h3>
Worked around the issue by manually creating the databases, the user and granting permissions to the new user on centreon and centreon_storage db.

**Comment by oragain** [comment]
[centreon.sql.txt](https://github.com/centreon/centreon/files/3122473/centreon.sql.txt)

**Comment by oragain** [comment]
[centreon.sql.txt](https://github.com/centreon/centreon/files/3122497/centreon.sql.txt)

**Comment by adr-mo** [comment]
Hi @oragain 

As discussed on **Slack** we'll be updating the documentation soon in order to add those instructions.

@lpinsivy Could you please take care of this issue ?

Regards,
