### ISSUE TITLE
[ API Rest ] - Export a list of users attached to a host?

### ISSUE THREAD

**Issue by TimuranB** [centreon/centreon#7492]
Hello all,
I would like to know if it's possible to have a list of users attached to a host with Rest API?
Best regards.

**Comment by lpinsivy** [comment]
From API documentation you can use [getcontactgroup](https://documentation.centreon.com/docs/centreon/en/latest/api/clapi/objects/hosts.html#getcontactgroup) or [getcontact](https://documentation.centreon.com/docs/centreon/en/latest/api/clapi/objects/hosts.html#getcontact)

To use this from Rest API see the [documentation](https://documentation.centreon.com/docs/centreon/en/latest/api/api_rest/index.html#configuration)
Regards,
