### ISSUE TITLE
[packages] Generic link to last version repository

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#7497]
Hi,

Every time Centreon updates to a new "major" version, we need to install a new specific repo, for example :
`yum install -y http://yum.centreon.com/standard/19.04/el7/stable/noarch/RPMS/centreon-release-19.04-1.el7.centos.noarch.rpm`

Could it be possible to have a "generic" repo which would point to the last available version ?
So that we are sure all updates will show-up with a simple `yum check-update`, even in case of a "major" version.
That would really be convenient.
Think for example about automation tools (Centreon ? :) checking / alerting when (yum) systems are not uptodate, today no alert is triggered when a new "major" Centreon version is available...

Thank you very much 👍

Edit : not present at time of 19.10.10.

**Comment by lpinsivy** [comment]
You rights @CPbN we need to work on it

**Comment by UrBnW** [comment]
Closing as not important, feel free to re-open if needed...
