### ISSUE TITLE
Exclusion in search fields

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#75]
---

Author Name: **sebastien maury** (sebastien maury)
Original Redmine Issue: 4970, https://forge.centreon.com/issues/4970
Original Date: 2013-11-06

---

Hi,

In all the different search fields of Centreon (monitoring, configuration, services ...), it would be great if we could include and/or exclude terms from the search.

It would really be helpful for maintaining and using Centreon.

In my case, i've 643 hosts and 12342 services, so being able to be more accurate in my searchs would really be of help (as well as for the different users).

Regards,
Sébastien

**Comment by Gwennhael** [comment]
could use '_' as a char wildcard and '%' as a multi-chars wildcard
