### ISSUE TITLE
index.html file is overwritten

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#7505]
<h1>BUG REPORT INFORMATION </h1>
<h3> Prerequisites </h3>

***Versions***
Centreon 18.10.x
CentOS 7

<h3> Description </h3>
When we do a vulnerability scan with the Nessus tool, it happens that the file /usr/share/centreon/www/index.html is overwritten and set to zero, so the application is no longer functional and displays a blank page.

<h3> Steps to Reproduce </h3>

Server : Master
Port : 443
SCANNER used : Nessus 8.3.X
SCAN TEMPLATE : Web Application Tests

PLUGINS used:
CGI Generic SQL Injection (blind, time based)
CGI Generic SQL Injection (HTTP Cookies)
CGI Generic SQL Injection (HTTP Headers)
 
<h3> Describe the received result </h3>
The index.html page changes to 0 bytes.
Centreon displays a blank page.

<h3> Describe the expected result </h3>
The tool should not be able to modify / delete file, this is quite critical.
This is a security breach.

Regards

**Comment by adr-mo** [comment]
@kduret Any solution for this N

**Comment by adr-mo** [comment]
Hi @bmareau,

Could you please provide more information how to reproduce the issue you described in the ticket ?

@lpinsivy What should we do with that ?

Regards,

**Comment by kozfelipe** [comment]
hi mates
once in a while my index.html becomes empty too, but no nessus involved.

I think this line is responsible for this (index.php):
`$indexFile = glob('index.html');`

**Comment by kozfelipe** [comment]
correction: index.html still becomes empty in 19.04.0
it just happened today

**Comment by adr-mo** [comment]
Hi @kozfelipe 

This issue occurs when doing any particular actions ?

The issue here is that we could not reproduce.
Without a procedure to reproduce it is **hard** to find a solution for this.

**The issue will remain opened though**, until a solution is found.

Regards,

**Comment by kozfelipe** [comment]
@adr-mo is it possible to merge a patch to avoid that like only `file_put_contents` if file is greater than zero or something similar. May I open a PR for that?

**Comment by adr-mo** [comment]
@kozfelipe That is the beauty of open sources project of course you can open a PR.
Just **FYI**, once the PR opened:

- It will be reviewed by the Centreon developers
- It will then be added to our backlog & sprint
- It will be then tested by the QA and then finally **released**

Just saying this to avoid any kind of frustration relating the gap between the PR made and the release :)

Anyway thanks again for the contribution ! :100: 

Regards

**Comment by cgagnaire** [comment]
Fixed by https://github.com/centreon/centreon/pull/7550
