### ISSUE TITLE
Monitoring Hosts - Severity filter

### ISSUE THREAD

**Issue by Benoit-Forveille** [centreon/centreon#7513]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ldap-20190412-141630.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190412-141630.el7.centos.noarch
centreon-web-19.04.0-3.el7.centos.noarch
centreon-common-19.04.0-3.el7.centos.noarch
centreon-engine-extcommands-19.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190412-141630.el7.centos.noarch
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-engine-19.04.0-2.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190412-141630.el7.centos.noarch
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-perl-libs-19.04.0-3.el7.centos.noarch
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Dns-20190412-141630.el7.centos.noarch
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190412-141630.el7.centos.noarch
centreon-license-manager-19.04.0-1.el7.centos.noarch
centreon-trap-19.04.0-3.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190412-141630.el7.centos.noarch
centreon-poller-centreon-engine-19.04.0-3.el7.centos.noarch
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-plugin-Hardware-Printers-Generic-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190412-141630.el7.centos.noarch
centreon-base-config-centreon-engine-19.04.0-3.el7.centos.noarch
centreon-engine-daemon-19.04.0-2.el7.centos.x86_64
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-plugin-Operatingsystems-Linux-Snmp-20190412-141630.el7.centos.noarch
centreon-database-19.04.0-3.el7.centos.noarch
centreon-19.04.0-3.el7.centos.noarch

***19.04***

***RHEL 7.6***

***KVM VirtualHost***

<h3> Description </h3>

In version 19.04, on the hosts monitoring, the filtering by severity does not work. No problem with version 18.10.

Creating a host does not register an entry in the centreon_storage.customvariables table.

MariaDB [centreon_storage]> SELECT * FROM customvariables;
+-------------------+---------+-------------------+------------+---------------+----------+------+-------------+---------+
| customvariable_id | host_id | name              | service_id | default_value | modified | type | update_time | value   |
+-------------------+---------+-------------------+------------+---------------+----------+------+-------------+---------+
|               186 |       1 | WARNING           |          7 | 200,20%       |        0 |    1 |  1556873932 | 200,20% |
|               187 |       1 | PACKETNUMBER      |          7 | 5             |        0 |    1 |  1556873932 | 5       |
|               188 |       1 | CRITICALITY_LEVEL |          7 | 20            |        0 |    1 |  1556873932 | 20      |
|               189 |       1 | CRITICALITY_ID    |          7 | 1             |        0 |    1 |  1556873932 | 1       |
|               190 |       1 | CRITICAL          |          7 | 400,50%       |        0 |    1 |  1556873932 | 400,50% |
|               191 |      10 | WARNING           |          9 | 200,20%       |        0 |    1 |  1556873932 | 200,20% |
|               192 |      10 | PACKETNUMBER      |          9 | 5             |        0 |    1 |  1556873932 | 5       |
|               193 |      10 | CRITICAL          |          9 | 400,50%       |        0 |    1 |  1556873932 | 400,50% |
|               194 |       9 | WARNING           |          8 | 200,20%       |        0 |    1 |  1556873932 | 200,20% |
|               195 |       9 | PACKETNUMBER      |          8 | 5             |        0 |    1 |  1556873932 | 5       |
|               196 |       9 | CRITICAL          |          8 | 400,50%       |        0 |    1 |  1556873932 | 400,50% |
+-------------------+---------+-------------------+------------+---------------+----------+------+-------------+---------+
11 rows in set (0.00 sec)

MariaDB [centreon_storage]> SELECT * FROM customvariables WHERE name="CRITICALITY_ID" AND service_id IS NULL;
Empty set (0.00 sec)

<h3> Steps to Reproduce </h3>

Create a host
Create a category of host
Assign the host to the category
Reload poller
The severity filter is not working

**Comment by sc979** [comment]
Hi @Benoit-Forveille ,
Thanks for your feedback. The issue is known and we're currently working on it.
Regards,
sc979

**Comment by lpinsivy** [comment]
Hi, You need to update to Centreon Engine 19.04.1 released last week.

Regards
