### ISSUE TITLE
CLAPI issue

### ISSUE THREAD

**Issue by JohnTianGuo** [centreon/centreon#7514]
when I run the command  as follow, the result gives me hint :

[root@server ~]# /usr/share/centreon/bin/centreon -u admin -p XXXXX -i /tmp/centreon_clapi_import_commands.txt
PHP Fatal error:  Uncaught Error: Class '\CentreonClapi\centreon' not found in /usr/share/centreon/www/class/centrlass.php:934
Stack trace:
#0 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(799): CentreonClapi\CentreonAPI->iniObject('
#1 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(769): CentreonClapi\CentreonAPI->launchActio
#2 /usr/share/centreon/bin/centreon(200): CentreonClapi\CentreonAPI->import('/tmp/centreon_c...')
#3 {main}
  thrown in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php on line 934

but i  check the php file  the class exists ?
why ?
please give me the answer if you know 

please forgive me what i  said about some days  ago

**Comment by v0strik0v** [comment]
Hello,
I've the same issue. Any update ?
Thanks in advance
Br

**Comment by lpinsivy** [comment]
Should be fix, no error on latest versions

**Comment by luiscontrerasdo** [comment]
On Centreon 21.04 I have the problem with it when importing from the command line:

centreon -u any -p any -i /tmp/file.txt

PHP Fatal error:  Uncaught Error: Class '\CentreonClapi\centreon' not found in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php:943
Stack trace:
#0 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(807): CentreonClapi\CentreonAPI->iniObject('--mode=list-bro...')
#1 /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php(777): CentreonClapi\CentreonAPI->launchActionForImport()
#2 /usr/share/centreon/bin/centreon(196): CentreonClapi\CentreonAPI->import('/tmp/file.txt')
#3 {main}
  thrown in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php on line 943

Any workaround ?
