### ISSUE TITLE
OpenID connect issue after upgrade to 22.10.4

### ISSUE THREAD

**Issue by Bochi75** [centreon/centreon#752]
Hello Team,

I’m faing an issue with OpenID connect after upgrade to version:  22.10.4.

I’m not able to connect, here is error that I encountered:

(Cannot assign null to property Core\Security\Authentication\Infrastructure\Provider\OpenId::$username of type string)

Someone can help ?

Many thanks !!!

**Comment by Bochi75** [comment]
Open new one.

**Comment by matoy** [comment]
Commenting line 72:
$this->username = $this->provider->getUserInformation()['email'];
in /usr/share/centreon/src/Core/Security/Authentication/Infrastructure/Provider/OpenId.php solves the issue on our platform (but i don’t know if there are side effects)

**Comment by Bochi75** [comment]
Hello Matoy
It's working on my pre-prodn I will check on production.
Many thanks !!!
