### ISSUE TITLE
Centreon Alert advanced possibilities

### ISSUE THREAD

**Issue by Elikha** [centreon/centreon#7520]
Hello Everyone,

I have a centreon plateform working basically, just reporting if host are up or down by using ping.

So I would like to know if there are some advanced properties that i can apply to know for example if an equipment is down and up successively X times at a certain period, we can attribute automatically some specific treatement in centreon etc...or some treatement that we can automate about a behaviour of equipement (if it's down X hours we classify, etc...)

Thanks in advance.
--------------french version
Bonjour à tous,

J'ai déployé une architecture centreon depuis un année et ça marche mais on ne fait que du ping pour l'instant, on aimerait aller plus loin dans la partie traitement par exemple.

Comme automatiser certains comportements avec un traitement spécifique par exemple une succession de Down par rapport à un temps donné on puisse être notifié ou l'associer à qlq chose....ou si un équipement est down directement depuis X heure on le classifie comme quoi y a un problème ....c'est ça l'idée en fait de trouver des possibilités ou des configurations avancées (est ce que des traps dédiés peuvent le faire) par rapport à ce qu'on peut faire aujourd'hui (récupérer un fichier de journaux d’événements) pour le ping des équipements.

Merci par avance.

**Comment by adr-mo** [comment]
Hi @Elikha 

Please feel free to join our official [Slack](https://centreon.github.io/register-slack).

I'm quite sure that our **community** will give you a great answer :)

Regards,
