### ISSUE TITLE
[ API Rest ] - Export host status

### ISSUE THREAD

**Issue by TimuranB** [centreon/centreon#7521]
I may have expressed myself poorly at the last issue (#7457), I would like to export the status of a host as what we found in the table "logs" but without going directly through the database. If you any idea of how i can do to export them.

**Comment by lpinsivy** [comment]
You can use real time API:

$ curl -s -k 'http://<IP_CENTREON>/centreon/api/index.php?action=authenticate' -d 'username=<login>&password=<password>'
{"authToken":"+vwZWXaPaiUmv7LYQEQ4rUP7ScmYQSDABfXrFLwhxCg="}

$ curl -s -k 'http://<IP_CENTREON>/centreon/api/index.php?object=centreon_realtime_hosts&action=list&search=<HOST_NAME>' -H 'Content-Type: application/json' -H 'centreon-auth-token: <TOKEN>'
[{"id":"51","name":"vCenter","alias":"vCenter","address":"10.1.1.0","state":"0","state_type":"1","output":"OK: vcenter rta 10,867ms lost 0%\n","max_check_attempts":"3","check_attempt":"1","last_check":"1560174000","last_state_change":"1555678332","last_hard_state_change":"1555599808","acknowledged":"0","instance_name":"Central","criticality":null}]

For the first call replace <IP_CENTREON>, <login> & <password>
For the second one, replace <IP_CENTREON>,  <HOST_NAME> and <TOKEN>

Regards,
