### ISSUE TITLE
Poller RED but okay

### ISSUE THREAD

**Issue by jakefoster2018** [centreon/centreon#7534]
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon
```

centreon-plugin-Operatingsystems-Linux-Snmp-20190412-141630.el7.centos.noarch
centreon-release-18.10-2.el7.centos.noarch
centreon-license-manager-18.10.2-1.el7.centos.noarch
centreon-widget-httploader-18.10.0-6.el7.centos.noarch
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-broker-18.10.1-1.el7.centos.x86_64
centreon-broker-core-18.10.1-1.el7.centos.x86_64
centreon-common-18.10.4-9.el7.centos.noarch
centreon-broker-cbmod-18.10.1-1.el7.centos.x86_64
centreon-widget-global-health-18.10.0-8.el7.centos.noarch
centreon-widget-servicegroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190412-141630.el7.centos.noarch
centreon-broker-storage-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190412-141630.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190412-141630.el7.centos.noarch
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-license-manager-common-18.10.2-1.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190412-141630.el7.centos.noarch
centreon-database-18.10.4-9.el7.centos.noarch
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-poller-centreon-engine-18.10.4-9.el7.centos.noarch
centreon-base-config-centreon-engine-18.10.4-9.el7.centos.noarch
centreon-widget-service-monitoring-18.10.2-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-widget-engine-status-18.10.0-9.el7.centos.noarch
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ldap-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190412-141630.el7.centos.noarch
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-pp-manager-18.10.4-1.el7.centos.noarch
centreon-18.10.4-9.el7.centos.noarch
centreon-widget-live-top10-memory-usage-18.10.0-6.el7.centos.noarch
centreon-widget-host-monitoring-18.10.1-1.el7.centos.noarch
centreon-widget-tactical-overview-18.10.0-6.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190412-141630.el7.centos.noarch
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
centreon-trap-18.10.4-9.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-widget-grid-map-18.10.0-6.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-18.10.0-6.el7.centos.noarch
centreon-perl-libs-18.10.4-9.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190412-141630.el7.centos.noarch
centreon-web-18.10.4-9.el7.centos.noarch
centreon-widget-graph-monitoring-18.10.0-6.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190412-141630.el7.centos.noarch

<h3> Description </h3>

Central reporting poller down & Poller has yellow issues based on Last Update time after central server rebooted
Are there any cache files that may have been corrupted during reboot etc?

<h3> Steps to Reproduce </h3>

1: Logged into centreon
2: Centreon reporting RED as Pollers not running
3: Under Configuration -> Pollers -> the poller has a yellow alert on Last Update Time

However, poller is responding, i can export configuration to it, and all hosts and services it is monitoring are in date and working.

<h3> Describe the received result </h3>

Poller last update is yellow warning and has incorrect date

<h3> Describe the expected result </h3>
Poller last update should have current date stamp

**Comment by adr-mo** [comment]
Hi @jakefoster2018 

Thanks for the feedback :100: 

Could you please check a few things

- Check that there is no retention on the poller
```
# ls -lah /var/lib/centreon-broker (should not display any *queue* files)
```
- Check that centcore service is correctly started and that there is no errors
```
# systemctl status centcore
# tail -f /var/log/centreon/centcore.log
```

Regards,

**Comment by jakefoster2018** [comment]
Hi there, - 

no *queue* files in /var/lib/centreon-broker

systemctl status centcore output:

● centcore.service - Centreon Core
   Loaded: loaded (/usr/lib/systemd/system/centcore.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-05-13 16:57:51 BST; 17h ago
 Main PID: 5322 (centcore)
   CGroup: /system.slice/centcore.service
           └─5322 /usr/bin/perl /usr/share/centreon/bin/centcore

May 13 16:58:21 <CENTRAL> centcore[5322]: 2019-05-13 16:58:21 - Send Centreon Engine config files on poller "<POLLER>" (2)
May 13 16:58:21 <CENTRAL> centcore[5322]: 2019-05-13 16:58:21 - Send Centreon Broker config files on poller "<POLLER>" (2)
May 13 16:58:22 <CENTRAL> centcore[5322]: 2019-05-13 16:58:22 - Init Script : "sudo service centengine restart" on poller "<POLLER>" (2)
May 13 16:58:22 <CENTRAL> centcore[5322]: Redirecting to /bin/systemctl restart centengine.service
May 14 08:33:20 <CENTRAL> centcore[5322]: We trust you have received the usual lecture from the local System
May 14 08:33:20 <CENTRAL> centcore[5322]: Administrator. It usually boils down to these three things:
May 14 08:33:20 <CENTRAL> centcore[5322]: #1) Respect the privacy of others.
May 14 08:33:20 <CENTRAL> centcore[5322]: #2) Think before you type.
May 14 08:33:20 <CENTRAL> centcore[5322]: #3) With great power comes great responsibility.
May 14 08:33:20 <CENTRAL> centcore[5322]: sudo: no tty present and no askpass program specified

I dont seem to have a centcore.log file on my system?

**Comment by jakefoster2018** [comment]
Not an issue with centreon - public IP address of poller had changed and firewall rules needed to be adjusted (outbound to the poller was working, but inbound wasn't)

**Comment by adr-mo** [comment]
Ok great thanks :)
