### ISSUE TITLE
Rights on files *.services

### ISSUE THREAD

**Issue by kabreu** [centreon/centreon#7543]
***Versions***

18.10.X & 19.10.X

(Tested on centreon-web-19.04.0-3.el7.centos.noarch & centreon-web-18.10.4-9.el7.centos.noarch )

***-- Describe the encountered issue --***

Fresh Install of Centreon

Messages in /var/log/messages :
systemd: Configuration file /usr/lib/systemd/system/centreon.service is marked executable. Please remove executable permission bits. Proceeding anyway.
for each centreon service (centengine, cbd, centcore, centreontrapd)

Checking the rights on the configuration files : 
-rwxr-xr-x.  1 root root  958 19 avril 11:28 cbd.service
-rwxr-xr-x.  1 root root  966 24 avril 10:33 centcore.service
-rwxr-xr-x.  1 root root  946 19 avril 11:41 centengine.service
-rwxr-xr-x.  1 root root  814 24 avril 10:33 centreon.service
-rwxr-xr-x.  1 root root 1,0K 24 avril 10:33 centreontrapd.service

Modifying the rights to be 644 remove the messages in /var/log/messages

No executable permission should be by default when installing ?

Best regards

**Comment by ganoze** [comment]
This was fixed in packaging files and will hopefully make it to the next bugfix release.

**Comment by adr-mo** [comment]
Fixed with the new releases **18.10.5 and 19.04.1**
