### ISSUE TITLE
[BUG] Monitoring - Encoding # in "monitoring page"

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#7549]
<h1>BUG REPORT INFORMATION </h1>

***Versions***
CentOS6 / CentOS7
Centreon 2.8.x
Centreon 18.10
Centreon 19.04

<h3> Description </h3>

If names of services start with a #.
In page _"Monitoring > Status Details > Services > click on the service"_ view, the url loaded is of type _"........service_description=**%23service_name**"_.
In page "_Monitoring > Status Details > Services > click on the host > click on the service_" view, the url loaded is of type "_......... service_description=**#service_name**_".

In the first case, the # is converted to %23 and the page is displayed
In the second case, the # is not converted and the page displays an error

Example : 
**Service name:** #Cpu 
**Click on the service directly:** 
`http://@IP/centreon/main.php?p=20201&o=svcd&host_name=host-test&service_description=%23Cpu`
**Click on the host, then on the service:** 
`http://@IP/centreon/main.php?p=20201&o=svcd&host_name=host-test&service_description=#Cpu`

<h3> Steps to Reproduce </h3>

1. Create a service with name #Cpu 
2. Export / Restart configuration
3. Go on "Monitoring > Status Details > Services > click on the service"
4. Go on "Monitoring > Status Details > Services > click on the host > click on the service"

<h3> Describe the received result </h3>

In page _"Monitoring > Status Details > Services > click on the service"_ view, the url loaded is of type _"........service_description=**%23Cpu**"_.
In page "_Monitoring > Status Details > Services > click on the host > click on the service_" view, the url loaded is of type "_......... service_description=**#Cpu**_".

In the first case, the # is converted to %23 and the page is displayed
In the second case, the # is not converted and the page displays an error

**Comment by garnier-quentin** [comment]
Maybe we could add the capability to use host_id and service_id also. It will avoid that kind of issues.
