### ISSUE TITLE
Api returning "Unauthorized"

### ISSUE THREAD

**Issue by cam-bdt** [centreon/centreon#7551]
Hi !

I am developing an interface that allows users to access the IS status. To do this, I have to retrieve the data collected by Centreon.

So I use (or rather, I try to use) the Rest of Centreon API (https://documentation.centreon.com/d...est/index.html).

However, as soon as I receive the first request via my browser (api.domain.tld/centreon/api/index.php?action=authenticate), I am returned "Unauthorized", even though I have the necessary authorizations to make the request.

Does anyone know what the problem is?

Thank you in advance

ps: I don't have console access to the server, that's why I use my browser

**Comment by adr-mo** [comment]
Hi @cam-bdt 

Thanks for the feedback 💯 

Could you please make sure that the user used for the authentication has the rights to access the API ?

In `Configuration -> Users -> Contact / Users`

![image](https://user-images.githubusercontent.com/31647811/58048484-21b84980-7b4b-11e9-8acd-09c819c04826.png)

Regards,

**Comment by cam-bdt** [comment]
Thank you for your answer. 

They are checked... I have the rights to access the api

**Comment by adr-mo** [comment]
Ok,

Could provide the exact command you are using for the authentication ?

Regards

**Comment by cam-bdt** [comment]
I have tried pretty much everything :') Here's some of my tests

 ```
curl -d "username='username'&password='pass" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://centreon.cst.cnes.fr/centreon/api/index.php?action=authenticate

 curl --data "username='username'&password='pass'" 'http://centreon.cst.cnes.fr/centreon/api/index.php?action=authenticate'


 curl 'http://centreon.cst.cnes.fr/centreon/api/index.php?action=authenticate' -H 'Content-Type: application/json' -H 'centreon_auth_token: tDJ5R0kOCN=' --data '{"action":"show", "object":"HOST"}'

```

**Comment by adr-mo** [comment]
Okay so the authentication works but not the action of **listing the hosts** ? ('cause I can see that you provided the _centreon-auth-token_ to the last request)

**Comment by adr-mo** [comment]
I've been trying to reproduce but I could not.
Is your server configured with **https** access ?

**Comment by cam-bdt** [comment]
> 
> 
> Okay so the authentication works but not the action of **listing the hosts** ? ('cause I can see that you provided the _centreon-auth-token_ to the last request)
> 
> Furthermore last request should look like this
> 
> ```
> curl 'http://centreon.cst.cnes.fr/centreon/api/index.php?action=action&object=centreon_clapi' -H 'Content-Type: application/json' -H 'centreon-auth-token: <token>' --data '{"action":"show", "object":"HOST"}'
> ```

Nothing works, even authentication returns Unauthorized




> 
> 
> I've been trying to reproduce but I could not.
> Is your server configured with **https** access ?

Yes, my server is https, forgot the S in the comment but I tried it, and it still outputs Unauthorized

**Comment by adr-mo** [comment]
Okay

- Could you try requesting the server using the `-k` option for curl

**Comment by cam-bdt** [comment]
Does not work

**Comment by cam-bdt** [comment]
But I need to pass through browser

**Comment by adr-mo** [comment]
Aw I see.

In you command could you please remove the simple quotes from username and password.
`"username=username&password=pass"`

**Comment by cam-bdt** [comment]
Does not change anything :'(

**Comment by adr-mo** [comment]
Okay, something you can do is joining our [Slack community](https://centreon.github.io/register-slack)

It will be easier to discuss of your issue and other community will help :)

**Comment by cam-bdt** [comment]
Thanks you for everything :)

**Comment by kozfelipe** [comment]
mine works like this 
![image](https://user-images.githubusercontent.com/25208457/58117627-64beff00-7bd5-11e9-97a0-26a7ef08e89f.png)

**Comment by cam-bdt** [comment]
Thank you ! Now I have this :
![image](https://user-images.githubusercontent.com/43960194/58157573-e1ef8000-7c78-11e9-869d-eca1cc8d6bff.png)

**Comment by adr-mo** [comment]
Hi @cam-bdt 

Did you finally succeed in what you wanted to do ?
This issue can be closed ? (_it is not related to Centreon itself_)

Regards,
