### ISSUE TITLE
A little mistake in the API documentation

### ISSUE THREAD

**Issue by MiStErLu** [centreon/centreon#7561]
I just want to warn you that the API documentation got a little mistake.

In the "Realtime information", "Host Status" 
There is a mistake in the parameters options
     sortType | ASC ou DESC
     order | the order type (selected in the field list)

It should be
     sortType | the sortType (selected in the field list)
     order | ASC ou DESC

The mistake is the same in the "Realtime information", "Service Status" 

Thanks,
MiStErLu

**Comment by adr-mo** [comment]
Hi @MiStErLu 

Thanks for the feedback :100: 

We'll do the correction ASAP :+1: 

Regards
