### ISSUE TITLE
Cron tasks not running after 19.10.4

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7564]
Hi,

After 19.10.4 update, cron tasks owned by `apache` do not run anymore.

```
May 28 10:09:02 srv CROND[28086]: (apache) CMD (/opt/rh/rh-php71/root/usr/bin/php -q /usr/share/centreon/cron/centAcl.php >> /var/log/centreon/centAcl.log 2>&1)
May 28 10:09:02 srv CROND[28086]: (CRON) ERROR chdir failed (/usr/share/httpd): No such file or directory
```

This is due to the fact that the old homedir `/usr/share/httpd` may not exist anymore after installation of the new `httpd-24-httpd` package and removal of the old one.

I then had to :
`usermod -d /opt/rh/httpd24/root/usr/share/httpd apache`

Thank you 👍

**Comment by adr-mo** [comment]
Hi @CPbN,

Thanks for the feedback :100: 

I've just opened an issue internally on the subject, we'll fix it ASAP :)

Regards

**Comment by lpinsivy** [comment]
@CPbN If you install a new Centreon server using 19.04 you got directly the correct homedir:

apache:x:48:48:Apache:/opt/rh/httpd24/root/usr/share/httpd:/sbin/nologin

If you perform an update from 18.10 you should have both httpd and httpd24-httpd packages and the /usr/share/httpd/ is still present.

Did you remove httpd package?

**Comment by CPbN** [comment]
Yes @lpinsivy, you're right, I removed the old unused httpd package.

**Comment by lpinsivy** [comment]
Maybe that is why you have this issue because you remove manually the old package and not only disable it.

Regards,
