### ISSUE TITLE
Centreon 19.04 - Syslog issue

### ISSUE THREAD

**Issue by TIB28** [centreon/centreon#7569]
Hi, i've make the update to centreon 19.04 in centos dist with the "yum update centreon\*" method but since httpd24 update i have a blank page at the place of Syslog-frontend  do u have a tutorial  for reinstate SYSLOG-SERVEUR and SYSLOG-FRONTEND ?
i've installed at first time centreon with the .iso package .
thank u for the futur reply  .

**Comment by adr-mo** [comment]
Hi @TIB28 

Thanks for the feedback 💯 

With the httpd upgrade the location of the files for the apache configuration **has changed.**

If you had configured apache for reaching syslog front-end, you'll have to move to files to the **correct directory**.

Please find here some documentation on the subject [here](https://documentation.centreon.com/docs/centreon/en/latest/upgrade/from_packages_1810.html#additional-actions)

Regards,

**Comment by lpinsivy** [comment]
Hi,

This module are obsolete and not compatible with Centreon >= 2.7.x

Regards,
