### ISSUE TITLE
No index definition files found

### ISSUE THREAD

**Issue by hecko** [centreon/centreon#7576]
Documentation here https://documentation.centreon.com/docs/centreon/en/19.04/faq/performance.html mentions SQL index definition files such as centreonIndexes.json - Im unable to find the files anywhere on the system not in this git repo. 

I assume these files are generated in development, not on the actual system where centreon runs - if so, what is the procedure to generate these files? 

Marcel

**Comment by lpinsivy** [comment]
Hi @hecko 

Yes you right we mentioned these files but there are not more in github.

On a fresh Centreon installation you can get them using following commands:

```
/opt/rh/rh-php71/root/bin/php /usr/share/centreon/bin/export-mysql-indexes  -d centreon -o /tmp/centreonIndexes.json
/opt/rh/rh-php71/root/bin/php /usr/share/centreon/bin/export-mysql-indexes  -d centreon_storage -o /tmp/centreonIndexes.json
```
