### ISSUE TITLE
Downtime in 1970

### ISSUE THREAD

**Issue by twitram** [centreon/centreon#7580]
Hello

I'm having a bug When I want to add a downtime to a future date, the downtime is created in 1970 and the downtime is active at the moment it is created.
Best Regards

----
Centreon version CES.

Centreon 2.8.27
--

**Comment by twitram** [comment]
IN GUi downtime set until 1970.

**Comment by twitram** [comment]
[1559655449] [2941] EXTERNAL COMMAND: SCHEDULE_HOST_DOWNTIME;MyHost;1560808800;1560830400;0;0;7200;matthieu;TP presta
[1559655449] [2941] EXTERNAL COMMAND: SCHEDULE_HOST_SVC_DOWNTIME;MyHost;1560808800;1560830400;0;0;7200;matthieu;TP presta

**Comment by twitram** [comment]
![Sans titre](https://user-images.githubusercontent.com/14791276/58883906-a83e6080-86df-11e9-9a8b-eaf13e0d31f9.png)

**Comment by adr-mo** [comment]
Hi @twitram 

Thanks for the feedback :100: 

This issue has been fixed since the release of the **18.10.0**

Is it possible for you to upgrade to this version ?
https://documentation.centreon.com/docs/centreon/en/18.10/upgrade/from_packages.html

Regards,

**Comment by twitram** [comment]
Its hard for me to upgrade to this version.if you have another solution I am a taker

**Comment by adr-mo** [comment]
Ok :smiley: 

Let me check with our Product Manager @lpinsivy and we'll get back to you **ASAP**

Regards

**Comment by twitram** [comment]
The workaround is to restart the poller.

**Comment by adr-mo** [comment]
Hi @twitram 

I saw with the Product Manager, there will be no fix for the **2.8.x** versions of Centreon for this issue.
Sorry.

You can still upgrade to **18.10.x or 19.04.x** to get the fix.

Regards,
