### ISSUE TITLE
SNMPEXTRAOPTIONS passphrases and passwords appears

### ISSUE THREAD

**Issue by nikitito** [centreon/centreon#7588]
Hello,
To refer to that issue below,
everything which is put in SNMPEXTRAOPTIONS appears in the web interface at the detailed status of service level.
Could you enhance that please ?

Have a nice day

https://github.com/centreon/centreon-plugins/issues/1540

**Comment by garnier-quentin** [comment]
Set password type macro in host configuration.

**Comment by nikitito** [comment]
Changes nothing, I did it before opening this issue

**Comment by CPbN** [comment]
_May_ be related to #7524.

**Comment by lpinsivy** [comment]
@nikitito can you try the fix in PR #7524 ?

**Comment by nikitito** [comment]
I'll do that asap and will give you the feedback.
Thank you for your answer
