### ISSUE TITLE
nagios-plugins from epel fails to install due to perl(utils) dependency

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon#7593]
Hi all,
On a CentOS 7 server, installing from packages (yum update), i have issue like the following one :

> Error: Package: nagios-plugins-udp-1.4.16-10.el7.centos.x86_64 (@centreon-stable)
>            Requires: nagios-plugins = 1.4.16-10.el7.centos
>            Removing: nagios-plugins-1.4.16-10.el7.centos.x86_64 (@centreon-stable)
>                nagios-plugins = 1.4.16-10.el7.centos
>            Updated By: nagios-plugins-2.2.1-16.20180725git3429dad.el7.x86_64 (epel)
>                nagios-plugins = 2.2.1-16.20180725git3429dad.el7
>            Available: nagios-plugins-2.2.1-9git5c7eb5b9.el7.x86_64 (epel)
>                nagios-plugins = 2.2.1-9git5c7eb5b9.el7
>            Available: nagios-plugins-2.2.1-15.20180725git3429dad.el7.x86_64 (epel)
>                nagios-plugins = 2.2.1-15.20180725git3429dad.el7
> Error: Package: centreon-plugins-2.8.28-2.el7.centos.noarch (installed)
>            Requires: perl(utils)
>            Removing: nagios-plugins-perl-1.4.16-10.el7.centos.x86_64 (@centreon-stable)
>                perl(utils)
>            Updated By: nagios-plugins-perl-2.2.1-16.20180725git3429dad.el7.x86_64 (epel)
>                Not found
> Error: Package: nagios-plugins-nsc-1.4.16-10.el7.centos.x86_64 (@centreon-stable)
>            Requires: nagios-plugins = 1.4.16-10.el7.centos
>            Removing: nagios-plugins-1.4.16-10.el7.centos.x86_64 (@centreon-stable)
>                nagios-plugins = 1.4.16-10.el7.centos
>            Updated By: nagios-plugins-2.2.1-16.20180725git3429dad.el7.x86_64 (epel)
>                nagios-plugins = 2.2.1-16.20180725git3429dad.el7
>            Available: nagios-plugins-2.2.1-9git5c7eb5b9.el7.x86_64 (epel)
>                nagios-plugins = 2.2.1-9git5c7eb5b9.el7
>            Available: nagios-plugins-2.2.1-15.20180725git3429dad.el7.x86_64 (epel)
>                nagios-plugins = 2.2.1-15.20180725git3429dad.el7
>  You could try using --skip-broken to work around the problem
> ** Found 2 pre-existing rpmdb problem(s), 'yum check' output follows:
> centreon-plugins-2.8.28-2.el7.centos.noarch has missing requires of centreon-common = ('0', '2.8.28', '2.el7.centos')
> centreon-poller-centreon-engine-2.8.26-3.el7.centos.noarch has missing requires of centreon-plugins = ('0', '2.8.26', '3.el7.centos')

Seems like centreon-plugins packages requires perl(utils), which is provided by nagios-plugins-perl from centreon repository.
But no more by nagios-plugins-perl from epel repository.

How can i fix it and procede with upgrading centroen?

Thanks

**Comment by adr-mo** [comment]
Hi @R00T88 

Thanks for the feedback :100: 

Maybe you could try to disable epel repository ?

Regards

**Comment by R00T88** [comment]
Hi @adr-mo 
How can i disable it?

**Comment by adr-mo** [comment]
@R00T88 You'll have to edit the epel repository file located in
```
/etc/yum.repos.d/
```

Regards

**Comment by lpinsivy** [comment]
or try

yum update Centreon\* --disablerepo=epel

Regards,
