### ISSUE TITLE
Upgrade from 18.10.4 to 18.10.5 failed

### ISSUE THREAD

**Issue by hdep** [centreon/centreon#7595]
# BUG REPORT INFORMATION

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
# rpm -qa | grep centreon
centreon-license-manager-common-18.10.2-1.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190412-141630.el7.centos.noarch
centreon-perl-libs-18.10.5-4.el7.centos.noarch
centreon-plugin-Virtualization-VMWare-daemon-3.0.2-20190606142851.el7.centos.noarch
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-release-18.10-2.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190412-141630.el7.centos.noarch
centreon-broker-storage-18.10.1-1.el7.centos.x86_64
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-nrpe3-plugin-3.2.1-7.el7.centos.x86_64
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190412-141630.el7.centos.noarch
centreon-trap-18.10.5-4.el7.centos.noarch
centreon-plugins-base-1.18-2.el7.centos.noarch
centreon-broker-core-18.10.1-1.el7.centos.x86_64
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190412-141630.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190412-141630.el7.centos.noarch
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-broker-18.10.1-1.el7.centos.x86_64
centreon-broker-cbmod-18.10.1-1.el7.centos.x86_64
centreon-database-18.10.5-4.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190412-141630.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20190412-141630.el7.centos.noarch
centreon-web-18.10.5-4.el7.centos.noarch
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Databases-Mysql-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190412-141630.el7.centos.noarch
centreon-common-18.10.5-4.el7.centos.noarch
centreon-poller-centreon-engine-18.10.5-4.el7.centos.noarch
```

***Operating System***

CentOS Linux release 7.6.1810 (Core)

***Browser used***

- [ ] Google Chrome
- [X ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***
VMWare
### Description

yum update on the system, this upgrade a centreon 18.10.4 to 18.10.5

### Steps to Reproduce

1 - yum update on the system to upgrade to centreon 18.10.5
2 - login to centreon ui and get redirected to https://centreon.domain.fr/centreon/install/upgrade.php
3 - Web page show the message ```Configuration file not found. (install.conf.php)```

### Logs

**PHP error logs**
no related logs

**Comment by hdep** [comment]
In order to fix this issue : 

```
cd /usr/share/centreon/www/install
cp install.conf.dist.php install.conf.php
```

**Comment by lpinsivy** [comment]
Hi @hdep no error during yum update?

Regards,

**Comment by hdep** [comment]
Hi,

No I didn't see any error.

**Comment by hdep** [comment]
same error for upgrade from 18.10.5 18.10.6
```
# find / -name install.conf.php
/usr/share/centreon/installDir/install-18.10.5-20190607_102820/install.conf.php
# cd /usr/share/centreon/www/install
# cp /usr/share/centreon/installDir/install-18.10.5-20190607_102820/install.conf.php install.conf.php
```

**Comment by hdep** [comment]
upgrade from 18.10.6 to 18.10.7 same issue. 
Maybe one day you will want to check this ! But I'm pretty sure you won't.
```
cd /usr/share/centreon/www/install
cp install.conf.dist.php install.conf.php
chown centreon:centreon install.conf.php
```

**Comment by adr-mo** [comment]
Hi @hdep 

**FYI** this issue has been already checked by the team. However we could not find a reproduction procedure to fix this issue.

If you have any kind of specific information allowing us to reproduce this issue do not hesitate.

Regards

**Comment by hdep** [comment]
Hi,

as you have the way I fix the issue, just by looking at the package centreon-web I can see that you don't ship the file install.conf.php

# rpm -ql centreon-web-18.10.7-3.el7.centos.noarch | grep install.conf.php

currently I don't have /usr/share/centreon/www/install folder because after upgrade process I assume you move or delete the directory.

So from my point of view this seem to be an easy fix : just add install.conf.php file into the rpm
