### ISSUE TITLE
Upgrade from 18.10.5 to 19.04.2

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon#7596]
Hi,

I attempted to upgrade Centreon 18.10.5 to 19.04.2.

I followed https://documentation-fr.centreon.com/docs/centreon/fr/19.04/upgrade/from_packages_1810.html#mise-a-jour-du-serveur-centreon-central and it fails here :

![image](https://user-images.githubusercontent.com/38944475/59095704-70226200-8919-11e9-9ef6-c179b89a3382.png)

As you can see it fails at step 19.04.0 to 19.04.1

```
$ rpm -qa |grep centreon
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-base-config-centreon-engine-19.04.2-7.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190412-141630.el7.centos.noarch
centreon-trap-19.04.2-7.el7.centos.noarch
centreon-poller-centreon-engine-19.04.2-7.el7.centos.noarch
centreon-license-manager-19.04.0-1.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190412-141630.el7.centos.noarch
centreon-common-19.04.2-7.el7.centos.noarch
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-engine-extcommands-19.04.1-9.el7.centos.x86_64
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-19.04.2-7.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190412-141630.el7.centos.noarch
ces-plugins-Operatingsystems-Windows-Wmi-check_centreon_wmi-1.1.1-1.el6.x86_64
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-engine-daemon-19.04.1-9.el7.centos.x86_64
centreon-engine-19.04.1-9.el7.centos.x86_64
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-web-19.04.2-7.el7.centos.noarch
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-plugin-Network-Cisco-Standard-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190412-141630.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190412-141630.el7.centos.noarch
ces-plugins-Operatingsystems-Windows-Wmi-check_centreon_wmi_query-1.1.1-1.el6.x86_64
centreon-release-19.04-1.el7.centos.noarch
centreon-perl-libs-19.04.2-7.el7.centos.noarch
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190412-141630.el7.centos.noarch
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-database-19.04.2-7.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190412-141630.el7.centos.noarch`
````
Firefox Version: -- 60.7.0esr

VMWare

### Description

Can’t upgrade to 19.04.2 from 18.10.5

### Steps to Reproduce

1. Install Centron 18.10.5 from RPM
2. Try to follow the procedure above to upgrade to 19.04.

### Describe the received result

Update-DB-19.04.1.sql Line 2:SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'http_method'

### Describe the expected result

Upgrade OK

I tried the following hoping it can fix the issue: I upgraded the database server (which is another host) to 19.04.2, it upgraded MariaDB (to version 10.1.38), went well. Then I clicked "refresh" in the upgrade form but it issued the same error :(

In _/var/log/httpd24/ssl_error_log_ I have only two messages : server certificate does NOT include an ID which matches the server name

In _/var/log/httpd24/ssl_access_log_ I have :

>[07/Jun/2019:11:24:37 +0200] "GET /centreon/ HTTP/1.1" 302 3091
[07/Jun/2019:11:24:38 +0200] "GET /centreon/install/upgrade.php HTTP/1.1" 200 2009
[07/Jun/2019:11:24:38 +0200] "GET /centreon/install/install.css HTTP/1.1" 200 3973
[07/Jun/2019:11:24:38 +0200] "GET /centreon/install/pub_install.css HTTP/1.1" 200 1402
[07/Jun/2019:11:24:38 +0200] "GET /centreon/install/step_upgrade/step1.php HTTP/1.1" 200 1569
[07/Jun/2019:11:24:38 +0200] "GET /centreon/img/centreon.png HTTP/1.1" 200 6730
[07/Jun/2019:11:24:41 +0200] "GET /centreon/install/step_upgrade/step2.php HTTP/1.1" 200 2535
[07/Jun/2019:11:24:42 +0200] "GET /centreon/install/step_upgrade/step3.php HTTP/1.1" 200 1864
[07/Jun/2019:11:24:42 +0200] "GET /centreon/install/RELEASENOTES.html HTTP/1.1" 200 2212
[07/Jun/2019:11:25:12 +0200] "GET /centreon/install/step_upgrade/step4.php HTTP/1.1" 200 4054
[07/Jun/2019:11:25:13 +0200] "GET /centreon/img/misc/ajax-loader.gif HTTP/1.1" 200 673
[07/Jun/2019:11:25:13 +0200] "POST /centreon/install/step_upgrade/process/process_step4.php HTTP/1.1" 200 151
[07/Jun/2019:11:25:13 +0200] "POST /centreon/install/step_upgrade/process/process_step4.php HTTP/1.1" 200 222
[07/Jun/2019:11:38:03 +0200] "GET /centreon/install/step_upgrade/step4.php HTTP/1.1" 200 4054
[07/Jun/2019:11:38:03 +0200] "POST /centreon/install/step_upgrade/process/process_step4.php HTTP/1.1" 200 222
[07/Jun/2019:11:38:30 +0200] "GET /centreon/install/step_upgrade/step4.php HTTP/1.1" 200 4054
[07/Jun/2019:11:38:31 +0200] "POST /centreon/install/step_upgrade/process/process_step4.php HTTP/1.1" 200 222

In _centreon-error.log_ I only have the following :
```
[05-Jun-2019 17:20:02 Europe/Paris] PHP Notice:  Undefined offset: 1 in /usr/share/centreon/www/index.php on line 112
```
Also no error in centcore.log 

I’m waiting your feedback before attempting anything.

Best regards,

**Comment by StefThomas** [comment]
Maybe commenting the following line in _ /usr/share/centreon/www/install/sql/centreon/Update-DB-19.04.1.sql_ :

ALTER TABLE remote_servers ADD COLUMN `http_method` enum('http','https') NOT NULL DEFAULT 'http';

could fix the issue ?

**Comment by StefThomas** [comment]
I finally tested my solution. I commented out the modifications in _/usr/share/centreon/www/install/sql/centreon/Update-DB-19.04.1.sql_ (after I checked they were already effectives) . The upgrade process terminated OK.

**Comment by adr-mo** [comment]
Hi @StefThomas 

Thanks for the feedback 💯 

In fact we are aware of this issue. I'll close this issue for now since you found a workaround.
The SQL upgrade script of the 19.04.2 will be modified and fixed in the next release.

A Jira ticket has been opened internaly

Regards,
