### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by markeur** [centreon/centreon#7599]
Please can you update the documentation with informations about the installation of a poller using package. In fact there is only information for a central server and no information for poller but by using the command `yum install centreon-poller` it seems that a specific process is existing.

Thank you.

**Comment by pkriko** [comment]
Hello @markeur 

You can find the documentation about the installation of a Poller here : https://documentation.centreon.com/docs/centreon/en/latest/administration_guide/poller/install_poller_packages.html

And you can retrieve everything about the distributed architecture here : https://documentation.centreon.com/docs/centreon/en/latest/administration_guide/poller/index.html
