### ISSUE TITLE
API - Auth broken when token contain '\/'

### ISSUE THREAD

**Issue by hdep** [centreon/centreon#7616]
# BUG REPORT INFORMATION

***Versions***

For the RPM based systems

```
$ rpm -qa | grep centreon
centreon-license-manager-common-18.10.2-1.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190412-141630.el7.centos.noarch
centreon-perl-libs-18.10.5-4.el7.centos.noarch
centreon-plugin-Virtualization-VMWare-daemon-3.0.2-20190606142851.el7.centos.noarch
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-release-18.10-2.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190412-141630.el7.centos.noarch
centreon-broker-storage-18.10.1-1.el7.centos.x86_64
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-nrpe3-plugin-3.2.1-7.el7.centos.x86_64
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190412-141630.el7.centos.noarch
centreon-trap-18.10.5-4.el7.centos.noarch
centreon-plugins-base-1.18-2.el7.centos.noarch
centreon-broker-core-18.10.1-1.el7.centos.x86_64
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190412-141630.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190412-141630.el7.centos.noarch
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-broker-18.10.1-1.el7.centos.x86_64
centreon-broker-cbmod-18.10.1-1.el7.centos.x86_64
centreon-database-18.10.5-4.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190412-141630.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20190412-141630.el7.centos.noarch
centreon-web-18.10.5-4.el7.centos.noarch
centreon-nrpe-plugin-2.15-4.el7.centos.x86_64
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Databases-Mysql-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190412-141630.el7.centos.noarch
centreon-common-18.10.5-4.el7.centos.noarch
centreon-poller-centreon-engine-18.10.5-4.el7.centos.noarch
```

***Operating System***

*CentOS Linux release 7.6.1810 (Core)*

***Browser used***

- [ ] Google Chrome
- [X ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 67.0.2

***VMWARE***

### Description

-- When I get a centreon-auth-token with special character like \/ authentification is forbidden  --

### Steps to Reproduce

1. get a token with curl until you get a token like this one : ```FTEXR+nYz\/ykEdPWsfS26oDo5yL7uN0BZAnLbo7P1kg=```
```
#!/bin/bash -x
LOGIN=admin
PASSWORD=password
CENTREON_URL=http://centreon.domain.fr

# GET TOKEN
TOKEN=$(curl -s \
-d "username=${LOGIN}&password=${PASSWORD}" \
-H "Content-Type: application/x-www-form-urlencoded" \
-X POST ${CENTREON_URL}/centreon/api/index.php?action=authenticate)
```

2. try to query APi 

 ```
# curl -s 'http://centreon.domain.fr/centreon/api/index.php?object=centreon_realtime_services&action=list&status=critical' -H 'Content-Type: apson' -H 'centreon-auth-token: jmc500xGqhn3\/mNPVcT4njr6FSIB4oMRi3u9Ng8Uhuc=' --verbose
*   Trying 192.168.1.1...
* TCP_NODELAY set
* Connected to (nil) (192.168.1.1) port 3128 (#0)
> GET http://centreon.domain.fr/centreon/api/index.php?object=centreon_realtime_services&action=list&status=critical HTTP/1.1
> Host: centreon.domain.fr
> User-Agent: curl/7.52.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> Content-Type: application/json
> centreon-auth-token: jmc500xGqhn3\/mNPVcT4njr6FSIB4oMRi3u9Ng8Uhuc=
>
< HTTP/1.1 403 Forbidden
< Date: Sat, 15 Jun 2019 10:01:50 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
< X-Powered-By: PHP/7.1.8
< Content-Type: application/json;charset=utf-8
< X-Cache: MISS from proxy
< X-Cache-Lookup: MISS from proxy:3128
< Transfer-Encoding: chunked
< Via: 1.1 proxy (squid/3.5.23)
< Connection: keep-alive
<
* Curl_http_done: called premature == 0
* Connection #0 to host (nil) left intact
```

### Describe the received result

We receive a  `HTTP/1.1 403 Forbidden`  but Header for authentification seems OK

### Describe the expected result
We expect to get an answer from API which is 200. 
I works when the token is like `oSJ6rfYKLodBTk0UqcyyWJ5xvTCqyWNg5+G94T+u6Xo=`
### Logs

**PHP error logs**
No logs

### Additional relevant information (e.g. frequency, ...)

I can reproduce everytime.

**Comment by hdep** [comment]
Hi can anyone could review this bug ?

**Comment by kermith72** [comment]
Hello,
It is necessary to protect the token by simple quote. 
Example :
 `curl -s 'http://192.168.1.99/centreon/api/index.php?object=centreon_realtime_services&action=list&status=critical' -H 'Content-Type: application/json' -H 'centreon-auth-token: 'UZi\/SB+cjxEf9L0ntkmci+3bROPhJ+w2DAEtZNcZN60=''
[{"host_id":"34","name":"mbi1904","description":"DWH-db-content","service_id":"310","state":"2","state_type":"1","output":"[Table mod_bi_hgmonthavailability: EMPTY] [Table mod_bi_hgservicemonthavailability: EMPTY] [Table mod_bi_metricmonthcapacity: EMPTY] [Table mod_bi_metriccentiledailyvalue: EMPTY]\n","perfdata":"","max_check_attempts":"3","check_attempt":"3","last_check":"1563172116","last_state_change":"1563084698","last_hard_state_change":"1563084698","acknowledged":"1","criticality":null},{"host_id":"102","name":"sw-berlin-01","description":"memory","service_id":"711","state":"2","state_type":"1","output":"Memory used : 5.73 Go - size : 6.00 Go - percent : 95 %\n","perfdata":"used=6154654781o;5153960755;5798205850;0;6442450944 size=6442450944o","max_check_attempts":"3","check_attempt":"3","last_check":"1563173699","last_state_change":"1563173039","last_hard_state_change":"1563173099","acknowledged":"0","criticality":null},{"host_id":"89","name":"srv-oracle-accounting","description":"Query -Bundle-","service_id":"643","state":"2","state_type":"0","output":"Query <Bundle> executed on 4.663 second\n","perfdata":"time=4.663147s","max_check_attempts":"3","check_attempt":"1","last_check":"1563173939","last_state_change":"1563173939","last_hard_state_change":"1563136874","acknowledged":"0","criticality":null}]`

**Comment by adr-mo** [comment]
Hi @hdep,

Thanks for the feedback :100: 

I guess with the explanations of @kermith72 we can close this issue.

Regards,

**Comment by aderuelle** [comment]
Hi @adr-mo, @kermith72, @hdep 

Centreon returns escaped forward slashes in auth token.

That is a problem as using the verbatim token value yields a 403 in subsequent requests.

You _have to_ unescape the forward slashes if the token contains some (replace '\/' with '/') before hand.

The mentioned "protect the token" solution actually does the _opposite_ of protecting as it relies on the shell evaluation mechanism to remove any backslashes.

In the `-H 'centreon-auth-token: 'UZi\/SB+cjxEf9L0ntkmci+3bROPhJ+w2DAEtZNcZN60=''` string, only the `'centreon-auth-token: '` part is protected and the `''` part is actually an empty string. Therefore, the token value is *not* protected and is evaluated by the shell and the backslash is removed.

This works at the shell prompt but doesn't work reliably/at all in non-interactive scripts.

@hdep, in your script(s) you can force backslash evaluation this way:

```shell
#!/bin/sh
raw_token="FTEXR+nYz\/ykEdPWsfS26oDo5yL7uN0BZAnLbo7P1kg="
eval token=${raw_token}
echo "token=${token}"
```

Regards,

Alexis
