### ISSUE TITLE
[Doc] SSH keys with passphrase ?

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7620]
Hi,

In the Remote Server installation documentation :
https://documentation.centreon.com/docs/centreon/en/latest/administration_guide/poller/install_remote_server_packages.html
(and I think in other documentations such as the Poller installation one)

In _Exchanging SSH Keys_ chapter, it is written, about the new generated keys :
_Leave the passphrase blank if you wish. However it is not recommended._

I don't understand how it could work setting a passphrase (I did not find any place in Centreon configuration to indicate the SSH key passphrase).
I think we must then leave it blank, right ?

Perhaps then a documentation mistake ?

Thank you :+1:

**Comment by lpinsivy** [comment]
hi @CPbN you right it's a mistake in the documentation.
