### ISSUE TITLE
[Remote Server] checkBamOnRemoteServer() is HTTP only

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7626]
Hi,

Function `checkBamOnRemoteServer()` uses HTTP, and then fails when Remote Server is available on HTTPS only.

Thx :+1:

Edit : issue still present in 19.04.3.

**Comment by adr-mo** [comment]
Hi @CPbN 

Thanks for the feedback :100: 

I'll check with @lpinsivy but looks like that in fact there is a bug here :+1: 

Regards,

**Comment by lpinsivy** [comment]
@CPbN can you check this patch?

**Comment by CPbN** [comment]
Sure, let me test it and report.
Thank you :+1:

**Comment by CPbN** [comment]
Just one comment in the PR to fix a small issue, and it will work perfectly.
Thx :+1:

**Comment by CPbN** [comment]
Closing this, as #7640 has been merged.
Thank you @lpinsivy.
