### ISSUE TITLE
Kerberos Authentication with keytab

### ISSUE THREAD

**Issue by mreinders** [centreon/centreon#7628]
Hi,

We want to implement Kerberos to add the SSO functionality. I added a small Kerberos script to the centreonAuth.SSO.class.php and it shows the right authentication information. The Centreon authentication doesn't do anything with this information. Even if I add the $_SERVER['REMOTE_USER'] or manipulate it to HTTP_AUTH_USER, Centreon shows the login page every time.

After googling there are several patches for the previous verions, but it seems outdated and cant look at the patches.

What can I do to activate SSO without setting up lemonldap?

**Comment by lpinsivy** [comment]
Hi @mreinders 

Currently Centreon is only compatible with SSO through LemonLDAP:NG frontend.
A pull request tu use keycloak exists.

Regards,

**Comment by lpinsivy** [comment]
You need to modify Apache configuration and not Centreon.
Apache must send correct login to Centreon
