### ISSUE TITLE
[Remote Server] The version of the Central and of the Remote are incompatible

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7629]
Hi,

I'm painfully trying to configure a Remote Server.
Remote Server correctly configured, seen online by the Central Server.
I can add a new host, and flawlessy export the configuration to the Remote Server and reload it.

However, on the Remote Server, when I click on the host to get its details, I get the following :
_This host no longer exists in Centreon configuration. Please reload the configuration._

After having enabled some debug, centcore.log reveals :
```
2019-06-18 17:05:42 - DEBUG - cmd: /usr/share/centreon//bin/centreon -u <admin_user> -p <admin_md5_password> -w -o CentreonWorker -a processQueue
2019-06-18 17:05:42 - DEBUG - Result : 2019-06-18 17:05:42 - Checking for pending export tasks: 0 task(s) found
2019-06-18 17:05:42 - Checking for pending import tasks: 1 task(s) found
2019-06-18 17:05:42 - Processing task #25 (parent ID #63) ... The version of the Central 19.04.2 and of the Remote 19.04.0 are incompatible
finished.
2019-06-18 17:05:42 - Worker cycle completed.
```

The interesting part :
_The version of the Central 19.04.2 and of the Remote 19.04.0 are incompatible_

Both servers are installed with last package versions.

Did I miss something ?

Thank you :+1:

Edit : issue still present in 19.04.2.

**Comment by CPbN** [comment]
Note that Central has been _updated_ to 19.04.2.
Remote has directly been installed to 19.04.2.

Then, culprit here ?
https://github.com/centreon/centreon/blob/19.04.2/www/install/insertBaseConf.sql#L5

**Comment by adr-mo** [comment]
Hi @CPbN 

Thanks for the feedback :100: 

@lpinsivy any ideas ?

Regards,

**Comment by lpinsivy** [comment]
Hi @CPbN I will change this to compare only Major version and not bugfix

**Comment by CPbN** [comment]
Sounds like a perfect fix, many thanks @lpinsivy :+1:

**Comment by CPbN** [comment]
However I still wonder if there is a bug here :
https://github.com/centreon/centreon/blob/19.04.2/www/install/insertBaseConf.sql#L5
For 19.04.2 version, we should insert 19.04.2, right ? :)

**Comment by lpinsivy** [comment]
right !
