### ISSUE TITLE
Lister les services configurés

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#763]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 1350, https://forge.centreon.com/issues/1350
Original Date: 2009-12-02

---

Pour les connaisseurs du fonctionnement de Nagios, vous n'êtes pas sans savoir que l'on défini des services et que dans ces services sont indiqués à quels hôtes ils sont rattachés.

Donc la véritable représentation de cela est qu'en regardant le détail d'un service on peut voir quels hôtes sont rattachés.

Il me semble que ce type de vue manque dans Centreon. On peut effectivement lister les services par hôte, mais cela nous présente que la liste des hôtes avec les services attachés.

Mais avec cette présentation, comment savoir combien de services différents sont déclarés ? Et quels sont il ?
En effet on peut très facilement avoir plusieurs services déclarés sous des noms similaires, qui font la même chose, sans s'en rendre compte.

On ne peut pas via l'interface, lister tout simplement la liste des services déclarés.

Serait il possible d'avoir une vue qui affiche la liste des services ?

**Comment by julienmathis** [comment]
intégré dans le monitoring et dans la configuration
