### ISSUE TITLE
[Remote Server] Automatically start processes in correct order

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7631]
Hi,

In the Remote Server FAQ / documentation :
https://documentation.centreon.com/docs/centreon/en/latest/faq/remote_server.html
_Some Centreon processes must be started in a specific order. Indeed, the cbd process of the Remote Server must be started before the centengine processes of each poller (including the Remote Server itself)._

The following would automatically help :
```
mkdir /etc/systemd/system/centengine.service.d/
echo [Unit]             > /etc/systemd/system/centengine.service.d/override.conf
echo After=cbd.service >> /etc/systemd/system/centengine.service.d/override.conf
```

The Wants & After rules could also be directly added into centengine.service file.

Note that it also helps for example on a Central Server, as engine will then wait for cbd to be up before starting, leading to an engine status in Centreon web available very shortly.
So might no apply to Remote Server only.

Same sort of rules proposed [here](https://github.com/centreon/centreon-broker/issues/199) for cbd.

Thank you :+1:

Edit : issue still present in 19.10.1.

**Comment by adr-mo** [comment]
Hi @CPbN 

Thanks for the feedback :100:

I'll check with @lpinsivy

Regards,

**Comment by CPbN** [comment]
See https://github.com/centreon/centreon-engine/pull/172 for a fix !
