### ISSUE TITLE
[Remote Server] No Broker Statistics (debug / investigation)

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7635]
Hi,

When you configure a Remote Server, Broker Statistics ( in _Administration / Platform Status / Broker Statistics_) are not available.

I investigated, and found that on the Remote Server, in `cfg_centreonbroker` table, `config_filename` field do not point to the correct filenames.
If I manually update them to the proper filenames, Broker Statistics correctly show.
Unfortunately these fields are updated on every poller configuration export.

Let's go further.

`export()` function from `PollerExporter.php` triggers to export the broker configuration.
And the configuration get messed-up by the following call :
`$cfgCentreonBroker = $overwritePollerService->getCfgCentreonBroker...`
`getCfgCentreonBroker()` calls `findPollerAndSetResourceData()` which deliberately removes the Remote Server configuration and replaces it by a default configuration template.

I don't understand why... But this does not seem to be correct...
Of course as `findPollerAndSetResourceData` is called for other configuration items (variables, engine...) impact may be bigger.

Coud you please investigate this further ?

Thank you 👍

Edit : issue still present in 19.10.0-beta.2.

**Comment by CPbN** [comment]
In `findPollerAndSetResourceData`, I wonder if this is correct :
`return $pollerData[$columnName] != $this->pollerID;`
I would have written :
`return $pollerData[$columnName] == $this->pollerID;`
But then I don't understand the goal of merging default configuration template with current configuration...

I also wonder is this issue is the root cause of the following behavior.
Let's assume you configured your Remote Server from the Central Server, naming it _remote1_.
It's then named _Central_ on the Remote Server itself (in the `nagios_server` table), as in the default configuration...

**Comment by adr-mo** [comment]
Hi @CPbN 

Thanks for the feedback :100:

I'll check with @lpinsivy for debug matters

Regards,

**Comment by lpinsivy** [comment]
Hi @CPbN the goal is to transform a Remote Server in configuration as a localhost Centreon Central server to use correctly centcore and other functionalities.

But yes for Centreon Broker statistics it doesn't work...
We will try to find a solution

**Comment by CPbN** [comment]
OK, thank you @lpinsivy for having investigated this.
Glad you identified the root cause of the issue :)

At the same time if you are able to avoid renaming it to _Central_, but keep its original name, then it would be perfect :+1:

Thank you again !

**Comment by lpinsivy** [comment]
@CPbN this will be really more complex :(

**Comment by CPbN** [comment]
I just pushed #7642 as a proposal for the Broker statistics issue.

**Comment by CPbN** [comment]
Fixed by #7749, thank you !
