### ISSUE TITLE
Last Check Control Date Problem

### ISSUE THREAD

**Issue by ptitpopey** [centreon/centreon#7652]
***Versions***
centreon-web-19.04.2-7.el7.centos.noarch

### Description
On detail service page, the date for the last and the next control check is on unix format

![centreon-date](https://user-images.githubusercontent.com/14994180/60111367-17065b00-976e-11e9-8c4c-fc85b72bae4b.png)

**Comment by julienmathis** [comment]
Hello,

Can you check in english that you have the same problem ? If it's not the case, this problem provide from the translation file.

Thanks

**Comment by ptitpopey** [comment]
Problem Solved whitout action. You can close this issue. This problem appeared just after migration from 2.8 to 19.04
