### ISSUE TITLE
Missing dbnameIndexes.json files

### ISSUE THREAD

**Issue by nikitito** [centreon/centreon#7653]
Hi on fresh install, are missing dbnameIndexes.json files

Centos 7
Centreon Web 19.04.0

Where can I find them please ?
There are not on my server and cannot find them on Internet

**Comment by nikitito** [comment]
After running mysqltuner, I got "joins performed without indexes: 25999"

**Comment by lpinsivy** [comment]
Hi @nikitito you can find indexes in attachment 
[centreonIndexes.zip](https://github.com/centreon/centreon/files/3392204/centreonIndexes.zip)


No all Centreon tables need indexes.

Regards,
