### ISSUE TITLE
Blank page not solved

### ISSUE THREAD

**Issue by prohand** [centreon/centreon#7656]
Hi, I'm update in 19.04.2. The problem is not solved.

_Originally posted by @prohand in https://github.com/centreon/centreon/issues/7500#issuecomment-500521475_

**Comment by julienmathis** [comment]
Hello, 

Can you check you PHP logs ?

**Comment by prohand** [comment]
Hello,

No error found in /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log

**Comment by Fen0l** [comment]
Same problem when a security scan is launched on the server on my side. Nothing is logs too. Seems that the only solution for now is to reinstall centreon-web

**Comment by prohand** [comment]
Hello,

Reinstall centreon-web not solved problem :(

**Comment by kozfelipe** [comment]
@Fen0l you should look at https://github.com/centreon/centreon/issues/7505

@prohand make sure you have this patch applied https://github.com/centreon/centreon/commit/e2922c5831d51792b8906caee50b9c358724d881

**Comment by prohand** [comment]
@kozfelipe  Good evening,

Thank you but how can I apply the patch without doing it manually?

Thank you

**Comment by kozfelipe** [comment]
@prohand Im not sure really. I confess I made it manually file by file.

**Comment by prohand** [comment]
Seriously... Will this be fixed in a future version of centreon?

**Comment by prohand** [comment]
Hello,

I solved the problem by putting this in the httpd conf file:

```
<LocationMatch ^ / centreon / (. * \. Php (/.*)?) $>
   ProxyPassMatch fcgi: //127.0.0.1: 9042 / usr / share / centeron / www / $ 1
</ LocationMatch>

Alias / centeron / usr / share / centeron / www

RedirectMatch ^ / $ / Centreon
```

Thank you

**Comment by adr-mo** [comment]
Hi @prohand glad to know that you've figured it out, can I close this issue ?

**Comment by prohand** [comment]
Yes you can close the issue

**Comment by adr-mo** [comment]
Okay thanks ! :+1:
