### ISSUE TITLE
snmp_standard::mode::interfaces returns "Traffic In : skipped, Traffic Out : skipped"

### ISSUE THREAD

**Issue by taston** [centreon/centreon#7657]
Hi,

everything works properly when I run command from console:

> centreon_plugins.pl --plugin=network::juniper::srx::plugin --mode=interfaces --hostname=x.x.x.x --add-traffic --interface=st0.0 --name --snmp-community=xxx --warning-in-traffic=1: --speed=100

> OK: Interface 'st0.0' Traffic In : 5.87Mb/s (5.87%), Traffic Out : 8.41Mb/s (8.41%) | 'traffic_in'=5865107.97b/s;1000000:;;0;100000000 'traffic_out'=8405196.08b/s;;;0;100000000

But when I run this command from centreon I get "skipped" output:

>  OK: Interface 'st0.0' Traffic In : skipped, Traffic Out : skipped 

I read file /var/lib/centreon/centplugins/snmpstandard_x.x.x.x_161_interfaces

> $datas = {
>            '532_speed_in' => 100000000,
>            '532_mode_traffic' => 32,
>            '532_display' => 'st0.0',
>            'last_timestamp' => 1561719111,
>            '532_in' => '24528648456',
>            '532_speed_out' => 100000000,
>            '532_out' => '10371591760'
>          };

If I run command again from centreon then values "in" and "out" increases.

> $datas = {
>            '532_speed_in' => 100000000,
>            '532_mode_traffic' => 32,
>            '532_display' => 'st0.0',
>            'last_timestamp' => 1561719174,
>            '532_in' => '24761511864',
>            '532_speed_out' => 100000000,
>            '532_out' => '10935233776'
>          };

But i still get:

> Traffic In : skipped, Traffic Out : skipped 

Any solutions?

**Comment by CPbN** [comment]
Use `--no-skipped-counters` option ?

**Comment by taston** [comment]
If I use 

> --no-skipped-counters 

option in ssh console it works normally, but if I use this option in centreon check command then I get 

> 0b/s traffic speed 

(but in file file /var/lib/centreon/centplugins/snmpstandard_x.x.x.x_161_interface I see that  values "in" and "out" increases.)

**Comment by kozfelipe** [comment]
https://github.com/centreon/centreon-plugins/issues/1368#issuecomment-457816778

**Comment by JackTor** [comment]
Hi, i have its problem. i check  one MV VMware vmxnet3 10Gb

**Comment by garnier-quentin** [comment]
If you have 0b/s, it means SNMP counters don't move.
