### ISSUE TITLE
[BUG] Dashboard menu displays templates instead of services

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#7662]
# BUG REPORT INFORMATION

### Prerequisites
***Versions***
CENTREON 19.04
CENTREON 18.10
CENTREON 2.8.x

***Operating System***
CentOS 6
CentOS 7

### Description

In the "Dashboard" menu, the status display gives the templates instead of the services.

### Steps to Reproduce

1. Create a Service Group in Centreon (Configuration > Services > Service Group) like this : 

- Name : _SG-CPU_
- Description : _SG-CPU_
- Linked Service Templates : _OS-Linux-Cpu-NRPE-custom, OS-Linux-Cpu-SNMP-custom, OS-Windows-Cpu-NRPE-custom, OS-Windows-Cpu-SNMP-custom_

2. Save and export configuration
3. Go in "Reporting > Dashboard > Service Groups" menu
4. Choose the "SG-CPU" service group

### Describe the received result
In "State Breakdowns For Host Services" part, the list displays templates instead of services
![Dashboard](https://user-images.githubusercontent.com/13255513/60421782-d0d84e00-9bea-11e9-80ed-d94659133134.png)

### Describe the expected result
In "State Breakdowns For Host Services" part, the list displays services linked to templates

Regards

**Comment by cgagnaire** [comment]
Fixed by https://github.com/centreon/centreon/pull/8406
