### ISSUE TITLE
RFP: Add new choice to the main  Centreon Web Menu on left side

### ISSUE THREAD

**Issue by blamal** [centreon/centreon#7667]
Hello,
Can you evaluate the opportunity to add a new functionnality on the left main menu of the web interface? See the attach.
![20190702_centreon_favoris](https://user-images.githubusercontent.com/6761085/60500003-d94b8a00-9cb9-11e9-8858-7d71e533216e.PNG)

Add an Favorite functionnality as by Browser.
For example a shortcut to Parameters>Service>Service by host
Regards
Bernard Lamal

**Comment by lpinsivy** [comment]
He

We do not plan to add this feature to the product.

You can create bookmarks in your browser from the generated link by clicking on the profile icon.

Thank you for your feedback.

Regards,
