### ISSUE TITLE
Remplace timstamp for date in export CSVevents logs 

### ISSUE THREAD

**Issue by SofieneB** [centreon/centreon#7671]
Centreon 19.04

Hello,

It's possible to have the date replace timstamps : 

Monitoring => Events Logs 

![image](https://user-images.githubusercontent.com/43996282/60583289-da002100-9d8a-11e9-9016-7a3513086493.png)

![image](https://user-images.githubusercontent.com/43996282/60583601-83dfad80-9d8b-11e9-901f-1d5270e1f3bc.png)

In old version it's working.

Thank's

**Comment by lpinsivy** [comment]
Corrected on 19.04.2 version by #7533
