### ISSUE TITLE
Search for disabled services

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#7672]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

Centreon 19.04.2

***Operating System***

CentOS

***Browser used***

- [X] Google Chrome
- [X] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

VM

### Description

When you select Disabled services the page refresh and the disabled services are not displayed

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. I reached Configuration - Services
3. In the Status field click on Disabled
4. Click on Search

### Describe the received result

The page is refreshed without show Disabled services

### Describe the expected result

Disabled services should be shown

### Logs

**PHP error logs**

```
No error in logs
```

**Comment by quanghungb** [comment]
Hello @lolokai 

Thank you for your feedback. Your issue should be resolved in this PR : https://github.com/centreon/centreon/pull/7612

As it was merged, it will be available in the next coming minor release (soon). 

Thanks for your patience. 

Regards.

**Comment by lolokai** [comment]
Thx @quanghungb  I've patched my Centreon it works perfectly
