### ISSUE TITLE
Filters don"t work on the next pages

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#7693]
***Versions***

Centreon 19.04

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I set a filter on Configuration > Services W Service by host 
2. Filter is apply on page 1
3. Filter is blank when i go on page 2 , and filter wasn't apply.

**PHP error logs**

```
tail -f /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log
```

Nothing in this lofgile => /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log

**Comment by sc979** [comment]
Hi @Jordan91 ,
Please, could you apply the modifications from this PR : `https://github.com/centreon/centreon/pull/7660/files`
Best Regards,
sc979

**Comment by cgagnaire** [comment]
> No relevant anymore
@kduret
