### ISSUE TITLE
admin connection impossible

### ISSUE THREAD

**Issue by markeur** [centreon/centreon#7699]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Operating System***

*CentOS.*

***Browser used***

- [ ] Google Chrome
- [ ] Firefox
- [x] Internet Explorer IE11
- [ ] Safari

Version: 19.04

Physical install

### Description

I didn't change the admin password but from two hours now centreon refuse the authentification

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Try to connect to centreon

### Describe the received result
authentification is refuse and and the following message appear: "The form has not been submitted since 15 minutes. Please retry to resubmit here"
### Describe the expected result
The authentification work
### Additional relevant information (e.g. frequency, ...)
I have nagvis installed too and the same problem append on it

edit : I just reverse the admin password and it is the same as expected

**Comment by lpinsivy** [comment]
Hi @markeur what is your version of Centreon?

**Comment by adr-mo** [comment]
Hi @markeur,

Could you please provide more informations ?

For instance logs for php ? (regarding your versions of Centreon and Apache)

**php7.1**
```
tailf /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log
```
**php7.2**
```
tailf /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log
```

Regards

**Comment by adr-mo** [comment]
@markeur 

Could you try also to force a new password for the admin account ?

```
mysql centreon <<< "UPDATE contact SET contact_passwd = 'MD5-ENCRYPTED-PASSWORD' WHERE contact_id = 1;"
```

**Comment by markeur** [comment]
Hi, 
sorry for the delay. After a long break I just try to reconnect and this work this time without doing anything. It's like the database was not available for a moment.

**Comment by adr-mo** [comment]
Hi,

Ok good to know.

I'll close this issue.

Regards
