### ISSUE TITLE
Columns Duration and Hard State Duration

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#770]
---

Author Name: **Bastien MAREAU** (Bastien MAREAU)
Original Redmine Issue: 6442, https://forge.centreon.com/issues/6442
Original Date: 2015-06-24

---

Centreon 2.6.1
Engine 1.4.13
Broker 2.8.2

Hi,

In "Monitoring - Services - Unhandled Problems" columns 'Duration' and ' Hard State Duration' have the same time.
They should not be identical.

Best Regards

**Comment by leoncx** [comment]
This issue is a related to Centreon Engine.
