### ISSUE TITLE
Problem after upgrade Mariadb 10.1 to 10.4

### ISSUE THREAD

**Issue by MagnaTM-sys** [centreon/centreon#7713]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***
centreon-19.04.2-7.el7.centos.noarch
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-engine-19.04.1-9.el7.centos.x86_64
centreon-web-19.04.2-7.el7.centos.noarch

***Operating System***

CentOS Linux release 7.6.1810 (Core) 

***Browser used***
- Firefox Quantum 68.0

Version: --

VMWare

### Description

After the Mariadb Upgrade from 10.1 to 10.4 it's impossible new Hosts nor Services to create. The UI freeze. 

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. Configuration -> Hosts
3. Duplicate a Host

### Describe the received result

UI freeze (Blank screen)

### Describe the expected result

Duplicate Host

### Logs

**PHP error logs**

[18-Jul-2019 09:20:56 Europe/Berlin] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `centreon`.`host_service_relation`.`hsr_id` at row 1 in /usr/share/centreon/www/class/centreonDB.class.php:267
Stack trace:
#0 /usr/share/centreon/www/include/configuration/configObject/service/DB-Func.php(587): CentreonDB->query('INSERT INTO hos...')
#1 /usr/share/centreon/www/include/configuration/configObject/service/serviceByHost.php(139): multipleServiceInDB(Array, Array)
#2 /usr/share/centreon/www/main.get.php(248): include_once('/usr/share/cent...')
#3 {main}
  thrown in /usr/share/centreon/www/class/centreonDB.class.php on line 267

**sql-error.log**

2019-07-18 09:20|0|0| QUERY : INSERT INTO host_service_relation VALUES ('', NULL, '349', NULL, '3889')

Thanks Guys

**Comment by adr-mo** [comment]
Hi @MagnaTM-sys 

Thanks for the feedback :100: 

The version 10.4 of MariaDB is not supported yet by Centreon.

In fact since the 10.2.4 release the SQL strict mode is enabled by default.

https://mariadb.com/kb/en/library/sql-mode/

We are currently working on it so that for the 19.10.0, Centreon will be compatible with the latest versions of MariaDB

For now, I recommand to disable the SQL strict mode of MariaDB.

Let me know if it has fixed your issue

Regards

**Comment by MagnaTM-sys** [comment]
Hi @adr-mo ,

Thanks for the Help. 

On the Centreon Documentation Site ( https://documentation.centreon.com/docs/centreon/en/latest/installation/prerequisites.html ) i've see MariaDB Version >= 10.1.29 and i thought that it was not a Problem if i upgrade to 10.4 .

Now with Strict mode disabled Centreon work like a charme again.

Thanks!

**Comment by adr-mo** [comment]
Nice :+1: 

I'll close this issue for now, until the next major release.

Thanks for using Centreon !

Regards
