### ISSUE TITLE
database upgrade 19.04.2 to 19.04.3

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#7722]
[Remote Base] MariaDB 5.7.26-0ubuntu0.16.04.1 (Ubuntu)

```sql
ALTER TABLE `traps` ADD COLUMN IF NOT EXISTS `traps_mode` ENUM('0', '1') DEFAULT '0' AFTER `traps_oid`;
```

![image](https://user-images.githubusercontent.com/25208457/61637538-1a5a0d00-ac6e-11e9-818c-f8725f318d2e.png)

**Comment by adr-mo** [comment]
Hi @kozfelipe 

Thanks for the feedback :100: 

What is your version of MariaDB ?

Regards

**Comment by kozfelipe** [comment]
Hi
My remote database is running MariaDB 5.7.26-0ubuntu0.16.04.1 (Ubuntu)

**Comment by adr-mo** [comment]
Okay :+1: 

Do not hesitate to reach us if you encountered any other issues

Regards

**Comment by kozfelipe** [comment]
@adr-mo actually I need help to finish my update process. I edited my sql file to complete that step but now my centreon web redirects to /install/upgrade.php which is a file that doesnt exist anymore.

**Comment by adr-mo** [comment]
@kozfelipe Since you have updated the DB manually (by playing the full script) you can remove the following directory

```
/usr/share/centreon/www/install
```

Then connect to the web interface and check that everything is OK.

**Comment by kozfelipe** [comment]
@adr-mo perfect.

**Comment by sc979** [comment]
Hi @kozfelipe ,
A fix has been merged on each major version :
18.10.x -> `https://github.com/centreon/centreon/pull/7799`
19.04.x -> `https://github.com/centreon/centreon/pull/7798`
19.10.beta.x -> `https://github.com/centreon/centreon/pull/7801`
If you find a bug or have feedbacks, please open another issue
Best Regards
sc979
