### ISSUE TITLE
Partitions for table 'centreon_storage.data_bin' are not up to date 

### ISSUE THREAD

**Issue by lbazan** [centreon/centreon#7725]
centreon 19.10

CRITICAL: Partitions for table 'centreon_storage.data_bin' are not up to date (current retention forward in days: 0) - Partitions for table 'centreon_storage.logs' are not up to date (current retention forward in days: 0) - Partitions for table 'centreon_storage.log_archive_service' are not up to date (current retention forward in days: 0) - Partitions for table 'centreon_storage.log_archive_host' are not up to date (current retention forward in days: 0)

**Comment by ArnoMdlt** [comment]
Hi, How did you solved this ?? Thanks
