### ISSUE TITLE
Massive downtime popup misplaced

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7727]
Hi,

When you set a (hosts or services) massive downtime, the popup is misplaced.
Instead of being in the center of the window (well I assume this is the expected behavior), it is placed with a constant left margin.
Leading to a cropped popup if your window is small enough...

Thank you 👍

Edit : issue still present in 19.04.3.

**Comment by lpinsivy** [comment]
Hi @CPbN which browser do you used? can you add a print screen?

**Comment by CPbN** [comment]
Hi @lpinsivy, well I cleared the browser cache and issue has gone, CSS may have been updated from 19.04.2 to 19.04.3, leading to this...
Sorry for the noise, closing this then...
