### ISSUE TITLE
Import - awie --> File is too large

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon#7743]
Hi,

I try to import my export.zip with awie  but I have this alert : 
"**File is too large (more than 500ko)**"
The file is 852 Ko.

Any suggestions :) ?

I use the _Centreon 2.8.28_ version on my both Centreon (prod/valid).
Thanks

**Comment by wackou72** [comment]
Hello @boogaaloo,
Its look like a php error, look at the php log and conf to increase the max upload size.
Regards

**Comment by boogaaloo** [comment]
Thank you !
Yes, I suspected that, but which file and where ?

**Comment by wackou72** [comment]
If I remember, the php.ini file location is the following :
`/etc/opt/rh/rh-php71/php.ini`
Their is also this location (but not used) :
`/opt/rh/rh-php71/register.content/etc/opt/rh/rh-php71/php.ini`
Edit the file and then look at `upload size`

**Comment by boogaaloo** [comment]
Ok, thank you for your help

**Comment by lpinsivy** [comment]
IF the file is too large, use CLAPI to import your file: https://documentation.centreon.com/docs/centreon/en/19.04/api/clapi/import_export.html

**Comment by boogaaloo** [comment]
Après l'execution de cette commande :
`./centreon -u admin -p centreon -e > /tmp/clapi-export.txt`
j'obtiens cette erreur :
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /usr/share/centreon/lib/Zend/Db/Statement/Pdo.php on line 290`

Merci !
