### ISSUE TITLE
mysql upgrade failed error sql syntax for 

### ISSUE THREAD

**Issue by jeromedevel** [centreon/centreon#7754]
Hello,

the upgrade from 2.8 to 18.10 or 19.04 failed for Mysql 5.7.X or 8

because the syntax  ADD COLUMN **IF NOT EXISTS**  works only under mariaDB

you might use a procedural to test the existing column.

affected fles :
www/install/sql/centreon/Update-DB-19.04.1.sql 
Update-DB-18.10.6.sql
Update-DB-19.04.3.sql

**Comment by kozfelipe** [comment]
https://github.com/centreon/centreon/issues/7722

**Comment by jeromedevel** [comment]
should use this answer to be more compatible :
https://stackoverflow.com/questions/24571611/mysql-alter-table-if-column-not-exists/31989541#31989541
and people will no longer need to edit files manually

**Comment by lpinsivy** [comment]
@jeromedevel we will modify Centreon updates to be compatible with MariaDB and MySQL.

Regards,

**Comment by lpinsivy** [comment]
PR #7760 will correct this

**Comment by sc979** [comment]
hi @jeromedevel ,
If your Centreon is blocked in a broken upgrade process.
reinstall the current centreon package :
`$ rpm -qa | grep centreon-web`
`$ yum reinstall centreon-web<reference from previous command>`
then go to : 
`/usr/share/centreon/www/install` and replace manually the files with whose from the specified PR 7760.
I'll do my best to validate and merge the PR on the next release.
Best Regards
sc979

**Comment by sc979** [comment]
Hi @jeromedevel ,
A fix has been merged on each major version :
18.10.x -> `https://github.com/centreon/centreon/pull/7799`
19.04.x -> `https://github.com/centreon/centreon/pull/7798`
19.10.beta.x -> `https://github.com/centreon/centreon/pull/7801`
All these modifications will be released soon.
If you find a bug or have feedbacks, please re-open this issue
Best Regards
sc979
