### ISSUE TITLE
Configuration > Commands > Plugins : add usage icon

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#777]
---

Author Name: **pierrecdn -** (pierrecdn -)
Original Redmine Issue: 3848, https://forge.centreon.com/issues/3848
Original Date: 2012-10-30

---

This page currently lists the content of $USER1$ directory. 
It could be interesting to display a "usage" icon, showing -h/--help output for users trying to find the best plugin. 

pch

**Comment by julienmathis** [comment]
page removed
