### ISSUE TITLE
[19.04.3] Filter disabled services and pagination

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon#7777]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***

Centreon 19.04.3

***Operating System***

CentOS 7.6

***Browser used***

- [ ] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 68.0.1

***Additional environment details (AWS, VirtualBox, physical, etc.):***

VMware

### Description

Filtering "Disabled" services on "Configuration > Services > Services by host" will work since PR https://github.com/centreon/centreon/pull/7612 but filter will be reset if using pagination.

### Steps to Reproduce

You must have enough disabled services to have pagination.

1. Go to "Configuration > Services > Services by host",
2. Select "Disabled" in the "Status" dropdown list,
3. Click on "Search",
4. Go to page 2.

### Describe the received result

You're on page 2 but without filtering.

### Describe the expected result

Be on page 2 with filtering.

### Logs

None

### Additional relevant information (e.g. frequency, ...)

Same behaviour with "Enabled" filter.

**Comment by loiclau** [comment]
#7755

**Comment by lpinsivy** [comment]
should be corrected
