### ISSUE TITLE
Poller (Monitoring Engine) status update/errors/export issues

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#78]
---

Author Name: **Lang Stephan** (Lang Stephan)
Original Redmine Issue: 5434, https://forge.centreon.com/issues/5434
Original Date: 2014-04-01

---

Hi, i've done some testing with additional pollers...
as long as the 2nd Poller is online everything is fine... if the poller is offline (shutdown, or network disconnected,etc) the status on the centreon web doesn't update any more... 

eventhough there is no warning or error message
i can still move/export files and restart monitoring engine on remote poller... log says everything fine, couldn't be true, because node is offline and has no connection any more... of course settings didn't get updated at all or new data comes in...

this means all host/services status information is frozen in it's state of last check status! but for my guess all the hosts and services should get critical really, i'm aware that this could not happen because the poller is down... but centreon web has to check this and reports it somehow!

even under configuration/centreon the "is running?" und the 2nd Poller stays on YES, this and the last start-time or last update time clears on an purge of the NDO database (NDO Tools)...

also i tried to catch this state with a host (on default poller) with the remote ip, not 127.0.0.1.... hosts check is critical... but it is not possible to add host dependencys to the 2nd poller hosts/services because after saving the relations/parent hosts following message appears: "Some hosts parent has not the same instance"

**Comment by ganoze** [comment]
As of now, NDO is not supported anymore.

Centreon Broker properly reports broken poller links.
