### ISSUE TITLE
Central poller and central database Red but ok and no information from poller

### ISSUE THREAD

**Issue by markeur** [centreon/centreon#7802]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
centreon-perl-libs-19.04.3-6.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190704-123459.el7.centos.noarch
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-release-19.04-1.el7.centos.noarch
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-19.04.3-6.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190704-123459.el7.centos.noarch
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-engine-19.04.1-9.el7.centos.x86_64
centreon-license-manager-19.04.0-1.el7.centos.noarch
centreon-base-config-centreon-engine-19.04.3-6.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190704-123459.el7.centos.noarch
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-engine-extcommands-19.04.1-9.el7.centos.x86_64
centreon-web-19.04.3-6.el7.centos.noarch
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190704-123459.el7.centos.noarch
centreon-trap-19.04.3-6.el7.centos.noarch
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190704-123459.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190704-123459.el7.centos.noarch
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-database-19.04.3-6.el7.centos.noarch
centreon-common-19.04.3-6.el7.centos.noarch
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-engine-daemon-19.04.1-9.el7.centos.x86_64
centreon-poller-centreon-engine-19.04.3-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190704-123459.el7.centos.noarch
```
rating System***

*CentOS 7*

***Browser used***

- [x] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***
AWS & Hyper-V
### Description

-- Describe the encountered issue --

Central reporting poller down & Poller has yellow issues based on Last Update time. Moreover other poller are working (if I look in log file) but not data are show by the central server.

Looks like a database issue but not sure, mysql service is running and ok.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. Centreon reporting RED as Pollers not running and no Hosts or Services
3. Under Configuration -> Pollers -> the poller has a yellow alert on Last Update Time

### Describe the received result
Poller last update is yellow warning and has incorrect date, no host or services are monitored (should have 50 hosts and 200 services)

### Describe the expected result
Poller work and hosts/services monitored

### Additional relevant information (e.g. frequency, ...)
Some 'queue' file (ls -lah /var/lib/centreon-broker | grep queue) : 
central-broker-master.queue.central-broker-master-sql
No error message in centengine.log file and connection was working few minutes before.

EDIT : When I checked log file this morning I discovered that : 

 ```$ sudo tail -f /var/log/centreon/centcore.log
2019-08-26 14:42:16 - ERROR - MySQL error: MySQL server has gone away (caller: centreon::script::centcore:/usr/share/perl5/vendor_perl/centreon/script/centcore.pm:1094)
Query: SELECT * FROM options WHERE `key` IN ('enable_perfdata_sync', 'enable_logs_sync', 'centcore_cmd_timeout', 'enable_broker_stats', 'centcore_illegal_characters')

Authorized uses only. All activity may be monitored and reported.
Redirecting to /bin/systemctl restart centengine.service
2019-08-27 01:28:46 - ERROR - MySQL error : cannot connect to database centreon: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "No such file or directory") (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:268)
2019-08-27 01:28:46 - ERROR - MySQL error : cannot connect to database centreon: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "No such file or directory") (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:268)
2019-08-27 01:28:46 - ERROR - MySQL error : cannot connect to database centreon: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "No such file or directory") (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:268)
2019-08-27 01:28:46 - ERROR - MySQL error : cannot connect to database centreon: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2 "No such file or directory") (caller: centreon::common::db:/usr/share/perl5/vendor_perl/centreon/common/db.pm:268)
2019-08-27 01:28:46 - ERROR - Error when getting server properties```

**Comment by tanguyvda** [comment]
it looks like you have an issue with your broker on your central. You may have a misconfiguration there. Head over the configuration -> pollers -> broker configuration menu. Click on the central-broker-master configuration .

from there, go to the output tab
![image](https://user-images.githubusercontent.com/7352865/64026545-43a86b80-cb3f-11e9-9775-811ac80ae6a7.png)


you should have at least one ouput called 
Broker SQL database 
and another one called 
Perfdata Generator (Centreon Storage)

check in both of them if the IP address, database user and user password are good. If not, change them.

when done, export your configuration on you central server and write the following command in your shell : 

service cbd restart

you also have a misconfiguration of centcore, so head over the /etc/centreon/conf.pm file and change the database server address, user and password. Since your web interface is working, you'll find those information in the /etc/centreon/centreon.conf.php file

you'll have to restart centcore if you've done a change in the conf.pm file

service centcore restart

when done, you should no longer see  this message in the /var/log/centreon/centcore.log file and the /var/log/centreon-broker/broker-master.log file should be free of any mysql connection issue
