### ISSUE TITLE
Cannot set downtimes, schedule checks on remote poller

### ISSUE THREAD

**Issue by elmarsievers** [centreon/centreon#7809]
***Versions***
Central:
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.04.0-5.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190704-123459.el7.centos.noarch
centreon-poller-centreon-engine-19.04.3-6.el7.centos.noarch
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-widget-tactical-overview-19.04.0-7.el7.centos.noarch
centreon-engine-extcommands-19.04.1-9.el7.centos.x86_64
centreon-trap-19.04.3-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190704-123459.el7.centos.noarch
centreon-widget-host-monitoring-19.04.1-1.el7.centos.noarch
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-widget-engine-status-19.04.0-5.el7.centos.noarch
centreon-engine-daemon-19.04.1-9.el7.centos.x86_64
centreon-engine-19.04.1-9.el7.centos.x86_64
centreon-plugin-Operatingsystems-Linux-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190704-123459.el7.centos.noarch
centreon-base-config-centreon-engine-19.04.3-6.el7.centos.noarch
centreon-release-19.04-1.el7.centos.noarch
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-license-manager-19.04.0-1.el7.centos.noarch
centreon-widget-grid-map-19.04.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-19.04.0-5.el7.centos.noarch
centreon-common-19.04.3-6.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190704-123459.el7.centos.noarch
centreon-19.04.3-6.el7.centos.noarch
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-widget-live-top10-cpu-usage-19.04.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.04.0-7.el7.centos.noarch
centreon-perl-libs-19.04.3-6.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190704-123459.el7.centos.noarch
centreon-widget-service-monitoring-19.04.1-1.el7.centos.noarch
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-widget-live-top10-memory-usage-19.04.0-5.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190704-123459.el7.centos.noarch
centreon-database-19.04.3-6.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190704-123459.el7.centos.noarch
centreon-web-19.04.3-6.el7.centos.noarch

Poller:
centreon-database-19.04.3-6.el7.centos.noarch
centreon-release-19.04-1.el7.centos.noarch
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-engine-daemon-19.04.1-9.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190704-123459.el7.centos.noarch
centreon-base-config-centreon-engine-19.04.3-6.el7.centos.noarch
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-engine-extcommands-19.04.1-9.el7.centos.x86_64
centreon-perl-libs-19.04.3-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190704-123459.el7.centos.noarch
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-common-19.04.3-6.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190704-123459.el7.centos.noarch
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-license-manager-19.04.0-1.el7.centos.noarch
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-poller-centreon-engine-19.04.3-6.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190704-123459.el7.centos.noarch
centreon-web-19.04.3-6.el7.centos.noarch
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-engine-19.04.1-9.el7.centos.x86_64
centreon-trap-19.04.3-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190704-123459.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190704-123459.el7.centos.noarch

***Operating System***
CentOS Linux release 7.6.1810 (Core)

***Browser used***
Firefox
Version: 68.0.1esr (64-Bit)

***Additional environment details (AWS, VirtualBox, physical, etc.):***
VMware ESXi 6.7 VMs

### Description

Cannot set downtimes, or schedule checks on remote poller. If I do it directly from poller web interface it works. You can reproduce this anytime. on central server there is no problem to set downtimes.

**PHP error logs**
Only on Central Server but seems to be not related:
[28-Aug-2019 11:14:54 Europe/Berlin] PHP Warning:  Illegal string offset 'label' in /usr/share/centreon/GPL_LIB/SmartyCache/compile/%%D3^D37^D378FF30%%formServers.ihtml.php on line 51

**centcore logs**

Everytime we try to set downtimes we get this error:
2019-08-28 12:22:10 - ERROR - Could not write into pipe file /var/lib/centreon-engine/rw/centengine.cmd on poller 6

**Comment by tanguyvda** [comment]
could you please provide us the result of the following command on your poller : 

ls -lah /var/lib/centreon-engine/rw/

**Comment by elmarsievers** [comment]
Central Server:
total 0
drwxrwxr-x. 2 centreon-engine centreon-engine  28 Aug 28 11:46 .
drwxr-xr-x. 5 centreon-engine centreon-engine 145 Aug 30 22:34 ..
prw-rw----  1 centreon-engine centreon-engine   0 Aug 30 09:42 centengine.cmd

Satellite:
total 0
drwxrwxr-x. 2 centreon-engine centreon-engine  28 Aug 28 12:06 .
drwxr-xr-x. 4 centreon-engine centreon-engine 120 Aug 30 09:42 ..
prw-rw----  1 centreon-engine centreon-engine   0 Aug 29 07:08 centengine.cmd

**Comment by kitatek** [comment]
The downtime and acknowledgement  problem existed before on pollers and was fixed by fixing the timezone on the poller, among other fixes.

Workarounds/patches here may be useful:
https://github.com/centreon/centreon/issues/3331
http://www.sugarbug.fr/blog/files/category-techniques.html (in French)

**Comment by elmarsievers** [comment]
hi,

solved by contacting sul.de.

ssh connect to remote system tries to resolve ip address to hostname per default.

that needs too much time (15 seconds) because there was no pointer record in dns.

switched off ssh dns and after a reboot system works again.

kind regards
elmar
