### ISSUE TITLE
Hostgroups URLs aren't used

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon#7812]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***
Centreon Web 19.04 and 18.10 and maybe olders versions.

### Description

We can add URLs (Note and Action) in the configuration page of a hostgroup but they are never used in Centreon monitoring.

### Steps to Reproduce

1. I lcreate an hostgroup and add an action URL
2. I generate and export the configuration

### Describe the received result

I can't used this URL because I can't find it.

### Describe the expected result

It could be nice to delete those fields.

**Comment by lpinsivy** [comment]
Hi @s-duret you can use the following macros:
* HOSTGROUPNOTES$
* $HOSTGROUPNOTESURL$
* $HOSTGROUPACTIONURL$

For check, notification, OCSP & OHSP commands
