### ISSUE TITLE
plugin database::mssql::plugin error

### ISSUE THREAD

**Issue by pia-chalavan** [centreon/centreon#7824]
Hello, 
I am trying to use the plugin "database::mssql::plugin" but i always have the same error:

> CRITICAL: Cannot connect: OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (44)
Server , database
Message String: Server name not found in configuration files.
OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (45)
Server , database
Message String: Unknown host machine name. |

i using the Centreon el7 ISO
version: 18.10.6

thx for your help!

**Comment by lpinsivy** [comment]
Hi @pia-chalavan what is the definition of your command?

**Comment by garnier-quentin** [comment]
You can open it in centreon-plugins github if you still have the issue.
