### ISSUE TITLE
mysqld high cpu usage

### ISSUE THREAD

**Issue by wackou72** [centreon/centreon#7837]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
centreon-widget-live-top10-memory-usage-19.04.0-5.el7.centos.noarch
centreon-widget-global-health-19.04.0-5.el7.centos.noarch
centreon-common-19.04.3-6.el7.centos.noarch
centreon-database-19.04.3-6.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190704-123459.el7.centos.noarch
centreon-web-19.04.3-6.el7.centos.noarch
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-engine-19.04.1-9.el7.centos.x86_64
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190704-123459.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190704-123459.el7.centos.noarch
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-widget-servicegroup-monitoring-19.04.0-7.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190704-123459.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190704-123459.el7.centos.noarch
centreon-19.04.3-6.el7.centos.noarch
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-plugins-base-1.18-2.el7.centos.noarch
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.04.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.04.0-5.el7.centos.noarch
centreon-trap-19.04.3-6.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190704-123459.el7.centos.noarch
centreon-poller-centreon-engine-19.04.3-6.el7.centos.noarch
centreon-widget-service-monitoring-19.04.1-1.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20190704-123459.el7.centos.noarch
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-widget-graph-monitoring-19.04.0-5.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190704-123459.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190704-123459.el7.centos.noarch
centreon-widget-host-monitoring-19.04.1-1.el7.centos.noarch
centreon-plugin-Virtualization-VMWare-daemon-3.0.3-20190704131142.el7.centos.noarch
centreon-release-19.04-1.el7.centos.noarch
centreon-engine-daemon-19.04.1-9.el7.centos.x86_64
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-widget-engine-status-19.04.0-5.el7.centos.noarch
centreon-widget-tactical-overview-19.04.0-7.el7.centos.noarch
centreon-widget-httploader-19.04.0-5.el7.centos.noarch
centreon-perl-libs-19.04.3-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190704-123459.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190704-123459.el7.centos.noarch
centreon-base-config-centreon-engine-19.04.3-6.el7.centos.noarch
centreon-widget-grid-map-19.04.0-5.el7.centos.noarch
centreon-engine-extcommands-19.04.1-9.el7.centos.x86_64
centreon-license-manager-19.04.0-1.el7.centos.noarch
```

***Operating System***

CentOS Linux release 7.6.1810 (Core)

***Browser used***

- [ ] Google Chrome
- [X ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 19.04.3

***Additional environment details (AWS, VirtualBox, physical, etc.):***

VM (ESXi)

### Description

Hello,
I have a strange issue since 3 days.
At exactly 4:57 AM, nothing is update on the Centreon Web Interface.
![Status when arriving](https://user-images.githubusercontent.com/21340779/64324640-fe64bd80-cfc6-11e9-84d2-576705103a50.png)
For all my distant Poller and Central.

I check on the Central and the mysqld daemon is at 100%
I made a quick check on the Maria DB.
![MariaDB Connections](https://user-images.githubusercontent.com/21340779/64324638-fdcc2700-cfc6-11e9-9dd4-741b7fd795aa.png)
![MariaDB Process List](https://user-images.githubusercontent.com/21340779/64324639-fdcc2700-cfc6-11e9-8dcb-6e85dadbaff8.png)

And suddently, without doing nothing, all the data came to the Central, at around 8:10 AM
![Centreon](https://user-images.githubusercontent.com/21340779/64324637-fdcc2700-cfc6-11e9-9ee2-17c43bd2ba2e.gif)

This error has been seen since last tuesday, without understand the root cause.

I check the history of the CPU usage, and it their is always a highter CPU usage between 2:00 AM and 7:00 AM.
![CPU History](https://user-images.githubusercontent.com/21340779/64324641-fe64bd80-cfc6-11e9-9508-b97e74d7ed06.png)

**Comment by wackou72** [comment]
Hello,
the problem appear once again this morning.
![2019-09-06 07_54_11-Centreon - IT   Network Monitoring](https://user-images.githubusercontent.com/21340779/64404248-991ed400-d07b-11e9-82df-8b58f9b2f744.png)

**Comment by pkriko** [comment]
Hello @wackou72,

Have you enable the backup of Centreon ?

Can you show the configuration of the backup (Administration  >  Parameters  >  Backup) and the page Databases (Administration  >  Platform Status  >  Databases).

Regards,

**Comment by wackou72** [comment]
Hello @pkriko,
the issue was due to this command :
`0 2 * * * centreon /opt/rh/rh-php71/root/usr/bin/php /usr/share/centreon/cron/centstorage_purge.php >> /var/log/centreon/centreon-purge.log 2>&1`

Looking at `/var/log/centreon/centreon-purge.log` it show the following :
`Error : Cannot purge data_bin, SQLSTATE[HY000]: General error: 1206 The total number of locks exceeds the lock table size`

So this is due to lack of ressource for the MariaDB (nothing written about this in the documentation ...)
You need to edit the following file :
`/etc/my.cnf.d/centreon.cnf`
and unable the following (or tune depending on the RAM) :
`# For 8 Go Ram
innodb_additional_mem_pool_size=1G
innodb_buffer_pool_size=1G
`

Issue is now solved, PURGE take around 10 minutes now.

Regards
