### ISSUE TITLE
Centreon 19.04 : alternative for Centreon syslog logs

### ISSUE THREAD

**Issue by mat3731** [centreon/centreon#7848]
Hi,

The Centreon documentation explains that the syslog module is obsolete and not compatible with Centreon >= 2.7.x.

Did someone know an alternative to display sylog logs into Centreon MMI (e.g Centreon 19.04) ?

Thanks in advance for your answers

**Comment by lpinsivy** [comment]
Hi @mat3731,

Sorry Centreon doesn't have alternative. Yo ucan store your logs into elasticsearch, etc. and use Centreon Plugins to generate alerts in Centreon UI based on specific search
