### ISSUE TITLE
Services and hosts not showing up in Chrome HTTPS but work in Firefox

### ISSUE THREAD

**Issue by abuissonnet** [centreon/centreon#7857]
Hello, we tried to bring our centreon server to AWS. 

We have 2 servers (sql -mysql + web/core -centos rhl7) running, and we set up an Application Load balancer at the front.

We made changes for https as required by documentation : https://documentation.centreon.com/docs/centreon/en/19.04/administration_guide/ui_access.html

When loading the centreon web on Firefox v69.0, everything works like a charm. URL gets redirected to https as intended, log on, services and hosts, parameters, everything works.

When loading the exact same thing on Chrome (tested on v76 or v77), URL gets redirected to https as intended too, log in success, everything seems OK in the top-status bar, (black border), but nothing shows up as services/hosts. Parameters can be accessed and changed.

If we cut the HTTPS part and bring it back to HTTP mode, both Chrome and Firefox work like a charm. 

Anything I missed ?

![issue_https_centreon](https://user-images.githubusercontent.com/30560583/65230700-9c2fb080-dace-11e9-969e-2d53e03bbaf9.png)

**Comment by pkriko** [comment]
Hello @abuissonnet,

Can you tell me which load balancer do you use ? Elastic from AWS, nginx, etc.

The SSL connection is configured on the Central Server ? The load balancer only forwards the package, no SSL from the load balancer ?

Kriko.

**Comment by abuissonnet** [comment]
Hello @pkriko thank you for your time.

We are using Elasting from AWS with 2 listeners (and it's own certificate as it is how it works on aws); 2 listeners : HTTP 80  redirect to 443; and HTTP 443 redirect to the target group (where is attached the ec2 instance).

SSL connection is configured on central server and certs are used as described in the documentation. 

When you create an ALB on AWS you need an aws certificate that will be used to authenticate the ALB, then you just set the DNS of the ALB as a CNAME pointer to your web server. 

I think then there is SSL for the website itself with the certificate provided in the virtualhost, and another SSL for the loadbalancer at the frontend delivered by amazon. 

(But I'm pretty new with AWS things so I maybe misleading there)

**Comment by abuissonnet** [comment]
Any updates on this ?

**Comment by pkriko** [comment]
Hello @abuissonnet 

I'm clearly not a AWS expert, but your issue seems to be related to 
https://github.com/centreon/centreon/issues/6337

But the fix proposed works.

I don't why there is a different behavior between Firefox and Chrome on the xsltRequest.statusText variables.

I need more time to investigate :)

**Comment by pkriko** [comment]
@abuissonnet Can you check is your load balancer doesn't use HTTP/2 ?
 
When I disable HTTP/2 on my load balancer, everything looks good. Check this thread to have more informations : https://stackoverflow.com/questions/41632077/why-is-the-statustext-of-my-xhr-empty

Regards,

**Comment by abuissonnet** [comment]
@pkriko , good point http/2 was enabled for the LoadBalancer on AWS. Sadly it didn't work when disabling it. 

However, using the #6337 I did the same thing and removed the "OK" part in the file and this is now working properly in chrome.

Thanks for your help, really appreciated it.
