### ISSUE TITLE
Linux Memory with negative percentage

### ISSUE THREAD

**Issue by florianncy** [centreon/centreon#7867]
# BUG REPORT INFORMATION

***Versions***
$ rpm -qa | grep centreon :
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190704-123459.el7.centos.noarch
centreon-dsm-server-19.04.0-1.el7.centos.noarch
centreon-database-19.04.4-6.el7.centos.noarch
centreon-release-19.04-1.el7.centos.noarch
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-widget-engine-status-19.04.0-5.el7.centos.noarch
centreon-widget-global-health-19.04.0-5.el7.centos.noarch
centreon-engine-extcommands-19.04.1-9.el7.centos.x86_64
centreon-plugin-Network-Cisco-Standard-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-X509-20190704-123459.el7.centos.noarch
centreon-perl-libs-19.04.4-6.el7.centos.noarch
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-widget-live-top10-memory-usage-19.04.0-5.el7.centos.noarch
centreon-engine-daemon-19.04.1-9.el7.centos.x86_64
centreon-plugin-Hardware-Storage-Synology-Snmp-20190704-123459.el7.centos.noarch
centreon-common-19.04.4-6.el7.centos.noarch
centreon-web-19.04.4-6.el7.centos.noarch
centreon-widget-service-monitoring-19.04.2-1.el7.centos.noarch
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-plugin-Operatingsystems-Linux-Snmp-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190704-123459.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190704-123459.el7.centos.noarch
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-widget-tactical-overview-19.04.0-7.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.04.0-5.el7.centos.noarch
centreon-widget-host-monitoring-19.04.1-1.el7.centos.noarch
centreon-dsm-19.04.0-1.el7.centos.noarch
centreon-poller-centreon-engine-19.04.4-6.el7.centos.noarch
centreon-19.04.4-6.el7.centos.noarch
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190704-123459.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190704-123459.el7.centos.noarch
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-license-manager-19.04.0-1.el7.centos.noarch
centreon-widget-grid-map-19.04.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.04.0-7.el7.centos.noarch
centreon-widget-graph-monitoring-19.04.0-5.el7.centos.noarch
centreon-engine-19.04.1-9.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Http-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190704-123459.el7.centos.noarch
centreon-trap-19.04.4-6.el7.centos.noarch
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-widget-live-top10-cpu-usage-19.04.0-5.el7.centos.noarch
centreon-widget-httploader-19.04.0-5.el7.centos.noarch
centreon-nrpe-plugin-2.15-4.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Central-20190704-123459.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190704-123459.el7.centos.noarch
centreon-dsm-client-19.04.0-1.el7.centos.noarch
centreon-base-config-centreon-engine-19.04.4-6.el7.centos.noarch
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-awie-19.04.0-1.el7.centos.noarch

***Operating System***
# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

### Description

Hi,
Since a recent update of my central (poller included), the control of the memory displays negative values in percentage.

### Steps to Reproduce

# ./centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=127.0.0.1 --snmp-version='2c' --snmp-community='public' --ignore-warn-msg

### Received result

OK: Ram Total: 3.56 GB Used (-buffers/cache): -203.45 MB (-5.58%) Free: 3.76 GB (105.58%), Buffer: 2.06 MB, Cached: 751.60 MB, Shared: 8.58 MB | 'used'=-213327872B;;;0;3826249728 'free'=4039577600B;;;0;3826249728 'used_prct'=-5.58%;;;0;100 'buffer'=2158592B;;;0; 'cached'=788111360B;;;0; 'shared'=8994816B;;;0;

**Comment by florianncy** [comment]
Thank you for your reply.
I have a lot of mysql process. When I kill 1 PID, all the processes is killing itself.
Even if there is no more mysql process, I still have negative values ​​for the memory :

OK: Ram Total: 3.56 GB Used (-buffers/cache): -2.27 GB (-63.71%) Free: 5.83 GB (163.71%),[...]

Can you help me ?

**Comment by cgagnaire** [comment]
Hi,
See above referenced issue.
