### ISSUE TITLE
Error Connection Ldap Server

### ISSUE THREAD

**Issue by CuentaAxion** [centreon/centreon#7868]
Hello,I have Ldap authentication configured and when I want to import users into Ldap they don't appear to me, I take a screenshot of my configuration
![image](https://user-images.githubusercontent.com/49510710/65492854-fa370c00-deb1-11e9-872b-e71ec1b96729.png)
![image](https://user-images.githubusercontent.com/49510710/65492891-09b65500-deb2-11e9-9e72-ddefe7ce0623.png)
![image](https://user-images.githubusercontent.com/49510710/65492942-205cac00-deb2-11e9-9475-82e9120a8ee8.png)

And now when I access users nothing appears to me ....
![image](https://user-images.githubusercontent.com/49510710/65493030-500bb400-deb2-11e9-923b-15755a10102a.png)

I don't know if it's because of my server because the machines ping between them and create a user inside my ldap server and it works correctly ...

**Comment by pkriko** [comment]
Hello @CuentaAxion,

Are you sure that your Active Directory use SSL or TLS ?
Have you tried with the port 636, the port used by LDAPS ?

Regards,

**Comment by CuentaAxion** [comment]
this is the ports to listen to the ldap server and none appears with port 636...
![image](https://user-images.githubusercontent.com/49510710/65674247-8846fa00-e04c-11e9-92c4-46a9c3a9dccb.png)

**Comment by pkriko** [comment]
Ok ok.
And you use SSL or TLS on your ldap server ?
I see an openldap server, maybe you need to use the POSIX template in your LDAP configuration.

Also if you want to check the connection between Centreon and your LDAP Service, you can try something like this :
ldapsearch -h <IP ldap server> -p <port> -D "<distinguished name of ldap service account>" -W -b "<ldap OU to browse>" "(cn=*)"

Regards,

**Comment by pkriko** [comment]
You need to run it on your Centreon server.

If the command is working it's mean that you don't need to check SSL/TLS on the LDAP server parameters. If it's not, you must check the bind user.

```
[root@central ~]# ldapsearch -h 192.168.0.50 -vvv -p 389 -D "cn=admin,dc=alamenthe,dc=fr" -W -b "dc=alamenthe,dc=fr" "(ObjectClass=*)"
ldap_initialize( ldap://192.168.0.50:389 )
Enter LDAP Password:
filter: (ObjectClass=*)                
requesting: All userApplication attributes         
# extended LDIF                            
#            
# LDAPv3                
# base <dc=alamenthe,dc=fr> with scope subtree
# filter: (ObjectClass=*)
# requesting: ALL
#

# alamenthe.fr
dn: dc=alamenthe,dc=fr
objectClass: top
objectClass: dcObject
objectClass: organization
o: Alamenthe
dc: alamenthe
```

**Comment by CuentaAxion** [comment]
Hello, I show you the bug that throws me when inserting the command you asked me ..
![image](https://user-images.githubusercontent.com/49510710/65860811-4e873380-e36b-11e9-9d03-0dce4a50b3dd.png)

the LDAP server is on another machine with a ubuntu system installed and ping between the machines

**Comment by pkriko** [comment]
Can you install the following package to use ldapsearch : 
```
yum install -y openldap-client
```
