### ISSUE TITLE
CENTREON - The centengine service of the poller does not recharge (reload / restart)

### ISSUE THREAD

**Issue by IdrissaHilda** [centreon/centreon#7915]
# BUG REPORT INFORMATION

***Versions***
19.04
For the RPM based systems
using packages for the installation of centreon

$ rpm -qa | grep centreon

centreon-plugin-Operatingsystems-Linux-Snmp-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20191002-125310.el7.centos.noarch
centreon-broker-core-19.04.0-2.el7.centos.x86_64
centreon-engine-extcommands-19.04.1-9.el7.centos.x86_64
centreon-web-19.04.4-6.el7.centos.noarch
centreon-base-config-centreon-engine-19.04.4-6.el7.centos.noarch
centreon-connector-ssh-19.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ftp-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191002-125310.el7.centos.noarch
centreon-release-19.04-1.el7.centos.noarch
centreon-common-19.04.4-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20191002-125310.el7.centos.noarch
centreon-connector-perl-19.04.0-2.el7.centos.x86_64
centreon-plugin-Network-Cisco-Standard-Snmp-20191002-125310.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191002-125310.el7.centos.noarch
centreon-trap-19.04.4-6.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20191002-125310.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191002-125310.el7.centos.noarch
centreon-broker-19.04.0-2.el7.centos.x86_64
centreon-broker-storage-19.04.0-2.el7.centos.x86_64
centreon-engine-daemon-19.04.1-9.el7.centos.x86_64
centreon-engine-19.04.1-9.el7.centos.x86_64
centreon-poller-centreon-engine-19.04.4-6.el7.centos.noarch
centreon-license-manager-19.04.0-1.el7.centos.noarch
centreon-auto-discovery-server-19.04.0-4.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Http-20191002-125310.el7.centos.noarch
centreon-clib-19.04.0-1.el7.centos.x86_64
centreon-broker-cbd-19.04.0-2.el7.centos.x86_64
centreon-broker-cbmod-19.04.0-2.el7.centos.x86_64
centreon-pp-manager-19.04.0-3.el7.centos.noarch
centreon-connector-19.04.0-2.el7.centos.x86_64
centreon-plugin-Hardware-Printers-Generic-Snmp-20191002-125310.el7.centos.noarch
centreon-license-manager-common-19.04.0-1.el7.centos.noarch
centreon-perl-libs-19.04.4-6.el7.centos.noarch

***Operating System***
CentOS7

***Additional environment details :***
Virtual Machine
### Description

When I want to reload or restart the collector with centreon interfaces, the application display that is properly carried out but the service CENTENGINE has not restart or reload.

![image](https://user-images.githubusercontent.com/56160040/66208538-8f59b200-e6b5-11e9-8369-b3af0570d846.png)

It should be restart with a shell command 
example: _systemctl restart centengine_
### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I connect with centreon login
2. I executed the command
> service centengine reload
the result:
![image](https://user-images.githubusercontent.com/56160040/66209611-0132fb00-e6b8-11e9-9e29-aae5ca2898b3.png)

or

> sudo service centengine reload
this command with sudo operates

![image](https://user-images.githubusercontent.com/56160040/66209752-5b33c080-e6b8-11e9-8c7f-bb1c2ff816a1.png)

3. I added this rules in /etc/sudoers

# Command Centengine
Cmnd_Alias CENTENGINE_RESTART = /sbin/service centengine restart
Cmnd_Alias CENTENGINE_RELOAD = /sbin/service centengine reload

# Command without password
centreon ALL=NOPASSWD: CENTENGINE_RESTART, CENTENGINE_RELOAD

**Comment by IdrissaHilda** [comment]
**The solution :** 

To resolve the problem, I modify the file `/usr/share/centreon/www/include/configuration/configGenerate/xml/restartPollers.php`

I changed the command ` service ` by `systemctl `command like you can see with the captures

 Before the change, we have the command framed in red: 

![image](https://user-images.githubusercontent.com/56160040/66484395-30c27880-eaa7-11e9-9c2b-685235d9cf1b.png)

You should modify the command for reload and restart, after modification we have:

![image](https://user-images.githubusercontent.com/56160040/66484413-3a4be080-eaa7-11e9-89b7-18aead331988.png)

![image](https://user-images.githubusercontent.com/56160040/66484424-4041c180-eaa7-11e9-9632-5e454f9ce856.png)

**Comment by lpinsivy** [comment]
Hi,

From Centreon 19.10 you can redefine these command from Centreon UI for each poller.

<img width="976" alt="Sans titre" src="https://user-images.githubusercontent.com/3351916/70527432-36dae100-1b4c-11ea-9e6a-b70e18c605fe.png">

Regards,
