### ISSUE TITLE
[Security] Privilege escalation from cron tab.

### ISSUE THREAD

**Issue by TheCyberGeek** [centreon/centreon#7921]
# Incorrect User Executing **/etc/cron.d/centreon-auto-disco**
/usr/share/centreon/www/modules/centreon-autodiscovery-server//cron/centreon_autodisco is owned by apache and executed by root every 24 hours at 22:30PM when centreon should be the owner of the file and cron executed by centreon as according to your manuals:

```
#####################################
# Centreon Auto Discovery
#
30 22 * * * centreon /usr/share/centreon/www/modules/centreon-autodiscovery-server//cron/centreon_autodisco --config=’/etc/centreon/conf.pm’ --config-extra=’/etc/centreon/centreon_autodisco.pm’ --severity=error >> /var/log/centreon/centreon_auto_discovery.log 2>&1
```

## Description
The cron /etc/cron.d/centreon-auto-disco is being executed as root and owned by apache in all OVF/OVA applications.

**Fixes** # (issue)
**/etc/cron.d/centreon-auto-disco** - Change user of execution to Centreon
**/usr/share/centreon/www/modules/centreon-autodiscovery-server//cron/centreon_autodisco** - Change owner of the file to Centreon.

## Type of change

- [x] Patch fixing an issue (non-breaking change)

## Target series

- [x] 18.10-9.ova/ovf
- [x] 19.04.2.ova/ovf

<h2> How this issue can be tested ? </h2>

Launch OVA/OVFs, sign in as root, 
```
cat /etc/cron.d/centreon-auto-disco 

Which will print the user who executes the cron and cron settings.
``` 
For the second stage:
```
ls -la /usr/share/centreon/www/modules/centreon-autodiscovery-server//cron/centreon_autodisco

This will show you apache owns the file.
```

Any **relevant details**:
Already discussed with yourselves.

**Comment by cgagnaire** [comment]
Fixed since Centreon Autodiscovery 18.10.8 and 19.10.4.
