### ISSUE TITLE
Cannot set downtime by Poller

### ISSUE THREAD

**Issue by pkriko** [centreon/centreon#7933]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
centreon-web-19.04.4

***Operating System***

*CentOS, Debian ...*
CentOS 7

***Browser used***

- [X] Google Chrome
- [X] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Log in Centreon
2. Go to Monitoring > Downtimes > Add downtime
3. Try to set a downtime on a Poller

### Describe the received result
![image](https://user-images.githubusercontent.com/32265250/66399784-83852d00-e9e0-11e9-991c-46870f2d592b.png)

### Describe the expected result
![image](https://user-images.githubusercontent.com/32265250/66399828-939d0c80-e9e0-11e9-8280-57175debac9e.png)

### Additional relevant information (e.g. frequency, ...) 
This bug is present on the demo, and on the 18.10 version. Not on a 2.8.x version.

**Comment by BenoitPoulet** [comment]
Présent aussi sur la branche 19.10

**Comment by lpinsivy** [comment]
Corrected by #7955
