### ISSUE TITLE
[BUG] Centreon - Engine Configuration - Blank Page

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#7942]
# BUG REPORT INFORMATION
***Versions***
Centreon 18.10.x
CentOS 7

### Description
A blank page appears when you want to save the configuration in "Configuration > Pollers > Engine Configuration".

### Steps to Reproduce
1. I logged in Centreon 18.10.x (reproduced on 18.10.7 and 18.10.8)
2. Go in Configuration > Pollers > Engine Configuration
3. Open a configuration
4. Change name (for example) and save
5. -> Blank Page

or 

1. I logged in Centreon 18.10.x (reproduced on 18.10.7 and 18.10.8)
2. Go in Configuration > Pollers > Engine Configuration
3. Duplicate a configuration
4. Open new configuration
5. Change "linked poller" option (for example) and save
6. -> Blank Page

### Describe the received result
A blank page appears and nothing is saved.

Regards

**Comment by bernah4** [comment]
Some nice effect maybe it could help :)
![image](https://user-images.githubusercontent.com/46378129/66817132-82518400-ef3b-11e9-936a-a5def79193f4.png)

**Comment by bernah4** [comment]
I get this maybe it could helps finding some clues
![Capture2](https://user-images.githubusercontent.com/46378129/66817452-fab84500-ef3b-11e9-86c0-26c246fa6f78.PNG)

**Comment by joschi99** [comment]
Same issue here on Centreon 18.10.7. We are not able to save centreon engine configuration.

**Comment by lpinsivy** [comment]
Hi, can you check /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log log file?

**Comment by joschi99** [comment]
We have done upgrade to 18.10.8 and seem's working, but status of Centreon Engine will not more displayed:

![image](https://user-images.githubusercontent.com/6400595/70529490-f9c51d80-1b50-11ea-9caa-924f0b8220b8.png)

![image](https://user-images.githubusercontent.com/6400595/70529499-fdf13b00-1b50-11ea-8faa-9f2c9099b0da.png)

**Comment by lpinsivy** [comment]
Hi @joschi99 ,

If you enable or disable and save the form and reopen it. The option appears?

**Comment by rmorandell-pgum** [comment]
Hi @lpinsivy

saving the configuration changes the value and when i reopen it the value appears.
