### ISSUE TITLE
RemotePoller statistics no more available

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#7948]
Hi,

### On a Remote Server :

In _Administration / Platform status / Broker Statistics_, there are no statistics at all.

![Screen Shot 2019-11-21 at 19 03 50](https://user-images.githubusercontent.com/40244829/69364164-1d075600-0c92-11ea-9988-09341f0060ab.png)

Some more debug [below](https://github.com/centreon/centreon/issues/7948#issuecomment-589533193).

~As well, in _Administration / Platform status / Engine Statistics_, there are no statistics at all (fixed in 19.10.2).~

### On a Central server :

~Remote broker statistics are available (after having enabled "Enable Broker Statistics Collection" option in _Administration  /  Parameters  /  CentCore_). Perfect. However, remote engine statistics are not available (fixed in 19.10.2).~

Thank you 👍

Edit : issue still present in 19.10.10.

**Comment by CPbN** [comment]
And from the Central server :

Remote broker statistics are available (after having enabled "Enable Broker Statistics Collection" option in _Administration  /  Parameters  /  CentCore_). Perfect.

However, remote engine statistics are not available.

**Comment by cgagnaire** [comment]
Related to https://github.com/centreon/centreon/issues/8084

**Comment by CPbN** [comment]
The second reported issue fixed in in 19.10.2, thank you !

But the first one remaining :

![Screen Shot 2019-11-21 at 19 03 50](https://user-images.githubusercontent.com/40244829/69364164-1d075600-0c92-11ea-9988-09341f0060ab.png)

**Comment by CPbN** [comment]
Sometimes I also get this empty screen (no error message, but still no statistics) :

![Screenshot 2020-01-23 at 18 02 02](https://user-images.githubusercontent.com/40244829/73006321-bc6bd500-3e0a-11ea-8b67-a43fbad2c3a4.png)

**Comment by UrBnW** [comment]
On a Remote Server :
```
MariaDB [centreon]> select id from nagios_server;
+----+
| id |
+----+
|  2 |
+----+
1 row in set (0.00 sec)

MariaDB [centreon]> select config_id,ns_nagios_server from cfg_centreonbroker;
+-----------+------------------+
| config_id | ns_nagios_server |
+-----------+------------------+
|         1 |                1 |
|         2 |                1 |
|         3 |                1 |
+-----------+------------------+
3 rows in set (0.00 sec)
```

The remaining statistics issue is due to this database inconsistency.
There may then be an issue when a Remote Server is added.

**Comment by UrBnW** [comment]
Regarding the remaining statistics issue :

On the Central Server :

```

MariaDB [centreon]> select name,id from nagios_server;
+------------+----+
| name       | id |
+------------+----+
| Central    |  1 |
| remote-srv |  2 |
+------------+----+

MariaDB [centreon]> select config_id,config_name,config_filename,ns_nagios_server from cfg_centreonbroker;
+-----------+-----------------------+-----------------------+------------------+
| config_id | config_name           | config_filename       | ns_nagios_server |
+-----------+-----------------------+-----------------------+------------------+
|         1 | central-broker-master | central-broker.xml    |                1 |
|         2 | central-rrd-master    | central-rrd.xml       |                1 |
|         3 | central-module-master | central-module.xml    |                1 |
|         4 | remote-srv-broker     | remote-srv-broker.xml |                2 |
|         5 | remote-srv-module     | remote-srv-module.xml |                2 |
|         6 | remote-srv-rrd        | remote-srv-rrd.xml    |                2 |
+-----------+-----------------------+-----------------------+------------------+
```

On the Remote Server :

```
MariaDB [centreon]> select name,id from nagios_server;
+------------+----+
| name       | id |
+------------+----+
| remote-srv |  2 |
+------------+----+

MariaDB [centreon]> select config_id,config_name,config_filename,ns_nagios_server from cfg_centreonbroker;
+-----------+-----------------------+--------------------+------------------+
| config_id | config_name           | config_filename    | ns_nagios_server |
+-----------+-----------------------+--------------------+------------------+
|         1 | central-broker-master | central-broker.xml |                1 |
|         2 | central-rrd-master    | central-rrd.xml    |                1 |
|         3 | central-module-master | central-module.xml |                1 |
+-----------+-----------------------+--------------------+------------------+

# ls -l /etc/centreon-broker/
total 32
-rw-rw-r-- 1 centreon-broker centreon-broker 5901 Feb 10 10:18 central-broker.xml
-rw-rw-r-- 1 centreon-broker centreon-broker 1592 Feb 10 10:18 central-rrd.xml
-rw-rw-r-- 1 centreon-broker centreon-broker 2247 Feb 10 10:18 poller-module.xml
-rw-rw-r-- 1 centreon-broker centreon-broker 2550 Feb 13 18:00 remote-srv-broker.xml
-rw-rw-r-- 1 centreon-broker centreon-broker 1575 Feb 13 18:00 remote-srv-module.xml
-rw-rw-r-- 1 centreon-broker centreon-broker 2085 Feb 13 18:00 remote-srv-rrd.xml
-rw-rw-r-- 1 centreon-broker centreon-broker  528 Feb 13 18:00 watchdog.xml

# ps -ef | grep cbd
centreo+ 638 629 0 Feb20 ? 00:04:55 /usr/sbin/cbd /etc/centreon-broker/remote-srv-broker.xml
centreo+ 639 629 0 Feb20 ? 00:01:38 /usr/sbin/cbd /etc/centreon-broker/remote-srv-rrd.xml
```

The issue is then due to this database inconsistency.
There may be a problem when a Remote Server is added, seems like the wrong broker configuration is stored into its database.

**Comment by UrBnW** [comment]
See #8488 for a remaining bug.
