### ISSUE TITLE
"Unable to hide passwords in command"

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#7949]
Hi,

In 19.10.0-rc.1, #7859 leads to the following :
'Unable to hide passwords in command'

More details here : https://github.com/centreon/centreon/pull/7859#issuecomment-539950386

I opened this to keep track of this bug.

Many thx 👍

Edit : issue still present in 19.10.0-rc.1.

**Comment by lpinsivy** [comment]
Hi @CPbN ,

We try too many methods to hide password in commands.
But because structure of command can be too much complex, you can have this message if centreon can't hide all password of a command.

We prefer to keep this instead of display command with clean password for security.

Regards,

**Comment by CPbN** [comment]
Hi @lpinsivy,

IMO, the following condition you added could safely be removed :
`if (count($aCommandLineWithMacros) == count($aCommandLineExecuted)) {`

If I remove it from the code, my passwords are correctly hidden, I have commands with 2 passwords, both a correctly hidden.

**Comment by CPbN** [comment]
See PR #7975 for a possible fix.
