### ISSUE TITLE
Fixed downtime is not set correctly

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#7974]
Centreon 19.04.4
OS: CentOS 7.7

If you set a downtime with fixed duration (for example 30 days) the downtime will be always created with End Time inserted. Fixed duration will not be considered.

![image](https://user-images.githubusercontent.com/6400595/66739553-43ef9280-ee71-11e9-9153-07020b7e7f84.png)

**Comment by loiclau** [comment]
maybe #7951

**Comment by joschi99** [comment]
You are absolutely right. It was my fault, sorry.
