### ISSUE TITLE
[BUG] Recurrent Downtimes search-bug

### ISSUE THREAD

**Issue by flex-pgum** [centreon/centreon#7987]
# BUG REPORT INFORMATION

***Operating System***
*CentOS 7*

***Centreon version***
*19.04.4*

***Browser used***

- [x] Google Chrome - version 77.0.3865.120
- [ ] Firefox
- [x] Internet Explorer IE11
- [ ] Safari

### Description

Searchinput in "Monitoring->Downtimes->*Recurrent Downtimes*" doesnt allow to search for an empty string (to display all downtimes) after searching something.

### Steps to Reproduce

1. move to Monitoring->Downtimes->*Recurrent Downtimes*
2. add a recurrent downtimes if you don't have any
3. insert any text into the searchfield and press search e.g. "test"
4. delete the whole text from the searchfield and press search again

### Received result
Searchinput resets to the text you've searched before (in my case "test")

### Expected result
Searchinput should stay empty after searching and the list should display all recurrent downtimes..

**Comment by lpinsivy** [comment]
@flex-pgum thank you for your feedback, we are currently working on it
