### ISSUE TITLE
Upgrading from Centreon 19.04  to 19.10

### ISSUE THREAD

**Issue by IdrissaHilda** [centreon/centreon#7995]
# The installation is on a perpetual loop

### Prerequisites

> For the RPM based systems
using packages for the installation of centreon, I install a Centreon Central Server without database

***Versions***
19.04
```
$ rpm -qa | grep centreon
```

centreon-broker-storage-19.10.0-1.el7.centos.x86_64
centreon-web-19.10.0-7.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20191016-111959.el7.centos.noarch
centreon-broker-cbmod-19.10.0-1.el7.centos.x86_64
centreon-connector-ssh-19.10.0-1.el7.centos.x86_64
centreon-license-manager-19.10.0-1.el7.centos.noarch
centreon-base-config-centreon-engine-19.10.0-7.el7.centos.noarch
centreon-clib-19.10.0-6.el7.centos.x86_64
centreon-perl-libs-19.10.0-7.el7.centos.noarch
centreon-engine-daemon-19.10.0-2.el7.centos.x86_64
centreon-trap-19.10.0-7.el7.centos.noarch
centreon-connector-19.10.0-1.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191016-111959.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191016-111959.el7.centos.noarch
centreon-pp-manager-19.10.0-5.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20191016-111959.el7.centos.noarch
centreon-release-19.10-1.el7.centos.noarch
centreon-broker-19.10.0-1.el7.centos.x86_64
centreon-engine-extcommands-19.10.0-2.el7.centos.x86_64
centreon-broker-cbd-19.10.0-1.el7.centos.x86_64
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20191016-111959.el7.centos.noarch
centreon-auto-discovery-server-19.10.0-2.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20191016-111959.el7.centos.noarch
centreon-common-19.10.0-7.el7.centos.noarch
centreon-engine-19.10.0-2.el7.centos.x86_64
centreon-connector-perl-19.10.0-1.el7.centos.x86_64
centreon-plugin-Operatingsystems-Linux-Snmp-20191016-111959.el7.centos.noarch
centreon-license-manager-common-19.10.0-1.el7.centos.noarch
centreon-poller-centreon-engine-19.10.0-7.el7.centos.noarch
centreon-broker-core-19.10.0-1.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20191016-111959.el7.centos.noarch

***Operating System***

*CentOS 7.*

***Additional environment details :***
Virtual Machine

### Description
The installation is on a perpetual loop , I can't finish the installation

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/56160040/66932840-844d3d00-f038-11e9-8320-166c4208825b.png)

![image](https://user-images.githubusercontent.com/56160040/66932867-8dd6a500-f038-11e9-9bf5-a325ad73b1c8.png)

![image](https://user-images.githubusercontent.com/56160040/66933016-bced1680-f038-11e9-9d70-c30420ceaf1a.png)

![image](https://user-images.githubusercontent.com/56160040/66933071-cfffe680-f038-11e9-9210-332d85c6c072.png)

![image](https://user-images.githubusercontent.com/56160040/66933151-f1f96900-f038-11e9-8717-a8c4b2000a1f.png)

![image](https://user-images.githubusercontent.com/56160040/66933195-00478500-f039-11e9-8c53-c07074f20118.png)

![image](https://user-images.githubusercontent.com/56160040/66933237-13f2eb80-f039-11e9-9795-3e0baad5db64.png)

 When I Click on Finish it's happening again, I am not redirected to access the login page but I am redirected to the first step of installation

**PHP error logs**

When I entered the command to check the error, I don't have an error
```
tail -f /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log
```
```
tail -f /var/log/centreon/centcore.log
```

**Comment by CPbN** [comment]
Should we then safely wait for 19.10.1 @adr-mo ?

**Comment by adr-mo** [comment]
Hi @CPbN if you want to avoid this issue yes.
New release should be available soon.

Regards

**Comment by CPbN** [comment]
No issue with 19.10.1.
Well, one of the database updates kept stuck indefinitely.
I had to restart the whole update process, database updates restarted with the script which was stuck before, and the update process finished.
