### ISSUE TITLE
Centreon on RHEL 8

### ISSUE THREAD

**Issue by ianishant** [centreon/centreon#8004]
Hi,

Do we have any ETA when we will be having Centreon deployment ready for RHEL 8?

**Comment by lpinsivy** [comment]
Hi @ianishant ,

We don't have yet an ETA for Centreon on CentOS/RHEL v8.

We are currently working to remove old libraries and component to help us to be compatible with CentOS v8.

**Comment by ianishant** [comment]
By any chance can we have centreon-nrpe package for RHEL 8 as my company started building RHEL 8 and monitoring is becoming a concern for this version.

**Comment by lpinsivy** [comment]
Hi @ianishant ,

We will start in January the support for Centreon on RHEL 8.

You can use the NRPE v3.x package fron EPEL and take your old NRPE configuration.

Regards,

**Comment by Kiolul** [comment]
Hello,
Do you have any update about this support?
Kind regards.

**Comment by itsul** [comment]
We had another support call and as a result of a marginal question we got a response to the pending CentOS 8 question:

> It will not be available on the coming release at the end of the month (20.04) maybe on the 20.10 but it is not sure and we can't confirm it.

**Comment by angelus2014** [comment]
Hello,

Is there any update on this?


---
With regards,

Angelo Machils

**Comment by cgagnaire** [comment]
I think we can legitimately close this one.
Documentation is up-to-date for RHEL 8 setups.
