### ISSUE TITLE
[doc] MariaDB tuning still needed ?

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#8015]
Hi,

Documentation ([here](https://documentation.centreon.com/docs/centreon/en/latest/installation/from_packages.html), [here](https://documentation.centreon.com/docs/centreon/en/latest/administration_guide/poller/install_remote_server_packages.html), ...) indicates :
```
# mkdir -p  /etc/systemd/system/mariadb.service.d/
# echo -ne "[Service]\nLimitNOFILE=32000\n" | tee /etc/systemd/system/mariadb.service.d/limits.conf
# systemctl daemon-reload
# systemctl restart mysql
```

However, there's already the following :
```
# cat /etc/systemd/system/mariadb.service.d/centreon.conf 
[Service]
LimitNOFILE=32000
```

Not sure then the above instructions are still needed.

Thank you 👍 

Edit : issue still present in 19.10.4.

**Comment by lpinsivy** [comment]
Hi @CPbN , depending on the version of your DBMS, this may still be necessary.

Regards,

**Comment by CPbN** [comment]
Hi Laurent,
Thank you for your answer.
Perhaps then the documentation could indicate that this tuning is needed only if you use another DBMS than the one provided by Centreon repository (which already contains the tuning).
Thank you !
