### ISSUE TITLE
[remote server] Useless email field ?

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#8017]
Hi,

On a remote server, in _Configuration / Users / Contacts Users_, we can't set contacts' email, field is not present.
Rather makes sense, as the mail used for notifications will be the one set on the central server.

However, in _Administration / Parameters / My Account_, email field is still available.

Perhaps it should then be removed ?

Thank you 👍

Edit : issue still present in 19.10.15.

**Comment by lpinsivy** [comment]
You rights !

**Comment by cgagnaire** [comment]
Hi @UrBnW,
Actually it's the other way: we added the email setting in contact form.
It is needed by the Map desktop client to connect to dedicated Map server linked to Remote Server.
