### ISSUE TITLE
Problems with host status

### ISSUE THREAD

**Issue by jonminguito** [centreon/centreon#8041]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***

```
$ rpm -qa | grep centreon | grep -v plugin
centreon-clib-19.10.0-6.el7.centos.x86_64
centreon-broker-cbmod-19.10.0-1.el7.centos.x86_64
centreon-widget-grid-map-19.10.0-1.el7.centos.noarch
centreon-widget-engine-status-19.10.0-1.el7.centos.noarch
centreon-poller-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-awie-19.10.0-1.el7.centos.noarch
centreon-engine-extcommands-19.10.1-2.el7.centos.x86_64
centreon-cwrapper-perl-0.1-1.el7.centos.x86_64
centreon-widget-service-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-graph-monitoring-19.10.0-1.el7.centos.noarch
centreon-license-manager-19.10.0-1.el7.centos.noarch
centreon-engine-19.10.1-2.el7.centos.x86_64
centreon-release-19.10-1.el7.centos.noarch
centreon-perl-libs-19.10.1-3.el7.centos.noarch
centreon-broker-core-19.10.0-1.el7.centos.x86_64
centreon-broker-cbd-19.10.0-1.el7.centos.x86_64
centreon-widget-host-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-httploader-19.10.0-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-connector-ssh-19.10.0-1.el7.centos.x86_64
centreon-license-manager-common-19.10.0-1.el7.centos.noarch
centreon-base-config-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-broker-19.10.0-1.el7.centos.x86_64
centreon-broker-storage-19.10.0-1.el7.centos.x86_64
centreon-widget-hostgroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-19.10.0-1.el7.centos.noarch
centreon-widget-global-health-19.10.0-1.el7.centos.noarch
centreon-connector-perl-19.10.0-1.el7.centos.x86_64
centreon-database-19.10.1-3.el7.centos.noarch
centreon-auto-discovery-server-19.10.0-2.el7.centos.noarch
centreon-19.10.1-3.el7.centos.noarch
centreon-engine-daemon-19.10.1-2.el7.centos.x86_64
centreon-widget-tactical-overview-19.10.0-1.el7.centos.noarch
centreon-trap-19.10.1-3.el7.centos.noarch
centreon-pp-manager-19.10.0-5.el7.centos.noarch
centreon-common-19.10.1-3.el7.centos.noarch
centreon-web-19.10.1-3.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.10.0-1.el7.centos.noarch
centreon-connector-19.10.0-1.el7.centos.x86_64
```
***Operating System***

*CentOS 7*

***Browser used***

- [ ] Google Chrome
- [X] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: Official Centreo ISO installed on a Proxmox Environment.

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

Monitorized hosts (even localhost) appear to be down randomly even if the PING service is OK all the time (no packet loss detected)

This is a fresh environment deployed using the official Centreo ISO with the default config.

### Steps to Reproduce

1. I logged in Centreon
2. I reached the Custom View
3. All the hosts are changin states between up and down randomly even though the PING service is ok all the time. This is happening even with localhost.

### Logs

**PHP error logs**

```
tail -f /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log
THE FILE IS EMPTY
```

![2019-10-23 15_31_21-Window](https://user-images.githubusercontent.com/17464427/67400101-79048f00-f5ad-11e9-8c09-379153b2f662.png)

**Comment by florianncy** [comment]
I have the same problem.
I had to return to 19.04 version.

**Comment by jrcorchete1** [comment]
I also have this problem on 19.10, sadly i can't reverse to 19.04 because it's a fresh install.

**Comment by cgagnaire** [comment]
Hi,
This behaviour is fixed since https://documentation.centreon.com/docs/centreon-engine/en/latest/release_notes/engine19.10.html#centreon-engine-19-10-2.
Can you please update and tell us ?

**Comment by jonminguito** [comment]
The bug has fixed in last update!

Thank you!
