### ISSUE TITLE
Cumulative inheritance, service + host contacts ?

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#8047]
Hi,

From [documentation](https://documentation.centreon.com/docs/centreon/en/latest/release_notes/centreon-19.10/centreon-19.10.0.html) :
_Cumulative inheritance: Cumulate all contacts and contactgroups of resources and linked templates (method used for new installation)_

Using _cumulative inheritance_, for a service, contacts from the host are dismissed, even if no contact is defined at this service level.
Expected behavior ?
Bug ?

Many thanks 👍

Edit : issue still present in 19.10.4.

**Comment by prohand** [comment]
Hello, I have a same bug.

Even when the Additional Legacy Contact Groups check box is selected

Thanks

**Comment by prohand** [comment]
Oups I did not check the box below  : 

![image](https://user-images.githubusercontent.com/20227162/67550455-d3653300-f706-11e9-8d14-5f314be0d730.png)

**Comment by CPbN** [comment]
Note that using _closest value_,  for a service, contacts from the host are notified if no contact is defined at this service level.
The behaviors then do not seem to be consistent (or this should be specified in the documentation).

**Comment by lpinsivy** [comment]
Hi,

The option **Closest Value** will try to get the most close contact(s) and contactgroup(s) of an object. For a service, if not contact(s) and contactgroup(s) are defined on the service and template, the process will try to find most close contact(s) and contactgroup(s) of the host.

For the **Vertical Inheritance Only**, it's the same a previously (legacy) but vertical additive inheritance for host deosn't work (as previously).

For the **Cumulative inheritance** option,  the process will aggregate all contacts and contactgroups of an object including vertical and horizontal inheritance (tzmplates).

But remenber that for **Vertical Inheritance Only**, a contact and a contactgroup must be defined for a service. So if any contact(s) and contactgroup(s) are defined of an object, the process will start **Closest Value**  method to get the first contact(s) and contactgroup(s).

Regards,

**Comment by CPbN** [comment]
Hi Laurent,

Thank you very much for the clarification.

The important thing, if I correctly understood, is that **Closest Value**, for a service, will search for contacts at host level if no contact is defined at service level.
Whereas **Cumulative Inheritance** will stay at service level.
Which makes a huge difference.

Thank you again :+1:
