### ISSUE TITLE
[19.10.1 : Configuration] Problem with Contact template and notification

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#8053]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon
```
centreon-broker-storage-19.10.0-1.el7.centos.x86_64
centreon-widget-host-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-clib-19.10.0-6.el7.centos.x86_64
centreon-widget-engine-status-19.10.0-1.el7.centos.noarch
centreon-license-manager-19.10.0-1.el7.centos.noarch
centreon-engine-extcommands-19.10.0-2.el7.centos.x86_64
centreon-release-19.10-1.el7.centos.noarch
centreon-trap-19.10.1-3.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191016-111959.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20191016-111959.el7.centos.noarch
centreon-base-config-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-connector-19.10.0-1.el7.centos.x86_64
centreon-broker-core-19.10.0-1.el7.centos.x86_64
centreon-broker-cbd-19.10.0-1.el7.centos.x86_64
centreon-widget-service-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-tactical-overview-19.10.0-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.10.0-1.el7.centos.noarch
centreon-widget-grid-map-19.10.0-1.el7.centos.noarch
centreon-widget-global-health-19.10.0-1.el7.centos.noarch
centreon-license-manager-common-19.10.0-1.el7.centos.noarch
centreon-pp-manager-19.10.0-5.el7.centos.noarch
centreon-engine-daemon-19.10.0-2.el7.centos.x86_64
centreon-engine-19.10.0-2.el7.centos.x86_64
centreon-common-19.10.1-3.el7.centos.noarch
centreon-web-19.10.1-3.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20191016-111959.el7.centos.noarch
centreon-database-19.10.1-3.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20191016-111959.el7.centos.noarch
centreon-poller-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-19.10.1-3.el7.centos.noarch
centreon-broker-19.10.0-1.el7.centos.x86_64
centreon-widget-graph-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-httploader-19.10.0-1.el7.centos.noarch
centreon-connector-ssh-19.10.0-1.el7.centos.x86_64
centreon-widget-live-top10-memory-usage-19.10.0-1.el7.centos.noarch
centreon-auto-discovery-server-19.10.0-2.el7.centos.noarch
centreon-broker-cbmod-19.10.0-1.el7.centos.x86_64
centreon-perl-libs-19.10.1-3.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20191016-111959.el7.centos.noarch
centreon-connector-perl-19.10.0-1.el7.centos.x86_64
`
***Operating System***

CentOS 7 ISO Centreon

***Browser used***

- [ ] Google Chrome
- [x ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 69.0.2

### Description

Add contact template with notification

![capture_2019-10-24_21-59](https://user-images.githubusercontent.com/12350746/67520719-af273900-f6a9-11e9-9c86-3d90f90dd261.png)

Add a contact test1 based contact template

![capture_2019-10-24_22-01](https://user-images.githubusercontent.com/12350746/67520894-062d0e00-f6aa-11e9-82d6-13a9dd3423ee.png)

Add a contact test1 based contact template

![capture_2019-10-24_22-02](https://user-images.githubusercontent.com/12350746/67520908-0decb280-f6aa-11e9-86cf-142df01dd802.png)

Add test1 and test2 for notification with template generic_active_custom

![capture_2019-10-24_22-05](https://user-images.githubusercontent.com/12350746/67521067-6b80ff00-f6aa-11e9-9243-43622cd31d98.png)

When applying the configuration, I have an error with the test2 contact

![capture_2019-10-24_22-08](https://user-images.githubusercontent.com/12350746/67521239-c6b2f180-f6aa-11e9-868f-f286b267c3f7.png)

And when I disable test1 or test2 it works. I have no problem with version 19.04

**Comment by cgagnaire** [comment]
Thanks @kermith72!
