### ISSUE TITLE
[v. 2.8.22 ] CLAPI:  Invalid credentials with encrypted password from DB.

### ISSUE THREAD

**Issue by kitatek** [centreon/centreon#8086]
Please describe your issue in English.
-->
[v. 2.8.22 ] CLAPI:  Invalid credentials. centreon -u admin -p 'md5__1bREMOVEDCHARACTERS' -o host -a show

# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

yum list installed|grep centreon
MariaDB-client.x86_64     5.5.57-1.el6     @centreon-stable                     
MariaDB-common.x86_64     5.5.57-1.el6     @centreon-stable                     
MariaDB-compat.x86_64     5.5.57-1.el6     @centreon-stable                     
MariaDB-server.x86_64     5.5.57-1.el6     @centreon-stable                     
centreon.noarch           2.8.22-1.el6     @centreon-stable-noarch              
centreon-base-config-centreon-engine.noarch
                          2.8.22-1.el6     @centreon-stable-noarch              
centreon-broker.x86_64    3.0.14-1.el6     @centreon-stable                     
centreon-broker-cbd.x86_64
                          3.0.14-1.el6     @centreon-stable                     
centreon-broker-cbmod.x86_64
                          3.0.14-1.el6     @centreon-stable                     
centreon-broker-core.x86_64
                          3.0.14-1.el6     @centreon-stable                     
centreon-broker-storage.x86_64
                          3.0.14-1.el6     @centreon-stable                     
centreon-clib.x86_64      1.4.2-1.el6      @anaconda-CES-201309230102.x86_64/6.8
centreon-common.noarch    2.8.22-1.el6     @centreon-stable-noarch              
centreon-connector.x86_64 1.1.3-1.el6      @centreon-stable                     
centreon-connector-perl.x86_64
                          1.1.3-1.el6      @centreon-stable                     
centreon-connector-ssh.x86_64
                          1.1.3-1.el6      @centreon-stable                     
centreon-engine.x86_64    1.8.1-1.el6      @centreon-stable                     
centreon-engine-daemon.x86_64
                          1.8.1-1.el6      @centreon-stable                     
centreon-engine-extcommands.x86_64
                          1.8.1-1.el6      @centreon-stable                     
centreon-license-manager.noarch
                          1.1-5.el6        @centreon-stable-noarch              
centreon-perl-libs.noarch 2.8.22-1.el6     @centreon-stable-noarch              
centreon-plugin-Applications-Databases-Mysql.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Applications-Monitoring-Centreon-Central.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Applications-Monitoring-Centreon-Database.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Applications-Monitoring-Centreon-Poller.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Applications-Protocol-Dns.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Applications-Protocol-Ftp.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Applications-Protocol-Http.noarch
                          20180409-1.el6   @centreon-stable-noarch              
centreon-plugin-Applications-Protocol-Ldap.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Hardware-Printers-Generic-Snmp.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-Network-Cisco-Standard-Snmp.noarch
                          20180409-1.el6   @centreon-stable-noarch              
centreon-plugin-Operatingsystems-Linux-Snmp.noarch
                          20180409-1.el6   @centreon-stable-noarch              
centreon-plugin-Operatingsystems-Windows-Snmp.noarch
                          20171208-1.el6   @centreon-stable-noarch              
centreon-plugin-meta.noarch
                          2.8.22-1.el6     @centreon-stable-noarch              
centreon-plugins.noarch   2.8.22-1.el6     @centreon-stable-noarch              
centreon-poller-centreon-engine.noarch
                          2.8.22-1.el6     @centreon-stable-noarch              
centreon-pp-manager.noarch
                          2.3-3.el6        @centreon-stable-noarch              
centreon-release.noarch   3.4-4.el6        @centreon-stable-noarch              
centreon-trap.noarch      2.8.22-1.el6     @centreon-stable-noarch              
centreon-web.noarch       2.8.22-1.el6     @centreon-stable-noarch              
centreon-widget-engine-status.noarch
                          1.0.2-1.el6      @centreon-stable-noarch              
centreon-widget-graph-monitoring.noarch
                          1.5.2-3.el6      @centreon-stable-noarch              
centreon-widget-grid-map.noarch
centreon-widget-host-monitoring.noarch
                          1.6.2-1.el6      @centreon-stable-noarch              
centreon-widget-hostgroup-monitoring.noarch
                          1.6.0-1.el6      @centreon-stable-noarch              
centreon-widget-live-top10-cpu-usage.noarch
                          1.1.1-1.el6      @centreon-stable-noarch              
centreon-widget-live-top10-memory-usage.noarch
                          1.1.1-1.el6      @centreon-stable-noarch              
centreon-widget-service-monitoring.noarch
                          1.6.2-1.el6      @centreon-stable-noarch              
centreon-widget-servicegroup-monitoring.noarch
                          1.6.0-1.el6      @centreon-stable-noarch              
centreon-widget-tactical-overview.noarch
perl-Exporter-Tiny.noarch 0.042-1.el6      @centreon-stable-noarch              
perl-HTTP-ProxyPAC.noarch 0.31-1.el6       @centreon-stable-noarch              
perl-IO-Interface.x86_64  1.09-1.el6       @centreon-stable                     
                          1.12-2.el6       @centreon-stable                     
perl-JE.noarch            0.066-1.el6      @centreon-stable-noarch              
perl-JMX-Jmx4Perl.noarch  1.11-2.el6       @centreon-stable-noarch              
perl-JSON-Path.noarch     0.205-1.el6      @centreon-stable-noarch              
perl-LV.noarch            0.006-1.el6      @centreon-stable-noarch              
perl-Net-FTPSSL.noarch    0.24-1.el6       @centreon-stable-noarch              
perl-Sys-SigAction.noarch 0.21-1.el6       @centreon-stable-noarch     

***Operating System***

*CentOS 6.5

### Description

-- Describe the encountered issue --

CLAPI call works with clear text password but not encrypted password from the database

### Steps to Reproduce

centreon -u admin -p 'clearTEXTpassword' -o host -a show
id;name;alias;address;activate
102;Ubuntu-18-04_-git-init-04;Ubuntu-18-04 -git-init-04;10.1.80.236;1

centreon -u admin -p 'md5__1bREMOVEDCHARACTERS' -o host -a show
Invalid credentials.

The string 'md5__1bREMOVEDCHARACTERS'  I took it from the database contacts table (just replaced confidential characters after md5__1b).

So normally, it should work as authentication with encrypted password, but it doesn't.

**Comment by lpinsivy** [comment]
Hi @kitatek, tu use crypted password in CLAPI you must set '-s' option in your command line:

`./centreon -u <LOGIN> -p <PASSWORD> [-s] -o <OBJECT> -a <ACTION>`

**Comment by kitatek** [comment]
Thank you @lpinsivy , yes I figured it from the help below, that -s is for SHA encryption/hashing, otherwise md5 is used if we omit the -s:

```
 centreon --help
Centreon version 2.8.22 - Copyright Centreon - www.centreon.com
This software comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to modify and redistribute it under the GPL license

usage: ./centreon -u <LOGIN> -p <PASSWORD> [-s] -o <OBJECT> -a <ACTION> [-v]
  -s     Use SHA1 on password (default is MD5)
  -v     variables 
  -h     Print help 
  -V     Print version 
  -o     Object type 
  -a     Launch action on Centreon
     Actions are the followings :
(.......)

   For more information about configuration objects, please refer to CLAPI wiki:
      - http://documentation.centreon.com/docs/centreon-clapi/ 

Notes:
  - Actions can be written in lowercase chars
  - LOGIN and PASSWORD is an admin account of Centreon
```
So I expect to be able to use md5 hashed password if I omit the -s option, is this correct ? 

I remember I tried all combinations unsuccessfully, so actually I am doubtful that it works as per the documentation.

To make some progress, can you please let me know:

1. if/how we can use the password hash from the database user record to produce a working command line (for example: do we need to remove the md5_ prefix to make it work ?)
2. is the password hash of the admin user password, created at setup time, using different encryption/standards than other users created from the Web GUI
3. if so, what are the algorithm used at setup for admin (md5 ?) , and for users created later in the GUI (SHA ?)
4. or maybe the older md5 hash was updated to the stronger SHA in a code update, after we installed ?

Thank you to give me clues here, all my tests fail with encrypted password (with and without -s).

**Comment by kitatek** [comment]
Thank you @lpinsivy , yes I figured it from the help below, that -s is for SHA encryption/hashing, otherwise md5 is used if we omit the -s:

```
 centreon --help
Centreon version 2.8.22 - Copyright Centreon - www.centreon.com
This software comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to modify and redistribute it under the GPL license

usage: ./centreon -u <LOGIN> -p <PASSWORD> [-s] -o <OBJECT> -a <ACTION> [-v]
  -s     Use SHA1 on password (default is MD5)
  -v     variables 
  -h     Print help 
  -V     Print version 
  -o     Object type 
  -a     Launch action on Centreon
     Actions are the followings :
(.......)

   For more information about configuration objects, please refer to CLAPI wiki:
      - http://documentation.centreon.com/docs/centreon-clapi/ 

Notes:
  - Actions can be written in lowercase chars
  - LOGIN and PASSWORD is an admin account of Centreon
```
So I expect to be able to use md5 hashed password if I omit the -s option, is this correct ? 

I remember I tried all combinations unsuccessfully, so actually I am doubtful that it works as per the documentation.

To make some progress, can you please let me know:

1. if/how we can use the password hash from the database user record to produce a working command line (for example: do we need to remove the md5_ prefix to make it work ?)
2. is the password hash of the admin user password, created at setup time, using different encryption/standards than other users created from the Web GUI
3. if so, what are the algorithm used at setup for admin (md5 ?) , and for users created later in the GUI (SHA ?)
4. or maybe the older md5 hash was updated to the stronger SHA in a code update, after we installed ?

Thank you to give me clues here, all my tests fail with encrypted password (with and without -s).

**Comment by kitatek** [comment]
ooops sorry closed by mistake, not solved at all..

**Comment by kitatek** [comment]
Easy to reproduce:

`$ mysql -u root`
Then
`select contact_id , contact_name , contact_alias  , contact_passwd  , contact_lang , contact_email  , contact_oreon  , contact_admin from centreon.contact where contact_admin = "1" ;
exit;`

Then, in shell, print and try all combinations:

`for user in 1 name_admin admin ; do   for pass in md5__76xxxxxxxxxxxxxxxxxxxxx53 __76xxxxxxxxxxxxxxxxxxxxx53 _76xxxxxxxxxxxxxxxxxxxxx53 76xxxxxxxxxxxxxxxxxxxxx53 'AdminClearTextPassword' ; do   for opt in "-s "  " " ; do   echo "------------- centreon -u  $user -p $pass $opt -o host -a show -v";    centreon -u  $user -p "$pass" $opt -o host -a show -v; done; done; done`

The values name_admin admin are from the DB, as well as md5__76xxxxxxxxxxxxxxxxxxxxx53 .

Only the last combination with clear text password does work.

**Comment by lpinsivy** [comment]
Yes you rights after some test it look like an issue

Sorry for the inconvenience

**Comment by lpinsivy** [comment]
Can you try this fix?

```
--- a/www/class/centreon-clapi/centreonAPI.class.php
+++ b/www/class/centreon-clapi/centreonAPI.class.php
@@ -510,8 +510,9 @@ class CentreonAPI
         /**
          * Check Login / Password
          */
-        if ($useSha1) {
-            $pass = $this->dependencyInjector['utils']->encodePass($this->password, 'sha1');
+        $algo = $this->dependencyInjector['utils']->detectPassPattern($this->password);
+        if ($algo) {
+            $pass = $this->password;
         } else {
             $pass = $this->dependencyInjector['utils']->encodePass($this->password, 'md5');
         }
```

**Comment by kitatek** [comment]
Error:
Maybe some function dependency missing ?
See:

> [ ~]$ centreon -u batchadmin -p 'md5__xxxxxxxxxxxxxxxxxxxx'  -s -o host -a show -v
> PHP Fatal error:  Call to a member function detectPassPattern() on a non-object in /usr/share/centreon/www/class/centreon-clapi/centreonAPI.class.php on line 545
> [~]$ 

My code:

```
 539         /**
 540          * Check Login / Password
 541          */
 542 /**        if ($useSha1) {
 543             $pass = $this->utilsObject->encodePass($this->password, 'sha1');
 544 */
 545         $algo = $this->dependencyInjector['utils']->detectPassPattern($this->password);
 546         if ($algo) {
 547             $pass = $this->password;
 548         } else {
 549             $pass = $this->utilsObject->encodePass($this->password, 'md5');
 550         }
```
