### ISSUE TITLE
SNMP Traps, add filters on traps view

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#809]
---

Author Name: **benoit p** (benoit p)
Original Redmine Issue: 6435, https://forge.centreon.com/issues/6435
Original Date: 2015-06-17

---

Hello,

I would be nice if we could apply filters via drop down menus, on columns shown on «Configuration > SNMP Traps», like «Vendor Name«, «Status».

I would be easier to manage traps.

Regards.

**Comment by julienmathis** [comment]
Quentin, 

Can you help us on this point ?

Regards

**Comment by lpinsivy** [comment]
done by #7758
