### ISSUE TITLE
Replace SSO Keycloak Client Realm and Server URL with a single parameter to allow other OAUTH2/OpenID Connector Providers

### ISSUE THREAD

**Issue by srinathman** [centreon/centreon#8096]
Replace auth Keycloak Client Realm and Keycloak Server URL with a single parameter to comply OpenID Connect specs. The parameter should accept something like:

``` http://localhost:8080/realms/myrealm/protocol/openid-connect/auth ```
or 
``` https://company.otherprovider.com/oauth2/auth ```

Then, the constructed URL would be 

`            $authUrl = $base . "client_id=" . $clientId  . "&response_type=code&redirect_uri=" . redirect;
`
Ref: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by lpinsivy** [comment]
Hi @srinathman do you have opportunity to test PR #9025 ?

**Comment by srinathman** [comment]
I don't currently have a "source" based installation on hand. I'll try to get one to test it.
Merci,

**Comment by lpinsivy** [comment]
Thank you @srinathman, you can maybe use a VM from https://download.centreon.com/ and apply changes just to test

**Comment by srinathman** [comment]
Sorry for the late response on this.
I finally was able to test this on the latest release and it seems to be working fine.
The only issue I had was that Okta requires the "state" parameter and I had to hard code it to make it work.
Okta also requires "openid" and "profile" scopes.

Here are the OpenId Connect settings I used for Okta:

```
Base Url: https://<company>.okta.com
Authorization Endpoint:  /oauth2/v1/authorize
Token Endpoint: /oauth2/v1/token
Introspection Token Endpoint: /oauth2/v1/introspect
User Information Endpoint: /oauth2/v1/userinfo
End Session Endpoint: /oauth2/v1/logout
Scope: openid profile
```
