### ISSUE TITLE
Display parent service categories in service template relations tab

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon#8101]
Hi,

Currrently the only way to edit a service category is from the service category form itself. It would be very convenient to have a way to do it in the service template form ("relations" tab) in the same way it is possible to do it for host templates/category relations.

This feature request is following ticket #00083496 opened on the commercial support tracker.

Best regards,

Stéphane THOMAS

**Comment by bmareau** [comment]
Hi,

The option already exists but not in the same tab.
For host template : "Relations" tab
For service template : "Extended Info" tab

Could it be harmonized?
Regards

**Comment by StefThomas** [comment]
Hi Laurent,

Why did you close this one? This is more an improvement request than a simple question. Do we have to consider this harmonization is not possible?
