### ISSUE TITLE
Notification Escalations - No handling for state change from CRITICAL to WARNING

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#8130]
### Installed packages 

```centreon-plugin-Applications-Databases-Mysql-20191016-111959.el6.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20191016-111959.el6.noarch
centreon-broker-core-3.0.16-1.el6.x86_64
centreon-license-manager-1.1-5.el6.noarch
centreon-pp-manager-2.4.0-1.el6.noarch
centreon-engine-1.8.1-1.el6.x86_64
centreon-plugin-Operatingsystems-Linux-Snmp-20191016-111959.el6.noarch
centreon-plugin-Applications-Protocol-Ftp-20191016-111959.el6.noarch
centreon-connector-ssh-1.1.3-1.el6.x86_64
centreon-widget-httploader-1.0.0-2.el6.noarch
centreon-poller-centreon-engine-2.8.29-1.el6.noarch
centreon-widget-live-top10-memory-usage-1.1.1-1.el6.noarch
centreon-release-3.4-4.el6.noarch
centreon-widget-service-monitoring-1.6.3-1.el6.noarch
centreon-widget-graph-monitoring-1.5.2-3.el6.noarch
centreon-plugin-Applications-Protocol-Dns-20191016-111959.el6.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20191016-111959.el6.noarch
centreon-widget-engine-status-1.0.2-1.el6.noarch
centreon-plugin-Applications-Protocol-Http-20191016-111959.el6.noarch
centreon-broker-3.0.16-1.el6.x86_64
centreon-clib-1.4.2-1.el6.x86_64
centreon-broker-cbd-3.0.16-1.el6.x86_64
centreon-connector-perl-1.1.3-1.el6.x86_64
centreon-connector-1.1.3-1.el6.x86_64
centreon-widget-servicegroup-monitoring-1.6.1-1.el6.noarch
centreon-engine-daemon-1.8.1-1.el6.x86_64
centreon-common-2.8.29-1.el6.noarch
centreon-plugins-2.8.29-1.el6.noarch
centreon-widget-live-top10-cpu-usage-1.1.1-1.el6.noarch
centreon-widget-tactical-overview-1.0.1-2.el6.noarch
centreon-widget-host-monitoring-1.6.3-1.el6.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191016-111959.el6.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20191016-111959.el6.noarch
centreon-plugin-Applications-Protocol-Ldap-20191016-111959.el6.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191016-111959.el6.noarch
centreon-broker-storage-3.0.16-1.el6.x86_64
centreon-widget-grid-map-1.0.0-8.el6.noarch
centreon-engine-extcommands-1.8.1-1.el6.x86_64
centreon-perl-libs-2.8.29-1.el6.noarch
centreon-web-2.8.29-1.el6.noarch
centreon-base-config-centreon-engine-2.8.29-1.el6.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191016-111959.el6.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20191016-111959.el6.noarch
centreon-widget-hostgroup-monitoring-1.6.0-1.el6.noarch
centreon-trap-2.8.29-1.el6.noarch
centreon-poller-display-central-1.6.0-2.el6.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191016-111959.el6.noarch
centreon-broker-cbmod-3.0.16-1.el6.x86_64
centreon-2.8.29-1.el6.noarch
```
***Operating System***

CentOS release 6.10 (Final)
Cross tested on a Centreon 2.8.29 (CentOS 7)

### Description
We have configured Escalations to send out one notification when the first notification would be triggered and deactivated the repetition.
Every object within our monitoring has an "dummy"-user attached that receives notifications for every possible state. This user is just used as a trigger for the escalation process.

We have encountered the problem that a state change from CRITICAL to WARNING doesn't trigger the corresponding escalation. However the (normal) notification is triggered correctly.

### Steps to Reproduce

Create a user that has activated notification for every state and a vaild notification command.
Activate the notification within a service and attach the created user. Set the notification interval to 0.

Create an escalation that triggers for WARNING/CRITICAL/RECOVERY, has the created service attached with it, first notification set to 1, last notification set to 2, notification interval set to 0 and a contact group attached which has at least one user attached to it. This user also needs valid notification commands and activated notifications for WARNING/CRITICAL/RECOVERY.

Now let the created service lead to a CRITICAL hard state and check the eventlog for a correct notifcation of the first user (defined in service element itself) and the escalation user (triggered by this notification).
Now change the service to lead to a WARNING hard state. Then check the eventlog again. You'll see that the first user was noitified, but the escalation didn't execute.

State changes from WARNING to CRITICAL are working by the way. There is just this one exception.

### Describe the received result

Notification escalations don't trigger by a state change from CRITICAL to WARNING within a related service.

### Describe the expected result

Escalations should value every state change without an exception.

### Eventlogs
Escalation_Dummy is a user related to the service.
Hotline is an user attached to an escalation.

![Screenshot from 2019-11-14 11-25-02](https://user-images.githubusercontent.com/12328177/68934092-532a6e80-0796-11ea-8a79-7906e7a85c54.png)

**Comment by lpinsivy** [comment]
Hi @itsul , this must be fixed with Centreon Engine 19.10.8 as defined in [release note](https://github.com/centreon/centreon-engine/blob/master/doc/release_notes/engine19.10.rst#centreon-engine-19108).

Regards,
