### ISSUE TITLE
Bug in graph processing using wildcards for data source

### ISSUE THREAD

**Issue by acelor** [centreon/centreon#8131]
Wildcards in Data Source for curves don't work anymore.
Found this yesterday. This is related to #4128. I understand the intention of the fix, but in my eyes it's wrong. Affected are both centreonGraph.class.php around line 568 and centreonGraphNg.class.php around line 338. Code looks like this:
`$metricPattern = '/^' .  preg_quote($dsVal['ds_name'], '/') . '$/i';`
`$metricPattern = str_replace('*', '.*', $metricPattern);`
Lets assume you want a specific graph for the metric `GigabitEthernet 0/0`. The upper line would turn it into `^/"GigabitEthernet 0\/0$/i` and the curve definition would match. This is perfectly fine.

In contrast, if you intend to use wildcards, i.e `GigabitEthernet 0/*`, the result of the upper line would be `^/"GigabitEthernet 0\/\*$/i` and the lower line would replace it to `^/"GigabitEthernet 0\/\.*$/i`.
This would NOT match `GigabitEthernet 0/0` or `GigabitEthernet 0/1` as intended, but would match `GigabitEthernet 0/`, `GigabitEthernet 0/.`, `GigabitEthernet 0/..` and so on. This is because the preg_quote directive will escape any regex-specific characters.

I suggest to either replace the upper line as 
`
$metricPattern = '/^' . str_replace('/', '\/', $dsVal['ds_name']).'$/i';
`
and leave the second line unouched to avoid #4128 and accept asterisk as a wildcard character in DS names. Additionally, this fix allows using PCRE in DS names. 

If you want to only accept asterisk,  replace a second line like this:
`$metricPattern = '/^' .  preg_quote($dsVal['ds_name'], '/') . '$/i';`
`$metricPattern = str_replace('\*', '.*', $metricPattern);`

Please also adapt the documentation. There is no mention that DS accepts widcards, even thou it's implemented since 4 years.

Thanks guys, keep the good work!

**Comment by lpinsivy** [comment]
Hi @acelor, thank you for your report.

Can you explain me where in Centreon UI you want to use wildcards for metric name?

Regards,

**Comment by acelor** [comment]
Hi @lpinsivy ,
It's in Monitoring  >  Performances  >  Curves  >  <Any Item>  > Data source name

Wildcards have been implemented with #3755, but broken with #4128
Practical use cases are numerous, you can use wildcard to colour similar curves the same way, or (as we do) stack curves that start with a defined prefix
