### ISSUE TITLE
[BUG] Remove filter "Name" in Monitoring > Downtimes > Recurrent Downtimes

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#8137]
***Versions***
Centreon 19.10.1 - CentOS 7
Reproduced on demo.centreon.com

***Browser used***
- [ x ] Google Chrome
- [ x ] Edge

### Description
It is not possible to remove the filter "Name" specified in the "Monitoring > Downtimes > Recurrent Downtimes" page.

### Steps to Reproduce
1. Log in Centreon
2. Go to "Monitoring > Downtimes > Recurrent Downtimes
3. Put a name in filter "Name" 
4. Try to remove it

### Describe the received result
It is not possible to remove the filter "Name" specified in the "Monitoring > Downtimes > Recurrent Downtimes" page.

### Describe the expected result
It's possible to remove the filter "Name" specified in the "Monitoring > Downtimes > Recurrent Downtimes" page.

Regards

**Comment by cgagnaire** [comment]
Fixed in 19.10.2
