### ISSUE TITLE
Freeze "Setting up basic configuration" on Fresh Install

### ISSUE THREAD

**Issue by LeDOC666** [centreon/centreon#8138]
BUG REPORT INFORMATION
Hello, I wanna make a Fresh Install with RPM, and on Step 7, the step Setting up basic configuration freeze. It run since last night.

The table are created on centreon, and centreon_storage database, but nothing more.
I tryed refresh, but same thing

### Prerequisites
***Versions***

For the RPM based systems
```
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191016-111959.el7.centos.noarch
centreon-19.10.1-3.el7.centos.noarch
centreon-release-19.10-1.el7.centos.noarch
centreon-web-19.10.1-3.el7.centos.noarch
centreon-widget-engine-status-19.10.0-1.el7.centos.noarch
centreon-widget-tactical-overview-19.10.0-1.el7.centos.noarch
centreon-license-manager-19.10.0-1.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20191016-111959.el7.centos.noarch
centreon-broker-core-19.10.1-1.el7.centos.x86_64
centreon-widget-host-monitoring-19.10.0-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-connector-19.10.0-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Dns-20191016-111959.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20191016-111959.el7.centos.noarch
centreon-broker-storage-19.10.1-1.el7.centos.x86_64
centreon-widget-live-top10-memory-usage-19.10.0-1.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.10.0-1.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20191016-111959.el7.centos.noarch
centreon-database-19.10.1-3.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20191016-111959.el7.centos.noarch
centreon-clib-19.10.0-6.el7.centos.x86_64
centreon-perl-libs-19.10.1-3.el7.centos.noarch
centreon-engine-19.10.6-3.el7.centos.x86_64
centreon-widget-service-monitoring-19.10.1-1.el7.centos.noarch
centreon-widget-global-health-19.10.0-1.el7.centos.noarch
centreon-widget-graph-monitoring-19.10.0-1.el7.centos.noarch
centreon-connector-ssh-19.10.0-1.el7.centos.x86_64
centreon-license-manager-common-19.10.0-1.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191016-111959.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191016-111959.el7.centos.noarch
centreon-broker-19.10.1-1.el7.centos.x86_64
centreon-broker-cbmod-19.10.1-1.el7.centos.x86_64
centreon-widget-servicegroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-connector-perl-19.10.0-1.el7.centos.x86_64
centreon-plugin-Hardware-Printers-Generic-Snmp-20191016-111959.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20191016-111959.el7.centos.noarch
centreon-base-config-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-engine-daemon-19.10.6-3.el7.centos.x86_64
centreon-widget-grid-map-19.10.0-1.el7.centos.noarch
centreon-trap-19.10.1-3.el7.centos.noarch
centreon-pp-manager-19.10.0-5.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191016-111959.el7.centos.noarch
centreon-poller-centreon-engine-19.10.1-3.el7.centos.noarch
centreon-common-19.10.1-3.el7.centos.noarch
centreon-engine-extcommands-19.10.6-3.el7.centos.x86_64
centreon-widget-httploader-19.10.0-1.el7.centos.noarch
centreon-broker-cbd-19.10.1-1.el7.centos.x86_64
centreon-auto-discovery-server-19.10.0-2.el7.centos.noarch

***Operating System***

CentOS Linux release 7.7.1908 (Core)
Linux srvgazer 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

***Browser used***
- [ ] Google Chrome


Version: Latest

***Additional environment details (AWS, VirtualBox, physical, etc.):***
Physical

### Description

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Fresh install  via rpm
2. Start applications 
3. Start configuration until step7

### Describe the received result
Freeze at step 7

### Describe the expected result
Step to 8
### Logs

**PHP error logs**

```
No centreon-error.log
```
**centreon-engine logs (*if needed*)**

```
tail -f /var/log/centreon-engine/centengine.log
```
**centreon-broker logs (*if needed*)**

```
[1574155612] error:   storage: could not fetch index list from data DB: could not execute query: Table 'centreon.rt_index_data' doesn't exist QMYSQL: Unable to execute query (SELECT index_id       , host_id, service_id, host_name,       rrd_retention, service_description, special,       locked FROM rt_index_data)
[1574155612] error:   SQL: could not get the list of outdated instances: could not execute query: Table 'centreon.rt_instances' doesn't exist QMYSQL: Unable to execute query (SELECT instance_id  FROM rt_instances WHERE outdated=TRUE)
[1574155612] info:    file: opening new file '/var/lib/centreon-broker//central-broker.queue.central-broker-correlation'
[1574155612] info:    file: end of file '/var/lib/centreon-broker//central-broker.queue.central-broker-correlation' reached, erasing file
[1574155612] info:    file: opening new file '/var/lib/centreon-broker//central-broker.cache.central-broker-correlation'
[1574155612] error:   parsing error on '/etc/centreon-broker/correlation.xml': No such file or directory

```
**centcore logs (*if needed*)**

```
[2019-11-19 09:42:01] SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
PHP Notice:  Undefined variable: conf_centreon in /usr/share/centreon/cron/centAcl.php on line 45
PHP Warning:  Use of undefined constant hostCentreon - assumed 'hostCentreon' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 89
PHP Warning:  Use of undefined constant hostCentstorage - assumed 'hostCentstorage' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 90
PHP Warning:  Use of undefined constant user - assumed 'user' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 91
PHP Warning:  Use of undefined constant password - assumed 'password' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 92
PHP Warning:  Use of undefined constant db - assumed 'db' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 93
PHP Warning:  Use of undefined constant dbcstg - assumed 'dbcstg' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 94
PHP Warning:  Use of undefined constant port - assumed 'port' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 95
[2019-11-19 09:43:01] SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
PHP Notice:  Undefined variable: conf_centreon in /usr/share/centreon/cron/centAcl.php on line 45
PHP Warning:  Use of undefined constant hostCentreon - assumed 'hostCentreon' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 89
PHP Warning:  Use of undefined constant hostCentstorage - assumed 'hostCentstorage' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 90
PHP Warning:  Use of undefined constant user - assumed 'user' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 91
PHP Warning:  Use of undefined constant password - assumed 'password' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 92
PHP Warning:  Use of undefined constant db - assumed 'db' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 93
PHP Warning:  Use of undefined constant dbcstg - assumed 'dbcstg' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 94
PHP Warning:  Use of undefined constant port - assumed 'port' (this will throw an Error in a future version of PHP) in /usr/share/centreon/www/class/centreonDB.class.php on line 95
[2019-11-19 09:44:01] SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
[2019-11-19 09:45:02] SQLSTATE[HY000] [1045] Access denied for user 'centreon'@'localhost' (using password: YES)
[2019-11-19 09:46:01] SQLSTATE[HY000] [1045] Access denied for user 'centreon'@'localhost' (using password: YES)
[2019-11-19 09:47:01] SQLSTATE[HY000] [1045] Access denied for user 'centreon'@'localhost' (using password: YES)
[2019-11-19 09:48:01] SQLSTATE[HY000] [1045] Access denied for user 'centreon'@'localhost' (using password: YES)

```

### Additional relevant information (e.g. frequency, ...)

**Comment by LeDOC666** [comment]
Problem is with password: If I change password on configuration, centreon_storage take the good password, but centreon user use centreon password.
So unable to connect to database.

I tested with centreon as database user password, and the step continu.

**Comment by lpinsivy** [comment]
can't reproduce

**Comment by eliebenayoun** [comment]
I have the same problem on all new version of Centreon. I have open a issue for this but nobody answer. 
I think you have a better explanation on what arrive here. But all new user can meet this problem. And ITS AN IMPORTANT ISSUE.
