### ISSUE TITLE
ACL: after upgrade to 19.04.5 only hosts are shown without any services

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#8152]
Centreon 19.04.5

We have users with limited resource access through a ACL, which is filtering by hostgroup. Users with this ACL cannot see more the services for this hosts.
This issue is related to the upgrade to Centreon 19.04.5, with 19.04.4 services are shown correctly.

![image](https://user-images.githubusercontent.com/6400595/69609956-04e55d00-102b-11ea-9736-4d5dda0bc0fb.png)

**Comment by joschi99** [comment]
Maybe related to https://github.com/centreon/centreon/pull/8146?

**Comment by adr-mo** [comment]
Hi @joschi99 

Thanks for the feedback :100: 

As you see we are aware of the issue and a version will be released **ASAP**.
Keep tuned to the release

Regards,

**Comment by cgagnaire** [comment]
Hi @joschi99,
You can find a new version in our stable repos.
Regards.
