### ISSUE TITLE
Status "Unknown" for services 

### ISSUE THREAD

**Issue by kastu707** [centreon/centreon#8157]
Hi all, 

I'm running Centreon 19.04 for one of my client. The central is on AWS and the poller on VMWARE inside the client network (so behind a FW). Both running Centos 7.
We have a firewall rule with a NAT to make sure the central and the poller communicate together through SSH.
Everything seems to work fine. I have the availability of all the network devices that I monitor but all the service that use to work before (I migrated the poller VM from another DC) and I keep getting Status unknown (No output returned from plugin). I checked the path for the nagios plugins and  everything looks good to me. 
So here's my question: **can I use the command line to check if my plugin is really working? Should I run it on my poller or the central? I'm a complete novice here and I'm not sure to understand how the full communication works between the both centreon component for SNMP trap.** Documentation is pretty dry and I didn't manage to get a clear answer by myself. 

Thanks a lot!
K.

**Comment by adr-mo** [comment]
Hi @kastu707 

Thanks for the feedback :100: 

> can I use the command line to check if my plugin is really working?

Yes, you just need to
* Go on Monitoring -> Status Details -> Services.
* Then open the detail of the service you want to check
* And you'll see the check command detail with a copy to clipboard button that you can execute on the server.

Here is an example for our demo site.

![image](https://user-images.githubusercontent.com/31647811/70426512-7386d980-1a73-11ea-8ad4-fd2d86b9caa0.png)

Do not hesitate to close the issue if I've answered your question :+1: 

Regards

**Comment by lpinsivy** [comment]
Run command line using 'centreon-engine' user to check rights

**Comment by cgagnaire** [comment]
Looks like given help was a success!
