### ISSUE TITLE
[19.10 - API REST] - APIs V2 do not work with a source installation 

### ISSUE THREAD

**Issue by kermith72** [centreon/centreon#8175]
Installation by sources

The configuration is missing in the apache configuration file

Solution

It is necessary to modify the libinstall/functions file

function prepare_apache_config()

[function_prepare_apache.txt](https://github.com/centreon/centreon/files/3925712/function_prepare_apache.txt)

**Comment by lpinsivy** [comment]
Hi @kermith72 , can you prepare a pull request with this change?

Regards,

**Comment by kermith72** [comment]
it's done : https://github.com/centreon/centreon/pull/8188
