### ISSUE TITLE
rrdcached not starting up

### ISSUE THREAD

**Issue by IdrissaHilda** [centreon/centreon#8176]
### Prerequisites

> I have install centreon rrdcached as the documentation indicates.
https://documentation.centreon.com/docs/centreon/en/19.10/faq/performance.html
***Versions***
19.10
For the RPM based systems
using packages for the installation of centreon

***Operating System***

Centos 7

***Additional environment :***

Virtual Machine

```
systemctl status rrdcached
```
![image](https://user-images.githubusercontent.com/56160040/70221081-ed535600-1747-11ea-85cc-c338fc2189c4.png)

```
tailf /var/log/centreon-broker/central-rrd-master.log
```
**
Centreon Broker 19.10.0 log file opened
[1575391830] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
**

The graphics are drawn as if rrdcached is not enabled, I don't know which file log or configuration, I have to go to see to solve this problem.

**Comment by lpinsivy** [comment]
Hi,

to use RRDCacheD with Centreon, you need to [configure Centreon Broker](https://documentation.centreon.com/docs/centreon/en/latest/faq/performance.html#centreon-web-configuration) to use it.

Then you need to generate the configuration of your poller and restart **cbd** process

**Comment by IdrissaHilda** [comment]
Hi,
Like I say I followed the procedure, I have configured Centreon Broker, I generate the configuration from the interface and I have restarded cbd process.
I didn't notice any changes, moreover in the file "/etc/centreon-broker/poller-module.xml", there are no entries concerning the configuration of rrdCcahed.
Like you can see with the picture

![image](https://user-images.githubusercontent.com/56160040/70789115-b78b1e80-1d92-11ea-9be3-2d069c7cd972.png)

![image](https://user-images.githubusercontent.com/56160040/70789165-cb368500-1d92-11ea-9323-b2186e36b655.png)

![image](https://user-images.githubusercontent.com/56160040/70789194-d8537400-1d92-11ea-9b2b-f039ccf9dcce.png)

I no longer have any ideas as to cause of the malfunction.

**Comment by lpinsivy** [comment]
Hi @IdrissaHilda ,

The configuration of Centreon Broker to use RRDCacheD has to be done for the Centreon Broker RRD module as defined is this [schema](https://documentation.centreon.com/docs/centreon/en/latest/installation/architecture/03a.html#architecture).

The "poller-module" is the Centreon Broker client used by Centreon Engine to forward collected data.

Regards,

**Comment by IdrissaHilda** [comment]
Hi, 
I'm sorry , I was wrong about the file I wanted to show you.
As a first step , here is a screen of the configuration of the central-rrd.

![image](https://user-images.githubusercontent.com/56160040/70792095-c8d72980-1d98-11ea-9c0a-9b175b91f074.png)

And here is the file output " more /etc/centreon-broker/central-rrd.xml"

![image](https://user-images.githubusercontent.com/56160040/70792256-19e71d80-1d99-11ea-9fe8-22e3caf95666.png)

And the tag for rrdcached, we don't find it in the file.
Regards,

**Comment by lpinsivy** [comment]
Did you generate the configuration of your "Centreon Central server" and move it ?

**Comment by IdrissaHilda** [comment]
Yes, I did it.

![image](https://user-images.githubusercontent.com/56160040/70793460-a4308100-1d9b-11ea-99ea-c5d6aec3380d.png)

And just after that
`/usr/bin/systemctl restart cbd`

And as you can see, rrdcached run
`/usr/bin/systemctl status rrdcached`

![image](https://user-images.githubusercontent.com/56160040/70793694-35075c80-1d9c-11ea-9f80-5a85a9a80135.png)

**Comment by lpinsivy** [comment]
Hi @IdrissaHilda can you check in "Administration > Platform Status > Broker Statistics" menu for the Centreon Broker RRD the statistics and check that ihe process manage events?

![rrd_broker](https://user-images.githubusercontent.com/3351916/71160212-6e7e1300-2247-11ea-8d3b-8bdf3b6d777f.png)

**Comment by IdrissaHilda** [comment]
Hi @lpinsivy when I go to check "Administration > Platform Status > Broker Statistics", here is the result:
![image](https://user-images.githubusercontent.com/56160040/71160953-cb2dfd80-2248-11ea-8316-a24487dbe506.png)

**Comment by lpinsivy** [comment]
Do you have error in /var/log/centreon-broker/central-rrd-master.log file?

Can you enable RRD debug through "Administration > Parameters > Debug" and check in /var/log/centreon/rrdtool.log if you have error when you try to display a chart?

**Comment by IdrissaHilda** [comment]
Here are the results of different orders
`tailf /var/log/centreon-broker/central-rrd-master.log`

![image](https://user-images.githubusercontent.com/56160040/71162306-42649100-224b-11ea-803f-66ae76ce9cd5.png)

`tailf /var/log/centreon/rrdtool.log`

![image](https://user-images.githubusercontent.com/56160040/71162889-4d6bf100-224c-11ea-8128-6b31aac3326c.png)

>Neither command returns errors

**Comment by lpinsivy** [comment]
So everything look perfect.

You can see your curve in your chart? When You try to see chart, Centreon send a FLUSH command to RRDCacheD to flush it memory into RRDfile than Centreon can display them.

Regards,

**Comment by IdrissaHilda** [comment]
Hi @lpinsivy ,

I agree with you, the chart are well drawn but with the basic parameters of rrdCcahed. Each five minutes, the data is plotted.

Like you can see with the picture, here are the rrdcached parameters and  I would like it to take into account:
-w 1800 , the data are written every 1800 seconds on disk 
-z | Should be less than -w option. RRDCacheD uses a range value from [0:-z] to do not write in RRDs in same time.
-f | Timeout in cache before write data to disk.

`more /etc/sysconfig/rrdcached`

![image](https://user-images.githubusercontent.com/56160040/71247499-321ae780-2319-11ea-9b2a-d4262f4ccc42.png)

`/usr/bin/systemctl status rrdcached`

![image](https://user-images.githubusercontent.com/56160040/71247722-9ccc2300-2319-11ea-95a6-dadbb5b0a953.png)

Here is a chart capture to see how the parameters are taken into account.

![image](https://user-images.githubusercontent.com/56160040/71248178-8e323b80-231a-11ea-9ed5-5dcbf50fe1d0.png)

**Comment by lpinsivy** [comment]
IF you don't display chart, these parameters will be take account by RRDCAcheD.

But Centreon send flush command when user want to see a chart to display all values ;)

Regards,

**Comment by IdrissaHilda** [comment]
Hi @lpinsivy ,
The result I'm waiting for is the result announced in the documentation, as you can see with the capture.

![image](https://user-images.githubusercontent.com/56160040/71352992-0b0e2100-2578-11ea-9507-30157cfd1355.png)

Regards,

**Comment by lpinsivy** [comment]
Hi @IdrissaHilda thank to report this. The documentation is not up to date because we added a long time ago a command to sync RRDCacheD data with FS before to display charts.

I will update the documentation.
