### ISSUE TITLE
servicegroup_member hostgroup_member not supported in centreon

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#818]
---

Author Name: **John Alberts -** (John Alberts -)
Original Redmine Issue: 2028, https://forge.centreon.com/issues/2028
Original Date: 2010-11-03

---

There doesn't appear to be a way to add service groups that contain other service groups.  Nagios allows you to do this with the 'servicegroup_members' attribute.  http://nagios.sourceforge.net/docs/3_0/objectdefinitions.html#servicegroup

The same appears to be true for hostgroup_members attribute.
http://nagios.sourceforge.net/docs/3_0/objectdefinitions.html#hostgroup

This is an extremely important feature for larger installations as without the ability to next service and host groups, it makes configuration changes very tedious and error prone.

**Comment by PepeOnAChair** [comment]
Hello,

I`m trying to migrate from Nagios 4.4.5 to Centreon 21.10.3 and I can not find howto define "sub hostgroup" for a hostgroup:

For organizing thousands od devices/hosts in different locations this feature is quite essential. This is how it works in Nagios config files:

_define hostgroup{
	hostgroup_name		:: main hostgroup
	alias				"some alias"
	hostgroup_members		:: some sub-hostgroup1,:: some sub-hostgroup2,:: some sub-hostgroup3
	notes				note_string
	notes_url
	action_url
	}
	define hostgroup{
		hostgroup_name		:: some sub-hostgroup1
		alias				devices in smaller group
		members			host1,host2,host3,...
		notes				some note
		notes_url 
		action_url 
		}_

For example in our use-case, hosts in ":: main hostgroup" are hosts in whole town. And hosts in ":: some sub-hostgroup1" are devices from just one street in that town. This makes it easy to filter devices depending on "scale/view" of the town.

I`ve found something here:
https://docs-older.centreon.com/docs/centreon-engine/en/1.8/user/configuration/basics/object_definitions.html#obj-def-hostgroup
is some text about "hostgroup_members", but that is all I was able to find.

Is it possible in Centreon to group the hostgroups into hostgroups using "hostgroup_members" as it is possible in Nagios?

Thank you
Pep.
