### ISSUE TITLE
Import / export template (including check command and plugin)

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#821]
---

Author Name: **Jean-Baptiste Lamotte** (Jean-Baptiste Lamotte)
Original Redmine Issue: 1206, https://forge.centreon.com/issues/1206
Original Date: 2009-09-18

---

It could be interesting to add a feature, for importing / exporting host or service template.

When you export a template, it include all parent template, associated check command, and check plugin.
When you import a template, it create all needed parent, associated check command, and add check plugin.

Need also the ability to handle conflict with existing template. (merge or duplicate).

With a such system, it become possible to provide extra small package, including check plugin, check command, and template to quickly use and deploy the new plugin.

**Comment by lpinsivy** [comment]
Should be OK.

Please read the documentation: https://documentation-fr.centreon.com/docs/centreon/en/2.8.x/api/clapi/import_export.html#export-of-a-subset-of-objects
