### ISSUE TITLE
Cannot install from source

### ISSUE THREAD

**Issue by sdelafond** [centreon/centreon#8222]
Version=19.10.4, from GitHub tarball.

The webpack.config.js file is missing, so npm build fails because it has no clue where to look. After adding it from a tarball fetched from download.centreon.com, another error comes up because babel is not configured for dynamic imports. Copying .babelrc from the tarball fixes that, and the install can then proceed correctly.

**Comment by lpinsivy** [comment]
Hi @sdelafond those fils is missing from git clone? where do you download the Centreon sources?

Regards

**Comment by sdelafond** [comment]
From https://github.com/centreon/centreon/releases.
