### ISSUE TITLE
Icinga - Acknowledge with expire time

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#823]
---

Author Name: **Gavin Williams** (Gavin Williams)
Original Redmine Issue: 2842, https://forge.centreon.com/issues/2842
Original Date: 2011-11-30
Original Assignee: Sylvestre Ho

---

Now that Icinga 1.6.0 has been released, it would be great for Centreon to support the following new feature:
Acknowledge with expire time - #770 (https://dev.icinga.org/issues/770).

**Comment by querwin** [comment]
- Impossible to add this in service template
- The help message is missing
- In host an host template configuration : * 60 seconds is missing
- FR traduction is missing
