### ISSUE TITLE
Centreontrapd : Error code not documented

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#8237]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***

Centreon 19.04.07

### Description
On my Central server :

` cat centreontrapd.log

2020-01-06 09:56:58 - ERROR - 732 - Mode: central server

2020-01-06 09:58:59 - ERROR - 10496 - Mode: central server
`

### Steps to Reproduce
Don't know...

### Describe the expected result
We need a explicit message for each error,  or a place in the documentation where the error are listed with their code and their meanings.

**Comment by garnier-quentin** [comment]
it's not an error. we should use writeLogInfo
