### ISSUE TITLE
Paginate for rest api centreon 2.8.16

### ISSUE THREAD

**Issue by thanhtung6824** [centreon/centreon#8241]
I'm using centreon version 2.8.16. I tried to get list host by use this rest api: `api.domain.tld/centreon/api/index.php?action=action&object=centreon_clapi`

Here is my body: 
```
{
  "action": "show",
  "object": "HOST",
  "page": 1,
  "limit": 1
}
```

It still get all list host. How can I add page and limit for this?

**Comment by lpinsivy** [comment]
Hi @thanhtung6824 unfortunately, API v1 for configuration doesn't support pagination.

We are starting API v2 fir Centeron >= 19.10.x but currently only real time is available.

Regards,
