### ISSUE TITLE
Add new poller : TCP: could not connect to X.X.X.X:5669: Socket operation timed out

### ISSUE THREAD

**Issue by Brownie9** [centreon/centreon#8247]
Hi,

I added a new poller with an ISO image.
When I want to start it for the first time, it doesn't start.

If I type this command : 
tail -f /var/log/centreon-broker/poller-module.log

I receive this output : 
[1578584112] [0x7f049288b700] error:   TCP: could not connect to 192.168.88.8:5669: Socket operation timed out

The firewall is disable and I can ping 192.168.88.8 
I don't understand what i need to do.

**Comment by lpinsivy** [comment]
Hi @Brownie9 , I suppose that 192.168.88.8 is the IP address of your central server, right?

Can you check if the Centreon Broker Master on your central server is listening on 5669 port for 192.168.88.8 address using netstat?

**Comment by cgagnaire** [comment]
Hi @Brownie9,
Do you still have the problem?
