### ISSUE TITLE
Installing from source results in incomplete install.conf.php

### ISSUE THREAD

**Issue by sdelafond** [centreon/centreon#8249]
In createConfFile(), the key "centreon_cachedir" is not filled:

  https://github.com/centreon/centreon/blob/3824725eb0d0d71c1495b344d95b94d14c3afb90/libinstall/functions#L1613

The web installer however requires it:

  `AH01071: Got error 'PHP message: PHP Notice:  Undefined index: centreon_cachedir in /usr/share/centreon/www/install/steps/process/configFileSetup.php on line 76'`

Interestingly enough, `www/install/install.conf.dist.php` contains the key, but it doesn't seem to be used at all during the install process.

**Comment by cgagnaire** [comment]
Indeed the key is missing.
I don't really know about install.conf.dist.php.

**Comment by cgagnaire** [comment]
Fixed since https://github.com/centreon/centreon/pull/8341 and should be better with https://github.com/centreon/centreon/pull/9507
