### ISSUE TITLE
Installing from source results in missing container.php

### ISSUE THREAD

**Issue by sdelafond** [centreon/centreon#8250]
`libinstall/CentWeb.sh` properly copies bootstrap.php to the final install folder, but container.php is never copied. The web install cannot be performed because of this:

  `AH01071: Got error 'PHP message: PHP Warning:  require_once(/usr/share/centreon/container.php): failed to open stream: No such file or directory in /usr/share/centreon/bootstrap.php on line 65PHP message: PHP Fatal error:  require_once(): Failed opening required '/usr/share/centreon/container.php' (include_path='/usr/share/centreon/vendor/pear/pear_exception:/usr/share/centreon/vendor/pear/console_getopt:/usr/share/centreon/vendor/pear/pear-core-minimal/src:/usr/share/centreon/www/class:/usr/share/centreon/www/lib:.:/usr/share/php') in /usr/share/centreon/bootstrap.php on line 65'`

**Comment by cgagnaire** [comment]
Already fixed here https://github.com/centreon/centreon/pull/8180
