### ISSUE TITLE
Installing from source doesn't copy .env* into destination dir

### ISSUE THREAD

**Issue by sdelafond** [centreon/centreon#8252]
.env (and possibly .env.config.php) are never copied into the destination directory, resulting in symfony errors at install time.

**Comment by cgagnaire** [comment]
.env is copied since https://github.com/centreon/centreon/pull/8180, but .env.local.php might be missing.

**Comment by cgagnaire** [comment]
Also, the APP_SECRET should be replaced by a random string.

**Comment by cgagnaire** [comment]
Fixed by https://github.com/centreon/centreon/pull/8341.
