### ISSUE TITLE
Event logs fed at every check

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon#8259]
Hi,

Let's add a new service and reload engine.
Service will show in event logs only when its status will change.
Perfect.

Let's rename this service, or simply change its options, and reload engine.
Service will now show in event logs at every check.

Same issue when updating a service template and reloading the engine.

This makes event logs painfully readable...

The only solution is then to restart the engine.

Could we then fix this please ?

Thank you :+1:

Edit : issue still present in 19.10.4.

**Comment by cgagnaire** [comment]
Hi,
Can you validate that stalking options enable itselfs by running this query after a reload:
`SELECT stalk_on_critical, stalk_on_ok, stalk_on_unknown, stalk_on_warning FROM services WHERE service_id = <id of service>\G`
Thank you.

**Comment by cgagnaire** [comment]
Thank you.
I have notified the Engine team.

**Comment by SylvestreG** [comment]
fix in https://github.com/centreon/centreon-engine/pull/340
