### ISSUE TITLE
No folder /usr/share/centreon/installDir/install-19.10.0-YYYYMMDD_HHMMSS

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon#8263]
Hello,

I migrated from Centreon 3.4 to Centreon 19.10. In the last step of documentation, the server update is not possible because the /usr/share/centreon/installDir folder is missing.
```
cd /usr/share/centreon/installDir/
-bash: cd: /usr/share/centreon/installDir/: Aucun fichier ou dossier de ce type
```
I have only this :
`/var/lib/centreon/installs/install-19.10.4-20200116_103521`

Is there another way to perform this step? Or fix it ?

Thank you

**Comment by lpinsivy** [comment]
Hi @boogaaloo, this directory is used to move /usr/share/centreon/www/install to /usr/share/centreon/installDir at the end of installation.

What is your problem?

**Comment by boogaaloo** [comment]
I'm trying to perform a centreon migration from Centreon 3.4 to Centreon 19.10 using the documentation. At the end of this documentation, it's explained :

> On the new server, force the update by moving the contents of the /usr/share/centreon/installDir/install-19.10.0-YYYYMMDD_HHMMSS directory to the /usr/share/centreon/www/install directory:
https://documentation.centreon.com/docs/centreon/en/latest/migration/upgradetoCentreon19.10.html

So, the last step (the server update) is not possible because the /usr/share/centreon/installDir folder is missing.

**Comment by lpinsivy** [comment]
When you performed this step: https://documentation.centreon.com/docs/centreon/en/latest/migration/upgradetoCentreon19.10.html#installing-the-new-server
Did you success to connect to the web UI after performing web instalaltion? https://documentation.centreon.com/docs/centreon/en/latest/installation/from_iso.html#configuration

**Comment by boogaaloo** [comment]
That's right. I success to connect to the web UI after installing Centreon web.

**Comment by boogaaloo** [comment]
A little help would be appreciated :)
Thanks

**Comment by anthoc** [comment]
Hello
I came across the problem few minutes ago while trying to upgrade from 3.4 to 19.10 too. 
Something seems to be missing in the documentation (which in one of the best I ever used to upgrade a software by the way). 
I managed to bypass the problem by creating the /usr/share/centreon/www/install directory and copying the entire content of the install directory (/var/lib/centreon/installs/install-19.10.7-20200217_142117, which I found thanks to this topic) in it.

**Comment by boogaaloo** [comment]
Hi Anthoc,

Thank you for your answer and solution.
However once the files are copied and the update done, I'm stuck on a /centreon/install/upgrade.php url.
Did you have this problem?
I guess that some files need to be deleted...

**Comment by anthoc** [comment]
> Hi Anthoc,
> 
> Thank you for your answer and solution.
> However once the files are copied and the update done, I'm stuck on a /centreon/install/upgrade.php url.
> Did you have this problem?
> I guess that some files need to be deleted...

Do Centreon display an error message in this webpage ? 
Did you checked the permissions on the install directory ? I thni that the folder have to belongs to "apache" user.

**Comment by boogaaloo** [comment]
Probably a permissions issue but the update (19.10.7) put everything back in order.
Thank you ;)

**Comment by cgagnaire** [comment]
Thanks!
