### ISSUE TITLE
Can't locate centreon/plugins/script.pm in @INC

### ISSUE THREAD

**Issue by Myaww** [centreon/centreon#8271]
Hey,

I have a problem with my monitoring server:

I want to monitor my ESXi, I have installed the perl SDK. Install the connector, configure my /etc/centreon/centreon_vmware.pm file ...

**and whe I run this :**
perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --mode=tools-vm --verbose

**I have this error :**
Can't locate centreon/plugins/script.pm in @INC (@INC contains: /usr/lib/centreon/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at centreon_plugins.pl line 29.
BEGIN failed--compilation aborted at centreon_plugins.pl line 29.

**Here is my logs in /var/log/centreon/centreon_vmware.log:**
Use of uninitialized value in transliteration (tr///) at /usr/local/share/perl5/VMware/VICommon.pm line 491.
2020-01-21 13:46:10 - 'default' Login to VirtualCenter server failed: Undefined subroutine &URI::_generic::host called at /usr/local/share/perl5/VMware/VILib.pm line 277.

**But this command work :** 
/root/vmware-vsphere-cli-distrib/apps/general/connect.pl --server 10.11.10.99

**and return this :** 
length() used on @array (did you mean "scalar(@array)"?) at /usr/lib64/perl5/IO/Compress/Zlib/Extra.pm line 198, <STDIN> line 2.

Connection Successful
Server Time : 2020-01-21T13:48:51.649733Z

If someone can help me to decrypt the logs / command output :)

Thank you

**Comment by lpinsivy** [comment]
Hi @Myaww ,

did you install Centreon Plugin using a git clone?

**Comment by Myaww** [comment]
Hi,

I have istalled my plugins with the web UI, i have a .pl for each plugin.

But i see on many website, tutorials forums ... people use only the 'centreon_plugin.pl'
Is that the git version of plugins ?

I have both :
![Capture](https://user-images.githubusercontent.com/59284023/73080103-93f4e100-3ec5-11ea-8fe0-2fcc1eb75f00.PNG)

But i use only basic plugins (like 'centreon_mssql.pl' ....)

Thank you for your time, if you need more informations you can ask me :)

**Comment by Myaww** [comment]
Hey,

I have re installed all the setup, and it work now.

I think that my command was wrong, it work with this command:

/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=cpu-host --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default' --verbose
