### ISSUE TITLE
rrdcached does not start

### ISSUE THREAD

**Issue by IdrissaHilda** [centreon/centreon#8283]
> I have install centreon rrdcached as the documentation indicates.
https://documentation.centreon.com/docs/centreon/en/19.10/faq/performance.html
Versions
19.10
For the RPM based systems
using packages for the installation of centreon.

_**Operating System**_

Centos 7

**_Additional environment :_**

Virtual Machine

```
systemctl status rrdcached
```
When I compare the result of this command and the result of documentation I see a difference.

![image](https://user-images.githubusercontent.com/56160040/73052769-355c4280-3e86-11ea-8bc7-c0da7b97c017.png)

I just have one line "systemd[1]: Started Data caching daemon for rrdtool."
Whereas in the documentation we have 4 command lines that run.

![image](https://user-images.githubusercontent.com/56160040/73053093-21651080-3e87-11ea-9a19-651a40c7284f.png)

Another thing I have noticed, when I list the contents of the directory /var/rrdtool/rrdcached

![image](https://user-images.githubusercontent.com/56160040/73053459-18c10a00-3e88-11ea-8f30-ef7af75859f8.png)

I noticed that the "rrdcached.sock= " file is zero , as you can see and I don't known if it's normal.

**The centreon web configuration has been successfully completed.**

**Comment by lpinsivy** [comment]
Hi @IdrissaHilda 

On Centreon 19.10.x and rrdtool 1.7.2 I have:

```
# systemctl status rrdcached
● rrdcached.service - Data caching daemon for rrdtool
   Loaded: loaded (/etc/systemd/system/rrdcached.service; enabled; vendor preset: disabled)
   Active: active (running) since ven. 2020-01-24 11:20:26 CET; 5s ago
     Docs: man:rrdcached(1)
 Main PID: 25968 (rrdcached)
   CGroup: /system.slice/rrdcached.service
           └─25968 /usr/bin/rrdcached -m 664 -l unix:/var/rrdtool/rrdcached/rrdcached.sock -s rrdcached -b /var/rrdtool/rrdcached -w 7200 -f 14400 -z 3600 -p /var/rrdtool/rrdcached/rrdcached.pid

janv. 24 11:20:26 centreon-demo-back systemd[1]: Started Data caching daemon for rrdtool.
```

And:
```
# ls -lah /var/rrdtool/rrdcached/
total 20K
drwxrwxrwx 2 rrdcached rrdcached 126 12 janv. 15:12 .
drwxrwxrwx 3 rrdcached rrdcached  23 26 oct.   2018 ..
-rwxrwxrwx 1 rrdcached rrdcached 426 26 oct.   2018 .bash_history
-rwxrwxrwx 1 rrdcached rrdcached  18 11 avril  2018 .bash_logout
-rwxrwxrwx 1 rrdcached rrdcached 193 11 avril  2018 .bash_profile
-rwxrwxrwx 1 rrdcached rrdcached 231 11 avril  2018 .bashrc
-rw-r--r-- 1 rrdcached rrdcached   4 12 janv. 15:12 rrdcached.pid
srw-rw-r-- 1 rrdcached rrdcached   0 12 janv. 15:12 rrdcached.sock
```

So rrdcached seems to be started correctly. Can you check the log of /var/log/centreon-broker/central-rrd.log to know if any errors appear?

**Comment by IdrissaHilda** [comment]
I don't have any error in the log file.

How I can know it's set up right and working? 
As I can see in the last version of rrdcached when it's installed. RRDCacheD don't update performances graphs in real time.
If a blank range appears on right of performances graphs it means that cache are not yet written to disk.

**Comment by lpinsivy** [comment]
@IdrissaHilda ,

Before to display graph, Centreon send a flush command to rrdcached to write memory on disk.
Can you check on "Monitoring > Performance" that your graph displayed are up to date?

Regards,

**Comment by IdrissaHilda** [comment]
Hi @lpinsivy ,

When I go to check "Monitoring > Performance" I don't have a Graph that displays.
As you can see,
![image](https://user-images.githubusercontent.com/56160040/73340461-0d505300-427b-11ea-86c2-8412ab9f26ad.png)

And I don't have an error in the **central-rrd.log** file
