### ISSUE TITLE
centreon_storage.services.perfdata: Data too long for column 'perfdata' - Broker stop working

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#8300]
Centreon 19.10.4
OS: CentOS 7.7
MariaDB: 10.2.30

Centreon Broker **blocks** completely, because the performance datas from `database::mysql::plugin --mode=databases-size` causes the error:
`[1580384716] [0x7fdf56fd4700] error:   SQL: could not store service status (host: 103, service: 491): could not execute prepared statement: Data too long for column 'perfdata' at row 1 QMYSQL3: Unable to execute statement`

If we change the column type from "TEXT" to "MEDIUMTEXT" on centreon_storage.services.perfdata the Broker starts working again.

**Comment by lpinsivy** [comment]
Hi @joschi99, Yes with active Strict Mode we have issue. We are fixing this

**Comment by omercier** [comment]
Hi Jochen,
I am closing the issue, since this has been fixed since [20.04.9](https://docs.centreon.com/20.04/en/releases/centreon-core.html#20049-2) / [20.10.0](https://docs.centreon.com/20.10/en/releases/centreon-core.html#20100-2).
Regards
