### ISSUE TITLE
UNKNOWN: no output returned from plugin  |  Command work in CLI

### ISSUE THREAD

**Issue by Myaww** [centreon/centreon#8301]
Hello,

I have a problem when i try to monitor the Trafic on my moxa switches:

In centreon, i create my command, host, services and i have:
![Capture](https://user-images.githubusercontent.com/59284023/73462031-6ef7e680-437b-11ea-9017-15f2d2df2a9d.PNG)

But in the CLI, the command work well. I use this command for a long time and it worked well :c so i don't think it's the command..

My centreon server and the switch had a different time, but i change that and put them on the same ntp server, same timezone ... and it still doesn't work.

If someone have an idea :), thank you

**Comment by Myaww** [comment]
I think that the command return too much data, so I changed it to check only 1 interface on my moxa switchs, but now i have this message:

UNKNOWN: No entry found (maybe you should reload cache file)


I check others netgear switchs with the 'same' command and it work well ...


I tryed to reboot / reload the cache / i only test my commands with centreon user, and it still don't work :(

**Comment by tanguyvda** [comment]
Hello, 

could you please send us the command you're executing (remove any ip address, snmp community, passphrase and such)

**Comment by Myaww** [comment]
I find the solution :) !

I juste change thoses parameters from ifName to ifDesc and it work: 
	--oid-filter ifDesc
	--oid-display ifDesc

The complete command
./centreon_moxa_switch_snmp.pl
	--plugin=network::moxa::switch::snmp::plugin
	--mode=interfaces
	--host=X.X.X.X
	--snmp-version=2c
	--snmp-community=XXXXXX
	--warning-in-traffic=50
	--critical-in-traffic=80
	--warning-out-traffic=50
	--critical-out-traffic=80
	--interface="G1$"
	--no-skipped-counters
	--name
	--add-traffic
	--add-status
	--oid-filter ifDesc
	--oid-display ifDesc
	--verbose
