### ISSUE TITLE
Migration Centreon 2.6 to Centreon 19.10

### ISSUE THREAD

**Issue by emjrod** [centreon/centreon#8328]
Hi, 
I am currently having a hard time finding in the official documentation the process to follow in order to migrate from Centreon 2.6 [Centreon Web:2.6.1, Centreon Broker:2.8.x, Centreon Engine:1.4.x] to Centreon 19.10.
My goal is to transfer from my server-Centreon 2.6 all the necessary data (ex. configuration of hosts, configuration of services, Pollers' data , hosts templates, services templates, commands, users settings,...) to my new server-Centreon 19.10 in order to ensure data continuity after migration. 

Is there an official way to migrate from Centreon 2.6 to Centreon 19.10 or at least to migrate from Centreon 2.6 to Centreon 3.4?
(If I could at least migrate to Centreon 3.4, then I would follow the documentation explaining how to migrate from Centreon 3.4 to Centreon 19.10 : https://documentation.centreon.com/docs/centreon/en/19.10/migration/upgradetoCentreon19.10.html)

Thank you

**Comment by lpinsivy** [comment]
Hi @emjrod 

You should migrate first from 2.8.x than use official documentation to migrate from 2.8.x (Centreon 3.4) to Centreon 20.04.x: https://docs.centreon.com/current/en/upgrade/upgrade-from-3-4.html

Regards
