### ISSUE TITLE
[remote server] Some unavailable monitoring options

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#8335]
Hi,

On a remote poller, the following parameters, usually found in _Administration  >  Parameters  >  Monitoring_, are not available for tuning :

![image](https://user-images.githubusercontent.com/40244829/74466556-bdd36f00-4e97-11ea-937a-037755e0511c.png)

And unfortunately, sounds like they do not inherit from the Central values.

At least, these options should be made available on Remote side, or they should inherit from the Central values.

There may be other options in the same situation.
Same sort of issue here : #8016, #8017

Thank you 👍

**Comment by UrBnW** [comment]
Any thoughts ?
Thx 👍

**Comment by lpinsivy** [comment]
REF MON-6024
