### ISSUE TITLE
network::cisco::smallbusiness::standard::snmp::plugin - Strange temperature result in my SG500 Cluster 

### ISSUE THREAD

**Issue by ChristophePelichet** [centreon/centreon#8348]
Dear Teams,

After a full upgrade yesterday morning from 19.04 to 19.10 , my CISCO SG-500 Cluster show a strange error with the temperature check : 

CRITICAL: Temperature '1' is 2 degree centigrade - Temperature '2' is 2 degree centigrade

After used the check command without warning or critical argument i have this answer : 

/usr/lib/centreon/plugins/centreon_cisco_smallbusiness.pl --plugin=network::cisco::smallbusiness::standard::snmp::plugin --mode=environment --hostname=xxx.xxx.xxx.xxx --snmp-version='1' --snmp-community='ma_community'  --component='temperature' --verbose

temperature '1' is 1 degree centigrade [instance = 1]
temperature '2' is 1 degree centigrade [instance = 2]
temperature '3' is 2 degree centigrade [instance = 3]
temperature '4' is 2 degree centigrade [instance = 4]
temperature '5' is 1 degree centigrade [instance = 5]

I think I understand that each instance is one of the switches in my cluster but the temperature is very strange. My cluster is on a datacenter and i have the same error with all SG-500 in my Centreon.

I have found this 3 oid in your script 

      rlPhdUnitEnvParamTempSensorValue                  => { oid => '.1.3.6.1.4.1.9.6.1.101.53.15.1.10' },
      rlPhdUnitEnvParamTempSensorWarningThresholdValue  => { oid => '.1.3.6.1.4.1.9.6.1.101.53.15.1.12' },
      rlPhdUnitEnvParamTempSensorCriticalThresholdValue => { oid => '.1.3.6.1.4.1.9.6.1.101.53.15.1.13' },

But when i try to use with snmpget i have this error 

[centreon@cldmongep03 plugins]$ snmpget -v1 -c my_community xxx.xxx.xxx.xxx .1.3.6.1.4.1.9.6.1.101.53.15.1.10
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SNMPv2-SMI::enterprises.9.6.1.101.53.15.1.1	

but I may not be using it correctly snmpget

**Plugin version in my poller :** 

centreon-plugin-Network-Cisco-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Switchs-Cisco-Smallbusiness-Standard-Snmp-20200204-093915.el7.centos.noarch

**snmpwalk** 

snmpwalk is in progress.

**Comment by garnier-quentin** [comment]
Please in centreon-plugins github ;)
