### ISSUE TITLE
[BUG] Downtime Parameters (Admin->Param->Monitoring) have no impact

### ISSUE THREAD

**Issue by flex-pgum** [centreon/centreon#8362]
# BUG REPORT INFORMATION
***Operating System***

CentOS

***Browser used***

- [x ] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 
latest 19.10 (19.10.7)
latest 19.04 (19.04.10)

### Description
<img width="573" alt="sas" src="https://user-images.githubusercontent.com/56337995/75139765-c0cb2c80-56ed-11ea-8c0e-e1543093b98c.png">

(Administration->Pramaeters->Monitoring)

With the setup from above, following happens when adding a downtime to a service/host in Monitoring->Status Details by selecting "Set Downtime" in the Actions:
<img width="335" alt="2020-02-24 09_07_05-Centreon - IT   Network Monitoring" src="https://user-images.githubusercontent.com/56337995/75139517-1d7a1780-56ed-11ea-8ed2-16a12d2fda1f.png">
* The Duration Input field should be activated
* The default duration from the parameters is not set, neither in the date/time picker nor in the duration field

**Comment by UrBnW** [comment]
Solved in #7606.

**Comment by sc979** [comment]
Hi @flex-pgum ,
The pull request with the modifications have been merged : https://github.com/centreon/centreon/pull/8486,
and will be merged on the specified next targeted version after validation.
Best Regards,
sc979
