### ISSUE TITLE
Centreon 2.8.27 enable LDAPS

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon#8370]
Hi all,
im trying to enable LDAPS connection in centreon but it's not working.
it working perfectly on normal LDAP with port 389.

When enabling SSL or TLS i receive this error

LDAP Connect: Bind: Can't contact LDAP server
LDAP Connect: connection error

I have RootCA and IntermediateCA certificate for ActiveDirectory but i don't know where to store them and in which format (.crt or .pem)

Thanks

**Comment by R00T88** [comment]
Hi all,
can someone help me out on this?

Microsoft will release a security patch next month to allow only LDAP connection over SSL

Thanks

**Comment by R00T88** [comment]
Hi all,
you can close fixed

**Comment by schif1** [comment]
Hello,

Can you give a description how do you solve that ?
Your answer could help the community with the same issue.

The workaround i found is editing the file "/etc/openldap/ldap.conf" and adding this line:
TLS_REQCERT never

If you have a more secure config, let share.

Thanks
