### ISSUE TITLE
centreon after upgrade from repo ask script from external server

### ISSUE THREAD

**Issue by arheops** [centreon/centreon#8377]
After update via yum i have all my links in index.html go to 

`<link rel="shortcut icon" href="http://51.77.91.132:1923/centreon/img/favicon.ico">`

Centos 7.

```
[centreon-stable-noarch]
name=Centreon open source software repository.
baseurl=http://yum.centreon.com/standard/18.10/el7/stable/noarch/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CES
```

**Comment by arheops** [comment]
Acordinly to httpd config seams like it never used, should be used index.php.
however index.php give zero output via apache(no errrors too) after login and login form via cli.

**Comment by arheops** [comment]
http://prntscr.com/r8w438

**Comment by arheops** [comment]
fix: open index.php and replace 51.77.91.132:1923 with your host/port.
But command, i start scary update centreon. This is second issue with update from start of year.

**Comment by StefThomas** [comment]
>But common, I am starting scary update centreon.

I do too. I hope they will work more on stabilization than on functionalities. :( 

Recently they introduced a bug in a revision update of 19.04, with a modification that should, imho, have been done on 19.10 only  (Encryptation of some Perl scripts). One should never introduce new functionalities on a revision update, especially when it breaks things…

Monitoring needs stability!
