### ISSUE TITLE
[BUG] End Time in "Add Downtime" has wrong default date

### ISSUE THREAD

**Issue by flex-pgum** [centreon/centreon#8383]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***

* 19.04.11
* 19.10.8

***Operating System***

* CentOS

***Browser used***

- [x] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

### Description
End time is wrong for browser language it (italian) and de (german) (see images below)
Could possibily affect other languages too. Problem is rather new, maybe 3-4 patches old.

(it)
![it](https://user-images.githubusercontent.com/56337995/75661740-254a3680-5c6e-11ea-8821-23246fabcfbd.png)
The end date is 3rd February instead of 2nd march

(de)
![de](https://user-images.githubusercontent.com/56337995/75661893-722e0d00-5c6e-11ea-9210-ece4cf9d5403.png)
The end date is 17 september 2025 instead of 2nd march

Also tested with other timezones.
Problem probably lies in www/include/common/javascript/datepicker/localizedDatepicker.js (function initDatepicker).. Start date input gets correct default value (as date instance), end date gets only a string for the default value, maybe this causes the problem if other date patterns are used.

Other interesting fact: Problem only occurs in Monitoring->Downtime->Add Downtime, not in the "Set Service/Host Downtime" Popup.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Change Browser language to de/it/others
2. Monitoring->Downtimes->Add Downtime

### Additional relevant information (e.g. frequency, ...)

No Javascript errors

**Comment by tmss999** [comment]
Hi,

same Problem..

tmss999

**Comment by UrBnW** [comment]
Solved in #7606.

**Comment by sc979** [comment]
Hi @flex-pgum , @tmss999 ,
The pull request with the modifications have been merged : https://github.com/centreon/centreon/pull/8486,
and will be merged on the specified next targeted version after validation.
Best Regards,
sc979
