### ISSUE TITLE
Ldap parameters filters make UI go crazy

### ISSUE THREAD

**Issue by leo5593** [centreon/centreon#8476]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

centreon-plugin-Hardware-Storage-Fujitsu-Eternus-Dx-Ssh-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Jenkins-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Jboss-Jmx-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Ovh-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Storagetek-Sl-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Sensormetrix-Em01-Web-20200204-093915.el7.centos.noarch
centreon-plugin-Discovery-Nmap-20181019-1.el7.noarch
centreon-plugin-Network-Huawei-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Switchs-Alcatel-Omniswitch-6850-20170329-1.el7.noarch
centreon-engine-daemon-19.10.13-1.el7.centos.x86_64
centreon-plugin-Network-Loadbalancers-Netscaler-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Switchs-Alcatel-Omniswitch-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Ruckus-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Juniper-Mag-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Beeware-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Pdu-Apc-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Loadbalancers-Kemp-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Nimble-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Netapp-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Hp-Ilo-Xmlapi-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Vtom-Restapi-20200204-093915.el7.centos.noarch
centreon-license-manager-19.10.1-3.el7.centos.noarch
centreon-plugin-Applications-Webservers-Tomcat-Jmx-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Voip-Asterisk-Ami-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Violin-3000-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Tcp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Netbotz-Snmp-20200204-093915.el7.centos.noarch
centreon-common-19.10.10-1.el7.centos.noarch
centreon-plugin-Network-Radware-Alteon-Snmp-20200204-093915.el7.centos.noarch
centreon-19.10.10-1.el7.centos.noarch
centreon-plugin-Network-Juniper-Isg-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Stormshield-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ds4000-Smcli-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Kvm-Avocent-Acs-6000-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Polycom-Rmx-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Generic-Bluecoat-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Oracle-Otd-Snmp-20200204-093915.el7.centos.noarch
centreon-broker-19.10.3-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ntp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-IBM-Tsm-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Udp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-X509-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Ruggedcom-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Compellent-Snmp-20200204-093915.el7.centos.noarch
centreon-database-19.10.10-1.el7.centos.noarch
centreon-plugin-Applications-Sendmail-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Cisco-Voice-Gateway-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Operatingsystems-Freebsd-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Pdu-Clever-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Oracle-Zs-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hitachi-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-widget-engine-status-19.10.0-1.el7.centos.noarch
centreon-plugin-Network-Audiocodes-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Loadbalancers-Netscaler-Mpx8000-Snmp-20170120-1.el7.noarch
centreon-plugin-Applications-Zookeeper-Jmx-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Redis-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Solr-Jmx-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Php-Fpm-Web-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Selenium-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Clariion-Navisphere-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Voip-Asterisk-Snmp-20200204-093915.el7.centos.noarch
centreon-connector-perl-19.10.1-1.el7.centos.x86_64
centreon-plugin-Hardware-Storage-Dell-Equallogic-Snmp-20200204-093915.el7.centos.noarch
centreon-connector-19.10.1-1.el7.centos.x86_64
centreon-plugin-Hardware-servers-ibm-imm-snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Checkpoint-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Nortel-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Pdu-Raritan-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Switchs-Aruba-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-widget-live-top10-memory-usage-19.10.0-1.el7.centos.noarch
centreon-plugin-Network-Switchs-Juniper-Ex-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Operatingsystems-Aix-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Aws-Lambda-Api-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Aws-Billing-Api-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Xtremio-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Freebox-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Juniper-Ggsn-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Md3000-Smcli-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Oracle-Infiniband-Snmp-20200204-093915.el7.centos.noarch
centreon-trap-19.10.10-1.el7.centos.noarch
centreon-plugin-Network-Citrix-Sdx-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Virtualization-VMWare-daemon-3.1.1-20200310125215.el7.centos.noarch
centreon-plugin-Network-Netasq-Snmp-20170807-1.el7.noarch
centreon-plugin-Applications-Video-Openheadend-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Haproxy-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Juniper-Ssg-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Juniper-Sa-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Cisco-Waas-Snmp-20200204-093915.el7.centos.noarch
centreon-widget-httploader-19.10.0-1.el7.centos.noarch
centreon-plugin-Network-Efficientip-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Cisco-Meraki-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Aws-Rds-Api-20200204-093915.el7.centos.noarch
centreon-broker-cbmod-19.10.3-1.el7.centos.x86_64
centreon-plugin-Cloud-Aws-S3-Api-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Php-Apc-Web-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Stormshield-Ssh-20200204-093915.el7.centos.noarch
centreon-cwrapper-perl-0.1-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Smtp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Telnet-20200204-093915.el7.centos.noarch
centreon-widget-service-monitoring-19.10.2-1.el7.centos.noarch
centreon-plugin-Notification-Highsms-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Databases-Sap-Hana-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Storeonce-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Operatingsystems-Hpux-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Aws-Ec2-Api-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Oneaccess-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Qnap-Snmp-20200204-093915.el7.centos.noarch
centreon-engine-extcommands-19.10.13-1.el7.centos.x86_64
centreon-plugin-Operatingsystems-Solaris-Snmp-20200204-093915.el7.centos.noarch
centreon-base-config-centreon-engine-19.10.10-1.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Serverscheck-Sensorgateway-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Pfsense-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Cisco-Ucs-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Digi-Sarian-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Devices-Gorgy-Ntpserver-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Fortinet-Fortimanager-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Switchs-Cisco-Smallbusiness-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Extreme-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Ups-Mge-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Device-Safenet-Keysecure-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Cisco-Asa-Snmp-20200204-093915.el7.centos.noarch
centreon-widget-graph-monitoring-19.10.0-1.el7.centos.noarch
centreon-plugin-Network-Dell-Sseries-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ospf-20200204-093915.el7.centos.noarch
centreon-plugin-Network-3com-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Databases-Oracle-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Modbus-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Redis-Cli-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Cisco-Prime-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Storwize-Ssh-20200204-093915.el7.centos.noarch
centreon-license-manager-common-19.10.1-3.el7.centos.noarch
centreon-plugin-Applications-Peoplesoft-Jmx-20200204-093915.el7.centos.noarch
centreon-widget-host-monitoring-19.10.1-1.el7.centos.noarch
centreon-plugin-Applications-Webservers-Tomcat-Webmanager-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Aws-Cloudwatch-Api-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Lync-2013-Mssql-20200204-093915.el7.centos.noarch
centreon-plugins-base-1.18-2.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ts3500-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Github-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Zyxel-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Raisecom-Snmp-20200204-093915.el7.centos.noarch
centreon-perl-libs-19.10.10-1.el7.centos.noarch
centreon-plugin-Hardware-Telephony-Alcatel-OXE-Snmp-20200204-093915.el7.centos.noarch
centreon-connector-ssh-19.10.1-1.el7.centos.x86_64
centreon-plugin-Hardware-Ups-Powerware-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Dell-6200-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Juniper-Trapeze-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Panzura-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Hp-Blade-Chassis-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Digi-Portserverts-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Routers-Juniper-Mseries-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Citrix-Appacceleration-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Quantum-Scalar-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Bgp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-TrendMicro-Iwsva-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Voip-Asterisk-20200204-093915.el7.centos.noarch
centreon-pp-manager-19.10.0-5.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ts3100-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Netapp-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Databases-Firebird-20200204-093915.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Celerra-Ssh-20200204-093915.el7.centos.noarch
centreon-broker-cbd-19.10.3-1.el7.centos.x86_64
centreon-plugin-Hardware-Servers-Sun-Mgmtcards-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Aws-Elasticache-Api-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ds5000-Smcli-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Jmx-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Eva-Cli-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Databases-Mssql-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Lenovo-Sseries-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Webservers-Apache-Serverstatus-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Sonus-SBC-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Radius-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Cyberoam-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Netasq-Ssh-20170811-1.el7.noarch
centreon-plugin-Hardware-Storage-Overland-Neo-Snmp-20200204-093915.el7.centos.noarch
centreon-auto-discovery-server-19.10.2-2.el7.centos.noarch
centreon-plugin-Network-Hp-Vc-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Fluidfs-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Antivirus-Kaspersky-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Jacarta-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Msl-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Paloalto-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Msa2000-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Dell-Ml6000-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Supermicro-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Switchs-Hirschmann-20200204-093915.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Fs900-Snmp-20200204-093915.el7.centos.noarch
centreon-widget-global-health-19.10.0-1.el7.centos.noarch
centreon-plugin-Network-Ucopia-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-H3c-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Riverbed-Steelhead-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Mail-Bluemind-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dhcp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Video-Zixi-Restapi-20200204-093915.el7.centos.noarch
centreon-widget-tactical-overview-19.10.1-1.el7.centos.noarch
centreon-plugin-Applications-Webservers-Nginx-Serverstatus-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-3par-7000-Ssh-20190704-123459.el7.centos.noarch
centreon-plugin-Hardware-Storage-Synology-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Acmepacket-Snmp-20200204-093915.el7.centos.noarch
centreon-poller-centreon-engine-19.10.10-1.el7.centos.noarch
centreon-plugin-Network-Sophos-Es-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ts3200-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Virtualization-Nutanix-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Dell-Cmc-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Loadbalancers-A10-AX-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Sun-Mseries-Snmp-20200204-093915.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.10.0-1.el7.centos.noarch
centreon-plugin-Network-Dell-N4000-20200204-093915.el7.centos.noarch
centreon-broker-storage-19.10.3-1.el7.centos.x86_64
centreon-plugin-Operatingsystems-Linux-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ssh-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Aws-Cloudfront-Api-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Clamav-Ssh-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Imap-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Storeonce-Ssh-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Arkoon-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Isilon-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Stonesoft-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Loadbalancers-F5-Bigip-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Sensorip-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-Lefthand-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Ats-Apc-Snmp-20200204-093915.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.10.0-1.el7.centos.noarch
centreon-plugin-Applications-Lmsensors-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ts2900-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Backup-Emc-Recoverypoint-Ssh-20200204-093915.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Esx-Wsman-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Weblogic-Jmx-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Databases-Postgresql-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Vplex-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Dlink-Dgs3100-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Fritzbox-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Switchs-Hp-Procurve-Snmp-20200204-093915.el7.centos.noarch
centreon-engine-19.10.13-1.el7.centos.x86_64
centreon-plugin-Hardware-Sensors-Hwgste-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Protocol-Bgp-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Netgear-Mseries-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Nokia-Timos-Snmp-20200204-093915.el7.centos.noarch
centreon-clib-19.10.0-6.el7.centos.x86_64
centreon-plugin-Hardware-Storage-Qsan-Nas-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Routers-Atrica-Snmp-20200204-093915.el7.centos.noarch
centreon-widget-grid-map-19.10.0-1.el7.centos.noarch
centreon-plugin-Hardware-Pdu-Emerson-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Ups-Apc-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Pacemaker-Ssh-20200204-093915.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Hibernate-Jmx-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Docker-Restapi-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hp-P2000-Xmlapi-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Firewalls-Juniper-Srx-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Fritzbox-Snmp-20171013-1.el7.noarch
centreon-plugin-Applications-Databases-Elasticsearch-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Watchguard-Snmp-20200204-093915.el7.centos.noarch
centreon-web-19.10.10-1.el7.centos.noarch
centreon-plugin-Hardware-Storage-Emc-Datadomain-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Digi-AnywhereUSB-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Sensors-Akcp-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Dell-TL2000-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Ibm-Ds3000-Smcli-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Aerohive-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Exagrid-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Dell-IDrac-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Dell-Openmanage-Snmp-20200204-093915.el7.centos.noarch
centreon-broker-core-19.10.3-1.el7.centos.x86_64
centreon-plugin-Applications-Databases-Sybase-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Biztalk-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Sun-Sfxxk-Pssh-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Databases-Informix-20200204-093915.el7.centos.noarch
centreon-plugin-Cloud-Aws-Elb-Api-20200204-093915.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Dlink-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Routers-Redback-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Storage-Hitachi-Hnas-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Cisco-Ironport-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Evertz-FC7800-Snmp-20200204-093915.el7.centos.noarch
centreon-release-19.10-1.el7.centos.noarch
centreon-plugin-Network-Switchs-Brocade-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Hp-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Network-Cisco-Wlc-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Hardware-Servers-Ibm-Bladecenter-Snmp-20200204-093915.el7.centos.noarch

***Operating System***

LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core

***Browser used***

- [x] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

VMWare server deploy over OVF.

When using the filters of ldap server on the page "Administration  >  Parameters  >  LDAP", the web page become unsatable. Can't select poller to reload configuration, missing icon, can't configure LDAP server on new LDAP.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. I reached in Administration  >  Parameters  >  LDAP
3. And I use the Search button or the LDAP Server field.

### Describe the received result

I get the page for "Modify General Options".

Next I can't reconfigure a poller in Configuration  >  Pollers  >  Export configuration

I keep having the "Compulsory Poller"

### Describe the expected result

N/A

### Logs

N/A

### Additional relevant information (e.g. frequency, ...)

N/A

**Comment by R00T88** [comment]
@leo5593 i have the same exact issue
How do you resolve it?

**Comment by leo5593** [comment]
Hello,

Sorry for the delay. It reset some configuration of the web interface.

I manage to reconfigure the web pages path on the configuration.

I'll try to send you the configuration I have so you can get the data.

Regards,

Leo

Le lun. 4 mai 2020 à 11:58, Sebastiano Bertini <notifications@github.com> a
écrit :
