### ISSUE TITLE
Acknowledge, downtime and schedule immediate check (force) don't work

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon#8482]
Hello,
This morning i had to reboot my centreon box and since then i've got exactly the same problem than last time in this ticket : https://github.com/centreon/centreon/issues/7986

I did an update to 19.04.13 and i'm still unable to acknowlegde, set downtime or force immediate schedule.
As last time i did the checks.

I can see the actions i'm doing in centcore.cmd 

But nothing happens. Last time i restarted httpd and things went working again. Not this time :(

Any clue ?

Kind regards

**Comment by cgagnaire** [comment]
Hi,
If you're seeing _centcore.cmd_ file, that's not ok.
Make sure centcore service is started and that it consumes the file.
If not, make sure the right are apache/644 and that centreon user belongs to apache group.

**Comment by gerpion** [comment]
Hi,
centreon belongs to apache group.
Here are the changes i've done and it worked :
chown apache:apache centcore.cmd
chmod 644 centcore.cmd

And the file been consumed and everything is back working !

Thanks a alot.
