### ISSUE TITLE
Hostname no longer allow zero been in the hostname

### ISSUE THREAD

**Issue by Lumanet2012** [centreon/centreon#849]
Hello,

I am running Centreon 22.04.9 Community Version on Debian Bullseye latest version with all patches. 
We just did 2 patches in Centreon within the last 3-4 weeks. Since the latest version is now in place we noticed this issue : 

https://prnt.sc/9BCu8Mkq-2FH  

random hostname's can't be changed anymore for one, 2nd we noticed servers/hosts no longer contain a "0" in the name which they clearly had before : 

https://prnt.sc/n8kfoiTOjrOs

we had those fields set the same but now we noticed the number "0" is no longer allowed to be used. 

we did start noticing it when we did wanted to do changed that also all of the sudden this showed up : 

https://prnt.sc/TfpFiweUlp6a

so I got to look into the source cache file and noticed they all do have suddenly now a "SPACE" character at the end of each line.

https://prnt.sc/kIzzc9i-pyuA

Anyone ever had issues with this and figured out what is going / how to solve this ?

**Comment by omercier** [comment]
Hi @Lumanet2012,
Sorry for the delay, this issue should be fixed now (see [release notes](https://docs.centreon.com/docs/22.04/releases/centreon-core/#220410)).
Please reopen the issue if you still face the bug after updating your platform.
