### ISSUE TITLE
Add possibility to configure flap detection options

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#855]
---

Author Name: **Emylou Mavic** (Emylou Mavic)
Original Redmine Issue: 4490, https://forge.centreon.com/issues/4490
Original Date: 2013-05-24

---

hi, 

Can you please add the advanced option for flapping detection to the GUI ? 

Such as excluding some statuses from the detection / notification ?

Today, only enable option and threshold are available, the documentation specifies the flap_detection_options directive that can be used. 

Thank you in advance for your feedback,

Best regards

**Comment by julienmathis** [comment]
Hi, 

Sorry, we will not plan to implement this feature. 

Post again if you need it.
