### ISSUE TITLE
Problem with MediaWiki Integration

### ISSUE THREAD

**Issue by Ejant** [centreon/centreon#8617]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

```
$ rpm -qa | grep centreon
centreon-release-18.10-2.el7.centos.noarch
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Database-20200410-101650.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20200410-101650.el7.centos.noarch
centreon-widget-engine-status-18.10.1-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-license-manager-18.10.3-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-18.10.0-6.el7.centos.noarch
centreon-common-18.10.12-3.el7.centos.noarch
centreon-broker-storage-18.10.2-1.el7.centos.x86_64
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-broker-cbmod-18.10.2-1.el7.centos.x86_64
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200410-101650.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20200410-101650.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20200410-101650.el7.centos.noarch
centreon-database-18.10.12-3.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20200410-101650.el7.centos.noarch
centreon-license-manager-common-18.10.3-1.el7.centos.noarch
centreon-base-config-centreon-engine-18.10.12-3.el7.centos.noarch
centreon-widget-tactical-overview-18.10.1-1.el7.centos.noarch
centreon-widget-host-monitoring-18.10.3-1.el7.centos.noarch
centreon-broker-18.10.2-1.el7.centos.x86_64
centreon-trap-18.10.12-3.el7.centos.noarch
centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-broker-cbd-18.10.2-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ftp-20200410-101650.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20200410-101650.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20200410-101650.el7.centos.noarch
centreon-web-18.10.12-3.el7.centos.noarch
centreon-poller-centreon-engine-18.10.12-3.el7.centos.noarch
centreon-auto-discovery-server-18.10.8-3.el7.centos.x86_64
centreon-widget-service-monitoring-18.10.5-1.el7.centos.noarch
centreon-widget-grid-map-18.10.0-6.el7.centos.noarch
centreon-widget-graph-monitoring-18.10.0-6.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-perl-libs-18.10.12-3.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200410-101650.el7.centos.noarch
centreon-pp-manager-18.10.5-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-broker-core-18.10.2-1.el7.centos.x86_64
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
centreon-plugin-Hardware-Printers-Generic-Snmp-20200410-101650.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20200410-101650.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20200410-101650.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20200410-101650.el7.centos.noarch
centreon-18.10.12-3.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-18.10.0-6.el7.centos.noarch

```

***Operating System***

*CentOS 7*

***Browser used***

- [X ] Google Chrome
- [X ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: -18.10-

### Description

-- Hi, we can't integrate Centreon 18.10 with MediaWiki. Mediawiki Version 1.31.1 --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. Configured Knlowedge Base Parameters
3. When we try to reach Knlowedge Base page "An error occured, please check your Knowledge base configuration "
### Logs

**PHP error logs**

```
/var/log/centreon/knowledgebase.log

PHP Notice:  Undefined index: query in /usr/share/centreon/www/class/centreon-knowledge/wikiApi.class.php on line 99
An error occured, please check your Knowledge base configuration

Do we need to downgrade wiki version? Upgrade Centreon?

Kr.
```

**Comment by garnier-quentin** [comment]
I have done a PR for the last version: https://github.com/centreon/centreon/pull/8595
Maybe it can be applied on 18.10.x also.

**Comment by magicbret** [comment]
Hello, Still not working with Centreon 20.04

**Comment by Ejant** [comment]
Same error with patch applied:


**
PHP Notice:  Undefined index: query in /usr/share/centreon/www/class/centreon-knowledge/wikiApi.class.php on line 97
An error occured, please check your Knowledge base configuration
**

Is there any recommended version of MediaWiki for integration?
Kr.

**Comment by kduret** [comment]
It seems centreon-web does not join your mediawiki.
Can you do a health check with the following line (executed from centreon server) : 
`curl -Is <mediawiki_url>`

**Comment by Ejant** [comment]
[root@xxxxxxxxx ~]# curl -Is https://wiki.my.site/
HTTP/1.1 200 OK
Date: Mon, 04 May 2020 01:40:44 GMT
Server: Apache/2.4.25 (Debian)
X-Content-Type-Options: nosniff
Content-language: en
X-UA-Compatible: IE=Edge
Link: </resources/assets/Mysite-Logo.png?1f8af>;rel=preload;as=image
X-Frame-Options: DENY
Vary: Accept-Encoding,Cookie
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Content-Type: text/html; charset=UTF-8



On Apache side i see:

192.168.14.5 - - [03/May/2020:13:45:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:13:50:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:13:55:03 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:00:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:05:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:10:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:15:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:20:03 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:25:03 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:30:03 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:35:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:40:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:45:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:50:03 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:14:55:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:15:00:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:15:05:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:15:10:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"
192.168.14.5 - - [03/May/2020:15:15:02 -0300] "POST /api.php HTTP/1.1" 200 912 "-" "-"

192.168.14.5 is my centreon host. If you need more info, just let me know.
I've checked centreon user against wiki and it works.

Kr:
Marcelo

**Comment by kduret** [comment]
Could you try the following curl from you centreon central server : 
`curl, --data "action=query&meta=siteinfo&format=json" <mediawiki_url>/api.php`

It should return a json response

**Comment by Ejant** [comment]
curl --data "action=query&meta=siteinfo&format=json" https://my.wiki.site/api.php
{"error":{"code":"readapidenied","info":"You need read permission to use this module.","*":"See https://wiki.telecentro.net.ar/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."}

We are not using proxy. Maybe should i disable auth on my mediawiki server?

**Comment by kduret** [comment]
You can enable auth on mediawiki server, but the call to read `siteinfo`should be allowed without authentication

**Comment by fabien493** [comment]
Hello,
How to disable API authentication in mediawiki ? or why not add the login function in the construct ?

**Comment by fabien493** [comment]
Solved: Download the master version of wikiApi.class.php and add "$this-> login ();" at line 88 (in the getWikiVersion function) and use Special: BotPasswords for use the bot to configure knowledge base. (login example: admin@bot and password)
Best regards
