### ISSUE TITLE
Fullscreen doesn't work on firefox

### ISSUE THREAD

**Issue by odin78** [centreon/centreon#8641]
# BUG REPORT INFORMATION

***Operating System***

Centos 7

***Browser used***

- [ ] Google Chrome
- [ *] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 18.10.10;19.10.10;20.04

### Description

The button on the right bottom of the page which allow to have fullscreen doesn't work on firefox (whatever the version)

### Steps to Reproduce

N/A

### Describe the received result

No change, the window doesn't change

### Describe the expected result

Having  fullscreen on firefox

**Comment by lpinsivy** [comment]
Hi,

If you open the console log from developer menu, do you have any errors?

**Comment by lpinsivy** [comment]
Moreover, what is your firefow version?

**Comment by odin78** [comment]
Hi,
Problem has been solved by downloading and installing the new firefox  version (75). The version which i used came from debian packages (esr version) and it didn't work.
