### ISSUE TITLE
Multiple Hostgroups

### ISSUE THREAD

**Issue by rntbrgtt** [centreon/centreon#8643]
### Feature explanation

We would like tho have the hability to use multiple hostgroups when listing Hosts, Services and setting up Views. 

Today we can list hosts/services in Hostgroup A and the idea is being able to list hosts/services that are member of Hostgroup A and Hostgroup B and Hostgroup C...

### What is the value of the wanted feature ?

We (and I believe most of people) have hundreds of hostgroups. We basically categorize a host by adding it in different HGs. Being able to list hosts that are member of multiple HGs would help us to identify specific hosts  on specific situations.

### Additional information

None

**Comment by lpinsivy** [comment]
Hi,

In the Centreon 20.04 version, you have a new "Events View" that allows to select multiple groups.
Did you try?

**Comment by rntbrgtt** [comment]
Hi,

We are still using Centreon Engine 19.10.7.

I will check it later.

Thanks,

**Comment by lpinsivy** [comment]
Regards,

**Comment by lpinsivy** [comment]
Reopen this ticket if you have more needs about it after upgraded to 20.04

**Comment by rntbrgtt** [comment]
HI,

You are saying that 20.04 has it available on Views.

I also requested to see Host and Services that are member of multiple HGs and this is not on 20.04.

Regards,

**Comment by rntbrgtt** [comment]
How can I reopen it?
