### ISSUE TITLE
Poller not starting after upgrade to 20.04

### ISSUE THREAD

**Issue by philipraets** [centreon/centreon#8645]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***
```
$ rpm -qa | grep centreon
centreon-20.04.0-7.el7.centos.noarch
```

***Operating System***
```
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

***Browser used***

- [ ] Google Chrome
- [X] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***
Centreon => VMWare guest

### Description

-- Describe the encountered issue --
After upgrading from 19.10 to 20.04 centreon poller is not starting

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I upgraded centreon according the documentation on https://docs.centreon.com/20.04/en/upgrade/upgrade-from-19-10.html

2. I logged on in centreon
3. exported the configuration and restart the engine
4. poller does not start

### Describe the received result
![image](https://user-images.githubusercontent.com/708011/80074117-fef79780-8548-11ea-8b68-e2ef9d913bec.png)

![image](https://user-images.githubusercontent.com/708011/80074178-16cf1b80-8549-11ea-86ba-58a8e88885cd.png)

### Describe the expected result
The poller should be started

### Logs

**centreon-engine logs (*if needed*)**

```
tail -f /var/log/centreon-engine/centengine.log

log-file is empty
```
**centreon-broker logs (*if needed*)**

```
tail -f /var/log/centreon-broker/central-broker-master.log
[1587628728] config:  main: configuration update requested
[1587628728] config:  log applier: applying 1 logging objects
[1587628728] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1587628728] config:  applier: 10 modules loaded
[1587628728] config:  endpoint applier: loading configuration
[1587628803] config:  main: configuration update requested
[1587628803] config:  log applier: applying 1 logging objects
[1587628803] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1587628803] config:  applier: 10 modules loaded
[1587628803] config:  endpoint applier: loading configuration
```

**Comment by lpinsivy** [comment]
Hi,

Can you try to:

- Restart the gorgoned process : systemctl restart gorgoned
- Generate/export the configuration and restart Centreon Engine

Regards,

**Comment by philipraets** [comment]
I've restarted gorgoned, and then exported and restarted centreon engine, but the poller does not start:

```
$ tail -f /var/log/centreon-gorgone/gorgoned.log
2020-04-23 11:01:06 - DEBUG - [core] Message received - [COMMAND] [909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b] [1] {"content":[{"metadata":{"centcore_proxy":1,"centcore_cmd":"RESTART"},"command":"sudo service centengine restart"}]}
2020-04-23 11:01:06 - DEBUG - [action] Event: [COMMAND] [909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b] [] {"content":[{"metadata":{"centcore_proxy":1,"centcore_cmd":"RESTART"},"command":"sudo service centengine restart"}]}
2020-04-23 11:01:06 - DEBUG - [legacycmd] Event: [ACK] [909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b] {"data":null,"code":0}
2020-04-23 11:01:06 - DEBUG - [action] Create sub-process
2020-04-23 11:01:06 - DEBUG - [core] Message received - [PUTLOG] [909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b] [] {"etime":1587632466,"data":{"request_content":[{"metadata":{"centcore_proxy":1,"centcore_cmd":"RESTART"},"command":"sudo service centengine restart"}],"message":"commands processing has started"},"instant":null,"token":"909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b","code":0}
2020-04-23 11:01:06 - DEBUG - [core] Message received - [PUTLOG] [909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b] [] {"etime":1587632466,"data":{"metadata":{"centcore_proxy":1,"centcore_cmd":"RESTART"},"command":"sudo service centengine restart","message":"command has started"},"instant":null,"token":"909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b","code":0}
2020-04-23 11:01:06 - DEBUG - [core] Message received - [PUTLOG] [909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b] [] {"etime":1587632466,"data":{"metrics":{"duration":0,"end":1587632466,"start":1587632466},"metadata":{"centcore_proxy":1,"centcore_cmd":"RESTART"},"result":{"exit_code":0,"stdout":"Redirecting to /bin/systemctl restart centengine.service"},"command":"sudo service centengine restart","message":"command has finished successfully"},"instant":null,"token":"909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b","code":2}
2020-04-23 11:01:06 - DEBUG - [core] Message received - [PUTLOG] [909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b] [] {"etime":1587632466,"data":{"message":"commands processing has finished successfully"},"instant":null,"token":"909b72fe1c955fa026638ef3713e8640179f1f0063368ea43b131d87da9cbcbfc04da66789b171947e434fdb45f89f505f85131500903a7166b33e87a623f73b","code":2}
2020-04-23 11:01:06 - DEBUG - [core] Received SIGCLD signal (pid: 3124)
2020-04-23 11:01:11 - INFO - [proxy] Send pings
2020-04-23 11:02:31 - INFO - [proxy] Send pings
```

**Comment by lpinsivy** [comment]
Can you check the logs of /var/log/centreon-engine/centengine.log when you run the command: systemctl restart centegnine?

**Comment by philipraets** [comment]
/var/log/centreon-engine/centengine.log gives nothing, but with journalctl -f I get the following:

```
Apr 23 11:12:46 centreon polkitd[747]: Registered Authentication Agent for unix-process:3526:530091 (system bus name :1.303 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Apr 23 11:12:46 centreon systemd[1]: Stopping Centreon Engine...
Apr 23 11:12:46 centreon systemd[1]: Stopped Centreon Engine.
Apr 23 11:12:46 centreon systemd[1]: Started Centreon Engine.
Apr 23 11:12:46 centreon polkitd[747]: Unregistered Authentication Agent for unix-process:3526:530091 (system bus name :1.303, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Reading main configuration file '/etc/centreon-engine/centengine.cfg'.
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/hostTemplates.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/hosts.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/serviceTemplates.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/services.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/commands.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/contactgroups.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/contacts.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/hostgroups.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/servicegroups.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/timeperiods.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/escalations.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/dependencies.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/connectors.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/meta_commands.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/meta_timeperiod.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/meta_host.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Processing object config file '/etc/centreon-engine/meta_services.cfg'
Apr 23 11:12:46 centreon centengine[3533]: [1587633166] [3533] Reading resource file '/etc/centreon-engine/resource.cfg'

```

I've also noticed that in centreon the version says Centreon engine 19.10.13:
![image](https://user-images.githubusercontent.com/708011/80081840-c610f000-8553-11ea-9622-385edbd39a34.png)

but version 20.04 is installed:
```
$ rpm -qa | grep centreon-engine
centreon-engine-20.04.0-3.el7.centos.x86_64
centreon-engine-daemon-20.04.0-3.el7.centos.x86_64
centreon-poller-centreon-engine-20.04.0-7.el7.centos.noarch
centreon-base-config-centreon-engine-20.04.0-7.el7.centos.noarch
centreon-engine-extcommands-20.04.0-3.el7.centos.x86_6
```

**Comment by lpinsivy** [comment]
OK, can you check also the /var/log/centreon-broker/central-module-master.log and /var/log/centreon-broker/central-broker-master.log log files?

**Comment by philipraets** [comment]
when restarting cbd I get the following (output shortened a bit, lot of filtering elements)
```
$tail -f tail -f /var/log/centreon-broker/central-broker-master.log
Centreon Broker 20.04.0 log file opened
[1587634403] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1587634403] config:  endpoint applier: loading configuration
[1587634403] config:  endpoint applier: new filtering element: 131073
...
[1587634403] config:  endpoint applier: creating new endpoint 'connection-to-central'
[1587634403] config:  endpoint applier: new filtering element: 131073
...
[1587634403] config:  endpoint applier: creating new endpoint 'central-broker-master-sql'
[1587634403] config:  endpoint applier: new filtering element: 65550
...
[1587634403] error:   async_buf::async_read_cb incoming packet size: 23
[1587634403] error:   async_buf::async_read_cb incoming packet size: 38
[1587634403] config:  endpoint applier: creating new endpoint 'centreon-broker-master-rrd'
[1587634403] config:  endpoint applier: new filtering element: 131073
[1587634403] config:  endpoint applier: new filtering element: 65550
...
[1587634403] error:   async_buf::async_read_cb incoming packet size: 38
[1587634403] config:  endpoint applier: creating new endpoint 'central-broker-master-perfdata'
[1587634403] error:   unexpected end of input
[1587634403] error:   async_buf::async_read_cb incoming packet size: 20
```

central-module-master.log is empty

**Comment by lpinsivy** [comment]
Can you check in the UI for the "Configuration  >  Pollers  >  Engine configuration" menu, edit your poller, and in the "Data" tab if you have the following entries:

/usr/lib64/centreon-engine/externalcmd.so
/usr/lib64/nagios/cbmod.so /etc/centreon-broker/central-module.json

**Comment by philipraets** [comment]
they are there:

![image](https://user-images.githubusercontent.com/708011/80084844-b85d6980-8557-11ea-8fdc-f8eb20607e7f.png)

**Comment by SylvestreG** [comment]
Hi,

Can you provide us your broker configuration files, located in /etc/centreon-broker ? 

Thanks,

**Comment by philipraets** [comment]
No problem, 

here you can download the files:
https://www.dropbox.com/s/ibxa7szmbs0t3jo/centreon-broker.zip?dl=0

**Comment by cgagnaire** [comment]
Hi @philipraets,
Can you validate that when you export the configuration of your Central, the files in /etc/centreon-broker are updated ?
If so, can you restart both cbd and centengine from the Central terminal ?
Thank you.

**Comment by philipraets** [comment]
The timestamps of the files in /etc/centreon-broker are being updated when I do an export.
when restarting cbd and centengine with systemctl restart cbd centengine I have an error in my journal:
```
Apr 23 12:57:07 centreon systemd[1]: Stopping Centreon Broker watchdog...
Apr 23 12:57:08 centreon mysqld[1168]: 2020-04-23 12:57:08 10605 [Warning] Aborted connection 10605 to db: 'centreon_storage' user: 'centreon' host: 'localhost' (Got an error reading communication packets)
Apr 23 12:57:09 centreon systemd[1]: Stopped Centreon Broker watchdog.
Apr 23 12:57:09 centreon systemd[1]: Started Centreon Broker watchdog.
Apr 23 12:57:09 centreon systemd[1]: Started Centreon Engine.
Apr 23 12:57:09 centreon polkitd[747]: Unregistered Authentication Agent for unix-process:5305:1156155 (system bus name :1.616, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Reading main configuration file '/etc/centreon-engine/centengine.cfg'.
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/hostTemplates.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/hosts.cfg'
Apr 23 12:57:09 centreon cbwd[5312]: [1587639429] config:  log applier: applying 1 logging objects
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/serviceTemplates.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/services.cfg'
Apr 23 12:57:09 centreon cbwd[5312]: [1587639429] config:  log applier: applying 1 logging objects
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/commands.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/contactgroups.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/contacts.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/hostgroups.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/servicegroups.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/timeperiods.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/escalations.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/dependencies.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/connectors.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/meta_commands.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/meta_timeperiod.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/meta_host.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Processing object config file '/etc/centreon-engine/meta_services.cfg'
Apr 23 12:57:09 centreon centengine[5313]: [1587639429] [5313] Reading resource file '/etc/centreon-engine/resource.cfg'
Apr 23 12:57:09 centreon kernel: cbd[5344]: segfault at 9 ip 00007ff99149b651 sp 00007ff95affc840 error 6 in 20-storage.so[7ff991452000+7b000]
Apr 23 12:57:09 centreon mysqld[1168]: 2020-04-23 12:57:09 18536 [Warning] Aborted connection 18536 to db: 'centreon_storage' user: 'centreon' host: 'localhost' (Got an error reading communication packets)
Apr 23 12:57:14 centreon cbwd[5312]: [1587639434] config:  log applier: applying 1 logging objects

```

**Comment by cgagnaire** [comment]
Ok so we can see that there is a segfault here:
`Apr 23 12:57:09 centreon kernel: cbd[5344]: segfault at 9 ip 00007ff99149b651 sp 00007ff95affc840 error 6 in 20-storage.so[7ff991452000+7b000]`

@SylvestreG will surely ask you for more info on this one, including a doredump.

**Comment by philipraets** [comment]
It doesn't always happen.
I've just found the following in an upgrade log file:
```
2020-04-22 14:13|0|0|UPGRADE - 20.04.0-beta.1 : Gorgone configuration file is not created properly - Code : 0 - Error : Gorgone configuration file is not created properly - Trace : #0 /usr/share/centreon/www/install/step_upgrade/process/process_step4.php(72): include_once()
#1 {main}
```

**Comment by SylvestreG** [comment]
Hi,

Can you activate coredumpctl, so we will have some insight if another segfault happens. here is the way to enable coredumpctl : 

Step by step core dump activation : 
- install gdb
- inside /etc/systemd/system.conf uncomment: DumpCore=yes 
- replace: DefaultLimitCORE= by : DefaultLimitCORE=Infinity
- add these lines in /etc/sysctl.conf  :
 ```
 kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e 
fs.suid_dumpable=2
```
- add LimitCORE=Infinity  in /usr/lib/systemd/system/cbd.service just after the lign User
- reload the confs :
```
sysctl -p 
systemctl daemon-reexec
```
- Retrieve back trace

1.  list coredumps: `coredumpctl list`
2. access to a core dump:  `coredumpctl gdb id_of_coredump`
3. get the backtrace: `bt`

**Comment by SylvestreG** [comment]
And can you add a file named /etc/centreon-broker/log-config.json containing this : 

```
{
	"console": true,
	"log_path": "/tmp",
	"loggers": [
		{
			"name: "sql",
			"lvl": "debug"
		},
		{
			"name: "bbdo",
			"lvl": "debug"
		},
		{
			"name: "tcp",
			"lvl": "debug"
		},
		{
			"name: "tls",
			"lvl": "debug"
		},
		{
			"name": "perfdata",
			"lvl": "debug"
		},
		{
			"name": "lua",
			"lvl": "debug"
		}
	]
}
```

It will give us more data in journalctl and some other log files in /tmp.

Thanks

**Comment by philipraets** [comment]
I've activated coredumpctl, but have not been able to produce a segfault. I've also added the log-config.json, but I don't get extra log files

**Comment by SylvestreG** [comment]
Hi are you available for a online meet, if yes can you join me here :

https://meet.google.com/ama-cmbf-yzp

It will be easier for me to find whats wrong with your config.

Best Regards,

**Comment by SylvestreG** [comment]
ok we can try with anydesk , if you have a free time tomorrow I will be available between 9am and 6pm. (I am located on (GMT+2)

**Comment by philipraets** [comment]
I've noticed this in the gorgoned.log:
```
2020-04-23 16:22:32 - INFO - [core] Module 'broker' is loading
2020-04-23 16:22:32 - INFO - [core] Module 'broker' cannot be loaded: Can't locate gorgone/modules/centreon/broker/hooks.pm in @INC (@INC contains: /usr/bin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/perl5/vendor_perl/gorgone/class/core.pm line 306.
```
And it does not exist indeed

**Comment by philipraets** [comment]
tomorrow is no problem, I am on the same time zone (Belgium)

**Comment by SylvestreG** [comment]
Hi,

Can you provide me your anydesk address ?

Thanks

**Comment by philipraets** [comment]
it is 452 309 407

I've opened 2 ssh-sessions and 2 sftp-sessions to the server for you

Thanks

**Comment by SylvestreG** [comment]
sorry i was just disconnected can you accept the session back ? Thanks

**Comment by cgagnaire** [comment]
Hi @philipraets,
As seen with @SylvestreG you had change your Gorgone config using the init script provided by the project. This one loaded a no more existent broker module. After changing the conf everything did go back to normal.
Then we saw that when specifying the log level to "Log everything" in Engine configuration, the Engine won't start completely. We will make a fix for that.
Let us know if there is anything else.

**Comment by philipraets** [comment]
Thank you for finding the problem and helping us.

**Comment by oasisck** [comment]
> 
> 
> Hi @philipraets,
> As seen with @SylvestreG you had change your Gorgone config using the init script provided by the project. This one loaded a no more existent broker module. After changing the conf everything did go back to normal.
> Then we saw that when specifying the log level to "Log everything" in Engine configuration, the Engine won't start completely. We will make a fix for that.
> Let us know if there is anything else.

Hey everyone, what exactly did you change ? I have the same issue on my first poller (2015). My second poller (2017) upgraded as expected.

**Comment by C0rish** [comment]
> Hi @philipraets,
> As seen with @SylvestreG you had change your Gorgone config using the init script provided by the project. This one loaded a no more existent broker module. After changing the conf everything did go back to normal.
> Then we saw that when specifying the log level to "Log everything" in Engine configuration, the Engine won't start completely. We will make a fix for that.
> Let us know if there is anything else.

Hello, we have the same problem with our broker, same error messages in the logs... maybe the config fix would also help us. What exactly did you change?

**Comment by philipraets** [comment]
In my case they set debug_level=0 in /etc/centreon-engine/centengine.cfg (and I also set all logging options to no in the web interface for the engine-configuration
and if you update centreon-gorgone to the latest version, that configuration will be fixed

**Comment by C0rish** [comment]
![2020-04-28 13_24_54-Centreon](https://user-images.githubusercontent.com/10572596/80484334-d7913800-8957-11ea-8e30-f1d39ebb1e46.png)
![2020-04-28 13_25_10-Centreon](https://user-images.githubusercontent.com/10572596/80484336-d8c26500-8957-11ea-9d5f-24a4c42fb371.png)
I gave it a shot... the poller seems to be running (via Web UI):
![2020-04-28 13_55_29-Centreon](https://user-images.githubusercontent.com/10572596/80484409-f7c0f700-8957-11ea-81eb-9c355c1e1e1c.png)
But unfortunately Centreon still believes it's not working... forcing checks also doesn't work:
![2020-04-28 13_57_02-Centreon](https://user-images.githubusercontent.com/10572596/80484539-2c34b300-8958-11ea-8805-e4823661b50a.png)

So no luck on my side...

**Comment by C0rish** [comment]
Just noticed that my poller is working for 30-60 seconds after a reboot:

"Last Check" timestamps change inside centreon

After that short tme period no communication between centreon and the poller / broker again (default installation on the same machine)

**Comment by oasisck** [comment]
> 
> 
> In my case they set debug_level=0 in /etc/centreon-engine/centengine.cfg (and I also set all logging options to no in the web interface for the engine-configuration
> and if you update centreon-gorgone to the latest version, that configuration will be fixed

Thanks for your feedback.
I also disabled all logging options and I updated centreon-gorgone on poller1 from github but still no luck.
The failed poller is still offline
![image](https://user-images.githubusercontent.com/30388990/80486786-07423f00-895c-11ea-9f9c-7853c2785369.png)
All I can add is atm Poller1 (192.168.30.204) is always established with central (172.20.91.204). Whereas poller2 (172.30.91.204) is not always established.
```
ESTAB      0      0      172.20.91.204:53518              192.168.30.204:5556
TIME-WAIT  0      0      172.20.91.204:40460              172.30.91.204:5556
```

**Comment by rafaelgesser** [comment]
Hello,

I am have same problem.
See that status file not exists:

# ls /var/log/centreon-engine/status.dat
ls: cannot access /var/log/centreon-engine/status.dat: No such file or directory

**Comment by Bbertatum** [comment]
For us, the issue was there because of residue of configuration locking broker state. 
This was solved doin this :
mv /var/lib/centreon-broker/* /tmp/centbroker/ # or rm /var/lib/centreon-broker/* 
systemctl restart cbd

Then the state of the poller inside centreon configuration came back to normal.

**Comment by JuliusKoenig** [comment]
> 
> 
> For us, the issue was there because of residue of configuration locking broker state.
> This was solved doin this :
> mv /var/lib/centreon-broker/* /tmp/centbroker/ # or rm /var/lib/centreon-broker/*
> systemctl restart cbd
> 
> Then the state of the poller inside centreon configuration came back to normal.

Thanks that helped me ^^

**Comment by BFG73** [comment]
I'm experiencing a similar problem.

I've setup a Central and a Poller and everything is working just fine (after my workaround described below). I use the new ZMQ for communication. When I export a new config to the poller and select "restart" instead to "reload", the poller will be marked as "not running" in the pollers overview (I can see on the poller that it has the new configs and the daemon is restarted successfully). One effect of this behavior is that the nodes monitored by the poller doesn't show up in the interface, since Central thinks the poller is not running.

The workaround is to update the database with "update centreon_storage.instances set running=1 where instance_id=<instance-id of the poller>;"

After the workaround the poller is marked as "running" and the monitored nodes show up in the interface again. I'm starting to think that the function that detects if the poller is running or not is broken.

**Comment by omercier** [comment]
Hi all, 
Considering the time elapsed since these messages, the probable number of distinct issues and the number of releases since then, I am closing this issue.
Any one having trouble can open a new issue.
Regards
