### ISSUE TITLE
NOT FOUND 404 after URL change on Events view (beta)

### ISSUE THREAD

**Issue by Caaruzo** [centreon/centreon#8647]
Greetings,

iam using Centreon v20. I changed the domain in centreon UI settings.

![grafik](https://user-images.githubusercontent.com/39491096/80087964-27d55800-855c-11ea-9b8a-5c755fc60223.png)

i also changed the httpd config

**/opt/rh/httpd24/root/etc/httpd/conf.d/10-centreon.conf** : 
[10-centreon.conf.txt](https://github.com/centreon/centreon/files/4521775/10-centreon.conf.txt)

Everything seems to work fine so far, except one behavior.

When i stay logged in and visit Centreon via https://iponly it redirects me to https://ip/itmonitor/monitoring/events.

On the page itself there appears a 404 for this page. 
This only happens if i stay logged in and visit https://iponly
![grafik](https://user-images.githubusercontent.com/39491096/80088223-800c5a00-855c-11ea-92d7-342be6c783e9.png)

I also changed the default site for my account, but the error still persist. It only redirects me to the choosen defaultpage after login.

Is there an fix/workarround for that or did i miss something?

Greetings Caaruzo

**Comment by lpinsivy** [comment]
Hi,

After changing the default uri, can you try to execute: 

`su - apache -s /bin/bash -c "/usr/share/centreon/bin/console cache:clear"`

Regards,

**Comment by Caaruzo** [comment]
I tried. Cache for prod got cleared successfully. But error still exists.

**Comment by lpinsivy** [comment]
can you give me the list of 404 you have from the browser developer console?

**Comment by Caaruzo** [comment]
What exactly do you mean with that? The sourcecode of the 404 page?

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
`

Also updated my first post for better understanding.

**Comment by lpinsivy** [comment]
Can you put a print screen of the "Network" tab of developer mode when you have 404?

I need the call failling

**Comment by Caaruzo** [comment]
Ah, now i understand. Sorry, unfortionally english is not my native language xD

There you go:
![grafik](https://user-images.githubusercontent.com/39491096/80090453-d333dc00-855f-11ea-9612-a182cc70c1a1.png)

**Comment by kduret** [comment]
Your apache configuration is wrong ;)
you should replace `ErrorDocument 404 /centreon/index.html` by `ErrorDocument 404 /itmonitor/index.html`
Then restart apache : `systemctl restart httpd24-httpd`

**Comment by Caaruzo** [comment]
Well, that resolved the issue. Damn it. I didn't seen that. Iam really sorry for this. Thanks very much for your help. Stay healthy :)
