### ISSUE TITLE
[Centreon] Authentication type does not fallback from LDAP to local automatically

### ISSUE THREAD

**Issue by vmonegatto** [centreon/centreon#8654]
# BUG REPORT INFORMATION

***Versions***
```
18.10
19.04
19.10
20.04
```

***Operating System***

CentOS Linux release 7.7.1908 (Core)

***Browser used***

- [x] Google Chrome
- [x] Firefox
- [x] Internet Explorer IE11
- [x] Safari

Version: Not relevant

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

In a scenario where LDAP is configured and 'Store LDAP password' is set, Centreon should be able to authenticate an user if the connection with the LDAP server fails and the password has been previously stored. This fallback from the LDAP to local authentication should be automatic. Nowadays, the authentication fails instead.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Go to Administration  >  Parameters  >  LDAP
2. Create your LDAP configuration and select ALL the following options:
	Enable LDAP authentication: Yes
	Store LDAP password: Yes
	Auto import users: Yes
3. Save the LDAP configuration
4. Login to Centreon using an LDAP user that has not logged in before
5. Logout
6. Go to the database and confirm that the user account has been imported and password saved (probably, user and password are in the DB)
```
SELECT contact_name, contact_passwd, contact_auth_type, contact_ldap_last_sync, contact_ldap_required_sync
FROM contact
WHERE contact_alias='<user_name>'\G;
```
7. Simulate a disruption in the connection with the LDAP. This can be achieved by manipulating the iptables on Centreon Central, for example
```
iptables -A INPUT -p tcp --sport 389 -j DROP
```
8. Try to login again using the same LDAP user account from the step 4

### Describe the received result
The GUI shows the message "Your credentials are incorrect"

### Describe the expected result
I expected that Centreon would be able to authenticate the user with the password stored in the database

### Logs

**LDAP search log**

```
[root@hostname ~]# tailf /var/log/centreon/ldapsearch.log
[24/04/2020 12:42]LDAP Connect : trying url : ldap://<ldap URL>:389/
[24/04/2020 12:42]LDAP Connect : Credentials : CN=xxx,CN=xxx,DC=xxx,DC=xxx,DC=xxx
[24/04/2020 12:49]LDAP Connect : Bind : Can't contact LDAP server
[24/04/2020 12:49]LDAP Connect : connection error
```
**Login log**

```
[root@hostname ~]# tailf /var/log/centreon/login.log
2020-04-24 12:49:18|-1|0|0|[WEB] [10.20.1.1] Authentication failed for '<ldap username>'
```

**Comment by lpinsivy** [comment]
Has been corrected in the following versions:

- Centreon Web 20.04.3
- Centreon Web 19.04.16
- Centreon Web 19.10.13
