### ISSUE TITLE
Base 1000/1024 calculation metric

### ISSUE THREAD

**Issue by fraktury** [centreon/centreon#8655]
___________________________________________________________________________________________________________
rpm -qa | grep centreon|
-----------------------
centreon-plugin-Applications-Protocol-Http-20200204-093915.el7.centos.noarch
centreon-widget-host-monitoring-19.10.1-1.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20200204-093915.el7.centos.noarch
centreon-release-19.10-1.el7.centos.noarch
centreon-connector-perl-19.10.1-1.el7.centos.x86_64
centreon-connector-19.10.1-1.el7.centos.x86_64
centreon-perl-libs-19.10.10-1.el7.centos.noarch
centreon-engine-extcommands-19.10.13-1.el7.centos.x86_64
centreon-widget-engine-status-19.10.1-1.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.10.1-1.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20200204-093915.el7.centos.noarch
centreon-broker-core-19.10.3-1.el7.centos.x86_64
centreon-open-tickets-19.10.1-1.el7.centos.noarch
centreon-pp-manager-19.10.0-5.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20200204-093915.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.10.1-1.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200204-093915.el7.centos.noarch
centreon-nrpe3-plugin-3.2.1-7.el7.centos.x86_64
centreon-widget-tactical-overview-19.10.1-1.el7.centos.noarch
centreon-broker-cbmod-19.10.3-1.el7.centos.x86_64
centreon-license-manager-19.10.1-3.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20200204-093915.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.10.1-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-19.10.1-1.el7.centos.noarch
centreon-poller-centreon-engine-19.10.10-1.el7.centos.noarch
centreon-19.10.10-1.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20200204-093915.el7.centos.noarch
centreon-broker-cbd-19.10.3-1.el7.centos.x86_64
centreon-open-tickets-widget-19.10.1-1.el7.centos.noarch
centreon-license-manager-common-19.10.1-3.el7.centos.noarch
centreon-database-19.10.10-1.el7.centos.noarch
centreon-engine-daemon-19.10.13-1.el7.centos.x86_64
centreon-engine-19.10.13-1.el7.centos.x86_64
centreon-widget-httploader-19.10.1-1.el7.centos.noarch
centreon-widget-global-health-19.10.1-1.el7.centos.noarch
centreon-trap-19.10.10-1.el7.centos.noarch
centreon-base-config-centreon-engine-19.10.10-1.el7.centos.noarch
centreon-broker-19.10.3-1.el7.centos.x86_64
centreon-plugin-Virtualization-VMWare-daemon-3.1.1-20200310125215.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20200204-093915.el7.centos.noarch
centreon-broker-storage-19.10.3-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ftp-20200204-093915.el7.centos.noarch
centreon-widget-service-monitoring-19.10.2-1.el7.centos.noarch
centreon-clib-19.10.0-6.el7.centos.x86_64
centreon-open-tickets-module-19.10.1-1.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20200204-093915.el7.centos.noarch
centreon-widget-grid-map-19.10.1-1.el7.centos.noarch
centreon-auto-discovery-server-19.10.2-2.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20200204-093915.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20200204-093915.el7.centos.noarch
centreon-connector-ssh-19.10.1-1.el7.centos.x86_64
centreon-common-19.10.10-1.el7.centos.noarch
centreon-web-19.10.10-1.el7.centos.noarch
centreon-widget-graph-monitoring-19.10.1-1.el7.centos.noarch

***Operating System***

CentOS

***Browser used***

- [x] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: -- 19.10.10

***Additional environment details (AWS, VirtualBox, physical, etc.): ESXI VM

### Description

Although the configured graph template is on a 1024 basis, the calculation when viewing graphs is performed on a 1000 basis. The strangest thing is that in a PNG export, it is the right value that
is displayed (calculated on a 1024 basis). 
It is also observable on your demo platform in 20.04. 

### Steps to Reproduce

1. Create a classic storage supervision service using the centreon plugins and the "storage" graphical model delivered by default (base 1024)
2. Conduct audits to obtain sufficient performance data.
3. Compare in the standard information the "used" value that was calculated by the perl program on a 1024 basis and the value on the graph calculated from the performance data. It should be higher
4. Take the raw performance data in bytes and divide it by 1000 to make sure that it is a 1000 base instead of 1024 used.
5; Do a PNG export to see that the displayed value is different, it corresponds to the one on a 1024 basis.

![issue centreon](https://user-images.githubusercontent.com/23696544/80277055-b842a280-86ec-11ea-80dd-0cb8ebb8cf43.jpg)

Yours sincerely,
Bailleul Matthieu

**Comment by dalfo77** [comment]
Ciao, I have the same problem with Centreon 20.04.3 (commit 5066c39df)

![Annotazione 2020-06-17 171213](https://user-images.githubusercontent.com/55084117/84916771-c692b680-b0be-11ea-9926-ca6b20bf2cca.png)

![Annotazione 2020-06-17 171305](https://user-images.githubusercontent.com/55084117/84916822-da3e1d00-b0be-11ea-81ed-d6a9e03ab9d2.png)

![centrapp-prd01-Disk--var-lib-mysql](https://user-images.githubusercontent.com/55084117/84916892-f04bdd80-b0be-11ea-970c-df66abd529f1.png)

**Comment by LeDOC666** [comment]
Same problem for me but from 19.04 and to latest fresh updateded:
![image](https://user-images.githubusercontent.com/29775748/91065483-cf5cb700-e630-11ea-8dc5-c5fa6607b8db.png)
OK: Storage 'C:' Usage Total: 39.90 GB Used: 28.03 GB (70.24%) Free: 11.87 GB (29.76%) | 'count'=1;;;0; 'used'=30093262848B;;;0;42841665536

**Comment by Moujimouja** [comment]
Hi,

Thanks for your feedbacks.  It's been taken by developpers and we'll be fixed in futur Centreon version.

refs MON-5815
refs MON-5813

We'll keep you posted here.

**Comment by cgagnaire** [comment]
Already fixed on legacy pages (ie not Event View) here https://github.com/centreon/centreon/pull/8908.
We'll soon be done on Event View.

**Comment by LeDOC666** [comment]
Hello there, I just updates to latest centreon, and Graph seems to be correct!!!
...
But 2 days later, the problem come back (I didn't touch the Service).
I checked again configuration, rebuild RRD, rebuild template in 1024, but still problem:

![image](https://user-images.githubusercontent.com/29775748/111321039-dea46000-8667-11eb-8b17-6fa7c2e9c2b4.png)

![image](https://user-images.githubusercontent.com/29775748/111321162-f976d480-8667-11eb-9ec0-0b668306e90a.png)

RRD graph is correct.
