### ISSUE TITLE
[Documentation update] - MariaDB doesn't start after reboot since upgrade to 10.3

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#8656]
Hi,

Since migrating to 20.04 and particularly update mariaDB 10.1 to 10.3, after a rebootof server,  mariaDB doesn't start.
It probably caused by uninstall and reinstall mariadb-server where the symlink were deleted.

To solve this, simply enable mariadb with command:
`systemctl enable mariadb`

Can you add this in documentation at the end of migration process, just before upgrade remote-servers?
=> here: https://docs.centreon.com/current/fr/upgrade/upgrade-from-19-10.html#mont%C3%A9e-de-version-des-remote-servers

kind regards

**Comment by lpinsivy** [comment]
Thank you @cmeschin for your feedback
