### ISSUE TITLE
Menu Rules not found in Configuration/Notifications/ after installed centreon-open-tickets

### ISSUE THREAD

**Issue by McklRgt** [centreon/centreon#8669]
OS : CentOS 7
MariaDB

Centreon 18.10.12
centreon-open-tickets 20.04.0

After installing centreon-open-tickets, I should find Rules in Configuration / Notifications to add new rule and continue to parameter the open-tickets object. 
Do you know why and how to solve this problem ?

**Comment by lpinsivy** [comment]
Duplicate of #8668
