### ISSUE TITLE
[events view] Incorrect default downtime duration

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#8705]
Hi,

In the new 20.04 _events view_, the default downtime duration is not correctly set.

it should take the value from _Administration > Parameters > Monitoring > Default downtime settings_.
As it was reported in ##5963 and fixed in #8486 for other views.

Thank you 👍

**Comment by Moujimouja** [comment]
Thanks for opening this issue, we 'll have a look and fix this.

refs MON-5812

**Comment by UrBnW** [comment]
Fixed by #9235.
