### ISSUE TITLE
Centreon Events View Beta Problem

### ISSUE THREAD

**Issue by gonnetl** [centreon/centreon#8726]
Operating System: CentOS 7.8.2003
Centreon v 20.04.0
Php v7.2

Hello Everybody,

I have a problem : after upgrading centreon 19.10 -> 20.04, when I'm opening my home page (Events View beta) : I have nothing on screen , except an error message : Oops, something went wrong...

When I'm searching in /Var/log/centreon files : I have nothing to explain that...

Can U help me please ?

Thank's a lot.

**Comment by cgagnaire** [comment]
Hi @gonnetl,
Can you update your platform to the latest version and tell us if you still have the problem ?
Be sure to empty the cache of your browser after an update.

**Comment by cgagnaire** [comment]
Reopen the issue if you still have the problem, thanks!
