### ISSUE TITLE
Failure in centreon web from browser when adding host from template.

### ISSUE THREAD

**Issue by vcegarra** [centreon/centreon#8729]
![example](https://user-images.githubusercontent.com/42231675/82338685-7a842180-99ed-11ea-8de0-15e080b1338c.jpg)

# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

*Versions*

For the RPM based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon

centreon-20.04.2-4.el7.centos.noarch
centreon-web-20.04.2-4.el7.centos.noarch

For the deb based systems

-- Copy/Paste the result of the following command --
```
$ dpkg -l | grep centreon
```
*Operating System*

CentOS 7

*Browser used*

- [X ] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: Versión 81.0.4044.138 (Build oficial) (64 bits)

***Additional environment details (AWS, VirtualBox, physical, etc.):***
VM on vSphere 6.7

### Description

When performing some actions from centreon web, the browser does not respond, showing an error like "connection has been reestablished" in Chrome.

These actions have verified that they are:
- Add a host> use a template for the host> save> the error appears.

- When modifying some parameter in centreon-engine from the web browser> save> the error appears.

### Steps to Reproduce
Add a host> use a template for the host> save> the error appears.

### Describe the received result
![image](https://user-images.githubusercontent.com/42231675/82338018-ad79e580-99ec-11ea-851c-b50d055ba2a1.png)


### Describe the expected result

Creating the host from the template

### Logs

**PHP error logs**

```
tail -f /var/opt/rh/rh-php71/log/php-fpm/centreon-error.log
```
**centreon-engine logs (*if needed*)**

```
tail -f /var/log/centreon-engine/centengine.log
```

[root@centreon ~]# tail -f /var/log/centreon-engine/centengine.log
[1589897378] [2131] Event broker module '/usr/lib64/centreon-engine/externalcmd.so' initialized successfully
[1589897378] [2131] Centreon Broker: log applier: applying 1 logging objects
[1589897378] [2131] Event broker module '/usr/lib64/nagios/cbmod.so' initialized successfully
[1589897378] [2131] INITIAL HOST STATE: Herramientas_KIO.Centreon;UP;HARD;1;
[1589897378] [2131] Event loop start at Tue May 19 16:09:38 2020
[1589897378] [2131] Configuration loaded, main loop starting.

**centreon-broker logs (*if needed*)**

```
tail -f /var/log/centreon-broker/central-broker-master.log
```
[root@centreon ~]# tail -f /var/log/centreon-broker/central-broker-master.log
Centreon Broker 20.04.0 log file opened
[1589889772] error:   TCP peer 'localhost:5670'connection reset
Centreon Broker 20.04.0 log file opened
Centreon Broker 20.04.2 log file opened
Centreon Broker 20.04.2 log file opened
[1589897175] error:   TCP peer 'localhost:5670'connection reset
Centreon Broker 20.04.2 log file opened

**centcore logs (*if needed*)**

```
tail -f /var/log/centreon/centcore.log
```

### Additional relevant information (e.g. frequency, ...)

Fresh install.

**Comment by cgagnaire** [comment]
Hi @vcegarra,
It looks like you have some Palo Alto firewall in your network blocking requests.
To be sure connect to the Panorama console and go to 'Monitor > Logs > Threat' and filter logs on Centreon server IP as destination address. You should then see vulnerability logs with ID 57903.
This threat is fixed and 20.04 is not impacted. So you can create a rule to ignore it.

**Comment by vcegarra** [comment]
Hi @cgagnaire !

Thanks for your reply. I effectively use FW Palo Alto.

Next Monday, I will check with my Comm's Team the logs in the PA and report it in this thread.

But it is good to know that the problem may be in the FW.

I hope to report the checks to you the following Monday.

A greeting!

**Comment by cgagnaire** [comment]
Hi @vcegarra,
Do you have any news since you've investigate ?

**Comment by vcegarra** [comment]
Hi!

I confirm that by applying the filter in PA as you indicated, I have had full visibility of the web interface.

Therefore I already have Centreon fully operational.

Thank you very much!

**Comment by cgagnaire** [comment]
Perfect, thanks!
