### ISSUE TITLE
To replace my current license with the 100-host-free one

### ISSUE THREAD

**Issue by geekmichael** [centreon/centreon#8738]
I have updated my Centreon instance to the latest version 20.04.2, and received the new license code for 100-host-free. Thanks for your hard work!

However, when I follow the instruction to visit the page Administration>Extensions>Manager, I see no button displayed with "Add Token", but one of "View License" showing my current expired license and there is no way to replace it.

**Comment by cgagnaire** [comment]
Hi @geekmichael,
Did you manage to deal with your problem ?
If not I think @OnjaOR can help you on this one.
