### ISSUE TITLE
Closing as not important, feel free to re-open if needed...

### ISSUE THREAD

**Issue by yunopi** [centreon/centreon#8774]
Closing as not important, feel free to re-open if needed...

_Originally posted by @UrBnW in https://github.com/centreon/centreon/issues/7333#issuecomment-624115444_

I believe the missing process_perf_data directive being taking from host and service definitions is preventing Service Performance Data processsing commands from running.

Reference the screenshots from issue #7333

"This option allows you to specify a command to be run after every service check to process service performance data that may be returned from the check. This command is only executed if the process_performance_data option is enabled globally and if the process_perf_data directive in the service definition is enabled."

https://centreon.slack.com/archives/CCRGLQSE5/p1591298954476600

**Comment by UrBnW** [comment]
Please this this comment : https://github.com/centreon/centreon/issues/7333#issuecomment-487923397
This feature is deprecated, you should now use Stream Connectors 👍

**Comment by yunopi** [comment]
Im not trying to export the data, I am trying to run some scripts on the local machine to process disk growth for sending out alerts.
