### ISSUE TITLE
Aide indisponible pour les commandes

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#880]
---

Author Name: **Joffrey Dislaire** (Joffrey Dislaire)
Original Redmine Issue: 5525, https://forge.centreon.com/issues/5525
Original Date: 2014-05-06

---

Sur CES 3 / centreon-engine et broker, les aides contextuelles dans les commandes ne sont plus disponibles (qu'on retrouve aussi bien dans les modèles de services que dans les descriptions de commandes (screenshot en PJ si je ne suis pas assez clair).
Quand on clique sur la petite icone en "?" on obtient :

@Ligne de commande --help 
Statut détaillé Erreur: Impossible d'exécuter cette commande en raison d'un problème de sécurité sur le chemin.@ 

Avant mise à jour, le résultat était :

Ligne de commande /usr/lib64/nagios/plugins/check_http --help 
Statut détaillé check_http v1.4.16 (nagios-plugins 1.4.16)
Copyright (c) 1999 Ethan Galstad 
Copyright (c) 1999-2011 Nagios Plugin Development Team
etc, etc, ...

Visiblement, le chemin n'est plus pris en compte.

Mes superviseurs se servent beaucoup de cette fonction, c'est pénalisant pour moi au point de ne pouvoir passer en prod Centreon 2.5

D'avance merci !

**Comment by julienmathis** [comment]
Sorry but it works for me on Centreon 2.6.2
