### ISSUE TITLE
Inherit contacts from host not working at all CES 3.1

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#881]
---

Author Name: **Matt Henry** (Matt Henry)
Original Redmine Issue: 6362, https://forge.centreon.com/issues/6362
Original Date: 2015-04-24

---

The "Inherit contacts from host" option for a service is not working.
I created a host that will notify a user specifically.  It has a service that checks mysql.

The host and service are both inheriting from templates.
 The host has both user1 and a contact group that only has user2 in it.  Inherit Contacts form Host is checked directly on the service.  Enable notifications is checked on the service as well.

Going to Configure > Users > View Contact Notification and selecting either user reveals the service is not going to notify anyone.

Setting a contact group or contact directly on the service works as expected.

I have tested this on two different hosts and manually setup a service from scratch and have experienced the same issue.

**Comment by postmannen** [comment]
Experiencing the same problem. But I believed it was with Centreon Engine.
Posted as Issue #19 under centreon-engine 
https://github.com/centreon/centreon-engine/issues/19

**Comment by ganoze** [comment]
The "Inherit contacts from host" issue comes from Centreon Engine's behavior that do not inherit host's contacts in services. This will be fixed in the next Centreon Engine release.
