### ISSUE TITLE
Centreon Poller 20.04.4 : Could not load module '/usr/lib64/nagios/cbmod.so'

### ISSUE THREAD

**Issue by AlterSolaria** [centreon/centreon#8853]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20200602-094050.el7.centos.noarch
centreon-broker-storage-20.04.6-3.el7.centos.x86_64
centreon-engine-extcommands-20.04.4-1.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20200602-094050.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20200602-094050.el7.centos.noarch
centreon-connector-perl-20.04.0-2.el7.centos.x86_64
centreon-connector-20.04.0-2.el7.centos.x86_64
centreon-clib-20.04.0-7.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Central-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20200602-094050.el7.centos.noarch
centreon-common-20.04.4-6.el7.centos.noarch
centreon-broker-20.04.6-3.el7.centos.x86_64
centreon-broker-core-20.04.6-3.el7.centos.x86_64
centreon-engine-20.04.4-1.el7.centos.x86_64
centreon-gorgone-centreon-config-20.04.3-1.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20200602-094050.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20200602-094050.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200602-094050.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20200602-094050.el7.centos.noarch
centreon-release-20.04-1.el7.centos.noarch
centreon-connector-ssh-20.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Poller-20200602-094050.el7.centos.noarch
centreon-gorgone-20.04.3-1.el7.centos.noarch
centreon-engine-daemon-20.04.4-1.el7.centos.x86_64
centreon-broker-cbmod-20.04.6-3.el7.centos.x86_64
centreon-perl-libs-20.04.4-6.el7.centos.noarch
centreon-trap-20.04.4-6.el7.centos.noarch
centreon-poller-centreon-engine-20.04.4-6.el7.centos.noarch
```
***Operating System***

CentOS 7

***Browser used***

- [ ] Google Chrome
- [ x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 78.0.2

***Additional environment details (AWS, VirtualBox, physical, etc.):***
VMware ESXi 6.5.0

### Description
We've deployed a new poller running on Centreon 20.04 in order to replace an older poller that was running on Centreon Engine 1.8.1. We've installed the new poller using the Centreon ISO and linked it to our new Central also running Centreon 20.04. We used the "mass change" option to change the hosts from the old poller to the new one and then exported the configuration. However, after exporting the configuration, the poller is suddenly marked as "Not running" and is not monitoring our hosts though they appear in the hosts.cfg file.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Change an host from one poller to the new poller
2. Go to Configuration -> Poller
3. Export the configuration of the new Poller

### Describe the received result
The new poller is now marked as "Not running" and is not monitoring anything.

### Describe the expected result
The poller should start monitoring the hosts.

### Logs

**PHP error logs**

```
tail -f /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log
Empty log
```
**centreon-engine logs (*if needed*)**

```
tail -f /var/log/centreon-engine/centengine.log
[Thu Jul 16 16:34:08 2020] [16357] Error: Could not load module '/usr/lib64/nagios/cbmod.so': load library failed: /usr/lib64/nagios/cbmod.so: undefined symbol: servicedependency_list
```
**centreon-broker logs (*if needed*)**

```
tail -f /var/log/centreon-broker/central-broker-master.log
```
**centcore logs (*if needed*)**

```
tail -f /var/log/centreon/centcore.log
```

### Additional relevant information (e.g. frequency, ...)
The error in the centengine.log appears each time centengine is restarted whether is it with the web interface or using the systemctl command. Before showing this error, we had another error in the centengine.log :
```
[Fri Jul 10 09:33:48 2020] [6446] Error: Could not load module '/usr/lib64/nagios/cbmod.so': load library failed: libQtXml.so.4: cannot open shared object file: No such file or directory
```
We were able to get rid of this one by installing the Qt library that was missing.
Note : this library was already installed on the Centreon 19.10 ISO but is nowhere to be found when using the Centreon 20.04 ISO.

**Comment by cgagnaire** [comment]
Hi @AlterSolaria,
That's odd. Engine and Broker are not using Qt anymore.
Are you sure you did not copy the cbmod.so from the old Poller, along with plugins ?
Can you do a `file` and a `md5sum` of the file ?
And try to reinstall `centreon-broker-cbmod` ?
Thanks.

**Comment by AlterSolaria** [comment]
Hi @cgagnaire 

Thanks for the help ! Reinstalling centreon-broker-cbmod worked.
After restarting gorgoned and centengine on my central and exporting the configuration once more, I had my hosts monitored.

Thanks again !

**Comment by cgagnaire** [comment]
Good news!
Thanks for the feedback.
