### ISSUE TITLE
Export poller permission issue

### ISSUE THREAD

**Issue by cdc-ttexier** [centreon/centreon#8884]
Hello,

I'm trying to delegate poller "export configuration" feature to some people that i don't want to be admins.
they are affected to a menu access ACL for which configuration/pollers/export configuration is ticked but the button doesn't appear in their session.
another strange thing is when we click on read/write or readonly tick buttons for configuration/pollers, it changes the permission on other buttons not accordingly to what it should be: for example, i click read/write for configuration/pollers, it selects readonly for pollers and Engine configuration submenus (looks like a javascript issue).

i also tried with clapi commands:
ACLMENU;GRANTRW;mACL-HostsandServicesConfigOnly;0;Configuration;Pollers;
ACLMENU;GRANTRW;mACL-HostsandServicesConfigOnly;0;Configuration;Pollers;Export configuration;
ACLMENU;GRANTRW;mACL-HostsandServicesConfigOnly;0;Configuration;Pollers;Pollers;
ACLMENU;GRANTRW;mACL-HostsandServicesConfigOnly;0;Configuration;Pollers;Engine configuration;
but same result: ACL affected users don't see the export configuration button in pollers section.

thank you for your help.
I use Centreon 19.10.13

**Comment by cdc-ttexier** [comment]
same with version Centreon 19.10.15

**Comment by cdc-ttexier** [comment]
same with version Centreon 19.10.16

**Comment by matoy** [comment]
Hi,

Looks like problem is still on latest version 20.10.1.

Regards,

**Comment by matoy** [comment]
nevermind ; i guess it was coming from the beginning from the action ACL that did not include export configuration item.
please close this ticket.
