### ISSUE TITLE
[19.10.8] Impossible to delete comments in distant poller.

### ISSUE THREAD

**Issue by Worms95** [centreon/centreon#8925]
Hi,

I can create comment in local poller and i can delete it but it impossible to delete a comment for ahost in a distant poller.

### Logs

**Centcore logs**

```
2020-08-18 12:03:15 - INFO - External command : AA.BB.CC.DD (2) : "[1597744995] ADD_HOST_COMMENT;HOST_TEST;1;admin;test 18/08/2020
"
2020-08-18 12:03:36 - INFO - External command on Central Server: (1) : "[1597745016] DEL_HOST_COMMENT;232
"
```
Normaly : 
```
2020-08-18 12:03:36 - INFO - External command on AA.BB.CC.DD (2) : "[1597745016] DEL_HOST_COMMENT;232
"
```
AA.BB.CC.DD it's my distant poller where is attacher host HOST_TEST

how to fix this ?

Best regards,
Worms95

**Comment by lpinsivy** [comment]
Hi @Worms95 can you check on your distant poller that it receive the external command in /var/log/centreon-engine/centengine.log?

**Comment by Worms95** [comment]
Bonjour,
Il semblerait qu'il faille modifier le fichier common-Func.php dans .../www/include/monitoring/comments pour prendre en compte un poller distant.

**Comment by Worms95** [comment]
function DeleteComment

**Comment by Worms95** [comment]
ou dans comments.php dans : 
    case "ds":
        if (!empty($select)) {
            foreach ($select as $key => $value) {
                $res = explode(';', urldecode($key));
                DeleteComment($res[0], [(int)$res[1] . ';' . (int)$res[2] => 'on']);
                #DeleteComment($res[0], [$res[1] . ';' . (int)$res[2] => 'on']);
            }
        }

**Comment by Worms95** [comment]
Bonjour,
J'ai finalement trouvé la solution.
J'ai modifié 2 scripts PHP.
Cette modification me semble être une modification majeur pour la prochaine version de centreon.
Dans le fichier :
../www/include/monitoring/comments/comments.php
```
    case "ds":
        if (!empty($select)) {
            foreach ($select as $key => $value) {
                $res = explode(';', urldecode($key));
                #DeleteComment($res[0], [(int)$res[1] . ';' . (int)$res[2] => 'on']);
                DeleteComment($res[0], [$res[1] . ';' . (int)$res[2] => 'on']);
            }

```
Et dans le fichier :
../www/include/monitoring/comments/common-Func.php
```
    foreach ($hosts as $key => $value) {
        $res = preg_split("/\;/", $key);
        #$res[0] = filter_var($res[0] ?? 0, FILTER_VALIDATE_INT);
        $res[1] = filter_var($res[1] ?? 0, FILTER_VALIDATE_INT);
        write_command(" DEL_" . $type . "_COMMENT;" . $res[1], GetMyHostPoller($pearDB, $res[0]));
        }

```

**Comment by lpinsivy** [comment]
Hi,

This is already fixed for Centreon 19.04.19 and 19.10.16 by https://github.com/centreon/centreon/pull/8367

Regards,
