### ISSUE TITLE
Fresh install 20.04 -- Forced check does not work

### ISSUE THREAD

**Issue by IdrissaHilda** [centreon/centreon#8929]
# Forced check does not work

### Prerequisites

> Hi, after installe the Centreon 20.04 version the forced check does not work. I need help to resolve this problem because in the  log file we don't have any error about this problem. 

***Centreon 20.04***

Using packages

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon
```

centreon-release-20.04-1.el7.centos.noarch
centreon-broker-storage-20.04.7-1.el7.centos.x86_64
centreon-connector-20.04.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Database-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20200803-072952.el7.centos.noarch
centreon-engine-daemon-20.04.4-1.el7.centos.x86_64
centreon-trap-20.04.4-6.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20200803-072952.el7.centos.noarch
centreon-gorgone-20.04.3-1.el7.centos.noarch
centreon-poller-centreon-engine-20.04.4-6.el7.centos.noarch
centreon-clib-20.04.0-7.el7.centos.x86_64
centreon-broker-20.04.7-1.el7.centos.x86_64
centreon-engine-extcommands-20.04.4-1.el7.centos.x86_64
centreon-connector-perl-20.04.0-2.el7.centos.x86_64
centreon-license-manager-20.04.2-1.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20200803-072952.el7.centos.noarch
centreon-gorgone-centreon-config-20.04.3-1.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200803-072952.el7.centos.noarch
centreon-base-config-centreon-engine-20.04.4-6.el7.centos.noarch
centreon-perl-libs-20.04.4-6.el7.centos.noarch
centreon-broker-core-20.04.7-1.el7.centos.x86_64
centreon-engine-20.04.4-1.el7.centos.x86_64
centreon-connector-ssh-20.04.0-2.el7.centos.x86_64
centreon-pp-manager-20.04.1-1.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20200803-072952.el7.centos.noarch
centreon-auto-discovery-server-20.04.4-3.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20200803-072952.el7.centos.noarch
centreon-web-20.04.4-6.el7.centos.noarch
centreon-broker-cbmod-20.04.7-1.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200803-072952.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20200803-072952.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20200803-072952.el7.centos.noarch
centreon-common-20.04.4-6.el7.centos.noarch
centreon-broker-cbd-20.04.7-1.el7.centos.x86_64
centreon-license-manager-common-20.04.2-1.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20200803-072952.el7.centos.noarch

*CentOS

***Browser used***

- [ X ] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 20.04

### Logs

```
**centreon-engine logs (*if needed*)**

```
tail -f /var/log/centreon-engine/centengine.log
```
**centreon-broker logs (*if needed*)**

```
tail -f /var/log/centreon-broker/central-broker-master.log
```
**centcore logs (*if needed*)**

```
tail -f /var/log/centreon/centcore.log
```
the forced check does not work.

![image](https://user-images.githubusercontent.com/56160040/90870432-de760780-e399-11ea-8372-22393d26599a.png)

**Comment by cgagnaire** [comment]
Hi @IdrissaHilda,
Do you have only one Central or do you also have Pollers ?
Is this problem only on hosts monitored by Central ?
Can you provide us the log of the Central's Gorgone:
- enable debug from 'Administration > Parameters > Debug',
- restart `gorgoned`,
- do the "force check" action,
- retrieve file `/var/log/centreon-gorgone/gorgoned.log`.

Thank you.

**Comment by IdrissaHilda** [comment]
Hi @cgagnaire ,

I just have a central server and it's this server that does the collections.

When I look at the logs here is the result.
![image](https://user-images.githubusercontent.com/56160040/91170231-dccd7c00-e6d8-11ea-9b42-398efc1cdf04.png)

I don't have any trace on the launched forced check.

**Comment by cgagnaire** [comment]
Hi @IdrissaHilda,
Ok so it looks like Gorgone's database is not readable by centreon-gorgone user.
Try this: `chown centreon-gorgone. /var/lib/centreon-gorgone/history.sdb`
And restart `gorgoned`.

**Comment by IdrissaHilda** [comment]
When the log was activate 
> tailf /var/log/centreon-gorgone/gorgoned.log

![image](https://user-images.githubusercontent.com/56160040/91178119-fd033800-e6e4-11ea-8e2a-8f57db5cd3d4.png)
` (caller: gorgone::class::db:/usr/share/perl5/vendor_perl/gorgone/class/db.pm:278)`

I don't know if it's normal to have a "connection refused" . knowing that on the web interface everything seems to be ok.

![image](https://user-images.githubusercontent.com/56160040/91178357-4e132c00-e6e5-11ea-84ee-254c3d392a57.png)

I don't have any trace on the launched forced check.

**Comment by cgagnaire** [comment]
Can you change the dsn in `/etc/centreon/config.d/10-database.yaml` to `mysql:host=dev.centreon.db.corp.ssg;port=3307;dbname=centreon` and `mysql:host=dev.centreon.db.corp.ssg;port=3307;dbname=centreon_storage` ?

**Comment by IdrissaHilda** [comment]
Hi @cgagnaire , 
Here is the content of the file and the information is the same that you ask me to fill in.
![image](https://user-images.githubusercontent.com/56160040/91546587-fcf07b80-e922-11ea-8b56-9e301af366e2.png)

**Comment by cgagnaire** [comment]
Hi @IdrissaHilda,
Actually the port is not defined the same.
Can you change it and test again ?

**Comment by IdrissaHilda** [comment]
Thank you, it's ok, the problem is solved.

**Comment by cgagnaire** [comment]
You're welcome!
