### ISSUE TITLE
Option to Graphs show real values instead of average values

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#893]
---

Author Name: **manuvaldi -** (manuvaldi -)
Original Redmine Issue: 369, https://forge.centreon.com/issues/369

---

Is There any posibility or option for showing graphs with real values instead of averages.

For example, I have some checks that show traffic peak. With centreon this peaks show less important because the interface show averages. I need to show real values to my users.

**Comment by lpinsivy** [comment]
linked to #1184 #2125
