### ISSUE TITLE
Not using BAM but /var get wasted by central-broker-master.queue.centreon-bam-monitoring files

### ISSUE THREAD

**Issue by elmarsievers** [centreon/centreon#8935]
# BUG REPORT INFORMATION

***Versions***

centreon-plugin-Applications-Protocol-Ldap-20200803-072952.el7.centos.noarch
centreon-release-20.04-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-pp-manager-20.04.1-1.el7.centos.noarch
centreon-engine-daemon-20.04.5-1.el7.centos.x86_64
centreon-gorgone-20.04.4-1.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20200803-072952.el7.centos.noarch
centreon-base-config-centreon-engine-20.04.5-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.04.0-5.el7.centos.noarch
centreon-widget-engine-status-20.04.1-1.el7.centos.noarch
centreon-broker-20.04.8-1.el7.centos.x86_64
centreon-widget-host-monitoring-20.04.4-4.el7.centos.noarch
centreon-database-20.04.5-5.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200803-072952.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20200803-072952.el7.centos.noarch
centreon-poller-centreon-engine-20.04.5-5.el7.centos.noarch
centreon-clib-20.04.0-7.el7.centos.x86_64
centreon-widget-servicegroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-grid-map-20.04.0-5.el7.centos.noarch
centreon-widget-global-health-20.04.0-5.el7.centos.noarch
centreon-connector-ssh-20.04.0-2.el7.centos.x86_64
centreon-license-manager-common-20.04.2-1.el7.centos.noarch
centreon-common-20.04.5-5.el7.centos.noarch
centreon-broker-storage-20.04.8-1.el7.centos.x86_64
centreon-engine-20.04.5-1.el7.centos.x86_64
centreon-widget-service-monitoring-20.04.3-3.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200803-072952.el7.centos.noarch
centreon-auto-discovery-server-20.04.4-3.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20200803-072952.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20200803-072952.el7.centos.noarch
centreon-widget-httploader-20.04.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.04.0-5.el7.centos.noarch
centreon-connector-20.04.0-2.el7.centos.x86_64
centreon-license-manager-20.04.2-1.el7.centos.noarch
centreon-perl-libs-20.04.5-5.el7.centos.noarch
centreon-broker-core-20.04.8-1.el7.centos.x86_64
centreon-broker-cbmod-20.04.8-1.el7.centos.x86_64
centreon-trap-20.04.5-5.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20200803-072952.el7.centos.noarch
centreon-gorgone-centreon-config-20.04.4-1.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20200803-072952.el7.centos.noarch
centreon-20.04.5-5.el7.centos.noarch
centreon-web-20.04.5-5.el7.centos.noarch
centreon-broker-cbd-20.04.8-1.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Database-20200803-072952.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20200803-072952.el7.centos.noarch
centreon-widget-tactical-overview-20.04.0-5.el7.centos.noarch
centreon-connector-perl-20.04.0-2.el7.centos.x86_64
centreon-engine-extcommands-20.04.5-1.el7.centos.x86_64

```
***Operating System***


CentOS Linux release 7.8.2003 (Core)


***Browser used***

Edge Chromium

Not using BAM but /var get wasted by central-broker-master.queue.centreon-bam-monitoring files



tail -f /var/log/centreon-broker/central-broker-master.log
[1598264081] error:   BAM-BI: could not load timeperiods from DB: statement preparation failed (Unknown column 'relation_id' in 'where clause')
[1598264082] error:   BAM: could not process configuration update: BAM: could not retrieve BA configuration from DB: BAM: Unknown column 'b.state_source' in 'field list' while executing query SELECT b.ba_id, b.name, b.state_source, b.level_w,       b.level_c, b.last_state_change, b.current_status,       b.in_downtime, b.inherit_kpi_downtimes  FROM mod_bam AS b  INNER JOIN mod_bam_poller_relations AS pr    ON b.ba_id=pr.ba_id  WHERE b.activate='1'    AND pr.poller_id=1


How to consequently disable BAM?

Kind Regards

**Comment by Moujimouja** [comment]
Hi, 

It's probably because at one point you had Centreon BAM installed or you took a dump from a platform where Centreon BAM was installed.

To stop the problem, you need to remove the output corresponding to BAM.  To do so, go `Configuration  >  Pollers  >  Broker configuration`,  click on your "Central Broker" configuration and remove **outputs** called "Monitoring engine (BAM)" and the other one  BI engine (BAM)

![image](https://user-images.githubusercontent.com/6620287/91057882-16927a00-e628-11ea-96c2-5e56bfb870cb.png)

If you don't have them, can you send the configuration file of your Centreon Broker in `/etc/centreon-broker/`

Did it work for you ?

**Comment by elmarsievers** [comment]
HI Moujimouja,

that worked thank you very much!

Can I just safely delete all files in /var/lib/centreon-broker containing the words bam and queue (e. g. central-broker-master.queue.centreon-bam-reporting & central-broker-master.queue.centreon-bam-monitoring24?

**Comment by Moujimouja** [comment]
Yep you can but stop broker before doing that.

I close this ticket then, have a nice day ;)
