### ISSUE TITLE
BAM host object visible in performance graph filters

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon#8975]
***Versions***

centreon-web-20.04.5-5.el7.centos.noarch
centreon-bam-server-20.04.3-2.el7.centos.noarch

***Operating System***

CentOS 7

***Browser used***
- [x ] Google Chrome

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I go to Monitoring  >  Performances  >  Graphs
2. I search a host in Filter by host , i found  host name like BAM
3. And so no graph (ok) but why i found this "host" in this filter?

### Describe the received result
I found host named BAM

### Describe the expected result
Find real hosts with graph associated

### Logs / Sreenshot

![bug__graph_bam](https://user-images.githubusercontent.com/16045498/92696447-2c9f7a80-f34a-11ea-9b9b-6d281c947b10.png)

**Comment by lpinsivy** [comment]
I din't understand.

If you filter by "BAM" for "Filter by Host" then you access to "Chart", you can see the list of Business Activities, select them and display associated chart:
<img width="1377" alt="bam_charts" src="https://user-images.githubusercontent.com/3351916/93091710-c0e94480-f69e-11ea-9b3e-44f95359e542.png">
