### ISSUE TITLE
Unable to Edit/Disable/Enable a command/notification.

### ISSUE THREAD

**Issue by vineethvin2007** [centreon/centreon#9011]
Environment: Azure
OS : Red Hat Enterprise Linux Server release 7.8 (Maipo)
Centreon Version: 

centreon-web-20.04.5-5.el7.centos.noarch
centreon-widget-tactical-overview-20.04.0-5.el7.centos.noarch
centreon-release-20.04-1.el7.centos.noarch
centreon-common-20.04.5-5.el7.centos.noarch
centreon-perl-libs-20.04.5-5.el7.centos.noarch
centreon-engine-daemon-20.04.6-1.el7.centos.x86_64
centreon-connector-20.04.0-2.el7.centos.x86_64
centreon-license-manager-common-20.04.2-1.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20200803-072952.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-engine-status-20.04.1-1.el7.centos.noarch
centreon-base-config-centreon-engine-20.04.5-5.el7.centos.noarch
centreon-broker-20.04.8-1.el7.centos.x86_64
centreon-plugin-Network-Cisco-Standard-Snmp-20200803-072952.el7.centos.noarch
centreon-broker-storage-20.04.8-1.el7.centos.x86_64
centreon-pp-manager-20.04.1-1.el7.centos.noarch
centreon-widget-graph-monitoring-20.04.0-5.el7.centos.noarch
centreon-gorgone-20.04.5-1.el7.centos.noarch
centreon-20.04.5-5.el7.centos.noarch
centreon-trap-20.04.5-5.el7.centos.noarch
centreon-broker-cbmod-20.04.8-1.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Database-20200803-072952.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20200803-072952.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.04.3-3.el7.centos.noarch
centreon-widget-global-health-20.04.0-5.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20200803-072952.el7.centos.noarch
centreon-gorgone-centreon-config-20.04.5-1.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20200803-072952.el7.centos.noarch
centreon-broker-cbd-20.04.8-1.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20200803-072952.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.04.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.04.4-4.el7.centos.noarch
centreon-auto-discovery-server-20.04.5-2.el7.centos.noarch
centreon-poller-centreon-engine-20.04.5-5.el7.centos.noarch
centreon-clib-20.04.0-7.el7.centos.x86_64
centreon-plugin-Applications-Databases-Mysql-20200803-072952.el7.centos.noarch
centreon-broker-core-20.04.8-1.el7.centos.x86_64
centreon-license-manager-20.04.2-1.el7.centos.noarch
centreon-widget-grid-map-20.04.0-5.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20200803-072952.el7.centos.noarch
centreon-database-20.04.5-5.el7.centos.noarch
centreon-engine-20.04.6-1.el7.centos.x86_64
centreon-connector-ssh-20.04.0-2.el7.centos.x86_64
centreon-widget-httploader-20.04.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.04.0-5.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20200803-072952.el7.centos.noarch
centreon-engine-extcommands-20.04.6-1.el7.centos.x86_64
centreon-connector-perl-20.04.0-2.el7.centos.x86_64
centreon-plugin-Hardware-Printers-Generic-Snmp-20200803-072952.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20200803-072952.el7.centos.noarch

### Description

Unable to Edit a command/notification.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1) login to Centreon
2) go to Commands/Checks/Notifications
3) open one check
4) change something (Disable/Enable/Edit)
5) Click save button

### Describe the received result

Throws error : {SERVER_IP} didn’t send any data. 

![tempsnip](https://user-images.githubusercontent.com/37109240/93720041-2c05b000-fba4-11ea-8494-ac61cde30279.png)

### Describe the expected result

The command/check/notification should be editable. We should be able to disable/enable it.

### Logs

Nothing relevant in logs found related to this issue. Verified all services are up and running. PS: This is a fresh installation.

centreon-devel ~]# systemctl status centreon.service
● centreon.service - One Service to rule them all.
   Loaded: loaded (/usr/lib/systemd/system/centreon.service; enabled; vendor preset: disabled)
   Active: active (exited) since Thu 2020-09-17 18:09:06 UTC; 3 days ago
 Main PID: 3471 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/centreon.service

centreon-devel systemd[1]: Starting One Service to rule them all....
centreon-devel systemd[1]: Started One Service to rule them all..
centreon-devel ~]# systemctl status centreontrapd.service
● centreontrapd.service - Centreon Trapd Daemon is a Centreon program that manage traps
   Loaded: loaded (/usr/lib/systemd/system/centreontrapd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-09-17 18:09:06 UTC; 3 days ago
 Main PID: 3475 (centreontrapd)
   CGroup: /system.slice/centreontrapd.service
           └─3475 /usr/bin/perl /usr/share/centreon/bin/centreontrapd --logfile=/var/log/centreon/centreontrapd.log --severity=error --config=/etc/centreon/conf.pm --config-ext...

centreon-devel systemd[1]: Started Centreon Trapd Daemon is a Centreon program that manage traps.
centreon-devel ~]# systemctl status cbd.service
● cbd.service - Centreon Broker watchdog
   Loaded: loaded (/usr/lib/systemd/system/cbd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-09-17 18:09:06 UTC; 3 days ago
 Main PID: 3473 (cbwd)
   CGroup: /system.slice/cbd.service
           ├─3473 /usr/sbin/cbwd /etc/centreon-broker/watchdog.json
           ├─3477 /usr/sbin/cbd /etc/centreon-broker/central-broker.json
           └─3478 /usr/sbin/cbd /etc/centreon-broker/central-rrd.json

centreon-devel systemd[1]: Started Centreon Broker watchdog.
centreon-devel cbwd[3473]: [1600366146] config:  log applier: applying 1 logging objects
centreon-devel cbwd[3473]: [1600366146] config:  log applier: applying 1 logging objects
centreon-devel ~]# systemctl status gorgoned.service
● gorgoned.service - Centreon Gorgone
   Loaded: loaded (/etc/systemd/system/gorgoned.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2020-09-20 18:48:17 UTC; 22min ago
 Main PID: 16190 (perl)
   CGroup: /system.slice/gorgoned.service
           ├─16190 /usr/bin/perl /usr/bin/gorgoned --config=/etc/centreon-gorgone/config.yaml --logfile=/var/log/centreon-gorgone/gorgoned.log --severity=info
           ├─16197 gorgone-nodes
           ├─16199 gorgone-dbcleaner
           ├─16211 gorgone-autodiscovery
           ├─16217 gorgone-cron
           ├─16225 gorgone-engine
           ├─16238 gorgone-statistics
           ├─16247 gorgone-action
           ├─16281 gorgone-httpserver
           ├─16284 gorgone-legacycmd
           ├─16302 gorgone-proxy
           ├─16311 gorgone-proxy
           ├─16320 gorgone-proxy
           ├─16327 gorgone-proxy
           └─16334 gorgone-proxy

Sep 20 18:48:17 centreon-devel systemd[1]: Started Centreon Gorgone.

**Comment by cgagnaire** [comment]
Hi @vineethvin2007,
Do you have a Palo Alto firewall in your network ?

**Comment by vineethvin2007** [comment]
@cgagnaire , Yes, we have a Palo Alto and after your comment while checking the firewall it shows the request being generated as a vulnerability and is blocking the request. By any chance do you have more information about this vulnerability or what is causing Palo Alto see Centreon request as a vulnerable one?

**Comment by vineethvin2007** [comment]
@cgagnaire We have the latest information from Palo Alto regarding the vulnerabilities. The following are the listed vulnerabilities. 

![CPAV](https://user-images.githubusercontent.com/37109240/93902301-077d1580-fd15-11ea-8cb4-b988f6bcfd60.JPG)

As per the website https://www.cybersecurity-help.cz/vdb/SB2019112908, we have to update to the latest patch available for the product. But we are already using the latest patch available in the Centreon repository. Can you recommend some solution for this.

**Comment by cgagnaire** [comment]
Hi @vineethvin2007,
Yes actually those have been fixed since Centreon Web 19.04.5.
Now, we don't know how and when PaloAlto will issue a protection signature that will remove the vulnerabilities protection.
So you can contact the support to ask them, and in the meantime add a rule on your firewall to allow the requests. You can do it from the firewall console and the Logs > Threat menu: you'll see the blocked requests there.

**Comment by cgagnaire** [comment]
Hi @vineethvin2007,
As we cannot do anything on our side, I'm closing that issue.
Don't hesitate to comment if you have any feedbacks from PaloALto.
