### ISSUE TITLE
Sending SNMP trap 'Enterprise OID' to a 'preexec' command as a variable

### ISSUE THREAD

**Issue by ahurtadob** [centreon/centreon#9044]
Hi!

I've been testing Centreon and I'm specially interested in passive monitoring (we manage a lot of SNMP traps).
I've been learning about how Centreon manages SNMP traps and I know trap variables can be passed to a preexec command using 'macros' like @{NUMERIC_OID}. 

But is there any 'macro' for trap Enterprise OID? It would be very useful for us to be able to pass the trap Enterprise OID to a preexec script in order to unify traps managemenent. According to https://docs.centreon.com/current/en/monitoring/passive-monitoring/create-snmp-traps-definitions.html, I pass to my preexec script a list of variables, for instance @TRAPOUTPUT@ or @{NUMERIC_OID}, but what about the Enterprise OID? What about the OID I use to define the trap in Centreon? Can I get it? Is there any contextual variable that keeps it?

Thankd in advance!

Albert

**Comment by cgagnaire** [comment]
Hi @ahurtadob,
Maybe @garnier-quentin can help on this one.

**Comment by garnier-quentin** [comment]
You can pass entreprise OIDs to a prexec command (like: $1, $2,..) or special variables like $R, $r, $aR, $a,....

**Comment by ahurtadob** [comment]
Hi @garnier-quentin 
I didn't know anything about these variables you show ($R, $r, $a...). Are they documented? 
I tested the ones you commented. None of them is the enterprise OID. 
Thanks in advance.

**Comment by garnier-quentin** [comment]
Do you talk of the trap OID itself ? Because you want to use the same preexec script for different trap OIDs ? 

I have looked my code and i didn't map a special variable for var[3] (trap oid it's here...)
You could use custom code and save the var[3] in ```$self->{user_arg1}``` and use after ```@USERARG1@```.

**Comment by garnier-quentin** [comment]
I could also do a patch. It will be easier.

**Comment by ahurtadob** [comment]
Exactly, I want to use same script for different OIDs. If I can have Enterprise OID in a special variable, everything is easier without adding any code.

**Comment by ahurtadob** [comment]
A patch would be fantastic.

**Comment by garnier-quentin** [comment]
The patch is here:
https://github.com/centreon/centreon/pull/9182

The important part is: https://github.com/centreon/centreon/pull/9182/files#diff-ff0468526656a52d5c94ad415827689e9b410f2a50da5f9a555f30ad3526e81eR892
