### ISSUE TITLE
After update to 20.04 acknowledge, downtime and schedule immediate check (force) don't work

### ISSUE THREAD

**Issue by Olda7** [centreon/centreon#9046]
$ rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
centreon-20.04.5-5.el7.centos.noarch
centreon-auto-discovery-server-20.04.5-2.el7.centos.noarch
centreon-awie-20.04.0-4.el7.centos.noarch
centreon-base-config-centreon-engine-20.04.5-5.el7.centos.noarch
centreon-broker-20.04.8-1.el7.centos.x86_64
centreon-broker-cbd-20.04.8-1.el7.centos.x86_64
centreon-broker-cbmod-20.04.8-1.el7.centos.x86_64
centreon-broker-core-20.04.8-1.el7.centos.x86_64
centreon-broker-storage-20.04.8-1.el7.centos.x86_64
centreon-clib-20.04.0-7.el7.centos.x86_64
centreon-common-20.04.5-5.el7.centos.noarch
centreon-connector-20.04.0-2.el7.centos.x86_64
centreon-connector-perl-20.04.0-2.el7.centos.x86_64
centreon-connector-ssh-20.04.0-2.el7.centos.x86_64
centreon-database-20.04.5-5.el7.centos.noarch
centreon-engine-20.04.6-1.el7.centos.x86_64
centreon-engine-daemon-20.04.6-1.el7.centos.x86_64
centreon-engine-extcommands-20.04.6-1.el7.centos.x86_64
centreon-gorgone-20.04.5-1599059176.c0ba4e3.el7.centos.noarch
centreon-gorgone-centreon-config-20.04.5-1599059176.c0ba4e3.el7.centos.noarch
centreon-license-manager-20.04.2-1.el7.centos.noarch
centreon-license-manager-common-20.04.2-1.el7.centos.noarch
centreon-perl-libs-20.04.5-5.el7.centos.noarch
centreon-poller-centreon-engine-20.04.5-5.el7.centos.noarch
centreon-pp-manager-20.04.1-1.el7.centos.noarch
centreon-release-20.04-1.el7.centos.noarch
centreon-trap-20.04.5-5.el7.centos.noarch
centreon-web-20.04.5-5.el7.centos.noarch
centreon-widget-engine-status-20.04.1-1.el7.centos.noarch
centreon-widget-global-health-20.04.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-grid-map-20.04.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.04.4-4.el7.centos.noarch
centreon-widget-httploader-20.04.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.04.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.04.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.04.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.04.3-3.el7.centos.noarch
centreon-widget-tactical-overview-20.04.0-5.el7.centos.noarch
```
***Operating System***

*CentOS

***Browser used***

- [ X] Google Chrome
- [ X] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

### Description

After update to 20.04 i'm not able to do the following actions :

Acknowledge
downtime
schedule immediate check

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

I logged in Centreon
I reached the Monitoring > Status Detials > Services view
I checked some services
I acknowledge them

### Describe the received result
If I try acknowledge problem, I can see the popup window and I can click add, but nothing happend. I can see the actions i'm doing in centcore.cmd. I try restart gorgoned centengine centreon and cbd. All of this are runnig.

tail -f /var/lib/centreon/centcore.cmd
EXTERNALCMD:4:[1601028964] ACKNOWLEDGE_SVC_PROBLEM;XXX;CPU;2;0;1;XXX;Acknowledged by XXX

### Describe the expected result

### Logs

**PHP error logs**

```
tail -f /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log
Empty
```
**centreon-engine logs (*if needed*)**

```
tail -f /var/log/centreon-engine/centengine.log
```
**centreon-broker logs (*if needed*)**

```
tail -f /var/log/centreon-broker/central-broker-master.log
empty
```
**centreon gorgone logs for Centreon >= 20.4  (*if needed*)**

```
tail -f /var/log/centreon-gorgone/gorgoned.log
empty
```
**centcore logs for Centreon <= 19.10.x (*if needed*)**

```
tail -f /var/log/centreon/centcore.log
only old error
```

### Additional relevant information (e.g. frequency, ...)

In conf.pm is way to centcore.cmd 
# Centreon Centcore Command File
$cmdFile = "/var/lib/centreon/centcore.cmd";

ls -lah /var/lib/centreon/
total 460K
drwxrwxr-x. 10 centreon centreon  152 sep 28 09:28 .
drwxr-xr-x. 35 root     root     4,0K sep  4 16:01 ..
drwxrwxr-x.  2 centreon centreon 8,0K sep 25 11:17 centcore
-rw-r--r--   1 apache   apache   1,4K sep 25 12:16 centcore.cmd
drwxrwxr-x.  2 centreon centreon  16K sep 25 11:24 centplugins
drwxrwxr-x   3 centreon centreon   45 sep  4 16:21 installs
drwxrwxr-x.  2 centreon centreon    6 aug  6 14:43 log
drwxrwxr-x.  2 centreon centreon 188K sep 25 12:18 metrics
drwxrwxr-x.  3 centreon centreon   23 aug  6 14:43 nagios-perf
drwxrwxr-x.  2 centreon centreon    6 aug  6 14:43 perfdata
drwxrwxr-x.  2 centreon centreon  76K sep 24 08:21 status

ls -lah /var/lib/
total 12K
drwxr-xr-x. 35 root             root             4,0K sep  4 16:01 .
drwxr-xr-x. 21 root             root             4,0K sep 16 15:33 ..
drwxr-xr-x.  2 root             root               79 sep  6 20:00 alternatives
drwx------.  3 root             root               18 júl 11  2018 authconfig
drwxrwxr-x. 10 centreon         centreon          152 sep 28 09:28 centreon

tail -f /var/lib/centreon/centcore.cmd
EXTERNALCMD:4:[1601028964] ACKNOWLEDGE_SVC_PROBLEM;XXX;CPU;2;0;1;XXX;Acknowledged by XXX

**Comment by cgagnaire** [comment]
Hi @Olda7,
Do you still have this issue ?
If yes, can you update to the latest 20.04.x for all components, or at least Gorgone ?
Can you put Gorgone in debug (from Administration > Parameters > Debug) and restart it.
Then do an acknownledgement and post the log here from the restart to the acknowledgement action.
Thank you.
