### ISSUE TITLE
[Stream Connector] - fill up the broker_cache methods

### ISSUE THREAD

**Issue by ppremont-capensis** [centreon/centreon#9085]
### Feature explanation

Complete the list of available methods of the broker_cache object or add some more attributes in your host and service status events (category 1 and element 14 or 24).

### What is the value of the wanted feature ?

For interconnection purpose, we need to get some more informations about host and service status events like :

- host's alias
- instance name
- all defined macro

### Additional information

We have found some of these variables in other elements as the 12 by example but it's not where we can consider to get it.
What is the real difference by the way between host/service status elements and raw host/service elements ?

Centreon-broker version tested : centreon-broker-20.04.8-1.el7.centos.x86_64

**Comment by Sims24** [comment]
Hello @ppremont-capensis

**Comment by paulpremont** [comment]
Ok so where do you prefer this issue ? In stream-connector or centreon-broker ?
Many thanks.

**Comment by ppremont-capensis** [comment]
Ok so where do you prefer this issue ? Into stream-connector or the centreon-broker dedicated github.
Many thanks.

**Comment by Sims24** [comment]
I opened it here https://github.com/centreon/centreon-broker/issues/473

We'll come back to you as soon as possible
