### ISSUE TITLE
Centreon (19.10.15 and 20.04.05) always send statistics

### ISSUE THREAD

**Issue by MiStErLu** [centreon/centreon#9144]
Hi all,

    In my centreon interface administration (20.04. i have uncheck this options long time ago : 

   ![image](https://user-images.githubusercontent.com/5516692/96888809-4cb47480-1486-11eb-8e89-1b537d3f1e28.png)

   But i can see in my statistics.log many entry that statistics are sent...

![image](https://user-images.githubusercontent.com/5516692/96889076-88e7d500-1486-11eb-9a33-87a03415df3d.png)
 
   Can you fix this bug (or it's probably not a bug...) ?

Best regards,
MiStErLu

**Comment by UrBnW** [comment]
See #9145 for a fix.

**Comment by lpinsivy** [comment]
HI @MiStErLu and @UrBnW 

As defined in contract, if the platform has a valid license, statistics are sent.
You can disable this option only if you use the Open Source Edition.

Regards,

**Comment by UrBnW** [comment]
@lpinsivy I think there's still an issue, because even in Open Source Edition with option disabled, requests are done.
We should then re-open (rework if needed) #9145.
Thx 👍

**Comment by MiStErLu** [comment]
Hi @lpinsivy 

   We use Open Source Edition. And before this patch, the statistics were always send if option was check or not.

Regards,

**Comment by lpinsivy** [comment]
@MiStErLu , @UrBnW,

As described in [the documentation](https://docs.centreon.com/current/en/ceip/what-is-centreon-ceip.html), their is 2 programs:

- A simple telemetry
- Advanced statistics on the use of the Centreon software suite

Simple telemetry is always sent but advanced statistics can be sent or not (regarding the status of the option "Send anonymous statistics") only if you Centreon Open Source Edition.

To better manage the roadmap of the product, we need to know how our user use the product. Have anonymously the OS version, the Centreon version and the architecture (standalone / distributed) are really small information but really important for us.

Regards

**Comment by garnier-quentin** [comment]
The simple way is to disable the script in cron file ```/etc/cron.d/centreon```:
```
#9 3 * * * centreon /opt/rh/rh-php72/root/usr/bin/php -q /usr/share/centreon/cron/centreon-send-stats.php >> /var/log/centreon/statistics.log 2>&1
```

**Comment by UrBnW** [comment]
Yes, or to null-out the domain in `/etc/hosts` :
`127.0.0.1	statistics.centreon.com`

**Comment by UrBnW** [comment]
_I think we can finally close this @MiStErLu._

**Comment by UrBnW** [comment]
_I think we can finally close this @MiStErLu._
