### ISSUE TITLE
Discovery host not accessible by a non-admin user (ACL)

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon#9150]
***Versions***

```
$ rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
centreon-19.10.15-2.el7.centos.noarch
centreon-auto-discovery-server-19.10.4-1.el7.centos.noarch
centreon-base-config-centreon-engine-19.10.15-2.el7.centos.noarch
centreon-broker-19.10.5-1.el7.centos.x86_64
centreon-broker-cbd-19.10.5-1.el7.centos.x86_64
centreon-broker-cbmod-19.10.5-1.el7.centos.x86_64
centreon-broker-core-19.10.5-1.el7.centos.x86_64
centreon-broker-storage-19.10.5-1.el7.centos.x86_64
centreon-clib-19.10.0-6.el7.centos.x86_64
centreon-common-19.10.15-2.el7.centos.noarch
centreon-connector-19.10.1-1.el7.centos.x86_64
centreon-connector-perl-19.10.1-1.el7.centos.x86_64
centreon-connector-ssh-19.10.1-1.el7.centos.x86_64
centreon-database-19.10.15-2.el7.centos.noarch
centreon-engine-19.10.15-2.el7.centos.x86_64
centreon-engine-daemon-19.10.15-2.el7.centos.x86_64
centreon-engine-extcommands-19.10.15-2.el7.centos.x86_64
centreon-license-manager-19.10.1-3.el7.centos.noarch
centreon-license-manager-common-19.10.1-3.el7.centos.noarch
centreon-perl-libs-19.10.15-2.el7.centos.noarch
centreon-poller-centreon-engine-19.10.15-2.el7.centos.noarch
centreon-pp-manager-19.10.1-3.el7.centos.noarch
centreon-release-19.10-1.el7.centos.noarch
centreon-trap-19.10.15-2.el7.centos.noarch
centreon-web-19.10.15-2.el7.centos.noarch
centreon-widget-engine-status-19.10.2-1.el7.centos.noarch
centreon-widget-global-health-19.10.1-1.el7.centos.noarch
centreon-widget-graph-monitoring-19.10.2-1.el7.centos.noarch
centreon-widget-grid-map-19.10.1-1.el7.centos.noarch
centreon-widget-hostgroup-monitoring-19.10.1-1.el7.centos.noarch
centreon-widget-host-monitoring-19.10.6-6.el7.centos.noarch
centreon-widget-httploader-19.10.1-1.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-19.10.1-1.el7.centos.noarch
centreon-widget-live-top10-memory-usage-19.10.1-1.el7.centos.noarch
centreon-widget-servicegroup-monitoring-19.10.1-1.el7.centos.noarch
centreon-widget-service-monitoring-19.10.6-6.el7.centos.noarch
centreon-widget-tactical-overview-19.10.1-1.el7.centos.noarch
```

***Operating System***

*CentOS 7*

***Browser used***

- [x] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

***Additional environment details (AWS, VirtualBox, physical, etc.): VM (vsphere)***

### Description

1. as an admin user, the host discovery module appears.
2. as a non-admin user (via the acl), the host discovery module does not appear.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon via non-admin user.
2. I reached the Host View and Discovery
3. No line appears

Non admin user:
![Capture d’écran_2020-10-26_22-34-19](https://user-images.githubusercontent.com/61595839/97232045-c331d900-17dc-11eb-8d23-4256428951cb.png)

Admin user:
![Capture d’écran_2020-10-26_22-34-55](https://user-images.githubusercontent.com/61595839/97232073-cf1d9b00-17dc-11eb-90ff-5fedde3dc839.png)

ACL user:
![Capture d’écran_2020-10-26_22-46-49](https://user-images.githubusercontent.com/61595839/97232315-363b4f80-17dd-11eb-8468-f05d10a3c7dc.png)

### Logs

**no PHP error logs**

### Additional relevant information (e.g. frequency, ...)
permanently with non-admin user

**Comment by gagzou** [comment]
Hi,
Same problem with Centreon 19.10.16.

**Comment by gagzou** [comment]
Hi,
Do you need specific logs?
Best regards

**Comment by cgagnaire** [comment]
Hi @gagzou,
I don't seem to be able to reproduce your problem.
Can you indeed open the developer console of your browser and hit the refresh button above the table while in the Host Discovery page.
You should have a request on with parameters looking like that: "/centreon/api/internal.php?object=centreon_host_discovery&action=jobs&search=..." .
Please give use the status and message of the response of this request.
Thanks.

**Comment by gagzou** [comment]
Hi,
Request:
https://xxxxxxxxxxxxxxxxx/centreon/api/internal.php?object=centreon_host_discovery&action=jobs&search={%22$and%22:[{%22$or%22:[{%22connection_name%22:{%22$lk%22:%22%22}},{%22alias%22:{%22$lk%22:%22%22}},{%22generate_date%22:{%22$lk%22:%22%22}}]},{%22$or%22:[{%22status%22:{%22$eq%22:%223%22}},{%22status%22:{%22$eq%22:%220%22}},{%22status%22:{%22$eq%22:%221%22}},{%22status%22:{%22$eq%22:%222%22}}]}]}&page=1&limit=25&sort_by=generate_date&order_by=desc

Response:
"Forbidden"

Status:
403 Forbidden

**Comment by gagzou** [comment]
Same problem with Firefox or Chrome

**Comment by cgagnaire** [comment]
Well like I said, I cannot reproduce.
I can only reproduce by removing the menu access while connected with the non-admin user in a private window.
Maybe @kduret have a clue ?

**Comment by gagzou** [comment]
For information, when I click on 'ADD', I have the message :
**First, install plugin packs which provide host discovery rules**

At networl level : 403 Forbidden
GET https://xxxxx/centreon/api/internal.php?object=centreon_host_discovery&action=providers

**Comment by gagzou** [comment]
Resolve with 20.10 upgrade.

**Comment by gagzou** [comment]
Resolve with 20.10 upgrade.
