### ISSUE TITLE
Unable to hide passwords in command

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#9173]
Hi,

There are still some occasions where the "Unable to hide passwords in command" message shows-up.
Below is the most annoying one.
Tests were done with #9168 patch over `19.10.16`, and with `20.10.0`.
And again with `19.10.18`.

```
Command = /bin/echo OK $_SERVICEUSER$ $_SERVICEPASS$ $RESOURCE$
$_SERVICEUSER$ = user
$_SERVICEPASS$ = pass
$RESOURCE$ = two items

19.10 KO : Unable to hide passwords in command
20.10 KO : Unable to hide passwords in command (Reason: Different number of tokens between configuration and monitoring command line)
```

As you can see, if we use a poller resource (or a [macro](https://github.com/centreon/centreon/issues/9173#issuecomment-829157441)) containing spaces, algorithm fails.
Rather annoying, as using such resources is really convenient (to default various options in all commands etc...).
Could it then be possible to handle this case please ?

Thank you :+1:

**Comment by UrBnW** [comment]
Hi @callapa, I link you to this bug, as you wrote the algorithm (#8663 / #8781).
Thx 👍

**Comment by callapa** [comment]
> Hi @callapa, I link you to this bug, as you wrote the algorithm (#8663 / #8781).
> Thx

Thank you for your report.
Could you give us an example please?

**Comment by UrBnW** [comment]
Thank you for your interest in this @callapa.
Simply create a poller resource, for example `$SNMPOPTIONS$`, with a value containing spaces, for example :
`--authprotocol=SHA --privprotocol=AES --snmp-retries=5 --snmp-timeout=1`
And use this resource in any command you already have.
Password-masking algorithm should fail.
Thank you again 👍

**Comment by UrBnW** [comment]
@callapa, Centreon dev team, whatever is it a poller resource or a macro, if its value contains spaces, then password-masking algorithm fails.
Thx 👍

**Comment by callapa** [comment]
@UrBnW Which version of Centreon?

**Comment by UrBnW** [comment]
Just re-tested with `19.10.18`.

**Comment by UrBnW** [comment]
Just re-tested with `19.10.18` (which uses the same masking algorithm as on never versions).

**Comment by UrBnW** [comment]
Did not manage to reproduce for now with `21.04.4`, will reopen if case triggers again, with the culprit example.
Thank you again !
