### ISSUE TITLE
Re-enable "legacy" monitoring views

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#9174]
Hi,

In Centreon 20.10.0, the following monitoring views are not available anymore :
`Monitoring  >  Status Details  >  Hosts`
`Monitoring  >  Status Details  >  Services`

Centreon 19.10.x :

![image](https://user-images.githubusercontent.com/40244829/97778968-4bb4ce80-1b7b-11eb-99f2-39951fcebb37.png)

Centreon 20.10.0 :

![image](https://user-images.githubusercontent.com/40244829/97778992-730b9b80-1b7b-11eb-90dc-e0b71523ef2e.png)

Could we then think about re-enabling them please ?

Thank you 👍

**Comment by cgagnaire** [comment]
Hi @UrBnW,
Please make sure to don't bypass the issue/feature templates 👍 
You can display them as said in the documentation https://docs.centreon.com/current/en/alerts-notifications/event-console.html

**Comment by UrBnW** [comment]
Hi @cgagnaire,
Many thanks for your response.
I went through the "Resources Status" documentation chapter, but not the "Events consoles" one... My mistake, sorry.
Thank you again 👍

**Comment by cgagnaire** [comment]
We try to make people lost so those pages can be forgotten :)
