### ISSUE TITLE
404 error in Ressource Status page

### ISSUE THREAD

**Issue by julienmathis** [centreon/centreon#9177]
# BUG REPORT INFORMATION

### Prerequisites

Juste setup the last 20.10

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --

[root@central-20 ~]#  rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
centreon-20.10.0-3.el7.centos.noarch
centreon-auto-discovery-server-20.10.1-2.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.0-3.el7.centos.noarch
centreon-broker-20.10.0-7.el7.centos.x86_64
centreon-broker-cbd-20.10.0-7.el7.centos.x86_64
centreon-broker-cbmod-20.10.0-7.el7.centos.x86_64
centreon-broker-core-20.10.0-7.el7.centos.x86_64
centreon-broker-storage-20.10.0-7.el7.centos.x86_64
centreon-clib-20.10.0-2.el7.centos.x86_64
centreon-common-20.10.0-3.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-database-20.10.0-3.el7.centos.noarch
centreon-engine-20.10.0-6.el7.centos.x86_64
centreon-engine-daemon-20.10.0-6.el7.centos.x86_64
centreon-engine-extcommands-20.10.0-6.el7.centos.x86_64
centreon-gorgone-20.10.0-14.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.0-14.el7.centos.noarch
centreon-license-manager-20.10.0-1.el7.centos.noarch
centreon-license-manager-common-20.10.0-1.el7.centos.noarch
centreon-perl-libs-20.10.0-3.el7.centos.noarch
centreon-poller-centreon-engine-20.10.0-3.el7.centos.noarch
centreon-pp-manager-20.10.0-1.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.0-3.el7.centos.noarch
centreon-web-20.10.0-3.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch

***Operating System***

CentOS 7.6

***Browser used***

- [x] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 86.0.4240.111

Server install on DigitalOcean

### Description

-- Describe the encountered issue --

### Steps to Reproduce

1. Go to the page Ressource Status and 
2. Check the  Chrome developper console and you will find the following error : 

Call URL: http://<IP ADDRESS>/centreon/monitoring/resources?filter=%7B%22id%22%3A%22all%22%2C%22name%22%3A%22All%22%2C%22criterias%22%3A%7B%22resourceTypes%22%3A%5B%5D%2C%22states%22%3A%5B%5D%2C%22statuses%22%3A%5B%5D%2C%22hostGroups%22%3A%5B%5D%2C%22serviceGroups%22%3A%5B%5D%7D%7D&details=%7B%22tab%22%3A%22details%22%7D

Status: 404 

### Logs

**PHP error logs**

no PhP log error

**Comment by Phoenixoboros** [comment]
Hello,

I have the same issue:

Chrome 86.0.4240.198 (Build officiel) (64 bits)

CentOS Linux release 7.9.2009 (Core)

```
rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort
centreon-20.10.2-4.el7.centos.noarch
centreon-auto-discovery-server-20.10.2-1.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.2-4.el7.centos.noarch
centreon-broker-20.10.3-2.el7.centos.x86_64
centreon-broker-cbd-20.10.3-2.el7.centos.x86_64
centreon-broker-cbmod-20.10.3-2.el7.centos.x86_64
centreon-broker-core-20.10.3-2.el7.centos.x86_64
centreon-broker-storage-20.10.3-2.el7.centos.x86_64
centreon-clib-20.10.0-2.el7.centos.x86_64
centreon-common-20.10.2-4.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-cwrapper-perl-0.1-1.el7.centos.x86_64
centreon-database-20.10.2-4.el7.centos.noarch
centreon-engine-20.10.2-2.el7.centos.x86_64
centreon-engine-daemon-20.10.2-2.el7.centos.x86_64
centreon-engine-extcommands-20.10.2-2.el7.centos.x86_64
centreon-gorgone-20.10.1-5.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.1-5.el7.centos.noarch
centreon-license-manager-20.10.1-1.el7.centos.noarch
centreon-license-manager-common-20.10.1-1.el7.centos.noarch
centreon-perl-libs-20.10.2-4.el7.centos.noarch
centreon-poller-centreon-engine-20.10.2-4.el7.centos.noarch
centreon-pp-manager-20.10.0-1.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.2-4.el7.centos.noarch
centreon-web-20.10.2-4.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch
```




```
==> /var/log/httpd24/access_log <==
::1 - - [04/Jan/2021:13:49:09 +0100] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.34 (Red Hat) (internal dummy connection)"
myip - - [04/Jan/2021:13:49:26 +0100] "GET /centreon/monitoring/resources HTTP/1.1" 404 818 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
myip - - [04/Jan/2021:13:49:26 +0100] "GET /centreon/static/vendor.e7f5e355.chunk.css HTTP/1.1" 200 84610 "http://centreonip/centreon/monitoring/resources" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
myip - - [04/Jan/2021:13:49:26 +0100] "GET /centreon/static/main.63dc8264.chunk.css HTTP/1.1" 200 16970 "http://centreonip/centreon/monitoring/resources" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
myip - - [04/Jan/2021:13:49:26 +0100] "GET /centreon/static/runtime~main.6503ebbe.js HTTP/1.1" 200 3616 "http://centreonip/centreon/monitoring/resources" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
myip - - [04/Jan/2021:13:49:26 +0100] "GET /centreon/static/main.9c2882c2.chunk.js HTTP/1.1" 200 141462 "http://centreonip/centreon/monitoring/resources" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
myip - - [04/Jan/2021:13:49:26 +0100] "GET /centreon/static/vendor.e7a65e18.js HTTP/1.1" 200 1017159 "http://centreonip/centreon/monitoring/resources" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
```

**Comment by Kevs308** [comment]
Hello,
I had this problem when following links in custom views and logging in when my default page was on "Resources Satuts"
I don't know if it is the same problem, but if it is, try to add that to <Directory "/usr/share/centreon/www">

RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
ErrorDocument 404 /centreon/index.html

Solution found at "https://github.com/centreon/centreon/issues/9268#issuecomment-748929719"
Thank to him :)
