### ISSUE TITLE
Action urls do not work in views

### ISSUE THREAD

**Issue by ArnoMdlt** [centreon/centreon#9197]
Versions :
19.10 and 20.04

Browser used
- [x] Firefox
- [x] Microsoft Edge

Description
I use my action link like these : "protocol://$HOSTADDRESS$" -> example : telnet://$HOSTADDRESS$
It work well from the event view (not the beta, the "classic") in V19.10 or 20.04.

But it does not work from the custom views.

when i clic on it, it goes to an https link -> https://telnet//$HOSTADDRESS$ : 

We have this trouble on Service Monitoring Widget and Host monitoring in v20.04.3

i found an issue close from this but in v 2.8 : https://github.com/centreon/centreon/issues/6041

These still can correct this issue in v20.04 ? 

Thank you !

**Comment by ArnoMdlt** [comment]
hi, Any news ?  Tks

**Comment by lpinsivy** [comment]
Hi, Actions and Notes urls have been fixed in Centreon Web 20.10.6 and 21.04.0

Regards,
