### ISSUE TITLE
Dans le tableau de bord > ServiceGroup, on voit des service dont l'hote est désactivée

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#920]
---

Author Name: **m m** (m m)
Original Redmine Issue: 4864, https://forge.centreon.com/issues/4864
Original Date: 2013-09-02

---

Bonjour,
j'ai remarqué un bug avec ma version de Centreon:
Lorsque je clique sur le tableau de bord, Onglet ServiceGroup,

Je trouve des services dont les hotes sont désactivées, ce qui fausse mes stats.

Il faudrait rajouter un filtre SQL dans le tableau de bord:
"AND host.host_activate <> '0'"

Merci

**Comment by lpinsivy** [comment]
already solved
