### ISSUE TITLE
Add "state" parameter in the OpenId Connect Settings (Required by some providers)

### ISSUE THREAD

**Issue by srinathman** [centreon/centreon#9200]
### Feature explanation

Add "state" parameter in the OpenId Connect Settings as it's required by some providers

### What is the value of the wanted feature ?

Make Okta OpenId Connect work with not workarounds

### Additional information

With no "state" parameter authentication will fail with the following redirection:
`
location: https://<centreon>/centreon/index.php?error=invalid_request&error_description=The+authentication+request+has+an+invalid+%27state%27+parameter.`

More Info: https://developer.okta.com/docs/reference/api/oidc/#authorize

**Comment by lpinsivy** [comment]
Hi @srinathman,

The state parameter should be a random key I suppose, but what about the size of this one? Must this be configurable?

Regards,

**Comment by srinathman** [comment]
I suggest checking the RFC to see how it must be implemented:
https://datatracker.ietf.org/doc/html/rfc6819#section-5.3.5
Okta doc may also help: https://developer.okta.com/docs/reference/api/oidc/#parameter-details

**Comment by srinathman** [comment]
Closing this as the state parameter is now included in the code and confirmed working:

www/class/centreonAuth.SSO.class.php line 125
```
$authUrl .= "&state=" . uniqid();
```
