### ISSUE TITLE
[Feature] Debian packages

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon#9282]
Hi,

https://lists.centos.org/pipermail/centos-announce/2020-December/048208.html
_CentOS Linux 8, as a rebuild of RHEL 8, will end at the end of 2021._
_Meanwhile, we understand many of you are deeply invested in CentOS Linux 7, and we’ll continue to produce that version through the remainder of the RHEL 7 life cycle._

As a result, it's better to stay on CentOS 7, even with Centreon 20.10, rather than migrating to CentOS 8...

Then, what about supporting another system, such as Debian ?
Providing packages for this Linux distribution would be perfect, as it is perfectly server-oriented.

Many thanks 👍

**Comment by hecko** [comment]
Lets see what https://rockylinux.org/ comes up with in the next few weeks.

**Comment by cgagnaire** [comment]
See https://github.com/centreon/centreon/discussions/9317
