### ISSUE TITLE
Filter pollers in Resources Status view

### ISSUE THREAD

**Issue by sylvainrolland** [centreon/centreon#9284]
### Feature explanation

Add a filter to select the poller in the Resources Status view.

### What is the value of the wanted feature ?

Since the Status Details> Hosts and Status Details> Services views are deprecated, we try to use the Resources Status view.
We use a single platform to monitor all our equipments, with different pollers for our production and our other environments. The "Poller" filter was therefore very useful in our search for services and hosts.

**Comment by PhilCANDIDO** [comment]
Hello everybody,

Do you have a date, or release number that will implement this feature?

**Comment by sbrizini** [comment]
Hello Phil,

This has been implemented in the latest version 21.04 already out ! 👍

Cheers,
Sam
