### ISSUE TITLE
CentOS 7, 8 deprication - what next?

### ISSUE THREAD

**Issue by hecko** [centreon/centreon#9289]
So, Im wondering now that CentOS 8 stable releases will be depricated by RedHat / IBM ( https://blog.centos.org/2020/12/future-is-centos-stream/ ) which system will Centreon be suggesting to build the monitoring platform on top of.

Lots of centreon documentation focuses on installation on specific CentOS releases - specifically CentOS 7 and most recently CentOS 8 for centreon 20.10 - where CentOS 8 will not be an option after 2021.

Any discussion took already place regarding this in centreon core team?

**Comment by UrBnW** [comment]
See #9282 ?

**Comment by cgagnaire** [comment]
See https://github.com/centreon/centreon/discussions/9317
