### ISSUE TITLE
fresh 20.10 install from ISO on ESX : "credentials are incorrect"

### ISSUE THREAD

**Issue by innotip-com** [centreon/centreon#9354]
Hi,

I tried again few times and reproduced each time. ESXi 6.5, fresh vm installed with latest ISO downloaded, no error on install.

When I arrive to the first login, I follow the info of the documentation : yum update then reboot then systemctl enable rh-php72-php-fpm httpd24-httpd mariadb centreon cbd centengine gorgoned snmptrapd centreontrapd snmpd

Then I configure on web, nothing special, chose admin password (tried even simple one like centreon) and database password.

Then I try to access web server, impossible to get in. I tried several times, checking database : user is present, etc.

here are revelant logs happening when login fails :

tailf /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log

[03-Jan-2021 15:09:56 Europe/Paris] PHP Notice:  Undefined index: x-centreon-token in /usr/share/centreon/www/lib/HTML/QuickForm/HTML_QuickFormCustom.php on line 119
[03-Jan-2021 15:09:56 Europe/Paris] PHP Warning:  in_array() expects parameter 2 to be array, null given in /usr/share/centreon/www/lib/HTML/QuickForm/HTML_QuickFormCustom.php on line 119
[03-Jan-2021 15:09:56 Europe/Paris] PHP Notice:  Undefined index: x-centreon-token-generated-at in /usr/share/centreon/www/lib/HTML/QuickForm/HTML_QuickFormCustom.php on line 152
[03-Jan-2021 15:09:56 Europe/Paris] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/centreon/www/lib/HTML/QuickForm/HTML_QuickFormCustom.php on line 152

For the RPM based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon | egrep -v "(plugin|pack)" | sort

centreon-20.10.1-9.el7.centos.noarch
centreon-auto-discovery-server-20.10.2-1.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.1-9.el7.centos.noarch
centreon-broker-20.10.2-1.el7.centos.x86_64
centreon-broker-cbd-20.10.2-1.el7.centos.x86_64
centreon-broker-cbmod-20.10.2-1.el7.centos.x86_64
centreon-broker-core-20.10.2-1.el7.centos.x86_64
centreon-broker-storage-20.10.2-1.el7.centos.x86_64
centreon-clib-20.10.0-2.el7.centos.x86_64
centreon-common-20.10.1-9.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-database-20.10.1-9.el7.centos.noarch
centreon-engine-20.10.1-1.el7.centos.x86_64
centreon-engine-daemon-20.10.1-1.el7.centos.x86_64
centreon-engine-extcommands-20.10.1-1.el7.centos.x86_64
centreon-gorgone-20.10.1-5.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.1-5.el7.centos.noarch
centreon-license-manager-20.10.1-1.el7.centos.noarch
centreon-license-manager-common-20.10.1-1.el7.centos.noarch
centreon-perl-libs-20.10.1-9.el7.centos.noarch
centreon-poller-centreon-engine-20.10.1-9.el7.centos.noarch
centreon-pp-manager-20.10.0-1.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.1-9.el7.centos.noarch
centreon-web-20.10.1-9.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch


*CentOS, Debian ...*

Centos (official centreon ISO downloaded today 03/01/2020)

***Browser used***

- [ X] Google Chrome

**Comment by cgagnaire** [comment]
Hi,
Can you check that `/var/opt/rh/rh-php72/lib/php/session` directory is owned by `root:apache` with permissions `770`, and all files in it are `apache:apache` and `600`?

**Comment by edudele** [comment]
Verify, in since 19.10
- [ KO ] Google Chrome
- [ OK ] Mozilla Firefox
- [ OK ] Microsoft Edge

**Comment by lpinsivy** [comment]
Hi @edudele may be it is a Google Chrome cache issue because the ISO has been downloaded several time without issue.
