### ISSUE TITLE
Resource Status: Timeline order wrong

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#9395]
Centreon 20.10.2
OS: CentOS 7.x

There is a issue viewing the timeline on Resource Status page. The events are ordered by date, but this will fail if the year changes:
![image](https://user-images.githubusercontent.com/6400595/104568317-3b77a000-5650-11eb-9a99-d580a90ffef4.png)
![image](https://user-images.githubusercontent.com/6400595/104568353-48948f00-5650-11eb-9863-a075395e3db0.png)

As you can see on the screenshots on the top we can see the last events from year 2020 and at the end of the page the events from 2021.

**Comment by lpinsivy** [comment]
Hi @joschi99,

We fixed this issue. It will be present in a minor release soon.

Internal: MON-6561

**Comment by cgagnaire** [comment]
Fixed by https://github.com/centreon/centreon/pull/9390.
