### ISSUE TITLE
Resource status - display Host "action URL" and "URL" also on related services

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#9397]
It should be nice to display action URL and URL from the host on related services. Since 20.10.2 the URL's are displayed on Host object, but they are not visible on service objects:
![image](https://user-images.githubusercontent.com/6400595/104613814-e788ad80-5687-11eb-8a73-1224e483b119.png)
If you apply some filter and Host is not displayed you don't have the links.

**Comment by lpinsivy** [comment]
Hi,

This should be fixed with Centreon Web 20.10.6 and 21.04.

Regards,
