### ISSUE TITLE
Changing service or host templates does not change the poller's Conf Changed status to Yes

### ISSUE THREAD

**Issue by yanickgirouard** [centreon/centreon#9433]
When you change the settings of a host or service template, such as notification contacts or other notification options, the "Conf Changed" status of the poller (in the Configuration > Pollers > Pollers page) does not change to "Yes" even though a refresh of the configuration must be done in order to apply the changes for all hosts and services that use these templates.

Currently using version **20.10.0** of Centreon with IT Edition license.

**Comment by cgagnaire** [comment]
Hi,
This is totally "normal" and an asterix explains it on the mentionned page:
> * Only services, servicegroups, hosts and hostgroups are taken in account in order to calculate this status. If you modify a template, it won't tell you the configuration had changed.
