### ISSUE TITLE
Ressources status view filter enhancement (share filter)

### ISSUE THREAD

**Issue by afavre-intersed** [centreon/centreon#9449]
### Feature explanation

The resource status view is very interesting. The filtering option is useful. It would be interesting to be able to share filters. 

### What is the value of the wanted feature ?

- Facilitate teamwork
- Facilitate the adoption of this view

### Additional information

This should be based on the same logic as the shared view in the dashboard.

Sharing :
- public (read or read/write)
- user (read or read/write)
- group (read or read/write)

*Little extra: Allow access from the android centreon app to these shared filters.*

Thank you for your work

**Comment by cgagnaire** [comment]
Hi @afavre-intersed,
You can actually copy/paste the URL which will bring all filters with it.
But there might be something around filters sharing in @sbrizini's roadmap.

**Comment by afavre-intersed** [comment]
Hello @cgagnaire ,

Thanks for the tip about URL sharing.

have a good day

**Comment by sbrizini** [comment]
Hi,
I confirm, sharing the URL will now bring all the filters along.
If the "receiving" user wants to save all the filters as a Custom Filter, he can simply save it from his own session.

Sharing in this manner is pretty straight forward and efficient and should make a dedicated "filter sharing manager" (with yet anoter layer of ACLs etc) redundant. 
Ofc we'll be happy to revisit if the community feels different once the feature in hand.

Regards

**Comment by afavre-intersed** [comment]
Hi @sbrizini,

I understand the difficulty of implementing an extra layer of ACL for a low utility.

I will create my own filter glossary that I will share with my collaborators.

Thank you for your answer.
