### ISSUE TITLE
Cancel host downtime via REST API v2 not working

### ISSUE THREAD

**Issue by Iralein** [centreon/centreon#9452]
# BUG REPORT INFORMATION

***Versions***

Centreon Web 20.10.2.-7

### Description

When trying to cancel a host downtime via REST API v2 (URL: xxxx/centreon/api/beta/monitoring/downtimes/IDXXXX) nothing happens. It is working for service downtimes, but not for host downtimes.

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Get a token and your contact.id from the API via calling curl -s -X POST -d '{ "security": { "credentials": { "login": "VALID ACCOUNT", "password": "PASSWORD" } } }' https://xxxxxx/centreon/api/beta/login
2. Choose a host and get his ID.
3. Set host downtime (inclusive all services):  curl -s -X POST -H X-AUTH-TOKEN:TOKEN -d '{ "start_time": "2021-02-05T09:15:22Z", "end_time": "2021-02-06T11:15:22Z", "is_fixed": true, "duration": 3600, "author_id": YOURID, "comment": "Downtime TEST XXXXXX", "with_services": true }' https://xxxxx/centreon/api/beta/monitoring/hosts/HOSTID/downtimes
3. Get all Downtime IDs via curl -s -G -H X-AUTH-TOKEN:TOKEN --data-urlencode 'search={"$and":[{"host.name":"HOSTNAME"},{"contact.id":"XXXX"},{"comment":"Downtime TEST XXXXXX"},{"is_cancelled": false}]}' -d limit=500 https://xxxxxxxx/centreon/api/beta/monitoring/downtimes
4. Iterate over all DowntimesIDs with curl -s -X DELETE -H X-AUTH-TOKEN:TOKEN https://xxxxxx/centreon/api/beta/monitoring/downtimes/DOWNTIMEID

### Describe the received result
You will get a 204 response for all DELETE requests. Service downtimes will be canceled, but the hostdowntime will remain.

### Describe the expected result
As you cancel a downtime with it's ID, it should work. The host downtime should be canceled, too.

### Logs
No entries.

**PHP error logs**
no entries

**centreon gorgone logs for Centreon >= 20.4  (*if needed*)**
There are only  entries for  DEL_SVC_DOWNTIME but no entries for DEL_HOST_DOWNTIME.

**Comment by sanste78** [comment]
Hi,

I have the same bug, do you have a solution ?

Thank

**Comment by lpinsivy** [comment]
Hi,

Fixed with Centreon 21.10.8 => https://docs.centreon.com/20.10/en/releases/centreon-core.html#20108
