### ISSUE TITLE
Plattform Status -> Engine Statistics: The results could not be loaded

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#9467]
Centreon 20.04.9
Centreon 20.10.3

After last update on 20.04.x and 20.10.x it is not more possible to select a Poller from Poller list under  Plattform Status -> Engine Statistics. If you click on the List box no results are shown.

**Comment by cgagnaire** [comment]
Hi @joschi99,
Can you add a space after "name" and before the quote on this line https://github.com/centreon/centreon/blob/c942bfef59dbd2c75e1a2acb8fc260a0406bdde7/www/api/class/centreon_monitoring_poller.class.php#L82.
I'll open an internal ticket to fix that.

**Comment by joschi99** [comment]
I can confirm that with the additional space works

**Comment by cgagnaire** [comment]
Thanks for the feedback.

Refs: MON-6759

**Comment by gagzou** [comment]
Same issue with Centreon 19.10.20.
It's ok with space after "name" and before the quote.
