### ISSUE TITLE
Centreon 20.10.3 - unable to add host - You are not allowed to access this host

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#9477]
On Centreon 20.10.3 a user with ACL configured is not more able to add a new Host and would get the message "You are not allowed to access this host"
![image](https://user-images.githubusercontent.com/6400595/107637847-0b331980-6c6f-11eb-9a8a-f14c24c50bec.png)

Same on "massive change". But user can duplicate a host and edit an existing host

**Comment by gagzou** [comment]
Same issue with Centreon 19.10.19

**Comment by cgagnaire** [comment]
Hi,
It is fixed by https://github.com/centreon/centreon/commit/5996f1f7d8476b22152661f7ed2d8b82eaa478e7 for 20.10 and https://github.com/centreon/centreon/commit/a8ab1cf1d39c55f89784f3fe5e8dd3b7a2980b48 for 19.10.
It will be available in the next versions to come.
