### ISSUE TITLE
[Resources Status] - executed command is shown even ACL has the option disabled

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#9478]
Centreon 20.10.x
If you have a user where Action access "Display executed command by monitoring engine" is disabled on Resources Status the command is visible

**Comment by sbrizini** [comment]
Hi,
We're correcting this (API wise as well as visually by graying out the command icons): MON-6648
Regards

**Comment by lgigil** [comment]
Hello, I updated to Centreon 22.04.0 and this bug is still present. Do you have any news about?

**Comment by ponchoh** [comment]
@lgigil please note 
https://github.com/centreon/centreon/pull/9803 
and remember that admin has different rights
