### ISSUE TITLE
After update to Centreon Web 20.04.9 APPLYCFG and CFGMOVE doesn't work anyore

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#9501]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

Centreon web 20.04.9

***Operating System***

CentOS 7

***Browser used***

CLI

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Use CLI to do a CFGMOVE or APPLYCFG

### Describe the received result

/usr/share/centreon/bin/centreon -u admin -p 'XXXXXXX' -a CFGMOVE -v "XXXX"
Please check that your parameters are valid

### Describe the expected result

Using debug I 've found the error : 

/usr/share/centreon/bin/centreon -u admin -p 'XXXXXX' -a CFGMOVE -v "XXXX" -d
Array
(
    [u] => admin
    [p] => XXXXXX
    [a] => CFGMOVE
    [v] => 30
    [d] =>
)
**SQLSTATE[42S02]: Base table or view not found: 1146 Table 'centreon.platform_topology' doesn't exist**
Please check that your parameters are valid

**Comment by cgagnaire** [comment]
Hi,
It has been fixed by https://github.com/centreon/centreon/commit/fbe2f11e02c76556e6f2605be61daffc566d5220.
It will soon be available in next 20.04.10 version.
