### ISSUE TITLE
Page Config > Services > Services by Host group is broken

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon#9524]
# BUG REPORT INFORMATION

***Versions***
20.10.3

***Operating System***
CentOs

***Browser used***

- [x] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

### Description
When going to page "Config > Services > Services by Host group" there is never any result.
![image](https://user-images.githubusercontent.com/664748/109202374-32c3cf00-77a3-11eb-94f5-22630a067cc8.png)

### Steps to Reproduce
1. I logged in Centreon
2. I reached the Page Config > Services > Services by Host group is broken
3. I try to enter exactly an Host Group
4. I click on "Search" button

### Describe the received result
All services related to this host group must appear

### Logs
**PHP error logs**
=> Nothing on the Php errorlog

### Additional relevant information (e.g. frequency, ...)
I repeated the result on another instance of Centreon

**Comment by TheCriSys** [comment]
Hi,

There is the same issue in other browsers.
No error shown in the browser's console log.

**Comment by Odka33** [comment]
Is broken on 20.10 too.
Issue where only one host of the group is printed in the web ui.

**Comment by lpinsivy** [comment]
HI, can you check in /var/log/centreon/sql-errors.log?

Regards,

**Comment by fixlair** [comment]
Hello ! 
I do not see any new logs in /var/log/centreon/sql-errors.log when browsing this "service by host group" page on the same time.

The problem seems also be present on https://demo.centreon.com (updated in last 21.04 version).

Regards,

**Comment by lpinsivy** [comment]
I made a test on a Centreon 21.04 version and everything works perfectly.

Do you create a Services by host group using the "Add" button?

**Comment by TheCriSys** [comment]
Hi,

I can confirm too that it's not working for me neither on the demo with Chrome and the new Edge.
However, i've tried to use the default available hostgroups like 'Domain-Controllers' or ''.

I've no error in my log.

![screenshot 405](https://user-images.githubusercontent.com/15217120/116093332-dc8de200-a6a6-11eb-8bad-251ffc412d51.jpg)

**Comment by lpinsivy** [comment]
Hi, on the demo.centreon.com there is no services by hostgroups configured.

Moreover, on the demo, it is impossible to configure objects. All actions are blocked.

**Comment by fixlair** [comment]
Ok ! clear !
I just get your point. 
I thought it was a way to see all service (associated to host) filtering host by host group.
But in fact its a way to set a new king of service associated to host group directly

I closed the ticket
