### ISSUE TITLE
[GRAPH] Enhancement of the zoom feature

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#953]
---

Author Name: **sebastien maury** (sebastien maury)
Original Redmine Issue: 5052, https://forge.centreon.com/issues/5052
Original Date: 2013-12-13
Original Assignee: Maximilien Bersoult

---

So far, to be able to zoom on a graph, we have to :
1/ Click on the magnifier
2/ Make a selection on the graph
3/ Click again on the magnifier

So far, none knew that we had to do the 3rd step.
So everyone stopped at step 2 and we all thought that the feature wasn't usable ... And none were using it.

I think the 3rd step is pointless and make the feature not very user friendly (even more for someone used to Cacti for example).

Is it possible to make it so that the selection we made on the graph is displayed as soon as we've done our selection ?

Thanks in advance.
Regards,
Sébastien

**Comment by lpinsivy** [comment]
solved with new chart display
