### ISSUE TITLE
[20.10.04] API V2; security concern, users get more rights than allowed.

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#9597]
# BUG REPORT INFORMATION

### Prerequisites
***Versions***

centreon-20.10.4-6.el7.centos.noarch
centreon-auto-discovery-server-20.10.2-1.el7.centos.noarch
centreon-awie-20.10.0-1.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.4-6.el7.centos.noarch
centreon-bi-server-20.10.0-2.el7.centos.noarch
centreon-broker-20.10.3-5.el7.centos.x86_64
centreon-broker-cbd-20.10.3-5.el7.centos.x86_64
centreon-broker-cbmod-20.10.3-5.el7.centos.x86_64
centreon-broker-core-20.10.3-5.el7.centos.x86_64
centreon-broker-storage-20.10.3-5.el7.centos.x86_64
centreon-clib-20.10.0-2.el7.centos.x86_64
centreon-common-20.10.4-6.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-database-20.10.4-6.el7.centos.noarch
centreon-engine-20.10.2-2.el7.centos.x86_64
centreon-engine-daemon-20.10.2-2.el7.centos.x86_64
centreon-engine-extcommands-20.10.2-2.el7.centos.x86_64
centreon-fingerprint-19.04.0-1.el7.centos.x86_64
centreon-gorgone-20.10.3-1.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.3-1.el7.centos.noarch
centreon-license-manager-20.10.1-1.el7.centos.noarch
centreon-license-manager-common-20.10.1-1.el7.centos.noarch
centreon-mbi-release-20.10-2.el7.centos.noarch
centreon-perl-libs-20.10.4-6.el7.centos.noarch
centreon-poller-centreon-engine-20.10.4-6.el7.centos.noarch
centreon-pp-manager-20.10.1-3.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.4-6.el7.centos.noarch
centreon-web-20.10.4-6.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch

***Browser used***

- [ ] Google Chrome
- [x ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 87

### Description
A simple user can :
  - Get the list of all the pollers with the full configuration (name, ip, file path, etc...)
  - Modify the topology

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Add a user will no administrative or configuration right,
2. Get the full list of poller with this method : https://docs.centreon.com/api/centreon-web/#tag/Monitoring-Server
3. Modify the topology with this method : https://docs.centreon.com/api/centreon-web/#tag/Topology

### Describe the received result
I get the full poller list and i can modify the topology

### Describe the expected result
all theses actions must be denied as a regular user with not right on theses objects

**Comment by sc979** [comment]
Dear @BenoitPoulet ,
I have created an internal ticket to investigate on it.
Indeed, an “500 : Access denied” message should have been returned by the API

If you want to give us more details, kindly send us an email at :  security@centreon.com.
The PGP key is provided here : 
https://github.com/centreon/centreon/security/policy#reporting-a-vulnerability

Best Regards,
sc979

**Comment by sc979** [comment]
Dear @BenoitPoulet ,

The pull request referenced above has been merged and will be released in next minors.
You can already apply the correction by, changing the line 414 : https://github.com/centreon/centreon/pull/9614/files#diff-e983493eb049539270d4228fbf3fb854a1e0abe1e366692885d809ac7630f5f4R415
or downloading the RAW file : https://raw.githubusercontent.com/centreon/centreon/c36a16d778e3fc3aeef58ad94c317fe3ef71d9b4/src/Centreon/Domain/Contact/Contact.php

Best regards,

sc979

**Comment by BenoitPoulet** [comment]
Hello,

Thanks for the fixes. Now the request on theses 2 endpoint by a user is denied, perfect.

But the error message seems to be not right :
Response : 500 Internal Server Error

And in the body :

```
{
    "code": 500,
    "message": "Access Denied."
}
```
Regards.

**Comment by BenoitPoulet** [comment]
One more thing; at least the following endpoint where working before the patch :

{protocol}://{server}:{port}/centreon/api/{version}/users/acl/actions
{protocol}://{server}:{port}/centreon/api/{version}/configuration/users/current/parameters

They now send a Access Denied (code 500) as a regular user, i think it's a side effect.

**Comment by sc979** [comment]
Dear @BenoitPoulet ,

About the returned code, the symfony kernel returns currently a 500 instead of the 401, when the error is not "managed" in a non maintainable way for us. We are investigating a way to implement a more friendly and global way to return the code we need.

About the API rights.
The side effect, was that the user was able to access these endpoints.
The two endpoints you try to access require the API_configuration rights and not the API_realtime one.

We are currently working on a way to improve the API v2 rights granularity, and to apply the chosen ACL in the IHM to the API v2.
But we need some time, as the 21.04.0 release is coming

Best regards,

sc979

**Comment by sc979** [comment]
Dear @BenoitPoulet,

Could you contact me by mail : schapron@centreon.com

Regards,

sc979
