### ISSUE TITLE
La génération de la configuration ne fonctionne pas.

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#96]
---

Author Name: **Sébastien Boulianne** (Sébastien Boulianne)
Original Redmine Issue: 6230, https://forge.centreon.com/issues/6230
Original Date: 2015-03-27
Original Assignee: Julien Mathis

---

Bonjour,

Je ne suis plus en mesure de générer la configuration pour "All Pollers".

Pour reproduire mon BUG.
Je vais dans Configuration > Monitoring Engines et je coche toutes les cases tel qu'indiqué et fait export.
http://imgur.com/6WQVJX0,EYezRfw,oRV2Ce6

Ca fonctionne très bien pour TOUS les pollers.
http://imgur.com/6WQVJX0,EYezRfw,oRV2Ce6#2

MAIS

Si j'ajoute ces services templates en utilisant CLAPI à l'aide de ces commandes:
http://pastebin.com/95ZGLJwL

Ensuite, je vais dans Configuration > Monitoring Engines et je coche toutes les cases tel qu'indiqué et fait export.
La génération de la configuration semble ne pas se faire et ce, même si j'attends plus de 20 minutes.
http://imgur.com/6WQVJX0,EYezRfw,oRV2Ce6#1

M A I S

Si je sélectionne chaque poller INDIVIDUELLEMENT:
http://imgur.com/buQElBq,SZpMTNz
http://imgur.com/buQElBq,SZpMTNz#1
CA FONCTIONNE!

+*Conclusion*+: Selon mon analyse, le problème se produit seulement lorsque j'essaie de générer la configuration pour tous les pollers en même temps...
Si je sélectionne chaque poller individuellement, ca fonctionne parfaitement!
POURQUOI ?

Le statut de mes services sont tous RUNNING.
> [root@centreon_central ~]# /etc/init.d/centengine status
> centengine status: running [ OK ]
> [root@centreon_central ~]# /etc/init.d/centcore status
> centcore (pid 1733) is running...
> [root@centreon_central ~]# /etc/init.d/centstorage status
> centstorage is stopped
J'ai 13 pollers et ils sont tous en RUNNING.

J'utilise CES 3.1 avec toutes les dernières mises à jour.
> rpm -qa | grep centreon
> centreon-connector-1.1.1-2.el6.x86_64
> centreon-widget-host-monitoring-1.3.2-1.el6.noarch
> centreon-common-2.5.4-2.el6.noarch
> centreon-broker-2.8.1-5.el6.x86_64
> centreon-base-config-centreon-engine-2.5.4-2.el6.noarch
> centreon-perl-libs-2.5.4-2.el6.noarch
> centreon-engine-extcommands-1.4.11-4.el6.x86_64
> centreon-clib-1.4.2-1.el6.x86_64
> centreon-broker-core-2.8.1-5.el6.x86_64
> centreon-broker-cbmod-2.8.1-5.el6.x86_64
> centreon-widget-service-monitoring-1.3.2-1.el6.noarch
> centreon-2.5.4-2.el6.noarch
> centreon-widget-graph-monitoring-1.1.0-2.el6.noarch
> centreon-widget-servicegroup-monitoring-1.1.0-1.el6.noarch
> centreon-engine-daemon-1.4.11-4.el6.x86_64
> centreon-connector-ssh-1.1.1-2.el6.x86_64
> centreon-broker-cbd-2.8.1-5.el6.x86_64
> centreon-engine-1.4.11-4.el6.x86_64
> centreon-connector-perl-1.1.1-2.el6.x86_64
> centreon-trap-2.5.4-2.el6.noarch
> centreon-plugin-meta-2.5.4-2.el6.noarch
> centreon-widget-hostgroup-monitoring-1.1.1-2.el6.noarch
> centreon-plugins-2.5.4-2.el6.noarch
> centreon-web-2.5.4-2.el6.noarch
> centreon-broker-storage-2.8.1-5.el6.x86_64
> centreon-clapi-1.7.1-2.el6.noarch
> 
Est-ce que quelqu'un aurait une petite idée ou le problème se situerait ?

Merci et au plaisir.

Sébastien B.

**Comment by julienmathis** [comment]
Can access to exemple... Sorry
