### ISSUE TITLE
OpenId Connect - Ability to choose the response variable (only preferred_username today)

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon#9611]
### Feature explanation
It would be great to be able to select on Centreon Side the ability to enter which variable we select from the IDP answer during the login process.

### What is the value of the wanted feature ?
Today "preferred_username" is hardcoded and the only choice. But some IDP are not able to provide this information in standard OpenID Scope (like profile).
It would be great to add the possibility to select the right attribute like nickname, email, ... during the configuration process

### Additional information
It could consist : 
* Add the option to specify the wanted attribute on Config Page (by default "preferred_username" for retro-compatibility)
* Implement it in centreonAuth.SSO.class.php
* Update the documentation

Thanks for your feadback !

**Comment by mayrstefan** [comment]
Looks like this will be addressed by pull request #9846 in commit db4c91373e3d46be610448180405c801c7815925

**Comment by fixlair** [comment]
Hello !
I confirm you may close this issue as it's implemented !
Regards !
