### ISSUE TITLE
Link URL, URL notes, Actions URL bug in 20.10.05

### ISSUE THREAD

**Issue by ArnoMdlt** [centreon/centreon#9675]
# BUG REPORT INFORMATION
V20.10.05

$ rpm -qa | grep centreon-broker 
centreon-broker-core-20.10.3-5.el7.centos.x86_64
centreon-broker-storage-20.10.3-5.el7.centos.x86_64
centreon-broker-cbmod-20.10.3-5.el7.centos.x86_64
centreon-broker-cbd-20.10.3-5.el7.centos.x86_64
centreon-broker-20.10.3-5.el7.centos.x86_64
 rpm -qa | grep centreon-engine 
centreon-base-config-centreon-engine-20.10.5-20.el7.centos.noarch
centreon-poller-centreon-engine-20.10.5-20.el7.centos.noarch
centreon-engine-extcommands-20.10.2-2.el7.centos.x86_64
centreon-engine-daemon-20.10.2-2.el7.centos.x86_64
 rpm -qa | grep centreon-web
centreon-web-20.10.5-20.el7.centos.noarch

***Operating System***
CentOS

### Description

Hello, the functionality of "URL", "URL note" and "Action URL" does not work correctly in the event view: 

Host : 
Configuration : 

![image](https://user-images.githubusercontent.com/73098333/114075199-93b3ec00-98a5-11eb-82a2-cc410bcf1b92.png)

Events view : 

![image](https://user-images.githubusercontent.com/73098333/114075565-f4dbbf80-98a5-11eb-84bf-19e5889ad914.png)

"URL" : 
It works but instead of opening a new tab we leave the current page ... ->  https://github.com/centreon/centreon/issues/9497
Also : Bug -> when we use macro "$hostaddress$" it does not work : 
![image](https://user-images.githubusercontent.com/73098333/114076162-a4189680-98a6-11eb-83e4-a012b477ca9a.png)

"URL note" : 
Bug : It does not indicate what is specified in the host configuration: 
![image](https://user-images.githubusercontent.com/73098333/114076319-d1654480-98a6-11eb-8621-57485be697ba.png)

"Action URL"  
Bug : Not present in the events view..

All the same for "service configuration".

Thanks.

**Comment by lpinsivy** [comment]
Dear,

This issue have been fixed in Centreon Web 20.10.6 : https://docs.centreon.com/20.10/en/releases/centreon-core.html#bugfixes

Regards
