### ISSUE TITLE
Upgrade 20.10.6 to 21.04 blocked application cache generation

### ISSUE THREAD

**Issue by prohand** [centreon/centreon#9757]
Hello,

I tried an update from 20.10.6 to 21.04.0 and during the step of the update process via the web interface, I found myself stuck on the following page:

![image](https://user-images.githubusercontent.com/20227162/116525648-0595b900-a8d9-11eb-91ce-54f0563ebb32.png)

I am under redhat 8.

Can you help me ?

Thank you

**Comment by prohand** [comment]
I have found the error : 

```
[root@s-centreon-central step_upgrade]# php /usr/share/centreon/www/install/steps/process/generationCache.php
PHP Warning:  Failed loading Zend extension 'ioncube_loader_lin_7.2.so' (tried: /usr/lib64/php/modules/ioncube_loader_lin_7.2.so (/usr/lib64/php/modules/ioncube_loader_lin_7.2.so: undefined symbol: _zval_ptr_dtor), /usr/lib64/php/modules/ioncube_loader_lin_7.2.so.so (/usr/lib64/php/modules/ioncube_loader_lin_7.2.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'gnupg.so' (tried: /usr/lib64/php/modules/gnupg.so (/usr/lib64/php/modules/gnupg.so: undefined symbol: _zend_hash_str_add), /usr/lib64/php/modules/gnupg.so.so (/usr/lib64/php/modules/gnupg.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.

Please visit get-loader.ioncube.com for install assistance.
```

**Comment by prohand** [comment]
The following command resolved the problem : 

```
wget http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
tar xzf ioncube_loaders_lin_x86-64.tar.gz
cp ioncube/ioncube_loader_lin_7.3.so /usr/lib64/php/modules/
rm /usr/lib64/php/modules/ioncube_loader_lin_7.2.so
```

modify in /etc/php.d/10-ioncube_loader.ini the version 7.2 to 7.3.

systemctl restart php-fpm

The cached reload successfuly but the new warning : 

`PHP Warning:  PHP Startup: Unable to load dynamic library 'gnupg.so' (tried: /usr/lib64/php/modules/gnupg.so (/usr/lib64/php/modules/gnupg.so: undefined symbol: _zend_hash_str_add), /usr/lib64/php/modules/gnupg.so.so (/usr/lib64/php/modules/gnupg.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by adr-mo** [comment]
I @prohand,

This is due to a packaging issue. Version packaged for ioncube-loader and php-pecl-gnupg on 21.04.0 are different from the ones packaged for 20.10 BUT it seems that name & version are the same between the 2 major versions so that yum does not upgrade the packages.

This needs a new version of those packages on 21.04.0 (increase of the release number) so that when migrating from 20.10 the packages are correctly upgraded.

**Workaround** 

```
rpm -Uvh --force http://yum-1.centreon.com/standard/21.04/el8/stable/x86_64/RPMS/ioncube-loader-10.4.5-2.el8.x86_64.rpm http://yum-1.centreon.com/standard/21.04/el8/stable/x86_64/RPMS/php-pecl-gnupg-1.4.0-4.el8.x86_64.rpm
```

Regards,

**Comment by prohand** [comment]
Hello, 
it's OK.
Thank you
