### ISSUE TITLE
Server internal Error API Rest

### ISSUE THREAD

**Issue by johnnync13** [centreon/centreon#9860]
# BUG REPORT INFORMATION

Instalattion with:
`curl -L -s https://raw.githubusercontent.com/centreon/centreon/21.04.x/unattended.sh | sh`

Packages:

```
centreon-21.04.1-14.el8.noarch
centreon-auto-discovery-server-21.04.0-1.el8.noarch
centreon-base-config-centreon-engine-21.04.1-14.el8.noarch
centreon-broker-21.04.0-7.el8.x86_64
centreon-broker-cbd-21.04.0-7.el8.x86_64
centreon-broker-cbmod-21.04.0-7.el8.x86_64
centreon-broker-core-21.04.0-7.el8.x86_64
centreon-broker-selinux-0.0.5-1.x86_64
centreon-broker-storage-21.04.0-7.el8.x86_64
centreon-clib-21.04.0-1.el8.x86_64
centreon-common-21.04.1-14.el8.noarch
centreon-common-selinux-0.0.10-1.x86_64
centreon-connector-21.04.0-1.el8.x86_64
centreon-connector-perl-21.04.0-1.el8.x86_64
centreon-connector-ssh-21.04.0-1.el8.x86_64
centreon-database-21.04.1-14.el8.noarch
centreon-engine-21.04.1-1.el8.x86_64
centreon-engine-daemon-21.04.1-1.el8.x86_64
centreon-engine-extcommands-21.04.1-1.el8.x86_64
centreon-engine-selinux-0.0.8-1.x86_64
centreon-gorgone-21.04.0-4.el8.noarch
centreon-gorgone-centreon-config-21.04.0-4.el8.noarch
centreon-gorgoned-selinux-0.0.3-1.x86_64
centreon-license-manager-21.04.0-1.el8.noarch
centreon-license-manager-common-21.04.0-1.el8.noarch
centreon-perl-libs-21.04.1-14.el8.noarch
centreon-poller-centreon-engine-21.04.1-14.el8.noarch
centreon-pp-manager-21.04.0-1.el8.noarch
centreon-release-21.04-4.el8.noarch
centreon-trap-21.04.1-14.el8.noarch
centreon-web-21.04.1-14.el8.noarch
centreon-web-selinux-0.0.6-1.x86_64
centreon-widget-engine-status-21.04.0-1.el8.noarch
centreon-widget-global-health-21.04.0-1.el8.noarch
centreon-widget-graph-monitoring-21.04.0-1.el8.noarch
centreon-widget-grid-map-21.04.0-1.el8.noarch
centreon-widget-hostgroup-monitoring-21.04.0-1.el8.noarch
centreon-widget-host-monitoring-21.04.0-2.el8.noarch
centreon-widget-httploader-21.04.0-3.el8.noarch
centreon-widget-live-top10-cpu-usage-21.04.0-1.el8.noarch
centreon-widget-live-top10-memory-usage-21.04.0-1.el8.noarch
centreon-widget-servicegroup-monitoring-21.04.0-1.el8.noarch
centreon-widget-service-monitoring-21.04.0-1.el8.noarch
centreon-widget-tactical-overview-21.04.0-1.el8.noarch
```
***Operating System***

*CentOS 8.3*

***Browser used***

- [x] Google Chrome

Version: Centreon 21.04

### Description

When I try to access via API to my URL I have this message:
`curl -s -d '{"security": {"credentials": {"login": "admin","password": "password"}}}' -H "Content-Type: application/json" -X POST http://127.0.0.1/centreon/api/beta/login`

Error:
{"code":500,"message":"Internal error"}

If I use:
`curl -s -d "username=admin&password=password" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://127.0.0.1/centreon/api/index.php?action=authenticate`

works perfectly

### Logs

**PHP error logs**

No such file or directory" at /usr/share/centreon/www/class/centreonDB.class.php line 165

[24-May-2021 19:22:19 UTC] [critical] Uncaught PHP Exception Exception: "SQLSTATE[HY000] [2002] No such file or directory" at /usr/share/centreon/www/class/centreonDB.class.php line 165

[24-May-2021 19:23:18 UTC] [critical] Uncaught PHP Exception Exception: "SQLSTATE[HY000] [2002] No such file or directory" at /usr/share/centreon/www/class/centreonDB.class.php line 165

[24-May-2021 19:23:19 UTC] [critical] Uncaught PHP Exception Exception: "SQLSTATE[HY000] [2002] No such file or directory" at /usr/share/centreon/www/class/centreonDB.class.php line 165

[24-May-2021 19:24:19 UTC] [critical] Uncaught PHP Exception Exception: "SQLSTATE[HY000] [2002] No such file or directory" at /usr/share/centreon/www/class/centreonDB.class.php line 165

**Comment by lpinsivy** [comment]
Can you check logs in /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log or /var/opt/rh/rh-php73/log/php-fpm/centreon-error.log regaarding your PHP version.

**Comment by johnnync13** [comment]
with your script curl -L -s https://raw.githubusercontent.com/centreon/centreon/21.04.x/unattended.sh | sh my /var/opt/ is empty @lpinsivy

**Comment by johnnync13** [comment]
in /var/log/httpd
`[Thu May 27 10:40:40.602295 2021] [suexec:notice] [pid 18727:tid 140201353345344] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::45f:76ff:fe50:fd74. Set the 'ServerName' directive globally to suppress this message
[Thu May 27 10:40:40.616727 2021] [lbmethod_heartbeat:notice] [pid 18727:tid 140201353345344] AH02282: No slotmem from mod_heartmonitor
[Thu May 27 10:40:40.617389 2021] [http2:warn] [pid 18727:tid 140201353345344] AH02951: mod_ssl does not seem to be enabled
[Thu May 27 10:40:40.619678 2021] [mpm_event:notice] [pid 18727:tid 140201353345344] AH00489: Apache/2.4.37 (centos) configured -- resuming normal operations
[Thu May 27 10:40:40.619696 2021] [core:notice] [pid 18727:tid 140201353345344] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 27 10:40:47.984788 2021] [authz_core:error] [pid 18731:tid 140200722065152] [client 85.50.102.32:55177] AH01630: client denied by server configuration: /usr/share/centreon/`

**Comment by jeremyjaouen** [comment]
Hello, 

We have investigated on this issue and open a PR this morning : https://github.com/centreon/centreon/pull/9880

Thank you for your feedbacks.

Kindly.

**Comment by johnnync13** [comment]
@jeremyjaouen 
is it possible search host by name in api?
http://XXXX/centreon/api/v2.1/monitoring/hosts?name=central or 
req = requests.get('http://XXXXXXX/centreon/api/v2.1/monitoring/hosts/Central', headers=headers)
