### ISSUE TITLE
Improved exporting for Pollers

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#987]
---

Author Name: **Thomas - aka Jogarem -** (Thomas - aka Jogarem -)
Original Redmine Issue: 428, https://forge.centreon.com/issues/428

---

When exporting configuration then you have to choose the
pollers from a drop down list. When you have more than 5 Pollers
and want to change settings only on 3 or 2 of them it becomes
inconvenient.

It would be a nice improvement when you could change from
drop down to a list of clickable pollers..
Then it is possible to export config/commands etc to Poller A,D,F,K
with only one click ;-)

The possibility to export to ALL should stay of course too..

Regards
Thomas

**Comment by julienmathis** [comment]
ok implemented
