### ISSUE TITLE
[20.10]] [RESSOURCE VIEW] - Lost of visibility of notification activated or not for services

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#9900]
### Feature explanation

On detailled status, we can see if notification is enabled or not beside of service name like KB link's, etc...
![image](https://user-images.githubusercontent.com/8720203/120632880-c0315200-c469-11eb-8b6b-295fee3a1e98.png)

This information isn't displayed on the new ressource view, directly on listing or in detailled box on the right.
![image](https://user-images.githubusercontent.com/8720203/120632719-8bbd9600-c469-11eb-872c-2138d82947ee.png)

### What is the value of the wanted feature ?

Display this information beside of KB link's for example or in detail Box

### Additional information
I know some features are added in 21.04 with selection of column for example .
So, if it's already added on 21.04 or in update in 20.10, you can close this request.

King Regards

**Comment by lpinsivy** [comment]
will be available with 21.10
