### ISSUE TITLE
Rest API(v1) -> Submit results - hide hosts and services

### ISSUE THREAD

**Issue by tsusa-p** [centreon/centreon#9908]
### Feature explanation

We are using Rest API(v1)-Submit results in a way that different customers submit status of services into one Centreon. Their servers are onPrem and they just send the status to Centreon and then a team can react based on different warnings. 

Currently all customers can "see" all hosts & services regardless the user they use for sending the status.  We would like to have a possibility to limit certain user to certain hosts. Without this any user can Submit status for any service and host. Using action "show" and object "host"/"service" it is possible to get all the information needed to submit false data into Centreon. 

### What is the value of the wanted feature ?

We could limit users to have access only to their host/service reducing the possibility to set false data.

**Comment by tsusa-p** [comment]
I forgot to mention that we did set up the ACL --> Resources access and it is working as it should in front end. 
But if I use below command (for the user that has limited resources access in app) I can still list out ALL hosts and services.

curl -k --location --request POST 'https://********/centreon/api/index.php?action=action&object=centreon_clapi' \
--header 'Content-Type: application/json' \
--header 'centreon-auth-token: '***********************************************************'' \
--data '{
    "action": "show",
    "object": "HOST"
}
'

**Comment by lpinsivy** [comment]
HI,

We know that with API v1 for configuration, there is no ACL applied.
With v2, full ACL definitions are applied.
