### ISSUE TITLE
centreonPurgeEngine.class.php do not works with MariaDB 10.3 if you have more than one partition to delete

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#9911]
# BUG REPORT INFORMATION

### Prerequisites

Centreon 20.10.5

***Versions***

MariaDB 10.3

***Operating System***
CentOS

***Browser used***

- [ ] Google Chrome
- [ ] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: --

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. Configure retention in order to delete 2 partitions on the next purge
2. Execute  /opt/rh/rh-php72/root/usr/bin/php /usr/share/centreon/cron/centstorage_purge.php

### Describe the received result

You will have this error :

Error : Cannot drop partitions of table data_bin, SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DROP PARTITION `p20190909`, DROP PARTITION `p20190910`, DROP PARTITION `p2019...' at line 1

### Describe the expected result

Delete more than one partition should work

**Comment by lolokai** [comment]
UP ?

**Comment by lpinsivy** [comment]
Fixed with 21.04.2 / 20.10.8
