### ISSUE TITLE
Some changes on configuration not displayed in poller listing

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#9913]
# BUG REPORT INFORMATION

### Prerequisites

***Versions***

centreon-20.10.7-1.el7.centos.noarch
centreon-auto-discovery-server-20.10.3-2.el7.centos.noarch
centreon-awie-20.10.0-1.el7.centos.noarch
centreon-bam-release-20.10-2.el7.centos.noarch
centreon-bam-server-20.10.4-1.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.7-1.el7.centos.noarch
centreon-bi-server-20.10.2-4.el7.centos.noarch
centreon-broker-20.10.4-5.el7.centos.x86_64
centreon-broker-cbd-20.10.4-5.el7.centos.x86_64
centreon-broker-cbmod-20.10.4-5.el7.centos.x86_64
centreon-broker-core-20.10.4-5.el7.centos.x86_64
centreon-broker-storage-20.10.4-5.el7.centos.x86_64
centreon-clib-20.10.1-2.el7.centos.x86_64
centreon-common-20.10.7-1.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-database-20.10.7-1.el7.centos.noarch
centreon-engine-20.10.4-1.el7.centos.x86_64
centreon-engine-daemon-20.10.4-1.el7.centos.x86_64
centreon-engine-extcommands-20.10.4-1.el7.centos.x86_64
centreon-gorgone-20.10.3-1.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.3-1.el7.centos.noarch
centreon-license-manager-20.10.3-3.el7.centos.noarch
centreon-license-manager-common-20.10.3-3.el7.centos.noarch
centreon-mbi-release-20.10-2.el7.centos.noarch
centreon-nrpe3-daemon-3.2.1-9.el7.centos.x86_64
centreon-open-tickets-20.10.2-1.el7.centos.noarch
centreon-perl-libs-20.10.7-1.el7.centos.noarch
centreon-poller-centreon-engine-20.10.7-1.el7.centos.noarch
centreon-pp-manager-20.10.1-3.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.7-1.el7.centos.noarch
centreon-web-20.10.7-1.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch

***Operating System***

*CentOS 7

***Browser used***

- [X] Google Chrome
- [X] Firefox
- [?] Internet Explorer IE11 => not tested
- [?] Safari => not tested

Version: latest

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

I don't know if it's a bug or feature.

When we move a host on another poller, the configuration changed is only displayed on poller receive host but not on poller lost the host.
If we make some changes in same time, we can't see exhaustively which poller need recharge configuration

### Steps to Reproduce

1. I logged in Centreon
2. In host configuration change monitoring poller to another one and save

### Describe the received result

On poller view, only destination poller is marked changed. The source poller isn't marked change.
see below
![poller_view](https://user-images.githubusercontent.com/8720203/121155525-2a6e3c00-c848-11eb-9b8b-fc4ffd5b82a0.png)

sql request for changes
![sql_request_poller_change](https://user-images.githubusercontent.com/8720203/121155755-630e1580-c848-11eb-95f0-d8439237c55f.png)

### Describe the expected result

See all poller have been changed marked changed

### Additional relevant information (e.g. frequency, ...)
Here is the bash script I made for that; but in some case, maked changes are not displayed, I've not yet find the reason
it's surely optimizable:

```
#!/bin/bash

pollers=$1
user_db="centreon_dbuser"
password_db="centreon_dbpwd"

if [ "$pollers" == "" ];then
        pollers=$(mysql -u $user_db -p$password_db -N -e "SELECT CONCAT(instance_id, ';', name) FROM centreon_storage.instances WHERE deleted='0';")
        pollers=$(echo $pollers | sed "s/ /,/g")
fi

echo $pollers | while read -d, poller || [[ -n $poller ]];
do
        pollerId=$(echo $poller | awk -F";" '{print $1}')
        pollerName=$(echo $poller | awk -F";" '{print $2}')
        echo "##### $pollerName - $pollerId #####"
        mysql -u $user_db -p$password_db -t -e "SELECT
                FROM_UNIXTIME(action_log_date) as date,
                '$pollerName' as poller,
                object_type,
                object_id,
                CONCAT (h.host_name, ' / ', s.service_description) as object_name,
                action_type,
                c.contact_alias
        FROM centreon_storage.log_action
                LEFT JOIN centreon.contact c ON centreon_storage.log_action.log_contact_id=c.contact_id
                LEFT JOIN centreon.host_service_relation hsr ON object_id=hsr.service_service_id
                LEFT JOIN centreon.host h ON hsr.host_host_id=h.host_id
                LEFT JOIN centreon.service s ON object_id=s.service_id
                LEFT JOIN centreon.ns_host_relation nshr ON h.host_id=nshr.host_host_id
                LEFT JOIN centreon.nagios_server ns ON nshr.nagios_server_id=ns.id
        WHERE
                object_type = 'service' AND
                action_log_date > (
                        SELECT last_restart
                        FROM centreon.nagios_server
                        WHERE id = '$pollerId')
                AND (
                (object_type = 'host' AND (object_id IN (SELECT host_id FROM centreon_storage.hosts WHERE instance_id = '$pollerId') OR object_id IN (SELECT host_host_id FROM centreon.ns_host_relation WHERE nagios_server_id = '$pollerId')))
                        OR
                (object_type = 'service' AND (object_id IN (SELECT service_id FROM centreon_storage.services s, centreon_storage.hosts h WHERE h.instance_id = '$pollerId' AND s.host_id = h.host_id)
                        OR
                object_id IN (SELECT service_service_id FROM centreon.ns_host_relation nhr, centreon.host_service_relation hsr WHERE nagios_server_id = '$pollerId' AND hsr.host_host_id = nhr.host_host_id))) )
        UNION
        SELECT
                FROM_UNIXTIME(action_log_date) as date,
                '$pollerName' as poller,
                object_type,
                object_id,
                object_name,
                action_type,
                c.contact_alias
        FROM centreon_storage.log_action
                LEFT JOIN centreon.contact c ON centreon_storage.log_action.log_contact_id=c.contact_id
                LEFT JOIN centreon.host h ON object_id=h.host_id
                LEFT JOIN centreon.ns_host_relation nshr ON h.host_id=nshr.host_host_id
                LEFT JOIN centreon.nagios_server ns ON nshr.nagios_server_id=ns.id

        WHERE
                object_type = 'host' AND
                action_log_date > (
                        SELECT last_restart
                        FROM centreon.nagios_server
                        WHERE id = '$pollerId')
                AND (
                (object_type = 'host' AND (object_id IN (SELECT host_id FROM centreon_storage.hosts WHERE instance_id = '$pollerId') OR object_id IN (SELECT host_host_id FROM centreon.ns_host_relation WHERE nagios_server_id = '$pollerId')))
                        OR
                (object_type = 'service' AND (object_id IN (SELECT service_id FROM centreon_storage.services s, centreon_storage.hosts h WHERE h.instance_id = '$pollerId' AND s.host_id = h.host_id)
                        OR
                object_id IN (SELECT service_service_id FROM centreon.ns_host_relation nhr, centreon.host_service_relation hsr WHERE nagios_server_id = '$pollerId' AND hsr.host_host_id = nhr.host_host_id))) );"

done

```

Kind regards

**Comment by omercier** [comment]
Hi @cmeschin, 
This has been added to our backlog (ref MON-11874).
It will presumably be released in 22.10.
Regards,
