### ISSUE TITLE
Blocage du débogage de la supervision

### ISSUE THREAD

**Issue by centreon** [centreon/centreon#995]
---

Author Name: **cedric meschin** (cedric meschin)
Original Redmine Issue: 6187, https://forge.centreon.com/issues/6187
Original Date: 2015-03-09

---

Bonjour,

il semble y avoir un problème dans l'analyse du débogage via l'interface qui bloque l'export de la configuration.
Le problème est lié au message d'erreur suivant:
[1425903583] [10432] Warning: Recovery notification option in service 'UPTIME' for host 'XXXX' doesn't make any sense - specify warning and/or critical options as well
Ce message d'erreur a été obtenu en lançant la vérification de configuration en ligne de commande.

La configuration du service au niveau des notifications est en PJ (il s'agit du modèle generic-notification et utilisé pour l'ensemble des services).
l'interface reste bloquée sur "Génération des fichiers...". après vérification, les fichiers sont correctement générés. c'est donc le débogage qui bloque (vérifiable en faisant la manipulation "pas à pas")
Ce qui est étonnant, c'est que l'export fonctionne sur certains satellites et pas sur d'autres alors que tous utilisent ce modèle.

Ma configuration:
CES 2.2
architecture distribuée avec 1 central et 17 pollers.
Centreon 2.5.4
Centreon-Broker 2.8.1
Centreon-engine 1.4.10

cordialement,

**Comment by julienmathis** [comment]
many changes since 2.7.x.
