### ISSUE TITLE
Mobile access (Android/iOS) - access denied

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#9982]
Centreon 20.10.9 (problem is also on some older version)

It is not possible to login from mobile. Seems that real time api is not accessible for non admin users.
Real time API is enabled for the user

**Comment by joschi99** [comment]
Done some test with realtime api which is accessible

**Comment by joschi99** [comment]
Found the problem. If you enable the "Reach API Configuration" the user can login and work with mobile app.

- Following the documentation https://docs.centreon.com/21.04/en/mobile/introduction.html#installer-lapplication this is missing
- Why the "Reach API Configuration"? Bug?

**Comment by cg-tw** [comment]
Hello,
Thanks for pointing this out. The documentation was not up to date. We have tested the scenario and updated the documentation accordingly.
Best regards
